### ISSUE TITLE
Time to think about what needs to be done for 1.0

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#1000]
Brainstorming time.

What would we really like accomplished before we publish version 1.0?

Remember that at 1.0, we start playing right with full Semver compatibility, which means, among other things, that we don't break backward compatibility except on major versions.  This probably means slower iteration time, and a slightly more contemplative approach to API changes.

Thanks to all the hard work of so many contributors, we've gotten quite a useful library built, and thanks to some hard work especially by @davidchambers, both the API and the implementation are relatively consistent.  But there's probably still work to do in both API and implementation.

Moreover there are several other places that need work.  There is infrastructure work to be done.  @buzzdecafe has just started switching over to using NPM instead of grunt for many build tasks.  I'd really like to get to the point where everything we need can be built through NPM.  And there are some other issues regarding the running of Sauce, reporting of our Benchmark tests, the possibility of more sophisticated custom builds.

Our documentation has improved remarkably fairly recently.  But I think there is still work to do.  It really should have a more responsive design so that it works well on mobile.  It would be nice to include source code links.  Although we're publishing multiple versions, there's no indication that the docs for older versions are online; we should have a link to them.  Dreaming a little further, it would be nice if a hover of an example offered you the ability to launch it in the REPL.

Speaking of the REPL, it's a very nice piece of work, but it could also use some love.  It would be great to skin it to look like any other of our pages, for one.  But there could be other improvements, like capturing `console.log` statements and displaying their output.  Perhaps we could hover help to Ramda functions used, with the content of the documentation serving as a guide.

So, while the most important issues will always be the core code itself, it's obvious that there are many other things that need to be done.

I'm not sure of the best way to start addressing these points.  Should we just leave open an issue like this?  Should be keep track of this on our little-used wiki?  Something else?

I'm not going to struggle too hard to make this happen, but if it's possible, I would love to see 1.0 come out in May or June.  Does that sound reasonable?

Are there people out there willing to help with some of these tasks?  I don't think Michael, David, and I could possibly do all this in two months.

**Comment by buzzdecafe** [comment]
my $0.02:

# Must:

- [ ] compile a list of functions that should be transducer-comaptible
- [ ] make the list transducer-compatibile
- [ ] decide where exactly we stand on variadic functions in the lib
- [ ] decide on returning a curried function from `curry` and `compose`
- [ ] consider curried, binary `compose` along with another compose function that takes a list

# Would be nice:

- [ ] docs category dropdown
- [ ] links to prior version docs
- [ ] REPL in same template
- [ ] more REPL examples

# Maybe someday

- [ ] Ramda cookbook
- [ ] Debug build


what else ....

**Comment by CrossEye** [comment]
## Must ##

  - [ ] curate the remainder of our issues/pr lists
  - [ ] figure out our stand on the depth of internal dependencies we're willing to accept 

## Would be nice ##

  - [ ] build everything through NPM
  - [ ] responsive design for docs
  - [ ] links to source code in docs

## Maybe someday ##

  - [ ] docs examples link to REPL
  - [ ] better REPL output

**Comment by bobiblazeski** [comment]
Two more nice to haves:
Some official mechanism for extending Ramda. 
Official meteor support currently package by @kevohagan is used https://github.com/kevohagan/meteor-ramda/

**Comment by davidchambers** [comment]
It's cool that this is the 1000th issue!

**Comment by CrossEye** [comment]
> It's cool that this is the 1000th issue!

I'd been thinking about it for a while, and was going to discuss it first in Gitter, but when I saw that we were at issue 999, I had to write it up and hope no one beat me to that nice round number!  So it was intentional.  (And yes, I'm a geek!)

**Comment by scott-christopher** [comment]
> Some official mechanism for extending Ramda.

It might be worthwhile looking at introducing something like a `ramda-contrib` org in Github where suggestions or things that would make useful extensions, but aren't quite core to Ramda, still have a central place to live. If it's only likely to house a few extra repos though, it may not be worthwhile.

**Comment by paldepind** [comment]
@bobiblazeski:

> Some official mechanism for extending Ramda. 

What do you have in mind? I don't understand it. Wouldn't just defining a new function dependent on Ramda be an "extension"? The way I see it that's one of the neat things with functional programming: you don't have to attach functions to prototypes, inherit from classes, define mixins, etc. as would to extend a OO library.

**Comment by bobiblazeski** [comment]
@paldepind  where would you put functions that are used all over your projects but aren't general enough to go into core ramda? And what if you want to use ramda internals for efficiency or something?

**Comment by paldepind** [comment]
> where would you put functions that are used all over your projects but aren't general enough to go into core ramda?

In a module for utility functions – the same place where I keep all the other functiosn that are used all over my project but aren't part of any third party library.

> And what if you want to use ramda internals for efficiency or something?

Then I would argue that Ramda has failed in delivering what it should. It should give you all the essential building blocks with adequate performance.

I think exposing internal functions in any way is a path to disaster. I library can and should only make promises with regards to its external API.

**Comment by bobiblazeski** [comment]
@paldepind Note the plural, projects in my question. I have certain functions that I repeatedly use in many projects that extend Ramda functionality. I could either create separate project but it would be nicer to be able to somehow extend Ramda.They're like jquery plugins.

Ramda is general purpose utility expecting to deliver performance or certain behavior in some niche use cases is not something that could be expected.
I wasn't proposing to expose the internals, but being be able to hook into the build process would  be nice feature to experiment and add custom functionality. 
Note that all those things are nice to haves, maybe even better to be considered after 1.0 when API is more stable.

**Comment by paldepind** [comment]
> Note the plural, projects in my question.

I missed that, sorry.

> I have certain functions that I repeatedly use in many projects that extend Ramda functionality. I could either create separate project but it would be nicer to be able to somehow extend Ramda.They're like jquery plugins.

How would you avoid having a separate project? They'd have to be part of something other than Ramda. ramda-contrib, my-awesome-ramda-functions, etc.

As far as I know jQuery plugins do not have access to any internal jQuery functions. They are just functions added to the jQuery objects prototype.

> Ramda is general purpose utility expecting to deliver performance or certain behavior in some niche use cases is not something that could be expected.

No, indeed not. But it should provide general functions that could be combined for your specific use case. If extension (whatever that means) writers find they need some internal function then other Ramda users will need it as well.

> I wasn't proposing to expose the internals

It sounds like that to me when you ask "_And what if you want to use ramda internals_".

This still doesn't make much sense to me. Could you maybe give an example of what you would like to be able to do?

**Comment by bobiblazeski** [comment]
I want to be able to experiment easier with adding custom functions, that might use internals in the build process and are bundled with Ramda code.
