### ISSUE TITLE
Documenting and softening API changes

### ISSUE THREAD

**Issue by bbarr** [ramda/ramda#1001]
It would be tremendously helpful if, when the API breaks (ex. mixin -> merge, lPartial -> partial), we set up aliases with console.warn'ings to update code. This way people can ease into a new version and not be scared of updating.

**Comment by CrossEye** [comment]
Please see the discussion around #786.

Our current technique involves adding a deprecation flag to the documentation for a version before removing or renaming a function.  We are hoping to hit [v1.0.0][v1] soon, at which point, we'll become much more conservative about breaking API changes anyway.

  [v1]: https://github.com/ramda/ramda/issues/1000
