### ISSUE TITLE
Add dedupe/dropRepeats function

### ISSUE THREAD

**Issue by paldepind** [ramda/ramda#1005]
I think Ramda needs a function that drops consecutive repeated values from an array.

```javascript
R.dropRepeats([1, 1, 2, 3, 4, 4, 4, 3, 1]); //=> [1, 2, 3, 4, 3, 1]
```

This is not `uniq`. This function only removes _consecutive_ repeated values. This function can be implemented more efficiently and is useful for reducing a dataset only to its changes. For instance, if you have an array with some value sampled every second and you want to reduce the dataset to only the points at which the sampled value actually changed.

Furthermore this function can be implemented as a transducer (transducers.js actually includes a function like this).

My own use case for a function like this is to achieve something similar to Elms [dropRepeats](http://package.elm-lang.org/packages/elm-lang/core/1.1.1/Signal#dropRepeats) using [Flyd](https://github.com/paldepind/flyd)s transducer support.

If there is support for this I'll be happy to create a pull request with the suggested function.

**Comment by davidchambers** [comment]
This function sounds useful to me!

**Comment by CrossEye** [comment]
:herb:
