### ISSUE TITLE
Build pipeline suggestions.

### ISSUE THREAD

**Issue by scott-christopher** [ramda/ramda#1011]
There are a few tweaks that I would like to propose with the current build process and would love to get some feedback before I embark on anything further.

What I suggest:
- **Remove Grunt and the Makefile in favour of NPM scripts.**
  - There is currently quite a bit of duplication across all three that could be reduced down to a single source of truth.
  - Anything that requires more than a simple one-liner can be added as a shell or JS script in the `scripts` folder.
- **Use browserify for generating `dist/ramda.js`.**
  - I'm not aware of the history behind the `scripts/build` script and as such, unaware of anything additional that it is doing beyond resolving modules. If its only purpose is to resolve module dependencies, that logic could be taken care of by something such as the following shell script, which will build out a common-js and browser friendly `ramda.js`:
```sh
( cd src;
  find . -name '*.js' -not -path './internal/*' \
  | sed 's:\\./\\(.*\\)[.]js:exports.\\1 = require(\"./\\1\");:' \
  | browserify - -s R \
  > ../dist/ramda.js )
```
- **Customise the NPM publish step by copying all the contents of `src` and `package.json` into `dist`, alongside a freshly built `ramda.js` and `ramda.min.js`, then running `npm publish dist`.**
  - The tagging of a release should probably continue in its current form (i.e. with only `ramda.js` and `ramda.min.js` in dist) to prevent duplicated code in both `src` and `dist`.
  - This would require either updating `x.y.z` to support passing a path to `npm publish`, or creating a bespoke script to capture the version bump and release process.
  - This change would allow for use in a common-js environment such as:
```js
// load an individual function
var add = require('ramda/add');
// or alternatively load everything
var R = require('ramda');
```
- **Update the tests to require the individual function modules being tested, rather than requiring a built `R` module.**
  - Makes it simpler/quicker to run the tests in isolation if a build isn't required after every change.
  - Watching files for quicker test feedback becomes straight forward.

I appreciate these requests can be potentially controversial, so I am happy to accept a "Go home, there is no reason to change this" response, though I just wanted to raise them as issues I have noticed since contributing a little recently. And to be honest, the main motivator behind this for me is to try to get nicer common-js module support in before a v1.0 release.

**Comment by buzzdecafe** [comment]
> Remove Grunt and the Makefile in favour of NPM scripts.

:+1: i have already started doing this in buzzdecafe/ramda "degrunt" branch. Any help gratefully accepted :smile:

Most of the publish steps are handled by xyz, which has been fine for the job, IMO.

> Update the tests to require the individual function modules being tested, rather than requiring a built R module.

I like this idea.

**Comment by CrossEye** [comment]
> Remove Grunt and the Makefile in favour of NPM scripts.

This is already underway.   @buzzdecafe has a branch that eliminates at least most of the need for `Grunt`.  I'd like to see `make` go next. 

> Use browserify for generating dist/ramda.js.

On this one I disagree.   I still see that file as our main export.   I would like it to be as clean and readable as possible.   The cruft from browserify simply dies not have a place. 

> Customise the NPM publish step by copying all the contents of `src` and `package.json` into `dist`, alongside a freshly built `ramda.js` and `ramda.min.js`, then running `npm publish dist`.

This has definitely been discussed, but I don't think anyone is working on it yet.   I would love to see it. 


> Update the tests to require the individual function modules being tested, rather than requiring a built `R` module.

This one is harder.  I really want _both_ but I can't see any easy way to achieve that. ..

**Comment by scott-christopher** [comment]
> i have already started doing this in buzzdecafe/ramda "degrunt" branch. Any help gratefully accepted

More than happy to help :) Is there anything captured that identifies the remaining tasks, or just how best I can help out?

> Most of the publish steps are handled by xyz, which has been fine for the job, IMO.

Sure. The suggested change is more about *what* gets published to NPM rather than *how* it happens. An alternative would be to leave xyz as is and copy all source files to the root dir before running `npm publish`. This could be managed with a few entries in `.npmignore` to prevent publishing duplicate files.

>  The cruft from browserify simply does not have a place.

Fair point and I do agree.

> This one is harder. I really want both but I can't see any easy way to achieve that.

Having just soldiered through updating the first half of all the test files, I have discovered tests such as `test/invariants.js` which depend on `R` to test all functions. Not sure whether I should continue and leave those as post-build tests, or abort now – advice welcome :)

**Comment by davidchambers** [comment]
@scott-christopher, what is your plan for tests which use other Ramda functions for convenience? (#1007, for example, uses `R.eqProps('i')`.) Is it to replace these with vanilla functions? This plan seems reasonable; I'm just curious.

**Comment by buzzdecafe** [comment]
> Is there anything captured that identifies the remaining tasks, or just how best I can help out?

the important stuff is done, although can be improved: hint, jscs, browserify, test. what remains is saucelabs, benchmark, orchestrate, and all of the docs-related stuff. The docs stuff is a big job, and might be best just moving to ramda.github.io repo.

**Comment by scott-christopher** [comment]
@davidchambers: I was just requiring the individual functions directly, so for the `adjust` test which references `add` it looks like:
```js
var add = require('../src/add');
var adjust = require('../src/adjust');
```

**Comment by CrossEye** [comment]
> Having just soldiered through updating the first half of all the test files, I have discovered tests such as `test/invariants.js` which depend on `R` to test all functions. Not sure whether I should continue and leave those as post-build tests, or abort now – advice welcome :)

I'm having a hard time offering suggestions, or even endorsing the approach, as I agree that testing the way you're suggesting is useful, but I also want to test the functions as namespaced on the Ramda `R` object.  Perhaps it's because I still do a lot of browser development or because that was how I started creating it, but I still think of `ramda.js` as our flagship export.  I really would like to know that our tests are capturing it running that way.  I can't see a simple way to do both.  But I would really like one.

**Comment by kedashoe** [comment]
How about something like..

in package.json, you have a "onlytest" key in scripts

"scripts":{
...
"onlytest":"node scripts/onlytest.js"
}

onlytest.js grabs the environment and adds "RAMDA_ONLYTEST=1", then runs mocha with this environment on the test file passed in from the command line, eg

`npm run onlytest test/adjust.js`

then in `test/adjust.js`, instead of `var R = require('..');` at the top of every file, you have something like

    if (process.env.RAMDA_ONLYTEST) {
        var R = {
            add:require('../src/add'),
            adjust:require('../src/adjust')
            // etc etc for other stuff needed for this test
        };
    }
    else {
         var R = require('..');
    }

shouldn't have to update any of the rest of the test code since they currently use the R namespace. Using something like `onlytest.js` in order to support windows complicates things vs make, but I reckon shouldn't be too bad?

**Comment by CrossEye** [comment]
@kedashoe:

One of the ways the tests run, one that we don't spend much effort on these days, I'm afraid, but might still be useful, is in the browser, through `test/index.html` (you need to run `browserify` first.)  I'm afraid this suggestion would cause problems with that.

**Comment by buzzdecafe** [comment]
when we (let's face it: *I*) re-integrate saucelabs, we'll have to have some way to run the tests in a browser. how they are assembled is immaterial for that.

**Comment by scott-christopher** [comment]
If we're wanting the flexibility of testing both, we'd probably need to replace the `require` calls with a something like a call to `requireR`, which could be operate differently depending on the environment/configuration.

e.g. something like:
```js
function requireR(module) {
  if (process && process.env.RUN_UNIT) {
    return require('./src/' + module);
  } else {
    return R[module];
  }
}
```

Then in the test:
```js
var add = requireR('add');
var adjust = requireR('adjust');
// ...
```

**Comment by CrossEye** [comment]
@scott-christopher This looks like a very useful way to proceed.

Except... how do we include `requireR` everywhere?

**Comment by scott-christopher** [comment]
@CrossEye: I've got a working example of the proposed test changes here: https://github.com/scott-christopher/ramda/commit/29c8f43c098bcc90353b8fdd665f3ef8c87f7c99

This uses `test/helpers/requireR.js` to differentiate whether to run the test suite by requiring the individual `src` files, or using `dist/ramda.js` if a `TEST_DIST` env var is set to something that evaluates truthy.

The other change included on that branch, which may or may not be considered desirable, is moving all the tests that are focused on individual functions/modules into `test/unit` and anything testing `ramda.js` as a whole (currently only `invariants.js`) into `test/integration`.

These tests can be run via:
```sh
# just unit
node_modules/.bin/mocha test/unit
# just integration
node_modules/.bin/mocha test/integration
# both unit and integration
node_modules/.bin/mocha test/unit test/integration
# testing with dist/ramda.js
TEST_DIST=1 node_modules/.bin/mocha test/unit test/integration
# run tests when src changes
node_modules/.bin/mocha -w src -R min test/unit test/integration
```

**Comment by wayneseymour** [comment]
+1 for npm scripts

**Comment by buzzdecafe** [comment]
this is underway, see #1057 will continue post-0.14

**Comment by buzzdecafe** [comment]
this is mostly done; let's track further progress in separate issues
