### ISSUE TITLE
dispatch in R.and and R.or

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1015]
Sanctuary's [`or`][1] function is simple, intuitive, and useful. Example usage:

```javascript
S.or(S.Nothing(), S.Nothing());  // => S.Nothing()
S.or(S.Nothing(), S.Just('bar'));  // => S.Just('bar')
S.or(S.Just('foo'), S.Nothing());  // => S.Just('foo')
S.or(S.Just('foo'), S.Just('bar'));  // => S.Just('foo')
```

Now that Ramda's [`or`][2] function operates on values rather than functions we could consider dispatching to an `or` method if present. We could also dispatch to an `and` method in `R.and`.

[1]: https://github.com/plaid/sanctuary/blob/v0.4.0/index.js#L210-L221
[2]: http://ramdajs.com/docs/#or

**Comment by CrossEye** [comment]
I think this mostly makes sense.

But you know, the day someone say that it's broken, and it turns out that some moron did this elsewhere in their app we have to decide what degree of derision to apply:

    Boolean.prototype.or = function(that) {
        return this.valueOf() && that;
    };

    R.or(1 === 2, 3 === 4); //=> true;  WTF?  Gotta be Ramda's fault! 

:smile:
