### ISSUE TITLE
use R.toString in REPL

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1040]
The output of [`R.fromPairs([['x', 1], ['y', 2]])`][1] is currently `[object Object]`. We should apply [`R.toString`][2] to the result of evaluating the last expression, giving `{"x": 1, "y": 2}` in this case.

[1]: http://ramdajs.com/repl/?v=0.13.0#R.fromPairs(%5B%5B'x'%2C%201%5D%2C%20%5B'y'%2C%202%5D%5D)
[2]: https://github.com/ramda/ramda/pull/924

**Comment by buzzdecafe** [comment]
:cow2:

i assume this will give better array output as well? at present, repl output for `[1,2,3]` and `"1,2,3"` are indistinguishable

**Comment by davidchambers** [comment]
> i assume this will give better array output as well?

Indubitably:

```javascript
> R.toString([1, 2, 3])
'[1, 2, 3]'
> R.toString(['1', '2', '3'])
'["1", "2", "3"]'
```

**Comment by buzzdecafe** [comment]
this should probably be an issue on ramda.github.io

**Comment by CrossEye** [comment]
:herb:

**Comment by davidchambers** [comment]
Do you know where to look for the code we'd need to modify, @buzzdecafe?

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda.github.io/tree/master/repl/assets/js

repl.js?

**Comment by CrossEye** [comment]
https://github.com/ramda/ramda.github.io/blob/master/repl/assets/js/repl.js#L123

Although... does someone have an explanation for what the `'global'` string does here?:

```js
evalElement.textContent = ('global', eval)(source);
```

ISTM that the comma operator will simply return `eval`, which will then be applied to `source`.

**Comment by davidchambers** [comment]
Thanks for locating the file, @buzzdecafe, and for locating the precise line, @CrossEye.

[(1,eval)('this') vs eval('this') in JavaScript?][1] explains the reason for `('global', eval)` rather than `eval`: it affects the context in which `source` is evaluated.


[1]: http://stackoverflow.com/q/9107240/312785

**Comment by CrossEye** [comment]
Thanks for that pointer @davidchambers.  Although I certainly know about reference versus direct call to `eval`, and have maintained a reference to `eval` in order to avoid the local pollution, I never realized you could do it this easily!  That's so much cleaner than the technique I've used!
