### ISSUE TITLE
_.throttle

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1041]
I'm pretty new to the functional programming game, but I'm eager to get better at it.

One question I have for you guys, if where does [`_.throttle`](https://lodash.com/docs#throttle) fit in to Ramda?

**Comment by bergus** [comment]
It doesn't really. Ramda is about <s>manipulating</s> transforming data and composing functions. And mostly,

> Ramda emphasizes a purer functional style. Immutability and side-effect free functions are at the heart of its design philosophy <sub>(http://ramdajs.com/#what-s-different-)</sub>

`throttle` and `debounce` are very much about side effects. If you look for such functionality in a pure way, you should have a look at FRP libraries that would abstract over this with event streams that can be manipulated.

**Comment by buzzdecafe** [comment]
i agree with @bergus . `throttle` is not referentially transparent, because you may get different results for identical calls.

**Comment by megawac** [comment]
yeah, if you need throttle/debounce I highly recommend using https://www.npmjs.com/package/lodash.debounce & https://www.npmjs.com/package/lodash.throttle which are highly tested

**Comment by ccorcos** [comment]
I see. RxJS is probably the right way to go for FRP. Or would you recommend Highlandjs or something else?

**Comment by ccorcos** [comment]
I really like functional programming, when it comes to programming user interfaces, it tends to get a little hairy, especially when you want to do animations, etc...

**Comment by CrossEye** [comment]
> I see. RxJS is probably the right way to go for FRP. Or would you recommend Highlandjs or something else?

I've not yet spent enough time with any of them to offer a suggestion.  But as well as RxJS, I know that Bacon is well-respected.  I've never really thought of Highland as operating in the same space, although there is clearly some overlap.  But there is an interesting new offering from a Ramda contributor: https://github.com/paldepind/flyd.  This is a much smaller, more focused library than RxJS or Bacon.  But again, I don't have enough experience to really offer a suggestion.

**Comment by ccorcos** [comment]
floyd looks awesome actually. A little immature though. RxJS has so many nice operators...

**Comment by CrossEye** [comment]
Flyd is definitely immature.  But it's also, I'm pretty sure, intentionally minimal.  It looks like it was written in part as a reaction to the oversized APIs of the others. Ah well, _De gustibus non est disputandum_.
