### ISSUE TITLE
R.pickPath && R.createNestedMapEntry

### ISSUE THREAD

**Issue by boxxxie** [ramda/ramda#1046]
i recently discovered that ramda is missing some nested data structure functions

I find R.createMapEntry very useful, and I wanted to do this in a path style (i give a path, i get a partial object fn back)

```javascript
var path = [ 'worker', 'publicKey' ];

var createNestedMapEntry = r.compose(
  r.apply(r.compose),
  r.map(r.createMapEntry)
);

createNestedMapEntry(path)('asdfa'); // { worker: { publicKey: 'asdfa' } }
```

so, that is pretty simple, but not very intuitive (my first attempts were with reduce).

so, now that i have that i can combine it with some sort of other funkyness and merge R.pick with R.path.

```javascript
var pickPath = r.curry(function(paths, obj){
  return r.compose(
  r.mergeAll,
  r.map(function(mapEntry){
    var path = mapEntry[0];
    var val = mapEntry[1];
    return createNestedMapEntry(path)(val);
  }),
  r.map(function(path){
    return [path, R.path(path, obj)];
  }))
  (paths);
});

var paths = [['worker', 'publicKey']];
var extractFrom = {
  mongo: {
    host: 'localhost',
    port: 3001
  },
  redis: {
    host: 'localhost',
    port: 6379
  },
  worker: {
    publicKey: 'adsfasdfadsf',
    secretKey: 'bbbbbbbbbbbbbbbbbbbbb'
  }
};
pickPath(paths, extractFrom);  // { worker: { publicKey: 'adsfasdfadsf' } }
```

is there any interest in these?

**Comment by buzzdecafe** [comment]
how is `createNestedMapEntry` better than/different from `assocPath`? http://ramdajs.com/docs/#assocPath

**Comment by boxxxie** [comment]
i tried assocPath and it didn't make new paths.
maybe i used it wrong? i'll try again and edit this comment with results.

**Comment by buzzdecafe** [comment]
try this: http://bit.ly/1bm2Xoh

**Comment by boxxxie** [comment]
they do have different APIs, however it would probably be better to implement the nestedMapEntry with assocPath.

**Comment by CrossEye** [comment]
`pickPaths` is an interesting concept.  I don't know that it is generally useful enough for Ramda itself.

One API decision that bothers me is the multiple paths.  There also seems to be an implementation bug: try it with both of these paths: `[['worker', 'publicKey'], ['worker', 'secretKey']]`, but I'm sure that could be resolved.

I'd like to hear more, especially about why the need for multiple paths in a single return.

**Comment by boxxxie** [comment]
well, `pick` returns multiple paths in a single return, and `path` returns one. so this is an attempt to merge the 2 concepts. in the current project i'm on i've found it very useful to declarativly express how i want to transform an object/tree. this is one of the simpler transformations that i have found useful.

I think the bug is due to mergeAll's behaviour. this is a minor issue i can fix, most likely by taking advantave of assocPath and avoiding a merge.

maybe i should send this to fantasyland (is that still maintained)?

**Comment by CrossEye** [comment]
I can see the point, but I'm not sure enough about the general need for something like this.  I'm hoping others will chime in with their viewpoints.

As to implementation, you could do it with `assocPath` like this:

    var pickPath = R.curry(function(paths, obj){
      return R.compose(
        R.reduce(function(acc, keyVal) {
          return R.assocPath(keyVal[0], keyVal[1], acc)
        }, {}),
        R.map(function(path){
          return [path, R.path(path, obj)];
        })
      )(paths);
    });

And if you wanted to get a little more concise you could do this:

    var pickPath = R.curry(function(paths, obj){
      return R.compose(
        R.reduce(R.useWith(R.flip(R.call), R.identity, R.apply(R.assocPath)), {}),
        R.map(function(path){
          return [path, R.path(path, obj)];
        })
      )(paths);
    });

or maybe even 

    var pickPath = R.curry(function(paths, obj){
      return R.compose(
        R.reduce(R.useWith(R.flip(R.call), R.identity, R.apply(R.assocPath)), {}),
        R.map(R.converge(R.unapply(R.identity), R.identity, R.path(R.__, obj)))
      )(paths);
    });

although perhaps that's going overboard!  :-)  Trying to get it entirely points-free sounds, well, pointless!

> maybe i should send this to fantasyland (is that still maintained)?

It is, but I think you have the wrong idea about it.  FantasyLand maintains a specification for Algebraic Data Types.  It has nothing to do with utility functions.

**Comment by davidchambers** [comment]
`pickPath` seems too specialized to include in Ramda.

**Comment by piekarskid** [comment]
@CrossEye 
```
var pickPath = R.curry(function(paths, obj){
  return R.compose(
    R.reduce(R.useWith(R.flip(R.call), R.identity, R.apply(R.assocPath)), {}),
    R.map(R.converge(R.unapply(R.identity), R.identity, R.path(R.__, obj)))
  )(paths);
});
```
doesn't works, probably because of changes in API. I've made adjustments, refreshing it if anybody would look for similar solution

```
const pickPaths = curry((paths, obj) => compose(
	reduce(useWith(flip(call), [
		identity, 
		apply(assocPath),
	]), {}),
	tap(console.log),
	map(converge(unapply(identity), [
		identity, 
		path(__, obj),
	])),
)(paths))
```

**Comment by CrossEye** [comment]
@piekarskid: Sure, but these days, I personally wouldn't even *try* to make something like this point-free.  I find this much cleaner:

```js
const pickPath = (paths, obj) => 
  reduce ((o, p) => assocPath(p, path(p, obj), o), {}, paths)
```

**Comment by piekarskid** [comment]
@CrossEye 
Yep, looks cleaner. Thanks, I’ll update my code.
