### ISSUE TITLE
Question: FunctionalJS w/o OO?

### ISSUE THREAD

**Issue by wayneseymour** [ramda/ramda#1049]
Not a knock on anyone or any code, because _I'm a functional programming wannabe_.

However, I've been wondering if anyone knows of a functional JS lib that does not use `new` and also does not use `this` in the implementation.

What I really want to know is that even possible.

My apologies for this being orthogonal to `λamda`.

**Comment by TheLudd** [comment]
Does ramda use `new`/`this`?

**Comment by buzzdecafe** [comment]
there's a couple of places we might call a function in the context of `this`, but i'm not aware of any `new`

**Comment by CrossEye** [comment]
All the Transducer implementation (`_xall`, `_xany`, etc.) use `new`.

And I believe for the most part, where we are in the business of specifically creating functions (and not merely currying them), we pass `this` through.  That's not essential for FP, of course, but allows users to use Ramda-created functions as object methods if they desire.

**Comment by CrossEye** [comment]
@wayneseymour Yes it's certainly possibly.  And Ramda could avoid doing so if we were motivated to.  But we make a major distinction between our public API and our internal implementation.  We are trying to create a functional API.  But for various exigent reasons, our internal implementation is mostly imperative, and our Tranducers code actually has an OO implementation.  The use of `this` is only to allow users to more easily combine Ramda functions in their OO projects; it's far from essential, but is perhaps nice to do.

Would there be a particular practical goal to avoiding `new` and `this`, or it mostly of academic interest?

**Comment by paldepind** [comment]
> What I really want to know is that even possible.

It certainly is. `new` is merely sugar for the invocation of a constructor function and setting up the prototype based on the constructor functions `prototype` property. If you don't use prototypal inheritance any use of `new` can easily be converted to a direct invocation of the constructor function. And any method invocation can easily be converted to a plain function that takes the object as a normal parameter.

It's not even just possible it's pretty practical as well.

> All the Transducer implementation (_xall, _xany, etc.) use new.

And they would be pretty easy to get rid of.

> Would there be a particular practical goal to avoiding new and this, or it mostly of academic interest?

I highly doubt that! But if one can get over it ugliness I think it is in some cases the easiest way to use prototypal inheritance.

**Comment by wayneseymour** [comment]
Wow, thank you all for the responses.

@CrossEye I cannot attend to this being academic as I've humbly come FP from Java. 
As of late, I'm a full time JS engineer.  My initial reaction to FP was the recognition of a breath of fresh air.  Better yet, a breath of freedom from creating `enterprise` _boring_ applications.
The practical goal is to simplify mental state.  There have been times in the past where I really felt my brain would come undone due to having to juggle so much state in large OO applications.

**Comment by wayneseymour** [comment]
So far, I've attempted to solve problems with Underscore, Lodash, and now Highland is in heavy use at the office.  

I'm wondering if highland is abstracting too much from me.  But alas, that is probably a question for another blog/post/issue.  

Thanks gentlemen.
