### ISSUE TITLE
`R.converge` does not pass `this` context to its arguments

### ISSUE THREAD

**Issue by anton-rudeshko** [ramda/ramda#1059]
I hope this is not intended behavior.

https://github.com/ramda/ramda/blob/master/src/converge.js#L38-L40

There should be `_map(function () { ... }.bind(this), fns)`.

**Comment by buzzdecafe** [comment]
i se it. trying to imagine the test to capture this regression

**Comment by anton-rudeshko** [comment]
Yeah, kind of spooky case. I use `this` to inject service dependencies in highly composed functions.

**Comment by anton-rudeshko** [comment]
For example:
```js
var getIssue = function(issueNo) {
  return this.github.getIssue(issueNo);
};
```

BTW, is there any function in R to access `this`?

**Comment by buzzdecafe** [comment]
> BTW, is there any function in R to access this?

hmmm, like `() => return this;`?

**Comment by anton-rudeshko** [comment]
Yes, maybe something like `R.propThis('propToGetFromThis')` =)

**Comment by buzzdecafe** [comment]
can you flesh out a test case to satisfy? That would make it easier to fix.

**Comment by anton-rudeshko** [comment]
It might look like this:
```js
var a = function(x) { return this.first(x); };
var b = function(x) { return this.second(x); };
var c = R.converge(R.add, a, b);

var context = { first: R.add(1), second: R.add(2) };

assert.equal(a.call(context, 1), 2);
assert.equal(b.call(context, 1), 3);
assert.equal(c.call(context, 1), 5); // TypeError: this.first is not a function
```

Not the best test case I ever wrote, but whatever.

**Comment by anton-rudeshko** [comment]
BTW, there probably should be a function to write `function(x) { return this.f1(x); }` in pointfree style.

**Comment by buzzdecafe** [comment]
seems like there are now two topics here. you may want to make a separate issue/PR for this one: `function(f1) { return function(x) { return this.f1(x); }; };`

as to the first one, here is the current impl:

```js
module.exports = curryN(3, function(after) {
  var fns = _slice(arguments, 1);
  return curryN(max(pluck('length', fns)), function() {
    var args = arguments;
    return after.apply(this, _map(function(fn) {
      return fn.apply(this, args);
    }, fns));
  });
});
```

I take it something like this would solve your problem:

```js
module.exports = curryN(3, function(after) {
  var fns = _slice(arguments, 1);
  return curryN(max(pluck('length', fns)), function() {
    var args = arguments;
    var ctx = this;
    return after.apply(ctx, _map(function(fn) {
      return fn.apply(ctx, args);
    }, fns));
  });
});
```

yes? i'm just wondering about the effects of that. I find it difficult to reason about the binding of `this` in js

**Comment by jdalton** [comment]
Is `this` arg implied for other transformative functions? I don't see it done for `useWith`.

**Comment by CrossEye** [comment]
We usually do add it where it's pointed out.   I think none of the core committers tend to use it so it's hard to remember, sometimes.   But I think that so long as it's not doing us harm, it's worth adding where we can.
