### ISSUE TITLE
It's time for v0.14.0?

### ISSUE THREAD

**Issue by anton-rudeshko** [ramda/ramda#1060]
> ## v0.13.0
> davidchambers tagged this on Mar 23
> **71 commits to master since this tag**

There is a lot of changes...

**Comment by buzzdecafe** [comment]
:+1:  it's past :clock1:

**Comment by anton-rudeshko** [comment]
Please, include fix for #1059 =)

**Comment by buzzdecafe** [comment]
done and done

**Comment by anton-rudeshko** [comment]
Cool :+1:

**Comment by lwassermann** [comment]
In the future, for those of us who use Ramda and have a CI, it would be helpful if you had the release notes with what changed available when publishing the new version.

We like watching how the library evolves and all the changes do make sense and we appreciate them, only it is easier to fix our project if we know what did change.

**Comment by davidchambers** [comment]
Our approach to release notes is unconventional: we publish [upgrade guides][1] as GitHub issues. This allows anyone to comment on release notes, and I appreciate being able to link to the appropriate upgrade guide when opening a pull request to upgrade the Ramda dependency in another project.


[1]: https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22

**Comment by buzzdecafe** [comment]
@davidchambers in this case we published a day before the changelog was updated. so it's a fair point.
