### ISSUE TITLE
Wrapper for `new`

### ISSUE THREAD

**Issue by jon49** [ramda/ramda#1065]
Sometimes when I'm doing point free programming I run into the problem of using functions that need the `new` constructor. Would it be possible to have a wrapper for it?

E.g.,

```js
R.compose(nullOrXml, R.new(Date))
```

**Comment by davidchambers** [comment]
See [`R.construct`][1] and [`R.constructN`][2]. :)


[1]: http://ramdajs.com/docs/#construct
[2]: http://ramdajs.com/docs/#constructN

**Comment by jon49** [comment]
I missed it! Thanks!
