### ISSUE TITLE
Transposing an array, similar to partition or unzip

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1068]
I have an array like this `[[0, 'chet'], [2, 'charlie'], [10, 'joe']]` and I want to transpose the array.

The result looks like this `[R.map(R.nth(0))(array), R.map(R.nth(1))(array)]` but obviously, I'd like a point free way of doing this. I'm not sure what the most general form of this would be either.

**Comment by CrossEye** [comment]
So, something like this?:

```js
var transpose = function(a) {
    return R.mapIndexed(function(col, i) { 
        return R.map(R.nth(i), a)
    }, R.head(a));
};

transpose([[0, 'chet'], [2, 'charlie'], [10, 'joe']]); //=> [[0,2,10],["chet","charlie","joe"]]
```

There are three different versions at http://bit.ly/1P17BKx; none manages to get quite points-free.

**Comment by ccorcos** [comment]
Ah, yes. Well I guess the problem I'm having is when there are multiple arguments to different functions within the map... I tried doing this with `nthArg`, but the problem is we're mapping over two values. I'm realizing the same thing on a similar problem where I want to go from `[[0, 'chet'], [2, 'charlie'], [10, 'joe']]` to `[{id:0, username:'chet'}, ...]`. Ideally, something like `R.map(R.zipObj)` should work, but the problem is that whatever you pass will be mapped immediately. I also tried `R.compose(R.map, R.zipObj)` which doesnt work either...

**Comment by ccorcos** [comment]
This is what I settled with for the second example:
```
zip = R.curry (keys, values) ->
    R.map(R.zipObj(keys))(R.apply(R.zip, values))
```

**Comment by CrossEye** [comment]
Oh, we have two functions that help with things like this, `converge` and `useWith`.  Here `useWith` [will help][re]:

    var zip = R.useWith(R.map, R.zipObj, R.identity);

  [re]: http://bit.ly/1Qo7N42

**Comment by ccorcos** [comment]
Whoa. Thats exactly what I wanted! Its pretty hard getting used to thinking like that, but I like it!
