### ISSUE TITLE
2000 stars

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1070]
:tada:

Are you going to give away more Ramda schwag, @buzzdecafe?

**Comment by donnut** [comment]
:birthday:

**Comment by CrossEye** [comment]
:balloon: :tulip: :balloon:

**Comment by CrossEye** [comment]
So, we need to organize a giveaway whenever we pass a 1000 * (2 ^ n) marker?  Sounds good to me.

**Comment by bergus** [comment]
C'mon, can't you wait for a proper power of 2? 2<sup>11</sup> is only 44 stars away :-)

**Comment by buzzdecafe** [comment]
> C'mon, can't you wait for a proper power of 2? 211 is only 44 stars away :-)

sounds good to me

**Comment by CrossEye** [comment]
But we did our first at 1000.  Perhaps we were just jumping the gun.  I'm sure by the time the swag arrived, we'd already passed 2^10.  :smiling_imp:

**Comment by buzzdecafe** [comment]
""A foolish consistency is the hobgoblin of little minds ..."

nothing personal, of course

**Comment by CrossEye** [comment]
ok, I'm convinced.  (10) ^ 3, then (2) ^ 11.  Next one should logically be at (-6) ^ 19.  When we get below -609 trillion stars, somebody start paying attention.  :smile:

<small>"Waldo, the question is what are you doing out there?"</small>

**Comment by wayneseymour** [comment]
+1 @davidchambers 
I like `μ.swag`

**Comment by wayneseymour** [comment]
[μ sticker](http://www.zazzle.com/ramda_stickers-217012658836728564)

**Comment by buzzdecafe** [comment]
base^exp -> (exp-1)^(base+1)

so:

10^3 -> 2^11 -> 10^3 -> 2^11 -> etc

**Comment by megawac** [comment]
Jesus - how does [that sticker have so many reviews](http://www.zazzle.com/ramda_stickers-217012658836728564)

**Comment by buzzdecafe** [comment]
> Are you going to give away more Ramda schwag, @buzzdecafe?

you are pretty free with my :dollar: @davidchambers 

Nonetheless, let's do this @ 2048 :star: , which is coming up pretty fast. I'll compile a list of contributors since 1000 and hold another random drawing.

**Comment by wayneseymour** [comment]
@megawac 
Ramda rox?

**Comment by buzzdecafe** [comment]
superseded by https://github.com/ramda/ramda/issues/1086
