### ISSUE TITLE
Consider the API of maxBy/MinBy

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#1071]
https://github.com/ramda/ramda/pull/456#discussion_r29909778

If passed an empty list, these functions don't return anything.  Should we accept a default/initial value?  Is there any other possibility?  Or is this simply a matter of _caveat emptor_?

**Comment by buzzdecafe** [comment]
i dropped it -- how can we know what kind of objects the user is comparing? if they think they are comparing a list of deeply nested properties on complex objects but pass an empty list, then what? IOW we don't have enough info to take an init object.

**Comment by CrossEye** [comment]
This would have to be an API change.  And I think we'll end up dropping it again.  But we should then at least document the issue.  Obviously we cannot _choose_ an empty value.  But the current implementation feels a bit like `foldl1`, which we ended up dropping for [some fairly good reasons][i20].

We could change the API to _accept_ the default val.

```js
    var maxBy(prop('x'), {x: -1, name: 'Unknown'}, 
        [{x: 20, name: 'A'}, {x: 33, name: 'B}, {x: 15, name: 'c'}]
    ); // => {x: 33, name: 'B'}

    var maxBy(prop('x'), {x: -1, name: 'Unknown'}, []); //=> {x: -1, name: 'Unknown'}
```

It's not exactly that I _want_ to do this.  It got brought up again yesterday, and it seemed that it had just been dropped.  While my first inclination is to drop it again, and simply document the behavior, I do have at least some reservations about the difference between how we handle this and how we handle folds.

  [i20]: https://github.com/ramda/ramda/issues/20

**Comment by buzzdecafe** [comment]
:-1: for adding an init to the public API. If they want a default value they can wrap in `ifElse` or `cond`. I agree it's weird like `foldl1`, but not quite as bad.

**Comment by davidchambers** [comment]
Could one do this to provide a default value?

```javascript
R.maxBy(R.prop('x'),
        R.append({x: -1, name: 'Unknown'}, list))
```

It creates some work for the garbage collector but otherwise seems to be a nice option.

**Comment by buzzdecafe** [comment]
@davidchambers i strongly prefer that

**Comment by CrossEye** [comment]
@davidchambers: Yes, we certainly could, but it doesn't answer the fundamental question:

What is the correct behavior of this function when the user supplies an empty list?  Return `undefined` (current) or some other signal value?  (`null` is the only other choice I can seriously contemplate.)  Throw an exception?  Use a (supplied) default value (breaks the API.)  None seem like great choices.  But I guess I lean toward the current behavior (return `undefined` and pray.)  But I think we should probably document this odd behavior.

**Comment by buzzdecafe** [comment]
yes, and it is odd that `max` is guaranteed to return a Number and `maxBy` is not guaranteed to return anything. but i don't see a solution.

**Comment by davidchambers** [comment]
I think returning undefined is the best of the options.

**Comment by buzzdecafe** [comment]
i think @davidchambers and i agree this is a "wontfix" so it's up to you to close or act on it, @CrossEye

**Comment by CrossEye** [comment]
Just added a note to the docs.  I agree that there's nothing better to do.

But it still makes me a bit squeamish to note the difference between this and the folds.

**Comment by davidchambers** [comment]
#1231 solves this problem. :)
