### ISSUE TITLE
Suggestion: improvement for docs

### ISSUE THREAD

**Issue by yazla** [ramda/ramda#1074]
It would be very very handy to have an ability to search function by input and output types.
Example:
```input - Object, output - List```
this should show functions such as ```keys, project, toPairs ...``` etc. 

Thanks.

**Comment by CrossEye** [comment]
I'm not quite sure how to make that work in our current docs.  I'd love a pull request, if you have suggestions.  In the meantime, just announced yesterday was this:

    https://github.com/raine/alfred-ramda-workflow

I have no idea if configuration files for Alfred works for similar tools for non-Apple OS's, though.

**Comment by davidchambers** [comment]
Something along the lines of [Hoogle][1] would be sweet!


[1]: https://www.haskell.org/hoogle/

**Comment by raine** [comment]
Now there's also: [Browse Ramda documentation in Terminal](https://gist.github.com/raine/413b9ed9fd437942af0e)

**Comment by CrossEye** [comment]
The man is prolific!  :fireworks:

**Comment by buzzdecafe** [comment]
closing without prejudice. i think we all agree we'd like something like this, and a PR would be welcome. so if anyone finds some time ....
