### ISSUE TITLE
Consider implementing uniq (and union) on top of native Set, if available

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1077]
ES6 includes a native Set object, that has the proper "has" complexity you'd want for uniq implementation.

Here's a quick & dirty performance compression between ramda's loop-based uniq to a uniq implementation on top of Set - it only works in Firefox because I'm using Array.from.

http://bit.ly/1F8awKZ

For 350 unique objects, each repeated 1000 times, I get 0.15 native : non-native ratio.

Note that Array.from isn't essential for this proposal, and that Set (unlike Array.from) is available in most environments.

**Comment by asaf-romano** [comment]
The ratio depends mostly on the number of unique objects. If you try it with 4 objects (no matter how many times they're repeated) the ratio is at about 0.8.

**Comment by CrossEye** [comment]
This is much more convincing than the recent example on Gitter.

It might be made a little better with `R.of`: http://bit.ly/1H9rfNC.  This now works in Chrome as well.

I don't think we want to abandon non-es6 environments, so if we choose to do this, it would have to use some sort of testing for the existence of `Set`.  We've done it before (`keys` comes to mind) but I'm loathe to make a habit out of it.  These numbers are pretty convincing, though.

**Comment by asaf-romano** [comment]
Yes, it took me a moment to realize that if all four elements appear at the top of the array, it's surprising that there was any difference to begin with.

Testing for Set existence is one option. Another is some sort of polyfill that is used unconditionally.

**Comment by buzzdecafe** [comment]
:+1: for using Set and backfilling for older environments. 

http://kangax.github.io/compat-table/es6/#Set

**Comment by asaf-romano** [comment]
@CrossEye Regarding R.of, it doesn't do what Array.from does; it simply wraps it's 1st arg in an array. Array.from creates an array out of an iterable.

**Comment by asaf-romano** [comment]
R.into([], R.map(R.identity), new Set([1,1,3,4])) works though.

**Comment by CrossEye** [comment]
I'm definitely convinced that this is something we should do.  I would love to see a PR for it.

**Comment by asaf-romano** [comment]
It was only after I implemented this that I realized this cannot be supported (from tests/uniq.js):
assert.strictEqual(R.uniq([new Just([42]), new Just([42])]).length, 1);

**Comment by asaf-romano** [comment]
So for further discussion, here's what I did:
https://github.com/asaf-romano/ramda/commit/44c011e76b34a785d2e9cd2443ed23c1bc21c385

The test that fails is the one that checks eq-dispatching. For NaN and +-0, Set happens to behave the way the test expects.

**Comment by scott-christopher** [comment]
If `uniq` holds a requirement for homogeneous lists, you could continue using the current implementation for elements satisfying the fantasy-land Setoid spec (`.equals`) and keep the custom equality semantics, while dispatching the remaining primitives and objects to use the native `Set` implementation demonstrated here.

If list elements implemented some type of comparison method (side note: this could also be useful for dispatching `sort`) along with the Setoid spec, a B-tree could be used to improve the performance of those wanting custom equality semantics, though the complexity introduced is likely growing beyond the value gained here.

If heterogeneous lists must be supported, then I don't see many alternatives beyond the existing implementation.

**Comment by asaf-romano** [comment]
One simple thing we could do is to scan the list once, and if there's any element that implements eq, go with the current implementation. Otherwise (if available) dispatch to Set.

**Comment by scott-christopher** [comment]
I guess you could have a hybrid like:
```js
function uniqViaSet(list) {
  var item,
      idx = -1,
      len = list.length,
      set = new Set(),
      setoids = [],
      uniqs = [];
  while (++idx < len) {
    item = list[idx];
    if (R.is(Function, item.equals)) {
      if (!R.contains(item, setoids)) {
        setoids.push(item);
        uniqs.push(item);
      }
    } else {
      if (set.size != set.add(item).size) {
        uniqs.push(item);
      }
    }
  }
  return uniqs;
}
```
```js
function Just(x) {
  this.x = x;
}
Just.prototype.equals = function(other) {
  return R.is(Just, other) && this.x == other.x;
}
Just.prototype.toString = function() {
  return "Just(" + this.x + ")";
}
```
```js
R.equals(new Just(5), new Just(5))
//=> true

var uniqueItems = uniqViaSet([1, 3, new Just(5), 1, new Just(3), 2, new Just(5), 4, 3, 2])
console.log('%s', uniqueItems)
//=> 1,3,Just(5),Just(3),2,4
```

**Comment by asaf-romano** [comment]
Nice, though at this point I should probably leave the PR to you :)

**Comment by davidchambers** [comment]
This proved problematic due to differing notions of equality.
