### ISSUE TITLE
Bookmarklet CSP problem

### ISSUE THREAD

**Issue by Sequoia** [ramda/ramda#1078]
`Refused to load the script 'http://cdn.jsdelivr.net/ramda/latest/ramda.min.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".`

The bookmarklet doesn't seem to work on most sites. https://github.com/blog/1477-content-security-policy

If a fully-inlined bookmarklet is an acceptable solution I can try to put something together (bookmarklet + task to update it on build). This was a royal pain in the butt when [I did it for another project](http://sequoia.makes.software/blog/building-to-github-pages-with-grunt/), mostly related to rebasing a `gh-pages` branch, but this time I think I could do it with less muss & fuss :smile_cat:. Lemme know if would be useful & I'll give it a shot when I have a mo.

**Comment by Sequoia** [comment]
looks like you keep the site source [on the same branch](https://github.com/ramda/ramda/blob/2b2c745c3187ef9f82d80d67a4e872bd095360b2/README.md). This should make it pretty easy to implement.

**Comment by CrossEye** [comment]
> If a fully-inlined bookmarklet is an acceptable solution I can try to put something together

I'd love it!

> looks like you keep the site source [on the same branch](https://github.com/ramda/ramda/blob/2b2c745c3187ef9f82d80d67a4e872bd095360b2/README.md). This should make it pretty easy to implement.

I'm not following, but if it makes it easier, all the better!

**Comment by buzzdecafe** [comment]
note that we are trying to remove the Grunt dependency, if that affects your thinking.

**Comment by Sequoia** [comment]
That's fine with me! I'll work it into an existing npm script if there's a `build` script (I'm on mobile, can't easily check)

**Comment by Sequoia** [comment]
## An aside about why I chose this approach
As a side note, using `//cdn.jsdelivr.net/ramda/latest/ramda.min.js` instead of `http://cdn.jsdelivr.net/ramda/latest/ramda.min.js` allows the current (remote script) bookmarklet to work on some sites (e.g. twitter) but still not on sites with stricter CSP policies (e.g. github). Github's `Content-Security-Policy` (sensibly) includes the following:

```
default-src *; script-src assets-cdn.github.com collector-cdn.github.com; object-src assets-cdn.github.com;
```
which disallows scripts from anywhere but those `github` urls. The inline method sacrafices auto-updating but gains:

1. works everywhere
2. no need for XHR request (so it would work while offline whereas current one won't)
