### ISSUE TITLE
Why a transducer of Ramda is so slow?

### ISSUE THREAD

**Issue by xgrommx** [ramda/ramda#1081]
I had created some test http://jsperf.com/like-a-linq-libraries-performance/18. And I don't understand why a transducer of Ramda is so slow.

**Comment by bergus** [comment]
Why haven't you written a function around it like for all the other test cases? Now you're measuring the performance of creating all those functions.

**Comment by CrossEye** [comment]
Well the first thing to do before anyone could tell would be to make it parallel to the other tests.  Here is what runs in every iteration for the `Lazy` code:

```js
    r_Lazy(arr);
```

Here is what's running in every iteration for the `Ramda Transducers` one:

```js
var t = R.compose(
  R.filter(R.compose(R.eq(0), R.modulo(R.__, 2))),
  R.map(function(x) { return x * x})
);

var r_Ramda_Transducer = R.transduce(t, R.flip(R.append), [], arr);
```

That's a lot of overhead!

**Comment by CrossEye** [comment]
Damn, beat again!

**Comment by CrossEye** [comment]
An appropriate way to write `r_Ramda_Transducer` would be:

    var r_Ramda_Tranducer = arr => R.into([], r_Ramda, arr);

or

    var r_Ramda_Tranducer = function(arr) {return R.into([], r_Ramda, arr);};

But, again, that shouldn't be done in the loop.

**Comment by xgrommx** [comment]
@CrossEye You did fixed my example? But Ramda transducer still slow. Also how can I use R.multiply if I want reproduce ```x => x * x```?

**Comment by CrossEye** [comment]
I  don't know why you _would_ use R.multiply for that, when there is such a convenient lambda.

And I was going to make another version with such edits, but someone else beat me to it.

**Comment by xgrommx** [comment]
If you talk about Revision 19 it was me.

**Comment by CrossEye** [comment]
No, someone altered 18 in the time between when I posted the code above and when you commented on it.  I was going to do a slightly different version, after trying it in the REPL.  

#21 was me.  And that one seems more respectable.  It's in the top half, although still only a quarter the speed of the fastest one.  I'm not sure what Lazy does that achieves that performance, but it's pretty impressive.

**Comment by xgrommx** [comment]
Interesting that on the Chrome faster is transducers but on the Firefox faster is Lazy =)

**Comment by CrossEye** [comment]
All sorts of things like that.  I wrote mine before I'd done a Chromium test.

I know the two engines optimize different things; I never remember very many details except that if there are a lot of function calls, it will probably perform better in Chrome than in FF.

**Comment by CrossEye** [comment]
I did mean to answer the `multiply` question earlier.  I still content that one generally wouldn't want to do this, as it's less clear than either of these:

```js
x => x * x
function(s) {return x * x;}
```

But if you really want to do something points-free with Ramda, you could choose this instead:

```js
R.converge(R.multiply, R.identity, R.identity);
```

**Comment by buzzdecafe** [comment]
closing for now. before we release 1.0 we will probably want to make perf tweaks.
