### ISSUE TITLE
R.contains curry trouble

### ISSUE THREAD

**Issue by fyyyyy** [ramda/ramda#1082]
Since R.contains gut curried it has changed behavior. is this intended ?

```javascript
R.contains(R.__)([2,5])(2) // this used to result in true ~ ramda 0.8
false
R.contains(R.__, [2,5])(2)
true

**Comment by TheLudd** [comment]
I think this is because only applying `R.__` returns a non modified version of the function i.e 
`R.contains(R.__)` is equal to `R.contains`.

**Comment by buzzdecafe** [comment]
this is surprising though. I would expect `R.contains(R.__)([2,5])(2) == R.contains(R.__, [2,5])(2)`

**Comment by TheLudd** [comment]
Yes, me to =)

**Comment by CrossEye** [comment]
@buzzdecafe and I have been discussing this offline.  I'm not convinced this should change.

I think -- and I'm far from certain of this -- that a placeholder in the last place of a parameter list should be a no-op.  The point is that it's not a value you can supply like any other; it's a way to modify the function.  But I can absolutely see the other side of this, and am concerned by this.

What say you @davidchambers?

**Comment by buzzdecafe** [comment]
i think this is a real problem. Consider:

```js
f = curry(function(a, b) { return a - b; });
f(R.__)(10)(1); //=> 9
f(R.__, 10)(1); //=> -9
f(R.__)(10, 1); //=> 9
```

IMO these three should have identical semantics.

**Comment by kedashoe** [comment]
hmm.. I don't see why this is a problem in theory or in practice. What else could it be doing except what it already is? `f(R.__)` return `f`. `f(R.__, 10)` returns a function with the 2nd argument curried in and waiting for the first argument. At a passing glance it maybe looks strange but the behavior is predictable and consistent, is it not?

In practice, I've been using placeholder currying for quite a while now and have never been tripped up by it (which admittedly doesn't mean much :)

**Comment by buzzdecafe** [comment]
what I am suggesting is that `f(__)` should equal `flip(f)`. Then:

```js
f(R.__)(10)(1); //=> -9
f(R.__, 10)(1); //=> -9
f(R.__)(10, 1); //=> -9
```

**Comment by CrossEye** [comment]
> IMO these three should have identical semantics.

I think that's only true if we consider `R.__` a value akin to any other.  If we do this, then we essentially treat 

```js
    f(R.__)
```

as equivalent to 

```js
    R.flip(f);
```

So what sort of interpretation do we give to 

```js
    f(R.__)(R.__);
```

Does that become equivalent to 

 ```js
    R.flip(R.flip(f)); //=~> f    
```

That won't make sense if f is ternary, perhaps we mean it for

```js
    var f = R.curry(function g(a, b, c) {return (a - b) / c;});
    f(R.__, R.__, 2)(15, 9); //=> 6
    f(R.__)(R.__)(2)(15, 9); //=> -13 / 9, if f(R.__) is simply flip(f)
```

I'm sure we can work it out.  But to me, the whole idea seems fraught with strange peril.  If we try to treat the placeholder as any other value, then we shouldn't be doing anything special with it in the first place.  The whole reason we have it is so that it can be put inline with other parameters.  The only reason to allow it to appear in the final place is for certain consistencies.  If these consistencies are contradicting one another, we might have serious problems.

**Comment by davidchambers** [comment]
```javascript
var f = R.curry((a, b, c) => [a, b, c]);
var g = f('foo', R.__);
```

What is `g`? A function awaiting two arguments: one to fill the empty slot left by the placeholder; one for `f`'s third argument which was not provided in the partial application of `f`. `g` takes the former before the latter, just as `f` does.

The alternative approach presented in this thread is more difficult to understand and explain. The idea is that we should distinguish between empty slots left by placeholders and those arising naturally from partial application. The rule for determining the order in which empty slots are filled is more involved: first fill the empty slots which arose naturally from partial application in left-to-right order; then fill the empty slots left by placeholders in left-to-right order.

I'm strongly opposed to replacing the straightforward left-to-right rule with one which distinguishes between `f('foo')` and `f('foo', R.__)`. I see no reason to take on this mental burden. If one wishes to change the order in which a function takes its arguments, one can write a wrapper function (or in some cases use `R.flip`). We should not increase the complexity of partial application.

---

One idea is to have multiple placeholder values. One could do something like this:

```javascript
var g = f(R.$1, R.$0, 'baz');
```

`g` awaits two arguments: the first is provided as the *second* argument to `f`; the second is provided as the *first* argument to `f`.

I don't think this is necessary, but if we want to control the order in which empty slots are filled we should provide an explicit mechanism for doing so.

**Comment by buzzdecafe** [comment]
Yes, this arises from permitting `__` in the tail position of the function call, where it really makes no sense. So I guess this is a "wontfix".

**Comment by davidchambers** [comment]
> Yes, this arises from permitting `__` in the tail position of the function call, where it really makes no sense.

Rather than "makes no sense" I would say "isn't useful". Adding zero to a number isn't useful either<sup>†</sup>, yet programming languages allow `x + 0`. Consistency is valuable, and sometimes necessitates allowing constructs which are not useful.

---

† Ignoring the horror of implicit type coercion.

**Comment by buzzdecafe** [comment]
> Rather than "makes no sense" I would say "isn't useful".

fair enough, my apologies.

So we're agreed this is "wontfix"?

**Comment by davidchambers** [comment]
> So we're agreed this is "wontfix"?

Yep. :)
