### ISSUE TITLE
2^11 stars

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#1086]
We're pretty close to 2048 stars, so @davidchambers generously recommended that I should give  away another [Ramda mug](http://www.zazzle.com/ramda_classic_white_coffee_mug-168294919219766885) to a random contributor. So what the hell. Here is the list of contributors since the [last drawing](https://github.com/ramda/ramda/issues/585). As before, please let me know in the comments below if you want to be *excluded*.

Candidates for 2048 prize:

@davidrusu 
@kedashoe 
~~@mLuby~~ 
~~@jethrolarson~~
@arcseldon 
@stites 
@taylor1791 
@saikobee 
@tolmasky 
~~@dtinth~~ 
@101100 
~~@kevinbeaty~~ 
@fyyyyy 
~~@honzabrecka~~
@wildermuthn
@nsluss 
@ppalladino 
@benjamingr 
@nicolasv 
@benperez 
~~@cust0dian~~ 
~~@gurdiga~~ 
@hemanth 
@bergus 
@Hilzu 
@josepot 
@raine 
@donnut 
~~@zemlanin~~ 
~~@bobiblazeski~~
@michaelckelly 
@santialbo 
~~@mcamac~~ 
@paldepind 
@scott-christopher 
@alexnormand 
@andyleggett 
~~@vikfroberg~~ 
@Sequoia 
~~@lwassermann~~ 

Thanks to all of you, and good luck. I'll do the drawing after we pass 2048 stars.

**Comment by jethrolarson** [comment]
I actually went and bought my own so I should probably be excluded so someone else can get one.

**Comment by jethrolarson** [comment]
2 ^ http://upload.wikimedia.org/wikipedia/en/0/06/Spinal_Tap_-_Up_to_Eleven.jpg

**Comment by cust0dian** [comment]
Thank you so much for including me in the list, Michael and team, but please exclude me. My contribution was really small, so I'd rather let others have a better chance at winning! :+1:

Also, didn't know Ramda had mugs, super cool!

**Comment by buzzdecafe** [comment]
@jethrolarson  "it's one louder, isn't it"

**Comment by benjamingr** [comment]
Here's to 2048 more!

**Comment by kevinbeaty** [comment]
Congrats on the milestone!  I think someone should create a 2048 knockoff using Ramda to celebrate. 

I'll also give up my raffle ticket.  Thanks for all of your work on a great library.

**Comment by hemanth** [comment]
8 more :star2: to go! :+1: :tada: Congrats!

**Comment by gurdiga** [comment]
Hey, this is cool! :) …but my only contribution is a tiny documentation tweak, so I don’t feel comfortable competing with guys that did real work. :->

**Comment by mLuby** [comment]
Same here, auto-disqualifying. Thanks for building Ramda!​

**Comment by zemlanin** [comment]
:+1: 

Mug for two typos is a steal, so exclude me

**Comment by lwassermann** [comment]
Same here. Exclude me.

**Comment by honzabrecka** [comment]
Same here, exclude me. Keep up the good work!

**Comment by davidchambers** [comment]
You people are so thoughtful. I :heart: typo fixes, by the way. :)

**Comment by vikfroberg** [comment]
Exclude me! Congrats on the success :tada:

**Comment by bobiblazeski** [comment]
Beside small documentation example, my main contribution was getting on the authors nerves, so please exclude me.  Congrats on the success :tada: & keep up the great work. By the end of the year I'm expecting Ramda to be second only to lodash.

**Comment by CrossEye** [comment]
@bobiblazeski: That's a very important contribution!!

**Comment by mcamac** [comment]
Please exclude me as well, thanks for running this though!

**Comment by dtinth** [comment]
Thank you, but my contribution is very small, so please exclude me.

Congrats, by the way.

I just realized that I did not star this project, so here's one more star towards 2048! :star:

**Comment by buzzdecafe** [comment]
looks like we hit 2048. I'll do the drawing this weekend.

**Comment by Sequoia** [comment]
Congrats @Ramda team! And to everyone with small contributions (mine was sort of a meta-contribution, not to the lib itself) don't talk your work down too much! Many hands light work & all that-- FOSS projects would be much more painful without all those small-but-important contributions. Big up yourselves! :tada: :+1: :palm_tree:

**Comment by buzzdecafe** [comment]
well said @Sequoia

**Comment by CrossEye** [comment]
:sparkles: @Sequoia :sparkles:

**Comment by jethrolarson** [comment]
@kevinbeaty I looked at the [2048 source](https://github.com/gabrielecirulli/2048) and it's pretty good actually. I think if I rewrote it using ramda it'd only be maybe 40% smaller and probably be less performant. Probably take 1000-2000 LOC.

**Comment by kevinbeaty** [comment]
@jethrolarson I agree, the original source is quite clean.  I was mostly joking... but it would be fun to see.  Maybe a basis for an "Intro to Ramda" blog post, or something.

**Comment by CrossEye** [comment]
Back when Mike and I were starting on Ramda (or maybe on it's predecessor, Eweda) I actually started such a beast.  But I lost interest pretty quickly.  It might be fun to put one together using Ramda and @paldepind's [flyd][fl].  But I do agree that it wouldn't be a matter of trying for a drastic improvement on the original, more a matter of, "Well, here's how you might use this stuff for _that_."


  [fl]: https://github.com/paldepind/flyd

**Comment by buzzdecafe** [comment]
I have drawn a winning name .... `a[Math.floor(Math.random() * a.length)]` ....

... and the winner is ....

:checkered_flag: @saikobee :checkered_flag: 
:dancers: :tada: :dancers:

Congratulations @sakiobee -- contact me via email to let me know where to ship your :trophy:

**Comment by saikobee** [comment]
Oh my gosh!

Big thanks to everyone else for all the work you've done! Don't discount yourself just because you believe your change trivial.

**Comment by hemanth** [comment]
Congrats @saikobee :tada: :+1:
