### ISSUE TITLE
R.toString should show non-numeric array properties

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1091]
```javascript
> /x/.exec('xyz')
[ 'x', index: 0, input: 'xyz' ]
> R.toString(/x/.exec('xyz'))
'["x"]'
```

`eval(R.toString(/x/.exec('xyz')))` is currently not equivalent to `/x/.exec('xyz')`, which breaks the contract.

I believe `R.toString(/x/.exec('xyz'))` should evaluate to `'["x", "index": 0, "input": "xyz"]'`. The non-numeric properties would appear, alphabetically ordered, after the values of the numeric properties.

**Comment by CrossEye** [comment]
I don't know.  Should we choose the Node.js output over the console output from Chrome/FF, which both report `["x"]` ?  IE console reports

```js
    x {
        0 : "x",
        input : "xyz",
        index : 0
    }
```

These environmental differences seem likely to make enforcing that invariant fairly tricky.

**Comment by davidchambers** [comment]
The `R.compose(eval, R.toString)` ≍ `R.identity` invariant is broken in the case of `/x/.exec('xyz')`, but my suggested fix is not a fix at all: `["x", "index": 0, "input": "xyz"]` is not syntactically valid. Oops!

We can't satisfy the invariant in this case, so the question is whether it's more important to return a syntactically valid string or to prevent values which are not equivalent (e.g. `['x']` and the result of evaluating `/x/.exec('xyz')`) from sharing a string representation.
