### ISSUE TITLE
Ramda fails to follow semver

### ISSUE THREAD

**Issue by mondalaci** [ramda/ramda#1092]
According to the Ramda changelog it's clear that Ramda introduces incompatible API changes across minor versions but according to semver you should increase the major number in such cases. You shouldn't break people's expectations regarding semver even if we end up with Ramda 234.1.2 eventually.

**Comment by TheLudd** [comment]
Well. not since ramda is in major version 0. 

> 4: Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/

**Comment by mondalaci** [comment]
@TheLudd Thanks, I stand corrected.

**Comment by CrossEye** [comment]
And we are getting close to 1.0, at which point we are planning on following this rule.
