### ISSUE TITLE
equality functions

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1094]
Currently we have [`R.eq`][1] and [`R.eqDeep`][2]. What we do not have is function to determine whether `Just(42)` and `Just(42)` are equivalent. Presumably `Just.prototype.equals` is defined, allowing `Just(42).equals(Just(42))`. But `Just([1, 2, 3]).equals(Just([1, 2, 3]))` will evaluate false if the method's implementation is similar to the following:

```javascript
Just.prototype.equals = function(x) {
  return x instanceof Just && x.value === this.value;
};
```

To resolve this, an author might use `R.eqDeep` to compare the values:

```javascript
Just.prototype.equals = function(x) {
  return x instanceof Just && R.eqDeep(x.value, this.value);
};
```

But `R.eqDeep` does not dispatch to an object's `equals` method if present, which creates another issue. `Just(Left(42)).equals(Just(Right(42)))`, for example, will evaluate true if `Left(42)` and `Right(42)` both appear as `{value: 42}` in the eyes of `R.eqDeep`.

My proposal is as follows:

1.  We change the name of `R.eq` to `R.identical`. The semantics will not change: `R.identical(0, -0)` will evaluate false, as will `R.identical([], [])`; `R.identical(NaN, NaN)` will evaluate true.

2.  We remove `R.eqDeep`.

3.  We define a new function, `R.eq`, with deep equality semantics which recursively dispatches to the `equals` method, if present, of each objects it encounters.

As a result of these changes the other equality functions (such as [`R.propEq`][3]), which are all defined in terms of `R.eq`, will acquire the new equivalence semantics.

The author of the Maybe type could then update her implementation of `Just.prototype.equals`:

```javascript
Just.prototype.equals = function(x) {
  return x instanceof Just && R.eq(x.value, this.value);
};
```

This will give the correct behaviour:

```javascript
> Just([1, 2, 3]).equals(Just([1, 2, 3]))
true
> Just(Left(42)).equals(Just(Right(42)))
false
```

[1]: http://ramdajs.com/docs/#eq
[2]: http://ramdajs.com/docs/#eqDeep
[3]: http://ramdajs.com/docs/#propEq

**Comment by buzzdecafe** [comment]
I think we should name the function `equals`. Then we avoid multi-dispatch (for now), and bring the lib into compliance with FL Setoid spec. And that, I think, is the point here.

Otherwise, this would be the first case of dispatching to an alias (viz. `eq(obj1, obj2) -> obj1.equals(obj2)`). i think that sort of multi-dispatch is inevitable, and even desirable, but we should consider the best way to do that generally.

So here's a counter-proposal:

1. Keep `eq` as is
2. Remove `eqDeep`
3. Add `equals` with dispatching and deep-equality semantics

**Comment by davidchambers** [comment]
Thanks for your feedback, @buzzdecafe. :)

Your point about a Ramda function named X dispatch to a method with a name other than X is well taken. There are two compelling reasons to do so:

  - `equals` makes a good method name: `a.equals(b)` reads nicely, and is much more visually appealing than `a.isEqualTo(b)` (which also reads nicely). The Fantasy Land authors made a good choice.

    For a function name, though, `equals` is not so good: `R.equals(a, b)` looks like it should really be `R.equal(a, b)` since the question is whether `a` and `b` are equal. (Counterpoint: `R.equals(42)` reads *very* nicely.)

  - The more significant point is that I believe the equivalence function (whatever we name it) encourages thinking in terms of *values*, whereas the identity equality function (whatever we name it) is concerned with where things live in memory. The other equality functions (such as `R.propEq`) should also have equivalence semantics.

    If one agrees that `R.propEq` et al. should have equivalence semantics, and if the equivalence function is named `R.equals`, `R.propEq` should be renamed `R.propEquals` for consistency. `R.pathEq` and `R.propEq` should be similarly renamed. `R.whereEq` sounds a little strange when renamed `R.whereEquals`. I'm not sure what name we'd give `R.eqProps`.

Though the points above are concerned with naming, the name to me is the least important aspect of this discussion. My requirements are:

  - an equivalence function which dispatches to `equals`;
  - equivalence semantics for other equality functions; and
  - consistently named equivalence functions.

**Comment by CrossEye** [comment]
I definitely agree about the basic requirements as expressed by @davidchambers.

I'm more inclined to like the naming @buzzdecafe proposed, and the `R.equals(42)` counterpoint demonstrates that there likely is no one perfect name.

I do want to ability to dispatch to alternate names, if nothing else, then for #1037.  But that needs to be a coordinated approach.  It could be led by this requirement, but it needs some careful consideration.

ISTM that the implementation we want for `equals` is simply to add the dispatching check to the current `_eqDeep`, presumably right after the reference equality check.

I still haven't thought through all the implications of the changes to the other equality functions, but my first thought is that @davidchambers' proposals sound good.

**Comment by davidchambers** [comment]
Having functions named `R.eq` and `R.equals` doesn't strike me as a good idea. The existence of both `substr` and `substring` methods on `String.prototype` has always bothered me.

Shouldn't we choose names which at least hint at the differences between the two functions?

**Comment by buzzdecafe** [comment]
to my mind FL compliance is higher priority than linguistic niceties. At present we have:

```js
Functor.map -> R.map
Apply.ap -> R.ap
Applicative.of -> R.of
Chain.chain -> R.chain
Semigroup.concat -> R.concat
Monoid.empty -> R.empty
Foldable.reduce -> R.reduce
```

And eventually:

```js
Traversable.sequence -> R.sequence
Extend.extend -> R.extend
Comonad.extract -> R.extract
```

.... so for `Setoid.equals` we *must* have `R.equals`.

**Comment by buzzdecafe** [comment]
> Having functions named R.eq and R.equals doesn't strike me as a good idea.

ok, but note that we have `ap` and `apply` already.

**Comment by davidchambers** [comment]
I'm fine with `R.equals`, @buzzdecafe. My objection is to naming the other function `R.eq` rather than `R.identical`. With `R.equals` and `R.identical` one has a sense of the difference even before reading the documentation.

**Comment by davidchambers** [comment]
> note that we have `ap` and `apply` already

Also confusing. ;)

**Comment by buzzdecafe** [comment]
> My objection is to naming the other function `R.eq` rather than `R.identical`.

understood. so we are coming to a compromise proposal here where we have:

1. `R.equals` dispatches or does deep equality (including nested dispatching i expect)
2. goodbye to `eqDeep` (except possibly as a private helper for `equals`)
3. rename `R.eq` to `R.identical` (or `R.sameAs`? `R.alike`? `R.quiteSimilar`? actually `alike` is not bad ...)

**Comment by davidchambers** [comment]
> so we are coming to a compromise proposal here where we have:
>
> 1. `R.equals` dispatches or does deep equality (including nested dispatching i expect)
> 2. goodbye to `eqDeep` (except possibly as a private helper for `equals`)
> 3. rename `R.eq` to `R.identical` (or `R.sameAs`? `R.alike`? `R.quiteSimilar`? actually `alike` is not bad ...)

I'm totally on board with this, though you haven't mentioned `R.propEq` and friends. What do you have in mind for this group of functions?

**Comment by buzzdecafe** [comment]
I expect we'll disagree here. But here goes: if `eq` is gone, `propEq` et al. could stand as is, since it is then unambiguous.

**Comment by davidchambers** [comment]
That seems reasonable to me, @buzzdecafe, though my question is about behaviour rather than naming. Should `R.uniq([Just(42), Just(42)])` give `[Just(42)]` or `[Just(42), Just(42)]`?

**Comment by buzzdecafe** [comment]
> Should `R.uniq([Just(42), Just(42)])` give `[Just(42)]` or `[Just(42), Just(42)]`?

Good question. IMO the best answer is `[Just(42)]`.

**Comment by davidchambers** [comment]
> IMO the best answer is `[Just(42)]`.

I agree! Since we agree in broad strokes, I'll open a pull request to give us something concrete to discuss.

**Comment by CrossEye** [comment]
Sorry I wasn't online for these discussions, but I agree wholeheartedly  with these decisions.
