### ISSUE TITLE
Command line documentation

### ISSUE THREAD

**Issue by srijanshetty** [ramda/ramda#1106]
Can the following gist be bundled somewhere:

https://gist.github.com/raine/413b9ed9fd437942af0e

It's a nifty script to browse ramda documentation from the shell.

**Comment by CrossEye** [comment]
I'm not sure of a great way to include this.  For the moment, I've added a Tools section to the home page of the wiki:  https://github.com/ramda/ramda/wiki#tools

Are there suggestions for better ways to incorporate something like this?  It's a wonderful tool, as are many of @raine's recent contributions.

Ping @raine

**Comment by srijanshetty** [comment]
I'm not entirely sure of it as well, some projects have an extra folder for completion and helpers but the extra folder becomes noise against the 'core' of the project. Maybe, having in the Wiki is the best possible way to go about it.
