### ISSUE TITLE
Expose _reduced?

### ISSUE THREAD

**Issue by garyposter** [ramda/ramda#1109]
What are your thoughts on exposing _reduced to the API?  Not important to me right now, but it would scratch an itch at least, and I could imagine it being more important to me or others in the future.

Thanks for a cool library!

**Comment by CrossEye** [comment]
I think it's a fine idea, and I would welcome a PR.

**Comment by garyposter** [comment]
Cool, thanks. :+1:

**Comment by CrossEye** [comment]
Closed by #1118
