### ISSUE TITLE
Calling a curried function with no arguments

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#1110]
In 0.9.1, doing the following:

R.curryN(1, function(){})()

Resulted in an error.

Now, it seems to just return the curried function again (allowing infinite empty calls).

I have no particularly concern with default behavior, but I'd really like some way to just allow it to interpret it as calling it with undefined (as would happen in normal function usage), that way I can do f() instead of f(undefined). That way I can pass it in to something that expects a function with no parameters, and the curried function is OK with receiving no parameter.

**Comment by CrossEye** [comment]
This has been in since 0.11.0.  You can see the PR and related discussion in #836.

**Comment by davidchambers** [comment]
> That way I can pass it in to something that expects a function with no parameters, and the curried function is OK with receiving no parameter.

There's no way to fully apply a curried function without providing any arguments. If providing `undefined` is acceptable, one could wrap the curried function:

```javascript
var f = ...;
var g = R.curryN(1, f);
var h = function(x) { return f(x); };
```

One could, of course, provide `f` as an argument rather than `h`. This seems the best option.
