### ISSUE TITLE
ES6-Map version of count[By]

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1115]
"Note that all keys are coerced to strings because of how JavaScript objects work."

An ES6-Map version of countBy (probably just count then) would, of course, not have that limitation and would be much more powerful in modern environments.

**Comment by buzzdecafe** [comment]
:+1:

**Comment by CrossEye** [comment]
A good idea.  I'd like to see a PR.  But it would have to be conditional on Map being as expected, as Ramda currently works in earlier versions of JS (actually back to ES3!)

**Comment by davidchambers** [comment]
I could make this change in #1056.

**Comment by asaf-romano** [comment]
@davidchambers do you mean that countBy would return a Map rather than an object if Map is supported (considering the scope of #1056)? That kind of "branching" makes sense (at least to me) only when it's also based on the input (e.g. filtering a Map should probably return a Map). This doesn't apply for countBy... the input is almost always an array (certainly not a Set), regardless of the environment. So here I believe a separate function would work better.

**Comment by davidchambers** [comment]
> So here I believe a separate function would work better.

I agree.

**Comment by CrossEye** [comment]
I have a bad feeling about adding functions that will only operate in an ES6 environment.  I have no issue with the ones in #1056 that expand the API to also include `Map`, or with using `Map` when available as a way to boost performance.  But I'd rather not fork our API on language version.

**Comment by asaf-romano** [comment]
Maybe something like R.es6.* for these cases?

Another option is a version of countBy that takes the accumulator (similar to into).

**Comment by asaf-romano** [comment]
Hmm, obviously this should be discussed after/together with groupBy.

**Comment by buzzdecafe** [comment]
closed for inactivity
