### ISSUE TITLE
Function inverses in the documentation

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1119]
I've spent a lot of time searching through the documentation looking for the opposite of a function that I have found in the documentation. 

For example, I've found the function `take` which is useful. But now I'm looking for the opposite function -- rather than take the first n, I'd like to `drop` the first n. It would be nice if there were notes in the documentation of these opposites. It would just be a nice touch so I dont have to search around as long.

**Comment by paldepind** [comment]
I like this idea :+1:

**Comment by CrossEye** [comment]
I don't think a specific annotation for _opposite_ is necessary.  But in any cases where there is an opposite, we should have an _@see_ annotation.

**Comment by ccorcos** [comment]
exactly

**Comment by CrossEye** [comment]
Well, a PR would be quite welcome!
