### ISSUE TITLE
before and after

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1120]
I think this two functions would be a nice addition for dealing with lists and strings.

```coffee
before = R.curry (func, list) ->
  idx = 0
  len = list.length
  while idx < len
    if func(list[idx])
      break
  return list[0...idx]

after = R.curry (func, list) ->
  idx = 0
  len = list.length
  while idx < len
    if func(list[idx])
      break
    idx += 1
  return list[idx+1...]
```

**Comment by buzzdecafe** [comment]
isn't this essentially `takeWhile` and `dropWhile`?

**Comment by ccorcos** [comment]
hmm. Those seem like they're no different from `filter`

**Comment by buzzdecafe** [comment]
they are different in that they stop evaluating as soon as the predicate is satisfied.

**Comment by ccorcos** [comment]
yeah, so `before` and `after` are different.

```js
list = [1,2,3,4,5,6,7]
before(R.eq(1), list)
// => []
before(R.eq(19), list) 
// => [1,2,3,4,5,6,7]
before(R.eq(4), list) 
// => [1,2,3,4]
after(R.eq(4), list)
// => [5,6,7]
after(R.eq(19), list) 
// => []
```

**Comment by stoeffel** [comment]
How about naming it `takeUntil` and `dropUntil` to match the existing `takeWhile` and `dropWhile`?

We did the same in [1-liners#takeUntil](https://github.com/1-liners/1-liners/tree/master/documentation#takeuntil)

**Comment by ccorcos** [comment]
@stoeffel 1-liners is pretty cool haha

[`takeUntil`](1-liners#takeUntil) and `before` are the same. But `after` is different from `takeWhile` or `dropWhile`. Perhaps `after` could be called `takeAfter`.

**Comment by stoeffel** [comment]
> 1-liners is pretty cool haha

:smile_cat:

> But after is different from takeWhile or dropWhile. Perhaps after could be called takeAfter.

You are right. `takeAfter` sounds accurate.

**Comment by buzzdecafe** [comment]
the only difference i can see is the sense of the predicate. your functions are the opposites of those taken for `takeWhile/dropWhile`. Inverting the predicate is not a big deal. These still look like `takeWhile/dropWhile` to me. http://bit.ly/1Qcp6TA

**Comment by CrossEye** [comment]
In other words,

    var before <=> R.useWith(R.takeWhile, R.complement, R.identity);
    var after <=> R.useWith(R.dropWhile, R.complement, R.identity);

http://bit.ly/1GGuzRR

**Comment by ccorcos** [comment]
Hmm. `dropWhile` says this:

> Returns a new list containing the last n elements of a given list, passing each value to the supplied predicate function, skipping elements while the predicate function returns true. The predicate function is passed one argument: (value).

That definition sounds a lot like `filter` to me. And the example doesn't really help to disambiguate.

```js
var lteTwo = function(x) {
  return x <= 2;
};

R.dropWhile(lteTwo, [1, 2, 3, 4]); //=> [3, 4]
```

I verified that this works `R.dropWhile(lteTwo, [1, 2, 3, 4, 3, 2, 1]); //=> [3, 4, 3, 2, 1]`

So yes, they're the same.

**Comment by davidchambers** [comment]
The current example for `R.dropWhile` is unclear. Your example is much better, @ccorcos. Would you like to open a pull request for this change?

**Comment by ccorcos** [comment]
I'd be happy to. I haven't contributed before so just to double check with you. Do I just change it here:

https://github.com/ramda/ramda/blob/master/src/dropWhile.js#L28

Then how do I update the docs?

**Comment by buzzdecafe** [comment]
great, thanks! just update the comments, the docs get built at release-time in a separate repo
