### ISSUE TITLE
R.pick doesn't support numeric object keys.

### ISSUE THREAD

**Issue by josephong** [ramda/ramda#1121]
Assume we create an entry in an object as follows:

```javascript
  var obj = {};
  obj[1] = 'foo';
  console.log(obj[1]);
  console.log(obj['1']);
```

Logs 'foo' twice.

However,

```javascript
  var obj = {};
  obj[1] = 'foo';
  console.log(R.pick([1], obj));
  console.log(R.pick(['1'], obj));
```

Logs {}, and then {1: hello}.

**Comment by josephong** [comment]
Granted the function signature is ```[String] → {String: *} → {String: *}``` but it would be convenient to support ```[k] → {k: v} → {k: v}``` like ```R.pickAll``` does?

**Comment by buzzdecafe** [comment]
certainly `pick` and `pickAll` should have the same semantics w/r/t selecting properties. At present `pick`:

```js
function pick(names, obj) {
  var result = {};
  for (var prop in obj) {
    if (_indexOf(names, prop) >= 0) {
      result[prop] = obj[prop];
    }
  }
  return result;
})
```

and `pickAll`:

```js
function pickAll(names, obj) {
  var result = {};
  var idx = -1;
  var len = names.length;
  while (++idx < len) {
    var name = names[idx];
    result[name] = obj[name];
  }
  return result;
}
```

it should be pretty trivial to unify them by iterating in the same way.
