### ISSUE TITLE
Picking from a list by an array of indices.

### ISSUE THREAD

**Issue by josephong** [ramda/ramda#1123]
Sorry if this already exists – I needed something like this today, but couldn't seem to find something that does this without using R.nth and other functions together! Would this be generally useful enough to add?

```javascript
R.takeIndexed([0, 2], ['a', 'b', 'c']); // =>['a', 'c']
```
I'm hesitant to submit a pull request, since I don't if it's appropriate with what's wanted, what to name it, or whether there's an internal function to make this more concise 😶. But something like this would work?

```javascript
var _curry2 = require('./internal/_curry2');
var _nth = require('./internal/_nth');

/**
 * Returns a new list containing the elements of xs at the specified indices.
 * If an index n is negative, the element at index length + n is returned in the corresponding slot. 
 * If an index n is past the end of the array, undefined is returned in the corresponding slot.
 *
 * @func
 * @memberOf R
 * @category List
 * @sig [Number] -> [a] -> [a]
 * @param {Array} indices An array of indices used to pull elements into the new list
 * @param {Array} xs The list to pull elements from
 * @return {Array} A new list with only elements from the specified indices.
 * @example
 *
 *      R.takeIndexed([0, 2], ['foo', 'bar', 'baz']); // => ['foo', 'baz']
 *      R.takeIndexed([-1, 0], ['foo', 'bar', 'baz']); // => ['baz', 'foo']
 *      R.takeIndexed([0, 3], ['foo', 'bar', 'baz']); // => ['foo', undefined]
 */
module.exports = _curry2(function takeIndexed(indices, xs) {
  var result = [];
  var idx = -1;
  while (++idx < indices.length) {
    result[idx] = _nth(indices[idx], xs);
  }
  return result;
});
```

**Comment by raine** [comment]
`takeIndexes` might be a better name. The `...Indexed` naming has other semantics.

**Comment by buzzdecafe** [comment]
`R.compose(R.values, R.pickAll);`

**Comment by josephong** [comment]
Ah, I didn't know R.pickAll would work on lists as well. Perhaps the documentation should be updated to reflect that? I tried pick at first, which didn't work, so I assumed R.pickAll wouldn't. 

In that case, there is a difference between R.pickAll and R.pick when working on lists:

```
R.pick([0, 2], ['a', 'b', 'c'])
Object {0: "a"}

R.pick([0, 2], ['a', 'b', 'c'])
Object {0: "a"}
```

Also, the order of ```R.compose(R.values, R.pickAll)``` is also not guaranteed to be the order of the input array of indices, which is undesirable, so there might still be a case for a List specific method.

**Comment by CrossEye** [comment]
> In that case, there is a difference between R.pickAll and R.pick when working on lists:

Right, discussed in #1121.  This should be fixed soon.

**Comment by buzzdecafe** [comment]
the key iteration order is still a valid issue though. if you are very convcerned about that case you could do something like

```js
function pickIdx(ids, list) {
  return R.filterIndexed(function(_, idx) {
    return R.contains(idx, ids);
  }, list);
}

pickIdx([0, 2], ['a', 'b', 'c']); //=> ['a', 'c']
```

i could probably do this as a one-liner using `ap` ....

**Comment by raine** [comment]
`ap(map(nth, [0, 1]), of(['a', 'b', 'c']))`

**Comment by buzzdecafe** [comment]
@raine nice! very similar use case to a blog post i did on using `ap` and `of`

**Comment by buzzdecafe** [comment]
(add it to the cookbook!)

**Comment by davidchambers** [comment]
Another solution:

```javascript
R.map(R.nth(R.__, ['a', 'b', 'c']), [0, 2])
```

**Comment by josephong** [comment]
Agreed that it can be written using other functions, it can just take a little time to parse what's going on from a readability standpoint. I think there's still the case that it might be a fairly basic piece of functionality that an engineer could want! Anyways, I will let you guys decide :), and use ```ap``` for now.

**Comment by buzzdecafe** [comment]
my feeling is we should not expand the api with functions that can easily be composed except when there is a compelling reason to do so. i'm interested to hear other opinions.

**Comment by CrossEye** [comment]
I agree.  Compelling reasons might include that such a function would be really common (`pipe` versus `compose`) or where this allows us to expose very well-known names (`unary`, `binary`.)

**Comment by jetpackpony** [comment]
A pointfree version of @raine's solution:
`R.useWith(R.ap, [R.map(R.nth), R.of])([0, 2], ['a', 'b', 'c'])`

**Comment by rmarren1** [comment]
+1 for implementing this as a separate function for readability, I think this is a pretty common operation

**Comment by 3limin4t0r** [comment]
I'm surprised nobody mentioned `props` yet.

``` JavaScript
props([0, 2], ['a', 'b', 'c']); // => ['a', 'c']
```
