### ISSUE TITLE
bench issues

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#1128]
I commented on some bench issues [here](https://github.com/ramda/ramda/commit/0cdfebc0a22a60de86d708ab170ddc1bd8e6827a#commitcomment-11420193), [here](https://github.com/ramda/ramda/commit/99508d15632f8cefca13d2440027fc4de432c7ef#commitcomment-11420133), & [here](https://github.com/ramda/ramda/commit/99508d15632f8cefca13d2440027fc4de432c7ef#commitcomment-11420134). Basically some `_.filter`, `_.find`, `_.findIndex`, & `_.max` comparisons aren't equiv and return different results than Ramda.

**Comment by buzzdecafe** [comment]
do you have recommendations for more equitable comparisons?

**Comment by jdalton** [comment]
The "where" syntax of Lodash doesn't map to `isEmpty` so you could punt on those comparisons or change them to not be "where" style comparisons for that and use basic predicates.

Their isn't a `maxBy` equiv (with the behavior of Ramda) so you'd need to punt on it or compare the basic `max`.

**Comment by jdalton** [comment]
Also note that `count` shouldn't be highlighted as it's more supplemental than substance.
It's really hz + margin of error you're wanting. Benchmark has a `formatNumber` helper to display the results prettier. Something like:
```js
Benchmark.formatNumber(bench.hz.toFixed(bench.hz < 100 ? 2 : 0)) + '+-' +
  bench.stats.rme.toFixed(2) + '%'
```

**Comment by buzzdecafe** [comment]
thx, will try and get to this when i have a fewe mins

**Comment by CrossEye** [comment]
I'd vote we simply remove the lodash calls altogether.  We put them in as a way to compare to what was at the time undeniably the best-of-breed library for performance.  It seemed a useful baseline.  That has changed a bit with Lazy and transducers.

But the real goal of these is to ensure that our implementation does not regress too badly in performance.  The only important thing for these samples is how Ramda does compared to previous runs.  Let's not worry about staying in sync with lodash.

**Comment by jdalton** [comment]
>  That has changed a bit

Naw, lodash is still holding its own. 

> But the real goal of these is to ensure that our implementation does not regress too badly in performance. 

Great goal.

**Comment by CrossEye** [comment]
>> That has changed a bit

> Naw, lodash is still holding its own. 

No disrespect intended.  lodash is still clearly _among_ the fastest.  It's just no longer alone at the top of the pack.  :smile:

The point, though, is that where comparing ourselves to lodash when Ramda was brand-new made some sense; it was a sanity-check that we weren't getting way too slow.  Now, since we really don't pay much attention to the benchmarks, our best bet might be just to keep those that help us avoid/track major performance regressions.

**Comment by jdalton** [comment]
> It's just no longer alone at the top of the pack.

Its mix of perf & features certainly make the others work for it.

> The point, though

You're preaching to the choir. I've been rocking a suite for the same purpose for more than 3yrs now.
