### ISSUE TITLE
assoc, prop, assocPath, and path

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1131]
How do you feel about checking if an argument is an array or a string so we can do this:

```js
R.assoc('a', 1, {}) // => {a:1}
R.assoc(['a', 'b', 'c'], 1, {}) // => {a:{b:{c:1}}}
R.prop('a', {a:1}) // => 1
R.prop(['a', 'b', 'c'], {a:{b:{c:1}}}) // => 1
```

This would consolidate two functions and I think it would make a lot of sense

**Comment by CrossEye** [comment]
Ramda tries very hard to keep its functions [simple][rh].  Outside the fact that some of them will dynamically dispatch to one's internal implementation (especially useful for [FantasyLand][fl] integration), our functions are meant to be as straightforward as possible.  We would almost always have separate functions that operate on different types, even if they do similar things.  There is more information in my [Philosophy of Ramda][pr] essay.


  [fl]: https://github.com/fantasyland/fantasy-land
  [pr]: http://fr.umio.us/the-philosophy-of-ramda/
  [rh]: http://www.infoq.com/presentations/Simple-Made-Easy

**Comment by ccorcos** [comment]
Thanks for the links. I'll have to take more time to read them.

I understand your reasoning, though I'm not sure I wholeheartedly agree (I havent read those links yet ;). I believe there is at least one contradiction in Ramda:

```js
R.concat('as', 'df') // => 'asdf'
R.concat([1,2], [3,4]) // => [1,2,3,4]
```

**Comment by buzzdecafe** [comment]
sometimes things fall out of the implementation, e.g. `R.add` is intended to work with numbers. But `R.add('a', 'b') //=> 'ab'`. I don't want to enforce numeric inputs, but I don't want to encourage loose typing either. In the `concat` case that bothers me less, since that is dispatching on type of the _input data_, which we do all over the place

**Comment by ccorcos** [comment]
hmm. I see. theres a subtle difference.
