### ISSUE TITLE
Dispatch forEach for anything but arrays

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1134]
Symbol.iterator / @@iterator aside, both ES6 and third-party libs follow the pattern of implementing forEach for all iterables, as the "functional analogy" for for-of loops.

Now, I know that for arrays ramda's forEach semantics are intentionally different from Array.prototype.forEach, but for anything else I believe dispatching forEach makes sense.

**Comment by buzzdecafe** [comment]
i agree, this should happen.

**Comment by asaf-romano** [comment]
So, _dispatchable already excludes arrays. The only thing that makes this a little un-trivial is that forEach probably should not act on transducers.

**Comment by buzzdecafe** [comment]
>  forEach probably should not act on transducers.

then use the simpler `_hasMethod` inside `forEach` instead of wrapping it in `_dispatchable`
