### ISSUE TITLE
Stable Sort

### ISSUE THREAD

**Issue by taylor1791** [ramda/ramda#1135]
[Stable sorts](http://en.wikipedia.org/wiki/Sorting_algorithm#Stability) provide desirable features over a non-stable sorts that is necessary a some cases. Since the Array.prototype.sort does not provide any such guarantee and, according to [this](http://blog.rodneyrehm.de/archives/14-Sorting-Were-Doing-It-Wrong.html), browsers do not agree in the implementation, there is no guarantee about Ramda's. 

Does ramda care about this? If not, should ramda contain a stable sort?

**Comment by buzzdecafe** [comment]
i think this is a desirable feature. certainly worth exploring.

**Comment by CrossEye** [comment]
Agreed.  And since Ramda doesn't really do any internal sorting, we could easily decide, even if this ended up less performant than the native non-stable versions to nontheless offer it as an alternative version for those who need it.

**Comment by paldepind** [comment]
* Ramda already includes a very similar function and in most cases unstable sort it not a problem. And if #994 gets solved I think the need would be even smaller.
* The complexity/size of such a function would not be insignificant.
* It is not hard to find [implementations elsewhere](https://www.npmjs.com/package/stable) compared to which Ramda would not offer any benefits.
* It doesn't really have anything to do with functional programming but is a general purpose algorithm.

**Comment by buzzdecafe** [comment]
> It is not hard to find implementations elsewhere compared to which Ramda would not offer any benefits.

ok, fair point.

> It doesn't really have anything to do with functional programming 

it supports referential transparency: any input list is guaranteed to have the same output list on any platform.

**Comment by CrossEye** [comment]
- This would be either in addition to [`sort`][so] or in place of it, although now that I look at it, we would probably also need to consider [`sortBy`][sb], which dampens my enthusiasm a bit.  As to whether a non-stable sort is an issue, that's to my mind, and issue for the user to decide.
  - The complexity does not have to be great at all.  We can easily map elements onto a `{elt, idx}` structure, sort according to the original comparator, break ties by index, and then pluck the elements off the results.  Clearly this is not as efficient as a good mergeSort implementation, but it demonstrates that we can choose the level of complexity that fits.
  - For almost all our functions, one can find easily find other implementation.  The main questions are usually about how well they fit with the rest of Ramda
  - Many of our other functions also have little to do with FP, but are useful utilities that one might want to have offered with a functional API. 


  [sb]: http://ramdajs.com/docs/#sortBy
  [so]: http://ramdajs.com/docs/#sort

**Comment by CrossEye** [comment]
Closing in favor of $1456
