### ISSUE TITLE
Grouping functions by input and/or usecase

### ISSUE THREAD

**Issue by villesau** [ramda/ramda#1136]
Hello!

I'm new to Ramda and i have hard time to learn all the functions; There is so many of them.

Because of that, it just came to my mind that it would be a lot easier to understand ramda and it's functions by grouping the somehow. For example: R.object.where, or R.math.sum. This way it would be easier to find in editor the correct function for each use case and understand straight away where it should be used.

I just want to raise some conversation how you guys feel about the idea. Of course for older users like ramdas core developer its always clear how and where to use the function, but for newcomers the learning curve is quite high because of the amount of functions.

I know it's more verbose, but i think it would pay back by making it clearer for user what is the purpose and/or what the function takes in. It could also be optional: reserving for example words R.object, R.math, R.function, R.list/array R.string etc for more declarative use, and let the current api as it is.

**Comment by buzzdecafe** [comment]
welcome @villesau !

I love the idea of grouping common functions _for the documentation_. That should absolutely happen. But I think adding namespaces to the library will be a tough sell.

**Comment by villesau** [comment]
Is there any drawbacks in namespacing them? It could be just an alias for the R.<function> so the function could work in both ways. I haven't tried of course, but as a newcomer and fresh eyes to Ramda i think it would make the learning and understanding the library a lot easier, at least with an editor/ide which has some sort of autocomplete.

Now it's not very intuitive when there is a huge list of functions for totally different purposes.

I don't see any harm in namespacing/aliasing the functions, so why not give it a try? If i'm right, Ramdas api is not freezed yet so if  after gathering some feedback about the approach it turns out to be a bad idea for some reason, it is always possible to revert. Only drawbacks what i see, is that it's more verbose(but more declarative) and it pollutes the api a bit.

**Comment by CrossEye** [comment]
Well if it were just an alias for `R`, then weird constructs like these would be legal, which would bother me:

    R.math.map // should be R.list.map
    R.math.list.string.object.function.logic.relation.filter // Well, why not?

I agree with @buzzdecafe that this belongs as part of documentation, and not as part of the runtime code.  But it definitely belongs.  The only challenge is that some of our functions really should be listed in multiple categories.  (Does `max` belong in `List` or `Math`?)  But there seems to be no good reason to duplicate the listings...

**Comment by davidchambers** [comment]
Closing since we've decided not to pursue the original proposal.

As for documentation, the [Ramda Manual][1] will provide thematic function grouping.


[1]: https://github.com/ramda/ramda/issues/1282
