### ISSUE TITLE
R.is implementation has the problematic characteristics of instanceof 

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1140]
Long story short: http://bit.ly/1I3wwqf

This isn't an issue in node.js environments (at least not in non-esoteric usage... I guess one could get multiple globals through the vm modules), because node uses a single global object for all modules. However, in browser environments, and probably in some other JS environments, having to deal with multiple global scopes is a quite common obstacle, and also one of the reasons why some developers avoid using instanceof.

There is no perfect solution for this, but I think that at least for native js types, Ramda should work "as expected" (i.e. in the practical manner ;-)). The obvious example is arrays: I don't think the current difference between Array.isArray to R.is(Array) is something that can ever be beneficial to anyone.

On a side note, an interesting edge case is |R.is(Object, Object.create(null))|, which returns false (as expected) even though Object.create(null)| walks and does almost all of the things an object does - it's just not an Object (Object.create(null) is often used to avoid accidentally picking Object.prototype keys when using an object in the role of a map).

**Comment by CrossEye** [comment]
Somehow I missed this one when it was posted.  You're right that this is unfortunate.  Obviously we can switch to the sort of solution kangax gave some years ago for the known types, but it would be some pretty ugly code, involving something like:

    Object.prototype.toString.call(val) === '[object Array]'

    Object.prototype.toString.call(val) === '[object Date]'

etc., with a separate path for anything other than the known types.  Do you have any other suggestion?

**Comment by asaf-romano** [comment]
This seems to work ok:
http://tinyurl.com/o3eab7p

("Make short URL" doesn't work there for whatever reason)

**Comment by benjycui** [comment]
@asaf-romano Function.name [does not work in IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name).
```js
var fixedIsImpl = R.curry((ctor, obj) => {
  if (R.type(obj) == "Object" && ctor != Object) {
    return R.is(ctor, obj);
  }
                      
  return R.type(obj) == ctor.name;  // I mean ctor.name
});
```

@CrossEye I can not find any documentation about the browser compatibility of Ramda. Is that OK?

**Comment by buzzdecafe** [comment]
@benjycui we have a sauce suite, we just have to get it running again. the problem was it was running *too much* (and timing out). Anyways, ramda should be ES3-compatible, for better or worse.

**Comment by asaf-romano** [comment]
The reason I used Function.name is because Object.toString.apply is only useful when it runs on an instance. That is, it will only return "...Array..." if it runs on []. Running it on |Array| just returns "...Function...".

So, indeed, if constructor.name cannot be used, all the native object have to be hardcoded in the implementation.

**Comment by benjycui** [comment]
@buzzdecafe THX!
@asaf-romano You can try `toString`, and then slice the function name. :-)
```js
Array.toString()  // => "function Array() { [native code] }"
```

**Comment by asaf-romano** [comment]
Nice, just need to double check that all browsers return a similar result for native functions like this.

**Comment by asaf-romano** [comment]
http://tinyurl.com/ob9t7pl

**Comment by asaf-romano** [comment]
On a side note, I think R.toString is using .constructor.name

**Comment by davidchambers** [comment]
plaid/sanctuary#105 demonstrates a solution to this problem. The one thing we would lose is knowledge of the type hierarchy: `R.is(Error, new TypeError())` currently evaluates true, but would evaluate false were we to abandon `instanceof` checks. Also, for `R.is(Foo, new Foo())` to evaluate true, Foo would need to define a `'@@type'` property on its prototype.

**Comment by svozza** [comment]
I've never really understood the point of having `instanceof` in a language that doesn't have classes.

**Comment by CrossEye** [comment]
This seems to be a deal-breaker:

> Also, for `R.is(Foo, new Foo())` to evaluate true, Foo would need to define a `'@@type'` property on its prototype.

That sounds far too intrusive.

**Comment by raine** [comment]
For what it's worth, I had this issue with my repl tool not working for example with Ramda functions that use `R.is`  against function values produced in repl context. The built-in node repl didn't exhibit this issue so I dug in the code a bit and found the option `useGlobals: true` for `repl.start(opts)`. It has the effect of using same globals (`Function` etc.) for repl context and required modules.

**Comment by CrossEye** [comment]
That's a nice find, @raine.

I do think we should solve the underlying problem as best we can in Ramda.  There are clear enough solutions for native types, but I haven't seem anything great fir user types.   I find the `@@type` solution both too intrusive and to fat from robust.
