### ISSUE TITLE
Ligatue for right arrow

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#1150]
Although I really like the look of the Haskell-style type signatures in our documentation, there is one down side to the right arrow character used in them.  It makes searching much more difficult.  If we want to find all of the 30+ instances of this in the documentation page:

    [a] → [a]

we can't search for

    [a] -> [a]

even though that would clearly be most useful.  One way to fix this would be to use a font that applies a ligature to the characters '`-`' and '`>`' to display a reasonable right-arrow character.

Does anyone know of such a font?  Or have the skills to build one?  I've never played around with fonts in any way.

**Comment by buzzdecafe** [comment]
we should probably just use `->`. [that's what they do here e.g.](http://hackage.haskell.org/package/base-4.8.0.0/docs/Prelude.html#t:Functor)
... and they even use it in [example searches](https://www.haskell.org/hoogle/)

**Comment by CrossEye** [comment]
Possibly, but I did do some further research after submitting the issue, and I found that there are some tools to make this fairly easy.  I will look further.  For the moment, though, I think we should stop replacing ` -> ` with ` → `.

**Comment by paldepind** [comment]
I like just using `->`. Keep it simple. It would also make it obvious to people that they can search by using `->`. I think few people would realize that they don't have to use the fancy arrows when searching.

**Comment by CrossEye** [comment]
I suppose you're right.  It should be obvious enough.  I guess we just want to make sure the look is fairly pleasant in the font we choose.
