### ISSUE TITLE
Error occurs when `npm test`

### ISSUE THREAD

**Issue by benjycui** [ramda/ramda#1152]
I `git clone` to my local just now, and then `npm test`. The following error occurs and/but I have not edited my local repo. What's wrong with it?
```bash
path-to/ramda/test/addIndex.js:13
var mapIndexed = R.addIndex(R.map);
                   ^
TypeError: undefined is not a function
```

I try to find the reason for this error. Then, I found that there is no `addIndex` in `path-to/ramda/dist/ramda.js`. Is that a mistake?

**Comment by buzzdecafe** [comment]
try `npm run build && npm test`

**Comment by benjycui** [comment]
A stupid question :-). THX!

**Comment by buzzdecafe** [comment]
not stupid at all. it's not obvious to do this. I wonder if we should build the dist file in `pretest` and reset it in `posttest` to make it completely transparent

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda/pull/1157
