### ISSUE TITLE
Maybe the killer feature for Ramda is managing state?

### ISSUE THREAD

**Issue by falafflepotatoe** [ramda/ramda#1154]
Was working last night on a MVC app, and I'm wondering if the real killer feature for ramda is going to be "managing state"

I'm wondering if you guys can do better than all other libs now with managing state/ui interactions with Ramda..

So a typical state>ui interaction is like

    if (checkbox.is_disabled == 1) return false; // dont let user input  (but with jquery or vanilla its really like 40-80 chars of code)
    if (model.game_level == 0) $('.obj1,.obj2,.obj3.....................').hide(); /* then 20 more lines of this */ 
    if (model.checkPiechart == 1) data.transform(1,2,3,4,5) else data.transform(3,4,5,6,7) // line chart

So I was thinking something like ramda for managing state would be great.

My MVC already uses an event emitter so I could go off that very easy. And ES7 has a observable() pattern. So I think were not that far off...

in this code snippet I put functions with params inside an object, this would not work without returning only a (Ramda) function.
(pseudo-code)

    //fake observable/event emitter plugin
    function w (v, opts){ 
        this.listenTo(v, 'change', function (){ 
            var keys = Object.keys(opts)
            for(i=0;i++;i<keys.length)
                if(event==keys[i] || value == keys[i]
                 ramda(this, opts[keys][i])
        }
    })
    
    //ramda -- maybe goodness for magaging state
    w(model.state, {
        inputmode: app.show(['.input','.add'])
        listmode: app.hide(each(['.input','.add']).show(each(['.lbl','.rem']))
        reset: app.hide(each(['.rem','.lbl']).show(each('.input','.add'))
    })
    
    w(downloadpercent, {
        change: app.label1(val(value + '% complete'))
        complete: app.label1(val('download complete').link.show().attr('href',model.filename)
    }
      
    websocketRespond(app, MapObjectKeyToFn('command', {
      'open': app.new,
      'close': ()=> {send('clientexit')},
      'update':app.model.Merge(newData.transform(first,second...))
      'playerjoin':app.model.push(newData.player),
      })
      
    

i think theres some hope in using it for creating UI elements -- but more for C or Go, IDK what do you think. Way cleaner than XAML or C++ Forms:
      
    app.button1=button(val('asdf'),click(dostuff),visible(False),addClass('asdf'),dataBind('val',&model.whatever))
    app.link1=a(val('click here'),attr('href',some_url),onclick( (e)=>
      console.log('click!'))

**Comment by falafflepotatoe** [comment]
what about something like this

    new component({
      'model' = onChange(EachKey({
          players2UI: assign('playersUIView', this.addIcon().addFont('large')),
          levels:  assign('levelListUIView', renderAsList),
          }),
      'model.state' = onChange(Compare({
          'titlemenu' = drawHomeScreen,
          'ingame'    = renderAt30FPS,
          'paused'    = pause
      }))
    })

cheers

**Comment by paldepind** [comment]
Now, this whole question is a bit vague so let me use that as an excuse for a bit of rambling ;)

Managing state is a killer feature of functional programming in general! If you use immutable data with pure functions state can't change at all! The input and output of functions is completely transparent. Testing and reasoning about functions becomes much easier.

But you _need_ to change state. Not all values are constant – some are _dynamic_. In the imperative world this fact is crudely expressed by mutating state. To quite the brilliant Conal Elliott:

> Conventional imperative programming captures these dynamic values only indirectly, through state and mutations. The complete history (past, present, future) has no first class representation

In the imperative world everything can be changed. State dependencies throughout the program can be very complex and lead code that is brittle (hard to change, easy to break). In the functional world we can however introduce a concept values that change over time in a restricted and controlled manner with FRP.

I believe a proper web application architecture should ensure the following things:

* It should be completely obvious _how_ state can be changed. I.e. what actions it is possible to perform.
* It should be easy to inspect the state. Both in it's current form and in it's past forms. This is achieved by having the entire state in a single big object (like in Om) and by having a time traveling debugger.
* The vast majority of code should consist of pure functions. Otherwise the above cannot be achieved.

[I'm currently working on implementing](https://github.com/paldepind/noname-functional-frontend-framework/) the [Elm architecture](https://github.com/evancz/elm-architecture-tutorial) in JavaScript with Ramda and [Flyd](https://github.com/paldepind/flyd). When using that architecture the entire application state is handled in a single reactive stream in a purely functional way. You then pass this stream through a render function that creates a virtual DOM tree based on the data and applies it to the real DOM as a side effect.

Since all data is in one stream you can log the entire application state to the console or serialize it to JSON for inspection or persistence. You can also store the entire history and do time travel for debugging purposes. _Every_ state change is triggered by an action from a single action stream in the code. _Every_ state change is applied by an `update` function. All functions are pure.

**Comment by benjycui** [comment]
IMHO, Ramda is to manipulate data, instead of UI. If you need a functional library to handle UI, you can try [Bacon](https://github.com/baconjs/bacon.js). @falafflepotatoe :-)

**Comment by falafflepotatoe** [comment]
@benjycui -- well i always have to manipulate my data when drawing a new ui view,so it comes in pretty handy when the state changes. i havent checked out bacon yet but i will, thanks :)

**Comment by bobiblazeski** [comment]
@falafflepotatoe Ramda is great for manipulating data, though for managing state in functional-ish style I recommend https://github.com/Reactive-Extensions/RxJS reactive library. The other option is aforementioned bacon. I'm near complete in porting meteor realtime todo application using Ramda, RxJS, Socket.io with RethinkDB as backened.  Ramda helps but RxJS is doing the heavy lifting in managing state.

**Comment by bobiblazeski** [comment]
@paldepind Your project seems very interesting, but forgive me for being very skeptical of people who suggest functional solution of stateful problems. Several times I read about such projects over promising and under delivering http://prog21.dadgum.com/54.html . How for example would you write my 3d carousel https://github.com/bobiblazeski/react-3d-carousel  without having state ?

**Comment by paldepind** [comment]
@bobiblazeski Being skeptical is good!

> without having state ?

Of course there is state. State is in the center of the architecture. It's how you manage the state that matters. I've implemented a [todo app](http://paldepind.github.io/noname-functional-frontend-framework/examples/todo/) ([source here](https://github.com/paldepind/noname-functional-frontend-framework/tree/master/examples/todo/js)) without any problems. You're carousel would not be an issue either. But it's a bit too big an example for me to implement it just to prove a point.

Programming in the twenty-first century is a splendid blog! And I believe the author has a valid point in his article. But the architecture I'm talking about still lives inside JavaScript so you can essentially do whatever you want. But the the todo application linked above is written with only three functions with side effects, one to read from localStorage, one to save to localStorage and one that does the rendering based on the state.

**Comment by CrossEye** [comment]
I'm really having a hard time understanding the idea here.

Ramda is meant to be a fairly low-level library.  I certainly have no desire to move it towards anything like an application framework.  Nor do I see it developing features that could make it compete with RxJs, Bacon, or the new entry from our own @paldepind, Flyd.  But I can't tell if that's what you meant, @falafflepotatoe, by managing state, or if you had something lower level than that.

Can you explain a little more what sort of API you're imagining from some Ramda functions?

**Comment by falafflepotatoe** [comment]
@CrossEye  yea - a lot of times in mvc you hate state based code, ill just give you an example for brevity:

    if (this.state == 0) renderHTML = ''; // nothing
    if (this.state == 1) renderHTML = 'welcome to game <br><br><br> press start'
    if (this.state == 2) renderHTML = 'level one, push enter to continue'
    if (this.state == 3 && keypushed == 13) life = 100; mp = 200; drawlvl1()

conveniently ramda passes funcs instead of values, so instead of callbacks or nested if loops you could do

   statemap({
     0:   Render,
     1:   R.partial(Render(loading_txt)),
     2:   R,partial(Render('level one, push enter to continue')),
     3:   CheckKey(13, 2 /*=value to set state on fail */, ResetChar(), DrawLvl1) // set state to 2 if fail (well pretend its a real param
    })
    // and later we can do
    Render(more_scene_data) // and finish the partial (if necessary)
    // also if we have a MVC framework with event emitter or ES7 we can maybe? listen to state, for instant reactive programming
    this.listenTo(this.state, change, handleState /*=ramda fn?)

Idk if its the right way but its definitely interesting me ATM.

**Comment by CrossEye** [comment]
@falafflepotatoe: It sounds as though you're not looking for any actual changes from Ramda for now.  There are features to help you do some of what you want.  (See [`cond`][co] for your `statemap`.)  And there are people putting together all sorts of interesting projects with this.  (See especially the recent work from @paldepind.)

So I'm closing this for now, without prejudice.  If you really have something specific you're looking for, I'm more than willing to reopen.



  [co]: http://ramdajs.com/docs/#cond

**Comment by falafflepotatoe** [comment]
@CrossEye 
yea i would have tagged it proposal but i dont know how

i only posted because i remembered one of the ramda authors or supporters saying when he wrote ramda he wasnt sure what it would be used for but he knew it would be useful. i kind of had that feeling about ramda also when coupled with reactive programming.

im not a ramda guy, but only because i havent had the time yet. great lib, cheers.

**Comment by tycho01** [comment]
Sorry for reviving this, just wanted to chime in.

I've been planning to do this, and it doesn't seem to require any change on the part of Ramda from what I can see.
So there have been quite some stage management libraries out there so far (Flux/Redux, not to mention versions of the RxJS-based Redux-Observable in the Angular and Vue worlds).

The point here isn't to have Ramda replace those libraries, but rather that the concepts just complement each other: as soon as you can get those libraries to take pointfree functions (e.g. have Redux-like reducer functions use say `state => state`, `param => state => state`, `(param, state) => state`, as opposed to having the state before the payload parameter), you can just plug in Ramda functions as-is.
I agree with the OP that seems like the most elegant way of managing state out there.
