### ISSUE TITLE
derive R.take and R.drop from R.slice

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1158]
`R.slice` works on strings as well as arrays, since we dispatch to a `slice` method if present:

```javascript
> R.slice(0, 3, [1, 2, 3, 4, 5])
[ 1, 2, 3 ]
> R.slice(0, 3, 'Ramda')
'Ram'
```

One can define `take` in terms of `slice`. If one does so `take` also works on strings:

```javascript
> var take = R.slice(0)
undefined
> take(3, [1, 2, 3, 4, 5])
[ 1, 2, 3 ]
> take(3, 'Ramda')
'Ram'
```

`drop` can be defined similarly:

```javascript
> var drop = R.slice(R.__, Infinity)
undefined
> drop(3, [1, 2, 3, 4, 5])
[ 4, 5 ]
> drop(3, 'Ramda')
'da'
```

`take` and `drop` are derivable from `slice`. I suggest we update the implementations of `R.take` and `R.drop` to use this approach. We could then deprecate `R.substringTo` and `R.substringFrom`.

**Comment by buzzdecafe** [comment]
hmmm. i like the idea of dropping string functions. OTOH i am afraid of creating the impression that we treat strings like `[char]`. 'cuz i don't want to fulfill that tacit promise.

**Comment by buzzdecafe** [comment]
and `take` and `drop` should be dispatchable, but that is just a note, i don't think that would block this idea.
