### ISSUE TITLE
decide whether to cache array lengths

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1165]
We currently mix these two styles:

```javascript
var idx = 0;
var len = xs.length;
while (idx < len) {
  ...
  idx += 1;
}
```

```javascript
var idx = 0;
while (idx < xs.length) {
  ...
  idx += 1;
}
```

Thanks to JIT compilation I imagine the performance is equivalent, in which case we should remove the manual length caching.

We should consistently apply our preferred style, whichever we decide that is.

**Comment by asaf-romano** [comment]
The second option doesn't assume immutability, for better or worse.

**Comment by paldepind** [comment]
I'm all for not caching array lengths! A modern optimizer does it automatically: [How the Grinch stole array.length access ](http://mrale.ph/blog/2014/12/24/array-length-caching.html)

**Comment by CrossEye** [comment]
I'm for not caching it either.  I'm probably pretty guilty here.  I've had years of doing it, and I still work in environments (DOM collections) where it's important.  But so long as the bounds we're checking is a simply property access and not a function call on each iteration, let's consistently let the compiler do this optimization.

**Comment by buzzdecafe** [comment]
yep. let's ditch the cargo-cult length caching.

**Comment by megawac** [comment]
> The second option doesn't assume immutability, for better or worse.

I think this is **very** dangerous and merits array length caching. It could potentially break ramda use with third party libraries and pretty much any code that follows different philosophy. For instance, this may now be an infinite loop if `someExternalFunction` does something dubious with the `arr`.

```js
R.each(someExternalFunction, arr)
```

:-1: for this change

![](http://www.nevadaday.com/images/smokey-grand-marshal.jpg)

**Comment by paldepind** [comment]
@megawac I can see your point. But not caching the array length can also provide better safety. If the function shortens the array it will assure that we do not in any case access the array out of bounds.

> any code that follows different philosophy"

Is there any coding philosophy where modifying and array while looping over it isn't a total no go?

`Array.prototype.map` doesn't cache arrays lengths either:

```javascript
[1,2,3,4,5].map(function(n, idx, list) {
  // called 3 times, not 5
  list.shift();
})
```

**Comment by megawac** [comment]
Can think of some parsing and regeneration algorithms that loop and modify.
Its more commonly indicative of a bug however and its probably better to
use original length than loop to inf.

Also array.prototype.map does cache length (consider the same snippet with
push), it just skips sparse indexes. Its easy to miss that difference ;)

**Comment by paldepind** [comment]
Oh, yes. Spare arrays. That explains it indeed!

I agree with @megawac. Safety is worth more than the code simplification.

**Comment by buzzdecafe** [comment]
i also agree. but where were you a week ago???

**Comment by megawac** [comment]
Haha /cc me if you want comments :p I'm not always trolling GitHub

**Comment by CrossEye** [comment]
Yup, looks like we got it wrong.
