### ISSUE TITLE
R.evolve where transformation only applies to keys that exist in object?

### ISSUE THREAD

**Issue by peter** [ramda/ramda#1171]
Hi!
I found myself needing an evolve function that only applies transformations to the keys that exist in an object. Something like this:

var evolve = function(transformations, object) {
  return R.evolve(
    R.pick(R.keys(object), transformations),
    object);
};

Is that something that would make sense in Ramda or is it something that I should roll myself?

Example:

R.evolve({foo: R.add(2)}, {}) => { foo: NaN }

evolve({foo: R.add(2)}, {}) => {}

**Comment by paldepind** [comment]
That is a good idea! `evolve` has actually already been changed to exactly the behavior you request. See #1141.

This will be included in 0.15.

**Comment by peter** [comment]
@paldepind awesome job, thanks!

**Comment by paldepind** [comment]
You're welcome! 0.15 is not far away.
