### ISSUE TITLE
ramda-maybe

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#1177]
Hello.

I just created [ramda-maybe](https://github.com/TheLudd/ramda-maybe) (wrapping all Ramda functions that may return undefined in a Maybe). I'd be glad to get some feedback on the idea and if there is any interest from the ramda organization on github in adopting it.

**Comment by CrossEye** [comment]
I've so far been mostly intetested in the work [Sanctuary][sa] has been doing along these lines. It would be interesting to have another project doing that, but there's likely to be a lot of duplicated effort.

It's not something I've felt like folding into Ramda itself.  I feel as though that's perhaps too much Kool-Aid to expect Javascript developers to drink.   



  [sa]: https://github.com/plaid/sanctuary

**Comment by TheLudd** [comment]
Well, this is just 29 LOC with one word added for every new function that might return undefined. 

I am not at all suggesting that this should be the official ramda, it is just a wrapper usable by anyone who wants to go down this path.

**Comment by paldepind** [comment]
I think this has value. It really is something different since it is just the exact same API that Ramda has.

**Comment by buzzdecafe** [comment]
i also like the idea of a thin layer of "type safety" like this.

**Comment by TheLudd** [comment]
FYI. I released version 0.0.1 but I plan on releasing versions ~ 0.10.0, 0.11.0 and up to the current that all depend on the corresponding ramda version. Like I said, consider if you want to make this a child of the ramda organization but there is no hurry...

**Comment by CrossEye** [comment]
I'm on my mobile, so I haven't looked carefully yet.   I will soon. 

@paldepind: it is definitely not the same APi as Ramda if you're changing return values. 

@TheLudd: I could definitely see adopting something like this within the Ramda community.  I'm betting we'll find more functions that can return `undefined` though.   Did you consider `reduce`?

**Comment by TheLudd** [comment]
@CrossEye Well, a lot of functions could be *made* to return undefined. Like 
```
defaultTo(undefined, null)
```
But I think the case for `Maybe` is related to the functions mentioned in #1176 where special conditions of the input data may cause it to return `undefined`. 

Another example is `always` where the signature will hold even if you pass in `undefined` so I don't think that one needs to be wrapped.

**Comment by buzzdecafe** [comment]
> Like I said, consider if you want to make this a child of the ramda organization but there is no hurry...

sounds good to me. do you wanna transfer to ramda org? lmk if you need my help

**Comment by paldepind** [comment]
> it is definitely not the same APi as Ramda if you're changing return values. 

I meant the same API except the change in return values for selected functions. Everything else is the same.

**Comment by buzzdecafe** [comment]
but that change is a BFD:

```js
//currently:
map(f, find(g, [])) //=> throw

// with maybe
map(f, find(g), []) //=> Nothing
```

**Comment by TheLudd** [comment]
Migrating from one mode to another in an existing system will surely not be a trivial task. I think @paldepind is just saying that it will be a familiar library. Right?

**Comment by paldepind** [comment]
Yes, excactly. I did not mean to imply that one could swap one with the other. But almost all ones knowledge of Ramdas API transfers between the two.

**Comment by CrossEye** [comment]
> but that change is a BFD:
> 
> ```js
> //currently:
> map(f, find(g, [])) //=> throw
> 
> // with maybe
> map(f, find(g, [])) //=> Nothing
> ```

Right.  But there's another side too:

// currently
add(42, head([1, 2, 3]); //=> 43

// with maybe
add(42, head([1, 2, 3]); //=> "42Maybe.Just(1)"

// it would take something like this to get (somewhat) similar behavior:
R.head([1, 2, 3]).map(R.add(42)) //=> Just(43)

**Comment by TheLudd** [comment]
@CrossEye 
Yes, that is the style one needs to approach.
The coding style is *quite* different. And it affects all the code everywhere. I really want this in my project but it is going to take a while to get there. But the undefined reference bug I had this week was the straw that broke the camels back for me :)

**Comment by TheLudd** [comment]
> That's why I think there is a bigger API change than it might seem at first

The API change is small IMHO but the effects are huge.

**Comment by CrossEye** [comment]
> The API change is small IMHO but the effects are huge.

That's probably a good way to put it.  Did you investigate Sanctuary?  I have only poked around at it, but it looks really well done.

**Comment by davidchambers** [comment]
By the time a Ramda function returns null/undefined information may already have been lost. It's thus not possible in certain cases to implement a safe version of a function in terms of its Ramda equivalent.

```javascript
> R.find(R.T, [null])           > S.find(R.T, [null])
Nothing()                       Just(null)

> R.head([null])                > S.head([null])
Nothing()                       Just(null)

> R.last([null])                > S.last([null])
Nothing()                       Just(null)

> R.nth(0, [null])              > S.at(0, [null])
Nothing()                       Just(null)

> R.prop('x', {x: null})        > S.get('x', {x: null})
Nothing()                       Just(null)
```

I won't argue for the usefulness of the Sanctuary approach, but I will argue for its correctness. These Sanctuary functions are easy to document, because the way they behave is so clearly defined. Take [`S.head`][1], for example:

> #### `head :: [a] -> Maybe a`
>
> Takes a list and returns Just the first element of the list if the list contains at least one element; Nothing if the list is empty.

Documenting ramda-fantasy's `head` function is not straightforward, as one must explain the handling of null/undefined.


[1]: https://github.com/plaid/sanctuary#head

**Comment by buzzdecafe** [comment]
> Documenting ramda-fantasy's head function 

you must mean ramda-maybe?

**Comment by davidchambers** [comment]
Quite right, @buzzdecafe. I've fixed the typo.
