### ISSUE TITLE
curried functions ignore placeholders given enough non-placeholder args

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1178]
``` node
var f = R.curry(function(a, b, c) { return [a, b, c]; });

f(1, 2, 3, 4);
// => [1, 2, 3]

f(R.__, 2, 3)(1);
// => [1, 2, 3]

f(R.__, 2, 3, 4);
// => [{'@@functional/placeholder': true}, 2, 3]

f(R.__, R.__, 3, 4)(1, 2);
// => [1, 2, 3]

f(R.__, R.__, 3, 4, 5);
// => [{'@@functional/placeholder': true}, {'@@functional/placeholder': true}, 3]
```

I suggest we wait until #1155 is merged before fixing this, to avoid merge conflicts. In the interim, though, we can (hopefully) agree on the desired behaviour. I propose ignoring superfluous arguments in the presence of one or more placeholders. What do others think is desirable behaviour?

**Comment by paldepind** [comment]
Yes. This is ugly. I bet solving it is going to be ugly as well. And this is only a problem because we want our curry to support variadic functions.

To be honest I'm not even sure we should solve it. I think @CrossEye said that behavior when passing extra arguments to curried functions is unspecified (our curry rules don't hold in that case either).

**Comment by davidchambers** [comment]
Whatever we decide should not involve passing the placeholder value to the function! Better to either:

  - ignore superfluous arguments; or
  - throw.

**Comment by buzzdecafe** [comment]
there is a third option, no? viz. match extra arguments in left-to-right order for each placeholder, and then pass any *remaining* arguments in. that ought to be consistent with expect behavior, i think, and you don't destroy any info.

**Comment by buzzdecafe** [comment]
that would make a case like:

`f(R.__, R.__, 3, 4, 5); //=> [4, 5, 3]

**Comment by davidchambers** [comment]
That's a third option, yes.

**Comment by CrossEye** [comment]
@buzzdecafe's approach sounds like a good one, but still not the most obvious thing.

Especially when it seems to also imply

    f(R.__, R.__, 3, 4); //=> (b -> [4, b, 3])

Hmm, this is ugly.  I'm starting to join @buzzdecafe's distaste for these things.

**Comment by buzzdecafe** [comment]
yes, it would imply that. and yes, i am not thrilled with generalized placeholders, because of the amount of complexity they are baking into fundamental operations of the lib. to my mind they don't give you much you can't get with `flip`. the cost exceeds the benefit.

**Comment by davidchambers** [comment]
> This is ugly. I bet solving it is going to be ugly as well. And this is only a problem because we want our curry to support variadic functions.

We could revisit #1139. It solves this problem by disallowing superfluous arguments in `R.curry`.

**Comment by paldepind** [comment]
@buzzdecafe I don't see that complexity? Dealing with them in `curryN` is not too tricky. There's a bit more going on in the "manual" internal curry function but it doesn't look too bad either?

> We could revisit #1139. It solves this problem by disallowing superfluous arguments in R.curry.

But in a way it actually makes it worse. Currently the fact that you can supply extra arguments to a curried function is an undocumented secret. I.e. this error currently occurs when using functions in a way that is unspecified. With `R.currryMinMax` this error would still happen if you had done `R.curryMinMax(3, 6)`. And then it would happen inside our documented API.

**Comment by buzzdecafe** [comment]
> I don't see that complexity?

Placeholder:

```js
function _curry3(fn) {
  return function f3(a, b, c) {
    var n = arguments.length;
    if (n === 0) {
      return f3;
    } else if (n === 1 && a != null && a['@@functional/placeholder'] === true) {
      return f3;
    } else if (n === 1) {
      return _curry2(function(b, c) { return fn(a, b, c); });
    } else if (n === 2 && a != null && a['@@functional/placeholder'] === true &&
                          b != null && b['@@functional/placeholder'] === true) {
      return f3;
    } else if (n === 2 && a != null && a['@@functional/placeholder'] === true) {
      return _curry2(function(a, c) { return fn(a, b, c); });
    } else if (n === 2 && b != null && b['@@functional/placeholder'] === true) {
      return _curry2(function(b, c) { return fn(a, b, c); });
    } else if (n === 2) {
      return _curry1(function(c) { return fn(a, b, c); });
    } else if (n === 3 && a != null && a['@@functional/placeholder'] === true &&
                          b != null && b['@@functional/placeholder'] === true &&
                          c != null && c['@@functional/placeholder'] === true) {
      return f3;
    } else if (n === 3 && a != null && a['@@functional/placeholder'] === true &&
                          b != null && b['@@functional/placeholder'] === true) {
      return _curry2(function(a, b) { return fn(a, b, c); });
    } else if (n === 3 && a != null && a['@@functional/placeholder'] === true &&
                          c != null && c['@@functional/placeholder'] === true) {
      return _curry2(function(a, c) { return fn(a, b, c); });
    } else if (n === 3 && b != null && b['@@functional/placeholder'] === true &&
                          c != null && c['@@functional/placeholder'] === true) {
      return _curry2(function(b, c) { return fn(a, b, c); });
    } else if (n === 3 && a != null && a['@@functional/placeholder'] === true) {
      return _curry1(function(a) { return fn(a, b, c); });
    } else if (n === 3 && b != null && b['@@functional/placeholder'] === true) {
      return _curry1(function(b) { return fn(a, b, c); });
    } else if (n === 3 && c != null && c['@@functional/placeholder'] === true) {
      return _curry1(function(c) { return fn(a, b, c); });
    } else {
      return fn(a, b, c);
    }
  };
};
```

No Placeholder:

```js
function _curry3(fn) {
  return function f3(a, b, c) {
    var n = arguments.length;
    if (n === 0) {
      throw _noArgsException();
    } else if (n === 1) {
      return _curry2(function(b, c) { return fn(a, b, c); });
    } else if (n === 2) {
      return function(c) { return fn(a, b, c); };
    } else {
      return fn(a, b, c);
    }
  };
};
```

QED

**Comment by buzzdecafe** [comment]
let's circle back to this after #1843 ; that pr may make this moot
