### ISSUE TITLE
xScan

### ISSUE THREAD

**Issue by jethrolarson** [ramda/ramda#1179]
Right now R.scan does not transduce. It should do so for consistency. Scan is much more commonly used for streams so it's also important for compatibility with stream libraries like flyd.

**Comment by buzzdecafe** [comment]
yes, it absolutely should. :+1:

**Comment by jasonhansel** [comment]
:+1:

**Comment by CrossEye** [comment]
@jethrolarson: Do I hear a PR coming our way? :smile:

**Comment by jethrolarson** [comment]
Not this week. I'm too behind on everything but rest.

**Comment by jethrolarson** [comment]
I'll give this a shot.

**Comment by buzzdecafe** [comment]
:tada:

**Comment by jethrolarson** [comment]
Reduce itself doesn't use dispatchable which is kind of perplexing. Is reduce not a valid transformer?

**Comment by jethrolarson** [comment]
I think reduce and thus scan isn't a valid transformer, so making it transduce might not be correct. Anyone disagree?

**Comment by jethrolarson** [comment]
The above PR makes scan dispatch but doesn't use _dispatchable since that requires a transducer function.
