### ISSUE TITLE
R.uniq bug with Set

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#1188]
At the risk of being labeled [a concern troll](https://github.com/ramda/ramda/pull/907#issuecomment-111716832) I found that enviros w/o `Set`, e.g. IE 10 or Node 0.10:
```js
R.uniq([[1],[1]])
// => [[1]]
```

While enviros w/ `Set`, e.g. IE 11 or Node 0.12:
```js
R.uniq([[1],[1]])
// => [[1],[1]]
```

**Comment by benjycui** [comment]
I think this is the reason #1142, for `[1] === [1]` return false.

**Comment by davidchambers** [comment]
Thank you, @jdalton!

> I think this is the reason #1142, for `[1] === [1]` return false.

Yes. I don't see how we can use Set given our different definition of equality. Unless @scott-christopher or someone else has a solution, let's revert #1142 and publish v0.15.1.

**Comment by scott-christopher** [comment]
+1 to reverting the `Set` implementation. If it really is desirable to make use of Set, we can investigate an alternative solution.

**Comment by CrossEye** [comment]
:+1:

**Comment by asaf-romano** [comment]
Hrm, how did this happen? Array.from(new Set([1, 1])) is always [1] afaik. Was this caused by the hybird implementation somehow?

**Comment by asaf-romano** [comment]
Ah, arrays-of. nvm.

**Comment by benjycui** [comment]
@asaf-romano in most cases, the value equality is based on the same algorithm as `===`.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality
