### ISSUE TITLE
callback args normalization

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#1193]
Not sure if this has been brought up so I figure I'd check. With dispatching I think there may be a consistency note to consider for the callback args passed. For example `R.forEach` of a set object will provide `value, value, setObj`, for a map object its `value, keyValue, mapObj`. For things like `R.map` and a jQuery collection it'll call `$.fn.map` which is `index, element`, and so on.

Are you all cool with that or is there plans to normalize it?

**Comment by CrossEye** [comment]
I just responded to a [related issue][ss].  I would love to hear some suggestions as to how we might be able to normalize these calls.  But I'm not particularly hopeful.

I'm more concerned with with being able to dispatch to compatible functions, and dealing with aliasing issues to make that happen, than I am with figuring out a way to coordinate  with incompatible functions.  But if we could manage to do that as well, all the better.

Any ideas?


  [ss]: https://github.com/ramda/ramda/pull/1173#issuecomment-112234357

**Comment by jdalton** [comment]
>  I would love to hear some suggestions as to how we might be able to normalize these calls. But I'm not particularly hopeful.

If going down the dispatch branch then wrap to force the callback's arity.

**Comment by CrossEye** [comment]
> One way could be if going down the dispatch branch then wrap to enforce the callback's arity.

Ok, but I feel that arity is the least of our problems.  Remember that since Ramda is no longer in charge of actually applying the callback function, we don't even know what arity is actually to be expected of a callback function.  So the biggest problem, I think would not be the signature of the callback function, but of the dispatched functions themselves.  For instance, Ramda's `reduce` takes `callback`, `accumulator`, then `list`.  If someone calls it with a non-list that has a `reduce` function, we will call that function with `callback`, `accumulator`.  If their signature is different, I think we're probably hosed.  On the other hand, I don't really have a problem simply saying, "Then don't do that."  The dispatching will only work with that signature.   But the details of how the callback is handled will actually not matter, since the dispatched-to method of the object gets to handle those itself.

Or am I confused somehow?  It's certainly been known to happen.

**Comment by jdalton** [comment]
So is that a "We're cool with it"?

**Comment by CrossEye** [comment]
I'd rather it wasn't, but I don't see much in the way of options.

I am much more concerned with being able to, for instance, dispatch `fold` to `reduce` to than I am about what happens if someone tries to dispatch `R.reduce` to something that doesn't match.

**Comment by jdalton** [comment]
>  than I am about what happens if someone tries to dispatch R.reduce to something that doesn't match.

Was asking less about what doesn't match and more about varying callback signatures.

**Comment by CrossEye** [comment]
I guess I'm not sure what you would expect to work and not to work.

The [following][re] seems to work fine:

```js
    var m = new Map([['key1', 'value1'], ['key2', 'value2'], ['key3', 'value3']]);
    var mapResults = []
    R.forEach((v, k) => mapResults.push(k + ' has value ' + v), m);
    mapResults; //=> ["key1 has value value1", "key2 has value value2", "key3 has value value3"]

    var s = new Set(['alpha', 'beta', 'delta']);
    var setResults = [];
    R.forEach((v, k) => setResults.push('set contains ' + v), s);
    setResults; //=> ["set contains alpha", "set contains beta", "set contains delta"]
```

So you can iterate `Set` and `Map` instances with a dispatched `forEach` without any real issues.  I don't have a handy environment with both Ramda and jQuery so I can't demonstrate that one, but I don't see any reason why you wouldn't be able to do 

```js
   R.map((idx, elt) => elt.href, $('a'))
```

(This hasn't been tested, and it might actually not work.  jQuery collections might be close enough to arrays that we treat them as lists, and run them through our internal `map` function.  I'd have to check to be sure.)

But I think we can reasonably dispatch many different types.

Perhaps the concern is that we can't pass the same callback to various types and expect it to work.  That's quite true, but it does not concern me particularly.  We are not trying to unify various types in any strong sense.  A`Tree` is different from a `List`, which is different from a `Maybe` or from an `Either`.  That we can achieve some sort of commonality is important, not that we expect the same exact callback functions to work on each.

Does this make sense?


  [re]: http://bit.ly/1IZXHWc

**Comment by jdalton** [comment]
> The following seems to work fine:

I didn't say they didn't. I showed that the callbacks are provided different arguments and asked if that was by design (you're cool with it) or if there was a plan to normalize it.

I think you've answered my question.

**Comment by buzzdecafe** [comment]
this conversation is continuing in #1173. I am with @paldepind that we should not be dispatching to arbitrary objects, only those that we know (somehow, tbd) are "lawful".

>  I showed that the callbacks are provided different arguments and asked if that was by design (you're cool with it) or if there was a plan to normalize it.

this is a useful observation. I lean to having a thin layer to normalize these functions, and ensure their compliance, much as we do with list functions.

**Comment by CrossEye** [comment]
I'm not even sure what such normalization would mean.

Is there a suggestion that no matter what type it's called on, when `forEach` is called, we should be able to supply the exact same callback function?  If so, then I think we should give up on dispatch right now.  `Maps` are not `Sets`, and neither of them is a `Maybe`, and there are sure to be types we know nothing about.  But the point is that Ramda does not supply the callback function.  The same user who's supplying the object of a certain type is also giving us the callback function, so I am personally not worried about a mismatch.  _Caveat emptor_.

**Comment by jdalton** [comment]
Moving to #1173.
