### ISSUE TITLE
R.isEmpty({}) returns false

### ISSUE THREAD

**Issue by xorcus** [ramda/ramda#1194]
```
R.isEmpty('') returns true,
R.isEmpty([]) returns true
```

but

`R.isEmpty({}) returns false`

=> If an object is observed as a collection of (enumerable) properties, this can be considered inconsistent. If `Object.keys({})` returns `[]`, it may make sense to consider the object as empty

**Comment by buzzdecafe** [comment]
>  If an object is observed as a collection of (enumerable) properties, this can be considered inconsistent. 

That's a pretty big "if". I note that the documentation says:

>  Reports whether the **list** has zero elements.

(emphasis added)

And:

```js
/* ...
 * @example
 *
 *      R.isEmpty([1, 2, 3]); //=> false
 *      R.isEmpty([]); //=> true
 *      R.isEmpty(''); //=> true
 *      R.isEmpty(null); //=> false
...*/
```

So one can work with plain objects by `isEmpty(keys({}))` which transforms the object to a list. That said, it *does* feel pretty natural to expect `isEmpty({})` to be `true`. Curious for other opinions.

**Comment by xorcus** [comment]
I understand and can agree with the reasoning that isEmpty operates on **lists**. Probably an example should clarify the use case, as you mentioned:
`
 R.isEmpty({}); //=> false
 R.isEmpty(R.keys({})); //=> true
`

**Comment by CrossEye** [comment]
> I understand and can agree with the reasoning that `isEmpty` operates on **lists**. Probably an example should clarify the use case, as you mentioned:

:+1:

**Comment by CrossEye** [comment]
I'm definitely not in favor of changing the function to handle the empty object type as well.  This is simply part of our `List` API.

**Comment by davidchambers** [comment]
We discussed the possibility of changing the behaviour of `R.isEmpty({})` in #539.

Let's add the two examples @xorcus suggested.
