### ISSUE TITLE
function equivalent of "do" notation

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1197]
This idea is being discussed in plaid/sanctuary#53. I won't duplicate the proposal, but I will open a Ramda pull request if we decide Ramda should provide this function.

@buzzdecafe is eager to *reduce* the number of composition functions, so may not want to add this one, though @joneshf has intimated that this behaviour could be provided by a more general `R.compose`.

**Comment by CrossEye** [comment]
Somehow I missed this one when it was first posted.  I find this one quite important.  I don't quite see how this would reduce our `compose`s, but I wouldn't be too surprised.

At the moment, a cautious :+1:, although I don't really like the name `$do`.

**Comment by davidchambers** [comment]
I don't like the name `$do` either. `R.composeK` and `R.pipeK` sound right to me (K is for [Kleisli][1]).

The rule should be that one is allowed to add a new composition function to Ramda only if one first removes one of the existing ones. ;)


[1]: https://en.wikipedia.org/wiki/Kleisli_category

**Comment by CrossEye** [comment]
I think @buzzdecafe might phrase it a little more briefly:  "One is not allowed to add a new composition function to Ramda."

:smiling_imp:

**Comment by scott-christopher** [comment]
Perhaps if it went by the name `chainAll`, it could go unnoticed as Yet Another Composition Function™?

**Comment by jethrolarson** [comment]
+1 for chainAll. I think composeK just gives the user extra research homework
