### ISSUE TITLE
uniqIdentical, unionIdentical?

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1198]
This is an alternative suggestion to the uniq-on-set API I proposed some time ago, and that @scott-christopher bravely tried to implement without breaking dispatching... and that is now backed out because it doesn't play well with the new equals and identical semantics.

I prpose to add uniqIdentical, and/or to optimize uniqWith(identical), and also add corresponding union API. When working with very large data collections the performance hit of "full-scan" equality check in uniq, when it's not necessary, is too much to bear IMO.

**Comment by CrossEye** [comment]
Without links to the various issues or source code, I'm left to my own (very unreliable, these days) memory.  Is this just too ill-performant?:

    uniqWith((a, b) = > a === b)

**Comment by scott-christopher** [comment]
I would be hesitant to see additional functions added for the sole purpose of improving performance.

You can however achieve what you're after with something like the following:
```js
var uniqIdentical = R.compose(Array.from, R.invoker(0, 'values'), R.constructN(1, Set));
var unionIdentical = R.compose(uniqIdentical, R.concat);

uniqIdentical([0, 1, 2, 3, 2, 1, 0]); // [0, 1, 2, 3]
unionIdentical([0,1,2,3], [0,2,4,6]); // [0, 1, 2, 3, 4, 6]
```

**Comment by asaf-romano** [comment]
@scott-christopher How about, rather than introducing new functions, just optimizing uniqWith(identical) and unionWith(identical)? It's just that the performance gain is huge to be dismissed, and the Set trick is by no means "common knowledge" in the js community afaict.

**Comment by asaf-romano** [comment]
@CrossEye I was referring to my now-obsolete uniq-on-Set proposal. It went like this: (1) my naive version was broken by the need to dispatch eq; (2) @scott-christopher implement a hybird solution; (3) ramda switched to value-equality across the board, rendering any Set-based implementation for the default uniq function (i.e uniqWith(equals)) invalid.

**Comment by scott-christopher** [comment]
>How about, rather than introducing new functions, just optimizing `uniqWith(identical)` and `unionWith(identical)`?

There are still edge cases like:
```js
R.identical(0, -0); // false
Array.from(new Set([0, -0])); // [0]
```

Perhaps a comment could be added to the docs of `uniq` and `union`, or in the cookbook to suggest the alternative `R.compose(Array.from, R.constructN(1, Set))` for large lists or when performance is a concern?

**Comment by asaf-romano** [comment]
Lord knows why they used different equality algos for new technologies added roughly at the same time (Set, Object.is). This indeed makes it a no-go (unless R.identical is changed to old times === equality, which seems to be what Set does).

Regarding cookbooks, the conservative thing to do is to assume people don't reach them unless they must, and if uniq is going to work, but slowly, the assumption will be that it's just JS being slow and there's not much to do.

**Comment by paldepind** [comment]
> Regarding cookbooks, the conservative thing to do is to assume people don't reach them unless they must, and if uniq is going to work, but slowly, the assumption will be that it's just JS being slow and there's not much to do.

If that is the only problem then the API documentation could refer to the cookbook.

**Comment by davidchambers** [comment]
I'm strongly opposed to this idea. Sorry, @asaf-romano!
