### ISSUE TITLE
R.takeLast and R.dropLast

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1200]
@asaf-romano and I formulated this idea on Gitter:

```javascript
             [ 1 , 2 , 3 , 4 , 5 , 6 , 7 ]

       head    1
       tail      [ 2 , 3 , 4 , 5 , 6 , 7 ]
       last                            7
       init  [ 1 , 2 , 3 , 4 , 5 , 6 ]
    take(2)  [ 1 , 2 ]
    drop(2)          [ 3 , 4 , 5 , 6 , 7 ]

takeLast(2)                      [ 6 , 7 ]
dropLast(2)  [ 1 , 2 , 3 , 4 , 5 ]
```

These last two functions seem useful. Currently one must use the rather ugly `R.slice(-2, Infinity)`; `R.takeLast(2)` would be nicer.

**Comment by asaf-romano** [comment]
See also https://github.com/ramda/ramda/pull/1159#issuecomment-113057473

**Comment by paldepind** [comment]
To me these functions looks very consistent with our existing offerings and they seems to fill a very sensible gap :+1:

**Comment by buzzdecafe** [comment]
> Currently one must use the rather ugly `R.slice(-2, Infinity)` 

```js
takeLast(n) <=> drop(ls.length - n)
dropLast(n) <=> take(ls.length - n)
```

**Comment by CrossEye** [comment]
While I don't have any major objection, I want to note that I would think of `last`, and `init`, as well as the new `takeLast` and `dropLast` as much less important members of the Ramda API than `head`, `tail`, `take`, and `drop`.  This latter group make sense on _lists_ and not only on array-like structures.  They also work for streams, and other infinite or lazy structures.  Their counterparts are there only to fill some sense of symmetry, and because when we have arrays, these are nicer than having to compose `reverse` with the core functions.  But let's keep sight of the fact that they are always somewhat secondary.

**Comment by asaf-romano** [comment]
Looking at other APIS, I think the names should be dropRight, and takeRight.

If there are no objection to the inclusion of these APIs, I'll happily PR them.

**Comment by buzzdecafe** [comment]
pretty much agree with @CrossEye . These functions only make sense where you know the list has a length. in that case you can make 'em work with existing functions as shown above.

**Comment by davidchambers** [comment]
> > Currently one must use the rather ugly `R.slice(-2, Infinity)`
>
> ```javascript
> takeLast(n) <=> drop(ls.length - n)
> dropLast(n) <=> take(ls.length - n)
> ```

Sure, but in a pipeline it's nice to avoid functions which require `R.converge`.

```javascript
// @buzzdecafe's approach using existing technology:
R.converge(R.drop,
           R.pipe(R.length, R.add(-2)),
           R.identity)

// @davidchambers's approach using existing technology:
R.slice(-2, Infinity)

// Proposed technology:
R.takeLast(2)
```

> Looking at other functions (e.g. reduce vs. reduceRight), I think the names should be dropRight, and takeRight.

That was my first thought, but I then realized this suggests right-to-left ordering.

**Comment by paldepind** [comment]
> Looking at other functions (e.g. reduce vs. reduceRight), I think the names should be dropRight, and takeRight.

On the other hand `takeLast` and `dropLast` are consistent with `last`. And they're much closer related to `last`.

**Comment by CrossEye** [comment]
@asaf-romano:

I think this would be fine for a PR.  I'd argue that the names are better as `xxxLast`.  This is partly for the same reason that @paldepind gave and also because `reduceRight` and `mapAccumRight` have to do with the order of processing than with the position of data.

**Comment by megawac** [comment]
> Looking at other functions (e.g. reduce vs. reduceRight), I think the names should be dropRight, and takeRight.

:+1: to PR and these names

**Comment by CrossEye** [comment]
@davidchambers:

> Sure, but in a pipeline it's nice to avoid functions which require R.converge.

The suggestion from @buzzdecafe fits fine into a pipeline reasonably well without `converge`, especially with ES6 syntax becoming ubiquitous:

    (n, ls) => drop(ls.length - n)

I think sometimes we focus too much on making everything points-free.  I'm certainly as guilty of it as anyone; after all, that's the reason for the existence of my good friends `useWith` and `converge`.  But we really should consider simple lambas when appropriate.

**Comment by davidchambers** [comment]
In `R.drop(ls.length - n, ls)` I see `ls` in both of the expressions which form the arguments to `R.drop`. To me this suggests a possible abstraction.

I don't see any reasonable grounds on which we could reject a pull request to add these functions. The implementations would not be complex. These functions fit well with existing Ramda functions: they would complete a family, in fact. Ramda has several functions which are partially applied forms of other Ramda functions. These exist because they are convenient and/or more expressive. The lambda argument could equally be applied to these convenience functions. To reject `takeLast` and `dropLast` would be inconsistent with the precedent set by `inc`, `dec`, `unary`, `binary`, and others.

**Comment by megawac** [comment]
Could alternatively support negative indicies on drop and take

**Comment by asaf-romano** [comment]
The problem with:
```
(n, ls) => R.drop(ls.length - n)
```
isn't that it's a lamda (not for me anyway), but that it's simply not how you think of what you're trying to do. I want to take the last 5 elements, not to drop all the elements before the last 5 elements.

**Comment by CrossEye** [comment]
> The problem with:
> ```
> (n, ls) => R.drop(ls.length - n)
> ```
> isn't that it's a lamda

I wasn't seriously suggesting that someone use this.  This was simply a response to @davidchambers syntax comparison.  

I already expressed my support for a PR on these.  I don't think of them as highly important, but they're reasonable, and certainly understandable, with either `xxxLast` or `xxxRight` names.

**Comment by asaf-romano** [comment]
So, meanwhile, in my own code, I also had to add take/dropWhileLast...

**Comment by CrossEye** [comment]
Is anyone doing a PR on this?

**Comment by asaf-romano** [comment]
I can. Are take/dropLastpWhile on the table too?

**Comment by asaf-romano** [comment]
Anyway, PR for the first two (takeLast, dropLast) sometime this weekend.

**Comment by CrossEye** [comment]
> I can. Are take/dropLastpWhile on the table too?

Might as well.
