### ISSUE TITLE
Example for mapObjIndexed is insufficient

### ISSUE THREAD

**Issue by kwijibo** [ramda/ramda#1219]
The docs say:
> Like mapObj, but but passes additional arguments to the predicate function. The predicate function is > passed three arguments: (value, key, obj).

But the example makes no use of this 3rd key, so is not as helpful as it could be in showing where mapObjIndexed could be useful

```
var values = { x: 1, y: 2, z: 3 };
var prependKeyAndDouble = function(num, key, obj) {
  return key + (num * 2);
};
R.mapObjIndexed(prependKeyAndDouble, values); //=> { x: 'x2', y: 'y4', z: 'z6' }
```

**Comment by buzzdecafe** [comment]
you are right. Do you have an example in mind? I would be happy to take a PR that fixes inadequate docs.

**Comment by kwijibo** [comment]
I can't think of a good example. Presumably where you want to do something with another key (or keys) in the object... but then you probably need to wrap it up in an `if(key!==specificKey)` ?

**Comment by buzzdecafe** [comment]
idk, i don't have much call to use the indexed functions. But I certainly agree we should illustrate its full potential.

**Comment by asaf-romano** [comment]
Isn't it deprecated anyway?

**Comment by CrossEye** [comment]
No, we deprecated all the list-based `xxxIndexed` ones with common code.  But no one has bothered even trying to do the same for this one remaining function with a similar name but not a close enough API to be factored in the same way.

**Comment by davidchambers** [comment]
I don't think it's possible to write a simple, useful example where the third argument is useful. We'll gladly accept a pull request is anyone can prove me wrong. :)

**Comment by Craken420** [comment]
At use this function for first time, i was little confused but tried with this

` const xyz = { x: 1, y: 2, z: 3 } `

`const shows = (param1, param2, param3, param4) => {`
 ` console.log('param1: ',param1,'\nparam2: ',param2, '\nparam3: ',param3, '\nparam4: ',param4)`
`    return param1 + 2`
`}`

`const mapObj = (fn, obj) => R.mapObjIndexed(fn, obj) `

`console.log(mapObj(shows, xyz)) `

> //=>
param1:  1
param2:  x
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  2
param2:  y
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  3
param2:  z
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
{ x: 3, y: 4, z: 5 }

As you can see, I make a function called mapObj and receive like arguments a function and object to which the function will be applied, as I did not know what it recieves as parameters in the function, I introduced random parameters to see that it is what I recieve, which when printed I could translate it in the following way

`const xyz = { x: 1, y: 2, z: 3 }`
`R.mapObjIndexed((value, key, obj) => value + 2, obj)`

Or

`const addTwo = (value, key, obj) => value +2`
`console.log(R.mapObjIndexed(addTwo, obj))`

understanding this was very helpful for me and a great step to use this good function of ramda, and what better than to help understand what I already understood

**Comment by Craken420** [comment]
At use this function for first time, i was little confused but tried with this

` const xyz = { x: 1, y: 2, z: 3 } `

`const shows = (param1, param2, param3, param4) => {`
 ` console.log('param1: ',param1,'\nparam2: ',param2, '\nparam3: ',param3, '\nparam4: ',param4)`
`    return param1 + 2`
`}`

`const mapObj = (fn, obj) => R.mapObjIndexed(fn, obj) `

`console.log(mapObj(shows, xyz)) `

> //=>
param1:  1
param2:  x
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  2
param2:  y
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  3
param2:  z
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
{ x: 3, y: 4, z: 5 }

As you can see, I make a function called mapObj and receive like arguments a function and object to which the function will be applied, as I did not know what it recieves as parameters in the function, I introduced random parameters to see that it is what I recieve, which when printed I could translate it in the following way

`const xyz = { x: 1, y: 2, z: 3 }`
`R.mapObjIndexed((value, key, obj) => value + 2, obj)`

Or

`const addTwo = (value, key, obj) => value +2`
`console.log(R.mapObjIndexed(addTwo, obj))`

understanding this was very helpful for me and a great step to use this good function of ramda, and what better than to help understand what I already understood

**Comment by Craken420** [comment]
At use this function for first time, i was little confused but tried with this

` const xyz = { x: 1, y: 2, z: 3 } `

`const shows = (param1, param2, param3, param4) => {`
 ` console.log('param1: ',param1,'\nparam2: ',param2, '\nparam3: ',param3, '\nparam4: ',param4)`
`    return param1 + 2`
`}`

`const mapObj = (fn, obj) => R.mapObjIndexed(fn, obj) `

`console.log(mapObj(shows, xyz)) `

> //=>
param1:  1
param2:  x
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  2
param2:  y
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  3
param2:  z
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
{ x: 3, y: 4, z: 5 }

As you can see, I make a function called mapObj and receive like arguments a function and object to which the function will be applied, as I did not know what it recieves as parameters in the function, I introduced random parameters to see that it is what I recieve, which when printed I could translate it in the following way

`const xyz = { x: 1, y: 2, z: 3 }`
`R.mapObjIndexed((value, key, obj) => value + 2, obj)`

Or

`const addTwo = (value, key, obj) => value +2`
`console.log(R.mapObjIndexed(addTwo, obj))`

understanding this was very helpful for me and a great step to use this good function of ramda, and what better than to help understand what I already understood

**Comment by Craken420** [comment]
At use this function for first time, i was little confused but tried with this

` const xyz = { x: 1, y: 2, z: 3 } `

`const shows = (param1, param2, param3, param4) => {`
 ` console.log('param1: ',param1,'\nparam2: ',param2, '\nparam3: ',param3, '\nparam4: ',param4)`
`    return param1 + 2`
`}`

`const mapObj = (fn, obj) => R.mapObjIndexed(fn, obj) `

`console.log(mapObj(shows, xyz)) `

> //=>
param1:  1
param2:  x
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  2
param2:  y
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
param1:  3
param2:  z
param3:  { x: 1, y: 2, z: 3 }
param4:  undefined
{ x: 3, y: 4, z: 5 }

As you can see, I make a function called mapObj and receive like arguments a function and object to which the function will be applied, as I did not know what it recieves as parameters in the function, I introduced random parameters to see that it is what I recieve, which when printed I could translate it in the following way

`const xyz = { x: 1, y: 2, z: 3 }`
`R.mapObjIndexed((value, key, obj) => value + 2, obj)`

Or

`const addTwo = (value, key, obj) => value +2`
`console.log(R.mapObjIndexed(addTwo, obj))`

understanding this was very helpful for me and a great step to use this good function of ramda, and what better than to help understand what I already understood
