### ISSUE TITLE
dropRepeatsWith does not work as documented

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#1221]
http://ramdajs.com/docs/#dropRepeatsWith

```js
import {dropRepeatsWith} from "ramda";

// ok
console.log(dropRepeatsWith(() => false, ["a", "a", "!", "!", "b", "b"]));
// Result:   ['a', 'a', '!', '!', 'b', 'b']
// Expected: ['a', 'a', '!', '!', 'b', 'b']

// bug?!
console.log(dropRepeatsWith(() => true, ["a", "a", "!", "!", "b", "b"]));
// Result:   ['a']
// Expected: ['a', '!', 'b']
```

**Comment by megawac** [comment]
Your predicate `() => true` tells `dropsRepeatWith` that every value is identical. I think you want your predicate to be `(prev, curr) => prev === curr`

**Comment by paldepind** [comment]
It looks the same to me as to @megawac. This is expected behavior. Also in the last case you should just use `dropRepeats`.

**Comment by ivan-kleshnin** [comment]
Yes, you're right.
