### ISSUE TITLE
Calling range with letters causes Chrome to crash

### ISSUE THREAD

**Issue by ccapndave** [ramda/ramda#1222]
Calling `R.range('a', 'z')` breaks Chrome so badly it needs to be restarted.

Although `range` is only supposed to work on numbers, it should fail gracefully rather than taking out the browser (especially since range works on characters in other languages so its not an unreasonable error to make when developing).

**Comment by buzzdecafe** [comment]
i think we can cast `from` to a Number and that may solve the problem:

```diff
module.exports = _curry2(function range(from, to) {
  var result = [];
-  var n = from;
+ var n = +from;
+ var t = +to
-  while (n < to) {
+   while (n < t) {
    result[result.length] = n;
    n += 1;
  }
  return result;
});
```

untested of course

**Comment by buzzdecafe** [comment]
nm, that won't work. but at least it shouldn't crash.

**Comment by buzzdecafe** [comment]
on second thought, that does work for some definition of "work"; `+from` is `NaN` when `from` is a string. So `range` would return an empty list when given non-numeric arguments.
