### ISSUE TITLE
R.take(0) in place of a transducer is an infinite loop if it runs on an infinite iterator.

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1224]
```js
function* gen() {
	yield 1;
  	yield* gen()
}

R.into([], R.take(0), gen());
```

**Comment by CrossEye** [comment]
Perhaps someone has a clever response, but my first response is the old joke:  "Doctor, it hurts when I do _this_."  "Then don't _do_ that!"

**Comment by davidchambers** [comment]
Taking the first zero values in a sequence seems completely reasonable to me. In this case, the expected result is surely `[]`.

**Comment by asaf-romano** [comment]
Yes, what @davidchambers said.

The use case here is pretty interesting actually.  The generator is circularly yielding a color palette (yield* ["red", "green"]; yield* generateColors()), to be zipped with lists of objects that need to be "colored" somehow. Now, sometimes the list is empty, and that's how I got here. The temporary fix was a pretty ugly ternary operator expression, to which my doctor responded with ""Don't do that!".

**Comment by kedashoe** [comment]
I think you can just change

https://github.com/ramda/ramda/blob/master/src/internal/_xtake.js#L15

`return this.n === 0 ? _reduced(this.xf['@@transducer/step'](result, input)) : this.xf['@@transducer/step'](result, input);`

to

`return this.n <= 0 ? _reduced(this.xf['@@transducer/step'](result, input)) : this.xf['@@transducer/step'](result, input);`

**Comment by CrossEye** [comment]
Yes, that certainly looks like it would fix it.

(And my initial response really _was_ meant as a joke.  I was going to get online and look at it this evening if no one had beat me to it.  Clearly we shouldn't just thrash on such input.!)

**Comment by kedashoe** [comment]
I'll submit a PR after #1227 lands.

Other note: currently `take`ing a negative number, non-transducer style, [returns the original list](https://github.com/ramda/ramda/blob/master/test/take.js#L16). However I don't think this really makes sense with transducers, and a quick glance at some of the other transducer libraries shows they will take nothing. What do you guys think?

**Comment by asaf-romano** [comment]
Nothing seems less surprising to me (ditto for upcoming takeLast, dropLast).

**Comment by asaf-romano** [comment]
Many many thanks! -1 ternary operator! :)

**Comment by CrossEye** [comment]
Funny, although [I commented][co] on one deeply nested ternary, I don't have any issues with them overall.  I think they often make code more expressive. 


  [co]: https://github.com/ramda/ramda/pull/1236#discussion-diff-33891677
