### ISSUE TITLE
Meteor package outdated on 0.14.0

### ISSUE THREAD

**Issue by bySabi** [ramda/ramda#1240]
Please update meteor atmosphere package to latest release.

**Comment by CrossEye** [comment]
I don't think we have done anything for meteor.  I didn't know there was a meteor package.  Do you  know anything about how it is and who maintains it?

**Comment by bySabi** [comment]
Maybe "Azog the defiler" doit :-)
[ramda:ramda](https://atmospherejs.com/ramda/ramda)

**Comment by bySabi** [comment]
Maybe @ccorcos is the owner, is it??

**Comment by CrossEye** [comment]
Maybe.  He's spent some time around here.  I've never used Meteor, and don't know anything about it's environment or about Atmosphere.  @ccorcos, is this your undertaking?

**Comment by ccorcos** [comment]
Hey there. I didn't actually build the package but it lives here and I use it all the time:

https://github.com/MeteorPackaging/ramda-wrapper/issues/1

I believe autopublish.meteor.com should be taking care of updating the package, but we'll see. idk how that stuff works yet...

**Comment by CrossEye** [comment]
Thanks @ccorcos.  Here''s hoping someone on that project can straighten it out!

**Comment by ccorcos** [comment]
haha yeah, he'll get on it. He's pretty good about maintaining these packages.

**Comment by CrossEye** [comment]
#1375
