### ISSUE TITLE
Object tree filtering. How?

### ISSUE THREAD

**Issue by bySabi** [ramda/ramda#1241]
A newbie here. Thanks for "easy(compose(good,hard), R)" just a bad joke :-)

I have this object:

```
obj1 = {
    one: {
        type: Number
    },
    two: {
        type: Object
    },
    three: {
        type: "String"
    }
}
```

and need this: 
```
new_obj1 = {
    three: {
        type: "String"
    }
}
```

Say filter all object props who "type" prop value is a String

Right now I have this but not work, obviusly, that´s cause I write here :-).

```
sayX = function(x) { console.log('x: ' + x); };

new_obj1 = R.mapObj(
    R.compose(
        R.tap(sayX),
        R.filter(R.is(String)),
        R.prop("test")
    ), obj1);
```

Thanks

**Comment by bySabi** [comment]
Answer my self:
```
new_obj1 = R.pickBy(
    R.compose(
        R.is(String),
        R.prop('type')
    ),
    obj1
)
```

now I´m 0.02€ less newbie :-)

**Comment by CrossEye** [comment]
I'm glad you were able to solve it.  Two points:

  * There's a strange ill-parallel between `type: Number`, `type: Object`, and `type: "String"`.  If you were to add
  ```js
  four: {
      type: "Foo"
  }
  ```
  this would still be accepted by your filter.  Is that what's expected?  Or do you really want `type: String` (without the quotes?)

  * Your solution is fine.  There's nothing wrong with it.  If you're striving for a points-free solution for whatever reason, this will give it to you, just by creating a named function without including the `obj1` parameter.  But points-free can sometimes also obscure things.  This might be more easily stated as:
  ```js
  R.pickBy(
    x => x.type == "String",
    obj1
  )
  ```
  Even if you had to do this without the ES6 sugar (`function(x) {return x.type == "String";}`), this would still to my eyes be a cleaner solution than the original.  And with that sugar it makes a nice one-line function definition:
  ```js
  var myFilter = R.pickBy(x => x.type == "String");
  ```

**Comment by bySabi** [comment]
Is correct. I store object name like strings. Then I parse arbitrary object who contain "type" has string and set "type" to correct reference with `window["Foo"]`, strange?, sure! newbie stuff here ...
