### ISSUE TITLE
concat with null second argument has unexpected error

### ISSUE THREAD

**Issue by SohumB** [ramda/ramda#1246]
```javascript
> R.concat([1,2], null)
TypeError: can't concat object
```

For the record, this works fine:
```javascript
> R.concat([1,2], null)
[1,2]
```

**Comment by CrossEye** [comment]
I assume you mean that this works fine:

```js
> R.concat(null, [1,2])
[1, 2]
```

**Comment by buzzdecafe** [comment]
neither one of those should work

**Comment by CrossEye** [comment]
This definitely looks like a bug, but I think the right answer is that either one would throw rather than that they would both return `[1, 2]`.

**Comment by TheLudd** [comment]
Passing in null and a list is a breach of the functions contract so I wouldn't consider this a bug. But is there some documentation for those cases? I would expect all breaches of contract to leave the behavior of the function undefined.

**Comment by SohumB** [comment]
Yep, sorry, I did mean that the reversed argument order is a bug. And it makes sense that the bug is the inconsistency, not the case I raised. 

The other part of this problem is that the error thrown is weird. The only thing of type object being passed is `[1,2]`, which most certainly has a concat method. 

The issue seems to be that `_hasMethod([1,2], 'concat')` returns `false`. Is this expected?

**Comment by megawac** [comment]
Yes, `hasMethod` ignores array methods

**Comment by CrossEye** [comment]
> Yes, `hasMethod` ignores array methods

... because generally we want to handle any array processing with our own functions, and not used the built-in versions.

**Comment by davidchambers** [comment]
Add a `:+1:` to #1125 if you'd like to see invalid arguments handled consistently. :)
