### ISSUE TITLE
Rename R.times to R.repeatWith

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#1250]
I don't always use `times` or `repeat`, but when I do, I can never remember which is which (`repeat('x', 2)`)

Alternatively, deprecate `times` and have `repeat` take a function and just do `R.repeat(R.always(10))` if you need to

Alternatively, don't change anything :)

**Comment by davidchambers** [comment]
I like the idea of `R.repeat` and `R.repeatWith`!

**Comment by buzzdecafe** [comment]
:+1:

**Comment by kedashoe** [comment]
Cool I'll submit a PR later tonight
