### ISSUE TITLE
Split useWith into transform functions

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#1254]
This is a suggestion inspired by the long lived frustration of @CrossEye with the name `useWith` :smile: 

I do use this function and would not want it completely removed but searching all my code I only find that I use it to modify binary functions. I mostly only transform the first argument passed in to the main function, sometimes the second and rarely both. But I do have all these cases:
```
R.useWith(fn, someTransformingFn, R.identity)
R.useWith(fn, R.identity, someTransformingFn)
R.useWith(fn, someTransformingFn, someOtherTransformingFn)
```

If the case of mostly applying it to binary functions is recognized by others then suggest this: Remove `useWith` and replace it with three functions `transformFirst`, `transformSecond` and `transformBoth`. (could call them `transformLeft` and `transformRight` as well).

They would be pretty easy to reason about (currying omitted):
```
function transformFirst(f, g, a, b) {
  return f(g(a), b);
}
function transformSecond(f, g, a, b) {
  return f(a, g(b));
}
function transformBoth(f, g, h, a, b) {
  return f(g(a), h(b));
}
```
If needed perhaps a general case could be added where a list of functions are added but I would only do so if someone had a specific need.
This would also be a step towards reducing the number of varardic functions with a special parameter.

**Comment by CrossEye** [comment]
I'll have to think about this more.  Again it's one of those interesting cases of deciding to give up flexibility for simplicity -- an interesting and difficult trade-off.

My first thought, though, is that if we were to do this, it might be better just to do the `Both` version, and allow users to pass `identity` through as appropriate.

See also #1237.

**Comment by jdalton** [comment]
I've added this method as `modArgs`. Naming is tough. I'm not super excited about the name either but thought it was a little better than `useWith`.

**Comment by CrossEye** [comment]
> Naming is tough.

Yes, I've been looking for a name for this one for [more than two years][so].  Still nothing that really appeals.

  [so]: http://stackoverflow.com/questions/17386706/whats-a-good-name-for-this-extended-compose-function

**Comment by TheLudd** [comment]
I think `modArgs` is a step in the right direction. only objection to me is that it hints to a variable number of arguments.

**Comment by jdalton** [comment]
> I think modArgs is a step in the right direction. only objection to me is that it hints to a variable number of arguments.

In my case it was (basically a rest param of transforms).

**Comment by asaf-romano** [comment]
FWIW, I've been using useWith in much more complex ways (albeit for somewhat dirty and questionable stuff), which cannot be covered by the suggested alternatives.

**Comment by CrossEye** [comment]
See also #1260, which actually offers additional functionality, with a somewhat different API.

**Comment by CrossEye** [comment]
Ping.

Anyone have thoughts on this idea?

**Comment by davidchambers** [comment]
I'm not sure that

```javascript
R.transformSecond(Math.abs, f)(x, y)
```

is preferable to

```javascript
(x, y) => f(x, Math.abs(y))
```

or

```javascript
function(x, y) { return f(x, Math.abs(y)); }
```

I love point-free code, but sometimes a lambda is just what one needs.
