### ISSUE TITLE
Unexpected behaviour of R.partialRight

### ISSUE THREAD

**Issue by nomosyn** [ramda/ramda#1259]
From the [doc](http://ramdajs.com/0.15/docs/#partialRight):
![screen shot 2015-07-09 at 11 10 47](https://cloud.githubusercontent.com/assets/2693150/8591828/35b54268-262b-11e5-8762-6cacd5b26cc0.png)

so: `f = function (a,b) { return a - b; }; R.partialRight(f)(2)(1)` should be equal to `-1`

Instead, an error is raised:
![screen shot 2015-07-09 at 11 13 07](https://cloud.githubusercontent.com/assets/2693150/8591884/85e8ef32-262b-11e5-8f9d-e6f04a2dab94.png)

A work around for 2-arity functions:
![screen shot 2015-07-09 at 11 14 05](https://cloud.githubusercontent.com/assets/2693150/8591915/b8835a7c-262b-11e5-89ca-bf243b60ee65.png)

Or maybe my understanding is wrong?
Please, let me know.

**Comment by davidchambers** [comment]
`R.partialRight(f)` is not very useful as it doesn't specify any arguments to which `f` should be partially applied. In fact, `R.partialRight(f)` is equivalent to `f`.

Here's a working example:

```javascript
const subtract = (a, b) => a - b;
const dec = R.partialRight(subtract, 1);

dec(7);  // => 6
```

It's worth noting that `R.partialRight` does not return a curried function:

```javascript
const triplet = (a, b, c) => [a, b, c];
R.partialRight(triplet, 3)(1, 2);  // => [1, 2, 3]
R.partialRight(triplet, 3)(1)(2);  // TypeError: object is not a function
```

**Comment by nomosyn** [comment]
`It's worth noting that R.partialRight does not return a curried function:`
Because most other functions do return a curried function, maybe  `R.partialRight` should?
and, if ` f : *... -> a` then  `R.partialRight(f) : *... -> (*... -> a) | a` so that

if  `f : a -> b` then `R.partialRight(f) = f`
if   `f : a -> b -> c` then `R.partialRight(f)(b) : a -> c` `R.partialRight(f)(b)(a) = f(a,b)`
if   `f : a -> b -> c -> d` then `R.partialRight(f)(c) : a -> b -> d` `R.partialRight(f)(c)(a,b) = f(a,b,c)`
...

**Comment by davidchambers** [comment]
One of the few reasons to use `R.partialRight` over `R.curry` is that it works correctly for variadic functions and functions which do not report their arities correctly.

In most cases one is better off with a combination of [`R.curry`][1] and [`R.__`][2]:

```javascript
R.curry(f2)(_, b)(a) === f2(a, b)
R.curry(f3)(_, _, c)(a, b) === f3(a, b, c)
R.curry(f3)(_, _, c)(a)(b) === f3(a, b, c)
R.curry(f3)(_, _, c)(_, b)(a) === f3(a, b, c)
```


[1]: http://ramdajs.com/docs/#curry
[2]: http://ramdajs.com/docs/#__

**Comment by nomosyn** [comment]
Ok! Many thanks!

**Comment by davidchambers** [comment]
You're welcome! Feel free to ask questions on [Gitter][1] if you enjoy IRC-style communication.


[1]: https://gitter.im/ramda/ramda
