### ISSUE TITLE
differenceWith introduces unexpected values

### ISSUE THREAD

**Issue by atseng95** [ramda/ramda#1261]
Note the empty values introduced into the resulting array:
> function cmp(x, y) { return x.a === y.a; }
undefined
> x = [{a: 1}, {a: 2}, {a: 3}]
[ { a: 1 }, { a: 2 }, { a: 3 } ]
> y = [{a: 2}, {a: 4}]
[ { a: 2 }, { a: 4 } ]
> R.differenceWith(cmp, x, y)
[ { a: 1 }, , { a: 3 } ]
> R.differenceWith(cmp, y, x)
[ , { a: 4 } ]

**Comment by davidchambers** [comment]
Which version of Ramda are you using?

**Comment by davidchambers** [comment]
This was fixed in #982.

**Comment by CrossEye** [comment]
http://bit.ly/1NSNr0v
