### ISSUE TITLE
R.hasMethod (or R.can)?

### ISSUE THREAD

**Issue by bezhermoso** [ramda/ramda#1266]
Is this a check that people are doing on a regular enough basis that would earn its place in the `ramda` toolbelt?

I have a couple of scenarios where I am doing this for a couple of projects, a couple of obvious ones being is checking if something is a thenable, or is a full-blown promise:

``` javascript
var isThenable = R.hasMethod("then");
var isPromise = R.allPass(R.map(R.hasMethod, ["then", "catch", "error", "finally"]))
```

**Comment by davidchambers** [comment]
You'll soon be able to use `R.propIs` added in #1243:

```javascript
var isThenable = R.propIs(Function, 'then');
var isPromise = R.allPass(R.map(R.propIs(Function), ['then', 'catch', 'error', 'finally']));
```

**Comment by jdalton** [comment]
> You'll soon be able to use R.propIs added in #1243:

Downside is cross-context issues with iframes, windows, & vm module stuff.

**Comment by davidchambers** [comment]
You're right, @jdalton. This is a known issue with `R.is` (#1140). If and when we agree on how that function should be changed, `R.propIs` will inherit the new behaviour.
