### ISSUE TITLE
reduce with transform

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#1284]
Maybe as much of a question as a suggestion (I feel like I've seen a way to do this before). I often find myself wanting to perform an action on the second argument of the reducing function. For example:

var sumAbs = R.reduce(function(acc, val) { return acc + abs(val) }, 0, list)

Normally I'd do: R.reduce(R.add, 0, R.map(abs, list))

But it would be nice to not have to iterate twice. Again, I *feel* like I've seen a good workaround using nthArg before, but can't quite remember.

**Comment by CrossEye** [comment]
You could almost certainly use Transducers for this in some way.  To my mind, the main point of them is to allow you to swap the typical multiple iterations of a `compose`d function with a single iteration that runs runs each of the composed functions in sequence against an individual value.

Another possibility is to use `useWith`:

    var sumAbs = R.reduce(R.useWith(R.add, R.identity, Math.abs), 0);

**Comment by scott-christopher** [comment]
`R.transduce` will allow you to map and then reduce as per your example without creating an intermediate list:

```js
var list = [2, -4, 8, -16];
R.transduce(R.map(Math.abs), R.add, 0, list); //=> 30
```

**Comment by TheLudd** [comment]
@CrossEye 

> You could almost certainly use Transducers for this in some way.

That is absolutely true and transducers is a more general way of modifying the reduce function than just this. But I do feel that the case presented by @tolmasky is a fairly common one. I previously mentioned in another issue the possibility of introducing the function `transformRight` which would be defined as:
```
var transformRight = R.curry(function(f, g, a, b) {
  return f(a, g(b));
});
```

The usage would be `R.reduce(R.transformRight(R.add, R.abs), 0, list)`. I don't know if people fiund this more pleasant to read but it is a solution to a very common reducing problem. 

Imagine a list of users with age where you want to sum the age:

```
R.reduce(R.transformRight(R.add, R.prop('age')), 0, userList)
```

Just a suggestion from me...

**Comment by CrossEye** [comment]
I'd forgotten that suggestion in the wake of @davidchamber's big attempts at redoing `compose`/`pipe`.   Let's discuss it again over on #1254.
