### ISSUE TITLE
curryRIght

### ISSUE THREAD

**Issue by xgrommx** [ramda/ramda#1285]
How can I reproduce this method in Ramda https://lodash.com/docs#curryRight?

**Comment by CrossEye** [comment]
We so far haven't been very interested in that.  We do have [`partialRight`][pr].


  [pr]: http://ramdajs.com/docs/#partialRight

**Comment by xgrommx** [comment]
Now I use `const decrement = curryN(2, flip(dec))` http://codepen.io/xgrommx/pen/pJZbEz. `partialRight` probably isn't suitable.

**Comment by CrossEye** [comment]
That feels to me like a -- let's say "creative misuse" -- of `flip`.  I wouldn't want to guarantee that we won't some day choose to throw when you supply a unary function to `flip`.  I'll  try to think more on this when I'm not falling asleep.  :smile"

**Comment by davidchambers** [comment]
Not all code needs to be point-free. Wrapping third-party functions is a task to which the lambda is well suited. I would simply write:

```javascript
const g = R.curry((a, b) => f(b, a));
```

**Comment by char0n** [comment]
@xgrommx if you're still interested [ramda-adjunct](https://github.com/char0n/ramda-adjunct) contains implementation of [curryRightN](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.curryRightN) and [curryRight](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.curryRight). I had a usecase for it while bending some functions from underscore into autocurried data-last versions.
