### ISSUE TITLE
compose/pipe argument order for lenses composition is counter intuitive

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1288]
For those of us not having a strong Haskell/ML background, ``pipe`` is, generally speaking, much more practical than ``compose``, esp. when the pipeline includes more than three functions or so. It was thus quite easy to choose between the two for  #1205 changed this situation: for those who think in ``pipe`` terms, ``compose`` makes much better sense when dealing with lenses.

```js
var getFooHead = R.pipe(R.prop("foo"), R.head);
var fooHeadLenses = R.compose(R.lensProp("foo"), R.lensIndex(0));
```

**Comment by asaf-romano** [comment]
Now I realize this was done intentionally, and likely to stay that way, but if it does there should be, I think, at least one example of composing lenses in the documentation.

**Comment by SeeThruHead** [comment]
Why does compose work left to right for lenses?

**Comment by scott-christopher** [comment]
I imagine some more information about composition order could be added to the lens tutorials coming in #1282.

As for why they compose left to right, consider the types:
```
Lens s a :: Functor f => (b -> f b) -> (a -> f a)

compose :: Lens a b -> Lens b c -> Lens a c
// or
compose :: ((b -> f b) -> (a -> f a))
        -> ((c -> f c) -> (b -> f b))
        -> ((c -> f c) -> (a -> f a))
```
which might help to see by lining up the types:
```
compose ::               ((b -> f b) -> (a -> f a))
        -> ((c -> f c) -> (b -> f b))
        -> ((c -> f c)               -> (a -> f a))
```

Perhaps another way to gain some intuition about the composition order is to consider the composition of some simple mapping functions:
```js
var mapHead = f => R.converge(R.prepend, R.compose(f, R.head), R.tail);
var mapNotNull = f => R.ifElse(R.isNil, R.identity, f);

// Note the composition order here
var mapHeadNotNull = R.compose(mapHead, mapNotNull);
// which could also be written as: f => mapHead(mapNotNull(f));

var absoluteHeadOrNull = mapHeadNotNull(Math.abs);

absoluteHeadOrNull([-1, -2, -3]); //=> [1, -2, -3]
absoluteHeadOrNull([null, -2, -3]); //=> [null, -2, -3]
```

Not sure whether this helps, or I've just muddied the water even more :grinning:

**Comment by kujon** [comment]
This is BY FAR the most helpful topic I read on Ramda so far. Took me ages to figure out why I can't compose lenses, much appreciated!

**Comment by anton-rudeshko** [comment]
BTW, lenses is not even mentioned in `compose` docs, that's sad.

**Comment by yemi** [comment]
@kujon did you figure out how to compose lenses for structures containing lists?
