### ISSUE TITLE
Can Ramda solve this API approach?

### ISSUE THREAD

**Issue by bySabi** [ramda/ramda#1291]
Hello.
I was trying to implement an API like this:

say I have a object `Stores`, with this prototype functions:

```
Stores = function(){
   ... 
}

Stores.prototype.insert = function(obj) {
    ...
}

Stores.prototype.find = function(selector, options) {
    ...
}
```

and `SubStores` that act like function and object, with this prototype functions:

```
SubStores = function(fn, args) {
    return this[fn](args)
}

SubStores.prototype.insert = function(obj) {
    ...
    return this.options.path + obj;
}

SubStores.prototype.find = function(selector, opt) {
    ...
    return this.options.path + selector;
}
```

First I need to create and initialize `SubStores` objects:

I don´t know how ...
```
    Store1 = 'create from SubStores' with options={path: 'perfil', ...} 
    Store2 = 'create from SubStores' with options={path: 'rol', ...}
```

I have to create and initialize `Stores` object to ...

maybe..
```
    stores = new Stores("stores");
```

Now Ramda part:

You see that `Stores` and `SubStores` share same API, `insert` and `find` functions. And I pretend do it this Ex:
```
    //stores is a Stores instance
    stores.insert([Store1({name: 'Foo'}), Store2({event: 'Bar'})])
```
this is syntax sugar of:

```
    stores.insert([Store1.insert({name: 'Foo'}), Store2.insert({event: 'Bar'})])
```

The same for all API: `insert`, `find`, `update`, ...

Can I implement this with Ramda curry or ...?

Thanks.

**Comment by CrossEye** [comment]
I'm afraid I'm not following entirely.  Are you suggesting that you want to call this:

    stores.insert([Store1({name: 'Foo'}), Store2({event: 'Bar'})])

and behind the scenes have it delegat to something more like this:

    stores.insert([Store1.insert({name: 'Foo'}), Store2.insert({event: 'Bar'})])

with the same abilities for `find` and `update`?

If so, I think you're going to run into serious issues, since the parameters in the list passed to `stores.insert` will be the _result_ of running `Store1({name: 'Foo1})`, etc.  I think it would be too late to try to restructure the calls to create `Store1.insert({name: 'Foo1'})`.

But I may well be misunderstanding entirely.

**Comment by bySabi** [comment]
```
stores.insert([Store1.insert({name: 'Foo'}), Store2.insert({event: 'Bar'})])
```
Probably not posible literally, sorry for bad explain.
I mean:
```
stores.insert([Store1({name: 'Foo'}), Store2({event: 'Bar'})])
```
become
```
stores.insert([Store1('insert',{name: 'Foo'}, Store2.('insert', {event: 'Bar'})])
```

`Store1('insert', {name: 'Foo'})` is just a call to  `Store1.insert({name: 'Foo'})`

**Comment by bySabi** [comment]
I´m open to better API suggest too :-)

**Comment by bySabi** [comment]
Actually I think is posible to implement with curry´s but I don´t have arrive to this part yet.
I'm stuck on object/function creation. Maybe this is too complex ...
I was testing all kind of things.
Right now this is my object/function creation:
```
SubStore.create= function(options) {
    let options = options;
    return function (fn, args) {
        console.log(options);
    }
}
```
This is very basic but I don´t know how can add/call propertys to/from returned clousure
Now I can create "object":
```
Store1 = SubStore.create({path: "perfil"});
```
I can call: `Store1('insert', {name: "Foo"})`
But how implement??
```
Store1.insert({})
```
I know is posible implement functions API within a `switch` on function clousure but `Store1.insert()` form is desirable.

**Comment by CrossEye** [comment]
> I mean:
> ```js
> stores.insert([Store1({name: 'Foo'}), Store2({event: 'Bar'})])
> ```
> become
> ```js
> stores.insert([Store1('insert',{name: 'Foo'}, Store2.('insert', {event: 'Bar'})])
> ```

I still have the same concern.  Before evaluating

> ```js
> stores.insert([Store1({name: 'Foo'}), Store2({event: 'Bar'})])
> ```

the JS engine has to evaluate

> ```js
> var s1 = Store1({name: 'Foo'})
> ```

and

> ```js
> var s2 = Store2({event: 'Bar'})
> ```

Only then can it evaluate

> ```js
> stores.insert([s1, s2])
> ```

But once it does this, how would it convert `s1` into 

```js
Store1('insert',{name: 'Foo'})
```

Does the `s1` object have a reference to the `Store1` function and to the `{name: 'Foo'}` configuration object?

**Comment by bySabi** [comment]
I make a dirty  snippet of code for test ... 
```
var SubStore = {};
SubStore.create= function(options) {
    let options = options;
    return R.curry(function (args, fn) {
        switch (fn) {
            case 'insert':
                console.log('insert');
                break;
            case 'find':
                console.log('find');
                break;
        }
    })
}

var Store = {};
Store.insert = function(args) {
    for(let i = 0, len = args.length; i  < len; i++ ) {
        args[i]('insert');
    }
} 



var sub1 = SubStore.create({x:1});
var sub2 = SubStore.create({y:2});

Store.insert([sub1({name: "Foo"}), sub2({age: 18})]);
```

I had invert arguments order on ... `R.curry(function (args, fn) { ...` . I need `fn` on first place cause function signature change, say
 Ex:
 `sub1({name: "Foo"}, {$inc: {value:"1"}}, 'insert')`
 `sub1({}, 'find')` 
 

Still searching for remove `switch` and props inside returned closure curried function.

**Comment by bySabi** [comment]
Finally solved:

```
//return 'fn' with all 'obj' props
function functionize(obj, fn)
{
    let fn = fn;
    for( let i in obj ){ fn[i] = obj[i] };
    return fn;
}


SubStore = function(options) {
    this.options = options;
}
SubStore.prototype.getOptions = function() { return this.options }
SubStore.prototype.setOptions = function(options) { this.options = options }
SubStore.prototype.insert = function(doc) { return doc }
SubStore.prototype.find = function(selector, options) { return selector }

SubStore.create = function(options) {
    let sub = functionize(new SubStore(options), R.curry(function (args, fn) {
        let self = sub;         //reference to new SubStore obj
        return self[fn](args);
    }))
    return sub;
}

Store = function(options) {
    this.options = options;
}
Store.prototype.insert = function(args) {
    for (let i = 0, len = args.length; i < len; i++) {
        if ( R.is(Function, args[i]) ) { args[i] = args[i]('insert') }
        console.log(args[i]);
    }
}
Store.prototype.find = function(args) {
    for (let i = 0, len = args.length; i < len; i++) {
        if ( R.is(Function, args[i]) ) { args[i] = args[i]('find') }
        console.log(args[i]);
    }
}
````

Test code

```
store = new Store();

sub1 = SubStore.create({path:'perfil'});
sub2 = SubStore.create({path:'rol'});

// test#1
store.insert([ sub1({name: "Foo"}), sub2({age: 18}) ]);

// test#2
store.insert([ sub1.insert({name: "Foo"}), sub2.insert({age: 18}) ]);
```

I guest this need more R way on `array for` loops 
Any advice??

**Comment by CrossEye** [comment]
> I guest this need more R way on array for loops 
> Any advice??

I'd have to see what you really wanted to do, rather than the presumably dummy code of `console.log`.  To me a loop is usually for something, and that something is almost always best expressed as a `map`, a `reduce`, a `filter`, or a `find`.  As a desparate last resort, Ramda also includes `forEach`, but I would highly recommend against using it unless nothing else would do.

I'm afraid I really have not been able to follow what your code is for.  So I'm having a hard time understanding what sorts of improvements you would like for it from Ramda.  Note that although Ramda can work with OO code in various ways, such is far from its strength.  Ramda is entirely designed to help with FP.
