### ISSUE TITLE
Unexpected behaviour of R.clone

### ISSUE THREAD

**Issue by nomosyn** [ramda/ramda#1292]
We have:
```
(new Mongo.ObjectID()) instanceof Mongo.ObjectID // => true ✓
(EJSON.clone(new Mongo.ObjectID())) instanceof Mongo.ObjectID // => true ✓
```

But:
```
(R.clone(new Mongo.ObjectID())) instanceof Mongo.ObjectID // false (EXPECTED TO BE TRUE)
```
Maybe some inpirations could be taken from [EJSON.clone](https://github.com/meteor/meteor/blob/devel/packages/ejson/ejson.js) ?

**Comment by CrossEye** [comment]
I could definitely see borrowing this:

```js
  if (typeof v.clone === 'function') {
    return v.clone();
  }
```

I would certainly not want us to try to get into the business of figuring out someone else's inheritance models and trying to capture them in our clones, but if they have a clone method, perhaps we could use it?

**Comment by nomosyn** [comment]
Yes, just like [R.equals](https://github.com/ramda/ramda/blob/master/src/equals.js) does it...
Would be useful to me, probably to others (anyone?), I cannot see why it would be a bad thing...

**Comment by davidchambers** [comment]
Dispatching to `clone` seems reasonable. I agree with Scott that we shouldn't go any further than that.

**Comment by CrossEye** [comment]
@nomosyn: Do you feel like opening a PR for this???

**Comment by nomosyn** [comment]
haha yes let's do it! :-)
