### ISSUE TITLE
Failed at the build script 'make && make dist/ramda.min.js

### ISSUE THREAD

**Issue by nomosyn** [ramda/ramda#1294]
Hi!

I checked out ramda, `$ npm test`, expected to see: `Yeay! All tests passed!` but got this [npm test dump](https://gist.github.com/nomosyn/76707d145007db6d5b08).

Same error for `v0.15.0`, `v0.16.0`, `v0.17.0`

**Comment by TheLudd** [comment]
Did you run `npm install` first?

**Comment by nomosyn** [comment]
No! Now it works. Thx.

I was following the `CONTRIBUTING.md`: this command is not mentioned. It may be useful to add it.

**Comment by TheLudd** [comment]
> I was following the CONTRIBUTING.md: this command is not mentioned. It may be useful to add it.

It is also possible to add a script in the package.json file:

```
scripts: {
  "pretest": "npm install"
}
```

This will make sure dependencies are installed before running tests. If all downloaded dependencies satisfy the requirements, no download requests are made. I have this in all my projects.

**Comment by nomosyn** [comment]
Yes, better!

**Comment by CrossEye** [comment]
@TheLudd:

That sounds like a good idea.

I suppose it also should be in CONTRIBUTING.md, just to make it clear that the build does have a number of external dependencies.
