### ISSUE TITLE
ifElse should accept the actual input as its fourth argument

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1297]
Because ifElse returns a function accepting the input as its argument, it doesn't behave properly when it's curried. Consider this example:

```js
var transformIfNotNull = R.ifElse(R.isNil, R.identity);
var incIfNotNull = transformIfNotNull(R.inc);
incIfNotNull(3); // => 4
transformIfNotNull(R.inc, 3); // A function is returned; the second argument is ignored
```

This may apply to other functions.

**Comment by davidchambers** [comment]
The difficulty is that `R.ifElse` does not currently require unary functions.

**Comment by CrossEye** [comment]
But it does open the question of just how useful the variadic nature of the resulting function really is.

Some of these things were written on spec, mostly to deal with cases of "But this is how we work in Javascript".  I'd like to see if anyone is really using it for its variadic nature.  If there are none, it would be straightforward to switch, and if there are only a few, it might be best to switch anyway and recommend using `apply`s and `unapply`s where needed.

**Comment by TheLudd** [comment]
Did a scan through our code found ~20 occurances of `ifElse` all treating the functions as unary, exept for one case where it is nullary.

**Comment by asaf-romano** [comment]
What about honoring the arity of the input functions? Sure, it won't work if the arity is broken, but it's still better than nothing.

**Comment by CrossEye** [comment]
@asaf-romano: 
We can't really do that.  We already curry the resulting to the maximum length of the three supplied functions, but we obviously can't pre-curry `ifElse` to this length without knowing these values.  It seems it would only work if the functions are unary, or if we require the arguments to be wrapped in an array so that we could apply them.  The latter is fairly unappealing.

@TheLudd: nullary?  Then why bother? :smile:

**Comment by TheLudd** [comment]
@CrossEye I was wrong about that. Misinterpreted the code. But I was referring to the resulting functions and not the conditional one. They could be prepared functions that return a constant value.

**Comment by asaf-romano** [comment]
true true.

My own use case for ```ifElse`` are all unary btw. However, for ```cond`` I did find a few multipe-arguments use cases in m my code.

**Comment by alexeygolev** [comment]
I didn't even know that it has a 'variadic nature' :-)

**Comment by davidchambers** [comment]
We've decided to stick with the more flexible definitions of functions such as `R.pipe` and `R.both` (see #1395, for example). The same reasoning surely applies to `R.ifElse` as well.
