### ISSUE TITLE
Cookbook question

### ISSUE THREAD

**Issue by davidchase** [ramda/ramda#1300]
In the section about [futures](https://github.com/ramda/ramda/wiki/Cookbook#use-ramda-fantasy-future-to-wrap-ajax).
this line `var fetchJSON = fetch.chain(parseJSON);` it throws an error because `chain` doesn't yet exist since `fetch` hasn't been called. 

I used `R.chain` as a work around since it dispatches to fantasy-land chain as well as `R.map` since i get errors with rest of the code.

Is that a good solution and should the docs be updated? or do you guys recommend something else?

cheers,
david

**Comment by TheLudd** [comment]
Not familiar with the cookbook but it seems like `fetch` needs an argument which should be a URL. So try `fetch(url).chain(parseJSON)`

**Comment by davidchase** [comment]
right but at the bottom you will see `getNewTitles('/products.json').fork(console.error, console.log);` `products.json` being the url.. if you visit my above link it may help

**Comment by TheLudd** [comment]
At first glance the cookbook seems incorrect. Fetch is a function right? So it does not have a property called chain. You could do this:

```
var getNewTitles = R.compose(
   R.map(R.prop('title')), // In the cookbook this was R.map('title') which looks incorrect
   R.map(R.filter(R.prop('new'))),
   R.map(R.prop('items')),
   R.chain(parseJSON),
   fetch
);
getNewTitles('/products.json').fork(console.error, console.log);
```

This should work unless there are other errors I missed. And of course you need a server that responds to the url.....

**Comment by davidchase** [comment]
yeah thats exactly what i did :+1: i was just making sure i wasnt missing anything

**Comment by davidchambers** [comment]
Feel free to update the example from the cookbook, @davidchase.
