### ISSUE TITLE
Add a list XOR function

### ISSUE THREAD

**Issue by trbrc** [ramda/ramda#1301]
There is currently no simple way to do an XOR between two lists, i.e. take two lists and return a list of the elements that occur in only one of the lists. Like this:
```javascript
R.xor([0, 1, 2, 3, 4], [6, 4, 2]) // => [0, 1, 3, 6]
```
Lodash [has a method like this](https://lodash.com/docs#xor).

As suggested by @davidchambers on Gitter, here's a way to do it currently:

```javascript
const xor = R.converge(R.difference, R.union, R.intersection);
```
But that's unlikely to be efficient.

**Comment by CrossEye** [comment]
:+1: for the idea.  We can play around with implementations.  And of course we'd probably want a `xorWith` version as well.

Here's an alternative, just for comparison.  I haven't thought at all about what would be most efficient:

```js
const xor2 = R.converge(R.union, R.difference, R.flip(R.difference));
```

**Comment by davidchambers** [comment]
I'm in favour of this function. `R.xor` is not a good name for it, though, as we already have `R.or` which does something entirely different. I suggest `R.symmetricDifference` or `R.symDifference`.

**Comment by buzzdecafe** [comment]
once again i agree with @davidchambers . fins with the function, but not the name. to my ear, `xor` is a boolean or bitwise operation.

**Comment by CrossEye** [comment]
`diffɟɟıp` :smile:
