### ISSUE TITLE
Lazy evaluation

### ISSUE THREAD

**Issue by xgrommx** [ramda/ramda#1304]
Can Ramda use a lazy evaluation like in lodash? For example:

``` js
function priceLt(x) {
   return function(item) { return item.price < x; };
}
var gems = [
   { name: 'Sunstone', price: 4 }, { name: 'Amethyst', price: 15 },
   { name: 'Prehnite', price: 20}, { name: 'Sugilite', price: 7  },
   { name: 'Diopside', price: 3 }, { name: 'Feldspar', price: 13 },
   { name: 'Dioptase', price: 2 }, { name: 'Sapphire', price: 20 }
];

var w = _(gems).filter(priceLt(10)).take(3);

console.log(w.value(), 'old value');

setTimeout(function() { gems.unshift.apply(gems, [{name: 'Denis', price: 3}]); console.log(w.value()); }, 2000);

```

**Comment by megawac** [comment]
Correct me if I'm wrong but I think #878 implemented short circuiting via transducers.

**Comment by xgrommx** [comment]
@megawac As you can see I haven't passed `gems` to the function `w` in `setTimeout`

**Comment by CrossEye** [comment]
This would do what you want without processing `filter` for every gem.

```js
R.into([], R.compose(R.filter(priceLt(10)), R.take(3)), gems),
```
For some reason I really should investigate, this runs through until the fourth match on the filter and then stops, having included only the three.  Something seems very wrong with that, but it still has the overall laziness you're looking for.  Not all Ramda functions are transducerified in this manner, but a number are, and we would probably be willing to consider adding it to other ones.

**Comment by xgrommx** [comment]
@CrossEye unfortunately this code doesn't work:

```js
function priceLt(x) {
   return function(item) { return item.price < x; };
}
var gems = [
   { name: 'Sunstone', price: 4 }, { name: 'Amethyst', price: 15 },
   { name: 'Prehnite', price: 20}, { name: 'Sugilite', price: 7  },
   { name: 'Diopside', price: 3 }, { name: 'Feldspar', price: 13 },
   { name: 'Dioptase', price: 2 }, { name: 'Sapphire', price: 20 }
];

var w = R.into([], R.compose(R.filter(priceLt(10)), R.take(3)), gems);

console.log(w, 'value');

setTimeout(function() { gems.unshift.apply(gems, [{name: 'Denis', price: 3}]); console.log(w, 'new value'); }, 2000);
```

**Comment by xgrommx** [comment]
@CrossEye With `curry` I reproduced it but I should pass `gems` to `w` unlike in lodash:

```js
function priceLt(x) {
    return function(item) { return item.price < x; };
}
var gems = [
    { name: 'Sunstone', price: 4 }, { name: 'Amethyst', price: 15 },
    { name: 'Prehnite', price: 20}, { name: 'Sugilite', price: 7  },
    { name: 'Diopside', price: 3 }, { name: 'Feldspar', price: 13 },
    { name: 'Dioptase', price: 2 }, { name: 'Sapphire', price: 20 }
];

var w = R.into([], R.compose(R.filter(priceLt(10)), R.take(3)));

console.log(w(gems));

setTimeout(function() { gems.unshift.apply(gems, [{name: 'Denis', price: 3}]); console.log(w(gems))}, 2000);
```

**Comment by CrossEye** [comment]
> With `curry` I reproduced it but I should pass `gems` to `w` unlike in lodash:

We certainly don't try to mimic lodash's chaining style anywhere.  We also deal mostly with immutable data, so the whole `unshift` mechanism is an odd match for Ramda.  (BTW, why the runaround on that call?  Wouldn't `gems.unshift({name: 'Denis', price: 3})` do the same?)

I'm glad this does work.  I'm still confused about some additional work it's doing, though.

**Comment by xgrommx** [comment]
@CrossEye Plus in lodash that I shouldn't pass `gems` to `w`. Will be better if Ramda will support this approach.

**Comment by CrossEye** [comment]
I'm sorry, it's not clear to me if Ramda does what you want with something like my example or if you'd like something additional.

**Comment by jdalton** [comment]
@xgrommx fwiw lodash supports shortcut fusion in methods like `_.flow` or `_.compose` too which is handy with [lodash-fp](https://www.npmjs.com/package/lodash-fp).

**Comment by xgrommx** [comment]
@jdalton I know and I love it =)
