### ISSUE TITLE
Docs cannot be printed

### ISSUE THREAD

**Issue by SamHasler** [ramda/ramda#1305]
The docs page (http://ramdajs.com/0.17/docs/) won't print in chrome, and only prints what's on screen in IE11.

**Comment by CrossEye** [comment]
Very interesting.   Any CSS experts around?  Any ideas why?

**Comment by yuanchuan** [comment]
That's weird, I can't even preview print in chrome. 
Just removing the 'position: fixed' attribute on the `main` node and it works:

<img width="254" alt="2015-07-23 20 27 25" src="https://cloud.githubusercontent.com/assets/250426/8850266/52227ba6-3179-11e5-8b43-5659cf808233.png">

The `style.css` is quite huge. I suggest separate the print styles in a different file.

**Comment by SamHasler** [comment]
Adding this to the inspector stylesheet worked for me:

```
@media print {

  html.docs-page aside,
  a[title="View source on GitHub"] {
    display: none;
  }

  html.docs-page main {
    position: inherit;
    left: 0;
  }

  h2, .h2 {
    font-size: 12px;
  }

  .card {
    font-size: 10px;
    padding-bottom: 0;
  }
  .card pre code {
    padding-top: 0;
    padding-bottom: 0;
  }
}
```

**Comment by jenshedqvist** [comment]
Yeah @yuanchuan that fixed main element is definitely the culprit. And a couple of print styles wouldn't be nice as @SamHasler points out. I might be able to grab a CSS shovel and do some work on that.

**Comment by CrossEye** [comment]
@jenshedqvist:

> I might be able to grab a CSS shovel and do some work on that.

That would be quite welcome.  If you do, please start from https://github.com/ramda/ramda.github.io/pull/25, which will be going in when we release v0.18.  This includes all sorts of improvements for responsive design.

**Comment by buzzdecafe** [comment]
closing; if still needed, this should go on ramda.github.io repo
