### ISSUE TITLE
Flip R.bind sig

### ISSUE THREAD

**Issue by megawac** [ramda/ramda#1307]
Mentioned this in gitter earlier, but I was looking for a quick way to do a `bindAll` on an array earlier and reached for

```
R.map(R.bind(context), functionArray)
```

Assuming the `bind` sig was `object func -> func`

**Comment by CrossEye** [comment]
Interesting.  I'm not sure this is any more likely than

    R.map(R.bind(fn), contextList)

This is another one of those cases where I don't have strong instincts about the likelihood of either one.  Do you have an argument in favor of your preferred order?

**Comment by davidchambers** [comment]
My hunch is that binding one context to many functions is more common than binding many contexts to one function. The existence of [`_.bindAll`][1] supports this hunch.


[1]: http://underscorejs.org/#bindAll

**Comment by paldepind** [comment]
I agree. A lot of contexts has many functions but few functions works on more than one context.

**Comment by CrossEye** [comment]
> A lot of contexts has many functions but few functions works on more than one context. 

Well `R.map(fn)` seems to contradict this.  

I don't have any serious objection.  I simply want to have a good reason to change a long-standing API.

**Comment by TheLudd** [comment]
If this is to be changed, would you consider also renaming this function to `bindContext`? I would like `bind` to be the "opposite"  of this, i.e a functions that binds arguments but not context. When using the native `Function.prototype.bind` I am often bothered by passing in `null` as the first argument.

**Comment by kedashoe** [comment]
> If this is to be changed, would you consider also renaming this function to bindContext?

+1. For some reason I find `bind` to be more confusing than some others in this regard, ie functions with the same names as native ones that do something different.

> I would like bind to be the "opposite" of this, i.e a functions that binds arguments but not context. When using the native Function.prototype.bind I am often bothered by passing in null as the first argument.

I agree with this as well. Do you think `partial` is good enough to use in this case @TheLudd ? (Does anyone else feel like `partial` should take 2 parameters (1. the `fn` and 2. the list of arguments to apply) rather than being variadic?)

**Comment by davidchambers** [comment]
> Does anyone else feel like `partial` should take 2 parameters (1. the `fn` and 2. the list of arguments to apply) rather than being variadic?

I do. :)

**Comment by TheLudd** [comment]
> Do you think partial is good enough to use in this case @TheLudd ?

I think "partial" is a bad name for doing bind operations. However I do find "bind" to be  a good name for partial operations. With bind you can supply all needed parameters or just some of them. Partial implies that you do not provide all parameters. 

Long ago I used `partial` in lodash but I have never needed it with ramda since `curry` exists.

**Comment by raine** [comment]
> Long ago I used partial in lodash but I have never needed it with ramda since curry exists.

I have sometimes used it to satisfy all arguments before passing a function to callback or so.

**Comment by CrossEye** [comment]
>> Does anyone else feel like `partial` should take 2 parameters (1. the `fn` and 2. the list of arguments to apply) rather than being variadic?

> I do. :)

I do as well.  Some time ago, I agreed that Ramda would be better off with no variadic functions at all.  I have not made any sort of sweep through the code for them, but as we address these functions, it would be nice to change them into fixed-arity versions.

**Comment by megawac** [comment]
Agreed, partial should be fixed sig based on current directions

**Comment by kedashoe** [comment]
I wonder if there is a useful distinction to be made between variadic functions where all the arguments are of the same type and those with mixed types? I think this is what makes `partial` seem odd, while `pipe` and `compose` feel ok.

**Comment by CrossEye** [comment]
But even `pipe` and `compose` wouldn't be made much different by requiring the wrapping of these arguments in a list.  If we could gain that much more consistency, and if we could then use these functions consistently from internal structures as well as from source code, I think that would be a nice win.

**Comment by buzzdecafe** [comment]
closed for inactivity
