### ISSUE TITLE
R.compose breaking behavior after 0.15

### ISSUE THREAD

**Issue by pzavolinsky** [ramda/ramda#1308]
var values = [1,2,3];

var isInValues = R.compose(
	R.flip(R.any)(values),
	R.equals
);

isInValues(1)
// 0.15.1: returns true
// 0.17.1: returns f()

**Comment by scott-christopher** [comment]
This is due to #1260 which now curries the resulting composed function when the initial function is polyadic (`R.equals` expecting 2 arguments in your example).

If you need to retain the previous behaviour, a simple workaround would be to wrap the function in `N.unary`:
```js
var values = [1,2,3];

var isInValues = R.compose(
  R.flip(R.any)(values),
  R.unary(R.equals)
);

isInValues(1) //=> true
```
