### ISSUE TITLE
cdn returns 404

### ISSUE THREAD

**Issue by Bondifrench** [ramda/ramda#1309]
FYI `http://cdnjs.cloudflare.com/ajax/libs/ramda/0.17.1/ramda.min.js ` which is the first cdn link in the Home page returns 404

**Comment by CrossEye** [comment]
I don't know why.  I'm afraid we might have to stop auto-updating the README for CDNJS links.  JSDelivr seems to update speedily without issue.  But we keep having our README point to nonexistent links on CNDJS.  I've raised an issue with them:

https://github.com/cdnjs/cdnjs/issues/5129

**Comment by CrossEye** [comment]
Fixed in https://github.com/cdnjs/cdnjs/commit/d1b5472f4d5054dc5043378fb7ad9cf9b52787c5
