### ISSUE TITLE
add R.pair

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1310]
```haskell
pair :: a -> b -> (a,b)
```

Didn't someone once say that all numbers except 0 and 1 are arbitrary? In the context of Ramda, I disagree: 2 is also a number with special significance. `R.fromPairs` and `R.toPairs` use a pair to represent a map entry.

This morning I wanted to transform `[{ name :: String, sig :: String, description :: String }]` into `Map String { name :: String, sig :: String, description :: String }`. Here's my solution:

```javascript
R.fromPairs(R.map(R.converge(R.concat, R.compose(R.of, R.prop('name')), R.of), list))
```

With `R.pair`, I could have written:

```javascript
R.fromPairs(R.map(R.converge(R.pair, R.prop('name'), R.identity), list))
```

I believe this function would be a good companion of `R.createMapEntry`. The implementation is trivial.

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by CrossEye** [comment]
I've wanted it often enough too.  :herb:

**Comment by paldepind** [comment]
> Didn't someone once say that all numbers except 0 and 1 are arbitrary?

That much surely have been a computer scientist and not a mathematician ;)

This function looks useful to me.

One might also consider something like this:

```javascript
function createArray(length) {
  return _arity(length, function() { return _slice(arguments); };
}
```

Then `pair` could be defined like this:

```javascript
var pair = createArray(2);
```

I have no idea if that is useful and worth the additional complexity though.

**Comment by kedashoe** [comment]
Same problem #931 ?

**Comment by CrossEye** [comment]
@kedashoe:

Pardon?  Although tuples were briefly discussed in that issue, that was never the goal there.  I suppose this would offer a way to solve that issue without dedicated code, based on your suggestion in that thread, but I think the idea there was that people were looking for a named function not a recipe.

**Comment by kedashoe** [comment]
Sorry, I actually meant the bigger problem.. wasn't fyyy trying to do the exact same thing in that issue that @davidchambers is here? I know I have also done it. Still maybe too specific for Ramda, just bringing up that thread as this reminded me of it.

I'm all for `pair`! :+1:
