### ISSUE TITLE
Algorithms in Ramda?

### ISSUE THREAD

**Issue by gaurav21r** [ramda/ramda#1311]
I don't know if this fits in the *philosophy of Ramda*, but I'd like to ask the collaborators if there is a possibility to integrate certain **CS Algorithms** inside Ramda.

I believe users of functional JavaScript will also be needed things like `R.quicksort()`, `R.DepthFirstSearch()`, `R.minDistance()`.

Is a definite use case in our case where we can drop in this great library and it takes care of "all the functions" for us (so to speak!)

**Comment by buzzdecafe** [comment]
i'd love to see it but don't think it belongs in the core lib.

**Comment by CrossEye** [comment]
The [Cookbook][co] might be a good place for these.  Others have suggested a Ramda-contrib library, but I don't think anything has happened.

As much as I'd like to see such useful functions in some location easily associated with Ramda, I don't really see how it would work.  Take `quicksort`.  What's it's input?  Does it operate only on lists? On arrays?  On array-like structures (and what would we mean by that here?)  Does it only work on mutually comparable elements?  Or do we use the language's coercion?  Or would one have to supply a comparator?  How about a sort-key-extractor?

If we want to include such a function in Ramda, we need to consider these questions quite carefully.  But if we want to include it as example code, with such API decisions simply documented, we can make whatever choices seem convenient.


  [co]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by gaurav21r** [comment]
@CrossEye  All points noted! Like Ramda functions are overloaded, I was thinking the same for these lagorithmic functions. Eg: User supplies comparator for `quicksort`, if not we use a default.

We may need to create Data Structures too for this, but I'm trying to avoid and researching whether Ramda lists, JS Arrays will work!

@buzzdecafe Great! like @CrossEye said, if not in the core library then where do you suggest? Maybe I can send a sample PR there?

**Comment by gaurav21r** [comment]
@davidchambers I know this is an old PR. I was just waiiting for my organisation to adopt Ramda full time before submitting PRs and that time is near!

I want to send a sample PR based on the the points raised by @CrossEye! Should I do it here only?

**Comment by davidchambers** [comment]
Feel free to open pull requests at any stage, @gaurav21r. The important thing is to ensure that each pull request is concerned with exactly one issue. When proposing new functions via pull requests it's generally advisable to open one pull request per function.

**Comment by gaurav21r** [comment]
@davidchambers When we are ready, I think first I'll open an issue so that you and the other core team members can give your sign off on a proposed API

**Comment by davidchambers** [comment]
Sounds good!

**Comment by CrossEye** [comment]
Issues or PRs are fine.  PRs are especially nice because they give us something more concrete to discuss.  If your thinking is close enough to code to offer a PR, I find those preferable.  If not, an issue is fine.
