### ISSUE TITLE
transforming object keys

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1312]
I'm curious if there's a convenient way of doing this in Ramda:

```coffee
transform = (result) ->
  name: result.name
  id: result.id
  img: result.picture.data.url
```

I find myself doing this rather often. But at the same time, its a pretty simple function so it doesnt seem too unreasonable to just write out the function.

**Comment by asaf-romano** [comment]
+1.

Using ``props`` and ``zipObj``, this is pretty easy to achieve when the properties set is known. It's getting messy once you want to rename a single property (or a small subset).

**Comment by davidchambers** [comment]
I agree that writing ad hoc transformation functions isn't elegant, but I don't see a simple API that would handle your example, @ccorcos.

**Comment by ccorcos** [comment]
Well heres an attempt:

```coffee
transform = R.pickPath({
  name: ['name']
  id: ['id']
  img: ['picture', 'data', 'url']
})
```

At the very least, its point free.

**Comment by CrossEye** [comment]
> Well heres an attempt:

> ```js
> transform = R.pickPath({
>   name: ['name']
>   id: ['id']
>   img: ['picture', 'data', 'url']
> })
> ```

But might one also want to do something like

```js
var transform = R.whatever({
    fullName = person => person.first + ' ' + person.last,
    id: R.prop('id'),
    img: R.path(['picture', 'data', 'url'])
})
```

... or some other transformation than simply `prop`/`path`?

**Comment by davidchambers** [comment]
`R.pickPath` is too narrow to be added to Ramda, in my view, and `R.whatever` is less convenient than a lambda. Lambda seems to be the right tool for this particular job.

**Comment by CrossEye** [comment]
I don't want to argue for `whatever`, as my rationale for bringing it up was only to show that `pickPath` was too limited to be really useful.

I don't think `whatever` with its implied API is generally useful enough for Ramda, but I also don't think that it's necessarily easy to replace it with lambdas.  If I had named functions above, for whatever reasons, then this would be very readable code (modulo a better name for the function):


```js
var transform = whatever({
    fullName: extractName,
    id: getId,
    img: pullImg
});
```

compared to doing this via a lambda:

```js
var transform = obj => {
    fullName: extractName(obj),
    id: getId(obj),
    img: pullImg(obj)
};
```

Still, I think that if someone wants to write this (and give it a good name), the best location would be the [Cookbook][co].

  [co]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by ccorcos** [comment]
Oh nice! The cookbook is a *great* idea!
