### ISSUE TITLE
cannot start an async pipe with a tap

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1314]
The recent changes to pipeP/composeP behavior broke a common pattern I was using:

``` js
function validateString(v)
{
  if (typeof v != "string")
    throw new Error("err");
}

var promiseValueFor = R.pipeP(
  R.tap(validateString),
  () => Promise.resolve(null)
);

promiseValueFor("p");

// => TypeError: (intermediate value).then is not a function
```

The only workaround I could think of (except something silly like promiseValidate) is mixing pipe and pipeP [this way](http://bit.ly/1Msco4E). That's quite ugly and makes pipeP much less appealing as a general way to deal with promises pipelines.

**Comment by asaf-romano** [comment]
Note that the old behavior is not the only way to support such pattern. pipeP/compose could force the Last function to return a promise, so that if my ```tap``` functions throws, the resulting function would actually return a rejected promise (rather than throw synchronously as it did until 0.15.1).

**Comment by asaf-romano** [comment]
Upgrading to 0.17.1 today (from 0.15.1), this turned out to be remarkably painful. First, a lot of our pipeP usage surrounds REST API wrapping, almost always with some post-processing (which wasn't affected), but more often than not, with some pre-processinng as well. e.g.:

```js
var promiseThoseObjectsByIds = pipeP(
  uniq,
  ids => agent.get({ ...}),
  ...post-processing...
);
```
For a simple case like this, I had to merge uniq into the first step.

More complex pattern, involves '``map'`` and ``Promise.all``
```js
var promiseThoseObjectByIds = pipeP(
   map(promiseThatObjectById),
   ::Promise.all,
   ...post-processing...
);
```

Here I had to nest pipeP-pipes into a "parent" pipe.

Another pattern that came up:

```js
  var promiseThatObjectById = pipeP(
    createMapEntry("id"),
    promiseThatObject,
    ...
 );
```

Here I had to manually call Promise.resolve in the first step, loosing point-free goodness.

**Comment by dtipson** [comment]
If you're willing to wrap the initial value in a Promise, you can compose sequences like this just by reducing them (plus some syntax modifcations to make sure the starting point comes last and the list of operations can be passed as a list of arguments): http://bit.ly/1Wu2GWo
