### ISSUE TITLE
groupBy and countBy should use the in-house version of toString

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1330]

**Comment by davidchambers** [comment]
Good idea!

**Comment by CrossEye** [comment]
On vacation and not much online, but this caught my attention.  I don't make sense of it.   `groupBy` and `countBy` (and in general `xxxBy`) are about supplying a function for one's specific problem.   I don't know what a generic `toString` would do.

**Comment by davidchambers** [comment]
> I don't know what a generic `toString` would do.

It would prevent accidental key collisions.

Current behaviour:

```javascript
> R.countBy(R.identity, ['1,2,3', [1, 2, 3]])
{'1,2,3': 2}
```

Proposed behaviour:

```javascript
> R.countBy(R.identity, ['1,2,3', [1, 2, 3]])
{'"1,2,3"': 1, '[1, 2, 3]': 1}
```

Arguably we shouldn't worry about such cases since the provided function is supposed to return a string.

This change would also impact usability: rather than `counts.foo` one would need to write `counts['"foo"']`, which looks pretty strange.

**Comment by asaf-romano** [comment]
ah, I didn't know ```R.toString("foo")``` doesn't return the string as-is (that's pretty strange, btw). If this behavior is here to stay, I take my proposal off the table.

**Comment by davidchambers** [comment]
In as many cases as possible `R.toString` upholds this invariant:

```javascript
R.equals(x, eval(R.toString(x))) === true
```

Having `R.toString('foo')` evaluate to `'foo'` would greatly limit the function's usefulness. `'42'` and `42` would then have the same string representation which would make `R.toString` unsuitable for use as a serializer. Let's not repeat [JSON's mistakes][1]. ;)


[1]: https://github.com/davidchambers/CANON#differences-between-canon-and-json

**Comment by asaf-romano** [comment]
Then the only option here is to special-case the string case (i.e. if the function passed to groupBy/countBy already returned a string, don't run toString on that). This probably doesn't align with ramda's philosophy, and if so I guess I should close this issue.

**Comment by davidchambers** [comment]
`R.toString` can be given as the function argument to `R.countBy` or `R.groupBy`; I don't think these functions should use it internally.

**Comment by asaf-romano** [comment]
So I think it was a mistake to name toString after the native function, because if one isn't aware of the implementation details (but is aware of how js objects work), he'd expect groupBy(identity) and groupBy(toString) to do pretty much the same thing.
