### ISSUE TITLE
R.assocPath should not convert arrays to objects

### ISSUE THREAD

**Issue by epeli** [ramda/ramda#1332]
I have a two dimensional array:

```js
var grid = [[1,1], [2,2]];
```

and I want to update a single cell

```js
R.assocPath([1,0], "foo", grid);
```

but to my surprise arrays where converted to objects: http://bit.ly/1MjZKUU

**Comment by svozza** [comment]
I don't think assocPath is supposed to work on lists.

**Comment by davidchambers** [comment]
I suggest using lenses:

```javascript
const fst = R.lensIndex(0);
const snd = R.lensIndex(1);

const grid = [[1, 1], [2, 2]];

const fst = R.lensIndex(0);
const snd = R.lensIndex(1);

const grid = [[1, 1], [2, 2]];

R.set(R.compose(fst, fst), 0, grid);  // => [[0, 1], [2, 2]]
R.set(R.compose(fst, snd), 0, grid);  // => [[1, 0], [2, 2]]
R.set(R.compose(snd, fst), 0, grid);  // => [[1, 1], [0, 2]]
R.set(R.compose(snd, snd), 0, grid);  // => [[1, 1], [2, 0]]
```

I'd like to *remove* `R.assocPath`, potentially, since lenses solve this problem in a general way. Removing a useful function can be challenging politically, so `R.assocPath` is likely to stay, but I don't think we should make it support arrays given the existence of lenses.

**Comment by oscarlgz** [comment]
I see the philosophical point of not having assocPath work on lists, but in practice I don't think it makes much sense. Composing lenses to set nested paths is a lot less performant, and to set paths dynamically you have to use helper functions. Errors will also be thrown for undefined paths.

http://jsperf.com/ramda-assocpath-vs-set

**Comment by buzzdecafe** [comment]
>  I believe I've suggested this before

Yes, you suggested this before: https://github.com/ramda/ramda/issues/773. I was opposed, mostly on the grounds you just stated.
