### ISSUE TITLE
Compose with higher order arity

### ISSUE THREAD

**Issue by cscalfani** [ramda/ramda#1341]
I would like to code the following:

```js
R.compose(console.log, R.multiply, R.inc)(3)(4); // displays 16
```

The problem with `R.compose` is that it **only** allows for functions of arity of 1.

Is there an alternative version of compose?

**Comment by davidchambers** [comment]
> Is there an alternative version of compose?

See the last of the three functions proposed in https://github.com/ramda/ramda/issues/1318#issuecomment-132005376. It could be used to create the desired (curried) binary function:

              +-------+               +------------+
    --- a --->|  inc  |--- inc(a) --->|            |
              +-------+               |  multiply  |                            +---------------+
    --- b --------------------------->|            |--- multiply(inc(a), b) --->|  console.log  |--- console.log(multiply(inc(a), b)) --->
                                      +------------+                            +---------------+

**Comment by TheLudd** [comment]
Championing my suggestion for `compose` again. The desired behavior would also be accheived by implementing curry according to #732 and defining compose as 
```
var compose = curry(function(f, g, x) {
  return f(g(x))
});
```
Then `compose(R.multiply, R.inc)(3,4) //=> 16`

**Comment by paldepind** [comment]
@TheLudd Doesn't that leave you with the same problems as in #1318. If `R.inc` had been a binary function and you wanted it to receive both 3 and 4 you'd have been out of luck.

```js
compose(R.multiply(2), R.add)(3, 4) //=> 14
```

You win some you loose some. It does not seem like a compose thats better at handling functions with higher order arity. Only different.

**Comment by TheLudd** [comment]
@paldepind Indeed. When the last function is binary then you need another compose for that, which I have called `composeBinary` in other issues. Going down that path is very preferable to me since the implementations become very simple and it is clear what how the resulting function will work when composing. One could argue that we will then need one function for each airity but I don't think so. I do believe that unary and binary are the only ones needed to cover 99% of the cases out there.

**Comment by paldepind** [comment]
> Going down that path is very preferable to me since the implementations become very simple

Well. Then you have `compose`, `composeBinary`, `composeAll` and `composeBinaryAll`. I'm not convinced that will end up being simpler.

> it is clear what how the resulting function will work when composing.

I think our old non-curried compose was equally simple.

But I can certainly see the advantages of the approach.

The only think I'm opposed to is not having a variadic curry function. It makes the API more cumbersome with only theoretical benefit.

```js
R.compose(f, g, h) // Ahh!
R.compose([f, g, h]) // Why? :(
```

**Comment by TheLudd** [comment]
> Well. Then you have compose, composeBinary, composeAll and composeBinaryAll. I'm not convinced that will end up being simpler.

Simpler is exactly what I think it is. I agree that it might feel a bit cluttered but I believe I would prefer this over the other. But no solution is perfect.

> The only think I'm opposed to is not having a variadic curry function

You mean compose? =)

Yes I agree. If a function is fully varardic, putting the arguments in an array makes no difference.

**Comment by paldepind** [comment]
> Simpler is exactly what I think it is. I agree that it might feel a bit cluttered but I believe I would prefer this over the other. But no solution is perfect.

In terms of implementation it won't be simpler. But one can of cause argue that each function is simpler. But when you have a variadic `compose` you don't need separate binary and array versions. That is a win IMO.

> You mean compose? =)

Yes :)

> Yes I agree. If a function is fully varardic, putting the arguments in an array makes no difference.

Great! Ramda users compose a lot. I think requiring arrays in anything but the binary case would add unnecessary visual noise.

**Comment by paldepind** [comment]
> Simpler is exactly what I think it is. I agree that it might feel a bit cluttered but I believe I would prefer this over the other. But no solution is perfect.

In terms of implementation it won't be simpler. But one can of cause argue that each function is simpler. But when you have a variadic `compose` you don't need separate binary and array versions. That is a win IMO.

> You mean compose? =)

Yes :)

> Yes I agree. If a function is fully varardic, putting the arguments in an array makes no difference.

Great! Ramda users compose a lot. I think requiring arrays in anything but the binary case would add unnecessary visual noise.

**Comment by TheLudd** [comment]
> In terms of implementation it won't be simpler.

Is [this implementation](https://github.com/ramda/ramda/issues/1341#issuecomment-134512299) not simpler?

> But when you have a variadic compose you don't need separate binary and array versions

I do think they are needed in order to avoid  `useWith`.

**Comment by paldepind** [comment]
> Is this implementation not simpler?

Yes. Of course. That is an absolutely beautiful implementation. But we have to add `composeBinary`, `composeAll` and `composeBinaryAll` on top of that as well.

**Comment by TheLudd** [comment]
> But we have to add composeBinary, composeAll and composeBinaryAll on top of that as well

And my point is that they will all individually be as beautiful. 

It is obvious that making functions this specific requires more functions. They will all be very small and only do one specific thing. When I started using ramda I came under the impression that this was what the library were aiming for. Perhaps I misunderstood or perhaps we have different interpretations of what "one specific thing" means.

Anyway. This is where I stand in this question and I understand that there are trade offs. I also understand that this kind of approach would be a very big change for ramda. Many returned functions use `arguments` instead of specific arity so I get that this would be a big change. If other disagree with me I wont push further.

**Comment by davidchambers** [comment]
Check out the esoteric [`S.meld`][1]:

```javascript
> S.meld([R.inc, R.multiply])(3)(4)
16
> S.meld([R.inc, R.multiply])(3, 4)
16
```

If there's interest we could have Ramda provide a variadic version of this function.


[1]: https://github.com/plaid/sanctuary#meld
