### ISSUE TITLE
converge with lens

### ISSUE THREAD

**Issue by kmcclosk** [ramda/ramda#1342]
Based on my reading of the converge example, I expected the following to be equivalent:

var xLens = R.lens(R.prop('x'), R.assoc('x'));
var xLens = R.converge(R.lens,R.prop,R.assoc)('x');

However the converge version does not construct a proper lens. Is this expected?

**Comment by CrossEye** [comment]
I had to think this one through a bit, as I was surprised too.

The problem is one of conflicting arities.  `prop` is arity 2, `assoc` is arity 3.  So the function you're calling xLens is an arity 3 function (taking max arity of the helper functions.)  Passing just `x` to it won't help.

It's not pleasant, but you could do something like this if you chose:

    var xLens = R.converge(R.lens, p => R.prop(p), p => R.assoc(p))('x');

This is a limitation of `converge` that I had never really noticed.  It's not earth-shattering, but it is disappointing.

**Comment by kmcclosk** [comment]
Appreciate the feedback and thanks for this library.

**Comment by CrossEye** [comment]
I'm assuming this was an attempt to play around with `converge`.  I didn't point out that you can also create `xLens` most easily with another Ramda function:

    var xLens = R.lensProp('x');

... just in case.  :smile:

**Comment by kmcclosk** [comment]
Actually, it was for this original case that I discovered that it didn't work as I might have expected:

var lensPath = R.converge(R.lens,R.path,R.assocPath)([ 'key0','key1' ]);

But I saw it another Github issue a lensPath by scott-christopher that does the trick:

var lensPath = R.reduce(function(lens,prop) {
    var propToLens = R.ifElse(R.is(Number), R.lensIndex, R.lensProp);
    return R.compose(lens, propToLens(prop));
}, R.identity);

**Comment by jethrolarson** [comment]
So is there no issue?

**Comment by TheLudd** [comment]
> var xLens = R.converge(R.lens,R.prop,R.assoc)('x');
>
> However the converge version does not construct a proper lens. Is this expected?

That has definitely worked before but I believe this commit broke it: https://github.com/ramda/ramda/commit/43b57125e746f7ec9a8751e8a0a77869cbd9d962#diff-3556211e3b9aef02a18018b0f93a79caR35

**Comment by benperez** [comment]
I would expect `R.converge` to exhibit the same behavior before that commit. It seems like the change in behavior probably came [here](https://github.com/ramda/ramda/commit/47e82b2541d48934a2cd6f2fc3d881b2b408082c#diff-3556211e3b9aef02a18018b0f93a79ca). Previously the function would have been invoked right away with any number of arguments provided, now it's waiting for all 3 that `R.assoc` wants.
