### ISSUE TITLE
Additional functions

### ISSUE THREAD

**Issue by Chris911** [ramda/ramda#1343]
I remember reading in an issue here that it's possible to defined extra functions to Ramda. We use `indexBy` (from the [cookbook](https://github.com/ramda/ramda/wiki/Cookbook#indexby)) everywhere in our codebase but we'd like to have it directly accessible as `R.indexBy` rather than having to either declare it everywhere or go through utility files. 

Is there a proper way to do this with Ramda? Looking at the soon to be Ramda manual it seems there's a way to ["Add additional functionality"](http://ramdajs.com/0.17/manual/02-functions/Enhancing.html)?

Thanks

**Comment by buzzdecafe** [comment]
you could just attach it to the `R`.

aside -- probably to @CrossEye who i believe wrote the outline -- "Add additional functionality"? How about "Add functionality"? or even "Extend Ramda"?

**Comment by Chris911** [comment]
What's the recommended way to attach a function to `R` globally?

**Comment by buzzdecafe** [comment]
i don't know that it's *recommended*, but you could simply `R.myFn = myFn`

**Comment by Chris911** [comment]
For sure that works but then we need an internal file that requires ramda, adds new function and exports the extended `R` object. I was wondering if there was a way to do this globally and keep `require('ramda')`. 

I don't want this issue to become a JS tutorial. I was just under the impression ramda supported some kind of way to declare additional functions that would be loaded in the library.

**Comment by CrossEye** [comment]
That section of the manual is supposed to describe functions like `tap`, `wrap`, and `invoker` that extend the abilities of existing functions rather than extending Ramda itself.

(Somehow I didn't put a proper note on the TODO there.)

There is at the moment no way to add your own functions to the library except as @buzzdecafe mentioned.  Do you have a suggested alternate mechanism?

**Comment by Chris911** [comment]
Alright thanks. 

No not really. I think at this point this has more to do with JS in general rather than ramda. What I had in mind initially is something like a `.ramda-declarations.js` file that would be loaded by the lib on boot and attach functions in there. But it's easily debatable this is something we should build ourselves vs having it part of the project. 

I think the easiest way for us will just be to have a `ramda-ext.js` file that exports `R` overloaded with some more functions.

**Comment by davidchambers** [comment]
> I think the easiest way for us will just be to have a `ramda-ext.js` file that exports `R` overloaded with some more functions.

Yes, that's what I recommend. I did so in the past (with a different package) and didn't run into any issues.

**Comment by Chris911** [comment]
Thanks for your help. Closing.
