### ISSUE TITLE
Test cases fail in `testem`

### ISSUE THREAD

**Issue by benjycui** [ramda/ramda#1348]
It seems that Ramda use Test'em to test the compatibility of browsers, see #244. So I run Test'em in Ramda, but most of the test cases are failed. Is that an issue?

**Comment by davidchambers** [comment]
> I run Test'em in Ramda

What did you do, exactly? I'm not familiar with Test'em.

**Comment by CrossEye** [comment]
We were actually using SauceLabs.  I think @buzzdecafe got tired of being the only one ever to maintain them, and when we ran into issues with multiple builds, they were disabled.  It would be nice to get them back, but I don't even recall the process.

**Comment by benjycui** [comment]
@davidchambers Just `cd` into the folder of Ramda, and run `testem`, and then open browser. I am not sure if you read [Test'em's doc](https://github.com/airportyh/testem).

@CrossEye SauceLabs is good, and if you are interested in getting it back, I can try.

**Comment by scott-christopher** [comment]
It looks like the majority of the test failures can be addressed by just updating `ramda.js` to `dist/ramda.js` in `testem.json`. I'm happy to chip away and address the remaining.

**Comment by davidchambers** [comment]
> I'm happy to chip away and address the remaining.

I'm already on the case. :)

**Comment by benjycui** [comment]
@scott-christopher It seems that this solution does not work on my computer, and I had run `npm run build` before `testem`. Anyway, waiting for @davidchambers ' solution.

**Comment by scott-christopher** [comment]
Yep sorry, that too. :) You should soon just be able to `npm run testem` and it will take care of that for you.

**Comment by CrossEye** [comment]
One other way to test in the browser:  open `lib/test/index.html` in a browser.  :smile:

That used to be one of my common ways of testing Ramda.  I don't know just how out-of-date it might be now.

**Comment by benjycui** [comment]
Close now.

BTW, do you want to use antd? We are going to provide English documentation.
