### ISSUE TITLE
Special case strings (charAt)

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#1355]
Things like this currently *mostly* work:

R.reduce(R.max, "a", "abcdef")

However, it relies on strings supporting indexing, which is not the case in IE 7. If it were special cased to use charAt instead, then it would work across the board.

**Comment by CrossEye** [comment]
See current discussions in #1275.

**Comment by davidchambers** [comment]
We've decided not to have `R.reduce` operate on strings. One can, of course, use `R.split('')` to split a string into a list of single-character strings before folding.
