### ISSUE TITLE
Equivalent to lodash's uniqueId()

### ISSUE THREAD

**Issue by alexcarruthers** [ramda/ramda#1360]
I'm trying to migrate from Ramda to lodash, and one thing we use in tests quite often is `uniqueId()`, which is useful for making test users and the like (ie fields that should be unique). I'm wondering if it's in the Ramda philosophy/whatever to have a function like this? Also, if there's something that already exists for this, please let me know, cause I can't find anything.

**Comment by TheLudd** [comment]
Will probably not go into ramda since this seems to be a non pure function. But there seems to be plenty of alternatives available for this specific task. https://www.npmjs.com/search?q=unique+id

**Comment by jdalton** [comment]
[lodash.uniqueid](https://www.npmjs.com/package/lodash.uniqueid) or `require('lodash/utility/uniqueId')`.

**Comment by CrossEye** [comment]
Yes, this one is definitely outside Ramda's philosophy, in which a function called with the same parameters (even if that's no parameters) should get the same results every time.
