### ISSUE TITLE
indexOf does not work with list of functions or objects

### ISSUE THREAD

**Issue by vyrak** [ramda/ramda#1362]
I'm using v0.17.1. When checking for the index of an element in, either a list of functions or list of objects, it always returns `0`. This also prevents me from relying on `R.contains`.

``` javascript
function foo() {}
function bar() {}
var list = [foo, bar];
R.indexOf(foo, [bar]); // returns 0 instead of -1

var baz = {};
R.indexOf(foo, [baz]); // returns -1
```
``` javascript
var foo = {};
var bar = {};
var list = [foo, bar];
R.indexOf(foo, [bar]); // returns 0 instead of -1

function baz() {}
R.indexOf(foo, [baz]); // returns -1
```

**Comment by buzzdecafe** [comment]
looks like the problem is in `equals` which, if the functions are not identical, treats `function` like an `object`, and recursively checks the objects' keys for equality. That is not particularly useful when comparing functions.

**Comment by CrossEye** [comment]
> That is not particularly useful when comparing functions.

No.  It's certainly not a case I would have considered, but it's something worth fixing.

**Comment by davidchambers** [comment]
Thanks to #1235, functions are now compared by identity:

```javascript
> var R0 = require('ramda')
> var R1 = require('.')
> var f = function() {}
> var g = function() {}
> R0.equals(f, f)
true
> R1.equals(f, f)
true
> R0.equals(f, g)
true
> R1.equals(f, g)
false
```

Thanks to #1096, `R.indexOf({}, [{}])` evaluates to `0`. This is intended behaviour.

**Comment by buzzdecafe** [comment]
looks like we need a test to guarantee correct behavior for functions
