### ISSUE TITLE
How to apply exact arguments for variadic function?

### ISSUE THREAD

**Issue by anton-rudeshko** [ramda/ramda#1366]
I need to call variadic or curried functions with all arguments provided *before* call.

```js
var log = console.log.bind(console);
var promise = Q('promised');

var applyExactArgs = compose(R.nAry(0), R.partial);

promise.then(R.add(1, 2)); // this is calling result function right away
promise.then(R.partial(R.add, 1, 2)); // this is populating all args, but not calling

// usual R.partial
promise.then(R.partial(log, 'Hello', 'World')); // → outputs "Hello World promised"

// What I need
promise.then(applyExactArgs(log, 'Hello', 'World')) // → outputs "Hello World", ignores all additional not pre-applied args.
```

Is there some function for this already? Or better solution?

**Comment by raine** [comment]
If you happen to have access to prettier lambda syntax, in this case it's quite readable option.

**Comment by anton-rudeshko** [comment]
Even better:

```js
var min = magicFunction(2, Math.min);
// min — curried, has 2 real args, but must be called one more time to get result
var min1 = min(1);
var min1and2 = min1(2);
min1and2(0, -1); // 1, all additional args are ignored
```

How `magicFunction` should be defined?

> If you happen to have access to prettier lambda syntax, in this case it's quite readable option.

What do you mean?

**Comment by raine** [comment]
Is [nAry](http://ramdajs.com/docs/#nAry) what you're looking for?

I meant `promise.then(() => console.log('Hello world'))`

**Comment by anton-rudeshko** [comment]
Yeah, lambda looks pretty good.
nAry limits count of args, but i need to have result of it as callback. I need to have it called *one more time* to have a result.

**Comment by CrossEye** [comment]
Ramda does not have a function for this.  But I'm certain of the name you should use if you create one: [`thunk`][th].  I don't have a particular implementation in mind, though.


  [th]: https://en.wikipedia.org/wiki/Thunk#Functional_programming

**Comment by davidchambers** [comment]
It sounds as though a pull request for `R.thunk` may be accepted.
