### ISSUE TITLE
R.equals does not dispatch on nested values

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#1368]
Example:
```js
var left = S.Left(1);
var right = S.Right(1);
console.log(right.equals(left)); //=> false
console.log(R.equals(left, right)); //=> false
console.log(R.equals([left], [right])); //=> true
```
Right now only the top level checks for an `equals` method on the objects, once you get to the internal `_equals` there is no more dispatching.

**Comment by davidchambers** [comment]
Thanks for reporting this issue, @kedashoe. This is certainly not desirable behaviour. I'll fix it presently.
