### ISSUE TITLE
Meteor package version outdated

### ISSUE THREAD

**Issue by beobast** [ramda/ramda#1375]
If I do `meteor add ramda:ramda` I get ramda v0.17.1

If I create a meteor package and write `api.use('ramda:ramda')` insde package.js, I get ramda v0.14.0

```
=> Started proxy.                             
=> Started MongoDB.                           
                                              
Changes to your project's package version selections:
                                              
ramda:ramda  added, version 0.14.0            

=> Started your app.                          

=> App running at: http://localhost:3000/
```

**Comment by ccorcos** [comment]
https://github.com/MeteorPackaging/ramda-wrapper

should be at v17.1 now

**Comment by ccorcos** [comment]
perhaps one of your pacakges has a constraint on version 14.0. There are many breaking changes between 14 and 17

**Comment by CrossEye** [comment]
Thanks, @ccorcos!
