### ISSUE TITLE
R.indexOf is quite slow

### ISSUE THREAD

**Issue by jseppi** [ramda/ramda#1376]
I was writing some code that made considerable use of `R.contains` and noticed that the performance was pretty poor so I dug a little into the underlying code. It appears the performance issue is `R.indexOf`, which is considerably slower (orders of magnitude) than browser-native `indexOf`. Here is a jsPerf test illustrating the difference: http://jsperf.com/ramda-indexof/2

For the code I was writing, I was calling `R.contains` about 400 times successively, and that section of code was taking over 3 seconds. Using browser-native `indexOf` has reduced the time to about 16 milliseconds.

**Comment by davidchambers** [comment]
[`R.indexOf`][1] (and all other Ramda functions except [`R.identical`][2]) use [value-based equality][3], so it's unreasonable to expect its performance to be comparable with that of [`Array.prototype.indexOf`][4].

That said, if we can improve the performance of the function, we should. :)


[1]: http://ramdajs.com/docs/#indexOf
[2]: http://ramdajs.com/docs/#identical
[3]: https://github.com/ramda/ramda/pull/1096
[4]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by paldepind** [comment]
We might consider adding a `R.indexOfWith` so that people who does not need value equality can use `R.indexOfWith(R.identitcal)` to get better performance.

**Comment by jseppi** [comment]
:+1: Thanks for taking the time to think through this issue. I appreciate all the devs' hard work on Ramda!

**Comment by buzzdecafe** [comment]
> We might consider adding a `R.indexOfWith` so that people who does not need value equality can use `R.indexOfWith(R.identitcal)` to get better performance.

:+1: 

(although i would like to find a way to chain more prepositions together, for example, an Australia-only version: `R.indexOfWithDownUnder`)

**Comment by paldepind** [comment]
In this specific use case using `R.containsWith(R.identical)` would be the solution.

**Comment by davidchambers** [comment]
> In this specific use case using `R.containsWith(R.identical)` would be the solution.

In fact, we'd want [`R.containsBy`][1] rather than [`R.containsWith`][2].


[1]: https://github.com/ramda/ramda/pull/1353
[2]: http://ramdajs.com/docs/#containsWith

**Comment by TheLudd** [comment]
What about http://ramdajs.com/0.17/docs/#findIndex

**Comment by davidchambers** [comment]
Thanks, @TheLudd! I didn't know about (or had forgotten about) [`R.findIndex`][1].


[1]: http://ramdajs.com/docs/#findIndex
