### ISSUE TITLE
R.all always returns true for empty lists

### ISSUE THREAD

**Issue by TGOlson** [ramda/ramda#1380]
`R.all` returns `true` for any predicate when passed an empty list. Is this the intended behavior? 

```js
R.all(R.equals('a'), []) // => true
```

FWIW, `R.any` returns `false` when passed an empty list.

**Comment by davidchambers** [comment]
All zero of the values in `[]` are equal to `'a'`. ;)

**Comment by TGOlson** [comment]
Indeed, and it looks like the native `array.every` seems to concur, thanks for the response.

**Comment by CrossEye** [comment]
@TGOlson 

Another way to think about this is how `all` and `any` interact:

    all(pred, list) ≍  ¬any(¬pred, list))
    any(pred, list) ≍  ¬all(¬pred, list))

So

    R.all(R.equals('a'), []) ≍ R.complement(R.any(R.complement(R.equals('a')), []))

The right-hand-side will be `false` only if this is `true`:

    R.any(R.complement(R.equals('a')), [])

which is true only if there is some element of `[]` which is not equal to 'a'.  But there is no element of `[]`, so this is `false` and the original statement is `true`.

This is what's known in mathematics as a [vacuous truth][vt].

  [vt]: https://en.wikipedia.org/wiki/Vacuous_truth
