### ISSUE TITLE
uniq/union performance improvement suggestion

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1386]
Value-based equality and dispatching issues killed my terrible ``Set`` idea. The sad thing is that my 10:1 performance comparison back done was done, iirc, when Ramda still relied on reference-equality. 

The situation is even worse now: http://bit.ly/1FK9p1j

Note this is by no means a "theoretical" issue. For a fat array of roughly-same-shape objects (admittedly somewhat complex shape), I had to switch a project to use my implementation of uniqIdnetical (and also make the elements identical again... long story) to get back to sensible performance (it was so bad Fx popped up the "slow script" dialog very often).

On the positive side, ``toString`` was not implemented back then, and I think it (or what I'm suggesting in #1384) could help here. For ``uniq``, the algo would basically be: ``pipe(filter(eqBy(toString))``, currentUniq). union can be altered similarly.

A potential problem with this approach is that it enforces even more the requirement to either dispatch both ``equals`` and ``toString``, or none of them.

**Comment by CrossEye** [comment]
I'm afraid I don't follow what you're actually suggesting.

**Comment by asaf-romano** [comment]
Roughly this: http://bit.ly/1iXNmQ0

**Comment by paldepind** [comment]
I'm hesitant to believe that is any faster. `R.toString` certainly adds an overhead. Consider for instance a short list, say 20 element, of a very nested structure. Converting them all to strings, adding them to an object and pulling them back out will likely be slower than just running our current O(n^2) uniq algorithm.

**Comment by asaf-romano** [comment]
I'll try do some tests next week. I hope you are wrong :), because the current implementation is very slow.

**Comment by asaf-romano** [comment]
So I'm afraid you're right :-/

**Comment by paldepind** [comment]
Are you having "real world" problems with `uniq`? I'd love to hear what your data is like.

**Comment by asaf-romano** [comment]
Yes, see my first comment (I worked around them by implementing uniqIdentical and utilizing some cache magic).
