### ISSUE TITLE
do not rely on .constructor.name in R.toString

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1393]
As mentioned in https://github.com/ramda/ramda/issues/1140#issuecomment-119953239, the implementation of `_toString` currently contains `x.constructor.name !== 'Object'`. Apparently not every environment provides a `name` property on each function. Instead we could use a regular expression such as `^function (\w*)` to extract a function's name from its string representation.

**Comment by kujon** [comment]
:+1:, it doesn't play nicely with ramda-fantasy `R.is(IO, foo)`.

**Comment by davidchambers** [comment]
Could you elaborate, @kujon? I don't see the connection to `R.is`.
