### ISSUE TITLE
R.ap() does not dispatch correctly when using native Array as functor

### ISSUE THREAD

**Issue by branneman** [ramda/ramda#1399]
In the light of this functor:

```js
// Identity
var Identity = function(val) {
  this.val = val;
};
Identity.prototype.map = function(fn) { // Functor
  return Identity.of(fn(this.val));
};
Identity.prototype.ap = function(app) { // Apply
  return app.map(this.val);
};
Identity.of = function(val) { // Applicative
  return new Identity(val);
};
```

The native JavaScript Array is a functor by the Fantasy Land definition. In addition, I've implemented the Apply and Applicative spec directly on the Array prototype:
```js
Array.prototype.ap = function(app) { // Apply
  return this.map(fn => app.map(fn));
};
Array.of = function(val) { // Applicative
  return [val];
};
```

Then when I'd like to use my Apply, this works for my Identity functor, but not for my Array functor:
```js
R.ap(Identity.of(R.add(5)), Identity.of(50)); //=> Identity(55)
R.ap([R.add(3), R.add(5)], Identity.of(50)); //=> []
```

I would expect the last line to return the same as using `.ap()` directly on the functor:
```js
[R.add(3), R.add(5)].ap(Identity.of(50)); //=> [Identity(53), Identity(55)]
```
Instead, I get an empty array.

My guess would be that Ramda's `.ap()` does not dispatch correctly somehow when I'm extending JavaScript's native Array as a functor. From a quick scan of the ramda source, I'd say the problem is in the hardcoded check for [`isArray` within `hasMethod`](https://github.com/ramda/ramda/blob/v0.17.1/src/internal/_hasMethod.js#L22).

Is this expected behaviour? For me it's certainly not.

I realize that piggybacking the `.ap()` implementation on top of the native JavaScript Array is probably not the best solution, but adding another array-like type to JavaScript is not a great solution either imho.

**Comment by davidchambers** [comment]
I'd like to remove the Array exclusion from `_hasMethod`. From memory, though, @CrossEye is opposed.

**Comment by CrossEye** [comment]
I don't remember such a discussion.

But unless my memory fails me, that exclusion is how we run Ramda's functions rather than the native `map`, `filter`, `reduce`, etc.

I'm guessing this is a bug in our internal `ap` function that's causing the current behavior.  It really has had little workout, I believe, and I wouldn't be surprised if we misunderstood the spec when it was implemented, thinking that `a.ap(b)` required `a` and `b` to be of the same `Apply` type.

I will try to look into it, but I'm afraid it won't be until tomorrow at the earliest.

As to wanting to dispatch on lists, that might be more difficult.  I'm really not sure how we could comfortably do that and yet still handle those functions we want to implement ourselves.

**Comment by davidchambers** [comment]
> I don't remember such a discussion.

With the help of Gmail search I was able to find the [exchange][1].


[1]: https://github.com/ramda/ramda/pull/1295#issuecomment-123403131

**Comment by CrossEye** [comment]
Ok, I do remember _that_.  But that doesn't sound like a discussion about removing it, or opposition from me to doing so.

I don't have any strong attachment to our mechanism for dispatching to appropriate functions or any objection to changing it.  But I want to ensure that the functions that Ramda actually creates for operating on the types it's claiming, especially lists, in fact do get called.  We have claimed `ap` for lists (and probably implemented it badly), so we cannot also dispatch `ap` when called on a list.

How we do that, though, doesn't make much difference to me.

**Comment by CrossEye** [comment]
This might not work so well typing on my phone, but I think that getting this to work might be as simple as adding a pair of square braces in the `ap` implementation:

### Current ###

```js
module.exports = _curry2(function ap(fns, vs) {
  return _hasMethod('ap', fns) ? fns.ap(vs) : _reduce(function(acc, fn) {
    return _concat(acc, map(fn, vs));
  }, [], fns);
});
```

### Suggested ###

```js
module.exports = _curry2(function ap(fns, vs) {
  return _hasMethod('ap', fns) ? fns.ap(vs) : _reduce(function(acc, fn) {
    return _concat(acc, [map(fn, vs)]);
  }, [], fns);
});
```

I will try to test when I'm in front of a computer.

**Comment by davidchambers** [comment]
I have a patch to remove `_hasMethod`. I'll open a pull request within the hour.

**Comment by CrossEye** [comment]
Ok, well I'll look at it tomorrow.  I'm looking forward to seeing if you have a way to solve @branneman's issue.  It seems a fairly fundamental conflict with Ramda's claiming `ap` on lists.

Cheers!

**Comment by davidchambers** [comment]
I've just confirmed that #1400 resolves this issue. It does so by replacing

```javascript
_hasMethod('ap', fns) ? fns.ap(vs) : ...
```

which expands to

```javascript
fns != null && !_isArray(fns) && typeof fns[methodName] === 'function' ? fns.ap(vs) : ...
```

with

```javascript
typeof fns.ap === 'function' ? fns.ap(vs) : ...
```

so we dispatch to an `ap` method if available regardless of the type of `fns`.

**Comment by branneman** [comment]
Sweet! :+1:

**Comment by CrossEye** [comment]
My suggestion above handles the Identity case, but changes the behavior for two lists.  It's not clear to me that it's doing something wrong, though.

```js
ap([R.add(3), R.add(5)], Identity.of(50)); //=> [Identity(53), Identity(55)]
ap([R.multiply(2), R.add(3)], [1, 2, 3]); //=> [[2, 4, 6], [4, 5, 6]]
```

You can see this [in the repl][re].

The current behavior of the latter snippet would be to return `[2, 4, 6, 4, 5, 6]`, a flattened list.  I'm still trying to figure out if the FL laws dictate one over the other or if either would be lawful.  But I certainly prefer this unflattened behavior if it's legitimate.


  [re]: http://bit.ly/1G4IzBf
