### ISSUE TITLE
InvertObj yields unexpected results when called with a deep nested object

### ISSUE THREAD

**Issue by dumconstantin** [ramda/ramda#1402]
```javascript
var obj = {
    a: { foo: 'bar' },
    b: { baz: 'bam' }
}
var invertedObj = R.invertObj(obj); // Object {[object Object]: "b"}
```
- Prop "a" is lost without trace (this also happens if both "a" and "b" have the same value .e.g Object {foo: "b"})
- Object.keys(invertedObj).length !== Object.keys(obj)
- The initial value is replaced by its toString() value making this operation irreversible.

This is very subtle bug to figure out, maybe an error/complete invalidation of result might save the day? Or a debate if the benefits of this function out weight the possible bugs that might occur?

The following is a naive JSON implementation but does it make sense?

```javascript
  // Extracted from https://github.com/ramda/ramda/blob/master/src/invertObj.js

  // Add N space characters together
  var spacesN = R.compose(R.join(''), R.times(R.always(' ')));
  var history = [];
  var newKey = "";

  // Added conditional
  if (typeof obj[key] === 'object') {
    newKey = JSON.stringify(obj[key]);
  } else {
    newKey = obj[key]
  }
  // Makes sure duplicates don't overwrite each other
  if (history.indexOf(newKey) !== -1) {
     newKey += spacesN(idx);
  }
  history.push(newKey);
  out[newKey] = key;
```
Of course, the above code might introduce even more subtle bugs.

**Comment by CrossEye** [comment]
This function won't lose the duplicate: [`invert`][in].

I'm afraid that neither makes much sense if your values are not Strings (or easily converted to Strings.) 

Could you put your code together as a complete sample function, either here or in a gist, or in the [repl][re]?


  [in]: http://ramdajs.com/docs/#invert
  [re]: http://ramdajs.com/repl/

**Comment by dumconstantin** [comment]
I've put some code together here:

da7edbdebcefe605095e8b2031c9c2316203c4fa

If this is a good idea I can add further support for non-primitive types and get some tests going for those.

**Comment by CrossEye** [comment]
Ok, I see what you're doing.  Honestly, this seems like quite bizarre behavior to me.

My thought is that this is simply a case of "Doctor it hurts when I do _this_."  "Then don't _do_ that!".

I simply don't see a good reason to use `invert` on objects that aren't simple, one-level deep data objects.  If you need more sophisticated processing, then you probably need a different tool.

What do others think?

**Comment by davidchambers** [comment]
I think this would be asking too much of `invertObj`.

**Comment by dumconstantin** [comment]
I totally agree, the scope would just expand. An object manipulation library would be better suited for this.

Maybe adding a heads up to the invertObj docs instead?
b67ba27819815bd2284387c75db0e546b876b30a

Just for the reference, my use case was something on the lines:
```javascript
var changeFilename = R.compose(R.inverObj, R.mapObj(R.add('path/to/file')), R.invertObj)

changeFilename({
  'filename': jsonData
  ....
})
//=> {
  'path/to/filename': jsonData
}
```

**Comment by raine** [comment]
Check out `mapKeys` in the Cookbook: https://github.com/ramda/ramda/wiki/Cookbook#map-keys-of-an-object

```js
var changeFilename = mapKeys(R.add('path/to/file'));
```

**Comment by dumconstantin** [comment]
Amazing! Thank you for that, makes total sense!

Should I do a pull request for adding to the invertObj docs? https://github.com/ramda/ramda/commit/b67ba27819815bd2284387c75db0e546b876b30a

**Comment by CrossEye** [comment]
Yes, that would be worth including in the docs.  Thanks!

**Comment by dumconstantin** [comment]
Great! I did a pull request just now https://github.com/ramda/ramda/pull/1407
I think its safe to close this issue thread. Thanks for all the help!
