### ISSUE TITLE
It would be nice to have a flatMap function

### ISSUE THREAD

**Issue by ccapndave** [ramda/ramda#1403]
Since this is a pretty common and widely understood tool in functional languages it would be nice to have a `List` implementation for Ramda.

**Comment by TheLudd** [comment]
I think what you are looking for is [`chain`](http://ramdajs.com/docs/#chain)

**Comment by ccapndave** [comment]
Any reason why it is called `chain` and not `flatMap`?

**Comment by TheLudd** [comment]
Because it is [fantasy-land](https://github.com/fantasyland/fantasy-land#chain) compatible I think

**Comment by ccapndave** [comment]
What do people think about adding an alias?

**Comment by TheLudd** [comment]
> What do people think about adding an alias?

People think "no" :)

https://github.com/ramda/ramda/issues/859
https://github.com/ramda/ramda/pull/574#issuecomment-64124850

**Comment by TheLudd** [comment]
I do also beleive that "chain" is a common name just like "flatMap". Another name for the same function is "bind". https://github.com/cwmyers/monet.js#bind-alias-flatmap-chain

**Comment by ccapndave** [comment]
Ok, I do understand the reluctance to add aliases.  My problem here was simply that I didn't know that `chain` was the same as `flatMap`, so I looked for `flapMap` in the docs, couldn't find it and gave up.  What about a documentation solution to this problem?  So perhaps in the list of functions on the left there could be common aliases (like `flatMap`, `foldL`, etc) in a different colour which simply link to their equivalent Ramda function.  I don't mind learning new names for things, but I need to know they exist in the first place :)

**Comment by TheLudd** [comment]
There has been a discussion about an "aka" tag so that you could search for "flatMap" and get "chain". Don't know what happened there...

**Comment by davidchase** [comment]
@ccapndave if you do a `cmd/ctrl + f` in the docs you and search for `flatMap` its there..

<img width="1394" alt="screen shot 2015-09-24 at 7 59 54 am" src="https://cloud.githubusercontent.com/assets/490291/10072787/53bbb712-6292-11e5-8008-49b62bad9b00.png">

**Comment by raine** [comment]
Unfortunately this page on wiki is not the most discoverable thing in the world:

https://github.com/ramda/ramda/wiki/Functions-AKA
