### ISSUE TITLE
When you pass a string to R.test instead of a regex, it always returns true

### ISSUE THREAD

**Issue by albrow** [ramda/ramda#1413]
The following code returns true:

```javascript
R.test('foo', 'bar')
```

[Here it is in the repl](http://bit.ly/1Jz66KK).

This seems like a pretty easy mistake to make, and I think the appropriate behavior is to throw an exception and point out that the first argument is not the correct type.

**Comment by davidchambers** [comment]
Are you happy for us to check the type of the first argument, @CrossEye?

**Comment by CrossEye** [comment]
Not really, but I can't think of anything better.
