### ISSUE TITLE
_dispatchable shortcuts for no args case

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#1418]
Currently `_dispatchable` [exits early](https://github.com/ramda/ramda/blob/9c74f71868699f841d83779c3078be25bfb6a590/src/internal/_dispatchable.js#L22-L25) when no args are provided. Though if you're dispatching shouldn't that be the job of the method you're deferring to to handle (the no arg case).

**Comment by davidchambers** [comment]
Good point!

**Comment by CrossEye** [comment]
um... if there's no arguments, then we have [no object][no] to which we could delegate a function as a method.  

  [no]: https://github.com/ramda/ramda/blob/9c74f71868699f841d83779c3078be25bfb6a590/src/internal/_dispatchable.js#L26

**Comment by jdalton** [comment]
Ah *doh*!
