### ISSUE TITLE
R.head doesn't support lazy evaluation

### ISSUE THREAD

**Issue by jacobp100** [ramda/ramda#1425]
See http://bit.ly/1jJphwL

**Comment by asaf-romano** [comment]
Lazy evaluation is only supported with transducers. See the modified sample code: http://bit.ly/1PeYfZT

The problem is that I don't see a way to collect the "first" (if any) item with transducers.

**Comment by CrossEye** [comment]
And I'm not really following what output you'd expect from this if there was support for lazy evaluation.  What output would there be?

**Comment by asaf-romano** [comment]
See my version, @CrossEye the map function is only called twice, so i=2.

**Comment by CrossEye** [comment]
Maybe i'm still foggy-brained after the weekend.  I didn't see the point of twice.

**Comment by jacobp100** [comment]
Called once, surely?

**Comment by CrossEye** [comment]
We used to include a [`LazyList` extension][ll], but that was removed in #857 as it wasn't getting any love.  If that has something that interests you, we could certainly revive it.  We could also rework it in terms of the iteration protocol.


  [ll]: https://github.com/ramda/ramda/blob/0bd54cc00bc741101c52cebbcee155ec82f680fc/ext/lazylist/lazylist.js

**Comment by scott-christopher** [comment]
> The problem is that I don't see a way to collect the "first" (if any) item with transducers.

I'm not overly familiar with transducers, but I believe this is something that the `@@transducer/result` method can take care of.

e.g. If we borrow the implementation of the existing transducer for `take` and just override the `@@transducer/result` property to be `R.head`:
```js
xhead = xf => R.assoc('@@transducer/result', R.head, _xtake(1, xf));
R.into([], R.pipe(xhead, R.map(mapFn)), array); //=> [2, 1]
```

**Comment by asaf-romano** [comment]
Still, you're ``into``ing into an array.

**Comment by scott-christopher** [comment]
Yep, I'll put that down to pre-coffee brain.

You should be able to use `transduce` instead of `into`, but in any case it's stepping away from the intent of this PR.
