### ISSUE TITLE
Include a convenience function `print`

### ISSUE THREAD

**Issue by niloy** [ramda/ramda#1431]
It would be nice if Ramda includes a convenience function `print` out of the box because having to define `const print = console.log.bind(console)` in every project is such a pain. I understand Ramda doesn't like side-effects, but debugging is a integral part of programming, and a little convenience doesn't hurt.

**Comment by CrossEye** [comment]
:-1:

This suggestion would fly in the face of what I think of as core principle of Ramda.

Before my house-guests arrived a few days ago, I finally got back to work on the [Ramda Manual][rm].  The section I am working on is the one on avoiding side-effects, although I've expanded the title to include more general referential transparency concerns.

The point I have been making is that all Ramda functions are pure, in that they determine their outputs based on nothing but their inputs, and that they introduce no side effects.

As discussed on Gitter, there are only a few functions to even help users who want to introduce side-effects: `forEach`, `tap`, and perhaps `once` are the only ones that come to mind.  There are none that actually create side-effects themselves.  I really am not interested in starting now.

Clearly this function is not that difficult to create, as you demonstrated.

  [rm]: https://github.com/ramda/ramda/issues/1282

**Comment by davidchambers** [comment]
> [H]aving to define `const print = console.log.bind(console)` in every project is such a pain.

As @raine suggested on Gitter, this can be solved by defining a snippet and accompanying key binding in your text editor.

Ramda has a lot of functions, but we must still consider each new function carefully. No one would be happy if the library were to become a collection of unrelated "helper" functions. `print` violates one of Ramda's principles, and can easily be defined though other means.
