### ISSUE TITLE
pow

### ISSUE THREAD

**Issue by cgarciae** [ramda/ramda#144]
Ramda is missing exponentiation. Since exponentiation is not commutative, there must be two function, depending which argument you want to partially apply
1. `powl (x,y) = x^y` where the partial application `pow(n)` is equivalent to Haskell's `(n^)`
2. `powr (y,x) = x^y` where the partial application `pow(n)` is equivalent to Haskell's `(^n)` 

You could also have a standard `pow`, which is just defined as one of the above.

**Comment by LandonSchropp** [comment]
@CrossEye It would be awesome to see this reopened. There are several great math functions in Ramda, and I was surprised to not see `pow` included in the list. The thread linked above seems to be closed. 

I realize it might be a lot of work to support many of the `Math` functions (as well as the other functions listed in the linked thread, but as a consumer of Ramda it's incredibly handy to grab them and go.

Thanks!

**Comment by CrossEye** [comment]
@LandonSchropp:

`Math.pow` is already a pure function.  The only thing that I see Ramda adding to it is currying, and that seems easy enough to leave in user land if desired, as `const pow = R.curry(Math.pow)` seems simple enough for those who want to use it.

To me the main reason that Ramda includes things like `add` and `modulo` is that these are not simple functions.  Since Ramda has been meant, at least until v1.0, to work well in pre ES6 environments, making function out of these operators meant avoiding code like

```js
const add = function(x, y) {return x + y;};
```

This is not horrible, but it's not particularly nice.  With lambdas in ES6, though, it's the much nicer:

```js
const add = (x, y) => x + y;
```

There simply isn't that sort of gain for something that's already a function.

**Comment by davidchambers** [comment]
I do see value in providing this function: `R.pow(2)` is clearer than `R.flip(Math.pow)(2)`.

**Comment by LandonSchropp** [comment]
I also think it's nice to not have small bits of code duplicated between files and projects. I realize something like this might be simple:

``` js
const add = (x, y) => x + y;
const add = (x, y) => x + y;
const add = (x, y) => x + y;
```

**Comment by LandonSchropp** [comment]
One last thing to add: it's not clear to me up front which functions in the standard library require explicit bindings and which don't. For example, I tried to use `Promise.all` in a point-free style, and I was surprised to learn it wouldn't work without a binding. So `Math.pow` might work, but I don't know which built-in functions do and which ones don't.

**Comment by CrossEye** [comment]
@davidchambers:

> I do see value in providing this function: `R.pow(2)` is clearer than `R.flip(Math.pow)(2)`.

I don't know if we would provide it that way, especially with the ES2016 introduction of the [exponentiation operator][eo], which adds an infix version of `Math.pow`: `2 ** 3; //=> 8`.  If we wanted this to be like our other binary math functions, we would translate `LHS ~ RHS` into `tilde(LHS, RHS)` and not `tilde(RHS, LHS)`.  Of course this has caused us a lot of headaches, but I don't see us reversing this.


  [eo]: https://github.com/rwaldron/exponentiation-operator

**Comment by CrossEye** [comment]
@LandonSchropp:
> it's not clear to me up front in the standard library require explicit bindings and which don't

It's not clear to me, nor do I know of any good general reference about this.

**Comment by davidchambers** [comment]
@LandonSchropp and others may be interested in sanctuary-js/sanctuary#428 which enables:

```javascript
> S.map(S.pow(2), [-3, -2, -1, 0, 1, 2, 3])
[9, 4, 1, 0, 1, 4, 9]

> S.map(S.pow_(10), [-3, -2, -1, 0, 1, 2, 3])
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
```

**Comment by LandonSchropp** [comment]
@davidchambers Thanks!
