### ISSUE TITLE
0.18 Slowdown

### ISSUE THREAD

**Issue by jacobp100** [ramda/ramda#1440]
Mocha on 0.17: 777ms, 774ms, 752ms, 767ms (avg 767.5ms)
Mocha on 0.18: 854ms, 896ms, 914ms, 905ms (avg 892.25ms)
~14% slowdown.

Upgrade performed: https://github.com/jacobp100/recora/commit/e9ff34601347aa2f2454f2a741a9101bce62e806

Node v4.1.2.

**Comment by CrossEye** [comment]
Did you manage to dig into this to see what the issue was?

Our benchmarks are woefully out-of-date.
