### ISSUE TITLE
Curried R.and 

### ISSUE THREAD

**Issue by lifehackett** [ramda/ramda#1441]
Thank you for this library.  I am new to functional programming. RE: R.and, is it possible to curry into it?

`R.compose(R.and(curriedIsActive, R.isNill), curriedGetItemByName(name))(items)`

I'm getting an error: "g.call is not a function"

What I want is the result of `curriedGetItemByName` to be passed into `R.isNill` then `curriedIsActive` then to evaluate `R.and`, but I think the `R.and` is getting evaluated prematurely.

Any thoughts on how to do this?
Any tips for debugging?  As a n00b to functional programming, it is difficult to troubleshoot some of these curry and composed function.

Thanks!

**Comment by lifehackett** [comment]
FWIW here is the solution I came up with
`const and1 = R.curry((fn1, fn2, a) => fn2(a) && fn1(a))`

**Comment by davidchambers** [comment]
Perhaps [`R.both`][1] is what you're after?


[1]: http://ramdajs.com/docs/#both

**Comment by raine** [comment]
> const and1 = R.curry((fn1, fn2, a) => fn2(a) && fn1(a))

This looks like `R.both`, but `R.both` doesn't short-circuit anymore.
