### ISSUE TITLE
An inert lense

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1444]
I think there should be a way to have inert lenses. Lenses that basically dont do anthing, but you can call lense functions on them. For example.

```
R.view(L, anything);            //=> anything
R.set(L, something, anything);          //=> something
```
And also an unwritable inert lense

```
R.view(L, anything);            //=> anything
R.set(L, something, anything);          //=> anything
```

**Comment by davidchambers** [comment]
Interesting. What are the use cases? Does Haskell's lens library support "inert" lenses?

**Comment by scott-christopher** [comment]
These are fairly straightforward to implement.
```js
var idLens = f => s => f(s);
// or
var idLens = R.unary;

var constLens = f => s => R.map(R.always(s), f(s));
// or
var constLens = f => R.converge(R.map, [R.always, f]);
```

I am also curious of the use case though :)

**Comment by scott-christopher** [comment]
The `constLens` unfortunately doesn't satisfy the "put then get" law:
```js
R.view(constL, R.set(constL, 42, 1)) === 42; // false
```

**Comment by ccorcos** [comment]
Well I'm messing around with Redux -- have you guys used it? Anyways, this issue explains what the end goal: https://github.com/rackt/redux/issues/822

I was thinking about using a lens for these "high-order" reducers that abstract other reducers. This probably means nothing to you, but check it out:

```jsx
const list = (state=[], action) => (reduce) => {
  switch (action.type) {
    case LIST_INDEX:
      return R.lensIndex(action.index)
    default:
      return R.inertLens
  }
}
```

**Comment by scott-christopher** [comment]
In your example, assuming you just want the lens that you described as:
```js
R.view(L, anything);            //=> anything
R.set(L, something, anything);  //=> something
```
You could try:
```js
const list = (state=[], action) => (reduce) => {
  switch (action.type) {
    case LIST_INDEX:
      return R.lensIndex(action.index)
    default:
      return R.unary; // inert lens
  }
}
```

**Comment by ccorcos** [comment]
Ah. Sweet!
