### ISSUE TITLE
Reconsider the signature of reduce

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#1445]
I'm not at a computer now, or this would be a PR.  A [recent StackOverflow question][so] noted that that the current signature for `reduce` looks like this:

    (a,b -> a) -> a -> [b] -> a

which can easily be mis-parsed as

    (a, (b -> a)) -> a -> [b] -> a

We should make it unambiguous with

    ((a,b) -> a) -> a -> [b] -> a

  [so]: http://stackoverflow.com/questions/33142252

**Comment by buzzdecafe** [comment]
agreed. worth doing wherever we are using commas to eliminate ambiguity
