### ISSUE TITLE
R.uniqWith(R.identical) is slow

### ISSUE THREAD

**Issue by raine** [ramda/ramda#1449]
```js
const taim = require('taim')
const R = require('ramda')
const _ = require('lodash')

const N = 20000;
const RAND_RANGE = [0, 5000];
const rand = R.partial(_.random, RAND_RANGE)
const arr = R.map(R.call, R.repeat(rand, N))

const uniqWithIdentical = R.uniqWith(R.identical)

taim('uniqWithIdentical', uniqWithIdentical)(arr)
taim('_uniq', _.uniq)(arr)
```

```
uniqWithIdentical took 15 s
_uniq took 5.31 ms
```

The larger the max end of `RAND_RANGE` is, i.e. the bigger the variability in values, the slower it gets, while lodash's `uniq` performs much the same.

**Comment by CrossEye** [comment]
Obviously it's getting to be time we take up performance.

I still have one major API change I'm looking to introduce -- didn't get to it over the weekend, but should have time in the next few evenings.  After that, I'd like to start looking at where we are slow in comparison to other similar libraries or simply to our own expectations.

There will be places where we will never meet the speed of something like lodash, as our emphasis on value equality rather than reference equality implies significantly more processing, but this case should not cause huge slow-downs, which makes me thing that we have an algorithmic issue.

I had another recently.  I did an `invert` on an object with about 45,000 keys mapping to about 125 unique values.  That took tens of seconds to run -- don't remember the exact number.  But it was far higher than I believe it should have been.  Since it was a one-off, I didn't bother investigating too deeply at the time, but it's clearly doing something `O(n2)` when there should be significantly faster methods available.

I think we're hitting the time when we need to address these issues.

**Comment by scott-christopher** [comment]
We previously had a crack at using `Set` where possible, but it proved troublesome maintaining value-based equality semantics (see #1142 & #1188).

We _could_ optimise the case where `R.identical` is provided as the equality predicate, but it's a route we haven't traditionally gone down.
e.g.
```js
_curry2(function uniqWith(pred, list) {
  var idx = 0,
      len = list.length,
      result = [],
      item, set;

  if (pred === identical && typeof Set == 'function') {
    set = new Set();
    while (idx < len) {
      item = list[idx];
      if (set.size !== set.add(item).size) {
        result[result.length] = item;
      }
      idx += 1;
    }
  } else {
    while (idx < len) {
      item = list[idx];
      if (!_containsWith(pred, item, result)) {
        result[result.length] = item;
      }
      idx += 1;
    }
  }

  return result;
});
```
The above implementation ends up yielding slightly better performance than lodash's `uniq`.
```
uniqWithIdenticalSet took 3.37 ms
uniqWithIdentical    took 2.63 s
_uniq                took 7.92 ms
```
A similar optimisation can be applied to `containsWith` too. We just need to weigh up the cost/benefit to introducing these kinds of optimisations, as they tend to uncover a few edge cases while increasing complexity.

**Comment by asaf-romano** [comment]
See  #1198

**Comment by scott-christopher** [comment]
My memory is short-lived :)

I'm still not convinced that `identical` should treat `0` and `-0` as unequal. It also doesn't help that ES6 defines the equality semantics of `Object.is` treating them as unequal, while `Set`/`Map` treat them as equal.

If there is still interest in pursuing this, we can include a check for `-0`.

```patch
   var idx = 0,
       len = list.length,
       result = [],
+      hasNegZero = false,
       item, set;
 
   if (pred === identical && typeof Set == 'function') {
     set = new Set();
     while (idx < len) {
       item = list[idx];
-      if (set.size !== set.add(item).size) {
+      if (item === 0 && 1/item === -Infinity) {
+        if (!hasNegZero) {
+          result[result.length] = item;
+          hasNegZero = true;
+        }
+      } else if (set.size !== set.add(item).size) {
         result[result.length] = item;
       }
       idx += 1;
```

```
> uniqWithIdenticalSet([-0, 0, -0, 0]);
[ -0, 0 ]
```

And it still performs quite well using the example the @raine provided:
```
uniqWithIdenticalSet took 3.71 ms
uniqWithIdentical took 2.62 s
_uniq took 9.41 ms
````

**Comment by CrossEye** [comment]
I'm not particularly comfortable with privileging Ramda's `identical` function over user-provided functions.   If this is to support another public code-path, I could probably live with it.   That is, if we had some `uniqXXX` that delegated to `uniqWith(identical)` I would probably be all right with it.   But if `uniqWith(identical)` had arbitrarily better performance characteristics than `uniqWith((a, b) => a === b)` then I think we're straying into dangerous territory.

**Comment by scott-christopher** [comment]
I'm on the fence with this. On the one hand it is an opportunity to optimise a code path that is currently a poor performer, but on the other it increases the complexity of the implementation. I think that not introducing a performance optimisation simply because it doesn't apply to all code paths would be somewhat disappointing.

I have also considered improving the general performance here by using a b-tree that could provide the custom equality semantics. Unfortunately, this would require the elements of the list to be orderable in some way, changing the API of `uniqWith` and friends to instead accept a comparator-like function like `R.sort` does (or overload `R.lt`/`R.gt` to apply some arbitrary ordering logic for objects, but that's a whole new can o' worms).

**Comment by CrossEye** [comment]
The issue for me is that one of the things I really don't like about Underscore/lodash is the chaining, where you ca'n create a fairly readable data flow, _but only if you're just using library functions_.  You cannot (or cannot simply) add your own functions into the mix.

I would really like it if Ramda can avoid doing that, treating its own internal functions, when we do use  them publicly, as exactly like any user-defined function.

On the other had, I really do want to to improve performance.  At least this isn't running afoul the a notion we've pushed that the API is king over implementation.  We should be able to improve performance generally while keeping our desired API.

**Comment by scott-christopher** [comment]
I'd say there is a distinction between restricting functionality only to internal functions like you suggest with `_` vs improving the performance where possible for internal functions.

**Comment by davezuko** [comment]
@CrossEye I apologize if this is not the place to ask this (it probably isn't), and excuse my ignorance of Ramda's internals, but I'm curious about this quote:

> There will be places where we will never meet the speed of something like lodash, as our emphasis on value equality rather than reference equality implies significantly more processing...

I've seen a few issues in Ramda about this topic, and was hoping maybe you could shed some light on _why_ Ramda uses value-based equality rather than reference equality, or at least point me in the right direction. From what I understand, in functional programming it's generally accepted that data structures should be immutable, which would give you the opportunity to just use reference-based equality. Is it that you just don't want the library to force the user's hand in this regard, or is there some deeper reason? I assume there must be since you're consciously using value-based equality.

Anyways, thanks in advance, really appreciate the work you guys have done on Ramda.

**Comment by buzzdecafe** [comment]
@davezuko 

is `{a: 1}` equal to `{a: 1}`? 
are `{a: 1, b: 2}` and `{b:2, a: 1}` equal?

If you want to call these thing "equal" then you have to make some decisions about what that means. For ramda, we want to support the invariant that whenever `equals(x, y)` holds, then that implies that for any `f`, `equals(f(x), f(y))`

**Comment by CrossEye** [comment]
@davezuko:

This is a fine place for such questions.

Beyond what @buzzdecafe said, functional programming is all about values.  References, as I see it, simply have no place at all.

    R.findIndex(R.equals({a: 42}), [{x: 10}, {b: 52}, {a: 42}, {a: 43}]); //=> 2

This is exactly right.  I don't want to care about whether two objects refer to the same memory location.  I want to know that they have the same value.  If we were to use reference equality, we could not tell that the value in the list actually matched our search term.  They wouldn't, and much of the point of FP is lost.

**Comment by davezuko** [comment]
Thanks for the explanations @buzzdecafe and @CrossEye, it definitely makes a lot of sense; I think I was just coming into the problem with the wrong perspective after being buried in a lot of Redux-related work.

**Comment by raine** [comment]
I can confirm @niloy's findings in #1500 

```js
const taim = require('taim')
const R = require('ramda')
const _ = require('lodash')

const N = 10000;
const RAND_RANGE = [0, 3000];
const rand = R.partial(_.random, RAND_RANGE)
const arr = R.map(R.call, R.repeat(rand, N))

const uniqWithIdentical = R.uniqWith(R.identical)

taim('uniqWithIdentical', uniqWithIdentical)(arr)
taim('uniqWithStrictEqual', R.uniqWith((a, b) => a === b))(arr)
taim('_uniq', _.uniq)(arr)
```

```
uniqWithIdentical took 6.12 s
uniqWithStrictEqual took 144 ms
_uniq took 5.56 ms
```

**Comment by niloy** [comment]
Upon close inspection, `R.identical` works great, better than plain function. I inlined the identical function for this test. So the bottleneck must be `_curry2`.

```js
var arr = R.times(Math.random, 20000);

console.time('identical');
R.uniqWith(function identical(a, b) {
  // SameValue algorithm
  if (a === b) { // Steps 1-5, 7-10
    // Steps 6.b-6.e: +0 != -0
    return a !== 0 || 1 / a === 1 / b;
  } else {
    // Step 6.a: NaN == NaN
    return a !== a && b !== b;
  }
}, arr);
console.timeEnd('identical'); // 1s

console.time('plain function');
R.uniqWith(function(a, b) {
  return a === b;
}, arr);
console.timeEnd('plain function'); // 7s
```

**Comment by scott-christopher** [comment]
It looks like a lot of the time here is spent boxing and unboxing the primitives to check if the placeholder property exists.

e.g. you'll probably find the times drop quite significantly if you change the array items to objects:
```js
// from
var arr = R.times(Math.random, 20000)
// to
var arr = R.times(() => ({a: Math.random}), 20000)
```

We also get a decent perf improvement if we update the placeholder check in the curry functions:
```js
// from
a != null && a['@@functional/placeholder']
// to
a instanceof Object && a['@@functional/placeholder']
```

Extending upon @niloy's example:
```js
var _curry1 = require('./src/internal/_curry1');
var _curry2 = require('./src/internal/_curry2');
var times = require('./src/times');
var uniqWith = require('./src/uniqWith');

function instanceOfCurry2(fn) {
  return function f2(a, b) {
    var n = arguments.length;
    if (n === 0) {
      return f2;
    } else if (n === 1 && a instanceof Object && a['@@functional/placeholder'] === true) {
      return f2;
    } else if (n === 1) {
      return _curry1(function(b) { return fn(a, b); });
    } else if (n === 2 && a instanceof Object && a['@@functional/placeholder'] === true &&
      b instanceof Object && b['@@functional/placeholder'] === true) {
      return f2;
    } else if (n === 2 && a instanceof Object && a['@@functional/placeholder'] === true) {
      return _curry1(function(a) { return fn(a, b); });
    } else if (n === 2 && b instanceof Object && b['@@functional/placeholder'] === true) {
      return _curry1(function(b) { return fn(a, b); });
    } else {
      return fn(a, b);
    }
  };
}

function switchCurry2(fn) {
  return function f2(a, b) {
    switch (arguments.length) {
      case 0: return f2;
      case 1:
        return a instanceof Object && a['@@functional/placeholder'] === true
          ? f2
          : _curry1(function(_b) { return fn(a, _b); });
      case 2:
        if (a instanceof Object && a['@@functional/placeholder'] === true) {
          return b instanceof Object && b['@@functional/placeholder'] === true
            ? f2
            : _curry1(function(_a) { return fn(_a, b); });
        }
        return b instanceof Object && b['@@functional/placeholder'] === true
          ? _curry1(function(_b) { return fn(a, _b); })
          : fn(a, b);
    }
  };
}

function noPlaceholderCurry(fn) {
  return function f2(a, b) {
    switch (arguments.length) {
      case 0: return f2;
      case 1: return _curry1(function(_b) { return fn(a, _b); });
      case 2: return fn(a, b);
    }
  };
}

function run() {
  var arr = times(Math.random, 2000),
      id = function(a, b) { return a === b; },
      cId0 = _curry2(id),
      cId1 = instanceOfCurry2(id),
      cId2 = switchCurry2(id),
      cId3 = noPlaceholderCurry(id);

  console.time('identical');
  uniqWith(function identical(a, b) {
    if (a === b) {
      return a !== 0 || 1 / a === 1 / b;
    } else {
      return a !== a && b !== b;
    }
  }, arr);
  console.timeEnd('identical');

  console.time('plain function');
  uniqWith(id, arr);
  console.timeEnd('plain function');

  console.time('_curry2');
  uniqWith(cId0, arr);
  console.timeEnd('_curry2');

  console.time('instanceOfCurry2');
  uniqWith(cId1, arr);
  console.timeEnd('instanceOfCurry2');

  console.time('switchCurry2');
  uniqWith(cId2, arr);
  console.timeEnd('switchCurry2');

  console.time('noPlaceholderCurry');
  uniqWith(cId3, arr);
  console.timeEnd('noPlaceholderCurry');
}
```
Running in Node v5:
```
identical: 3.634ms
plain function: 16.777ms
_curry2: 423.600ms
instanceOfCurry2: 105.617ms
switchCurry2: 77.530ms
noPlaceholderCurry: 27.960ms
```

**Comment by buzzdecafe** [comment]
#1363 

let's drop placeholders in `curry`

**Comment by svozza** [comment]
Or we could just use `switchCurry2` whose performance is still 6x better than the current implementation and involves no loss of functionality.

**Comment by buzzdecafe** [comment]
i would argue that generalized placeholders are themselves a loss of functionality.

**Comment by CrossEye** [comment]
I think that together with #1497 and perhaps a minor additional `partialN` function, we could remove the placeholders altogether, both cleaning things up and improving the performance across the library.

**Comment by asaf-romano** [comment]
See #1503. I think that with uncurried R.identical, the performance would be almost in par with Object.is.

**Comment by scott-christopher** [comment]
I decided to have a go at tackling this and have pushed up a branch containing a few improvements.

https://github.com/ramda/ramda/compare/master...scott-christopher:perf-improv

This contains some tweaks to the internal currying functions and utilises `Set` where possible in `uniqBy` and `_contains`. All the tests are passing with these changes in place and the performance improvements look quite promising.

I've copied the output of a benchmark for `uniq` below (included in the above branch).

Current HEAD of master:
```
┌────────────────────────┬────────────────────────┬────────────────────────┐
│ uniq                   │ Hertz                  │ Margin of Error        │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr1)       │ 21.52                  │ 0.60%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr1) │ 21.81                  │ 0.68%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr1)             │ 21.66                  │ 0.81%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr2)       │ 8.73                   │ 0.72%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr2) │ 8.72                   │ 0.58%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr2)             │ 8.67                   │ 0.83%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr3)       │ 692                    │ 0.55%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr3) │ 695                    │ 0.60%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr3)             │ 686                    │ 0.72%                  │
└────────────────────────┴────────────────────────┴────────────────────────┘
```
With the improvements in the branch linked above:
```
┌────────────────────────┬────────────────────────┬────────────────────────┐
│ uniq                   │ Hertz                  │ Margin of Error        │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr1)       │ 94.13                  │ 0.57%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr1) │ 40.21                  │ 0.55%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr1)             │ 87.88                  │ 0.62%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr2)       │ 21,299                 │ 0.45%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr2) │ 25.60                  │ 0.46%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr2)             │ 18,967                 │ 0.65%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqBy(id, arr3)       │ 787                    │ 0.51%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniqWith(equals, arr3) │ 808                    │ 0.53%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ uniq(arr3)             │ 783                    │ 0.61%                  │
└────────────────────────┴────────────────────────┴────────────────────────┘
```
Where `arr1` is a heterogeneous and somewhat random array of 1000 items, `arr2` is random array of 1000 integers, and `arr3` is an array of 1000 items all containing `[true]`.

I'll let people weigh in on the ideas and have a play with it and if the outcome looks positive I will raise a PR.

n.b. if you want to pull the branch down and try this yourself, please remember to `npm run build` before running benchmarks, etc.

**Comment by buzzdecafe** [comment]
:+1: @scott-christopher these changes look minimally invasive, and the benefits are obvious.

**Comment by CrossEye** [comment]
I won't have time to look closely until this evening (8 hours away), if then.  But at a quick glance, this looks great.  The performance improvements are strong, but there will still be much more to do, given the perf problems we have with `uniq`/`contains`, especially for value types.  I said over in #1508 that we will probably have to have some API expansion to deal with this.  What I was thinking of was allowing a (preferably more performant) version of the current API for normal cases, but allowing the user to opt-in to a faster version for value types.  One simply does not need to use the full power of `equals` to check if 42 is in a list of integers.

**Comment by scott-christopher** [comment]
I've run the sample above since #1512 has landed in master, also including `R.uniq` in the test.

```
uniqWithIdentical took 753 ms
R.uniq took 4.7 ms
_uniq took 3.92 ms
```

Closing this for now. Please reopen if it still seems to be an issue.
