### ISSUE TITLE
Alternate input style for R.path

### ISSUE THREAD

**Issue by alexcarruthers** [ramda/ramda#1451]
Using R.path as it currently stands,  `R.path(['path', 'to', 'what', 'you', 'want', 'at', 0], input)` feels a bit weird and clunky whereas `R.path('path.to.what.you.want.at[0]', object)` feel more natural and closer to what you would write using vanilla javascript. Would there be a place for/no objection to using both input styles?

**Comment by raine** [comment]
It used to be so. See https://github.com/ramda/ramda/pull/876.

New discussion on the matter is welcome, though.

**Comment by dustinblackman** [comment]
I can agree that @alexcarruthers suggestion is much cleaner to read and can be understood at a glance without needing to know the workings of Ramda.

**Comment by Chris911** [comment]
What was the reason for making the change in the first place? And why not keep both syntax?

**Comment by smaspe** [comment]
I think any attempt at parsing the path can be incomplete at best, short of developing a very complex machinery. For full expression evaluation, I would rather use a dedicated tool, like JSONPath.

**Comment by buzzdecafe** [comment]
what if your keys have a "." in them? simplest solution was to take the string-parsing out of the equation. if you are confident that your data will not have such keys, it's still pretty easy to:

```js
path(split(".", pathString), obj)
```

**Comment by smaspe** [comment]
@buzzdecafe more like `/\]?\.|\[/` to get the complete thing with `[]`

    R.split(/\]?\.|\[/, 'a.b[0].c');

**Comment by CrossEye** [comment]
Well, I don't think we ever supported the `[0]` notation, although I think that one could always do `a.b.0.c`.  But you could support such if you wanted to in your own wrapper, of course.

**Comment by davidchambers** [comment]
I'll take a hard line here. `R.path` must take a value of type `[String]` as its first argument to support property names such as `''`, `'.'`, and `'[0]'`. Providing *another* path function would cause confusion, and violate _The Zen of Python_ (`python -c 'import this' | grep 'only one'`).

We're all free to define convenience functions in our own projects. :)

**Comment by CrossEye** [comment]
I've come to agree with that hard line for the library, although I often use such convenience functions for my own code.

**Comment by cht8687** [comment]
I know this is a closed issue. Sorry to comment on this again.

I keep getting complaints from other developers saying that lodash's [_.get](https://lodash.com/docs/4.17.10#get) is more readable due to this syntax:
```js
_.get(object, 'a[0].b.c');
// => 3
```
I totallly agrees every maintainer's point of view above.

Personally, I wish Ramda could have this kind of flexibility that I don't need to try to convince others when introducing Ramda into a new codebase.

Thank you all for this awesome library! This is just my thoughts.

**Comment by CrossEye** [comment]
Well you can ask them what to expect when their key contains a `.` or `[0]`.  :smile:

But we would never try to compete with lodash on flexibility.  We strictly prefer simplicity (in the [Rich Hickey][se] sense.)


  [se]: https://www.infoq.com/presentations/Simple-Made-Easy
