### ISSUE TITLE
R.type Map/Set returns 'Object' in IE11

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#1457]
Map/Set in IE11 resolve a `R.type` value of `'Object'`.

**Comment by davidchambers** [comment]
Is there a reliable way to detect `Map` and `Set` under these conditions?

**Comment by jdalton** [comment]
```js
Function.prototype.toString.call(new Map().constructor);
//'
// function Map() {
//     [native code]
// }
//'
```

**Comment by scott-christopher** [comment]
Does `mapInstance.constructor.name` report `Map` in IE11? (I don't have an instance readily available to try)

**Comment by jdalton** [comment]
IE11 does not support the `Function#name` property.

**Comment by CrossEye** [comment]
Uggh.  `Object.prototype.toString.call(x)` has been so reliable for so long.  Is the Function.prototype version equally robust?

**Comment by jdalton** [comment]
It's robust for getting a functions real `toString` value (avoids custom `toString` representations). Moving forward in ES6 any value can use their `Symbol.toStringTag` to assign custom `Object.prototype.toString.call(...)` result. The general attitude though is that if you're using a custom `Symbol.toStringTag` value you get what you get.

**Comment by CrossEye** [comment]
@jdalton: Thanks.  I've followed a lot of the ES6 stuff, but I only vaguely remember hearing about this.
