### ISSUE TITLE
0.18 regression: R.both does not short circuit

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1466]
```js

R.both(R.complement(R.isNil), R.whereEq({ a: 1 }))(null)
// => 0.18: TypeError: n is null
// => 0.17: false
```

**Comment by asaf-romano** [comment]
R.allPass still short-circuits though.

**Comment by gilligan** [comment]
I found this quite annoying but was under the impression that this was intentional - is it just a byproduct of  the lift implementation ?

**Comment by CrossEye** [comment]
It is a byproduct of the implementation.

The thought was that in a functional system order of operations shouldn't matter. 

This perhaps was hasty, though, especially as these functions were documented specifically add behaving that way. 

Hmmm.

**Comment by asaf-romano** [comment]
For one thing, it makes vanilla-ramda (that is, without Maybes and such) somewhat cumbersome to use because pre-conditions are harder to implement (you need to either know about allPass not being broken, or use lamdas).

**Comment by scott-christopher** [comment]
> The thought was that in a functional system order of operations shouldn't matter.

In my mind, it's not so much whether the order should matter as to whether both function arguments should be called if not necessary. Even a pure function can be expensive to evaluate. In other languages with lazy evaluation, you could expect the second function to be ignored too.

e.g.
```hs
> let both = liftA2 (&&)
> both (> 2) (< 4) 1
False
> both (> 2) (< 4) 3
True
> both (> 2) (const undefined) 1
False
> both (> 2) (const undefined) 3
*** Exception: Prelude.undefined
```

As elegant as the new implementations for `both` and `either` may be, the eager evaluation seems to have tripped a number of people up, so I would be in favour of rolling back their behaviour.

**Comment by CrossEye** [comment]
> As elegant as the new implementations for `both` and `either` may be, the eager evaluation seems to have tripped a number of people up, so I would be in favour of rolling back their behaviour.

Yes, that's where I've come to as well.

**Comment by asaf-romano** [comment]
Yes (on Friday).

**Comment by asaf-romano** [comment]
And thanks for reconsidering this because I'm freaking out here :)

**Comment by gilligan** [comment]
So after the non-short-circuting change was introduced I just wrote a `bothPass` function behaving as `both` did before. Was wondering if it was worth considering to stick to the new implementation but add `bothPass` and `eitherPass` to Ramda ? 

But I guess it's not such a great idea because based on the naming there is no obvious difference between `bothPass` and `both`. Still, I was wondering if just having both variations would be an option.

**Comment by CrossEye** [comment]
` Was wondering if it was worth considering to stick to the new implementation but add `bothPass` and `eitherPass` to Ramda ? 

I don't think so.  The only reason for the original change was for the elegance of the implementation.  We're quite willing to do that so long as it doesn't cause other problems.  But it changed the API, and that change is turning out to be more harmful than anticipated.

The only conceivable reason people might prefer the current version, outside of the elegance of the implementation, is that the eager version would allow you to embed side effects inside the path that would other be short-circuited.  That is not something Ramda is looking so support.  Ever.

So I think a change is quite warranted.
