### ISSUE TITLE
Difference in when and ifElse semantics

### ISSUE THREAD

**Issue by raine** [ramda/ramda#1469]
- `ifElse` checks its arguments' arity to determine the returned function's arity. You can use `ifElse` to make a function that takes multiple arguments.
- `when` doesn't "return a function", it's a curried function with arity of 3 where the last argument is the value passed to the `whenTrueFn`. So you can't use `when` to make a function that takes any number of arguments.

With `ifElse` you can make a `when` that takes multiple args:

``` js
const when = R.ifElse(R.__, R.__, R.identity)
const foo = (val, key) => 'yep'
R.mapObjIndexed(when(R.is(String), foo), obj)
```

In this example using `R.when` is not possible because you'd only see `val` in `foo`.

Would it be possible to make `R.when` check its arguments arities to determine how many to pass on in the way `R.ifElse` does?

It'd probably mean that `when` gets semantics similar to `ifElse` in that you would not be able to pass all arguments in the first call: `R.when(R.is(String), R.toUpper)("foo")`.

**Comment by asaf-romano** [comment]
See #1297

**Comment by scott-christopher** [comment]
The issue I see with making `when` and `unless` accept multiple arguments is it then becomes unclear which argument should be returned when the predicate isn't satisfied. e.g.
```js
var neverFoo = R.when(R.binary(R.F), R.always('foo'));
neverFoo('bar', 'baz'); // should this return 'bar' or 'baz'?
```

**Comment by futpib** [comment]
Returning the first argument is arbitrary, but would allow for more use-cases. I was about to use it in a redux reducer which has a signature of `(state, action) -> state`, which is a right fit for a `when` that returns the first argument. `R.reduce`'s reducer also fits the signature.

Had to do this:

```js
const when_ = ifElse(__, __, identity);
```
