### ISSUE TITLE
High-Order function helper

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1472]
I find myself wanting to write functions of the form `f -> g -> * -> f(g(*))`. This is helpful when you want a high-order function to wrap a function and alter the result when its called. Much like a high-order compose function. Kind of like the opposite of the way memoize works because this function only alters the result.

```coffee
R.hof = R.curry (f, g) -> (args...) -> f(R.apply(g, args))

# for example
wrapValue = R.hof (value) -> {value}
a = wrapValue -> 1
a()
# => {value: 1}
```

High-order function might not be the proper term here either.... what do you think?

**Comment by davidchambers** [comment]
The type of [`S.compose`][1] is `(b -> c) -> (a -> b) -> a -> c`, which vaguely resembles your `f -> g -> * -> f(g(*))`. I'm not clear as to what you're trying to achieve, though. Could you elaborate?


[1]: https://github.com/plaid/sanctuary#compose

**Comment by ccorcos** [comment]
I just realized R.map does precisely this:

> Map treats also treats functions as functors and will compose them together.

This was the goal:

```
coffee> a = -> 10
[Function]
coffee> b = (value) -> {value}
[Function]
coffee> R.map(b, a)
[Function]
coffee> R.map(b, a)()
{ value: 10 }
```
