### ISSUE TITLE
"do" function

### ISSUE THREAD

**Issue by rogeriochaves** [ramda/ramda#1476]
Would it be a bad idea to have a function like clojure's `do` in Ramda (but passing arguments)? (https://clojuredocs.org/clojure.core/do)

Although I want to avoid the most, sometimes side-effect functions are needed.

The idea is to apply the same arguments to a list of functions, I manage to achieve it with this:

```javascript
R.do = R.uncurryN(2, R.compose(R.map, R.curryN(1, R.flip(R.apply))));
```

so it can be called like this:

```javascript
// apply doesn't work with console functions
log = function (x, y) { console.log(x, y); };
warn = function (x, y) { console.warn(x, y); };
error = function (x, y) { console.error(x, y); };

R.do(['foo', 'bar'], [log, warn, error]);
```
![captura de tela 2015-10-28 as 00 53 21](https://cloud.githubusercontent.com/assets/792201/10778531/522148e0-7d0e-11e5-83df-63ade05c06f4.png)

Although `do` is probably not a good name as it is a javascript reserved word
What do you think?

**Comment by CrossEye** [comment]
You might want to look at the discussion in the recently-active-again #986.  That seems fairly similar.

**Comment by davidchambers** [comment]
> Although I want to avoid the most, sometimes side-effect functions are needed.

True, but Ramda needn't accommodate this. ;)
