### ISSUE TITLE
R.toPairs has an interesting effect on arrays

### ISSUE THREAD

**Issue by dumconstantin** [ramda/ramda#1477]
The docs for R.toPairs say:
```` 
Converts an object into an array of key, value arrays. Only the object's own properties are used. Note that the order of the output array is not guaranteed to be consistent across different JS platforms. 
```
Which might need to also include the following case:
http://bit.ly/1GxM3SH

Looking at the toPairs source there is a ```for (var prop in obj)``` which gives the array indexes as keys.

Can I propose the docs to include something on the following lines or do an object check in the toPairs function instead?
```
If the given object is an ```Array``` then the array indexes will be used as keys. For example: 
R.toPairs(['a', 'b', 'c']); // [["0", "a", ["1", "b"], ["2", "c"]]
```
Thanks!

**Comment by raine** [comment]
The way I see it is Ramda prefers well-defined functions that do only one thing. `toPairs` providing a reasonable result for an array is an interesting coincidence but I don't think documenting that behavior would be in spirit of Ramda. It would also mean that there would have to be a test case for that behavior.

**Comment by CrossEye** [comment]
>  `toPairs` providing a reasonable result for an array is an interesting coincidence but I don't think documenting that behavior would be in spirit of Ramda. 

Agreed.  It's actually not simply a fallout of the implementation, but more a result of the way the language defines Arrays in terms of Objects.  So a canny user might take advantage of it, but I don't think we want to call attention to it.

**Comment by dumconstantin** [comment]
Yup, that makes sense to keep things loose instead of strictly enforcing behaviors.

Just noted ``` typescript-ramda ```. It makes sense to enforce types only in a language that enforces types :) 

Thanks for the heads up and for making this obvious! Closing the issue.
