### ISSUE TITLE
lens composition?

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1479]
Is it possible to compose lenses?

```js
x = R.lens(R.prop('x'), R.assoc('x'))
y = R.lens(R.prop('y'), R.assoc('y'))
z = {x: {y:1}, y: 2}
R.view(x, z)
R.view(y, z)
R.view(y, R.view(x, z))
```

I got up to here and I can view it, but idk how I'm going to set the lens. I basically want to compose x and y. Any thoughts?

**Comment by davidchambers** [comment]
The wonderful thing about van Laarhoven lenses is that they compose via regular function composition:

```javascript
const o = {x: {y: 1}, y: 2};
const x = R.lensProp('x');
const y = R.lensProp('y');

R.view(x, o);  // => {y: 1}
R.view(y, o);  // => 2
R.view(R.compose(x, y), o);  // => 1
```

`R.compose(x, y)` will give you a lens whose focus is `.x.y`. :)

**Comment by ccorcos** [comment]
wow. I just kind of assumed that wouldnt work -- but thats amazing!

**Comment by ccorcos** [comment]
I'm thinking about how to use [flyd](https://github.com/paldepind/flyd) and lenses to create cursors...

**Comment by polytypic** [comment]
Note that the [documentation](http://ramdajs.com/0.18.0/docs/) seems to present lenses as an abstract type `Lens s a`.  The documentation also does not seem to mention that lenses are van Laarhoven lenses.  Composing lenses via function composition essentially exposes an implementation detail of lenses.

**Comment by davidchambers** [comment]
> The documentation also does not seem to mention that lenses are van Laarhoven lenses.

Good point. We should rectify this.

**Comment by ni-ko-o-kin** [comment]
Why are lenses composed backwards? I expected `R.compose(x, y)` to return a lens whose focus is `.y.x` and not `.x.y`.

**Comment by CrossEye** [comment]
> Why are lenses composes backwards?

There's a pretty good answer to this [on Reddit][cb].

  [cb]: https://www.reddit.com/r/haskell/comments/23x3f3/lenses_dont_compose_backwards/

**Comment by vegansk** [comment]
I think that it should be reopened because ``compose`` is for functions and not for lenses, I can't use the result of compose to set the value. Besides, this code fails with exception:
```js
let a = R.lensProp("a")
let b = R.lensProp("b")
let ab = R.compose(a, b)
R.view(ab, {})
```

But it works ok with ``lensPath``

**Comment by rockymadden** [comment]
@vegansk You might check out this article (in the Ramda wiki): https://www.linkedin.com/pulse/composing-lenses-ramda-vladim%C3%ADr-gorej
