### ISSUE TITLE
R.map(R.compose(fn))

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1480]
R.compose gets really mad when you only pass one function.

**Comment by davidchambers** [comment]
Are you sure? `R.map(R.compose(R.negate), [1, 2, 3])` evaluates to `[-1, -2, -3]` for me in v0.18.0. Which version are you using?

**Comment by ccorcos** [comment]
Ah. So I'm assuming compose is fixed-arity and takes two functions. Then I realized that R.map will compose functions for you!

```js
R.map(fn, [R.inc])
```
