### ISSUE TITLE
0.18 regression: Cannot curry the first function in a pipe

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1483]
I'm pretty sure this is a recent regression:
```js
var f1 = R.curry(R.pipeP((a, b) => Promise.resolve(a), R.tap(() => {})));
var f2 = R.pipeP(R.curry((a, b) => Promise.resolve(a)), R.tap(() => {}));

f1(1); // => Function
f2(1); // => TypeError: (intermediate value).then is not a function
```

**Comment by asaf-romano** [comment]
Note that both function report the correct arity (2).

**Comment by asaf-romano** [comment]
Yep, this got broke in 0.18. The above code works as expected in both 0.17 and 0.15.

**Comment by asaf-romano** [comment]
It's not just pipeP:
http://bit.ly/1KLIov

Looking at the current implementation of both pipe and pipeP, they seem to assume that they are called with all of the arguments of the first function supplied. In 0.17, this assumption was fine because the functions returned by pipe/P were curried.

**Comment by asaf-romano** [comment]
Needless to say, in-house curried functions are broken as well:
http://bit.ly/1Oesmlk

No idea why a string is returned there though...

**Comment by buzzdecafe** [comment]
> No idea why a string is returned there though...

because javascript very helpfully coerces the `1` and the partially applied `subtract` inside `add` since `+` is overloaded.

**Comment by asaf-romano** [comment]
Not hearing, not hearing.

**Comment by asaf-romano** [comment]
So I was wrong. 0.17 was the only reason it worked. Compare http://bit.ly/1MyHIRz to http://bit.ly/1MyHLwE

...and it worked because the function returned by pipe was curried by itself.

**Comment by asaf-romano** [comment]
Now the problem is that Ramda has no way to tell that the first function in the pipe is curried, as far as I know. This keep the possible fixes very short, namely:
* Go back to 0.17's behavior: I think that's not on the table anymore.
* Mark all curried functions created by ramda (internally and externally) with something like ``function['@@curried']``, and then, in pipe*/compose* curry the returned function if the first function to be called is by itself curried This won't help with third-party currying, but it's still better than the current behavior.
* Known Issue.

**Comment by asaf-romano** [comment]
And there's also the very hacky, complicated option of dealing with the situation that the first function function was called with partial arity and returned a function. At that point the implementation could probably assume that the function is curried and adjust its behavior as necessary. It'll break in cases like this though:
```js
function getDateFormatter(type, overrideThisOrThat = null)
{
  return function(value) { ... }
}
``
I'm not sure this case is worth discussing because I cannot see how including such a function in a pipeline makes sense. Still, it's a limitation to keep in mind if we go down that path.

**Comment by asaf-romano** [comment]
Another example: http://bit.ly/1khY7Nc

**Comment by CrossEye** [comment]
I am still swamped and not really able to participate.   But if you look at #1318 and others linked from there, or search for @davidchambers' Alice and Bob story, you can see some of what went into the decision to reverse the automatic currying of `compose`d / `pipe`d functions. I should be back online tomorrow, or (remote chance) this evening, and will try to take this up more carefully.

**Comment by davidchambers** [comment]
As @asaf-romano noted in an earlier [comment][1], this issue is misleading. Given

```javascript
const f = R.pipe(R.curry((x, y) => x + y));
```

`f('foo')`, `f('foo')('bar')`, and `f('foo', 'bar')` all work as expected in all the Ramda versions in question. I'll close this issue to avoid further confusion. :stuck_out_tongue_winking_eye:


[1]: https://github.com/ramda/ramda/issues/1483#issuecomment-152715975
