### ISSUE TITLE
assocFromPath, assocPathFromPath

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1486]
This may very well be cookbook material, but I find myself using it so often I thought it's worth proposing anyway. For copying properties from one property into another (as a step in a transformation pipeline), the current options are, afaict:

1) Point-free with ``converge``: ``converge(assoc("displayName"), [path(["result", "userName"]), identity])`` - the problem is that I'll likely never get my coworkers to understand ``converge`` ;) More importantly, it's just  too technical, and will get even worse if ``converge`` is replaced with the more general ``lift``.
2) lamda: ``obj => assoc("displayName", path(["result", "userName"]), ,obj)``, which I'd be fine with if it happened once a month rather than twice a day.

So in my own project I defined something like this:
``export let assocFromPath = curry((fieldName, valuePath, obj) => assoc(fieldName, path(valuePath, obj), obj));``

This covers my use cases, but I guess assocPathFromPath would also make sense.

**Comment by CrossEye** [comment]
Another one I missed altogether.  Wonder what I was busy with around Halloween.

But yes, I do think this looks mostly like Cookbook material.  Did you add an entry for it?

**Comment by asaf-romano** [comment]
I closed this as, over time, it didn't prove to be as dominant in our utility belt as it initially was.

One Saturday I'll look at that directory and see what can be easily ported to self-contained code and post it on the cookbook
