### ISSUE TITLE
R.map that skips `undefined`

### ISSUE THREAD

**Issue by gaurav21r** [ramda/ramda#1488]
I am doing a BFS for a new type of JSON Querying Language (to be Open Sourced soon!) and I'm trying to build it completely out of Ramda!

Consider this tree walk:

`[1, [2, 3], {a: 1, b: 2}]`
Changes to `[undefined, 2, 3, [1,2]]`
Changes to `[undefined, undefined, undefined, 1, 2]`

I am using `R.chain` / `R.map` primarily for this. As you can see I am unnecessarily traversing through `undefine`s.

I know I can combine `R.filter` and `R.map` but again that's wasting an entire pass!

Is there any way that I can do this in Ramda? Does it need another operator?

I think that this would be a common use case for anyone doing any sort of **Tree Traversing** with Ramda.

PS: It's always a pleasure raising issues here! The team is soooo responsive :smiley:

**Comment by davidchambers** [comment]
`R.chain` and `R.reduce` are useful when one wishes to map and filter in a single step. `R.chain` is likely to be particularly useful in this case because it can also change the shape of the data. For example:

```javascript
//    f :: * -> [Number]
const f = R.chain(R.cond([[R.is(Array),  R.identity],
                          [R.is(Number), R.of],
                          [R.is(Object), R.values],
                          [R.T,          R.always([])]]));

f([1, [2, 3], {a: 4, b: 5}]);  // => [1, 2, 3, 4, 5]
```

**Comment by gaurav21r** [comment]
@davidchambers i get your drift, but not exactly what I'm looking for. `chain` reduces nested arrays. Can you suggest something for this =>

```js
f({a: {b : 'c'}, e: [3, 4], f: [{h:[5,4]}])
f([ {b:'c'}, [3,4], [{h: [5,4]}] ])
f(['c', 3, 4, {h: [5,4]} ])
f([[5,4]])
```

**Comment by TheLudd** [comment]
I do not really understand what you are doing but if you want to do both filter and map and not iterate more than once, you can use `transduce`. 

```
var transduceFn = R.compose(R.map(mapFn), R.filter(filterFn))
R.transduce(transcudeFn, accFn, initialValue, list)
```

**Comment by gaurav21r** [comment]
@TheLudd I'm building a BFS system for traversing a json based on an arbitrary path given by the user. I'm using it for a JSON querying system.

Eg: If a user specifies something like `$.*.*` ie *traverse `2` levels down of root*
My function `f` should return `['c', 3, 4, {h: [5,4]} ]` for `{a: {b : 'c'}, e: [3, 4], f: [{h:[5,4]}]}` after being applied **twice**,  as per my example above :point_up: 

Can `transduce` do this for me?

**Comment by TheLudd** [comment]
> I know I can combine R.filter and R.map but again that's wasting an entire pass!

Transduce would let you do this without wasting a pass ([example](http://bit.ly/1ixnsSh)). But transduce is very similar to reduce which expects a list as it's last argument. If the input is an object then it might not be suitable since you cannot reduce objects. You could of course call `values` on the object first if you are not using the keys.

**Comment by CrossEye** [comment]
I'm afraid I'm not following what it is you're looking for, but it still sounds to me as if it isn't `map`.  The point of `map` is that it returns a new structure of the same shape as the original.  `filter` should be able to return a structure recognizably a substructure of the original.  `reduce` can return anything at all.

**Comment by OliverJAsh** [comment]
This sounds a lot like the `filterMap` function which exists in other languages like Elm: https://package.elm-lang.org/packages/elm/core/latest/List#filterMap
