### ISSUE TITLE
documentation of reduced is outdated

### ISSUE THREAD

**Issue by safareli** [ramda/ramda#1490]
it is referencing founctions which have been removed: reduceIndexed reduceRightIndexed https://github.com/ramda/ramda/blob/v0.18.0/src/reduced.js#L11-L12

**Comment by CrossEye** [comment]
Thanks.  Feel like creating a quick PR for this?

**Comment by safareli** [comment]
Welcome.

**Comment by davidchambers** [comment]
Fixed in #1492

**Comment by CrossEye** [comment]
Oh, trying to catch up in small snatches.  Thanks.

**Comment by safareli** [comment]
Welcome :3
