### ISSUE TITLE
is treats Array as Object

### ISSUE THREAD

**Issue by mpj** [ramda/ramda#1496]
``` javascript
R.is(Object, []) // true
```

Should we have an isPlainObject?

**Comment by raine** [comment]
The behavior seems correct as far as the documentation of `R.is` goes:

> See if an object (val) is an instance of the supplied constructor. This function will check up the inheritance chain, if any.

You could use `R.type`, and come up with something like:

`var typeEq = R.flip(R.useWith(R.equals, [ R.type, R.identity ]))`

**Comment by CrossEye** [comment]
Note that 

```js
R.is(Array, []); //=> true
```

And also

```js
Object.prototype.isPrototypeOf(Array.prototype); //=> true
```

So I think this is correct as designed.

I've never had need of anything like `isPlainObject`.  Care to try to justify it?

**Comment by henriklundgren** [comment]
```javascript
R.is(Array, []); //=> true
```

...should be in the examples for `R.is`. If for nothing else just as a heads up when you're reflecting on the usage. I was doing something like `partition(is(Object))([{}, []])`.
