### ISSUE TITLE
Bookmarklet 404

### ISSUE THREAD

**Issue by Conaws** [ramda/ramda#1501]
Dead link on Ramdajs homepage for bookmarklet

**Comment by CrossEye** [comment]
Well, it looks like the link is still there, pointing to https://github.com/ramda/ramda/blob/master/BOOKMARKLET.md

But that seems to be out-of-date, loading 0.17.1 on the page, so something's definitely not right.

**Comment by vog** [comment]
This issue still exists in 0.18.0, whose documentation (http://ramdajs.com/0.18.0/) points to:

http://ramdajs.com/0.18.0/BOOKMARKLET.md

which returns a 404.

**Comment by CrossEye** [comment]
I'll try to take a look tonight.  I'm not sure how this is built, or when it changed.

**Comment by davidchambers** [comment]
I doubt this ever worked. [__README.md__][1] contains a *relative* URL for [__BOOKMARKLET.md__][2]:

> ```markdown
> 
Or you can inject ramda into virtually any unsuspecting website using [the bookmarklet](BOOKMARKLET.md).
> ```

This works on GitHub but not on the Ramda website.

A straightforward solution is to use an *absolute* URL for __BOOKMARKLET.md__ instead.


[1]: https://raw.githubusercontent.com/ramda/ramda/v0.19.0/README.md
[2]: https://github.com/ramda/ramda/blob/master/BOOKMARKLET.md
