### ISSUE TITLE
.reverse() improvements proposal

### ISSUE THREAD

**Issue by houd1ni** [ramda/ramda#1502]
http://jsperf.com/ramda-reverse/4

Maybe, special type of _slice just for copying. (_copy()?)
We also can use this test thread's results: http://jsperf.com/new-array-vs-splice-vs-slice/113
And sometimes this is incredibly slow in EDGE. Idk why yet.

And how do you look at using different algorithms in different environments?
Maybe some sort of detection during initialization?

UPD1: Somebody has made my tests much more functional style and added *Array.prototype.slice()*. Thank you!

UPD2: Seems that copy2() *for-index*  copying with native *.reverse()* is the fastest (and 2nd in EDGE with a little difference).

UPD3: Changing the copying method gave ~10% to Chrome and great performance boost to EDGE.
           Perhaps, the bootle's neck is in _isString() or _curry1(). *Is it necessary to curry a function of one argument?..* Will try to check it in private tests.

UPD4: Have made another quick isString variant (in tests), making almost double boost in Chrome. If necessary, it will be same fast with numbers with
```javascript
    x.substr !== undefined && Object.prototype.toString.call(x) === '[object String]';
```

Waiting for response before making anything.

**Comment by CrossEye** [comment]
I'm not sure what you want to propose here.

I don't think many of these implementations would maintain the current API:

```js
R.reverse([1, 2, 3]); //=> [3, 2, 1]
R.reverse([{x: 1}, {x: 2}, {x: 3}]); //=> [{x: 3}, {x: 2}, {x: 1}]
R.reverse('abc'); //=> 'cba'
```

As to the currying, it's mostly there to support some lawful behavior in the presence of placeholder values.  There is now talk (#1449, #1497) of removing the placeholders, and then the currying would become unnecessary.

**Comment by houd1ni** [comment]
Thank you! I'm going to learn these talks.

I relied on tests here (*/test/reverse.js*). Tests with Objects are passing too (Objects are copied successfully too).

Seems, It could be faster with non-native copying implementation (copy2 in jsperf tests) and easier _isString check, that provides much faster way to distinguish that *It isn't a String*, keeping other functionality. It is what I want to propose.

All these things could make at least .reverse() is much faster at least for arrays even without changing curry algorithm.

**Comment by CrossEye** [comment]
Well, I'm sure we'd be more than willing to entertain a specific proposal.  Unless and until we decide to forgo the placeholders, we will try to [uphold certain laws][pl], including one that says that if for any function `fn` in Ramda, `fn(R.__)  ≍  fn`

I added the object case, because, while I didn't test it, it certainly looked as though at least one of your versions, `xor` would not work with anything other than numbers.

  [pl]: https://github.com/ramda/ramda/blob/d3fbf3d604f7cfaa1ebf246203d601dcca001779/src/__.js#L6-L15

**Comment by houd1ni** [comment]
I'm sorry for confusing, eventually I've decided to use Native reverse, but with other improvements.

**Comment by houd1ni** [comment]
The main bottleneck is in _isString, slowing down any request for arrays.

**Comment by CrossEye** [comment]
So what do you propose?

We're generally in favor of changes that improve performance so long as they don't change the API and stay within the style of other Ramda functions.

But we're generally not motivated by smaller performance changes.  When there are [substantial differences][sd] we take notice and try to fix issues, but the difference between 7m operations per second and "only" 4m operations per second, it seems less crucial.  It's not that we won't listen.  If you put a proposal in front of us, we would certainly consider it; it's simply that it won't become a high priority issue.


  [sd]: https://github.com/ramda/ramda/issues/1449#issuecomment-154561985

**Comment by houd1ni** [comment]
Okay, I'll just try to collect all similar issues, issue it and show as a PR with performance and functional(API compliance) tests nearest days. Thank you!

**Comment by CrossEye** [comment]
Great!  Thank you very much.

**Comment by houd1ni** [comment]
After fine tuning of tests to make it more real using node (In particular new data generating randomly before each loop to avoid inlining), started to play with length of test inputs.

Сoncluded that effect of using different helpers methods **is almost futile in cases of input.length>>10**, approx. linear from slight advantage of handmade to equity at ~100-1000 and then light existing implement advantage (on the native slice()). In practice, **carrying doesn't make any serious influence.**

=> You are completely, 100% right (I just have proven it). I'll keep the eye on possible troubles and issues here, just making more competitive tests anytime before making a decision.

Thank you!
One of long input variants: http://jsperf.com/ramda-reverse/5

**Comment by CrossEye** [comment]
Thanks for checking into this.
