### ISSUE TITLE
R.curry slows down resulting function way too much

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1503]
Altering @niloy's test on #1500, I found out that R.curry has a dramatic influence on performance, even when the result curried function is called with all of the arguments at once:

``` js
var arr = R.times(Math.random, 20000);

console.time("Object.is");
R.uniqWith(Object.is, arr);
console.timeEnd("Object.is");

console.time("R.curry(Object.is)");
R.uniqWith(R.curry(Object.is), arr);
console.timeEnd("R.curry(Object.is)");
```

results in latest Firefox nightlty:
Object.is: timer started repl.js line 123 > eval:2
Object.is: **276.76ms** repl.js line 123 > eval:4
R.curry(Object.is): timer started repl.js line 123 > eval:5
R.curry(Object.is): **68341.41ms**

**Comment by asaf-romano** [comment]
REPL link (remove ``throw 1`` and get some coffee): http://bit.ly/1MPu10K

**Comment by houd1ni** [comment]
Why you curry it every time before calling? Try to save result function before :)

**Comment by asaf-romano** [comment]
I don't curry it each time... the expression is evaluated right away, i.e. before it's passed to R.uniqWith. It makes no difference if you set in on a variable.

**Comment by houd1ni** [comment]
I see. just deleted the comment.

**Comment by asaf-romano** [comment]
Sigh, I just realized the same benchmark was done independently on #1449

**Comment by houd1ni** [comment]
Yeah, that issue is a starting point to think about (maybe) some compromises between reference and value equity. Looks, like sometimes it isn't necessary to compare values. But I'm going to deeply learn that thread.

**Comment by scott-christopher** [comment]
Some improvements to the currying functions when dealing with primitive arguments in #1512 have just landed in master which will give this a slight improvement.

Using an `arr` size of 5000 in the example above results in:
```
Object.is: timer started
Object.is: 140.62ms
R.curry(Object.is): timer started
R.curry(Object.is): 1081.84ms
```

Unfortunately, while support for placeholders exist in the currying functions there will continue to be a slight hit in performance. On a positive note, using `R.uniq` from the current HEAD of master for the above example now results in:
```
R.uniq: timer started
R.uniq: 2.54ms
```

**Comment by buzzdecafe** [comment]
we could probably get a further boost by setting properties on the function returned from `curry*` and doing the bookkeeping there (i.e. what args have we seen so far, placeholder (yuk), current arity). the problem with that approach is it blows away the returned function's `length` property, which would be handled by the function's metadata. in case external consumers are looking for `length`, i think as long as we provide a way to set arity on a function on the way out of ramda-world, this approach is acceptable.

**Comment by asaf-romano** [comment]
I think that setting some sort of meta-data on curried functions is necessary anyway (see #1483). How does it affect the function arity though?

**Comment by buzzdecafe** [comment]
> How does it affect the function arity

i'm suggesting that instead of returning a new function as arguments are applied, we keep returning the same function with its metadata updated. 

incidentally, metadata would be a good place to keep typing information.

**Comment by CrossEye** [comment]
@asaf-romano:
I don't think #1483 is really soluble, except by adding an additional composition function.  Breaking this:

```js
> R.compose(R.map, R.add)(10)([1, 2, 3])
[ 11, 12, 13 ]
```

is just too painful.  But if we automatically curry the result of `compose`, then this is broken, and unrecoverable.  As it stands, the user can simply call `curryN` on the output as necessary.

**Comment by CrossEye** [comment]
@buzzdecafe:
> i'm suggesting that instead of returning a new function as arguments are applied, we keep returning the same function with its metadata updated. 

Mutation of the function object?  I can't see that.  How could a user then use both the before and after versions of such a function or partially apply two different values to it?

But needing to return different functions might give a way to retain the arity at the same time.  It's worth considering.  But perhaps I'm the only one that has that concern.
