### ISSUE TITLE
Lack of method for removing array values

### ISSUE THREAD

**Issue by razzius** [ramda/ramda#1507]
Ramda provides `omit` for removing values from objects by key, but has no builtin way to remove values from an array.

Underscore for instance provides this under the [`without`](http://underscorejs.org/#without) moniker.

I'd be happy to try implementing this if it would be a welcome addition. It would look something like

```
without
[a] -> [a] -> [a]
Returns a partial copy of an array omitting the keys specified.

R.without([1, 2], [1, 2, 3, 4]); //=> [3, 4]
```

**Comment by TheLudd** [comment]
What you are describing is really just a flipped version of [difference](http://ramdajs.com/0.18.0/docs/#difference). 

[Example..](http://bit.ly/1PojmKI)

**Comment by razzius** [comment]
There is one difference - `R.difference` returns a set, when in some cases it might be desirable to return the original array with duplicates preserved:

```
without([1], [1, 2, 2]) //=> might want to equal [2, 2]
```

**Comment by TheLudd** [comment]
I see the difference. But then this is not comparable to `omit` which works on keys. A similar function would work on indexes.

```
R.without([1, 2], [1, 2, 3, 4]); //=> [1, 4]
```

**Comment by razzius** [comment]
You're right, `omit` is not comparable - I hadn't noticed `difference` at the time of asking, hence the confusion with `omit`, which was the closest thing I'd seen at that time.


I suppose the question of whether there should be a `difference` that preserves duplicates is another matter entirely.

**Comment by razzius** [comment]
In my original use case the `difference`-as-set behavior would have been adequate, though, so I'll close this issue.

**Comment by CrossEye** [comment]
It's been sitting for a while, but #1423 addresses this.
