### ISSUE TITLE
R.contains is quite slow

### ISSUE THREAD

**Issue by greggigon** [ramda/ramda#1508]
[https://jsperf.com/ramda-contains-vs-indexof](https://jsperf.com/ramda-contains-vs-indexof) simple test of looking up for a single char in the Array of chars.

Used **R.contains** agains **Array.indexOf > -1**

I can see some performance issues raised in the last few months. Not sure they are related.

**Comment by buzzdecafe** [comment]
probably related. see https://github.com/ramda/ramda/issues/1449 we may be seeing some improvements presently

**Comment by CrossEye** [comment]
Note that part of the reason for the difference is the difference in the APIs:

```js
var haystack = [{a: 1}, {b: 1}, {c: 1}, {d: 1}, {e: 1}, 
                {f: 1}, {g: 1}, {h: 1}, {i: 1}, {j: 1}, 
                {k: 1}, {l: 1}, {m: 1}, {n: 1}, {o: 1}, 
                {p: 1}, {q: 1}, {r: 1}, {s: 1}, {t: 1}, 
                {u: 1}, {v: 1}, {w: 1}, {x: 1}, {y: 1}, 
                {z: 1}];

var needles = [{a: 1}, {b: 1}, {c: 1}, {d: 1}, {e: 1}, 
               {f: 1}, {g: 1}, {h: 1}, {i: 1}, {j: 1}];

var nativeContains = function(needle, haystack) {
  return haystack.indexOf(needle) > -1
};

R.map(needle => nativeContains(needle, haystack), needles);
//=> [false, false, false, false, false, false, false, false, false, false]

R.map(needle => R.contains(needle, haystack), needles);
//=> [true, true, true, true, true, true, true, true, true, true]
```

`Array.prototype.indexOf` does not recognize that `{a: 1}` is the same as `{a: 1}`.  When doing functional programming, reference equality should mean little.  It's value equality that's important.

Of course it we were using shared references, there is no difference:

```js
var needles2 = haystack.slice(0, 10);

R.map(needle => nativeContains(needle, haystack), needles2);
//=> [true, true, true, true, true, true, true, true, true, true]

R.map(needle => R.contains(needle, haystack), needles2);
//=> [true, true, true, true, true, true, true, true, true, true]
```
  
Nonetheless, we do have to find a way to note when we're searching a list of value types, and not attempt a more complex `equals` operation on them.  Any suggestions of what the API for that would look like?

**Comment by scott-christopher** [comment]
#1512 has landed in master which provides a little boost in performance to `R.contains`, however I have just raised #1530 to address this specifically.

**Comment by kedashoe** [comment]
#1530
