### ISSUE TITLE
No dedicated tests for lens functions

### ISSUE THREAD

**Issue by gilligan** [ramda/ramda#1509]
As mentioned in #1506 there are no separate tests for the individual lens functions, instead there is only .`test/lenses.js` which is mostly about the functionality of view/set/over and combining lenses. 

There should be separate tests for `lensProp`, `lensIndex` (and if #1506 gets merged also `lensPath`) each testing its functionality in regard to view/over/set.

**Comment by gilligan** [comment]
I started working on this. See f.ex : https://github.com/gilligan/ramda/blob/split-lens-tests/test/lensProp.js

**Comment by CrossEye** [comment]
Thank you!  I look forward to seeing this.

(Just noted that https://github.com/gilligan/ramda/blob/split-lens-tests/test/lensProp.js#L31 is probably a cut-and-paste error.)
