### ISSUE TITLE
Honor valueOf in value equality checks

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1518]
If an object implements `valueOf`, and if that implementation returns a primitive[1][2], it'd be reasonable for `R.equals` and related functions (`difference`, `contains`, etc) to "dispatch" to  that method in addition to the current explicit `equals` dispatching. The work done in #1512 could thereafter be leveraged to support many native and non-native non-primitive objects. The first examples that come to mind are, of course, `Date` and `Moment` . Both of which don't implement `equals` (moment implements `isSame`), but do implement `valueOf`.

Furthermore, `R.memoize` could see a nice performance boost by utilizing such primitive-valueOf before it falls to R.toString.

Note that few libraries already leverage `valueOf` this way (Notably, immutable.js).

---

[1] Even if it returns an object (and if that object is not the original object itself), it might makes sense to use it as the base for comparison.
[2] +-0 will need some special handling.

**Comment by CrossEye** [comment]
This sounds good.

Would this go in `_equals` right after

    if (a == null || b == null) {
      return false;
    }

?

I don't think I buy this: 

> Even if it returns an object (and if that object is not the original object itself), it might makes sense to use it as the base for comparison.

which I think could lead to infinite regress.  But other than that, this makes sense to me.

**Comment by asaf-romano** [comment]
Yeah, that's a "bonus" that has to be implemented very carefully, if at all, but that can be very useful. I was thinking of a "classed"/"prototyped" object returning a simple pojo that's better suited for value-equality comparison. That would ease dealing with situations like the one I described in #1383.

**Comment by asaf-romano** [comment]
Regarding the placement: For an explicit operation like R.equals, I think it makes sense to give priority to explicit ``equals`` dispatching. In the context of R.difference and such, ``valueOf`` is way more useful as it could be used as sort of an hash-key.

**Comment by melinath** [comment]
+1 on being able to implement a valueOf (or really _any_ custom method) that ramda would use to get a representation suitable for checking equality.

**Comment by davidchambers** [comment]
This should be possible one day thanks to [`fantasy-land/equals`][1]. :)


[1]: https://github.com/fantasyland/fantasy-land#equals-method
