### ISSUE TITLE
How can I find if a string is within a JSON field?

### ISSUE THREAD

**Issue by d3netxer** [ramda/ramda#1523]
How can I find if a string is within a JSON field?

**Comment by davidchambers** [comment]
Could you elaborate?

**Comment by d3netxer** [comment]
Yes, here is a sample record I am parsing:

{ metadata: 
   { id: '35362716',
     created_at: '2015-11-16T21:55:50Z',
     closed_at: '2015-11-16T21:55:51Z',
     open: 'false',
     num_changes: '5',
     user: 'Lpatter_GMU',
     uid: '3376869',
     min_lat: '-23.0316748',
     max_lat: '-23.0316071',
     min_lon: '26.4924867',
     max_lon: '26.4925596',
     comments_count: '0',
     comment: '#hotosm-project-899 #PeaceCorps #PeaceCorpsBotswana #osmgeoweek #pcosmgeoweek source=Bing',
     locale: 'en-US',
     host: 'https://www.openstreetmap.org/id',
     imagery_used: 'Bing',
     created_by: 'iD 1.7.4' },
  elements: 
   [ { id: '3839981199',
       lat: '-23.0316748',
       lon: '26.4925011',
       version: '1',
       timestamp: '2015-11-16T21:55:50Z',
       changeset: '35362716',
       uid: '3376869',
       user: 'Lpatter_GMU',
       action: 'create',
       type: 'node',
       tags: {} },
     { id: '3839981200',
       lat: '-23.0316604',
       lon: '26.4925582',
       version: '1',
       timestamp: '2015-11-16T21:55:50Z',
       changeset: '35362716',
       uid: '3376869',
       user: 'xxxx',
       action: 'create',
       type: 'node',
       tags: {} },
     { id: '3839981201',
       lat: '-23.0316120',
       lon: '26.4925438',
       version: '1',
       timestamp: '2015-11-16T21:55:50Z',
       changeset: '35362716',
       uid: '3376869',
       user: 'Lpatter_GMU',
       action: 'create',
       type: 'node',
       tags: {} },
     { id: '380670357',
       version: '1',
       timestamp: '2015-11-16T21:55:50Z',
       changeset: '35362716',
       uid: '3376869',
       user: 'Lpatter_GMU',
       action: 'create',
       type: 'way',
       tags: [Object],
       nodes: [Object] } ] }

**Comment by d3netxer** [comment]
see the comment field?  comment: '#hotosm-project-899 #PeaceCorps #PeaceCorpsBotswana #osmgeoweek #pcosmgeoweek 

I am looping through a list of specified hashtags and want to filter the records that contain a hashtag in the comment field

**Comment by d3netxer** [comment]
this isn't returning anything:

hashtagRecords = R.filter(R.match('comment', hashTagArray[index]), obj);

neither is this:

var hashtagRecords = R.filter(R.where({comment: R.contains('hashTagArray[index]')}))(obj);

**Comment by d3netxer** [comment]
or this: 

hashtagRecords = R.filter(R.propEq('comment', hashTagArray[index]), obj);

**Comment by davidchambers** [comment]
What is the value of `hashTagArray`? Please take advantage of [GFM][1] to format your code snippets. :)


[1]: https://help.github.com/articles/github-flavored-markdown/

**Comment by scott-christopher** [comment]
@d3netxer: if I understand correctly, you could do something like:
```js
var hasHashtag = R.curry((hashtag, obj) =>
  R.propSatisfies(R.test(new RegExp('#' + hashtag + '\\b', 'i')), 'comment', R.prop('metadata', obj)));
```
And assuming the example object you provided above is assigned to a variable called `item`, you can then check whether it contains a given hashtag like so:
```js
hasHashtag('peacecorps', item); // true
```
So if you have a list of these objects in a variable called `items`, you could then filter them using:
```js
var onlyPeaceCorpItems = R.filter(hasHashtag('peacecorps'), items);
```

**Comment by d3netxer** [comment]
@davidchambers 

```// Hashtag array
var hashTagArray = ["#hotosm-project-1185", "#MissingMaps", "#RedCross", "#Khayelitsha", "#MapGive" ];```

**Comment by d3netxer** [comment]
@scott-christopher using the curried function is a bit over my head. I need up converting the comment field into an array first, that made it easier to check if a hashtag was in the array. Thanks

**Comment by CrossEye** [comment]
Another way to think about it:

```js
// Tag -> Record -> Bool
var hasHashTag = R.curry(R.useWith(
  R.contains, // Tag -> [Tag] -> Bool
  R.identity, // Tag -> Tag
  R.pipe(R.path(['metadata', 'comment']), R.split(' ')) // Record -> [Tag]
));
```

It doesn't have the features of the solution from @scott-christopher that you can skip the initial `'#'` and that its a case-insensitive test.   But I think it's reasonably clean, and with the annotations, I hope it's fairly clear as well.

**Comment by CrossEye** [comment]
... and the same thing, split apart a little differently:

```js
// Record -> [Tag]
var getTags = R.pipe(R.path(['metadata', 'comment']), R.split(' '));

// Tag -> Record -> Bool
var hasHashTag = R.curry((hashtag, record) => R.contains(hashtag, getTags(record)));
```

**Comment by d3netxer** [comment]
Thanks, I re-looked at this and understand everything except what curry does or what '=>' means

**Comment by scott-christopher** [comment]
The `=>` is used to separate the argument list from the function body in the newer [ES6 arrow function syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

The example above:
```js
(hashtag, record) => R.contains(hashtag, getTags(record))
```
is equivalent to:
```js
function (hashtag, record) {
  return R.contains(hashtag, getTags(record))
}
```

As for `R.curry`, I'd suggest having a read of http://fr.umio.us/favoring-curry/

**Comment by d3netxer** [comment]
Thanks @scott-christopher those resources help a lot.
