### ISSUE TITLE
Incorrect lens type signature (v 0.18)

### ISSUE THREAD

**Issue by jackfirth** [ramda/ramda#1531]
The docs for `lens` declare it has the following type signature:

```
(s -> a) -> ((a, s) -> s) -> Lens s a
```

This claims the setter function must accept a tuple of a new focus and a target. However the example given, which works at the repl, provides a function `R.assoc('x')` of type `(a -> s -> s)`:

```
var xLens = R.lens(R.prop('x'), R.assoc('x'));
```

Based on this behavior, the type of `lens` should be:

```
(s -> a) -> (a -> s -> s) -> Lens s a
```

Assuming `(a, s)` is the type of a two element array, it's probably a bit more awkward to use tuples than two-argument functions.

**Comment by buzzdecafe** [comment]
In a reasonable language I would agree with you. However, since this is javascript, there is a problem with `a -> s -> s` (apart from the fact that it spells "ass"). 

> Assuming `(a, s)` is the type of a two element array,

Unfortunately that assumption doesn't hold. The setter needs a function of arity 2, not a two-element array masquerading as a tuple.

So, I don't think it would be smart enough to handle e.g.

```js
function f(a) {
  return function (b) {
     return a + b; // whatever
  };
}
```

... although that matches the "ass" signature. But this should be fine:

```js
function f(a, b) {
  return a + b;
}
```

... and so should a ramda-style curried function, because it will behave correctly w/r/t the arity.

**Comment by CrossEye** [comment]
Any suggestions for how we could clearly and unambiguously extend this type signature to handle the sorts of things we deal with in JS would be quite welcome.

For Ramda's uses, we generally don't have to deal with optional parameters, and we are almost done with variadic functions (although callbacks passed to us _could_ be variadic.)  But, though we generally report our functions as though they are purely curried, they're really not.  

As @buzzdecafe says, `R.assoc('x')` is a binary function which, if called with only one parameter, will return a unary function that applies both values to the underlying definition.  The difference between this and a truly curried function is not particularly subtle, but it's unimportant for normal usage.  It does lead to some problems with these descriptions, though.  I would love to have an obvious and unambiguous extension of the signature syntax that captured this.

Any ideas?

**Comment by jackfirth** [comment]
Ah right, I completely forgot about those issues. I had to solve a similar problem with a project adding Haskell types to a language with uncurried functions, and settled on a syntax looking like `(a b -> c)`. Using commas or more delimiters throws me off because I associate it with list/tuple types. With that approach, `lens` would have type `(s -> a) -> (a s -> s) -> Lens s a`.

...but that only works without higher kinded types because otherwise it looks like it takes one argument and `a` has kind `* -> *`. Maybe drop the parens, but keep the comma? Like `(s -> a) -> (a, s -> s) -> Lens s a`

**Comment by davidchambers** [comment]
`(a, s -> s)` looks nice but is ambiguous: should be read `((a, s) -> s)` or `(a, (s -> s))`?

**Comment by jackfirth** [comment]
Looking at the types of the `*With` functions `containsWith`, `differenceWith`, `dropRepeatsWith`, `intersectionWith`, `unionWith`, and `uniqWith` all use the `(a, b -> c)` form (however some drop the space like `(a,b -> c)`). However `useWith` uses `(x -> x2 -> ... -> z)`, which seems like it should be `(x, x2 ... -> z)` for consistency. `addIndex` uses both `(a ... -> b)` and `(a ..., Int, [a] -> b)`. `lens` definitely is the odd one out here, it's the only one whose type adds parens.

**Comment by jackfirth** [comment]
@davidchambers I think if it's standing alone, it would be `(a, (s -> s))`, but when it's the argument to a function the parens are needed, making it `((a, s) -> s)`.

**Comment by CrossEye** [comment]
The docs are very inconsistent in this.  We know that.  I'd really like to figure out a consistent approach and then give everything another look to ensure it meets that standard.

@jackfirth: I didn't quite follow this:

>  I think if it's standing alone, it would be (a, (s -> s)), but when it's the argument to a function the parens are needed, making it ((a, s) -> s)

Are you suggesting that `(a, s -> s)` would be parsed differently depending on whether it was the entire expression or if it were part of, say, `(s -> a) -> ((a, s) -> s) -> Lens s a` ?  If so, I don't really like that idea.  ISTM that it would get quite confusing if we allowed that.

**Comment by jackfirth** [comment]
@CrossEye Yes, that was my first thought. I now realize that's a very confusing way to do things.
