### ISSUE TITLE
What do you call this function?

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1532]
I've had to use this function on more than one occasion and I never know what to name it. 

```
divvy = R.curry (a, b) ->
  [R.difference(a, b), R.difference(b, a)]
```

I find myself using it a lot to determine whats old and whats new.

**Comment by ecwyne** [comment]
It's not quite [complement](https://en.wikipedia.org/wiki/Complement_(set_theory)) but it feels close

[Visualization](https://www.wolframalpha.com/input/?i=%28complement+A%29+union+%28complement+B%29)

**Comment by ccorcos** [comment]
That's close! I'm thinking about calling it vanDiagram and returning 3 elements in the array.
