### ISSUE TITLE
How to implement a index for an array of objects

### ISSUE THREAD

**Issue by acroca** [ramda/ramda#1535]
Hi,

I'm not sure how to implement something like the following:
```javascript
R.reduce(function(acc, item){
  return acc[item.a] = item
}, {}, [
  {a: 'foo', b: 1},
  {a: 'bar', b: 2},
])
// {foo: {a: 'foo', b: 1}, bar: {a: 'bar', b: 2}}
```
it's like a reduce that always returns an object using one of the fields as a key and the whole element as a value. It's a bit like a `groupBy` but assuming the items are unique. It  behaves like an index by one of the keys of the objects.
It can also return as a value one of the values as well, like `{foo: 1, bar: 2}` if it uses `'a'` as key and `'b'` as a value.

Can you think of any better implementation for this logic?

Thank you.

**Comment by raine** [comment]
When in doubt, check the cookbook.

https://github.com/ramda/ramda/wiki/Cookbook#index-objects-by-property-name

**Comment by acroca** [comment]
My real need is to index with a key as a key and another key as a value. I changed it a bit and got this:
```javascript
R.curry(function(propK, propV, list) {
  return R.mapObj(R.compose(R.prop(propV), R.head), R.groupBy(R.prop(propK), list));
})
```
I'm a bit worried about memory allocation of this compared with the reduce and the function I wrote in the issue description.

**Comment by acroca** [comment]
I ended up with a more generic function for my use case. I'll leave it here in case is useful for someone:
```javascript
var indexFn = R.curry(function(k, v, arr) {
  return R.reduce(function(acc, i) {
    acc[k(i)] = v(i);
    return acc;
  }, {}, arr);
});
```
So I now I can do:
- `indexFn(R.prop('a'), R.identity, arr)` to index an array by one of the attributes
- `indexFn(R.prop('a'), R.prop('b'), arr)` same as before, but the value will be another attribute
- `indexFn(R.identity, R.T, arr)` to get something like `['a', 'b', 'c']` into `{a: true, b: true, c: true}`
