### ISSUE TITLE
Update path documentation

### ISSUE THREAD

**Issue by steida** [ramda/ramda#1536]
Because this check https://github.com/ramda/ramda/blob/cffff75259a5b251811bc5197ea6ec41b33731e2/src/path.js#L26
both null and undefined are checked. Or fix code and use !== instead.

`R.path(['a', 'b'], {c: {b: 2}}); //=> undefined or null`

**Comment by svozza** [comment]
Do you mean something like this is incorrect?

```javascript
R.path('a', 'b', {a: 1, b: null}) => // undefined
```

**Comment by iofjuupasli** [comment]
```js
R.path(['foo', 'bar'], {foo: null}) === null
```

It returns value of `obj.foo`. But as I understand it should return value of `obj.foo.bar` or `undefined`

**Comment by svozza** [comment]
Ah yes, I get what you mean now. Yeah, I'd expect `undefined` there too.

**Comment by CrossEye** [comment]
I see @svozza's fine fix in #1537.

My only question is whether we want to fix the code, or whether we're better adjusting the documentation.  Which is the better response for

```js
R.path(['foo', 'bar'], {foo: null}) 
```

`undefined`?  or `null`?

**Comment by steida** [comment]
I think documentation should be updated. We need to test both values.
undefined is absence of evidence, while null is evidence of absence.

**Comment by svozza** [comment]
I'm conflicted about this, on the one hand I wish JavaScript only had one `null` value (or `Maybe` even none :wink:) but we are where we are. I've used APIs where `null` had meaning as opposed to `undefined`and a user doing so is not necessarily doing anything incorrect by respecting the distinction the language makes. End of the day, this is just wrong:

```js
R.path(['a', 'b', 'c'], {a: null}); // => null
```
