### ISSUE TITLE
How to call each function with an argument, point-free?

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1542]
This is effectively what I want to accomplish.

```js
let a = 1
let f = (x) => x+1
let g = (y) => x-1

callEachWith(a, [f, g])
// => [2, 0]
```

I'd love to figure out how to do with the functional composition of existing ramda functions. Any ideas?

**Comment by raine** [comment]
```
> R.ap([f, g], [a])
[ 2, 0 ]
```

**Comment by ccorcos** [comment]
I just figured this one out, but I like yours more! :+1: 

```
map(call(__, a),[f, g])
```
