### ISSUE TITLE
What is R.lift?

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1543]
This makes no sense to me:

```js
var madd3 = R.lift(R.curry((a, b, c) => a + b + c));
madd3([1,2,3], [1,2,3], [1]); //=> [3, 4, 5, 4, 5, 6, 5, 6, 7]
var madd5 = R.lift(R.curry((a, b, c, d, e) => a + b + c + d + e));
madd5([1,2], [3], [4, 5], [6], [7, 8]); //=> [21, 22, 22, 23, 22, 23, 23, 24]
```

I just that its combinatoricly adding the numbers together, but I'm not sure why you'd use it -- yet I hear its a very important function. When would you *actually* use this?

**Comment by CrossEye** [comment]
Some of these algebraic functions are hard to demonstrate on lists.  The unit tests have a slightly more useful example:

```js
var addM = R.lift(R.add);
addM(Maybe.Just(3), Maybe.Just(5)); //=> Maybe.Just(8);
```

So `add` operates on values.  `lift(add)` operates on containers of values.

Does that help?

**Comment by ccorcos** [comment]
I see. So it maps over each argument. That makes more sense to me. Thanks!
