### ISSUE TITLE
Support for `indexBy`

### ISSUE THREAD

**Issue by Chris911** [ramda/ramda#1545]
There's an example in the wiki on how to index an array of objects by a property: https://github.com/ramda/ramda/wiki/Cookbook#index-objects-by-property-name

Is there a reason why this isn't a "native" Ramda function? Would you accept a PR that introduces this function?

**Comment by davidchambers** [comment]
It is a useful function. I'm open to a pull request. :)

**Comment by Chris911** [comment]
Alright I'll get on it then :+1:

**Comment by Chris911** [comment]
@davidchambers implemented here: https://github.com/ramda/ramda/pull/1546
