### ISSUE TITLE
Add info about @since to CONTRIBUTING.md

### ISSUE THREAD

**Issue by gilligan** [ramda/ramda#1548]
I just recently saw another PR where someone added a `@since` tag to the PR and @scott-christopher mentioned that one should not add this since it will be added automatically on the next release. 

if I knew what the process is I would do a PR with the info myself but I don't - hence this PR so it's not forgotten ;-)

**Comment by scott-christopher** [comment]
Thanks for raising the issue @gilligan. `CONTRIBUTING.md` has been updated.
