### ISSUE TITLE
Update R.call and R.pair documentation

### ISSUE THREAD

**Issue by kookoskar** [ramda/ramda#1550]
The example provided in [`R.call`](http://ramdajs.com/0.18.0/docs/#call) doesn't work in 0.18.0 (`R.converge` takes a list as the second argument).

The example provided in [`R.pair`](http://ramdajs.com/0.18.0/docs/#pair) should, for consistency's sake, use `R.pair()` not just `pair()`.

**Comment by davidchambers** [comment]
Thank you for raising these issues, @kookoskar. Would you like to open a pull request to address them?
