### ISSUE TITLE
Add constructor wrapper

### ISSUE THREAD

**Issue by jasmith79** [ramda/ramda#1561]
How about wrapping constructors so that they play nicer with functional techniques like `map`ping, `apply`ing, etc.? Sample (ES 6) implementation might look like

```javascript
R.unNew = R.curryN(2, function(...args) {
  var constructor = args[0];
  if (typeof constructor !== 'function') {
    throw new Error("Invalid argument to function unNew");
  } else {
    return new (Function.prototype.bind.apply(constructor, args));
  }
};
```

Sample use might be something like

```javascript
let dateFn = R.unNew(Date);
let arr = [2015, 1, 1];
let janFirst = R.apply(dateFn, arr); 
```

Does anybody else like this? If so I'll write it for ES 3 and put it and some tests into a pull request.

**Comment by stoeffel** [comment]
There is already `construct`. See http://ramdajs.com/docs/#construct
