### ISSUE TITLE
Strangle

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1563]
A nice easy function for bounding a number's minimum and maximum.

```js
const strangle = curry((min, max, value) => {
  return value < min ? min :
         value > max ? max :
         value
})
```

**Comment by niloy** [comment]
Nice function, but `strangle` is such a weird name. `bound` or `clamp` sounds nice.

**Comment by ccorcos** [comment]
clamp -- I think thats more commonly used...

**Comment by CrossEye** [comment]
: herb:

I can definitely see this being useful.
