### ISSUE TITLE
mergeWithSpec

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1583]
The new `mergeWithKey` function is pretty nice, but with its callback being ternary, it's not as useful if one has more than a single key to deal with. Inspired by the new function and by `evolve`, I came up with something like this:

``` js
  var mergeWithSpec = R.useWith(R.mergeWithKey, [spec => (k, l, r) => spec[k] ? spec[k](l, r) : l,  R.identity, R.identity]);
  var objects = R.repeat({ a: 1, b: 2 }, 10);
  var foldThem = R.converge(R.reduce(mergeWithSpec({ a: R.add, b: R.multiply })), [R.head, R.tail]);
  foldThem(objects);  // => {"a": 10, "b": 1024}
```

This is far more useful, imho. What do others think?

---

I know the name is a little problematic given the use of `with` elsewhere.

**Comment by CrossEye** [comment]
I'm wondering if this example might make it more clear:

```js
var combine = mergeWithSpec({min: R.min, max: R.max, vals: R.concat});
var a = {name: 'foo', min: 10, max: 20, vals: [12, 17, 20, 10]};
var b = {name: 'bar', min: 13, max: 25, vals: [18, 25, 13]};
combine(a, b); //=> {name: 'bar', min: 10, max: 25, vals: [ 12, 17, 20, 10, 18, 25, 13]}
```

I can see the usefulness, I suppose, although I've yet to have a real need for this or for `mergeWithKey` myself.

**Comment by buzzdecafe** [comment]
isn't this just sugar for `mergeWith(where(spec))`?

**Comment by asaf-romano** [comment]
mergeWith doesn't pass the key to the function.

**Comment by asaf-romano** [comment]
> I'm wondering if this example might make it more clear:

My own use case was pretty much something like this: I had "raw" entries in the db that I wanted to fold into a logical combined entries:
```js
var foldEntries = mergeWithSpec({ values: intersection, name: concat, _id: always(null));
```

**Comment by asaf-romano** [comment]
Personally, I view this as a replacement for ``mergeWithKey``, rather than a companion. I think that the use case for ``mergeWithKey`` is very restrictive. Once there's more than a single key to process, a simple lamda doesn't do the trick, and ``cond`` doesn't play well either because both the condition and the consumer need to take care of all three arguments.

**Comment by buzzdecafe** [comment]
ok, well `mergeWhere` might be a better name anyways

**Comment by gilligan** [comment]
Thanks for the example @CrossEye - i really did not get what was going on before ;)

@buzzdecafe I don't think `mergeWhere` would fit since this would suggest that there is some filtering *on what* is being merged where what actually happens is that the caller can specify *how* values of identical values are being merged. 

Then again I just realised i am not sure if only the keys which have been specified will be merged using the provided functions) or everything.

Either way, perhaps `mergeWith` would be better ? I have to say though that while this seems _nice_ I am not sure I would personally find it interesting enough to include into ramda.

**Comment by asaf-romano** [comment]
The current behavior:
1. key only in ``l`` or ``r`` - value from ``l`` or ``r`` respectively
2. key in both, and also in the spec, the result of applying the spec function on the values
3. key in both, but not in spec, the value from ``l`` is used.

**Comment by Zip753** [comment]
@asaf-romano Great idea! I also have a use-case, where I have a list of objects of the same shape and need to aggregate them in a non-trivial way (where `R.mergeWith` didn't suffice).

I came up with a somewhat different implementation, but it doesn't handle missing props the nice way your implementation does. I'm posting it below just for reference:
```javascript
const argsToList = R.unapply(R.identity);
const mergeWithSpec = config => R.pipe(
  argsToList,
  R.reduce(R.evolve, config),
);
```
