### ISSUE TITLE
Bug with R.equals?

### ISSUE THREAD

**Issue by cowlike** [ramda/ramda#1584]
http://ramdajs.com/repl/?v=0.19.0#R.equals%280%2C%20R.modulo%28-4%2C%202%29%29%3B%0A

Why is this false? If I check `R.type(R.modulo(-4, 2));` it is a "Number" and if I just `+0` to it then the equals check returns true.

**Comment by asaf-romano** [comment]
``Object.is(0, -0); // false``

**Comment by svozza** [comment]
```js
1/-0 // => -Infinity
1/0 // => Infinity
```

**Comment by cowlike** [comment]
Ugh this seems inconsistent to me:
`Object.is(-1, -1+0)  //true`
`Object.is(-0, -0+0) //false`

**Comment by svozza** [comment]
It's slightly surprising but if you think about what happens when you add a number to the negative version of itself you always get `0` so `-0 + 0 = 0`; that means your second expression is equivalent to `Object.is(-0, 0)`.

**Comment by cowlike** [comment]
Ok, thanks for the explanation.

**Comment by svozza** [comment]
Welcome to JavaScript!
