### ISSUE TITLE
Feature request: easier to read source

### ISSUE THREAD

**Issue by Sequoia** [ramda/ramda#1585]
Reading [the source](https://github.com/ramda/ramda/blob/v0.19.0/src/lens.js) when...
```js
module.exports = _curry2(function lens(getter, setter) {
  return function(f) {
    return function(s) {
      return map(function(v) { return setter(v, s); }, f(getter(s)));
    };
  };
});
```
`f`? `s`? `v`? `s` is... I think the property name? Or wait, maybe `v` is the propname and `s` is . . . well `f` if "function", that's clear, but what is the function's purpose here?

### Benefit
1. Easier to read source
2. Makes Ramda a better teaching tool
3. Makes it easier for newbs to understand & contribute

### Cost
1. ???

**Comment by CrossEye** [comment]
Are you looking for names for those three properties in this function, or do you think it's an issue endemic to Ramda in general?

Ramda does try to keep reasonably readable source-code.  I picked another function at random.  `anyPass` is defined like this:

```js
module.exports = _curry1(function anyPass(preds) {
  return curryN(reduce(max, 0, pluck('length', preds)), function() {
    var idx = 0;
    var len = preds.length;
    while (idx < len) {
      if (preds[idx].apply(this, arguments)) {
        return true;
      }
      idx += 1;
    }
    return false;
  });
});
```

Here we do abbreviate a number of variables, `'idx'` for `'index'`, `'len'` for `'length'`, and `'preds'` for `'predicates'`, but to me its quite readable.  I _believe_ the vast majority of our source code is of this type.

Lenses are a particularly abstract data structure.  Perhaps we could replace `'f'`, `'s'`, and `'v'` -- if my tenuous grasp of lenses is correct (pinging @davidchambers or @scott-christopher!)  -- with `'fn'`, `'structure'`, and `'value'`.  Note that `'fn'` is what we generally use for arbitrary functions.  But `'structure'` and `'value'` are not really meaningful names; they're as bad as calling a variable `'data'` or `'info'`.  I think making a change like that just generates a false sense of understanding: "Oh so **this** is the structure, and **that** is the value, I get it!"  But I can certainly be convinced otherwise.

Do you have other suggested names for these?  Or any way to write the code that's more clear?

**Comment by CrossEye** [comment]
... and I forgot to say that "property name" is not the correct abstraction.  Lenses are applicable to all sorts of data structures, not simply Objects.

**Comment by CrossEye** [comment]
... and still further, there is clearly a need to describe **what** a lens is, and how it works.  Several issues recently have touched on this need, and I hope we can address this soon.  But `Lens` is one of the oddest functions in the library.  It doesn't return a value that the user is likely to use directly, only one that can be fed into functions like `view`, `set`, and `over`.  This is not something Ramda generally does.

**Comment by scott-christopher** [comment]
Some other options for the argument names in `lens`, if it is specifically regarding that particular function.
* `f`: `toFunctorFn`
* `s`: `target`
* `v`: `focus`

We could also document how the lens machinery works inside the implementation of the function, though I'd probably suggest leaving it out of the API docs for the sake of brevity.

**Comment by davidchambers** [comment]
I like those names, Scott!

**Comment by CrossEye** [comment]
Should we refactor with those names?

(And my grasp was clearly more tenuous than I thought.  I have the abstraction right, I believe, but little understanding of the implementation!)

**Comment by scott-christopher** [comment]
I've raised #1588 to address the specific concerns raised about the various lens functions.

**Comment by davidchambers** [comment]
@Sequoia, are there other functions you'd like to see changed, or were the lens functions the only offenders?

**Comment by Sequoia** [comment]
@davidchambers I opened this issue because I was having trouble when investigating this particular function (via `lensProp`). There are probably other places in the source that could be improved with such changes, but I have not done a thorough review. If I encounter other issues I'll be sure to raise them!

The only other thing I can think of off-hand is the `assoc` function. Why is the name so short? Does it stand for... "associative?"

**Comment by Sequoia** [comment]
I think ultimately, a blog post or "guide" might be a better solution for "lenses." They are a specific concept that goes beyond the more general FP style Ramda enables. Maybe a code walk-thru. Is there such a guide?

**Comment by davidchambers** [comment]
> Is there such a guide?

Not a Ramda-specific one, but @DrBoolean's [Lenses Quick n’ Dirty][1] is terrific! Ramda's implementation is very similar to the one Brian presents in the video, which is no coincidence: I watched the video several times before updating Ramda's lens functions.


[1]: https://vimeo.com/104807358

**Comment by DrBoolean** [comment]
Ha! Funny story - I woke up today and decided to start contributing to ramda's lens effort :)

I'd love to add maps, traverses, iso, and folds if that's not too much...

**Comment by davidchambers** [comment]
> I'd love to add maps, traverses, iso, and folds if that's not too much...

Yes, please!

**Comment by scott-christopher** [comment]
@Sequoia: There's also a good blog post about lenses with Ramda and Virtual-Dom recently written by @joneshf too: http://joneshf.github.io/programming/2015/12/19/Lenses-and-Virtual-DOM-Support-Open-Closed.html

**Comment by scott-christopher** [comment]
> @DrBoolean: I'd love to add maps, traverses, iso, and folds if that's not too much...

I'd really like to see these too, though I suspect they may be better suited in their own package (arguably along with the existing lens functions in Ramda). I floated the idea of a separate `ramda-lens` library a while ago – perhaps it might be the time to pursue it now? I also have some prism prototypes which could potentially end up there too: https://github.com/scott-christopher/ramda/commit/ff755e192dfa3124f28650c503b40c98391ff0f7

**Comment by DrBoolean** [comment]
@scott-christopher That's super cool. I'd love to play with those prisms. I'm most interested in adding `iso` to work with a few immutable js lenses I've been using:

```
var lensImmutable = function lensImmutable(k) {
  return lens(function(o){ return o.get(k) },
              function(v, o) { return o.set(k, v) })
}
```

+1 for `ramda-lens`, but that means `over`, `set`, `view` should be moved over with it.

I would say we should keep minimal lens stuff here and build upon it in an extension lib, but I feel the use case is almost too weak without supplying `mapped` at least.

**Comment by stoeffel** [comment]
`ramda-lens` would be great. It think it would be easier to users new to lenses to get start, with all the functionality and documentation in one place.

**Comment by DrBoolean** [comment]
Just started https://github.com/DrBoolean/ramda-lens
I can make it an organization, we can roll it into ramda, or leave be. Whatever works.

I had to overwrite `view/over` because `Identity` `Const` needed to be extended

**Comment by scott-christopher** [comment]
> Just started https://github.com/DrBoolean/ramda-lens

Nice. I'll have a look this evening.

> I had to overwrite view/over because Identity Const needed to be extended

While playing around with prisms I ended up pulling these types out into their own file too for much of the same reason.

**Comment by CrossEye** [comment]
This is great.  If you wouldn't mind, I would love to host it as part of the Ramda organization, a related-to-Ramda project, but maintained separately the same way Ramda-Fantasy is.  But wherever it ends up, I like seeing this stuff grow.

**Comment by DrBoolean** [comment]
@scott-christopher totally! I'd love to combine with your prism work and I tried to keep consistent with your identity/const files.

@CrossEye heck yeah! Let's move it over. I actually would love to integrate with ramda-fantasy in a lot of the coming features.

**Comment by Sequoia** [comment]
Yaay!! :palm_tree: I think this is a great outcome for the library, as it will make it less befuddling for newcomers & allow lenses to get the attention they deserve as a distinct concept/tool. :+1:

**Comment by CrossEye** [comment]
I added a new team to the Ramda organization, and invited you, @DrBoolean.  I think you have to intiate the transfer.  Alternately, it's small enough and new enough to just start afresh as a Ramda project.  Whatever you think is easier.

**Comment by DrBoolean** [comment]
@CrossEye thanks for the invite! I don't do this often so I may be wrong, but it's complaining that I don't have admin rights.
<img width="1530" alt="screen shot 2016-01-18 at 8 14 47 am" src="https://cloud.githubusercontent.com/assets/28562/12396316/9de7d972-bdbb-11e5-847e-705302bb72cd.png">

**Comment by DrBoolean** [comment]
Tried to transfer first, but got the same message

**Comment by DrBoolean** [comment]
Thanks! All transferred up

**Comment by CrossEye** [comment]
@DrBoolean:
Just updated your membership status.  I don't know much about this stuff either.  I think you're now a full owner of all Ramda projects.  We hadn't discussed that with the full group, but @buzzdecafe had already wanted to do that.  If that doesn't make it possible, let me know and I'll ask around for someone with actual expertise.

**Comment by CrossEye** [comment]
Great!  I look forward to seeing this happen!
