### ISSUE TITLE
pluckPath ([k] → [{k: v}] → [v]) pluck a path from a list of objects

### ISSUE THREAD

**Issue by krainboltgreene** [ramda/ramda#1586]
``` javascript
const data = [
  {
    id: 1,
    attributes: {
      name: "Kurtis Rainbolt-Greene"
    }
  },
  {
    id: 2,
    attributes: {
      name: "Angela Englund"
    }
  }
]

const names = (records) => pluckPath(["attributes", "name"], records)

names(data) # => ["Kurtis Rainbolt-Greene", "Angela Englund"]
```

**Comment by krainboltgreene** [comment]
I'm willing to write this feature out if given some assistance!

**Comment by krainboltgreene** [comment]
In current ramda:

``` javascript
const data = // ...
const names = (records) => {
  return map((record) => path(["attributes", "name"], record), records)
}
```

**Comment by krainboltgreene** [comment]
Also, just in case someone is wondering if this is real: That JSON body conforms to https://jsonapi.org.

**Comment by jackfirth** [comment]
In current Ramda, taking advantage of currying, your example can be written:

```es6
const data = // ...
const names = map(path(["attributes", "name"]);
```

**Comment by krainboltgreene** [comment]
@jackfirth Is the example unfinished? D:

**Comment by jackfirth** [comment]
No, `names` in the example I provided is exactly the function you want (through currying).

**Comment by krainboltgreene** [comment]
@jackfirth Er, okay, I guess I was thrown off by the `;`. I don't see in `path()`'s documentation that it returns a function for currying.

**Comment by davidchambers** [comment]
All Ramda functions are curried, @krainboltgreene. :)

```javascript
//    R.add :: Number -> Number -> Number

//    inc :: Number -> Number
const inc = R.add(1);

//    x :: Number
const x = inc(42);
```

**Comment by CrossEye** [comment]
@jackfirth: Did you try that?

It seems to me that since you want the equivalent of 

    const pluckPaths = (paths, list) => R.map(R.path(paths), list);

You would need to use a bit more.  My first thought, if I were looking for points-free would be:

    const pluckPath = R.useWith(R.map, [R.path, R.identity]);

You could skip the `R.identity` if you didn't mind the function wrongly reporting its arity.

This looks a likely fit for the [Cookbook][cb].

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by davidchambers** [comment]
@jackfirth's snippet is lovely. Given `R.map(R.path(['attributes', 'name']))`, I see no reason to support `R.pluckPath(['attributes', 'name'])`.

**Comment by CrossEye** [comment]
Agreed, I see little reason to add such a function.

But it takes a bit of work to turn this into a reusable function.

**Comment by krainboltgreene** [comment]
So I guess what's the bar then? Because pluck is little more than
`R.map(R.prop(key))`, right?

On Mon, Jan 11, 2016 at 5:48 PM, Scott Sauyet <notifications@github.com>
wrote:

> Agreed, I see little reason to add such a function.
>
> But it takes a bit of work to turn this into a reusable function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ramda/ramda/issues/1586#issuecomment-170756052>.
>



-- 
Kurtis Rainbolt-Greene, Software Developer
Founder of Difference Engineers

2985 San Marino St.
Los Angeles, CA 90006
202-643-2263

**Comment by CrossEye** [comment]
> So I guess what's the bar then?

We always have to weigh how widely useful a function seems to be.  If there was a sudden outcry for something like this, we certainly might consider it.  But seeing how easy it is to add on one's own, there would be little reason beyond popular demand.

**Comment by krainboltgreene** [comment]
I guess that's the interesting part about functional libraries like ramda, theoretically we're talking about a small set of functionality, for which you have to weight building an entire library.

**Comment by CrossEye** [comment]
There is always a need to find a middle-ground between including every function that anyone might ever find useful and including only the minimal core necessary for users to build what they need.

Too minimal and you can decide that there's no reason for a library at all, indeed no reason for any abstractions; you can always build things on first principles.  Too inclusive and you have an unfocused hodgepodge of unrelated functions.  Ramda seems to be steering toward the latter a bit, which is a little worrying.

There are two guides to these decisions.  One is popularity.  A lot of requests for something inoffensive that the core team isn't excited about might be enough.  The other is the sensibilities of the core team, aesthetic or practical.  If a function seems to several of the core developers to be particularly useful, it will likely get added, regardless of whether there's any noticeable clamor at all for it.

So far, we haven't hit either of these thresholds.  And I see that you've closed the issue, but don't feel any great need to do so.  If you feel like arguing for it, open the issue back up, and over the next few days, you may find that there are many others who really like the idea.  We've done a lot of `prop => path` conversions to add consistency.  People might find that this should be another one.  But I'm not excited by it... yet.

**Comment by krainboltgreene** [comment]
Sorry, I closed it because I felt pretty satisfied that it's solvable with currying! I think it'd be nice to have it, but I understand bloat. :)
