### ISSUE TITLE
isArrayLike false positive

### ISSUE THREAD

**Issue by kelveden** [ramda/ramda#1589]
Any object passed in to `isArrayLike` that has a `length` property set to 0 is considered an array. So for example:

```javascript
R.isArrayLike({ myqueue:'something', length: 0 })
=> true
```

[this line](https://github.com/ramda/ramda/blob/master/src/isArrayLike.js#L30) is the cause of the problem. Here's the reason for that line: https://github.com/ramda/ramda/blob/master/test/isArrayLike.js#L26

So a check for at least one string-based key in the object (in addition to "length") before deciding that the object "is array like" would solve this I think. Thoughts? Am happy to implement.

**Comment by buzzdecafe** [comment]
`isArrayLike

**Comment by CrossEye** [comment]
> Any object passed in to `isArrayLike` that has a `length` property set to 0 is considered an array.

Can you describe how this causes issues for you?

> So a check for at least one string-based key in the object (in addition to "length") before deciding that the object "is array like" would solve this I think.

I don't follow.

**Comment by kelveden** [comment]
@CrossEye Thanks for the reply. Basically there is an assumption in the code that any object with a property `length` set to `0` will be considered an array; but "length" isn't a concept limited to the scope of arrays.

The specific case is related to an endpoint that returns metadata on a queue - the format of the response is JSON of the form `{ queue:"myqueue", length: 0 }`. So, `isArrayLike({ queue:"myqueue", length: 0 }) => true` but `isArrayLike({ queue:"myqueue", length: 1 }) => false` which seems inconsistent. Or am expecting more from `isArrayLike` than I should (it's just array_like_)?

As for the proposed solution, that was working on the basis that a "real" array will have a `length` property and numeric property names based on the index of the array - so checking for a string-based property would indicate that the "array" isn't an array at all. A bit dangerous if folks have been extending the array prototype and it consequently wouldn't be backward-compatible. I might just use a workaround instead.

**Comment by buzzdecafe** [comment]
the problem is that `isArrayLike` is a pretty slippery, ill-defined concept. Maybe it should be removed from the lib.

**Comment by CrossEye** [comment]
>  So, `isArrayLike({ queue:"myqueue", length: 0 }) => true` but `isArrayLike({ queue:"myqueue", length: 1 }) => false` which seems inconsistent. Or am expecting more from `isArrayLike` than I should (it's just array_like_)?

Perhaps you are.  Again, I'm wondering if this is leading to problems for your code.

> As for the proposed solution, that was working on the basis that a "real" array will have a length property and numeric property names based on the index of the array - so checking for a string-based property would indicate that the "array" isn't an array at all. 

There's a reasonable argument for checking, _when `length` is positive_, for the existence of the `length - 1` property in the object.  But that wouldn't help your case at all.  I think your solution doesn't really work.  Someone who adds a property to any array, not just someone who mucks about with the prototpye would break it.

**Comment by kelveden** [comment]
Sure yeah, didn't mention that but you're right of course. Ok, I'll do a workaround.

**Comment by asaf-romano** [comment]
I always wondered why it's there. Never found any use for it. But it seems to me that if isArrayLike returns true for some value, all list functions should work on that value. However:
```js
var f = R.when(R.isArrayLike, R.concat(["A"]));
f({ length: "b" }); // => {"length": "b"}
```

**Comment by buzzdecafe** [comment]
@asaf-romano that's a great example. I think we should deprecate & remove `isArrayLike`

**Comment by davidchambers** [comment]
I don't understand your example, @asaf-romano. `{length: 'b'}` is not array-like, no matter how much I squint. :)

**Comment by asaf-romano** [comment]
err, sorry for the spam. I just got very confused :)

**Comment by asaf-romano** [comment]
So the problem is only with length == 0, but that's unfixable, because in JS it's find for an (empty or not) array to have additional properties.

**Comment by olsonpm** [comment]
Got here wondering what use-cases `isArrayLike` covers.  After reading this thread and others I still don't understand.

What does an object's extreme indeces and length buy you?

**Comment by buzzdecafe** [comment]
it's a good question -- as i mentioned above, i think we should deprecate & remove it.

**Comment by davidchambers** [comment]
#1877
