### ISSUE TITLE
applySpec / juxtObj

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1591]
As mentioned on gitter, this little abstraction above ~ pipe(juxt(...), zipObj(...)) turns out (at least for us) to be very useful:

```js
function applySpec(spec)
{
  // TODO: Set arity.
  return (...args) => R.map(fn => fn(...args), spec);
}

var f = applySpec({ sum: (a, b) => a + b, mul: (a, b) => a* b });

f(3, 4); // => {"mul": 12, "sum": 7}
```

REPL: http://bit.ly/1UPpD13

**Comment by davidchambers** [comment]
I'd be in favour of taking `args` as an array rather than as positional arguments:

```javascript
var applySpec = R.curry(function(spec, args) {
  return R.map(R.apply(R.__, args), spec);
});

var f = applySpec({sum: R.add, mul: R.multiply});

f([3, 4]);
```

**Comment by buzzdecafe** [comment]
@davidchambers I agree; i think if we can get `// TODO: Set arity.` to work then that is even a better option. But I don't see a nice way without passing the desired arity in, or taking the max of all the functions on the `spec`.

**Comment by asaf-romano** [comment]
Locally I did max over spec, which matches what juxt and converge do now. I just didn't bother copying that over to the repl.

**Comment by asaf-romano** [comment]
Regardless, I'd find it quite odd for the spec functions to take the arguments in a different shape. And I'd also prefer not to complicate the unary case, which is very common.

**Comment by CrossEye** [comment]
As I said on Gitter, I really like this function.  I've never thought to write anything like it, but I've often written code that could have used it.  :+1:

I feel that generating a function which does not require you to wrap the parameters in an array would be cleaner.  I think max arity would be fine.

**Comment by asaf-romano** [comment]
I'll PR this once someone comes up with a name, as I know most of the peers here don't like *spec names.

**Comment by CrossEye** [comment]
> I know most of the peers here don't like *spec names.

Is that true?  I hadn't realized it...

**Comment by asaf-romano** [comment]
I had a deja vu reading a comment on ``mergeWithSpec``, but I might be wrong. I'm fine with ``applySpec``, of course.

One thing I realized that's missing here is nested-object support (i.e. make the function recursive), in par with ``evolve``.

**Comment by asaf-romano** [comment]
recursive: http://bit.ly/1Znqck5

**Comment by asaf-romano** [comment]
Note to self: use curryN rather than _arity.
