### ISSUE TITLE
One Million Downloads!  Another giveaway

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#1593]
Ramda [just passed][ns] the one million download mark!  :balloon: :cake: :sparkles: :fireworks:

Thanks for all the great work from all the contributors.  This has been such an amazing experience.  I believe we're building an incredible library! 

As we've done with two [previous][m1] [milestones][m2], we'd like to celebrate with a giveaway.  We'll be giving out another [Ramda mug][rm] to a random contributor.  Below we list everyone who's ever had a contribution merged to Ramda, Ramda-Fantasy, or the Ramda documentation site.  (Sorry, core contributors, we're all ineligible!)

If you would like to be _excluded_ from consideration, please let me know in the comments below.

(The list is split over several comments, as GitHub doesn't seem to want more than 50 shout-outs at a time.)

* @101100
* @alexnormand
* @andyleggett
* @anton-rudeshko
* @arcseldon
* @asaf-romano
* @AutoSponge
* @Avaq
* @begriffs
* @benjamingr
* @benjycui
* @benperez
* @bergus
* @bezhermoso
* <del>@bobiblazeski</del>
* @branneman
* @carlosrocha
* <del>@ccorcos</del>
* @cgarciae
* @Chris911
* @cust0dian
* <del>@davezuko</del>
* @davidchase
* @davidrusu
* @Delapouite
* @dmitrig01
* @DrBoolean
* @dtinth
* @dumconstantin
* @ecwyne
* @fix-fix
* @fson
* @fyyyyy
* @garyposter
* @geophree
* @gilligan
* @gonzaloruizdevilla
* @gurdiga
* @hemanth
* @Hilzu
* @honzabrecka
* @igncp
* @jackjennings
* @JAForbes
* <del>@jethrolarson</del>
* @jimf
* @jon49
* @joneshf
* @kedashoe
* <del>@kevinbeaty</del>

  [m1]: https://github.com/ramda/ramda/issues/585
  [m2]: https://github.com/ramda/ramda/issues/1086
  [ns]: http://npm-stat.com/charts.html?package=ramda
  [rm]: http://www.zazzle.com/ramda_classic_white_coffee_mug-168294919219766885

**Comment by CrossEye** [comment]
List continued:

@kookoskar
@kwijibo
@lo1tuma
@lwassermann
@magee
@manuelmauro
@markprzepiora
@MartijnDwars
@mattsmith14
@mcamac
@megawac
@michaelckelly
@miwillhite
@mLuby
@mondalaci
@MrP
@ndhoule
@niant
@nicolasv
@niloy
@nomosyn
@nsluss
@ppalladino
@ptolemybarnes
@rhinoceraptor
@rpominov
@safareli
@samueller
@santialbo
@Sequoia
@statpro-awebb
@steelsojka
@stites
@stoeffel
@syves
@taylor1791
@ThomasDeutsch
@tolmasky
@tomByrer
@vikfroberg
@watsoncj
@wavebeem
@wildermuthn
@Youpinadi
@yrns
@yuri
@zemlanin

**Comment by JAForbes** [comment]
Congratulations everyone!  Ramda is an incredible library.  1 million is a huge achievement!

**Comment by Chris911** [comment]
Congrats. Great achievement! Happy to contribute and use Ramda on a daily basis!

**Comment by niloy** [comment]
Congratz :tada: :balloon:

**Comment by vikfroberg** [comment]
That's amazing, thanks for all the hard work!

**Comment by arcseldon** [comment]
Great accomplishment, and fully deserved!  Well done all the contributors, and in particular the core contributors.  Created an outstanding JS library, and community around it - a Ramda mug would be most welcome :smile: for all the hard work I've let others do over the past 12 months. Still got plans to write a book on Ramda as soon as a v1 is official :wink:

**Comment by asaf-romano** [comment]
Congrats!

**Comment by safareli** [comment]
Cool 🙉🎓

**Comment by hemanth** [comment]
Congrats!

![](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)

**Comment by bobiblazeski** [comment]
Congratulations!
Please exclude me from the raft.

**Comment by tomByrer** [comment]
1 million... 
![one-billion-dollars-austin-powers-above-the-law-blog](https://cloud.githubusercontent.com/assets/1308419/12353773/bf6e343e-bb4e-11e5-9b5d-97ab48acc09b.jpg)

**Comment by miwillhite** [comment]
Congrats everyone! This library has changed the way I write code (not only JS!) and I look forward to the next million :) :tada:

**Comment by davidchase** [comment]
this is huge!!! congrats and great work :100:

**Comment by bezhermoso** [comment]
Congratulations everyone!

**Comment by jethrolarson** [comment]
Exclude me. I bought my own.

**Comment by kevinbeaty** [comment]
Congrats!  Please exclude me as well.

**Comment by anton-rudeshko** [comment]
:tada:

**Comment by wavebeem** [comment]
I would like to be excluded because I won this contest last time. Happy to be a contributor to this project :smile:

**Comment by jackjennings** [comment]
Awesome! No need to include me—I'm happy if it goes to someone with more substantial contribution(s).

**Comment by CrossEye** [comment]
@jackjennings:

I will exclude you if you choose, but first, please take into account something @Sequoia said [last time][se]:

> Congrats @Ramda team! And to everyone with small contributions (like mine which was sort of a meta-contribution, I didn't augment or fix *anything* in the lib itself) don't talk your work down too much! Many hands light work & all that-- FOSS projects would be much more painful without all those small-but-important contributions. Big up yourselves! :tada: :+1: :palm_tree: 

I couldn't agree more.  It takes all sorts of contributions, large and small, and we're very happy to have them all.

  [se]: https://github.com/ramda/ramda/issues/1086#issuecomment-102424416

**Comment by begriffs** [comment]
:+1:

**Comment by stites** [comment]
![rocky celebrating](https://cloud.githubusercontent.com/assets/1694705/12366196/87e5f796-bb8e-11e5-80da-e63a6d324e01.gif)

Fantastic!

**Comment by ccorcos** [comment]
Sweet!!! :herb:

That mug is so awesome I'm just going to buy one :)

**Comment by davezuko** [comment]
:+1: congrats, please exclude me from the drawing though, I hardly did anything :P

:beers:

**Comment by svozza** [comment]
Congratulations guys!

**Comment by CrossEye** [comment]
:checkered_flag: The Winner :checkered_flag: 
=====================================

:microphone: Ladies and Gentlemen (and you too, Hurley!), it's time to announce the winner, as chosen by a select panel of `Math.random`.

First, our runners-up:  For those of you who haven't heard before, this library was started as a learning exercise.  @buzzdecafe and I wanted to play around with some useful techniques.  That's all.  We were gob-smacked to find it becoming popular.  We never set out to create a widely used tool or to help foster a community of like-minded folks.  But so many folks have come to join us in making it so much better than we could ever have done on our own.  Thank you, thank you all very much for participating.

:trophy:  And the winner, with a mug on the way<sup>1</sup>, is @gilligan!   Thank you, Tobias, for your help with this project.

And again, thank you everyone for all your contributions!


----------
<sup>1</sup>If Zazzle's stupid store, which makes me pick a U.S. state even though I insisted it was a German address, doesn't get too confused trying to find Alabama, Germany.

**Comment by benjamingr** [comment]
Thanks for doing these! A model open source project. By the way, I helped organize a meetup on the 27th and one of the lectures is about Ramda :) http://www.meetup.com/JavaScript-Israel/events/228057072/

**Comment by gilligan** [comment]
Awesome, thanks a lot Scott!

I will use my 5 minutes of fame to also say thanks to everyone who is part of this community around Ramda. Everyone is really friendly and helpful and the gitter channel is a cool place to get help or just hang out with cool FP people.

A couple of months ago I switched our production code from lodash to Ramda which has been awesome. I suppose I would not hesitate if I was offered a Haskell job, but with Ramda JS can actually be fun!

Best wishes,
Tobias

**Comment by dumconstantin** [comment]
Congrats Ramda and to all the great people that are making it and keeping the community so active. 

I stopped enjoying writing code until came across Ramda and the FP mindsets, I feel alive again when writing code due to it. Thanks a lot!

**Comment by buzzdecafe** [comment]
> ... with Ramda JS can actually be fun!

gotta put that quote on the movie poster. Thanks @gilligan

**Comment by Luckvery** [comment]
I would just like to thank you all. Ramda has sparked a lot of conversation about functional programming where I work and for that I believe I owe you all a debt. Cheers and here's to the next 1 million downloads!

**Comment by ccorcos** [comment]
:+1:

**Comment by fyyyyy** [comment]
Congragts, pure awesomeness !

**Comment by gilligan** [comment]
![enjoying my ramda mug](http://imgur.com/XkeQP5N)

**Comment by gilligan** [comment]
![image](https://cloud.githubusercontent.com/assets/27668/12695786/f1ea5f3a-c758-11e5-8c23-1d55ed0f0c14.jpeg)

Enjoying my coffee mug :)

**Comment by buzzdecafe** [comment]
Prosit, @gilligan
