### ISSUE TITLE
For a primitives array, uniqWith(identical) is still much slower than plain uniq, which is much slower than a Set-based implementation

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1594]
I apologize for bringing this up again, as I have no constructive suggestions.

Thinking about removing our `uniqIdentical`, `differenceIdentical` and similar function from our code-base given recent improvements within the library (or at least implement them using With functions), I ran an old test I had and was somewhat surprised by how bad the results were.

http://bit.ly/1PfgsTk (Let it run, it'll finish after some time)

**Comment by CrossEye** [comment]
I'm not sure there is anything to do here.  If we can speed up `uniqWith(identical)` that would be great.  But do note that `uniq` has different, and to my mind better, behavior than either of the others in your test.  It is testing value equality.  That is what FP is all about.  In the end, `uniq` returns only a single value, as can be seen in this variant: http://bit.ly/1OmqS60.  The other two return 350 identical values with different references.  Yes, the 350000 had been reduced to 350, but this is still not the correct answer from a value-based perspective.

http://bit.ly/1Omu2qD gives a somewhat different view.  Here, there are a number of different values, with a combination of equal and different references.  `uniq` is by far the slowest, but it correctly gives the number of distinct _values_.  If you want to compare references, then the native approach is unsurprisingly quite a bit faster than all the function calls necessary for a `*With` or `*By` approach.  This seems to be scaling approximately linearly, so when we hit 350000 values, it's painful: http://bit.ly/1OmsVHp.

If people really want to support a reference-based version, it would be easy enough to use something like `R.compose(Array.from, R.constructN(1, Set))` in environments that support it and default to slower implementations elsewhere.  But moving anything to reference equality seems to me a move in the wrong direction.

**Comment by asaf-romano** [comment]
Of course I don't suggest giving up value equality. But the fact is that for a large list of strings (e.g. guids), all Ramda functions that rely on _contains are providing the exact same functionality as other libraries which rely on reference equality, but with pretty bad performance in comparison. I was under the impression that Scott's work fixed this issue (by providing a faster path for primitive-items arrays), but the situation is still pretty bad, it seems.

``uniq`` is just one example. Lately I've struggling with both`` intersection`` and ``difference``.

**Comment by CrossEye** [comment]
I'd love to hear suggestions.  One thing that comes to mind is to pass through the list(s) and see if everything is primitive and then use a simpler path for that case, I suppose.

If we can speed up the case that worries you without sacrificing the correctness of the cases that worry me, we'd definitely have a big win.
