### ISSUE TITLE
R.compose not curried by default

### ISSUE THREAD

**Issue by tcoats** [ramda/ramda#1599]
When the arity of the rightmost function in a compose takes more than one argument it does not wait to be curried before called.

```js
var valueRequired = R.compose(R.not, R.either(R.isEmpty, R.isNil));
var propRequired = R.compose(valueRequired, R.prop);

var emailRequired = propRequired('email'); // is instantly run and returns true
```

Instead the output needs to be manually curried.

```js
var valueRequired = R.compose(R.not, R.either(R.isEmpty, R.isNil));
var propRequired = R.curry(R.compose(valueRequired, R.prop)); // note: R.curry

var emailRequired = propRequired('email'); // is a function
console.log(emailRequired({ email: '' })); // false
console.log(emailRequired({ email: 'something' })); // true
```

Is this expected behaviour?

**Comment by davidchambers** [comment]
Which Ramda version are you using, @tcoats? The behaviour changed in v0.16.0 (via #1260) and was changed again in v0.18.0 (via #1391).

**Comment by tcoats** [comment]
Latest on npm - v0.19.1.

Reading that second pull request it seems currying compose had been removed to support optional parameters and other complexity.

Perhaps that could be added to the documentation - that compose and pipe do not curry?

**Comment by davidchambers** [comment]
> Perhaps that could be added to the documentation - that compose and pipe do not curry?

Good idea. Fancy opening a pull request?

**Comment by tcoats** [comment]
Functionality has been documented.
