### ISSUE TITLE
Currying the function passed to map?

### ISSUE THREAD

**Issue by tcoats** [ramda/ramda#1602]
I'd like to run a function across an array with the same piece of data each time. This is the best I have come up with so far:

```js
var multiply = R.map(R.multiply);

// At this point I'm expecting a function of 2 arity - another `factor` for multiply and a functor
// but the result is 1 arity waiting for the functor so the following does not work
var multiplyby2 = multiply(2);

var functor = [1, 2, 3];
var functorDoubled = multiplyby2(functor);

console.log(functorDoubled); // expect [2, 4, 6]
```

Should this work?
Is there a better way to express this instead?

**Comment by CrossEye** [comment]
First off, you can express what you're looking for with a simple lambda:

```js
const multiply = n => R.map(R.multiply(n));
const multiplyBy2 = multiply(2);
multiplyBy2([1, 2, 3]); //=> [2, 4, 6]
```

Of course, pre-es6, that would be written:

```js
var mutliply = function(n) {return R.map(R.multiply(n));}
```

As to why what you're trying doesn't work, it's simply how currying works:

```
R.map :: Functor f => (a -> b) -> f a -> f b
```

When we curry in the first parameter, `(a -> b)` (in this case `multiply`), we get back this:

```js
Functor f => f a -> f b
```

This leaves us no way to further configure the `multiply` function.

**Comment by asaf-romano** [comment]
``useWith`` works too: http://goo.gl/wQfRSg

Note that the function you get with ``useWith`` is binary - and curried - so it can be called with both arguments or with one argument at a time.

**Comment by tcoats** [comment]
Excellent, thank you all!

**Comment by CrossEye** [comment]
> ``useWith`` works too: http://goo.gl/wQfRSg

d'oh.  Of course it does. That's generally my baby, and the one I think about right away.  Thanks for pointing it out.

**Comment by tcoats** [comment]
Looking more into `useWith` - it's the missing function I've been searching for. Thank you @asaf-romano!
