### ISSUE TITLE
R.concat dispatches to the FIRST argument's concat method

### ISSUE THREAD

**Issue by ecwyne** [ramda/ramda#1604]
Not the second (per docs)

https://github.com/ramda/ramda/blob/v0.19.0/src/concat.js

```javascript
var a = {value: 'abc', concat: function (v) {return this.value + v}};

R.concat(a, 'def');
//=> 'abcdef'

R.concat('def', a);
//=> 'def[object Object]'
```

**Comment by buzzdecafe** [comment]
yes, the docs should be fixed. i see `concat` as an infix operator which has been converted to prefix. These kinds of functions are often problematic for us (see discussions on `lt/gte` etc.)
