### ISSUE TITLE
support any number of parameters passed into concat

### ISSUE THREAD

**Issue by josh-egan-ps** [ramda/ramda#1611]
I propose that any number of arguments be supported by the `concat` method. Currently, the first two arguments are used and remaining arguments are ignored.

So this is the current implementation:

```js
var x = ['a', 'b'];
var y = ['c', 'd'];
var z = ['e', 'f', 'g'];

R.concat(x, y); // returns ['a', 'b', 'c', 'd']
R.concat(x, y, z); // returns ['a', 'b', 'c', 'd']
```

I propose that any number of arguments be supported, so that the following would work:

```js
var x = ['a', 'b'];
var y = ['c', 'd'];
var z = ['e', 'f', 'g'];

R.concat(x, y, z); // returns ['a', 'b', 'c', 'd', 'e', 'f', 'g']
```

**Comment by davidchambers** [comment]
Variadic functions don't play nicely with currying. Instead, though, you could fold:

```javascript
> R.reduce(R.concat, [], [x, y, z])
['a', 'b', 'c', 'd', 'e', 'f', 'g']
```

**Comment by josh-egan-ps** [comment]
Ah, thanks for the idea. That works great!
