### ISSUE TITLE
isDivisibleBy

### ISSUE THREAD

**Issue by jackfirth** [ramda/ramda#1612]
``` javascript
const isDivisibleBy = R.curry((modulus, n) => n % modulus == 0);
isDivisibleBy(2, 6); //=> true
isDivisibleBy(2, 7); //=> false
```

The best use for this IMHO is in documentation examples, tests, and playing around in the REPL. It's the first kind of function we reach for when showing what `filter` does, for example, and I find myself using it all the time when testing predicate / filtering logic I've created.

**Comment by svozza** [comment]
You could put it in the [cookbook](https://github.com/ramda/ramda/wiki/Cookbook)?

**Comment by CrossEye** [comment]
> You could put it in the [cookbook](https://github.com/ramda/ramda/wiki/Cookbook)?

I agree.  This is a useful little function, but doesn't seem important enough for the core.
