### ISSUE TITLE
Make ramda REPL not require "R." prefix

### ISSUE THREAD

**Issue by edmulraneyMFT** [ramda/ramda#1614]
When writing code in the ramda REPL it's slightly tedious to add "R." to every ramda function we use.
Please could you default the ramda functions?

Thanks

**Comment by davidchambers** [comment]
Seems reasonable to me. What do you think, @davidchase?

**Comment by arcseldon** [comment]
+1

**Comment by asaf-romano** [comment]
Three minor problems:
```js
Object.keys(R).filter(k => k in window); \\ => ["find", "length", "toString"]
```
But +1 of course.

**Comment by buzzdecafe** [comment]
i also prefer writing without the `R`, but we should provide both. And this issue really belongs on the docs repo. Unfortunately since both Sanctuary and ramda-fantasy provide `Just`, `Nothing`, etc. those will have to be fully qualified

**Comment by davidchase** [comment]
i am neutral on the subject since you can easily do `const {compose, reduce, map, filter} = R;`

**Comment by edmulraneyMFT** [comment]
@davidchase it's easy, but tedious/unnecessary. I often copy and paste various code blocks from real projects I'm working on, and having to find/copy/write the `const {...} = R` lines is annoying.
@asaf-romano agreed. `window` functions should be explicit.

**Comment by davidchase** [comment]
Ok let's do as @buzzdecafe suggests move this to the ramda docs issue tracker and I will get to it hopefully tonight... how does that sound?

**Comment by buzzdecafe** [comment]
SGTM

**Comment by edmulraneyMFT** [comment]
Oh cool, didn't realise the REPL was on github. I'll submit the PR.

**Comment by davidchase** [comment]
Yeah I've been working a PR to make some fixes and as well as Babel so that has prevented this fix from coming in
