### ISSUE TITLE
R.equals considers any two promises to be equal

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1616]
This issue was raised by @zhangchiqing in davidchambers/doctest#70.

```javascript
> R.equals(Promise.resolve(2), Promise.resolve(3))
true
```

Value-based equality may not be applicable to promises, but we could at least fall back to identity.

**Comment by CrossEye** [comment]
Man, I hate Promises.

At least when trying to deal with them here.

Identity doesn't seem like a good idea, for 

```js
R.equals(Promise.resollve(2), Promise.resolve(2)); 
//=> should be true, no?
```

Uggh!

**Comment by scott-christopher** [comment]
It gets worse when you consider something like the following, which could arguably be considered equal by value:
```js
R.equals(Promise.resolve(2), new Promise(res => setTimeout(res, 1000, 2)));
```
I thought about potentially doing something a bit hacky like comparing only resolved promises for value-equality by updating a mutable variable from a continuation given to `then` and then comparing the values outside but the A+ spec states that the callbacks must not be executed in the same event loop tick as `then`, so the mutable variables won't be set in time to compare.

Perhaps we need to adapt `Boolean` to three values of `true`, `false` and `shrug` :smile:

I think it's a fairly safe bet that anything function-like can't be compared for value-equality. It then boils down to whether there is still any benefit in comparing for reference-equality.

**Comment by CrossEye** [comment]
Yes, this is my concern.  They are not equal, and then they are... <shudder>

```js
new Promise(res => setTimeout(res, 1000, GeigerCounter.particleEmitted());
```

Shmosises!

**Comment by asaf-romano** [comment]
I don't think there's *any* way to inspect native promises, so falling back to strict-equality is the best we can do anyway.

**Comment by buzzdecafe** [comment]
> falling back to strict-equality is the best we can do anyway.

I think @asaf-romano is correct. I doubt that anybody is happy with this solution, but it is marginally better than what we've got.
