### ISSUE TITLE
Typescript definitions for intellisense

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda#1617]
Hi, am raising this as an "issue" but please feel free to close if wrong forum for enquiry. 

Am used to pulling in the typescript community stub definitions whenever I use a popular library so that I have immediate access to autocomplete etc within Editor / IDE - eg  [Angular](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts).  Although, 100s of typescript definitions now exist covering every popular library I tend to regularly use in JS, I have noticed that Ramda is conspicuously absent. For instance, lodash and siblings have such defs.  More info [here](https://github.com/DefinitelyTyped/DefinitelyTyped)

Please can anyone tell me if I have missed something etc, or best alternatives. Will ask on gitter now too.

**Comment by buzzdecafe** [comment]
IIRC @donnut was working on typescript annotation for ramda but that was a while ago. maybe he could answer?

**Comment by arcseldon** [comment]
@buzzdecafe  - thanks for reply.  As per gitter conversation, have discovered that git repo at [donnut/typescript-ramda](https://github.com/donnut/typescript-ramda) is currently still active (up to version 0.18 at least).

**Comment by dancasey** [comment]
@arcseldon While Ramda still doesn't have its own `.d.ts`, with TS 2.0 you can now get these types installed and referenced with just `npm install --save @types/ramda` ([ref](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/)).

**Comment by tycho01** [comment]
On the topic of a `.d.ts` built in to the main repo, would there be interest in this? What would considerations there look like?
Context: I'm in the Angular boat as well, so having a need for Ramda TS definitions, I started trying to [integrate](https://github.com/donnut/typescript-ramda/network) the existing commits across the network.

**Comment by knikel** [comment]
Adding to @tycho01's comment, I'm also using `ramda` on a daily basis (and will for the foreseeable future 😉) in `TypeScript` and `Angular 2` context and I'd be happy to help maintaining the `*.d.ts` if they land in the main repository too.

**Comment by CrossEye** [comment]
If there's enough interest, and people willing to commit to keeping such up-to-date, I would have no problem seeing these in the repo.  I don't know how much of a commitment that it.  I have yet to give either Typescript or Flow a serious test.

**Comment by tycho01** [comment]
I'd tried replying earlier, but it seems that hadn't gotten through.

I imagine keeping up to date with Ramda releases in itself shouldn't so much be a bottleneck. Some of the typings can be annoying at the moment (-> there not being a great way to handle currying until hopefully variadic kind support as mentioned by @blakeembrey in the linked thread), but for the most part I imagine the typings would require updates largely for edits actually affecting the API surface.

That said, TS inference isn't perfect yet, meaning in certain cases the user may still want to manually annotate types (unfortunate for [map](https://github.com/Microsoft/TypeScript/issues/12393) on tuples / heterogeneous objects, looking forward to progress there). But such are the woes of TypeScript users.

**Comment by tycho01** [comment]
Could this be considered resolved with the typings at [types/npm-ramda](https://github.com/types/npm-ramda)?

**Comment by andy-ms** [comment]
@tycho01 This issue is to [bundle](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) typings, as opposed to having them externally.

**Comment by tycho01** [comment]
@andy-ms: we'd discussed that in [here](https://github.com/ramda/ramda/pull/1999), but ended up deciding against it for the time being.

**Comment by tycho01** [comment]
Semi-related, the quest to improve typings for Ramda has pushed me to try and further flesh out the TypeScript features for type-level programming, see my PRs [here](https://github.com/Microsoft/TypeScript/pulls/tycho01).

I think there's nice synergy between type inference and fp libs like Ramda -- writing typings with good inference is [tough enough](https://github.com/Microsoft/TypeScript/issues/12215) that it helps a lot to be able to just hook into existing typed functions, while on the other hand, it's especially in the functional paradigm that static typing adds value.

So it's still WIP, but I hope this could both help draw more people toward Ramda, as well as, given some luck on these PRs, help TS gain some extra ground to fans of e.g. PureScript / Elm.
