### ISSUE TITLE
Make sure all transduce-friendly functions are documented as such

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1620]
Had to use transducers at last! While doing so, I figured it's a little hard to track which functions in the library are already supported in transduce. Here's a probably-partial list of undocumented transduce-friendly functions:
- pluck
- chain
- unnest

---

I will update the list as I find more functions, if any.

**Comment by CrossEye** [comment]
:+1:

Good idea.

**Comment by arcseldon** [comment]
@asaf-romano - hi, can you elaborate what you mean by "which functions are supported in transduce?"

I am just bringing myself up to speed, but my initial impressions are that for the transducer (first reduction function) you can pretty much use any of the Ramda list operations that support taking an array as their first free argument (potentially after currying the first arg with a transform etc).

For example, take R.all whose signature is (a → Boolean) → [a] → Boolean, then using a transducer of

```
 const transducer = R.all(R.always(false));
```

would work.

Here are some further examples, but the same applies across the board from limited testing I have done:

```
 it('should work with ramda transducer example given', () => {
    const numbers = [1, 2, 3, 4];
    const transducer = R.compose(R.map(R.add(1)), R.take(2));
    const res0 = R.transduce(transducer, R.flip(R.append), [], numbers);
    expect(res0).to.eql([2, 3]);

    // this also gives the same answer.... but cuts out transducer completely
    expect(transducer(numbers)).to.eql([2, 3]);

  });

  it('should work with ramda transducer for addition', () => {
    const numbers = [1, 2, 3, 4];
    const transducer = R.identity;
    const res0 = R.transduce(transducer, R.add, 0, numbers);
     expect(res0).to.equal(10);
  });

  it('should work with ramda transducer for all', () => {
    const numbers = [1, 2, 3, 4];
    const transducer = R.all(R.always(false));
    const res0 = R.transduce(transducer, R.flip(R.append), [], numbers);
    expect(res0).to.eql([false]);
  });

  it('should work with ramda transducer for filter', () => {
    const numbers = [1, 2, 3, 4];
    var isOdd = R.modulo(R.__, 2);
    const transducer = R.filter(isOdd);
    const res0 = R.transduce(transducer, R.flip(R.append), [], numbers);
    expect(res0).to.eql([1, 3]);
  });
```
It does appear that the second reducer - the accumulating iterator - really needs to be an array unless you are prepared to cludge it with say R.identity as i did in the summation example above.

**Comment by arcseldon** [comment]
Managed to achieve a similar effect, with this quick hack, but definitely not road-worthy, and I am unclear whether it qualifies as a proper transducer although it does offer composable algorithmic transformation capabilities on lists...

```
 const createTransducer = (transformer) => {
      return (iterator) => {
        return (result, input) => {
          return iterator(result, transformer(input));
        };
      };
    };

    // (c → c) → (a,b → a) → a → [b] → a
    const transduce = function (transformer, iterator, acc, list) {
      return R.reduce(transformer(iterator), acc, list);
    };

    const numbers = [1, 2, 3, 4];

    const transducer1 = createTransducer(R.identity);
    const res1 = transduce(transducer1, R.add, 0, numbers);
    expect(res1).to.deep.equal(10);

  //  the compose actually behaves like R.pipe..
    const transducer2 = R.compose(createTransducer(R.add(1)), createTransducer(R.add(2)));
    const res0 = transduce(transducer2, R.flip(R.append), [], numbers);
    expect(res0).to.eql([4, 5, 6, 7]);
```

Open question, are the composed transformations inside the Ramda transducer done in such a way that all transformations on the first element of the list are completed before moving on to the second element in list etc ?

**Comment by arcseldon** [comment]
> Open question, are the composed transformations inside the Ramda transducer done in such a way that all transformations on the first element of the list are completed before moving on to the second element in list etc ?

From what I am reading / hearing about Transducers this must be a resounding "yes".

**Comment by CrossEye** [comment]
> Open question, are the composed transformations inside the Ramda transducer done in such a way that all transformations on the first element of the list are completed before moving on to the second element in list etc ?

Yes, that's the main point of Transducers.  It allows one to avoid creating intermediate collections in composed pipelines.

I don't have the time to give the rest of this a thorough reading right now.  I will try to read through it more tonight.  But some of trandsucers are still a bit mysterious to me.

**Comment by arcseldon** [comment]
@CrossEye - thank you, appreciate the feedback. 

> But some of transducers are still a bit mysterious to me.

Reassuring to know that I'm in good company! Hoping to play around with more examples when time permits.

Note to self, and for anyone visiting this issue, and totally new to transducers but keen to get started then two links I found helpful (both by Rich Hickey).

[Transducers](https://www.youtube.com/watch?v=6mTbuzafcII&feature=youtu.b)

[Inside Transducers](https://www.youtube.com/watch?v=4KqUvG8HPYo&feature=youtu.be)

**Comment by arcseldon** [comment]
@kedashoe - was this completed then?  `Make sure all transduce-friendly functions are documented as such`  - please can you add some comments before closing.

**Comment by kedashoe** [comment]
> @kedashoe - was this completed then? Make sure all transduce-friendly functions are documented as such - please can you add some comments before closing.

ty, see #2349

**Comment by kedashoe** [comment]
thanks again @arcseldon , let me know if you think anything is still missing
