### ISSUE TITLE
internet explorer edge flatten mutations from MutationObserver error with EmptyTextNode

### ISSUE THREAD

**Issue by marcog83** [ramda/ramda#1624]
Hi, I wrote a function that returns an Array of added nodes to the DOM . It looks like this.

``` javascript
var getAdded =compose(
            filter(nodes=>nodes.length>0),
            map(node=>[node].concat(Array.prototype.slice.call(node.querySelectorAll("[data-mediator]"), 0))),
            filter(node=>node.querySelectorAll),
            flatten(),
            pluck("addedNodes")
        )

    }
//usage with MutationObserver
var observer = new MutationObserver(mutations=> {
        var added=getAdded(mutations);


    });

```

Chrome, FF and Safari work well, but IE throw an Error when flatten function is invoked.
Debugging I found a condition in **isArrayLike.js**

``` javascript
 if (x.length === 0) {
    return true;
  }
```

When `x` is an `EmptyTextNode`, `x.length` is **Invalid Arguments**. and an Error occurs.

I added a condition, but i know it is just a workaround for my use case.

``` javascript
if (x.toString()==="[object Text]") {
    return false;
  }
```

Thanks for the great work you did with Ramda.

![image](https://cloud.githubusercontent.com/assets/4071265/12755783/2f8be064-c9d1-11e5-8951-bf2c5c071e85.png)

**Comment by buzzdecafe** [comment]
arg. another hit to `isArrayLike`; i am really thinking that ill-defined function has got to go. 

aside: you don't need to invoke `flatten()`, just `flatten` is sufficient (in fact `flatten() === flatten`)
