### ISSUE TITLE
Documentation for integration with algebraic types

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1627]
I've sort of gathered that there's something called algebraic data types from something called Fantasy Land, which integrates with Ramda, but I've yet to understand the nature of this integration.

It would be great to have some documentation on the front page which explains it. It seems very useful and I would love to get started on it.

Related to https://github.com/ramda/ramda/issues/1610. Probably related to https://github.com/ramda/ramda/issues/1628.

**Comment by CrossEye** [comment]
See [my response][sc] in #1628.

  [sc]: https://github.com/ramda/ramda/issues/1628#issuecomment-179850367

**Comment by remojansen** [comment]
:+1: I was wondering about `Maybe`, `Just` and `Nothing` it would be great if it could be documented.

**Comment by CrossEye** [comment]
Yes, I keep hoping someone will step up to write some of this documentation.

Any interest in trying to write the documentation on this type?

**Comment by kwijibo** [comment]
@CrossEye Something to start with? https://gist.github.com/kwijibo/fa7360c8ded8f91a97ac

**Comment by CrossEye** [comment]
@kwijibo: Thank you.  Definitely a good place to start.  Something else to look at is the [Sanctuary Types documentation][st].


  [st]:https://github.com/plaid/sanctuary#types

**Comment by CrossEye** [comment]
I've also started documenting the signatures.  I'll try to post something tonight.

**Comment by CrossEye** [comment]
Ok, this took me much longer than I hoped.  I've [added a page to the wiki][ts] explaining how our signatures work that I'd like to put somewhere on our documentation pages, and perhaps put a link to it from the top of the API page.

I'd love some feedback on it.  But I warn you it is large.

I'm especially concerned about the sections on Type Aliases and Type Constraints.  But anything feedback you have, from glaring gaps in the descriptions to typos to "What were you smoking, Crosseye", would be appreciated.


  [ts]: https://github.com/ramda/ramda/wiki/Type-Signatures

**Comment by CrossEye** [comment]
I just noticed that some footnotes aren't showing up in GFM.  They're not that important, but you can see the markup side-by-side with the output at http://goo.gl/7f2EKg.  The footnotes are included there.

**Comment by arcseldon** [comment]
@CrossEye - This is excellent!! Not in the least bit surprised it took longer than expected either :smile:

**Comment by davidchambers** [comment]
This is invaluable, @CrossEye!

**Comment by scott-christopher** [comment]
That is fantastic @CrossEye, it reads really well. Many thanks for taking on that effort. :mushroom:

**Comment by dalgard** [comment]
Thanks so much, @CrossEye! Will correct typos if I find some.

**Comment by buzzdecafe** [comment]
+:100:  kudos, this is an impressive piece of work. Thanks

**Comment by remojansen** [comment]
Happy days :rainbow: nice work!

**Comment by dalgard** [comment]
The new wiki page doesn't actually describe the algebraic types (`Maybe`, `Just`, `Nothing`) that I was seeking when I created this issue. But this discussion might as well continue in the open issue https://github.com/ramda/ramda/issues/1610.

**Comment by CrossEye** [comment]
@dalgard: There were always two parts of this to my mind: the types and the signatures... or three if you consider changes to the API docs to link to the Types.  The signatures took so much more effort that I haven't started working on the types yet.  Several people have partial solutions to this that I would love to expand on.
