### ISSUE TITLE
Documentation for type signatures

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1628]
I'm discovering functional programming beyond the capabilities of Underscore/Lodash through Ramda and am loving the process. However, I've had some trouble reading the type signatures in the documentation.

First off, I didn't know how to find out more, since I didn't realize they were called *type signatures* until I read through some issues. Then I struggled with comprehending what the arrows that separate arguments mean, until the penny finally dropped after reading [wiki](https://en.wikipedia.org/wiki/Type_signature#Haskell) (the reason is currying, of course).

Now I'm having trouble understanding the documentation for more advanced signatures containing types and fat arrows/equals signs/spaces – for example `Ord a => a → a → Boolean` or `Lens s a = Functor f => (a → f a) → s → f s`.

It would be great to have an **Introduction to the docs** on the front page.

Probably related to https://github.com/ramda/ramda/issues/1627.

**Comment by CrossEye** [comment]
Agreed.  There are a number of top-level documentation topics like this we need to create and make easily available.

I believe that the best documentation jobs are usually done by people just learning the material, only lightly edited by the more experiences.  Do you feel like taking a crack at documenting the signatures?  Any Markdown version would be fine, a pull-request against the [docs project][rd], or a comment here, or whatever.  If we get the content, we will figure out how to include it on the page.


  [rd]: https://github.com/ramda/ramda.github.io

**Comment by dalgard** [comment]
I can see why someone from the outside might have a useful perspective. Being able to pass on knowledge effectively is one of the last stages of understanding, and I still feel like I'm rummaging around in semi-darkness.

If I continue to use Ramda after gaining a deeper insight into functional programming, I might take on the task. Thanks for the great work so far, though!

**Comment by davidchambers** [comment]
Sanctuary's [types][1] section largely applies to Ramda as well.

The paragraph on the use of the fat arrow (`=>`) hopefully sheds some light on the situation:

> Sanctuary supports type classes: constraints on type variables. Whereas `a -> a` implicitly supports every type, `Functor f => (a -> b) -> f a -> f b` requires that `f` be a type which satisfies the requirements of the Functor type class. Type-class constraints appear at the beginning of a type signature, separated from the rest of the signature by a fat arrow (`=>`).


[1]: https://github.com/plaid/sanctuary#types

**Comment by jirutka** [comment]
I’ve learnt Hindley-Milner type signatures from @DrBoolean’s wonderful [Mostly Adequate Guide to FP, chapter 7](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch7.md).

**Comment by CrossEye** [comment]
> I never thought about it that way, but I can see why someone from the outside might have a useful perspective. Being able to pass on knowledge effectively, though, is one of the last stages of understanding

It's up to you, of course.  But trying to document something is to me one of the best ways to really learn it.  And documentation from someone struggling to learn it is often the most helpful sort for someone else in the same situation.

**Comment by arcseldon** [comment]
I know this book is (superficially) about Haskell, but actually it is a pretty easy introductory read to FP in general (and that is where it shines), and has a section that covers the basics of the types and type signatures. 

I think reading this book goes along way to helping anyone learning FP with JavaScript, and in particular the Ramda library - [Learn You A Haskell](http://learnyouahaskell.com) - don't be put off by the title, if you happen to learn a little Haskell as part of the read, great, but honestly I think  you'll quickly forget it is Haskell you're reading. Oh yeah, and it's free too. Makes a great companion text to Mostly Adequate Guide recommended by @jirutka. 

Entirely agree with @CrossEye that having a go at the docs would help consolidate your learnings. I am doing something similar, doing screen cast material which will include several sections on Ramda. Watch this space :smile:

**Comment by dalgard** [comment]
Thanks for your points. Can you tell me what `Lens s a = Functor f => ...` means?

**Comment by jackfirth** [comment]
@dalgard The equals character there means that the left is a _type alias_ for the right. Type aliases are used all over Haskell to make types more readable. Instead of a type `User Int String` (representing that a User object contains an int value and a string value), a typed FP-er might define type aliases like `ID = Int` and `Name = String` and define the user type as `User ID Name`. The aliases mean the exact same thing as the types they stand for, but it helps document intent.

`Lens s a` is a type alias for a more complex type built off a transformation of functor-producing functions (called the van Laarhoven representation) which is rather complex, so the alias makes it easier to read type signatures of functions that manipulate or produce lenses without the hairy details of lenses.

**Comment by dalgard** [comment]
@jackfirth: Thanks, that's very helpful.

@CrossEye has written a [wiki chapter](https://github.com/ramda/ramda/wiki/Type-Signatures) about this subject, as discussed in https://github.com/ramda/ramda/issues/1627. It's really good and I'd like to see it promoted on the website, but I think this issue can be closed. Thanks again.
