### ISSUE TITLE
R.is(Number, NaN) === true

### ISSUE THREAD

**Issue by mrtnbroder** [ramda/ramda#1629]
Welcome to Javascript!

In my opinion `R.is(Number, NaN)` should return false....obviously.

**Comment by jirutka** [comment]
Well, the NaN is still a number type. It may look weird, but it's actually quite reasonable; read answers at http://stackoverflow.com/questions/2801601/why-does-typeof-nan-return-number

**Comment by mrtnbroder** [comment]
But if you read it out loud... it makes zero sense. I think ramda should take care of this, as it should fix javascript quirks like that.

**Comment by jirutka** [comment]
Yeah, if you read it "Not a Number is a Number", then it's an oxymoron. However, it may be just a problem of our interpretation.

**Comment by jirutka** [comment]
Documentation is very clear about it:

> See if an object **is an instance of** the supplied constructor.

NaN is an instance of Number in JS (and I guess that not just here). It's a special instance that indicates that the result of numeric calculation actually isn't a valid number. If `R.is` worked as you suggests, than it'd lie.

I understand your point of view, but I'm afraid that it may cause even more confusion.

**Comment by raine** [comment]
I don't think it's reasonable to expect code to always make sense when interpreted literally. If we really wanted that we'd be renaming this function to `R.isInstanceOf`. To keep function names sane it's probably not feasible endeavor to convey function semantics in this way.

**Comment by mrtnbroder** [comment]
`to make function names sane` this is what bugs me here. `R.is` doesn't make up for it's name then. `R.isType` could also be a name for this and then I could agree on `typeof NaN === 'number'` but `R.is` sounds a lot more stricter about the type/instance checks it does imo.

**Comment by mrtnbroder** [comment]
Me as a human I tend to think more literally of course and I think a library like ramda should take this in mind. I mean this lib is for us humans, not the computer :)

**Comment by CrossEye** [comment]
I think the problem is that `NaN` is spelled wrong.  It is a number according to the IEEE 754 specification, which is what Javascript supports.  If it were called `InvalidNumber` rather than `Not a Number`, things would be much more clear.

This is for humans, and we want the proper ergonomic fit where we can.  `is(Rectangle)` reads better and is altogether clearer than `isType(Rectangle)`.  This is true across the board.  Because of the weird naming of `NaN`, though, in that one case, the read-aloud is correct, but _sounds_ very strange.

**Comment by davidchambers** [comment]
`NaN` is a member of [`Number`][1] (though not of [`ValidNumber`][2]).

One can always define one's own function:

```javascript
//    isValidNumber :: Any -> Boolean
const isValidNumber = R.both(R.is(Number), R.complement(R.equals(NaN)));
```


[1]: https://github.com/plaid/sanctuary-def#number
[2]: https://github.com/plaid/sanctuary-def#validnumber
