### ISSUE TITLE
Error in "Mess with the DOM"

### ISSUE THREAD

**Issue by fortil** [ramda/ramda#1630]
```
var cssQuery = R.invoker(1, 'querySelectorAll');
var setStyle = R.assoc('style');
R.pipe(
  cssQuery('a, p'),
  R.map(setStyle('color', 'red'))
)(document)

```

**Return error**

I think it must be this way

```
var cssQuery = R.invoker(1, 'querySelectorAll');
var setStyle = R.curry((prop, value,node) => node.style[prop] = value)
R.pipe(
  cssQuery('a, p'),
  R.map(setStyle('color', 'red'))
)(document)

```

**Comment by davidchambers** [comment]
You're providing four arguments to `R.assoc`: `'style'`, `'color'`, `'red'`, and a value from the collection. `R.assoc` takes three arguments.

Note also that `R.assoc` does not mutate the provided object, but in this case the point of the operation is to mutate the DOM node.
