### ISSUE TITLE
Fix broken link in README.md to "Introducing Ramda by Buzz de Cafe"

### ISSUE THREAD

**Issue by protron** [ramda/ramda#1633]
Seems like Buzz de Cafe now doesn't support the forward slash (/) at the end.
Replace :
http://buzzdecafe.github.io/code/2014/05/16/introducing-ramda/
with:
http://buzzdecafe.github.io/code/2014/05/16/introducing-ramda

**Comment by buzzdecafe** [comment]
gah, updated jekyll this weekend. did not realize this was a side-effect
