### ISSUE TITLE
Concat does not dispatch

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#1635]
http://ramdajs.com/0.19.1/docs/#concat

> Dispatches to the concat method of the second argument, if present.

```js
let R = require("ramda");

class Buffer {
  concat() {
    console.log("called!");
  }
}

R.concat([1], new Buffer()); // no luck
```

**Comment by buzzdecafe** [comment]
docs are wrong. `concat` is treated as infix, so first arg dispatches

**Comment by ivan-kleshnin** [comment]
Ah, another point for adding controllable multidispatch https://github.com/ramda/ramda/issues/1634
It's really important to dispatch on second argument here.

**Comment by ivan-kleshnin** [comment]
I see. Duplicate of https://github.com/ramda/ramda/issues/1604
