### ISSUE TITLE
Cookbook

### ISSUE THREAD

**Issue by jcristovao** [ramda/ramda#1637]
Hey,

Just though I would ask first before pull requesting / trying to edit the wiki:

1) There's no mention to the cookbook on the readme - it took me sometime to find it (probably my fault, I keep forgetting github has wiki's, but as so many projects don't use it... )

2) Can I also edit the wiki to mention [this cookbook implementation](https://github.com/enten/rcb)?

**Comment by CrossEye** [comment]
Feel free to both edit the wiki and to make a PR for the ReadMe.  You're absolutely right that the ReadMe should point to the Cookbook.

And I would have no problems if the Cookbook had a section with a title something like "Similar Resources" that listed pages like the one you suggest.

**Comment by raine** [comment]
`rcb` is mentioned here already https://github.com/ramda/ramda/wiki
