### ISSUE TITLE
Document relationship with Ramda Fantasy and Sanctuary

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1641]
I'm confused by how Ramda integrates with or relates to [Ramda Fantasy](https://github.com/ramda/ramda-fantasy) and [Sanctuary](https://github.com/plaid/sanctuary). It seems that algebraic data types from Ramda Fantasy are sometimes handled (\*quack-quack\*) by Ramda, and in one issue thread, Sanctuary is mentioned as a "sister project".

There's also the [Ramtuary REPL](http://davidchase.github.io/ramtuary/), which gives me the impression that combining the three is a sort of holy grail. I can't figure out why, though.

Someone mentioned at one point that the scope and goal of the two companion libraries are completely different. I'm not sure why, as they both implement stuff like `Maybe`.

@CrossEye @davidchase @davidchambers @svozza @buzzdecafe @scott-christopher (I'm not sure which repo this issue is most relevant in, so I'm tagging you instead – sorry for the inconvenience)

**Comment by CrossEye** [comment]
Yes, that does need to get into documentation somewhere.  For the nonce, if you're curious you can see https://github.com/ramda/ramda/pull/1391#issuecomment-163051576,

The work of David Chase's excellent Ramtuary REPL has become the basis for the new version of the [Ramda REPL][re].  It's not so much that combining the three is some major goal on its own, but the three communities have very substantial overlaps; most of the people using Sanctuary or Ramda-Fantasy are also using Ramda.  Sanctuary grew out of the need to have safer versions of Ramda functions, and is, at least for now, built on top of Ramda.  Ramda Fantasy was at first a playground trying to work out the implications of the [FantasyLand][fl] types, but has slowly evolved into a more realistic implementation of them.  Ramda should work with _any_ implementation of these specifications, not just our own.  I can attest that it works fine with [Folktale][fo] and Sanctuary.


  [fl]: https://github.com/fantasyland/fantasy-land
  [fo]: http://folktalejs.org/
  [re]: http://ramdajs.com/repl/?v=0.19.1

**Comment by dalgard** [comment]
Thanks, @CrossEye. I guess there's already the Manual thread (https://github.com/ramda/ramda/issues/1282) for documenting these relationships, then.
