### ISSUE TITLE
Why prefer compose over pipe?

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1642]
Up until now, I have been using `pipe` exclusively instead of `compose`. As a normal JavaScript developer, `pipe` just seems more natural. When reading about functional programming, though, the `compose` function is always used, so I fear that I'm somehow limited in my thinking.

Is there some advantage in the ordering of arguments that `compose` uses?

**Comment by buzzdecafe** [comment]
I don't think there's a meaningful difference. `compose` is closer to the mathematical notion of `(f ∘ g)(x) = f(g(x))`, but `pipe` is often easier to read in evaluation order.

**Comment by dalgard** [comment]
Thanks, I see your point, especially when calling it right away. Anyway, I guess I shouldn't be *worried*, then, just because I've never used a single `compose` but have always used `pipe` instead...

**Comment by jirutka** [comment]
I always prefer `pipe`, it's more natural, because it follows evaluation order.

**Comment by arcseldon** [comment]
Yes, pipe does actually seem more natural, I tend to compose pretty heavily for everyday functional pipelining. Here is a simple (contrived) illustration using Reduce (which can be used for Map, Filter, Flatten, FlatMap et al too...) to illustrate how they are sort of reverse operations of one another:

```js
'use strict';

const R = require('ramda'),
  reduce = R.reduce,
  reduceRight = R.reduceRight,
  increment = R.inc,
  double = R.multiply(2),
  decrement = R.dec;

const pipeline = [
  increment,
  decrement,
  increment,
  double,
  increment,
  decrement,
  increment
];

const initial = 1;

const pipe = reduce(function(acc, fn) {
  return fn(acc)}, initial);

const compose = reduceRight(function(acc, fn) {
  return fn(acc)}, initial);

pipe(pipeline);
//=> 5

compose(pipeline);
//=> 5
```

**Comment by foiseworth** [comment]
Compose also makes a lot of sense when using React components:
`const TodoList = R.compose(Container, List, R.map(ListItem), items)`

Whilst you create the inner components first, you think of the outer ones as containing the inners.

**Comment by jspengeman** [comment]
A little late to the party here but I am not seeing how your example @foiseworth would work, would you mind explaining it a bit further? 

A React component has props as one of it's parameters so for example, when you try and compose `List` with `Container` you are passing a function in place of the prop to the `Container` component which seems wrong to me. How would the `Container` component know what to render? Same goes for `List` when it is passed an array of `ListItem`s in place of it's props. Thanks! I am looking forward to your response.

**Comment by hyungjunk** [comment]
Agreed to @jspengeman.
Component in the middle of compose is just a function that takes only an argument and returns `JSX.Element`.
Would there be any way that `React.Component` gets composed without being a normal function?
