### ISSUE TITLE
maps-difference analog?

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1643]
Guava has a nice little utility for computing the difference between maps (along with the non-differing portions):
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Maps.html#difference%28java.util.Map,%20java.util.Map%29

Implementing similar functionality in JS code today, I was wondering if it's a good fit for the library. Here's one implementation:
http://goo.gl/zbSMwR

**Comment by CrossEye** [comment]
While I could be convinced, my first thought is that this is more likely Cookbook material.  I have used functions like this... but only once or twice in my career.  That to me doesn't reach some fuzzy threshold necessary to mark it for inclusion in the core.

But I'm not dead-set against it.

**Comment by asaf-romano** [comment]
That was my initial thought too. The reason I think this might be worth it anyway (and I believe that's why Guava has it) is that the implementation isn't trivial at all.

**Comment by davidchambers** [comment]
I'm not in favour of including this in Ramda, though I'd love to see it in the cookbook.

**Comment by buzzdecafe** [comment]
:+1: :cookie: :book:

**Comment by asaf-romano** [comment]
Fair enough!

**Comment by asaf-romano** [comment]
Add here: https://github.com/ramda/ramda/wiki/Cookbook#use-ramda-fantasy-future-to-wrap-ajax

But I don't know how to update the ToC.

**Comment by CrossEye** [comment]
@raine has told me how to do it several times, and I always forget.  It involves running some build script in some project somewhere.  I'll try to look at my notes tomorrow.
