### ISSUE TITLE
Converge via array in pipe/compose

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1645]
It would be really convenient if `pipe` and `compose` accepted an array for an argument, so that these would all become equivalent:

`R.pipe(f, [g, h], i)(x)`
`R.compose(i, [g, h], f)(x)`
`R.compose(R.converge(i, [g, h]), f)(x)`
`i(g(f(x)), h(f(x)))`

It would give a slightly weird impression if the signature of `pipe`/`compose` had been different, with the supplied functions wrapped in an array (https://github.com/ramda/ramda/issues/1644), because the outer array would then not have the same meaning as the inner array. But since this is **not** the case, I think this syntax is nice.

**Comment by CrossEye** [comment]
This is absolutely fascinating!  It combines, say, `pipe` and `converge` fairly seamlessly with an intuitive syntax.

It will take me some time to think through the implications, but it would be another great way to get rid of `converge`.  I really want to find some extension of this that would also handle `useWith`.  I don't know what that is, but it does feel as though it might be possible.

(Don't you think that the order of elements inside the array in `compose` should be reversed?)

**Comment by davidchambers** [comment]
This is an interesting idea. I'm pretty sure I don't want to see `R.compose` and `R.pipe` support this: they already have awful type signatures! I'm open to the possibility of a *new* function which makes "diamond-shaped" compositions easier to define.

**Comment by CrossEye** [comment]
Perhaps `flow` as kindred to `pipe`.  And if we did create a new function, we wouldn't have to define both directions as with `compose`.

If there is an intuitive way to cover `useWith` as well, I would find this a really big win.

**Comment by scott-christopher** [comment]
This feels somewhat related to the notion of Arrows, with tuples being swapped with arrays.

https://en.wikibooks.org/wiki/Haskell/Understanding_arrows#An_Arrow_can_multitask

If we specialise the `Arrow` typeclass to functions, we get something that looks like:
```hs
first  :: (a -> b) -> (a, c) -> (b, c)
second :: (a -> b) -> (c, a) -> (c, b)
(***)  :: (a -> c) -> (b -> d) -> (a, b) -> (c, d)
(&&&)  :: (a -> b) -> (a -> c) -> a -> (b, c)
```

And swapping the tuples out with lists could get something like:
```hs
first  :: (a -> a') -> [a, b, ... z] -> [a', b, ... z]
second :: (b -> b') -> [a, b, ... z] -> [a, b', ... z]
(***)  :: [(a -> a'), (b -> b'), ... (z -> z')] -> [a, b, ... z] -> [a', b', ... z']
(&&&)  :: [(a -> b), (a -> c), ... (a -> z)] -> a -> [b, c, ... z]
```
`first` and `second` here are affectively just `adjust(_, 0)` and `adjust(_, 1)` respectively, while `***` and `&&&` become close to representing `useWith` and `converge` respectively.

It should then be possible to replicate the existing `converge` and `useWith` functions: <sup>[1]</sup>
```
converge = (mergeFn, fns) => compose(unapply(mergeFn), starStarStar(fns));
useWith = (mergeFn, fns) => compose(unapply(mergeFn), andAndAnd(fns));
```

Getting back to the original request here, something like this should then be possible:
```
pipe(f, andAndAnd([g, h]), unapply(i))(x)
compose(unapply(i), andAndAnd([g, h]), f)(x)
```
While this doesn't have the same brevity as just dropping an array of functions in a `compose` chain like the original suggestion, I wonder whether something could potentially be gained here.

---

<sup>[1]</sup> *Feel free to come up with better names for `andAndAnd` and `starStarStar`*

**Comment by CrossEye** [comment]
> While this doesn't have the same brevity as just dropping an array of functions in a compose chain like the original suggestion, I wonder whether something could potentially be gained here.

At the very least, there's something to be learned by investigating this.

I might still play around with the original proposal, as this might really help build declarative pipelines, a worthy goal.  I wish I could think of a good extension to this for `useWith`.  The only one that's coming to mind is `flow([[pick, identity]], map)`, and even if that wasn't starting to lose the readability of the original, I'm afraid that it might introduce some ambiguity.

**Comment by benperez** [comment]
@scott-christopher Nice! I'd love to see `&&&` and `***` in ramda. I think I've seen `&&&` called `fanout`. A good name for `***` might be `flow` since the inputs flow through to the arrows (functions)

I personally prefer these versions since they aren't variadic:
```haskell
first  :: (a -> b) -> (a, c) -> (b, c)
second :: (a -> b) -> (c, a) -> (c, b)
(***)  :: (a -> c) -> (b -> d) -> (a, b) -> (c, d)
(&&&)  :: (a -> b) -> (a -> c) -> a -> (b, c)
```

**Comment by dalgard** [comment]
@CrossEye: I don't think the order should be reversed in `compose`, since it is a reflection of the parameter order, not the application order.

I like the name `flow`. It is better than `pipe`, in my opinion, since `pipe` in various other contexts means direct invocation rather than composition.

I'm surprised that no one has expressed any concerns about the signature, though. As much as I like these kinds of APIs, wouldn't it be considered overloading?

The stuff about Arrows is too advanced for me at this stage. In regard to `useWith`, it clashes with the fact that functions only return a single value – `useWith` can only ever be used as the first function in the pipe (without resorting to destructuring), whereas `converge` can be placed anywhere.

@davidchambers: I believe we're talking about the first half of your diamond here :)

**Comment by dalgard** [comment]
Even if the signature becomes a bit bothersome to read, playing around with the nested array syntax is kind of fun – what if these two were equivalent, for example?

`R.flow(f, [g, h, [i, j]], k)(x)`
`k(i(g(f(x))), j(h(f(x))))`

**Comment by scott-christopher** [comment]
> @benperez: I personally prefer these versions since they aren't variadic:

So do I, though the problem there is we don't have a native tuple type that we can return, meaning we can alternatively treat arrays as tuples (in which case we might as well extend to support variable-length arrays) or otherwise use functions via a church encoding of tuples:

```hs
type Pair a b = (a -> b -> c) -> c

flow   :: (a -> c) -> (b -> d) -> Pair a b -> Pair c d
fanout :: (a -> b) -> (a -> c) -> a -> Pair b c
first  :: (a -> b) -> Pair a c -> Pair b c
second :: (a -> b) -> Pair c a -> Pair c b
```

Which could be implemented via something like:
```js
const flow   = curry((f, g, p) => p((x, y) => pair_(f(x), g(y))))
const fanout = curry((f, g, x) => flow(f, g, pair_(x, x)))
const first  = f => flow(f, identity)
const second = f => flow(identity, f)
```

Along with a couple of helper functions for constructing and deconstructing tuples:
```js
//:: a -> b -> Pair a b
const pair_  = curry((a, b, z) => z(a, b))

//:: (a -> b -> c) -> Pair a b -> c
const unpair = curry((z, p) => p(z))
```

And then something similar to original request:
```js
const f = inc
const g = multiply(8)
const h = divide(4)
const i = subtract

// equiv to: `x => subtract(multiply(8, inc(x)), divide(4, inc(x)))`
const f1 = R.pipe(f, fanout(g, h), unpair(i))
f1(1) // 14

// or with compose
const f2 = R.compose(unpair(i), fanout(g, h), f)
f2(3) // 31

// or something a little more involved
// equiv to: `x => subtract(divide(4, multiple(8, inc(x))), multiple(8, divide(4, inc(x))))`
const f3 = R.pipe(f, fanout(g, h), flow(h, g), unpair(i))
f3(1) // -15.75
```

**Comment by buzzdecafe** [comment]
@scott-christopher can we use ramda-fantasy Tuple type for `Pair`?

**Comment by scott-christopher** [comment]
@buzzdecafe: Sure. It could be used for a few other things too like `toPairs`, `fromPairs` and `pair`, but that's a whole new conversation to be had :smile:

The other interest thing with the use of church encoding is that `flow` and `fanout` come very close to just being flipped versions of `useWith` and `converge` restricted to functions of two arguments.

**Comment by buzzdecafe** [comment]
this looks pretty familiar. `pair_` is `cons`; `first` is like `car`, and `second` is like `cdr` but just slightly twisted.

```js
const cons = (x, y) => (f) => f(x, y)
const car = (f) => f((x, y) => x)
const cdr = (f) => f((x, y) => y)
```

but the elaboration you are able to do with `flow` is a total revelation to me. Pretty exciting stuff

**Comment by arcseldon** [comment]
Found this moderately interesting and loosely related to this post - `compose` that takes an array as its argument in terms of `compose` with a `fold right` and `identity` initial accumulator.

```js
describe('compose with array support in terms of reduceRight and Identity', () => {

    const mul100 = R.multiply(100);
    const add1 = R.add(1);
    const pipeline = [add1, mul100, add1];
    const compose = R.compose;
    const composeA = R.reduceRight(R.compose, R.identity);

    it('should work with compose and args as params', () => {
      const algo = R.compose(...pipeline);
      expect(algo(1)).to.eql(201);
    });

    it('should work with compose and args as array', () => {
      const algo = composeA(pipeline);
      expect(algo(1)).to.eql(201);
    });

  });
```

**Comment by arcseldon** [comment]
This looks moderately encouraging:

```js
    const mul100 = R.multiply(100);
    const add1 = R.add(1);
    const pipeline = [add1, mul100, add1];
    const composeC = R.reduceRight(R.compose, R.identity);
    const composeP = R.reduceRight(R.pipe, R.identity);

    const composeH = function () {
      const args = Array.from(arguments);
      const composer = R.equals(R.length(args), 1) && R.isArrayLike(args[0]) ? composeC : composeP;
      const converter = (x) => R.isArrayLike(x) ?  composer(x) : x;
      return (data) => R.compose.apply(null, R.map(converter, args))(data);
    };

    it('should be possible to use composeH with params as args', () => {
      const algo = composeH(...pipeline);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with an array argument', () => {
      const algo = composeH(pipeline);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 1', () => {
      const algo = composeH(add1, [mul100, add1]);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 2', () => {
      const algo = composeH([add1, mul100], add1);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 3', () => {
      const algo = composeH(add1, mul100, [add1]);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 4', () => {
      const algo = composeH(add1, [mul100], add1);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 5', () => {
      const algo = composeH([add1], mul100, add1);
      expect(algo(1)).to.eql(201);
    });

    it('should be possible to use composeH with mix of params and arrays - 6', () => {
      const algo = composeH(add1, [add1]);
      expect(algo(1)).to.eql(3);
    });
```

Not catering for nested arrays.

**Comment by arcseldon** [comment]
> It would be really convenient if pipe and compose accepted an array for an argument, so that these would all become equivalent:
> 
> R.pipe(f, [g, h], i)(x)
> R.compose(i, [g, h], f)(x)
> R.compose(R.converge(i, [g, h]), f)(x)
> i(g(f(x)), h(f(x)))

ok, here is a working code solution. Note that pipe and compose are equivalent, as are compose(converge) and the final function composition, but they are ** not** all equivalent. I may have misunderstood how I read the above as I thought the OP was stating all four functions would be equivalent.

```js
'use strict';
/*eslint no-unused-expressions:0*/

const chai = require('chai'),
  expect = chai.expect,
  R = require('ramda');

describe.only('compose and pipe with arrays', () => {

  const mul100 = R.multiply(100);
  const add1 = R.add(1);
  const add3 = R.add(3);

  const composeH = function () {
    const args = Array.from(arguments);
    const composeP = R.reduceRight(R.pipe, R.identity);
    const converter = (x) => R.isArrayLike(x) ? composeP(x) : x;
    return (data) => R.compose.apply(null, R.map(converter, args))(data);
  };

  const pipeH = function () {
    const args = Array.from(arguments);
    const pipeP = R.reduce(R.pipe, R.identity);
    const converter = (x) => R.isArrayLike(x) ? pipeP(x) : x;
    return (data) => R.pipe.apply(null, R.map(converter, args))(data);
  };

  describe('compose in terms of reduceRight and Identity', () => {

    it('should be possible to use composeH with params as args', () => {
      const algo = composeH(...[add3, mul100, add1]);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with an array argument', () => {
      const algo = composeH(add3, mul100, add1);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 1', () => {
      const algo = composeH(add3, [mul100, add1]);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 2', () => {
      const algo = composeH([add3, mul100], add1);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 3', () => {
      const algo = composeH(add3, mul100, [add1]);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 4', () => {
      const algo = composeH(add3, [mul100], add1);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 5', () => {
      const algo = composeH([add3], mul100, add1);
      expect(algo(1)).to.eql(203);
    });

    it('should be possible to use composeH with mix of params and arrays - 6', () => {
      const algo = composeH(add3, [add1]);
      expect(algo(1)).to.eql(5);
    });

  });


  describe('pipe in terms of reduceRight and Identity', () => {


    it('should be possible to use composeH with params as args', () => {
      const algo = pipeH(...[add3, mul100, add1]);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with an array argument', () => {
      const algo = pipeH(add3, mul100, add1);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 1', () => {
      const algo = pipeH(add3, [mul100, add1]);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 2', () => {
      const algo = pipeH([add3, mul100], add1);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 3', () => {
      const algo = pipeH(add3, mul100, [add1]);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 4', () => {
      const algo = pipeH(add3, [mul100], add1);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 5', () => {
      const algo = pipeH([add3], mul100, add1);
      expect(algo(1)).to.eql(401);
    });

    it('should be possible to use composeH with mix of params and arrays - 6', () => {
      const algo = pipeH(add3, [add1]);
      expect(algo(1)).to.eql(5);
    });

  });


  describe('with regards to this issue', () => {

    const f = R.multiply(3);
    const g = R.add(2);
    const h = R.add(3);
    const i = R.add(4);

    // R.pipe(f, [g, h], i)(x)
    it('should work with pipeH(f, [g, h], i)', () => {
      const algo = pipeH(f, [g, h], i);
      expect(algo(1)).to.eql(12);
    });

    // R.compose(i, [g, h], f)(x)
    it('should work with composeH(i, [g, h], f)', () => {
      const algo = composeH(i, [g, h], f);
      expect(algo(1)).to.eql(12);
    });

    // R.compose(R.converge(i, [g, h]), f)(x)
    it('should work with R.compose(R.converge(i, [g, h]), f)', () => {
      const algo = R.compose(R.converge(i, [g, h]), f);
      expect(algo(1)).to.eql(9);
    });

    // i(g(f(x)), h(f(x)))
    it('should work with i(g(f(x)), h(f(x)))', () => {
      expect(i(g(f(1)), h(f(1)))).to.eql(9);
    });

  });

});
```

**Comment by dalgard** [comment]
@arcseldon: Very nice. I'm still thinking about `useWith`, though....

**Comment by arcseldon** [comment]
@dalgard - interesting, am looking at that code again, and starting to suspect I have just rewritten a `flatten` function .. ooops.
