### ISSUE TITLE
Add documentation to DevDocs

### ISSUE THREAD

**Issue by dalgard** [ramda/ramda#1647]
... If anyone has time and/or knows how to do it in a breeze.

https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs

**Comment by buzzdecafe** [comment]
http://devdocs.io/ramda/

**Comment by CrossEye** [comment]
But I have no idea who actually added it!  :smile:

**Comment by dalgard** [comment]
Wow. I thought I scrutinized that list really closely yesterday. Thanks :+1:

**Comment by davidchambers** [comment]
> http://devdocs.io/ramda/

It's beautiful! Is it okay to find this more attractive than the Ramda website? ;)

**Comment by buzzdecafe** [comment]
sure. i don't have strong feelings either way, but i am grateful to the anonymous person that did it

**Comment by arcseldon** [comment]
Agreed, I think this format is perhaps more convenient than the website...

My personal favourite, is using bash command line:

![ramdabash](https://cloud.githubusercontent.com/assets/2599332/13181990/f88d052a-d772-11e5-8ca1-deed10b66301.gif)

Going to have to shell out for the full license for Alfred as it would be great to get support there too.

**Comment by davidchambers** [comment]
> My personal favourite, is using bash command line

That's cool! How does one set that up?

**Comment by arcseldon** [comment]
Thanks to** raine** for this:

[alfred ramda workflow](https://github.com/raine/alfred-ramda-workflow)

[Terminal based alternative](https://gist.github.com/raine/413b9ed9fd437942af0e)

While we are on it, I really like that new ramda bot on gitter - the stuff this community creates is fantastic :smile:
