### ISSUE TITLE
Functors, Applicative Functors, and Monads support in Ramda - documentation regarding current support?

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda#1650]
This week I have been swatting up on Haskell, and believe I have a pretty good grasp on the fundamentals constituting the fantasy land types - certainly as they relate to Haskell (i think!). However, I am now trying to relate what I now understand in Haskell to what has been implemented in Ramda in terms of algebraic type support.  Will start looking at source code, but I thought it would be worth raising an issue that the docs appear unclear on what kind of support each function offers. For instance, this [test](https://github.com/ramda/ramda/blob/master/test/liftN.js#L42-L45) suggests LiftN works with arbitrary applicative functors (in this case a Monad too). But I am unclear in general what support is available for which functions - I understand that Ramda should work well with Folktale or other Fantasy-land implementations, just be great to get some commentary on which and how if you know what I mean. 

For instance:  Ramda's map function, operates similarly to the one on Array.prototype, so R.map(square, [1, 2, 3, 4]); //=> [1, 4, 9, 16]. But because Folktale's / Ramda-Fantasy's Maybe implements the Fantasy-land Functor spec, which also specifies map, you can also use Ramda's map with it. And I have seen this first-hand too, working with Ramda and Maybe, and third party libs like ImmutableJs, and RxJs over the past week.

Right, I get that but would like more information around "dispatch" and which functions it applies too etc without trawling the code base where possible. Can anyone offer some quick pointers here, it may be I am raising a non-issue and just need someone to point out something fundamental.

Thanks in advance.

**Comment by arcseldon** [comment]
Just going to add a visual here too, to further illustrate what i think might be helpful. Comments welcome.

![ramdadocs](https://cloud.githubusercontent.com/assets/2599332/13181770/05bd7ff0-d772-11e5-8607-c6e61d01517c.jpg)

**Comment by CrossEye** [comment]
Of course you can get the same thing with a text search of the page, but I think it might be useful if our search bar filtered the list by doing the equivalent of a text search of the sections for each named function.  That could well be more useful.

**Comment by arcseldon** [comment]
@CrossEye - right, something like search of sections.  The search might address questions like - "Which functions in Ramda have dispatch capabilities that allow them to work with Objects that conform to the Fantasy Land apply specification?"

My original question was actually also questioning whether the Ramda docs are up-to-date, and whether a manual search (text search) would even be possible as things stand. Can you confirm the docs are consistent enough that searching for a single keyword such as** functor** or **apply** etc would display the right results?

Quoting a comment you made on [SOF in November](http://stackoverflow.com/questions/33486989/handling-asynchronous-programming-with-ramda) - you mention the docs aren't up to scratch for LiftN etc to do this.

It may well be that the docs are now improved. Anyhow, I shall keep researching, it might just be obvious with more hands-on usage.

**Comment by arcseldon** [comment]
Think this is (loosely) related [ramda docs Issue 61 - search by type signature](https://github.com/ramda/ramda.github.io/issues/61), in so far as there is overlap in what is trying to be achieved to some extent - a means to efficiently filter relevant function(s) based on their intent / scope / type support / type signature.

**Comment by arcseldon** [comment]
Here is a clear cut example of what I am seeing:

Take a look at the docs for [R.unnest](http://ramdajs.com/0.19.1/docs/#unnest)

There is no mention anywhere from reading that, that it holds the key to `mjoin` monadic behaviour.

For example:

```js
it('should remove one level of nested monad', () => {

      const nestedIceCream = Maybe(Maybe('Ice cream'));
      //=> _Just { value: _Just { value: 'Ice cream' } }
     
      const res2 = R.unnest(nestedIceCream);
      //=> _Just { value: 'Ice cream' }

      const res1 = R.chain(R.identity, nestedIceCream);
      //=> _Just { value: 'Ice cream' }
      
 });
```

Admittedly, `R.chain` does specify more info, but overall it isn't clear to someone coming in without context about the library and how the API is laid out. And it isn't really searchable either atm.

I would like to help out, but am still finding my feet with the library as it relates to Ramda-Fantasy (almost there mind you).

**Comment by arcseldon** [comment]
ok, there is a link to Chain...

**Comment by arcseldon** [comment]
Ok, I have done some further research, and wish to paste here a sort of survival guide to getting started with Ramda and Ramda-Fantasy - really illustrates simple usage of `map`, `ap`, and `chain` as they can be used with `Maybe`

Really think there should be equivalent examples like this for all the Data Types in ramda-fantasy, the documentation doesn't give explicit examples, and the test cases are too terse to be of assistance. I think the folktale test cases are generally easier to read if looking for example usages, eg. [folktale either](https://github.com/folktale/data.either/blob/master/test/specs/either.ls) but even they aren't that clear.

So here are the essentials to know (this focuses on usage of existing Monads in the ramda-fantasy package with ramda, and therefore does not indicate what rules need to be followed to roll your own monads etc):

```js
'use strict';
/*eslint no-unused-expressions:0*/

const chai = require('chai'),
  expect = chai.expect,
  R = require('ramda'),
  map = R.map,
  lift = R.lift,
  identity = R.identity,
  chain = R.chain,
  unnest = R.unnest,
  RF = require('ramda-fantasy'),
  Maybe = RF.Maybe,
  add = R.add;

describe('various uses of map, ap, and chain', () => {

  // functors are for things that can be mapped over
  // implement .map()
  // point free ramda equivalent is map

  // applicative functors are enhanced functors - they
  // allow us to apply normal functions between applicative values
  // implement .ap()
  // point free ramda equivalent is lift

  // monads are enhanced applicative functors which add the ability
  // for applicative values to be fed into normal functions
  // implement .chain()
  // point free ramda equivalents are unnest and chain


  // So every monad is an applicative functor, and every applicative functor
  // is a functor.

  // lets see chained and point free ways of invoking these in action


  describe('map, ap, chain equivalence', () => {

    it('should be possible to map over a Maybe applying an inc function', () => {

      const inc = add(1);

      // map point-free with ramda:
      expect(map(inc, Maybe(1))).to.eql(Maybe(2));
      // or:
      expect(Maybe(1).map(inc)).to.eql(Maybe(2));

      const addA = lift(add);

      // equivalent to using ap point-free with ramda:
      expect(addA(Maybe(1), Maybe(1))).to.eql(Maybe(2));
      // or:
      expect(Maybe(inc).ap(Maybe(1))).to.eql(Maybe(2));


      const incM = function (x) {
        return Maybe(inc(x));
      };

      // equivalent to using chain point-free with ramda:
      expect(chain(incM, Maybe(1))).to.eql(Maybe(2));
      // or:
      expect(Maybe(1).chain(incM)).to.eql(Maybe(2));

    });

  });

  describe('unnest / chain for unnesting', () => {

    it('should deal with unnesting using unnest and chain identity', () => {

      const nestedOne = Maybe(Maybe(1));

      // point free using ramda:
      expect(unnest(nestedOne)).to.eql(Maybe(1));

      // alternative point free using ramda:
      expect(chain(identity, nestedOne)).to.eql(Maybe(1));

      // explicitly
      expect(nestedOne.chain(identity)).to.eql(Maybe(1));

    });

  });


  describe('ap', () => {

    it('should work with ap - just pass a standard a -> b function, and ap' +
      'will handle the map process for you', () => {

      const add2 = add(2);

      // explicitly
      expect(Maybe(add2).ap(Maybe(2))).to.eql(Maybe(4));

      // equivalent to writing your own function, something like this:
      const customAdd2 = function (x) {
        return x + 2;
      };

      expect(Maybe(customAdd2).ap(Maybe(2))).to.eql(Maybe(4));

      // point free using ramda:
      expect(lift(add)(Maybe(2), Maybe(2))).to.eql(Maybe(4));

    });

  });


  describe('chain', () => {

    it('should result in Nothing when chaining with Nothing', () => {
      const Nothing = Maybe.Nothing(null);
      const Just = Maybe.Just('a');
      expect(Nothing.chain(Just)).to.eql(Nothing);
    });

    it('should add another maybe', () => {
      const addMaybe3 = function (x) {
        return map(add(x), Maybe(3));
      };
      expect(Maybe(2).chain(addMaybe3)).to.eql(Maybe(5));
    });

  });

});

```

In addition to this, I have written tens of test cases with more everyday usage scenarios for each individual data type  (Maybe, Future, IO, Either)  - be happy to share all this - perhaps one for the Ramda Manual?

**Comment by arcseldon** [comment]
Currently researching available support for Natural Transformations. These would permit transforming one data type to another eg.

```js
maybeToList :: Maybe a -> [a]
maybeToList (Just x) = [x]
maybeToList Nothing = []

listToMaybe :: [a] -> Maybe a
listToMaybe (x:xs) = Just x
listToMaybe [] = Nothing

tupleToEither :: (a, b) -> Either a b
eitherToReader :: Eitehr a b -> Reader a b
```

**Comment by CrossEye** [comment]
> Ok, I have done some further research, and wish to paste here a sort of survival guide to getting started with Ramda and Ramda-Fantasy - really illustrates simple usage of `map`, `ap`, and `chain` as they can be used with `Maybe`

Again, I think this is great stuff.  You're coming up with more on Ramda-Fantasy than I was originally expecting to include in the manual.  But I have no objection at all to expanding what is now a small section into something larger.

One point, though, if you're looking to include this in the manual, the style is a meant to be a fairly even mixture of code and expository text.  See the examples of the two sections built so far:

  * [Small Function][sf]
  * [Immutability][im]

I posted a fairly small [styleguide][sg] when I got to work on the Manual.  Let's stick to it as best we can, or at least discuss it before veering from it.

  [im]: http://ramdajs.com/0.19.1/manual/01-intro/Immutability.html
  [sf]: http://ramdajs.com/0.19.1/manual/01-intro/SmallFunctions.html
  [sg]: https://github.com/ramda/ramda/issues/1282#issuecomment-123879214

**Comment by arcseldon** [comment]
@CrossEye - thanks, appreciate the feedback and guidance on how to write entries for the Manual.  I will likely aim to start merging in some of the examples pasted in various issues together with further test cases next weekend (time permitting). Will also add some more commentary on what is going on if I can.

**Comment by arcseldon** [comment]
Wished to add here, that I contacted Brian Lonsdorf and the company where he works is using the following heavily in production (for past year already) - in case others are searching for fantasy land implementations of Future that have been proven in PRD:

[control async](https://github.com/folktale/control.async)

[data task](https://github.com/folktale/data.task)

**Comment by slavomirvojacek** [comment]
For Monads perhaps see https://github.com/Threestup/monads.
