### ISSUE TITLE
Should R.partition work for objects?

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1651]
Now that R.filter and R.reject work with objects, it might make sense to make package-deal R.partition (in contrast to R.splitWhen, btw) to do so as well.

**Comment by davidchambers** [comment]
`filter` and `reject` take a value of some (appropriate) type and return a value of that same type. Are you suggesting that `partition` should take a value of some (appropriate) type and return a pair of values of that type?

```javascript
R.partition(n => n > 0, {a: 1, b: -2, c: 3});
// => [{a: 1, c: 3}, {b: -2}]
```

**Comment by jackfirth** [comment]
It would make sense, as it means the law `partition(p, vs) = [(filter(p, vs), filter(complement(p), vs))]` would be properly satisfied for all `vs`, rather than just for lists.

**Comment by davidchambers** [comment]
Sounds good to me! Would you like to submit a pull request, @asaf-romano?

**Comment by asaf-romano** [comment]
Someday soon.

**Comment by CrossEye** [comment]
Would this generalize as discussed in #1429 to anything which meets

```js
class Filterable f where
  filter :: (a -> Boolean) -> f a -> f a
```

I can't help it; there's that slightly queasy feeling again!

**Comment by davidchambers** [comment]
I believe it would, @CrossEye. It's a good sign when you're *slightly* queasy. ;)

**Comment by asaf-romano** [comment]
Here's something worse to distract you...

```js
pluck("wtf", { a: { wtf: 1 } }); // => {"a": 1}  this actually works
```

**Comment by davidchambers** [comment]
```javascript
R.pluck('wtf', {a: {wtf: 1}});
// => {a: 1}

S.pluck(Number, 'wtf', {a: {wtf: 1}});
// ! TypeError: ‘pluck’ expected a value of type (Array a) as its third argument; received {"a": {"wtf": 1}}
```

I'm very pleased to have access to a refuge from unsafe JavaScript.

**Comment by CrossEye** [comment]
> Here's something worse to distract you...
> 
> ```js
> pluck("wtf", { a: { wtf: 1 } }); // => {"a": 1}  this actually works
> ```

What seems wrong with that?

Seriously, when we decided to extend `map` to objects (#1426), we open this up, since `pluck` is logically `map(prop)`, if this _didn't_ work, I think people would have the right to ask why.  We happen to implement it that way, so everything is fine.

**Comment by asaf-romano** [comment]
I don't know, it just felt wrong. I've never thought of pluck as a sugar for all functors, but rather as a utility for lists. You might be right though, because the following does feel intuitive in a strange way:
```js
pluck("p", Maybe.of({ p: 1 })); // => Maybe.Just(1)
```

**Comment by asaf-romano** [comment]
BTW, is there an equivalent to S.toMaybe in ramda-fantasy?

**Comment by arcseldon** [comment]
I think it is just the Maybe constructor isn't it?

**Comment by asaf-romano** [comment]
ah, cool.

**Comment by asaf-romano** [comment]
Regarding the ``Filterable`` abstraction, looking at the code again, I think we have a problem here: ``partition`` does not even dispatch to ``filter``, so there will be ``Filterable`` instances for which ``filter`` works, but partition does not.

**Comment by stoeffel** [comment]
Jop, it's just the constructor. [see](http://davidchase.github.io/ramtuary/#?code=var%20log%20%3D%20%28rf%2C%20san%29%20%3D%3E%20console.log%28rf.toString%28%29%2C%20san.toString%28%29%29%0Avar%20nope%20%3D%20null%3B%0Avar%20something%20%3D%2042%3B%0A%0Alog%28%0A%20%20Maybe%28nope%29%0A%2C%20S.toMaybe%28nope%29%0A%29%3B%0A%0Alog%28%0A%20%20Maybe%28something%29%0A%2C%20S.toMaybe%28something%29%0A%29%3B%0A)

**Comment by asaf-romano** [comment]
It should probably be mentioned in the documentation, which atm only specifies the top-level constructors (Just, Nothing).

**Comment by arcseldon** [comment]
Agreed. Not obvious from the docs - you, I and others have raised similar question on this over past few days.

**Comment by buzzdecafe** [comment]
> `partition` does not even dispatch to `filter`, so there will be `Filterable` instances for which `filter` works, but `partition` does not.

that seems bad

**Comment by asaf-romano** [comment]
Note that all of this is not a problem if we could've simply ignore performance and implement ``partition`` in terms of ``filter`` and ``reject``:
```js
var naivePartition = juxt([filter, reject]);  // or converge(pair, [filter, reject])

naivePartition(gt(__, 0), [-2, -1, 0, 1, 2]);
// = [[1, 2], [-2, -1, 0]]

naivePartition(gt(__, 0), { a: -2, b: -1, c: 0, d: 1, e: 2 });
// [{"d": 1, "e": 2}, {"a": -2, "b": -1, "c": 0}]
```
But we cannot. However, we could do the following:
1) Provide a fast path for arrays,
2) Provide a fast path for objects
3) ``juxt([filter, reject])`` everything else.

**Comment by buzzdecafe** [comment]
IMO we should favor correctness and optimize later. and i believe that's the consensus view.

**Comment by asaf-romano** [comment]
That is, just call ``juxt([filter, reject])``? In terms of performance, that's a downgrade comparing to the current implementation, which fills both sides in a single iteration.

**Comment by buzzdecafe** [comment]
> That is, just call juxt([filter, reject])? In terms of performance, that's a downgrade comparing to the current implementation, which fills both sides in a single iteration.

I'd rather get the right answer slowly than get the wrong answer quickly. And as you mentioned, if we later decide that we need to optimize, we can add special-case "fast paths".

Just my $0.02

**Comment by asaf-romano** [comment]
OK, I'll PR that option and stash the other. I guess I'm just over paranoid given all the performance issues I had to fight with lately (Note to self: file that ticket about ``into([])``)

**Comment by buzzdecafe** [comment]
one comment on this; we are using the notion of "type" pretty loosely here:

> Are you suggesting that partition should take a value of some (appropriate) type and return a pair of values of that type?
> ```js
> R.partition(n => n > 0, {a: 1, b: -2, c: 3});
> // => [{a: 1, c: 3}, {b: -2}]
> ```

I think most strongly-typed languages would consider `{a: int, b: int, c: int}`, `{a: int, c: int}`, and `{b: int}` to be *three different types*. That said, I certainly do not want to get to that granular here.

**Comment by CrossEye** [comment]
I agree that an implementation that will work for all the types we want to support is best.  We've generally shied away from building our functions on top of each other overmuch, but that's mostly out of a vague desire to keep performance concerns vaguely alive while we wrote correct code.  I would have no issue with `juxt([filter, reject])` or something similar.

As to
> I think most strongly-typed languages would consider `{a: int, b: int, c: int}`, `{a: int, c: int}`, and `{b: int}` to be *three different types*. 

Or they would consider them all instances of a `Dictionary`/`Map` type.  That's the interesting thing about types; things that from one perspective are unrelated, from another are brother and sister.

**Comment by davidchambers** [comment]
> > I think most strongly-typed languages would consider `{a: int, b: int, c: int}`, `{a: int, c: int}`, and `{b: int}` to be *three different types*.
>
> Or they would consider them all instances of a `Dictionary`/`Map` type.

This is what I had in mind. [StrMap][1] is one such type.

It's worth remembering that the relationship between values and types is many-to-many. For example:

```javascript
{a: 1, b: -2, c: 3} :: { a :: Number, b :: Number, c :: Number }
                       { a :: ValidNumber, b :: ValidNumber, c :: ValidNumber }
                       { a :: FiniteNumber, b :: FiniteNumber, c :: FiniteNumber }
                       // [340 RecordType permutations omitted]
                       Object,
                       (StrMap Number),
                       (StrMap ValidNumber),
                       (StrMap FiniteNumber),
                       (StrMap Integer),
                       (StrMap NonZeroValidNumber),
                       (StrMap NonZeroFiniteNumber),
                       (StrMap NonZeroInteger)
```

Of the several hundred types listed (or elided) above, only the last eight are common to `{a: 1, b: -2, c: 3}`, `{a: 1, c: 3}`, and `{b: -2}`.

Of the several hundred types listed (or elided) above, only the last *seven* satisfy the requirements of Filterable.


[1]: https://github.com/plaid/sanctuary-def/pull/33

**Comment by buzzdecafe** [comment]
> Or they would consider them all instances of a Dictionary/Map type.

Sure; in JS you get to have it both ways (or neither, depending on how you look at it); i.e. there is no type difference between `{a: 1}` and `{a: 'one'}`. But if this were a Map type in some other language, the first would be a `string, int` Map, and the second would be a `string, string` map, i.e. two different types. As noted elsewhere, the js `{ }` is overloaded to be struct, record, dictionary, map .... and that may be a plus or a minus depending on where you're coming from. Anyways, not looking to drag this out any further.
