### ISSUE TITLE
Cheat Sheet

### ISSUE THREAD

**Issue by akshayl** [ramda/ramda#1652]
It would be great a have a cheat sheet similar to this: https://oscarotero.com/jquery/

**Comment by CrossEye** [comment]
Yes, it would.  Any interest in working on it?

Even better, in creating a tool that would automatically build it from JSDoc Category tags or other metadata?

**Comment by geusebi** [comment]
No time to work on it now but I did this:
https://geusebi.github.io/ramda-cheat-sheet/dist/

The search input will just highlight the matching function names,
a click on a function name redirect to ramdajs.com/...,
tooltips show the function jsdoc description. 

Problems:

- doesn't use any CSS framework so it will probably be ugly on many browsers,
- doesn't use any JS library so the search input probably won't work on some browsers,
- uses python with mako to build the cheat sheet (would be better to use js),
- the few lines of js and python are offending the public decency :-),
- to have a predictable order for categories and to have sub-categories an additional index file needs to maintained "ramda-fn-listing.js",
- others..

If somebody is interested in working on it or start something better, it would be great.

**Comment by buzzdecafe** [comment]
nice work, @geusebi! if i can find some time i may try some things with what you have started

**Comment by CrossEye** [comment]
:100:

**Comment by tusharmath** [comment]
@geusebi Loved the cheatsheet, could you update it with the latest functions?

**Comment by evgenykochetkov** [comment]
I made a quick-and-dirty tool that generates a cheatsheet from `jsdoc`: https://github.com/evgenykochetkov/ramda-cheatsheet

Would love some advice/PRs/etc
