### ISSUE TITLE
R.add is inconsistent with documentation

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda#1654]
The documentation for R.add states that it works with **numbers**. 

The type signature is:  **Number → Number → Number**

Was surprised it silently worked with Strings, which then made me consider whether it would work with arrays too. It does, but not how you might expect...

```js
 it('should work with different types', () => {
      expect(add(1.2, 1.3)).to.eql(2.5);
      expect(add('hello ', 'world')).to.eql('hello world');
      expect(add('1', '2')).to.eql('12');
      // expect(add([1, 2, 3], [4, 5, 6])).to.eql([1, 2, 3, 4, 5, 6]);
      expect(add([1, 2, 3], [4, 5, 6])).to.eql('1,2,34,5,6');
    });
```
Interactive example [here](http://goo.gl/l7YDRg)

My point here is that **R.add** is behaving incorrectly - either it works 'polymorphically' for different types (for example Array concatenation) or it should be restricted to just working with Numbers. It shouldn't be returning non-sensical String values regardless of whether "this is how plain JS works with + operator..." unsafe and ambiguous. 

Comments welcome.

**Comment by buzzdecafe** [comment]
My $0.02:

it would be nice, but at what cost? type coercion in JS is an unfortunate fact of life. I have absolutely no interest in run-time type-checking and enforcement. The majority of lines in the library would become type-checks. No thanks. For example, what about this:

`filter(whereEq({x: 0}), () => 1);`

that was almost certainly an invalid argument, right? Or was it? And what about:

`prop(10, {'10': 'ten'})`

Should that evaluate to a type error or 'ten'?

I've played with the idea of implementing Algorithm W to do type inference for ramda. But this implies a build step to do the type-check. In that case, there's no reason to use JS. 

If you really want real, comprehensive type safety I think you should use a language that will actually help you. There are plenty. JS will not help; in fact, it will fight you every step of the way. Pursuing real type-safety from JS is the road to madness.

**Comment by arcseldon** [comment]
@buzzdecafe - thanks for your reply. Am happy to close this issue, I actually thought twice about raising it. I was playing around with ideas out of Haskell to some extent, and add is often used as a showcase for various qualities from category theory (which you are no doubt familar with chapter and verse):

```js
 it('should simple category theory ideas from maths', () => {
      expect(add(1, 1)).to.eql(2);
      // associative
      expect(add(add(1, 2), 4)).to.eql(add(1, add(2, 4)));
      // commutative
      expect(add(4, 1)).to.eql(add(1, 4));
      // identity
      expect(add(1, 0)).to.eql(1);
      // distributive
      expect(multiply(2, add(3, 4))).to.eql(add(multiply(2, 3), multiply(2, 4)));
    });
```

Off the back of that, some documentation I was following (from brian lonsdorf) was using add as an example to illustrate generics regarding type etc, and that was when I noticed the behaviour of add in ramda didn't do what was being explained. Mind you, I understand your position on this. Thanks again.

**Comment by buzzdecafe** [comment]
> add is often used as a showcase for various qualities from category theory (which you are no doubt familar with chapter and verse)

No indeed -- i have a lot to learn about all of this stuff. My ignorance is exactly what got me interested in this project to begin with. I agree with you that the unintentionally polymorphic behavior of `add` is a problem. I just don't see a clear way to "fix" it in a js lib.

On the other hand, experience has taught me that I'm often wrong. So I am interested to hear if others want to contribute on this subject.

**Comment by arcseldon** [comment]
Further playing around... I think I might have closed this issue too early. Insultingly simple demo admittedly but..:

```js
const _Identity = function (value) {
  this.value = value;
};

_Identity.prototype.map = function (fn) {
  return new Identity(fn(this.value));
};

const Identity = function (value) {
  return new _Identity(value);
};
```

The problem with `add` really starts to show itself when you use the algebraic data types, in particular with nested functors. Take a look at this example:


```js

 R = require('ramda'),
  map = R.map,
  compose = R.compose,
  add = R.add,

it('should handle single functor map', () => {

      const inc = add(1);
      expect(map(inc, Identity(4))).to.eql(Identity(5));
    });

```

So far so good. Now, we have nested functor to map, and mistakenly get it wrong:

```js
  it('should handle nested functor map', () => {

// note 4 is wrapped inside a singleton array
      const broken = map(inc, Identity([4]));
      console.log(broken.value);
       // => 14  !!!!!!!!     // oh dear...
    });
```

Of course, what we wanted was to map twice and increment the value inside the singleton array inside Identity:

```js
it('should handle nested mapping', () => {

      const res = map(map(inc), Identity([4]));
      expect(res).to.eql(Identity([5]));

    });
```

I am really started to be skeptical that these algebraic types make much sense unless Type support is available. Otherwise, it is just so easy to go wrong without any compile time or (perhaps even) runtime errors to indicate something has gone wrong.

Feedback most welcome.

**Comment by buzzdecafe** [comment]
> I am really started to be skeptical that these algebraic types make much sense unless Type support is available

yep. ultimately, the onus is on the user to be the type checker.

**Comment by arcseldon** [comment]
@buzzdecafe - Agree with you here, thanks for the input. Perhaps overstating the problem, as this isn't so different from the risks inherent in JS full-stop. Do find in this language I have to aim for very high test coverage to remediate bugs that can be identified early. But this algebraic stuff isn't that easy to reason about when it starts dealing with nesting, maps, flatmaps, compositions etc.

Will leave this issue open for another day in case others wish to contribute. Satisfied I know where I stand on this - proceed with caution.

**Comment by CrossEye** [comment]
> Satisfied I know where I stand on this - proceed with caution.

I think that is one of the lessons to take with you when working in a dynamically typed language.  But many people find that these sorts of issues have little practical import for them.

I absolutely love what @davidchambers is doing with [Sanctuary][sa], and it does help add some sanity to the process.  But I feel that so long as the base language is JS, it's a fool's errand to expect strong type safety.

As to something like `add`, I'm perfectly happy with _caveat emptor_.  We create a function, tell you the types it's designed to work on.  That it manages to have some interesting behavior when you supply other types, appropriate or not, is happenstance.  Don't count on that behavior remaining the same on the next release, though. 


  [sa]: https://github.com/plaid/sanctuary/

**Comment by arcseldon** [comment]
Thanks for comments. Closing, as this is expected behaviour.
