### ISSUE TITLE
in-house transducer accumulators should use mutable reductions 

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1656]
Last week I tired to optimize some slow, heavy multi-map-inversion-kind-of-code to use transducers, only to find out they made the situation even worse. Curios, I went ahead and read the implementation, and was surprised to see that the in-house transducer accumulators ([] and {}) do not perform what's, in Java 8's lingo, called "mutable reductions" (https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#MutableReduction ; apart the combiner element and the naming conventions, Java's Collector is Clojure's transducer). Rather, they clone the result object *every step of the way* (see https://github.com/ramda/ramda/blob/master/src/internal/_stepCat.js). I don't know what Cloujre is doing in their analogous APIs (comparing to java's mutable reductions, or to Ramda's implementation of transducers), but regardless, it seems very strange for the "default" implementation of into([]) and into({}) not to take advantage of the functionality provided by transducers themselves, esp. given that all those intermediate objects are not visible to the consumer.

Semi-benchmark:
http://goo.gl/xn24gq

**Comment by asaf-romano** [comment]
Note that you don't want to add another 0 to this line:
```js
var pairs = times(() => times(randomInt, 2), 1000); 
```
Unless you keep just the new implementation running. into([]) doesn't return in a reasonable time.

**Comment by buzzdecafe** [comment]
nice analysis. this needs to be fixed. As long as the mutation can't escape, i think we have to do it that way.

**Comment by asaf-romano** [comment]
What's the time frame for 0.20? I can PR this soonish; will save me a file or two in my projects :)

**Comment by buzzdecafe** [comment]
i was in a rush, but now that deprecating `converge` has turned out to be controversial, i'm no longer in a rush. I may revert that deprecation and publish 0.20 without it

**Comment by CrossEye** [comment]
This is impressive.  I had known that our transducers were not as quick as they seemingly should be.  It looks like you discovered why.  Thanks!

I know that @buzzdecafe is looking to get 0.20 out soon, but I would like to see this in quickly; either it will go in 0.20, or we'll follow soon with 0.21.

**Comment by davidchambers** [comment]
Terrific discovery, @asaf-romano!
