### ISSUE TITLE
equals can not handle circular Map objects

### ISSUE THREAD

**Issue by ZEDCWT** [ramda/ramda#1661]
``` javascript
var a = new Map
var b = new Map
a.set('x',a)
b.set('x',b)
console.log(R.equals(a,b)) //RangeError: Maximum call stack size exceeded
```

Though I don't think anyone would do like this

**Comment by CrossEye** [comment]
> Though I don't think anyone would do like this

... and perhaps stack exhaustion is an appropriate punishment.  :smiling_imp:
