### ISSUE TITLE
lift(pair) is slow

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1662]
http://goo.gl/PJcQPT

**Comment by CrossEye** [comment]
I don't know that there is anything that can be done about that.  `xprod` is a straightforward implementation of that algorithm.  It would be hard to beat, as far as I can tell.

`lift(pair)` takes a very complex function (`lift`) designed for its elegance and ability, but far from any performance tweaks and applies it to another dead-simple function (`pair`).  It would be quite surprising if it _did_ perform anything close to as well as `xprod`.

Moreover, to be as broadly useful as it is (works on all Applicative Functors), `lift` really needs to be defined in terms of `ap` and `map`.  So I don't see a great deal of room for performance improvements.

----------

I'd love to be proved wrong, of course.

**Comment by asaf-romano** [comment]
I don't think we can beat xprod, but I think we can get closer, possibly with the optimized transducers. I'll investigate that once 0.20 is out.

**Comment by CrossEye** [comment]
Great.  I'd love to see it.
