### ISSUE TITLE
R.traverse examples appear to be broken

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda#1666]
Was just playing around with [R.traverse](http://ramdajs.com/docs/#traverse) and thought I would give the first example a spin in the REPL. 

`R.traverse(Maybe.of, R.negate, [Just(1), Just(2), Just(3)]);`
//=> Just([-1, -2, -3])

First error right away is `Just is not defined`. 

So modified to:

`R.traverse(Maybe.of, R.negate, [Maybe.Just(1), Maybe.Just(2), Maybe.Just(3)]);`
//=> Just([-1, -2, -3])

Now, error is: `f is not a function`

Locally, am seeing this stack trace:

```
TypeError: f is not a function
    at _Just.map (node_modules/ramda-fantasy/src/Maybe.js:47:18)
    at node_modules/ramda/dist/ramda.js:540:44
```

Please can someone confirm this isn't just user error.

**Comment by buzzdecafe** [comment]
Yep. RF `Maybe` is foldable but not traversable. So that shouldn't work. So that example has got to go

**Comment by arcseldon** [comment]
Right. It is passing `undefined` as `f` into `map` here:

```js
// functor
_Just.prototype.map = function(f) {
  return this.of(f(this.value));
};
```

**Comment by arcseldon** [comment]
Shall i raise a PR and change the examples to something else?  Or would you prefer to fix up what's already there?

**Comment by arcseldon** [comment]
Did try with the Sanctuary Maybe (same fantasy land spec) and can confirm same outcome.

**Comment by buzzdecafe** [comment]
would be worth seeing if we can make `Maybe` traversable, but that's a bigger job than removing the example

**Comment by davidchambers** [comment]
> would be worth seeing if we can make `Maybe` traversable

plaid/sanctuary#121

**Comment by buzzdecafe** [comment]
@scott-christopher has been seeing other libraries!!!

srsly though, it feels a bit foolish to duplicate this effort.

**Comment by CrossEye** [comment]
The implementation does not look like much work; the testing looks substantial.

I have badly negleted R-F, but perhaps it's time to think about implementing our tests in terms of the [new test framework][tf] in FantasyLand.  


  [tf]: https://github.com/fantasyland/fantasy-land/pull/123

**Comment by CrossEye** [comment]
I'm assuming this broke at the conversion from `commute`/`commuteMap`.  Does anyone have a good simple example that we could put in even temporarily?  I was thinking of publishing 0.20 tonight, and it would be nice to correct this then.

**Comment by buzzdecafe** [comment]
I think this one (that is already there) is sufficient for now:

`R.traverse(Maybe.of, R.negate, [Just(1), Just(2), Just(3)]);`

**Comment by CrossEye** [comment]
But the point was that this example [does not work][re] with the current implementation.  I would rather not have a broken example in the docs if we can have a working one.

  [re]: http://goo.gl/vT9XrM

**Comment by arcseldon** [comment]
@CrossEye - Am in Japan, just going through first 100 emails since 2 am.

Well, this is the example I was playing around with (actually as something I wished to promote as perhaps being more exciting than the existing examples). But not sure you will like it?

```js
    const getPost = function (obj) {
      return Future.of({post: 'my post ' + obj.id})
    };

    const results = traverse(getPost, Future.of, [{id: 1}, {id: 2}]);
    results.fork(null, function (data
```

**Comment by arcseldon** [comment]
I was trying to come up with something that might look a bit more like everyday code.

**Comment by scott-christopher** [comment]
The example has been updated to:
```js
// Returns `Nothing` if the given divisor is `0`
safeDiv = n => d => d === 0 ? Nothing() : Just(n / d)

R.traverse(Maybe.of, safeDiv(10), [2, 4, 5]); //=> Just([5, 2.5, 2])
R.traverse(Maybe.of, safeDiv(10), [2, 0, 5]); //=> Nothing
```

**Comment by arcseldon** [comment]
Nice.  I thought these would be equivalent as follow:

```js
const getPost = function (obj) {
      return Future.of({post: 'my post ' + obj.id})
    };

    map(getPost, [{id: 1}, {id: 2}]);
    // [Future(post), Future(post)]

    const results = traverse(getPost, Future.of, [{id: 1}, {id: 2}]);
    // [Future(post), Future(post)]
```

**Comment by arcseldon** [comment]
Ok, can someone tell me why the above doesn't work?

**Comment by arcseldon** [comment]
Final post to illustrate;

 const getPost = function (obj) {
      return Future.of({post: 'my post ' + obj.id});
    };

    const res = map(getPost, [{id: 1}, {id: 2}]);
    // [Future(post), Future(post)]

    res[0].fork(null, function (res) {
      // { post: 'my post 1' }
    });

    res[1].fork(null, function (res) {
      // { post: 'my post 2' }
    });

    const res2 = traverse(getPost, Future.of, [{id: 1}, {id: 2}]);
    // Future([post, post])

    res2.fork(null, function (res) {
      // [ { id: 1 }, { id: 2 } ]
    });

















9

**Comment by scott-christopher** [comment]
@arcseldon: You've got the first two arguments of `traverse` swapped around. Can you try `traverse(Future.of, getPost, [{id: 1}, {id: 2}])`?

**Comment by arcseldon** [comment]
Thanks @scott-christopher! - I could have sworn i tried that already but hey.. like I say - going to back for a couple of days and let the dust settle :smile:   Cheers.

**Comment by arizonatribe** [comment]
Repl doesn't work for the `traverse` example. Please fix

**Comment by CrossEye** [comment]
@arizonatribe:

Do you feel like creating a PR?  It should require declaring the helper function and fully qualifying `Just`/`Nothing` with `Maybe.Just`/`Maybe.Nothing`.

**Comment by arizonatribe** [comment]
Sure I'll give it a shot later today

**Comment by arizonatribe** [comment]
#2408
