### ISSUE TITLE
Should zipObj truncate if values array is shorter than keys array?

### ISSUE THREAD

**Issue by davezuko** [ramda/ramda#1667]
Looking at the documentation for `zip` and `zipWith`:

> Creates a new list out of the two supplied by pairing up equally-positioned items from both lists. The returned list is truncated to the length of the shorter of the two input lists. Note: zip is equivalent to zipWith(function(a, b) { return [a, b] }).

However, `zipObj` will happily implicitly set keys with values of `undefined` if the keys array is longer than the values array. Example:

```js
const _keys = ['foo', 'bar', 'baz']
const _vals = [1]

const _zipped = R.zipObj(_keys, _vals)

// produces
{
  foo: 1,
  bar: undefined,
  baz: undefined,
}
```

I was going to submit a PR for this but wanted to verify because you may very well have a good reason for this that I'm just not aware of. If it is in fact unintentional, I will happily submit a followup PR.

**Comment by CrossEye** [comment]
Agreed.  It seems that, however it's implemented, this identity should hold: 

```js
 zipObj(keys, vals) ≍ pipe(zipWith(pair), fromPairs)(keys, vals)
```

Do you feel like creating a PR for this?

**Comment by davezuko** [comment]
Awesome, glad to see I'm not crazy. Yes, I will submit a PR today for this, thanks!
