### ISSUE TITLE
R.join unusable in other contexts due to instanceof check

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1670]
```console
$ node -p 'require("vm").runInNewContext("R.join(\"-\", [\"foo\", \"bar\", \"baz\"])", {R: require("ramda")})'

path/to/ramda/dist/ramda.js:7927
            throw new TypeError(toString(target) + ' does not have a method named "' + method + '"');
            ^
TypeError: ["foo", "bar", "baz"] does not have a method named "join"
```

This fails due to an `instanceof` check in [__invoker.js__][1]:

```javascript
target != null && is(Function, target[method])
```

We should update [`R.is`][2] to work like [`S.is`][3].

[1]: https://github.com/ramda/ramda/blob/v0.19.1/src/invoker.js#L34
[2]: http://ramdajs.com/docs/#is
[3]: https://github.com/plaid/sanctuary#is

**Comment by asaf-romano** [comment]
#1140

**Comment by semmel** [comment]
Yes, `instanceof` really gets into the way when working with (same-domain) iframes too.
Currently I can't use `R.invoker` in the line below if element is inside an iframe, so I have too keep good old `R.func` from Ramda v. 0.8 around:
```javascript
element.addEventListener("mousedown", R_.func("stopPropagation"), false);
```

**Comment by CrossEye** [comment]
I'm all for a fix for this.  I definitely don't like depending on something like `@@type`, but if that were a secondary mechanism after the built-in versions were handled, I could live with it.

**Comment by davidchambers** [comment]
[`S.type`][1] (and by extension `S.is`) handles built-in types as well:

```javascript
> S.type(S.Just(42))
'sanctuary/Maybe'

> S.type([1, 2, 3])
'Array'
```

For values without a `@@type` property we can fall back to `Object.prototype.toString`.


[1]: https://github.com/plaid/sanctuary#type
