### ISSUE TITLE
Implementation of R.isNotEmpty and R.isNotNil

### ISSUE THREAD

**Issue by StefanoMagrassi** [ramda/ramda#1675]
Hi guys,
I've used Ramda for a couple of projects in the last weeks and I frequently had to add the aforementioned methods/functions (isNotEmpty, isNotNil).

It wouldn't be nice to have them both in Ramda?

I searched and I didn't find any opened or closed issue on this topic: if you think they can be good features, I can make a PR asap.

**Comment by CrossEye** [comment]
I'm not excited by these.  I'd certainly be willing to entertain a PR.  But it might be an uphill battle to convince people (including me) that this minor sugar on `complement(isEmpty)` and `complement(isNil)` is worth the addition of new functions.

But please do feel free to try to convince us!

**Comment by davidchambers** [comment]
I wouldn't be happy to see these functions added. As Scott mentioned, we already have `R.complement`. We also have `R.reject(pred)` as sugar for `R.filter(R.complement(pred))`.

If you find yourself writing `R.complement(R.isNil)` many times in one file, by all means create a convenient alias. :)

**Comment by asaf-romano** [comment]
Since I have those defined in my own projects I cannot claim they're not useful (although they are not as useful as they were before ``unless``, ``when``, ``propOr`` and ``pathOr`` were introduced). But they're no more useful than, for example, ``isNilOrEmpty`` (``either(isNil, isEmpty)``), which I also have defined, or similar utilities. What's common to all those functions is that they don't really add any further abstraction above their ingredients, and their recopies  are trivial. I'd not want to see all of those added into the core library. There are just way too many of them.

**Comment by TheLudd** [comment]
I am for this but I believe ramda decided a long time ago not to go this route

**Comment by StefanoMagrassi** [comment]
I agree with you: these methods will be nothing more than "sugar" and I understand your idea to keep the core code as leaner as possible.
But also `propEq` can be seen as sugar: it's just an utility, composed with other core methods.

I don't know the previous discussions about this topic, so if the mantainers have decided to do not follow this path, also for me it's ok.

**P.S.:** I used `R.compose(R.not ...)` in order to negate isNil or isEmpty (I didn't remember that there was `R.complement`); I made some [performance tests on jsperf](http://jsperf.com/ramda-negate-isempty-isnil-with-complement-vs-not) and it seems that "composing" is a little bit faster than "complementing" (but more tests are needed to be absolutely sure).

**Comment by asaf-romano** [comment]
``R.complement`` was recently changed to be implemented as ``R.lift(R.not)`, so I'd not be surprised if that's the case (It could have been implemented as R.map(R.not), which is probably somewhere in between, in terms of performance).

**Comment by StefanoMagrassi** [comment]
@asaf-romano  got! :thumbsup:

My P.S. was only something like "F.Y.I".

@CrossEye @davidchambers if you think that adding these methods doesn't comply with Ramda philosophy, close this issue without hesitation.

**Comment by svozza** [comment]
If the performance bottleneck in your app is `R.complement(R.not)` then you've a much bigger problem than that call.
