### ISSUE TITLE
Proposal to add R.random

### ISSUE THREAD

**Issue by Risto-Stevcev** [ramda/ramda#1677]
Would you be interested in adding a helper function for a random number generator, `R.random`?

`Math.random` is limited in that you can't specify a range (it's `[0, 1)`), which is why Lodash and Underscore have their own implementation. It would be nice to have something like this in the library.

**Comment by Risto-Stevcev** [comment]
Something like this maybe?
```js
const random = R.curry((min, max, isFloat) => {
  let range = max - min
  let random = Math.random() * range + min
  return isFloat ? random : Math.floor(random)
})
```

It might also be useful to add an option to generate a CSPRNG

**Comment by asaf-romano** [comment]
👎 There are - and rightly so - dedicated libraries for this.

**Comment by Risto-Stevcev** [comment]
I guess.. but it might be useful to have a purely functional implementation like Haskell's and to make it compatible with ramda

**Comment by TheLudd** [comment]
I guess that if you want a random number generator ramda style you'll need to use the `IO` monad from ramda-fantasy. A function that returns different results for the same input is very much against ramdas philosophy.

**Comment by buzzdecafe** [comment]
> A function that returns different results for the same input is very much against ramdas philosophy. 

exactly. We actually had a random extension for a while. But it would produce repeatable results based on the initial seed value. I'm inclined to agree with @asaf-romano that this should be the domain of a separate lib.

**Comment by Risto-Stevcev** [comment]
@buzzdecafe That's along the direction I'm thinking of, but AFAIK there's no library that does this. Maybe it would be worthwhile to create one even if kept separate?

**Comment by buzzdecafe** [comment]
@Risto-Stevcev that sounds good to me (a pseudo ramda number generator?) Here's where the old extension got whacked: https://github.com/ramda/ramda/pull/590/files

**Comment by Risto-Stevcev** [comment]
It might be worthwhile to just use an existing library and wrap it accordingly, especially something so low level. Not a huge fan of reinventing the wheel.

**Comment by CrossEye** [comment]
I would have no problem reinstating that random extension the way we now have separate repos for side projects.  I think it's of reasonable quality, and it might be a good place to add other random-related functions.  Right now it's just a replacement for `Math.random` and a list `shuffle` function, but it's easy to imagine others.

We couldn't port it directly in, because when that was written, these were actual extensions, adding functions directly to Ramda.  I'm quite certain we don't want that.  But it would be easy to adjust.  And as tempting as it is, we probably don't want to call it "Ramdom" either.  :smile:.

**Comment by scott-christopher** [comment]
I raised https://github.com/ramda/ramda-fantasy/pull/92 some time ago to add a `State` type which can be used to model a pure RNG.

```js
// An example deterministic pseudorandom number generator
// see: https://en.wikipedia.org/wiki/Linear_congruential_generator
const RNG = State.get.chain(seed => {
  const newSeed = (seed * 1103515245 + 12345) & 0x7FFFFFFF;
  const randVal = (newSeed >>> 16) / 0x7FFF;
  return State.put(newSeed).map(_ => randVal);
});

// Produce a random integer from 1 to 6
const rollDie = RNG.map(n => 1 + Math.floor(n * 6));

// Produces a new RNG that returns a Tuple of two random values from the given RNG
const pair = rng =>
  rng.chain(a => rng.chain(b => State.of(Tuple(a, b))));

// eval takes a seed (123 here) to run the RNG.
// 123 could be replaced with Math.random() here.
pair(rollDie).eval(123); // Tuple(2, 5)
```

**Comment by Risto-Stevcev** [comment]
@scott-christopher Cool! I'm whipping up a quick xorshift RNG atm

**Comment by Risto-Stevcev** [comment]
I created a pure random number generator:
https://github.com/Risto-Stevcev/pure-random

I used xorshift because it was very succinct and performant

**Comment by Risto-Stevcev** [comment]
```js
> const rnd = require('pure-random')
> const IO = require('ramda-fantasy').IO
> const rollDie = IO(_ => rnd.random(rnd.genSeed(), 1, 6))
IO { fn: [Function] }
> rollDie.runIO()
Right(5)
> rollDie.runIO()
Right(1)
> rollDie.chain(R.pipe(R.tap(console.log), IO.of)).runIO()
Right(4)
Right(4)
```

**Comment by CrossEye** [comment]
But `rnd.genSeed` is not referentially transparent?  That would bother me in the Ramda ecosystem.  I would rather something that required

```js
const myRnd = rnd.genSeed(mySourceOfRandomness());
```

where `mySourceOfRandomness` might be a call to `Math.random`, some mouse-tracking tool, your own private Geiger counter, or whatever, but if `genSeed` is called twice with the same input, the PNRGs returned should have the same behavior as one another.

**Comment by Risto-Stevcev** [comment]
The seed you give to the random number generator can be any function that returns an array of 4 `Uint32` types, or in JS would be an array of four numbers in the range [0, 4294967295]. That part is referentially transparent. `genSeed` just provides a handy way of generating a seed value using `Date.now`.

In your example, `mySourceOfRandomness` would just be your own `genSeed` function that you pass in like this: `rnd.random(mySourceOfRandomness(), 1, 6)`

**Comment by CrossEye** [comment]
Right, it's `genSeed` I was objecting to.  I hadn't read through the code to realize that you could replace it with your own 4-`Uint32`-yielding function, but I assumed that you could duplicate it's ability reasonably straightforwardly.  But I would not want `genSeed`, a non-referentially transparent function in Ramda code.  We've managed so far to be able to say, "Everything is referentially transparent."  I'd hate to change that to "everything but".

Of course this is still not referentially transparent, just repeatable, and perhaps that should be revisited.

----------

I must say too, that I really like the [code we borrowed from Johannes Baagøe][jb] for seeding the function.  It accepts any parameters at all, turns them all into strings, and uses these strings to generate the seed.


  [jb]: https://github.com/ramda/ramda/commit/560052586b3e7590bcac718ed2d6e933fd640df7

**Comment by Risto-Stevcev** [comment]
You could leave `genSeed` out of the implementation. `genSeed` and `genCsSeed` are just convenient functions, but I do like  Johannes Baagøe's approach. It would be nice to just have a transparent function that can generally handle `String`s, `Number`s, and `Object`s as input and convert it to the required 4-`Uint32` seed. I think I'll change the implementation of `genSeed` to just do that instead, and then you could put in `Date.now()` or `crypto.randomBytes`, or mouse gestures, etc.

I should mention though that that code isn't referentially transparent and it doesn't quite accept any parameters at all. If no parameters are supplied, it uses `[+new Date]`, and it can only accept parameters that have a `toString` method.

I'm not sure what you mean by this:
> Of course this is still not referentially transparent, just repeatable, and perhaps that should be revisited.

**Comment by Risto-Stevcev** [comment]
Actually, I guess all the types have a `toString` method, so nvm

**Comment by CrossEye** [comment]
> I'm not sure what you mean by this:

>> Of course this is still not referentially transparent, just repeatable, and perhaps that should be revisited.

I was thinking of the older extension, but it applies equally well to this version, I suppose.

A expression is referentially transparent if it can be replaced by its value without changing the behavior of a program.  For a function that implies both no side effects and that the same input yields the same output.  But a PNRG that does not accept the current seed breaks both: The whole point is that if `a = random(); b = random();`, almost certainly, `a !== b`.  And of course this happens because of the side effect of updating the internal seed.

So, given a particular seed value, you do get a repeatable set of values, but it's not actually referentially transparent.

This could be fixed if the PNRG accepted the current seed value/structure as a parameter.  But that does make it harder to use.

**Comment by Risto-Stevcev** [comment]
If I'm understanding you correctly, you mean that it would only be truly referentially transparent if you could make the `seed` function transparent, like something that's analagous to the Haskell's System.Random?

```hs
Prelude> import System.Random
Prelude System.Random> let gen1 = mkStdGen 1234
Prelude System.Random> let result1 = fst $ random gen1
Prelude System.Random> result1
-4311284599041119727
Prelude System.Random> let result2 = fst $ random $ mkStdGen result1
Prelude System.Random> result2
4250114187885638776
Prelude System.Random> let result3 = fst $ random $ mkStdGen result2
Prelude System.Random> result3
-1756935596885184753
```

If that's what you mean, I'm totally on board with that. I don't think it makes it that much harder to use:

```js
> var roll1 = rnd.random(genSeed(1234), 1, 6)
5
> var roll2 = rnd.random(genSeed(roll1), 1, 6)
4
> var roll3 = rnd.random(genSeed(roll2), 1, 6)
1
```

If you wanted it to be more convenient you could just return it partially applied with `Date.now`:
```js
> var random = _ => rnd.random(genSeed(Date.now())
[Function]
> var roll1 = random()(1, 6)
2
> var roll2 = random()(1, 6)
6
```

**Comment by buzzdecafe** [comment]
ok to close this one? I think we can direct people to https://github.com/Risto-Stevcev/pure-random
