### ISSUE TITLE
Retain function name, when possible, in all decorators

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1678]
TLDR: http://goo.gl/0RZcN1

This is now supported in Chrome, Firefox and Node. It would vastly improve stacktraces.

**Comment by asaf-romano** [comment]
Not PRing this at this point because rumor has it @CrossEye is re-working this area.

**Comment by buzzdecafe** [comment]
i wouldn't hold off for that. if you can whip up a quick PR, then i say do it.

**Comment by davidchambers** [comment]
This would be very nice!
