### ISSUE TITLE
Add shuffle and sample

### ISSUE THREAD

**Issue by megawac** [ramda/ramda#168]
Reference implementations:

https://github.com/jashkenas/underscore/blob/master/underscore.js#L324-347

**Comment by idchlife** [comment]
Can random/sample be used now in ramda?

**Comment by kedashoe** [comment]
> Can random/sample be used now in ramda?

I don't believe there is any random number generating library associated with ramda. I've used http://chancejs.com/ before but don't really know much about it.

**Comment by idchlife** [comment]
@kedashoe not exactly number generator, but pick random element from array. Shuffle is too not in the ramda

**Comment by angeloocana** [comment]
Hi @idchlife  
I would like ramda to pick up an random element from array too.
So I created a small Math library to me https://github.com/angeloocana/ptz-math

After reading this whole issue, I think It needs an randomWith like ramda has memoizeWith.

**Comment by idchlife** [comment]
@angeloocana the funny thing, pure function can be used even for random number/element of an array. There are implementations with passing randomizer object or even "random" number (timestamp) as second argument, making function pure by definition.

Same randomizer passed - same result will be in return. It's for developer to provide randomizer, of course. But function in ramda will stay pure.

**Comment by lemongrassnginger** [comment]
https://github.com/Risto-Stevcev/pure-random might be of interest here. Stumbled across it at #1677

**Comment by lemongrassnginger** [comment]
hmm, interesting reading around this subject :) 

here's a simple Knuth Fisher-Yates shuffle function, adapted from https://bost.ocks.org/mike/shuffle/
It requires a random number generator of your choice, default is Math.random
Realised I have no idea how to go about testing whether a function produces a random output!

```
const shuffle = function (random, list) {
	// default random function
	random = R.defaultTo(Math.random, random);

	let m = list.length, t, i,
		// work on clone of the list
		listout = R.clone(list);

	// work from end to beginning of the list
	// 'shuffled' elements start filling from the back
	while (m) {
		// select index of a non-shuffled element
		i = Math.floor(random() * m--);
		// shuffle the elements by swapping them
		t = listout[m];
		listout[m] = listout[i];
		listout[i] = t;
	}
	return listout;
}

// demo
let aLetters = ["a", "b", "c", "d", "e"],
shuffleLetters = () => console.log(shuffle(null, aLetters));
// repeat the output
R.times(shuffleLetters, 10)
```

example output
```
["d","e","b","c","a"]
["b","d","e","c","a"]
["a","d","b","e","c"]
["c","d","a","b","e"]
["d","c","a","b","e"]
["b","a","c","d","e"]
["e","c","a","d","b"]
["b","e","a","d","c"]
["c","e","d","a","b"]
["e","d","b","a","c"]
```

**Comment by lemongrassnginger** [comment]
ahah, just come across the random shuffle extension that was removed at https://github.com/ramda/ramda/commit/992aff2c0ad3fdb57a8289616c839acafcfb3222

```
const shuffler = R.curry(function(random, list) {
         var idx = -1;
         var len = list.length;
         var position;
         var result = [];
         while (++idx < len) {
             position = Math.floor((idx + 1) * random());
             result[idx] = result[position];
             result[position] = list[idx];
         }
         return result;
     }),
shuffle = shuffler(Math.random);

shuffle(R.range(0, 5))
```
