### ISSUE TITLE
adjustBy?

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#1681]
It's arguably a common task to update an array value by predicate.
We have a close cousin `adjust` function but it lacks a predicate search.
So I do it like this:

``` js
let {adjust, curry, findIndex, flip, merge, whereEq} = require("ramda");

let adjustBy = curry((pred, adjustFn, array) => {
  let i = findIndex(pred, array);
  if (i >= 0) {
    return adjust(adjustFn, i, array);
  } else {
    return array;
  }
});

let data = [
  {id: "2", name: "bar"},
  {id: "1", name: "foo"},
  {id: "3", name: "bazz"},
];
```

``` js
// found: apply fn to data
console.log(
  adjustBy(whereEq({id: "1"}), flip(merge)({name: "FOO"}), data)
);
```

```
[ { id: '2', name: 'bar' },
  { id: '1', name: 'FOO' },
  { id: '3', name: 'bazz' } ]
```

``` js
// not found: keep original data
console.log(
  adjustBy(whereEq({id: "9"}), flip(merge)({name: "BOO"}), data)
);
```

```
[ { id: '2', name: 'bar' },
  { id: '1', name: 'foo' },
  { id: '3', name: 'bazz' } ]
```

Is there an easier way to achieve this (with existing Ramda toolkit)?
Does it deserve to be included in library?

P.S.
Any reason why `findIndex` returns `-1` but `findLast` returns `undefined` for not-found cases?
Another legacy?

**Comment by davidchambers** [comment]
`R.map(R.when(R.propEq('id', '1'), R.assoc('name', 'FOO')))` should do the trick, @ivan-kleshnin.

**Comment by ivan-kleshnin** [comment]
@davidchambers your example will update every item while mine will update only fist.

**Comment by davidchambers** [comment]
Ah, I see. I assumed `id` to be unique.

**Comment by ivan-kleshnin** [comment]
I dunno. Maybe your example is ok for most cases.
Thanks for the `where` use-case. Now I'm willing to use this function :smile:

**Comment by polytypic** [comment]
See also issue #2302

**Comment by CrossEye** [comment]
Wow had this one been dropped!  Thanks @polytypic.  Closing in favor of the one under current discussion.
