### ISSUE TITLE
R.gt and R.lt arguments are backwards

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1682]
```js
R.pipe(R.length, R.gt(2))('hello') // false
R.pipe(R.length, R.lt(2))('hello') // true
```

Its pretty much impossible to read that and intuitively guess the correct answer...

**Comment by TheLudd** [comment]
Has been discussed, among other places, here: #1497 #175 #388

**Comment by CrossEye** [comment]
And I think we did come to some rough consensus in #1497, but no one has done anything about it....  hmm.

**Comment by Bradcomp** [comment]
@CrossEye I would be interested in adding the isGT, isLT, etc. functions per #1497 if there is still an interest in doing that.  Seems like it would involve adding a significant number of functions to the already wide Ramda API though.  Is that a concern?

**Comment by ccorcos** [comment]
Ah, lets continue in https://github.com/ramda/ramda/issues/1497

**Comment by CrossEye** [comment]
@Bradcomp: I think it is a concern, but if it solves this longstanding issue it would be well worth it.
