### ISSUE TITLE
[question] should mapping over object preserve the protoype?

### ISSUE THREAD

**Issue by davidchase** [ramda/ramda#1684]
Given:
```js
function Box (x) {
  if (!(this instanceof Box)) return new Box(x);
  this.value = x;
}

Box.prototype.toString = function(){
  return `Box(${this.value})`;
};


map(add(10))(Box(10)) // {"value": 20}
```

http://goo.gl/jgFyfS

however adding `Object.create(functor)` to the reduce method in the `case [object Object]`

```js
const _map = curry(function(fn, functor){
 switch (Object.prototype.toString.call(functor)) {
    case '[object Function]':
      return curryN(functor.length, function() {
        return fn.call(this, functor.apply(this, arguments));
      });
    case '[object Object]':
      return reduce(function(acc, key) {
        acc[key] = fn(functor[key]);
        return acc;
      }, Object.create(functor), keys(functor));
    default:
      return map(fn, functor);
  }
});

_map(add(10))(Box(10)) // Box(20) the toString works.. yay
```

http://goo.gl/zdEypT

 thoughts?

**Comment by davidchambers** [comment]
:thumbsdown: from me. `R.map` operates on functors, such as a values of type [`StrMap a`][1], not on arbitrary objects. The correct solution, in my view, is to implement `Box.prototype.map` if you wish Box to be a functor.


[1]: https://github.com/plaid/sanctuary-def/pull/33

**Comment by davidchase** [comment]
hmm interesting perspective @davidchambers the reason this came up is that i was play around with coyo from @DrBoolean and wanted to use a more general `map` https://gist.github.com/DrBoolean/4f74b0f096f6d8e790b4#file-coyo_uses-js-L12-L14 so i used ramda's map

from what i understood was with `coyo` i did not need to have `Box` be functor, since you can make any type a functor, therefore `map` was not implemented...

i realize this is out of scope for ramda and i thought i would ask... 

thanks again for the input

**Comment by DrBoolean** [comment]
Looks like what we really want here is derived instances. Haskell will figure out the functor instance based on polymorphic variables inside your type. I think there was some work put in on the fantasyland side at some point.

**Comment by CrossEye** [comment]
A simple example of why not would be with [multiple properties][re].

```js
const Box = (function() {
  var serialNbr = 0;
  return function Box (x) {
    if (!(this instanceof Box)) return new Box(x);
    this.value = x;
    this.serialNbr = 'box#' + ++serialNbr;
  }
}());

Box.prototype.toString = function(){
  return `Box(${this.value} (${this.serialNbr}))`;
};

const box = Box(42); //=> Box(42 (box#1))
_map(add(10))(box); //=> Box(52 (10box#1))
```

But note that although Ramda's `map` may not work as expected if your `map` function isn't exactly functor-like, that won't stop us from calling it.  Ramda simply checks for the existence of a `map` method on the last parameter (if it's not a list) and calls it if it's there.
  [re]: http://goo.gl/mxNq2M

**Comment by davidchase** [comment]
@CrossEye thanks for your input as well... i wasnt sure that this would go through as a good idea... it was more part of learning the `coyoneda` and its application in javascript

I happened to stumble along a small issue where `toString` was not working when applying the `map` fn and thought I would ask about on here... maybe gitter channel would have been more appropriate.

**Comment by davidchambers** [comment]
> maybe gitter channel would have been more appropriate

I don't think anyone here minds where questions are posed (although GitHub issues are easier to reference than Gitter posts). Thanks for taking the time to write this proposal.
