### ISSUE TITLE
Combine functions (not compose)

### ISSUE THREAD

**Issue by deathmood** [ramda/ramda#1685]
Is there any function that can make a function that calls list of functions on given arguments and returns array of called functions return values? I know its a bit verbose, but basically I would like to have smth like this:

```js
function combine() {
  var functions = arguments
  return function () {
    var params = arguments
    return R.map(function (f) {
      return f.apply(null, params)
    }, functions)
  }
}
```

Of course I can write by my own. But maybe there is already a solution?

**Comment by deathmood** [comment]
Ooh(( I found solution

```js
function f1() {}
function f2() {}

var ff = compose(
  R.op([f1, f2]),
  Array
)
```

But maybe there is a better way?

**Comment by deathmood** [comment]
Ok. I've found it --- it is `R.juxt`

```js
function f1() {}
function f2() {}

var ff = R.juxt([f1, f2])
```

But how could I guess? What does `juxt` mean? It is really difficult find thing you're looking for in these docs with such function names(((

**Comment by davidchambers** [comment]
[`juxt`][1] comes from Clojure, and is short for juxtaposition, apparently.

We could do a better job of assisting users in getting from _I'd like to do X_ to _I should use Y_.


[1]: https://clojuredocs.org/clojure.core/juxt

**Comment by CrossEye** [comment]
> We could do a better job of assisting users in getting from _I'd like to do X_ to _I should use Y_.

I'm quite certain that we could.  But I'm not quite sure exactly _how_.  Anyone have a suggestion?

**Comment by Lube** [comment]
A hoogle like solutions would be a godsend for me.

**Comment by jgoux** [comment]
> We could do a better job of assisting users in getting from I'd like to do X to I should use Y.

I find this table from RxJS quite helpful to reduce the list of choices : https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/categories.md

**Comment by CrossEye** [comment]
I agree.  That would be a great start.  Is there anyone who wants to take a swing at this with Ramda?

**Comment by sotojuan** [comment]
This is something I'd love to do, but I need time to get acquainted with most Ramda functions as I'm a casual/semi-casual user. Would this be done in a PR or a separate repository? I'd like as much community involvement as possible.

**Comment by CrossEye** [comment]
See the Wiki Page [What Function Should I Use?][wf] by @svozza.  It's still a work in progress, and will need some more prominent placement, but I believe it's a great leap toward this.


  [wf]: https://github.com/ramda/ramda/wiki/What-Function-Should-I-Use%3F
