### ISSUE TITLE
Homepage: Wrong link to "Introducing Ramda by Buzz de Cafe"

### ISSUE THREAD

**Issue by Hocdoc** [ramda/ramda#1686]
On the ramda homepage http://ramdajs.com/0.19.1/index.html the link "Introducing Ramda by Buzz de Cafe" doesn't work. 

You have to remove the last slash: 
http://buzzdecafe.github.io/code/2014/05/16/introducing-ramda instead of http://buzzdecafe.github.io/code/2014/05/16/introducing-ramda/

**Comment by buzzdecafe** [comment]
fixed in https://github.com/ramda/ramda/pull/1671

will be updated at next publish, thanks
