### ISSUE TITLE
ap1? perFunction? applyMap? I'm terrible at names.

### ISSUE THREAD

**Issue by krainboltgreene** [ramda/ramda#1687]
So recently I've found myself, no less than twice on a project, wanting a specific ramda function that either doesn't exist or isn't obvious. Here's the signature (I'm new to writing these):

```
([* -> n]) -> Anything -> [Anything, ...]
```

The description:

Takes a list of functions and an argument, and applies the argument to each function, returning a list of the return values.

Here's an example:

``` javascript
const record = {
  "id": "1",
  "type": "activities",
  "attributes": {
    "summary": "JSON API paints my bikeshed!"
  },
  "relationships": {
    "actor": {,
      "data": {
        "type": "accounts",
        "id": "2"
      }
    }
  }
}
const normalize = pipe(
  functionsMap(
    [
      omit(["attributes", "relationships"]),
      props(["attributes", "relationships"])
    ]
  ),
  mergeAll
)

normalize(record) // {id, type, summary, actor}
```

I've implemented it here:

``` javascript
const perFunction = (functions) => pipe(of, ap(functions))
```

I know it looks small, but this took me about 4-5 hours, split over a few days, to come up with sensibly.

**Comment by CrossEye** [comment]
I think you're [looking for][re] the function [`juxt`][ju], whose name came from Clojure, and seems to be short for "juxtaposition".  But no one can discover it.  If you have a better name, we'd love to hear it.


  [ju]: http://ramdajs.com/0.19.1/docs/#juxt
  [re]: http://goo.gl/0S7Wim

**Comment by krainboltgreene** [comment]
The funny thing is I actually found juxt, and tried it, but couldn't get it to do what I thought I wanted. I'm guessing I didn't understand the behavior until I at least found `ap`.

**Comment by CrossEye** [comment]
Note that the sig for this one is tricky because of some ambiguity of parentheses being both grouping and tuples.  (I think we should really think about using `<val1, val2, val3>` for tuples instead.)  But essentially `juxt` accepts a list of functions, returns a new function that will return a list formed by applying each of those functions to the newly supplied arguments.

```js
juxt([fn1, fn2, fn3, ...)(arg1, arg2, ...);
//=> [fn1(arg1, arg2, ...), fn2(arg1, arg2, ...), fn3(arg1, arg2, ...), ...)]
```

So the resulting function does not take its arguments as a list, just as normal function arguments.
