### ISSUE TITLE
Why don't we have the Haskell's groupBy function?

### ISSUE THREAD

**Issue by kahless** [ramda/ramda#1688]
Use case
========

I have an array of objects. Each object contains a parsed street address like this one:
```
{
   country: 'Russia',
   house_number: '5/6',
   road: "Tverskaya Street",
   ...
   theatre: "Театр им. М.Н. Ермоловой"
}
```

The problem is that some addresses are too specific. For example I don't need to know about the theatre that is located there. From this point of view my array contains duplicates (theatre, bakery, hotel and others that are located in the same building). And I need to replace this duplicates with one, least specific address, with the same house number but without unwanted information about theatre and others. There is always one such address for all the duplicates.

In Haskell we have a wonderful groupBy function that can help me locate a sequence of duplicates and reduce them to one address by a predicate. But Ramda's groupBy returns an object so I lose the original order. But order is important because addresses were sorted by relevance.

I am sorry for my english and possibly excessive verbosity.

**Comment by TheLudd** [comment]
Perhaps these functions will come in handy?
http://ramdajs.com/0.19.1/docs/#uniqBy
http://ramdajs.com/0.19.1/docs/#uniqWith

**Comment by kahless** [comment]
I tried it, but these functions won't let me choose a certain address that will be in place of the duplicates. It would be just the first one. But in my case the desired address usually is the last duplicate (but it's position is not guaranteed).

**Comment by kahless** [comment]
This is the missing groupBy function from Haskell:
http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:groupBy

**Comment by TheLudd** [comment]
It seems to me to have the same signature as `uniqWith`

**Comment by kahless** [comment]
Nop. In Haskell it returns a list of lists. In Ramda uniqWith returns just an array:
```
Ramda's uniqWith  — (a, a → Boolean) -> [a] -> [a]
Haskell's groupBy — (a -> a -> Bool) -> [a] -> [[a]]
```

For example:
```
groupBy (==) "Mississippi"
   -- Returns ["M","i","ss","i","ss","i","pp","i"]
R.uniqWith(R.eq, ['M','i','s','s','i','s','s','i','p','p','i'])
   // Returns ["M", "i", "s", "p"]
```

**Comment by CrossEye** [comment]
I couldn't find where I'd written something like this before.  But I know that I have done so.  I think of this as control-break logic, from a long-ago course on report generation.  I'm not sure whether it belongs in Ramda itself or in the Cookbook, but we definitely should capture this somewhere.

Here is [an implementation][re] that come to mind immediately:

```js
var groupOn = R.curry((pred, ls) => 
  R.addIndex(R.reduce)((acc, elem, idx) => 
    idx === 0 || !pred(ls[idx - 1], elem)
       ? R.append([elem], acc)
       : R.append(R.append(elem, R.last(acc)), R.init(acc))
    , [], ls)
); 

map(join(''), groupOn(R.equals, R.split('', 'Mississippi')));
//=> ["M", "i", "ss", "i", "ss", "i", "pp", "i"]
```

There are probably many better ways to do it.

What do people think?  Does something like this belong in the library, or the Cookbook?  Is there a good name for it?

  [re]: http://goo.gl/X1e4sZ

**Comment by davidchambers** [comment]
> ```
> groupBy (==) "Mississippi"
>    -- Returns ["M","i","ss","i","ss","i","pp","i"]
> ```

This function seems very useful to me. I think Ramda should provide it. Thanks for the suggestion, @kahless!

As for the name, I'd suggest `groupBy` were it available. `clumpBy`, perhaps?

**Comment by asaf-romano** [comment]
This is very useful indeed.

``nestBy`` maybe?

**Comment by benperez** [comment]
`collectBy`? Is anybody else interested in putting together a PR for this? If not I'll take it.

**Comment by CrossEye** [comment]
@benperez: Please feel free.  I'm on something else very time-consuming, and brain-draining.

As to the name, please keep in mind a standard we're at least mostly keeping to: https://github.com/ramda/ramda/issues/65#issuecomment-46786430.

**Comment by benperez** [comment]
Fair enough, I'll leave it as `*With` until somebody comes up with a good name.

**Comment by buzzdecafe** [comment]
`bunch`?

**Comment by svozza** [comment]
`cluster`?

**Comment by benperez** [comment]
Couldn't it technically be called `groupWith`? According to the comment that @CrossEye linked to:
> *By focuses on a single list item, generates a key for it. *With is the one that knows how to do the comparison between two different items.

By this logic, `R.groupBy` accepts a function which operates on a single argument, while `R.groupWith` would accept a function that compares two items for equality.

**Comment by buzzdecafe** [comment]
`groupWith` sounds good to me

**Comment by CrossEye** [comment]
Yes, I was going to suggest `groupWith` when I saw `cluster`, which sounded better to me.  But I don't have a strong feeling either way.

**Comment by buzzdecafe** [comment]
`cluster` too loaded with negative connotations to my ear.

**Comment by davidchambers** [comment]
The problem with `groupBy`/`groupWith` is that they would return values of different types. I believe our other `*By`/`*With` pairs differ only in terms of their input types.

**Comment by CrossEye** [comment]
I was originally going to write the same thing, but could only think of one instance.  And in fact:

```js
> filter(s => /By$/.test(s), keys(R));
["countBy","eqBy","groupBy","indexBy","maxBy","minBy","pickBy","sortBy","uniqBy"]
> filter(s => /With$/.test(s), keys(R));
["differenceWith","dropRepeatsWith","intersectionWith","mergeWith","symmetricDifferenceWith",
  "unionWith","uniqWith","useWith","zipWith"]
```

So the only place where we have both is `uniqBy`/`uniqWith`.  That's probably not a particularly strong basis for generalization.  Nonetheless, it might still be a good habit to maintain.
