### ISSUE TITLE
until

### ISSUE THREAD

**Issue by iofjuupasli** [ramda/ramda#1690]
Like `R.unless` but applies function until predicate is satisfied and passes new values to predicate each step.

Or `while` which is the same but with `complement` pred

```js
R.until(
    R.gt(R.__, 100),
    R.multiply(2)
)(1) === 128
```

**Comment by buzzdecafe** [comment]
What do you see as the use case for this? It feels a little imperative, like `while` as you said. 

What is the type of `until`? Looks like

`(a -> Boolean) -> (a -> a) -> a -> a`

is that correct?

**Comment by CrossEye** [comment]
... and would we just assume _caveat emptor_ for 

```js
R.until(
    R.gt(R.__, 100),
    R.identity
); // this might take a while...
```

?

**Comment by iofjuupasli** [comment]
> What do you see as the use case for this?

Use cases similar to native `while` and `R.unfold`. In comparison with `unfold` - it seems weird to do predicate and modificator in one function with mixed type `[a] | bool`.

Example I've provided is similar to what I have now in my code.

> `(a -> Boolean) -> (a -> a) -> a -> a`

Yes

> and would we just assume caveat emptor for

Yeah, actually I just ran with it. I don't know how to reliably solve this. But it obvious when running (if pred doesn't depend on externals that can be very different depending on use cases), it just hangs :)

Also `unfold` have this.

**Comment by iofjuupasli** [comment]
> It feels a little imperative

I don't see anything imperative here

**Comment by buzzdecafe** [comment]
well, i'm persuaded that this is worth a look. I'm pretty sure we can't guard against the (halting) problem @CrossEye pointed out.

**Comment by CrossEye** [comment]
Agreed.  This could be useful.

@iofjuupasli: Do you have an implementation in mind?

**Comment by scott-christopher** [comment]
This could be handy for implementing a poor-man's tail call via trampolining with an `Either` type.

```js
const until = curry(function until(pred, step, init) {
  var val = init;
  while (!pred(val)) {
    val = step(val);
  }
  return val;
});
```

`Left` signifies the function should terminate, while `Right` signifies there is more recursion necessary.
```js
// Simple recursive factorial
//:: Either Int [Int, Int] -> Either Int [Int, Int]
const factE = chain(([n, x]) =>
  n === 0 ? S.Left(x)
          : S.Right([n - 1, n * x]))

// `S.either(identity, identity)` is used to extract the value from the final `Left`
const fact = n =>
  S.either(identity, identity, until(S.either(T, F), factE, S.Right([n, 1])));

fact(4); // 24
```

**Comment by davidchambers** [comment]
Very interesting, @scott-christopher!

[`S.isLeft`][1] could be used in place of `S.either(T, F)` (though it's thrilling to see that `isLeft` can be defined so simply in terms of `either`).


[1]: http://sanctuary.js.org/#isLeft

**Comment by scott-christopher** [comment]
> `S.isLeft` could be used in place of `S.either(T, F)`

Ah, I somehow missed that and thought it only existed as a property of the instance. :)

It reads much nicer as `until(S.isLeft, ...)` too.

**Comment by scott-christopher** [comment]
We could potentially include a stack-safe `trampoline` function without depending on an external `Either` type too. This would just require the use of some continuations to take the place of `Left` and `Right`.

```js
function trampoline(fn, initVal) {
  const done = val => (l, r) => l(val);
  const next = val => (l, r) => r(val);
  const step = e => e(void 0, a => fn(done, next, a));
  const isDone = e => e(T, F);
  
  return until(isDone, step, next(initVal))(identity, void 0);
}
```

Which could be used like so:
```js
const sum = list => trampoline(
  (done, next, [sum, xs]) => isEmpty(xs) ? done(sum) : next([sum + head(xs), tail(xs)]),
  [0, list]
);
```

Alternatively, the continuations could be exposed via `left`, `right` and `choice`, rather than passing them as arguments to the trampolining function.
```js
const left  = val => (l, r) => l(val);
const right = val => (l, r) => r(val);
const choice = curry((whenL, whenR, e) => e(whenL, whenR));

const trampoline = (fn, initVal) =>
  until(choice(T, F), choice(void 0, fn), right(initVal))(identity, void 0);

const sum = list => trampoline(
  ([sum, xs]) => isEmpty(xs) ? left(sum) : right([sum + head(xs), tail(xs)]),
  [0, list]
);
```
