### ISSUE TITLE
About `equals` implementation

### ISSUE THREAD

**Issue by ascartabelli** [ramda/ramda#1691]
Recently I've been thinking again about implementing an `equals` function in my own library and I had a look at how others managed some "edge" cases.
Ramda's implementation draws a very clear line [here](https://github.com/ramda/ramda/blob/v0.19.1/src/internal/_equals.js#L13) by assuming that different types cannot be "equals".
I was wondering what do you think about a case similar to this one:
```javascript
var a = [1, 2, 3];
var b = Int32Array.from(a);

R.equals(a, b); // => false
```
Is it an oversight or by design in your reasoning?

**Comment by CrossEye** [comment]
It would be quite a challenge to imagine two distinct types that we would want to treat precisely the same.  I think the basic idea for `equals` is that for any `f`

`x ≍ y` should imply `f(x) ≍ f(y)`.

That wouldn't be true for your `a` and `b`.  Imagine `f = ls => {ls.push('foo'); return ls}` or many other ways in which their behaviors would differ.

**Comment by ascartabelli** [comment]
@CrossEye, not sure I'm getting your point. You say that: 

> the basic idea for `equals` is that for any `f` `x ≍ y` should imply `f(x) ≍ f(y)`

And, of course, different types with different interfaces couldn't satisfy your assumption.
But we can also use as an example two different types sharing the same `TypedArray` interface:
```javascript
var a = Int32Array.of(1, 2, 3);
var b = Float32Array.of(1, 2, 3);

R.equals(a, b); // => false
```
Still thinking about your assumption and if it's the correct way to think about `equals` though.

**Comment by CrossEye** [comment]
But we can also use as an example two different types sharing the same `TypedArray` interface:

```javascript
var a = Int32Array.of(1, 2, 3);
var b = Float32Array.of(1, 2, 3);
```

Right, and now run this:

```js
const f = x => {x.set([6.28], 2); return x};
f(a); //=> Int32Array.of(1, 2, 6)
f(b); //=> Float32Array.of(1, 2, 6.28000020980835)
```

They end up with very different behaviors.  Ramda's notion of `equals` is one of substitutability.  You should should be able to substitute one for the other without changing system behavior.  That's one of the reasons that key-ordering issues have been such a thorn in our side.

Because of reasons like the above, even though they're both `TypedArray`s, with the same initial values, `a` and `b` are not substitutable for one another.

**Comment by ascartabelli** [comment]
> Right, and now run this: [...]

Again, of course, your initial assumption isn't satisfied and I think it's clear that the answer to my original question is "by design".
And, don't get me wrong, I respect your take on this and my original post was only a means to understand your reasoning behind it.

Leaving JavaScript aside I'm more inclined to think of `equals` in another way though, e.g. in Scala:
```scala
val a = List[Int](1, 2, 3)
val b = Seq[Int](1, 2, 3)
val c = List[Double](1, 2, 3)

a.equals(b) // => true
a.equals(c) // => true
```
Still not sure if it's worth it to implement it in JavaScript following my point of view.

Out of curiosity, another interesting take is the one in Facebook's `Immutable` in their [`is` function](https://github.com/facebook/immutable-js/blob/master/src/is.js#L64), also used in the `equals` method for types implementing the [Iterable](http://facebook.github.io/immutable-js/docs/#/Iterable/equals) interface.
 
Thanks for explaining your point of view.

**Comment by CrossEye** [comment]
I would be a lot more sympathetic to such a point of view in `Clojure` or `Immutable.js` (possibly `Scala` too; I don't really know it) where types are immutable by default.

But while Ramda does not mutate our data, it operates in the normal JS world where we might mutate it at any time.  So it's much harder to see the fact that two types which might currently hold the same shape and contents as a true equals if the same user modification to them would change them differently.

I do understand the rationale for a different point of view.  I might implement it in a project library in which I am steadfastly refusing to mutate my values.  But for a library like Ramda that has to live in the wider world of Javascript mutation, I don't think it's feasible.

**Comment by ascartabelli** [comment]
>  But for a library like Ramda that has to live in the wider world of Javascript mutation, I don't think it's feasible

Agreed, or at least I think I agree as I periodically come back to think about it.
Point is that in my head `equals` should be about equivalence, while your implementation, like others, seems more akin to the concept of equality.
It's fair to think like that, especially in JavaScript as the `strict equality` operator behaves more like an identity operator, but the equivalence concept is missing (and thus I find the function name misleading).

Having said that I'm well aware that we can discuss a lot about what "equivalence" really means.

Well, thanks again for your time: you've given me some food for thought.

**Comment by CrossEye** [comment]
> Well, thanks again for your time: you've given me some food for thought.

Thank you too.  It's a very interesting question.  And I honestly wish there was something else that seemed to make sense for Ramda, because I'm not thrilled with this.
