### ISSUE TITLE
Discovering Functions

### ISSUE THREAD

**Issue by svozza** [ramda/ramda#1695]
In #1578 and in the Gitter channel it has been suggested that Ramda should have a document similar[ to the one in RxJs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-instance.md) that aids the discoverability of the various functions in the library. I decided to make a start on it tonight. I've done a selection of the functions (I don't think we should include every function in the library) and I thought it might make sense to iterate on the list in an issue first before putting it on the wiki. ~~I'll carry on this work tomorrow but if anyone wants to add to it while I'm asleep I think that would be great. ;)~~
# Which function to use?

| Type | Action | Function |
| --- | --- | --- |
| List | I want to change every value | [map](http://ramdajs.com/0.19.0/docs/#map) |
|  | I want to pull a property off each value | [pluck](http://ramdajs.com/0.19.0/docs/#pluck) |
|  | I want to select values based on custom logic | [filter](http://ramdajs.com/0.19.0/docs/#filter) |
|  | I want to select values from a specific index range | [slice](http://ramdajs.com/0.19.0/docs/#slice) |
|  | I want to select values from the start | [take](http://ramdajs.com/0.19.0/docs/#take) |
|  | I want to select values from the start based on custom logic | [takeWhile](http://ramdajs.com/0.19.0/docs/#takeWhile) |
|  | I want to select values from the end | [takeLast](http://ramdajs.com/0.19.0/docs/#takeLast) |
|  | I want to select values from the end based on custom logic | [takeLastWhile](http://ramdajs.com/0.19.0/docs/#takeLastWhile) |
|  | I want to remove the first value | [init](http://ramdajs.com/0.19.0/docs/#init) |
|  | I want to remove specific values | [without](http://ramdajs.com/0.19.0/docs/#without) |
|  | I want to remove values based on custom logic | [reject](http://ramdajs.com/0.19.0/docs/#reject) |
|  | I want to remove all duplicates | [uniq](http://ramdajs.com/0.19.0/docs/#uniq) |
|  | I want to remove all duplicates based on custom logic | [uniqWith](http://ramdajs.com/0.19.0/docs/#uniqWith) |
|  | I want to remove values from the start | [drop](http://ramdajs.com/0.19.0/docs/#drop) |
|  | I want to remove values from the start based on custom logic | [dropWhile](http://ramdajs.com/0.19.0/docs/#dropWhile) |
|  | I want to remove values from the end | [dropLast](http://ramdajs.com/0.19.0/docs/#dropLast) |
|  | I want to remove values from the end based on custom logic | [dropLastWhile](http://ramdajs.com/0.19.0/docs/#dropLastWhile) |
|  | I want to compute the sum | [sum](http://ramdajs.com/0.19.0/docs/#sum) |
|  | I want to compute the average | [mean](http://ramdajs.com/0.19.0/docs/#mean) |
|  | I want to compute the median | [median](http://ramdajs.com/0.19.0/docs/#median) |
|  | I want to compute based on custom logic and only output the final value | [reduce](http://ramdajs.com/0.19.0/docs/#reduce) / [reduceRight](http://ramdajs.com/0.19.0/docs/#reduceRight) |
|  | I want to compute based on custom logic and output the values as they are calculated | [scan](http://ramdajs.com/0.19.0/docs/#scan) |
|  | I want to take the first value | [head](http://ramdajs.com/0.19.0/docs/#head) |
|  | I want to take the last value | [last](http://ramdajs.com/0.19.0/docs/#last) |
|  | I want to take a value from a specific index | [nth](http://ramdajs.com/0.19.0/docs/#nth) |
|  | I want to take the first occurrence of a value based on custom logic | [find](http://ramdajs.com/0.19.0/docs/#find) |
|  | I want to take the last occurrence of a value based on custom logic | [findLast](http://ramdajs.com/0.19.0/docs/#findLast) |
|  | I want to know where the first occurrence of a value is | [indexOf](http://ramdajs.com/0.19.0/docs/#indexOf) |
|  | I want to know where the first occurrence of a value is based on custom logic | [findIndex](http://ramdajs.com/0.19.0/docs/#findIndex) |
|  | I want to know where the last occurrence of a value is | [lastIndexOf](http://ramdajs.com/0.19.0/docs/#lastIndexOf) |
|  | I want to know where the last occurrence of a value is based on custom logic | [findLastIndex](http://ramdajs.com/0.19.0/docs/#findLastIndex) |
|  | I want to know if a condition is satisfied by all of the values | [all](http://ramdajs.com/0.19.0/docs/#all) |
|  | I want to know if a condition is satisfied by any of the values | [any](http://ramdajs.com/0.19.0/docs/#any) |
|  | I want to know if a condition is satisfied by none of the values | [none](http://ramdajs.com/0.19.0/docs/#none) |
|  | I want to know if all values are unique | [allUniq](http://ramdajs.com/0.19.0/docs/#allUniq) |
|  | I want to replace a value at a specific index | [update](http://ramdajs.com/0.19.0/docs/#update) |
|  | I want to replace a value at a specific index based on custom logic | [adjust](http://ramdajs.com/0.19.0/docs/#adjust) / [lensPath](http://ramdajs.com/0.19.0/docs/#lensPath) |
|  | I want to add a value at the start | [prepend](http://ramdajs.com/0.19.0/docs/#prepend) |
|  | I want to add a value at the end | [append](http://ramdajs.com/0.19.0/docs/#append) |
|  | I want to add a value at a specific index | [insert](http://ramdajs.com/0.19.0/docs/#insert) |
|  | I want to add multiple values at a specific index | [insertAll](http://ramdajs.com/0.19.0/docs/#insertAll) |
|  | I want to group values based on custom logic | [groupBy](http://ramdajs.com/0.19.0/docs/#groupBy) |
|  | I want to know how many values it contains | [length](http://ramdajs.com/0.19.0/docs/#length) |
|  | I want a specific range of integer values | [range](http://ramdajs.com/0.19.0/docs/#range) |
|  | I want to split at a specific index | [splitAt](http://ramdajs.com/0.19.0/docs/#splitAt) |
|  | I want to split based on custom logic | [splitBy](http://ramdajs.com/0.19.0/docs/#splitBy) |
|  | I want to split into chunks of a specific length | [splitEvery](http://ramdajs.com/0.19.0/docs/#splitEvery) |
|  | I want to sort | [sort](http://ramdajs.com/0.19.0/docs/#sort) |
|  | I want to sort based on custom logic | [sortBy](http://ramdajs.com/0.19.0/docs/#sortBy) |
|  | I want to concatenate two lists | [concat](http://ramdajs.com/0.19.0/docs/#concat) |
|  | I want to find the common values in two lists | [intersection](http://ramdajs.com/0.19.0/docs/#intersection) |
|  | I want to find the common values in two lists based on custom logic | [intersectionWith](http://ramdajs.com/0.19.0/docs/#intersectionWith) |
|  | I want to find the distinct values compared to another list | [difference](http://ramdajs.com/0.19.0/docs/#difference) |
|  | I want to find the distinct values compared to another list based on custom logic | [differenceWith](http://ramdajs.com/0.19.0/docs/#differenceWith) |
|  | I want to combine two lists into a list of unique values | [union](http://ramdajs.com/0.19.0/docs/#union) |
|  | I want to combine two lists into a list of unique values based on custom logic | [unionWith](http://ramdajs.com/0.19.0/docs/#unionWith) |
|  | I want to combine two lists into a list of pairs | [zip](http://ramdajs.com/0.19.0/docs/#zip) |
|  | I want to combine two lists into a list of pairs based on custom logic | [zipWith](http://ramdajs.com/0.19.0/docs/#zipWith) |
| Object | I want to change every value | [map](http://ramdajs.com/0.19.0/docs/#map) / [mapObjIndexed](http://ramdajs.com/0.19.0/docs/#mapObjIndexed) |
|  | I want to select a specific key | [prop](http://ramdajs.com/0.19.0/docs/#prop) / [path](http://ramdajs.com/0.19.0/docs/#path) |
|  | I want to select a specific key and return a default if it is not found | [propOr](http://ramdajs.com/0.19.0/docs/#propOr) / [pathOr](http://ramdajs.com/0.19.0/docs/#pathOr) |
|  | I want to select specific keys | [pick](http://ramdajs.com/0.19.0/docs/#pick) / [pickAll](http://ramdajs.com/0.19.0/docs/#pickAll) |
|  | I want to select keys based on custom logic | [filter](http://ramdajs.com/0.19.0/docs/#filter) / [pickBy](http://ramdajs.com/0.19.0/docs/#pickBy) |
|  | I want to remove a specific key | [dissoc](http://ramdajs.com/0.19.0/docs/#dissoc) / [dissocPath](http://ramdajs.com/0.19.0/docs/#dissocPath) |
|  | I want to remove specific keys | [omit](http://ramdajs.com/0.19.0/docs/#omit) |
|  | I want to remove specific keys based on custom logic | [reject](http://ramdajs.com/0.19.0/docs/#reject) |
|  | I want to add a specific key and value | [assoc](http://ramdajs.com/0.19.0/docs/#assoc) / [assocPath](http://ramdajs.com/0.19.0/docs/#assocPath) |
|  | I want to replace a specific value based on custom logic | [lens](http://ramdajs.com/0.19.0/docs/#lens) / [lensProp](http://ramdajs.com/0.19.0/docs/#lensProp) / [lensPath](http://ramdajs.com/0.19.0/docs/#lensPath) |
|  | I want to replace specific values based on custom logic | [evolve](http://ramdajs.com/0.19.0/docs/#evolve) |
|  | I want to know if a specific key is present | [has](http://ramdajs.com/0.19.0/docs/#has) / [hasIn](http://ramdajs.com/0.19.0/docs/#hasIn) |
|  | I want to know if a specific key has a specific value | [propEq](http://ramdajs.com/0.19.0/docs/#propEq) / [pathEq](http://ramdajs.com/0.19.0/docs/#pathEq) |
|  | I want to know if a specific key's value satisfies a custom predicate | [propSatisfies](http://ramdajs.com/0.19.0/docs/#propSatisfies) / [pathSatisfies](http://ramdajs.com/0.19.0/docs/#pathSatisfies) |
|  | I want to know if specific keys have specific values | [whereEq](http://ramdajs.com/0.19.0/docs/#whereEq) |
|  | I want to know if specific keys' values satisfy custom predicates | [where](http://ramdajs.com/0.19.0/docs/#where) |
|  | I want to list all the keys | [keys](http://ramdajs.com/0.19.0/docs/#keys) / [keysIn](http://ramdajs.com/0.19.0/docs/#keysIn) |
|  | I want to list all the values | [values](http://ramdajs.com/0.19.0/docs/#values) / [valuesIn](http://ramdajs.com/0.19.0/docs/#valuesIn) |
|  | I want to convert to a list of pairs | [toPairs](http://ramdajs.com/0.19.0/docs/#toPairs) / [toPairsIn](http://ramdajs.com/0.19.0/docs/#toPairsIn) |
|  | I want to know if two objects share the same key and value | [eqProps](http://ramdajs.com/0.19.0/docs/#eqProps) |
|  | I want to create an object with a single key and value | [objOf](http://ramdajs.com/0.19.0/docs/#objOf) |
|  | I want to create an object with multiple keys and values | [zipObj](http://ramdajs.com/0.19.0/docs/#zipObj) |
|  | I want to clone an object | [clone](http://ramdajs.com/0.19.0/docs/#clone) |
|  | I want to merge two objects into one object | [merge](http://ramdajs.com/0.19.0/docs/#merge) |
|  | I want to merge two objects into one object based on custom duplicate key logic | [mergeWith](http://ramdajs.com/0.19.0/docs/#mergeWith) |
|  | I want to merge more than two objects into one object | [mergeAll](http://ramdajs.com/0.19.0/docs/#mergeAll) |
| Functions | I want to combine functions | [compose](http://ramdajs.com/0.19.0/docs/#compose) / [pipe](http://ramdajs.com/0.19.0/docs/#pipe) |
|  | I want to combine promise returning functions | [composeP](http://ramdajs.com/0.19.0/docs/#composeP) / [pipeP](http://ramdajs.com/0.19.0/docs/#pipeP) |
|  | I want to curry a function | [curry](http://ramdajs.com/0.19.0/docs/#curry) |
|  | I want to partially apply a function | [partial](http://ramdajs.com/0.19.0/docs/#partial) / [partialRight](http://ramdajs.com/0.19.0/docs/#partialRight) |
|  | I want to uncurry a function | [uncurry](http://ramdajs.com/0.19.0/docs/#uncurry) |
|  | I want to swap the argument order | [flip](http://ramdajs.com/0.19.0/docs/#flip) |
|  | I want to apply a list of arguments | [apply](http://ramdajs.com/0.19.0/docs/#apply) |
|  | I want to apply multiple functions to a single value and merge the results somehow | [converge](http://ramdajs.com/0.19.0/docs/#converge) |
|  | I want to transform a function's arguments | [useWith](http://ramdajs.com/0.19.0/docs/#useWith) |
|  | I want to apply a list of functions to each argument and collect the results | [juxt](http://ramdajs.com/0.19.0/docs/#juxt) |
|  | I want to create a variadic function from one that takes an array | [unapply](http://ramdajs.com/0.19.0/docs/#unapply) |
|  | I want to restrict the number of accepted arguments to 1 | [unary](http://ramdajs.com/0.19.0/docs/#unary) |
|  | I want to restrict the number of accepted arguments to 2 | [binary](http://ramdajs.com/0.19.0/docs/#binary) |
|  | I want to restrict the number of accepted arguments to specific number | [nAry](http://ramdajs.com/0.19.0/docs/#nAry) |
|  | I want to return the supplied argument unchanged | [identity](http://ramdajs.com/0.19.0/docs/#identity) |
|  | I want to turn a method into a function | [invoker](http://ramdajs.com/0.19.0/docs/#invoker) |
|  | I want to invoke a function only once | [once](http://ramdajs.com/0.19.0/docs/#once) |
|  | I want to inspect values without affecting them | [tap](http://ramdajs.com/0.19.0/docs/#tap) |
|  | I want to bind to a specific context | [bind](http://ramdajs.com/0.19.0/docs/#bind) |
|  | I want to lift a function | [lift](http://ramdajs.com/0.19.0/docs/#lift) / [liftN](http://ramdajs.com/0.19.0/docs/#liftN) |
|  | I want to memoize | [memoize](http://ramdajs.com/0.19.0/docs/#memoize) |
| relation | I want to compare for value equality | [equals](http://ramdajs.com/0.19.0/docs/#equals) |
|  | I want to compare for reference equality | [identical](http://ramdajs.com/0.19.0/docs/#identical) |
|  | I want to know if a value is less than another | [lt](http://ramdajs.com/0.19.0/docs/#lt) |
|  | I want to know if a value is less than or equal to another | [lte](http://ramdajs.com/0.19.0/docs/#lte) |
|  | I want to know if a value is greater than another | [gt](http://ramdajs.com/0.19.0/docs/#gt) |
|  | I want to know if a value is greater than or equal to another | [gte](http://ramdajs.com/0.19.0/docs/#gte) |
|  | I want to find the smallest of two values | [min](http://ramdajs.com/0.19.0/docs/#min) |
|  | I want to find the smallest of two values based on custom logic | [minBy](http://ramdajs.com/0.19.0/docs/#minBy) |
|  | I want to find the largest of two values | [max](http://ramdajs.com/0.19.0/docs/#max) |
|  | I want to find the largest of two values based on custom logic | [maxBy](http://ramdajs.com/0.19.0/docs/#maxBy) |

**Comment by davidchambers** [comment]
This is terrific, Stefano! Very clearly written.

**Comment by CrossEye** [comment]
This is fantastic!

**Comment by 6ewis** [comment]
This is awesome

**Comment by jirutka** [comment]
This is brilliant!

**Comment by scott-christopher** [comment]
This is great @svozza! I expect this would help a great deal with newcomers to Ramda who are not familiar with some of the function names.

Perhaps these could even exist in the doc-blocks of the individual functions under an `@usecase` annotation to help keep them maintained over time? Then we could generate the necessary content to exist somewhere on the docs site.

**Comment by svozza** [comment]
Ok, I think I've finished the first draft. I found the functions ones the hardest to summarise in one short non-technical sentence; `converge` and `useWith` were particularly tricky so if anyone can improve on them please feel free to.

@scott-christopher Yes, I was thinking that one risk of putting these in the wiki would be that they'd be harder to keep up to date. I like the idea of it being generated as part of the build and this getting started guide really needs to be one of the first things you see when you land on http://ramdajs.com; however, the reason I suggested the wiki initially is because I've no idea how to integrate something like this into the build, which is a labyrinth to begin with.

**Comment by svozza** [comment]
Btw, does anyone think there are any functions not in the list that need to be?

**Comment by davidchambers** [comment]
My suggestions for `converge` and `useWith` respectively are:

  - _I want to apply multiple functions to a single value and merge the results somehow._

  - _I want to transform a function's arguments._

> [O]ne risk of putting these in the wiki would be that they'd be harder to keep up to date.

True, although Ramda is no longer changing rapidly. Let's put these in the wiki for now, at least. :)

**Comment by svozza** [comment]
Yes, I like those definitions.

> Let's put these in the wiki for now, at least. 

Is that enough though? I still have to dig a little to find the cookbook even though I know where it is. What hope does a newcomer have of actually finding this? I think there needs to be a link on Ramda's Github landing page at the very least and preferably ramdajs.com too.

**Comment by CrossEye** [comment]
>  I think there needs to be a link on Ramda's Github landing page at the very least and preferably http://ramdajs.com too.

I'm finishing something else up, hopefully tonight, and then I'll go back to getting additional documents onto the documentation page.  I'd like to have  another section of that page -- perhaps "Info" -- with all sorts of miscellaneous documents.  There should be a link from the README, and at least some of the documents should be directly linked from a new short section at the top of API page.  The type signatures document and this one would definitely be among those, as well as the to-be-written page on types.

**Comment by svozza** [comment]
Sounds good. I'll stick this on the wiki later today if no one has any objections. Any future edits can be done there.

**Comment by svozza** [comment]
So here it is. :)

https://github.com/ramda/ramda/wiki/What-Function-Should-I-Use%3F

Will I close this issue now or wait until we've done the other documentation work mentioned by @CrossEye ?

**Comment by CrossEye** [comment]
Let's leave it open as a reminder.   I'm hoping it's only a day or two.

**Comment by svozza** [comment]
I just realised that I complete forgot to add any of the logic functions.

**Comment by svozza** [comment]
Logic functions now added. I think all that's left are the maths ones.

**Comment by CrossEye** [comment]
This is great.  I have stalled again in my other effort.  I will try to finish at least _one_ of these tasks this weekend.

**Comment by svozza** [comment]
Maths functions added so I think that's them all.

**Comment by sotojuan** [comment]
RxJS docs now have a cool [multiple choice thing](http://reactivex.io/rxjs/) to help with this. Maybe we can do that as well!

**Comment by svozza** [comment]
Are you offering? :wink:

**Comment by sotojuan** [comment]
Once I figure out how they did it, I'd be more than happy to!

**Comment by asaf-romano** [comment]
Only thing missing is, I think, the functions added in 0.20.

**Comment by VitorHP** [comment]
This is really great. It's the third time I come to this PR to check some function since I first saw it.

**Comment by tycho01** [comment]
I wonder if a flowchart like [this](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-static.md) might be an option?

**Comment by CrossEye** [comment]
@tycho01:

> I wonder if a flowchart like [this][ro] might be an option?

While I think it might, I believe it would be significantly more complex for Ramda, as that chart is really simply a how-to-create discovery.  Ramda's functions have many more basic purposes.  That doesn't mean it can't be done, only that it would be quite a bit larger.

  [ro]: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/which-static.md
