### ISSUE TITLE
R.over implementation (question)

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#1696]
Talking about `R.over` implementation.

Can somebody point me to a difference between

```js
// current Ramda implementation
var Identity = function(x) {
  return {value: x, map: function(fn) { return Identity(f(x)) }}
};

function over(ln, fn, x) {
  return ln((y) => Identity(fn(y)))(x).value
}
```

and simplified:

```js
let over = function (ln, fn, s) {
  return ln((v) => ({value: fn(v)}))(s).value
}
```

I failed to find a case where second would not work instead of the first.

P.S.

or even

```js
function over(ln, fn, x) {
  return ln((y) => [fn(y)])(x)[0]
}
```

**Comment by ivan-kleshnin** [comment]
I've find out that this is kinda conventional and while it technically **can** be simplified
those functors are meaningful in static typed langs. So I'm closing this.

**Comment by scott-christopher** [comment]
> I've find out that this is kinda conventional and while it technically can be simplified
those functors are meaningful in static typed langs.

They can also convey meaning in dynamic languages too, namely that the Identity type is _the_ functor behaviour that we're interested in here.

Like you've pointed out, we could use the functor behaviour of a singleton list or object (or even a `Maybe.Just`), but the Identity functor captures the intent.

**Comment by ivan-kleshnin** [comment]
Yeah. Thanks for clarification.
