### ISSUE TITLE
about assoc prototype flattening

### ISSUE THREAD

**Issue by VitorHP** [ramda/ramda#1697]
As is documented, assoc flattens prototype properties into the new object.

I'm using Ramda in a MeteorJS project. I have objects that have helpers which are assigned as properties in the prototype and a schema validation that checks the structure of the object before saving it to the database. Whenever I do an operation in an object using assoc it becomes invalid because of the prototype properties flattening.

I know this is not really a Ramda issue, but I think this behavior is not really what you would expect when you're just trying to change a property in an object.

Would the performance cost be too high if we were to set the prototype properties on the new object's prototype or is there something I'm missing?

**Comment by CrossEye** [comment]
I think this might be running up against one of those places where FP and OOP are really quite at odds.  If you are really "just trying to change a property in an object" then you probably shouldn't be using `assoc` or any Ramda function.  Ramda takes the immutability of input data quite seriously.  You could always use something like

```js
R.curry(function(prop, val, obj) {obj[prop] = val; return obj;});
```

`assoc` clearly does not play well with behaviorful objects from the OOP world.  There's an unspoken assumption that these are generally plain data, structure similar to what one might get back from a `JSON.parse` call.

I saw this Issue and went to write some code that demonstrated a possible problem involved in not flattening the prototype chain.  I came back to find that you'd already coded a possible solution... and that I'd entirely misunderstood your proposal.  I thought you wanted to _walk_ the prototype chain and try to reconstitute the object as close to the original as possible, with only the relevant property altered.  I created [a snippet][sn] I thought might demonstrate problems in trying to do this, a constructor that creates items with two numeric properties, but only one of which is directly writeable, and with no hint on how to replicate an existing object with those two properties from and existing one.

Looking at [your solution][ch], I see that instead you seem to want to _ignore_ the prototype chain.

While this is of course much easier to do, you are ignoring data that is on the input object.  It's not that it's an unreasonable proposal, but why should we assume that something on the prototype is unimportant and not worth cloning on an `assoc` call?  Your example showed an OOP method not being cloned, which might be reasonable, but you replaced one showing other normal data not being cloned.  Does the library get to make that call?


  [ch]: https://github.com/ramda/ramda/pull/1699
  [sn]: http://goo.gl/203HTV

**Comment by VitorHP** [comment]
I don' t really mean to change the input's property. I guess I expressed myself poorly. I want what assoc says it does. A shallow copy of the object with its property overriden.

And pardon me if I'm being dumb on this, but I don't think I'm ignoring the prototype chain. I'm creating the result object using the input's prototype, so the methods on the input go with it. Am I misunderstanding this?

I added another spec to show this.

**Comment by CrossEye** [comment]
Yes, when I thought I was misreading, I was misreading.  :smile:

But then my original objection still stands.  Constructor functions do more than attach prototypes, and I feel that if we start down the path of trying to work out OOP behavior, we would start setting expectations we could never meet.

An [extension of my earlier example][ex] shows a constructor that maintains some silly invariant.  The existing `assoc` simply copies properties, and `assocPath` copies structures, changing only the required bit.  This new one also sets the prototype, and passes, for example, `instanceof` tests.  This to me makes it seem as though it should act like an object of the type it's mimicking.   But it can't do so in the general case, or in far too many cases, I believe.


  [ex]: http://goo.gl/Klb0Xx

**Comment by VitorHP** [comment]
I get your point and you're right, but coming to think of it, even the current implementation of `assoc` has some of the pitalls you mentioned.

[In the same case as your example](http://goo.gl/h44Xyg), the changes to the invariant would not work on the result object, so we're not guaranteeing that what's in the prototype will continue to work anyway and are still changing the structure of the resulting object (by changing the structure, I mean adding properties that were not there on the first place).

**Comment by CrossEye** [comment]
Absolutely.  The difference is that at the moment, we're not trying to do any more, nor promising any more.  Perhaps this should be more explicit.

What I'm afraid of is making it sound as though this were a full OOP clone, with just a single property changed.  That, I think is impossible without some sort of user-controlled `reviver` function.

What would be the expected value of 

```js
dissoc('height', new Rectangle(5, 8)).area()
```

Is this just an instance of _caveat emptor_?  Perhaps, but it worries me.  I would rather simply stay away.

**Comment by svozza** [comment]
I always think of `assoc` et al as functions for manipulating hashmaps or records, I don't think the increase in complexity needed to support other usages is worth it.

**Comment by VitorHP** [comment]
The motivation behind this issue/PR was that once I saw the prototype being flattened, I though "Alright. This guy is trying to keep the object behavior working", so to make that possible in more situations and to avoid changing structure I came up with this solution. As demonstrated by @CrossEye above, both mine and the current implementation of assoc does not solve this problem for all cases.

I acknowledge that what I proposed may not be consistent with the vision for the lib, but I can't agree that the current solution is the optimal way to go too, because it stands in the middle of the way. It flattens the prototype, but does not guarantee that what was there still works. It doesn't to keep being an instance of whatever it was, but behaves more or less like one, which seems kind of misleading too me.

I think that a good solution would be to try and keep the object as close as possible as it was (which may not be possible or so it seems) or rip the prototype off at once and state "Sorry mate, only plain maps allowed. No silly behaviors here". May seem like the lib would be making a lot of choices for the user, but the current implementation already is. At least in the second case, I could plug a function at the end of a compose/pipe to hydrate a new instance of the input based on the object returned.

**Comment by buzzdecafe** [comment]
perhaps you want to implement `map` on your object and treat it as a functor. Then the object is responsible for knowing how to transform itself, since there is no reasonable way for us to know that.

**Comment by CrossEye** [comment]
> The motivation behind this issue/PR was that once I saw the prototype being flattened, I though "Alright. This guy is trying to keep the object behavior working", so to make that possible in more situations and to avoid changing structure I came up with this solution. 

I think this might just be an issue of wording in the documentation, then.  The point is not that we are trying to do _anything at all_ with the prototype.  That comment was there to explain that we are _not_ trying to keep the prototype chain alive, but that we would still capture all of an object's (enumerable) properties.  We keep them in a flat object, thought, without attempting to capture the prototypal structure of the original object.

The whole goal was to keep people from assuming what you assumed.  So obviously it's not worded correctly.  Any suggestions would be welcome.

**Comment by VitorHP** [comment]
Yeah. I think this settles things. It was indeed a problem of interpretation of the docs.

I think that something on the lines of "Note that when copying the object, we iterate on all enumerable properties, so prototype properties are copied and flattened onto the new object as well" would make it clearer, but it's just a suggestion.

It's a great lib. I'm learning a lot. :)

**Comment by CrossEye** [comment]
This sounds like an improvement to me.  Do you feel like creating a PR with this suggestion?

**Comment by Izhaki** [comment]
[immutability-helper](https://github.com/kolodny/immutability-helper) (a react util drop-in) is a library that does something very similar to `assoc` but without flattening prototype properties.

I've ran some [benchmarks](https://run.perf.zone/view/RassocPath-vs-update-1502973924436) that show ramda is faster, but some of this must be due to the lack of `ownProperty` checks.

I feel ramda should offer a similar set of functions. That is, `assoc` without flattening.
