### ISSUE TITLE
0.20.1 upgrade guide

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#1698]
__2016-04-09 update:__ reduceBy signature has changed in [v0.21.0](https://github.com/ramda/ramda/issues/1722). Those updating to v0.20.1 from an earlier version should upgrade directly to v0.21.0 to avoid needlessly updating call sites.

---

Changes: https://github.com/ramda/ramda/compare/v0.19.1...v0.20.1

Removals:
- :x: `R.commute` (see `R.traverse` and `R.sequence`) #1625
- :x: `R.commuteMap` (see `R.traverse` and `R.sequence`) #1625

Deprecations:
- :floppy_disk: `R.allUniq` #1626

Changes:
- `R.zipObj` now will truncate to shorter list #1669
- `R.partition` now works with other filterables #1655
- `R.equals` now compares Promises by reference #1619
- `R.add` and `R.subtract` coerce arguments to Number #1580, #1573
- Correct arity in `R.juxt`, `R.cond` functions #1571, #1587
- :rainbow: `R.either` and `R.both` work with any fantasy-land compatible applicative functor #1566
- Performance improvements:
  * Transducer implementation #1657
  * `R.merge` and `R.mergeAll` #1660
  * `R.intersection` #1597
  * `R.uniqBy` #1639

Additions:
- :new: `R.until` #1692
- :new: `R.reduceBy` #1598
- :new: `R.applySpec` #1592
- :new: `R.tryCatch` #1581
- :new: `R.clamp` #1564

**Comment by asaf-romano** [comment]
Minor correction: ``R.converge`` always reported correct arity. The only thing that changed is that it no longer throws for empty-function-list (the combining-function is nullary in that case).
