### ISSUE TITLE
Unwind?

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1705]
This aggregation-pipeline operator in MongoDB's Aggregation Framework is an interesting candidate for a general utility function:
https://docs.mongodb.org/manual/reference/operator/aggregation/unwind/

There are some use cases I know of:
1. poor man's `head`
2. preliminary step to `groupBy`/`reduceBy`-like behavior.
3. preliminary step to `$lookup` (Mongo's simplified join)
4. "finalizer" step for aggregation, when it was easier to generate ~ `[{ _id: "foo", results: ["1", "2", ...] }, ...]`, but the requirement is for ~ `[{ name: "foo", result: "1" }, { name: "foo", result: "2" }, ...]`

For `1` we have better alternatives (e.g. `map(evolve({ foo: head }))`); `3` is border-line use case because `map(evolve({ foo: map(...) }))` is often just-as-good. For `2` and `4`, however, I don't think we offer any straight-forward alternatives.

Quick demo:
http://goo.gl/QJ03To

What do people think?

**Comment by CrossEye** [comment]
Although I'm pretty sure I've used something like this before, I don't recall details, and I'd like to hear more support before deciding that it's important for the library rather than the Cookbook.
