### ISSUE TITLE
Reconsider reduceBy arguments order

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1706]
Naive implementations of the 3 in-house use-cases for reduceBy:
```js
const groupBy = reduceBy(__, append, [], __);
const countBy = reduceBy(__, add, 0, __);
const indexBy = reduceBy(__, (a, b) => b, null, __);
```

However if the signature were reduceBy(valueFn, initialValue, keyFn, list):
```js
const groupBy = reduceBy(append, []);
const countBy = reduceBy(add, 0);
const indexBy = reduceBy((a, b) => b, null);
```
I understand why the current signature makes sense, but the above seems reasonable as well, given that it resembles plain ``reduce`` quite nicely.

**Comment by CrossEye** [comment]
This makes sense to me.  I think if we do this quickly, not too many people would have come to depend on the current signature.  And in this case, I don't see any good argument for any particular signature except of course data-last.

Are there counter-examples to show the current one would be more useful for currying in some cases?  They're not coming to mind at the moment.

**Comment by asaf-romano** [comment]
@jirutka

**Comment by jirutka** [comment]
So you suggests to change the `reduceBy` signature as follows?

```diff
- // reduceBy :: (b -> String) -> ((a, b) -> a) -> a -> [b] -> {String: a}
- function reduceBy(keyFn, valueFn, valueAcc, list) { … }
+ // reduceBy :: ((a, b) -> a) -> a -> (b -> String) -> [b] -> {String: a}
+ function reduceBy(valueFn, valueAcc, keyFn, list) { … }
```

**Comment by asaf-romano** [comment]
Indeed.

**Comment by jirutka** [comment]
I think that it’s reasonable. :+1:
