### ISSUE TITLE
Reverse of indexBy

### ISSUE THREAD

**Issue by jimf** [ramda/ramda#1708]
I'm working with data in the following shape:

``` js
{ xyz: { title: 'A' },
  abc: { title: 'B' } }
```

And transforming it into:

``` js
[ { id: 'xyz', title: 'A' },
  { id: 'abc', title: 'B' } ]
```

I'm wondering if this is a general/common enough problem to warrant either a core contribution or cookbook entry, and if so, what a desirable name / API might look like.

Proposal:

``` js
deindexBy(id => ({ id }), dataset);
```

The idea here is to take a function that will transform the keys into objects that will subsequently be merged with their respective values. Thoughts?

**Comment by CrossEye** [comment]
It's unquestionably worth putting in [the Cookbook][cb].  I'm not so sure about the library itself.

As to the API, can you think of any other useful function besides one that essentially gives a property name to the key?  If not , might this not be a cleaner API?:

```js
deindex('id', dataset);
```


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by jimf** [comment]
Yes, in my specific case I have a need to coerce the keys to numbers. Otherwise I agree that I'd prefer that simplicity.

**Comment by CrossEye** [comment]
Well, you've already demonstrated a reason for the more sophisticated API.

Again, I can definitely see this in the Cookbook.  If you want to push for its inclusion in the main library, please feel free to try to make the case.  But the Cookbook is simply part of a publicly editable wiki, and you can add it yourself, if you like.

**Comment by asaf-romano** [comment]
I've this function defined somewhere:

```js
const listFromObject = curry(
    // Don't use assoc, deliberately control the order.
    (keyPropName, obj) => values(mapObjIndexed((v, k) => ({ [keyPropName]: k, ...v }), obj))
);
```
And even though I had to use it a few times (almost always in quick-and-dirty scripts), I agree that it probably belongs to the cookbook (at least as long as all of Ramda's functions are under a single namespace).

**Comment by jimf** [comment]
Sounds good. I agree this belongs in the cookbook.

@asaf-romano Nice, I like that solution. Seems more efficient than what I had come up with, which uses `juxt` with some `mergeAll` / `keys` / `values` noise. Can you expand on the _Don't use assoc, deliberately control the order_ comment?

**Comment by asaf-romano** [comment]
As mentioned, I use this mainly in scripts, which are all about eye-balling the output, sometimes. Since json output is controlled by js iteration order, here's what happens if you use plain assoc:

```js
{
   oldProp1: 1,
   oldProp2: 1,
   oldProp3: 3,
   allNewProp: "a"
}
```

And here's what happens if you "assoc" the other way:
```js
{
   allNewProp: "a"
   oldProp1: 1,
   oldProp2: 1,
   oldProp3: 3
}
```

**Comment by guilhermejcgois** [comment]
This solutions works for me:
`array = keys(object).map(property=> object[property]);`

**Comment by CrossEye** [comment]
@guilhermejcgois: That looks to be just `values`.  The functions here are a bit different.
