### ISSUE TITLE
propOr should probably work like pathOr, looking at all properties

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1712]
This is not so nice:
http://goo.gl/zL7Q3v

**Comment by buzzdecafe** [comment]
yeah that does look bad

**Comment by CrossEye** [comment]
I'm trying to think through the implications of replacing this:

```js
module.exports = _curry3(function propOr(val, p, obj) {
  return (obj != null && _has(p, obj)) ? obj[p] : val;
});
```

with this:

```js
module.exports = _curry3(function propOr(val, p, obj) {
  return (obj != null && p in obj) ? obj[p] : val;
});
```

Why are we using `._has` here?  Any ideas?

**Comment by asaf-romano** [comment]
I guess that in _some_ cases this is the desired behavior, but it can always be achieved explicitly (using a ``has`` check), and I think that most of the time the fact that ``propOr(null, 10)`` can return null is counter-intuitive (and contradicts pathOr's behavior).
