### ISSUE TITLE
apply function n times

### ISSUE THREAD

**Issue by FMensurado** [ramda/ramda#1715]
Is there a function to apply another function n times? Something like:

```
var applyN = function(f, n) { 
  if(n > 0) {
    n -= 1;
    return R.compose(f, applyN(f, n));
  }
  else {
    return R.identity();
  }
};
```

Thanks

**Comment by scott-christopher** [comment]
[`R.times`](http://ramdajs.com/docs/#times) should do what you want.

**Comment by FMensurado** [comment]
Thanks for the response.
The type signature of  R.times is `(Number → a) → Number → [a]` but I'm using a more general type `(a  → b)` that I need to be call n times. I believe it's not exactly the same functionality that `times` implements (is it?). I'm actually trying to generate a N times composition of the same function, like so `f(f(...f(x)...))`. The function I'm trying to call one or more times is `R.compose(R.flatten,R.map(R.values))`. The function I posted works just fine but would prefer to use something already in the library.

**Comment by buzzdecafe** [comment]
Try `until`

http://ramdajs.com/docs/#until

**Comment by FMensurado** [comment]
Thanks for you suggestion.
The `Number` is not showing in the type of `until`, should I assume it is implicit in type `a` of the `until` signature? How should I use it in my case?

**Comment by buzzdecafe** [comment]
your predicate will have to keep track of a counter. Also note that `R.compose(R.flatten,R.map(R.values))` may be the same as `R.chain(R.values)` (if your flattening is one level deep)

**Comment by FMensurado** [comment]
That's much more concise, thank you! In my case I have more than one level but your suggestion works well all the same. Regarding keeping track of a counter in the predicate I prefer to use a function like the one I'm using, at least for now. Thank you very much for all your suggestions!
BTW congrats for this lib!!

**Comment by FMensurado** [comment]
Actually to apply compose function `f` `n` times we could do it like so:
`R.reduceRight(R.compose, R.identity, R.repeat(f, n))`

**Comment by CrossEye** [comment]
I definitely think this should go in the [Cookbook][cb].  Of course we can make this [points-free][re] too, if we choose:

```js
const applyN = compose(reduceRight(compose, identity), repeat);
```

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [re]: http://goo.gl/vtqaXh

**Comment by FMensurado** [comment]
Thank you, that's even better! Should I add it to the Cookbook or is it required to be one of you guys?

**Comment by CrossEye** [comment]
Please go ahead.  There's some magic I never remember that will update the table of contents, but don't worry about that.  It will get listed automatically the next time someone remembers the incantation.

**Comment by FMensurado** [comment]
Done. Copied your REPL example, only added the type definition but I'm not sure if that's acceptable in this context. Thanks!!

**Comment by CrossEye** [comment]
Looks fine to me.  Thanks you very much!
