### ISSUE TITLE
update and adjust arguments order

### ISSUE THREAD

**Issue by iofjuupasli** [ramda/ramda#1716]
`update` and `adjust` is very similar method. I frequently change between them in code. But it seems inconsistent that `adjust` have index as second argument, but `update` have index as first argument. This often leads to errors.

**Comment by davidchambers** [comment]
Great point!

Another option to consider is removing these functions, since they're effectively just shorthands for [`R.set`][1] and [`R.over`][2].


[1]: http://ramdajs.com/docs/#set
[2]: http://ramdajs.com/docs/#over

**Comment by CrossEye** [comment]
I think it's definitely worth fixing the argument order.  Whether we come back and take a pass at removing everything that overlaps with `Lens`es should be a separate, dedicated discussion.

Which order makes more sense?  Index first for both?

**Comment by davidchambers** [comment]
> Which order makes more sense? Index first for both?

I like index first as it mirrors `R.set` and `R.over`, which take lens first.

**Comment by asaf-romano** [comment]
``update`` is currently consistent with ``assoc[Path]``. It's only ``adjust`` that takes the index/prop second. I cannot comment on the currying use-case, because I always use this functions with known indices (0, 1, -1).

**Comment by kedashoe** [comment]
see https://github.com/ramda/ramda/pull/973#issuecomment-87829805

**Comment by paldepind** [comment]
It seems like there is an agreement that the current API is inconsistent. I just stumbled into this when I was reimplementing `adjust` and `update` for the [immutable list](https://github.com/funkia/list) I'm working on. I also think that the different placement of the index is inconsistent and confusing.

I'd love to do a PR that moves the index to the first argument in `adjust`. But it would obviously be a breaking change.

**Comment by kedashoe** [comment]
> I'd love to do a PR that moves the index to the first argument in adjust. But it would obviously be a breaking change.

:+1: from me
