### ISSUE TITLE
Multiple types are not shown in "expand parameters" in documentation 

### ISSUE THREAD

**Issue by jagare** [ramda/ramda#1718]
When there are several possible types for a parameter, only the first one is shown when clicking "expand parameters" in the documentation. For example for "pluck" in the code we have [`@param {Number|String} key `](https://github.com/ramda/ramda/blob/master/src/pluck.js#L15) . However only `Number` is display in the expand parameter box.

**Comment by CrossEye** [comment]
Moved to https://github.com/ramda/ramda.github.io/issues/74
