### ISSUE TITLE
R.defaultTo(+/- Infinity)  would expect to be the default value instead of +/- Infinity since NaN would return the default as well.

### ISSUE THREAD

**Issue by bcowgill** [ramda/ramda#1719]
```
    var def = R.defaultTo(42);
            it('should NOT EXPECTED return default value for Infinity', function () {
                expect(def(Infinity)).to.be.equal(Infinity);
            });
            it('should NOT EXPECTED return default value for -Infinity', function () {
                expect(def(-Infinity)).to.be.equal(-Infinity);
            });
```

**Comment by davidchambers** [comment]
I disagree. We can't know whether `Infinity` is a "valid" value in the user's domain. For a pretty-printing function, for example, one may take `depth` as an argument. `Infinity` is a useful value in this case.

One is free to define one's own `defaultTo` function, of course. :)

**Comment by CrossEye** [comment]
I'm not following the suggestion.  Do you think we should add those test cases because it seems to you that it's ambiguous otherwise?  If so, I don't have a serious objection, although I don't feel a similar need.

If you believe that we should change the behavior when `±Infinity` is supplied, then I don't see any reason at all for that.  Those strike me as perfectly legitimate values.

**Comment by asaf-romano** [comment]
If anything, I would change defaultTo not to special-case NaN as it does now (and not because it's not potentially useful, but rather because it's inconsistent with all other fallback/fallback-check functions).

**Comment by bcowgill** [comment]
As asaf-romano suggests I think it would be more clear if there was an explicit defaultTo / defaultToNumber, defaultToValidNumber  then in code it's clear what type of value is being dealt with

**Comment by CrossEye** [comment]
What would be the behavior of `defaultToNumber` and `defaultToValidNumber`? And would `NaN` be different in validity than `±Infinity`?

**Comment by bcowgill** [comment]
Well I would think something like this:

pseudo tests:
var def=R.defaultToValidNumber(42)
				it('should return default value for undefined', function () {
					expect(def(void 0)).to.be.equal(42);
				});
				it('should return default value for null', function () {
					expect(def(null)).to.be.equal(42);
				});
				it('should return default value for NaN', function () {
					expect(def(NaN)).to.be.equal(42);
				});
				it('should return default value for Infinity', function () {
					expect(def(Infinity)).to.be.equal(42);
				});
				it('should return default value for -Infinity', function () {
					expect(def(-Infinity)).to.be.equal(42);
				});

var def=R.defaultToNumber(42)
				it('should return default value for undefined', function () {
					expect(def(void 0)).to.be.equal(42);
				});
				it('should return default value for null', function () {
					expect(def(null)).to.be.equal(42);
				});
				it('should return default value for NaN', function () {
					expect(def(NaN)).to.be.equal(42);
				});
				it('should return default value for Infinity', function () {
					expect(def(Infinity)).to.be.equal(Infinity);
				});
				it('should return default value for -Infinity', function () {
					expect(def(-Infinity)).to.be.equal(Infinity);
				});
				it('should return the default value for non-number as string', function () {
					expect(def('not38')).to.be.equal(42);
				});
				it('should return the value for number as string', function () {
					expect(def('38')).to.be.equal(38);
				});



var def=R.defaultTo(42)
				it('should return default value for undefined', function () {
					expect(def(void 0)).to.be.equal(42);
				});
				it('should return default value for null', function () {
					expect(def(null)).to.be.equal(42);
				});
				it('should return default value for NaN', function () {
					expect(def(NaN)).to.be.equal(NaN);
				});
				it('should return default value for Infinity', function () {
					expect(def(Infinity)).to.be.equal(Infinity);
				});
				it('should return default value for -Infinity', function () {
					expect(def(-Infinity)).to.be.equal(-Infinity);
				});
				it('should return the default value for non-number as string', function () {
					expect(def('not38')).to.be.equal(42);
				});
				it('should return the value for number if given as string', function () {
					expect(def('38')).to.be.equal(38);
				});

**Comment by CrossEye** [comment]
I guess I don't understand.

I can see some reasonable sense in special behavior for `NaN` -- it is a particularly odd value.  But I don't see at all why one would expect the same for `±Infinity`.  These especially look odd:

```
it('should return default value for Infinity', function () {
    expect(R.defaultTo(42, Infinity)).to.be.equal(Infinity);
});
it('should return default value for -Infinity', function () {
    expect(R.defaultTo(42, -Infinity)).to.be.equal(Infinity);
});
```

but even the `ValidNumber` ones seem slightly strange to me.

Can you explain why you would expect this?  When is this useful, and worth the possible harm?  I suppose if we add enough functions there is theoretically no harm -- just use the function with the behavior you want -- except that the library grows that much more.

Maybe it's just that I'm not made particularly nervous by Infinity.  :-)

Obligatory Buzz Lightyear line dropped by popular request.

**Comment by bcowgill** [comment]
Well, I'm thinking of validation of user input. If you want a default value when the input is not a valid number it won't make much sense to allow +/- Infinity if you cannot operate on that value.
