### ISSUE TITLE
Suggestion: Null-safe `get`

### ISSUE THREAD

**Issue by cjohansen** [ramda/ramda#1720]
Lodash has `get` (similar to Clojure's `get-in`), to grab for nested properties in a null-safe manner:

```
const obj = {};
get(obj, ['some', 'nested', 'property']) //=> null
```

As opposed to:

```
const obj = {};
obj.some.nested.property //=> Boom!
```

Lodash also supports a default value, which is quite handy. I guess I want a shorthand for this:

```js
defaultTo(42, prop('nested', prop('something', obj)))
```

I guess it might have to be two functions as variadic functions and auto-currying doesn't mix to well.

```js
const get = curry((path, target) => {
  return path.reduce((res, p) => res && res[p], target);
});
```

```js
const getWithDefault = curry((path, defaultVal, target) => {
  return path.reduce((res, p) => {
    const val = res && res[p];
    return val === null || val === undefined || typeof val === 'number' && isNaN(val) ? defaultVal : val;
  }, target);
});
```

**Comment by cjohansen** [comment]
Perhaps make `prop` support an array path argument:

```js
prop(['something', 'nested'], obj);
```

**Comment by cjohansen** [comment]
Lodash `get` also supports a default value, that would be nice as well.

**Comment by asaf-romano** [comment]
See ``path``, ``pathOr`` and ``propOr``.

**Comment by CrossEye** [comment]
I think [`path`][pa] already does what you want.  Ramda also already has [`propOr`][po], and [`pathOr`][pt] for default values.  You might also look at [`lensPath`][lp] which creates a lens for a particular path with which you can then [`view`][vw], [`set`][se], or adjust the value with [`over`][ov].

  [dt]: http://ramdajs.com/0.20.1/docs/#defaultTo
  [lp]: http://ramdajs.com/0.20.1/docs/#lensPath
  [ov]:http://ramdajs.com/0.20.1/docs/#over
  [pa]: http://ramdajs.com/0.20.1/docs/#path
  [pt]: http://ramdajs.com/0.20.1/docs/#pathOr
  [po]: http://ramdajs.com/0.20.1/docs/#propOr
  [se]: http://ramdajs.com/0.20.1/docs/#set
  [vw]: http://ramdajs.com/0.20.1/docs/#view

**Comment by buzzdecafe** [comment]
... although the real killer feature of lenses is that they compose

**Comment by cjohansen** [comment]
Cool, thanks!
