### ISSUE TITLE
Lazy Sequences

### ISSUE THREAD

**Issue by bas080** [ramda/ramda#1724]
I was playing with clojure and lazy sequences. I tend to do javascript development and thought it would be nice to define lazy sequences with recursive functions in javascript. I checked out my favorite javascript toolbelt (Ramda) and was not able to use the functions provided to define lazy sequences. I made something that enables me to do what I want.

So I was wondering what Ramda currently has to offer when it comes to lazy sequences.

If Ramda does not offer such a feature, should it and how?

``` javascript
function lazy(fn, args) {

  var result = [];

  return function take(n, startArgs){
    var v = fn.apply(this, startArgs || args);
    result.push(v);

    for (var i = 1, l = n; i < l; i++) {
      v = fn.apply(this, v);
      result.push(v);
    }

    return result;
  }
}

function exponential(a) {
  return [a * a];
}

function fibo(a, b) {
  return [b, a + b];
}

var lazyExponential = lazy(exponential, [2]);

var lazyFibo = lazy(fibo, [0, 1]);

function prop(p) {
  return function(o){
    return o[p];
  };
}

console.log(
  //lazyExponential(3, [3])
  lazyFibo(10)
);
```

**Comment by CrossEye** [comment]
We once had a LazyList exension, which never got significant attention and was eventually pulled in #857.  I would like to see us resurrect some of those ideas in a different form.  See also #1482, which discussed related ideas, but never really went anywhere.  Somehow, we really do need to support lazy structures.  I'm just not certain how.

**Comment by Izhaki** [comment]
This can be done: #2356
