### ISSUE TITLE
R.juxt should be a binary function

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1725]
According to the documentation, [`R.juxt`](http://ramdajs.com/docs/#juxt) "applies a list of functions to a list of values".

I assumed the function would be of type `[a -> b] -> [a] -> [b]`, but it actually has a complex type I find difficult to grok: `[(a, b, ..., m) -> n] -> ((a, b, ..., m) -> [n])`.

What's our reason for choosing this type?

For now I'll use [`R.ap`](http://ramdajs.com/docs/#ap), which in my view is a much simpler function. (I currently wish to apply a list of functions to a single value, so the difference between `ap` and `juxt` is not important.)

**Comment by buzzdecafe** [comment]
> What's our reason for choosing this type?

i think that is traceable to [its clojure roots](http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/juxt). 

i agree the sig you suggest is clearer. it is essentially the sig of `ap`.

**Comment by CrossEye** [comment]
Discussions in #986 and #1495.

The basic idea was that it should behave like `compose`, `cond`, `converge`, _et. al._

While it does overlap with `ap`, it is more powerful (and filled with more JS <del>goodies</del> weirdness.)

**Comment by asaf-romano** [comment]
I personally find the current behavior very intuitive in JS context, and quite useful (see R.partition). I rarely find ``ap`` useful for arrays, and when I did use it, it was wrapped with something like ``useWith(ap, [identity, of])``.

**Comment by paldepind** [comment]
How would the proposed function behave? It would have signature `[a -> b] -> [a] -> [b]`. But would the result of `R.juxt([f, g, h], [x, y, z])` be `[f x, g y, h z]` or would it be `[f x, f y, f z, g x, g y, g z, h x, h y, h z]`? The former is identical to `R.zipWith(R.call)` and the later is identical to `R.ap`. So neither seems useful.

**Comment by buzzdecafe** [comment]
welcome back, @paldepind !

**Comment by CrossEye** [comment]
Agreed on all points @paldepind.  (uh oh!  :smile:)  And, also, welcome back.

**Comment by paldepind** [comment]
Thank you very much :smile: I'm not making a grand return. But I do miss you.

**Comment by thurt** [comment]
>"applies a list of functions to a list of values"

Are there some more concrete terms for describing how a list of functions can be applied to a list of values? Because I can think of a few different possibilities which @paldepind has also alluded to.

For instance, isn't there a possible difference in the output order depending on how list items are processed? 
`[f x, g x, h x] + [f y, g y, h y] + [f z, g z, h z]`
vs
`[f x, f y, f z] + [g x, g y, g z] + [h x, h y, h z]`

**Comment by CrossEye** [comment]
How about

> Creates a new function out of a list of functions that will return a list created by applying each of those functions to the arguments supplied.  For example, if `fn = juxt([f, g, h])`, then `fn(a, b) //=> [f(a, b), g(a, b), h(a, b)]`

??

**Comment by thurt** [comment]
:thumbsup: that is better for sure. i like how you show the function application with generics

**Comment by CrossEye** [comment]
I won't bother doing anything about this until we figure out #1774, but if we keep `juxt`, I think this would be a reasonable improvement.

**Comment by thurt** [comment]
There is an edge case to consider where the function list only contains 0-ary functions. In this case, i think a `binary_juxt` may behave unexpectedly if `curryN` is used internally.

```javascript
const fns = [always(0)] // 0-ary function list

juxt(fns)() // executes fine -- returns 0
binary_juxt(fns)() // will not execute due to curryN requiring one more value
```
Maybe the same consideration with `applySpec`, if it ever gets turned to binary function.
