### ISSUE TITLE
Error in R.groupWith() documentation

### ISSUE THREAD

**Issue by kahless** [ramda/ramda#1728]
http://ramdajs.com/0.21.0/docs/#groupWith

- Wrong return value in the first example;
- Missed "R." prefix in the first and second examples;
- Broken indentation;
- Missed lovely "=>" prefix before returned value in the comments;

So the correct code snippet should be:
```
R.groupWith(R.equals, [0, 1, 1, 2, 3, 5, 8, 13, 21])
//=> [[0], [1, 1], [2], [3], [5], [8], [13], [21]]

R.groupWith((a, b) => a % 2 === b % 2, [0, 1, 1, 2, 3, 5, 8, 13, 21])
//=> [[0], [1, 1], [2], [3, 5], [8], [13, 21]]

R.groupWith(R.eqBy(isVowel), 'aestiou')
//=> ['ae', 'st', 'iou']
```

**Comment by buzzdecafe** [comment]
yes, all well-spotted, thanks. one other change to make: The sig should be corrected to `(a → a → Boolean) → [a] → [[a]]`

**Comment by kahless** [comment]
Actually the callback is called in this way: `fn(list[idx], list[nextidx])`
If the user trust your curried signature and pass a curried function (a => b => true) it would be an error.

**Comment by buzzdecafe** [comment]
well, not really, because of the way we do curry. In the examples above, `R.equals` is a curried function and there is no error. But I'd be fine with the "safer" sig `((a, a) → Boolean) → [a] → [[a]]` which is still an update from the current ambiguous one.
