### ISSUE TITLE
Documentation somewhat unclear for dropLastWhile

### ISSUE THREAD

**Issue by bcowgill** [ramda/ramda#1730]
Signature says (a → Boolean) → [a] → [a]

Docs say:
Returns a new list containing all but **last the n elements** of a given list, passing each value from the right to the supplied predicate function, skipping elements while the predicate function returns true. The predicate function is passed one argument: (value)*.

But
There is no Number in the signature to specify the last N elements.

**Comment by buzzdecafe** [comment]
that's not the signature's job. The signature is there to tell you what it takes for input ant what it returns for output, so that you will know how to snap the pieces together. In this case, it takes a function from `'a -> bool`, an `'a list` and returns an `'a list`. That the returned `'a list` may (or may not) have fewer elements is not an important consideration in the signature. 

Consider the signature of `filter :: Filterable f => (a → Boolean) → f a → f a`. Similarly, the returned list (when it's a list) may have fewer elements. But that is not the point.

**Comment by bcowgill** [comment]
Isn't it a lot clearer to say:

Returns a new list excluding all the tailing elements which match the supplied predicate function. It passes each value from the right to the supplied predicate function, skipping elements while the predicate function returns true. The predicate function is passed one argument: (value)*.

There's no need to mention n.

**Comment by bcowgill** [comment]
While experimenting here I notice the drop/Repeats/While family of functions have alternative signatures when String is used for input. May want to add that to the documentation as was done for drop() and dropLast()

R.dropLastWhile :: (Char → Boolean) → String → [Char]
R.dropRepeatsWith :: (Char, Char → Boolean) → String → [Char]
R.dropWhile :: (Char → Boolean) → String → [Char]

maybe they're not really designed as string functions but they do something useful that way.

**Comment by davidchambers** [comment]
> There's no need to mention n.

You're absolutely right. This is no doubt a copy-and-paste error. Would you like to submit a pull request to correct this?

> While experimenting here I notice the drop/Repeats/While family of functions have alternative signatures when String is used for input. May want to add that to the documentation as was done for drop() and dropLast()

A string really is a list of characters in Haskell:

```haskell
Prelude> :t ['a', 'b', 'c']
['a', 'b', 'c'] :: [Char]

Prelude> :t "abc"
"abc" :: [Char]

Prelude> ['a', 'b', 'c'] == "abc"
True
```

This is not the case in JavaScript, as much as we might like it to be. Consider `R.map`, for example:

```javascript
> R.map(R.identity, 'abc')
['a', 'b', 'c']
```

We start with `String` but end with `[String]`. Thus I would argue that `R.map` doesn't support String arguments, so we shouldn't document this behaviour.

`R.drop`, on the other hand, preserves the input type.

`R.dropWhile` and friends fall into the same category as `R.map`. Thus, the fact they do *something* when applied to String arguments is best left undocumented.

**Comment by CrossEye** [comment]
> `R.dropWhile` and friends fall into the same category as `R.map`. Thus, the fact they do *something* when applied to String arguments is best left undocumented.

... and especially leave us free to change this behavior at will, simply based on the implementation.

**Comment by bcowgill** [comment]
Pull request created as suggested by davidchambers.

https://github.com/ramda/ramda/pull/1738
