### ISSUE TITLE
Document `R.chain` supports FantasyLand Chain spec

### ISSUE THREAD

**Issue by yotamDvir** [ramda/ramda#1732]
I see that functions like [`R.lift`](http://ramdajs.com/docs/#lift) and [`R.map`](http://ramdajs.com/docs/#map) can be used with (appropriate) functors satisfying the specifications in [Fantasy-Land](https://github.com/fantasyland/fantasy-land), yet not [`R.chain`](http://ramdajs.com/docs/#chain). Why is this?

**Comment by buzzdecafe** [comment]
`R.chain` works with FL chains. 

http://goo.gl/18QP4V

**Comment by yotamDvir** [comment]
Oh great. Why isn't this written in the documentation though?

**Comment by buzzdecafe** [comment]
absolutely should be
