### ISSUE TITLE
R.all(R.always(false),[]) === true?

### ISSUE THREAD

**Issue by afharo** [ramda/ramda#1734]
Hi, just found out that R.all, no matter the predicate, it always returns `true` for an empty array `[]`.
Is this intended or a bug?

I saw in `test/all.js`
```Javascript
it('returns true for an empty list', function() {
  eq(R.all(T, []), true);
});
```
so I think it is intended but I don't understand why.

Documentation says __`true` if the predicate is satisfied by every element, `false` otherwise__ so I expect that if predicate cannot be satisfied because there are no elements in the array, then predicate isn't satisfied at all => return `false`.

**Comment by TheLudd** [comment]
This is the correct behavior. You can think of it this way: `all` will return `false` if at least one element yields the result `false`. There is no such element in an empty array.

The opposite is true for `any` which will return `true` if at leas one element yields the result `true`, which means that `any`will return `false` for an empty array.

#1380

**Comment by afharo** [comment]
Thanks @TheLudd for your reply!
I think documentation should say it clearer, because it could lead to be misunderstood as _if predicate isn’t evaluated as true by all elements, return false. So, in empty arrays, as predicate isn't evaluated at all, it leads to a false_.
It's difficult to find a proper phrase to be as clearer as possible with this one. But I understand the reason. Closing my MR :smiley:

**Comment by benperez** [comment]
> I think documentation should say it clearer, because it could lead to be misunderstood

I think if anything, the "false otherwise", should be removed.

```diff
- true if the predicate is satisfied by every element, false otherwise
+ true if the predicate is satisfied by every element.
```

**Comment by CrossEye** [comment]
> I think if anything, the "false otherwise", should be removed.

Possibly, but I don't think this would be enough.  This comes up frequently enough that we should probably be more explicit, and even offer a link to https://en.wikipedia.org/wiki/Vacuous_truth for those really curious.

**Comment by benperez** [comment]
OK, I can open a PR to update the docs for `all` and `any` to be more explicit. Are there any other functions that should be included in this list? Here are the functions I'd consider related:

1. `R.any`
2. `R.all`
3. `R.none`

**Comment by CrossEye** [comment]
That's all I can think of.
