### ISSUE TITLE
reduceWhile

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#1737]
any interest in `reduceWhile`? This is simply sugar for `reduce` using a passed-in predicate to detremine whether to short-circuit (i.e. `reduced(acc)`) or keep evaluating. I think it might be nicer than the current somewhat awkward use of `reduced`.

Also, should the predicate be `x -> Bool` or `(acc, x) -> Bool`? I have my opinion; I'm curious if anyone sees reasons to favor one or the other.

**Comment by CrossEye** [comment]
I'd like to include it, and absolutely would prefer `(acc, x) -> Bool`

**Comment by asaf-romano** [comment]
^^. For most of the use case I can imagine, the condition is based on the accumulator.

**Comment by buzzdecafe** [comment]
agreed, i'll put a pr together
