### ISSUE TITLE
Proposal for circular indexes

### ISSUE THREAD

**Issue by kahless** [ramda/ramda#1740]
I see that the new function R.clamp() is added in ramda-0.20.0:
http://ramdajs.com/0.21.0/docs/#clamp
https://github.com/ramda/ramda/blob/v0.21.0/src/clamp.js

I want to propose another tiny function for similar tasks. In my practice this function is used as frequently as R.clamp(). It is a function to implement a circle of indexes (list indexes for example). This function calculates an increment/decrement for an index so that it must not exceed some maximum and minimum. And if it does, it will be counted from the opposite border. It is a wired explanation, so I hope the code below will make everything clear.

```
// circle :: Number -> Number -> Number -> Number
const circle = R.curry( (length, step, i) => {
    const j = i + step;
    return j < 0
        ? j + length
        : j >= length
            ? j - length
            : j;
} );

// For increment
circle(3, 1, 0) //=> 1
circle(3, 1, 1) //=> 2
circle(3, 1, 2) //=> 0 — passed over the maximum

// For decrement
circle(3, -1, 2) //=> 1
circle(3, -2, 1) //=> 2 — passed over the minimum

// For multiple increments
const c = circle(3, 1);
c(i); // Increment some index
```

What do you think, do we need it in ramda? Perhaps we should replace "length" parameter with a pair ("min" and "max").

**Comment by CrossEye** [comment]
I'd really like to hear more about _why_.  While I can't say I've _never_ had a need for such, I think it's been relatively rare.  How would you expect to use it, and why is it important enough to have a dedicated function when `mathMod(step + i, length)` should do the same thing?

**Comment by kahless** [comment]
Sometimes there are cyclically linked elements on the page, for example if a cursor must return to the beginning of the list after it reaches it's ending. And I need a function to get the next index of an element to move cursor to.

Now I have a task to implement 3 sliders that allows to set a number in a range 1–100 with step 10. The sum of all three values must always be 100. According to the task, I need to move the next slider to compensate any change and reach this 100 in sum. So I need a function to get the index of the next slider to move.

But you are right. `R.mathMod(step + i, length)` is enough. I apologize that I was not smart enough to see this solution.

**Comment by CrossEye** [comment]
>  I apologize that I was not smart enough to see this solution.

Don't be silly.  There are well over two hundred functions in Ramda.  I don't know if anyone knows them all in depth, or would think of the best one for any circumstance.

I'm glad that one would work for you.  Thanks for your participation!
