### ISSUE TITLE
Make a second on the website for common formulas

### ISSUE THREAD

**Issue by krainboltgreene** [ramda/ramda#1744]
Hey! Long time (4 months) lover of ramda.js, and I find myself with a fun little function that I don't think should be added to ramda but should be available to others if they need the same thing.

So as I propose a new tab on the website for function frankensteins that are too easy to be added to ramda, but too small for a library. "Examples" or "Practical" or "Recipies"?

Thoughts?

**Comment by svozza** [comment]
You can stick it in the [Cookbook](https://github.com/ramda/ramda/wiki/Cookbook) if you want?

**Comment by buzzdecafe** [comment]
Thanks for the kind words. We have a [Cookbook](https://github.com/ramda/ramda/wiki/Cookbook)

**Comment by krainboltgreene** [comment]
I know cookbook exists, but it's not very "public" in the same way as the website :(

**Comment by buzzdecafe** [comment]
i'm all ears if you want to raise the profile of the cookbook stuff. what do you have in mind?

**Comment by pauloliver** [comment]
:+1: for a tab on the site with examples.

I think putting the cookbook a bit more out in the open is a good idea.

**Comment by CrossEye** [comment]
Perhaps we could simply post the Cookbook to the site?  It's simply Markdown, after all.  I have several other pages I'd like to do this with.  That might make REPL integration a bit tougher, though.

**Comment by buzzdecafe** [comment]
> That might make REPL integration a bit tougher

one problem at a time. I'm in favor of promoting the cookbook on ramdajs.com ASAP and integrating with repl later.

**Comment by taylonr** [comment]
> >That might make REPL integration a bit tougher

>one problem at a time. I'm in favor of promoting the cookbook on ramdajs.com ASAP and integrating with repl later.

I think integrating with the REPL won't be that hard...or at least one option won't be.

For example, I played around with a couple libraries tonight and figured out this code:
```

'use strict';

let R = require('ramda');
let gfm = require('gfm-code-blocks');
let fs = require('fs');

var str = fs.readFileSync('Cookbook.md', 'utf8');

let urlEncoder = R.pipe(
    encodeURIComponent,
    R.concat('http://ramdajs.com/repl/#?code=')    
)

console.log(urlEncoder(gfm(str)[8].code));
```

That outputs a URL encoding string for example #9 from the Cookbook (Get and Object's Method Names).

The URL is: http://ramdajs.com/repl/#?code=%2F%2F%20%20methodNames%20%3A%3A%20Object%20-%3E%20%5BString%5D%0Avar%20methodNames%20%3D%20R.compose(R.keys%2C%20R.pickBy(R.is(Function)))%3B%0A%0Avar%20obj%20%3D%20%7B%0A%20%20foo%3A%20true%2C%0A%20%20bar%3A%20function()%20%7B%7D%2C%0A%20%20baz%3A%20function()%20%7B%7D%2C%0A%7D%3B%0A%0AmethodNames(obj)%3B%20%2F%2F%20%3D%3E%20%5B'bar'%2C%20'baz'%5D

I'm not exactly sure where to do this in the code, or I'd be submitting a PR and not just pasting code in this issue.

**Comment by buzzdecafe** [comment]
ok, i think we have a direction and some ideas; i will move this issue to ramda.github.io and let's proceed form there

**Comment by buzzdecafe** [comment]
This issue was moved to ramda/ramda.github.io#78
