### ISSUE TITLE
Documentation for flatten could be improved

### ISSUE THREAD

**Issue by bcowgill** [ramda/ramda#1745]
flatten List 
[a] → [b]

might be better as 
[ a | [a] ] → [a]

the first signature seems to indicate the underlying type of the array contents is changed

**Comment by buzzdecafe** [comment]
it might make more sense to emulate the [Haskell definition](http://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Tree.html#v:flatten), viz. `flatten :: Tree a -> [a]`.
