### ISSUE TITLE
equals should compare value types after value.equals check

### ISSUE THREAD

**Issue by amelon** [ramda/ramda#1746]
Actually, I'm using mongodb with mongoose.
Mongodb ObjectId handle .equals function that is compatible with R.equals function (in previous version) 

``` js
var x = ObjectId()
var y = x.toString()

x.equals(y) // => true

// with previous version of ramda I could do
R.equals(x, y) // => true

// with version 0.21
R.equals(x, y) // => false
```

This is due to type comparison 

``` js
function _equals(a, b, stackA, stackB) {
  if (identical(a, b)) {
    return true;
  }

  if (type(a) !== type(b)) { // type comparison here
    return false;
  }

  if (a == null || b == null) {
    return false;
  }

  if (typeof a.equals === 'function' || typeof b.equals === 'function') {
    return typeof a.equals === 'function' && a.equals(b) &&
           typeof b.equals === 'function' && b.equals(a);
  }
...
```

What I propose is to move type checking after .equals check

``` js
function _equals(a, b, stackA, stackB) {
  if (identical(a, b)) {
    return true;
  }

  if (a == null || b == null) {
    return false;
  }

  if (typeof a.equals === 'function' || typeof b.equals === 'function') {
    return typeof a.equals === 'function' && a.equals(b) &&
           typeof b.equals === 'function' && b.equals(a);
  }

  if (type(a) !== type(b)) { // type comparison here
    return false;
  }


...
```

**Comment by buzzdecafe** [comment]
this makes sense to me; if the user defines `equals` on their objects, we should favor that

**Comment by davidchambers** [comment]
`'123'` and `new ObjectId('123')` are not equivalent, just as `'123'` and `new String('123')` are not equivalent. They respond differently to `typeof`, to name just one difference. As a result, I consider the `equals` method in question unsound. That said, Ramda should assume an `equals` method to be sound, if present, so I'm indifferent to the proposed change.

**Comment by CrossEye** [comment]
I don't think this would solve @amelon's issue.  Presumably it would still fail equality when you hit this line:

```js
          typeof b.equals === 'function' && b.equals(a);
```

Nonetheless it's an interesting proposal.  The question is whether this should be moved to more firm control of the users as proposed, allowing, say, the possibility of

```
equals(new Rectangle(4, 4), new Square(4)); //=> true
```
 if `Rectangle` and `Square` have agreeable `equals` methods, or whether we simply don't want to raise all the possibilities inherent in co- and contravariant notions of equality.

I think I'm leaning towards this, but I'm afraid someone could easily show me an example that kills the notion entirely.  Does anyone have one of those handy?  @joneshf? @scott-christopher?

**Comment by scott-christopher** [comment]
I have no issue in trusting the `equals` method of the given two objects, providing it exists on both. For example, the two instances may share some common prototype hierarchy which is to be used for comparison, despite producing a different `typeof` value for each. I think we just need to set the expectation that `equals(a, b) === equals(b, a)` should hold.

On a side note, I don't know why we check whether `equals` is a method twice:
```diff
-  if (typeof a.equals === 'function' || typeof b.equals === 'function') {
-    return typeof a.equals === 'function' && a.equals(b) &&
-           typeof b.equals === 'function' && b.equals(a);
-  }
+  if (typeof a.equals === 'function' && typeof b.equals === 'function') {
+    return a.equals(b) && b.equals(a);
+  }
```

**Comment by joneshf** [comment]
> I think I'm leaning towards this, but I'm afraid someone could easily show me an example that kills the notion entirely. Does anyone have one of those handy?

Seems fine to me :+1: From the fantasy-land perspective, it's undefined what happens if it's a different type, so do whatever.

**Comment by CrossEye** [comment]
>  I think we just need to set the expectation that `equals(a, b) === equals(b, a)` should hold.

Right, and I was concerned that someone would come up with examples that demonstrated how difficult that is to achieve in the presence of inheritance.  There are potential issues there, but I would rather leave that in the hands of users than in our own.

> On a side note, I don't know why we check whether equals is a method twice:

Good catch.  Regardless of anything else here, we should fix that.

> From the fantasy-land perspective, it's undefined what happens if it's a different type, so do whatever.

True, although there is that fussy parenthetical, "returning false is recommended."  :smile:

**Comment by amelon** [comment]
For my use case I much prefer

````js
if (typeof a.equals === 'function' || typeof b.equals === 'function') {
   return typeof a.equals === 'function' && a.equals(b) &&
           typeof b.equals === 'function' && b.equals(a);
} 
````

that

````js
if (typeof a.equals === 'function' && typeof b.equals === 'function') {
  return a.equals(b) && b.equals(a);
}
````

But I agree that according to fantasy-land, the second one fits better :(

**Comment by ascartabelli** [comment]
Just curious here, as I recently discussed `equals` in #1691.
If the goal is leaving the matter in the hands of the user, and on that I strongly agree by the way, I think it should be better to go along these lines and trust the implementations:
```javascript
// pseudocode assuming the existence of `hasMethod`
var hasEquals = hasMethod("equals");
var equalsInA = hasEquals(a);
var equalsInB = hasEquals(b);

if (equalsInA && equalsInB) {
    return a.equals(b) && b.equals(a);
} else if (equalsInA) {
    return a.equals(b);
} else if (equalsInB) {
    return b.equals(a);
}

// ...
```

**Comment by davidchambers** [comment]
> On a side note, I don't know why we check whether `equals` is a method twice:
>
> ```diff
> -  if (typeof a.equals === 'function' || typeof b.equals === 'function') {
> -    return typeof a.equals === 'function' && a.equals(b) &&
> -           typeof b.equals === 'function' && b.equals(a);
> -  }
> +  if (typeof a.equals === 'function' && typeof b.equals === 'function') {
> +    return a.equals(b) && b.equals(a);
> +  }
> ```

Currently we dispatch if *either* argument has an `equals` method. This patch would have us dispatch if *both* arguments have `equals` methods. I don't know which behaviour is preferable.

**Comment by buzzdecafe** [comment]
IMO we should support FL and not arbitrary user objects; in which case `a.equals(b) && b.equals(a)` must hold

**Comment by ascartabelli** [comment]
> Currently we dispatch if either argument has an equals method. This patch would have us dispatch if both arguments have equals methods. I don't know which behaviour is preferable.

@davidchambers Why do you see different behaviours?
I'm a bit out of order today, but it seems to me that the outcome would be always the same, with the proposal of @scott-christopher being more efficient and readable.

**Comment by davidchambers** [comment]
Here's a pathological example which demonstrates the difference, @ascartabelli:

```javascript
function NeverEqual() {}
NeverEqual.prototype.equals = R.F;

R.equals(new NeverEqual(), {});  // false currently; true after applying Scott's patch
```

Currently if either value has an `equals` method, the other value *must* also have an `equals` method in order for the values to be considered equal. Scott's change would mean that if only one of the two values has an `equals` method we would fall back to object equality.

Reasoning about this code is not easy!

**Comment by ascartabelli** [comment]
Of course, @davidchambers, now I see it clear as day.

> Reasoning about this code is not easy!

It actually was this time! There was even no boolean logic intricacy whatsoever.
I'm really starting to have serious issues dealing with Mondays...

**Comment by CrossEye** [comment]
> Here's a pathological example which demonstrates the difference.

I'm pretty sure that we discussed something like this once before, probably when this `equals` was under construction.  But I feel as though last time I saw examples like that was when reading Josh Bloch's _Effective Java_, many years ago.  Nice clear example, as always, David.

**Comment by anodynos** [comment]
`R.equals('', new String('')) === false` 

whereas 

`_.isEqual('', new String('')) === true`

I find the latter more consistent. Probably is cause `(new String('')).equals === undefined` which is a shame, but is an easy way to compare `new String('hello')` and 'hello' in Ramda ?

**Comment by CrossEye** [comment]
@anodynos: Why does that seem more consistent to you?

**Comment by anodynos** [comment]
Semantically these two values are the same - they both carry the string `''` or 'hello world'. 
So they should be `R.equal`. 

If I wanted to be super strict, I could use `===`, but any `utilityBelt.equals` should bring me the confidence of comparing user level things to be such (`equal`, `empty`, etc). 

As an overall comment & IMHO, although I love Ramda's functional purity, think  is missing a lot from lodash's existing consistency on some simple things like these. 

I went on to create Ramdash to bridge some of imminent these gaps, and it is a chore - if you just check the incompatibilities in [`isEmpty`](https://github.com/anodynos/ramdash/blob/master/source/code/ramdash.coffee#L81-L91)

**Comment by davidchambers** [comment]
> Semantically these two values are the same - they both carry the string `''` or `'hello world'` or whatever. So they should be `R.equal`.

It depends on how one defines equivalence. For me, two values are equivalent if they are interchangeable. `''` and `new String('')` are not interchangeable:

```javascript
> typeof ''
'string'

> typeof new String('')
'object'
```

**Comment by anodynos** [comment]
I see your point, it does depends on how one defines equality - Ramda has opted for `equals` to be a strict check, my argument is that there needs to exist a more loose equals.

**Comment by Frikki** [comment]
Two questions: say I have an entity type `Player` with an `id` and a `name`, then I also have a an entity type `Subject` with an `id` and a `name`. Assume that the `id` of `Player` is `1` and the `id` of `Subject` is also `1`, and the `name` of `Player` is `foo` and the `name` of `Subject` is also `foo`. Are these two instances equal? What if the `id` of type `Player` was string `'1'`, would they still be equal?

What I mean is: are they conceptually or objectively equal?

As @davidchambers  illustrates, `typeof ''` is *not* equal to `typeof new String('')`.

**Comment by anodynos** [comment]
IMHO a String and a number should be equal only by user casting one or the other, not automatically. On the other hand your Player `{id:1, name: 'foo'}` and Subject `{id:1, name: 'foo'}` are indeed equal, unless you are comparing their ancestors (prototype chain) also. Check my implementation of my extended `isEquals` https://github.com/anodynos/uBerscore/blob/master/source/code/objects/isEqual.coffee that covers this case & more and gives rise to `isIqual` https://github.com/anodynos/uBerscore/blob/master/source/code/objects/isIqual.coffee etc.
