### ISSUE TITLE
Proposal to have R.split for string arrays

### ISSUE THREAD

**Issue by Risto-Stevcev** [ramda/ramda#1747]
I think that it would be useful to have something like `R.split` for string arrays, something like:

``` js
split(';', ['foo', 'bar', ';', 'baz', ';', 'qux', 'norf'])
// [['foo', 'bar'], ['baz'], ['qux', 'norf']]
```

Since strings are also lists, maybe `R.split` could be generalized to the above?

**Comment by buzzdecafe** [comment]
i agree, i am really surprised it doesn't exist already

**Comment by CrossEye** [comment]
I would rather have a function such as `splitWhenever` or some such:

```js
// splitWhenever:: (a -> Boolean) -> [a] -> [[a]]
splitWhenever(equals(';'), ['foo', 'bar', ';', 'baz', ';', 'qux', 'norf']);
//=> [['foo', 'bar'], ['baz'], ['qux', 'norf']]
```

I could see a very similar `breakWhenever`, with a slightly different signature:

```js
// breakWhenever:: (a -> a -> Boolean) -> [a] -> [[a]]
const differentFirst = (a, b) => a.charAt(0) != b.charAt(0);
breakWhenever(differentFirst, ['A1', 'A42', 'B6', 'C17', 'C6', 'C5', 'A3']);
//=> [['A1', 'A42'], ['B6'], ['C17', 'C6', 'C5'], ['A3']]
```

This just seems more powerful at little extra cost.

**Comment by buzzdecafe** [comment]
@CrossEye i think that could be `splitWith`

**Comment by CrossEye** [comment]
Yes, or some other `splitPreposition`.  But you're right, we haven't used `With` and this would match our convention.
