### ISSUE TITLE
Question: map method for Identity

### ISSUE THREAD

**Issue by k33g** [ramda/ramda#1750]
Why there is no `map` method with `identity` ? 
I would like to do something like this:
```javascript
let incrementBy2 = v => v + 2;
let multiplyBy5 = z => z * 5;
let divideBy3 = a => a / 3;

let computeWith = (x) => R.identity(x)
  .map(incrementBy2)
  .map(multiplyBy5)
  .map(divideBy3);
```

what I missed (misunderstood) with `identity`?

thx 😄

**Comment by buzzdecafe** [comment]
`R.identity` is a plain identity function, not a functor-factory

**Comment by CrossEye** [comment]
`identity` is used when you need to supply a transformation function, but in fact you simply want to pass the value along unchanged.  It sounds like a strange idea, but it comes up surprisingly often.  

To do what you're looking for in Ramda, you would just do:

```js
const computeWith = pipe(incrementBy2, multiplyBy5, divideBy3);
computeWith(7) ; //=> 15   == ((((7 + 2) * 5) / 3)
```

**Comment by k33g** [comment]
@buzzdecafe @CrossEye I'm going to meditate on it and come back later
thx 😄

**Comment by k33g** [comment]
@buzzdecafe ok, I did my homework and I actually did not understand the difference between functor function ans functor type.
thx @buzzdecafe @CrossEye for comments 👍

**Comment by CrossEye** [comment]
You might find this interesting:  [Why using `_.chain` is a mistake.][nc].


  [nc]: https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba
