### ISSUE TITLE
groupWith documentation example is incorrect

### ISSUE THREAD

**Issue by bcowgill** [ramda/ramda#1751]
documentation:
groupWith(R.equals, [0, 1, 1, 2, 3, 5, 8, 13, 21])
   // [[0], [1, 1], [2, 3, 5, 8, 13, 21]]

reality:
				it('should group consecutive duplicates with each other', function () {
					const result = R.groupWith(R.equals, [0, 1, 1, 2, 3, 5, 8, 13, 21]);
					console.error('dups', JSON.stringify(result));
					expect(result)
						.to.deep.equal([[0], [1, 1], [2], [3], [5], [8], [13], [21]]);
				});

**Comment by svozza** [comment]
This was fixed here in #1729 .

**Comment by CrossEye** [comment]
... and will be included in the next release.
