### ISSUE TITLE
Ramda REPL Suggestion: Make mid-line adjustable

### ISSUE THREAD

**Issue by thurt** [ramda/ramda#1752]
So the input side can be wider and the output side thinner

**Comment by CrossEye** [comment]
Sure.  A PR would be welcome!

**Comment by thurt** [comment]
@CrossEye I didn't see any repl files in the ramda/ramda repo? so I made a PR in davidchase/ramtuary

**Comment by thurt** [comment]
Looks like I should maybe move the PR over here (ramda/ramda.github.io) ?

**Comment by buzzdecafe** [comment]
> Looks like I should maybe move the PR over here ramda/ramda.github.io ?

Yes please, and thanks
