### ISSUE TITLE
document handling of duplicate keys in R.fromPairs

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1753]
We should state whether first wins or last wins.

**Comment by CrossEye** [comment]
Should we?  Is that part of the contract we want to enforce or just an accident of the implementation that we would rather not have users depend upon?

**Comment by davidchambers** [comment]
Are you suggesting the behaviour is best left unspecified? If so, I disagree. If we guarantee consistent handling of collisions, users are then free to apply `R.reverse` if desired before applying `R.toPairs`.

**Comment by CrossEye** [comment]
I'm simply bringing it up.  I was hurrying through issues after being away from Ramda more than a week, and I didn't have time to think it through carefully.  But yes, I did think it was an interesting possibility to leave it unspecified.  That's often my go-to solution when there's no clear-cut advantage of one choice over another.

But I think I agree that this is not a case of "don't depend on this".  So, yes, after finding a few minutes for reflection, I'm :+1:.

**Comment by davidchambers** [comment]
Okay, so what should it be? First wins or last wins? Has another Ramda function set a precedent? Failing that, I suggest last wins to match the behaviour of [`Map`][1]:

```javascript
> new Map([['x', 1], ['x', 2]])
Map {"x" => 2}
```


[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by CrossEye** [comment]
Yes, I think that last-in wins is conceptually simpler, as well as easier to implement.

**Comment by buzzdecafe** [comment]
i followed a similar path as @CrossEye, viz. from "do we *want* to proclaim that?" to "i guess so".

:cow2:
