### ISSUE TITLE
mean based on reduce?

### ISSUE THREAD

**Issue by jondot** [ramda/ramda#1754]
Hi,
Do you consider aggregate operations to be terminal - which is why they take a prematerialized list of items, or should they also be streaming? if so, how does this implementation of `mean` look like?

``` javascript
R.reduce((a,b)=>{ return [((a[0]*a[1])+b)/(a[1]+1), a[1]+1 ] }, [0.0, 0])
```

And:

``` javascript
> R.map((x)=>x[1], R.reduce((a,b)=>{ return [((a[0]*a[1])+b)/(a[1]+1), a[1]+1 ] }, [0.0, 0]))([1,2,3])
3
```

**Comment by CrossEye** [comment]
I tend to think of `reduce` as terminal.  That does not prevent you from writing something like that (altered slightly):

```js
const avg = map(head, reduce(
  (a, b) => [((a[0] * a[1]) + b)/(a[1] + 1), a[1] + 1 ], [0.0, 0])
);

avg([1, 2, 3, 4]); //=> 2.5
```

But I would probably feel better using `scan` for this, which seems more closely related:

```js
const avg2 = pipe(                    // ... Input [1, 2, 3, 4]
  scan(add, 0),                       // [0, 1, 3, 6, 10] 
  tail,                               // [1, 3, 6, 10]
  converge(divide, [last, length]),   // 10 / 4
);                                    // ... Output 2.5

avg2([1, 2, 3, 4]); //=> 2.5
```

The output of `scan` already intrinsically contains the `length` you need here, but it would be easily queried for other desired parameters such as `min` or `max`, or even `mode`, and this could be done  stream-like on every addition to the data set or once when it's complete.

**Comment by jondot** [comment]
Thanks, this looks like another lovely way to do it 👍 
Do you think any of these belong within ramda - in other words, is this worth a PR or should these live outside of ramda?

**Comment by CrossEye** [comment]
My initial thought is that these would do well in the [Cookbook][cb].  While they could be useful, they don't seem common enough in the way that the few math-related functions in Ramda are.  But if you think they belong there, feel free to argue the point.


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
