### ISSUE TITLE
Special case R.concat for Arrays

### ISSUE THREAD

**Issue by Bradcomp** [ramda/ramda#1755]
Currently: 
```
R.concat([1, 2, 3], 4);  
=> [1, 2, 3, 4]

R.concat(R.concat([1], 2), 3);
=> [1, 2, 3]

R.concat([1], R.concat(2, 3));
=> Throws!
```
Given that we special case arrays for `map`, `filter`, etc., the same should be done here.  

`R.concat([1], 2)` Should throw an error.

**Comment by buzzdecafe** [comment]
thanks @Bradcomp this needs to be fixed

`R.concat([1, 2, 3], 4);  => [1, 2, 3, 4]` :-1:

`R.concat(R.concat([1], 2), 3); => [1, 2, 3]` :-1: 

`R.concat([1], R.concat(2, 3)); => Throws!` :+1:

**Comment by Bradcomp** [comment]
I would be willing to PR this with possibly a little guidance. Would the rule be something like: 
If the first arg is a JavaScript array, and the second arg is not a JavaScript array, throw an error?
