### ISSUE TITLE
Hard to analyze ramda (functional placeholder)

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#1760]
So, Tonic is a big user of Ramda. Unfortunately, some of our analysis code breaks when using ramda itself.

The problem is with @@functional/placeholder. Basically, it is possible to funnel ramda objects into code that expects these properties to have special meanings, and then things get confused. This is really a specific version of the more general "if a user can more or less control what goes _into_ ramda, things can break if they figure out how to pass in a functional placeholder". Now, even though users, to simplify, can only really pass in JSON strings, they can still create the situation by doing:

{
 @@functional/placeholder: ...
}

Of course, this problem would not exist if object identity were used (and thus the user wouldn't be able to create this situation):

R.__ = { };

isPlacholder() = === R.__;

Here, theres no way to get something to parse to that. However, I imagine the idea here is to prevent different versions of Ramda not being able to work together? I'm curious if there'd be consideration for adding a switch or something to use object identity instead of meaningful keys.

**Comment by davidchambers** [comment]
> I imagine the idea here is to prevent different versions of Ramda not being able to work together?

Yes, and to have the placeholder work cross-frame and with the [vm][1] module, and to allow other libraries (such as Sanctuary) to use `R.__`, and to allow Ramda to accept placeholders defined by other libraries.


[1]: https://nodejs.org/api/vm.html

**Comment by CrossEye** [comment]
All of what David said, and one more thing: FP is about values, not references.  We always try to think about equality in a way that has nothing to do with where something is stored in memory.

I'm curious about the basic problem, though.  Is this a problem that Tonic has with dealing with Ramda in general, or something that might happen  only on the off-chance that someone creates something like `{a: 1, b: 2, '@@functional/placeholder': true, c: 3}`?  And if it's the latter is this a problem that you've run across in the real world or only noticed might be possible?  When does this happen?

**Comment by tolmasky** [comment]
It is in fact when users happen to create objects with that magic key. It
actually happens frequently... When users require Ramda :)

On Thursday, May 5, 2016, Scott Sauyet <notifications@github.com> wrote:

> All of what David said, and one more thing: FP is about values, not
> references. We always try to think about equality in a way that has nothing
> to do with where something is stored in memory.
>
> I'm curious about the basic problem, though. Is this a problem that Tonic
> has with dealing with Ramda in general, or something that might happen only
> on the off-chance that someone creates something like {a: 1, b: 2,
> '@@functional/placeholder': true, c: 3}? And if it's the latter is this a
> problem that you've run across in the real world or only noticed might be
> possible? When does this happen?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ramda/ramda/issues/1760#issuecomment-217332582>
>


-- 
Francisco Tolmasky
www.tolmasky.com
tolmasky@gmail.com

**Comment by CrossEye** [comment]
Ok, can you describe more what the issue is?  I'm clearly not following what the problem is.  Do you have similar problems if someone creates a property named `'@@foo/bar'`?
