### ISSUE TITLE
R.equals does not compare inherited object properties

### ISSUE THREAD

**Issue by xorcus** [ramda/ramda#1769]
```
// Ramda 0.21.0
var a = Object.create({ value: 1 });
var b = Object.create({ value: 2 });
R.equals(a, b); // returns true, but should return false, because a.value !== b.value
```

**Comment by CrossEye** [comment]
I'm not sure there is a great fix for that.

```js
class Rectangle {
  constructor(w, h) {
    this.width = w; this.height = h;
  }
  area() {
    return this.width * this.height;
  }
}

class Square extends Rectangle {
  constructor(s) {
    super(s, s);
  }
}

equals(new Rectangle(5, 5), new Square(5)); //=> true
```

Do you think that should return `false`?

We tend to think about value equality, with deep nesting on objects, but ignoring prototypal hierarchies.  I think it would get pretty ugly to try to incorporate them.

**Comment by xorcus** [comment]
Thank you for the comment. In short, I would expect `R.equals` to compare **all** enumerable and not just all **own** enumerable properties when comparing objects.

Aside the syntactic sugar, your question to me has a completely different topic - switching to a discussion about specific constructor functions. More precisely, I would expect `R.equals` relating to `typeof` (object) and not relating to `instanceof` (constructor functions).

If one wanted to check whether an object has a specific constructor function, probably [`R.is`](http://ramdajs.com/0.21.0/docs/#is) would be the choice. So, if one wanted to check whether both `r` and `s` are rectangles, the test would be: `R.is(Rectangle, r) && R.is(Rectangle, s)`.

On the other hand, JavaScript does not know about those types. For JavaScript, they are just plain objects (in the `typeof` sense), while the specific constructor functions (`instanceof`) represent our own creation. If one tests `typeof r === typeof s`, the result would most certainly be `true`. Therefore, considering the JavaScript language specifics, and treating objects as "bags" of properties (`typeof x === 'object'`), I would expect `R.equals()` to return `true` in your example. If you defined `equals` as an alias for `R.equals`, then yes. I would expect it to return `true`.

**Comment by svozza** [comment]
I think we have to be pragmatic here, `R.equals` is slow enough already without having to traverse the prototype chain as well.

**Comment by CrossEye** [comment]
It just seems there would be all sorts of odd cases.  Do we care about _where_ in the prototype chain such things are defined?  Isn't there a difference between an object that defines a property itself and one that has it defined in the prototype object of its prototype object?  Dealing with such cases seems pretty intractable.

```js
const x = {value: 1};
const a = Object.create(x);
const b = {value: 2};
equals(a, b); //=> Presumably false
x.value = 2;
equals(a, b) //=> What would you want here?
```

**Comment by xorcus** [comment]
@svozza: If one decides to use inheritance, they must accept the incurred performance penalty. On the other hand, I believe there is no performance penalty for those who do not use inheritance, because the inherited `Object.prototype` does not have any enumerable properties - hence, there's nothing to traverse over. The control is still in the hands / decisions of the developer.

`var count = 0; for (var key in Object.prototype) count++; console.log(count); // prints zero`
`var count = 0; for (var key in {}) count++; console.log(count); // prints zero`

@CrossEye: From my point of view, nothing odd there. It does not matter where the property comes from. The only important thing would be that it is there and that it is enumerable. In this example, it is important to remark that although `x` is const, the object it refers to is **not** [frozen](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), so its properties can be modified. Once the `value` property is set to the same value in both objects, I would expect `R.equals` to return `true`.

In your example, when calling `equals` the second time, `a.value === b.value`, so I would expect the result to be `true`. The same would hold `true` also if you set `a.value = 2`, leaving the "hidden" `x.value` originally set to `1`. JavaScript property lookup goes down the chain only to the first object that defines the property (regardless of the property's value, may as well be set explicitly to `undefined`, and it will still hide the inherited property values)

**Comment by CrossEye** [comment]
To me, there are problems I just don't particularly like thinking about, but once you start dealing with these questions you need to take on:

```js
var x = {a: 1}, y = {a: 1};
x.b = y; y.b = x;
equals(x, y) //=> ???
```

Or

```js
equals({x: document.createTextNode('foo')}, {x: document.createTextNode('foo')}); //=> ???
```

or 

```js
equals({nodes: document.querySelectorAll('div')}, {nodes: document.querySelectorAll('div')}) 
//=> ???
```

It just seems really hairy to me.

**Comment by paldepind** [comment]
@xorcus 

> On the other hand, I believe there is no performance penalty for those who do not use inheritance, because the inherited `Object.prototype` does not have any enumerable properties - hence, there's nothing to traverse over. The control is still in the hands / decisions of the developer.

You'd still have to traverse the prototype chain to figure that out. If doing that has any significant performance penalty for plain objects I don't know. But if you can show that there is no impact on performance then I don't see what we would _loose_ by making this change.

**Comment by CrossEye** [comment]
@xorcus:

I think I've finally figured out what's bothering me with this.  I've been coming up with a number of scenarios, but none of them struck at the core of my issue with this notion, and I didn't know why.  The reason is that I would like a simple invariant to be true.  If we use `a ≍ b` to mean `equals(a, b); //=> true`, then 

> `x ≍ y` should imply `f(x) ≍ f(y)` for any function `f`

But here's an example where this would fail if we extend `equals` this way:
```js
function deleteY(obj) {
  delete obj.y;
  return obj;
}

const a = Object.create({x: 1, y: 2})
const b = Object.create({x: 1, y: 3})
a.y = 4;
b.y = 4;

equals(a, b); //=> true
equals(deleteY(a), deleteY(b)); //=> false
```

It's not clear to me if we already have such cases.  We might.  It seems to me that if we check for deeper property equality, we have to go all the way and test the entire prototype tree and make sure that every property at the same level has the same value.  But that also feels wrong, because, of course, most commonly we simply wouldn't care.  It just seems fraught with complexity.

**Comment by davidchambers** [comment]
> `x ≍ y` should imply `f(x) ≍ f(y)` for any function `f`

If this is the goal, we can demonstrate a failure with a less contrived example:

```javascript
function Point(x, y) {
  this.x = x;
  this.y = y;
}
Point.prototype.toString = function() {
  return 'new Point(' + this.x + ', ' + this.y + ')';
};

const p = new Point(1, 2);
const q = {x: 1, y: 2};

R.equals(p, q);  // => true
R.equals(String(p), String(q));  // => false
```

**Comment by xorcus** [comment]
@CrossEye I tend to agree regarding `x ≍ y` and `f(x) ≍ f(y)` invariant, but only for a pure function `f` (without any side-effects). The example by @davidchambers uses `toString()` method inherited from `Object.prototype` which operates on different data types (polymorphic), so I would treat those two `toString` methods as different functions.

In any event, it is fine for me if you close this issue without making any changes. My need for it comes from sharing (supposedly immutable) data (a list of objects) with multiple UI component instances which (unfortunately) **store their state** in those objects, so I figured I'd pass in blank objects inheriting from the originals, thus preventing the UI components from polluting the shared immutable data. On the other hand, the UI components rely on R.equals for detecting property changes and updating the UI, so when I replace one array of blank objects (inheriting from the immutable data objects) with another array of blank objects inheriting from different data objects, the UI component does not detect the change and does not update the UI.

In the end, the root of my need for `R.equals` to compare the inherited properties comes from the poor design of the UI component and the proper way to deal with it would be to fix the UI component design, so that it does not mutate the objects it does not own (i.e. the objects passed in from the outside world). A workaround could also be to use `R.merge` for creating the new objects instead of creating blank objects inheriting from the originals.

**Comment by CrossEye** [comment]
@davidchambers: Yes, I suppose it was contrived.  My realization was based on `dissoc`, but of course that flattens things and doesn't actually demonstrate the issue.  I simply went with something close to my original thought.

@xorcus: It's an interesting question, which is why I've wanted to keep the debate alive.  There's a lot to say in favor of it, but I can't wrap my head around the potential complexities.

**Comment by paldepind** [comment]
Let me add that if one uses classes from ECMAScript then methods will be non-enumerable ([reference](http://www.2ality.com/2015/02/es6-classes-final.html)).

Thus if we make this change. And someone writes this,

```js
function Point(x, y) {
  this.x = x;
  this.y = y;
}
Point.prototype.toString = function() {
  return 'new Point(' + this.x + ', ' + this.y + ')';
};
```

then makes use of the fact that `R.equals` considers the method. And then later converts it to:

```js
class Point {
  constructor(x, y) {
    this.x = x; 
    this.y = y;
  }
  toString() {
    return 'new Point(' + this.x + ', ' + this.y + ')';
  };
};
```

Then this simple conversion will have resulted in a bug in the users program.

My argument is this: ECMAScript clearly wants methods to be non-enumerable and therefore writing code that deliberately enumerates the methods of "old-school" class instances is a bad idea.

**Comment by xorcus** [comment]
**Remark:** Testing libraries usually implement assertion tests that implement deep equality including the comparison of inherited properties. For example: [jquery/qunit/.../src/equiv.js](https://github.com/jquery/qunit/blob/master/src/equiv.js). Exploring the subject, one may be interested in checking out the other implementations and seeing what they do in their versions of equal (jasmine, chai, etc.). Even if this behavior never makes it into Ramda, one may use the desired third party function for comparison, as an alternative to `R.equal`
