### ISSUE TITLE
Proposal: R.catchP

### ISSUE THREAD

**Issue by neftaly** [ramda/ramda#1770]
I propose a function, `catchP`, for attaching error handling to promise chains. 
```js
const catchP = invoker(1, "catch");
```
```js
const getJSON = R.composeP(
    doSomething,
    R.catchP(handleError),
    fetch
);
```
It seems to invite side-effects, so I don't know if it's actually appropriate for compositions. Promise.catch is an important part of promises, however, which may justify the existence of catchP beyond userland (https://github.com/ramda/ramda/issues/1528#issuecomment-158788298).

**Comment by davidchambers** [comment]
Thanks for the proposal, @neftaly.

I'd actually like to go in the other direction, and remove the existing Promise-specific functions from Ramda. Promises are flawed. See [plaid/async-problem][1] for a better data type. ;)


[1]: https://github.com/plaid/async-problem

**Comment by neftaly** [comment]
Fair enough, I definitely prefer approaches like core.async.
