### ISSUE TITLE
How to modify a subset of data without using variables

### ISSUE THREAD

**Issue by gaurav21r** [ramda/ramda#1772]
Since I'm more familiar with Underscore I'm going to elicit my question in `_ ` but the question is equally valid for Ramda!

If I have some (semi-accurate) data like this:

    var data = {
      people: [
        {name: 'Vishwanathan Anand', age: 46},
        {name: 'Garry Kasparov', age: 52},
        {name: 'Magnus Carlsen', age: 25},
      ],
      computers: [
        {name: 'Deep Blue', age: 26},
        {name: 'Deep Fritz', age: 21},
        {name: 'Deep Thought', age: 28},
      ]
    }

I wish to transform it to

    var data = {
      people: [
        {name: 'Vishwanathan Anand', age: 46, rank: 0},
        {name: 'Garry Kasparov', age: 52, rank: 1},
        {name: 'Magnus Carlsen', age: 25, rank 2},
      ],
      computers: [
        {name: 'Deep Blue', age: 26},
        {name: 'Deep Fritz', age: 21},
        {name: 'Deep Thought', age: 28},
      ]
    }

*Note how only the `people` substructure got `rank`*.

In Underscore, I know I can,

    _.extend({
      computers: _.map(data.people, (p, i) => {
        p.rank = i;
        return p;
      })}, {
        computers: data.computers
      })

But what if I need to do this without using any variables (no more access to `data`!) using underscore's `chain` (Ramda's Currying?) ?

Something like

    _.chain(data).subset('people').map((p, i) => {
      p.rank = i;
      return p;
    })

**NOTE** This is a real problem and not a matter of convenience. I am working on a project that involves creating a sort of environment for functional operators and ***variables*** are not allowed.

It seems Ramda and the like operate on the ***entire*** structure (Array / List). is there any way I can ask it to operate on a substructure while preserving the rest?

**Comment by CrossEye** [comment]
Lenses let you work on parts of a structure.

You can do this like:

```js
const fn = R.over(R.lensProp('people'), R.addIndex(R.map)(R.flip(R.set(R.lensProp('rank')))));
fn(data);
```

But this is a bit obscure.  It is perhaps easier to read if it's not quite as points-free as this:

```js
var pLens = R.lensProp('people');
var rLens = R.lensProp('rank');

const fn = R.over(pLens, R.addIndex(R.map)(
  (person, idx) => R.set(rLens, idx, person)
));

fn(data);
```

You can see this in action at http://goo.gl/q4BGqA

**Comment by asaf-romano** [comment]
You can also try evolve, like this:

```js
const mapIndexed = addIndex(map);
const addRanksToPeople = evolve({
  people: mapIndexed((person, index) => assoc("rank", index, person))
  // Or
  // people: mapIndexed(flip(assoc("rank")))
})
```

You can see both options here: http://goo.gl/OvDcna
