### ISSUE TITLE
map(object) performance could be improved

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1773]
http://goo.gl/CIbMkr

I get 0.4 in Chrome ; 0.55 in Firefox.

**Comment by CrossEye** [comment]
I would have no problem at all adding that optimization.

**Comment by asaf-romano** [comment]
Did an awful mistake in the initial script. numbers + link updated.

**Comment by asaf-romano** [comment]
Couple of notes:
1. This turned out during a profiling I did for a project that uses applySpec (which calls map) extensively. I think that at least in V8 some of the overhead is a result of very short-lived XWrap objects GC collecting in _reduce. The other issue is that the object is looped twice (keys, _reduce).
2. It's not just ``map``. This pattern is repeating in few other functions (e.g. filter, mapObjIndexed).
