### ISSUE TITLE
Proposal: lensPath should error on non-list input.

### ISSUE THREAD

**Issue by mLuby** [ramda/ramda#1778]
Since lensPath's type signature is `[String] → Lens s a` multiple arguments should be rejected. 

1. good: `view(lensPath(['a', 'b']), {a: {b: 2}}) // 2`
2. bad: `view(lensPath('a', 'b'), {a: {b: 2}}) // {b: 2}`
3. better: `view(lensPath('a', 'b'), {a: {b: 2}}) // Error: lensPath input must be a list`
4. might be necessary for backwards-compatibility but not great: `view(lensPath('a'), {a: {b: 2}}) // {b: 2}`
5. bad: `view(lensPath('ab', 'cd'), {ab: {cd: 2}}) // undefined` because lensPath looks at `'ab'[0]`

I'm happy to write a PR for this if people think it's a good idea.

Related to https://github.com/ramda/ramda/issues/1389

**Comment by buzzdecafe** [comment]
i agree that is better behavior. the question is *how*. I've always resisted run-time type-checking for a bunch of reasons i won't bore you with here. 

But if we are going to catch problems like this one then we should do it *across the board* and not *ad hoc*, function by function.

**Comment by mLuby** [comment]
Does Ramda provide backwards compatibility for unspecified behavior like case 4 (where `lensPath` acts as `lensProp` when first arg is a string not an array)?

**Comment by buzzdecafe** [comment]
no, we only support the intended behavior. stuff that falls out we blame on javascript

**Comment by mLuby** [comment]
Apparently this behavior *is* [undocumented but tested for](https://github.com/ramda/ramda/blob/master/test/lensPath.js#L44). Still don't think it's a great idea, and it should definitely be in the docs, but I'll close this issue.

**Comment by davidchambers** [comment]
> Apparently this behavior *is* undocumented but tested for.

Yikes! I've opened #1779 to address this.

**Comment by buzzdecafe** [comment]
thanks for spotting that @mLuby

**Comment by CrossEye** [comment]
Yes, nice catch!

**Comment by mLuby** [comment]
A generally-applicable way to catch this kind of error would be to enforce that non-variadic functions receive no more than the expected number of args. `Curry` may be able to do this check.
```js
lensPath(['ab', 'cd']) // Lens
lensPath( 'ab', 'cd' ) // Error: arity 1 function received 2 arguments ['ab', 'cd'] .
```
If it's something that may be useful, I can put together a PR. But I can also drop it if type-safety is outside the library's scope.

**Comment by davidchambers** [comment]
Are you familiar with [Sanctuary][1], @mLuby? It embraces the approach you're advocating:

```javascript
S.unwords('foo', 'bar', 'baz');
// ! ‘unwords’ requires one argument; received three arguments

S.unwords('foo');
// ! Invalid value
//
//   unwords :: Array String -> String
//              ^^^^^^^^^^^^
//                   1
//
//   1)  "foo" :: String
//
//   The value at position 1 is not a member of ‘Array String’.
```


[1]: http://sanctuary.js.org/
