### ISSUE TITLE
Date API

### ISSUE THREAD

**Issue by corporatepiyush** [ramda/ramda#1785]
Date API is one of the most essential features to have 
Can we  have date helper functions in Ramda like e.g. SugarJS Date API

http://sugarjs.com/dates

**Comment by svozza** [comment]
Have you looked at [date-fp](https://github.com/cullophid/date-fp)?

**Comment by CrossEye** [comment]
I can't see a good reason to include something like this in Ramda?  Can you elaborate on the reasons?  I haven't done much date processing recently, but if I were to do so, I would certainly reach for [date-fp][df], as svozza suggests.

  [df]: https://github.com/cullophid/date-fp

**Comment by paldepind** [comment]
Working with time and dates is not a small task. Moment.js is a fine example of how complex such a task can become. It is certainly useful but, in my opinion, out of scope for Ramda.

**Comment by buzzdecafe** [comment]
closing this. if you want to fight for it, feel free to reopen.
