### ISSUE TITLE
Safari shows a blank page for try ramda?

### ISSUE THREAD

**Issue by krainboltgreene** [ramda/ramda#1789]
https://twitter.com/stephencelis/status/738085352410320896

**Comment by CrossEye** [comment]
Uggh.  Anyone out there with a Mac who can give this a look?

**Comment by krainboltgreene** [comment]
I was able to get it working normally + via the google short link

Safari: 9.1 (11601.5.17.1)
OSX: 10.11.4 (15E65)

**Comment by stephencelis** [comment]
![screen shot 2016-06-01 at 5 09 14 pm](https://cloud.githubusercontent.com/assets/658/15725819/9d99f16a-281b-11e6-9640-bd969113f9f9.png)

<img width="396" alt="screen shot 2016-06-01 at 5 09 45 pm" src="https://cloud.githubusercontent.com/assets/658/15725828/aafdb29c-281b-11e6-8c45-f84943c4d8f1.png">

<img width="698" alt="screen shot 2016-06-01 at 5 09 52 pm" src="https://cloud.githubusercontent.com/assets/658/15725832/afe26aaa-281b-11e6-882c-8f4f06e1b03c.png">

**Comment by krainboltgreene** [comment]
I didn't even think to look at the content of the panes. I also get empty code panes.

**Comment by stephencelis** [comment]
You all are using `=>`, which is only supported in the Technology Preview right now.

**Comment by thurt** [comment]
@stephencelis your screenshots are very helpful! This problem does not appear to be directly related to Safari. 

Looks like `./lib/js/main.js` is currently not being transpiled to an ES5 equivalent. Now the question is how to best fix this. 

I am able to get `main.js` into the rest of the `bundle.js` by changing the build script to 
`"browserify ./lib/js/main.js -t babelify ./lib/js/repl.js -o ./lib/js/bundle.js"`. I also change `const` declarations in `main.js` to `global.variable_name`. 

This solution appears to work but I wonder if there is a better way to use browserify here? I think there may be a way to use `require()` notation to refer to the libraries loaded with `<script>`. Not sure
