### ISSUE TITLE
Consider adding curry explanation to `flip` documentation 

### ISSUE THREAD

**Issue by thurt** [ramda/ramda#1791]
The result of `flip` appears to be automatically curried for arity 2. Yet it passes more than 2 arguments to the function if they are provided.

``` javascript
flip((a, b, c) => a + b + c)('a')('b', 'c') // bac
```

I think it could be helpful to add a note to the documentation about this. Also to note that if you require a higher arity curry, you can wrap `flip` with `curryN`

``` javascript
flip((a, b, c) => a + b + c)('a')('b')('c') // ERROR
curryN(3, flip((a, b, c) => a + b + c))('a')('b')('c') // bac
```

http://goo.gl/r3HcGN

Does this sound like a useful addition?

**Comment by thurt** [comment]
It looks like this also works for currying > 2
```javascript
flip(curry((a, b, c) => a + b + c))('a')('b')('c')
```

**Comment by CrossEye** [comment]
I think `flip` should retain the arity of the original function.  We should use `curryN` internally.

Your second example works because when flip tries to call the internal function, the internal one knows that there is still a parameter missing, and so returns a new function instead.

**Comment by thurt** [comment]
> flip should retain the arity of the original function.

:+1: That seems the most logical to me.

```javascript
// flip
module.exports = _curry1(function flip(fn) {
  return curryN(fn.length||2, function(a, b) {
    var args = _slice(arguments);
    args[0] = b;
    args[1] = a;
    return fn.apply(this, args);
  });
});
```

I show `fn.length||2` in case a variadic function is passed to `flip`?? In that case, `fn.length` will equal 0, so default value of 2 will be chosen instead. But maybe variadics are not a concern. 

I notice the current test is: 'returns a curried function'
That could be changed to be more specific: 'returns a curried function that matches the arity of the passed in function'

Something like this

**Comment by buzzdecafe** [comment]
> That could be changed to be more specific: 'returns a curried function that matches the arity of the passed in function'

Sounds like two tests:

1. returns a curried function
2. preserves the arity of the passed in function

**Comment by CrossEye** [comment]
@thurt:

> I show `fn.length||2` in case a variadic function is passed to `flip`?? In that case, `fn.length` will equal 0, so default value of 2 will be chosen instead.

Agreed.

@buzzdecafe 

> Sounds like two tests

Agreed.

----------

Damn, I'm agreeable today.

**Comment by asaf-romano** [comment]
See  #1714
