### ISSUE TITLE
unary-to-instance-method helper?

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1795]
For someone implementing a "type", or just mixing FP with OOP the JS way (or the other JS way), it's very rare that ramda's auto-currying could be leveraged for writing point-free functions. That's because there's no straight-forward mechanism for converting a unary function to a function that takes no arguments and simply runs on `this` (the inverse of `invoker`, in other words).

demo: http://goo.gl/cIL9kz

**Comment by thurt** [comment]
I will have to think about *this*. Could you make a more detailed example showing how your function is more beneficial to have than not have? 

And can your function be written more clearly as
```javascript
function unaryToInstanceMethod(method) {
  return function() { return method(this) }
}
```
?

**Comment by CrossEye** [comment]
I'm glad you responded @thurt, as I meant to take this one up, but it got lost in the shuffle of bad connection, and poor health.  I will try to look at this tomorrow.  I find this pretty interesting.
