### ISSUE TITLE
Consider honoring MonadPlus pseudo-interface in filter

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1796]
If a type implements `chain`, `of` and `empty`, we can filter it:
http://goo.gl/71AWo6

**Comment by asaf-romano** [comment]
url updated

**Comment by davidchambers** [comment]
This would be fantastic!

**Comment by buzzdecafe** [comment]
yup

**Comment by CrossEye** [comment]
I like it.  But do note that both `of` and `empty` have some strange definitions in FL: https://github.com/fantasyland/fantasy-land/issues/88

**Comment by kedashoe** [comment]
Is this maybe a bit much for ramda to bother itself with? If Alice creates a type with all three of these methods, surely she is aware of the concept of filtering and can either define filter or derive it on her type as you're done here (or let a FL library derive it)? I would imagine there are a ton of combinations of methods that can be derived from others (including multiple ways of deriving a method), seems like this would be a fair amount of overhead for something that might best be handled elsewhere.

**Comment by asaf-romano** [comment]
The problem is that the fantasy-land spec does not mention ``filter`` at all, as far as I can tell, so it's not on the menu. Indeed, most implementations of ``Maybe`` I've looked at so far offer ``of`` (combination of ``mzero`` and ``mplus``) and ``chain``, but not ``empty`` (which is ``mzero``). I guess that's because they don't want to implement ``concat`` (``mplus``) which is the other half of the monoid spec.

Anyway, since this is already the canonical (well, Haskell's) implementation of ``mfilter'', I don't think this is far-fetched.

**Comment by asaf-romano** [comment]
Following the discussion in #1786, another option is to follow Haskell a little more by completely ignoring ``of`` and instead rely on a full implementation of Monad and Monoid (i.e. ``chain``, ``empty`` and ``concat``). This might not be a terrible idea given that someone implementing ``empty`` might as well implement the rest of its associated type.

...e.g. https://gist.github.com/briancavalier/8199502 (``of`` is also implemented there though).

**Comment by davidchambers** [comment]
> If Alice creates a type with all three of these methods, surely she is aware of the concept of filtering and can either define filter or derive it on her type as you're done here (or let a FL library derive it)?

For what it's worth [Sanctuary's Maybe type][1] provides a `filter` method for compatibility with `R.filter`, but I'd prefer to have `R.filter` and `S.filter` derive the function from the existing :rainbow: methods.


[1]: http://sanctuary.js.org/#maybe-type
