### ISSUE TITLE
evolve fails for objects implementing valueOf

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1797]
`evolve({}, { valueOf() { return null; } }); // => cannot convert null to object`;

And it does not matter  where `valueOf` is in the prototype chain. It breaks because it's enumerable, and `transformation["valueOf"]` is not null.

**Comment by CrossEye** [comment]
Sorry, been mostly offline for several weeks.  This looks significant.  do you have a proposed solution?

**Comment by asaf-romano** [comment]
hoping to publish a PR (along with others) this weekend.

**Comment by asaf-romano** [comment]
In short, I don't think it's really necessary to support transformations not directly set on the transformations object, but rather on one of its prototypes.

**Comment by CrossEye** [comment]
Make sense.
