### ISSUE TITLE
Help: Compose multiple nary functions? tap-like, maybe?

### ISSUE THREAD

**Issue by mAAdhaTTah** [ramda/ramda#1798]
I've got a few functions that takes 3 arguments:

```
function render(el, previous, next) {
  // Perform DOM updates
}
```

What I would like to do it "compose" a set of these together, such that the first function is called with those 3 arguments, then the next function is called with the same 3 arguments, and so on.

1. Is this even possible with Ramda?
2. Would a function that supports this be considered a use addition?

My suspicion is "no", because the functions themselves aren't pure and the return values don't actually matter (it's the DOM mutation we're looking for), but I figured it was worth asking before I go write my own utility function for it.

Thanks for any help!

**Comment by jackfirth** [comment]
You can use `apply` and `tap` to turn them into functions that accept and return a 3 element tuple, then compose those functions together:

```javascript
compose(
  tap(apply(render1)),
  tap(apply(render2)),
  tap(apply(render3)))
```

**Comment by drewproud** [comment]
You can use the [converge](http://ramdajs.com/0.21.0/docs/#converge) function for that, though it might be kind of confusing since you don't care about the output.

```
const manipulateDom = R.converge(
  function() {}, [
    func1,
    func2,
    ...
    funcN
]);
```

**Comment by drewproud** [comment]
The tap/apply method is better, given that people will expect side affects when using `tap`.

**Comment by asaf-romano** [comment]
juxt / applySpec:
http://goo.gl/mr4r5J

**Comment by mAAdhaTTah** [comment]
Super helpful, everyone, thanks so much!
