### ISSUE TITLE
R.composeP does not handle a promise rejection. Is this by design?

### ISSUE THREAD

**Issue by KrishnanSrinivasan** [ramda/ramda#1799]
```
//dbConnect :: uri -> Promise
const connect = R.composeP(console.log, dbConnect)

//usage
connect(config.uri);
```
When dbConnect resolves I get a db connection. But when its rejected, I would like that to be handed over to a "handle" method which can handle the rejection.

I'm trying to use composeP to wrap a `Promise` returning function and return a `Either`. Is this possible?

**Comment by buzzdecafe** [comment]
I am with @davidchambers [on the subject of ramda's promise-related functions](https://github.com/ramda/ramda/issues/1770#issuecomment-219626369):

> I'd actually like to go in the other direction, and remove the existing Promise-specific functions from Ramda.

**Comment by TheLudd** [comment]
Yes they are a misstake IMHO. Better add functions like these (currying omitted):
```
function runThen (fn, promise) {
  return promise.then(fn)
}
function runCatch (fn, promise) {
  return promise.catch(fn)
}
```

And then you can use the ordinary compose with promises

**Comment by KrishnanSrinivasan** [comment]
Thanks @TheLudd for the suggestion.

Is it fair to conclude to that rejections be handled by top level impure functions and not consider composing promises with side-effect free functions?

> [plaid/async-problem: ](https://github.com/plaid/async-problem)
> All side effects must be isolated to the main function. Impure functions may be defined at the top level but may only be invoked in main.

This solution would work, but I was looking for an alternative to de-centralise handling rejections.

**Comment by davidchambers** [comment]
@KrishnanSrinivasan, I strongly suggest switching to [Fluture][1] or [data.task][2].


[1]: https://github.com/Avaq/Fluture
[2]: https://github.com/folktale/data.task

**Comment by shinzui** [comment]
@davidchambers Do you have any examples of using Fluture with Ramda?

**Comment by scott-christopher** [comment]
@shinzui: Not sure whether it helps or not, but this is a simple script I put together the other day to collect some website performance metrics that makes use of Fluture and Ramda.

https://gist.github.com/scott-christopher/982549ef947625056578417a5aee7eca

**Comment by shinzui** [comment]
@scott-christopher Thank you. I was looking for examples of complex pipelines, especially ones with multiple futures combining data with other sources.

**Comment by jaqmol** [comment]
I find the advice to stop using promises seriously harmful. The JS ecosystem is full with Promise-based APIs. In case Ramda stops supporting Promises it would render itself incompatible.

**Comment by CrossEye** [comment]
The idea is to suggest alternatives (`Futures` or `Tasks`), and not to cater to Promises, which themselves miss being lawful types that could be used with the sorts of abstractions which Ramda supports.  By using #2515 alongside an `R.then` function (coming soon to a PR near you), users could still work with Promises.  But `then` (and perhaps `fail`) would be Ramda's only direct Promise concessions.

The [FantasyLand][fl]  specification that's highly important to Ramda was created [in directl response][i1] to the problems that [make Promises unlawful][i2] (warning: those are long discussions!)

  [fl]: https://github.com/fantasyland/fantasy-land
  [i1]: https://github.com/promises-aplus/promises-spec/issues/94
  [i2]: https://github.com/promises-aplus/constructor-spec/issues/24

**Comment by danielo515** [comment]
I really want to know how

```
pipe(
then(stuff) 
, then(moreStuff) 
) 
```

It's better than just 

```
pipeP(
stuff
, moreStuff
) 
```

**Comment by Bradcomp** [comment]
We actually are adding `pipeWith` and `composeWith` functions (see @CrossEye comment directly above yours) that would make it as simple as

```
pipeWith(then, [stuff, moreStuff]);
```

The benefit is that now we will be able to remove `pipeP`, `composeP`, `pipeK`, and `composeK` in favor of a more versatile function that can easily recreate the prior use cases, and is more in line with Ramda's philosophy.

There have been a number of issues around `pipeP` et. al. that you can find by following some of  the links in this issue. The big discussion was here: https://github.com/ramda/ramda/pull/1869.  It might give you some background on why Ramda isn't keen on keeping those functions.

**Comment by danielo515** [comment]
> We actually are adding pipeWith and composeWith functions (see @CrossEye comment directly above yours) that would make it as simple as

I missed that part. Then it makes perfect sense. Will it automatically catch also?
