### ISSUE TITLE
Error in R.modulo docstring?

### ISSUE THREAD

**Issue by pnavarrc** [ramda/ramda#1802]
from http://ramdajs.com/0.21.0/docs/#modulo

> Divides the second parameter by the first and returns the remainder. Note that this function preserves the JavaScript-style behavior for modulo. For mathematical modulo see mathMod.

Shouldn’t it be “Divides the first parameter by the second and returns the reminder”? I would be happy to create a pull request (I will follow the [guidelines](https://github.com/ramda/ramda/blob/master/CONTRIBUTING.md), I promise) if someone can confirm that this is a bug.

**Comment by buzzdecafe** [comment]
yes, that is definitely an error. I would welcome a PR on this. thanks
