### ISSUE TITLE
just a couple of fun errors in the tests, discovered via Suman

### ISSUE THREAD

**Issue by ORESoftware** [ramda/ramda#1804]
[suman-output.txt](https://github.com/ramda/ramda/files/317387/suman-output.txt)

**Comment by ORESoftware** [comment]
<img width="1272" alt="screen shot 2016-06-15 at 4 40 18 pm" src="https://cloud.githubusercontent.com/assets/11139560/16101101/e42cd604-3317-11e6-8280-40d508afe118.png">

<img width="1284" alt="screen shot 2016-06-15 at 4 40 54 pm" src="https://cloud.githubusercontent.com/assets/11139560/16101108/f4de0b8a-3317-11e6-84b5-93d13577753d.png">


<img width="1258" alt="screen shot 2016-06-15 at 4 41 13 pm" src="https://cloud.githubusercontent.com/assets/11139560/16101116/0235e4d8-3318-11e6-9294-2cc8d9810c9b.png">

<img width="1315" alt="screen shot 2016-06-15 at 4 41 38 pm" src="https://cloud.githubusercontent.com/assets/11139560/16101121/1005012a-3318-11e6-8f1b-9947280eb4ef.png">

code 56 means test fail :)

**Comment by buzzdecafe** [comment]
ok this is interesting. are you recommending that we switch to suman? do you have some insight about why the tests above are failing?

**Comment by ORESoftware** [comment]
the same tests fail for me with Mocha too! Are they not failing on your side? I can give you my Node and Mocha versions etc. But yes I do recommend switching to Suman :)

**Comment by buzzdecafe** [comment]
the test suite runs and passes on every checkin. what version of node are you running? And thanks for the report

**Comment by ORESoftware** [comment]
NP, here are my stats:

ramda: "version": "0.21.0",

mocha --version
2.5.3

node -v
v4.4.5


any obvious reasons why the tests pass for you, but the tests don't pass on my end?

You can see the exact test fails in the text file at the very top, I will copy my Mocha output too momentarily.

**Comment by ORESoftware** [comment]
```

  1010 passing (624ms)
  12 failing

  1) ap interprets ((->) r) as an applicative:

      AssertionError: 'function (a0) {\n                return fn.apply(this, arguments);\n            }' === '30'
      + expected - actual

      -function (a0) {
      -                return fn.apply(this, arguments);
      -            }
      +30
      
      at module.exports (test/shared/eq.js:8:10)
      at Context.<anonymous> (test/ap.js:25:5)

  2) concat throws if attempting to combine an array with a non-array:
     AssertionError: Missing expected exception (TypeError)..
      at _throws (assert.js:330:5)
      at Function.assert.throws (assert.js:354:3)
      at Context.<anonymous> (test/concat.js:50:12)

  3) countBy can act as a transducer:
     TypeError: reduce: list must be array or iterable
      at _reduce (dist/ramda.js:5178:19)
      at reduceBy (dist/ramda.js:6279:16)
      at dist/ramda.js:551:35
      at dist/ramda.js:48:27
      at dist/ramda.js:296:22
      at dist/ramda.js:48:27
      at into (dist/ramda.js:5755:99)
      at Object.f3 [as into] (dist/ramda.js:516:22)
      at Context.<anonymous> (test/countBy.js:63:10)

  4) indexBy can act as a transducer:
     TypeError: reduce: list must be array or iterable
      at _reduce (dist/ramda.js:5178:19)
      at reduceBy (dist/ramda.js:6279:16)
      at dist/ramda.js:551:35
      at dist/ramda.js:48:27
      at dist/ramda.js:296:22
      at dist/ramda.js:48:27
      at into (dist/ramda.js:5755:99)
      at Object.f3 [as into] (dist/ramda.js:516:22)
      at Context.<anonymous> (test/indexBy.js:33:20)

  5) invoker does not rely on constructor identity:
     TypeError: [1] does not have a method named "concat"
      at dist/ramda.js:8221:19
      at dist/ramda.js:551:35
      at dist/ramda.js:56:27
      at Context.<anonymous> (test/invoker.js:45:8)

  6) reduceBy can act as a transducer:
     TypeError: reduce: list must be array or iterable
      at _reduce (dist/ramda.js:5178:19)
      at reduceBy (dist/ramda.js:6279:16)
      at dist/ramda.js:551:35
      at dist/ramda.js:48:27
      at dist/ramda.js:296:22
      at dist/ramda.js:48:27
      at into (dist/ramda.js:5755:99)
      at Object.f3 [as into] (dist/ramda.js:516:22)
      at Context.<anonymous> (test/reduceBy.js:62:10)

  7) reduceWhile reduces until its predicate fails:
     TypeError: R.reduceWhile is not a function
      at Context.<anonymous> (test/reduceWhile.js:8:10)

  8) reduceWhile returns its accumulator when given an empty array:
     TypeError: R.reduceWhile is not a function
      at Context.<anonymous> (test/reduceWhile.js:12:10)

  9) reduceWhile is curried:
     TypeError: R.reduceWhile is not a function
      at Context.<anonymous> (test/reduceWhile.js:16:28)

  10) reduceWhile correctly reports the arity of curried versions:
     TypeError: R.reduceWhile is not a function
      at Context.<anonymous> (test/reduceWhile.js:22:28)

  11) take steps correct number of times:
     expected f to be called twice but was called thrice
    f(1) at XMap.@@transducer/step (/Users/amills/WebstormProjects/oresoftware/ramda/dist/ramda.js:898:62)
    f(2) at XMap.@@transducer/step (/Users/amills/WebstormProjects/oresoftware/ramda/dist/ramda.js:898:62)
    f(3) at XMap.@@transducer/step (/Users/amills/WebstormProjects/oresoftware/ramda/dist/ramda.js:898:62)
  AssertError: expected f to be called twice but was called thrice
      f(1) at XMap.@@transducer/step (dist/ramda.js:898:62)
      f(2) at XMap.@@transducer/step (dist/ramda.js:898:62)
      f(3) at XMap.@@transducer/step (dist/ramda.js:898:62)
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:90:29)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:51:24)
      at Object.assert.(anonymous function) [as calledTwice] (node_modules/sinon/lib/sinon/assert.js:74:21)
      at Context.<anonymous> (test/take.js:46:18)

  12) uniq has R.equals semantics:

      AssertionError: '2' === '1'
      + expected - actual

      -2
      +1
      
      at module.exports (test/shared/eq.js:8:10)
      at Context.<anonymous> (test/uniq.js:25:5)


```

**Comment by ORESoftware** [comment]
Suman is still in beta => it's not quite ready for prime-time, and not officially released, but if you don't mind I can let you know when it's done and give your tests a run with it at that time.

**Comment by buzzdecafe** [comment]
sure, keep me posted on suman. 

so here's what i get running `make test` or `npm test` in ramda root dir: `1021 passing (486ms)`, and no failures. Is that how you are invoking the tests?

**Comment by ORESoftware** [comment]
well that's odd, because

 1010 passing (624ms)
  12 failing

1010 + 12 = 1022 not 1021, but let double check

**Comment by ORESoftware** [comment]
Ok, I do get 1022 passing (670ms) when I run "npm test"

I wasn't running the build step with either Mocha or Suman.

I was looking at the make files just now, perhaps the test pass when the project is minified/concatenated, but not passing otherwise?

**Comment by buzzdecafe** [comment]
not clear, but worth investigating. How were you invoking the test?

**Comment by ORESoftware** [comment]
yeah, I don't see you running any transpilation (which is good), so I would think the tests should pass before the build step too.

by the way, if you are interested in doing transpilation as part of a build step, the async lib src was recently refactored and they do some really crazy ES6/ES7 things before running a build step, definitely check that out.

I invoked mocha like so:

`$ mocha test`

I ran Suman the same ay, and most of the errors overlapped with Mocha (10/12 I believe)

**Comment by buzzdecafe** [comment]
i am gonna close this one, since the tests do appear to be passing.

**Comment by ORESoftware** [comment]
weird, even when you run `$ mocha test`? Will let you know if I figure out why they were failing over here

**Comment by buzzdecafe** [comment]
`mocha test` is not sufficient, since we need the Makefile to build the artifact to test.

**Comment by ORESoftware** [comment]
got it thanks

**Comment by CrossEye** [comment]
Suman looks fascinating.  I'm excited to see its progress.

**Comment by ORESoftware** [comment]
thanks - suman is progressing well, unit tests actually run faster as a
single process (ramda has 200+ unit tests so that means 200+ processes,
with ~10 running at a time, which is slower than 1 single process) but
"api" tests are sped significantly by parallelization, and it forces
application developers to have better software design and better handling
of concurrent access to resources etc.

after running suman with traditional 1:1 process:test file against unit
tests (in libraries like yours) I decided to allow suman to run multiple
tests in a single process as an option, finishing that over the next week
or two.

if you have any thoughts, questions or feature requests after reading the
readme, please feel free to open an issue. the design philosophy outlined
in the readme wont change and it seems that a lot of people understand
where suman is coming from compared with mocha ava jasmine and tape etc.
