### ISSUE TITLE
concat works on strings, append doesn't

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#1805]
This always bothered me:
`concat("a", "bc"); // => "abc"`
`append("bc", "a"); // => ["a", "b", "c"]`

**Comment by buzzdecafe** [comment]
yeah either it should work as it suggests or fail outright. i could be persuaded wither way

**Comment by CrossEye** [comment]
I get this instead:

```js
  append('bc', 'a'); //=> ['a', 'bc']
```

Which feels like exactly like the issue in #1800.

```js
concat('a', 'bc')
```

turns into a delegation to `'a'.concat('bc')`.  We can't do that with `append`.  But as to why `'a'` is treated as `['a']`, it's not so clear, and certainly not so pleasant.

**Comment by ascartabelli** [comment]
@CrossEye, as we discussed in the other issue, haven't forgotten about it I swear, strings are array-like objects.
```javascript
let s = "a";
let arr = ["a"];
s[0

**Comment by CrossEye** [comment]
That does help explain the issue.  So

```js
append('bc', 'foo'); //=> ['f', 'o', 'o', 'bc']
```


But we should make sure we realize that Strings are not lists.  One of the nice things about lists is that, at least via Ramda, they can be used as Functors:

```js
map :: (a -> b) -> f a -> f b
map :: (a -> b) -> [a] -> [b]
```

But we can see that for the function, `f`: `x => x.charCodeAt(0) :: Char -> Int`, `map` does not fulfil that:

```js
R.map(x => x.charCodeAt(0), 'foobar'); //=> [102, 111, 111, 98, 97, 114] 
```

That is,

```
map((Char -> Int), String) -> [Int].  
```

The result is not a String.

**Comment by ascartabelli** [comment]
@CrossEye, just because I love to play the devil's advocate part:
> ```map((Char -> Int), String) -> [Int]``` 

As strings are array-like objects you could rethink that as:
```
map((Char -> Int), [Char]) -> [Int]
```
And you have your contract fulfilled.

**Comment by CrossEye** [comment]
I certainly do understand that this is possible.  But it's not a String.  Try to call `trim`, `toLowerCase`, `substring` or `charAt` on the result.

Although a String has a lot in common with a list of characters, and can be implemented in terms of one, a list of characters is not by itself a String.  Some languages actually implement Strings this way, and I think that this makes sense, but we don't have that in JS.

Specifically, this fails the [identity law][il]:

```js
const u = 'foo'
const v = map(x => x, u); //=> ['f', 'o', 'o']

toUpper(u); //=> 'FOO'
toUpper(v); //=> throws error

// since f(u) <> f(v), u <> v
```


  [il]: https://github.com/fantasyland/fantasy-land#functor

**Comment by ascartabelli** [comment]
> Specifically, this fails the identity law

Well, of course it does: you're using your own functions that don't handle the case.
Theoretically, I'm not suggesting it, as strings are an array-like object we can detect and rebuild, you can write an implementation of map that returns a string when a string input is supplied.

My point is, as usual, that this isn't something you should defend against.

Going back to the matter at hand, `append`'s signature is `a → [a] → [a]`:
```javascript
R.append("bar", ["f", "o", "o"]) // => ["f", "o", "o", "bar"]
```
So, given what strings are in JavaScript, you can see `"foo"` as an _alternative_ way to write `["f", "o", "o"]`:
```javascript
R.append("bar", "foo") // => ["f", "o", "o", "bar"]
```
Nothing strange at my eyes, but I wouldn't even try it unless you specify it in the docs.
More importantly I would not write defensive code against it: it's pointless.

My personal choice is to write `@param {ArrayLike} ... @returns {Array}` in the doc comments whenever I'm not using some array specific stuff to actually let users leverage the behaviour.
Not so useful usually with strings, unless you are dealing specifically with single chars, but there are other array-like in the wild: `NodeList`s come to mind, and many of your current functions work [just fine](http://goo.gl/wKiuaS).

**Comment by davidchambers** [comment]
> Theoretically, I'm not suggesting it, as strings are an array-like object we can detect and rebuild, you can write an implementation of map that returns a string when a string input is supplied.

Really? What string would `map(c => c.charCodeAt(0), 'foo')` return? `'102111111'`? `102,111,111`? Either way we'd violate the requirement that `map` must return a value with the same shape as the input. We can't take a three-character string and return a nine- (or eleven-) character string.

> So, given what strings are in JavaScript, you can see `"foo"` as an _alternative_ way to write `["f", "o", "o"]`:
>
> ```javascript
> R.append("bar", "foo") // => ["f", "o", "o", "bar"]
> ```

I don't buy this. If correct, there's no way to represent a three-element sequence containing the strings `'f'`, `'o'`, and `'o'`. That's a real problem.

**Comment by ascartabelli** [comment]
>> Theoretically, I'm not suggesting it, as strings are an array-like object we can detect and rebuild, you can write an implementation of map that returns a string when a string input is supplied.

> Really? What string would map(c => c.charCodeAt(0), 'foo') return? '102111111'? 102,111,111? Either way we'd violate the requirement that map must return a value with the same shape as the input. We can't take a three-character string and return a nine- (or eleven-) character string.

Agreed, that's why I wrote "I'm not suggesting it"!
Ok, I made a poor argument.

What I meant is that using JavaScript you are going to break some law not written with JavaScript in mind at some point.

I'm fine with `map(c => c.charCodeAt(0), 'foo')` returning an array of numbers as I'm fine being able to filter a `NodeList` and having an array of `Node`s back like in the [other example](http://goo.gl/wKiuaS) I made.

I wouldn't be fine having an arbitrary, and wrong as you pointed out, representation such as `"102111111"` and I wouldn't be fine having to make my way against some excessively defensive code.

>> R.append("bar", "foo") // => ["f", "o", "o", "bar"]

> I don't buy this. If correct, there's no way to represent a three-element sequence containing the strings 'f', 'o', and 'o'. That's a real problem.

Sorry, probably not fully awake yet, but I'm not getting your point here.

**Comment by davidchambers** [comment]
> Sorry, probably not fully awake yet, but I'm not getting your point here.

In Haskell, say, we have `"foo" :: [Char]` and `["f", "o", "o"] :: [[Char]]`. These are different values. If you're arguing that these two values can be considered equivalent in JavaScript, it seems to me we lose the ability to represent the equivalent of Haskell's `["f", "o", "o"]` in JavaScript.

**Comment by ascartabelli** [comment]
> In Haskell, say, we have "foo" :: [Char] and ["f", "o", "o"] :: [[Char]]. These are different values. If you're arguing that these two values can be considered equivalent in JavaScript, it seems to me we lose the ability to represent the equivalent of Haskell's ["f", "o", "o"] in JavaScript.

Ah, no, I wasn't arguing that: they're **very** different things sharing some similarities.
Namely they share a length property, integer indexes and the ability to get the value at such indexes using the square bracket notation. 
That's, more or less, what the concept of "array-like" is about.

So, when @CrossEye argued that you don't get a string back by doing `map((Char -> Int), String) -> [Int]` I replied that he could try to put his mind at ease by seeing that `String` as a `[Char]`.
Which is not completely false for the reasons above.

As per your Haskell example we don't have that ability from the beginning as we lack a `Char` type in the first place.
I know, seems obvious, but although we can *conceptually* see a string as a sequence of chars, we have only strings.

Which are sequences of strings.

Stringception:
```javascript
let s = "foo";

foo[0][0][0] === "f" // => true

foo.charAt(0).charAt(0).charAt(0) === "f" // => true
```

**Comment by CrossEye** [comment]
This conceptual association doesn't bother me, so long as we don't think about it having any practical consequences.  I do recognize it, and think it would be great if the language actually implemented Strings in such a manner.  But the laws around `map` are much more important to me.  I won't try to necessarily enforce them in all cases, and sometimes strange things fall out of implementations, but users using functions in ways they aren't designed to work can expect odd behavior.

**Comment by davidchambers** [comment]
`append("bc", "a")` is a type error and should result in an exception, in my view.

**Comment by buzzdecafe** [comment]
even worse:

`append(1, 22) //=> [1]`

weeeeeeee

**Comment by paldepind** [comment]
I think the key reason why `append` cannot work on strings is that in JavaScript there is no notion of a character. Only a string of length one.

> even worse:

> `append(1, 22) //=> [1]`

> weeeeeeee

In that case the surely is nothing to do except maybe throw an error?

**Comment by buzzdecafe** [comment]
> In that case the surely is nothing to do except maybe throw an error?

i agree it should throw in that case. This means we are moving steadily in the direction of run-time type-checking. maybe that is ok? it is certainly a change -- and we'd probably be better off deciding on the boundaries of the type-checking we will do and how best to do it, rather than adding type-checks _ad hoc_.

**Comment by CrossEye** [comment]
I'm not at all sure I'm ready for that.  But I'm certainly ready for the discussion on it.  Perhaps we can find reasonable common ground here.

**Comment by paldepind** [comment]
My opinion is that throwing a deliberate error seems nicer than returning a nonsensical error that will probably cause a run-time error later in the program anyway. Alternatively I believe TypeScript and Flow provides a much better solution to this problem in general.
