### ISSUE TITLE
R.difference should link to R.symmetricDifference (among others)

### ISSUE THREAD

**Issue by pnavarrc** [ramda/ramda#1806]
From https://github.com/ramda/ramda.github.io/issues/72 — Difference should link to symmetricDifference, and vice-versa.

The author of the original issue proposes to add links between all the following methods:

- `R.difference`
- `R.differenceWith`
- `R.symmetricDifference`
- `R.symmetricDifferenceWith`

I can create a pull request if this is still considered relevant.

**Comment by CrossEye** [comment]
Absolutely.  Please to create a PR.
