### ISSUE TITLE
Please consider fixing mathMod to work with non-integers

### ISSUE THREAD

**Issue by Klortho** [ramda/ramda#1810]
I've read the discussions on  #672 and #186, and I understand why you decided to go with a separate function, `mathMod`, to "fix" JavaScript's broken `%` operator. But the discussion seemed to revolve around negative numbers, and the integer- type checking got short shrift, IMO.

If I understand it correctly, mathematicians define the operation only over integers so as to be able to define a multiplication operation over the congruence relation. Considering, for example, mod5, then 3 ≡ 8, and 1 ≡ 6, and that implies (3_1) ≡ (8_6). But that doesn't hold if you extend to, for example, mod5.1:

> (3  ≡ 8.1) and (1  ≡ 6.1) doesn't imply (3 \* 1)  ≡ (8.1 \* 6.1)

But, _how many programmers need that_?

You're documentation says this is supposed to be a _practical_ library, and I'd guess the use cases for modeling a cyclic continuous quantity far outnumber those that use this multiplication. I can't even think of an example where it'd be needed. (I'm sure there are some, but I can't think of any. What is 12:31PM times two?)

I imagine backwards-compatibility is an issue now. If so, maybe you could incorporate a third function? Maybe `floatMod` or something?

**Comment by CrossEye** [comment]
Sorry I'm slow to respond.  Been under the weather.

My rationale for `mathMod` was that I was then doing (and still occasionally continue to do) a fair bit of mathematical programming.  And our `mod` function, which was simply a wrapper around the language's `%`, would not do for that.

But the mathematical point of view is clear.  `mod n` divides the world into `n` equivalency groups.  The only call I've ever had for your continuous cyclic quantity is probably a `[0, 2π)`.  And for that I've found it easy to write quick functions of my own.  I've used `mathMod` in business contexts, but I can't imagine using a `floatMod` there.  What sort of uses do you expect for it?

**Comment by Klortho** [comment]
Thanks for the response! Yes, `[0, 2π)` is the main use-case I am working on. But another, on the same project, is a toroidal drawing canvas.

**Comment by Klortho** [comment]
But you're right, it's pretty easy to write you're own. I think I really need to maintain a utility library of my own up on npm just for these kinds of things.

**Comment by CrossEye** [comment]
I'd be very curious to see your toroidal drawing canvas, if it's something which does more than simply associates left/right and top/bottom edges of an otherwise rectangular surface.  Can you pan or scroll around your surface or pull back to note the toroidal shape?

**Comment by Klortho** [comment]
Oh, sorry, no, I just meant the topographical kind -- like asteroids.

**Comment by CrossEye** [comment]
Oh well.  That I can probably code myself.  I was hoping for a really cool demo.  :smile:
