### ISSUE TITLE
Some fonts aren't loading on the docs

### ISSUE THREAD

**Issue by wmonk** [ramda/ramda#1815]
Hi, when using the docs, these fonts below don't seem to load, resulting in a bunch of ▢ characters, slightly confusing when they open a new window! 😄 

```
http://ramdajs.com/fonts/glyphicons-halflings-regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
http://ramdajs.com/fonts/glyphicons-halflings-regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://ramdajs.com/fonts/glyphicons-halflings-regular.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by buzzdecafe** [comment]
yeah been aware of this one for a while, but haven't had bandwidth to fix it yet. PR would be *most* welcome

**Comment by buzzdecafe** [comment]
should have mentioned, this issue should be on ramda.github.io repo.

**Comment by wmonk** [comment]
Ah sorry! Will move over there 😄

**Comment by buzzdecafe** [comment]
thanks
