### ISSUE TITLE
assocPath alternative for working with nested objects + arrays?

### ISSUE THREAD

**Issue by nickb1080** [ramda/ramda#1816]
I'm curious if there's a solution to this problem using Ramda's existing operations (I've read #1332 and #773 to no avail): 

I have a list of "paths" into an object (a JavaScript AST produced by [esprima](https://github.com/jquery/esprima)) which I want to use to perform "update" operations (without mutation, like `R.assocPath` does) -- the issue is `R.assocPath` converts arrays to objects, which [escodegen](https://github.com/estools/escodegen) won't work with. I can't know in advance what the paths will be, and it's not clear how to compose lenses, or if that would even work in this case.

Essentially I'm interested in composing `updateIn` for arbitrary paths (as shown below) out of Ramda functions:

```js
var tree = {a: [ { b: 'hey' }  ] }
var path = ['a', 0, 'b']
R.assocPath(path, 'hi', tree) // returns { a: { '0': { b: 'hi' } } }
updateIn(path, 'hi', tree) // returns { a: [ { b: 'hi' } ] }
```

Thanks!

**Comment by CrossEye** [comment]
I don't think there's anything simple.  But you can certainly build one by composing lenses.  This might work for you:

```js
const tree = {a: [ { b: 'hey' }  ] };

const updateIn = curry((path, val, obj) => compose(
  set(__, val, obj),
  apply(compose),
  map(cond([[is(Number), lensIndex], [T, lensProp]]))
)(path));

updateIn(['a', 0, 'b'], 'hi', tree); //=> {"a": [{"b": "hi"}]}
```

If you take out the `set` line, this would be a possibly more robust version of `lensPath`, similar to what was discussed for `assocPath` in #773.

**Comment by nickb1080** [comment]
thanks!

**Comment by StefanoDeVuono** [comment]
Is there a way to make this work if the tree const is empty or incomplete?

By the way, I've found this recipe very useful as I'm trying to parse a JSON blob that's a bit unwieldy. If I have:

    const treeEmpty = {};
or

    const treePartial = {a: [ ] };
I'd like to have:

    const updateIn = curry((path, val, obj) => compose(
      set(__, val, obj),
      apply(compose),
      map(cond([[is(Number), lensIndex], [T, lensProp]]))
    )(path));

    updateIn(['a', 0, 'b'], 'hi', tree); //=> {"a": [{"b": "hi"}]}
Any thoughts?

**Comment by CrossEye** [comment]
It would probably not be hard to extend to make this happen.  But it's not clear to me whether or not this is a good idea.

Hmmm...

**Comment by loganpowell** [comment]
Sorry for pingin on a closed issue, but I just tried this and I got the following error:

```
ramda@latest:3 Uncaught TypeError: r is not a function
    at ramda@latest:3
    at n (ramda@latest:2)
    at ramda@latest:3
    at Object.n [as set] (ramda@latest:2)
    at R.curry (<anonymous>:3:6)
    at ramda@latest:2
    at ramda@latest:2
    at <anonymous>:1:1
```
with code:
```js
var tree = {a: [ { b: 'hey' }  ] };

var updateIn = R.curry((path, val, obj) => 
  R.compose(
    R.set(R._, val, obj),
    R.apply(R.compose),
    R.map(
      R.cond([
        [R.is(Number), R.lensIndex], 
        [R.T, R.lensProp]
      ])
    )
  )(path)
)

updateIn(['a', 0, 'b'], 'hi', tree)
```
What am I doing wrong?

**Comment by loganpowell** [comment]
Nevermind! I used `R._` instead of `R.__` my fault.

**Comment by CrossEye** [comment]
Ok, I won't try to figure out what's wrong, then.

But this would likely be much easier:

```js
assocPath(['a', 0, 'b'], 'hi', tree)
```

At some point since that issue started, this functionality was folded into `assocPath`.

**Comment by CrossEye** [comment]
There is:

```js
path(['a', 0, 'b'], tree)
```

But you might also look at lenses, which combine these notions:

```js
const myLens = lensPath(['a', 0, 'b']);

view(myLens, tree) //=> 'hey'
set(myLens, 'hi', tree) //=> a: [ { b: 'hi' }  ] }
```

**Comment by loganpowell** [comment]
@CrossEye Perfection!
@functionalStoic thank you as well!
