### ISSUE TITLE
fmap maybe

### ISSUE THREAD

**Issue by jcristovao** [ramda/ramda#1823]
Hey,
This is quite a simple question really, but is there anything similar to a `fmap` on a maybe (on Haskell)?

My use case was to apply a function to a value which can be either null, undefined, or have a decent value.

I ended up with:

```javascript
defaultXpto = (v) => defaultTo('N/A', v ? v + ' €' : null);
```

Which feels quite dumb, to have to checks on the validity of the value, one implicit, the other explicit. 

`defaultTo` is equivalent to Haskell's `fromMaybe`. So where is the `fmap`, so that I could write the cleaner:

```javascript
defaultXpto = (v) => defaultTo('N/A',fmap(x => x + ' €',v));
```

**Comment by buzzdecafe** [comment]
this seems more like a case for pattern matching? You can only sorta come close to pattern matching using things like `cond` or `ifElse`, e.g. http://goo.gl/QUDqa3

Once you have wrapped your value in a `Maybe` like this, you ought to be able to pass it to `R.map` and it should do the right thing (i.e. `fmap` over it, provided your `Maybe` is fantasyland-compliant).

**Comment by davidchambers** [comment]
[`S.toMaybe`][1] and [`S.fromMaybe`][2] would be useful:

```javascript
//    v :: Nullable String
const v = ...;

//    v$ :: Maybe String
const v$ = S.toMaybe(v);

//    v$$ :: Maybe Number
const v$$ = R.chain(S.parseFloat, v$);

//    v$$$ :: Maybe String
const v$$$ = R.map(amt => amt.toFixed(2) + ' €', v$$);

//    v$$$$ :: String
const v$$$$ = S.fromMaybe('N/A', v$$$);
```

One could use a pipeline to avoid intermediate variables:

```javascript
//    formatAmount :: Nullable String -> String
const formatAmount =
S.pipe([S.toMaybe,
        R.chain(S.parseFloat),
        R.map(amt => amt.toFixed(2) + ' €'),
        S.fromMaybe('N/A')]);
```

[`S.maybe`][3] provides a shorthand for `R.map`+`S.fromMaybe`:

```javascript
//    formatAmount :: Nullable String -> String
const formatAmount =
S.pipe([S.toMaybe,
        R.chain(S.parseFloat),
        S.maybe('N/A', amt => amt.toFixed(2) + ' €')]);
```


[1]: http://sanctuary.js.org/#toMaybe
[2]: http://sanctuary.js.org/#fromMaybe
[3]: http://sanctuary.js.org/#maybe
