### ISSUE TITLE
Thinking in ramda

### ISSUE THREAD

**Issue by slavaGanzin** [ramda/ramda#1827]
I think this link would be useful for newcomers:
http://randycoulman.com/blog/categories/thinking-in-ramda/

Let's add it into readme

**Comment by buzzdecafe** [comment]
wow that's nice stuff! do you want to do a PR?

**Comment by slavaGanzin** [comment]
https://github.com/ramda/ramda/pull/1828

**Comment by CrossEye** [comment]
This series is *fantastic*.  Thank you!   (I also added this to [the wiki][wi].)

  [wi]: https://github.com/ramda/ramda/wiki
