### ISSUE TITLE
unexpected behaviour with R.remove

### ISSUE THREAD

**Issue by slavaGanzin** [ramda/ramda#1830]
Hello everyone.
Is this a bug or a feature?

```
R.remove(0,1, [1,2,3,4])
[2,3,4]
R.remove(undefined,1, [1,2,3,4])
[]
```

**Comment by buzzdecafe** [comment]
garbage in, garbage out. The signature of `remove` is `Number → Number → [a] → [a]`. `undefined` is not a number.

**Comment by slavaGanzin** [comment]
I thought, it should be exception.

Michael, please clarify, how in functional world should I handle this situation? Using ```Maybe```?

**Comment by buzzdecafe** [comment]
> it should be an exception.

Probably so -- the problem is run-time type-checking of all arguments is not only a super-boring job, but I expect JS will present many bizarro edge cases that will make the run-time type-checking difficult, expensive, and complex.

In any case, this sort of thing is coming up enough that I am inclined to move in a type-checking direction. But I am afraid it might bore or frustrate me to death.

**Comment by buzzdecafe** [comment]
> how in functional world should I handle this situation? 

I guess it depends how you got into a situation where you are returning `undefined` where you are expecting a `Number`.  Q&D solution:

`const toNum = ifElse(isNil, always(0), identity);`

**Comment by slavaGanzin** [comment]
Thanks Michael

**Comment by CrossEye** [comment]
There's another interesting point here.  If we move to run-time type-checking, what does that mean for our signatures?  Should we then document all the sorts of exceptions a function might throw if supplied bad data?  Do they become a fixed part of our contract?

These sorts of -- yes, boring -- concerns are why I've been mostly happy with *garbage in, garbage out*.

**Comment by buzzdecafe** [comment]
good point @CrossEye. I feel like we are already swimming against the current of the language. 

FWIW note that OCaml functions that may throw are (not surprisingly) not "inferred" by the type system, e.g.:

```ocaml
exception NotFound;;
let find f = function
  | [] -> raise NotFound
  | x::xs -> if f x then x else find f xs;;

val find : ('a -> bool) -> 'a list -> 'a = <fun>
```

**Comment by davidchambers** [comment]
> If we move to run-time type-checking, what does that mean for our signatures? Should we then document all the sorts of exceptions a function might throw if supplied bad data? Do they become a fixed part of our contract?

I view the situation differently. The current signatures lie. The true type of `R.inc` is not `Number -> Number` but `(Any, Any...) -> Number`, as `R.inc('42')` and `R.inc(1, 2, 3)` are both "supported".

Run-time type checking could enforce the contracts implied by our type signatures. As a result we'd no longer find ourselves discussing the appropriate handling of "incorrect" applications of Ramda functions (see #1832, #1830, #1825, #1812, #1808, #1805, #1800, #1787, #1778, #1755, #1528, #1489, and probably others).

> run-time type-checking of all arguments is […] a super-boring job

Whether a feature is fun to implement is not relevant to Ramda users. We should first decide whether the feature is a good idea, then see whether someone will provide an implementation.

In this case an implementation already exists: [sanctuary-def][1].

Were we to adopt sanctuary-def or create a competing solution we could save ourselves from countless of hours of reading and writing comments regarding the handling of invalid inputs. :stuck_out_tongue_winking_eye:


[1]: https://github.com/sanctuary-js/sanctuary-def

**Comment by CrossEye** [comment]
> The current signatures lie.

Or "the current signatures describe what's intentionally supported."

> Run-time type checking could enforce the contracts implied by our type signatures. 

But to those of us who fundamentally object to throwing exceptions except as a very last resort, such enforcement is an extremely coarse measure.  There's a balancing act between avoiding ever allowing bad data to propagate and ensuring that the system will always continue to run.  Those who spend much time on data conversion tasks and those who spend it on user interaction tasks can easily come down on the opposite side of this divide.


>> run-time type-checking of all arguments is […] a super-boring job

> Whether a feature is fun to implement is not relevant to Ramda users. We should first decide whether the feature is a good idea, then see whether someone will provide an implementation.

Well, it's not simply whether the feature is a good idea, but how well it fits with the other features in -- and the philosophy of -- the system.  Do you think Ramda and Sanctuary should just merge into one library?  I don't.  I believe it's very good for the community that there are competing ideas being tried.

**Comment by davidchambers** [comment]
> Well, it's not simply whether the feature is a good idea, but how well it fits with the other features in -- and the philosophy of -- the system.

Absolutely. It's rarely correct to state _X is good_ without limiting the assessment to a specific context.

The point I sought to make is that we should consider X in the context of Ramda *before* considering the costs involved in making it happen. It's important to distinguish between believing X *not* to be a good idea in the context of Ramda, and believing X to be a good idea in the context of Ramda but choosing not to adopt/implement/include X for reasons such as time, cost, or API stability.

**Comment by buzzdecafe** [comment]
> The point I sought to make is that we should consider X in the context of Ramda before considering the costs involved in making it happen. 

I agree -- but I can't help but jump to "what would it take to do and then support this" and find that very discouraging. And I am leaning more and more in the direction of type-checking every day! 

But doing it at runtime still feels like we would be re-implementing solutions other languages have solved elegantly and baked in from the beginning, but we would be doing it awkwardly and bolting it on. And the implementation would be awkward mostly because of the intrinsic constraints of the host language.

GIGO is punting on this problem, and essentially saying to the user "You are responsible for getting your types to line up. Get it right, 'cuz we won't help you." That *also* makes me uncomfortable.

**Comment by olsonpm** [comment]
@buzzdecafe - If you were to take on the daunting task of validating not only the number of passed in arguments but their interfaces as well, you'd be one of very few in the javascript world.

Yes it'd be ideal, but I'd say only create exceptions to those functions which have proven to be problematic.  Even then, I'd assume that's a problem better solved via API and documentation - not input validation.

Finally, I don't think performance would be that impactful practically speaking.  And in the case it were, adding/removing validation as a build step wouldn't be too hard if the structure was created up front.

**Comment by buzzdecafe** [comment]
@olsonpm it almost sounds like you are volunteering :smiling_imp: 

for pre-1.0 this is not a priority for me. after that, i think everything should be up for discussion.

**Comment by olsonpm** [comment]
Haha I am a professional at making stupid mistakes and paying the price in debugging time.

But I didn't mean to sound volunteer'y, my opinion is that in an ideal world all public methods would pass strict input validation.  Javascript is most definitely not an ideal world, and I would argue zero users should expect input validation coming into this library assuming they didn't jump straight here from a typed language.
