### ISSUE TITLE
Broken link on Ramda website

### ISSUE THREAD

**Issue by DaveOrDead** [ramda/ramda#1831]
Hey guys,

I wasn't sure where to post this, on your homepage the link to the article: **Why Curry Helps** points to:
`https://web.archive.org/web/20140714014530/http://hughfdjackson.com/javascript/why-curry-helps`

whereas I think it should be: `https://hughfdjackson.com/javascript/why-curry-helps/`
cheers

Dave

**Comment by buzzdecafe** [comment]
Thanks for the heads up, we should fix this.

For some background on how it got his way:
https://github.com/ramda/ramda/issues/793

**Comment by CrossEye** [comment]
This is fixed in the README.  It will show up on the site next time we publish the docs.
