### ISSUE TITLE
invoker should throw error for negative number?

### ISSUE THREAD

**Issue by thurt** [ramda/ramda#1835]
``` javascript
invoker(0, 'T')(R) // true

// do you think a negative number to invoker should throw error?
invoker(-1, 'T')

// because I can't call the returned function without 
// getting an error anyways
invoker(-1, 'T')() // undefined does not have a method named "T"
invoker(-1, 'T')(R) // undefined does not have a method named "T"
```

http://goo.gl/NUl4cN

**Comment by davidchambers** [comment]
> [D]o you think a negative number to invoker should throw error?

Yes.

**Comment by CrossEye** [comment]
> [D]o you think a negative number to invoker should throw error?

No.

GIGO

**Comment by buzzdecafe** [comment]
Maybe!

**Comment by paldepind** [comment]
No matter what, an error will eventually be thrown. The questions seems to be whether or not we want the error to be

> undefined does not have a method named "foo"

from a line that may be distant from the incorrect application of `invoker`. Or if we want the error to be something like

> `invoker` incorrectly given a negative number

thrown directly from the incorrect application.

It seems to me like the later is more user friendly in every way.

**Comment by buzzdecafe** [comment]
> It seems to me like the lat[t]er is more user friendly in every way.

no doubt about it. my hesitation is what happens when we start pulling on that thread? Or, if we are going to type-check and throw, let's do so in a universal, consistent fashion across the lib, not _ad hoc_.

**Comment by paldepind** [comment]
> no doubt about it. my hesitation is what happens when we start pulling on that thread? Or, if we are going to type-check and throw, let's do so in a universal, consistent fashion across the lib, not ad hoc.

So it's all or nothing?

Another option would be to add official support for TypeScript and let that be the answer when people ask for more type safety. However TypeScript does not play well with currying and our placeholder (which reminds me of #1363).

**Comment by buzzdecafe** [comment]
yup -- all or nothing. I'm not interested in fielding questions like "Why does `f` throw with bad arguments, but `g` doesn't?" 

Thanks for bringing up #1363 -- I think we should definitely pursue your idea on restricting placeholder to `partial*`

**Comment by CrossEye** [comment]
> Thanks for bringing up #1363 -- I think we should definitely pursue your idea on restricting placeholder to `partial*`

:100:

**Comment by kedashoe** [comment]
> Thanks for bringing up #1363 -- I think we should definitely pursue your idea on restricting placeholder to partial*

I actually have a fairly complete implementation (updated some tests but not all of them, didn't do `partialRight` yet, some more doc updates, things like that). Was pretty recent, two or so months ago I think, got busy with some other stuff but shouldn't be too hard to resurrect. I'll try to submit a PR next week.

**Comment by buzzdecafe** [comment]
wow @kedashoe that is amazing. looking forward to seeing it

**Comment by CrossEye** [comment]
great!  I will be on vaca, but look forward to seeing it after I return 14 Aug.

**Comment by paldepind** [comment]
That sounds really great @kedashoe :+1:

**Comment by LeonineKing1199** [comment]
I think it makes the most sense to use the exception mechanism where strong types are defined. For example, `R.join`'s first parameter is `String` while the next one is an array of any type, a. I think `invoker` is a good example as well as its first two arguments are `Number` and `String`.  Any place where a strong type is listed in the function signature should throw exceptions.
