### ISSUE TITLE
Bug in `uncurryN`?

### ISSUE THREAD

**Issue by zhangchiqing** [ramda/ramda#1837]
I want to make a `second` function that returns the second argument by composing Ramda functions.

```
var second = function(a, b) {
  return b;
};

second(1, 2) 
// => 2
``` 

First I made a curried version of `second`:
```
var secondCurried = R.always(R.identity);

secondCurried(1)(2)
// => 2
```

Then I expect i can just uncurry the curried function using `uncurryN`, but it doesn't work
```
var secondBad = R.uncurryN(2, secondCurried);

secondBad(1, 2);
// => 1
// expected to return 2

```

Am I doing something wrong?

**Comment by buzzdecafe** [comment]
yes. `uncurryN` is intended to unravel a *manually* curried function so that you can call it with all the arguments at once. functions curried ramda-style already behave this way, so `uncurryN` is redundant.

As the example shows:

```js
var addFour = a => b => c => d => a + b + c + d;

var uncurriedAddFour = R.uncurryN(4, addFour);
uncurriedAddFour(1, 2, 3, 4); //=> 10
```

**Comment by zhangchiqing** [comment]
Thanks for replying. 

Yeah, actually the document said the function should be "manually" curried. I didn't notice :p 

Closing this issue.

But I'm just curious: Is it possible to make this `second` function by composing Ramda functions? Meaning without using the keyword`function`.

I know it might not practical, but I guess in theory Ramda can make any pure functions by composing existing Ramda functions, no?  :)

**Comment by buzzdecafe** [comment]
`nthArg` should do what you are after, but it doesn't. That does look like a bug to me, and we should fix it.

**Comment by buzzdecafe** [comment]
i think `nthArg` should be redefined:

```js
function nthArg(n) {
  return curryN(n + 1, function() {
    return nth(n, arguments);
  });
}
```

**Comment by zhangchiqing** [comment]
Right. `nthArg` works for me

```
var second = nthArg(1);
second(1, 2);
// => 2
```

Thanks. I don't think it's a bug though. It's consistent with [`nth`](http://ramdajs.com/0.21.0/docs/#nth);

**Comment by buzzdecafe** [comment]
i may raise a PR, we'll see how people feel about it.

**Comment by CrossEye** [comment]
> `nthArg` should either return a curried function or be curry-able after the fact

I'm not sure what that would mean.  By its very nature, this is one of the functions most closely connected to working with variadic functions.

These are the examples from the docs:

```js
R.nthArg(1)('a', 'b', 'c'); //=> 'b'
R.nthArg(-1)('a', 'b', 'c'); //=> 'c'
```

Are you suggesting that it should also work like this?:

```js
R.nthArg(1, 'a', 'b', 'c'); //=> 'b'
R.nthArg(-1, 'a', 'b', 'c'); //=> 'c'
```

**Comment by buzzdecafe** [comment]
No, I am suggesting that it should work like this:

```js
const second = nthArg(1);
second(1, 2) === second(1)(2);
```

**Comment by davidchambers** [comment]
> But I'm just curious: Is it possible to make this `second` function by composing Ramda functions? Meaning without using the keyword`function`.

There are (at least) two nice ways to express this via [combinators][1]:

```haskell
I :: a -> a
K :: a -> b -> a
C :: (a -> b -> c) -> b -> a -> c
K(I) :: b -> a -> a
C(K) :: b -> a -> a
```

```javascript
> S.K(S.I)(0)(42)
42

> S.C(S.K)(0)(42)
42
```

See [`S.I`][2], [`S.K`][3], and [`S.C`][4].


[1]: https://gist.github.com/Avaq/1f0636ec5c8d6aed2e45
[2]: http://sanctuary.js.org/#I
[3]: http://sanctuary.js.org/#K
[4]: http://sanctuary.js.org/#C

**Comment by buzzdecafe** [comment]
`K(I)` is what he originally tried `var secondCurried = R.always(R.identity);` but it did not behave as expected.

**Comment by davidchambers** [comment]
@buzzdecafe, that's because `R.always` is not a binary function. See #1680.

**Comment by buzzdecafe** [comment]
Thanks @davidchamber, i'm just relieved I agree with my former self. IMO We should add `K :: a -> b -> a`

**Comment by zhangchiqing** [comment]
>There are (at least) two nice ways to express this via combinators:

Awesome! Thanks @davidchambers.

**Comment by CrossEye** [comment]
> No, I am suggesting that it should work like this:
> 
> ```js
> const second = nthArg(1);
> second(1, 2) === second(1)(2);
> ```

Would this necessitate the resurrection of `arity` or some equivalent?  Because this would also imply at least

```js
second(1, 2, 3) === second(1)(2, 3);
```

Right?

**Comment by buzzdecafe** [comment]
`curryN` should take care of arity. In the case of your example, `second` would report its `length` as `2` -- but additional args get passed along; but if the point is to grab the nth arg, who the hell cares about any args beyond `n`?

**Comment by CrossEye** [comment]
D'oh.  Of course.  So something like

```js
const nthArg = n => curryN(n, (...args) => nth(n, args));
```

?  Or its ES-old equivalent?

**Comment by buzzdecafe** [comment]
yeah i proposed an implementation here: https://github.com/ramda/ramda/issues/1837#issuecomment-235608652

has to be `n + 1` because `nthArg` is zero-indexed and `curryN` expects the length

**Comment by buzzdecafe** [comment]
#1840
