### ISSUE TITLE
Define consistent comment format for examples

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda#1838]
Low priority, but creating this based on concerns by @CrossEye in #1836.

Currently, the [forEach](http://ramdajs.com/0.21.0/docs/#forEach) and [tap](http://ramdajs.com/0.21.0/docs/#tap) examples use the following format:

- `\\=>` for return value.
- `\\->` for logging output.

If this is the desired format, maybe it should be explained somewhere for those reading the docs.

The proposed alternative was `// logs "output here"`.

**Comment by buzzdecafe** [comment]
:+1: for the more explicit "logs x" comment when illustrating the side-effect of e.g. `tap` and `forEach`

**Comment by davidchambers** [comment]
:+1:

**Comment by CrossEye** [comment]
:+1: 

A slight correction (slash direction) is that we currently use:

- `//=>` for return value.
- `//->` for logging output.

But it would be good to adjust this.

**Comment by MattMS** [comment]
Ah yeah. Why can't everything just use CoffeeScript/Python comments! :trollface: 

I can do a couple of pull requests to switch them over.
