### ISSUE TITLE
Possible way to concisely create lens

### ISSUE THREAD

**Issue by 2426021684** [ramda/ramda#1839]
Working with `lensIndex` and `lensProp` can get kind of annoying. I wrote a small program to make it much easier. It requires ES6 proxies.

``` javascript
const blankLens = R.lens(
  (x) => x,
  (x) => x
)

const handler = {
   get: function(target, name, reciever){
     const nameAsInt = parseInt(name)
     if(!isNaN(nameAsInt)){
       return createLensObject(R.compose(target, R.lensIndex(nameAsInt)))
     }else{
       return createLensObject(R.compose(target, R.lensProp(name)))
     }
   }
}

function createLensObject(lens = blankLens){
  return new Proxy(lens, handler)
}

const L = createLensObject(blankLens)

// Access properties and indices on L to create a lens
// L.x = R.lensProp("x")
// L[0] = R.lensIndex(0)
// L.x.y = R.compose(R.lensProp("x"), R.lensProp("y"))
// L = blankLens

view(L.x, {x: 7}) // = 7
over(L[0].q, x => x + 3, [{q: 4}]) // = [{"q": 7}]
set(L.z.q, 5, {z: {q: 3}}) // = {"z": {"q": 5}}
```

Would you want to include something like this in ramda?

**Comment by buzzdecafe** [comment]
the concise syntax is really nice. I like this idea. :cow2:

anything es6-y will be up for consideration post 1.0. So let's try and get 1.0 out the door. :-)

Or we could start a development branch for post 1.0, and start es6 conversion in that.

**Comment by davidchambers** [comment]
Very cool!

> Would you want to include something like this in ramda?

We could include this in [ramda-lens][1].


[1]: https://github.com/ramda/ramda-lens

**Comment by buzzdecafe** [comment]
good thought @davidchambers ; the only problem is ramda-lens has not been released yet; i don't know if there is any reason it *couldn't* be released.

**Comment by CrossEye** [comment]
I'm a little surprised to see the enthusiasm for this after rejecting the `'a.b.c'` syntax in `path` (see #876 and #637.)

I find the code interesting, and a nice demonstration of Proxies.  But I think I would prefer to make it easier to make Lenses by updating `lensPath` or creating a new, related function:

```js
const lensPath = compose(
  apply(compose),
  map(ifElse(is(Number), lensIndex, lensProp))
);

const lensA1B = lensPath(['a', 1, 'b']);

view(lensA1B, {a: ['foo', {b: 42, c: 49}]}); //=> 42
over(lensA1B, add(5), {a: ['foo', {b: 42, c: 49}]}); //=> {a: [foo, {b: 47, c: 49}]
set(lensA1B, 100, {a: ['foo', {b: 42, c: 49}]}); //=> {a: [foo, {b: 100, c: 49}]
```

This feels much more consistent with the rest of Ramda.

**Comment by asaf-romano** [comment]
A (very) nice demo of Proxies, but I agree with @CrossEye this feels out of place.

I don't think it's the same as stringish `a.b.c.`, as you can always do ``L.a["b.c"].d``.
