### ISSUE TITLE
Add the method "startsWith" from Strings

### ISSUE THREAD

**Issue by zatziky** [ramda/ramda#1842]
Hello, can you please add `R.startsWith()` just like it is in lodash - https://lodash.com/docs#startsWith ?

**Comment by CrossEye** [comment]
If you want to create a PR, I'm sure we'd consider it.  We would not want the lodash API.  Ramda avoids optional arguments.

But I'm not sure we'd accept it, as this seems so easy to create with existing tools:

```js
    const startsWith = R.invoker(1, 'startsWith');
    startsWith('a', 'abc'); //=> true
    startsWith('b', 'abc'); //=> false
```

**Comment by asaf-romano** [comment]
FWIW, my personal startsWith supports both strings and arrays:
``const startsWith = curry((prefix, xs) => equals(take(xs.length, xs), xs));``

**Comment by asaf-romano** [comment]
What's nice about that is that it plays really nice with value equality semantics..

**Comment by asaf-romano** [comment]
With those semantics, I'd happily accept both startsWith and endsWith.

**Comment by Tapsi** [comment]
@asaf-romano I tried your snippet and it behaves different than expected. Am I correct that `const startsWith = curry((prefix, xs) => equals(take(prefix.length, xs), prefix));` is the correct implementation? I think prefix.length is correct because you want to check prefix against xs, right?

**Comment by asaf-romano** [comment]
:)

**Comment by asaf-romano** [comment]
endsWith would be pretty much the same, but with takeLast.

**Comment by zatziky** [comment]
I let the PR to someone else. I just would like to see a list of functions that is, say, longer. As I see functional methods as operators and e.g. in rx you have got lots of them. Then you are just composing them. And that's fine. ;-) Goodjob you do otherwise!

**Comment by jethrolarson** [comment]
This wouldn't just be `invoker(1, 'startsWith')` as the browser support of the native is poor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by CrossEye** [comment]
You're right.  Those pesky browsers.

I've used this one a lot in Node.  I'd be interested in something like @asaf-romano's formulation, then.  Anyone interested in creating a PR?

**Comment by mattgrande** [comment]
The only issue I have with @asaf-romano's answer is it has the parameters in the opposite order of lodash.

I'll try whipping up a PR for this tonight (about 8-10 hours from posting this), but if someone else gets to it first, feel free.

**Comment by jethrolarson** [comment]
That's consistent with almost every function in ramda

**Comment by CrossEye** [comment]
@mattgrande: 
> The only issue I have with @asaf-romano's answer is it has the parameters in the opposite order of lodash.

One of the main reasons for starting Ramda was that we found the parameter orders in Underscore/lodash not appropriate for the composeable style we were interesting in pursuing.  There were many other reasons, and it did start as an educational exercise, not an attempt to create a competing library.  But the parameter order is quite important.

**Comment by mattgrande** [comment]
Yes, I realised my error after posting. If I end up doing the PR, I'll ensure it's composable.
