### ISSUE TITLE
placeholder not working when currying

### ISSUE THREAD

**Issue by mattecapu** [ramda/ramda#1845]
```js
var addFourNumbers = (a, b, c, d) => a + b + c + d;

var curriedAddFourNumbers = R.curry(addFourNumbers);
var f = curriedAddFourNumbers(R._, 1, 2, 3);
var g = curriedAddFourNumbers(R._, R._, 1, 2);
var h = curriedAddFourNumbers(R._, R._, R._, 1);
f;
g;
h();
```
[Docs](http://ramdajs.com/0.21.0/docs/#curry) say `f`,`g`,`h` should be functions [when in fact they are `NaN`.](http://ramdajs.com/repl/#?code=var%20addFourNumbers%20%3D%20%28a%2C%20b%2C%20c%2C%20d%29%20%3D%3E%20a%20%2B%20b%20%2B%20c%20%2B%20d%3B%0A%0Avar%20curriedAddFourNumbers%20%3D%20R.curry%28addFourNumbers%29%3B%0Avar%20f%20%3D%20curriedAddFourNumbers%28R._%2C%201%2C%202%2C%203%29%3B%0Avar%20g%20%3D%20curriedAddFourNumbers%28R._%2C%20R._%2C%201%2C%202%29%3B%0Avar%20h%20%3D%20curriedAddFourNumbers%28R._%2C%20R._%2C%20R._%2C%201%29%3B%0Af%3B%0Ag%3B%0Ah%28%29%3B)

**Comment by buzzdecafe** [comment]
Thanks for the heads up, that is bad behavior. On the bright side, it looks like [placeholder support may soon be removed from `curry`, and only supported via `partial*`](/ramda/ramda/pull/1843). 

So I think we should defer this one until #1843 is merged.

**Comment by mattecapu** [comment]
Yeah I saw the issue. Still thought was worth a shot.
How can I curry a middle parameter using only partial and partialRight?

**Comment by buzzdecafe** [comment]
you may wanna try asking in the gitter room -- lots of smart folks hang out in there https://gitter.im/ramda/ramda

**Comment by Bradcomp** [comment]
It looks like you're using one underscore instead of two for the placeholder.  Try it with two and it should do what you want.

http://goo.gl/rhHvKf

**Comment by buzzdecafe** [comment]
well spotted @Bradcomp ! closing this one then

**Comment by mattecapu** [comment]
Oh. I never noticed there were two versions. Thank you very much!
