### ISSUE TITLE
add the T combinator : R.thrush ?

### ISSUE THREAD

**Issue by guillaumearm** [ramda/ramda#1846]
Hey guys, I think add a thrush function in Ramda can be cool, is not it ?
`
const thrush = x => f => f(x);
`

an example here with lenses: http://goo.gl/RgLubh

**Comment by buzzdecafe** [comment]
i'd be happy to see a PR for it

**Comment by davidchambers** [comment]
I'd like to remove `R.T` and `R.F`, to make the single-upper-case-character identifiers available for combinators.

**Comment by guillaumearm** [comment]
@davidchambers : today i use ramda in production, and i have some : 
`
  const otherwise = R.T
`
in my code.
Maybe lots of people use R.T and R.F in their code, and i think R.identity is more expressive than R.I

**Comment by davidchambers** [comment]
> i think R.identity is more expressive than R.I

I'd say `R.always(true)` is more expressive than `R.T` by the same logic. :stuck_out_tongue_winking_eye:

**Comment by guillaumearm** [comment]
Yes, you're totally right.
anyway, i did a PR for R.thrush -> #1847
Maybe we should create an issue for talking about removing R.T and R.F, and another one for adding missing combinators and rename them.
does it would mean than R.compose should be called R.K ? o_Ô

**Comment by buzzdecafe** [comment]
`R.K` would have to be added. `always` is close, but really generates a thunk instead of a unary function. 

You may see some resistance on using `T` for the combinator instead of a constant `true` function.

**Comment by guillaumearm** [comment]
but it means, R.compose will be removed or just R.K = R.compose ?

**Comment by guillaumearm** [comment]
oups sorry, the B combinator is `compose`, and K is `always`

**Comment by CrossEye** [comment]
While I have little problem removing `T` and `F`, although I would like to have simple names for these, and not depend on `R.always(true)`.

But part of the reason I'm in favor of this is that I'm not in favor of such single-character names.

S-K-I, and other combinator-systems are wonderful.  But for a general-purpose library, code that looks like `B(K, T)` looks too much like gibberish, IMHO.
