### ISSUE TITLE
New function R.select

### ISSUE THREAD

**Issue by rsmoorthy** [ramda/ramda#1848]
I find the following new function helpful.

### **select**
```
// [Number] -> [a] -> [a]
// [Number] -> String -> String
```

Selects and returns only the elements of the given list, string that is based on the indices provided. 

This is similar to slice, but gives us the ability to chose any assorted elements, based on the index values provided.

`
R.select([1, 3], ['a', 'b', 'c', 'd']);        //=> ['b', 'd']
`

_Note: Let me know if this make sense or this can be accomplished by composition of existing methods._

**Comment by buzzdecafe** [comment]
> Note: Let me know if ... this can be accomplished by composition of existing methods.

See `props`, e.g. `props([1, 3], ['a', 'b', 'c', 'd']); //=> ['b', 'd']`. 

However, `props` doesn't handle the String case you have in the sigs above.

**Comment by rsmoorthy** [comment]
Thanks. I thought I looked at all of existing methods. It looks like I have overlooked something, that was there for long time.

`props` is good enough for what I wanted to achieve. I was not really looking for String case,  but just added it while defining the signature.

_Trivial Note: `select` is such a nice keyword. Should get used for something really apt_

**Comment by buzzdecafe** [comment]
> `select` is such a nice keyword. Should get used for something really apt :-)

Agreed. We are using `project` for sql-ish `select`, so that name is up for grabs.
