### ISSUE TITLE
Any high quality open source codebase to learn coding style with ramda?

### ISSUE THREAD

**Issue by liweiz** [ramda/ramda#1851]
Sorry to place a question like this here. Please remove it, if this is not the right place to ask such question.

I'm trying to find a coding style to follow. Based on my understanding, I think Ramda.js is the way to go. If Douglas Crockford's way of object creation (something like this: http://stackoverflow.com/questions/27257397/constructor-pattern-by-douglas-crockford) is used, it would be even nicer.

Thanks in advance,

Liwei

**Comment by buzzdecafe** [comment]
Hi @liweiz ,

It's hard to make a recommendation without knowing what your goal is. 

If you want some background about the motivation and design choices for ramda, I recommend these articles by @CrossEye:

* [Why Ramda?](http://fr.umio.us/why-ramda/)
* [Favoring Curry](http://fr.umio.us/favoring-curry/)
* [The Philosophy of Ramda](http://fr.umio.us/the-philosophy-of-ramda/)

If you want to learn ML-style functional programming -- and I recommend that you do -- then try learning one of the ML languages, e.g. OCaml, Haskell, F#, etc. 

Good luck

**Comment by liweiz** [comment]
Thank you for your nice advice, @buzzdecafe .

I skimmed through the [thinking-in-ramda series](http://randycoulman.com/blog/categories/thinking-in-ramda/) to get an idea what Ramda offers. Definitely love it.

So my current plan is, to shorten the time of learning Javascript, I want to find some high-quality code base available to learn Javascript itself, functional programming with JS and a good style to code.

My superficial understanding of Javascript is that treating object as struct/map-like data structure (I think Douglas Crockford's thought makes more sense than others) and building data pipelines is a good way that does not fight against the nature of JS. That's where my plan comes from.

Hopefully, I provided more information for my goal here.

Thanks again,

Liwei

**Comment by slavaGanzin** [comment]
@liweiz
I recommend:
[SICP](https://github.com/sarabander/sicp-pdf/raw/master/sicp.pdf) as FP Bible

And [mostly-adequate-guide](https://drboolean.gitbooks.io/mostly-adequate-guide/content/) as practical guide

**Comment by liweiz** [comment]
Thank you, @slavaGanzin .

I now have a lot to read;)

**Comment by buzzdecafe** [comment]
i agree with @slavaGanzin 's recommendations. read, code, repeat.
