### ISSUE TITLE
Passing no args to the result of a unary function causes it to run

### ISSUE THREAD

**Issue by vintem** [ramda/ramda#1856]
In the docs it says: "Wraps a function of any arity (including nullary) in a function that accepts exactly 1 parameter."

But if I call its result with no parameters, it works. 

Like in this example:

```
    const add = R.curry((x, y, z) => {
      return x + y + 1;
    });
    
    const add1 = R.unary(add(1, 40));
    
    add1(); // 42
```

But if I had called the result of the add function without a next parameter it would not work. Like so:

```
add(1, 40)(); // function
```

Is the behavior from the unary function intentional? Or is it a bug? 
Thanks

**Comment by buzzdecafe** [comment]
this appears to be an issue with `unary`. Here are simpler examples that illustrate the behavior:

```js
unary((x) => x)(111); // 111
unary((x) => x)(); // undefined
unary((x, y, z) => x + y + z)(); // NaN
```

`unary` will return  a function of arity 1, and that's it. Once it's invoked it does not count arguments. I agree it feels a little weird.

**Comment by davidchambers** [comment]
I favour removing `R.unary` and friends. These functions are only necessary for "JavaScript interop", and lambdas perform this role perfectly well. I don't see the appeal of `R.unary(f)` over `x => f(x)`.

**Comment by buzzdecafe** [comment]
i'm inclined to agree, especially given the modern, terse lambda syntax. You could also get `unary` behavior without the undesired weirdness by `curryN(1, f)` (although I'd argue you get some different weirdness, viz. when invoking with no args, but that's another topic ...) 

So if you wanna deprecate `unary` and `binary` i support that.

**Comment by davidchambers** [comment]
> So if you wanna deprecate `unary` and `binary` i support that.

#1858

**Comment by vintem** [comment]
I guess I had my answer. Thanks.
