### ISSUE TITLE
Add uncurry function

### ISSUE THREAD

**Issue by mrtnbroder** [ramda/ramda#1859]
`const uncurry = (fn) => (...args) => args.reduce((left, right) => left(right), fn)`

really simple and yet super-useful. I just ran into a problem where I couldn't use `uncurryN`, as it works differently than I thought. This one accepts one function and partially applies each argument to a function.

**Comment by buzzdecafe** [comment]
Do you have some example use cases this function solves?

**Comment by mrtnbroder** [comment]
I'm not talking about deprecating `uncurryN`. But I noticed that it doesn't work in my use case.

Example:
http://goo.gl/VwUDOv

```
const uncurry = (fn) => (...args) => args.reduce((left, right) => left(right), fn)

const arr = [{
  foo: {
    bar: 2
  }
},{
  foo: {
    bar: 1
  }
},{
  foo: {
    bar: 3
  }
},{
  foo: {
    bar: 3
  }
},{
  foo: {
    bar: 3
  }
}]

const equalsN = pathEq(['foo', 'bar'])
const filterBy = uncurry(compose(filter, equalsN))

filterBy(3, arr)
// [{"foo": {"bar": 3}}, {"foo": {"bar": 3}}, {"foo": {"bar": 3}}]
```

try replacing `uncurry` with `uncurryN` and see that it will not result into anything useable.

**Comment by davidchambers** [comment]
I find `uncurry` confusing here. I would simply write:

```javascript
const filterBy = (n, xs) => R.filter(equalsN(n), xs);
```

If a point-free solution is desired, one could use [`R.useWith`][1]:

```javascript
const filterBy = R.useWith(R.filter, [equalsN, R.identity]);
```


[1]: http://ramdajs.com/docs/#useWith

**Comment by mrtnbroder** [comment]
@buzzdecafe if you use ramdas curry to create the curried function `const a3 = curry((a, b, c) => a + b + c))` then it works with `(1)(2, 3)`. Not sure why though.
