### ISSUE TITLE
May array into an object

### ISSUE THREAD

**Issue by zhaoyao91** [ramda/ramda#1863]
how to map an array into an object, say , use fn1 to map key and fn2  to map value

**Comment by davidchambers** [comment]
Here's one solution:

```javascript
//    strMapFromArray :: (a -> String) -> (a -> b) -> StrMap b
const strMapFromArray = R.curry((keyFn, valFn, xs) =>
  R.fromPairs(R.map(x => [keyFn(x), valFn(x)], xs))
);

strMapFromArray(R.toUpper, R.identity, ['a', 'b', 'c']);
// => {A: 'a', B: 'b', C: 'c'}
```

See [`StrMap`][1] if you're wondering why I used `StrMap b` rather than `Object` in the type signature.


[1]: https://github.com/sanctuary-js/sanctuary-def#strmap

**Comment by zhaoyao91** [comment]
good solution. I don't know why Ramada didn't include such functions
