### ISSUE TITLE
remove redundant auto-curried examples

### ISSUE THREAD

**Issue by olsonpm** [ramda/ramda#1865]
Would you take a PR to remove all redundant auto-curried examples?  I am reading through the API now and am willing to remove all examples where currying is used only to show auto-curry congruency.

**Comment by buzzdecafe** [comment]
I assume you mean like this:

```
R.adjust(R.add(10), 1, [0, 1, 2]);     //=> [0, 11, 2]
R.adjust(R.add(10))(1)([0, 1, 2]);     //=> [0, 11, 2]
```

?

If so, then yes, I'd be happy to see that streamlined

**Comment by olsonpm** [comment]
Right - there shouldn't be too many

**Comment by CrossEye** [comment]
Thanks.  Would definitely like to see those removed.

**Comment by olsonpm** [comment]
@CrossEye - Kind of minute, but what are your thoughts on items like [add](http://ramdajs.com/0.22.1/docs/#add)

```
R.add(2, 3);       //=>  5
R.add(7)(10);      //=> 17
```

It's subjective - but I'm leaning toward removing unnecessary autocurry examples, or modifying them to comma-form (there's probably a term for that)

**Comment by CrossEye** [comment]
This is one of the common examples used to explain `curry`, usually by defining an intermediate function, such as `const add42 = R.add(42)` and using it.

Since we are not trying to explain `curry` but instead explain `add`, I don't think it's relevant or useful here, though.

**Comment by olsonpm** [comment]
Ah good to understand the reasoning - I appreciate it
