### ISSUE TITLE
Sort docs by Type

### ISSUE THREAD

**Issue by ChrisPenner** [ramda/ramda#1872]
Hello! I'm loving Ramda so far, I use it in my reducers for my react-redux app and it usually allows me to reduce each step down to one or two simple operations!

One thing that would be very useful to me (and I assume many others) would be to add a 'type' sorter on the [ramda docs](http://ramdajs.com/0.22.1/docs/) page. I notice that each function already has its type listed (List, Object, etc.), even having a toggle to limit search results would be brilliant! Often I know I want to do a transformation on a list, but I don't know what the particular function is called in Ramda, currently I need to filter through the entire list of functions looking for ones that operate on lists that might be what I like.

Hopefully this is simple enough to add :)

Thanks!

**Comment by kedashoe** [comment]
Hi @ChrisPenner , glad you are enjoying ramda :)

If you enter a category in the search box, the results will show all functions in that category. You have to type the full name, ie if you type "lis" you will have no results but when you make it all the way to "list" you'll see all the list functions.

Hope that helps!

**Comment by ChrisPenner** [comment]
I swear I tried that! Haha, works great, thanks!
