### ISSUE TITLE
Website repl is down

### ISSUE THREAD

**Issue by Joe-Withey** [ramda/ramda#1873]
The Ramda Repl on the site is down.

**Comment by kedashoe** [comment]
Looks like https://wzrd.in/ is down. Not sure what to do about that. Does @jfhbrook from https://github.com/jfhbrook/wzrd.in run the site?

**Comment by jfhbrook** [comment]
Kind of. I have admin on the box, though max pays the bills.

It looks like the machine is out of disk. Usually Max deals with this so I gotta figure out what our accepted approach is---will have an answer soon.

**Comment by jfhbrook** [comment]
Should be back.

**Comment by kedashoe** [comment]
Awesome, thanks @jfhbrook . REPL looks like it is working again, thanks for pinging us @Joe-Withey

**Comment by buzzdecafe** [comment]
I'm getting "502/Bad Gateway" from wzrd.in this morning. REPL is dead. ping @jfhbrook -- please let me know if i can help

**Comment by fix-fix** [comment]
Can the REPL page use https://unpkg.com/ instead of https://wzrd.in/?

**Comment by buzzdecafe** [comment]
@fix-fix the thing about wzrd.in is it browserifies the package for you. That is necessary for RF which does not have any UMD wrapper

**Comment by CrossEye** [comment]
https://github.com/jfhbrook/wzrd.in/issues/143

Should we see about either another service or at least running a slightly crippled version of the REPL without those things that need UMD?

**Comment by jfhbrook** [comment]
sorry: wzrd.in should be up.

As you can gather from the issue, we are in severe need of a logrotate config. If you can help there that would, well, be great!

**Comment by buzzdecafe** [comment]
failing in a new way for me: https://wzrd.in/standalone/sanctuary@latest returns "Cannot GET /standalone/sanctuary@latest"

**Comment by buzzdecafe** [comment]
it's been a long time since i've done gnu/linux system admin, but maybe i can help with logrotate. if you don't mind that the last time i touched logrotate was 10 years ago :smile:

**Comment by jfhbrook** [comment]
Just wanted to confirm that the new failure mode from 13 hours ago is new. It looks like leveldown bindings got broken somehow.

The site is mostly up, though the cache is completely cold so the whole thing's falling over (lol). Will try to sort this out.

**Comment by jfhbrook** [comment]
thread https://github.com/jfhbrook/wzrd.in/issues/144

**Comment by jfhbrook** [comment]
It should be back up. Something kicked the npm install and npm2 is extra flaky with not touching the bundledDependencies.

I'd say this would go away when we switch to npm3, but it'll also go away when jfhbrook/wzrd.in#133 hits.

**Comment by buzzdecafe** [comment]
yup, looks good, thanks
