### ISSUE TITLE
Some more string functions

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1874]
I know we generally do not want to bloat Ramda with functions that are easily created, but I find myself creating these functions when manipulating strings all the time. They're so simple and help with point free programming so I still think we should consider adding them.

```js
const prefix = R.add
const suffix = R.flip(R.add)
const startsWith = R.curry((q, str) => str.startsWith(q))
const endsWith = R.curry((q, str) => str.endsWith(q))
const stripl = R.curry((q, str) => startsWith(q, str) ? str.slice(q.length) : str)
const stripr = R.curry((q, str) => endsWith(q, str) ? str.slice(0, str.length - q.length) : str)
const strip = R.curry((q, str) => stripl(q, stripr(q, str)))
```

What do you think?

**Comment by olsonpm** [comment]
I'm pretty sure they're trying to minimize aliases (R.add -> prefix and its fipped counterpart).

I'm on board with starts/endsWith, except keep in mind your implementation is not ie friendly

Not on board with your implementations of stripl/r simply because it's not in lodash.  My only reasoning for adhering to lodash in this case is that it's likely the most popular utility lib next to underscore.  If lodash hasn't found a need to implement those functions, then, considering ramda's smaller string category, I would assume it shouldn't be implemented here.

**Comment by fix-fix** [comment]
You can use [underscore.string.fp](https://www.npmjs.com/package/underscore.string.fp) or other string manipulation library.

**Comment by olsonpm** [comment]
Nice library - thanks for mentioning it.

Notice their aliases conflict with OP's strip implementation

> strip     = trim
> lstrip    = ltrim
> rstrip    = rtrim

**Comment by ccorcos** [comment]
Hmm. I just find it so awkward that I have to keep writing these functions. Seems like JS should really just have a standard lib...

**Comment by davidchambers** [comment]
I'd like to leave this open for a few days to give others a chance to comment.

**Comment by ccorcos** [comment]
That works for me :)

**Comment by CrossEye** [comment]
>  If lodash hasn't found a need to implement those functions, then, considering ramda's smaller string category, I would assume it shouldn't be included here.

I wouldn't buy that at all.

You might notice, in fact, that lodash/fp is essentially an API clone of Ramda, with an entirely different implementation (and, of course, assorted incompatibilities.)  

Ramda looks to lodash/underscore/FKit/fn.js/fnuc/wu/sugar/lazy/Bilby/whatever when we're building new functions to see if there's clear consensus on naming that we can willingly join.  Occasionally we'll look at others for their implementations of functions, especially if there seems to be an issue with our own.

But mostly we strike out on our own, building functions that seem useful to our community, and paying little heed to these others.

**Comment by CrossEye** [comment]
> I'm pretty sure they're trying to minimize aliases 

More like: entirely avoid aliases.

> (edit: though I haven't read enough to understand their criterion for when aliases are ok)

Never.  See the [parable][pa] by @davidchambers .

But note that the suggested `prefix` would not be a true alias of `add`, even if it could be implemented as such due to the overloading of `+` in JS.  It's simply not the same logical function.

  [pa]: https://github.com/ramda/ramda/pull/574#issuecomment-64124850

**Comment by CrossEye** [comment]
> I know we generally do not want to bloat Ramda with functions that are easily created, but I find myself creating these functions when manipulating strings all the time. 

These feel more suited to the Cookbook to me.  I don't feel there is likely enough call for them to include them in Ramda itself.  I did have to write `startsWith` and `endsWith` on a recent project, but that's one time in my 3+ years with Ramda.  The others I've never written with Ramda.

Other thoughts?

**Comment by olsonpm** [comment]
> But mostly we strike out on our own, building functions that seem useful to our community, and paying little heed to these others.

Hmm - I respect that decision though think you should consider the popularity of functions that other libraries include.  Functions are only popular out of need, and those which this community needs will not deviate much from the greater javascript population (besides those specific to functional programming of course)

> parable  

haha thanks for the correction and the link.  I definitely agree.

>  It's simply not the same logical function.  

Somehow I missed that and just assumed he was referencing `R.concat` which is already overloaded for such functionality.

**Comment by CrossEye** [comment]
We do consider functions for which people make requests, and popular functions from other libraries are more likely to be raised that way.  But their popularity is a fairly small factor.  We're much more interested in how useful they seem to us, how well they fit with Ramda's philosophy (we wouldn't even consider an impure function, for instance), how easy/difficult they are to implement, and how much excitement they generate in our discussions, all sorts of factors.

**Comment by olsonpm** [comment]
I appreciate the time you put into explanations @CrossEye .  Helps me learn a lot.

**Comment by ccorcos** [comment]
> These feel more suited to the Cookbook to me. I don't feel there is likely enough call for them to include them in Ramda itself.

Well you could say this about a lot of Ramda functions though:

```js
concat = R.curry((a,b) => a.concat(b))
```

Why is concat in Ramda and not just in the cookbook? Maybe I have a different perspective here, but I like to think of Ramda as a standard library for my projects. And in that regard, I find it convenient to have these sorts of string functions...

**Comment by buzzdecafe** [comment]
`concat` is not a good example to illustrate the point you are trying to make. that is the fundamental operation that defines a [semigroup](https://github.com/fantasyland/fantasy-land#semigroup). So it makes sense we would take control of that one.

**Comment by ccorcos** [comment]
Yeah, but my point is that we shouldn't have `concat` -- I would like to see Ramda have all kinds of useful functions. Even if they are one liners.

**Comment by buzzdecafe** [comment]
@ccorcos i am 100% in the other direction. I'd love to see the lib pared down to just the essentials. should make for interesting discussion :-)

**Comment by CrossEye** [comment]
I'll be the referee; I keep bouncing between these two points of view, but can't quite find the balance I'd like to strike.

**Comment by ccorcos** [comment]
Well one place to start is the `left-pad` fiasco. Surely, you could write your own, and there are a million ways to do it. Here's my one liner:

```js
const leftPad = (str, n, char) => Array(Math.max(str.length - n, 0)).fill(char).concat([str]).join('')
```

But why should I have to write and test this function?

So then I might go [looking on npm](https://www.npmjs.com/package/left-pad). Holy crap! 300k downloads last month?! lol. I was no expecting that... I'm sure this function works though and now I don't have to write test for it. But now we're just bloating our dependencies (and then the whole left-pad fiasco). Sure I could use `underscore.string`, but the arguments are going to be in the wrong order and thats really annoying.

So what if you could just use `R.leftPad`? Its going to be curried. There arguments are going to be in the correct order. Its going to be tested, and we're using Ramda everywhere already! So whats the harm? Its not like `leftPad` is going to involve any maintenance for the library maintainers. Or maybe you're worried about the side of the library? Well its not to hard to create a [babel plugin](https://github.com/lodash/babel-plugin-lodash) to cherry-pick only the functions you want from Ramda.

So that's it for my main argument, but while we're on the topic, I want to fantasize a little bit... 

I would *love* is Ramda become something like a standard library. Why do I need to write `R.map` -- shouldn't I be able to just write `map`? What kind of language doesn't have a `map`?! What if Ramda's functions were just global and you can use them freely. `leftPad`, `stripl`, `startsWith`... It would feel a lot more like programming in a language like Clojure which comes with batteries included. 

Idk if you guys have seen the [Wolfram Language](https://www.youtube.com/watch?v=_P9HqHVPeik) but its one of the most incredible things I've seen. They take "batteries included" to the max.

**Comment by olsonpm** [comment]
Any reason R can't be the bare-bones behind R.contrib (similar to lodash & underscore.contrib?)

https://github.com/node4good/lodash-contrib

Fwiw, I've never had an issue keeping my own set of utilities because I'm fully  aware of the ambiguity surrounding what functions "should" be in any given library.  In fact, functions that I write are more dependable than those from other libs which, although tested, still behave differently than my intuition expects.

**Comment by martinlechner1** [comment]
I second olsonpm's approach. This way the core would't become bloated, yet one could use a community driven utility lib for extended purposes.

**Comment by ccorcos** [comment]
I suppose... But thats just fragmenting the ecosystem even more... :/

**Comment by olsonpm** [comment]
It's the only solution to satisfy both trains of thought, and it's a proven solution.  You are never going to convince the maintainers of a given library to support "all kinds of useful functions".  I think of 'contrib' similar to community supported packages in a given linux repo.  Along with installing those packages comes added risk, less support, and all around more responsibility.

**Comment by CrossEye** [comment]
I could certainly live with such a solution.  It's been discussed several times, but no one has stepped forward to own it.  Such a package could clearly live in the same space that `ramda-fantasy`, `ramda-lens`, etc. live.  But it would be nice if there was some folks who wanted to own maintenance of it.

Of course I'm sure we'd still want to insist that the functions match Ramda's philosophy and design, but there could be less vetting of whether they were important enough to be included in the core.

**Comment by olsonpm** [comment]
Yeah that's another issue.  Finding someone who wants to invest that amount of time heh.

**Comment by ccorcos** [comment]
And documentation...
