### ISSUE TITLE
pickAll usecases?

### ISSUE THREAD

**Issue by olsonpm** [ramda/ramda#1876]
So I stumbled on pickAll because lodash's `pickAll` is equivalent to your `pick`.  In `R.pickAll` I was surprised to see the inclusion of the undefined properties.  What utility does that give?  I do know `delete obj.prop` is technically not the same as `obj.prop = undefined`, but I've yet to see a case where the difference carries semantic value.  As far as any readable program is concerned, an object with a property that's undefined should behave as it's not there in the first place.

My suggestion would be to rename pickAll to pickWithDefault or something of the sort, where the api allows the developer to specify a placeholder for when a property doesn't exist.  ~~In my mind null makes more sense than undefined as a default.  The user may want an empty string, a zero, or some other magical value instead.~~ (irrelevant)

**Comment by davidchambers** [comment]
> What utility does that give?

This may sound strange, but I find this line of thinking dangerous. A focus on convenience has led to many strange API decisions in the JavaScript world, such as functions which take three arguments, all of which are optional and which may be provided in any order!

What you're suggesting is perfectly reasonable, but there's a price to pay for the convenience of skipping each map entry whose value is `undefined`: information loss.

Current behaviour:

```javascript
> R.pick(['a', 'b', 'c'], {a: null, b: undefined})
{a: null, b: undefined}
```

Proposed behaviour:

```javascript
> R.pick(['a', 'b', 'c'], {a: null, b: undefined})
{a: null}
```

> I've yet to see a case where the difference carries semantic value

In the vast majority of cases there is no difference. Even if there is no difference in 99.99% of cases, I still don't feel comfortable having `R.pick` destroy information. If for some reason a caller *does* consider `{a: null, b: undefined}` and `{a: null}` to be meaningfully different values, she could no longer use `R.pick` if we were to make the proposed change. On the other hand, a caller who wants to treat these values as equivalent can simply filter the map:

```javascript
> R.reject(R.equals(undefined), {a: null, b: undefined})
{a: null}

> R.pick(['a', 'b', 'c'], R.reject(R.equals(undefined), {a: null, b: undefined}))
{a: null}
```

It's worth noting that `R.pick` is currently guilty of destroying information: from the return value we cannot determine the "set" of keys provided. We would need the Maybe type to preserve all the pertinent information:

```javascript
> R.pick(['a', 'b', 'c'], {a: null, b: undefined})
{a: Just(null), b: Just(undefined), c: Nothing}
```

It's also worth noting that many other Ramda functions destroy information: `R.nth`, `R.slice`, and the functions derived from these come to mind. The difference in this case, though, is that the function can preserve information (about the values) without the use of the Maybe type.

I'm interested in whether others consider preservation of information an important design principle for a general-purpose library such as Ramda.

**Comment by olsonpm** [comment]
Ehm - I'm referring to pickAll.  I removed an irrelevant portion of my original post.

```js
const obj = { a: 'this is a' };

R.pickAll(['a', 'b'], obj); // -> { a: 'this is a', b: undefined }

// vs pickAllWithDefault

R.pickAllWithDefault(['a', 'b'], 0, obj); // -> { a: 'this is a', b: 0 }
R.pickAllWithDefault(['a', 'b'], null, obj); // -> { a: 'this is a', b: null }
```

**Comment by davidchambers** [comment]
> Ehm - I'm referring to pickAll.

Oh! After using and contributing to Ramda for more than two years I had no idea that [`R.pickAll`][1] exists! I thought by "pickAll" you meant the Lodash function of that name, or the Ramda equivalent. I'm sorry about the confusion.

I now really like this API:

```javascript
> R.pick(['a', 'b', 'c'], {a: 42})
{a: Just(42), b: Nothing, c: Nothing}

> R.map(S.fromMaybe(0), R.pick(['a', 'b', 'c'], {a: 42}))
{a: 42, b: 0, c: 0}

> R.filter(S.isJust, R.pick(['a', 'b', 'c'], {a: 42}))
{a: Just(42)}

> R.map(S.toNullable, R.filter(S.isJust, R.pick(['a', 'b', 'c'], {a: 42})))
{a: 42}
```

It's flexible, and avoids the need for two "pick" functions. It's out of scope for Ramda, though.

> ```javascript
> R.pickAllWithDefault(['a', 'b'], 0, obj); // -> { a: 'this is a', b: 0 }
> R.pickAllWithDefault(['a', 'b'], null, obj); // -> { a: 'this is a', b: null }
> ```

I like the idea of replacing `R.pickAll` with `R.pickAllWithDefault`. Anyone wanting the current functionality could simply use `R.pickAllWithDefault(undefined)`. I think the default value should be the first argument, though, and I like the name you originally suggested: `pickWithDefault`.


[1]: http://ramdajs.com/docs/#pickAll

**Comment by olsonpm** [comment]
Yeah my original post was worded poorly - sorry for that.

**Comment by olsonpm** [comment]
I'm not familiar with FP enough to translate this into js
```js
R.pick(['a', 'b', 'c'], {a: 42}
// -> {a: Just(42), b: Nothing, c: Nothing}

// does this translate to
R.pick(['a', 'b', 'c'], {a: 42}
// -> {a: 42, b: undefined, c: undefined}
// ?
```

The only reason I ask is because I want your reasoning for why `b` and `c` should even be returned.  `R.pickAll` is only used in the ramda codebase in the 'project' function fyi, which I also think shouldn't be returning properties set to undefined.

Seems we're in agreement on the rest - and I didn't think about argument order, you're most likely right.

**Comment by davidchambers** [comment]
> I'm not familiar with FP enough to translate your example into js

Here's one possible implementation using [Sanctuary][1]:

```javascript
//    pick :: Array String -> StrMap a -> StrMap (Maybe a)
const pick = R.curry((keys, obj) =>
  S.reduce(memo => key => R.assoc(key,
                                  R.has(key, obj) ? S.Just(obj[key]) : S.Nothing(),
                                  memo),
           {},
           keys)
);
```


[1]: https://sanctuary.js.org/

**Comment by CrossEye** [comment]
I like the idea of replacing `pickAll` with `pickWithDefault`, and simply noting that those who want the somewhat odd current behavior of `pickAll` (was it done to match Codd's laws for `project` -- I can't recall?) need to use `pickWithDefault(undefined)`.

**Comment by olsonpm** [comment]
If I don't find time this weekend, I will definitely make time next to get a PR.  Thanks for the feedback.
