### ISSUE TITLE
Expose R to doc website devtool

### ISSUE THREAD

**Issue by thenikso** [ramda/ramda#1885]
Hey there, when I need to try out Ramda I default to go to http://ramdajs.com/docs/ and open up the devtools. It appear that `R` is no longer defined in the `window`!

Would you be so kind to put it back there? ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by buzzdecafe** [comment]
it's there. i think you may be encountering the chrome bug discussed here?: 
https://github.com/ramda/ramda/issues/1853

**Comment by thenikso** [comment]
I am 😨
