### ISSUE TITLE
differenceWith

### ISSUE THREAD

**Issue by awb99** [ramda/ramda#1886]
I am comparing lists of two different types with "differenceWith".
I now note, that the second parameter sometimes is of the first list.
Is this intended behavior?
Strangely it does not appear always. I made a hack for this now, but it seems
strange to me.
I use the version of today that is on npm.

```
var equals = (booking, calendarEvent) => {
            var dStart = new moment(booking.Arrival);
            var bookingDate = dStart.format('YYYY-MM-DD');
            var calDate = '';
            if (calendarEvent.start == null) {
                console.log(`*** booking; ** ${JSON.stringify(booking)}`)
                console.log(`*** calendarEvent: *** ${JSON.stringify(calendarEvent)}`);
                var dStart2 = new moment (booking.Arrival);
                calDate = dStart2.format('YYYY-MM-DD');
            } else {
                var calDate = calendarEvent.start.date; 
            }
            return (bookingDate === calDate);
        };
        var nb = R.differenceWith(equals, dbBookings, calendarEvents);
        return nb;
```

**Comment by CrossEye** [comment]
This is currently under discussion in #1868.

**Comment by aantipov** [comment]
Having exactly the same problem

**Comment by Achilles4400** [comment]
I don't know if this is the normal case, but I'm experiencing the same problem with the differenceWith function and the symmetricDifferenceWith function.
