### ISSUE TITLE
bug or i don't understand “evolve”

### ISSUE THREAD

**Issue by zatziky** [ramda/ramda#1887]
When using `Ramda.remove()` by itself the function takes an array and outputs an array:

    const grid = {rows: [1, 2, 3]};
    
    R.remove(1, 1, grid.rows) // output: [1,3]

When I use `Ramda.remove()` as a transformation function in `Ramda.evolve()` it becomes an object `{"0": 1, "1": 2, "2": 3}` instead of an array `[1,3]`:

    const grid = {rows: [1, 2, 3]};
    
    R.evolve({
      rows:  R.remove(1, 1, grid.rows)
    })(grid); // output:{"rows": {"0": 1, "1": 2, "2": 3}}

Do I understand `evolve` correctly or is a bug?

**Comment by zatziky** [comment]
Just when writing this issue I realized what's wrong. I had to wrap `R.remove` in a function or bind the args. Basically, I needed to pass the reference to the function.

`rows: () => R.remove(1, 1, grid.rows)`

**Comment by davidchambers** [comment]
```javascript
> R.evolve({rows: R.remove(1, 1)}, {rows: [1, 2, 3]})
{rows: [1, 3]}
```

**Comment by CrossEye** [comment]
Yes, see also http://stackoverflow.com/questions/39267833/
