### ISSUE TITLE
Path array definition and normal definitions defer

### ISSUE THREAD

**Issue by udnisap** [ramda/ramda#1890]
This is more of an improvement to support the single item case
When `/a` is given as string it doesnt fetch the path but `['/a']` would return the correct value. 
```
console.log(R.path('/a', {'/a':{b:4}}))
console.log(R.path(['/a'], {'/a':{b:4}}))
```

http://ramdajs.com/repl/?v=0.22.1#?code=console.log%28R.path%28%27%2Fa%27%2C%20%7B%27%2Fa%27%3A%7Bb%3A4%7D%7D%29%29%0Aconsole.log%28R.path%28%5B%27%2Fa%27%5D%2C%20%7B%27%2Fa%27%3A%7Bb%3A4%7D%7D%29%29%0A

**Comment by buzzdecafe** [comment]
looks to me like it is behaving as designed and documented http://ramdajs.com/docs/#path

this is an error: `R.path('/a', {'/a':{b:4}})` You could argue it should blow up at that point. There's a good case to be made for that. But I don't see any reason to support Array or String for the first argument.

**Comment by CrossEye** [comment]
> But I don't see any reason to support Array-or-String for the first argument.

Agreed.  There's already `R.prop('/a', {'/a':{b:4}})` for that if you want it.
