### ISSUE TITLE
`forEach` to iterate over an object

### ISSUE THREAD

**Issue by centsent** [ramda/ramda#1893]
In my opinion, it will be better if `forEach` supports object iteration (like `lodash`'s forEach) .

BTW, I can open a PR to do this.

**Comment by davidchambers** [comment]
We could do one or both of the following:

  - update `R.forEach` to iterate an object's values; and/or
  - define `R.forEachObjIndexed` which would provide access to keys as well as values.

Ramda avoids ad hoc polymorphism, so having `R.forEach` provide one argument to the iteratee in some cases and *two* in other cases is not an option.

Until one or both of the above changes is made, one can of course use [`R.map`][1] or [`R.mapObjIndexed`][2] and ignore the result.


[1]: http://ramdajs.com/0.22.1/docs/#map
[2]: http://ramdajs.com/0.22.1/docs/#mapObjIndexed

**Comment by buzzdecafe** [comment]
> one can of course use `R.map` or `R.mapObjIndexed` and ignore the result.

:scream:

**Comment by mjgpy3** [comment]
I think if this is really needed `R.toPairs(obj).forEach(...)` should suffice.

It's hard to reconcile `forEach` with functional programming values.

**Comment by buzzdecafe** [comment]
> It's hard to reconcile `forEach` with functional programming values.

I agree; `forEach` is there for side effects. So it is a bit of a red-headed stepchild in the lib.

**Comment by centsent** [comment]
> It's hard to reconcile `forEach` with functional programming values.

Agree, close this issue or I implement `R. forEachObjIndexed `?

**Comment by davidchambers** [comment]
Since we have `R.forEach`, I think we should add `R.forEachObjIndexed`. Would you like to submit a pull request?

**Comment by ricejasonf** [comment]
Both `R.reduce` and `R.forEach` should call the "iterator" function with a pair for each key/value when an object is provided.

Just to reference another functional programming library, Boost.Hana has a `Foldable` concept that, for "objects", it folds on pairs (key/value).

I could try a pull request for this suggestion if you find it acceptable.

**Comment by buzzdecafe** [comment]
@ricejasonf  `reduce` is not well-defined for objects in javascript. This is a subject that has come up repeatedly around here. We'v come close to folding objects, but they've never made it in. The problem boils down to this: `reduce(f, acc, {a: 1, b: 2})` should be equal to `reduce(f, acc, {b: 2, a: 1})`. Easy to formulate the problem, but finding the correct answer -- if one exists -- is not so simple.

**Comment by ricejasonf** [comment]
Ah yeah, that's why Boost.Hana has a `Foldable` concept and then an `Iterable` concept where the former does not guarantee that it maintains the order. FWIW my only knowledge of functional programming laws is from using that library. :stuck_out_tongue:

**Comment by centsent** [comment]
@davidchambers OK, I'll submit a PR.

**Comment by zachlysobey** [comment]
@davidchambers can this be closed now that the PR is merged?
