### ISSUE TITLE
A pointfree question

### ISSUE THREAD

**Issue by kozer** [ramda/ramda#1896]
Hi to everyone! I discovered the concept of functional programming recently, and i like ramda and pointfree style a lot!
Although i have some questions and I dont know how to deal with them.
I write an application in which i fetch a bunch of objects.One of their property is an image url.
At the time i have something like this.

compose(chain(traverse(Future.of, saveItem)), fetchItems)(url)
.fork(err => {
console.log(err);
}, data => {
process.exit();
});

fetchItems return a Future (or Task, whatever) and then i save the items to the db.
I want before that to extract all the urls, download the images, and then save to db, replacing the image prop with my own path.
How is this possible in a pointfree way?
How i can 'split' the execution and keep track of the input?
For example if i had something like that
compose(chain(traverse(Future.of, saveItem)),chain(traverse(Future.of, downloadImages)), fetchItems)(url)

it would work because after the download, i would have only the images.
I hope someone can help me out so i can have a better understanding of the pointfree style!
Thank you very much!

**Comment by buzzdecafe** [comment]
Hi @kozer, welcome -- I think this question is better suited to the [gitter room](https://gitter.im/ramda/ramda). A lot of smart people hang out in there answering questions like this. I can offer some general advice: Don't make a fetish out of point-free style. It can be a fun challenge to try and write everything tacit, but it may also lead to hard-to-read code. Favor readability.

**Comment by kozer** [comment]
I didnt know about gitroom! I ll try there too! Yes i favor readability, but fp is mind bending, and i like to understand all conscepts. Thank you for the response!
