### ISSUE TITLE
addIndex(reduceRight) produces an index 0->len instead of len->0

### ISSUE THREAD

**Issue by olsonpm** [ramda/ramda#1898]
Not sure this is an issue, but it's differing behavior from lodash and I wanted to know what the consequences of having an index that doesn't reflect the current element's position, but rather the iteration position.

At the very least it should be documented?  I'm mostly curious what you guys have to say given your experience.

Edit: Copy paste'able code

``` js
R.addIndex(R.reduceRight)(
  (res, cur, idx) => {
    console.log('cur: ' + cur);
    console.log('idx: ' + idx);
  }
  , ''
  , ['a', 'b', 'c']
);
// produces
// cur: c
// idx: 0
// cur: b
// idx: 1
// cur: a
// idx: 2
```

**Comment by buzzdecafe** [comment]
good question, this looks like an error to me, i would expect to see the index of the element as input, not as transformed.

**Comment by buzzdecafe** [comment]
i think the only reasonable solution here is to add `addIndexRight` which will decrement instead of increment

**Comment by olsonpm** [comment]
Yeah I don't have time to look at the code until tonight.  I was playing around in that area previously when figuring out how it worked generically (was impressed the implementation provided use outside of ramda functions).

**Comment by olsonpm** [comment]
Just checked it out - I agree that addIndexRight is the only practical solution.  I can submit a PR if/when that's the decided direction.

**Comment by CrossEye** [comment]
I agree that that's the only palatable option.

**Comment by asaf-romano** [comment]
Dare I say dispatching? reduceRight could expose addIndex semantics.
