### ISSUE TITLE
Inconsistent R.is(Number) behavior in node 6.3.1

### ISSUE THREAD

**Issue by ilkka** [ramda/ramda#1899]
Hi,

With either Ramda 0.21.0 or 0.22.0 installed I see this:

```
$ nvm exec 6 node -e 'console.log(require("ramda").is(Number,123))'
Running node v6.3.1 (npm v3.10.3)
true

$ nvm exec 6 node
Running node v6.3.1 (npm v3.10.3)
> console.log(require("ramda").is(Number,123))
false
undefined
>
```

The inconsistency goes away if using Node 4, where both versions work like the docs say (i.e. return true).

**Comment by ilkka** [comment]
Hm, I just tried this in Docker using `node:6` which includes 6.5.0, and there the problem goes away, so a bug specific to 6.3.1 maybe? Maybe I just gotta update my node :P

**Comment by ilkka** [comment]
Alright, this only happens on 6.3 so I guess it's a Node bug, sorry about the noise :)

**Comment by CrossEye** [comment]
I'm still curious as to why it happens, but I'm not going to spend too much effort on it....

**Comment by ilkka** [comment]
I replicated this in Docker with the official `node:6.3.1` image in a sort of poor man's cleanroom environment, so it would seem it's a problem with that specific Node version.
