### ISSUE TITLE
Extend the Philosophy section of the README with a Wiki page

### ISSUE THREAD

**Issue by fgarcia** [ramda/ramda#1901]
I although there is already a **Philosophy** section in the README, I've been finding very good conversations in some issues like [this one](https://github.com/ramda/ramda/issues/1447#issuecomment-188927694)

Some time ago I also saw an interesting thread about why `composeP` was not merged into `compose`

My proposal is to open a whole Philosophy Wiki to extend the text of the README where the authors can link to repeated requests that were refused for a good reason and/or common questions.

I like a lot many of the decisions the core contributors have made. There are lots of good decisions scattered across several issues that would be good having in one central place.

**Comment by buzzdecafe** [comment]
This would be a very interesting, although potentially contentious, project. I'd love to see it, and argue about it :smile:

**Comment by CrossEye** [comment]
No you wouldn't.

**Comment by CrossEye** [comment]
I could port my [philosophy post][pp] there if desired.

  [pp]: http://fr.umio.us/the-philosophy-of-ramda/

**Comment by buzzdecafe** [comment]
@CrossEye 
"An argument isn't just contradiction."

**Comment by CrossEye** [comment]
@buzzdecafe: Can be.
