### ISSUE TITLE
Add chainRec function from Fantasy Land

### ISSUE THREAD

**Issue by safareli** [ramda/ramda#1902]
As there is `chain` function in ramda I thought it would be nice also have `chainRec` from [ChainRec](https://github.com/fantasyland/fantasy-land#chainrec). Something like [this](https://gist.github.com/safareli/ea45b45bed99f32bae7002e19dcf13c2) should be default implementation for Array. If there is an interest in it, I would try to create a PR

**Comment by buzzdecafe** [comment]
I'm all for this; this should be a dispatchable function to support FL-compatibility

**Comment by CrossEye** [comment]
Absolutely.  I'd love to see it!

:herb:
