### ISSUE TITLE
Surprised that PipeP  doesn't also handle functions that return plain values like Promise.all

### ISSUE THREAD

**Issue by rmoskal** [ramda/ramda#1903]
Just a bit surprised that I have to wrap all my return values in a Promise.resolve();  I can live with it, but it would be nice to follow the standard promise convention!

**Comment by davidchambers** [comment]
One more reason to merge #1869. ;)

**Comment by cristianocd** [comment]
@rmoskal I use a modified pipeline where I don't need to care if functions return values, promises, or arrays of promises, while being sure that the pipeline will return a Promise:
```javascript
const openPromiseArray = when(isArrayLike, Promise.all)
const then = f => promise => promise.then(pipe(openPromiseArray, f))

const pipePromise = (...functions) =>
    pipe(
      Promise.resolve,
      ...map(then, functions)
    )
```

This is with `bluebird`. To use with native Promise just change the function calls.

**Comment by rmoskal** [comment]
I'll play with this now.  Thanks!
