### ISSUE TITLE
bug in R.difference when using R._

### ISSUE THREAD

**Issue by Hyperonic** [ramda/ramda#1907]
R.difference(R._, [1,2,3,4])([7,6,5,4,3])

gives error Cannot read property 'length' of undefined

**Comment by davezuko** [comment]
Looks like you may have forgotten an extra `_` in your placeholder. Just tried this in the REPL:

```js
R.difference(R._, [1,2,3,4])([7,6,5,4,3])   // your example, throws same error
R.difference(R.__, [1,2,3,4])([7,6,5,4,3]) // works
```
