### ISSUE TITLE
Remove currying related tests where it's unnecessary

### ISSUE THREAD

**Issue by safareli** [ramda/ramda#1909]
This tests should be removed as this behavior is tested in [invariants.js](https://github.com/ramda/ramda/blob/master/test/invariants.js):
- [`it('is curried', function() {...})`](https://github.com/ramda/ramda/search?utf8=%E2%9C%93&q=it%28%27is+curried%27%2C+function&type=Code)
- [`it('correctly reports the arity of curried versions', function() {...})`](https://github.com/ramda/ramda/search?utf8=%E2%9C%93&q=it%28%27correctly+reports+the+arity+of+curried+versions%27%2C+function&type=Code)

---

Creating this issue from discusstion [here #1908](https://github.com/ramda/ramda/pull/1908#r79291341)

**Comment by davidchambers** [comment]
The first list item should read `'is curried'` rather than `'is stacksafe'`. ;)

**Comment by safareli** [comment]
copy/paste :d, fixed

**Comment by davidchambers** [comment]
@CrossEye, I still think we should do this. I'll submit a pull request if you'll accept it.

**Comment by CrossEye** [comment]
Agreed, I just saw that this was linked to #1908, which I'd already tagged for discussion.  I didn't recognize that there is no real overlap.
