### ISSUE TITLE
Strange behaviour of R.contains and R.without

### ISSUE THREAD

**Issue by ChrisPenner** [ramda/ramda#1910]
So I actually discovered this when working with R.without, originally I was using R.without improperly: I neglected to realize that the first argument was supposed to be a list of values and passed it my string instead, e.g. `R.without("thing")` instead of `R.without(["thing"])`. Unfortunately however, there were no errors, and things actually seemed to work *mostly* correctly. This did result in really tough to find bugs though. Observe the following strange behaviour:
[Try it](http://ramdajs.com/repl/#?code=const%20derp%20%3D%20%5B%0A%20%20%22test%22%2C%22test1%22%2C%22test2%22%0A%5D%0A%0AR.without%28%22test2%22%2C%20derp%29%0A%0A)

```javascript
const arr = [
  "test","test1","test2"
]

R.without("test2", arr) //=> ["test1"]
```

wtf??

So I tracked it down a little further and found that it's likely caused by the behaviour of `contains`:

```javascript
contains("test", "mytest2") //=> true
```

Which, though correct in terms of substring logic, is a misuse of `contains` since Contains:

> contains :: a → [a] → Boolean
> Returns true if the specified value is equal, in R.equals terms, to at least one element of the given > list; false otherwise.

So since the signature in this case is `String -> String` and not `String -> [String]`, it should probably fail, or at least not work *almost* correctly.

So anyways, I fixed up my mistake, but perhaps we should patch `contains` to account for this possible misuse? What do you think?

**Comment by davidchambers** [comment]
I suggest taking [refuge from unsafe JavaScript][1].

```javascript
const R = require('ramda');
const $ = require('sanctuary-def');

const def = $.create({checkTypes: true, env: $.env});

const a = $.TypeVariable('a');

//    without :: Array a -> Array a -> Array a
const without =
def('without',
    {},
    [$.Array(a), $.Array(a), $.Array(a)],
    R.without);

without(['test2'], ['test', 'test1', 'test2']);
// => ['test', 'test1']

without('test2', ['test', 'test1', 'test2']);
// ! TypeError: Invalid value
//
//   without :: Array a -> Array a -> Array a
//              ^^^^^^^
//                 1
//
//   1)  "test2" :: String
//
//   The value at position 1 is not a member of ‘Array a’.
```

I would love to see Ramda embrace [sanctuary-def][2] and provide wonderfully helpful error messages such as the one above. This has been discussed in several threads over many months, and seems unlikely to happen. Some people don't seem to mind debugging from stack traces. :stuck_out_tongue_winking_eye:


[1]: https://sanctuary.js.org/
[2]: https://github.com/sanctuary-js/sanctuary-def

**Comment by CrossEye** [comment]
@ChrisPenner:
I need to think a little about whether I'd prefer to fix this by altering the useful secondary behavior, or by adding a second signature to the documentation.  The implementation is essentially

```js
curry((a, list) => indexOf(list, a, 0) >= 0)
```

which is useful with Strings or lists.

@davidchambers: 
Yes, I would love wonderful errors, but not at the expense of trying to turn a dynamically typed language into a statically typed one at run-time.

**Comment by davidchambers** [comment]
> Yes, I would love wonderful errors, but not at the expense of trying to turn a dynamically typed language into a statically typed one at run-time.

You could always run with `checkTypes: false`. This could be the default setting. At that point `def` is just `R.curry`.

Wouldn't it be nice, though, when presented with `undefined is not a function`, to flip the value to `true` and be told what the problem is? Are there any *disadvantages* to opt-in type checking over no type checking?

**Comment by CrossEye** [comment]
>  Are there any *disadvantages* to opt-in type checking over no type checking?

I think there are.

First of all, there's this transition:

from

```js
function append(x, xs) { return xs.concat([x]); }
```

to

```js
const a = $.TypeVariable('a');

const append =
  def('append',
      {},
      [a, $.Array(a), $.Array(a)],
      function(x, xs) { return xs.concat([x]); });
```

I personally find the former easier to understand.  Also, as I often work in a Web environment, the smaller file size is a clear advantage.

Secondly, there's the matter of the number of moving parts in the system.  Think of your question as though someone asked, "You can have this beautiful benefit at absolutely no cost."  Aren't you going to look for the catch?  To me part of the catch is having code that most of the time I don't care about sitting in my codebase.  It's the age-old problem of when to put debugging sub-systems in production environments.

Thirdly, I haven't been following closely enough to know if it's robust enough for what I want to do.  The discussion above makes me wonder whether we want to specifically document that `contains` delegates to `indexOf`.  But does `sanctuary-def` have a syntax that captures that?

So yes, I think there are disadvantages.

That doesn't mean I think they outweigh the advantages.  The idea that this could be off-by-default makes it much more interesting to me.  While I don't generally spend much time chasing down type errors in my code, when I do have them they can be obnoxious to find.  That makes this appealing.

I don't have an answer for myself yet, and I don't know how the rest of the commiters would feel, but this is certainly worth discussing again.

**Comment by davidchambers** [comment]
Great points, @CrossEye!

> I personally find the former easier to understand.

One could separate the implementations from the other `def` arguments if desired. For example:

```javascript
const append = def('append', {}, [a, $.Array(a), $.Array(a)], appendImpl);
const prepend = def('prepend', {}, [a, $.Array(a), $.Array(a)], prependImpl);
...

function appendImpl(x, xs) { return xs.concat([x]); }
function prependImpl(x, xs) { return [x].concat(xs); }
...
```

> Also, as I often work in a Web environment, the smaller file size is a clear advantage.

Yes, it is.

> To me part of the catch is having code that most of the time I don't care about sitting in my codebase.

Is this separate from your concern about file size?

I think this is a philosophical difference we've discussed in the past: wanting a program to crash as soon as it enters an invalid state versus wanting it to continue running if at all possible.

I *most* want to enforce invariants in production. If my `withdrawFromBankAccount` function takes a value of type `PositiveFiniteNumber`, I certainly don't want this to become `Any` in production. :stuck_out_tongue_winking_eye:

> I haven't been following closely enough to know if it's robust enough for what I want to do. The discussion above makes me wonder whether we want to specifically document that `contains` delegates to `indexOf`. But does `sanctuary-def` have a syntax that captures that?

We could assert that the value has an `indexOf` method, but we couldn't require the implementation to make use of it.

This point, though, strikes me as a disadvantage of sanctuary-def versus some more sophisticated type system, not a disadvantage of sanctuary-def versus no type checking.

> The idea that this could be off-by-default makes it much more interesting to me. While I don't generally spend much time chasing down type errors in my code, when I do have them they can be obnoxious to find. That makes this appealing.

:grinning:

> I don't have an answer for myself yet, and I don't know how the rest of the commiters would feel, but this is certainly worth discussing again.

I've opened #1912 to give us something concrete to look at.

**Comment by CrossEye** [comment]
>>To me part of the catch is having code that most of the time I don't care about sitting in my codebase.

> Is this separate from your concern about file size?

It is a separate concern, but if necessary, we can discuss it in #1912.
