### ISSUE TITLE
Blackbird Combinator

### ISSUE THREAD

**Issue by ccorcos** [ramda/ramda#1915]
Have you guys seen [this talk](https://www.youtube.com/watch?v=seVSlKazsNk&list=PLcGKfGEEONaDvuLDFFKRfzbsaBuVVXdYa&index=20) from Strange Loop 2016? I'm not so familiar with all this Haskell stuff but it looks really cool. 

I can't seem to get his examples to work though:

``` js
> blackbird = R.compose(R.compose, R.compose)
[Function]
> aggregate = blackbird(R.sum, R.map)
[Function]
> totalNumber = aggregate(R.length)
TypeError: reduce: list must be array or iterable
```

Anyone else interested in trying to see this through?

**Comment by CrossEye** [comment]
Haven't watched the video yet. 

But note that 

   aggregate(R.length, [[1, 2], [1, 2, 3]]); //=> 5

There's probably some way to curry that so that it works as you would like.  But I haven't thought it through.

**Comment by ccorcos** [comment]
hmmm. so this is what needs to happen

```js
R.compose(R.compose(R.sum), (R.compose(R.map)(R.length)))([[1],[1,2]])
```

He wrote this haskell code defining the blackbird combinator: `(...) = (.) . (.)` and also wrote that `f ... g = (f .) . g` so the compositions look like theyre in different places... (check out the video around 11:00)

When we write `blackbird = R.compose(R.compose, R.compose)` I think what's happening is this:

```js
R.compose(R.compose, R.compose)(R.sum, R.map)
R.compose(R.compose(R.sum), R.map)
```
I'm not sure why these definitions arent translating over properly. Maybe someone who know Haskell better can help.

**Comment by ccorcos** [comment]
So this last line tries to run `R.sum`.

```js
R.compose(R.sum)(R.map(R.length))
```

So if I define my own compose, I can get this to work:

```js
compose = a => b => c => a(b(c))
compose(R.sum)(R.map(R.length))([[1,2,3], [4,5]])
```

But this one doesnt work -- it returns a function

```js
compose(compose(R.sum), R.map)(R.length)([[1,2,3], [4,5]])
```

**Comment by jackfirth** [comment]
Ramda's compose isn't equivalent to Haskell's compose. Ramda's is *variadic*, accepting any number of functions. So when you R.compose(R.compose, R.compose), the result you get is the composition of a variadic function with another variadic function. I don't know how exactly that turns out in Ramda, but that's the reason it behaves differently than Haskell's composition and your hand-rolled binary composition.

**Comment by davidchambers** [comment]
You need [`S.compose`][1], which behaves like Haskell's `(.)`:

```javascript
//    blackbird :: (c -> d) -> (a -> b -> c) -> a -> b -> d
const blackbird = S.compose(S.compose, S.compose);

blackbird(R.sum)(R.map)(R.length)([[1,2,3],[4,5]]);
// => 5
```

Pretty nice! I'm open to a pull request if you'd like to add `blackbird` to Sanctuary's [combinators][2].


[1]: https://sanctuary.js.org/#compose
[2]: https://sanctuary.js.org/#combinator

**Comment by ccorcos** [comment]
ahhh. this works

```js
compose(R.sum)(R.map(R.length))([[1,2,3], [4,5]])
```

@davidchambers have you checked out FlowType? I've been pretty impressed with it. I'm curious what you think about it as an alternative to runtime type checking with Sanctuary.

This is an interesting library that you'd probably be better suited to evaluate than me: https://github.com/gcanti/flow-static-land

**Comment by davidchambers** [comment]
> @davidchambers have you checked out FlowType? I've been pretty impressed with it.

Flow is very interesting. I haven't yet used it, though. I'd like to see how it compares to sanctuary-def in terms of expressiveness. Compile-time checking is a boon, certainly.

TypeScript, on the other hand, is of little interest to me. An unsound type system is a missed opportunity.

**Comment by ccorcos** [comment]
> An unsound type system is a missed opportunity.

YES. I don't know what value you get out of a type system that has holes throughout it

**Comment by jasonkuhrt** [comment]
> TypeScript, on the other hand, is of little interest to me. An unsound type system is a missed opportunity.

OT but curious what you think of 2.0 given it has null-free programming option now.

**Comment by buzzdecafe** [comment]
IMO this is a bug in `compose` that should be fixed

**Comment by tycho01** [comment]
> TypeScript, on the other hand, is of little interest to me. An unsound type system is a missed opportunity.

@davidchambers: would you mind expanding on that? I'd like to raise concerns with them in hope for improvement.

**Comment by ccorcos** [comment]
@tycho01 the terms [soundness](https://en.wikipedia.org/wiki/Soundness) and [completeness](https://en.wikipedia.org/wiki/Completeness_(logic)) come from concepts from propositional logic.

In regards to a type system, a sounds type system is one where its impossible to compile a program that has a (uncaught) runtime exception.

The problem with the Java type system, for example, is that all types are by default nullable, yet the type system does not force you to null check them. Thus a program can compile and have runtime exceptions! Thus the type system doesn't actually give you any confidence that your program is correct and bug-free. 

TypeScript seems to have adopted this with the release of 2.0, although it looks like you need to set the compiler option.

https://blog.mariusschulz.com/2016/09/27/typescript-2-0-non-nullable-types

TypeScript does have a lot more features and development than Flow lately.

**Comment by davidchambers** [comment]
Thanks, @ccorcos. That's what I had in mind. TypeScript simply isn't *ambitious* enough to excite me. It may still be a useful tool, but I haven't yet had a reason to use it.

**Comment by tycho01** [comment]
@ccorcos @davidchambers Thanks.

I've definitely felt my share of [pain](https://github.com/Microsoft/TypeScript/issues/12838) trying to properly type Ramda with TS recently, but I suppose that'd be implementation rather than its ambition. I'm personally in the Angular 2 boat though, so yeah, I'd better figure stuff out there.

The null checks may solve a bit, but right now its failure to properly handle generics generically (for currying, composition) is still a bit of a let-down for Ramda... `compose(identity)` is currently enough to screw it up, `path` doesn't handle tuples despite its [current](https://github.com/donnut/typescript-ramda/blob/master/index.d.ts#L1707-L1871) verbosity, and `map` over tuples / heterogeneous objects also can't be done yet.

And here I was hoping Flow was doing better :P, though I wouldn't personally be able to make use of it considering ecosystem lock-in anyway.

**Comment by ccorcos** [comment]
I really like how [this talk](https://vimeo.com/153097877) approaches partial application. It seems like a much more idiomatic way of currying with `leftApply` and `rightApply`. I'd imagine thats a lot easier to statically type than the way Ramda's auto-curry works.

I'm no expert in type systems, but I thought [this was a fascinating article](https://medium.com/@gcanti/higher-kinded-types-in-flow-275b657992b7#.6ehcozydh) explaining Higher Kinded Types in a way I could actually understand. That might be able to help you with your problem.
