### ISSUE TITLE
`without` method doesn't use `equals` like it says in the documentation

### ISSUE THREAD

**Issue by portons** [ramda/ramda#1918]
I'm on version 0.21.
While I'm trying to use `without` function to remove exact strings from a strings array, some items are being removed (mistakenly?) due to usage of `flip`+`contains` methods.

Example:
```javascript
R.without("ab", ["a","ab"])
// output: []
```

I would expect that the output would be ["a"] because it's a completely different item (although it is being contained by "ab" string)

You can run this code [here](https://runkit.com/57e7744a900b9c13004ecbe9/57e7744a900b9c13004ecbea)

**Comment by davidchambers** [comment]
You have a type error:

```javascript
without('ab', ['a', 'ab']);
// ! TypeError: Invalid value
//
//   without :: Array a -> Array a -> Array a
//              ^^^^^^^
//                 1
//
//   1)  "ab" :: String
//
//   The value at position 1 is not a member of ‘Array a’.
```

Correct usage:

```javascript
without(['ab'], ['a', 'ab']);
// => ['a']
```

See #1912.
