### ISSUE TITLE
mapObjIndexed for Array?

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#1919]
I'd noticed that `R.map` lacks a key/index argument, while `R.mapObjIndexed` sort of works on arrays as well... if you don't mind the result suddenly becoming an object instead.
Proposed fixes, from easiest to potentially more controversial:
- addition of a `R.mapArrayIndexed`
- altering `R.mapObjIndexed` so as to work with arrays as well (as in don't change the mapped result into objects)
- have `R.map` provide a key argument so we can just stick with one function regardless of arrays/objects/indices...

**Comment by davidchambers** [comment]
You're looking for [`R.addIndex`][1]. ;)


[1]: http://ramdajs.com/0.22.1/docs/#addIndex

**Comment by tycho01** [comment]
Great, thanks! :D

**Comment by tycho01** [comment]
@babakness that change becomes unsafe once your function had an optional second argument that's not this index.

**Comment by Bradcomp** [comment]
The classic example is `['1', '2', '3'].map(parseInt);` which fails miserably, while Ramda's map will work just fine.

**Comment by babakness** [comment]
Ah... makes sense! Thanks.

**Comment by CrossEye** [comment]
There's another important reason beyond the `parseInt`-style examples.  `map` is a much more general function than just working on arrays.  It's the function used in all [Functors][fu].  There are many data types which can be unified by all working with `map`.  But that has a very specific requirement:

```hs
map :: Functor f => (a -> b) -> f a -> f b
```
which says that if `f a` is some functor type (such as arrays, objects, functions, `Maybe`s, `Either`s, `Future`s, or many more) over the type `a` and you have a function that converts an `a` to a `b`, then when you call map on that function and a member of that functor, you get back another of the same functor over the type `b`.

So

```js
// length :: string -> int, a :: string, b :: int)
map(length, ["what's", "up", "doc"]) //=>  [6, 2, 3]  // (f :: Array)
map(length, {a: 'shave', b: 'and', c: 'haircut'}) //=> {a: 5, b: 3, c: 7} // (f :: Object) 
map(length, Maybe.Just('foo')) //=> Maybe.Just(3) // (f :: Maybe)
map(length, Maybe.Nothing)) //=> Maybe.Nothing // (f :: Maybe)
map(length, Future('foo')) //=> Future(3) // (f :: Future)
map(length, (a -> string) //=> (a -> int) // (f :: Function)
/// etc.
```

But this depends on the specific signature of `map`, which does not admit a second (or third!) parameter.

  [fu]: https://github.com/fantasyland/fantasy-land#functor
