### ISSUE TITLE
leaking arguments object causes deopts

### ISSUE THREAD

**Issue by jaawerth** [ramda/ramda#1920]
I noticed Ramda methods like `curry`, as well as [many others throughout the codebase](https://github.com/ramda/ramda/search?utf8=%E2%9C%93&q=_slice%28arguments%29&type=Code) are passing the `arguments` object into functions (mostly `_slice` ~~or `Function#apply`~~ [_not apply - see comments_] quite frequently, including heavily-used internal utilities. In modern JS engines, and v8 in particular, this is a known [optimization killer](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments).
## More background

Babel itself originally implemented rest args by compiling them into something along the same lines as `var _args = _slice(arguments)` but eventually updated to use the copy-loop approach as well, along with a number of other optimizations, and avoids leaking `arguments`.

https://github.com/babel/babel/pull/2833
## Solution

Removing this use of `_slice` ~~and `apply`~~ by either adding a build step that allows for args `rest` and `spread` (a SweetJS macro, babel, etc) or manually replacing it with a primitive copy loop as shown in the link above should improve performance across the board.

Personally I'd recommend adding a build step (it can be as simple as using babel with only a few specific plugins if you don't want unpredictable side effects) to avoid the maintainability/readability issues of making this change manually. Has anyone given this much thought? Adding a build step is a major change, so I wanted to bring it up here before I go and do it myself and submit a PR.

**Comment by buzzdecafe** [comment]
@jaawerth thanks for the heads up. i think we want to get 1.0 out the door first. Then moving to ES6/rollup would make what you are proposing simpler. I hope we can get 1.0 out in the next few weeks?

**Comment by bergus** [comment]
@jaawerth Notice that `fn.apply(this, arguments);` is explicitly exempt from being an optimisation killer

**Comment by jaawerth** [comment]
@buzzdecafe Ah, good point regarding `apply` - I added that bit last-minute, that's what I get for over-editing ;-).

@buzzdecafe - That makes sense. While it isn't too hard, this wouldn't be a trivial change, particularly if you're in the midst of a major release!

**Comment by CrossEye** [comment]
I agree that we need to think about this.  But I also believe we need to think very hard before we decide to pursue it.  We haven't had real-world complaints about the speed here, and I hate to optimize on spec.

There are other places where we know we have speed problems, especially where value equality slows us down compared to possible reference equality versions.  Those we clearly need to address as best we can subject to our constraints.  But it's not clear to me that we need to address something like this.

**Comment by bergus** [comment]
Assuming ES6, the trivial `slice.call(arguments)` with index 0 could be replaced by

    Array.of.apply(Array, arguments)
