### ISSUE TITLE
Ramda REPL atom package

### ISSUE THREAD

**Issue by Joe-Withey** [ramda/ramda#1927]
Hey dudes, me and a buddy of mine made a little atom package to give you a REPL provisioned with Ramda in your text editor : [https://atom.io/packages/ramda-repl](https://atom.io/packages/ramda-repl).

Thanks for the great library!

**Comment by buzzdecafe** [comment]
wow @Joe-Withey that is really cool! where is the vim plugin 😜

**Comment by CrossEye** [comment]
Very nice!  I haven't used atom much, but recently started playing around with it.  I can't wait to give this a try.

**Comment by Joe-Withey** [comment]
@buzzdecafe I have a setup in neovim using tmux [tmux](https://github.com/tmux/tmux) and the package [vim-slime](https://github.com/jpalardy/vim-slime) which is very flexible as you essentially use it to broadcast highlighted code to the stdin of any tmux emulated shell. You can use it to send your code to a shell running [Ramda REPL](https://github.com/hemanth/ramda-repl). From there you can get really creative piping process's to each other.

**Comment by buzzdecafe** [comment]
would be nice to add a list of ramda-related tools on the wiki or website (or both)

**Comment by MrRacoon** [comment]
You guys have a cli interpreter yet?: [https://www.npmjs.com/package/r_](r_)
Ramda rocks my world. Thanks all.
