### ISSUE TITLE
Slightly unintuitive behavior around null and undefined JS values for 'clamp'

### ISSUE THREAD

**Issue by habu-mark** [ramda/ramda#1931]
Having tried clamp out, it appears that undefined works as per my intuition, but null behaves differently.

```
// undefined min - works as expected
clamp(undefined, 4, 5)  // 4
clamp(undefined, 4, -5)  // -5
```

```
// undefined max - works as expected
clamp(1, undefined, 5)  // 5
clamp(1, undefined, -5)  // 1
```

```
// null min or max - strange behavior
clamp(null, 4, -5)  // null
clamp(1, null, 5)  // throws an error
```

Should this be changed? I'm happy to submit a pull request if the Ramda team think it's worth pursuing

**Comment by habu-mark** [comment]
My thought was probably coming from an English language perspective where 'undefined maximum' basically means the same thing as 'no maximum'.

I would certainly agree with you if Javascript were a typed language, as `undefined` would have no place in this particular polymorphic function. However, in Ramda, as in Javascript, there is a balance to be struck between pragmatism and idealism, and treating undefined-like values as the absence of a limit seems a good, pragmatic use-case.

Either way, `null` and `undefined` should work the same as each other.

**Comment by buzzdecafe** [comment]
>  However, in Ramda, as in Javascript, there is a balance to be struck between pragmatism and idealism

indeed. that seems to keep coming up around here :smile: 

>  treating undefined-like values as the absence of a limit seems a good, pragmatic use-case.

I think I disagree; JS provides `Infinity` and `-Infinity` that are certainly a better fit there. I think overloading `undefined` and `null` to mean `+/- Infinity` would be muddying the water.

**Comment by habu-mark** [comment]
Well, undefined and null wouldn't **just** mean +/- Infinity. Since clamp is polymorphic over Ord, they would also mean 'A'/'z' and new Date(-8640000000000000)/new Date(8640000000000000).

I would find it a useful convenience to not have to know those values when I simply mean to state an unrestrained minimum or maximum.

**Comment by buzzdecafe** [comment]
> Since clamp is polymorphic over Ord, they would also mean 'A'/'z' and new Date(-8640000000000000)/new Date(8640000000000000).

Good point. However, I don't think this implies that `undefined/null` should fill the gap. But I am curious to hear from others on this.

**Comment by davidchambers** [comment]
> Since clamp is polymorphic over Ord, they would also mean 'A'/'z'

Where do `'A'` and `'z'` come from? Why should the range be from `'\u0041'` to `'\u007A'`? This strikes me as arbitrary. Why not the ASCII range or the Unicode range? Also, why single-character strings? `'zz' > 'z' = true`, so why not `'zz'` rather than `'z'`?

I'm strongly opposed to changing the type from `Ord a => a -> a -> a -> a` to `Ord a => Nullable a -> Nullable a -> a -> a`. I don't want `null` or `undefined` to appear *anywhere* in my programs.

**Comment by CrossEye** [comment]
> ... and treating undefined-like values as the absence of a limit seems a good, pragmatic use-case.

I think that if we want that behavior, it would be more in keeping with the spirit of Ramda to define `clampBelow` and `clampAbove` than to make a parameter do double-duty.  I don't know if we'd accept a PR for those, but I promise it would receive a full hearing if you think such behavior is important enough to justify new functions.

> Either way, null and undefined should work the same as each other.

When convenient, yes.  But I don't spend a lot of time worrying about the behavior of functions when people supply such inputs.

**Comment by habu-mark** [comment]
I'm closing this issue down due to a lack of support for my proposed solution. Thanks to all for taking the time to read and consider my suggestion.
