### ISSUE TITLE
How to group List of object by object's props, as follows:

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#1932]
``` js
const list = [
  {
    a: 1,
    b: 2,
    c: 3,
  },
  {
    a: 4,
    b: 5,
    c: 6,
  },
  {
    a: 7,
    b: 8,
    c: 9,
  }
];

// transformed result:
const groupByProp = {
  a: [1, 4, 7],
  b: [2, 5, 8],
  ...
}
```

**Comment by honzabrecka** [comment]
```js
const groupByProp = converge(reduce(mergeWith(flip(append))), [pipe(head, keys, reduce((r, k) => assoc(k, [], r), {})), identity])
```

**Comment by adispring** [comment]
good job! 👍

**Comment by CrossEye** [comment]
Or perhaps

```js
const groupByProp = pipe(chain(toPairs), groupBy(head), map(pluck(1)));
```
(That last bit could be replaced with `map(map(last))` if that seems more readable.

```js
pipe(
  chain(toPairs), // [["a", 1], ["b", 2], ["c", 3], ["a", 4], ...]
  groupBy(head),  // {"a": [["a", 1], ["a", 4], ["a", 7]], "b": [["b", 2], ...], ... } 
  map(pluck(1))   // {"a": [1, 4, 7], "b": [2, 5, 8], "c": [3, 6, 9]}
  // or map(map(last))
)(list)
```

You can see this on **[the REPL][rr]**.

  [rr]: https://goo.gl/EixsGK

**Comment by adispring** [comment]
> ```js
const groupByProp = pipe(chain(toPairs), groupBy(head), map(pluck(1)));
```
this implement is better, it can handle one more conditon: if object in list don't have the same keys. as follows:
```js
const list = [
  {
    a: 1,
    b: 2,
  },
  {
    b: 5,
    c: 6,
  },
  {
    a: 8,
    c: 9,
  }
];

// output
{
  a: [1, 8],
  b: [2, 5],
  c: [6, 9]
}
```

**Comment by carlosmori** [comment]
Hey! I had the same issue, try this , it should work! 
I know is closed but, anyway:

**Input**

`const list = [
  {
    a: 1,
    b: 2,
  },
  {
    b: 5,
    c: 6,
  },
  {
    a: 8,
    c: 9,
  }
];`

**Solution**

```
const concatNum = useWith(concat, [unless(Array.isArray, of), of])
reduce(mergeWith(concatNum),{})(list)
```

**output**

`{
  a: [1, 8],
  b: [2, 5],
  c: [6, 9]
}`


**Check** [**REPL**](https://ramdajs.com/repl/#const%20list%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20a%3A%201%2C%0A%20%20%20%20b%3A%202%2C%0A%20%20%20%20c%3A%203%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20a%3A%204%2C%0A%20%20%20%20b%3A%205%2C%0A%20%20%20%20c%3A%206%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20a%3A%207%2C%0A%20%20%20%20b%3A%208%2C%0A%20%20%20%20c%3A%209%2C%0A%20%20%7D%0A%5D%3B%0A%0Aconst%20concatNum%20%3D%20useWith%28concat%2C%20%5Bunless%28Array.isArray%2C%20of%29%2C%20of%5D%29%0A%0Areduce%28mergeWith%28concatNum%29%2C%7B%7D%29%28list%29%0A)
