### ISSUE TITLE
Is there something wrong with _curryN?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#1934]
I write wrong number of arguments to curried function, but it does not throw warning or error

``` js
const R = require('./node_modules/ramda');
const internal = './node_modules/ramda/src/internal';
const _arity = require(`${internal}/_arity`);
const _isPlaceholder = require(`${internal}/_isPlaceholder`);
const _curryN = require(`${internal}/_curryN`);
const add = (a , b, c) => a + b + c;
const addC = _curryN(3, [], add);
const addC1 = addC(R.__, R.__, R.__);
const addC2 = addC1(R.__, R.__, R.__, 5);
const addC3 = addC2(6, 7);
console.log(addC3); //output 13
```

and what condition will argsIndx >= arguments.length? in _curryN.js

``` js
module.exports = function _curryN(length, received, fn) {
  return function() {
    var combined = [];
    var argsIdx = 0;
    var left = length;
    var combinedIdx = 0;
    while (combinedIdx < received.length || argsIdx < arguments.length) {
      var result;
      if (combinedIdx < received.length &&
          (!_isPlaceholder(received[combinedIdx]) ||
           argsIdx >= arguments.length)) {
        result = received[combinedIdx];
      } else {
        result = arguments[argsIdx];
        argsIdx += 1;
      }
      combined[combinedIdx] = result;
      if (!_isPlaceholder(result)) {
        left -= 1;
      }
      combinedIdx += 1;
    }
    return left <= 0 ? fn.apply(this, combined)
                     : _arity(left, _curryN(length, combined, fn));
  };
};
```

**Comment by CrossEye** [comment]
No, this definitely exposes a flaw in that logic, albeit an obscure one.  By passing `(__, __, __, 5)` to a function fixed to three positions, we're essentially passing those arguments on to the next call.  Then when you call with `(6, 7)` the fill-in-the-blanks logic calls your add function with the parameters `(6, 7, __, 5)`.

This should mean that it will try to add 6, 7, and the placeholder, which would yield [different output][do] than you suggested, something like `"13[object Object]"`.

This is part of why I don't like our placeholders very much.

I'll try to work up a fix tomorrow.

  [do]: https://runkit.com/57ef1279751b541400b3e105/5802c33461df8e0013102bf2

**Comment by CrossEye** [comment]
> [In] what condition will argsIndx >= arguments.length? in _curryN.js

Well, they could definitely be equal on the initial iteration, if no arguments are supplied.

**Comment by adispring** [comment]
I know that unit test should not be overused, but internal modules are core part of the lib, external apis rely on internal modules.
If the core part of a system is not reliable, it can hardly to say that the whole system is reliable/stable. That's my worry about it.

**Comment by CrossEye** [comment]
> I'll try to work up a fix tomorrow.

... or the next day.  :frowning_face:
