### ISSUE TITLE
`where` TypeError

### ISSUE THREAD

**Issue by alex-deas** [ramda/ramda#1939]
In the following code:

```
const one = {
  a: 'foo',
  b: { c: 'bar' }
};

const two = {
  a: 'foo',
  b: 'bar'
};

const three = {
  a: 'foo'
};

const func = where({
  a: equals('foo'),
  b: propEq('c', 'bar')
});

expect(func(one)).toEqual(true);           // true
expect(func(two)).toEqual(false);          // false
expect(func(three)).toEqual(false);       // TypeError: Cannot read property 'c' of undefined
```

From the docs the type error should be false here or am I getting the wrong end of the stick with the `where` function?

**Comment by buzzdecafe** [comment]
interesting. i think the issue is with `propEq` really: `propEq('c', 1, undefined); //=> TypeError`

This seems like good behavior. Where in the docs does it say the third example would be supported?

**Comment by alex-deas** [comment]
The docs say "Each predicate is applied to the value of the corresponding property of the test object". I understood this to mean that so long the function can take the value it should evaluate to a Boolean. This would expand to `propEq('c', 'bar')({ c: 'bar' });`.

I'll probably take a look at this tonight and try to get it working.

**Comment by buzzdecafe** [comment]
> So `where` should probably handle an undefined property before passing it in when the key is lookup up.

I don't think this conclusion follows. I'd rather that the function throw than swallow the error.

**Comment by alex-deas** [comment]
A possible use case would be if we have an array such as:
```
var arr = [
  {
    type: 'a',
    parent: {
      type: 'b',
      also: 'c'
    }
    }
  },
  {
    type: 'a',
  }
]
```

Then calling something like:
`filter(where({ type: equals('a'), parent: propEq('type', 'b') }))(arr)` - this would throw a type error whereas it would be better to (at least in cases when data format can't be assured) to just return false from the `where`.

I think there's a case for having that sort of function, even if it isn't necessarily `where`. Wrapping it in a tryCatch only to return false is just messy imo.

**Comment by kedashoe** [comment]
Note you can use `pathEq`: https://goo.gl/ty1lJe

Maybe best to normalize your data before though?

I believe the difference between `prop` and `path` have come up in the past, current behavior does feel wrong.
