### ISSUE TITLE
R.without - unexpected result/bug

### ISSUE THREAD

**Issue by theanimal666** [ramda/ramda#1940]
The without function behavves very strange whan passing a string instead of an array as first argument:

```
> const R = require('ramda');
undefined
> R.without('242', ['242', '42', '2', '4', '21']);
[ '21' ]
```

i would expect either to get en error telling me to pass an array as first argument or when handling the string as an array it should IMHO filter only the elements '2' & '4'

**Comment by Bradcomp** [comment]
See the discussion at https://github.com/ramda/ramda/issues/1910 for more thoughts on this subject.
