### ISSUE TITLE
Path and prop handle undefined inconsistently

### ISSUE THREAD

**Issue by thomaslloyd** [ramda/ramda#1941]
I've noticed that `prop` and `path` handle an undefined object inconsistently:

```
R.path(['a'], undefined)     // => undefined 
R.prop('a', undefined)       // throws error: Cannot read property 'a' of undefined
```

To me it feels as if `prop(x)` should be equivalent to `path([x])`. Is this difference a conscious decision? If not, it may be worth aligning them to avoid tripping up devs who assume they are interchangeable and try "simplifying" from `path([x])` into `prop(x)`.

**Comment by CrossEye** [comment]
I would be in favor of normalizing, but I don't feel any great urgency about it.  As always when people supply bad data: _caveat emptor_!

**Comment by thomaslloyd** [comment]
That is true, but there are always situations where coding defensively against an undefined value is useful.

If you have a preference as to which response is preferable, I don't mind submitting a small PR for the change.

**Comment by CrossEye** [comment]
My choice would be `undefined`.  I'm not sure how widely shared that is, but I hate throwing errors unless absolutely necessary.

**Comment by ChrisPenner** [comment]
I've run into this a few times, I also would prefer to return undefined.

**Comment by datenreisender** [comment]
I also support to return `undefined` in both functions if the object to query is `undefined`. And please test and document the behaviour in both cases, as it is currently undocumented  behaviour for `path`.

**Comment by kedashoe** [comment]
> My choice would be undefined. I'm not sure how widely shared that is, but I hate throwing errors unless absolutely necessary.

Sounds good to me. Would you like to submit a pull request @thomaslloyd ?

**Comment by kedashoe** [comment]
Hmm, looking at this again I did not see exactly what was being proposed. I would rather throw in `path` to get these two functions aligned.

**Comment by datenreisender** [comment]
Proposed is, that `R.prop('a', undefined)` should return `undefined`. I (and it seems like also others) support that idea, because changing `path` so that it throws would break more of our code. 

I will try to create a pull request including tests in the next days.
