### ISSUE TITLE
Any interest in a currying syntax extension?

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#1942]
I was considering putting together a babel syntax extension to make curried functions feel more lightweight. Something like:

``` javascript
function % (a, b, c)
{
}
```

which transpiles to:

``` javascript
R.curryN(3, function (a,b,c) { })
```

It would work on arrow functions too, etc. I have no attachment to any particular syntax, but was curious what the thoughts were.

**Comment by CrossEye** [comment]
I have absolutely no experience with babel syntax extensions, but this sounds interesting.  I'd love to see it.  I could easily see it being something that the Ramda community would give its blessing to.

**Comment by davidchambers** [comment]
See also sanctuary-js/sanctuary-def#39

**Comment by ndaidong** [comment]
I'm not really interested in making new syntax! Please keep it as pure JavaScript.

**Comment by tolmasky** [comment]
It occurs to me that one of the potential benefits of implementing a syntax transformation is that a lot of this behavior can be inlined, such that curryN never shows up in your stack trace (and possibly helps performance as well).

```
function f(a)(b)(c)
{
}
```

Can become:

```
function f(a, b, c)
{
   if (arguments.length < 3)
    ...
}

```
Interestingly, if you know you are targeting node 6+, we can take advantage of default args to avoid using arguments object:

```
var secret = { };
function f(a,b=secret,c=secret)
{
    if (c===secret && b ===secret) return function(b=secret,c=secret){ return f(a,b,c) }
   if (c === secret) return function(c) { return f(a,b,c) }
   ...
    
}
```

**Comment by CrossEye** [comment]
@ndaidong:  We certainly are keeping Ramda as plain JS.  As I understand it, this would be a possible tool for Babel users to compile to Ramda code.

**Comment by tolmasky** [comment]
Yeah I'm aware that syntax features have a polarizing effect of totally selling some, but completely turning others off, so absolutely meant to be an augmenting tool.

My main goal is to experiment with minor changes that could really make usage more fundamental. I've had a suspicion for a long time that as silly as it may seem, simply having syntax for a feature automatically makes it more appealing to users. A great example is how arrays are so overused in JavaScript simply because 1) they are baked into the language, and 2) they can be trivially constructed. Even when we have much better data structures, there's a weird feeling of "heaviness" that leads people to just grab for an array an inadvertently O(N) penalties with it, vs. making something that has a constructor and some form of disconnected serialization of data (such as how you create a Set *with* an array). On the other hand, the fact that objects are so easy to construct in JavaScript is arguably a good example of the effects syntax can create.

To some extent I find myself avoiding curryN until I absolutely need it just because of this friction, which is unfortunate because currying really is the gateway feature to everything else in ramda (in my opinion). But having to wrap it up, and thus lose hoisting, and start getting the gears turning on "I wonder what the perf penalty is here..." can be detrimental. For my team, the first time they encounter something like "f(a)(b)(c){}" I think it is easier to sell that as a superpower, as opposed to this weird dependency they now need to encumber every one of their functions with.

**Comment by jethrolarson** [comment]
sweet.js macros are another option. Theres a couple curry macros already https://github.com/sweet-js/sweet.js/wiki/Example-macros
