### ISSUE TITLE
Introduce odd & even function on Numbers

### ISSUE THREAD

**Issue by webdude21** [ramda/ramda#1945]
Hi folks,

First of all, awesome library.

Do you think it could fit the library to have odd and even functions that operate on Numbers?

Example (while its obvious):

R.odd(3) //=> true
R.odd(2) //=> false
R.even(4) //=> true
R.even(5) //=> false

I could do a pull request, if there's interest in this and if it would fit the style of the library.

**Comment by webdude21** [comment]
Added pull request here https://github.com/ramda/ramda/pull/1947

**Comment by CrossEye** [comment]
I don't find any need, personally.  These are so easy to create, and less commonly needed than some of the other easy-to-create ones such as `add`.  It's not that I have a major objection, but I don't see a strong reason.
