### ISSUE TITLE
Can I translate Ramda Documentation into Chinese?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#1951]
Hi, @CrossEye, there is still no Chinese Documentation of Ramda. In order for more people to learn and use ramda, can I translate ramda documentation into Chinese?
  If the work begins, how should I add the Chinese version?

Look forward to your reply!

**Comment by CrossEye** [comment]
First off, this is a group effort, and although I was one of the original founders (@buzzdecafe was the other), I'm just one voice among many here.  So it would be a group decision.

But I can't imagine that anyone would object.  I personally think it would be a great idea.

I don't have a very clear idea of how, though.  I'll think about it a bit.

There is a separate repository for the documentation, and discussions are usually [carried out there][rd].  Would you be willing to create an issue there to discuss this?


  [rd]: https://github.com/ramda/ramda.github.io/issues

**Comment by buzzdecafe** [comment]
"how" is a tricky question. at present we simply parse the inline jsdocs and render them as the website. it's not clear to me where in the process we could branch for other languages. But I agree it would be great to have.

**Comment by adispring** [comment]
I've just create [an issue](https://github.com/ramda/ramda.github.io/issues/147) in that repository.

**Comment by CrossEye** [comment]
You beat me to it by a minute!  I moved my comment to your issue and closed mine.

**Comment by adispring** [comment]
Your title is more general :)

**Comment by tycho01** [comment]
@adispring replied to you in that one, I had some existing translations you can use if you'd like.

**Comment by adispring** [comment]
ok, @tycho01 , I'll refer to your translation, thanks :)
