### ISSUE TITLE
Contribution Build Error

### ISSUE THREAD

**Issue by zatziky** [ramda/ramda#1953]
Hi there, 

I'd like to add a functionality to ramda. I followed the [contribution guide](https://github.com/ramda/ramda/blob/master/CONTRIBUTING.md) but on Windows I end up with this error:

```
> ramda@0.22.1 pretest C:\DEV\ramda
> npm install && npm run lint && npm run clean && npm run build


> ramda@0.22.1 lint C:\DEV\ramda
> eslint scripts/bookmarklet scripts/build src/*.js src/internal/*.js test/*.js test/**/*.js lib/sauce/*.js lib/bench/*.js


> ramda@0.22.1 clean C:\DEV\ramda
> rimraf dist/* coverage/*


> ramda@0.22.1 build C:\DEV\ramda
> make && make dist/ramda.min.js

File not found - *.js
git checkout -- 'dist/ramda.js'
scripts/header >ramda.js.tmp
'scripts' is not recognized as an internal or external command,
operable program or batch file.
make: *** [dist/ramda.js] Error 1

```

Can you help me?

**Comment by davidchambers** [comment]
The build tool may not be compatible with Windows. There are (at least) two possible solutions:

  - you could install [Cygwin][1]; or
  - we could rewrite the Unix-specific portions of the build tool in Node.

I'm sorry that your contribution has been delayed!


[1]: https://en.wikipedia.org/wiki/Cygwin

**Comment by zatziky** [comment]
Number 2 is better. ;) But before it happens this way I will install Cygwin. Thx, Dave.

**Comment by davidchambers** [comment]
> But before it happens this way I will install Cygwin.

Okay. If you run into any problems don't hesitate to reopen this issue so we can investigate option 2.

**Comment by CrossEye** [comment]
Long-term, I'm in favor of Number 2, but it never seems to move very high on the priority list.

**Comment by zatziky** [comment]
`Git Bash` on Windows can be used too.

**Comment by CrossEye** [comment]
@zatziky: I haven't attempted to build with Git Bash lately, but last time I tried that on Windows, it did not have a useful `make` and didn't work.

**Comment by zatziky** [comment]
@CrossEye The truth is that I have `make` in my path variable...

**Comment by git-in-my-anus** [comment]
> Git Bash on Windows can be used too

No, it can't. `make` will still run commands in `cmd.exe` and not in `bash`

**Comment by zatziky** [comment]
@git-in-my-anus I have built and tested ramda using `git bash` on Windows. So it can be used. ;)

**Comment by CrossEye** [comment]
@zatziky:
>  I have built and tested ramda using `git bash` on Windows. So it can be used. ;)

Perhaps, but it cannot be used out of the box:

```shell
$ npm run build

> ramda@0.22.1 build c:\Projects\Temp\ramda
> make && make dist/ramda.min.js

'make' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
...
```
