### ISSUE TITLE
Link guide about type syntax more prominently

### ISSUE THREAD

**Issue by bergus** [ramda/ramda#1960]
Carrying over from [StackOverflow's "*Where can I find an explanation/summary of symbols used to explain functional programming, specifically Ramda.js?*"](http://stackoverflow.com/q/40361059/1048572).

The [wiki article](https://github.com/ramda/ramda/wiki/Type-Signatures) is good, but it should be linked more visibly. Somewhere on the docs page for sure, maybe somewhere else as well. Ideas?

**Comment by CrossEye** [comment]
Yes, we should.  There is a lot of work going on over in the [documentation repo][dr].  We can take this up there.


  [dr]: https://github.com/ramda/ramda.github.io

**Comment by CrossEye** [comment]
Closing in favor of https://github.com/ramda/ramda.github.io/issues/155
