### ISSUE TITLE
Online Ramda Repl failing to load

### ISSUE THREAD

**Issue by bijoythomas** [ramda/ramda#1963]
<img width="1435" alt="screen shot 2016-11-03 at 3 11 43 pm" src="https://cloud.githubusercontent.com/assets/5385730/19983296/7a84bddc-a1d7-11e6-85de-fa51eb0e6476.png">

I see these error messages in the Chrome console
bundle.js:39 GET https://wzrd.in/standalone/sanctuary@latest net::ERR_INSECURE_RESPONSE
bundle.js:39 GET https://wzrd.in/standalone/ramda-fantasy@latest net::ERR_INSECURE_RESPONSE

**Comment by davidchambers** [comment]
Thanks for letting us know. Let's track this in ramda/ramda.github.io#156.
