### ISSUE TITLE
Help needed: calling a function that is a property of an object

### ISSUE THREAD

**Issue by yosbelms** [ramda/ramda#1964]
What I need is to call a function contained in an object, I found this way:
```js
var obj = {
    getName: () => 'foo'
}
var name = R.compose(R.call, R.prop('getName'))

name(obj)
```

There is any other more succinct way?

**Comment by Bradcomp** [comment]
Check out [`R.invoker`](http://ramdajs.com/docs/#invoker).  It does just what you want it to do here.

```
var name = R.invoker(0, 'getName');
name(obj);
```

**Comment by yosbelms** [comment]
Thanks @Bradcomp
