### ISSUE TITLE
Any interest in adding a toPath function (a la lodash)?

### ISSUE THREAD

**Issue by EvanBurchard** [ramda/ramda#1965]
It takes a string, and makes an array from it. Open to alternative names. From the [lodash docs](https://lodash.com/docs/4.16.6#toPath), this is how it works:

```
String → [String]

_.toPath('a.b.c');
// => ['a', 'b', 'c']
 
_.toPath('a[0].b.c');
// => ['a', '0', 'b', 'c']
``` 

Just wanted to check for interest before working on/submitting a PR.

**Comment by buzzdecafe** [comment]
:-1: for me. taking an array of steps in the path minimizes ambiguities.

**Comment by EvanBurchard** [comment]
@buzzdecafe I'm suggesting a separate function. It could have "string" in the name like ```R.stringToPath``` or something.

**Comment by buzzdecafe** [comment]
yes, i understand. to my mind such a function is not "simple"; e.g. how does it handle keys with dots or square brackets in them? How does it distinguish the key `"a.b"` from the path `a.b`? etc.

I am just one POV on this, others may disagree.

**Comment by EvanBurchard** [comment]
Yeah. I'm with you that it's not "simple." 

To your earlier point, I get params and they are in that stringified form. If I had the array initially I wouldn't need this function. My options now are roll one myself, use lodash, or change the interface.

**Comment by davidchambers** [comment]
I'm with @buzzdecafe on this one. `Array String` represents a path better than `String` does.

If you do implement this function yourself you should add it to the [cookbook][1]. :stew:


[1]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by EvanBurchard** [comment]
Yeah. I agree that represents a path better. The problem is that I'm starting out with strings that are in that format from web request parameters I'm getting. If I started with the array, I'd be all set, and could build a path from it. Do others not commonly see request parameters come in that are in that form? 

Part of the context here is that I was trying to convince a coworker that we could use ramda as a better lodash, and this was his primary hangup for why that's not the case. We could just define the function separately (probably just taking lodash's  implementation), but thought it might be useful if others see parameters come in like that (assumed that was the case because lodash has it).

**Comment by CrossEye** [comment]
I wouldn't mind seeing this in the cookbook.  It seems pretty simple:

```js
const toPath = R.split(/[^\w\d]+/g);
```

**Comment by StefanoDeVuono** [comment]
@CrossEye, thank you! That looks great but it'll leave an empty string at the end of the array. Maybe this?

`const toPath = R.compose(R.filter(n =>!!n), R.split(/[^\w\d]+/));`

**Comment by davidchambers** [comment]
`R.reject(R.isEmpty)` seems clearer to me than `R.filter(Boolean)`. :)

**Comment by CrossEye** [comment]
Sure, any version of this that works.  (Is the empty string you're worried about when someone ends the path with a `'.'`?  If so, that sounds almost like a feature to me.  :smile:)

**Comment by EvanBurchard** [comment]
@CrossEye are you saying I should submit a PR? I'm cool with closing the issue it if we're just talking about what to put in the cookbook.

**Comment by CrossEye** [comment]
I think most of us have expressed a preference for the Cookbook.  If you still feel strongly in favor of this, by all means submit a PR.  But it might be difficult to sell...

**Comment by EvanBurchard** [comment]
Thanks for the discussion. Closing now.
