### ISSUE TITLE
R.assoc with int key sets a property, R.dissoc with int key does not remove it

### ISSUE THREAD

**Issue by beaucollins** [ramda/ramda#1966]
This was unexpected behavior for me. 

```js
R.pipe(
  R.assoc( 1, 'a' ),
  R.dissoc( 1 )
)( {} )
// => { "1", "a" }
```
https://goo.gl/1j55Af

Perhaps a note in the documentation. I'm not sure if `R.dissoc` with an int key _should_ remove the property from the object.

**Comment by beaucollins** [comment]
Actually the [documentation's type signature](http://ramdajs.com/docs/#dissoc) shows that it expects a `String` value for the key.

```
String → {k: v} → {k: v}
```

**Comment by CrossEye** [comment]
I think there's a good question here about whether we should restrict `assoc` to Strings.   Or whether we should coerce the first parameter to a string in both functions.

I think this would be a good invariant to support:

```js
// for all obj, name
R.equals(obj, R.pipe(
  R.assoc( name, 'a' ),
  R.dissoc( name )
)(obj); //=> true
```

**Comment by beaucollins** [comment]
Since `R.assoc` _does_ do coercion (well, JS does the coercion) for the sake of symmetry I would think that `R.dissoc` would too.

**Comment by TheLudd** [comment]
I see no need to complicate this one. Use it as documented. If you use it in other ways, the result is unspecified. Following this principle keeps functions simple. Trying to "simplify" things by covering up all holes that can be found is the road to hell IMO.

**Comment by beaucollins** [comment]
> I see no need to complicate this one. Use it as documented. If you use it in other ways, the result is unspecified.

@TheLudd that's why I quickly closed the issue. Saw the type signature and realized I need to make sure I provide a `String`.

**Comment by kulakowka** [comment]
In accordance with the specification ECMA Script, [objects keys can be strings or symbols](http://www.ecma-international.org/ecma-262/6.0/#sec-topropertykey). I think it's worth considering. Of course right now it is dangerous to change the behavior of dissoc function. But it would be right.
