### ISSUE TITLE
find if value in [object]

### ISSUE THREAD

**Issue by craigcosmo** [ramda/ramda#1969]
let array = [{car: 'sedan', brand: 'ford'}, {car:'suv', brand: 'GM'}]

How to know if in array there is a key with value equal to `suv`?

**Comment by mjgpy3** [comment]
Something like

```
const isThereAnSuv = R.any(R.propEq('car', 'suv'));
```

should do it

**Comment by CrossEye** [comment]
I'm also quite fond of `where`.  You can build a very readable predicate:

```js
where({car: equals('suv')})
```

which can then be passed to `filter`, to `find`, or to `any`.

**Comment by TheLudd** [comment]
Why not add this to the mix?
```
whereEq({car: 'suv'})
```
