### ISSUE TITLE
docs on `path/prop`: also allow number (esp. for navigating arrays)?

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#1973]
Currently, Ramda's `path` / `prop` and similar methods are described in their docs as using string paths/props, while in its implementation -- and imho reasonably so esp. when dealing with Arrays -- also allows numbers:

```
R.path([0, 'a'], [{ a: 1 }])
// 1
R.path(['0', 'a'], [{ a: 1 }])
// 1
R.prop(0, ['a'])
// "a"
R.prop(0, { '0': 'a' })
// "a"
```

Would it be reasonable to adjust the docs to reflect the fact it properly deals with numbers as well?

(Cross-posted from [here](https://github.com/donnut/typescript-ramda/issues/94).)

**Comment by CrossEye** [comment]
See #1926.  This will be included in the next release.
