### ISSUE TITLE
Distribute a build compatible with the bind operator (::) proposal

### ISSUE THREAD

**Issue by gajus** [ramda/ramda#1974]
I wonder if it is possible to transpile the existing Ramda code base to enable its use with the proposed bind operator (`::`).

The proposal:

https://github.com/tc39/proposal-bind-operator

**Comment by git-in-my-anus** [comment]
Why do you need to bind functions from Ramda at all?

**Comment by gajus** [comment]
Thats the point – I cannot at the moment.

**Comment by CrossEye** [comment]
This strikes me as antithetical to the general goals of Ramda, which is mostly to enable stateless processing through functional composition.

There is a library designed on such ideas, though, if you're interested: [Trine][tr].  I haven't been following, so I don't know their current status.


  [tr]: https://github.com/jussi-kalliokoski/trine

**Comment by gajus** [comment]
> which is mostly to enable stateless processing through functional composition.

This proposal does not break either of those values.

**Comment by CrossEye** [comment]
Could you describe what it is you're suggesting in greater detail then?  My understanding of the bind operator is fairly tenuous.  But I thought it would involve something like:

```js
const result = fetchData(...params)
  ::map(someTransform)
  ::filter(somePredicate)
  ::reduce(someCombiner)
```

which is fairly different from Ramda's ideas of 

```js
const myFunc = pipe(map(someTransform), filter(somePredicate), reduce(someCombiner));
//...later
const result = myFunc(fetchData(params));

Do you mean something like this or something different?

**Comment by gajus** [comment]
The first example is missing one layer of abstraction, but otherwise it is correct, i.e. this would be an equivalent using the `this-bind` operator:

```js
import {
  map,
  filter,
  reduce
} from 'ramda';

const myFunc = (...params) => {
  return fetchData(...params)
    ::map(someTransform)
    ::filter(somePredicate)
    ::reduce(someCombiner);
};

const result = myFunc(params);
```

**Comment by gajus** [comment]
I have written an alternative transpiler for `::` that enables function composition.

https://github.com/gajus/babel-plugin-transform-function-composition

I am closing this issue as the latter solves my problem. Please re-open if you'd like to champion this issue.

**Comment by CrossEye** [comment]
OK, then, I don't see any reason.  Can you explain why you think this is a good idea?

What are the benefits?  Ramda has been built to enable this style of coding:

```js
const myFunc = pipe(
  fetchData,
  map(someTransform),
  filter(somePredicate),
  reduce(someCombiner)
);
```

What advantage is there to adding an entirely new style?

**Comment by CrossEye** [comment]
oops, bad timing.  I'll take a look at your code this evening.
