### ISSUE TITLE
how to turn object to array

### ISSUE THREAD

**Issue by craigcosmo** [ramda/ramda#1978]
```js
{ {car:'mama'}, {plane:'baba'} } to [ {car:'mama'}, {plane:'baba'} ]
```

**Comment by kedashoe** [comment]
Hello @craigcosmo ! Your object doesn't have any keys so I'm not sure exactly what you're looking for, but maybe http://ramdajs.com/docs/#toPairs or http://ramdajs.com/docs/#values could help?

**Comment by dmitriz** [comment]
`{ {car:'mama'}, {plane:'baba'} }` is not legal in JS:

```
{ {car:'mama'}, {plane:'baba'} }
VM4093:1 Uncaught SyntaxError: Unexpected token ,
```

**Comment by CrossEye** [comment]
@craigcosmo: Any more feedback on this, or can we close it?

**Comment by craigcosmo** [comment]
sorry, too much programming, I don't what i'm doing any more :)

**Comment by nmrshll** [comment]
I supposed he meant `{ car:'mama', plane:'baba' } to [ {car:'mama'}, {plane:'baba'} ]`
which is an interesting question

**Comment by foxbunny** [comment]
@craigcosmo I think this should do it for you.

```
const o = { car: 'mama', plane: 'baba' }

const toIndividualKeys = R.pipe(
  R.toPairs,
  R.map(R.pipe(R.of, R.fromPairs))
)

toIndividualKeys(o)
// => [{"car": "mama"}, {"plane": "baba"}]
```

[Here](https://ramdajs.com/repl/?v=0.25.0#?const%20o%20%3D%20%7B%20car%3A%20%27mama%27%2C%20plane%3A%20%27baba%27%20%7D%0A%0Aconst%20toIndividualKeys%20%3D%20R.pipe%28%0A%20%20R.toPairs%2C%0A%20%20R.map%28R.pipe%28R.of%2C%20R.fromPairs%29%29%0A%29%0A%0AtoIndividualKeys%28o%29) it is in the online REPL.

**Comment by CrossEye** [comment]
Or, perhaps slightly more intuitively,

```js
const toIndividualKeys = R.pipe(
  R.toPairs,
  R.map(R.apply(R.objOf))
)
```

**Comment by nmrshll** [comment]
Good one ! it does make it easier to follow what's happening with this version
