### ISSUE TITLE
Is it safe to require `src/{function}`?

### ISSUE THREAD

**Issue by yosbelms** [ramda/ramda#1980]
Actually we can require each function from `src` directory, example:

```js
var map = require('ramda/src/map')
```

This way to use Ramda gives a lots of benefits when using bundlers (Browserify for example) to build projects for the browsers. Another way to reduce the final bundle size is using a custom build documented in http://ramdajs.com

However, require from `ramda/src` is not documented in official docs, what makes me think this way could be unsafe because directories structure may change in the future.

Finally, I would like to know how prudent is to use this aproach.

Edit1: fix typos

**Comment by CrossEye** [comment]
This works fine, and is supported... for the moment.  We are planning relatively soon on moving those to the root, so that you can instead simply do

```js
var map = require('ramda/map');
```

We'll probably keep both styles active for a version while we deprecate the first, though.

**Comment by ashah023** [comment]
Is that equivalent to the following?

`var { map } = require('ramda')`

**Comment by rickmed** [comment]
@ashah023 No. The latter is requiring the exported object with all the functions and using destructing to extract the map function. The former only imports the stand alone function.

**Comment by iamstarkov** [comment]
@ashah @rickmed it's the same if you use bundler with tree shaking like webpack 2

**Comment by rickmed** [comment]
@iamstarkov no. Tree shaking does not work with ramda because of currying.

**Comment by iamstarkov** [comment]
can you elaborate? tree shaking is about unused `require/import` statements and it has nothing to do with currying

**Comment by rickmed** [comment]
https://github.com/ramda/ramda/issues/1968
