### ISSUE TITLE
Reduce ignores custom curried functions

### ISSUE THREAD

**Issue by dmitriz** [ramda/ramda#1981]
It seems I cannot put a custom curried function directly into `reduce`:
```
var plus = a => b => a + b
R.reduce(plus, 10)([4, 2, 3])
// => function (b) {return a + b;}
```

For instance, this excellent Guide 
https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch7.html#tales-from-the-cryptic
declares the signature:
```
//  reduce :: (b -> a -> b) -> b -> [a] -> b
var reduce = curry(function(f, x, xs) {
  return xs.reduce(f, x);
});
```

But is not supported in this form as it seems.
To make it work I need to do something like
```
var uncurry2 = R.uncurryN(2)
R.reduce(uncurry2(plus), 10)([1, 2, 3]) 
//=> 16
```
which is not ideal.

Is this a bug?

**Comment by ascartabelli** [comment]
Seems to me that you are misled by Ramda's currying, which I call "auto-currying".
`reduce` waits for a binary function, the first argument being the accumulated value and the second one the element currently evaluated.
Your `plus` function is curried in a "standard" way, meaning that each call returns a unary function until the final arity is consumed.
Ramda's currying on the other way lets you to call a function with any amount of arguments at any time and will also apply the function when the arity is consumed.

Ramda's [add](http://ramdajs.com/docs/#add) should do fine in your example.

**Comment by ascartabelli** [comment]
P.S. Also note that with Ramda's currying "empty calls", as in functions called without arguments, don't consume the arity.

**Comment by davidchambers** [comment]
Sanctuary provides a function, [`S.reduce`][1], with the type you require:

```purescript
reduce :: Foldable f => (a -> b -> a) -> a -> f b -> a
```

Sanctuary also provides [`S.reduce_`][2] which has the same type as `R.reduce`:

```purescript
reduce_ :: Foldable f => ((a, b) -> a) -> a -> f b -> a
```


[1]: https://sanctuary.js.org/#reduce
[2]: https://sanctuary.js.org/#reduce_

**Comment by CrossEye** [comment]
Note that [Ramda's own signature][rr] describe this correctly as `((a, b) → a) → a → [b] → a`.  We can't easily cater to both styles without currying (recurrying?) the supplied function on every call.  That seems like a lot of overhead.  So Ramda has stuck with the convention more familiar to JS programmers.  [`S.reduce`][sr] looks like a good alternative if you need it.


  [rr]: http://ramdajs.com/docs/#reduce
  [sr]: https://sanctuary.js.org/#reduce

**Comment by dmitriz** [comment]
@davidchambers 
Thanks for the ref to Sanctuary, will have a look!
