### ISSUE TITLE
uncurryN seems to break with data-last currying 

### ISSUE THREAD

**Issue by guy-kdm** [ramda/ramda#1982]
I would guess these [two functions](https://goo.gl/Y3rntE) should be equivalent:
```javascript
const explicit = fn => uncurryN(2, a => b => fn(a)(b))
const dataLast = fn => uncurryN(2, fn)

const fn1 = compose(multiply, inc)
explicit(fn1)(2, 4) //12
dataLast(fn1)(2, 4) //12 as expected...

const fn2 = compose(map, divide)
explicit(fn2)(12, [6,4,3]) // [2, 3, 4]
dataLast(fn2)(12, [6,4,3]) // function n(r){return 0===arguments.length||w(r)?n:t.apply(this,arguments)}
```
But they are not. Should this be changed for consistency?

**Comment by CrossEye** [comment]
There's certainly nothing in the docs to suggest that `uncurry` would work in this circumstance.  It specifically calls out manually curried functions.

I haven't quite figured out whether I think it would be important to extend this to other functions.  This example makes me think yes, but I'd like to consider it a bit.

In the meantime, `useWith(map, [divide, identity])` would also do what you're trying to do.  That's precisely what [`useWith`][uw] was created for.

  [uw]: http://ramdajs.com/docs/#useWith

**Comment by guy-kdm** [comment]
Right, but the reason I tried hacking around is that there's a common scenario where data comes with metadata and I want frameFn(coreFn(metadata))(data). I think useWith won't do then since frameFn has arity of one (then maybe this sort of uncurry would be useful).
