### ISSUE TITLE
No official list of supported browser.

### ISSUE THREAD

**Issue by przemoli** [ramda/ramda#1983]
Hello. 

Couldn't find list of browsers that are supported by ramda.

Is IE8 supported?

Best regards

**Comment by CrossEye** [comment]
I don't know that we really know for sure.  We used to have some browser tests running automatically, but that's been gone a while.

But as far as I know, we should support even very old browsers with nearly all functions.  (We might depend on `Array.prototype.indexOf` for one or two, which would exclude some older IEs for those functions.)

**Comment by przemoli** [comment]
Array.prototype.indexOf is only IE9+.

What I would at least like to hear is that if there is bug in IE8, it will be treated as one to be fixed. But it looks like its IE9+
