### ISSUE TITLE
proposal: restrict domain of R.inc

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1985]
```javascript
> R.map(R.inc, [undefined, null, false, true, [], [[]], [[[null]]]])
[NaN, 1, 1, 2, 1, 1, 1]
```

Perhaps the function's domain should be restricted to `Number`. `Any` is a bit too broad. :stuck_out_tongue_winking_eye:

**Comment by CrossEye** [comment]
Restricted how?  Throwing exceptions?  Mapping non-numbers to NaN?

**Comment by davidchambers** [comment]
> Restricted how?

Right now the function's type is `Any -> Any`. We could restrict the codomain, or restrict both the domain and the codomain.

> Mapping non-numbers to NaN?

This would restrict the codomain, giving `Any -> Number`. I consider this an improvement.

> Throwing exceptions?

This would restrict the domain and by extension the codomain, giving `Number -> Number` (or even a more restrictive type such as `ValidNumber -> ValidNumber` or `FiniteNumber -> FiniteNumber`). This is my preferred option.

My position can be summarized as follows:

  - :persevere: `R.inc([])` = `1`
  - :confused: `R.inc([])` = `NaN`
  - :wrench: `R.inc([])` = :boom:

If I write a nonsensical program or fail to sanitize user input appropriately, I want my program to crash so I can fix it quickly. I'm sure I've said something to this effect before. :)

**Comment by CrossEye** [comment]
Yes, we've had this discussion at least as recently as #1764.
