### ISSUE TITLE
swap order of arguments to R.difference?

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#1996]
Feels like the 1st argument is the one that is being modified. I can't say I've used difference super often, but needed it just now and had to flip it in the middle of my composition.

**Comment by CrossEye** [comment]
I think this is the same issue we've discussed many times, including #1497, about non-commutative binary operators.  There simply doesn't seem to be a perfect solution, but the one we came to in there seems likely to be as good as we'll get.  That should go on our to-do list.

**Comment by kedashoe** [comment]
Ah, remember the thread but didn't realize `difference` was explicitly discussed.
