### ISSUE TITLE
Propose overPath to apply a function to a nested property.

### ISSUE THREAD

**Issue by MrRacoon** [ramda/ramda#1998]
Ramda has both `path` and `assocPath` for using the `[key]` strategy to get/set data respectively.

Curious if you guys would find `overPath` handy, where the signature could look something like:

```haskell
overPath :: [String] -> (a -> b) -> {k:v} -> {k:v}
```

and the implementation would be analogous to:

```javascript
const overPath = (pl, fn, obj) => {
    const was = path(pl, obj);
    return assocPath(pl, fn(was), obj);
}
```

The motivation being that, where lenses have `view`, `set`, and `over`. Path could be a lighter abstraction with `path`, `assocPath`, and `overPath` respectively.

If that sounds like something you guys dig, I wouldn't mind making a PR for it sometime this week.

**Comment by CrossEye** [comment]
While not adamantly opposed, I'm more inclined in the opposite direction.  @davidchambers has made the case for removing some of the functions that overlap with lenses in favor of promoting a consistent lens-based interface.  While I might not be so happy with losing ones like `prop` or `path`, ISTM that `assoc` and its cronies could well go.

Part of the point is that while there is a slight advantage to the conceptual weight of `overPath`, the usage is not *much* simpler:

```js
overPath(['a', 'b', 'c'], myFunc, myObj);
```
is only slightly simpler than
```js
over(lensPath(['a', 'b', 'c']), myFunc, myObj);
```

And the latter comes along with all sorts of useful abstractions not available to the former.

**Comment by MrRacoon** [comment]
I happen to totally agree with stripping out the redundancy. 

I would add though, IME "spreading the rhetoric" about how cool FP and Ramda are, I've noticed that the lens abstraction tends to shake new players. I find I've had to work up to it in most cases, especially in listeners who don't yet have that "FP itch".

Kind of what I planned to do with this change was to bait and switch listeners. Show them the various path functions and then put a lens in front of them at the last minute in an attempt to make the introduction less ground shattering.

---

Though, seeing how similar your example functions are, I'm starting to wonder if there would be benefit in merging the two styles?

```javascript
over(['a', 'b', 'c'], myFunc, myObj);
// could be equivalent to 
over(lensPath(['a', 'b', 'c']), myFunc, myObj);
```

If you're familiar with [partial.lenses](https://www.npmjs.com/package/partial.lenses), this is a similar approach they take. Using a `String` as a valid `lensProp`. Which is nice, I enjoy how minimal their lens compositions are.

I've got a PR ready to go if you guys see `overPath` as being useful. Or If you dig `over`, `view`, and `set` taking arrays as an implicit `lensPath`, I'd be willing to make an attempt. :)

**Comment by davidchambers** [comment]
> Using a `String` as a valid `lensProp`.

Good luck expressing this in a type signature. ;)

**Comment by MrRacoon** [comment]
No kidding. Not one to pass up a challenge though!

```haskell
classtype LensLike a where
    view :: a -> s -> s
    set  :: a -> a -> s -> s
    over :: a -> (v -> v) -> s -> s

instance LensLike (Lens a s) where
    view = R.view
    set  = R.set
    over = R.over

type Path = [String]

instance LensLike Path where
    view = R.path
    set  = R.assocPath
    over = R.overPath  -- Error: overPath is not found :P
```

Yeah, I'm pretty sure that's all bogus, best I can do.

**Comment by CrossEye** [comment]
> Though, seeing how similar your example functions are, I'm starting to wonder if there would be benefit in merging the two styles?

> ```js
> over(['a', 'b', 'c'], myFunc, myObj);
> // could be equivalent to 
> over(lensPath(['a', 'b', 'c']), myFunc, myObj);
> ```

This is something we're quite loathe to do in Ramda... unless we find a common abstraction shared by the different types we'd accept.  Your suggestion of `LensLike` doesn't seem to fit the bill, as our lenses are not defined by the relationship to `over`, `view`, and `set`; it's more generic than that.

**Comment by MrRacoon** [comment]
Oh Sure, it was a stretch and types are fun. :D

Anyway, `overPath`. Yay, nay? Got it if you want it. Used this library a lot. Always though it would be useful. Team don't want lenses (no matter how awesome they are). Make it easier to switch out all the `over`s I peppered everywhere.

That's all I got. Go ahead and close this sucker if Nay.

**Comment by CrossEye** [comment]
> That's all I got. Go ahead and close this sucker if Nay.

I'd like to hear a few more voices before making a call on this.  Again, I don't have a major objection, just an aversion to bloat, especially when there are simple enough techniques to accomplish the same goals with what's already there... and where it doesn't add a great deal in the way of readability.

Anyone else?  @scott-christopher? @raine?  @asaf-romano?

**Comment by kedashoe** [comment]
:+1:, this is very common IMHO, I always add it to my ramda wrapper.

How about `assocWith` and `assocPathWith`?

**Comment by MrRacoon** [comment]
Sounds good, Looking at types for similar functions, the closest I've seen is: `pathSatisfies`, which both uses `path` and takes a function. I assume we'd want the same layout?

`assocWith :: Function → String → Object → Object`
`assocPathWith :: Function → Path → Object → Object`

**Comment by MrRacoon** [comment]
I totally just opened a PR with the arguments in reverse from what I just suggested... Don't know why I did that. (yeah i do, because I just copy-pasted from `assoc`/`assocPath`)

Which would be preferred?

`assocWith :: Function → String → Object → Object`
`assocWith :: String → Function → Object → Object`

**Comment by CrossEye** [comment]
All of our `*With` functions take the function first.  So that definitely seems preferable.

**Comment by MrRacoon** [comment]
PR should be ready to go, I've aligned the functions to the `*With` format
