### ISSUE TITLE
addIndex(partition) gives incorrect results

### ISSUE THREAD

**Issue by jonahx** [ramda/ramda#2000]
Simple example to reproduce:

```
addIndex(partition)((_,i) => return (i%2) == 0, ['a', 'b', 'c', 'd', 'e'])
```

actual output: `[["a", "c", "e"], ["a", "c", "e"]]`
expected output: `[["a", "c", "e"], ["b", "d"]]`

[Ramda playground link](http://ramdajs.com/repl/#?addIndex%28partition%29%28%28_%2Ci%29%20%3D%3E%20i%252%20%3D%3D%200%2C%20%5B%27a%27%2C%20%27b%27%2C%20%27c%27%2C%20%27d%27%2C%20%27e%27%5D%29)

**Comment by CrossEye** [comment]
It looks as though #1651 is the culprit.

`partition` has become generic enough that `addIndex` can no longer make sense.  Is this something we want to live with?  @asaf-romano? @buzzdecafe? @davidchambers?

**Comment by jonahx** [comment]
If you do decide against supporting `addIndex(partition)`, it should be clear in the docs.  But my 2cents is that something isn't right if we're special casing exceptions like this.  At the least it's a violation of the principle of least surprise.

Depending on what's decided, I'd be willing to do some work on fixing it.

**Comment by CrossEye** [comment]
@jonahx:

The problem is that this is no longer a List function.  It works on a generic filterable type, that is, anything which matches

``` js
class Filterable f where
  filter :: (a -> Boolean) -> f a -> f a
```

One of the examples from the [`partition` docs][pd] is

```js
R.partition(R.contains('s'), { a: 'sss', b: 'ttt', foo: 'bars' });
// => [ { a: 'sss', foo: 'bars' }, { b: 'ttt' }  ]
```

But for something like this `addIndex` make no real sense.  Even if an order can be established, there is no natural order, so a numeric index makes little sense.  The most likely parallel would be to pass value and key.  But keys like 'a' and 'b' would not do you much good for the `modulus` operator.

The discussions in #1651 involved special-casing for lists and objects and only resorting to the current generic version for other types.  We rejected that for its complexity.  If we did so, we might manage to get your case working, but it would be at a significant increase in conceptual weight to the function, and it would not really be generic.

That's why I'm hoping from feedback from those involved in #1651.

  [pd]: http://ramdajs.com/docs/#partition

**Comment by jonahx** [comment]
@CrossEye,

Yeah, I should have been more specific: I understand in one way partition is now more general, but my point was that maybe it shouldn't be?  That is, you have these meta-rules informing the design like "`addIndex` should work for functions in which the iteration callback function is the first parameter, and where the list is the last parameter."  

Then in the present case, it appears the meta-rule "make functions as generic as possible" has led to a conflict with the `addIndex` rule.  Which principle should win?  It's really not clear to me.

As a programmer, what I want is for the library to be smart enough that something like `addIndex(partition)` will just work if I give it an array.  But by the same principle I want `partition` to "just work" with objects, per #1651.

I understand this may be too cumbersome to support without a proper type system, but I think what is being traded for what should be something the designers explicitly choose.

**Comment by davidchambers** [comment]
If it were up to me `addIndex` would not exist. If one really does need array indexes, one can use `Array#map`, `Array#filter`, or `Array#reduce` as appropriate. No need for assistance from Ramda. For example:

```javascript
['a', 'b', 'c', 'd', 'e'].reduce((partitions, elem, idx) => {
  partitions[idx % 2 === 0 ? 0 : 1].push(elem);
  return partitions;
}, [[], []]);
// => [['a', 'c', 'e'], ['b', 'd']]
```

**Comment by jonahx** [comment]
@davidchambers i'd be curious to hear your thoughts about why.

i find the example above significantly less readable than:

```
addIndex(partition)((_,i) => return (i%2) == 0, ['a', 'b', 'c', 'd', 'e'])
```

**Comment by davidchambers** [comment]
> @davidchambers i'd be curious to hear your thoughts about why.

Accessing array elements by index is place-oriented programming. I prefer to reason about *transformations* such as maps and folds. Here's an approach which produces the same result without referencing array indexes explicitly:

```javascript
const pairs = R.splitEvery(2, ['a', 'b', 'c', 'd', 'e']);
[R.unnest(R.map(R.take(1), pairs)),
 R.unnest(R.map(R.drop(1), pairs))];
// => [['a', 'c', 'e'], ['b', 'd']]
```

**Comment by jonahx** [comment]
@davidchambers ah, ok.  In this particular case the complexity seems higher, but I could see how that wouldn't be true with another pass at it, or with the introduction of better combinators, etc.  I think I agree philosophically.  Appreciate your thoughts.

**Comment by CrossEye** [comment]
@jonahx:

> Then in the present case, it appears the meta-rule "make functions as generic as possible" has led to a conflict with the `addIndex` rule.  Which principle should win?  It's really not clear to me.

I'm saying that since the second parameter is now a generic filterable and not a list, we've already made the call that `addIndex` does not make sense.  Now that is actually happenstance.  We certainly didn't think about how this would work with `addIndex` and decide that it should no longer work.  But as the function has grown away from a list function, it's likely something that will bother us little.

I'm not with David on a strong opposition to `addIndex`.  Ramda is meant to be a more gentle introduction to FP for JS users or a more happy introduction to JS for FP regulars.  The latter group will probably never need this.  But many of the former are quite used to having such indices, and making it available, but still somehow second class, seems to strike the right balance.  Ideally, seeing it buried this way should help newcomers understand that using such indices has some serious problems.  But at least they still can.

BTW, we do have reasonable equivalents to your functions already built in:

```js
const ans = pipe(
  splitEvery(2),
  converge(pair, [chain(take(1)), chain(drop(1))])
)(['a', 'b', 'c', 'd', 'e'])
```

But there is no question that this does not capture the same concept as 

```js
addIndex(partition)((_, i) => i % 2 == 0, ['a', 'b', 'c', 'd', 'e]);
```

in any straightforward way except that it happens to get the same answer.

**Comment by jonahx** [comment]
@CrossEye 

Thanks for the answer.  It seems the right play here is just to update the docs and warn users that `addIndex` can't be used.

I forgot about `pair` and hadn't realized that `converge` can be used any arity branching functions.  Also realized we can do:

```
pipe(
  splitEvery(2),
  converge(pair, [chain(head), chain(tail)])
)(['a', 'b', 'c', 'd', 'e'])
```

**Comment by CrossEye** [comment]
> If one really does need array indexes, one can use `Array#map`, `Array#filter`, or `Array#reduce` as appropriate.

So by the same token, should we also get rid of `R.reduce`?  How about `R.filter` (perhaps only if we remove dispatching.)

I could certainly get along without `addIndex`.  In those very rare cases I really need the equivalent, I could recreate it if necessary.  But for those coming from vanilla JS or something like jQuery or lodash, folks used to this parameter, keeping it available seems generally helpful.  Keeping it slightly buried seems pedagogically sound.

This is not for lists (meaning `head: tail` constructs), although it's arguably reasonable for them.  It's for Arrays/Vectors: types which are explicitly mappings of initial subsets of the natural numbers to some items.  For such types the index is intrinsically meaningful.  Even if you could accomplish something without it, there's no reason you *should*.

**Comment by CrossEye** [comment]
@jonahx:

One more variant:

```js
const ans = pipe(
  splitEvery(2),
  lift(pair)(chain(head), chain(tail))
)(['a', 'b', 'c', 'd', 'e'])
```

`lift` is a much more widely recognized function.  It's not quite as versatile for these sorts of cases, but when it does work (when the arguments to `lift(fn)` are unary), this is much nicer than `converge`.

I'm trying to figure out if it's important even to add such a caveat to the documentation.  It definitely doesn't feel like it fits with `partition`.  But perhaps something on `addIndex`:

    Note that this only works for functions that operate strictly on arrays/vectors.  For 
    instance, `addIndex(partition)` will *not* work.

**Comment by jonahx** [comment]
@CrossEye 

Thanks for the note about lift -- that is nice.

> Even if you could accomplish something without it, there's no reason you should.

I don't want to speak for @davidchambers, but the comment resonated with me as saying, "A non-indexed solution will generally be conceptually simpler to reason about."  There is usually a nice geometric picture that goes along with it, as there is in this case.  I don't want to stake the absolute claim that there always exists a better non-indexed version of any indexed solution, but I suspect as a guiding heuristic it's probably helpful -- in the sense of forcing you to find simpler solutions.

**Comment by davidchambers** [comment]
> > If one really does need array indexes, one can use `Array#map`, `Array#filter`, or `Array#reduce` as appropriate.
>
> So by the same token, should we also get rid of `R.reduce`?  How about `R.filter` (perhaps only if we remove dispatching.)

Perhaps I didn't explain my thought clearly. The point I was trying to make is that generalized functions such as `reduce` and `filter` cannot possibly provide array indexes:

```purescript
reduce :: Foldable f => ((b, a) -> b) -> b -> f a -> b
filter :: (Applicative f, Foldable f, Monoid (f a)) => (a -> Boolean) -> f a -> f a
filterM :: (Monad m, Monoid (m a)) => (a -> Boolean) -> m a -> m a
```

If one really needs array indexes, one needs an array-specific function rather than a generalized function. Is it Ramda's job to provide such a function? I don't think so, because such functions are provided by the language (in the form of methods).

These methods are not as ergonomic as Ramda functions: they don't support partial application in such a convenient manner and in some cases need to be wrapped in anonymous functions to avoid losing context. I can live with this, though, as Ramda needn't solve every problem.

**Comment by davidchambers** [comment]
There's a type error in your version, @jonahx:

```javascript
S.chain(R.head, [['a', 'b'], ['c', 'd'], ['e']]);
// ! TypeError: Type-variable constraint violation
//
//   chain :: Chain m => (a -> m b) -> m a -> m b
//                             ^^^     ^^^
//                              1       2
//
//   1)  "a" :: String
//
//   2)  [["a", "b"], ["c", "d"], ["e"]] :: Array (Array String)
//
//   Since there is no type of which all the above values are members, the type-variable constraint has been violated.
```

`R.head` is not of the required type, `Chain m => a -> m b`. You could use `map` + `head` instead. The erroneous version happens to work, of course, but it's unwise to rely on implementation details. ;)

**Comment by buzzdecafe** [comment]
it's worth noting that OCaml and F# both provide e.g. `mapi` on their List API.

**Comment by CrossEye** [comment]
> Perhaps I didn't explain my thought clearly. The point I was trying to make is that generalized functions such as reduce and filter cannot possibly provide array indexes.

I was noting that if we are going to remove dispatching, then these generalized functions may not matter, and we should worry once again only about lists.  For lists, indices are at least somewhat reasonable.

I would certainly be willing to consider removing `addIndex`, but I think it would take a lot of convincing, as it's one of those tools that helps ease JS people into FP.

> These methods are not as ergonomic as Ramda functions: they don't support partial application in such a convenient manner and in some cases need to be wrapped in anonymous functions to avoid losing context. I can live with this, though, as Ramda needn't solve every problem.

I think this a serious point of disagreement.  Solving these ergonomic issues was my initial goal with Ramda.  While the library has certainly grown beyond that, it's very hard to see such issues dismissed.

**Comment by CrossEye** [comment]
@jonahx:

> Also, regarding the docs, I'd suggest to add the warning in both places. It will definitely save some people over time. If that duplication doesn't sit right with you, I think that's really just the conceptual impurity not sitting right (ie, now we have a function with exceptions and caveats, rather than one that can just be used anywhere it makes sense)

It's not that it's duplication; the basic problem is that a signature like `Filterable f => (a -> Boolean) -> f a -> [f a, f a]` does not suggest that the function *might* be a target for `addIndex`.  So adding a caveat that it in fact is not would just be confusing.

On the other hand, it strikes me that we might want to revisit the discussion in #1651 that chose the simplest implementation for `partition`.  A version that optimized the list and object path and used this simpler implementation only for other cases might end up being better -- now that we see that the current one is causing some issues.

**Comment by jonahx** [comment]
> the basic problem is that a signature like Filterable f => (a -> Boolean) -> f a -> [f a, f a] does not suggest that the function might be a target for addIndex. 

Fair enough, but that's to the initiated.  I understand that signature, but honestly often I'll just look at an example to remind myself of basic usage, and start typing.   So here I see a list, lists have indexes, ok I can use `addIndex`.   That's the extent of it.

While _that_ may be my problem, and I should just be more careful, I think a lot of people work that way in practice, and _especially_ the newcomers you want to be friendly toward, to whom those signatures are often Greek.

So while I think you're point of view is technically correct (and maybe should just win out because of that anyway), I do believe that as _practical_ matter, adding the warnings would help some non-trivial number of people not run into bugs they otherwise would have.

**Comment by CrossEye** [comment]
Ok, before we worry too much about changing the documentation, I want to see if there is an appetite for changing the function so that this would work as you were originally expecting.   @asaf-romano? @buzzdecafe? @davidchambers?

**Comment by davidchambers** [comment]
I'm with @buzzdecafe on this. I'd prefer to add a separate array-specific partition function than make `partition` a parametrically polymorphic function with a special case for array arguments.

**Comment by CrossEye** [comment]
OK.  Then the question becomes twofold: do we want a separate function to partition lists?  And do we need to document this for `partition` as @jonahx suggests?  

My own answers are no and no.  I would like to add something to the documentation of `addIndex` to make it clear that it is somewhat more restricted than implied so far.

**Comment by CrossEye** [comment]
Out of curiosity, @buzzdecafe, are you expecting any issues with `addIndex(map)`?

Obviously it will only work with lists, but it seems to work there:

```js
addIndex(map)((a, i, li) => `a: ${a}, i: ${i}, li: [${li}]`, ['a', 'b', 'c'])
//=> ["a: a, i: 0, li: [a,b,c]", "a: b, i: 1, li: [a,b,c]", "a: c, i: 2, li: [a,b,c]"]
```

**Comment by Shou** [comment]
Sorry for bumping an old thread -- wouldn't `addIndex` being implemented in terms of `reject` and `filter` in Javascript have a performance impact due to traversing the list twice, i.e. no laziness/stream fusion?

**Comment by awelles** [comment]
This still exists and is not mentioned in docs.

**Comment by CrossEye** [comment]
@awelles: 

Do you want to create a PR to fix the documentation in some way?
