### ISSUE TITLE
ap function dispatches to wrong argument

### ISSUE THREAD

**Issue by JeffDownie** [ramda/ramda#2002]
From the description:

> Dispatches to the ap method of the second argument, if present.

However, the following code prints out CALLED:

```
var o = {
  ap: function(x){
    console.log('CALLED');
    return x;
  }
}
console.log(R.ap(o, 1)); //CALLED
```

This also appears to be the wrong way round to what the fanstasy-land spec requires:

> A value which has an Apply must provide an `ap` method. The `ap` method takes one argument:
> `ap :: Apply f => f a ~> f (a -> b) -> f b`
> `a.ap(b)`
> `b` must be an Apply of a function

**Comment by davidchambers** [comment]
> From the description:
>
> > Dispatches to the ap method of the second argument, if present.

Would you like to submit a pull request to correct this?

Ramda currently targets [v0.3.0][1] of the Fantasy Land specification, which explains why the argument order does not match that of the current version of the specification. #1900 will update Ramda to a more recent version of the specification, if merged.


[1]: https://github.com/fantasyland/fantasy-land/tree/d119757cca5db2dc3bf83ea56f24fc82c7e11fb4

**Comment by JeffDownie** [comment]
Ah, that makes sense! I thought I saw something to do with the order of `ap`'s arguments, but couldn't find it again!

I've made a PR for it now: #2004
