### ISSUE TITLE
isNil doesn't account for undeclared variables

### ISSUE THREAD

**Issue by greyvugrin** [ramda/ramda#2005]
<img width="997" alt="screen shot 2016-12-09 at 11 45 04 am" src="https://cloud.githubusercontent.com/assets/3294460/21062847/87aaf3b8-be07-11e6-8e6f-a61a6d768b72.png">

The source of isNil checks for `x == null`, but if x was never declared as a variable, an error is still thrown. Since isNil seems to imply that it checks for a variable being funky, it makes sense to account for that case and add something like `&& typeof(x) !== 'undefined'`.

Otherwise, a new function could be added, like `exists`, if this should be handled separately.

What do you think? I'm happy to put up a PR for either case.

**Comment by davidchambers** [comment]
This is actually nothing to do with `isNil`. JavaScript is eagerly evaluated, so before `isNil` can be applied to its argument its argument must be evaluated. In this case, evaluating the argument results in a ReferenceError being thrown:

```javascript
windoww;
// ! ReferenceError: windoww is not defined
```

One could use `typeof windoww` to guard against this at the call site.

**Comment by greyvugrin** [comment]
@davidchambers Huh I didn't know that JS did that. Thanks for the info, will close this!
