### ISSUE TITLE
Array containing undefined values

### ISSUE THREAD

**Issue by jvorcak** [ramda/ramda#2014]
Hi,

Maybe this is not a bug, but I want to consult and ask a question about a little bit unexpected behavior. 

In Javascript, you can have array which contains undefined values e.g.
```
>> const a = [];
<< undefined
>> a[3] = 33
<< 33
>> a[2]
<< undefined
>> a[3]
<< 33 
```

It also works in Lodash

```
>> const update = require("lodash.update")
>> update([], 3, () => 3)
<< [undefined, undefined, undefined, 3]
```

However in Ramda, `R.update(3, 4, [])` returns `[]`. Don't you think it's a little bit unexpected behavior? Thanks for consulting this.

**Comment by CrossEye** [comment]
Ramda make no guarantees at all about what happens with sparse lists.  It thinks about them as errors although it doesn't try to detect them.

Ramda's fundamental iterable structure should be a *list*.  It just happens that JS doesn't include an efficient list type in the core language, so we depend on dense arrays as the closest analogue available..  When someone passes a sparse list, all sorts of bad things can happen.

You can see further explanations in https://github.com/ramda/ramda/issues/1002#issuecomment-89385321 or https://github.com/ramda/ramda/issues/1761#issuecomment-220807007, where I say, 

>  If people pass sparse arrays to Ramda functions that are looking for lists, bad things could happen. Ramda might eat your hard drive, crash your car, steal your boyfriend, launch the nuclear weapons. I won't try to prevent it.

So, while Ramda does try to work with the grain of JS, it is more opinionated than some libraries about the parts of the language that it finds important.  Sparse arrays are not among them.

**Comment by jvorcak** [comment]
@CrossEye thanks for a great explanation. It makes sense to me now. I'm wondering whether it would be an idea to have this stated somewhere in the docs. (I'm not quite sure where exactly though).

Otherwise users needs to learn it the hard way. Luckily we found out that Ramda doesn't support sparse lists thanks to our unit tests, others might not be that lucky...

**Comment by CrossEye** [comment]
>  I'm wondering whether it would be an idea to have this stated somewhere in the docs.

Possibly, although I also am not quite sure where.

But this is, I believe, the first time that anyone has raised this as anything other than a theoretical concern.

**Comment by jkarttunen** [comment]
Happens sometimes when fetching edited arrays from firebase, not very theoretical to me :/

**Comment by CrossEye** [comment]
@jkarttunen: Do you have a recommendation?
