### ISSUE TITLE
Bug on view + lensPath

### ISSUE THREAD

**Issue by joaomilho** [ramda/ramda#2018]
Found this odd behavior today:
```js
R.view(R.lensPath('x'), {x: 1})
1
R.view(R.lensPath(['x']), {x: 1})
1
R.view(R.lensPath('name'), {name: "Joe"})
undefined
R.view(R.lensPath(['name']), {name: "Joe"})
Joe
```

**Comment by CrossEye** [comment]
... but

```js
R.view(R.lensPath('name'), {n: {a: {m: {e: "Joe"}}}}); //=> "Joe"
```

This is where the difference between Ramda and Sanctuary is most stark.

    User: Doc, it hurts when I do this.
    Ramda: Then don't do that.
    Sanctuary: Exception: expecting a list of Strings, received just a String. 

Ramda grew out of an earlier experiment that failed utterly because, even with a wonderful API and elegant code, it performed abysmally.  Taking on expensive type-checking, even if the original developers were interested, would have seemed a significant back-slide.  Sanctuary is much more interested in type safety and avoiding partial functions.

Because strings have lengths and are integer-indexable, it turns out that Ramda has no problem looking at `lensPath('name')` as pretty much the same as `lensPath(['n', 'a', 'm', 'e'])`.

So, while `R.lensPath('x')` should be a type error, it just happens to work.  I doubt this is something we really want to try to fix.

**Comment by joaomilho** [comment]
Right.... `String` is just `[Char]`... haven't thought about that.

**Comment by CrossEye** [comment]
> Right.... `String` is just `[Char]`... haven't thought about that.

It's not, of course.  Javascript hates us too much for that.  But it's close enough at times to confuse us.  :smile:

**Comment by joaomilho** [comment]
A similar problem seems to happen in this scenario:

```
const state = {todos: [{complete: true}]}
const newState = R.over(R.lensPath('todos', 0, 'complete'), R.not, state)
```

In this case `newState.todos` is not an array anymore, but an object with the index set as key (like a Set).

**Comment by joaomilho** [comment]
And the least convoluted solution seems to be: `{...state, todos: adjust(evolve({ complete: not }), 1, state.todos)}`

**Comment by CrossEye** [comment]
This is fixed in the latest release (although you need to pass a list to `lensPath`):

```js
R.over(R.lensPath(['todos', 0, 'complete']), R.not, state)
// v 0.22.1
//=> {"todos": {"0": {"complete": false}}}
// v 0.23
//=> {"todos": [{"complete": false}]}
```

REPL links:

  - v22.1: https://goo.gl/NbkqXy
  - v23: https://goo.gl/XgnZ2x

**Comment by joaomilho** [comment]
Yeah, sorry, the example wasn't correct :D

**Comment by joaomilho** [comment]
Yep, works perfectly.

Just a FYI, it seems to have the same symptom on this example:

```js
R.dissocPath(['a', 'b', 0], {a: {b: [1,2,3]}})
//=> "{"a":{"b":{"1":2,"2":3}}}"
```

I'm not sure "path" here means the same as in `lensPath`, but it's confusing if it doesn't.

**Comment by CrossEye** [comment]
> Just a FYI, it seems to have the same symptom on this example:
> 
> ```js
> R.dissocPath(['a', 'b', 0], {a: {b: [1,2,3]}})
> //=> "{"a":{"b":{"1":2,"2":3}}}"
> ```

I'm really not sure what to do here.  We try to only deal with arrays as lists, but `dissoc` on a list does not make real sense.  Nonetheless, `dissocPath` with an array index as a (non-terminal) path entry is perfectly reasonable.  I don't know if we need some exception logic here.  Hmm.

Any ideas, anyone?  @scott-christopher?

**Comment by joaomilho** [comment]
Seems to me that, as a rule of thumb, if it accepts a path, it should be ok with dealing with arrays.

**Comment by scott-christopher** [comment]
Yep, that was an oversight on my behalf when support for integer path segments was added to the other path functions recently.

I've raised #2036 to address this.

**Comment by CrossEye** [comment]
Oh, I didn't go looking at all.  I assumed that this had to do with it being in the terminal position.  This is much simpler!

**Comment by joaomilho** [comment]
Cool, closing.
