### ISSUE TITLE
reduceBy, reduceWhile, tail, F, T function length is incorrect

### ISSUE THREAD

**Issue by jeiea** [ramda/ramda#2019]
All functions in the title have 0 length.
```
console.log(`${R.reduceBy.length} ${R.reduceWhile.length} ${R.tail.length} ${R.F.length} ${R.T.length}`)
> 0 0 0 0 0
```
Function length seems generally right, so I wonder if these functions' behaviour is intended.

**Comment by kedashoe** [comment]
I've fixed `reduceBy` and `reduceWhile` as part of https://github.com/ramda/ramda/pull/1843. I believe `F` and `T` are correct having a length of 0. `tail` does appear to be wrong. Would you like to submit a pull request to fix `tail`?

**Comment by jeiea** [comment]
I don't know if I did well, but I push it anyway.

**Comment by jeiea** [comment]
I noticed my pull request has conflict with your #1843 removing `_curry1`.
But I'm not sure what method is right and I have enough knowledge to do it.
Can I use `curryN(1)`? If this method is also problematic, I think it's better for others to do it.

**Comment by kedashoe** [comment]
There's no guarantee #1843 will be merged and I'll have to do a ton of rebasing anyway at this point, so your use of `_curry1` is fine :)
