### ISSUE TITLE
customizer of only used functions

### ISSUE THREAD

**Issue by Rafi993** [ramda/ramda#2025]
It would be better if a customizer that would allow us to select only functions that we use and download ramda.min.js with only those functions. It would be even awesome if that customizer if part of  Ramda documentation.

**Comment by davidchambers** [comment]
@Rafi993, are you aware of <http://ramdajs.com/#partial-builds>?

@MattMS, note that the navigation bar prevents the link above from working nicely.

**Comment by Rafi993** [comment]
@davidchambers  this was the script I was talking about https://github.com/ramda/ramda/pull/2026.  I have created the pull request.
