### ISSUE TITLE
0.23.0 upgrade guide

### ISSUE THREAD

**Issue by scott-christopher** [ramda/ramda#2029]
Changes: https://github.com/ramda/ramda/compare/v0.22.1...v0.23.0

Additions:
- 🆕 #1917 Added `R.forEachObjIndexed`
- 🆕 #1946 Added `R.sortWith`, `R.ascend` and `R.descend`

Removals
- ❌ #1857 `R.wrap`

Deprecations:
- 💾 #1877 `R.isArrayLike`

Changes:
- #1833 Corrected `null` value handling in `R.evolve`
- #1883 `R.dissoc` now accepts non-string keys
- #1928 Introduced `index.js` entrypoint
- #1926 Integer path segments are now accepted in `R.path` and related functions
- #1992 Fixed `R.uniq` to compare functions by reference
- #2020 Fixed `R.tail` to report arity of 1
- ⚠️ #1949 Method dispatching removed for:
  `R.apperture`, `R.dropLast`, `R.dropLastWhile`, `R.dropRepeats`, `R.dropRepeatsWith`,
  `R.findIndex`, `R.findLast`, `R.findLastIndex`, `R.reduceBy`
- ⚠️ #1975 Argument order of `R.reduceRight` has been flipped
- ⚠️ #1986 `R.pipeK` and `R.composeK` now create functions that expect unlifted arguments
- ⚠️ #1937 Corrected `R.chain` implementation for `Function` arguments

Many thanks to all the contributors supporting this release, especially to those helping with numerous improvements to tests and documentation. :tada:

**Comment by UrsMetz** [comment]
PR #1975 also flipped the arguments of the reducer for `R.mapAccumRight`, so this should also be listed as an important change of #1975, shouldn't it?
