### ISSUE TITLE
scaling functions similar to D3

### ISSUE THREAD

**Issue by Rafi993** [ramda/ramda#2032]
It would be better if there are scaling functions present similar to D3js so that we can easily convert list from one scales to another. So we could something like this
```
R.linearScale = (domainMin,domainMax) =>
                   (rangeMin,rangeMax) =>
                       (n) => 
                         rangeMin + (n - domainMin) * (rangeMax - rangeMin) / (domainMax - domainMin) 


const initialScaleData = [0, 1000, 3000, 2000, 5000, 4000, 7000, 6000, 9000, 8000, 10000];
let linearScale = R.linearScale([0,1000]);
let converter = linearScale([0,100]);

console.log(R.map(converter(n),initialScaleData))
```
This could be implemented way better than this. similarly for logscales etc..

**Comment by CrossEye** [comment]
I believe this is the first time we've heard requests for functions such as this.

While these are functions I occasionally use myself, I don't see them being general-purpose enough to fit in the library.  What do you think about adding them to the [Cookbook][cb]?


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by Rafi993** [comment]
@CrossEye  I edited the Cookbook https://github.com/ramda/ramda/wiki/Cookbook#linear-scaling-of-array

**Comment by CrossEye** [comment]
Thank you @Rafi993!
