### ISSUE TITLE
lensPropOr

### ISSUE THREAD

**Issue by mspoulsen** [ramda/ramda#2033]
Ramda has prop and propOr. It also provides lensProp. Would adding lensPropOr makes sense?

**Comment by CrossEye** [comment]
I don't think so.  Lenses have their own logic, and while our lenses aren't perfect, we try not to stray too far from the norms.  There is (a fairly quiet) sister project [Ramda-lens][rl] dedicated to experimenting with Lenses, Prisms, Isos, and so on.


  [rl]: https://github.com/ramda/ramda-lens
