### ISSUE TITLE
ComposeK seems to be broken in 0.23.0

### ISSUE THREAD

**Issue by diegovdc** [ramda/ramda#2034]
Functions such as this are breaking in the most recent version.  
```
let plus5 =  x=> Task.of(x+5)
let times2 =  x => Task.of(x*2)
let plusTimes = R.composeK(times2, plus5)
plusTimes(Task.of(21)).fork(R.identity, R.identity))//NaN
```

I am using Folktale's Task

**Comment by diegovdc** [comment]
Oh found the commit with the breaking changes:  fcbb62b1a93b021414127787acb5c7d65bf5275d

Turns out the composition should now be called like this `plusTimes(21).fork(R.identity, R.identity))`

It looks cleaner, though.

**Comment by jethrolarson** [comment]
The new version seems more correct.

binary ComposeK would be 
`Chain M => (b -> M c) -> (a -> M b) -> a -> M b`
So plusTimes(Task.of(21)) is passing Task(21) to plus5 which is expecting a number
