### ISSUE TITLE
0.23.0 shipped not compiled

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#2035]
0.23.0 is a bunch of files instead of one compiled file (making it very slow in RunKit)

**Comment by kedashoe** [comment]
We still bundle a compiled version in `dist`. Would it help if we follow the directions [here](https://discuss.runkit.com/t/customizing-your-npm-packages-page-on-tonic/23) to provide an example like [this](https://runkit.com/5867353aff226c0014109366/58673a70ff226c001410946f)? Is there something else you recommend?

**Comment by CrossEye** [comment]
I'm going to have to go back to look at those discussions.  I thought that this new version was a way to make it easier to *test*, and that perhaps eventually it would help us make it easier to do a `require('ramda/map')`.  But I don't think I understood clearly that it would turn the standard Node loading into a large number of file calls.  Is there any benefit to that?  I can't see one at the moment.

**Comment by iamstarkov** [comment]
Let me think about it tomorrow

**Comment by CrossEye** [comment]
Thank you.

**Comment by tolmasky** [comment]
Any movement on this? This is actually also a big slowdown for naive gulp setups, since browserify will traverse hundreds of files instead of just one.

**Comment by kedashoe** [comment]
We're updating our build here: #2254. Let's wait until that is merged to address any concerns related to this issue.

**Comment by davidchambers** [comment]
This issue is stale now that #2254 has been merged.
