### ISSUE TITLE
Why 'use strict' is not present in the library

### ISSUE THREAD

**Issue by yesprasad** [ramda/ramda#2048]
I was wondering why none (maybe many) of the files don't have 'use strict'. What is the advantage and disadvantage of using 'use strict' in our library.

If you consider a silly question, am okay to have this closed yet I will be happy to have an answer to this a JS community question.

**Comment by henriklundgren** [comment]
https://github.com/ramda/ramda/blob/master/dist/ramda.js#L8

**Comment by CrossEye** [comment]
Yes, it's in the dist version.  For a long time that was the only thing we cared about.  I don't know how important it might be to include it in every file.  Care to make an argument for it, @yesprasad?

**Comment by yesprasad** [comment]
@CrossEye @henriklundgren Thank you so much for the reply. I have checked in my application from which file the functions are called from - and they are from 'dist/ramda.js'. As this is the file and it has 'use strict' there should never be a worry. I am starting up trying to understand and contribute to open source.
