### ISSUE TITLE
Optimize `R.call`'s comment

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2050]
> This is occasionally useful as a converging function for R.converge: the left branch can produce a function while the right branch produces a value to be passed to that function as an argument.

There could be more than one arguments pass to the function produced by the first branch function

```js
const obj = {
  func: (a, b) => a + b,
  firstArg: 1,
  secondArg: 2,
}
const result = R.converge(R.call, [R.prop('func'), R.prop('firstArg'), R.prop('secondArg')])(obj);
console.log(result); // 3
```

> the left branch can produce a function while the right branch produces a value to be passed to that function as an argument.

should be:
the first branch function can produce a function while the rest other branch functions produce a list of values to be passed to that function as it's arguments.

**Comment by davidchambers** [comment]
Could you provide a type signature?
