### ISSUE TITLE
Works in REPL but not in node.js

### ISSUE THREAD

**Issue by rasmeister** [ramda/ramda#2051]
I have a simple node module that gives a TypeError: Cannot read property 'call' of undefined when run. If I cut and paste the code into the REPL it works as expected.

Here's the code:

`var R = require('ramda');

var testList = [
  { a: 1, linkGuid: 2, test: "Item 1" },
  { a: 3, linkGuid: 12, test: "Item 2" },
  { a: 1, linkGuid: 22, test: "Item 3" },
  { a: 2, linkGuid: 32, test: "Item 4" },
  { a: 1, linkGuid: 42, test: "Item 5" }
];

var search = R.useWith(
  R.find,
  R.propEq('linkGuid'),
  R.identity
);

search(12, testList);`

Here's the error I get

`c:\Users\Rodney\WebstormProjects\firstProject\node_modules\ramda\dist\ramda.js:4646
                args.push(transformers[idx].call(this, arguments[idx]));
                                                           ^

TypeError: Cannot read property 'call' of undefined
    at c:\Users\Rodney\WebstormProjects\firstProject\node_modules\ramda\dist\ramda.js:4646:44
    at c:\Users\Rodney\WebstormProjects\firstProject\node_modules\ramda\dist\ramda.js:551:35
    at c:\Users\Rodney\WebstormProjects\firstProject\node_modules\ramda\dist\ramda.js:52:27
    at Object.<anonymous> (c:\Users\Rodney\WebstormProjects\firstProject\js\find.js:18:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

Process finished with exit code 1`

(The caret should point to the start of the .call portion of the line not where it is shown above)

I am running v0.22.1 in both environments (v0.23 also fails in node). My node version is v4.2.2.
Any idea why this might occur?

**Comment by rasmeister** [comment]
I have recreated in the REPL - https://goo.gl/dMgjb5

**Comment by rasmeister** [comment]
Nevermind... The 2nd parameter of useWith takes an array which I was missing.

**Comment by CrossEye** [comment]
Ahh, there's old documentation around here and there from before we switched to that...  sorry.

**Comment by CrossEye** [comment]
Also note: if you're operating in an ES6 environment (or with a preprocessor such as Babel), much of the utility of a function like `useWith` is superfluous.  To my mind, this is simply much more readable:

```js
var search = (guid, list) => R.find(R.propEq('linkGuid', guid), list)
```

(with an additional `curry` wrapper if you're planning on using it that way.)
