### ISSUE TITLE
String.includes

### ISSUE THREAD

**Issue by Cinderella-Man** [ramda/ramda#2056]
Would it be possible to add support for `String.includes`?

Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

**Comment by svozza** [comment]
Pretty sure `R.contains` does the same thing.

**Comment by Cinderella-Man** [comment]
Yes, I'm sorry just checked it, works fine as behind the scenes it's using `.indexOf`. Closing this one

**Comment by sugoidesune** [comment]
R.contains is deprecated and worked on lists.
Whats the current equivalent?

**Comment by adispring** [comment]
@sugoidesune ，Yes，`R.contains` has been renamed to `R.includes` since v0.26.0, see as follows:

https://github.com/ramda/ramda/pull/2452
https://github.com/ramda/ramda/issues/2702
