### ISSUE TITLE
pickAll - incorrect behavior if key name is `hasOwnProperty`

### ISSUE THREAD

**Issue by mimol91** [ramda/ramda#2063]
If elements in pickAll method has name equal to methods available in Object prototype returning value is not correct:
Examples:
```js
R.pickAll(['a', 'hasOwnProperty'], {a: 1}); 
R.pickAll(['a', 'toString'], {a: 1}); 
```

**Comment by ascartabelli** [comment]
Actually the result is what I would have expected as the documentation doesn't hint at all about the function picking only the "own properties" of the object. Given that, references to inherited properties, not only the ones in the Object prototype, are copied as "own properties" in the resulting object.

Or did I miss your point?

**Comment by mimol91** [comment]
Ye, You are right.
Sorry for confusion
