### ISSUE TITLE
Chain Documentation

### ISSUE THREAD

**Issue by keithbro** [ramda/ramda#2067]
Is the documentation for the chain function correct? The type is documented as:

    Chain m => (a → m b) → m a → m b

But the example given i.e.

    R.chain(R.append, R.head)([1, 2, 3]); //=> [1, 2, 3, 1]

Shows that chain can take multiple functions as args. These don't seem to match up. But maybe I'm misunderstanding?

**Comment by buzzdecafe** [comment]
It does match up. The signature says that anything that is a "Chain" will satisfy; `Function x` is a [Chain](https://github.com/fantasyland/fantasy-land#chain). I recently [blogged about this](http://buzzdecafe.github.io/2016/12/29/chain-chain-chain).

If you find that a satisfactory response, please close this issue. Thanks.

**Comment by keithbro** [comment]
Right, that does make sense and also blows my mind. But do you think it would be worth mentioning in the docs that functions are chains? Perhaps not, it might be more obvious if I was more familiar with the topic.

**Comment by buzzdecafe** [comment]
> do you think it would be worth mentioning in the docs that functions are chains?

I am fine with that idea. I do not think it is obvious. But would that mean updating `map` et al. docs as well? After all `Function x`is also a Functor.

**Comment by keithbro** [comment]
In the `map` documentation it does say:

    Also treats functions as functors and will compose them together.

Is that kind of saying the same thing? Could just have a similar line for `chain`

    Also treats functions as chains and will compose them together.

That might be enough?

**Comment by buzzdecafe** [comment]
LGTM. Would you like to submit a PR?
