### ISSUE TITLE
Lenses + pathEq

### ISSUE THREAD

**Issue by char0n** [ramda/ramda#2069]
Hi,

I am using lenses extensively and I am defining all data focusers as lenses. Problem is when I want to use functions like `pathEq`. These functions are not designed to work with lenses. I can overcome this limitation 
with simple shortcut
```javascript
const value = view(lens, object);
console.dir(value === exptected)
```
or with composition
```javascript
flow(
  view(lens, object),
  eq(exptected)
)()
```
But this doesn't seem quite right. I am inclined to create my own util `lensEq` with this signature

```javascript
lensEq :: Lens -> Any(exected) -> Any(focused object) -> Boolean
```

I am just wondering, am I missing something in ramda ? If not, is `lensPath` the right direction to go ?

Thank you very much

**Comment by ecwyne** [comment]
```javascript
const lensEq = curry((l, expected, comp) => compose(equals(expected), view(l))(comp));
```

**Comment by char0n** [comment]
@ecwyne thanks. The problem is not that I am not able to implement it, I can always create my own utils around the lenses. My question was rather: Am I suppose to do it ? Why ramda doesn't contain these utils itself ?

**Comment by CrossEye** [comment]
Although little has been done lately, there is a side project [ramda-lens][rl] to investigate possible extensions and enhancements to our lenses, included very different types of lenses and related creatures.

But Ramda doesn't try to do all the things one might want to do with do with lenses.  There are far too many.  It just includes `set`, `view`, `over`, and a few helpers to create simple `lens`es.  The library already well over 200 functions.

While this is a nice use of lenses, it's the first time I've heard a request for it.  I don't think it's quite as common as you might expect.  Or perhaps I'm wrong, and lots of people are creating it, but finding it easy enough to do that they don't bother making requests from Ramda.

I would love to see this in the [Cookbook][cb], though.


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [rl]: https://github.com/ramda/ramda-lens

**Comment by char0n** [comment]
@CrossEye thanks for your answer. I have already created [pull request](https://github.com/ramda/ramda-lens/pull/18) for [ramda-lens](https://github.com/ramda/ramda-lens). If it gets merged I will start using ramda-lens library futher and make pull request regarding further lens utilisation.

It would be great to put it in Cookbook also. I would do it, but I cannot create pull requests to wiki pages on github. 

Also it would be great for Cookbook to contain some recipes about lenses composition. It was something I had to figure out for my self. I wrote an [article](https://www.linkedin.com/pulse/composing-lenses-ramda-vladim%C3%ADr-gorej) on a subject with extended explanation and examples. Maybe if you could incorporate this article into Cookbook or at least put url of it in Cookbook it may save some people some time figuring it out.

**Comment by CrossEye** [comment]
Thanks for the link to the article.  I'm surprised that lens composition isn't documented.  We should definitely fix that.

The wiki page should be publicly editable.  If you can't edit it, please let us know.

**Comment by char0n** [comment]
@CrossEye I have added the link of the article to ramda Wiki homepage (title: `Composing lenses in Ramda`). I will also submit a recipe for lens composition in a couple of days.

**Comment by char0n** [comment]
Extensions to ramda lenses were implemented in [ramda-adjunct](https://github.com/char0n/ramda-adjunct) some time ago. Namely [lensEq](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.lensEq), [lensNotEq](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.lensNotEq), [lensSatisfies](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.lensSatisfies), [lensNotSatisfy](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.lensNotSatisfy) and [viewOr](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.viewOr). I guess we can close this one. 

@CrossEye should I also add these into cookbook ?

**Comment by buzzdecafe** [comment]
cookbook sounds good to me!

**Comment by CrossEye** [comment]
Yes, please.

**Comment by char0n** [comment]
Note: we have it in cookbook now.
