### ISSUE TITLE
consider using a backwards while-loop for map

### ISSUE THREAD

**Issue by mrtnbroder** [ramda/ramda#2072]
`map` and other methods could be made a tiny bit faster when we would use a backwards loop, see http://stackoverflow.com/a/23998651/1246198 why it's faster and so on.

```
...
**Look at this** 

    for( var index = 0 , length = array.length ; index < length ; index++ ) {
     
     //do stuff
    
    }

 1. Need to create at least 2 variables (index,length)
 2. Need to check if the index is smaller than the length
 3. Need to increase the index
 4. the `for` loop has 3 parameters

**Now tell me why this should be faster than:**

    var length = array.length;
    
    while( --length ) { //or length--
    
     //do stuff
    
    }

 1. One variable
 2. No checks
 3. the index is decreased (Machines prefer that)
 4. `while` has only one parameter
...
```

This is just a suggestion, doesn't have to be this way in any way ;)

**Comment by CrossEye** [comment]
I rarely find that sort of micro-optimization worth it, especially as the JS engines themselves continually change focus and optimize different parts of the specifications.  I'd rather stick to cleaner code unless there's an obvious gain.

**Comment by mrtnbroder** [comment]
This since is a library though, I'd say that micro-optimization is worth it.

**Comment by svozza** [comment]
I don't think there's one `for` loop in all of the Ramda source code.

**Comment by mrtnbroder** [comment]
> I don't think there's one for loop in all of the Ramda source code.

Idk about for, but there are [while loops](https://github.com/ramda/ramda/blob/master/src/internal/_map.js#L5-L8)

**Comment by svozza** [comment]
I was being facetious. ;) I'm with @CrossEye though, I'm not sure if it's worth the effort; I'm not really convinced of the usefulness of microbenchmarks: trying to outsmart the compiler if often a fool's errand.

**Comment by mrtnbroder** [comment]
It's not about trying to be clever and outsmart the v8 compiler, but to use the full optimization potential out of it.

**Comment by CrossEye** [comment]
I'm definitely not convinced:

```js
const suite = new Benchmark.Suite

suite.add("normal ramda", () => {
  R1.map(n => n * n, [1, 2, 3, 4, 5])
})
.add("ramda with reversed while", () => {
  R2.map(n => n * n, [1, 2, 3, 4, 5])
})
.on("cycle", event => {
  benchmarks.add(event.target)
})
.on("complete", () => {
  benchmarks.log()
})
.run()
```


```shell
>node bench

  2 tests completed.

  normal ramda              x 270,420 ops/sec ±0.84% (90 runs sampled)
  ramda with reversed while x 265,899 ops/sec ±0.82% (91 runs sampled)
```

**Comment by svozza** [comment]
Vyacheslav Egorov is well worth reading on this stuff, has some good talks too:

http://mrale.ph/blog/2012/12/15/microbenchmarks-fairy-tale.html

**Comment by mrtnbroder** [comment]
> I'm definitely not convinced:

Now imagine a larger array and the function being run many times in just a few seconds (quite the real world scenario, with React + some render logic)

**Comment by CrossEye** [comment]
Benchmark runs these as many times as it can.  (It's what underlies JSPerf, and a successor of sorts to JSLitmus.)

And I'm still not convinced:

```js
const R1 = require("./ramda")
const R2 = require("./ramda2")
const Benchmark = require("benchmark")
const benchmarks = require("beautify-benchmark")

const tenK = R1.range(1, 10001);

const suite = new Benchmark.Suite

suite.add("normal ramda", () => {
  R1.map(n => n * n, tenK)
})
.add("ramda with reversed while", () => {
  R2.map(n => n * n, tenK)
})
.on("cycle", event => {
  benchmarks.add(event.target)
})
.on("complete", () => {
  benchmarks.log()
})
.run()
```

```shell
>node bench2

  2 tests completed.

  normal ramda              x 9,611 ops/sec ±0.92% (90 runs sampled)
  ramda with reversed while x 9,806 ops/sec ±1.41% (85 runs sampled)


>node bench2

  2 tests completed.

  normal ramda              x 9,937 ops/sec ±0.83% (90 runs sampled)
  ramda with reversed while x 9,771 ops/sec ±1.28% (88 runs sampled)


>node bench2

  2 tests completed.

  normal ramda              x 9,922 ops/sec ±0.81% (89 runs sampled)
  ramda with reversed while x 9,919 ops/sec ±0.86% (86 runs sampled)
```

Mostly I'm not convinced of the worth of chasing such micro-optimizations.  If there is a really substantive difference, I would certainly be interested in talking about it.  But I don't see that here.  I see years of history of engines one-upping each other in various parts, and performance gaining unevenly because of that, but no particular algorithmic advantage.
