### ISSUE TITLE
tap with promise chains

### ISSUE THREAD

**Issue by bijoythomas** [ramda/ramda#2074]
I'd like to add tap variant to a promise chain (from composeP or pipeP) with the idea that the tap is dealing with a promise. Does a tapP function have any use? Or do we just do

```
var tapP = function (fn) {
     return function (promise) {
         return promise
             .then(function (x) {
                  fn(x);
                  return promise;
             });
     };
};
```

**Comment by CrossEye** [comment]
My feeling is that this would be best placed in the [Cookbook][cb].

Promises are not well-loved around here, and we're much more likely to be removing Promise-related functionality than to be adding it.


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by Bradcomp** [comment]
Seems like `tap` works just fine inside a promise chain https://goo.gl/uOL9cG

**Comment by bijoythomas** [comment]
Indeed it does. Not sure what I was thinking when I cooked up the idea for tapP. Thanks for pointing it out.

**Comment by CrossEye** [comment]
Even better!

**Comment by stevenyap** [comment]
@bijoythomas @Bradcomp 
`tap` only works if wrapped function does not return a promise. In other words, if `tap` wraps a promise, `pipeP` will not wait not for the promise to return before passing down the chain.

Please see my example here: http://bit.ly/2lClYM6
The first promise ('first') should resolve before the second promise ('second') but it did not.

We need a `tapP` which is a promise-aware `tap` that will resolve the promise before passing down the chain. (I need it... @bijoythomas needs it... I hope more people need it so that it becomes part of the module)

Please advise if this makes sense or if there are alternatives.
If this is useful to the community, I can help to contribute this feature.

A quick idea of `tapP` is like below:
```
var tapP = (fn) => (promise) => {
  return promise.then((result) => {
    return fn(result).then(() => result)
  })
}
```

**Comment by bijoythomas** [comment]
@stevenyap Just to clarify, I was under the wrong impression that the function wrapped with`tap` in a `pipeP` or `composeP` chain would be called the promise itself instead of what it resolves to.

The function wrapped with `tap` gets called with the result of the previous member of the chain in a non-promise chain, and the actual resolution of the promise in a promise chain. This helps so that I just need one function that I can wrap with `tap` regardless of the chain I use.

The other behavior of tap is that its return value is never used. It just calls the wrapped function with the argument and whatever it returns is sort of discarded in the chain. 

See example here: [https://goo.gl/pHoQQ0](url)

In that sense, even if the `tap` returned a promise, the chain would not wait for it since I believe that's just how the chains use `tap`

**Comment by CrossEye** [comment]
> The other behavior of `tap` is that its return value is never used. It just calls the wrapped function with the argument and whatever it returns is sort of discarded in the chain.

Yes, that's why it's an odd fit for Ramda.  It's so useful that we keep it, but it's strange to have a function only useful for its side-effects.

That it works this way should be clear enough from the source:

```js
const tap = curry(function tap(fn, x) {
  fn(x);
  return x;
});
```

It's all about the side effects... odd.

**Comment by stevenyap** [comment]
@bijoythomas thanks for your clarification... in your case as the wrapped function in `tap` are non-promise, so `tap` works.

For my case, my wrapped function is a promise in which `tap` does not work in a promise-chain.

@CrossEye do you think it is worthy to have a `tapP` function in ramda for my use case?
I used it a lot when chaining with pipeP. I am willing to contribute that code.

**Comment by svozza** [comment]
`tap` might be a bit unusual in that it's only useful for side effects but it's so useful for debugging that even Haskell has an [equivalent](https://hackage.haskell.org/package/base-4.9.1.0/docs/Debug-Trace.html#v:trace).

**Comment by CrossEye** [comment]
@stevenyap:
> @CrossEye do you think it is worthy to have a tapP function in ramda for my use case?
> I used it a lot when chaining with pipeP. I am willing to contribute that code.

I think it most likely belongs in the [Cookbook][cb], not in the library proper.  Most of the core contributors are not particularly fond of Promises and don't particularly want to encourage the use of them with Ramda.


  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by stevenyap** [comment]
@CrossEye thanks for reply! I hope you don't mind but I am curious as to If we don't want to encourage user to use Ramda with promises, what is the preferred style to handle promises from a Ramda or functional programming point of view?

**Comment by davidchambers** [comment]
@stevenyap, I recommend a [Fantasy Land][1] -compatible Future or Task type such as the one provided by [Fluture][2].


[1]: https://github.com/fantasyland/fantasy-land
[2]: https://github.com/fluture-js/Fluture

**Comment by CrossEye** [comment]
I agree with @davidchambers.  The main point is that `Future`/`Task` implementations follow known laws and can be used in a manner consistent with many other types.  `Promise` implementations generally do not.
