### ISSUE TITLE
meld

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#2076]
[`meld`][1] is to disappear from Sanctuary in the upcoming v0.12.0 release. In sanctuary-js/sanctuary#303 there was some support for adding this function to Ramda. While the type signature—`[** -> *] -> (* -> * -> ... -> *)`—is out of place in the heavily Haskell-inspired Sanctuary world, it would seem at home alongside Ramda functions with type signatures such as `(*... -> *) -> ([*]... -> [*])` ([`lift`][2]) and `(x1 -> x2 -> ... -> z) -> [(a -> x1), (b -> x2), ...] -> (a -> b -> ... -> z)` ([`useWith`][3]).

If there's interest I will submit a pull request. :thumbsup: / :thumbsdown:

[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#meld
[2]: http://ramdajs.com/0.23.0/docs/#lift
[3]: http://ramdajs.com/0.23.0/docs/#useWith

**Comment by CrossEye** [comment]
I've pointed people to the Sanctuary version a number of times, since Ramda doesn't have an equivalent.  I'd love to at least bring it up here for discussion.
