### ISSUE TITLE
A "problem"(?) with repeat

### ISSUE THREAD

**Issue by notarseniy** [ramda/ramda#2077]
Hello there! Thank you for this very useful library.

Today I ran into some interesting issue, that caused 1 hour of debugging 😅:
```javascript
import { repeat } from 'ramda';

// here i define two dimensional array
let coolArray = repeat([
  repeat(null, 20)
], 20);

// then I change [0][0] element of this array
coolArray[0][0] = true;

// and suddenly i wanna check [1][0] element of this array
console.log(coolArray[1][0]); // excepting 'null' but got 'true' — sadface.rar
```

This happens because 'repeat' function works with reference of value. 

So, there's question: is that behaviour normal in terms of library? Should this will be fixed?
<details>
  <summary>P.S. Fixed code</summary>
  <code>
  let coolArray = map(() => repeat(null, 20), new Array(20)); 
  </code>
</details>

**Comment by notarseniy** [comment]
oh, i have reread docs of repeat and finaly understood what repeat does.
This behaviour is normal, since repeated elements should be equal.

**Comment by CrossEye** [comment]
You might look at [`times`][ti].  I'm not sure if it will do what you want, but it's more flexible than `repeat`.


  [ti]: http://ramdajs.com/docs/#times

**Comment by notarseniy** [comment]
@CrossEye, yeah, exactly this function. thank you!

```javascript
// returns array of 20 arrays of 'null'
let arr = times(() => times(() => null, 20), 20);
```

**Comment by notarseniy** [comment]
I have an idea, @CrossEye. Can we add 'see also times' into docs? I can PR into https://github.com/ramda/ramda.github.io
![image](https://cloud.githubusercontent.com/assets/1084409/22654929/6a06ba38-ec9f-11e6-9bac-d646097b18e7.png)

**Comment by CrossEye** [comment]
absolutely.  A good idea.
