### ISSUE TITLE
Consider making `R.minBy`, `R.maxBy`, `R.min`, `R.max`accept multiple arguments

### ISSUE THREAD

**Issue by TylerYang** [ramda/ramda#2078]
For now `R.minBy`, `R.maxBy`, `R.min`, `R.max` is only accept three arguments, it's a bit confused especially the `Math.min` and `Math.max` accepts multiple arguments. 

e.g. 
```javascript
const list = [
    { name: 'Tyler', age: 28 },
    { name: 'John', age: 29 }, 
    { name: 'Mary', age: 18 }
]
R.minBy(R.prop('age')).apply(this, list) // should return `{name: 'Mary', age: 18} 
```

**Comment by davidchambers** [comment]
What would the value of `R.max()` be, @TylerYang? That's the problem.

Currently we can use `R.reduce` to reduce a list of people to a single person. Note that this forces us to acknowledge the possibility of failure (because `people` could be `[]`).

```javascript
//    people :: Array { name :: String, age :: Number }
const people = [
  {name: 'Tyler', age: 28},
  {name: 'John', age: 29},
  {name: 'Mary', age: 18},
];

//    defaultPerson :: { name :: String, age :: Number }
const defaultPerson = {name: '[default]', age: Infinity};

R.reduce(R.minBy(R.prop('age')), defaultPerson, people);
// => {name: 'Mary', age: 18}

R.reduce(R.minBy(R.prop('age')), defaultPerson, []);
// => {name: '[default]', age: Infinity}
```

**Comment by TylerYang** [comment]
I was thinking it's better to make `R.max()` more powerful by accepting multiple arguments, at least this could make our code a bit shorter and we could have one more option to implement the "max in list" method. 

But it seems it's not a good idea to leave all the options open. Thx @davidchambers
