### ISSUE TITLE
promise based reduceWhile

### ISSUE THREAD

**Issue by Cinderella-Man** [ramda/ramda#2081]
I was thinking would there be an interest in something like reduce while but working with promises? It looks like chain of responsibility - here's a draft that I needed to do yesterday:

https://gist.github.com/Cinderella-Man/2c9d6b89c40a62901e9cbbd6dab50778

Also would there be a chance to add simple methods like: isNumber, isString - I know that it can be achieved by combining methods but that's a little bit too verbose and I was thinking that this is what we would like to avoid?

**Comment by CrossEye** [comment]
We've mostly been avoiding Promise-related functionality.

Most regulars around here prefer Futures/Tasks and find Promises too difficult to think about.

I do like the idea of this functionality.  I would love to see an equivalent proposal for RamdaFantasy/Future.

**Comment by Cinderella-Man** [comment]
Ok. I'm new to Futures/Taks so would need to give it a look but still I'm happy to give it a try and contribute some PR if you are interested?

Any comments regards `isString` for example?

**Comment by CrossEye** [comment]
@Cinderella-Man:

> Ok. I'm new to Futures/Tasks so would need to give it a look but still I'm happy to give it a try and contribute some PR if you are interested?

Very much so.

> Any comments regards `isString` for example?

Sorry, missed that first time.

We made a decision a while ago to forgo those.  `R.is` covers these cases well enough, and makes it easy enough to create such helpers if the user wants without adding cruft to the library.

```js
R.is(String, 'foo'); //=> true
R.is(Array, [1, 2, 3]); //=> true
R.is(Array, 'foo'); //=> false

class Rectangle { /* ... */ }
R.is(Rectangle, new Rectangle(5, 3)); //=> true
R.is(Rectangle, {height: 3, width: 5}); //=> false

const isString = R.is(String);
isString('bar'); //=> true
isString([1, 2, 3]); //=> false
```

etc.
