### ISSUE TITLE
I went through ramda's code and you won't believe what I found out!

### ISSUE THREAD

**Issue by rickmed** [ramda/ramda#2083]
Ok I know click bait much...But this actually a serious post so I'll change the title to:

## **Simplify ramda**

Right now, here is what ramda's map can do by default. It can:
1) Map arrays.
2) Map objects.
3) Dispatch map of 2nd argument.
4) Act as a transducer if a transformer is given in list position.
5) Compose functions.
6) Be partially applied with placeholders.
7) Be partially applied "normally".

To me, it seems a bit too much. Also, it complicates functions signatures and description.

Moreover, only the transducers support, from my estimates, is at least 70% of that code. I'm not sure how much of the total code is transducers related but I would guestimate that a lot is. Code that according to @davidchambers' [poll](https://github.com/ramda/ramda/issues/1958) is never used by the 2/3rds and only occasionally used (many for educational purposes) by the rest.

### To give a man the fish or teach him to fish
I've read a fair amount of issues regarding people asking, requesting or trying to contribute some function to be implemented -functions that can be implemented with one or two one-liner functions using functional composition principles. I believe there needs to be more (better?) educational resources, not more code. Examples:
1) [A popular issue bc of Promises](https://github.com/ramda/ramda/pull/1869)  solved with ```const then = R.curry((f, p) => p.then(f))```. pipeP could also be implemented in one line.
2) ```R.replace(/foo/g, R.__, 'foo foo foo')``` equals to ```x => R.replace(/foo/g, x, 'foo foo foo')```

### Moving forward
I'm hopeful for long discussions like https://github.com/ramda/ramda/pull/1900 do not end in situations where [seek of perfection becomes the enemy of done](https://github.com/ramda/ramda/pull/1900#issuecomment-277905307)

### Motivation
Hopefully, I'm not trespassing or coming across as naive. I've come to really appreciate the js fp community and what it brings. I want to see ramda 1.0 soon! So I want to contribute, with words and with code -which, unfortunately, can't do that much normally. With luck, some of the ideas I show [here](https://github.com/ramda/ramda/pull/2082) can help. 

:)

**Comment by kwijibo** [comment]
Is this proposal to remove both transducers and placeholders from the API?

While both features are neat, my small datapoint is that, in my codebase at work where we've been using Ramda for well over a year, we don't use either of those features, and they presumably come with a price in terms of bundle size and performance overhead. I imagine it would also make code easier to debug when going through a callstack in a debugger.

**Comment by rickmed** [comment]
@kwijibo There is a description in the PR on how it would work. If wanted, the npm "ramda" package would be only a refactor. But there would be other packages (eg: "ramda-light" without transducers, placeholder or whatever you would not want or want.)
