### ISSUE TITLE
Can add deepMerge to repo?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2085]
```js
const bar = R.merge(
  {a: {b: 1}},
  {a: {c: 2}}
);
what I want is: {a: {b: 1, c: 2}},
actually result: {a: {c: 2}},
```

Want an api (name like deepMerge) that nest merge objects' properties.

https://jsbin.com/wurarodefi/edit?js,console

**Comment by kedashoe** [comment]
https://github.com/ramda/ramda/pull/1867 :crossed_fingers:
