### ISSUE TITLE
R.construct not working with Set?

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#2087]
The [`construct`](http://ramdajs.com/docs/#construct) docs state it works as a constructor, but it fails for me for `Set`:
```
new Set([1,2,3])
// Set {1, 2, 3}
R.construct(Set)([1,2,3])
// Set {}
```
Am I doing it wrong?

**Comment by ascartabelli** [comment]
After a quick look at Ramda docs, as `Set.length === 0`,  you should use [constructN](http://ramdajs.com/docs/#constructN) instead.

**Comment by tycho01** [comment]
Thanks -- I apologize for the silly question!

**Comment by davidchambers** [comment]
I'd love to get rid of `construct` and `constructN`. Is there any support for this?

**Comment by tycho01** [comment]
I won't pretend I know how other people use Ramda. That said, I'm under the impression there isn't a great alternative to constructing class instances in a point-free style (e.g. also agnostic with respect to constructor arity). Not that I'm using it much though. Feel free to get input from the other members.

**Comment by davidchambers** [comment]
My position is that Ramda needn't make it possible to write *everything* without points.

**Comment by s-ilya** [comment]
@tycho01 don't be so harsh on yourself. That was also super not obvious for me. Glad I came across that question :+1:

**Comment by tycho01** [comment]
@davidchambers Fair enough. I must say it's something it's been fairly good at though!

**Comment by tycho01** [comment]
I might joke I'd just about get the impression providing point-free alternatives to functions is just what Ramda does, but if I were to make an argument, I think the generality of functions including these is what adds value.
That's probably obvious, but in my eyes as a user of one of the typed super-sets of JS (TS), that becomes even more valuable. Like, a lot of things can suck to type manually.
I think this is one area where FP libs like this one can be quite useful -- not only could it add implementations for generally applicable functions (and curried/point-free/pure at that), but also help in providing this type inference that would take additional effort on the part of the user otherwise.
Well, for the moment given the state of TS that's in theory anyway :), and I realize people here have been using Ramda differently (CrossEye no typing, you run-time checks, ...).

**Comment by ascartabelli** [comment]
@tycho01 
> Thanks -- I apologize for the silly question!

No silly at all and no need to apologize, obviously!

@davidchambers 
> I'd love to get rid of construct and constructN

I'm curious, and I'd like to hear your rationale behind that. Just for the sake of an API design discussion as I'm not criticizing your point of view at all.
I think it's only a "somewhat useful" function, I would be the first to have second and third thoughts about introducing it, but as it's already there...

**Comment by davidchambers** [comment]
> I would be the first to have second and third thoughts about introducing it, but as it's already there...

This line of reasoning can lead to death by entropy. I believe active projects must continually reinvent themselves to avoid being replaced by simpler, more focused competitors. I believe exactly the same standards should be applied to existing functions as to newly proposed functions.

**Comment by tycho01** [comment]
I can mark this as open again so you the others might notice your proposal.

**Comment by ascartabelli** [comment]
> This line of reasoning can lead to death by entropy. I believe active projects must continually reinvent themselves to avoid being replaced by simpler, more focused competitors.

Extremely well put, @davidchambers, and I like your reasoning. Even if your statement would fit better in a business perspective, it's not bad even for free software to apply these principles every now and then (read: *cum grano salis*).

I could nitpick on a thing though, always for the sake of discussion:

> I believe exactly the same standards should be applied to existing functions as to newly proposed functions.

Given that I strongly endorse semantic versioning and that Ramda is still a "0.x" everything is fair game in my opinion.
But would you think the same with a "1.0" behind you?
Meaning that in a software development cycle I would be a bit more wary and try to pile up a bunch of "same standards" before deciding to eventually prune the tree.

**Comment by ascartabelli** [comment]
(to clarify: I know that lines are already blurred with Ramda being a "0.x" with an already consistent user base)

**Comment by davidchambers** [comment]
I value semantic versioning as well. Once Ramda reaches 1.0.0 I'd like to discuss which functions should be removed in 2.0.0, but let's not get too far ahead of ourselves. ;)

**Comment by CrossEye** [comment]
... if we ever manage to get to 1.0!

But until we do, I'd like to be able to provide comfortable support for ES5, if not even ES3.  That's where functions like this are still useful.  In ES6+, I think a number of our existing functions and some of our basic techniques should be considered for the chopping block.

**Comment by ascartabelli** [comment]
@CrossEye 

> ... if we ever manage to get to 1.0!

I know the feeling: I'm currently in the perilous and treacherous battle against some relics of the past, but if I don't meet my Waterloo maybe I can beat you to it!
My enemies are sneaky, though.
