### ISSUE TITLE
R.rename?

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#2089]
Every now and then I wonder "should this kind of function be in Ramda?".
I just went over the docs for Python's `Pandas` library (R-like `DataFrame`s), trying to get a sense of parts it currently made more convenient. Among these was an object to rename columns in a dataframe. I couldn't directly see a Ramda equivalent easier than some combination of `pipe`, `toPairs`, `map`, and `fromPairs`, so given that I'd propose a `R.rename({ a: 'b', foo: 'bar' }, { a: 1, foo: 2 }) -> { b: 1, bar: 2 }`. Pretty random, I know, especially since Pandas is by no means a direct competitor to Ramda users. Otherwise maybe fun for cookbook.
Now to get corrected on a super-straightforward equivalent after all!

On a side-note, other bits that stood out to me from its [cheat sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) as not having evident Ramda equivalents were NA handling (we'd probably end up deferring to Maybes?) / sparse data, stat-like functions e.g. binning into quartiles/percentiles, as well as maybe pivoting/unpivoting (which is kinda interesting too). Not a common comparison, I know, but that's why I felt it'd be interesting to check. :)

**Comment by Bradcomp** [comment]
I don't have a super simple equivalent, but this is in the cookbook: https://github.com/ramda/ramda/wiki/Cookbook#rename-keys-of-an-object

For what it's worth, I do use this function on occasion.

**Comment by CrossEye** [comment]
@tycho01:
Does @Bradcomp's suggestion fit the bill for you?

As to the Panda functions, there are some nice things in there, including some that I might personally use, but I see little that seems to make sense in Ramda.  Do you?

**Comment by mattgrande** [comment]
I used the `rename` function as provided in the cookbook more than once, so I opened a PR for this (#2094).

If you want to merge it, great. If not, no big deal. I can see why it's not strictly "ramda-y," but I, personally, think it's helpful.

**Comment by adispring** [comment]
I also use `rename` sometimes.

**Comment by tycho01** [comment]
I tried to add a few ideas from that Pandas to the cookbook (binning, pivoting, joins).

I'd be inclined to defer judgement on `rename`, so I'll mark this thread as resolved; I'm probably not in a great position to judge the identity of Ramda or what it means to people.

To me Ramda had been this single library single-handedly solving general coding problems, though I've only just found that Ramda cookbook functions may have an [alternative home](https://github.com/char0n/ramda-adjunct) as well, allowing for a convenient way to import them if deemed out of scope for the core project (for whatever reason). So in that sense, it should be fine for Ramda not to be like Lodash (be it `/fp`).

I've also just noticed the idea that Ramda's identity does not consist of providing [point](https://github.com/ramda/ramda/issues/2087#issuecomment-278669960)-free [functions](https://github.com/ramda/ramda/issues/2091#issuecomment-281225131) -- another aspect of what it'd been meaning to me. Based on [recent discussion](https://github.com/ramda/ramda/issues/1367#issuecomment-279887477) I started further considering alternatives there though, and played around to put together something of a [general solution](https://github.com/tycho01/pointfree), be it not as general as say `R.map`. Considering that, we might survive even if Ramda were to opt to shed its role as providing point-free alternatives to functions.

I suppose Ramda has also delegated the role of [ADT implementations](https://github.com/sanctuary-js/sanctuary), which admittedly leaves a more focused core.

I'm definitely curious how Ramda's identity will evolve, which I understand might not mean including just anything suggested, even if looking forward [tree-shaking](https://github.com/ramda/ramda/issues/1968) may mean a broader library might no longer mean fattening bundle size for users.

If there is general consensus on functionality somewhat generally of interest to Ramda users to shed off though, I hope we could communicate such intended division of labor between libraries though, e.g. a "Beyond Ramda" section in the readme so as to further clarify Ramda's intended place within this related ecosystem (and commenting on potential synergy / complementary libs where applicable).
I guess there could be some subjectivity there, but to me, general mention of the likes of Fantasy-Land / Sanctuary could make sense to introduce new users to the landscape.

**Comment by CrossEye** [comment]
@tycho01:
> To me Ramda had been this single library single-handedly solving general coding problems [ ... ]

I think of it much more as bringing to JS common techniques from the FP world.  It should make it easier for JS folks to do reasonable FP and make JS more familiar to those from Haskell, Clojure, OCaml, F#, Scala, ML, Scheme, etc.  There is no way we could port over all the functionality of even *one* of those languages, never mind all of them, but if we can provide some of the most common functions, especially for built-in types such as lists (well, arrays), strings, functions, and hash maps or records (objects).  And we can provide some of the most common abstractions to allow users to use our functions with other types.

> I've also just noticed the idea that Ramda's identity does not consist of providing point-free functions -- another aspect of what it'd been meaning to me. 

I think the central point here is **composability**.  We want to be able to easily compose functions.  Our auto-curried functions with parameters ordered reasonably compose much more easily than counterparts designed differently.  Oftentimes this allows for extremely expressive code written in a points-free manner.  But ideally we only choose points-free when it actually *is* more expressive.  When trying to write points-free makes it harder to understand, it should be quickly abandoned.  It is only a tool worth using when it promotes readability.

> I  started further considering alternatives there though, and played around to put together something of a [general solution][pf],

That looks very interesting, and I'm going to keep my eye on it.  At one point, I imagined Ramda moving in a similar direction, but I abandoned it after running up against the size of the API, the number of optional parameters, and the horrendous APIs of things like `Array.prototype.splice`.  I'm very curious to see how well you tame this beast.


  [pf]: https://github.com/tycho01/pointfree

**Comment by tycho01** [comment]
Yeah, I'll have to agree on API size -- it's like there's hundreds of classes in window, rather than just the Array/Object/String/Number that tend to come to mind... and even if you do constrain yourself it's still quite a bit.

Optional parameters were definitely an issue there, obviously. I started off trying to just read in the function lengths, but that ended up naive -- it turned out the lengths ended up short by some parameters not only for rest parameters, but apparently also in the case of optional parameters with defaults values... worse, `Array.prototype.splice` says it has two parameters, yet in practice you can still get away with specifying only `start`, not `deleteCount`. So sometimes you'd wanna specify more parameters than `Function.prototype.length` states, sometimes less...

So well, what this `pointfree` does there now is, given length 2 as a starting point it'd define a `slice` as `(start, deleteCount, array)`. At this point I'd need a way to deal with other arities (in this case all from 1 to theoretically 255 should work, though useful results start at 2), while there's no way to know any of that, and with Ramda I can only curry up to arity 10.

Faced with that, the only real solutions I could come with were:
- ignore non-`length` arities (probably bad).
- just generate variants for any curryable arity, just in case, meaning aside from `splice` I'd have a `splice1` up to `splice10`. In this case only `splice1` isn't particularly useful, but for most functions the majority will end up not even used.
- alternatively, keep things explicit by making the user specify they'd wanted `splice(2)`, e.g. with `deleteCount` left implied.

So the arities might actually work out (be it the optional ones, the faux optional ones e.g. `deleteCount`, or the variadic ones as in `splice`), if only by placing some burden of specifying arity on the user where needed (-> not the arity specified in `length`), which admittedly is hard to solve in an elegant way.

Obviously the semantics of `splice` remain intact in all their horror: if your method would mutilate your data, you now have mutilated data spiced with curry.

It's just remains sugar around batch-invoking `R.invoke`, which just called methods on whatever you end up jamming in, so um... I might wanna add a check there, lest people start trying to invoke `methods' of one prototype on stuff from a different one, as `invoke` would happily comply.

While `x=>x.slice()` is faster I'm not really expecting people to care about this thing (though somehow I'd managed to care for Ramda!), but to me personally static typing is still a bit of a concern as well -- all the more for all the IDE niceties it brings along. So far that's been enough of a pain to me for Ramda itself already, while I'd imagine this thing to be a bunch harder to type still. Read: TypeScript would probably consider all of this too dynamic. Heck, it still loses generics on `R.curry`. But yeah, I'll give it a go later.

**Comment by nicohvi** [comment]
Not to revive an old issue, but if someone runs into the case rewriting one or few keys, and feel like creating a custom function for `all` fields to be included seems like overkill I solve it this way:

```
const renameKeys = keyMap => obj => {
  return R.reduce((acc, key) => {
    keyMap[key] ? acc[keyMap[key]] = obj[key]
    : acc[key] = obj[key]
    return acc;
  }, {}, R.keys(obj));
};
```

**Comment by mg901** [comment]
@tycho01 ```const renameProp = R.curry(
  (oldProp, newProp, { [oldProp]: old, ...others }) => ({
    [newProp]: old,
    ...others,
  }),
);```


```renameProp('breakpoint', 'value', { breakpoint: '1200px' })```

**Comment by chughes87** [comment]
I found that you could also make creative use of `over` and `lens` along with `dissoc` to do a rename:
```
const renameXZ = pipe(over(lens(prop('x'), assoc('z')), identity), dissoc('x'));
renameXZ({x: 1, y: 2}); // { y: 2, z: 1 }
```
