### ISSUE TITLE
Does R.identical() try to fix JavaScript?

### ISSUE THREAD

**Issue by semmel** [ramda/ramda#2090]
When using strings with `R.identical()` it's documentation is wrong:

> Values are identical if they reference the same memory.

Eg. _identical_ individual strings that do not share the same memory (Even so, we could never find that out in JavaScript anyway):
```javascript
R.identical("TEST".toLocaleLowerCase(), "test") // true
```
This is because JavaScript's `===` operator works this way. Which is fine because everybody is familiar with it. 😄 

However, looking at it's implementation `R.identical()` does some things different than the well known `===` operator:

a | b | R.identical(a, b) | a === b
---|---|------------ | -------------
0 | -0 | false | true
NaN | NaN | true | false

I fear that that this list may be incomplete and therefore I cannot rely to know what `R.identical(()` does without every time looking at the implementation. Second I don't want to provide my own `isIdentical => (a, b) => a === b` for FP style JavaScript.

I'd wish that in the future Ramda's API is not diluted with functions which just try to _fix JavaScript_ and carry unnecessary mental overhead (We already have to tell `R.equals`, `===` and `==` apart). But perhaps `R.identical()` is a dinosaur from the early days of Ramda and a bad example for Ramda's API.

**Comment by CrossEye** [comment]
This does not try to fix JS.  It's duplicating the logic of [`Object.is`][oi].  It's specified by the [SameValue][sv] algorithm, which is unfortunately different from the [SameValueZero][sz] one used for object keys.

Granted, the description should be more artfully phrased.  The logic sounds reasonable, though.



  [oi]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
  [sv]: https://tc39.github.io/ecma262/#sec-samevalue
  [sz]: https://tc39.github.io/ecma262/#sec-samevaluezero

**Comment by semmel** [comment]
Thank you  👍 
I did not know that in JavaScript [you need something even stricter than ===](http://www.2ality.com/2012/03/stricter-equality.html) because apparently even that operator is crap. (MDN has a fine [equality comparison matrix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#A_model_for_understanding_equality_comparisons))

So in summary: **`R.identical()` is simply ES6' `Object.is()`.** (polyfilled because Internet Explorer <= 11 and older node.js' don't have it.)

I am not sure to be glad that the ES6 committee did not pick the quadruple equal `====` operator but instead opted for `Object.is()` which [at one point](http://www.2ality.com/2012/03/stricter-equality.html) was supposed to be `Object.egal()` which is very funny if you are German because _egal_ in German simply means _whatever_ which would be a ridiculous choice for naming an equality operator 🙈
