### ISSUE TITLE
Request: Please consider not excluding ./scripts/build in .npmignore

### ISSUE THREAD

**Issue by teehemkay** [ramda/ramda#2092]
It seems to me that this functionality should really be included in the npm package so that one can generate a custom, truly minified build of Ramda just using the npm package.

**Comment by CrossEye** [comment]
I'm curious as to why you feel that way.  I've always thought of NPM as supplying packages.  I would assume those who want to build custom versions would clone the project from GitHub.

Are there many projects delivered that way?

**Comment by teehemkay** [comment]
>  I'm curious as to why you feel that way

Sure.

We have a production build step that introspects our code to find all references to Ramda symbols and then generate a command line invocation of the Ramda build script to create the corresponding minimal build of Ramda which, is then bundled with the rest of our JS code. 

This is in effect our sort of our poor-man [tree-shaking](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80) step similar to what rollup / jspm / webpack 2 provide for code base that use ES2015 modules. 

During development we just use the regular Ramda npm package and only generate the minimal build automatically for production builds of our apps.

Having the build script in the npm package would allow us to manage Ramda just like any other JS dependency.

You can imagine how much more cumbersome it is to use a git clone repository instead of the npm package to manage a JS dependency...

> I've always thought of NPM as supplying packages. I would assume those who want to build custom versions would clone the project from GitHub.
>
>  Are there many projects delivered that way?

I don't know 😃.

I'm not aware of many package that have such as clean modular implementation *and* that also provide a clever build script enabling automatic tree-shaking. 

On the other hand, with the advent of ES2015 modules, more packages are taking advantage of the [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) field to allow for automatic tree-shaking.

I would submit that this may be something worth considering for Ramda too.

**Comment by CrossEye** [comment]
I'm certainly willing to consider it.  I've never had a similar need, but of course, I generally have the Ramda source/build at hand.  I'm wondering what others think.

@buzzdecafe? @davidchambers? @raine?

**Comment by davidchambers** [comment]
It seems reasonable to include this file in the tarball. Given the huge number of dependencies most projects require, the prospect of adding a few kilobytes to the `npm install ramda` payload doesn't bother me.

**Comment by teehemkay** [comment]
Please disregard my request. I didn't realized that Ramda was implemented in such a way that I  could just require individual function (also someone already implemented a [rollup plugin](https://github.com/idmitriev/rollup-plugin-ramda) to essentially rewrites `import {<foo>} from 'ramda'` to  `var  <foo> = require('ramda/src/<foo>'` which fit exactly our original need.
