### ISSUE TITLE
Inconsistency between lensIndex/lensPath

### ISSUE THREAD

**Issue by joaomilho** [ramda/ramda#2093]
Just found this issue:
```js
  R.view(R.lensIndex(-1), ['a','b','c']) // => 'c'
  R.view(R.lensPath([-1]), ['a','b','c']) // => undefined 
```

**Comment by CrossEye** [comment]
This looks like it would be fixed by a suggestion made in https://github.com/ramda/ramda/issues/1988#issuecomment-264376144, but not followed up.

@scott-christopher, any objections to this?

**Comment by scott-christopher** [comment]
The only concern I have is if we change the implementation of `lensPath` to match `lensIndex`, then it will become inconsistent with the behaviour of `path` and `assocPath`.

Could we instead update the implementation of `path` and `assocPath` to support negative indexes?

**Comment by CrossEye** [comment]
Yes, I think that would make sense.  I'll try to look into it soon.

**Comment by keithbro** [comment]
Hi, hope you don't mind me jumping on to help on this one. I was looking for an issue to help with and this one seemed straight forward. I've raised a PR, but I'm not sure that it solves the original issue.

**Comment by CrossEye** [comment]
Very sorry.  At some point I'll find the time to make a new release.
