### ISSUE TITLE
Newbie composition question

### ISSUE THREAD

**Issue by hmgibson23** [ramda/ramda#2095]
Apologies if this is not the place to ask this question but maybe other new people want help as well.

How do I compose a function multiple curried parameters to one with a single curried parameter?

So given a list of objects ```current```. How would I make this work?

```
 var n = R.compose(
   R.adjust(update, R.__, R.__),
   R.findIndex(R.propEq("id", id))
  );

n(current);

```

At the moment ```n(current)``` just results in another curried function.

Thanks

**Comment by buzzdecafe** [comment]
Hi, welcome. 

It's not clear to me what you are trying to achieve? what is the variable `id`? What should the output look like? Also, note FWIW that `adjust(f, _, _)` should be the same as `adjust(f)`. 

Leaving `id` aside for the moment, it makes sense to me that you would get a function out of that composition; I would expect a function from `[a] -> [a]`, since you will pass the `Number` out of `findIndex` to `adjust(f)` and that will give you what is left from `adjust`, namely a function `[a] -> [a]`

**Comment by hmgibson23** [comment]
Hi. Thanks for getting back to me. I basically want to take the result of ```R.findIndex```, apply that to the second argument of ```adjust``` and then ```apply``` adjust to the list. So the flow would be: ```list -> findIndex(fn, list) -> apply(update, findIndex(fn, list), list)```.

Hope that makes sense? I basically want to avoid:  ```apply(update, findIndex(fn, list), list)```. Obviously it doesn't matter but I was wondering if there's a more elegant way to do that function?

Thanks

**Comment by buzzdecafe** [comment]
I'm sorry, this is still not clear to me. Rather than describing how you may implement it, can you provide an example input, and then what the output of running this function on that example input would look like? e.g., `f([{id:1}, {id: 200}])` outputs `???`

**Comment by hmgibson23** [comment]
Sure. So I'd want ```f([id:1, key: "value"}, {id: 200, key: "value"}])``` to output ```[{id: 1, key:"an update"}, {id:200, key: "value"}]```. So the function finds the matching element in the list, updates it  with the update function and returns the new list. Hope that clarifies?

**Comment by buzzdecafe** [comment]
Talked this over with @CrossEye, I agree with him that this problem may not admit a point-free solution. But it can be done in a straightforward way nonetheless:

```js
const fn = curry((id, newValue, list) => adjust(assoc('value', newValue), findIndex(whereEq({id}), list), list))
```

It's tantalizingly close to `chain`; but defining the "updating" function in the `chain` is messier than the above, e.g.

```js
const id1 = propEq("id", 1);
const f = chain(adjust(always('magic happens here')), findIndex(id1))
f([{id:1, key: "value"}, {id: 200, key: "value"}]) //=> ["magic happens here", {"id": 200, "value": "x"}]
```

**Comment by davidchambers** [comment]
This may be a good starting point, @hmgibson23:

```javascript
R.map(R.when(R.propEq('id', 1),
             R.assoc('key', 'an update')),
      [{id: 1, key: 'value'}, {id: 200, key: 'value'}])
```

You could parameterize `1` and `'an update'` quite simply. I think you're better off avoiding `compose`/`pipe` in this case, because the arguments you wish to parameterize are quite nested.

**Comment by hmgibson23** [comment]
Okay thanks for your help. I'll look into that. 

I'll also close the issue.
