### ISSUE TITLE
Ramda Adjunct

### ISSUE THREAD

**Issue by char0n** [ramda/ramda#2097]
Hi,

Couple weeks ago I authored the library [Ramda Adjunct](https://github.com/char0n/ramda-adjunct).  This [README](https://github.com/char0n/ramda-adjunct/blob/master/README.md) and [article](https://www.linkedin.com/pulse/ramda-adjunct-vladim%C3%ADr-gorej) explains my motivations for creating it. I've built it on patterns and practices I found in ramda repo.

I would like you to ask for two things

1.) Is it possible to use [modified logo of Ramda](https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAqdAAAAJDA1MmFlNjc1LWE5YjYtNDRlZi1iMmZhLTg5YzE2MWI3ODkyOQ.png) in jsdocs generated from Ramda Adjunct ?
2.) is it possible to add link of the library to the wiki ? Or maybe even article explaining why it exists ?

Thank you

**Comment by buzzdecafe** [comment]
1. Yes, as long you abide by the terms of the license. As noted in the README: "Ramda logo artwork © 2014 J. C. Phillipps. Licensed Creative Commons CC BY-NC-SA 3.0." I would ask that you make the logo more readily distinguishable from the base ramda logo, but that is  just a courtesy request.

2. If ramda-adjunct turns into the contrib lib of choice, then I think it would make sense to do so. At the moment I don't know enough about the lib or its direction to "bless" it.

**Comment by char0n** [comment]
@buzzdecafe thanks for your answer.

1.) after reflecting on my question and your answer, I decided not to pursue the logo issue. It just doesn't seem right

2.) Let me collaborate more on this point. There is [related project section](https://github.com/ramda/ramda/wiki#related-projects) in ramda wiki. There are currently 9 related libraries including [rcb](https://github.com/enten/rcb). I was asking for permission to add ramda-adjunct in this section.  I have already made a deal with  [rcb](https://github.com/enten/rcb) author for rcb become part of ramda-adjunct. The ideas in library are valid, they just lacks tests, some code is buggy and it is not maintained anymore.

**Comment by CrossEye** [comment]
I'm guessing @buzzdecafe was thinking you were looking for a dedicated spot in the wiki.  This makes perfect sense in the related projects section.  The wiki is publicly editable.  I think this makes as much sense there as many others.  And perhaps if rcb is dead, that one should come out.

**Comment by char0n** [comment]
@CrossEye thanks for your answer. I will add ramda-adjunct into related projects sections. Concerning RCB, it still make sense to keep in related projects, ideas there are still valid. Let's keep it there until it is fully ported to ramda-adjunct.

**Comment by buzzdecafe** [comment]
ok to close this issue?

**Comment by char0n** [comment]
OK for me. Thanks
