### ISSUE TITLE
gt/lt/gte/lte naming

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#2099]
I wanted to comment I've found the naming of the functions such as `R.gt` confusing. It feels to me that in using the `(subject, object)` parameter order, these functions are not fully consistent with the rest of Ramda's functions' order.

This gets a bit more obvious if one were to use partial application on these, likely a common usage within Ramda's curried context. At that point, `R.gt(1)` would *feel* like it should return a function checking if something is greater than 1, but what it does is the opposite -- the `1` is actually the subject of the comparison instead.

Perhaps English isn't a great measure here, and I realize altering this behavior would be horribly confusing in terms of backward compatibility. With that in mind, I'm inclined to close this unless others were to significantly sympathize on this. Still felt it was worth mentioning though.

**Comment by fix-fix** [comment]
This was previously discussed *a lot* with no clear consistent solution, see #1497

**Comment by tycho01** [comment]
Thanks! I'll follow that one too then.
