### ISSUE TITLE
Possible documentation format

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#210]
@buzzdecafe @megawac @cgarciae @ndhoule @saikobee @Offirmo @richardharrington @davidchambers @begriffs @DrBoolean

I'm pinging everyone who's expressed any interest in Ramda documentation.  Feel free to ignore this if you are not actually interested in the topic!  :-)

We've made substantial strides in getting the code documented, thanks to many people, but especially to @ndhoule and @saikobee.  But we haven't done anything yet with the JSDocs that are in the codebase.  JSDoc gives you all sorts of ways to format your output.

I was noodling around with one possible, somewhat unusual, output format for the documentation, and would love to hear your feedback.  A hand-crafted, partial sample is at
http://ramdajs.com/tw/tiddly.html.  It's based on [TiddlyWiki](http://tiddlywiki.com/), which, if you haven't seen it, has historically been a pretty impressive all-in-one-page wiki.  These days, it's grown into a hybrid that can serve as an all-in-one wiki, but which could also be served over Node.js.

So far I've just hand-converted certain functions from the source code into this format, but would find it interesting to consider writing a template for JSDoc or a postprocessor for dox which automated the whole thing.

Right now you can play with changing it yourself.  (One of the icons in the right-hand bar is a "save".)  Tiddlywiki is quite sophisticated, and I think we could do a lot with the format.

So what do you think?  This would not be a trivial effort.  Is it worth working on?  Or should we find a more standard JSDoc template?

**Comment by protoEvangelion** [comment]
If anyone stumbles on this looking to sort by type (_function, object, list_) like lodash, devdocs does just that https://devdocs.io/ramda/
