### ISSUE TITLE
R.unionWith losing object keys

### ISSUE THREAD

**Issue by brentatkins** [ramda/ramda#2102]
I've noticed that unionWith loses additional properties on objects in the second list. Best explained with an example:

```JavaScript
var l1 = [{a: 1, b: 'b'}, {a: 2}];
var l2 = [{a: 1, c: 'c'}, {a: 4}];
R.unionWith(R.eqBy(R.prop('a')), l1, l2);
```

I would expect the result to be: `[{"a": 1, "b": "b", c: "c"}, {"a": 2}, {"a": 4}]`

but the actual result is: `[{"a": 1, "b": "b"}, {"a": 2}, {"a": 4}]`

It's dropped the property "c" in the object with key a = 1.

**Comment by CrossEye** [comment]
I think you misunderstand this function a bit.  The predicate you pass to `unionWith` is one that says that two values are equal.  Once you've determined that they're equal, you get one of them; we don't merge them.  Now we did some work to update the related `differenceWith` in #1868 to make it more consistent what we return; it's not ported here, but even if it were, it would not involve a merge.

**Comment by brentatkins** [comment]
Aha. Thanks @CrossEye 

I've just had another read of the documentation and it's clearer now. UnionWith will check for duplicates and return one rather than merge them.

Thanks
