### ISSUE TITLE
memoize: specify equality check

### ISSUE THREAD

**Issue by alex3165** [ramda/ramda#2107]
I would like to be able to specify the equality check of my `memoize` instead of serialising the arguments and check their values equality, for an `Object` or an `Array` I want to be able to do a reference equality check.

**Comment by tycho01** [comment]
I've been under the impression Ramda has a preference for checking equality over identity. That said, Ramda does do a bunch of `*by` methods allowing you to specify equality functions or whatever, so in that sense...

**Comment by alex3165** [comment]
hum from what I understand of the source code, there is no way to specify the equality check : https://github.com/ramda/ramda/blob/master/src/memoize.js#L33

I would like to be able to do the following:
```
const equalityCheck = (a, b) => a === b

memoize(() => {
// expensive operation here
}, equalityCheck)
```

**Comment by alex3165** [comment]
The problem with the value equality is that it is very expensive to serialise an object if you have a deep structure, so not worth using it when we run after performance when using memoize

**Comment by davidchambers** [comment]
The Ramda implementation relies on unique string representations. Without string representations a very different approach would be necessary, as we couldn't use a vanilla object as a lookup table.

I suggest writing your own `memoize` function, @alex3165, and sharing it here.

**Comment by tycho01** [comment]
If you may assume object identity equality as well, consider the [Lodash](https://lodash.com/docs/4.17.4#memoize) one (esp. with `_.memoize.Cache = WeakMap;`). That might be performant enough to also make it viable to start memoizing results of smaller pure functions.

**Comment by Bradcomp** [comment]
I think it would be reasonable to add a `memoizeBy` function with the following signature:

`(* -> String) -> (* -> a) -> (* -> a)`

Then it would be up to the user to provide a unique string representation for the arguments.

**Comment by CrossEye** [comment]
@Bradcomp:

That works.  If someone wants to push for this I wouldn't fight it.  But...

I find I care very little about `memoize`.  I'll probably be kicking myself the next time my CRUD service is in desperate need of fast access to the Fibonacci numbers, but there you have it.

**Comment by Bradcomp** [comment]
@CrossEye I think I've used it exactly once in production code, so I'm right there with you, although I might get double or even triple the usage out of it if serialization was more efficient 😜 

`memoizeBy` seems like a much easier solution than allowing for arbitrary equality comparisons, which would require a whole different approach as @davidchambers mentioned.
