### ISSUE TITLE
`range` doesn't support negative values

### ISSUE THREAD

**Issue by TimonVS** [ramda/ramda#2109]
The `range` function doesn't support negative values. This isn't a big deal because you can easily create your own function (`const negativeRange = pipe(range, map(negate))`). 
I'm not sure if the `range` function should support negative values, but otherwise it might be worth mentioning it in the documentation.

**Comment by davidchambers** [comment]
In my view `range` *does* support negative values:

```javascript
> R.range(-5, 0)
[-5, -4, -3, -2, -1]

> R.reverse(R.range(-5, 0))
[-1, -2, -3, -4, -5]
```

Perhaps the point you're really making is that `range` has a hard-coded "step" of `1`. We could provide a more general function:

```javascript
> R.rangeBy(-1, -1, -6)
[-1, -2, -3, -4, -5]

> R.rangeBy(2, 0, 10)
[0, 2, 4, 6, 8]
```

**Comment by TimonVS** [comment]
Oops, I should've provided an example of course. This doesn't work: `R.range(-1, -5)` (I expected to get `[-1, -2.., -4, -5]`). But in hindsight, it makes an awful lot of sense `range` doesn't work that way.

**Comment by CrossEye** [comment]
I wrote a post about this a long time ago: http://fr.umio.us/ranging-near-and-far/
