### ISSUE TITLE
R.type for async functions is incorrect 

### ISSUE THREAD

**Issue by iamstarkov** [ramda/ramda#2110]
```
~
λ node --version
v7.7.1
~
λ node
> Object.prototype.toString.call(async function(){})
'[object AsyncFunction]'

> R.type(async function() {})
Object
```

**Comment by iamstarkov** [comment]
Related https://github.com/angular/jasminewd/pull/87

**Comment by CrossEye** [comment]
Looking at the [code for type][ty] I don't understand how this happens.

I don't have Node 7 on the ancient machine I'm using at the moment.  Soon I should have my more modern machine working again.  

But this just confuses me.  `'[object AsyncFunction]'.slice(8, -1); //=> 'AsyncFunction'`.  :confused: 


  [ty]: https://github.com/ramda/ramda/blob/master/src/type.js#L30

**Comment by alexeyraspopov** [comment]
Worth mentioning, the same applicable to generators:

```
~
λ node
> Object.prototype.toString.call(function* gen(){})
'[object GeneratorFunction]'
```

**Comment by iamstarkov** [comment]
@CrossEye yeah, you are right and im wrong. /cc @alexeyraspopov 
![screen shot 2017-03-03 at 11 18 03](https://cloud.githubusercontent.com/assets/559321/23547326/160e755c-0003-11e7-91a1-94d0bcdbee95.png)

**Comment by CrossEye** [comment]
Ok, well I'm glad to know that the code still acts the way I thought it was supposed to.  Too often it doesn't.  :smiling_imp:
