### ISSUE TITLE
R.isNaN?

### ISSUE THREAD

**Issue by necrower** [ramda/ramda#2113]
R.is(Number, NaN) returns TRUE, so we could have a isNaN function.

**Comment by CrossEye** [comment]
You could just do 

    const isNaN = (x) => x !== x;

if you want something different from the built-in `isNaN` feature.

**Comment by necrower** [comment]
I thought that later. thx

**Comment by svozza** [comment]
You can also do:

```js
const isNaN = R.equals(NaN);
```

**Comment by davidchambers** [comment]
[`Number.isNaN`][1] is best of all, I would say.


[1]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by CrossEye** [comment]
> [`Number.isNaN`][1] is best of all, I would say.

Agreed, so long as you don't have to support IE.

[1]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by gurre** [comment]
I was really shocked that NaN is not covered by `isNil` or `isEmpty`.

**Comment by CrossEye** [comment]
I would never expect it to be covered by `isNil`, which is about the two nil values in JS, `null` and `undefined`.  But it's an interesting question for `isEmpty`.  I'm not sure what I think about this, but I would love to hear the arguments in favor.

**Comment by gurre** [comment]
I see a few broad options:

 1. Add NaN to isEmpty
 2. Add a new predicate `isNaN`
 3. Add a new predicates for `isTruthy` and `isFalsy` which includes NaN.

**Comment by CrossEye** [comment]
1. Seems to be worth discussing.  In fact it was the only idea I had considered.

2. Already exists in `Number.isNaN`

3. `isTruthy` seems perfectly covered by `Boolean`, and `isFalsy` is trivial: `complement(Boolean)`.

**Comment by davidchambers** [comment]
`R.isEmpty(x)` is sugar for `R.equals(x, R.empty(x))`. `Number` does not satisfy the requirements of [Monoid][1], therefore applying `R.isEmpty` to `NaN` is nonsensical.


[1]: https://github.com/fantasyland/fantasy-land#monoid

**Comment by CrossEye** [comment]
It seems a little strong to say that `Number`  does not satisfy [Monoid][mo].  There are obvious Monoids on numbers such as *addition*/**0** and *multiplication*/**1**.  You can even make ones with **NaN** if you like<sup>*</sup>, but unlike with other common monoidal types there is none that seems to be an obvious default.

I'm not sure that is a strong enough reason to say that we cannot define an empty value for `Number`.

I could define a monoid on Strings with an empty value of **'foo'**.  Does that mean that we should not use `''` as the empty value for them?

I'm not ready to argue that we *should* do this.  But I don't think there is anything in the Monoid laws that would prevent us from choosing a default empty number.  If we were to do that, `NaN` is the obvious candidate.

The biggest reason I see for avoiding this is that for the other types where Ramda directly defines `empty`, it also defines `concat`, but we don't try to define a `concat` for `Number`.

(Actually, that makes me think... is there a commonly recognized typeclass for types with an `empty` that works as expected but without necessarily adding associativity?  Research for another day.)


----------
<sup>*</sup> For instance: 
```js
// concat :: Number -> Number -> Number
const concat = (a) => (b) => Number.isNaN(b) ? a : b

// empty :: Number -> Number
const empty = (a) => NaN

// associativity: for Numbers a, b, c none of which are equal to NaN 
concat(concat(a, b), c)       == concat(b, c)     ==  c  == concat(a, c)     == concat(a, concat(b, c))
concat(concat(a, b), NaN)     == concat(b, NaN)   ==  b  == concat(a, b)     == concat(a, concat(b, NaN))
concat(concat(a, NaN), c)     == concat(a, c)     ==  c  == concat(a, c)     == concat(a, concat(NaN, c))
concat(concat(a, NaN), NaN))  == concat(a, NaN)   ==  a  == concat(a, NaN)   == concat(a, concat(NaN, NaN))
concat(concat(NaN, b), c)     == concat(b, c)     ==  c  == concat(NaN, c)   == concat(NaN, concat(b, c))
concat(concat(NaN, b), NaN)   == concat(b, NaN)   ==  b  == concat(NaN, b)   == concat(NaN, concat(b, NaN))
concat(concat(NaN, NaN, c)    == concat(NaN, c)   ==  c  == concat(NaN, c)   == concat(NaN, concat(NaN, c))
concat(concat(NaN, NaN) NaN)) == concat(NaN, NaN) == NaN == concat(NaN, NaN) == concat(NaN, concat(NaN, NaN))

// right identity
concat(a, NaN) == a

// left identity
concat(NaN, a) == a
```


  [mo]: https://github.com/fantasyland/fantasy-land#monoid

**Comment by davidchambers** [comment]
Allow me to update my comment, Scott.

> `Number` does not satisfy the requirements of [Monoid][1] <ins>according to [`R.empty`][2]</ins>, therefore applying `R.isEmpty` to `NaN` is nonsensical.

```javascript
> R.empty(42)
(function() { return arguments; }())
```

I'm not arguing that `Number` *cannot* satisfy Monoid; I'm stating that it does not according to `R.empty`, a function which claims to operate on a value of any type which satisfies Monoid.


[1]: https://github.com/fantasyland/fantasy-land#monoid
[2]: http://ramdajs.com/0.25.0/docs/#empty

**Comment by CrossEye** [comment]
@davidchambers: OK, but the question is whether it *should*.  Presumably if we were to "fix" this issue, it would be by adding `Number` to `empty` and using `NaN` as the empty value.  I certainly wouldn't want this to alter `isEmpty`'s dependence on `empty`.

**Comment by davidchambers** [comment]
> Presumably if we were to "fix" this issue, it would be by adding `Number` to `empty` and using `NaN` as the empty value.

This would imply updating `R.concat` so that `R.concat(NaN, 42)` and `R.concat(42, NaN)` both evaluate to `42` (in accordance with the left and right identity laws). I'm strongly against this "fix". ;)

**Comment by CrossEye** [comment]
> (Actually, that makes me think... is there a commonly recognized typeclass for types with an `empty` that works as expected but without necessarily being associative? Research for another day.)

Even if there is not, `empty` and `isEmpty` do not have to imply `Semigroup`.  The function `empty` asks the question "What is the empty value of the TypeRef?"  To me, the question comes down to whether want to declare an empty numeric value.  I'm not at all certain that we do, but if we do, I see nothing better than `NaN`.

**Comment by davidchambers** [comment]
I'm sorry, Scott, I haven't spent enough time reading your comments. I now see that you put forward `concat(NaN, a) == a` and `concat(a, NaN) == a` above. I won't argue with this, as it is lawful, but I think usefulness should also be evaluated.

**Comment by CrossEye** [comment]
Hey, no apologies needed.  I wasn't even suggesting that.  I am not interested in trying to define `concat` for numbers.  But that won't stop me from considering `empty` for them.

And it's funny, because I seem to be promoting a change I don't really think is a great idea.  I think it's possible, and maybe reasonable, but it doesn't seem at all necessary.
