### ISSUE TITLE
Looks like the icon fonts are down on the docs

### ISSUE THREAD

**Issue by chrbala** [ramda/ramda#2114]
Just an FYI.

![screen shot 2017-03-05 at 11 13 20 am](https://cloud.githubusercontent.com/assets/6834804/23590445/dcaf0810-0194-11e7-85f9-75e0115017ee.png)

**Comment by CrossEye** [comment]
Seems to be working for me.  Perhaps it was just a temporary glitch.  Could you test again?

**Comment by chrbala** [comment]
Yeah, it's still happening. I tried in other browsers just in case, but the fonts still don't load.

**Comment by CrossEye** [comment]
hmm, I cleared cached and it was working fine.  Can anyone else report either success or failure? 

And @chrbala: can you hit the font URL directly? http://ramdajs.com/fonts/glyphicons-halflings-regular.woff2

**Comment by chrbala** [comment]
I'm now inclined to think there's something up with my computer. They still don't load when I tether my computer to my phone, but work fine on the phone itself.

Interestingly, when I try loading the page in Firefox (mac), I get a 'The connection was reset' error.

**Comment by CrossEye** [comment]
Ok, let us know if this persists.  If it's your local infrastructure, we'll call in the SWAT team.  With a fist full of monads, they can solve anything!  :smile:

**Comment by chrbala** [comment]
thanks haha – I'm mostly curious at this point to know what the heck is going on. I can load the font directly on my mac, so it's a real mystery. It doesn't prevent me from reading the docs either, so ¯\_(ツ)_/¯
