### ISSUE TITLE
Transducers violate composition laws

### ISSUE THREAD

**Issue by barretron** [ramda/ramda#2124]
While playing around with transducers (based on the example in the docs), I came across what seems to be a bug in the transducer implementation. I looked around to see if this is expected behavior, but couldn't find anything.

Given: 
```JavaScript
var transducer = compose(map(multiply(2)), map(inc), take(4))
```

Both `R.transduce` and `t.transduce` (from `transducers-js`) perform the multiplication before addition.

The transducer works as expected when the `map`s are factored out, e.g.:
```JavaScript
var transducer = compose(map(compose(multiply(2), inc)), take(4))
```

The full tests I ran are below, including a test of `transducers-js` behavior. The `log` function is just a helper to show when each function is called. Note how the functions are logged in the correct order consistently despite the incorrect result.

```JavaScript
var R = require('ramda')

var log = function (msg, fn) {
  var that = this
  return function () {
    console.log(msg)
    return fn.apply(that, arguments)
  }
}
var concat = R.flip(R.append)
var numbers = [1, 2, 3, 4]

var t1 = R.compose(
    log('multiply', R.map(R.multiply(2))),
    log('inc', R.map(R.inc)),
    log('take', R.take(4))
)

// correct
console.log(t1(numbers))
// > take
// > inc
// > multiply
// > [4, 6, 8, 10]

// incorrect
console.log(R.transduce(t1, concat, [], numbers))
// > take
// > inc
// > multiply
// > [3, 5, 7, 9]

var t2 = R.compose(
    log('inc + multiply', R.map(R.compose(R.multiply(2), R.inc)),
    log('take', R.take(4))
)

// correct
console.log(t2(numbers))
// > take
// > inc + multiply
// > [4, 6, 8, 10]

// correct
console.log(R.transduce(t2, concat, [], numbers))
// > take
// > inc + multiply
// > [4, 6, 8, 10]

// testing with transducers-js

var t = require('transducers-js')

var t3 = t.comp(
    log('multiply', t.map(R.multiply(2))),
    log('inc', t.map(R.inc)),
    log('take', t.take(4))
)

// (can't call transducers here directly)

// incorrect
console.log(t.transduce(t3, concat, [], numbers))
// > take
// > inc
// > multiply
// > [3, 5, 7, 9]
```

**Comment by kurtmilam** [comment]
I might be wrong, but I think [this comment](https://github.com/ramda/ramda/issues/1288#issuecomment-122609438) may shed some light on the situation.

I don't think this has anything to do with transducers. Rather, I think it has to do with `compose`ing `map`s.

**Comment by CrossEye** [comment]
Unless I misunderstand the question, this is the expected behavior.  Transducers compose in the seeming opposite order of plain functions.  Two good explanations:

  * https://www.youtube.com/watch?v=6mTbuzafcII#t=1531 (Rich Hickey video, time set to discussion on compostion order)
  * http://isaaccambron.com/blog/2014/12/13/transducer-composition.html (Article specifically on Transducer composition, code in Clojure.)

**Comment by barretron** [comment]
Thanks @CrossEye, I had no idea! The links were very helpful. Closing this issue.
