### ISSUE TITLE
Mention toString implementation of R.memoize

### ISSUE THREAD

**Issue by jvorcak** [ramda/ramda#2125]
Hi,

Looking at the source code, I've noticed that `R.memoize` uses `toString` to memoize the result.
See related issue - https://github.com/ramda/ramda/issues/1384

Would it be an idea to mention this in a documentation? I assume that programmers are using this function in a hope it will increase performance, but in a lots of scenarios, it can actually decrease perf. because `toString` is rather expensive operation. Since people don't check the source code every time, it would be useful to have it stated in a docs I think

I'll be happy to create a PR if the issue is accepted.

**Comment by CrossEye** [comment]
I generally don't like for our docs to mention implementation details, as I feel that documentation and unit tests are a more long-term contract than the implementations themselves.

But this might the right place for an exception.  This function is [significantly slower][fm] than many of its counterparts.  It would be nice to also explain *why* that is so.  This has to do with some limitations of `JSON.stringify`, but for the life of me I can't remember what they were.  @davidchambers, any insights?

  [fm]: https://community.risingstack.com/the-worlds-fastest-javascript-memoization-library/

**Comment by davidchambers** [comment]
See [CANON][1] for some of JSON's flaws. Here's one flaw:

```javascript
> JSON.stringify(new Date(0))
'"1970-01-01T00:00:00.000Z"'

> JSON.stringify('1970-01-01T00:00:00.000Z')
'"1970-01-01T00:00:00.000Z"'
```

We could use CANON in the implementation of `memoize`, but JSON is no good.


[1]: https://github.com/davidchambers/CANON

**Comment by CrossEye** [comment]
Thanks, @davidchambers.

@jvorcak: does explaining some of this in the docs make sense?

**Comment by kedashoe** [comment]
I feel like we should deprecate current memoize and provide a version which takes a user function. As @jvorcak says, if you are memoizing you are trying to help with performance, and this default implementation will hardly ever (never?) beat a specific user supplied function. Very often I would imagine the user function will be simple, eg `prop('id')`.

**Comment by svozza** [comment]
Or maybe just add a function called `memoizeWith` rather than breaking everyone's code. ;)

**Comment by jvorcak** [comment]
@CrossEye it does, but I like where this discussion is going. Providing `memoizeWith` function would be awesome. How would that work, would Ramda have some prepared memoization functions one could use? cc @svozza

**Comment by CrossEye** [comment]
@jvorcak: I agree.  I like the idea too.  I would expect that Ramda would not supply any functions except for the current one in the plain `memoize`.  But you might easily build one out of Ramda function, such as @kedashoe's `prop('id')`.

**Comment by svozza** [comment]
I'm happy to do a PR for this given that I've sorted of generated the extra work.

**Comment by CrossEye** [comment]
@svozza: that would be great.  I would hope this should be a relatively straightforward one.

**Comment by jvorcak** [comment]
@svozza great, if you by chance won't have time for this in a near future just ping me. I'd also love to contribute in a future and this seems like a good way to start.

**Comment by svozza** [comment]
No probs, I should be able to do it tomorrow but if not I'll leave a message here. :)
