### ISSUE TITLE
R.remove() in v0.23.0 when used with an index of -1 returns array with the last item removed

### ISSUE THREAD

**Issue by seantarogers** [ramda/ramda#2129]
Hi,

In v 0.22.1 you would get the following output when using a -1 index for R.Remove
R.remove(-1, 1, [1,2,3]); //=> [1,2,3]
http://ramdajs.com/repl/?v=0.22.1#?R.remove%28-1%2C%201%2C%20%5B1%2C2%2C3%5D%29%3B%0A%0A%0A

Now in v 0.23.0 when using an index of -1 the final item is removed
R.remove(-1, 1, [1,2,3]); //=> [1,2]
http://ramdajs.com/repl/?v=0.23.0#?R.remove%28-1%2C%203%2C%20%5B1%2C2%2C3%5D%29%3B%0A%0A

Wondered if it was intentional as I couldn't see it in the upgrade guide?

Thanks

**Comment by CrossEye** [comment]
At a guess, this is fallout from 21d6a29, although not an unwelcome one.

**Comment by YannisMarios** [comment]
Does reject work on an array of objects?

```
let array = [
  {
    a: 1
  },
  {
    b: 2
  },
  {
    c: 3
  }
];
```
let removed = remove(0, array);
console.log(removed) = undefined
