### ISSUE TITLE
.mergeWith behavior inconsistent with docs, key included after returning undefined

### ISSUE THREAD

**Issue by jeffinmotion** [ramda/ramda#2132]
Docs for .mergeWith read:

> Creates a new object with the own properties of the two provided objects. If a key exists in both objects, the provided function is applied to the values associated with the key in each object, with the result being used as the value associated with the key in the returned object. _The key will be excluded from the returned object if the resulting value is undefined_. (emphasis mine) 

```
R.mergeWith((l, r) => { return r; }, { a: 'a', b: 'b' }, { b: undefined }) // { a: 'a', b: undefined }

// expecting { a: 'a' }
```

Wondering what's incorrect here, the behavior, the docs, or my comprehension of the docs :)

**Comment by kedashoe** [comment]
Ya something seems wrong here. What do you guys think? I'm not sure why `undefined` would be treated specially, and as the current code does not appear to actually do what the docs say, maybe best thing is to update the docs to remove that sentence?

**Comment by asaf-romano** [comment]
I'm fine either way.

**Comment by kedashoe** [comment]
Would you like to open a PR to update the docs to remove that sentence, @jeffinmotion ?

**Comment by jeffinmotion** [comment]
@kedashoe was just about to and it looks like the changed was made with the work for #1867 — thanks!
