### ISSUE TITLE
`propOr`/`pathOr` inconsistency

### ISSUE THREAD

**Issue by alex-deas** [ramda/ramda#2136]
```javascript
propOr('bar', 'foo')({ foo: undefined }); // -> undefined
pathOr('bar', ['foo'])({ a: undefined });  // -> 'bar'
```
Both `propOr` and `pathOr` define themselves as returning the value if it is non-null; else the 'or' value. These two functions should consistently handle `undefined`

**Comment by briancaine** [comment]
I don't think this is an inconsistency.

The documentation for `propOr` reads:
> If the given, non-null object has an own property with the specified name, returns the value of that property. Otherwise returns the provided default value.

And for `pathOr`:
> If the given, non-null object has a value at the given path, returns the value at that path. Otherwise returns the provided default value.

The non-null part refers to the object itself, not the value being fetched.

**Comment by alex-deas** [comment]
:man_facepalming: now I just feel silly...

**Comment by briancaine** [comment]
We've all been there.

**Comment by zachlysobey** [comment]
Not sure if I should piggy-back on this or open a new issue. I get that it behaves the way the docs say it does, but I am not convinced that this is the *right* approach.

To restate the issue:

`propOr` uses the default if it fails a `hasOwnValue` check, but `pathOr` returns the default if the path lookup returns a *falsy* value.

I find this to be confusing and inconsistent.

```
const foo = { bar: null }
R.propOr('hello', 'bar', foo) // null
R.pathOr('hello', ['bar'], foo) // 'hello'
```

The similarity in the fn names would make you think intuitively that they behave the same way. 

Personally, I think I prefer the way this is handled in R.pathOr because it seems more intuitive. Its like using `R.path(...)` __OR__ (`||`) the default.

```
R.path(['bar'], foo) || 'hello'
```

(Note: its not immediately clear to me how/if this relates to https://github.com/ramda/ramda/issues/1712, apologies if this is a dupe)

**Comment by buzzdecafe** [comment]
> `propOr` returns the default if it fails a hasOwnValue check, but `pathOr` returns the default if the path lookup returns a falsy value.

:+1: for pointing this out. I'd love to see consistent behavior across the `*Or` functions. This looks pretty gross to me.

**Comment by kurtmilam** [comment]
While I agree that the implementation of `propOr` and `pathOr` should be consistent, I prefer the `hasOwnProperty` behavior of `propOr`. It's my understanding that these functions are meant to allow the developer to provide default values for cases in which no values exist on the specified property or path.

The `hasOwnProperty` implementation also seems truer to the documentation of both functions:
> [pathOr](http://ramdajs.com/docs/#pathOr): If the given, non-null object has a value at the given path, returns the value at that path. Otherwise returns the provided default value.
> [propOr](http://ramdajs.com/docs/#propOr): If the given, non-null object has an own property with the specified name, returns the value of that property. Otherwise returns the provided default value.

**Comment by Bradcomp** [comment]
> `pathOr` returns the default if the path lookup returns a falsy value.

To be fair, `pathOr` returns the default for `null`, `undefined`, and `NaN`, not for all falsy values. While I agree that it's still somewhat problematic, it's not as egregious as I initially thought...

**Comment by zachlysobey** [comment]
@Bradcomp oops. Sorry for the misinformation.

@kurtmilam yea, I can definitely see that point of view too. Either approach would work IMO.

**Comment by zachlysobey** [comment]
Honestly, while I think these *fooOr* functions are really useful, I'm starting to think maybe they should not be a part of Ramda.

 - The Ramda API surface  area is already pretty darn big
 - Its relatively easy to implement these functions ourselves
 - I know its still a `0.x` release, I don't think we can change the behavior of either of these functions now without breaking peoples code in subtle ways. I can see this causing real problems for people who use this in production (like me). Deprecating the functions and encouraging people to just define their own would be safer

**Comment by davidchambers** [comment]
It's worth noting that Sanctuary doesn't need any `*Or` functions because the return values of functions such as [`S.head`][1] and [`S.get`][2] are never ambiguous.


[1]: https://sanctuary.js.org/#head
[2]: https://sanctuary.js.org/#get

**Comment by nfantone** [comment]
Came here for @zachlysobey comment. Was about to open a new issue for it. This bit me today:

```js
> propOr('foo', 'b', { b: null });
null

> pathOr('foo', ['a', 'b'], { a : { b: null } });
'foo'
```

I believe we should either level their behaviour or amend the docs of `pathOr`:

> If the given, non-null object has a value at the given path, returns the value at that path. 

...to read:

> If the given, non-null object has a **non-null** value at the given path, returns the value at that path.

**Comment by nfantone** [comment]
I can put together a PR if anyone is interested and/or we agree on what should be modified. (cc. @buzzdecafe @Bradcomp). And apologies for reviving a dead issue.

**Comment by alex-deas** [comment]
@zachlysobey I understand that it's pretty simple to create the functionality of `*Or` but I feel they lower the bar for entry and make Ramda more accessible by providing a single function which solves a everyday problem. That's a good thing imo.

I agree that the implication of breaking peoples code should be taken into consideration. It has been properly documented and we need to assume that there are people who rely on this behavior.

One way of achieving consistency in the future would be to just have `propOr(x, k)` as an alias for `pathOr(x, [k])`. Then align on a single definition of when the default should be called. I'm in favor of the existing `pathOr` definition personally as I feel the only real use case for the distinction of only checking for an own-property is to differentiate between all of `{ x: undefined }`, `{}` and `{x: 1}`. I can't personally think of a single case when I've wanted to do that. If I did want to though, it can be sufficiently covered by `pathSatisfies`.

**Comment by nfantone** [comment]
@alex-deas 

> I agree that the implication of breaking peoples code should be taken into consideration.

We wouldn't. This would belong in a new major release (`1.0.0`?).

> It has been properly documented and we need to assume that there are people who rely on this behavior.

It hasn't, though. At least not for `pathOr`. See my previous comment.

**Comment by foxbunny** [comment]
> It hasn't, though. At least not for pathOr. See my previous comment.

It hasn't in both cases, actually.

**Comment by CrossEye** [comment]
@nfantone: I'm going to try very hard to get a release out this weekend.  That should be part of it.
