### ISSUE TITLE
Use Array (Pair a b) in unfold

### ISSUE THREAD

**Issue by sadasant** [ramda/ramda#2138]
Quoting @davidchambers:
> Since we don't have the option of using Maybe (Pair a b), we'd need to use Array (Pair a b) and assume that the array's length will either be zero or one ([] or [['foo', 42]], say).

Perhaps in this form?

```
module.exports = _curry2(function unfold(fn, seed) {
  var pair = fn(seed);
  var result = [];
  while (pair && pair[0] && pair[0].length === 2) {
    result[result.length] = pair[0][0];
    pair = fn(pair[0][1]);
  }
  return result;
});
```

**Comment by davidchambers** [comment]
Rather than `pair && pair[0] && pair[0].length === 2` the check should be `pair.length === 1`.

**Comment by sadasant** [comment]
What if the user returns `['oops']` ?

**Comment by davidchambers** [comment]
> What if the user returns `['oops']` ?

We likely fail with an unhelpful type error. That's the Ramda way. *Suppressing* the error would be far worse, though.

Also, `pair` is a misleading name. I suggest `maybePair` instead.

**Comment by sadasant** [comment]
Aye captain!

**Comment by CrossEye** [comment]
After weeks away, I'm back.  And this is fascinating.  I finally understand the original posts on this.  And I really like updating `unfold`.
