### ISSUE TITLE
Repeat like replicateM in Haskell?

### ISSUE THREAD

**Issue by TheGrandmother** [ramda/ramda#2145]
Is there a function like `replicateM` from Haskell in ramda?

What I mean by this is a function, lets call it `repeatFun` for now, that behaves like this:
```
repeatFun(Math.random, 3) //=> [0.156, 0.789, 0.456]
```

If there is not such a function that is a feature I would gladly try to write one.

**Comment by kedashoe** [comment]
You could use [R.times](http://ramdajs.com/docs/#times)

```js
R.times(i => Math.random(), 3) //=> [0.156, 0.789, 0.456]
```

Hmm.. we should have `@see`s for `times`/`repeat`

**Comment by TheGrandmother** [comment]
I didn't see that, putting the `@see` seems like a good idea.

But I still think its a bit redundant to have to use the `times` function.
In many situations one may not care about the index of the element.

I used:
```
R.map((_e) => foo, R.repeat(null, n));
```
To achieve the same result.

Is a function like this worth adding?
Or would it just be redundant?
I can try writing one.

**Comment by kedashoe** [comment]
> I can try writing one.

Sure, I think a PR is worth discussing :)

**Comment by TheGrandmother** [comment]
Will make a desperate attempt later :)
I'm not exactly a skilled JS programmer :p

**Comment by CrossEye** [comment]
Discussion should continue in the pull request: #2146.
