### ISSUE TITLE
keys and equals make me in trouble

### ISSUE THREAD

**Issue by zyf0330** [ramda/ramda#2148]
I have this
```
let id = 1;
let obj = {};
obj[id] = null;
R.keys(obj) // ['1']
R.equals(R.keys(obj)[0], id) // false
```
What should I do? Please provide an `equals` equals `==`.

**Comment by davidchambers** [comment]
@zyf0330, you could define this function yourself:

```javascript
//    approximatelyEqual :: Any -> Any -> Boolean
const approximatelyEqual = R.curry((a, b) => a == b);
```

I don't think this function belongs in Ramda itself.

**Comment by buzzdecafe** [comment]
> I don't think this function belongs in Ramda itself.

Agree +:100: . If there is one thing we definitely **do not** want to support, it is type coercion.

**Comment by zyf0330** [comment]
Thanks, I am aware of it now.
