### ISSUE TITLE
document `R.replace` function option as replacement param

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#2149]
[`R.replace`](http://ramdajs.com/docs/#replace) just wraps [`String.prototype.replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace), which for its second param allows either a string or a function. So Ramda does as well here, but currently only the string case is documented (type signature, example).

**Comment by buzzdecafe** [comment]
ugh, that `R.replace` API is already pretty bad, blurring it up even further does not feel good:

`replace :: RegExp|String → String → String → String`

becomes

`replace :: RegExp|String → String | ((String, String..., Number, String) → String) → String → String`

😢  

If I think about this from the POV of "what API do I want?" I absolutely do not want the second one. So I guess I'd rather no mention that the implementation is simply a wrapper on `String.prototype.replace`; I'd rather see a different function for the function case, and even then, I'd rather change the API of the function to something simpler.

**Comment by tycho01** [comment]
Yeah, I'll agree it isn't optimized for legible type signature. What TypeScript type notation tends to do is overloading by showing the options separately... but then perhaps we'd be at four here.

I actually got in there assuming the function to be what it said, then wanted to make a `replaceBy` using a function instead, checked the source, and only then realized this one already did handle both cases... functionality-wise, I didn't quite mind that Ramda already did everything I could ask for, but discoverability was a bit problematic.

I mean, technically we could alias the same function as `replaceBy` and document them under different type signatures... :clown_face:

**Comment by tycho01** [comment]
That said, overloading / generality is obviously a broader thing in Ramda.
This may also affect functions that take both arrays as well as objects for input, among which:

[a|dis]soc(Path), path|prop(Eq|Or|Is|Satisfies), keys, values(In), props, pluck, forEach(ObjIndexed), has(In), invert(Obj),  keys(In), merge(All). Oh, and everything involving lenses.

Heck, the number of Ramda functions with trivial type signatures can be counted on one hand really! :smile_cat:
