### ISSUE TITLE
mergeWith and mergeWithKey do not exclude keys

### ISSUE THREAD

**Issue by m59peacemaker** [ramda/ramda#2150]
From the docs for `mergeWith` and `mergeWithKey`:

>  The key will be excluded from the returned object if the resulting value is undefined

I would expect the following to result in an empty object.

```js
mergeWith((a, b) => {}, { a: 1 }, { a: 2 })
// expected => {}
// actual => { a: undefined }
```

For what it's worth, I'm not sure it's good behavior to drop keys like that instead of mapping over and dropping keys with `undefined` afterward. I just noticed the behavior differs from the docs.

**Comment by kedashoe** [comment]
Yep, good catch. This has been resolved, see https://github.com/ramda/ramda/issues/2132#issuecomment-291864549, docs will be fixed in next release

**Comment by m59peacemaker** [comment]
Oh neat. That didn't show up in my search for `mergeWith` in the issues.
