### ISSUE TITLE
Understanding source code 

### ISSUE THREAD

**Issue by yesprasad** [ramda/ramda#2153]
I am a bit new to JS and am trying to learn the source code of Ramda here. However, I see in the currying file a variable _b at https://github.com/ramda/ramda/blob/master/src/internal/_curry2.js#L20
` : _curry1(function(_b) { return fn(a, _b); });`
who is filling this value? or how is this getting filled? Please help me improve my JS abilities.

**Comment by davidchambers** [comment]
Here's a simpler example:

```javascript
//  curry2 :: ((a, b) -> c) -> a -> b -> c
function curry2(f) {
  return function(x) {
    return function(y) {
      return f(x, y);
    };
  };
}

curry2(function(x, y) { return x + y; })(2)(2);
// => 4
```

`x` and `y` are simply provided as arguments (one at a time).
