### ISSUE TITLE
Math inverse

### ISSUE THREAD

**Issue by anthonydugois** [ramda/ramda#2154]
The `negate` function makes it possible to obtain the additive inverse of a number. How about adding a similar function, but for multiplicative inverse?

```js
// inverse :: Number -> Number

inverse(10); //=> 0.1
```

**Comment by buzzdecafe** [comment]
the notion of "invertability" opens up [some interesting possibilities](https://en.wikipedia.org/wiki/Group_(mathematics)) ....

Might be interesting to explore invertability in a more general way, with `negate` and multiplicative inverse being special cases?

**Comment by CrossEye** [comment]
> How about adding a similar function, but for multiplicative inverse?

What would these return?:

    inverse(0);
    inverse(-0)
    inverse(Infinity)
    inverse(-Infinity)
    inverse(NaN)

**Comment by TheLudd** [comment]
> What would these return?:
> 
> inverse(0);
> inverse(-0)
> inverse(Infinity)
> inverse(-Infinity)
> inverse(NaN)

`Infinity`
`-Infinity`
`0`
`-0`
`NaN`

... and I base this on how maths work in JavaScript.

**Comment by anthonydugois** [comment]
@buzzdecafe Makes sense to me, but I don't know algebra theory enough to be sure it's feasible. How would you implement a more general way to find the inverse of an unknown group? For example, finding the inverse of a matrix requires a lot more work than finding the additive inverse of an integer. And there are others problems: how do you represent the group (there are lots of ways to represent a matrix with JS)?

**Comment by buzzdecafe** [comment]
> How would you implement a more general way to find the inverse of an unknown group?

I don't think we can. Pretty sure that problem can't be solved in a general way. But as we do with e.g. `map`/Functor, we can support users who wanna work with groups, and rely on them to ensure their group is lawful. But maybe i am just dreaming

**Comment by semmel** [comment]
Mathematically I am familiar with the "inverse" of functions f<sup>-1</sup>(f(x)) = x and matrices not of numbers. So I would not like naming `x => 1 / x` "inverse".

In the case of `R.negate` or the proposed `R.multiplicativeInverse` f is its own inverse i.e. a [involutory function](https://en.wikipedia.org/wiki/Involution_(mathematics)) f<sup>-1</sup> = f; f(f(x)) = x. Of which there are many: All which are symmetric w.r.t.the 45°-axis. So for example f<sub>d</sub>(x) = 1 / (x -d) + d. Just picking `1 / x` and `-x` for Ramda would seem arbitrary?

For Linear Algebra and vector calculus I'd rather pick a specialized library than Ramda...

**Comment by buzzdecafe** [comment]
> Just picking 1 / x and -x for Ramda would seem arbitrary?

Agreed. `x => 1/x` might better be called `reciprocal`. 

> For Linear Algebra and vector calculus I'd rather pick a specialized library than Ramda...

... and a different language than JavaScript

**Comment by anthonydugois** [comment]
Yup, looks good to me.

**Comment by buzzdecafe** [comment]
in that case, `reciprocal = R.divide(1);`

**Comment by CrossEye** [comment]
Sorry, trying to catch up.

>> What would these return?:
>> 
>>    inverse(0);

> `Infinity`

but then this function is not actually a multiplicative inverse. `0 * inverse(0)` does not equal `1`.  This might not be a problem, since there is no complete multiplicative inverse.  But I feel as though it's a convoluted call.  If we want to name `divide(1)` as `reciprocal`/`inverse`, that's one thing.  But if we're claiming that this is a multiplicative inverse, then we may have gone too far.

**Comment by dmitriz** [comment]
>Mathematically I am familiar with the "inverse" of functions f^-1(f(x)) = x and matrices too. So I would not like naming x => 1 / x "inverse".

Both are inverses for different group operations. First for the composition of invertible functions, and second for the multiplication.

Which becomes a problem if `inverse` is used without clearly specifying the operation.
`reciprocal` would be unambiguous.

>0 * inverse(0)
That is because JS forcefully extends the division breaking the maths law: `(1/0)*0 != 1`
Still formally `(a/b)*b == a` holds for all valid expressions, but we cannot expect it to hold for the invalid ones.

**Comment by andry-baka** [comment]
I think this is not required since `reciprocal` is just as simple as `R.divide(1)`, as per explanation from @buzzdecafe.
This is also already explained on Ramda example:
```
var reciprocal = R.divide(1);
reciprocal(4);   //=> 0.25
```
