### ISSUE TITLE
Is there a plan for a new release?

### ISSUE THREAD

**Issue by mattgrande** [ramda/ramda#2157]
I'm just wondering what the timeline is for v0.24.0 or v1, whichever is the next target? Is there a schedule/timeline? Is there anything I can do to help?

**Comment by CrossEye** [comment]
There is no plan. I would like to go through and close out some issues before we create a release.  Perhaps next weekend we can cut a release.

**Comment by sikhote** [comment]
A beta release on NPM would be helpful for easier access & testing. Thanks!
