### ISSUE TITLE
Rename identity to id

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#2159]
The name is too long for such a frequently needed function IMO. 

`x => x` is shorter :(

I would also consider renaming of arithmetic functions to make them more similar to `R.add`.

1) `R.identity` -> `R.id`
2) `R.subtract` -> `R.sub`
3) `R.multiply` -> `R.mul`
4) `R.divide` -> `R.div`

In this way they will still pop up in search.

Of course I propose to alias current versions until 1.0.

Who feels the same?

**Comment by buzzdecafe** [comment]
I'd be happy with `R.I` for identity, but `id` is good too, i certainly prefer it to `identity`

**Comment by CrossEye** [comment]
:+1: on `identity -> id`.

But :-1: on the others.  Everyone knows what operation will be performed by "subtract".  But "sub" could represent "substitute", "subscript", or others.  And "div" might be an HTML node.  While I can't think of anything that might be confused with "mul", I'd prefer the consistency of the full words.    And again, anyone who reads "multiply" will surely understand what is meant.

And for those who want shorter names,

```js
import {multiply as mul, divide as div, subtract as sub} from 'ramda'
```

... or some other variant.

**Comment by dmitriz** [comment]
I find `identity` more expressive, as a matter of personal opinion.
`id` is often used as "id" of an object, in this case

```js
var ramda = require('ramda')
var id = ramda.id
```

would feel like the "id" of the `ramda` object :)

**Comment by anthonydugois** [comment]
I agree with @dmitriz, in my mind `id` is connoted to objects. I think it might be confusing.

**Comment by asaf-romano** [comment]
👎  ``id`` is quite hostile to users installing Ramda into the global scope one way or the other. The chance of shadowing is very high. From my own experience, there are currently very few functions for which the issues comes up at all (``path`` in node environments being the only prominent example, really).

**Comment by ivan-kleshnin** [comment]
> I agree with @dmitriz, in my mind id is connoted to objects. I think it might be confusing.

Only if you import that as `let {id} = require("ramda")`. And this is the style many people start with but everyone ends with `R.whatever` anyway ;) Because managing lists with tens of functions in every module is a huge waste of time. And `R.id` is diamond clear.

I tried so hard to stick with plain names because I thought `R.map` etc. were ugly. 
It was a matter of a single day to force myself change my habits and enjoy that in the end.

**Comment by svozza** [comment]
If we're going to bring back `R.I` can we rename `R.always` to `R.K`? :wink:

**Comment by davidchambers** [comment]
`R.always` is not the K combinator (whose type is `a -> b -> a`).

**Comment by svozza** [comment]
Maybe I'll 'fix' that if I ever finish #1609.

**Comment by buzzdecafe** [comment]
$0.02: happy to have `K :: a -> b -> a` as well as `always :: a -> () -> a`.

**Comment by CrossEye** [comment]
I'm personally not happy with the single-character names.  Even `T` and `F` feel wrong to me.

**Comment by davidchambers** [comment]
> Even `T` and `F` feel wrong to me.

Why "even"?

**Comment by CrossEye** [comment]
Those feel the most natural. I've seen them in many environments.  I think most native English speakers would have little doubt about them when viewed as a pair. 

And yet I still would prefer more explicit names.

**Comment by davidchambers** [comment]
> And yet I still would prefer more explicit names.

What could be more explicit than `R.always(true)` and `R.always(false)`? ;)
