### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#2161]
Does anyone else find this a bit disconcerting?

https://goo.gl/coH47H

**Comment by kedashoe** [comment]
That `toString` is blowing up the dependency graph for `concat`? Do you think we should get rid of it and display a less helpful error message? I don't currently have a strong opinion one way or the other.

**Comment by CrossEye** [comment]
LOL.  I hadn't chased it down at all, just saw how large and convoluted the whole graph was.

This is **much** better:

    https://goo.gl/rMed9O

I do think we need to consider removing `toString` here.  Using individual functions or custom builds becomes very bloated.  But I'm glad to realize that the complexity is all around that and not spread throughout.

**Comment by mattgrande** [comment]
Hey @CrossEye - How did you generate the mermaid syntax?

**Comment by CrossEye** [comment]
Manually.  I thought it was going to be just a few nodes... and then I got stubborn!  ;-)

I'm sure it would be easy to hook together a dependency tree walker, but this was a one-off.

**Comment by davidchambers** [comment]
#1938 is the solution, I think. :)

By adding one simple, well-tested dependency we can remove vast swathes of internal Ramda code, including `_equals` and `_toString`.

**Comment by CrossEye** [comment]
> By adding one simple, well-tested dependency we can remove vast swathes of internal Ramda code, including `_equals` and `_toString`.

That only helps if the code in sanctuary-type-classes is significantly simpler than that in Ramda.  My concern was about the function-level dependencies.  I don't care for these purposes what library contains those functions.

While I'm quite happy with Ramda's lack of external dependencies, I'm by no means wedded to it.  But if we're going to add one, we must be keeping in mind the convenience of the *users* of the library.  One of the issues that comes up regularly is the ability to import only what you want from Ramda, either through `const concat = require('ramda/src/concat)` (or es6 import) or through a custom build.  If building any Ramda function then required importing an entire second library, I think we may be doing a disservice to our users.

**Comment by davidchambers** [comment]
Ramda is not currently suitable for users who wish to import one or two functions without bringing in many bytes. If a user wishes to use `R.map`, but no other Ramda functions, she must still bring in:

  - the various `fantasy-land/map` implementations for built-in types;
  - the machinery for dispatching to `fantasy-land/map` and `map`;
  - the machinery for transducers; and
  - the machinery for currying (including support for placeholders).

We cannot please everyone. At some point, @CrossEye, you should decide what is it you really want Ramda to be. If the goal is to provide hundreds of lightweight, dependency-free functions, we should remove support for placeholders, transducers, and Fantasy Land dispatching.

**Comment by buzzdecafe** [comment]
@CrossEye :
> ... we must be keeping in mind the convenience of the users of the library.

I disagree. Maybe you must. I certainly did not start work on this lib in order to provide "convenience" for "users", whatever "convenient" means -- or for that matter whoever "users" are. To me it was/is a research project. If "users" wanna come along, then *caveat emptor* to them. 

Catering to an ill-defined, highly mercurial notion of convenience is not what I signed up for. That is not a problem I find interesting to solve, especially in my free time.

**Comment by CrossEye** [comment]
@buzzdecafe:

I think I spoke poorly.  But good API design is exactly that which keeps the needs of the user ahead of those of the implementor.  I would not use public opinion to decide *what* should be included, but if we are to support something, I believe we should do it in the way most useful to those using the library.  After all, we're primarily users of the libraries not writers of it.

**Comment by CrossEye** [comment]
> If a user wishes to use `R.map`, but no other Ramda functions, she must still bring in: [ ... ]

That yields this graph:

https://goo.gl/cqO2h6

It's a little bigger than I expected, but doesn't seem outrageous.  This is after all one of the functions in the library doing the most.  It's not like that initial graph for the relatively simple `concat`.

> At some point, @CrossEye, you should decide what is it you really want Ramda to be.

I refuse the nomination.  :wink:  If we cannot decide as a group, we should fold up and go home.

**Comment by teehemkay** [comment]
As someone who's rediscovered the joy of programming using JavaScript thanks to Ramda, please allow me to voice my $0.02. 

As far as I'm concerned the single thing that makes Ramda _useable_ as FP library is the fact that it is so beautifully modular.

This  makes it relatively easy (with the use of build tool plugins such as [rollup-plugin-ramda](https://github.com/idmitriev/rollup-plugin-ramda) and [babel-plugin-ramda](https://github.com/megawac/babel-plugin-ramda)) to only include (with some caveats, see @davidchambers' remark above ) those bits of code that are actually used in the app which is more and more a rather stringent requirement especially for mobile developments.

So IMHO, #1958 seems like it would be a fantastic solution **BUT**, it would be really great if `sanctuary-type-classes` could adopt the same modularity as Ramda or maybe achieve the same results (minimal builds) by other means (e.g. maybe via `/* #__PURE__ */` annotations supported by [uglifyjs2](https://github.com/mishoo/UglifyJS2#compressor-options) (see `side_effects` compressor option)

**Comment by teehemkay** [comment]
Please also see #1977 for additional context.
