### ISSUE TITLE
Ramda Universe

### ISSUE THREAD

**Issue by ivan-kleshnin** [ramda/ramda#2162]
Right now I'm working on a public (CC license) course on Ramda. Well, not exactly a course but rather a series of practical tasks kind-of like www.github.com/workshopper/learnyounode but much more elaborate. 

The work is about to finish. Any recommended place where I could post a link to it? 
Wiki? index.md? Something else?

Check the drafts here:
http://courses.paqmind.com/fp-beginner/1.map/challenges/1.1.qz/

This is just a demo. Domain name, URL and texts will likely change. 

---

**As the title implies it's a general question about the politics on the community-driven Ramda-based projects. I use my project only as an example.**

**Comment by CrossEye** [comment]
I'd say that for now the wiki is the right place, perhaps a new section right after Articles, something like "Learning".  When it's complete and in its more permanent home, we can bring up putting it on the README.

**Comment by buzzdecafe** [comment]
This is pretty cool! I may crib some of your examples for a presentation I am giving, if you don't mind

**Comment by ivan-kleshnin** [comment]
> I'd say that for now the wiki is the right place, perhaps a new section right after Articles, something like "Learning". When it's complete and in its more permanent home, we can bring up putting it on the README.

Thank you! I'll update wiki soon. Closing the issue for now...

> This is pretty cool! I may crib some of your examples for a presentation I am giving, if you don't mind

@buzzdecafe sure!

**Comment by CrossEye** [comment]
This is very nice.  I only had a few minutes to look at it this morning, but I just looked at it more closely.  I'm impressed!

**Comment by ivan-kleshnin** [comment]
> This is very nice. I only had a few minutes to look at it this morning, but I just looked at it more closely. I'm impressed!

Thank you again @CrossEye I really appreciate that. In a few words I'm making a platform uniquely based on different challenge types with explained solutions. FreeCodeCamp / HackerRank / etc. are all about algorithms and automated tests. Very limited in scope. I intentionally decided to sacrifice all that fancy runtime environment stuff for a novel (or classic?!) *write-compare-repeat* approach. I will also give a lot of refactoring tasks (someone has to do that at last).
