### ISSUE TITLE
`toString` is not idempotent for strings?

### ISSUE THREAD

**Issue by dmitriz** [ramda/ramda#2165]
Somewhat surprisingly:

```js
R.toString('abc'); //=> "\"abc\""
'abc'.toString(); //=> "abc"
```

Is it intended?

http://ramdajs.com/repl/?v=0.23.0#?toString%28%27abc%27%29%3B%20%2F%2F%3D%3E%20%27%22abc%22%27%0A

**Comment by davidchambers** [comment]
Yes, this is intended. `'123'` and `123` should have different string representations. Also:

```javascript
> R.equals(eval(R.toString('123')), '123')
true

> R.equals(eval(R.toString(123)), 123)
true
```

**Comment by dmitriz** [comment]
Oh I see, I've thought that kind of method is also called `inspect`.

`toString` reads like the JS traditional type conversion to String,
which is also identical with Lodash:

https://lodash.com/docs/4.17.4#toString

I understand that Ramda is different from Lodash,
but still find it unfortunate that methods with the same name produce different results.

**Comment by CrossEye** [comment]
> I understand that Ramda is different from Lodash,
> but still find it unfortunate that methods with the same name produce different results.

I really don't think that should influence us very much.  If Ramda were an API clone of lodash, itself an API clone of Underscore -- or even if Ramda were an all-but-parameter-order API clone -- it wouldn't offer much.  Ramda's focus is on simplicity, and on standard FP concerns.  That it overlaps in functionality with Underscore/lodash is not surprising.  And we will take some inspiration from them.  But our API design is our own..

I like the rule David mentioned: it makes for a much more robust `toString`.

However, as discussed briefly in #2161, the implementation makes for some pretty coupled functions: https://goo.gl/coH47H.  We may have to look at that.

**Comment by dmitriz** [comment]
>Ramda's focus is on simplicity, and on standard FP concerns.

I certainly can see the usefulness of that method,
just find it confusing to carry the same name as Lodash but doing different thing.
And worse, it is both similar and different, making it even more confusing.
So it goes against both Lodash and the JavaScript native type conversion.
It might be just me of course.

It really does what @DrBoolean calls the `inpect` method in https://egghead.io/lessons/javascript-refactoring-imperative-code-to-a-single-composed-expression-using-box, see [the code here](https://github.com/dmitriz/functional-examples/blob/master/examples/01-box.js#L21). 
Calling it `inspect` in line with that course would imo remove all the confusion.

Look forward to the simplified implementation, hopefully that confusion point can also be addressed along the way.

**Comment by semmel** [comment]
I agree with @dmitriz that the name `R.toString()` is surprising and I would expect it to be idempotent for Strings.

For a beginner the similarities between JavaScript's functional torso in Array's `map`, `filter`, `reduce` , etc. and Ramda's `R.map`, `R.filter`, `R.reduce` are obvious. Then there are functions like `R.test` and `R.match` which just dispatch to JS. Fine. However, except for Numbers, `R.toString` has  nothing to do with JavaScript's `toString()`.

I still have not encountered a situation there `R.toString()` could come in handy:
* for dictionary Objects and Arrays it's `JSON.stringify()`,
* for Strings it's something like `String.quote()` (or `JSON.stringify()`),
* for Numbers it's `Number.toString(10)` (or `JSON.stringify()`),
* for Date it produces the JS code of a date constructor call in a string

Idempotence:
The JS `toString()` method is often used to ensure that a variable is of type String if one is in doubt whether it is a Number or already a String. Applying `R.toString()` a number of times results in multiply quoted strings.

**Comment by davidchambers** [comment]
@semmel, it sounds as though `String` is the function you're after. ;)

`R.toString` is very helpful when writing a REPL or generating documentation. In these contexts it is not acceptable for `0` and `"0"`, `/x/` and `"/x/"`, etc. to have colliding string representations.

**Comment by semmel** [comment]
>  it sounds as though String is the function you're after. ;)

Yes indeed! Thank you @davidchambers !
Forever learning...
Semmel

**Comment by dmitriz** [comment]
If display for inspection is the primary intent of this function, would not some descriptive names like `inspect` or `stringify` better reflect it and be more intuitive to the consumer?

With `toString` it reads like one from the large group of the `toNumber`, `toWhatever`,..., with the intent to convert to the mentioned type. Even more broadly, you use names like `toJSON` or `toHTML` when converting something. 

The intent with `to...` methods feels always to convert to the right type, so being idempotent is very natural and easy to understand.

Any other intent I would try to make look different and more explicit in the name, to avoid precisely that confusion. Basically anything that does not look like type conversion. The "String" here is really the mean to inspect that you would switch e.g. for more elaborate loggers if going more sophisticated :) 

> it sounds as though String is the function you're after. ;)

If you mean the JS native one, here is what it does:

```js
String(['a',1])
// => "a,1"
String({a:1})
// => "[object Object]"
```

Also note 
> String generics are non-standard, deprecated and will get removed near future.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String
https://www.fxsitecompat.com/en-CA/docs/2016/non-standard-array-string-generics-have-been-deprecated/


Perhaps the current `R.toString` does it better for the job ;)

```js
toString({'a':1})
// => "{\"a\": 1}"
```

or `'{"a": 1}'` would be even easier to read in REPL:

```js
"{\"a\": {\"a\": 1}, \"b\": [1]}"
```
vs
```js
'{"a": {"a": 1}, "b": [1]}'
```

**Comment by davidchambers** [comment]
I think you're confused, @dmitriz.

```javascript
> "{\"a\": {\"a\": 1}, \"b\": [1]}" === '{"a": {"a": 1}, "b": [1]}'
true
```

It's the same value in both cases. ;)

**Comment by dmitriz** [comment]
@davidchambers 
You are right, I should have said it better.
I mean the way it looks in the Ramda REPL.

**Comment by davidchambers** [comment]
Are you suggesting that `R.toString(s :: String)` should use single or double quotes depending on the value of `s`?

**Comment by dmitriz** [comment]
@davidchambers 
Single quotes outside, double inside, like in my examples.
Or double outside, single inside, slightly less noisy but less JSON compliant.
Is it possible?

**Comment by davidchambers** [comment]
In this case, @dmitriz, we have `R.toString(R.toString({a: {a: 1}, b: [1]}))`.

`R.toString` *could* choose between single and double quotes in order to minimize escaping, but I don't like this option because:

  - it's less consistent; and
  - it only helps in some cases (any string containing both `'` and `"` will still require escaping).

**Comment by skirankumar7** [comment]
is **JSON.Stringify()** and **R.toString()** (ramda) both methods are equal ?

**Comment by CrossEye** [comment]
@skirankumar7: No. Among other differences:

```js
> JSON.stringify  ({a: 1, b: () =>{}})
{"a":1} 

> R.toString      ({a: 1, b: () =>{}})
{"a": 1, "b": () =>{}}
```

**Comment by dmitriz** [comment]
I presume you mean the string (not the object)
```js
'{"a": 1, "b": () =>{}}'
```

The name ".toString" might well be confusing to newcomers,
it seems more of an "inspect" method for internal debugging purposes
rather than something useful for your production code.
Also the description

> Returns the string representation of the given value.

seems to imply there is someting universal about "the string representation",
while this is really just one way to inspect the value,
perhaps "the" should be "a" here? :)

**Comment by skirankumar7** [comment]
> @skirankumar7: No. Among other differences:
> 
> ```js
> > JSON.stringify  ({a: 1, b: () =>{}})
> {"a":1} 
> 
> > R.toString      ({a: 1, b: () =>{}})
> {"a": 1, "b": () =>{}}
> ```

**why the function ( ()=> {} )  is omitted in JSON.stringify method and why R.toString is not?**

**Comment by davidchambers** [comment]
We could deprecate `R.toString` and suggest that users migrate to [`show`][1].


[1]: https://github.com/sanctuary-js/sanctuary-show

**Comment by CrossEye** [comment]
@skirankumar7:

> why the function ( ()=> {} ) is omitted in JSON.stringify method and why R.toString is not?

JSON is a data-transfer format.  It was created to allow inter-operation between different systems.  It was based off the JS literals format, but significantly restricted so that most any modern language can easily convert its representation into native types.  That means that it is restricted pretty well to strings, numbers, booleans, objects, and arrays.  It would be very difficult to find a way to pass functions, especially in a language like JS where a function comes complete with its closure, but also there are modern languages that don't even have first-class functions.

Ramda, on the other hand, has no such restrictions.  `toString` is simply an attempt to give as useful an output as possible to represent the input.

@dmitriz:
> I presume you mean the string (not the object)

Yes, of course.  I'll edit that comment.

> perhaps "the" should be "a" here? :)

Sure, but I don't find this very important.
