### ISSUE TITLE
Iterable Lenses

### ISSUE THREAD

**Issue by eecolella** [ramda/ramda#2167]
Hi All,

what do you think about something like that:

var lensIterable = R.lensPath(['x', '*', 'y']);
var lensIterable = R.lensPath(['x', R.map, 'y']); // if we want more power
R.over(lensIterable, R.negate, {x: [{y: 2, z: 3}, {y: 4, z: 5}]});
//=> {x: [{y: -2, z: 3}, {y: -4, z: 5}]}

would you accept a PR with this?

**Comment by buzzdecafe** [comment]
this appears readily achievable by composition, and so seems to me to be sugar. I'm not sure how useful this sugar is. Here is the composed version, which I already find pretty clear:

```js
const xlens = R.lens(R.prop('x'), R.assoc('x'));
const ylens = R.lens(R.prop('y'), R.assoc('y'));

over(xlens, map(over(ylens, negate)), {x: [{y: 2, z: 3}, {y: 4, z: 5}]});
```

https://goo.gl/bQYYNy

**Comment by jackfirth** [comment]
This is no longer a lens, it's a Traversal. If it were a lens it would allow you to change the number of elements in the intermediary array as well.

**Comment by CrossEye** [comment]
What would be the proposed behavior here?

```js
const lensIterable = R.lensPath(['x', '*', 'y']);
const list = [{y: 2, z: 3}, {y: 4, z: 5}]
list['*'] = {y: 6, z: 7};
R.over(lensIterable, R.negate, {x: list}); //=> ???
```

**Comment by eecolella** [comment]
@CrossEye 
It's an edge case but good point! Let's forget about the asterisks

@jackfirth 
I'm a very beginner of FP, I trust you that the right name is Traversal

@buzzdecafe 
That was a simple example and it was already the double of the code with a lot less expressivity.

It can actually become something:

```javascript
    const traversalK = R.traversalPath['x', R.map, 'y', R.filter(R.isNil)), R.map, 'z', R.head, 'k']
    R.over(traversalK, R.negate)(data)
```

**Comment by buzzdecafe** [comment]
> That was a simple example and it was already the double of the code with a lot less expressivity.

My point is that the end result is readily available by composition of existing functions. And "expressivity" is in the eye of the beholder.

>```js
>const traversalK = R.traversalPath['x', R.map, 'y', R.filter(R.isNil)), R.map, 'z', R.head, 'k']
>R.over(traversalK, R.negate)(data)
>```

I'm sorry but I have no idea what that example means? The type of `traversalPath` is incomprehensible to me. Lists should be of a single type, not an ad hoc stew of String, Function, etc.

**Comment by jackfirth** [comment]
A traversal is a lens that can view multiple targets in a streaming fashion instead of just one. In relation to other optical concepts:

- A Prism is dual to a lens; it views one form of a value that could exist in multiple forms (like a `Maybe` or `Either` type), as opposed to one subpart of a value with multiple parts.
- An Isomorphism is an equivalence between two types with conversion functions, and as such can function as both a lens and a prism.
- A Traversal is a generalization of lenses (which traverse exactly one element) and prisms (which traverse zero or one elements). All lenses and prisms are also traversals, and composing a lens with a prism yields a traversal.

Traversals are very powerful for expressing logic like "for all monsters less than 200 distance units away from the player, subtract their health by 10". They could be useful in Ramda, but would be a much better fit for the [`ramda-lens`](https://github.com/ramda/ramda-lens) package than Ramda proper.

**Comment by kurtmilam** [comment]
You may wish to take a look at the excellent, Ramda-friendly [partial.lenses](https://github.com/calmm-js/partial.lenses) library (11.6KB minified).

Here's the initial example with `partial.lenses`:
```javascript
L.modify( [ 'x', L.elems, 'y' ]
        , R.negate
        , { x: [ { y: 2, z: 3 }, { y: 4, z: 5 } ] }
        )
// -> { x: [ { y: -2, z: 3 }, { y: -4, z: 5 } ] }
```
[See it in action in the REPL](https://calmm-js.github.io/partial.lenses/playground.html#DIOgtg9gJglgZgTwBQAIDaKDkAPTAaFUAUwBsiwBnAzBTFAXQCgCAlEAOyIHMBDAFyLMUAbxTYAXOhEoEkgEwEAXpIDMKAL4FRslABYlkgKwaGGxgEogA).

The library also offers isomorphisms (`L.iso` for things like `L.iso( R.fromPairs, R.toPairs )` and `L.iso( decodeURIComponent, encodeURIComponent )` ), as well as a number of powerful abstractions.

Visit the [calmm-js room on Gitter](https://gitter.im/calmm-js/chat) if you'd like to ask specific questions about `partial.lenses`.

**Comment by polytypic** [comment]
FYI, about the Partial Lenses bundle size.  Partial lenses supports Rollup and uses the newish `/*#__PURE__*/` annotations of UglifyJS.  This means that when using a modern bundler and UglifyJS, dead-code elimination is effective on the Partial Lenses library code and the resulting bundle will only include what you use.  I have been previously fairly conservative about adding more features to the library, but I plan to add more features, which will increase the prebuilt bundle size, but will not increase bundle sizes when using a modern bundler and UglifyJS.  I would highly recommend also making Ramda compatible with Rollup and use those `/*#__PURE__*/` annotations supported by UglifyJS.  This way Rollup users would automatically only get what they use from Ramda.

**Comment by buzzdecafe** [comment]
I am surprised by this API: `L.modify( [ 'x', L.elems, 'y' ] ...` 

Looks like it is using the array as a JS imitation of a 3-tuple, and behaving polymorphically based on the type of the middle element?
https://github.com/calmm-js/partial.lenses#L-modify

**Comment by kurtmilam** [comment]
@buzzdecafe I used the shorthand syntax in my original post. Here's the full syntax:
```javascript
L.modify( L.compose( L.prop( 'x' ), L.elems, L.prop( 'y' ) )
         , R.negate
         , { x: [ { y: 2, z: 3 }, { y: 4, z: 5 } ] }
        )
```
[REPL](https://calmm-js.github.io/partial.lenses/playground.html#DIOgtg9gJglgZgTwBQAJQGMJgA4QM4Cmqo2AThNqgOQAeVKAlADRogEA2BYeLJ5lKKgnoNGAKBYAlEADsCAcwCGAFwISUAbxQ0AXCgDamlAj0AmFgC89AZhQBfFlpMoALJb0BWeygC69sQxAA)

In the shorthand syntax, one can compose an optic by passing in an array of optics, where a string like 'x' is short for `L.prop( 'x' )` (and an int like 1 is shorthand for `L.index( 1 )`. In the shorthand notation, the list can contain as many optics as you'd like, and the 'middle' or second one is not in any way special.
