### ISSUE TITLE
R.ap can't work sometimes

### ISSUE THREAD

**Issue by rainke** [ramda/ramda#2169]
` R.ap([R.ap([R.multiply(2), R.add(3)])], [1,2,3])`
 I want to get [2, 4, 6, 4, 5, 6], but the result is weird.

**Comment by davidchambers** [comment]
Here you go:

```javascript
> R.ap([R.multiply(2), R.add(3)], [1, 2, 3])
[2, 4, 6, 4, 5, 6]
```
