### ISSUE TITLE
Pluck multiple props

### ISSUE THREAD

**Issue by elaich** [ramda/ramda#2172]
Hello,

This is more a question than an issue, I didn't find any built in function in Ramda to pluck more than a property, but I guess there is an easy functional way to do it, and I can't see it.

Someone ?

**Comment by Tapsi** [comment]
Pretty naive solution, but the first one I thought of. :)

```
// object to read
const obj = {
  a: 1,
  b: 2,
  c: 3
}

// unzip the object to [[key, value]*]
const entries = R.toPairs(obj)

// function takes a list of keys and maps the keys to euqalizers which will be used to check the 
// left value in a pair
const readProperties =  props => 
  R.filter(
    R.compose(
      R.anyPass( R.map(key => R.equals(key), props) ), 
      R.head))

readProperties(["a", "b"])(entries)  // [["a", 1], ["b", 2]]
```

[See in Ramda REPL](http://ramdajs.com/repl/?v=0.23.0#?const%20obj%20%3D%20%7B%0A%20%20a%3A%201%2C%0A%20%20b%3A%202%2C%0A%20%20c%3A%203%0A%7D%0A%0Aconst%20entries%20%3D%20R.toPairs%28obj%29%0Aconst%20readProperties%20%3D%20%20props%20%3D%3E%20%0A%20%20R.filter%28%0A%20%20%20%20R.compose%28%0A%20%20%20%20%20%20R.anyPass%28%20R.map%28key%20%3D%3E%20R.equals%28key%29%2C%20props%29%20%29%2C%20%0A%20%20%20%20%20%20R.head%29%29%0A%0AreadProperties%28%5B%22a%22%2C%20%22b%22%5D%29%28entries%29)

Hope this helps to find a proper solution. :)

**Comment by davidchambers** [comment]
You may find [`R.pick`][1] or [`R.pickAll`][2] useful.


[1]: http://ramdajs.com/docs/#pick
[2]: http://ramdajs.com/docs/#pickAll

**Comment by Tapsi** [comment]
@davidchambers ok this makes my approach even more stupid. The function 'pickAll' looks perfect for the use-case. 👍

**Comment by ercpereda** [comment]
```javascript
// pluckAll :: [k] → [{k: v}] → [{k: v}]
const pluckAll = props => R.map(R.pickAll(props))
```
