### ISSUE TITLE
add function for merging multiple objects

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#218]
This is a very common pattern in the code I've written lately:

``` javascript
_.extend({}, options, {foo: 42})
```

Since [_.extend](http://underscorejs.org/#extend) mutates its first argument, it's often necessary to pass in an empty object in first position. Perhaps Ramda could provide a similar function:

``` javascript
R.merge(options, {foo: 42})
```

This would be a pure function, unlike _.extend. If there's interest in this function, I'll put together a pull request. :)

**Comment by chadams** [comment]
why is this not in the documentation?

**Comment by davidchambers** [comment]
The function's name has changed. See [`R.merge`][1] and [`R.mergeAll`][2].


[1]: http://ramdajs.com/docs/#merge
[2]: http://ramdajs.com/docs/#mergeAll

**Comment by wonderdogone** [comment]
_.extend({} is different in that it on and object and R.mergeAll works with array
