### ISSUE TITLE
The ramdajs.com/docs/'s Filter input is not smart enough for filtering what I really want.

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2196]
When searching `o` in Filter input of `ramdajs.com/docs/`, what I really want is `R.o`, but it is not on top of the result list. Can anyone optimize the filter algorithm?

**Comment by buzzdecafe** [comment]
this issue probably belongs in the ramda.github.io repo

**Comment by adispring** [comment]
yes, I'll open a new issue in ramda.github.io.
