### ISSUE TITLE
Built-in enumerate function

### ISSUE THREAD

**Issue by jvorcak** [ramda/ramda#2199]
Hi,

I know that you're trying the keep Ramda rather small and avoid introducing functions that can be composed of other functions.

However, have you been considering to introduce something like `enumerate`?
I've tried to search in the issue tracker, but haven't found any existing issue regarding this matter.

In Python it's built-in https://docs.python.org/2/library/functions.html#enumerate
For now I'm using
```
const enumerate = R.addIndex(R.map)((x, y) => [y, x])
enumerate(['hello', 'world'])
```
But I use it in various projects and need to copy&paste this solution all the time. That's why I wanted to ask whether something like this could be considered as it could help others as well.

**Comment by semmel** [comment]
What? Ramda gets enumerations? That would be great! 😲 
```
enum Color = {   RED,  GREEN, BLUE };
```
But wait - it's not the [Enumerations](http://2ality.com/2016/01/enumify.html) as I understand it. It's more like an *Indexation* thing is it not?

**Comment by buzzdecafe** [comment]
> It's more like an Indexation thing is it not?

Looks that way to me as well. For "enums" I'd recommend using a sum type anyways. More powerful, and ought to work with ramda. There are plenty of candidates out there: [daggy](https://github.com/fantasyland/daggy), [union-type](https://github.com/paldepind/union-type), [S](https://github.com/sanctuary-js/sanctuary), etc.

**Comment by jvorcak** [comment]
@semmel @buzzdecafe exactly, I meant `enumerate` as an indexation function. (Sorry I come from Python, I should have made myself more clear).

**Comment by CrossEye** [comment]
`toPairs` is already close to this...

**Comment by uriva** [comment]
I think you want `addIndex(map)`
