### ISSUE TITLE
Idea: `mapToObject` (or whatever name)

### ISSUE THREAD

**Issue by mAAdhaTTah** [ramda/ramda#2204]
I've been doing a bunch of data transformations of this form:

```js
const dataMapper = state => ({
    someProp: getSomePropFromState(state)
})
```

and was thinking a ramda function that produces these data mapper functions would be helpful. The  idea would be something like this:

```js
R.mapToObject({
   someProp: getSomePropFromState
});
```

Which would return a function that, for each property, calls the provided function with any provided arguments and returns an object where each property equals the return value of the property's functions.

It's a bit similar to `evolve`, but doesn't require the input & output to match. I don't know if something like this already exists, or is doable with current ramda functions, but maybe it would be a useful addition to the library? If it is, I'd be interested in putting it together myself and opening a PR for it.

**Comment by kurtmilam** [comment]
Yours sounds like it might be a good use-case for lenses. If Ramda's lenses don't offer everything you need, out of the box, I recommend that you take a look at the excellent [partial.lenses](https://github.com/calmm-js/partial.lenses) library. partial.lenses is more or less developed with the express purpose of making it easy to work with state objects in an immutable and speedy way.

You can also drop by [this gitter room](https://gitter.im/calmm-js/chat) to ask any questions you might have about partial.lenses or look for help writing lenses that solve specific problems.

**Comment by mAAdhaTTah** [comment]
@kurtmilam While I don't think I'll pull in another library for this just yet, I appreciate the link cuz that group has some other things that could be really useful (I'm a heavy user of Kefir, so the Kefir-related libs look really helpful).

**Comment by kurtmilam** [comment]
I understand the desire to forego adding a new library. On the other hand, I think partial.lenses is worth a look if you're having to do a lot of work with complex data structures.

Regarding your initial question, have you taken a look at Ramda's [`applySpec`](http://ramdajs.com/docs/#applySpec)? It may get you closer to what you're looking for.

**Comment by mAAdhaTTah** [comment]
@kurtmilam Actually `applySpec` is exactly what I'm looking for. Thanks!
