### ISSUE TITLE
why are they two 'transduce' compound function 's result different ?  is that bug?

### ISSUE THREAD

**Issue by shinefine** [ramda/ramda#2206]
`
//*****node npm install ramda 0.24.1*****

var R= require('ramda');

var arr = [1, 2, 3, 4];
var append = function (newArr, x) {
    newArr.push(x);
    return newArr;
};

var plusOne = x => x + 1;
var square = x => x * x;

var func1 = R.compose(R.map(square),R.map(plusOne))
var func2 =R.map(R.compose(square,plusOne))

//******  func1 and func2 's result are same，correct！*******

console.log(func1(arr)); //--> [4,9,16,25]
console.log(func2(arr)); //--> [4,9,16,25]

var bug_func =R.transduce(func1,append, []); 
var bug_func2 =R.transduce(func2,append, []); 

//*******  bug_func and bug_func2 's result are different，why? ******

console.log(bug_func(arr))  //-->[2,5,10,17]
console.log(bug_func2(arr)) //-->[4,9,16,25]

`

**Comment by kedashoe** [comment]
Function composition [evaluates backwards](http://isaaccambron.com/blog/2014/12/13/transducer-composition.html) when run via `transduce`. So `var func1 = R.compose(R.map(square),R.map(plusOne))` when transduced evaluates `square` first, then `plusOne`. For func2, it doesn't know what functions are inside your `map` so it evaluates the same either way.

**Comment by shinefine** [comment]
that means transduce will change  function composition evaluates order with compose ?

**Comment by kedashoe** [comment]
> that means transduce will change function composition evaluates order with compose ?

That is correct. Note this is not particular to ramda, that is standard behavior with transducers (https://clojure.org/reference/transducers).

**Comment by shinefine** [comment]
Thank you @kedashoe.
