### ISSUE TITLE
Set function changing Array to object

### ISSUE THREAD

**Issue by roopkt** [ramda/ramda#2207]
Hi all,
When I use R.set method to update nested property inside an array. 
It is changing array into object. Am I doing something wrong ? 
What should I do to not change the datatype of my initial state ?

Here is plunker with same code: https://plnkr.co/edit/K1Tcui?p=preview

```
var initial = {x: [{y: 2, z: 3}, {y: 4, z: 5}]};
console.log(initial.x.length);

var xHeadYLens = R.lensPath(['x', 0, 'y']);

var afterSet = R.set(xHeadYLens, 1,initial);
console.log(afterSet.x.length); // undefined why its chaing data type array to object ?;
//=> {"x":{"0":{"y":1,"z":3},"1":{"y":4,"z":5}}}

**Comment by roopkt** [comment]
I saw that this is fixed in version 0.24.1 Any idea when this version is going to be released ?

**Comment by mattgrande** [comment]
v0.24.1 is already released; It should just be a matter of updating your `package.json` file.

**Comment by roopkt** [comment]
Thanks for clarification . I will update it.
I am sorry, I installed Ramda in pluker app and by default it put 0.22
reference therefore I thought 0.24 is not yet published!
