### ISSUE TITLE
Using ramda documentation in ramda-ruby

### ISSUE THREAD

**Issue by lazebny** [ramda/ramda#2213]
Hey, 
 
I am trying to adopt Ramda principles in ruby https://github.com/lazebny/ramda-ruby.
Currently I have a link to RamdaJs documentation in README. In general function behaviors in ruby are very similar with javascript but ruby has some specific things and would be good to rewrite this places in docs. 

My question: is it ok to reuse Ramda documentation in ramda-ruby? I mean create a separate resource like github page, YARD, RDoc or Wiki. 

Big thanks to contributors team for this awesome library.

**Comment by davidchambers** [comment]
I've no problem with this, but I'll leave it to @CrossEye and @buzzdecafe to decide.

**Comment by buzzdecafe** [comment]
Sounds good to me

**Comment by CrossEye** [comment]
Sorry, just getting back to Ramda, after some time away.  I'm glad to hear of your Ruby library.  I also agree that it's fine to use Ramda docs.  But we don't have any particular mechanism to inform you of changes.  Obviously our [Release Notes][rn] can serve this purpose, but they happen at the end of the change cycle, just as we release a new version.

  [rn]: https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22

**Comment by lazebny** [comment]
@CrossEye thank you for a green light. I think that Release Notes is a good way to be informed. Currently i released ramda-ruby 0.12 version which should be closest to ramdajs 0.12 version. So time gap between Ramda Js releases isn't critical for me now.
