### ISSUE TITLE
eqPaths like eqProps?

### ISSUE THREAD

**Issue by bijoythomas** [ramda/ramda#2214]
Does it make sense to add eqPaths? I'm using it currently like so

```
const eqPaths = idx => useWith(equals, [path(idx), path(idx)])
```

**Comment by asaf-romano** [comment]
``eqBy`` is quite enough, IMO. ``eqBy(path(["a", "b"]))`` is declarative and not too verbose. Demo: https://goo.gl/Png6SL

**Comment by bijoythomas** [comment]
Thank you. That is indeed much better.
