### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by ivanzusko** [ramda/ramda#2215]
Hello, people!

Some time ago I've got tired to switch tabs between [ramdajs.com/docs](ramdajs.com/docs). And today I had some free time and decide to do small Chrome Extension([Ramda Docs](https://chrome.google.com/webstore/detail/ramda-docs/pglohphegkildojgiggolcilcinhdacg?authuser=1)) for the sake of easier access to documentation.
I did think at the moment of coding and publishing, but now I understand, that it would be better to ask your permission to use Ramda logo for extension... But better later than never, so I'm asking your permission.
Otherwise, I'll change it on somthing another.

Cheers!

**Comment by kedashoe** [comment]
:+1:

**Comment by ivanzusko** [comment]
@kedashoe thanx 😀

**Comment by CrossEye** [comment]
As it says in [Ramda's README][rm]

> Thanks to [J. C. Phillipps](http://www.jcphillipps.com) for the Ramda logo. Ramda logo artwork &copy; 2014 J. C. Phillipps. Licensed Creative Commons [CC BY-NC-SA 3.0](http://creativecommons.org/licenses/by-nc-sa/3.0/).

So long as you abide by the license, you should be fine.

And I look forward to trying out your extension!

  [rm]: https://github.com/ramda/ramda#acknowledgements

**Comment by ivanzusko** [comment]
@CrossEye thank you! Would be great to here any feedback :+1:

**Comment by mrosata** [comment]
@iamstarkov Before the topic closes I just wanted to say, I think this extensions sounds like a great idea. I just installed it and gave it a spin.

I'm actually going to make a PR if that's ok, to fix the header links.

**Comment by ivanzusko** [comment]
@mrosata thank you very much! :+1:

**Comment by iamstarkov** [comment]
@mrosata hm?

**Comment by CrossEye** [comment]
Added this to the [Tools Section][ts] of the [Wiki][wi].

  [ts]: https://github.com/ramda/ramda/wiki#tools
  [wi]: https://github.com/ramda/ramda/wiki
