### ISSUE TITLE
Is type constraints expressed in order?

### ISSUE THREAD

**Issue by coodoo** [ramda/ramda#2220]
Take following for example:

```
weirdFunc :: (Functor f, Monoid b, Ord b) => (a -> b) -> f a -> f b
```

Does it mean the first b in`(a -> b)` must be a `Monoid`, and the 2nd b in `f b` must be an `Ord`?

or no matter the order that b appears, as long as it's either `Monoid` or `Ord` it will be fine?

Thanks.

**Comment by davidchambers** [comment]
The order in which the type-class constraints are listed is inconsequential.

> as long as [`b` is] either `Monoid` or `Ord` it will be fine?

As long as `b` satisfies the requirements of Monoid **and** Ord it will be fine. :)

**Comment by coodoo** [comment]
ah, it's an `AND`, thanks for the clarification :D
