### ISSUE TITLE
Add mergeLeft and mergeRight

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ramda/ramda#2225]
Pretty often I find myself using `R.merge(R.__, object)`, it would be nice to have R.mergeLeft and R.mergeRight by analogy with R.mergeDeepLeft and R.mergeDeepRight.

**Comment by CrossEye** [comment]
Actually, we missed noting in the [0.24 release notes][rn] that we were [deprecating `merge`][dm] in favor of these `mergeDeep*` versions.  So, no, we don't want to add another version!  :smile:

  [dm]: https://github.com/ramda/ramda/pull/1867
  [rn]: https://github.com/ramda/ramda/issues/2183

**Comment by hrldcpr** [comment]
@CrossEye is that really the conclusion that thread came to? I had trouble following it.

Seems odd though—having the ability to do shallow merges is important for when you want to completely override a key with an object and not worry about deep stuff.

**Comment by CrossEye** [comment]
You're right.  It's not deprecating `merge`, which remains a shallow merge but adding all the `mergeDeep*` functions.  Sorry about that.

**Comment by hrldcpr** [comment]
@CrossEye Cool, thanks for reopening! If I get a chance soon I'll open a pull request adding `mergeLeft` and `mergeRight`

**Comment by Bradcomp** [comment]
Would this involve deprecating or renaming `merge` to `mergeLeft`, or leaving it as an alias?

**Comment by hrldcpr** [comment]
@Bradcomp good question, I think they discussed that a bit in #1867 and I'm sure it would get discussed in a new pull request as well.

I think either (a) `merge` should be deprecated (and eventually removed) or (b) there should be a corresponding `deepMerge`

Not sure if I have a preference for either choice, I just want consistency ✨

**Comment by hrldcpr** [comment]
#2365
