### ISSUE TITLE
R.type(R.mergeDeepLeft) is 'Undefined'

### ISSUE THREAD

**Issue by MidnightP** [ramda/ramda#2226]
```
R = require('ramda')
console.log(R.type(R.mergeDeepLeft))
```
This prints "Undefined"... Using latest version. Worth an issue?

**Comment by kedashoe** [comment]
http://ramdajs.com/repl/?v=0.24.1#?type%28mergeDeepLeft%29

logs "Function" for me. How have you installed ramda?

**Comment by MidnightP** [comment]
```
npm i --save ramda
```

Then in node (v 7.7.3) in the terminal:

```
R = require("ramda")
R.type(R.mergeDeepLeft)
```

I also see that mergeDeepLeft is not present on the `R` object...

2017-07-04 22:37 GMT+02:00 Kevin Wallace <notifications@github.com>:

**Comment by kedashoe** [comment]
```bash
$ npm --version
4.1.2
$ npm i --save ramda
$ grep ramda package.json 
    "ramda": "^0.24.1"
$ node -e 'console.log(typeof(require("ramda").mergeDeepLeft))'
function
```

Seems like somehow you are not getting the latest version of ramda. Behind a cache of some kind? Already have an earlier version of ramda installed?

**Comment by MidnightP** [comment]
Wasn't using latest indeed. Somehow didn't overwrite old version properly with `npm i --save ramda`.  Cheers!
