### ISSUE TITLE
Bug: Equals acts wrong on ES6 Sets

### ISSUE THREAD

**Issue by Jabher** [ramda/ramda#2227]
Set is an abstract structure which should not rely upon elements order. However, Ramda do not follow this spec.
E.g.
```javascript
R.equals(
  new Set([2,1]),
  new Set([1,2])
) //=> false
```
This is misbehavior; this two sets are actually equal. I clearly understand why this is happening; but, however, I'm definitely sure this should be fixed.

**Comment by kedashoe** [comment]
Yep. Using `entries` also doesn't make any sense. Would you like to submit a PR?

**Comment by Jabher** [comment]
My pleasure!

**Comment by jadengore** [comment]
@Jabher This should resolve issues with calling `R.isEmpty` on a set as well correct? I believe it uses the `equals` function.

**Comment by kedashoe** [comment]
closed #2232
