### ISSUE TITLE
typescript definitions for gaps?

### ISSUE THREAD

**Issue by devdoomari** [ramda/ramda#2228]
I know this might be too much to ask,
but do you guys have any plan for supporting 'gaps' in typescript definitions?

```
g(_, 2, 3)(1)
g(_, _, 3)(1)(2)
g(_, _, 3)(1, 2)
g(_, 2, _)(1, 3)
g(_, 2)(1)(3)
g(_, 2)(1, 3)
g(_, 2)(_, 3)(1)
```

**Comment by CrossEye** [comment]
(Sorry, just very slowly easing back into Ramda.  Sorry I missed this when it came out.)

Without searching through our issues, I can't even recall who maintains typescript configuration files. (I don't even know what such files are called!)  I'm sure you can find them in our discussions.  But you'd have to check with them.  Ramda doesn't maintain these itself.

**Comment by tycho01** [comment]
Hey, they're currently at [here](https://github.com/types/npm-ramda/). If this ends up becoming a common question perhaps it might help to include in the readme.

**Comment by devdoomari** [comment]
@tycho01 wow that's f****** awesome!!!
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
closing : )

**Comment by kedashoe** [comment]
> perhaps it might help to include in the readme.

Let's add it. Would you like to open a PR for this @tycho01 ? Maybe in a new section above translations called "Typings" or whatever term is best?

**Comment by tycho01** [comment]
@kedashoe: alright, PR at #2258. 😃
