### ISSUE TITLE
Rolling Window of Arrays?

### ISSUE THREAD

**Issue by diminishedprime** [ramda/ramda#2231]
I'm sure there's a clean way to do this, but I can't seem to find it. I'm wanting to take an array that's at least 2 elements log, and then get lists from a rolling window of a defined length.
e.g.
```
const array = [1, 2, 3, 4, 5]
const expected = [[1,2], [2,3], [3,4], [4,5]]
R.equals(R.Magic(array), expected) // should be true
```
I got something that works by doing this, but it seems like there's a simplier way to do this
```
const rollingWindow = (windowSize, list) => {
    const seed = {
        lastA: R.head(list),
        groups: [],
    }
    const reduceList = R.tail(list)
    return R.pipe(
        R.reduce(({lastA, groups}, a) => ({
            lastA: a,
            groups: R.append([lastA, a], groups),
        }), seed),
        R.prop('groups')
    )(reduceList)
}
rollingWindow(2, [1,2,3,4,5])
```

Thanks

**Comment by Bradcomp** [comment]
Hi @diminishedprime! I believe the function you're looking for is [aperture](http://ramdajs.com/docs/#aperture).

**Comment by diminishedprime** [comment]
@Bradcomp - thanks, that's exactly what I was looking for.
