### ISSUE TITLE
traverse() documentation is wrong

### ISSUE THREAD

**Issue by 1ven** [ramda/ramda#2234]
[.traverse](https://github.com/ramda/ramda/blob/v0.24.1/src/traverse.js#L34) is dispatching fantasy-land `.traverse` method of `traversable` but [docs](http://ramdajs.com/docs/#traverse) are telling that it's dispatching `.sequence` method.

Is it just a typo?

**Comment by CrossEye** [comment]
Yes, that was missed in https://github.com/ramda/ramda/commit/4bd28d56a6e0a7db2ab1ef53e29301da039fb401.  We need to update that comment.

**Comment by 1ven** [comment]
@CrossEye updated - https://github.com/ramda/ramda/pull/2236
