### ISSUE TITLE
traverse() function signature is not correct

### ISSUE THREAD

**Issue by 1ven** [ramda/ramda#2235]
According to [fantasy-land](https://github.com/fantasyland/fantasy-land#traverse-method) spec, `.traverse` method accepts `Applicative` type represantative as first argument, but Ramda `.traverse` accepts `of` function.

Is it a bug, or I'm wrong?

**Comment by davidchambers** [comment]
Ramda does not yet support recent versions of the Fantasy Land spec. [`Z.traverse`][1] and [`S.traverse`][2] are similar functions which support the current version.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes#traverse
[2]: https://sanctuary.js.org/#traverse

**Comment by 1ven** [comment]
@davidchambers thanks, I want to use Ramda for now, is that possible to update `traverse` according to recent Fantasy Land spec?

I can submit PR.

**Comment by davidchambers** [comment]
> [I]s that possible to update `traverse` according to recent Fantasy Land spec?

It is possible, but it's important that we support a version of the spec in a consistent manner. It would be confusing for one function to use the v1 definition while another function uses the v3 definition.

The best way for Ramda to consistently support the most recent version of the spec is to depend on sanctuary-type-classes, the unofficial standard library for Fantasy Land. I opened #1938 many months ago, but the changes were contentious. I still think it's a good direction. I'm happy to do more work on the pull request if @CrossEye and @buzzdecafe indicate that they are in favour of the approach.

**Comment by semmel** [comment]
This is fixed in #3360 and can be closed.
