### ISSUE TITLE
Functions that accept and return objects should respect frozenness

### ISSUE THREAD

**Issue by matthewp** [ramda/ramda#2238]
For example, with assoc:

```js
var first = Object.freeze({a: 1, b: 2});
var second = R.assoc('c', 3, first);

console.log(Object.isFrozen(second)); // currently false
```

I believe that Ramda should maintain the frozenness of objects passed in. Discuss!

**Comment by CrossEye** [comment]
Although I can see the appeal, the details become weird.  What happens with 

```js
merge(frozenObject, unfrozenObject); //=> ?
```

("unfrozen"?  hmmm.)

Or

```js
reduce(myFunc, thawedObject, [frozenObject1, frozenObject2, meltedObject1]); //=> ?
```

I find it difficult to see any reasonable answers to these.  Do you have an idea?

**Comment by buzzdecafe** [comment]
:-1: for me. Apart from the point @crosseye makes, it seems to me if you are using ramda you ought to be treating your data as if it were always "frozen" anyway.

**Comment by davidchambers** [comment]
I agree with Scott and Michael. Object freezing is not the solution, in my view. ;)

**Comment by matthewp** [comment]
@CrossEye I agree it gets a little fuzzy there. My thought was that in the case of multiple input objects you make a choice between 1) if all input objects are frozen then outbound object is frozen. and 2) if *any* of the input objects are frozen then the output object is frozen.

I don't have a strong opinion on these.

**Comment by matthewp** [comment]
@buzzdecafe 

> it seems to me if you are using ramda you ought to be treating your data as if it were always "frozen" anyway.

I don't agree with this for two reasons:

1. I use libraries that might not treat my objects as immutable and passing them a non-frozen object doesn't guarantee that they will not mutate it.
2. I am also not a perfect programming and simply remembering to never mutate is not good enough. Using Object.freeze gives me some confidence in the same way that types do.

**Comment by kurtmilam** [comment]
@matthewp An ESLint rule might help you remain true to your FP principles. It looks like there are multiple options in this area, according to [this google search](https://www.google.at/search?q=eslint+no+mutation).

That won't help with libraries that mutate your objects, but it's a start.

It might be interesting to have a companion library to Ramda that deep-freezes every object returned by any of the library's functions. I wouldn't use this in production, and I wouldn't need it for myself, but it might be useful in a team scenario where not all team members can be trusted to avoid mutation to install the deep-freeze library as a development dependency and have a flag in your app that chooses which version of Ramda to load - deep-freeze for development and vanilla for production.

The excellent [partial.lenses](https://github.com/calmm-js/partial.lenses) library has this behavior baked in. If I understand correctly, it deep freezes all objects returned by its methods if `process.env.NODE_ENV` is anything other than 'production'. Everything's frozen during development, but freezing is turned off in production.

**Comment by CrossEye** [comment]
>  I use libraries that might not treat my objects as immutable and passing them a non-frozen object doesn't guarantee that they will not mutate it.

But then wouldn't passing them a frozen object break your contract with those libraries?  If you ask a library to do something, and its process involves mutating the object you pass to it, you are not using it properly if you pass it a frozen object.

> [S]imply remembering to never mutate is not good enough. Using Object.freeze gives me some confidence in the same way that types do.

If this is a significant concern for you, I would suggest that you look at the [suggestions from @kurtmilam ][su].

----------

I still think the complexities in API design this would entail are fairly nasty.

```js
R.map(
  R.over(R.lensProp('val'), R.inc), 
  Object.freeze([{val: 1}, Object.freeze({val: 2}), {val: 3}])
)  //=> ?
```

Should the resulting list be frozen?  Should the objects in the list be frozen?  Do we need to check each one individually to decide?  After all, we're calling `over` on them individually.  Do we expect those who *want* to mutate the result of a Ramda call to have to `clone` the results so that they can?  (It's not that that last is totally unreasonable, but I can't see strong arguments in favor of it.)

I like Ramda's promise to never mutate your data on you, but I simply cannot see extending this to preventing you from mutating the data yourself.

  [su]: https://github.com/ramda/ramda/issues/2238#issuecomment-315204534

**Comment by matthewp** [comment]
@CrossEye 

> But then wouldn't passing them a frozen object break your contract with those libraries? If you ask a library to do something, and its process involves mutating the object you pass to it, you are not using it properly if you pass it a frozen object.

Maybe! Without protecting my data I have no way of knowing what a library really does. The only option is to freeze it, and if it's an API that expects to mutate, hand it an unfrozen clone instead.

> If this is a significant concern for you, I would suggest that you look at the suggestions from @kurtmilam .

Thanks, I will do that. I read the partial.lenses page but I don't understand what it is. Is it like ramda but for frozen objects?

-----

Would it change your mind if you thought about frozen as just another "property" of the object? For example, forget about frozenness for a second, your example, if it looked like:

```js
var arr = [{val:1}, {val2: isFrozen: true}, {val: 3}];
arr.isFrozen = true;

R.map(
  R.over(R.lensProp('val'), R.inc), 
  arr)
)  //=> ?
```

Does this change your perspective? From mine, the frozenness of an object is just as important as its properties.

**Comment by matthewp** [comment]
btw, no hard feelings if you all don't want to accept this, I'm just having fun trying to make the case :D . partial.lenses does seem pretty awesome! I might start using that regardless of the outcome here.

**Comment by CrossEye** [comment]
@matthewp:
> Would it change your mind if you thought about frozen as just another "property" of the object?

I believe you're thinking that Ramda is returning (some version of) your object.  But that is not how it works.  `map` for instance uses `(a -> b)` to convert a container of item(s) of type `a` into one of type `b`.  Even if both are objects, there is no reason to assume that their specific properties are related.

```js
const locations = [
  {name: 'Melbourne', lat: -37.81, lon: 144.96, temps: [9, 5, 7, 11, 13, 12, 14] /*. more */},
  {name: 'New York', lat: 40.73, lon: -73.93,  temps: [28, 26, 23, 31, 33, 34, 36] /*. more */},
  {name: 'Paris', lat: 48.86, lon: 2.35,temps: [18, 21, 19, 24, 24, 25, 22] /*. more */}
]

map(loc => ({city: loc.name, weeksHighTemp: Math.max.apply(null, loc.temps)}), locations)
//=> [
//   {"city": "Melbourne", "weeksHighTemp": 14}, 
//   {"city": "New York", "weeksHighTemp": 36}, 
//   {"city": "Paris", "weeksHighTemp": 25}
// ]
```

And `reduce` creates a single `a` value from a function that converts an `a` and a `b` into another `a`, an initial `a` value and a list of `b`s.  There is not one value to use for choosing our frozen property.

Ramda is definitely not competing with Immutable or mori.  They are designed around the notion of immutable values, as Ramda is, but they are in the business of *enforcing* where Ramda is more about *enabling*.

----------

> btw, no hard feelings if you all don't want to accept this,

I would hope that could go without saying.  Library writers are not always of the same mind as certain users, and they can be cantankerous, inflexible, and downright thick-witted.  But in the end, we assume that all contributors are working for the best of the library and the community.

**Comment by matthewp** [comment]
I agree that map, reduce, would make no sense to add additional metadata like frozenness to the outbound objects. That you thought I expected this means I've done a poor job communicating my position. So let me back up a minute and make this more simple.

To be clear, I do not think Ramba should have an opinion that objects should be frozen. I agree that enabling immutable but not enforcing it is a good idea for this library. So in case there is a misunderstanding, I do not think Ramba should freeze objects except for when it is returning what you called a version of the object provided.

Map, as you explained, is making a new object, and this is very explicit. So let's focus on the case of `assoc` only.  Surely you agree that:

```js
var first = {a: 1, b: 2, isFrozen: true};
var second = R.assoc('c', 3, first);
```

should contain the `isFrozen` property, correct?  If so, why would it not make sense to copy over the frozenness metadata into the new object (in this case it is **not** frozen)?

> I would hope that could go without saying.

Me too, but often it doesn't and I wanted to make it explicit that I appreciate you humoring me here :)

**Comment by kurtmilam** [comment]
Most Ramda functions that take objects as arguments and return objects work with the objects' own enumerable properties. There is no `isFrozen` own enumerable property on any object unless someone has added it explicitly (as you did to `first` in your example).

Think of `R.assoc` as being similar to JavaScript's native `Object.assign`. This native method, like `R.assoc`, only takes into account own enumerable properties.

For example, you could naively recreate `R.assoc` based on `Object.assign`:
```JavaScript
const assocNative =
  ( propName, propVal, target ) =>
    Object.assign( {}, target, { [ propName ]: propVal } )
```
The object returned by this `assocNative` function will always be 'unfrozen', regardless of whether the `target` object passed into it was frozen.

[See a more thorough example on Ramda's REPL.](https://goo.gl/cZnmaJ)

Also, you may be interested in taking a look at [Ramda's Gitter](https://gitter.im/ramda/ramda).
