### ISSUE TITLE
what happen in R.into or R.chain ?

### ISSUE THREAD

**Issue by zongwan** [ramda/ramda#2240]
http://ramdajs.com/repl/?v=0.24.1#?var%20intoArray%20%3D%20R.into%28%5B%5D%29%3B%0Afunction%20add1%28x%29%20%7B%20return%20%5Bx%20%2B%201%5D%3B%20%7D%0Afunction%20dec1%28x%29%20%7B%20return%20%5Bx%20-%201%5D%3B%20%7D%0Afunction%20times2%28x%29%20%7B%20return%20%5Bx%20%2A%202%5D%3B%20%7D%0A%0Avar%20numbers%20%3D%20%5B1%2C%202%2C%203%2C%204%5D%3B%0Avar%20transducer%20%3D%20R.compose%28R.map%28R.add%281%29%29%2C%20R.take%282%29%29%3B%0AintoArray%28transducer%2C%20numbers%29%3B%20%2F%2F%3D%3E%20%5B2%2C%203%5D%0Atransducer%28numbers%29%20%2F%2F%3D%3E%20%5B2%2C%203%5D%0A%0Avar%20mdouble%20%3D%20R.chain%28times2%29%3B%0Avar%20mdec%20%3D%20R.chain%28dec1%29%3B%0Avar%20xcomp%20%3D%20R.compose%28mdec%2C%20mdouble%29%3B%0AintoArray%28xcomp%2C%20%5B10%2C%2020%2C%2030%5D%29%20%2F%2F%3D%3E%20%5B18%2C%2038%2C%2058%5D%0Axcomp%28%5B10%2C20%2C30%5D%29%20%2F%2F%3D%3E%20%5B19%2C%2039%2C%2059%5D%0A
```
var intoArray = R.into([]);
function add1(x) { return [x + 1]; }
function dec1(x) { return [x - 1]; }
function times2(x) { return [x * 2]; }

var numbers = [1, 2, 3, 4];
var transducer = R.compose(R.map(R.add(1)), R.take(2));
intoArray(transducer, numbers); //=> [2, 3]
transducer(numbers) //=> [2, 3]

var mdouble = R.chain(times2);
var mdec = R.chain(dec1);
var xcomp = R.compose(mdec, mdouble);
intoArray(xcomp, [10, 20, 30]) //=> [18, 38, 58]
xcomp([10,20,30]) //=> [19, 39, 59]  why ?
```

**Comment by kedashoe** [comment]
Hi @zongwan . This happens because [transducers evaluate composition in reverse order](https://github.com/ramda/ramda/issues/2206).

**Comment by zongwan** [comment]
Thanks a lot!


http://ramdajs.com/docs/#into
```javascript
var numbers = [1, 2, 3, 4];
var transducer = R.compose(R.map(R.add(1)), R.take(2));

R.into([], transducer, numbers); //=> [2, 3]

var intoArray = R.into([]);
intoArray(transducer, numbers); //=> [2, 3]
```
This sample is not very clear


```javascript
var numbers = [1, 2, 3, 4];
var transducer = R.compose(R.map(R.add(1)), R.map(R.multiply(2)));

// [1, 2, 3, 4]
// R.map(R.multiply(2)) => [2, 4, 6, 8]
// R.map(R.add(1)) => [3, 5, 7, 9]
transducer(numbers) //=> [3, 5, 7, 9]

var intoArray = R.into([]);
// [1, 2, 3, 4]
// R.map(R.add(1)) => [2, 3, 4, 5] 
// R.map(R.multiply(2)) => [4, 6, 8, 10]
intoArray(transducer, numbers); //=> [4, 6, 8, 10]

```
