### ISSUE TITLE
Wrong description of "ifElse" method in the documentation

### ISSUE THREAD

**Issue by barbiturat** [ramda/ramda#2242]
The documentation says about ifElse method: "Returns function A new **unary** function that will process either the `onTrue` or the `onFalse` function depending upon the result of the `condition` predicate."
But ifElse accepts any number of arguments. For example:
`ifElse(lt, add, subtract)(5, 7) //=> 12`

**Comment by buzzdecafe** [comment]
Where do you see the "unary" bit? Here is what I see on the docs site:

![image](https://user-images.githubusercontent.com/716260/28744867-b3e23260-7438-11e7-8efa-8b8e5c364232.png)

**Comment by barbiturat** [comment]
http://dl4.joxi.net/drive/2017/07/29/0018/3328/1215744/44/746ebf703a.jpg

**Comment by buzzdecafe** [comment]
ah i see, well spotted. Are you interested in a PR to fix some of these things you are observing?
