### ISSUE TITLE
Misleading documentation of "either" and "both" methods. They can return not only functions

### ISSUE THREAD

**Issue by barbiturat** [ramda/ramda#2244]
Documentation said about the "either" method: 
"**Returns function** a function that applies its arguments to `f` and `g` and `||`s their outputs together."
But the method returns not only a function, but any applicative functor of corresponded type. Example:
`either(Maybe.Just(false), Maybe.Just(55)); // => Maybe.Just(55)`
`either([false, false, 'a'], [11]) // => [11, 11, "a"]`
This description may mislead.
Same about the "both" method

**Comment by buzzdecafe** [comment]
agreed, would you be willing to submit a PR to update the docs?

**Comment by karatsuba** [comment]
hey, here is a fix for that: https://github.com/ramda/ramda/pull/2373

**Comment by karatsuba** [comment]
Hello @buzzdecafe!
I guess this issue can be closed now.
