### ISSUE TITLE
Meteor package manager (atmosphere) has an old version of Ramda

### ISSUE THREAD

**Issue by Kiran-Rao** [ramda/ramda#2245]
The version available in atmosphere is 0.19.0, updated Jan 2, 2016. 
It is preventing my team from using some of the newer functions (`sortWith`, `forEachObjIndexed`)

Would it be possible for someone on the ramda team to update the package? 

https://atmospherejs.com/ramda/ramda

**Comment by buzzdecafe** [comment]
interesting. I have no idea who did that or how. Anyone?

**Comment by ecancino** [comment]
Seems like @ccorcos might know.

**Comment by ccorcos** [comment]
Just use the NPM Ramda. This was a hack from back in the da

**Comment by buzzdecafe** [comment]
how can we get the existing out-of-date thing removed?

**Comment by Kiran-Rao** [comment]
^it might break people' projects (like mine) if it's removed. 

A better solution would be to label as depricated and suggest to use npm.

**Comment by kedashoe** [comment]
> A better solution would be to label as depricated and suggest to use npm.

Do you know how we do this, @Kiran-Rao ?
