### ISSUE TITLE
Weird behavior in dissocPath after updating ramda

### ISSUE THREAD

**Issue by tomaswitek** [ramda/ramda#2249]
After I updated my APP to the newest ramda version I found a following problem:

```
var state = {
  rows: {
    1: {},
    2: {}
  },
  ids: [1, 2]
};
R.dissocPath(['rows', 1], state); // {"ids": [1, 2], "rows": []}
R.dissocPath(['rows', '1'], state); // {"ids": [1, 2], "rows": {2: {}}}
```
If I understand it right now I have to be very carefull and always provide path of strings?
When I provided an integer by accident it converts it to an empty array 😢 

Here is link to REPL: https://goo.gl/9KjZdX
It seems to be connected to https://github.com/ramda/ramda/pull/2036/files.

I am just asking if you find this behavior ok, nothing else. 
Thx

**Comment by kedashoe** [comment]
I believe this is intended. Numbers assume they are dealing with arrays, strings assume objects.

**Comment by kedashoe** [comment]
> If I understand it right now I have to be very carefull and always provide path of strings?

So yes, if you are indexing into an object, you need to use a string.

Gonna close, feel free to comment if you have more questions @tomaswitek
