### ISSUE TITLE
Documentation Tool I've been working on

### ISSUE THREAD

**Issue by domtronn** [ramda/ramda#2251]
Hi guys, I've been a fan of Ramda for years now, using it in a lot of my projects. As always, introducing people I work with to the library. However, one of the difficulties people seem to always face is knowing which function to [use when](https://github.com/ramda/ramda/wiki/What-Function-Should-I-Use%3F)...

So, I've been playing around with creating a tool called [`ramda-suggest`](https://github.com/domtronn/ramda-suggest) which is a CLI tool that will suggest a function to use to produce a certain output given some inputs, for example

```sh
ramda-suggest [1,2,3,3,3,4,4] [1,2,3,4]
```
produces the following output;

>**dropRepeats** [_category:List_]
>
>    **R**: _R.dropRepeats([1,2,3,3,3,4,4]) → [1,2,3,4]_
>    **λ**: _[a] → [a]_
>
> Returns a new list without any consecutively repeating elements.
> R.equals is used to determine equality.
> Acts as a transducer if a transformer is given in list position.
>
> **param 1**: {_Array_} list The array to consider.
> **returns**: {_Array_} list without repeating elements.
>
> -----
>
>**uniq** [_category:List_]
>
>    **R**: _R.uniq([1,2,3,3,3,4,4]) → [1,2,3,4]_
>    **λ**: _[a] → [a]_
>
> Returns a new list containing only one copy of each element in the original
> list. R.equals is used to determine equality.
>
> **param 1**: {_Array_} list The array to consider.
> **returns**: {_Array_} The list of unique items.

Anyway, I just though I'd make you aware of it - I would love any feedback, opinions, ideas or suggestions! 🙂  Thanks again for a fantastic library! ⭐️

**Comment by Qquanwei** [comment]
Great!

**Comment by nickmccurdy** [comment]
That's awesome, do you think this could be wrapped in a web library consumed by the docs?

**Comment by raine** [comment]
Unsurprisingly, `[1,2,3] [2,3,4]` doesn't work. Still cool though. :+1:

**Comment by domtronn** [comment]
@nickmccurdy I've tried to write it to also work as a library as well.. The CLI tool just parses the arguments into an array of inputs and an output.

So I don't see why not! 😃 

---

@raine What would you expect the outcome to be?

**Comment by nickmccurdy** [comment]
Nice! It would be also be nice to have a type-aware search feature like [Hoogle](https://www.haskell.org/hoogle/), but perhaps that's complex enough for its own issue.

**Comment by tycho01** [comment]
@domtronn whoa, how'd you make it check which functions might match?

**Comment by CrossEye** [comment]
This is very cool.  At the very least, this should be added to [the wiki][wi].

  [wi]: https://github.com/ramda/ramda/wiki#tools
