### ISSUE TITLE
R.mergePath

### ISSUE THREAD

**Issue by IMalyugin** [ramda/ramda#2255]
There is assoc function and there is assocPath, they solve one of the goals properly, but shouldn't there be a path analogue for merge as well?

A common case, you must travel 4 levels deep into an object and merge objects under same key, it can be done with composition, such as this:
```
const lens = R.lensPath(['a', 'b']);
R.over(lens, R.merge(R.__, {c2: 22, c3: 33}), {a: {b: {c1: 1, c2: 2}}});
//> {a: {b: {c1:1, c2: 22, c3: 33}}}
```

But isn't this a common usage case?
So something like R.mergePath(['a', 'b'], {c2: 22, c3: 33}, {a: {b: {c1: 1, c2: 2}}})

**Comment by kedashoe** [comment]
Hi @IMalyugin , how about [over](http://ramdajs.com/docs/#over) for this?

```js
over(lensPath(['a', 'b']), merge({c2: 22, c3: 33}), {a: {b: {c1: 1, c2: 2}}});
```
https://goo.gl/skc3v6

**Comment by IMalyugin** [comment]
That's exactly what I brought up above, It's just using a lot of code to solve a simple problem, but looking at difference for assocPath and assoc. Basically to mime assoc with assocPath, we only need to do this: assoc = (prop, value, src) = assocPath([prop], value, src) - which is 2 digits :) and mergePath is combination of 3 separate functions, which doesn't look easy

**Comment by kedashoe** [comment]
> That's exactly what I brought up above

lol sorry about that.

> It's just using a lot of code to solve a simple problem

hmm doesn't seem so much to me? I mean, if you `map` something, you do `map(f, x)`, that is 2 functions.. here we have 3? And it is not uncommon to have your lenses already defined, so it really boils down to `over(myLens, merge(x), y)`. Happy to leave this open though and see what everyone thinks.

**Comment by CrossEye** [comment]
Just catching up.

My feeling is that something like `mergePath` is the sort of function for which we created the [Cookbook][cb].  If we see a lot of demand, we could consider moving it into the library.

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by char0n** [comment]
@IMalyugin we could meanwhile incorporate `mergePath` into [ramda-adjunct](https://github.com/char0n/ramda-adjunct). We already have [mergePaths](https://char0n.github.io/ramda-adjunct/1.17.0/RA.html#.mergePaths) that does basically the same thing but with two paths in the source object. It would be a nice addition. Issue a PR if you're interested.

@CrossEye 
Is it legitimate to add the following functions into cookbook ?

Acts as multiple path: arrays of paths in, array of values out. Preserves order.
```javascript
const paths = curry((ps, obj) => ap([path(__, obj)], ps));
```
Merge objects under corresponding paths.
```javascript
const mergePaths = curry((ps, obj) => mergeAll(paths(ps, obj)));
```

**Comment by BjornMelgaard** [comment]
I suggest to rename current `mergeProps` and `mergePaths` to `flattenProps` and `flattenPaths` because of this function. 
`mergeProps` and `mergePaths` extracts parts from object and merges them together, but this function is shoves 1 object inside other, @char0n ?

P.S. Actually `flattenProps` were original name, because of [recompose flattenProp](https://github.com/acdlite/recompose/blob/master/docs/API.md#flattenprop)

**Comment by char0n** [comment]
@BjornMelgaard I think the naming of already existing functions is correct. `mergeProps` and `mergePaths` does exactly what they say they does. They extract and merge the objects at  props/paths and return the merge result.

Now there are the functions that are subject of this issue. `mergeProp`, `mergePath`: again I think the naming is correct because what the function does is merging the user provided data into prop/path and returning the new version of the object.

`flattenProps` is in mind different. It does the same as [spread](https://github.com/ramda/ramda/wiki/Cookbook#spread) function documented in ramda cookbook. It takes an object at prop/path and spreads it to the most outer level of provided object creating new version of the object.

**Comment by BjornMelgaard** [comment]
@char0n, ok, `flatten` is really wrong, I've thought about it tomorrow

**Comment by CrossEye** [comment]
@char0n: I seem to have missed a bunch of messages.  Those look fine for the Cookbook.

**Comment by char0n** [comment]
`mergePaths` and `paths` documented in cookbook.

`mergePath` and `mergeProp` is cooking here: https://github.com/char0n/ramda-adjunct/pull/148

**Comment by IMalyugin** [comment]
My initial concern was the fact, that assoc('a', b, c) actually equals to assocPath(['a'], b, c), which makes assoc incredibly overheaded. But even so, if there's such a set of function, it should be copied over to merge function, or even better, instead of having current merge function there could be mergePath, that covers both the needs of simple merge and goes further.

It isn't HARD to actually create a mergePath function with what ramda currently has, it just seems wrong not to have it right away. In my project, I just created ramda.js in the core, and defined it there, including yet another library  just for one function that i can write in a single line isn't exactly something I'd vouch for.

I found the answer I was looking for, the functions are added into ramda after proving they are requested, not by covering the functionality. And the reason assoc exist, is probably compose/pipe, which would be a bigger pain to assemble if one had to wrap first argument into array.

**Comment by CrossEye** [comment]
More to the point, `assoc` predated `assocPath`, at least conceptually.  (They may well have been added in the same PR; I don't recall.)  Similarly, I think `lensProp` and `lensIndex` predated `lensPath`.  We are, to @davidchamber's chagrin, slow to remove functionality.  There is an argument to be made for removing a great number of our functions in favor of the `lens` ones.  And certainly we could deprecate `assoc` in favor of `assocPath`, or `prop` in favor of `path`, etc.  But in my experience these simpler functions are used at least as often as their more thorough companions.  So we haven't seen a great reason to remove them.  (Removing everything that could be covered by lenses is much more intriguing to me, but quite invasive.)

**Comment by polytypic** [comment]
Note that in

```
over(lensPath(['a', 'b']), merge({c2: 22, c3: 33}), {a: {b: {c1: 1, c2: 2}}});
```

the `merge` might not be the way you want it and you might want to `flip` it.  In Partial Lenses I opted to provide the [flipped version](https://calmm-js.github.io/partial.lenses/playground.html#DYew5gFAUASgdCAbgUwE4XsZA7AzgBQEMAXACwgG0ByQqgGgAIqAjKgXQEpH4BbNMZBADeAYwBMALgZixjEQGYp8+QF8uDIYSlDm2kQEYp+uZOkrzHKJaihIUADJxCuXAEsw2SjXpNWbRqKmMnKKDMoqAVoauhoGRiZSYuZqVkA).

**Comment by char0n** [comment]
@polytypic yep, you're right. @IMalyugin provided correct signature using `R.merge(R.__, {c2: 22, c3: 33})` which was correct. It acts as [mergeRight](https://github.com/char0n/ramda-adjunct/blob/master/src/mergeRight.js). @kedashoe just ommited R.__ in his signature, I guess it was just a typo.
