### ISSUE TITLE
constructN REPL

### ISSUE THREAD

**Issue by jdkschang** [ramda/ramda#2260]
the [REPL](https://goo.gl/tV66fb) doesn't reflect the changes in the repo. 
Currently outputs as:
> function n(r){return NaN|b(r)?n:t.apply(this,arguments)} does not have a method named "join"

instead of the console messages
>// Add a whollop of Mayonnaise
// Add a whollop of Potato Chips
// Add a whollop of Potato Ketchup

**Comment by kedashoe** [comment]
repl will be updated with the next release

**Comment by jdkschang** [comment]
roger
