### ISSUE TITLE
R.into does not work properly with R.slice

### ISSUE THREAD

**Issue by xgbuils** [ramda/ramda#2264]
Hi,

I picked up the example of `R.into` defined in [documentation](https://goo.gl/QtcCgq) and I changed `R.take(2)` per `R.slice(1, 3)` and it throws [this error](https://goo.gl/JSzWKC):

``` javascript
t.@@transducer/step is not a function
```

I expected:
``` javascript
[3, 4]
```

However `R.compose` works well:

``` javascript
R.compose(R.map(R.add(1)), R.slice(1, 3))([1, 2, 3, 4]) // [3, 4]
```

**Comment by Bradcomp** [comment]
Hi @xgbuils,

Right now, `R.slice` is not a function that works with transducers. Looking at you issue, I suspect it probably should be though. 

`take` and `drop` both support transducers, so you should be able to wire something up with those two functions like [this](https://goo.gl/XzXnqS).

Might you be interested in looking into adding transducer support to `slice`?

**Comment by asaf-romano** [comment]
Let's keep this open - no reason not to support this behavior.
