### ISSUE TITLE
versioning scheme => "ramda": "^0.23.0" => ?

### ISSUE THREAD

**Issue by ORESoftware** [ramda/ramda#2268]
Does Ramda use semver? Is there some explanation as to why Ramda is still at major version 0?

I am simply confused by the fact the latest version of Ramda is 0.24.0, I would expect it to be 1.x.y.

**Comment by kedashoe** [comment]
No reason really, every now and then we try to figure out what should constitute 1.0 but it hasn't happened yet.

**Comment by ORESoftware** [comment]
whatever's clever

**Comment by Frikki** [comment]
Having a version `0.y.z`, indicates to me, and many others, that the library isn’t production ready and is subject to API changes.

**Comment by CrossEye** [comment]
The library has been subject to a great number of API changes.  That's one reason it's not gone to 1.0.  Another is that there's always been some confusion about what type of project this is.  It started as a learning experiment by @buzzdecafe and me.  And even as it's grown popular and gotten used by many others, it's difficult to give up the freedom afforded by a more personal project.

Mostly, though, we've never done the deep analysis as to what should constitute version 1, and what we might like to do differently for a version 2.
