### ISSUE TITLE
is() functionality for Functions and Object returns truthy.

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [ramda/ramda#2271]
Hello,

I am trying to validate a parameter with a simple predicate. I want to make sure that the parameter passed is an Object and not a Function.

The problem, and maybe this is the desired functionality, but due to instance of for both function and object being the same, I am not able to distinguish between the two.

My predicate is
```
is(Object)({}) === true
is(Object)(() => {}) === true
```

IS there a different method that I should be using or does this need to be revised?

Thanks

**Comment by kurtmilam** [comment]
[`type`](http://ramdajs.com/docs/#type) should do the trick:
```JavaScript
type( {} ) === "Object" //-> true
type( () => {} ) === "Function" //-> true
```

The behavior of `is` is by design. From the [docs](http://ramdajs.com/docs/#is):
> See if an object (val) is an instance of the supplied constructor. This function will check up the inheritance chain, if any.

In case you weren't aware, there's also a [Ramda Gitter channel](https://gitter.im/ramda/ramda) where you can get help with questions like this.

**Comment by theboyWhoCriedWoolf** [comment]
Amazing thanks,

Yeah I saw `type`, but since I need to return a curried function as its a predicate that gets executed in `where`, I would have to create a custom predicate with:

```
(prop) => (type( prop ) === "Function")
```
and so wondered if there was already inbuilt functionality so I wouldn't have to create a custom check.

**Comment by kurtmilam** [comment]
Another option would be something like this:
```JavaScript
const isType =
  typeName => x => typeName === type( x )
isType( 'Object' )( {} ) //-> true
isType( 'Object' )( _ => {} ) //-> false
```
