### ISSUE TITLE
Unexpected behavior of curry and curryN

### ISSUE THREAD

**Issue by danielo515** [ramda/ramda#2272]
Hello,

First of all, thanks for ramda, it's a great tool for FP.
Today, trying to make some testing I almost became mad because my tests were not executing properly. I blamed node, my testing tool and my testing environment. Then  I realized the problem was with `lodash.curry`. Why am I here then ? Because I thought: 

> "Ok lodash did it wrong, let's see if ramda does the same."

And happens that ramda does exactly the same. I can accept that maybe the person who is wrong is me, but not a single line in the documentation mentions the behavior I have discovered.

Here is a small snippet you can test on ramda REPL

```js
const x = curry((a,b,c) => console.log(a,b,c))
x()('b')('c')()()()()('a')
const y = curryN(3,(a,b,c) => console.log(a,b,c))
y()('b')('c')()()()('x')
```
As you can see I can call  `x` and `y` as many times as I want if I don't provide an argument. My expectation is that, if the function takes three parameters, the curried function is executed after being invoked 3 times.

Functions communicate their arity with the length property, so there curry can easily track function invocations and compare them with the arity. 
Maybe I can accept that behavior on curry, but the I want to have an escape hatch on `curryN`, but that is not the case.

Imagine that I have a curried function that takes an optional parameter, I can't use ES6 defaults because then curry will not work, so I try to check default inside the function.

```js
const x = curry((a,b,c) => {
a = a || 'default'
console.log(a,b,c)
})
```
This will not work either because I'll be forced to call the function like this

```js
//not working
x()('b','c')
// works
x(null)('b','c')
```
As I said, I can accept this behavior for curry, but not for `curryN`.
And even if you want to keep it the way it is, please document this particular behavior on the documentation.

Regards

**Comment by kedashoe** [comment]
I have never seen a pattern where the first argument is optional? You can use `curryN` to support optional arguments at the end however, if you would like:

```js
let f = curryN(2, (a, b, c) => {
  if (c === undefined) {
    c = 'no c';
  }
  console.log(a+', '+b+', '+c);
});
```

https://goo.gl/2YnmPa

**Comment by davidchambers** [comment]
In the uncurried world one might write something like this:

```python
def join(words, sep=' '):
    return sep.join(words)

join(['foo', 'bar', 'baz'], ', ')
# => 'foo, bar, baz'

join(['foo', 'bar', 'baz'])
# => 'foo bar baz'
```

The curried world has a different idiom:

```haskell
joinWith :: String -> [String] -> String
joinWith sep words = Data.List.intercalate sep words

unwords :: [String] -> String
unwords = joinWith " "

joinWith ", " ["foo", "bar", "baz"]
-- => "foo, bar, baz"

unwords ["foo", "bar", "baz"]
-- => "foo bar baz"
```

In the code above we apply `joinWith` to the default separator (`" "`) to define a specialized function.

Mixing currying and optional arguments is an anti-pattern. They're two solutions to the same problem.

**Comment by CrossEye** [comment]
> My expectation is that, if the function takes three parameters, the curried function is executed after being invoked 3 times.

The [documentation for `curry`][cu] and [`curryN`][cN] does explain that the arguments to a Ramda curried function needn't be supplied one at a time and gives some examples.  Instead, Ramda's currying will call the function when you've supplied at least three arguments, regardless of how many invocations that takes. 

As David says, currying and optional parameters simply don't work well together.

  [cu]: http://ramdajs.com/docs/#curry
  [cN]: http://ramdajs.com/docs/#curryN

**Comment by danielo515** [comment]
Ok, you are all right.
I'm just diving into FP and I'm used to provide optional parameters.

At this moment, I don't see a problem to allow optional parameters in a curried function, but I suppose that point of view will change with time.

Thanks for all your explanations

**Comment by CrossEye** [comment]
> At this moment, I don't see a problem to allow optional parameters in a curried function

It's not really that they're optional that's at issue.  The problem is that when JS decided to add defaults values for parameters, it chose to not count those with defaults when reporting the function's arity.

```js
(first, last, middle) => `${first} ${middle || ''} ${last}}`).length //=> 3
(first, last, middle = '') => `${first} ${middle} ${last}}`).length //=> 2
```

So we've already lost the ability to curry it with just plain `curry`, which uses that length.

But even beyond that, it's very hard to know what to do with such arguments given Ramda's style of currying.  We could switch to straightforward currying, and forget any calls with multiple parameters.  (And there's a fair bit to be said for this, but it's a radical change to Ramda.)  Or we could invent a second kind of placeholder to say "use the default here."  But this seems extravagant for the gain.

But mostly, I think what David said is appropriate: Optional parameters and currying are two different and incompatible solutions to a single problem.
