### ISSUE TITLE
Add R.adjustAll 

### ISSUE THREAD

**Issue by JMSantos94** [ramda/ramda#2273]
I was looking into an alternative for **evolve** that worked with arrays, but the closest thing I found was **adjust**. However it only works in a single element. I propose we do something similar to **evolve**, or a variant of **adjust** that could take a transform object to apply to difference indexes.

Here is currently my workaround (it won't work as good as evolve, since it doesn't account for nesting): 

```
const adjustAll = R.curry((transforms, arr) => {
  
    const newArrEls = Object.keys(transforms)
        .reduce((r, i) => {
            const fn = transforms[i];
            r[i] = fn(arr[i]);
            return r;
        }, {});
  
    return Object.assign(
      [], 
      arr, 
      newArrEls
    );
});
```
Here is a demo: https://goo.gl/ZbcpJj

What do you guys think?

**Comment by CrossEye** [comment]
It's an interesting function.  But it's not clear to me how great the need for it is.  Usually when that happens, we put it in the [Cookbook][cb] until it becomes clear that a number of people need it.  Feel free to edit the Cookbook to include it.

Another way to approach this is to use [`lenses`][le].  Here's one possibility for the example you linked:

```js
compose(
  over(lensIndex(1), assoc('name', 'Julio')),
  over(lensIndex(2), assoc('id', '17')),
)(myArr)
```

Or you could create this from your example format via a version something like this:

```js
const adjustAll = curry((transforms, arr) => 
   apply(compose)(map(([idx, fn]) => over(lensIndex(Number(idx)), fn), toPairs(transforms)))(arr)
)

adjustAll(transforms, myArr)
```

(I'm not suggesting that this is a better way to write your function, only that if you're invested in that `transforms` format, then this might move you toward lenses.)

You can see this in [the REPL][rr].

  [le]: http://ramdajs.com/docs/#lens
  [rr]: https://goo.gl/1Y7zFi



  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by JMSantos94** [comment]
Thanks for the quick reply and the suggestions!
I wasn't aware we had a cookbook :smile: :+1: 

We can close this issue, until other people finds this useful or not :nerd_face:

**Comment by buzzdecafe** [comment]
:+1: for cookbook

**Comment by kurtmilam** [comment]
I just worked [this](https://goo.gl/8b9ZVk) up in response to a question in the Ramda Gitter:

```JavaScript
const evolveArray =
  template =>
    addIndex( map )
            ( ( x, i ) => template[ i ]( x ) )
evolveArray( [ add( 1 ), add( 2 ), add( 3 ) ] )
           ( [ 1, 2, 3 ] )
//->[ 2, 4, 6 ]
```

**Comment by Bradcomp** [comment]
> I wasn't aware we had a cookbook

This is a common statement. I think we should have a link to the cookbook (or the wiki in general) somewhere on website or in the readme...
