### ISSUE TITLE
cdnjs and R.add(x)

### ISSUE THREAD

**Issue by woaiwodib107** [ramda/ramda#2274]
It's really a great project.
I find an error when I use "cdnjs" link`Failed to load resource` and I can't find the file when I write the link in my browser.
At last, I go `jsdelivr.com` to search the name and download it.

when I use R.add(1). It `console.log` this function, and it should be written `1`. So can we rewrite the `toString` function to change the result?

**Comment by woaiwodib107** [comment]
I'm so sorry about the error operation。

**Comment by Qquanwei** [comment]
emmm....
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/ramda@0.24.1/dist/ramda.min.js"></script>
<script type="text/javascript">
   window.alert(R.add(1,2))
</script>
```

**Comment by woaiwodib107** [comment]
Oh! yes!
The link in `Readme` lack the `@`.
And how do you like the `R.add(1)` function.

**Comment by Qquanwei** [comment]
啥意思

**Comment by woaiwodib107** [comment]
就是readme上面的link少了个`@`,导致找不到这个文件
然后就是R.add(1)是把这个函数打出来了，但应该返回1的，所以是不是应该重写原型链的toString()方法

**Comment by Qquanwei** [comment]
R.add :: a -> b -> c

R.add(1) 返回 b => R.add(1, b)

没有问题呀

**Comment by buzzdecafe** [comment]
> The link in Readme lacks the @.

@woaiwodib107 @Qquanwei would either of you like to submit a PR to fix the links on the README?

**Comment by woaiwodib107** [comment]
OK! It is the first time I submit a PR.  If there is something wrong operations or formats.  Please forgive me. @buzzdecafe
