### ISSUE TITLE
Update jsDelivr links

### ISSUE THREAD

**Issue by LukasDrgon** [ramda/ramda#2278]
I noticed that you updated the links on GitHub but, forgot to update links at http://ramdajs.com/.
The correct links are: 
//cdn.jsdelivr.net/npm/ramda@0.24.1/dist/ramda.min.js
//cdn.jsdelivr.net/npm/ramda@0.24/dist/ramda.min.js
//cdn.jsdelivr.net/npm/ramda@latest/dist/ramda.min.js

Be sure to update them, when you release a new version.
You can find links for all files at https://www.jsdelivr.com/package/npm/ramda.

**Comment by buzzdecafe** [comment]
Yes, the website will get updated when the next version (0.25) drops, which should be soon.

**Comment by buzzdecafe** [comment]
closing, 'cuz this is done, just not published yet
