### ISSUE TITLE
Support for functors, applicatives and monads ?

### ISSUE THREAD

**Issue by acmoune** [ramda/ramda#2290]
I am just starting with javascript functional programming, and discovered that functors, applicatives and monads are essentials, but when I search for monad in your doc I have no entry.

I know my question not really belongs to here but I would like to know if there is a javascript library that brings support for those types in javascript ? Or does every developer have to manage to create his functor type and so on ?  I have found monet on npmjs, but its stats are very low (about 5k dowload last month, in all the planet), it should not be the defacto.

I ask my question here because ramda is becoming the way to go in FP, so please, how do you expect us to create our own functor, applicative and monad INSTANCE ?

**Comment by Qquanwei** [comment]
common support monad/functor/applicative in follow repo
https://github.com/ramda/ramda-fantasy

**Comment by acmoune** [comment]
@Qquanwei thanks.
