### ISSUE TITLE
changelog should show minor versions

### ISSUE THREAD

**Issue by titouandk** [ramda/ramda#2291]
I think `CHANGELOG.md` should show minor versions upgrades as well.

Currently, the changelog redirect to the upgrade guides, showing only changes for major versions.

Based on the changelog, I upgraded to 0.24.0 instead of 0.24.1. Ouch.

Thanks!

**Comment by CrossEye** [comment]
Agreed that we should show them, which means that there should be a (usual trivial) upgrade guide for these minor versions.  That would then reflect in the changelog.

In this case, [0.24.1][ve] has a small fix to `memoize`, and then only documentation changes.

If you're interested in creating release notes for this, we'd love to have them.

  [ve]: https://github.com/ramda/ramda/compare/v0.24.0...v0.24.1

**Comment by kedashoe** [comment]
@titouandk thank you for reporting this, see #2296

**Comment by CrossEye** [comment]
Thanks, @kedashoe!
