### ISSUE TITLE
Add flattenProps (or mergeAllProps) function

### ISSUE THREAD

**Issue by BjornMelgaard** [ramda/ramda#2295]
Example on typescript

```
import { curry, props, mergeAll } from 'ramda'

/**
 * Function that does the same as object spread
 *
 * example:
 * // this statements are equal
 * let propsCopy = { ...obj.foo, ...obj.bar }
 * let propsCopy = flattenProps(['foo', 'bar'], obj)
 */
export const flattenProps = curry<string[], object, object>(function(
  propNames: string[],
  x: object
): object {
  return mergeAll(props(propNames, x))
})

```

**Comment by CrossEye** [comment]
This, in all honesty, is probably what `props` **should** have been.

I don't know if I like the name, and I think that implementation won't work (only one argument passed to `mergeAll`?)  But I like the idea, and it's easy enough to implement.

This (untested) version would probably work, but is not in our usual style:

```js
(keys, obj) => zipObj(keys, props(keys, obj))
```

(I guess with a `curry` wrapped around it.)

If you want to create a more complete implementation, I'd be interested in a PR.

**Comment by BjornMelgaard** [comment]
Glad you like the idea)

> only one argument passed to mergeAll?

?? mergeAll has signature `[{k: v}] → {k: v}`

my version works

**Comment by BjornMelgaard** [comment]
the `flattenProps` name is because recompose has `flattenProp`, but yes, im looking for better name

**Comment by BjornMelgaard** [comment]
https://github.com/ramda/ramda/pull/2297

**Comment by CrossEye** [comment]
> ?? mergeAll has signature [{k: v}] → {k: v}

Sorry, was thinking of `merge`.

**Comment by CrossEye** [comment]
Now that I see the implementation, I realize that I misunderstood.

I thought you were doing something like

```js
foo(['a', 'd'], {a: 1, b: 2, c: 3, d: 4}); //=> {a: 1, d: 4}
```

which seems a much better API than `props`:

```js
props(['a', 'd'], {a: 1, b: 2, c: 3, d: 4}); //=> [1, 4]
```

Now that I understand this, I'm afraid I'm less interested.

This doesn't seem to likely have a large enough audience to justify including it, and it's simple enough to implement oneself as `compose(mergeAll, props)` when necessary.

I'm very sorry for the misunderstaning.

Is there anyone else who wants to champion this function?  If not, this could certainly go in the [Cookbook][cb], and you might speak to @char0n about getting this in [ramda-adjunct][ra].

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [ra]: https://github.com/char0n/ramda-adjunct

**Comment by BjornMelgaard** [comment]
> I thought you were doing something like
> 
> foo(['a', 'd'], {a: 1, b: 2, c: 3, d: 4}); //=> {a: 1, d: 4}

its pick :smile:

**Comment by BjornMelgaard** [comment]
I still think that this function is very useful: it occurs from time to time in [react-apollo docs](http://dev.apollodata.com/react/using-with-types.html#props)

```
const withCharacter: OperationComponent<Response, InputProps, Props> = graphql(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  }),
  props: ({ data }) => ({ ...data })
});

``` 

and many other places (cant remember)

**Comment by CrossEye** [comment]
`pick`!!  I **knew** I'd seen that API.  (OK, so I [wrote it][co] long before Eweda morphed into Ramda.  I'm getting old!

> it doesnt matter that this function is easy to implement as far as it useful

Agreed, but we also can't take every useful function.  Ramda is probably already too large.  So to be included a function usually must have someone on the core team promoting it.  The only other ones we're likely to consider are those that are useful and difficult for users to create themselves or those for which we've gotten many requests<sup>*</sup>.  If we didn't have such considerations, we'd be in the thousands of functions already.

I was ready to promote this one when I thought it was something else (that I also mistakenly thought was missing :smile:), but I believe I don't feel that way once I understood it correctly.

Again, I apologize for the misunderstanding.  And feel free to try to convince us that it's important enough.  There are a number of core developers; perhaps one of them feels the same as you do.

----------
<sup>*</sup> I suppose there is another category of things we accept: ones that add consistency or symmetry to the library, as when we had `head` and `tail`, and someone argued for `last` as well: we also included `init` for symmetry

  [co]: https://github.com/CrossEye/eweda/commit/3fedd7ffca614b3bd183a830c200361824e96f8c#diff-91452c4737e0e4f3830175572840f99c

**Comment by BjornMelgaard** [comment]
> I'm getting old!

:bowing_man: 

No worries, ramda-adjunct is perfect place for this, made pr)

**Comment by char0n** [comment]
Will incorporate into ramda-adjunct under name `mergeProps` and will add to ramda cookbook. Thanks all!

**Comment by char0n** [comment]
Note: added to [cookbook](https://github.com/ramda/ramda/wiki/Cookbook#mergeprops)
