### ISSUE TITLE
Add adjustWith & updateWith?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2302]
adjust or update first satisfied item in the list
```js
adjustWith :: (a → a) → predicate → [a] → [a]
const adjustWith =  (transformer, pred, list) => R.converge(
    R.adjust(transformer),
    [
      R.findIndex(pred),
      R.identity,
    ]
  )(list);
```

```js
const data = [
  {id: 1, name: 'Jack'},
  {id: 2, name: 'Pony'},
];
adjustWith(R.evolve({ name: toUpper }), R.whereEq({ id: 1 }), data)

// output
[
  {id: 1, name: 'JACK'},
  {id: 2, name: 'Pony'},
];
```

**Comment by CrossEye** [comment]
While I like the basic idea, I run into some sort of wall with it.  If I pass a predicate and an action to a multivariate container I would assume that this action would apply to everything that matches the predicate, not just to the first match.  That would mean a change to your implementation.

But if we were to change it this way, then we are stray pretty far from what `adjust` does.

I don't see a wonderful solution.  Any ideas?

**Comment by adispring** [comment]
>  If I pass a predicate and an action to a multivariate container I would assume that this action would apply to everything that matches the predicate, not just to the first match.

What's the meaning of `a multivariate container`? Can you give an example of this situation?

**Comment by CrossEye** [comment]
Sorry, that was silly, but I simply mean a container that can hold more than one value, such as a list (or Array), a tree, a queue, etc.

Moreover that was phrased poorly even with this understood.  It should read something more like:

> If I pass a predicate, an action, and a multivariate container to a function, I would assume that the function would apply the action to every value in the container that matches the predicate, not just the first match.

**Comment by adispring** [comment]
> I would assume that the function would apply the action to every value in the container that matches the predicate, not just the first match.
According to my understanding, if the `multivariate container` is the parameter(list) passed into `adjustWith`, there can be two version of adjustWith: `adjustWith` and `adjustAllWith`; else if the `multivariate container` means every iterated item of the list, it's up to the action how to adjust every item?

**Comment by asaf-romano** [comment]
I'm for it.

The first-only update is extremely valuable indeed, especially in the UI world, in which very often a  set/map is in fact stored as a list, for practical reasons such as user-facing ordering. Then, rather than intended ``assocPath([id, "enabled"], true, accounts)``, one needs to find the account with that id and update it, or do something like ``map(when(...```, which always feels a little strange.

I think having adjustAllWith, updateAllWith would indeed make the situation clearer, though it's harder to make the case for them (esp. for updateAllWith)

**Comment by CrossEye** [comment]
I'm playing catch-up again.

I think with the `All` variant, I would at least be interested.  I would love to see a PR.  I think we need to balance this against a concern about adding still more functions to the library.  But this one, unlike many of our other object/array manipulation functions, does not seem amenable to lenses.  So it's certainly worth discussing.

**Comment by adispring** [comment]
OK, I'll make a PR.

**Comment by polytypic** [comment]
> But this one, unlike many of our other object/array manipulation functions, does not seem amenable to lenses.

It can be done with [traversals](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbwJZwBcMAjADQxgIC2ApsQOQBSCwA1gwL5m4HEBMFKnUYAFcAE8uPALpYsAegUwAggBs1MakmAALWhAB0WADKHqIOHgBmEgBQYztNbWoQKZgO76wdgEqG3rQATrQAogCOdvhEpJwAlPEUDMK0DDI8AVAgAKoADnkhPIjI8UA) and [partial lenses](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbwJZwBcMAjADQxgIC2ApsQOQBSCwA1gwL5m4HEBMFKnUYAFcAE8uPALpYsAegUwA8mAA2EmADM8AJ2gxqSYAAsAdFgAy56iDh5tEgBQYbusHGcAlcwHdTWj1aAFEAR2d8IlJOAEpYigZhWgYZHl8oEABVAAccoJ5EZFigA).

**Comment by polytypic** [comment]
Note that `adjustWith` as defined in the original issue adjusts the last element of the array in case nothing matches the predicate.  See [here](http://ramdajs.com/repl/#?const%20adjustWith%20%3D%20%20%28transformer%2C%20pred%2C%20list%29%20%3D%3E%20R.converge%28%0A%20%20%20%20R.adjust%28transformer%29%2C%0A%20%20%20%20%5B%0A%20%20%20%20%20%20R.findIndex%28pred%29%2C%0A%20%20%20%20%20%20R.identity%2C%0A%20%20%20%20%5D%0A%20%20%29%28list%29%3B%0A%0Aconst%20data%20%3D%20%5B%0A%20%20%7Bid%3A%201%2C%20name%3A%20%27not%20to%20be%27%7D%2C%0A%20%20%7Bid%3A%202%2C%20name%3A%20%27touched%27%7D%2C%0A%5D%3B%0A%0AadjustWith%28R.evolve%28%7B%20name%3A%20toUpper%20%7D%29%2C%20R.whereEq%28%7B%20id%3A%201331%20%7D%29%2C%20data%29).  This is a nice example of the fact that `findIndex` returning `-1` does not compose.

**Comment by CrossEye** [comment]
> It can be done with [traversals](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbwJZwBcMAjADQxgIC2ApsQOQBSCwA1gwL5m4HEBMFKnUYAFcAE8uPALpYsAegUwAggBs1MakmAALWhAB0WADKHqIOHgBmEgBQYztNbWoQKZgO76wdgEqG3rQATrQAogCOdvhEpJwAlPEUDMK0DDI8AVAgAKoADnkhPIjI8UA) and [partial lenses](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBAJgQygmBeGBtAUAbwJZwBcMAjADQxgIC2ApsQOQBSCwA1gwL5m4HEBMFKnUYAFcAE8uPALpYsAegUwA8mAA2EmADM8AJ2gxqSYAAsAdFgAy56iDh5tEgBQYbusHGcAlcwHdTWj1aAFEAR2d8IlJOAEpYigZhWgYZHl8oEABVAAccoJ5EZFigA).

Oh yes.  But the style lenses used by Ramda mean that you have a `setter` and that is certainly not possible when trying to match an arbitrary predicate.

**Comment by CrossEye** [comment]
> This is a nice example of the fact that `findIndex` returning `-1` does not compose.

What it really makes me observe is that we tried to do too much when we handled negative indices.  We added unwarranted complexity.
