### ISSUE TITLE
Can someone accept this pr for @types/ramda

### ISSUE THREAD

**Issue by BjornMelgaard** [ramda/ramda#2304]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18763

authors are not answering

**Comment by buzzdecafe** [comment]
nobody here has any control over what goes on over there.

**Comment by BjornMelgaard** [comment]
@buzzdecafe do you mind moving typings from `@types/ramda` to ramda (like in [ramda-adjunct](https://github.com/char0n/ramda-adjunct/blob/master/src/index.d.ts))

**Comment by CrossEye** [comment]
@BjornMelgaard: Few of the regulars here have the expertise to maintain it.  Perhaps, ... @donnut are you interested?

**Comment by BjornMelgaard** [comment]
Closing in favor of [npm-ramda](https://github.com/types/npm-ramda/)
