### ISSUE TITLE
ts typings for path must return any

### ISSUE THREAD

**Issue by BjornMelgaard** [ramda/ramda#2307]
currently `path` has this typings 

```ts
        path<T>(path: Path, obj: any): T;
        path<T>(path: Path): (obj: any) => T;
```

but it must be 

```ts
        path(path: Path, obj: any): any;
        path(path: Path): (obj: any) => any;
```

See [dt common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes) section about `function parseJson<T>(json: string): T;` and [my comment about similar mistake in lodash.get](https://github.com/Microsoft/TypeScript/issues/16#issuecomment-329291741)

**Comment by BjornMelgaard** [comment]
Closing in favor of [npm-ramda](https://github.com/types/npm-ramda/)

**Comment by CrossEye** [comment]
Given this comment, https://github.com/ramda/ramda/pull/2306#issuecomment-335082855, can this be closed?
