### ISSUE TITLE
OR type

### ISSUE THREAD

**Issue by yonatanmn** [ramda/ramda#2308]
Hi. 
Going through the documentation and js-doc code.
in [split](https://github.com/ramda/ramda/blob/v0.24.1/src/split.js) there is a param `sep` that can be either string or regexp (`@param {String|RegExp} sep`)

Similar vertical bar in [adjust](https://github.com/ramda/ramda/blob/v0.24.1/src/adjust.js) => `@param {Array|Arguments} list` but here I don't think it means "or". I guess it means `Array<a>`.

Maybe I'm not reading it right.

**Comment by kedashoe** [comment]
It is meant to mean "or" I think. So eg in the case of `adjust` the last parameter can be either an array or an [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments).
