### ISSUE TITLE
is it possible to extract changed properties?

### ISSUE THREAD

**Issue by davidparker** [ramda/ramda#2312]
Hi
Just wondering if and how i could extract properties from a changed / updated object.

Example

`
var original = {test:1, test2:2, test3:3};
var editable = R.clone(original);
editable.test2 = 6;

var changes = [ can i ramda editable, to get ] ==> { test2: 6 };

ta
`

I think I have worked it out as:

`
const orig = {a: 1, b: 2, c: 3}
let edited = merge(clone(orig),{b:7});
let user = {}

merge(user,reject(isNil, 
mergeWith(function(l,r){
  return (equals(l,r) === false) ? l : null
},edited,orig)));

`

seems to work

**Comment by svozza** [comment]
There's no need to clone the object, `merge` will not mutate the original.

**Comment by davidparker** [comment]
Oh okay thanks
