### ISSUE TITLE
both is splitting characters and returning an array

### ISSUE THREAD

**Issue by davidparker** [ramda/ramda#2316]
Just been trying to check if a string is something and that is matches ( indexOf )  and run that as a both.

`
var isSomething = R.not(R.isNil(R._));
var isMatching = R.test(/pick/,R._);
var checker = R.both([isSomething, isMatching]);
checker('pick');
`

output = [false, false, false, false, false, false, false, false]

if i run checker('1'); => [false, false]

just seems really odd and does not match up to docs description

**Comment by kurtmilam** [comment]
This is probably a good question for the [Ramda gitter channel](https://gitter.im/ramda/ramda).

It's not entirely clear to me what output you expect given the input you've shown, but these changes (which you can also see in the Ramda REPL [here](https://goo.gl/fporq4)) may point you in the right direction:

```js
var isSomething = R.complement(R.isNil);
var isMatching = R.test(/pick/);
var checker = R.both(isSomething, isMatching);
checker('pick');
// -> true
```

**Comment by davidparker** [comment]
oh sorry thought it was a bug was expecting a single false, or true.  but got an array :-)
