### ISSUE TITLE
`omit` in <0.25.0 has an ad hoc polymorphism issue

### ISSUE THREAD

**Issue by polytypic** [ramda/ramda#2330]
`omit` in versions before 0.25.0 suffers from an internal ad hoc polymorphism issue:

```bash
$ npm i ramda@0.24.1
demo@1.0.0
└── ramda@0.24.1 
$ node 
> const R = require('ramda')
undefined
> R.omit('lolbal', {lol: 1, bal: 2, adhoc: 'polymorphism'})
{ adhoc: 'polymorphism' }
```

That happens because `omit` used to internally use `contains`, which dispatches to `indexOf`.

I discovered this issue while porting a codebase using an earlier Ramda version to the latest 0.25.0. The codebase I ported sometimes had accidentally passed a string (name of a single property) to `omit` instead of an array of strings, which no longer accidentally works in Ramda 0.25.0.

Here is [the commit that fixed the behaviour of `omit`](https://github.com/ramda/ramda/commit/67d8b7a343adbbac04c170b654f69904e941994f).

**Comment by CrossEye** [comment]
Yes, it looks as though this was fixed as a side-effect of the performance enhancement in #2195.

**Comment by polytypic** [comment]
Note that apparently [`omit` with a string was even used in Ramda's own tests](https://github.com/ramda/ramda/commit/67d8b7a343adbbac04c170b654f69904e941994f#diff-6d17b506504f69507b835fc70a1a0260) previously.  Because of that I think the behaviour change should really be documented in the [upgrade guide](https://github.com/ramda/ramda/issues/2319).

**Comment by CrossEye** [comment]
Thank you very much for the heads-up!  I don't think there's any more to be done, as we're not fixing old versions.  So I'm closing this now, but feel free to disagree, and I'll reopen.
