### ISSUE TITLE
Add rangeWith?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2333]
rangeWith :: number -> number -> stepFn -> [number],

```js
rangeWith(1, 7, multiply(2)) => [1, 2, 4]
rangeWith(1, 7, inc) => [1, 2, ..., 6]
rangeWith(7, 1, dec) => [7, 6, ..., 2]
rangeWith(2, 9, square) => [2, 4, 8]
...
```

**Comment by CrossEye** [comment]
If nothing else, http://fr.umio.us/ranging-near-and-far/

But I don't thoroughly understand your examples.  Should the last one be something like this?:

```js
rangeWith(2, 20, square) //=> [2, 4, 16]
```

And how would you  distinguish 

```js
rangeWith(7, 1, dec); //=> [7, 6, ..., 2]
```

where the iteration stops when we hit something  *less than or equal to*  the stop value of `1` from the others in which it stops when we hit something no *greater than or equal to* the stop value ?

Do you have a suggested implementation for this?

Or maybe I should just go back to my original response: http://fr.umio.us/ranging-near-and-far/.

**Comment by adispring** [comment]
Yes, my last example is wrong.

> rangeWith(7, 1, dec); //=> [7, 6, ..., 2]
We can compare the first two arguments to decide the list is increasing or decreasing. I'll see the article.

**Comment by CrossEye** [comment]
> We can compare the first two arguments to decide the list is increasing or decreasing. I'll see the article.

But what if the function is not monotonic?  If it increases then decreases or vice versa?

**Comment by buzzdecafe** [comment]
i'd rather see the "stepping" function passed as the first param. then you can generate the `range` function you need.

I see @crosseye's point: how do we know when to stop generating the range?. Would this really require a terminating predicate? Er, that is getting a bit complicated

**Comment by Qquanwei** [comment]
I like `step` function as other programming language
```
step :: Number -> Number -> Number -> [Number]
```
step(begin, width, end)
step(0, 10, 30) => [0,10,20,30]
step(30, -10, 0) => [30, 20, 10, 0]

**Comment by scott-christopher** [comment]
I could see me using reaching for something like `step :: Number -> Number -> Number -> [Number]` more often than `rangeWith`, partly because we already have `R.unfold` for generating the sequences with a provided step function.

**Comment by CrossEye** [comment]
I find little need for a `step` function myself, but if people really want it (and it's come up twice recently...) then I don't have a major objection.  I might put the `width` as the first parameter, though, as that seems more likely to be static than the `begin` one.

**Comment by Bradcomp** [comment]
I still think there are some issues here...

What do these return (assuming the step is the middle param)? 
`step(0, 10, 35)` 
`step(30, -10, 5)`
`step(5, -1, 10)`

**Comment by CrossEye** [comment]
I believe the first two are quite tractable.  If the `end` value is inclusive, we swap out the `>` or `<` check we would have had for exclusive with `>=` or `<=`, but then the results should just fall out:

```js
step(0, 10, 35) //=> [0, 10, 20, 30]
step(30, -10, 5) ==> [30, 20, 10]
```

But the last example is harder.  And the same would be true even for a version with a predicate: how would we know it would ever change value?

**Comment by adispring** [comment]
@scott-christopher , 
I've just seen the `unfold` and its implementation. I found two points of `unfold` not very elegant: 

1. It's hard to understand what really `unfold` do, if not see the comment or implementation. ( the concept of `unfold` borrowed from other languages?) 

2. The `unfold`'s first argument (the iterate function) returns different types of values, that's wield, or not so functional.

**Comment by davidchambers** [comment]
@adispring, [`S.unfoldr`][1] is clearer than the Ramda equivalent. The function is copied from Haskell's [`unfoldr`][2].


[1]: https://sanctuary.js.org/#unfoldr
[2]: http://hackage.haskell.org/package/base-4.10.0.0/docs/Data-List.html#v:unfoldr

**Comment by CrossEye** [comment]
Yes, Ramda's `unfold` is problematic.  We really need to rewrite it.  But I'm not sure how to do it well unless we have a `Maybe` type.  But about that... https://github.com/ramda/ramda/issues/1731#issuecomment-337325830.

**Comment by CrossEye** [comment]
@adispring: Any further thoughts on `rangeWith`?  A `step` function or fixes to `unfold` should probably go in another issue.

**Comment by buzzdecafe** [comment]
FWIW i'd rather fix `unfold`

**Comment by adispring** [comment]
> i'd rather see the "stepping" function passed as the first param. then you can generate the range function you need.

```js
rangeWith :: stepFn -> number -> number -> [number]
```

I like "stepping" function as the first arguments too. Should User themselves guarantee the monotonic and the stop condition? I know this will make more or less chaos in practical. Or should we keep current status of `range`, more powerful and still keep simple (stable) is hard but important.

**Comment by CrossEye** [comment]
My thought is that `range` is fine as it is, and that we need to fix `unfold` anyway.  That could cover these cases.  I think that the only API that really adds flexibility and would still work in the Ramda way ends up being so close to `unfold` anyway.

**Comment by adispring** [comment]
Keep 'range' and fix 'unfold' is fine.
