### ISSUE TITLE
What is the best way to use Curry and JsDocs?

### ISSUE THREAD

**Issue by angeloocana** [ramda/ramda#2335]
Please forgive me if it is a dumb question or if its duplicated.

I just found this issue with no solution: https://github.com/jsdoc3/jsdoc/issues/1286
I would like to hear Ramda experts about this.

I love love love using **Curry**, but my Jsdocs goes away (types and descriptions) =/

Example:
```js
import { curry, filter, startsWith } from 'ramda';

/**
 * Get valid langKey in langs or return defaultLangKey
 * @func
 * @param {[String]} langs allowed lang keys ['en', 'fr', 'pt']
 * @param {String} defaultLangKey default browser language key
 * @returns {String} valid langKey
 */
const getValidLangKey = curry((langs, defaultLangKey, langKey) => {
  const currentLangKey = filter(l => startsWith(l, langKey), langs);
  return currentLangKey[0] || defaultLangKey;
});

export default getValidLangKey;

```

VS code txt when mouse over `getValidLangKey`:
```
(alias) getValidLangKey(t1: any, t2: any): any (+1 overload)
import getValidLangKey
```

Any suggestions?

**Comment by CrossEye** [comment]
Although, by popular demand, we use JSDoc for documenting Ramda, I am not a real user of it for my own projects.

So I'm afraid I don't have any suggestions.  As both manual currying and Ramda-style currying are getting more popular, I think the JSDoc folks really need to find a way to address it, but as far as I can see, such a fix belongs in their court.

I'd love to know that there is some trick to make this work now, but the issue you linked to makes me suspect that there isn't.

**Comment by semmel** [comment]
I find JSDoc extremely helpful for API documentation, for typing autocompletion and even for [unit testing](https://github.com/yamadapc/jsdoctest) but I have never seen a way to describe curried functions.
I agree with @CrossEye that this is on the part of the JSDoc folks.
Sometimes* however I might try something like this when declaring AMD modules:
```javascript
/** @type{function(Number): function(Number): Number | function(Number, Number): Number} */
const add = R.curry( (a, b) => a + b; );
```
Obviously this gets out of hand with longer parameter lists and complicated types.

*PhpStorm IDE has trouble extracting regular function signatures (`@params .., @return`, ...) out of AMD modules.

**Comment by CrossEye** [comment]
@semmel:

Hadn't seen [jsdoctest][jt] before, but I like it!

While I wouldn't mind adding such a type annotation if it would help, I'd have to learn more about the syntax, and think about just how complex it might get for our trickier functions.

  [jt]: https://github.com/yamadapc/jsdoctest

**Comment by semmel** [comment]
@CrossEye 
JSDocTest still needs some work to compete with the other established solutions. 
But it's great if you can write usage examples right in the source file *once* which are then used for unit testing *and* documentation. They are very similar: usage examples and unit tests.

Jsdoctest's syntax parser is brittle (spaces are important) but the syntax itself boils down to 
```javascript
// @example
//    func() -> result
//    func() -!> exception
//    pfunc() ~> promised value  (there is a fork for ~ instead of 'async')
//    pfunc() ~!> rejected value
```

Regarding Ramda however I am happy with the various efforts [npm-ramda](https://github.com/types/npm-ramda) or #2306) for Typescript definition files which enable good assistive typing in Php/WebStorm. I would suggest that ugly thing from my post above `/** @type{function(Number): function(Number): Number | function(Number, Number): Number} */` just just in rare cases and just for in-house code.
