### ISSUE TITLE
R.addIndex doesn't work in 0.25.0

### ISSUE THREAD

**Issue by acierto** [ramda/ramda#2339]
This line fails even on the stage of loading it by webpack.

```const mapIndexed = R.addIndex(R.map);```

![screen shot 2017-10-13 at 11 12 40](https://user-images.githubusercontent.com/2265094/31538979-7ccdf524-b007-11e7-8426-31a056b3a84e.png)

**Comment by CrossEye** [comment]
@acierto: You closed this right after opening it.  Can I assume that it was some other issue?  (Perhaps the changed import syntax?)
