### ISSUE TITLE
Deprecated propEq and propSatisfies?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2340]
`propEq` and `propSatisfies` are just two special case of `whereEq` and `where`, should these two Api be deprecated?

**Comment by asaf-romano** [comment]
I use those two (especially the former) for generated curried predicates. e.g
```js
const isAccountOfType = propEq("type");
```

**Comment by CrossEye** [comment]
Agree, @asaf-romano, the spec object functions can be quite useful, but they don't fit quite as well with Ramda's overall structure.

Anyone else want to argue for this, or should I close it?
