### ISSUE TITLE
npm test ignores tests in 'test/internal/' folder

### ISSUE THREAD

**Issue by kurtmilam** [ramda/ramda#2345]
I added some tests in `test/internal/` for https://github.com/ramda/ramda/pull/2344 and realized that they weren't being run when I executed `npm test`.

I tried using the glob `./test/**/*.js`, but mocha fell down when it encountered `test/helpers/test.examplesRunner.js`. Happy to issue a PR once I figure out the correct pattern to include files under `test/` and `test/internal` while excluding files in `test/helpers` and `test/shared`.

**Comment by CrossEye** [comment]
My take has always been that we test only public behavior.  `internal` is entirely for non-public behavior.  We should feel free to change its API as much as we like so long as the public tests pass.  If there's no public behavior affected by the internal behavior, then we should always leave it unspecified.

This is not a universally agreed-to philosophy, but it's a fairly common one, and I think its served Ramda well.

**Comment by kurtmilam** [comment]
I'm good with that. There were several test files in the `test/internal` folder already. At this time, they are not run when `npm test` is executed, but they can be run by explicitly specifying that folder (i.e. `mocha ./test/internal/*.js`).

**Comment by CrossEye** [comment]
Funny how that happens.  It's probably worth removing them.  But I'll worry about this a little later.
