### ISSUE TITLE
Uglify Error when trying to minify ramda

### ISSUE THREAD

**Issue by sepehr500** [ramda/ramda#2364]
I get the following error when uglifying ramda.

`ERROR in 1-4.chunk.js from UglifyJs Unexpected token: operator (>)
 [./node_modules/rambda/dist/rambda.esm.js:3,0][1-4.chunk.js:1934,20]`

has anybody seen this before?

**Comment by buzzdecafe** [comment]
there's no "b" in "ramda"

**Comment by sepehr500** [comment]
thanks!

**Comment by CrossEye** [comment]
Well spotted, @buzzdecafe!
