### ISSUE TITLE
Switch-cases in https://github.com/ramda/ramda/blob/master/source/internal/_arity.js

### ISSUE THREAD

**Issue by rahul1995** [ramda/ramda#2366]
It's more like a question. In [_arity.js](https://github.com/ramda/ramda/blob/master/source/internal/_arity.js), I see there are so many cases defined but the variables a0, a1, etc... are not being used. In each case, `apply` function is used with `arguments`. Is this redundant or am I missing something here?

**Comment by buzzdecafe** [comment]
yes, the point of `arity` is to set the correct `length` property on the function. The only way to set `length = n` that is to create a function with `n` arguments.

**Comment by rahul1995** [comment]
@buzzdecafe Thanks, I didn't know about function properties. Could you please tell me why properties of function objects can't be changed? I thought javascript treats them like any other object.

**Comment by buzzdecafe** [comment]
You can find some info here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

As you can see there, the `length` property is not writable.
