### ISSUE TITLE
R.or is not working properly

### ISSUE THREAD

**Issue by haasDev** [ramda/ramda#2367]
when using or I expect that when one of the two arguments are returning true then or would also return true.  Currently it seems as though it only returns true when the first argument is true.

See my snippet it the ramda repl:

http://ramdajs.com/repl/?v=0.25.0#?const%20body%20%3D%20%7B%0A%20%20patName%3A%20%27%27%2C%0A%20%20meetingId%3A%208%2C%0A%20%20phase%3A%20%2730%27%0A%7D%3B%0A%0Aconst%20getValue%20%3D%20R.prop%28R.__%2C%20body%29%3B%0Aconst%20checkEmpty%20%3D%20R.pipe%28getValue%2C%20R.isEmpty%29%3B%0Aconst%20checkNil%20%3D%20R.pipe%28getValue%2C%20R.isNil%29%3B%0Aconst%20isInvalid%20%3D%20R.or%28checkNil%2C%20checkEmpty%29%3B%0A%0Aconst%20invalidKeys%20%3D%20Object.keys%28body%29.filter%28isInvalid%29%3B%0Aconsole.log%28%7BinvalidKeys%7D%29%3B%0A%0Aconsole.log%28%27checkEmpty%20%3D%20%27%2C%20checkEmpty%28%27patName%27%29%29%3B%0Aconsole.log%28%27checkNil%20%3D%20%27%2C%20checkNil%28%27patName%27%29%29%3B%0Aconsole.log%28%27isInvalid%20%3D%20%27%2C%20isInvalid%28%27patName%27%29%29

**Comment by Bradcomp** [comment]
`R.or` takes 2 booleans and returns a boolean. You probably want to use `R.either` which takes functions as you would like to do.

**Comment by haasDev** [comment]
my bad. misread the documentation.  Thanks!

**Comment by CrossEye** [comment]
Yes, as @Bradcomp said, `either`.

Also, for future reference, there is a "Share" link in the top left of the REPL which will allow you to turn that monstrosity of a URL into https://goo.gl/grcYtT.

**Comment by haasDev** [comment]
awesome! Thanks for the pointer and help!
