### ISSUE TITLE
tap throws in empty Promise-chain

### ISSUE THREAD

**Issue by PutziSan** [ramda/ramda#2375]
(Not-)working example as REPL : https://goo.gl/WQfxZ3

**Comment by Bradcomp** [comment]
Hi @PutziSan, 

This was resolved, however I don't think it has been released yet. The fix is implemented [here](https://github.com/ramda/ramda/commit/37da98647bfd8f7a7907eb70ac62e3740b96ea4f)

**Comment by PutziSan** [comment]
Hi,
thx for the info, I just looked for open issues, sorry.
Are there any plans when it will be released?
