### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by rendall** [ramda/ramda#2377]
This isn't an issue, it's just to thank the ramda team for the hard work and sharp thinking that goes into this library.  

If you're not on the team and agree, gives a thumb's up!

If you're on the team, thanks again!  Keep up the good work! Even if we don't say it often enough, we users appreciate it.

**Comment by CrossEye** [comment]
Thank you.  It's always encouraging to hear kind words like that.  But do remember that there are [many][ra] [people][rd] [to][rr] [thank][rf].  It's very much a team effort.

  [ra]: https://github.com/ramda/ramda/graphs/contributors
  [rd]: https://github.com/ramda/ramda.github.io/graphs/contributors
  [rr]: https://github.com/ramda/repl/graphs/contributors
  [rf]: https://github.com/ramda/ramda-fantasy/graphs/contributors

**Comment by rendall** [comment]
Indeed, indeed!  It's wonderful to see such collective effort.

**Comment by tacomanator** [comment]
Thank you for also taking a relatively hard line on the philosophy behind Ramda's functionality and API. I'm sure it's not easy and you get a lot of flak for it, but those of us who appreciate thoughtful, principle driven development and maintenance applaud you. If nothing else, you've give the community a choice.

**Comment by CrossEye** [comment]
@tacomanator:

I actually think we get more flak from not being principled *enough*.  And that I sympathize with a lot more.  There are plenty of libraries out there to help you work with a less functional approach.  But there are only a few JS utility libraries that adopt a more strict FP approach.  (Hi [Sanctuary][sa]!) I'm glad you appreciate it, but please still feel free to tell us where we're steering wrong.

  [sa]: https://sanctuary.js.org/
