### ISSUE TITLE
composeK errors out if passed only one function as argument

### ISSUE THREAD

**Issue by niksosf** [ramda/ramda#2380]
Hi there, I don't know if this is by design (if so, perhaps we could add some explanation to the doc? ) but composeK with just one function passed in throws that compose (not composeK) `compose requires at least one argument` 

The source has this line where it `pop()` the last of the arguments of `composeK` and sending the rest to `compose`, which it clearly will complain if only one was passed to `composeK` to begin with. 
here's an example:
https://goo.gl/uf1sx4

Thanks for reading  this.

**Comment by davidchambers** [comment]
This sounds like a bug to me. Thanks for raising the issue.

**Comment by niksosf** [comment]
Thanks for looking into it. let me know if there's anything I could help.

Thank you * million for this wonderful lib.

**Comment by kedashoe** [comment]
Would you like to submit a PR @niksosf ?

**Comment by niksosf** [comment]
@kedashoe would love to contribute. Is there any code standard that the ramda team follows one should read up first?

**Comment by buzzdecafe** [comment]
@niksosf please start here: https://github.com/ramda/ramda/blob/master/CONTRIBUTING.md

**Comment by CrossEye** [comment]
`composeK` has been removed.  No longer relevant.
