### ISSUE TITLE
Could R.merge throw an error or some tips when pass in more than two arguments?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2382]
When I refactor some code which contains `R.merge`, I just add more objects to `R.merge`, and there's no tip for the wrong using of `merge`. Then QA found something wrong with the software, I debug for a while and found out that I should use `mergeAll` when merging more than two objects.

So In order to let ramda software development more friendly for SDE, could R.merge throw an error when pass in more than two arguments?

**Comment by davidchambers** [comment]
You may like to use [Sanctuary][1] to catch errors of this sort sooner rather than later.

```javascript
S.concat({x: 1, y: 2}, {y: 3, z: 4});
// => {x: 1, y: 3, z: 4}

S.concat({x: 1}, {x: 2}, {x: 3});
// ! Function applied to too many arguments
//
//   concat :: Semigroup a => a -> a -> a
//
//   ‘concat’ expected at most two arguments but received three arguments.
```


[1]: https://sanctuary.js.org/

**Comment by CrossEye** [comment]
Yes, Sanctuary is more likely to help with this than Ramda, who's philosophy has always included the idea that it doesn't particularly guide you, just offers you tools.  It rarely throws, and then only if there really seems no other way to proceed.

**Comment by adispring** [comment]
Sanctuary looks great, I'll try it when I have time.
