### ISSUE TITLE
Official Ramda plugin for ESLint

### ISSUE THREAD

**Issue by haskellcamargo** [ramda/ramda#2384]
I've been working on [this project](https://github.com/rung-tools/eslint-plugin-ramda) while [Mathias Schreck](https://github.com/lo1tuma) was working in [this one](https://github.com/lo1tuma/eslint-plugin-ramda). We've talking about unifying our projects into one and mine currently satisfies the rules defined by him also. Under https://github.com/rung-tools/eslint-plugin-ramda, there is already :white_check_mark: 100% code coverage and some basic simplifications and a lot of ideas about Ramda refactoring that would be useful. We believe that having this as a centralized official code base for ESLint rules for Ramda would be good for the community, so, we want to open to discussion the possibility to have a repository inside :ram: organization called `/eslint-plugin-ramda` with that, and having this as the official plugin.

Thanks in advance!

Best regards from @haskellcamargo and @lo1tuma!

**Comment by buzzdecafe** [comment]
First, this is cool. 

Second, I agree it makes sense to have a home under ramda org, my concern is: who would maintain it?

**Comment by haskellcamargo** [comment]
I would be proud to maintain the project, as long as I use Ramda all the time in my work, and everybody here where I work liked the feature. Also, maybe @lo1tuma too. Need to talk better to him.

**Comment by cuchi** [comment]
This is great!

I'm currently studying compilers and have some ideas going on, so I do not bother in helping as a maintainer too.

**Comment by lo1tuma** [comment]
I would love to help making this a successful eslint plugin and implementing some of the ideas we collected [here](https://github.com/lo1tuma/eslint-plugin-ramda/issues).

Maybe also @gilligan, who implemented the first [eslint-plugin-ramda](https://github.com/lo1tuma/eslint-plugin-ramda) rule with me, still has interest.

**Comment by CrossEye** [comment]
I would love to see this!  I'm with @buzzdecafe: so long as we have people interested in maintaining it, I think it would be great to include it inside the Ramda organization.

**Comment by haskellcamargo** [comment]
Having created the repository under :ram: organization, I can take care of moving the repository and @lo1tuma of publishing. There is, of course, documentation to do about everything. This we can do gradually.

**Comment by haskellcamargo** [comment]
I believe we have enough tests, rules and data for publishing the first release. @lo1tuma has access to `eslint-plugin-ramda` on `npm`. If possible, could somebody from :ram: organization create a repository give us initial access to continue the work?

**Comment by CrossEye** [comment]
@haskellcamargo:
I've just sent you an invite to become part of the Ramda team.  I believe once you accept that, you can initiate the transfer to Ramda.  When that's done, we can figure out who should be listed as collaborators.

**Comment by haskellcamargo** [comment]
@CrossEye could you please invite @lo1tuma too? He is the one who was working with me in the project and the owner of the `eslint-plugin-ramda` name. Thanks in advance!

**Comment by buzzdecafe** [comment]
i've added an eslint-plugin team, and invited @haskellcamargo and @lo1tuma

**Comment by CrossEye** [comment]
@cuchi: Would you like an invitation too?

**Comment by cuchi** [comment]
@CrossEye sure, I would be happy to help.

**Comment by CrossEye** [comment]
Sent

**Comment by mrosata** [comment]
@haskellcamargo I would like to help out where possible. Just let me know what the best way to help out would be. I think this would be an extremely helpful tool to have.

**Comment by haskellcamargo** [comment]
@mrosata we're still missing documentation for the current rules, configuration in some situations, scope resolving (for example, allow `map` and `R.map`) and rule suggestions. You can also contribute by suggesting simplifications and common patterns that could be caught by the linter or also implementing the _autofix_ feature for some rules. If you want too, we can add you as a collaborator there and provide more details about the tasks! I'm very happy seeing community engaged! :smile:

**Comment by haskellcamargo** [comment]
I'm closing this issue for now. @mrosata, we'll be opening issues under the `ramda-eslint-plugin` with the possible tasks from where we can continue the discussion. Congrats for everyone here and let's make the world functional again!
