### ISSUE TITLE
Flatten on object should flatten values

### ISSUE THREAD

**Issue by skallet** [ramda/ramda#2388]
I've noticed that flattening object yields empty list:
`flatten({0: ['a', 'b']}) // => []` 
Shouldn't it return same result as following code?
`flatten([ ['a', 'b'] ]) // => ['a', 'b']`

**Comment by CrossEye** [comment]
And what would this yield in that case?:

    flatten({foo: 1, bar: ['a', 'b'], baz: false})

And would that result be different for

    flatten({baz: false, bar: ['a', 'b'], foo: 1});

?

**Comment by skallet** [comment]
I think it should be same as:
`compose(flatten, values)`
If you pass an object to flatten fn you receive empty list and it can be confusing. Is there any reason for it?

**Comment by CrossEye** [comment]
I'm just not seeing why it should be that way.  If we did this, why wouldn't it also do something recursive with

    flatten({foo: 1, bar: {baz: 2, qux: [3, 4, [5, 6]]}, corge: [7, {waldo: [8, {fred: [9, 10]}]]);

?  The empty list is just the default for nothing there.  What would you expect from `flatten({})`?

**Comment by Bradcomp** [comment]
> I think it should be same as:
`compose(flatten, values)`

Why not just use that then? 

It's clearer on what you're actually doing, being that there are a bunch of edge cases that would have to be worked out to bake the behavior into `flatten`

**Comment by sjsyrek** [comment]
It seems to me that flattening an object has no meaning, at least not one you could apply consistently and automatically to any given object (unlike an array). However, you could supply for a given class of objects your own flatten method that would achieve the same effect. This is rather like the type class approach in Haskell, which also doesn't know how to flatten datatypes if you don't tell it how (e.g. by making an instance of monad).
