### ISSUE TITLE
add R.toBool, alias to R.complement(R.not)

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2389]
Sometimes, I want to judge the value `true` or `false`. `R.complement(R.not) ` can transform truth-y and false-y value to the corresponding Bool value, but a little bit long. So `R.toBool` is an convenient alias?

```js
const toBool = R.complement(R.not)
```

**Comment by git-in-my-anus** [comment]
there is already function [Boolean](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean) in js for exactly this purpose
