### ISSUE TITLE
Discrepancy between propOr and pathOr

### ISSUE THREAD

**Issue by mattgrande** [ramda/ramda#2391]
See REPL link here: https://goo.gl/7UGda4

It seems to me that `propOr` and `pathOr` behave differently.

```
const getProp1 = R.propOr([], 'x');
const getProp2 = R.pathOr([], ['x']);

getProp1({x: null});    // returns null
getProp2({x: null});    // returns []
```

Without checking the code, I'm guessing `propOr` uses `has` internally, whereas `pathOr` is just checking for a falsey result.

Is this expected, or is this a bug?

**Comment by CrossEye** [comment]
Yes, this is definitely a problem.  See #2394
