### ISSUE TITLE
Point-free object instantiation

### ISSUE THREAD

**Issue by haskellcamargo** [ramda/ramda#2392]
This issue proposes the implementation of a function to allow point-free programming while instantiating JS objects.

### The problem

```js
// :: User → Date
const getBirthday = pipe(
  path(['personal', 'birthday']),
  birthday => new Date(birthday)
)
```

As you can see, in some situations you are forced to use something like an arrow function because `new Date` won't return a function, but a value. In the specific situation, `Date` can be constructed without receiving `new`, but some other common structures, like `Map`, cannot.

### Proposed solution

A function that acts like `new` (`make`):

```js
const getBirthday = pipe(
  path(['personal', 'birthday']),
  make(Date)
)
```

So:

`make :: Object → (...*) → Object`

This can make interop with other JS libraries that aren't compliant with Fantasy Land a little less painful.

**Comment by Bradcomp** [comment]
Would this be any different from [`construct`](http://ramdajs.com/docs/#construct)?

**Comment by haskellcamargo** [comment]
Oh, my...!

There is already a function! 
I read all the documentation at least 10 times this year and didn't notice that!
It is exactly that!
