### ISSUE TITLE
Spread the love: transduce + chain

### ISSUE THREAD

**Issue by Izhaki** [ramda/ramda#2395]
# The secretive laziness

As some of you know, [some of us are using Ramda to compose lazy sequences](https://github.com/ramda/ramda/issues/2356). Although the library supports it, it isn't advertised anywhere, which means people like me have used [lazy.js](http://danieltao.com/lazy.js/) along side Ramda, although the latter alone would do.

# Serendipity

Now if you're lazy, the way to surf the docs would be to search for "transducer" or "transformer".

I've been looking for months for a way to do something. But the Ramda docs said "No can do" (or more precisely, it didn't say "can do"). So I have spent 3 weeks writing an [original lazy tree traversal implementation](https://github.com/Izhaki/gefri/blob/fp/src/core/LazyTree.ts).

Then one day, by sheer accident, my eyes landed on `chain`. Not a single hint it would work, but I had to give it a go. And guess what?

[[REPL]](https://goo.gl/jzksBF)

```
const tapLog = R.tap( (what) => console.log(what) )

const suits = ['♠', '♥', '♦', '♣']
const ranks = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'J', 'Q', 'K', 'A']

const addSuit = ( rank ) => R.xprod( [rank], suits)

var transducer = R.compose(
  R.chain(addSuit),
  tapLog,
  R.take(2)
);

R.into([], transducer, ranks);
```

Outputs:
```
["1","♠"] // console.log
["1","♥"] // console.log

// => [["1", "♠"], ["1", "♥"]]
```

So it turns out `chain` works with transducers.

# Why is it such a big deal?

Because it allows one-to-many lazy traversal, which enables the colossal ability to lazily traverse trees and graphs, not just lists.

Here's [an example](https://repl.it/@Izhaki/Language-influences-Lazy-Graph-Traversal-using-Ramda-paths), showing both breadth- and depth- first lazy graph traversal, albeit naïve.

# The issue

There is no mentioning of this in the docs.

If `chain` plays nicely with `transduce`, please let it be known.

**Comment by kedashoe** [comment]
Would you like to submit a PR to update the docs to match other functions which mention transducer support?

**Comment by Izhaki** [comment]
Sure.

I guess that will simply involve adding:

> Acts as a transducer if a transformer is given in list position.

?

**Comment by kedashoe** [comment]
:+1:

**Comment by Izhaki** [comment]
Seems like it has been done already:

https://github.com/ramda/ramda/commit/63778388b8bba6168c0fb04864caa6544bc38b68

Hmmm... by you @kedashoe

**Comment by kedashoe** [comment]
whelp, glad we got that cleared up :|

**Comment by buzzdecafe** [comment]
nonetheless, thanks for the excellent example!

**Comment by Izhaki** [comment]
@kedashoe @buzzdecafe and @CrossEye 

Forgive me for this is more of a question, but one too long for gitter and one that others landing on this issue may benefit from.

# Chain branch isn't lazy.

If you look at this revised example:

```javascript
const tapLog = R.tap( (what) => console.log(what) )

const suits = ['♠', '♥', '♦', '♣']
const ranks = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'J', 'Q', 'K', 'A']

const addRank = (suit) => R.map(concat(suit),ranks)

var transducer = R.compose(
  R.chain(addRank),
  tapLog,
  R.take(2)
);

R.into([], transducer, suits);
```

Then you probably know that `R.map(concat(suit),ranks)` will not be lazily evaluated - all the ranks will be mapped, and only then `chain` will 'pipe' them one by one.

This is not an issue, unless you are mapping 680k graph nodes.

# Can this be achieved?

Now I've looked at the implementation of chain, and I believe that the `_makeFlat` branch makes this impossible to achieve?

However, both the [tests for reduce](https://github.com/ramda/ramda/blob/v0.25.0/test/reduce.js) and [the source](https://github.com/ramda/ramda/blob/v0.25.0/source/internal/_reduce.js) show examples of 'Iterable' (either `symIterator` or `.next()`).  Intuitively, I thought it would be possible to return something like this from the mapper function given to the chain function; but like many other intuitions, this one was as good as John Lennon's decision to write songs whilst sober.

Yet I have a feeling that if you wire things right, you can get it done. But for the life of me I can't figure out how.

# Goal

Essentially what I'm after is in addition to the laziness on the tranducer sequence, laziness on the chain branch (which can do one to many).

By laziness I mean - one array item at a time. Like so:

![](https://cdn-images-1.medium.com/max/800/1*rEOyWd0MTPv_NZvzDaFbkA.gif)

**Comment by polytypic** [comment]
I'm pretty sure it can be achieved with transducers, but you will need to replace the `chain` implementation.  Here is [a simple stream implementation](http://ramdajs.com/repl/?v=0.25.0#?const%20suits%20%3D%20%5B%27%E2%99%A0%27%2C%20%27%E2%99%A5%27%2C%20%27%E2%99%A6%27%2C%20%27%E2%99%A3%27%5D%0Aconst%20ranks%20%3D%20%5B%271%27%2C%20%272%27%2C%20%273%27%2C%20%274%27%2C%20%275%27%2C%20%276%27%2C%20%277%27%2C%20%278%27%2C%20%279%27%2C%20%27J%27%2C%20%27Q%27%2C%20%27K%27%2C%20%27A%27%5D%0A%0A%2F%2F%20Processes%20one%20item%20at%20a%20time.%20%20Does%20not%20fuse%20in%20V8%2C%0A%2F%2F%20which%20requires%20you%20to%20use%20methods%20to%20achieve%20fusion.%0A%0Aconst%20S_fromArray%20%3D%20xs%20%3D%3E%20sink%20%3D%3E%20%7B%0A%20%20for%20%28let%20i%3D0%3B%20i%3Cxs.length%3B%20%2B%2Bi%29%0A%20%20%20%20if%20%28sink%28xs%5Bi%5D%29%29%0A%20%20%20%20%20%20return%20true%0A%7D%0A%0Aconst%20S_map%20%3D%20fn%20%3D%3E%20stream%20%3D%3E%20sink%20%3D%3E%20stream%28x%20%3D%3E%20sink%28fn%28x%29%29%29%0A%0Aconst%20S_chain%20%3D%20fn%20%3D%3E%20stream%20%3D%3E%20sink%20%3D%3E%20stream%28x%20%3D%3E%20fn%28x%29%28sink%29%29%0A%0Aconst%20S_take%20%3D%20n%20%3D%3E%20stream%20%3D%3E%20sink%20%3D%3E%20%7B%0A%20%20let%20i%20%3D%200%0A%20%20return%20stream%28x%20%3D%3E%20%7B%0A%20%20%20%20if%20%28i%20%3D%3D%3D%20n%20%7C%7C%20%28%2B%2Bi%2C%20sink%28x%29%29%20%7C%7C%20i%20%3D%3D%3D%20n%29%0A%20%20%20%20%20%20return%20true%0A%20%20%7D%29%0A%7D%0A%0Aconst%20S_toArray%20%3D%20stream%20%3D%3E%20%7B%0A%20%20const%20xs%20%3D%20%5B%5D%0A%20%20stream%28x%20%3D%3E%20%7B%20xs.push%28x%29%20%7D%29%0A%20%20return%20xs%0A%7D%0A%0AS_toArray%28%0A%20%20S_take%282%29%28%0A%20%20%20%20S_chain%28suit%20%3D%3E%20S_map%28rank%20%3D%3E%20suit%2Brank%29%28S_fromArray%28ranks%29%29%29%0A%20%20%20%20%20%20%20%20%20%20%20%28S_fromArray%28suits%29%29%29%29) that achieves the desired one-at-a-time processing.

**Comment by Izhaki** [comment]
@scott-christopher has [answered my question on SO](https://stackoverflow.com/a/47843887/1179377). I share the solution here:

```javascript
const combineWith = (fn, xs) => xf => ({
  // proxy both `init` and `result` straight through
  // Note that init is ignored by R.transduce, and result just
  // need to return identity (see internal/_xfBase.js, as used by _xtap.js)
  '@@transducer/init': xf['@@transducer/init'].bind(xf),
  '@@transducer/result': xf['@@transducer/result'].bind(xf),

  // combine the item at each step with every element from `xs`
  // using `fn`, returning early if `reduced` is ever encountered
  '@@transducer/step': (acc, item) => {
    for (let i = 0; i < xs.length; i++) {
      acc = xf['@@transducer/step'](acc, fn(item, xs[i]))
      if (acc['@@transducer/reduced']) return acc
    }
    return acc
  }
})

const suits = ['♠', '♥', '♦', '♣']
const ranks = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'J', 'Q', 'K', 'A']

const tapLog = R.tap(console.log.bind(console, 'tapLog'))

const transducer = R.compose(
  combineWith(R.concat, ranks),
  tapLog,
  R.take(2)
)

console.log('result', R.into([], transducer, suits))
```
