### ISSUE TITLE
R.pointfree?

### ISSUE THREAD

**Issue by tycho01** [ramda/ramda#2399]
I wonder if it might be worthwhile to somehow include [`pointfree`](https://github.com/tycho01/pointfree) as a function in Ramda. Usage:

```js
// generates curried function versions of JS functions/methods
var P = R.map(pointfree)({ String, Number });

// pointfree method, with method-calling object as the last argument:
P.String.replace(/o+/g, 'b')('foo') // 'fb'
// pointfree function, first argument provided separately last:
P.String.includes('f', 2)('food') // false
// optional arguments still work, using default values if not supplied:
P.String.includes('f')('food') // true
```

This expanded on some of the prior art discussed in #1367, notably on:
- on [`R.invoker`](http://ramdajs.com/docs/#invoker) by letting one convert in batch by avoiding length concerns by focusing on param order instead of doing full currying as well. This leaves users the freedom to curry the rest if they want, without breaking optional argument support for others.
- on @neftaly's [ImmutableJS application](https://github.com/ramda/ramda/issues/1367#issuecomment-279887477) of `invoker` by generalizing this to any other prototype.
- on @ccorcos's ES6 `Proxy`-based `fluent-pointfree` by playing nice with both methods and functions.
- and on Ramda's existing function library, both in providing a middle way between pointfree support and optional argument support, as well as by expanding its pointfree repertoire to JS functions not currently included.

Edit: dropped auto-curry in favor of optional argument support, simplifying usage while leaving users more freedom.

**Comment by tycho01** [comment]
A potential source of contention here might be handling of optional arguments, as we can't have both that *and* currying. Currently by default optional args are chopped off in favor of currying so as to use their default values, unless one were to use explicitly specify arities (`foo` -> `foo3`, or in a different mode, `foo(3)`).

Perhaps I should note there is a middle road here in weak currying, i.e. only transforming `(a, b, c?, d?) => ...` into `(b, c?, d?) => (a) => ...`, leaving optional args intact in pointfree mode, allowing the user to explicitly invoke full currying if they still felt so inclined. This has a precedent in `R.compose` / `R.pipe`, which also leave the decision to curry up to the user. I personally like this compromise.

**Comment by CrossEye** [comment]
I find this function fascinating.

I don't know yet if I think it's a good fit for Ramda.  It's going to take a while to sink in.

It doesn't do as much as one might hope.  For instance, the methods on `Array.prototype` are not enumerable, so they can't be called with this.  Second, the change mentioned in your "Edit" note makes the output functions feel quite non-Ramda-ish:

```js
P.String.substring(1)('abc') //=> 'bc'
P.String.substring(1, 2)('abc') //=> 'b'
```

But I am still intrigued.

**Comment by tycho01** [comment]
Feel free. I'll try to put both approaches in the readme, though currying is buggy atm.

`Array` had a bug for me too (`R.map` dispatch on `map` key), which I fixed now; enumerability works through `Object.getOwnPropertyNames`, though it's ES6 (IE would need a polyfill).
