### ISSUE TITLE
Propose to introduce another way of partial import

### ISSUE THREAD

**Issue by kopach** [ramda/ramda#2405]
Would be great to have a similar approach for partial import as in [rxjs](http://reactivex.io/rxjs/). So, something like this:

```
import { R } from 'ramda/core';
import 'ramda/add/operator/map';

R.map(x => x + '!!!'); // etc
```

**Comment by CrossEye** [comment]
```js
import map from 'ramda/src/map'
```

**Comment by kopach** [comment]
@CrossEye, thanks for your answer. Problem is, that in such a case, context is not saved - therefore readability gets worse. What I would like to have instead - main `R` object with methods I need. 
So, not `map(...)` but `R.map(...)`

**Comment by JasonSooter** [comment]
```import * as R from 'ramda'``` seems to be the recommended tree-shaking compatible way to import if using R. is desired. Based on a few previous issues. Feel free to correct me if there's a better way

**Comment by kopach** [comment]
hm. if it's tree-shaking compatible - then it's a perfect solution for me. have to test this :)

**Comment by CrossEye** [comment]
@kopach: Any news on this?

**Comment by kopach** [comment]
@CrossEye haven't had time to test this yet. Will do this weekend and let you know ;)

**Comment by kopach** [comment]
Ok, tested it. Tree shaking works just fine with `import * as R from 'ramda'` 
Thanks for a help

**Comment by kopach** [comment]
Sorry for misleading, but after some deeper testing it appears that tree shaking is not working with ramda.  Initially I thought it woks just because webpack for some reason doesn't recognize ramda as independent module during producing statistic file. So, all the alanyzing tools I've tried e.g.: https://webpack.github.io/analyse/ or [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) do not show ramda at all. So, I wrongly assumed that ramda  correctly tree-shaked :(. But after I've checked file size of bundle - it's bigger just as size of ramda :)

I've also tried to import just needed parts `import {compose, join, juxt, toUpper, head, tail} from 'ramda';` or use `ramda/es` - same result all the time. Build always is about 300kB bigger.

**Comment by JasonSooter** [comment]
This is the same result I have found. I have settled on importing ramda like below:

```import clone from 'ramda/es/clone'```

The file size and module count increase if I place:

```import * as R from 'ramda'```

anywhere in the project.

**Comment by CrossEye** [comment]
@Andarist: Any suggestions here?

**Comment by Andarist** [comment]
@kopach @JasonSooter would be great if you could check previous discussions about this - [here](https://github.com/ramda/ramda/issues/2355) and in another thread starting from [this comment](https://github.com/ramda/ramda/pull/2254#issuecomment-328061077). Would be good to have a confirmation if you observe things mentioned in those issues or are you facing something else. Example repo would be really helpful for me to assess what's the exact reason too.

Unfortunately webpack's tree-shaking algorithm is not perfect - using `ModuleConcatenationPlugin` can help a lot (this is gonna be on by default in webpack@4 but it's very much already usable in webpack@3). Also webpack@4 should help a lot even further as its gonna read `sideEffects` field from `package.json`.

**Comment by JasonSooter** [comment]
@Andarist Well adding the ```ModuleConcatenationPlugin``` seems to have done the trick for me. I can alternate between the 2 options I mentioned above and I get the same size and module count. 

I used the simple setup located here:

[](https://webpack.js.org/plugins/module-concatenation-plugin/)

Let me know if there is anything else I can confirm for you.

**Comment by Andarist** [comment]
@JasonSooter If `ModuleConcatenationPlugin` did reduce your bundle sizes, like a lot, then there is nothing more to confirm. The issue is known and the behaviour need to be tweaked in the webpack itself (as mentioned webpack@4 should do a lot better though, thanks to `sideEffects` field, when it gets released)

**Comment by JasonSooter** [comment]
@Andarist I agree
