### ISSUE TITLE
Get a common value from array

### ISSUE THREAD

**Issue by VadimZP** [ramda/ramda#2410]
I' ve found that there is no function that can retrieve a common value from an array. Maybe you can add something like this?

```
function commonVal(arr) {
        const sorted = arr.sort();

        let obj = {};

        let tempArray = [];

        sorted.forEach((val, i, arr) => {
            if (arr[i] != arr[i + 1]) {
                tempArray.push(arr[i]);
                obj[tempArray.length] = tempArray;
                tempArray = [];
            } else {
                tempArray.push(arr[i]);
            }
        });

        const numsArr = Object.keys(obj).map(el => +el);

        const getCommon = obj[Math.max(...numsArr)][0];

        return getCommon;
}
```

**Comment by alavkx** [comment]
I may be interpreting this incorrectly, but are you looking for the value with the most occurrences in a list (ie: mathematical "mode")?
Ramda does have a few math functions but only very simple ones. Maybe this is better off in the [cookbook](https://github.com/ramda/ramda/wiki/Cookbook)?

I got [an implementation of `commonVal`](https://goo.gl/6ha3Zh) using ramda functions (more akin to whats currently in the cookbook) started.

**Comment by davidchambers** [comment]
The :woman_cook: :book: is the place for this. :)

**Comment by VadimZP** [comment]
@alavkx , that's exactly what i meant. I'm just new to Ramda, that's why my impelementation is on pure JS

**Comment by alavkx** [comment]
https://github.com/ramda/ramda/wiki/Cookbook#mode-return-most-common-item-from-a-list

:)
