### ISSUE TITLE
Inconsistant API for Logic - Missing nonePass?

### ISSUE THREAD

**Issue by Undistraction** [ramda/ramda#2411]
It feels a little inconsistent to me that there are `all`, `none` and `any` for testing a list against a single predicate, but only `allPass` and `anyPass` for testing multiple predicates against a value. Feels like there should be a `nonePass` as well. 

Effectively:
```
const nonePass = compose(complement, anyPass);
```

I realise this is also relevant to other logical functions as well - `both` and `either` missing a `neither` for example.

**Comment by CrossEye** [comment]
I don't see a great need, personally.  This, I believe, is the first time I've seen a request for it, and, as you point out, it's extremely easy to write.

So I'm :-1: on this.

**Comment by Undistraction** [comment]
Fair enough.
