### ISSUE TITLE
Performance decrease for R.prop in v0.25.0

### ISSUE THREAD

**Issue by pmlamotte** [ramda/ramda#2413]
Due to #2305, `prop` now uses `path` under the hood in order to ensure behavior is consistent. A side-effect of this is that the performance of `prop` has decreased significantly. Each invocation now creates a new array with a single string/number in it, goes through the general curry functions for `path`, and finally goes through the body of path which includes an iteration of the array. With some tweaks, I'm able to get it to near native performance, and in one case replacing path with a non-curried version seems to solve the problem.

This similarly affects #2394 and I imagine any other future changes to the other prop functions that don't currently accept undefined objects, like `propEq`.

Running a quick bench shows a substantial decrease:

```javascript
const Benchmark = require("benchmark");
const benchmarks = require("beautify-benchmark");
const prop = require("./ramda/dist/ramda").prop;
const propNoInternalPath = require("./ramda-no-path/dist/ramda").prop;
const propNoInternalCurry = require("./ramda-no-curried-path/dist/ramda").prop;

const suite = new Benchmark.Suite;

const aPropOld = prop("a");
const aPropNoPath= propNoInternalPath("a");
const aPropNoCurry = propNoInternalCurry("a");
const inlineAProp = (obj) => obj == null ? undefined : obj["a"];

const obj = { a: "awtyf", b: "ftwoyfun" };
const obj2 = { a: "awtyf", e: "ftwoyfun" };
const obj3 = { d: "ftwoyfun" };

suite.add("R.prop: v0.25.0", function() {
  aPropOld(obj);
  aPropOld(obj2);
  aPropOld(obj3);
}).add("R.prop: ternary", function() {
  aPropNoPath(obj);
  aPropNoPath(obj2);
  aPropNoPath(obj3);
}).add("R.prop: no path curry", function() {
  aPropNoCurry(obj);
  aPropNoCurry(obj2);
  aPropNoCurry(obj3);
}).add("Inline function", function() {
  inlineAProp(obj);
  inlineAProp(obj2);
  inlineAProp(obj3);
}).on("cycle", event => {
  benchmarks.add(event.target)
})
.on("complete", () => {
  benchmarks.log()
}).run();

```

```
  4 tests completed.

  R.prop: v0.25.0       x   5,349,636 ops/sec ±0.90% (89 runs sampled)
  R.prop: ternary       x 555,449,526 ops/sec ±0.35% (94 runs sampled)
  R.prop: no path curry x 556,092,974 ops/sec ±0.42% (90 runs sampled)
  Inline function       x 581,866,864 ops/sec ±0.22% (90 runs sampled)
```

The no path curry version is the v0.25.0 implementation, but using an uncurried form of `path`. The ternary version is where I have reverted it to the old implementation, plus checking for null/undefined like `path` does currently:

```javascript
var prop = _curry2(function prop(p, obj) { return (obj == null) ? undefined : obj[p]; });
```

The v0.25.0 version is not abysmally slow relative to the rest of a typical application, but if I'm in need of a prop function within a hot path it's clearly much more advantageous to write it inline vs v0.25.0.

**Comment by CrossEye** [comment]
Thanks!

We really need to rebuild a benchmarking suite so that we can capture these problems.

I'd have to see your implementation, but it sounds as though a version like your "no path curry" would be useful.  It would be nice to layer this atop the same logic as `path`, since we've had a few issues like this for functions that clearly should be related but have slightly different behaviors.  I'd like to not repeat that.
