### ISSUE TITLE
Omit has inconsistent behavior for first argument as String vs [String]

### ISSUE THREAD

**Issue by bmatto** [ramda/ramda#2420]
In my testing I have recently discovered that certain keys of object members are not omitted when using omit(String) instead of omit([String])

Here it is in the [Repl](http://ramdajs.com/repl/?v=0.25.0#?%2F%2F%20Does%20not%20omit%20__foo%0Aconst%20a%20%3D%20R.omit%28%27__foo%27%2C%20%7B%27__foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%3B%0A%0A%2F%2F%20Does%20not%20omit%20_foo%0Aconst%20b%20%3D%20R.omit%28%27_foo%27%2C%20%7B%27_foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%3B%0A%0A%2F%2F%20Does%20not%20omit%20foo%0Aconst%20c%20%3D%20R.omit%28%27foo%27%2C%20%7B%27foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%0A%0A%2F%2F%20Omits%20b%0Aconst%20d%20%3D%20R.omit%28%27b%27%2C%20%7B%27foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%0A%0A%2F%2F%20Omits%20__foo%0Aconst%20e%20%3D%20R.omit%28%5B%27__foo%27%5D%2C%20%7B%27__foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%3B%0A%0A%2F%2F%20Omits%20foo%0Aconst%20f%20%3D%20R.omit%28%5B%27foo%27%5D%2C%20%7B%27foo%27%3A%201%2C%20b%3A%202%2C%20c%3A%203%2C%20d%3A%204%7D%29%3B%0A%0A%5Ba%2C%20b%2C%20c%2C%20d%2C%20e%5D)

Perhaps the omit(String) is an improper usage? Should it even be allowed?

**Comment by CrossEye** [comment]
I don't think there are any inconsistencies here.  The signature is

```hs
omit :: [String] -> Object -> Object
```

The behavior is undefined when you try to pass a string rather than a list of strings.  Ramda rarely throws an exception in such cases.

**Comment by bmatto** [comment]
Roger, well, I ❤️  ramda, thank you!

**Comment by JasonSooter** [comment]
@bmatto Maybe I'm missing something but it didn't appear to omit 'foo', it just ended up at the end for some reason.

```
[{"__foo": 1, "b": 2, "c": 3, "d": 4}, {"_foo": 1, "b": 2, "c": 3, "d": 4}, {"b": 2, "c": 3, "d": 4, "foo": 1}, {"c": 3, "d": 4, "foo": 1}, {"b": 2, "c": 3, "d": 4}]
```

**Comment by JasonSooter** [comment]
@bmatto It didn't appear to omit 'foo' in the 3rd example. It just ended up at the end. I hope I'm not missing something but I thought I'd point it out if helpful

```
[
    {
        __foo: 1,
        b: 2,
        c: 3,
        d: 4
    },
    {
        _foo: 1,
        b: 2,
        c: 3,
        d: 4
    },
    {
        b: 2,
        c: 3,
        d: 4,
        foo: 1
    },
    {
        b: 2,
        c: 3,
        d: 4
    },
    {
        b: 2,
        c: 3,
        d: 4
    }
]
```

**Comment by bmatto** [comment]
@JasonSooter yeah ... It looks to me that when you pass a String to omit instead of [String] it will try and omit each character in that string.  The behavior was different in the 0.24 ... though String as an argument type was never documented or tested from what I can see.  Thus the undefined behavior changed without resistance ... which is to be expected.

**Comment by CrossEye** [comment]
@bmatto: I don't think this changed recently.  But you're right, we don't object to arbitrarily changing undocumented, untested behavior.
