### ISSUE TITLE
0.25 regression: R.tap fails if the returned value is null

### ISSUE THREAD

**Issue by asaf-romano** [ramda/ramda#2421]
```js

const f = tap(identity);
f(null);

// => "t is null"
```

**Comment by CrossEye** [comment]
This will be fixed when  37da986 is released.

**Comment by alewaros** [comment]
An ETA for this?

**Comment by CrossEye** [comment]
I should have been yesterday, but I had unexpected company.  I will get to it in the next few days.

**Comment by alewaros** [comment]
Is there a new schedule for this fix?

**Comment by CrossEye** [comment]
I was *really* hoping for this weekend, but now I have company again.   I may still make it...

**Comment by trgwii** [comment]
Is it possible this weekend? 🤔

**Comment by wolfflow** [comment]
Oh, this is still unreleased. Maybe do the 0.25.1 ?

**Comment by CrossEye** [comment]
Yes, as soon as I can...

**Comment by trgwii** [comment]
🎉

**Comment by customcommander** [comment]
Just checked in the REPL and seems to have been fixed. Closing.
