### ISSUE TITLE
Util that selects a complex object from a transformation map

### ISSUE THREAD

**Issue by donrsh** [ramda/ramda#2423]
I am wondering if there is a util (see R.??? in the below) working like this:
```
const state = {
  orders: [
    {
      paidBy: 'Amy',
      amount: 1.00
    },
    {
      paidBy: 'Amy',
      amount: 2.50
    },
    {
      paidBy: 'John',
      amount: 10.00
    },
    {
      paidBy: 'Mike',
      amount: 5.20
    }
  ]
}

const totalPaidBy = (name) => (state) => R.pipe(
  R.filter(R.propEq('paidBy', name)),
  R.map(R.prop('amount')),
  R.sum
)(state.order)

const orderCount = (state) => state.orders.length

const selectingMap = {
  totalPaidBy: {
    Amy: totalPaidBy('Amy'),
    John: totalPaidBy('John')
  },
  orderCount
}

const selected = R.???(selectingMap)(state)
/* 
  expected: {
    totalPaidBy: {
      Amy: 3.50,
      John: 10.00
    },
    orderCount: 4
  }
*/
```

Basically the util takes a map of transformations, and a complex data structure, and spit out the map with the same structure as transformation map. 

I'd like to ask for that is particular useful when using `redux` and `reselect` together.

**Comment by polytypic** [comment]
Apologies for linking to a different library, but the [`L.pick`](https://github.com/calmm-js/partial.lenses/#L-pick) operation in Partial Lenses maps to the problem case rather directly.  Here is the [example](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBNCGUCmMC8MDeAoEAnAJkrhAFwwDaW2ADvAJb4BCAnmQOQCCAts2wDRZ4XEAFcwUMgEYAdAAZZWAL4Ca9Jqxice-QcLESYAJmkBWBcqpZaDFuwBSIABZgdQ0eKmy55lVbW3NAFk6AGskVz0PGBNpQ3MsAF0lLCxQSFgoECh4ABsABX9mNBgACjAhJABKNAA+UoRkatQ6gCVpajpqJBKsNoAzOhzkXBK26lwQagBRAEcStmt1fhhyrirKgTaueGpR9ondtjd9NkqN3ukIES4sSpKGpGk8QmJKlLToGGeiAGF3WHQ92yjVqcGBj2+xGkOSQYAA5lBHO9wJ8IEgYcAoHR4YEdsVsJlsvlCmRsNwNITcgUbMx5uTTgIHM4yJTiTT5kyXG8LJC-vpklgADLSOFIKAlYUdYAhe7opCY7Fw3HUDZgxBVIA).

**Comment by donrsh** [comment]
@polytypic The library looks awesome! Thanks a lot 😄

**Comment by CrossEye** [comment]
[`applySpec`][as] is quite close.  If you can change to this, then it [would just work][re]:

```js
const totalPaidBy = (name) => R.pipe(
  R.prop('orders'),
  R.filter(R.propEq('paidBy', name)),
  R.map(R.prop('amount')),
  R.sum
)
```

The point is that all the functions in the configuration supplied to `applySpec` should have the same input (in this case, `state`.)

It's up to you, but you could also write `orderCount` like this:

```js
const orderCount = R.path(['orders', 'length'])
```

  [as]: http://ramdajs.com/docs/#applySpec
  [re]: https://goo.gl/UKd18v

**Comment by donrsh** [comment]
@CrossEye That's exact what I am looking for! Thanks!
