### ISSUE TITLE
Could equals work with iterators?

### ISSUE THREAD

**Issue by Ciantic** [ramda/ramda#2427]
Consider this:

```javascript
let a = new Map();
a.set("a", 1);
a.set("b", 2);

let b = new Map();
b.set("a", 1);
b.set("b", 2);

equals(a.keys(), b.keys());
```

It returns `false`

I can make a workaround and use:

```javascript
equals(new Set(a.keys()), new Set(b.keys()));
// or
equals(Array.from(a.keys()), Array.from(b.keys()));
```

Not perhaps a big deal, but it would make parts of the code cleaner. Type-safety is question mark however.

**Comment by CrossEye** [comment]
I'm not sure there's anything we could do here.  Since there is no guarantee that iterators are finite, we can not check in finite time.  But even for finite ones, iterators are inherently stateful:

```js
const eqKeys = (a, b) => equals(Array.from(a), Array.from(b));

let aa = [1, 2, 3][Symbol.iterator]();
let bb = [1, 2, 3][Symbol.iterator]();
eqKeys(aa, bb); //=> true

aa = [1, 2, 3][Symbol.iterator]();
bb = [1, 2, 3][Symbol.iterator]();
aa.next();
eqKeys(aa, bb) //=> false
```

Do you have any suggestions to overcome this?
