### ISSUE TITLE
R.o throws error

### ISSUE THREAD

**Issue by pito-svk** [ramda/ramda#2430]
I have a function that trims, uppercase and replace spaces with dashes defined as:

```javascript 
const bar = R.compose(R.replace(/ /g, '-'), R.toUpper, R.trim)
```

if I call 
```javascript 
bar('  f o o bar ')
```
 I get 

```javascript
'F-O-O-BAR'
```

However I get error on call when I define function using R.o:

```javascript
const bar = R.o(R.replace(/ /g, '-'), R.toUpper, R.trim)
```

I get error

```javascript
TypeError: function f1(a) {
    if (arguments.length === 0 || _isPlaceholder(a)) {
      return f1;
    } else {
      return fn.apply(this, arguments);
    }
  } does not have a method named "toUpperCase"
    at [my folders]/node_modules/ramda/src/invoker.js:44:11
    at f1 ([my folders]/node_modules/ramda/src/internal/_curry1.js:18:17)
    at o ([my folders]/node_modules/ramda/src/o.js:31:12)
    at Object.f3 [as o] ([my folders]/node_modules/ramda/src/internal/_curry3.js:47:14)
    at repl:1:15
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
```
I think this is a bug, let me know if I am wrong.

Thanks.

**Comment by pito-svk** [comment]
Sorry, I thought R.o allows to compose more than 2 functions.

**Comment by CrossEye** [comment]
`R.o` was added specifically to cater to the simpler situation: composing two unary functions.  As opposed to the unholy signature of `compose`, `o` is simply

```hs
o :: (a -> b) -> (b -> c) -> a -> c
```

`R.compose` is significantly more powerful, but `o` has the advantage of clarity.

**Comment by pito-svk** [comment]
@CrossEye Thanks!

Maybe it's just me, but from documentation it wasn't clear to me. I had to look at the code to understand.

**Comment by pito-svk** [comment]
Also I don't get semantics why it's called `o`. I don't see similarity with Haskell/Clojure for example.

**Comment by CrossEye** [comment]
That's almost a pun.  It's meant to look like the mathematical composition operator:

```js
g ∘ f = x => g(f(x))
```

lowercase `o` is the closest ASCII match.

**Comment by JasonSooter** [comment]
@CrossEye Would your comment be helpful to the documentation? It seems to describe it's functionality (or at least it's limitation) better than comparing it to compose. Even though the type does clearly show it after looking

**Comment by CrossEye** [comment]
Certainly.  Would you be interested in creating a PR for this?

**Comment by JasonSooter** [comment]
Sure @CrossEye. I have created the PR. https://github.com/ramda/ramda/pull/2432 Thanks!

**Comment by CrossEye** [comment]
@JasonSooter: Thanks.  It looks good except for a [linting issue][;li].

  [li]: https://travis-ci.org/ramda/ramda/jobs/326571498#L725
