### ISSUE TITLE
Type error for R.pick when selected values aren’t all of same type

### ISSUE THREAD

**Issue by lensbart** [ramda/ramda#2434]
When using Ramda with Flow, `R.pick(['keys', 'with', 'values', 'of', 'different', 'type'], object)` gives an error when it shouldn’t

```
call of method `pick`
Function cannot be called on any member of intersection type
intersection
: my/local/file/:1
Member 1:
function type
: config/flow/flow-typed/npm/ramda_v0.x.x.js:1549
Error:
rest parameter array of call of method `pick`
: my/local/file/:1
Has some incompatible type argument with
array type
: config/flow/flow-typed/npm/ramda_v0.x.x.js:1551
Type argument `T` is incompatible:
Member 2:
function type
: config/flow/flow-typed/npm/ramda_v0.x.x.js:1553
Error:
object type
: my/local/file/:1
This type is incompatible with the expected param type of
object type
: config/flow/flow-typed/npm/ramda_v0.x.x.js:1555
Property `someValue` is incompatible:
```

**Comment by lensbart** [comment]
Sorry, I now realise I should’ve submitted this one to the `flow-typed` repository.

**Comment by CrossEye** [comment]
I'm afraid that there aren't many in the core team who know much about the flow typings.  Have you presented this problem in whatever project maintains the typing file you use?  (I know little enough that I'm not sure my wording on this is close to correct.)

**Comment by CrossEye** [comment]
I just wrote a response to that effect, and then saw that you had beat me to it.  If you don't get any satisfaction there, please come back... but there aren't many here with related expertise.  Good luck!
