### ISSUE TITLE
InvalidCharacterError in EDGE

### ISSUE THREAD

**Issue by koirikivi** [ramda/ramda#2437]
I have a project that uses ramda in conjunction with babel and webpack. Everything works in Chrome, Safari, Firefox and even IE11, but with EDGE I get the following error in the console: `SCRIPT5022: InvalidCharacterError`

The error happens here (compiled source):

```
/*!**********************************************************!*\
  !*** ./node_modules/ramda/es/internal/_isPlaceholder.js ***!
  \**********************************************************/
/*! exports provided: default */
/*! exports used: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (immutable) */ __webpack_exports__["a"] = _isPlaceholder;
function _isPlaceholder(a) {
       return a != null && typeof a === 'object' && a['@@functional/placeholder'] === true;
}

/***/ }),
```
Apparently, EDGE doesn't like special characters like (`/` or `@`) when accesssing attributes of `a`. I tested this with the debugger:

```
> a
[object NamedNodeMap]: {0: Object, length: 1}

>a['functionalplaceholder']
undefined

> a['@']
 InvalidCharacterError

> a['a/b']
 InvalidCharacterError
```

Curiously, this is not the case with every object:

```
> x = {}
[object Object]: {}

> x['@']
undefined

> x['/']
undefined
```

I have no idea if this is just a stupid user error or something worth investigating. It's an EDGE issue so one can never be sure...

Tested with ramda 0.25.0 and 0.24.1. I'm using EDGE 41.16299.15.0 on Windows 10, webpack 3.10.0, babel-core 6.26.0

**Comment by koirikivi** [comment]
Yep, confirmed that. The culprit was a code snippet like this:

```
import { forEach } from 'ramda';
const containers = document.querySelectorAll('p');
forEach(container => {
    forEach(attribute => {
        // do something with attribute
    }, container.attributes);
})
```

The innermost `forEach` caused the error. Wrapping `container.attributes` with `Array.from` fixed the issue.

Maybe this is something you'd want to consider or maybe not, but I'm hopeful that this issue lives in google for the next unfortunate person who encounters the same error :D .

**Comment by CrossEye** [comment]
I'm not sure there is anything for us to do here.  (Any suggestions?)  But thanks for the report.

**Comment by koirikivi** [comment]
The only consideration for you guys is probably if you want to support iterating over `NamedNodeMap` with the ramda functions in EDGE or not. If you want to do so, you would have to change `'@@functional/placeholder'` to something without special characters, but perhaps it's not worth it...

Or, you could have a note somewhere that it's safer not to use the ramda functions with strange iterable objects without using `Array.from`.

**Comment by CrossEye** [comment]
That `@@functional/placeholder` is very much patterned on the ones core to JS itself, such as the Iterator protocol.

We don't yet try to support general iterables, but I keep feeling that we should.  Perhaps this will be the motivation.
