### ISSUE TITLE
Lift seems inconsistent

### ISSUE THREAD

**Issue by babakness** [ramda/ramda#2442]
```javascript

R.lift( (a,b) => a + b)( 'a','b' )
// ['ab']

// Why does it 
R.lift( (a,b) => a + b)( ['a'],'b' )
// ['ab']


// vs

R.lift( (a,b) => a + b)(1,2)
// [undefined]

```

Why?

```javascript
// It can converge
R.lift( (a,b) => a+b)( identity, identity)(3)
// 6 

lift( (a,b) => a+b)( [identity,identity])([identity])
// ["a => aa => a", "a => aa => a"]

R.lift( (a,b) => a+b)( a => [a] , a => [a])(2)
// "22"

R.lift( (a,b) => a+b)( a => [a] , a => [a])(NaN)
// "NaNNaN"


```

... confusing...

I've also learned that `R.lift` can also behave like `R.converge`... 

```javascript
R.lift( (a,b) => a+b)( identity, identity) (3)
```

But this use isn't document. 

----

## Two different lifts?

I guess what I'm saying is that it feels like there are two different functions here. One lift acts like converge, which might be written as follows (assuming only curried functions)

### When `R.lift` behaves similar to  `R.converge` 

Here is how I understand how `R.lift` acts as `R.converge`

```javascript
R.lift( a => b => a - b )( R.identity, R.inc )( 1000 )
// [110, 120, 210, 220, 310, 320]
```

Implementation the way it seems to work here (assuming curried functions)

```javascript
const identity = a => a
const inc = a => a + 1
const liftLikeConverge = convergeFn => (...args) => x => 
  args.map( fn => fn(x) ).reduce( (acc,item) =>  acc(item),convergeFn)

liftLikeConverge( a => b => a - b )( identity, inc )( 1000 )
// -1
```

### When `R.lift` behaves as documented

Here is the documented behavior

```javascript
R.lift( (a,b) => a+b ) ([100,200,300],[10,20])
// [110, 120, 210, 220, 310, 320]
```

Which might be implement as  (assuming only curried functions)

```javascript
const head = arr => arr[0] 
const tail = arr => arr.slice(1)
const always = a => b => a
const ifElse = testCondition => trueCondition => falseCondition => input => (
  testCondition(input) ? trueCondition(input) : falseCondition(input)
)
const hasNoLength = a => a.length === 0

// helper functions
const ifHasNoLength = ifElse(hasNoLength)
const flattenReducer = (acc,item) => acc.concat(item)

// implementation
const liftLikeDocumentation = fn => ( ...args ) => 
  head(args).map( num => 
    ifHasNoLength
      ( always( fn(num) ) )
      // not sure if placing recursive call in tail position of 
      // map callback here makes a difference 🤷🏻‍♂️
      ( list => liftLikeDocumentation( fn(num) )(...list) )
      ( tail(args) )  
  ).reduce( flattenReducer, [] )

// example / test
liftLikeDocumentation( a => b => a + b ) ( [100,200,300], [10,20] )
// [110, 120, 210, 220, 310, 320]
```

As you can see `liftLikeConverge` and `liftLikeDocumentation` are quite different but `R.lift` does both of these things and more. Its a little confusing from a users view. Well.. at least my view. I can learn to use `R.lift` as a function overloaded to behave as both beasts (and maybe more). 

Perhaps I can be enlightened here. Perhaps both `liftLikeConverge` and `lifeLikeDocumentation` are implementations capturing projections from a single higher rational abstraction?

Thanks for your help.

**Comment by babakness** [comment]
I'm slowly coming around to how it works here...

```javascript
const IdentityFunctor = x => ({
  map: f => IdentityFunctor(f(x)),
  fold: f => f(x),
  ap: m => m.map(x),
  inspect: f => `IdentityFunctor(${x})`,
}) 

R.lift( a => b => a+b) ( IdentityFunctor(10), IdentityFunctor(50) ).inspect()
// IdentityFunctor(60)

```

**Comment by davidchambers** [comment]
When one runs into problems with a Ramda function it can be helpful to try the equivalent or similar Sanctuary or Haskell function. In this case, the equivalent Sanctuary function is [`S.lift2`][1].

First, let's simply enter it into the REPL to see the function's type:

```
> S.lift2
lift2 :: Apply f => (a -> b -> c) -> f a -> f b -> f c
```

Next, let's try your working example:

```
> S.lift2 (a => b => a + b) ('a') ('b')
! Type-class constraint violation

lift2 :: Apply f => (a -> b -> c) -> f a -> f b -> f c
         ^^^^^^^                     ^^^
                                      1

1)  "a" :: String

‘lift2’ requires ‘f’ to satisfy the Apply type-class constraint; the value at position 1 does not.

See https://github.com/sanctuary-js/sanctuary-type-classes/tree/v7.1.1#Apply for information about the sanctuary-type-classes/Apply type class.
```

This shows that the Ramda example “works” despite the type error.

Here's an example of correct usage:

```javascript
> S.lift2 (a => b => a + b) (['foo', 'bar', 'baz']) (['?', '!'])
['foo?', 'foo!', 'bar?', 'bar!', 'baz?', 'baz!']
```

Keep in mind that “lifting” is just sugar for `map` + `ap` (or `map` + `ap` + `ap` or `map` + `ap` + `ap` + …). Since we cannot map over `'a'` it is not compatible with `R.lift` or with `S.lift2`.


[1]: https://sanctuary.js.org/#lift2
