### ISSUE TITLE
Heap out of memory

### ISSUE THREAD

**Issue by are** [ramda/ramda#2445]
Executing this code in Node.js or Ramda REPL causes the process to crash.

```js
const R = require('ramda')
let args = [x => x + 2, [ 1, 2, 3 ] ]
let expected = [3, 4, 5]

let results = []

for (let fnName of Object.keys(R)) {
  try {
    let tres = R[fnName](...args)
    if (R.equals(tres, expected)) {
      results.push(fnName)
    }
  } catch (e) {

  }
}

console.log(results)
```

Node.js stack trace:
```

<--- Last few GCs --->

[8348:0000022740F2BB60]     5422 ms: Mark-sweep 579.3 (591.2) -> 579.3 (591.2) MB, 248.0 / 0.0 ms  allocation failure GC in old space requested
[8348:0000022740F2BB60]     5674 ms: Mark-sweep 579.3 (591.2) -> 579.3 (584.2) MB, 252.6 / 0.0 ms  last resort GC in old space requested
[8348:0000022740F2BB60]     5945 ms: Mark-sweep 579.3 (584.2) -> 579.3 (584.2) MB, 270.4 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000028374A778A1 <JSObject>
    1: unfold [path_to_project\node_modules\ramda\src\unfold.js:~30] [pc=00000316DBE0BD9D](this=000001989810BE21 <JSGlobal Object>,fn=00000185CFEA75F1 <JSFunction x (sfi = 000001F3522C7EF9)>,seed=00000185CFEA75D1 <JSArray[3]>)
    3: f2 [path_to_project\node_modules\ramda\src\internal\_curry2.js:29] [bytecode=0000028374A2CAE9 offset=201](this=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Is there something inherently wrong in the code I wrote that causes the crash?

**Comment by are1000** [comment]
Reason for this is an infinite loop in `unfold` that keeps adding to an array when called `R.unfold(x => x + 2, [ 1, 2, 3 ])`. I don't think it should be that easy to crash the whole process, maybe a simple check if `pair` is actually an array and not a string?

**Comment by Bradcomp** [comment]
You probably want to be careful with `R.until` as well. That one could obviously put you in an infinite loop.

**Comment by CrossEye** [comment]
Yep!  I had to look that one up.  Didn't even remember the function! :smile:

**Comment by are1000** [comment]
Just to push my case a little bit further (feel free to disregard this 😛):
Why couldn't we check if function returns either `false` or an array and otherwise throw? That would protect from a lot of (accidental) misuse. After all, `concat` is able to throw error if argument does not have `.concat`, `reduce` complains if list is not iterable, `test` complains if first argument is not a RegExp - I don't see why couldn't we also complain in `unfold` if the returned value is not either `false` or and `array` (compliantly with the spec of the function).

**Comment by davidchambers** [comment]
> Why couldn't we check if function returns either `false` or an array and otherwise throw?

Have you tried [Sanctuary][1], @are1000? It provides helpful error messages when a type error is detected. Here, for example, is an incorrect use of [`S.unfoldr`][2]:

```javascript
S.unfoldr(c => c <= 'z' ? [c, String.fromCharCode(c.charCodeAt(0) + 1)] : S.Nothing, 'a');
// ! TypeError: Invalid value
//
//   unfoldr :: (b -> Maybe (Pair a b)) -> b -> Array a
//                    ^^^^^^^^^^^^^^^^
//                           1
//
//   1)  ["a", "b"] :: Array String, Pair String String
//
//   The value at position 1 is not a member of ‘Maybe (Pair a b)’.
//
//   See https://github.com/sanctuary-js/sanctuary/tree/v0.14.1#MaybeType for information about the sanctuary/Maybe type.
```


[1]: https://sanctuary.js.org/
[2]: https://sanctuary.js.org/#unfoldr

**Comment by are1000** [comment]
@davidchambers I know about Santuary, but thanks anyways! I just wasn't sure why is Ramda typechecking in some functions, but not in those that can actually result in a crash.

**Comment by CrossEye** [comment]
> Why couldn't we check if function returns either `false` or an array and otherwise throw?

We could, but Ramda has always avoided hand-holding, assuming that users know what they're doing.  There is also a strong objection to throwing if at all possible, as exception-catching makes it much harder to work with functional composition/pipelines.

Those cases where we do type-check, it's generally for one of two reasons: to branch our implementations (see [`map`][ma]) or to return a reasonable value when we can do so even in the face of bad data (see [`propOr`][po]).  Sanctuary was created first as a complement to and eventually as an alternative to Ramda which would be more strict, in all sorts of ways, including run-time error checking.  This has advantages and [disadvantages][so], but it's good to have competing ideas available.



  [ma]: https://github.com/ramda/ramda/blob/v0.25.0/source/map.js
  [po]: https://github.com/ramda/ramda/blob/v0.25.0/source/propOr.js
  [so]: https://github.com/sanctuary-js/sanctuary/issues/477

**Comment by davidchambers** [comment]
> There is also a strong objection to throwing if at all possible, as exception-catching makes it much harder to work with functional composition/pipelines.

You seem to be arguing that we should think of all functions which do not throw exceptions as members of some very general type: `(Any...) -> Any`. I see little value in such a broad type. I would like to be able to compose a function of type `Foo -> Bar` and a function of type `Bar -> Baz` and know that the result will be of type `Foo -> Baz`. You seem to be arguing that it is inconvenient if, when we apply the resulting function to a value which is *not* a member of `Foo`, our program crashes. If our program does not crash, though, our types are farcical: in reality we composed `(Any...) -> Any` and `(Any...) -> Any` to produce `(Any...) -> Any`.

There are good abstractions for dealing with failure in pipelines: algebraic data types such as `Maybe a` and `Either a b`.

Please correct me if I have misrepresented your position, Scott.

**Comment by are1000** [comment]
Also I just want to point out, that _in my humble opinion_ it is not acceptable for a "theoretically safe" library to crash a whole process. Throwing is ok, even desired, but crashing? Definitely not.

**Comment by CrossEye** [comment]
@are1000: Can you think of a way to write an `unfold` that could not crash?  The basic idea of `unfold` is to keep accumulating values until a certain signal is returned.  What if that signal is not returned?  For instance, how would you prevent this from crashing?:

```js
unfold(n => [n, n + 1], 1);
```

There are no invalid types passed here.  But eventually, you will run out of memory.  In a lazy language like Haskell, this sort of issue doesn't arise, but I'm afraid we're in JS.

As for "theoretically safe", you're thinking about Sanctuary.  Ramda say "practical" and "for Javascript developers". :stuck_out_tongue_winking_eye:

**Comment by CrossEye** [comment]
> Please correct me if I have misrepresented your position, Scott.

I think you have.  Ramda tries to work more strictly than, say, Underscore.  But it has never had the type-safety concern of Sanctuary.  If I recall correctly, that was a motivating factor for the creation of Sanctuary.

My take is that if you supply the correct sorts of objects, Ramda should work as expected.  If you don't, we don't guarantee the results.  This can even be more restrictive than supplying the correct formal type.  For instance, `head([]) //=> undefined`.  The two alternatives to this that I know of are to throw, which is to me a very last resort, or to introduce `Maybe`/`Either`, etc.  That is a great choice, but it implies a further leap from idiomatic JS than Ramda would like to go.  I'm very glad Sanctuary does that.

Sanctuary takes the path of reducing the number of partial functions with `Maybe`/`Either`, but then it extends them [by adding exceptions][lu].  Ramda so far has done the reverse, eliminating exceptions where possible, but avoiding somewhat foreign-to-JS constructs as `Maybe`.

Unfortunately, there is no way to eliminate partial functions in a language like JS.  I don't know that one path is better than the other, but as always, I'm glad for the alternatives.

  [lu]: http://lambda-the-ultimate.org/node/4544#comment-71181

**Comment by Bradcomp** [comment]
> Also I just want to point out, that in my humble opinion it is not acceptable for a "theoretically safe" library to crash a whole process. Throwing is ok, even desired, but crashing? Definitely not.

As @CrossEye states above, this is theoretically impossible in a TC language like Javascript (AND Haskell for that matter). Furthermore, I am not sure it should be a priority from a practical standpoint. Functions have documentation and tests to ensure that they can be used for a particular set of inputs and outputs. That's what the type sigs are for. We've spent some time building out some property based tests to guarantee lawfulness over entire sets of inputs, but that work is still far from complete.

There are no guarantees when we don't follow the rules. It might work, it might throw, it might do the wrong thing (for instance, in Purescript, 1/0 evaluates to 0).   

If the input is outside the domain of the function, the result is [undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior) and there's no guarantee.

It seems like if you're looking to attempt to run arbitrary functions with arbitrary inputs, it might be worthwhile to do some type checking in the calling code before the attempt. You still can't eliminate all the potential problems, but at least you could eliminate improper inputs earlier, and with less risk. A project like [sanctuary-def](https://github.com/sanctuary-js/sanctuary-def) could make that process a lot easier, even if you don't want to use Sanctuary whole cloth.

**Comment by davidchambers** [comment]
> Sanctuary takes the path of reducing the number of partial functions with `Maybe`/`Either`, but then it extends them [by adding exceptions][1]. […]
>
> Unfortunately, there is no way to eliminate partial functions in a language like JS.

It seems you're arguing that in a JavaScript context a total function must be of type `(Any...) -> Any`. This seems silly to me. The fact that `S.trim` throws when applied to a value which is not a member of the function's domain does not make the function partial.


[1]: http://lambda-the-ultimate.org/node/4544#comment-71181

**Comment by CrossEye** [comment]
> It seems you're arguing that in a JavaScript context a total function must be of type `(Any...) -> Any`. 

More that in dynamic languages, the notion of a total function has to be considered a bit differently.  In Haskell, you simply cannot pass a value outside its domain to a function.  In Javascript it happens all the time.

Sanctuary deals with this via run-time type checking.  It's not a complete substitute, and it has a significant performance penalty, but it is a reasonable solution.  The biggest downside, to my mind, is the number of unnecessary exceptions.


> The fact that `S.trim` throws when applied to a value which is not a member of the function's domain does not make the function partial.

You can say that by explaining that the domain is restricted by extra-language concerns.  But it is not total on the complete set of values a user might pass to it.  Ramda, which tries to stay closer to plain JS, chooses not to throw exceptions that it can avoid (and that we notice.)  Sanctuary, which tries to exercise additional discipline, would rather throw an exception than allow a potentially unwanted result to propagate.

**Comment by davidchambers** [comment]
> Sanctuary deals with this via run-time type checking. It's not a complete substitute, and it has a significant performance penalty, but it is a reasonable solution.

Out of interest, the performance penalty is only significant for polymorphic functions (such as [`S.I`][1]).

> The biggest downside, to my mind, is the number of unnecessary exceptions.

How do you define unnecessary? Why does `R.trim(null)` throw rather than return `'null'` or `''` or some other value?


[1]: https://sanctuary.js.org/#I

**Comment by CrossEye** [comment]
> Out of interest, the performance penalty is only significant for polymorphic functions (such as [`S.I`][si]).

What portion of Sanctuary functions does this affect?  Because in a few tests I've run, that penalty is substantial.

> How do you define unnecessary? Why does `R.trim(null)` throw rather than return `'null'` or `''` or some other value?

Quite possibly it should return `''`.  I would have no objection to that.

"Unnecessary" to me is based on the formulation I've suggested several times: a function answers a question about its inputs.  If that question can be reasonably be answered in the case of bad data, then we should choose that answer rather than throwing an exception.  A good example is `propOr`.  When someone complained about it throwing on `null` or `undefined`, it was clear to me that we have a good answer to the question, even in the face of bad data.  Here the user has expressed an intent in the case things don't work out as expected.

So I can easily see `R.trim(null) //=> ''`


  [si]: https://sanctuary.js.org/#I

**Comment by davidchambers** [comment]
> Here the user has expressed an intent in the case things don't work out as expected.

I see this as conflating an expected error condition and an unexpected error condition (caused by a bug, perhaps). I will leave it at that, though, as we have disagreed on this point for several years now. ;)
