### ISSUE TITLE
Enhance pipeP to support both a -> Promise and common function

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2448]
optimize `pipeP` to `pipeAsync`, which can compose both `a -> Promise b` function & common function `a -> b`, inspired by async/await.

```js
function _pipeAsync(f, g) {
  return function() {
    var ctx = this;
    var gPromise = R.compose(
      // R.unless(R.is(Promise), val => Promise.resolve(val)),
      val => Promise.resolve(val),
      x => g.call(ctx, x)
    );
    var resultF = f.apply(ctx, arguments);
    return R.ifElse(
      R.is(Promise), 
      promise => promise.then(gPromise), 
      gPromise
    )(resultF);
  };
};

function pipeAsync() {
  return R.reduce(_pipeAsync, arguments[0], R.tail(arguments));
};

var result = pipeAsync(
  R.inc,
  R.tap(console.log),
  R.dec, 
  x => Promise.resolve(x + 1),
  R.inc
)(9);
result.then(console.log); // 11
```

codepen demo: https://codepen.io/adispring/pen/rpXapZ?editors=0011

**Comment by Qquanwei** [comment]
Greatful :+1: . This will make sense

A little tip: becase Promise can as a monad, so

equal:
```
    var gPromise = R.compose(
      val => Promise.resolve(val),
      x => g.call(ctx, x)
    );
```

**Comment by adispring** [comment]
@Qquanwei optimized it

**Comment by Qquanwei** [comment]
Actually,  just wrap by Promise.resolve. 

```
function _pipeAsync(f, g) {
  return function() {
    var ctx = this;
    var resultF = f.apply(ctx, arguments);
    return Promise.resolve(resultF);
};
```

**Comment by adispring** [comment]
You've lost Function g.

**Comment by CrossEye** [comment]
I love this change!  At a quick glance it looks like a real improvement.

But I'm not particularly inclined to fix *anything* in our Promises support, as we would really like to get rid of any Promise-related functions.  #1869, #1906.

**Comment by yaplas** [comment]
I use this:
```const isPromise = compose(
  is(Function),
  prop('then')
);

const ensurePromise = result =>
  isPromise(result)
    ? result
    : Promise.resolve(result);

const adapter = func => (...args) =>
  ensurePromise(func(...args));

// compose everything (no matter if it returns a promise or not)
const composeE = unapply(compose(
  apply(composeP),
  map(adapter)
));```

**Comment by lautarodragan** [comment]
I'd really like this feature, at least as long as Ramda is not dropping pipeP.

Can't this be solved succinctly by changing the `.then()` sequence to `await x`? I believe anything can be `await`ed. 

`await x` resolves to `x` if `x` isn't a promise AFAIK.

**Comment by pjo336** [comment]
Is there a way to accomplish this using `pipeWith` or just `pipe` currently?

**Comment by Bradcomp** [comment]
@pjo336 
```
const pipeP = R.pipeWith(R.andThen);
```
