### ISSUE TITLE
Describe path using dot(.) not array

### ISSUE THREAD

**Issue by sujameslin** [ramda/ramda#2456]
E.g. 
Instead of `R.path(['navigation', 'state', 'params', 'tabBarVisible'], this.props)`
`R.path('navigation.state.params.tabBarVisible', this.props)` is more convenient to use.

**Comment by davidchambers** [comment]
This is problematic because `.` is a valid character in a property name. You could define such a function yourself if this potential conflict is not applicable to your program. For example:

```javascript
//    myPath :: String -> Object -> Any
const myPath = R.useWith(R.path, [R.split('.')]);
```
