### ISSUE TITLE
dead code elimination cause problems with _arity

### ISSUE THREAD

**Issue by aizerin** [ramda/ramda#2459]
Some of the dead code eliminators (like babel-plugin-minify-dead-code-elimination) remove arguments from function's definition. Which cause problem with `_arity.js`

from:
`case 2: return function(a0, a1) { return fn.apply(this, arguments); };`
will become:
`case 2: return function() { return fn.apply(this, arguments); };`

and it will cause problems in combinations like `uncurryN and compose` because they are depending on the `function.length` returned from `_arity`.

I would like to open discussion if `_arity` can be more defensive. Because the function really depends on the dead code.

One of the possible solutions can be

```javascript
const arity2 = function() { return fn.apply(this, arguments);
arity2.arity = 2;
return arity2;
```

And then it is possible to check a function length by specified arity (if not specified than fallback to length).

What do you think about that?

problematic example:
```javascript
const lastFn = curry((firstArg, secondArg) => {
  console.log("lastFn-firstArg", firstArg);
  console.log("lastFn-secondArg", secondArg);
  return "finish";
});

const firstFn = (firstArg) => {
  console.log("firstFn-firstArg", firstArg); // there will be undefined when minified
  return firstArg;
};
const incorrectBehaviour = uncurryN(2, compose(lastFn, firstFn));


you can play with this example at
https://github.com/aizerin/dead-code-issue-example
just type yarn and yarn start
```
I have encountered the same problem with less complicated and usual code, but I cannot remember now.

note: args elimination can be disabled in the plugin mentioned above.

**Comment by CrossEye** [comment]
I wonder if reverting 07ecdaca would fix the issue.

> One of the possible solutions can be
> 
> ```js
> const arity2 = function() { return fn.apply(this, arguments);
> arity2.arity = 2;
> return arity2;
> ```

It's not quite as simple as that.  The property name is `length`, and we can't set it that easily.  But we should be able to with `defineProperty`

```js
Object.defineProperty(arity2, 'length', {value: 2, enumerable: false})
```

But this should be doable.  Or we could revert that commit above.  Or we could, I guess, go back even further to where this was actually done with the Function constructor (which annoyed the `eval` haters!)  Do you feel like taking a crack at one of these and creating a Pull Request?

**Comment by aizerin** [comment]
Yep, I will look into it further and see what can be done.

**Comment by CrossEye** [comment]
The choice isn't ours to make.  Ramda uses the length of any function supplied to it in a number of places, and the whole point of arity is to create functions that properly report this.

But probably the easiest fix would be to revert 07edac.

**Comment by CrossEye** [comment]
Yes, it would really be nice.  Is there a way we can inline such a directive?  We've done it before for es-lint; while it's far from ideal, it's worth considering.... if it's even possible.

**Comment by abritinthebay** [comment]
Yeah, not how babel-plugins work (they transform an AST) ESLint specifically has that line override (and they didn't used to - used to be file only).

**Comment by abritinthebay** [comment]
It's not an issue with Ramda - it's an issue with `babel-plugin-minify-dead-code-elimination`. To avoid it pass `keepFnArgs: true` into the plugin config.

**Comment by aizerin** [comment]
Same option can be also used for `uglifyjs`. (It is true by default, so you don't need to worry about that).

**Comment by Gregjarvez** [comment]
Hello this is not really an issue 
But i was just checking the implementation of arity and found how it was done in ramda 

however I am unsure as to why it was done with a switch statement 

```javascript 
const arity = (n, fn) => {
   return function () {
      return fn.apply(this, Array.prototype.slice.call(arguments, 0, n))
   }
}

const mapStringsToNumbers = (string) => {
   return string.split(",").map(arity(1, parseInt))
}

mapStringsToNumbers("1,2,3,4,5,6,7")
```

is there anything wrong with my implementation of arity

**Comment by Bradcomp** [comment]
@Gregjarvez your implementation causes fn.length to be 0. `arity` as it stands preserves function length, which is a very desirable property, especially when it comes to auto-currying.

**Comment by Gregjarvez** [comment]
@Bradcomp thank for the clarification. never would have seen that 💯

**Comment by CrossEye** [comment]
In fact, that is the whole reason for `arity`: to correctly report the arity of a function which otherwise might not do so.

**Comment by CrossEye** [comment]
@Gregjarvez: I don't see any way.
