### ISSUE TITLE
Possible inconsistency of converge when used with call

### ISSUE THREAD

**Issue by chrokh** [ramda/ramda#2461]
```javascript
converge(call, [
  x => y => x + y,
  add(2)
])(10)

// 22
```

```javascript
converge(call, [
  add,
  add(2)
])(10)

// function (t){return n.apply(this,arguments)}
```

I expected the 2nd example to yield the same result as the 1st.

Is this expected behavior? If so why?

Ps. thank you for all the great work :)

**Comment by adispring** [comment]
I've found out what's wrong, it's `converge` bug:

```javascript
var converge = /*#__PURE__*/_curry2(function converge(after, fns) {
  return curryN(reduce(max, 0, pluck('length', fns)), function () { // bug point
    var args = arguments;
    var context = this;
    return after.apply(context, _map(function (fn) {
      return fn.apply(context, args);
    }, fns));
  });
});
```

converge choose the longest fn's length from its second list argument, as returned function's length, so in the example above:
```javascript
var returnedFunc = converge(call, [
  add,
  add(2)
])
```

`add`'s length is 2, so `returnedFunc` will wait for two arguments to put into.

**Comment by leo19920823** [comment]
The number of argument can be changed to 1 by using unary
```
var test = R.converge(R.call, [
R.unary(R.add),
R.add(1)
])
test(20); // 21
```

**Comment by chrokh** [comment]
Very interesting! Thank you both for answering and bringing clarity to the situation.

So this behavior then exists to enable things like:

```javascript
const spread = unapply(identity)

converge(spread, [
  add,
  add(10)
])(1, 2)

// [3, 11]
```

Are there any specific uses-cases that motivated this design?

Or does it simply stem from trying to respect that all JS functions are variadic?

**Comment by adispring** [comment]
One example for multiple arguments is as following:
```javascript
var func = R.converge(R.divide, [R.add, R.subtract])
func(5, 3) // => (5+3)/(5-3) === 4
```

**Comment by adispring** [comment]
I think it's a bug should be fixed.

**Comment by davidchambers** [comment]
I suggest deprecating `R.converge`. It's such a confusing function.

**Comment by CrossEye** [comment]
@adispring: What do you think the behavior should be?  If we only wanted to support unary functions, then we could just deprecate it in favor of `lift`.  

`converge`'s behavior is very clear in my mind, but it is not easy to document.  Usually when there is an issue with variadic  functions, I find we can fix the signature by making it multiple signatures, but this one is more difficult because its variadic nature is confusing.

But this is one I reach for reasonably often.  The point of this function is described by its @symb tag:

```js
converge(f, [g, h])(a, b) ~> f(g(a, b), h(a, b))
```

It's complementary to `Function`'s `Chain` behavior:

```js
chain(f, g)(x) ~> f(g(x), x)
```

**Comment by adispring** [comment]
At least, `converge` used with `call` behaviors not exactly as `converge` described. Someone else also came up with the same problem recently. We can optimize `converge` for `call`, or describe `converge` more clearly.

**Comment by chrokh** [comment]
I find `converge` very useful but I'm not yet well versed enough in FP to determine whether it's duplicating behavior so I can't comment on that.

However, I now understand that the crux of this matter is that users might want to partially apply the function returned by `converge`. In other words, the function returned (as per the documentation) has the signature...

```javascript
(a → b → … → z)
```
and not...

```javascript
(a, b, …) → z
```

So if I'm not mistaken, the ambiguity is avoidable. There are two alternatives...

1. Either the returned function is polyadic and not curried which would mean that both example 1 and 2 (in this issue) would work since there would be no assumption regarding the arity of the function returned by `converge`.

2. Or (as currently) `converge` assumes that users may want to partially apply the returned function and thus makes the assumption that the number of arguments needed is equal to the longest function of the branching functions. This makes the 2nd example of the issue fail since `add` is only partially and not fully applied when `10` is passed to the function returned by `converge`.

If this was solveable I think it should be solved, but it seems to me that it isn't. If so, then I believe alternative 2 (i.e. current behavior) is probably better than alternative 1. 

If behavior is kept as is, then I would suggest adding something like this to the documentation of `converge`:

```diff
+ The arity of the new function is the same as the arity of the longest branching function.
```

Perhaps it would even be useful to point out that one can use `unary`, `binary`, or `nAry` if the convergance function expects to be applied to partially applied functions.

```diff
+ The arity of the new function can be reduced by reducing the arity of the longest branching function by using `unary`, `binary` or `nAry`. This is useful when the convergance function expects some arguments to be partially applied functions.
+
+ `converge(call, [unary(add), add(1)])(2) // => 5`
```

**Comment by CrossEye** [comment]
> ```diff
> + The arity of the new function is the same as the arity of the longest branching function.
> ```

This sounds great.  I can't see changing the behavior of `converge` in any substantial way, but we could certainly document it better.
