### ISSUE TITLE
Feature request: CLI

### ISSUE THREAD

**Issue by merlinnot** [ramda/ramda#2464]
Hi guys,
have you considered making a CLI for partial builds? It would be useful to easily add required methods to build processes, making sure Ramda is up-to-date, running in CI/CD pipelines etc. I’d love to make some initial PRs in this matter over the weekend, but I wanted to discuss it first with the community :)

**Comment by CrossEye** [comment]
I'd certainly like to hear more about what you're suggesting.

**Comment by Tatsh** [comment]
I think the potential benefits are minuscule compared to the maintenance cost for such a tool.

**Comment by davezuko** [comment]
> for partial builds

@merlinnot, have you tried using tools such as roll up to take advantage tree shaking? Not all implementations are perfect, but Ramda [now uses ES2015 modules](https://github.com/ramda/ramda/issues/2355), and that seems like a more universally applicable, dynamic way to eliminate unused code.

If your bundler doesn't do a great job with tree shaking, there are also tools such as [babel-plugin-ramda](https://github.com/megawac/babel-plugin-ramda) and [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) (which is not lodash-specific, despite the name) that can transform imports to achieve the same effect, without a Ramda-specific build step.

**Comment by merlinnot** [comment]
Personally I’ll be able to use Rollup and Webpack when Polymer 3 will be production-ready, but it’s almost impossible to make it work with HTML imports.

What if you’d be to add some functionalities to an existing codebase, which does not have these tools implemented?

I can think of dozens of different arguments why is it needed ;)

I didn’t have time to take a look at this lately, but I probably will in a few days.

Are TypeScript definitions hand-written? I’d like to generate typings too.

**Comment by merlinnot** [comment]
I'm personally using tree shaking now and it seems to work fairly well with Ramda, I don't see much traction here, so I'll go ahead and close this issue.
