### ISSUE TITLE
[question] pipe throws First argument to _arity must be a non-negative integer no greater than ten

### ISSUE THREAD

**Issue by abumalick** [ramda/ramda#2474]
Hello, I am learning Ramda at the moment and try to move a property in an object.
I found this way of doing it:
```js
const strings = R.path(['data', 'strings'], context)
const newContext = R.assoc('strings', strings, context)
return R.dissocPath(['data', 'strings'], newContext)
// This works well
```

Now I wanted to remove the newContext variable via pipe to make it cleaner and I get an error:
```js
return R.pipe(
  R.dissocPath(['data', 'strings'], context),
  R.assoc('strings', strings),
)
// Error: First argument to _arity must be a non-negative integer no greater than ten
```
Why doesn't it work, did I make an error ?

If you have a better way of doing it I am also interested ..

thanks

**Comment by abumalick** [comment]
oh okay sorry, I understood

```
const strings = R.path(['data', 'strings'], context)
        return R.pipe(
          R.dissocPath(['data', 'strings']),
          R.assoc('strings', strings),
        )(context)
```

sorry it is quite new to me. It a bit strange to make the brain used to this programming when you are used to es6.

Thank you for you work !

**Comment by CrossEye** [comment]
That leads me to an interesting function one might want, though:
```js
const moveProp = curry((oldPath, newPath) =>
  compose(dissocPath(oldPath), chain(assocPath(newPath), R.path(oldPath))))
const moveStrings = moveProp(['data', 'strings'], ['strings'])
moveStrings(context)
```
This could also be written:

```js
const moveProp = curry((oldPath, newPath, context) =>
  dissocPath(oldPath, chain(assocPath(newPath), R.path(oldPath))(context)))
moveProp(['data', 'strings'], ['strings'], context)
```

This would never likely be a candidate for Ramda itself, but I can see it as a useful function.

**Comment by abumalick** [comment]
I didn't know chain, I will use this it is nice.

Thank you very much for your help !

**Comment by CrossEye** [comment]
There's [a lot more][th] going on in `chain`, as it's an extremely important function in category theoretical programming, but when it's used with functions, it's pretty simple:

```js
chain(f, g) //~> (x) => f(g(x))(x)
```

which in Ramda can usually be thought of as

```js
chain(f, g) //~> (x) => f(g(x), x)
```

  [th]: http://www.tomharding.me/2017/05/15/fantas-eel-and-specification-13/
