### ISSUE TITLE
Can we use a placeholder for the function with R.call?

### ISSUE THREAD

**Issue by customcommander** [ramda/ramda#2478]
Hey guys,

I'm still quite new to Ramda so this may be a silly question :-/

Is `R.call` curried and/or can we use `R.__` in it?

Examples: (using Ramda 0.25)

```javascript
R.call(R.add, 1, 2);
//=> 3 (Yay)

R.call(R.__, 1, 2)(R.add);
//=> [Function: f2] (Mmmh... :-/)
```

Cheers.

**Comment by CrossEye** [comment]
No, unfortunately, `call` is a bit of an oddball Ramda function.  There are good arguments for removing it.

Certainly your case can be handled as 

```js
const callWith = (...args) => (fn) => fn.apply(null, args)
callWith(1, 2)(add) // => 3
```

If you haven't seen it, the [Gitter chat room][gr] is a good place for questions like this.  There are many helpful, friendly people there.

  [gr]: https://gitter.im/ramda/ramda

**Comment by customcommander** [comment]
Thanks for the reply.

I have found a workaround with `applyTo` which I'm much happier with anyway. Sorry for the spam I wasn't acquainted with Gitter.

**Comment by CrossEye** [comment]
It's not a problem to ask questions like that here.  But Gitter will likely give you a quicker response.
