### ISSUE TITLE
a function for make a new object with sub set of items of another object - See the case

### ISSUE THREAD

**Issue by LucasBadico** [ramda/ramda#2479]
```javascript
// the function
const getArgs = args => keys => R.reduce((obj, field) => ({ ...obj, [field]: args[field] }), {})(fields)

// I have a random set of keys as
const keys = ['foo', 'bar', 'baz']

// a bigger object
const bigger = {
  ...
  foo: 1,
  bar: 1,
  baz: 1,
   ...
}

// so for my new object
getArgs(bigger)(keys)
=> {
 foo: 1,
  bar: 1,
  baz: 1,
}

// or
getArgs(bigger)(['baz'])
=> { baz: 1 }
```

**Comment by CrossEye** [comment]
See [`pick`][pi] or [`pickAll`][pa].


  [pi]: http://ramdajs.com/docs/#pick
  [pa]: http://ramdajs.com/docs/#pickAll

**Comment by functionalStoic** [comment]
@LucasBadico https://goo.gl/64753c might help

**Comment by CrossEye** [comment]
Also note that there is usually faster response on the [Gitter chat room][gr].  It's not really a problem to ask questions here, but the chat room will likely give quicker response.  There are many of helpful people there.

  [gr]: https://gitter.im/ramda/ramda

**Comment by LucasBadico** [comment]
THanks.

Em Sex, 23 de fev de 2018 14:49, Scott Sauyet <notifications@github.com>
escreveu:
