### ISSUE TITLE
Proposal: assocBy ?

### ISSUE THREAD

**Issue by vitalets** [ramda/ramda#2480]
I've noticed that often I need a variant of [R.assoc](http://ramdajs.com/docs/#assoc) that instead of explicit value can receive function that transforms object and sets the result to the prop.
For example I want to join `x` and `y` props into `z`:
```js
const joinXY = R.pipe(R.props(['x', 'y']), R.join(''));
const f = R.converge(R.assoc('z'), [joinXY, R.identity]);
f({x: 'foo', y: 'bar'}); // => {"x": "foo", "y": "bar", "z": "foobar"}
```
What do you think about `R.assocBy` that allows to do it more straight way:
```js
const f = R.assocBy('z', joinXY);
f({x: 'foo', y: 'bar'}); // => {"x": "foo", "y": "bar", "z": "foobar"}
```
I've tried to create such `assocBy` function: 
```js
const assocBy = R.compose(R.over, R.lens(R.identity), R.assoc);
```
But I only works with separate arguments and can't receive all arguments at once:
```js
// Pass arguments separatly
const f = R.assocBy('z')(joinXY);
f({x: 'foo', y: 'bar'}); // => {"x": "foo", "y": "bar", "z": "foobar"}

// Pass 2 arguments at once
const f = R.assocBy('z', joinXY);
f({x: 'foo', y: 'bar'}); // => function r(e){return...
```

**Comment by CrossEye** [comment]
I think the simplest version with current tools would be

```js
const f = chain(assoc('z'), joinXY)
```

A generic version could be

```js
const assocBy = curry((name, fn, obj) => assoc(name, fn(obj), obj))
```

I'm sure we could make this point-free if we tried hard enough, but it would probably be much less readable.

I keep wanting to find a way to make this work with a `lens`-style getter and setter, but anything that did what you want would likely fail one of the lens laws.  Lenses with `over` would be the obvious solution if your modification function just needed to use the value at the focus.  This however is different.

This doesn't sound like something common enough to put in the library core, but it certainly is worth considering for the [Cookbook][cb].

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by vitalets** [comment]
@CrossEye thanks for the explanation!
I can try to prepare an example for Cookbook. 
But yet I'm impressed with your solution via `chain` and still can't realize how it works 🤔
If possible could you give some explanation? In [What Function Should I Use?](https://github.com/ramda/ramda/wiki/What-Function-Should-I-Use%3F) `chain` is not mentioned anywhere. I think it could be helpful for ramda users.
I see in [docs](http://ramdajs.com/docs/#chain) that `chain` works like flat-map, and that's clear. I think the point is in "Dispatches to the chain method of the second argument". But to me (as a not advanced fp-developer) it's unclear that this can allow `chain` to operate with Object instead of List.

**Comment by CrossEye** [comment]
This is the signature of `chain`:

```hs
chain: Chain m => (a -> m b) -> m a -> m b
```

Specializing this to Arrays gives us

```hs
chain:  (a -> Array b) -> Array a -> Array b
```

But `Array x` is more commonly written `[x]`, so this becomes:

```hs
chain: (a -> [b]) -> [a] -> [b]
```

which should be reasonably clear.  We can do the same thing with functions:

```hs
chain: Chain m => (a -> m b) -> m a -> m b
```

specialized to Functions gives us

```hs
chain:  (a -> Function b) -> Function a -> Function b
```

But `Function b` can be rewritten as `x -> b`, so this becomes

```hs
chain:  (a -> (x -> b)) -> (x -> a) -> (x -> b)
```

or more simply

```hs
chain:  (a -> x -> b) -> (x -> a) -> (x -> b)
```

Now to implement that, there is really only one option.  Our output function is `(x -> b)`, so we need to get an `a` to call the first function.  The only way to get that is to call `(x -> a)`, then this and the initial `x` can be passed into the first function.

That means that if we give names to the first two functions, `f :: (a -> x -> b)` and `g :: x -> a`, we can see that 

```js
chain(f)(g) //~> x => f(g(x))(x)
```

And in Ramda that is equivalent to

```js
chain(f, g) //~> x => f(g(x))(x)
```

Or if `f` has something like Ramda's currying applied

```js
chain(f, g) //~> x => f(g(x), x)
```

> In [What Function Should I Use?][wf] `chain` is not mentioned anywhere.

The trouble with generic functions like this is that it's hard to list all the places they can be used.  I'm not sure how to include this in that format.  We could mention the use for arrays, but that would not cover this, nor many of the other potential uses.  Any suggestions would be welcome.

  [wf: https://github.com/ramda/ramda/wiki/What-Function-Should-I-Use%3F

**Comment by vitalets** [comment]
@CrossEye this is awesome! Thanks for detailed explanation. I should think more about it to put in my head.

Anyway, returning to `assocBy` I've managed to get point-free version using `converge + juxt`. As you supposed it's not very elegant: 
```js
const assocBy = R.converge(R.assoc, [
  R.nthArg(0),
  R.pipe(R.juxt([R.nthArg(1), R.nthArg(2)]), R.apply(R.call)),
  R.nthArg(2),
]);

f('z', joinXY, {x: 'foo',  y: 'bar'}); // => {"x": "foo", "y": "bar", "z": "foobar"}
f('z')(joinXY)({x: 'foo',  y: 'bar'}); // => {"x": "foo", "y": "bar", "z": "foobar"}
```
But next I thought about having `R.args` - a function that returns list of arguments by their positions (as well as `R.props` returns properties by their names):
```js
const f = R.args([2, 1]);
f('x', 'y', 'z'); // => ['z', 'y']
```
It can be implemented as:
```js
R.args = R.compose(R.juxt, R.map(R.nthArg));
```
With `R.args` the code of `assocBy` would be simpler:
```js
const assocBy = R.converge(R.assoc, [
  R.nthArg(0),
  R.pipe(R.args([1, 2]), R.apply(R.call)),
  R.nthArg(2),
]);
```

So instead of `R.assocBy` maybe add more generic `R.args`?

**Comment by CrossEye** [comment]
Yes, not elegant at all!  :smile:  Any time you have to reach for `nthArg`, something has gone wrong.  Although Ramda was written in a way that makes point-free coding easier, I would never make a fetish of it.  Obviously either your first version or the one with `args`  is far less readable than `curry((name, fn, obj) => assoc(name, fn(obj), obj))`, and I can see no reason to choose either of them over it.

**Comment by vitalets** [comment]
Totally agree. 

One thought about `chain` documentation.
As you wrote:
> We could mention the use for arrays, but that would not cover this, nor many of the other potential uses. Any suggestions would be welcome.

In the `chain` source there is explicit check if second argument is a function:
```js
function chain(fn, monad) {
  if (typeof monad === 'function') {
    return function(x) { return fn(monad(x))(x); };
  }
  return _makeFlat(false)(map(fn, monad));
}
```
I think it could be mentioned in docs to provide more understanding of it. Something like: 
_if second argument is function `chain(f, g)(x)` works like `f(g(x), x)`_

**Comment by CrossEye** [comment]
We have an example in the docs that shows that, but I would have no problem adding that to the text to.  Do you want to create a PR?

**Comment by CrossEye** [comment]
The reason for the explicit check is that for all the [FantasyLand][fl] functions, Ramda supplies implementations for a number of native types (Arrays, Objects, Functions) and delegates to the named method for other types (Maybe, Future, IO,, Either, whatever.)


  [fl]:
