### ISSUE TITLE
transducer logic not called on R.flip (R.compose)

### ISSUE THREAD

**Issue by sourcevault** [ramda/ramda#2481]
@Andarist 

Hi !

I have been running some benchmarks for comparing `Ramda`'s transducer implementation to other transducer implementations - so far go good ! 

```
cognitect-labs :  559
jlongster :  560
Ramda :  452
```

However it seems if you flip arguments for compose using Ramda `flip`

```
var fipped_compose = R.flip (R.compose)
```

The transducer logic does not run :(

This is the results for running the same combinators

```
cognitect-labs :  576
jlongster :  561
Ramda :  894
```

So to confirm what was going on I used to `take` combinator and this the result.

```
cognitect-labs :  5
jlongster :  4
Ramda :  1123
```

I hope its possible to use a flipped Ramda compose along with the transducer logic.

Cheers ! 

Here is the code for runnig the test https://github.com/sourcevault/transducer-benchmark.

**Comment by CrossEye** [comment]
I'm afraid I don't follow your tests very well.  Do you simply alter the tests and run separately for each library?  But why does Ramda's implementation run in the opposite order to the other two?  Don't all the `compose`s work the same way?  And if not, Ramda has `pipe` so that `pipe(f1, f2, f3, ...) ~= `compose(..., f3, f2, f1)`  `flip` is somewhat different, as it just flips the first two parameters.  So I'm not sure quite what you're doing.

**Comment by sourcevault** [comment]
*But why does Ramda's implementation run in the opposite order to the other two? Don't all the composes work the same way?*

Ramda's compose is right to left, while the other two are left to right - its not really an issue as long as flip works. 

Thanks - I think pipe will do, I was under the impression that flip would flip all arguments. 

--- 

sorry if the test code was confusing, I un-commented all tests in the real script.

**Comment by CrossEye** [comment]
Just for the record, all three compositions run [in the same order][tc].  It's just that transducer run order is opposite normal composition order.  Two good explanations:

  * https://www.youtube.com/watch?v=6mTbuzafcII#t=1531 (Rich Hickey video, time set to discussion on compostion order)
  * http://isaaccambron.com/blog/2014/12/13/transducer-composition.html (Article specifically on Transducer composition, code in Clojure.)



  [tc]: https://runkit.com/crosseye/transducer-composition
