### ISSUE TITLE
Release a version with `sideEffects: false`

### ISSUE THREAD

**Issue by Antontelesh** [ramda/ramda#2482]
Hello, is there any chance to see the `sideEffects: false` published on npm in the nearest future?
Webpack 4 is out and it would be great to leverage aggressive tree-shaking here. I see the option added a few months ago, but no new version published for a long time.

Thank you.

**Comment by CrossEye** [comment]
I think we'll have a version out in the next few weeks.

**Comment by Undistraction** [comment]
I think this is a huge win and would really help avoid bloat when using Ramda in other libraries.

**Comment by EvgenyOrekhov** [comment]
According to https://github.com/ramda/ramda/blob/v0.27.0/package.json#L40, this issue is resolved and can be closed.
