### ISSUE TITLE
Ability to check Ramda's version at runtime

### ISSUE THREAD

**Issue by tjwallace** [ramda/ramda#2492]
It would be great if Ramda's version could be checked via something like `R.version`

**Comment by CrossEye** [comment]
Are you really likely to write code that will branch based on the version of Ramda involved?  That's the only reason I could see including such.  It's not that I have a major objection.  But it seems unnecessary.

(I do have a minor objection.  Right now Ramda has only one non-function property, [the placeholder, `__`][pl].  I would rather remove that one than add more of them.  But this is a minor concern.

Can you convince us of the worth of this?

@ramda/core: any thoughts?


  [pl]: http://ramdajs.com/docs/#__

**Comment by tjwallace** [comment]
@CrossEye because of the lack of tests in one of our applications we are hesitant to upgrade Ramda. I needed to use `mergeDeepRight` so I just wrote it myself in a util file. I wanted to make that file throw an error, once we upgrade Ramda, because that function will be able to be removed.

**Comment by CrossEye** [comment]
Well, that's not really a function... a thunk perhaps!  :smile:

That's an interesting use-case that I've never seen before with any library.  But it's certainly legitimate.

Let's see if others have any major objection.

**Comment by davidchambers** [comment]
@tjwallace, would `require('ramda/package.json').version` work for you?

**Comment by tjwallace** [comment]
@davidchambers yes, that does the trick! Thanks!

**Comment by CrossEye** [comment]
@david: that's so simple.  It's hard to believe I haven't seen it before.  Perfect!
