### ISSUE TITLE
R.over for lens path that does not exist

### ISSUE THREAD

**Issue by vitalets** [ramda/ramda#2499]
Assume a task: if object has some path - uppercase the value, otherwise - do nothing.
The first approach I made is following:
```js
const f = R.over(R.lensPath(['x', 'y']), R.toUpper);

f({x: {y: 'foo'}}); // => {"x": {"y": "FOO"}}
```
but if path does not exist I get an error:
```js
f({x: {z: 'foo'}}); // => undefined does not have a method named "toUpperCase"
```
I've constructed the function that works:
```js
const f = R.ifElse(
  R.pipe(R.path(['x', 'y']), R.isNil), 
  R.identity, 
  R.over(R.lensPath(['x', 'y']), R.toUpper)
);

f({x: {y: 'foo'}}); // => {"x": {"y": "FOO"}}
f({x: {z: 'foo'}}); // => {"x": {"z": "foo"}}
```
but it seems to me rather verbose and un-optimal: path `['x', 'y']` is repeated twice.

My questions/suggestions are following:
1. maybe I miss something and it can be achieved in more elegant way without path duplication?
2. is there a standard solution for dealing with non-existent lens? I looks to me a common case.
3. I've noticed the [R.viewOr](https://github.com/ramda/ramda/wiki/Cookbook#viewor) in Cookbook but it does not help. I need to modify path with `R.over` not `R.view`. R.overOr?
4. what about adding `R.hasPath()` function similar to current `R.has()`? It will partially help.

Thanks!

**Comment by tommmyy** [comment]
This is more compat way:

```js
const myLens = R.lensPath(['x', 'y'])
                   
const f = unless(o(isNil, view(myLens)), over(myLens, toUpper));
```
And you can make your more general function like that:

```
const overUnlessIsNil = (lens, fn) => unless(o(isNil, view(lens)), over(lens, fn))

const f = overUnlessIsNil(lensPath(['x', 'y']), toUpper)
```

**Comment by CrossEye** [comment]
I don't think there will be any reasonable way to do this with our lenses.  You might be interested to check out @polytypic's  [partial-lenses library][pl] for a tool that might help.

It's not too hard to write something that works in Ramda without using lenses:

```js
const hasPath = curry((pth, obj) => {
  const parent = path(init(pth), obj)
  return is(Object, parent) && last(pth) in parent
})

const updatePath = curry((pth, fn, obj) => {
  return hasPath(pth, obj) ? assocPath(pth, fn(path(pth, obj)), obj) : obj
}) 

updatePath(['x', 'y'], toUpper)({x: {y: 'foo'}}) //=> {"x": {"y": "FOO"}}
updatePath(['x', 'y'], toUpper)({x: {z: 'foo'}}) //=> {"x": {"z": "foo"}}
```

I think `hasPath` might well be a good fit for Ramda, if you're interested in pushing for it.  (There are questions, of course: Should that involve a `hasPathIn` function as well in parallel with `has`/`hasIn`?  How will this work we finally start supporting `Map`s?  But I think we could work these out.)

As to the main function, it feels to me at first blush that this belongs in user-land.  But if you feel like arguing for it, I would be interested in hearing you make your case.

  [pl]: https://github.com/calmm-js/partial.lenses

**Comment by CrossEye** [comment]
The only functional difference I see between my proposed solution and the one from @tommmyy is that mine treats `null`- and `undefined` properties no different from any others:

```js
updatePath(['x', 'y'], o(toUpper, String))({x: {y: null}}) //=> {"x": {"y": "NULL"}}
overUnlessIsNil(lensPath(['x', 'y']), o(toUpper, String))({x: {y: null}}) //=> {"x": {"y": null}}
```

But this is not much of a selling point.

**Comment by polytypic** [comment]
There are a number of ways to do this kind of thing with Partial Lenses.  One way is to compose with the [`L.optional`](https://github.com/calmm-js/partial.lenses/#L-optional) optic: `L.modify([lens, L.optional], fn, data)`.  Here is an [example](https://calmm-js.github.io/partial.lenses/playground.html#MYewdgzgLgBANgU0jAvDA2gcgB6YDQyYCemAugFDmiSxEISowDe2AXM0e8fZgL69Vw0GGBCMW7JgC8uovgPJwQAcwAUARgIAZAHTKEUVYkgE6EAJQxzilaoBM2vQaNIIBUZes21AZkcBbEAATAEsAMyJVdGM3GF0QAAcoEPAAQzhSAgAlHSgQAFUEhIQAJ1N6T29VABYA4PDI6NdHROS0jOzcgqLS9xBPIA).

**Comment by vitalets** [comment]
Thanks for your replies! Very useful. I'm ready to make 2 actions:
1. add to the Cookbook @tommmyy's solution, next to `R.viewOr` section (if @tommmyy don't mind :))
2. make a PR with `hasPath` proposal to continue discussion. @CrossEye?

**Comment by CrossEye** [comment]
Sounds great to me!

**Comment by vitalets** [comment]
Discussion of `hasPath` proposal could be continued in corresponding pr #2501.
