### ISSUE TITLE
Iterating the own [key, value] properties of an object

### ISSUE THREAD

**Issue by mondalaci** [ramda/ramda#250]
It'd be really useful if I could iterate the own properties of of an object as a list like `{a:1, b:2}` as `[[a,1],[b,2]]` and map the result.  Wondering whether it's possible with Ramda.  Looking for something like:

```
R.keysAndVals(function(key,val){return key+val})
```

The above would result in `['a1','b2']` when used with the above example object.

**Comment by gannon-zend-gdata264** [comment]
https://wharf89.github.io/leandro44/



I invested time searching for a solution and finally found the answer
