### ISSUE TITLE
Converge function is not included in the NPM rambda package

### ISSUE THREAD

**Issue by gandhiShepard** [ramda/ramda#2503]
Um, converge doest work anymore. `TypeError: R.converge is not a function` I checked the source files and it is not in the any of the NPM package files. Notice that `coverage` is missing from the list of exports.

<img width="675" alt="screen shot 2018-04-08 at 6 55 13 am" src="https://user-images.githubusercontent.com/8546059/38467207-930b9138-3afa-11e8-8c81-aa5ed4b1e2fd.png">

I see it in the Documentation for the site. I see it in the GitHub files, but it is not being output to the NPM package files. 

Is it being removed? Or is there some issue with outputting that function to the NPM package?

**Comment by gandhiShepard** [comment]
UGH, so sorry! please disregard this I installed ramBda not ramda. Yikes! I didn't know that a nearly identical package of Ramda existed.

**Comment by CrossEye** [comment]
Yes, a minor source of frustration to us...
