### ISSUE TITLE
Is Ramda ever planning on being as safe as lodash?

### ISSUE THREAD

**Issue by ulyr** [ramda/ramda#2504]
For example
`R.filter(R.whereEq({ foo: 'bar' }))(baz)`
breaks when `baz = undefined` and `baz = [..., undefined]`, is there any way to compose around this?

**Comment by tommmyy** [comment]
Check out `R.defaultTo`

**Comment by CrossEye** [comment]
The two initial founders of Ramda, @buzzdecafe and I, started with a strong sense that we were not interested in hand-holding.  We didn't want to type-check your arguments for you or worry overmuch about what would happen if you supplied bad ones.  Garbage in, garbage out.  The third person to join our development, @davidchambers, was more interested in this, and in avoiding partial function, and eventually he started an entirely different library where these concerns are central.  [Sanctuary][sa] has become a very interesting alternative to Ramda, with a reasonable overlap, but also some very different concerns.  It is likely much safer than lodash.

But now, as to that safety:

```js
const gt5 = x > x > 5

_.filter([5, 6, 7], gt5) //=> [6, 7]
_.filter({a: 5, b: 6, c: 7}, gt5) //=> [6, 7]
_.filter(undefined, gt5) //=> []

R.filter(gt5, [5, 6, 7]) //=> [6, 7]
R.filter(gt5, {a: 5, b: 6, c: 7} //=> {b: 6, c: 7}
R.filter(gt5, undefined) //~> error
```

So lodash has the ability to generate a reasonable default value if your filterable object is missing.  Ramda, which arguably has a more powerful `filter` function, cannot do so.  What would it be?  An empty object?  An empty array?  An empty member of your custom Filterable type?

There is certainly a case to be made for more useful error messages.  While I've softened on this point a bit, I haven't changed much, and I don't think @buzzdecafe's position has altered even as far as mine.  Writing and maintaining that sort of code does not interest me much.

  [sa]: https://sanctuary.js.org/

**Comment by alanwei0** [comment]
@CrossEye is this a typo?

```js
const gt5 = x => x > 5
```

**Comment by CrossEye** [comment]
@alanwei0:  Yes it was, thank you.  Fixed.

**Comment by atilkan** [comment]
@CrossEye How did you fixed? They are the same.

**Comment by CrossEye** [comment]
@atilkan:

I corrected a typo.  I originally wrote: `const gt5 = x > x > 5`.  I edited my answer to say instead `const gt5 = x => x > 5`. (replaced the first `>` with `=>`.)

You can edit your comments using the dropdown menu in the top-right of the comment header (`...`).  You can see the edits to a comment in a dropdown (`edited`) in the comment header.

**Comment by atilkan** [comment]
Ohh, thank you for the detailed information. I would never be able to find that dropdown despite the fact i am 10+ years member.
