### ISSUE TITLE
How can I clear memoizeWith items?

### ISSUE THREAD

**Issue by kudorori** [ramda/ramda#2509]
How can I clear memoizeWith items?

**Comment by CrossEye** [comment]
I'm afraid you can't.  I doubt Ramda will ever be interested in supporting that.  Functional programming is about pure functions.  If you supply the same arguments, you get the same value, and there are no side effects.  The only reason for `memoizeWith` is to allow you to avoid repeating expensive calculations.  The values stored are not the sort of things that should be invalidated.

Of course it's quite easy to write a simple `memoize` decorator of your own, especially if you know the types of parameters involved.

**Comment by Izhaki** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things. -- Phil Karlton

@kudorori I agree with @CrossEye - cache invalidation is a complex business. You have popular solutions like [memoize-one](https://www.npmjs.com/package/memoize-one), but even these can be are not suitable sometimes.

I've been working on this project that had a function called `getAbsoluteBoundingRect` which was *really* expensive to work out; `memoizeWith` would do the trick for static data (say with mouse-detection), but soon as the data change `memoizeWith` was out of the question. I ended up with bespoke cache invalidation.

There are just too many specific scenarios to support - I'd also encourage you to write one that best suits your needs.

**Comment by CrossEye** [comment]
... or my favorite variant:

> There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.  -- *Some Wag*

**Comment by meszaros-lajos-gyorgy** [comment]
My quick and dirty solution is to create a factory for the memoized function and call it every time you need a fresh, clean instance of memoization:

```javascript
const fnFactory = () => {
  return memoizeWith(toString, (arg1, arg2) => {
    // ... some expensive thing to be called/calculated
  })
}

// since the function reference will change over time
// it's needed to be referenced via on object or some other wrapper
const state = {
  fn: fnFactory()
}

// something happened, need to clear cache
document.getElementById('clear-cache').addEventListener('click', () => {
  state.fn = fnFactory()
})

document.body.addEventListener('click', () => {
  console.log(state.fn('arg1', 'arg2'))
})
```

**Comment by Qquanwei** [comment]
Can we add a new LRU Cache memorize function for ramda ? it will be helpful for high-frequence calc situation.

**Comment by CrossEye** [comment]
@Qquanwei: If you want to write one, feel free to create a PR.  While I can promise a fair hearing, my initial thought is negative.  It doesn't really seem a good fit with Ramda.  Perhaps, even if it's not accepted here, [ramda-adjunct][ra] might be interested in it.


  [ra]: https://github.com/char0n/ramda-adjunct

**Comment by Qquanwei** [comment]
Thanks , seems should do a real performance test before write this.
