### ISSUE TITLE
useWith and converge

### ISSUE THREAD

**Issue by stuartwhitehall** [ramda/ramda#2517]
Hi,

Can anyone help me understand why this code behaves as I expected (returns 1)

```
var myPredicate = curryN(2, function myPredicate(a, b) {
  return a;
});

useWith(
  flip(find)([0, 1, 2, 3]),
  [
    flip(myPredicate),
  ]
)('some state for myPredicate')
```
But if I swap the `useWith` for a `converge` then it does not (it returns a function)
```
var myPredicate = curryN(2, function myPredicate(a, b) {
  return a;
});

converge(
  flip(find)([0, 1, 2, 3]),
  [
    flip(myPredicate),
  ]
)('some state for myPredicate')
```

**Comment by CrossEye** [comment]
Careful, `lift` will take the place of `converge`, not of `useWith`.  We considered removing `converge` once we had `lift`, but it can handle certain variadic situations that `lift` cannot, so we've kept it... so far.

`useWith` is really only useful for making a pointed function point-free.  Sometimes there's value in that, but please don't make a fetish of point-free.

**Comment by stuartwhitehall** [comment]
I seem to come back to converge and useWith time and again when trying to solve a problem. Certainly I have been guilty of fetishizing point-free in the past (and maybe still), I'm trying to be better!

Thanks for your help.

**Comment by evan-king** [comment]
Converge is quite possibly my favorite function, and one I often use to demonstrate how elegant (and still readable) point-free programming can be.  Not my most used, but not uncommon to use either.  I'm sad that I'll probably never see a `convergeP` in core, for the rare times I need to converge with async operations.
