### ISSUE TITLE
tryCatch documentation error

### ISSUE THREAD

**Issue by edjroz** [ramda/ramda#2519]
Straight from the example of the tryCatch method:
```
const R = require('ramda');
console.log(R.tryCatch(R.prop('x'), R.F)(null));
```
Should return false, however it's returning undefined.

Passing a function and trying to console log anything from within doesn't seem to work either

```
console.log(R.tryCatch(R.prop('x'), () => {
  console.log(1)
  return false;
})(null));
```

**Comment by edjroz** [comment]
This issue actually doesn't happen because of the `tryCatch()` but actually because of `R.prop()` not throwing an error in regards the value receiving.

```Javascript
console.log(R.tryCatch(R.concat('a', R.__), R.F)('a'));  //=> false
```

**Comment by CrossEye** [comment]
Yes.  A PR for this would be most welcome.
