### ISSUE TITLE
map promises

### ISSUE THREAD

**Issue by elaich** [ramda/ramda#2521]
I want to use a function like `fetch` that returns a promise, and map it against an array of links, and I want it to return an array of responses instead of an array of promises, something like:

`R.map(fetch): Array<string> -> Array<response>`

**Comment by CrossEye** [comment]
It sounds as though you want [`Promise.all`][pa]:

```js
const urls = [
  'https://api.github.com/repos/ramda/ramda/issues?state=open',
  'https://api.github.com/repos/ramda/repl/issues?state=open',
  'https://api.github.com/repos/ramda/eslint-plugin-ramda/issues?state=open'
]

const then = fn => pr => pr.then(fn);
const json = resp => resp.json();
const get = compose(then(json), fetch)

Promise.all(R.map(get, urls))
  .then(map(length))
  .then(console.log)

//=> [30, 10, 1]
```
(https://goo.gl/eX12aQ)

  [pa]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by elaich** [comment]
I need my `R.map(fetch)` to return an array of responses rather than promises because I need it to compose with other fuctions:

```javascript
const run = R.compose(
  R.map(length),
  R.tap(console.log),  // [Promise {}, Promise {} ..]
  R.map(get),
)
```
run(urls);

**Comment by elaich** [comment]
Or I can use `then(length)`

**Comment by CrossEye** [comment]
You're not going to be able to get rid of the asynchronous nature of `fetch`.  The remainder of the program which uses it will also need to deal with the asynchrony,

But you can make `Promise.all` into a function to use in such compositions.
```js
const prAll = ps => Promise.all(ps) // or prAll = Promise.all.bind(Promise)

const run = pipe(
  map(get),
  prAll,
  then(map(length)),
  then(console.log),
)
run(urls)
```

(https://goo.gl/QBxGxG)

See also the recent discussion in #2512 and #2515.

**Comment by OlivierCuyp** [comment]
@CrossEye what the point of `prAll` ?
Won't it work exactly the same with just:

```js
const run = pipe(
  map(get),
  promise.all,
  then(map(length)),
  then(console.log),
)
run(urls)
```

**Comment by CrossEye** [comment]
@OlivierCuyp: I'm afraid it won't.  `Promise.all`, at least in certain environments, including Chrome and Node, is not a pure function.  I haven't looked at the implementation, but I assume it contains some `this` references.

It's easy enough to test.  See the differences between these two:

  - https://runkit.com/crosseye/promise-all-demo1
  - https://runkit.com/crosseye/promise-all-demo2

**Comment by OlivierCuyp** [comment]
@CrossEye Thanks for your answer with the demo.
But since it isn't the same, wouldn't it be nice to have this as a Ramda function ?
(maybe it already exists, I'm just starting playing around with Ramda...)

**Comment by CrossEye** [comment]
@OlivierCuyp:

It's always a hard call when deciding whether a function that is simple to write but commonly used is appropriate to include.  For instance, we have both `compose` and `pipe`.  It would be easy enough to offer only `compose`, and make users aware that they could just write

```js
const pipe = compose(apply(compose), unapply(reverse));
```

(... which would be even simpler if these weren't variadic (`const pipe = compose(compose, reverse)`.)

But this function is so common that it makes sense to include it.  Others, even though they are easy to write, don't seem common enough to include.  Ramda already is headed in a kitchen-sink direction.

But here it's actually an easy call.  Most of the Ramda core team is [fairly unimpressed][av] with Promises, preferring such lawful types as `Future`s or `Task`s.  We are trying to reduce our support for Promises to a minimal core (`andThen` and `otherwise`.)  There's more information about why at https://github.com/ramda/ramda/issues/2751#issuecomment-457631244.


  [av]: https://medium.com/@avaq/broken-promises-2ae92780f33

**Comment by trev-dev** [comment]
> You're not going to be able to get rid of the asynchronous nature of `fetch`. The remainder of the program which uses it will also need to deal with the asynchrony,
> 
> But you can make `Promise.all` into a function to use in such compositions.
> 
> ```js
> const prAll = ps => Promise.all(ps) // or prAll = Promise.all.bind(Promise)
> 
> const run = pipe(
>   map(get),
>   prAll,
>   then(map(length)),
>   then(console.log),
> )
> run(urls)
> ```
> 
> (https://goo.gl/QBxGxG)
> 
> See also the recent discussion in #2512 and #2515.

I'm attempting a refactor to Ramda using TypeScript for a webpack plugin with this pattern. It's making my eyes bleed a bit. This is likely more of a TS issue but if anyone here knows better than me I'd love to hear about it.
[
![Screenshot_2021-06-01_12-56-54](https://user-images.githubusercontent.com/28788713/120382773-ea9fd580-c2d8-11eb-94b3-190b215d7805.png)
](url)

```typescript
export const promiseAll = 
	(promises: Promise<any>[]) => 
		Promise.all<any>(promises)

export const prependChunk = (model: PluginModel) => async (chunk: Chunk) => {
  if (chunk.canBeInitial()) {
    const [firstFile] = chunk.files
    console.log(chalk.magentaBright(JSON.stringify(Array.from(chunk.files))))
    model.filename = firstFile
    model.extension = getExtension(model)

    try {
      model.content = await generateLogger(model)
      return model
    }
    catch (error) {
      console.error(chalk.redBright(error))
      return model
    }
  }
  return model
}

const prependWithModel = prependChunk(this.model)

const pipeline = R.pipe(
  R.map(prependWithModel),
  promiseAll
)

```

**Comment by CrossEye** [comment]
@trev-dev:

I'm afraid that for the most part, the Ramda team is not particularly adept at figuring out such Typescript problems.

I personally have no clue about why this error arises.

**Comment by trev-dev** [comment]
@CrossEye Fair, I took up my challenges in the TypeScript Gitter chat where I received helpful ideas/anecdotes about how to improve the Ramda typings or simply _get around_ them if I just want to get to work with TS & Ramda. I'll muddle through it from there. I love TS, but it's still based on JS which will forever be a bit goofy, and the types are written by humans, which speaks for itself.

**Comment by CrossEye** [comment]
I don't love TS.  But I also have not paid much attention to it.  While I've liked Flow better, I've also not paid attention to it, and it seems that TS has won that battle.  But a few years ago we would have been talking about CoffeeScript, and I have no idea what's next.  I simply don't try to keep up.  Sorry we couldn't help with this.  Best of luck!
