### ISSUE TITLE
v0.25.0 exported with reference to v0.24.1 

### ISSUE THREAD

**Issue by RobPethick** [ramda/ramda#2528]
Took me a while to be sure I had the updated version of ramda as in the dist folder of 0.25.0 there is a reference to 0.24.1

https://cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.js

**Comment by CrossEye** [comment]
It looks like that header was not build properly.  The 0.25.0 changes seem to be in there.  I'm not sure how that happened,, and I doubt we can fix it, but we will try to ensure that it doesn't happen again.
