### ISSUE TITLE
variable named "name" lens.

### ISSUE THREAD

**Issue by overflowz** [ramda/ramda#2530]
Was testing this piece in browser (Chrome).

```javascript
var name = R.lensProp('name');
console.log(name); // -> logs function as a string.
name(); // name is not a function.

var name1 = R.lensProp('name1');
console.log(name1); // logs function, as expected.
name1(); // no exception here.

var name2 = R.lensProp('name');
console.log(name2); // logs function, as expected.
name2(); // no exception here either.
```

Is this a bug (or browser-specific thing) or do I get something wrong?

**Comment by CrossEye** [comment]
```js
Object.keys(window).includes('name') //=> true
```

I'm guessing that it's also not a configurable property.

**Comment by overflowz** [comment]
Got it, thank you! Also please mind that I'm still learning FP alongside with Ramda and I might ask some weird questions though. Closing this.

**Comment by CrossEye** [comment]
No problem.  A place for a quicker answer is our [Gitter page][gp].  There are usually many helpful people there.


  [gp]: https://gitter.im/ramda/ramda

**Comment by overflowz** [comment]
Thank you, didn't knew that.
