### ISSUE TITLE
Missing keywords field in package.json

### ISSUE THREAD

**Issue by Undistraction** [ramda/ramda#2531]
I just noticed you are missing a [keywords](https://docs.npmjs.com/files/package.json#keywords) field in your `package.json`. I guess this probably isn't the biggest of problems given your popularity, but it's addition could only help people find their way to this library.

**Comment by CrossEye** [comment]
Any suggestions?  Want to offer a PR?

**Comment by Undistraction** [comment]
Sure. I'll put some suggestions in a PR and we can discuss there.

**Comment by CrossEye** [comment]
Great.  Thank you!

**Comment by dmitriz** [comment]
The keyword list on the Github repo could also be expended to include e.g. the FP keywords.
