### ISSUE TITLE
propOr returns null in case variable is null, but should return specified default value.

### ISSUE THREAD

**Issue by HammerSpb** [ramda/ramda#2534]
Works as expected [REPL](http://ramdajs.com/repl/?v=0.25.0#?var%20data%20%3D%20%7B%20education%3A%20null%20%7D%3B%0AR.pathOr%28%27N%2FA%27%2C%20%5B%27education%27%5D%2C%20data%29%3B%20%0A):
```js
var data = { education: null };
R.pathOr('N/A', ['education'], data); //=> 'N/A'
```
Works as unexpected [REPL](http://ramdajs.com/repl/?v=0.25.0#?var%20data%20%3D%20%7B%20education%3A%20null%20%7D%3B%0AR.propOr%28%27N%2FA%27%2C%20%27education%27%2C%20data%29%3B%20%0A):
```js
var data = { education: null };
R.propOr('N/A', 'education', data); //=> null
```

**Comment by CrossEye** [comment]
This will be fixed in the next release, hopefully very soon.

See e26fe5b for details.
