### ISSUE TITLE
partition fails with addIndex

### ISSUE THREAD

**Issue by chasm** [ramda/ramda#2536]
Unless I'm missing something, this appears to be broken:

https://goo.gl/47pN15

Another attempt:

https://goo.gl/m9ESKw

**Comment by Bradcomp** [comment]
Hi @chasm,

It is indeed the case that `partition` fails with `addIndex`. Here is a previous discussion on the same topic: https://github.com/ramda/ramda/issues/2000.

**Comment by chasm** [comment]
Thanks! Will check it out.
