### ISSUE TITLE
R.contains throws runtime error on `undefined`

### ISSUE THREAD

**Issue by lolcookie** [ramda/ramda#2537]
I am using R.prop with R.contains on the result and they do not compose since R.prop can return undefined.

What is the expected behaviour here?

**Comment by CrossEye** [comment]
If you have a default value, you might choose [`propOr`][po].

The only reasonable alternatives to the current behavior are to throw, which isn't composable either, or to make all library users work with `Maybe` types.  The latter is how Sanctuary works, but Ramda is meant to be more approachable for JS users, who are already used to Garbage In/Garbage Out.

I don't see any other choices.  Do you?

  [po]: https://ramdajs.com/docs/#propOr

**Comment by lolcookie** [comment]
Is it possible for ramda to throw a readable error on this to make it easier to debug?

**Comment by CrossEye** [comment]
I'm sure it could.  It's quite possible that we should just return `-1` in this case.

If you have a suggestion for what sort of error to throw, please let us know.  The relevant source is in [`internal/_indexOf.js`][io].  But I'm not too unhappy with this:

```shell

> const baz = R.pipe(
   R.prop('foo'),
   R.contains('bar')
 )

> console.log(baz({foo: ['qux', 'bar']}))

true

> console.log(baz({foo: ['qux']}))

false

> console.log(baz({}))

TypeError: Cannot read property 'indexOf' of undefined
    at _indexOf (/home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_indexOf.js:6:19)
    at _contains (/home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_contains.js:4:10)
    at /home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_curry2.js:22:18
    at f1 (/home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_curry1.js:18:17)
    at /home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_pipe.js:3:14
    at /home/scott/Dev/Temp/2018-05-21a/node_modules/ramda/src/internal/_arity.js:10:19
    at repl:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
```

  [io]: https://github.com/ramda/ramda/blob/master/source/internal/_indexOf.js

**Comment by lolcookie** [comment]
Is it not better to throw the error on the highest level instead of 3-4 levels deep?

I understand this may not be realistic or efficient to add errors at the highest level of every function but I'd happily do the work for this if it fit with the ramda philosophy.

`TypeError: Cannot read property 'indexOf' of undefined` 
Doesn't give me any information relating to contains method, instead an error like `Ramda.contains encountered an error with undefined argument` or similar would make debugging much easier.

**Comment by lolcookie** [comment]
That sounds like a good idea, but I'd also consider the semantics of error messages in javascript. 

Given that you have bad data I find it more reasonable to throw an error and alert the user that something has gone wrong instead of potentially obfuscating them with certain behaviours.

My issue here was that `contains` throws an `indexOf` error that is shared amongst multiple ramda methods causing difficulty debugging. 

If having a proper error message instead of making the user check the trace doesn't fit the philosophy then I am happy to close this issue.

**Comment by davidchambers** [comment]
@lolcookie, you may like to try [`S.prop`][1] as a replacement for `R.prop`:

```javascript
> S.prop ('a') ({a: 1, b: 2})
1

> S.prop ('b') ({a: 1, b: 2})
2

> S.prop ('c') ({a: 1, b: 2})
! TypeError: ‘prop’ expected object to have a property named ‘c’; {"a": 1, "b": 2} does not
```


[1]: https://sanctuary.js.org/#prop
