### ISSUE TITLE
Suggestion for clearer documentation

### ISSUE THREAD

**Issue by PaulGrimshaw** [ramda/ramda#2547]
We have been using Ramda for around a year now, and find it excellent.  The documentation is useful too, with the quick client side search.

However, one big gripe we have that particularly affects beginners, but also more advanced users is the use of other Ramda functions the examples.  This often means you have to go get your head round what the other function does just to understand how the current one works.  This convolutes and confuses the learning process.

I would suggest that every function is documented in the simplest form, using explicate predicates rather than composing other Ramda functions.  I know composition is at the heart of the framework, but at this point it is more detrimental than helpful.

A simple example from the docs:

```
var xs = [{a: 1}, {a: 2}, {a: 3}];
R.find(R.propEq('a', 2))(xs); //=> {a: 2}
R.find(R.propEq('a', 4))(xs); //=> undefined
```

Now for most users, this is fine as they understand `propEq`.  However a beginner may not have got that far yet, needs to go check what the `R.propEq(..)` function looks like.  Why not make this crystal clear:

```
var xs = [{a: 1}, {a: 2}, {a: 3}];
R.find(item => item.a === 2)(xs); //=> {a: 2}
R.find(item => item.a === 4)(xs); //=> undefined
```

You find this again and again in the docs:

```
var strEq = R.eqBy(String);
R.uniqWith(strEq)([1, '1', 2, 1]); //=> [1, 2]
R.uniqWith(strEq)([{}, {}]);       //=> [{}]
R.uniqWith(strEq)([1, '1', 1]);    //=> [1]
R.uniqWith(strEq)(['1', 1, 1]);    //=> ['1']
```

`R.eqBy`? `String`?  Yes this is some clever use of composition, but the purpose of the docs here should be to explain as clearly and as simple as possible the `uniqWith` function.

Now this may not be as funky and clever, but it immediately, at a glance, tells me how the uniqueWith function works:

```
var strEq = R.eqBy(String);
R.uniqWith( (x1, x2) => String(x1) === String(x2), [1, '1', 2, 1]);  //=> [1, 2]
```

Do others have thoughts on this?  I'm willing to accept that we may be in the minority here?

**Comment by PaulGrimshaw** [comment]
Another good example:
Set:

![image](https://user-images.githubusercontent.com/4194874/40645855-d4a782e6-6327-11e8-801c-9160d29cdf7b.png)

Ok, i need to go understand `lensProp`:

![image](https://user-images.githubusercontent.com/4194874/40645885-eb977c9a-6327-11e8-82ad-6708617f03d3.png)

`view`? `over`? `set`??

**Comment by mattgrande** [comment]
For what it's worth, I appreciated that Ramda uses its own functions a lot in the documentation; I found that it helped me understand how these small pieces could be put together to form a greater whole.

**Comment by PaulGrimshaw** [comment]
We were discussing here too, and it is true, it is useful.  Maybe a combination of both?

**Comment by PaulGrimshaw** [comment]
Agreed.  I haven't actually got my head around `set` yet, but didn't realise it was mostly used with `set`, `view` and `over`.  Might be a good to add a comment along your lines to the docs `The existing lens creators (lensProp, lensPath, lensIndex, and of course lens itself) are only useful in conjunction with other functions such as set, view, and over. And vice versa. `

**Comment by danielo515** [comment]
@CrossEye thanks for your terrific explanation. This is indeed one cool usage of lenses.
Mayabe you want to update your example:

```
view(farenLens, place) //=> 77
```

Note that the actual return value is 77, not 25.
Regards

**Comment by CrossEye** [comment]
@danielo515: Thank you.  Yes, that's rather the point!  :smile:.  Fixed.

**Comment by danielo515** [comment]
`a` and b on function signatures does not represent variables, but types. The fact that you specify an a on several places does not mean it is the same variable, it means it is of the same type.

**Comment by Bradcomp** [comment]
@ckeeney There is a very good explanation of the type signatures in the wiki: https://github.com/ramda/ramda/wiki/Type-Signatures

I agree they can be confusing at first, but they become very helpful once you get used to them.

**Comment by customcommander** [comment]
I sympathise with what you're saying @PaulGrimshaw and I agree with what @CrossEye said here:

> I think I agree that there should always be at least one (and probably the initial) example that uses no other Ramda functions. I'd love to see some PRs to change this. I think there could still be additional examples that do use Ramda functions. That helps with discovery, and with understanding that Ramda is designed around composition.

This isn't an issue we can "fix" once and for all. All we can do for now is update existing docs (where appropriate) and pay attention to this in future pull requests.
