### ISSUE TITLE
`R.reduce` curried with reference type argument is not pure

### ISSUE THREAD

**Issue by vclav** [ramda/ramda#2548]
This is side-effect of auto currying.

If you create a function with `R.reduce` by omitting third argument, and you provide second argument, the `initAccumulator` of `typeof === 'object'` (i.e. reference type), then this accumulator is bound for all calls, thus such curried `R.reduce` is not pure.

It might be sometimes useful, but IMHO it is hard to spot and it violates the philosophy of Ramda.

example here [https://ramdajs.com/docs/#reduced](https://ramdajs.com/docs/#reduced)

What do you thing? Shouldn't currying produce pure functions?

**Comment by Bradcomp** [comment]
I've definitely seen this as a source of bugs before, but generally it is the first parameter that is the culprit. It is only when the accumulator function mutates its input that this issue will manifest. 

```
//bad
reduce((acc, item) => {
  acc.push(item);
  return acc;
}, [])

//good
reduce((acc, item) => append(item, acc), []);
```

Because `append` doesn't mutate the input, the issue never arises. 

Even so, the issue can be subtle and tricky. Do you have a suggestion for how to fix it?

**Comment by vclav** [comment]
@Bradcomp you are right. Keep immutability in _reducer_ solves this.

The reducers are possibly the only callbacks, where I stick with single references. I assume huge overhead in generating intermediate objects, although I've never tested it, it's obvious that this produce a lot food for garbage collector without much benefits.

But it's clear now, that it's my habit that violates philosophy of Ramda, so this could be closed.

Thanks for reply ;)

**Comment by kurtmilam** [comment]
@vclav You (and anyone else interested in this topic) may find some of the discussion in this recent related issue informative: https://github.com/ramda/ramda/issues/2491
