### ISSUE TITLE
Documentation for R.__ placeholder not pointing to correct source file

### ISSUE THREAD

**Issue by KanoczTomas** [ramda/ramda#2550]
Hello,

If you check in the ramda docs page right below https://ramdajs.com/docs/#minBy the generated name of the R.__ placeholder says 'module.exports'. The source file for that links to module.export.js, which is clearly wrong. The correct file is https://github.com/ramda/ramda/blob/v0.25.0/source/__.js

**Comment by CrossEye** [comment]
Yes, it's on my list for this weekend.

https://github.com/ramda/ramda/issues/2542

**Comment by rpearce** [comment]
This seems to be fixed
