### ISSUE TITLE
confused with source code like path

### ISSUE THREAD

**Issue by MurakamiKennzo** [ramda/ramda#2552]
since ramada has defined some base function like ifElse、always、not, but when I look at path code, it look like:

```
var path = _curry2(function path(paths, obj) {
  var val = obj;
  var idx = 0;
  while (idx < paths.length) {
    if (val == null) {
      return;
    }
    val = val[paths[idx]];
    idx += 1;
  }
  return val;
});
export default path;
```
and if we defined like it :
```
var path = _curry2(function path(paths, obj) {
  let val = obj
  return ifElse(
    always(undefined)
  )(
    () => val
  )(
    any(path => not(val = prop(path)(val)))
  )(paths)
});
```
what about this definition mode ?

**Comment by MurakamiKennzo** [comment]
Ok, I got the point is that performance, right?

Thinking of this condition, If both they have the same performance(of course this is just a hypothesis)，Do second definition mode better than first one right?

Tthanks for your answer.

**Comment by MurakamiKennzo** [comment]
Great, Thanks for your answer.

Sorry to use ifElse not correctly, since it copy from my personal library [moy](https://github.com/MurakamiKennzo/moy/blob/master/src/object/path.js). Anyway, I prefer the recursion: definition mode.

And, I find a big bug from my version, like this:
```
path(['a', 'b'])({a: {b: null}}) // undefined
```

How foolish am I! 

It maybe solved with Array.prototype.some and give it index to judge.

but now, since I am new in ramada, if I define a function like this:
```
const isRamda = obj => compose(equals('ramda'), prop('name'))(obj) ? 'great' : 'not bad'
```

or define like this:
```
const isRamda = ifElse(
  compose(equals('ramda'), prop('name'))
)(
  always('great')
)(
  always('not bas')
)
```

Should I use ifElse or ?: ?

**Comment by MurakamiKennzo** [comment]
English is not good

**Comment by buzzdecafe** [comment]
in this particular case you may want to not use a lib at all, since the only thing that is varying is `obj`, and the internal composition is not buying you much:

`const isRamda = obj => obj.name === 'ramda' ? 'great' : 'not bad'`

**Comment by MurakamiKennzo** [comment]
Yes, I just give a simple example, just want When to use ifElse?

**Comment by CrossEye** [comment]
When to use `ifElse` is actually somewhat tricky.  There are a number of Ramda functions which make for nicely readable alternatives to their plain ES5 techniques but add little value in the days of ES6.

One can always write 

```js
const myFunc = (x, y) => condition(x, y) ? ifTrue(x, y) : ifFalse(x, y)
```

in place of 

```js
const myFunc = ifElse(condition, ifTrue, ifFalse)
```
and I would recommend it for many cases, especially if the functions are used only here.

But if any of the parameters (`condition`, `ifTrue`, or `ifFalse`) is reused elsewhere, the already shorter version using `ifElse` becomes the obvious choice.

Often point-free coding involves the trade-offs between code that is more explicit and code that more expressively demonstrates the interconnections between functions.

This:

```js
const collatz = (n) => (n % 2 === 0) ? (n / 2) : (3 * n + 1)
```
 is very explicit.  You know how the result will be calculated based on the input value.

This version, however, explicitly describes how certain functions are to be combined:

```js
collatz = ifElse(isEven, half, triplePlusOne)
```

But it's based on having reusable functions to work with.

There is no correct answer about when you should choose one over another.  It will depend on both your preferences about style and on your specific current need.
