### ISSUE TITLE
Documentation for tryCatch is not correct.

### ISSUE THREAD

**Issue by mrpotatoes** [ramda/ramda#2559]
Running this code returns an `undefined` not `false`.
```js
console.log(R.tryCatch(R.prop('x'), R.F)(null))
```

I have run this on both local, your repl and inline repl all of which are returning `undefined`.

Using `ramda: "^0.25.0"`

**Comment by Bradcomp** [comment]
Hi @mrpotatoes! Nice `catch`!

This is because the behavior of `R.prop` has changed to be in line with `R.path`, so the example will no longer throw an error.  Would you be interested in open a PR with a better example?

**Comment by CrossEye** [comment]
Interesting.  I swear I sent the same answer minutes after the issue was raised.  This happens every now and then; perhaps I leave something in Preview mode thinking I've sent it.  Damn, I'm getting old!

**Comment by otaviopace** [comment]
This PR fixes the issue: https://github.com/ramda/ramda/pull/2520
And it is already merged.

**Comment by JulianoGTZ** [comment]
Is this issue still open?

**Comment by CrossEye** [comment]
Not any more.  :smile:
