### ISSUE TITLE
Bug in 'all' and 'contains' with empty array; issues comparing arrays

### ISSUE THREAD

**Issue by kxcrl** [ramda/ramda#2570]
I'm trying to find out if the values of one array are contained in the values of another. I decided to just implement this in vanilla JS using `Array#some`, but it seemed like this was a bug in `all` so I figured I should put it here anyway.

```javascript
all(contains(__, ['a', 'b']))(['a'])
=> true // as expected

all(contains(__, ['a', 'b']))(['c'])
=> false // as expected

all(contains(__, ['a', 'b']))([])
=> true // should be false?
```

**Comment by bas080** [comment]
This is expected behavior. All checks if all items in array pass predicate. If no items are defined in the array, `all` will return true. The  contains predicate is never called.

**Comment by kxcrl** [comment]
@bas080 Interesting. Ok, thanks for the clarification. = )

**Comment by CrossEye** [comment]
This is called a [vacuous truth][vt].

One quick way to understand it is that this simple law seems useful to uphold:

    all(fn, concat(listA, listB)) == all(fn, listA) && all(fn, listB)

But that would fail if `all(fn, [])` were false, since `concat(listA, []) ~= listA`.


  [vt]: https://en.m.wikipedia.org/wiki/Vacuous_truth
