### ISSUE TITLE
Help describe this function beautifully with Ramda

### ISSUE THREAD

**Issue by inerc** [ramda/ramda#2571]
```javascript
const calculateRelated = (channels: Channels, selectedChannel: Channel): Array<Channel> => {
  let result = filter(channel => isNotEmpty(intersection(selectedChannel.genres, channel.genres)), values(channels))
  if (isEmpty(result)) {
    result = filter(
      channel => isNotEmpty(intersection(selectedChannel.categories, channel.categories)),
      values(channels),
    )
  }
  if (isEmpty(result)) {
    result = filter(channel => isNotEmpty(intersection(selectedChannel.languages, channel.languages)), values(channels))
  }
  return result
}
```

**Comment by foxbunny** [comment]
@inerc My impression is that you can't really make this function 'beautiful' without first decomposing it a bit, and making sure each decomposed part is doing only one thing. I would also want to think about the overall flow: "if I have some result, return it, otherwise try something else", and would look for a way to express this either by using what Ramda has or constructing a new function/monad that captures this idea.

**Comment by buzzdecafe** [comment]
You may want to seek this kind of input in the [ramda gitter room](https://gitter.im/ramda/ramda) rather than using the issues list.

**Comment by CrossEye** [comment]
While I agree with @buzzdecafe that the Gitter room (or [StackOverflow][so]) is the appropriate place for this sort of question, I did do some thinking about it.  And I might break it down in a manner like this:

```js
const falseIfEmpty = (fn) => (...args) => {
  const list = fn(...args)
  return isEmpty(list) ? false : list
}

const overlap = falseIfEmpty((prop, all, selected) => filter(
  channel => isNotEmpty(intersection(channel[prop], selected[prop])),
  values(all)
))

const calculateRelated = (channels, selectedChannel) => 
  overlap('genres', channels, selectedChannel)
    || overlap('categories', channels, selectedChannel)
    || overlap('languages', channels, selectedChannel)
    || []
```

`falseIfEmpty` might be included in your more general utilities, as it's fairly general.  It simply takes a function and returns a new function which returns the list created by the first function unless it's empty in which case it returns `false`.

`overlap` handles one stage of your testing. finding those channels which overlap the selected one in a single feature (`genres`, `categories`, etc.).

`calculateRelated` should do the same as your version (only slightly tested) using `overlap`.

The advantage here is that it breaks the problem into smaller pieces.  `overlap` might or might not be reusable.  But `falseIfEmpty` quite well could be.  And if you were to need multiple different functions that were similar but with different lists of features to test, then you could refactor this a bit further to work with a list like `['genres', 'categories', 'languages']`.

  [so]: https://stackoverflow.com/questions/tagged/ramda.js
