### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by shuhrat** [ramda/ramda#2573]
Hi there!

Probably there is an error in documentation, there is no ramda function called `module.exports` =)
Url - https://ramdajs.com/docs/#module.exports

**Comment by functionalStoic** [comment]
@shuhrat Yes it is being worked on. See https://github.com/ramda/ramda/issues/2550 and https://github.com/ramda/ramda/issues/2542

**Comment by CrossEye** [comment]
Yes, although quite slowly... :frown:

**Comment by def14nt** [comment]
Who does? The templates are awful. It's just a horrible system, and the docs suck which is irony at it's best.

**Comment by rpearce** [comment]
This seems to be fixed

**Comment by CrossEye** [comment]
Yes, we seem to have had a few issues for this.  Thanks.
