### ISSUE TITLE
Can I get the number of cases?

### ISSUE THREAD

**Issue by hyunsooda** [ramda/ramda#2578]
Hi, I'm korean student.
I have a question about implementation of string classification using your library.
for example, if I give a value as 'abc', the result that I want is 'abc', 'acb', 'bac', 'bca', 'cab', 'cba'

I have implemented string classification program, but that program only work within 6 characther.
about more charachter, that is hard to me to implment.
Is useful this libarary when it comse to implement this program?
if so, can you provide material realted to this?

Thank you, have a nice day:)

**Comment by bas080** [comment]
This is referred  to as [permutations](https://en.wikipedia.org/wiki/Permutation).
