### ISSUE TITLE
Issue with documentation: R.__

### ISSUE THREAD

**Issue by vanyadymousky** [ramda/ramda#2579]
![screen shot 2018-07-07 at 5 07 23 pm](https://user-images.githubusercontent.com/922747/42411664-4cbec948-8208-11e8-9f9b-c05b6e14a35e.png)

**Comment by Bradcomp** [comment]
Thanks @vanyadymousky . We're aware of this and working on a fix: https://github.com/ramda/ramda/issues/2573

**Comment by rpearce** [comment]
This seems to be fixed
