### ISSUE TITLE
prop assertion methods should be safe

### ISSUE THREAD

**Issue by jackmellis** [ramda/ramda#2583]
So to my mind, `propEq` and `propSatisfies` should be safe methods, like `prop`. But if you call either of these with null/undefined it throws.

Essentially I would expect to get the same result for all three of these examples:

```js
R.pipe(
  R.prop('foo'),
  R.equals('bah'),
)(null); // false
```

```js
R.propEq('foo', 'bah', null); // Cannot read property 'foo' of null
```

```js
R.propSatisfies(r.equals('bah'), 'foo', null);  // Cannot read property 'foo' of null
```

If I were to write the same examples using `path`, `pathEq`, and `pathSatisfies` I would get `false` each time.

Potentially breaking but it would be a lot more consistent. This catches me out on a regular basis. If I wanted strict type assertions I'd be using sanctuary :stuck_out_tongue_closed_eyes:

**Comment by CrossEye** [comment]
I agree and would love to see a PR for this.  I

**Comment by humanamburu** [comment]
Hello @CrossEye,

PR was created almost a year ago but still not merged yet. Do you have any updates on this?
Thank you in advance.

**Comment by CrossEye** [comment]
The update is simple: I missed the PR.  Somehow I don't think I ever saw it.  Merged now.

**Comment by humanamburu** [comment]
@CrossEye thank you! 👍
