### ISSUE TITLE
Proposal to translate the documentation to Portuguese

### ISSUE THREAD

**Issue by pacheco7** [ramda/ramda#2608]
Hello :)

Can be viable translate the documentation to Portuguese? What roadmap for it?

**Comment by CrossEye** [comment]
Please see [this thread][pt]. Some links (also linked in previous thread)

https://github.com/ramda/ramda/issues/1951
https://github.com/ramda/ramda/pull/2201

in particular this comment:

https://github.com/ramda/ramda/pull/2201#issuecomment-307977821


  [pt]: https://github.com/ramda/ramda.github.io/issues/196
