### ISSUE TITLE
Is there an interest in/need for a hasPath function?

### ISSUE THREAD

**Issue by mattgrande** [ramda/ramda#2609]
I've felt like I could use a `hasPath` function a few times; I've always gotten around it by using both `path` _and_ `has` and it's been fine, but I'm considering making a PR for `hasPath` if there is support for it.

    const user = { first_name: 'Cotten Eyed', last_name: 'Joe', address: { line_1: '123 Fake Street' }};
    R.hasPath(['last_name'], user);
    > true
    R.hasPath(['address', 'line_1'], user);
    > true
    R.hasPath(['address', 'line_2'], user);
    > false

**Comment by CrossEye** [comment]
While I can't guarantee that it would be accepted, I can see easily see something like this adding consistency.  So I'd love to see one.

**Comment by otaviopace** [comment]
This should be closed, look at this PR: https://github.com/ramda/ramda/pull/2501 @ramda/core
