### ISSUE TITLE
Deprecate pluck

### ISSUE THREAD

**Issue by GingerPlusPlus** [ramda/ramda#2615]
`pluck('foo')` == `map(prop('foo'))`, and it's trivial to figure it out.

It feels as if `pluck` was added early to mirror underscore, which needed it because it doesn't have curried, data-last `prop`.

**Comment by Bradcomp** [comment]
I think `pluck` covers a really common use case. We use it all the time. On our team it's preferred to using `map(prop('foo'))`.

There's plenty of stuff I wouldn't mind deprecating, but this is a really nice function, even if it's easy to create.

**Comment by buzzdecafe** [comment]
> Even more trivial: `head == nth(0)`. And no, I don't think it should go.

In general, your points are well taken. The case of `head` is a bit special, because we want to pretend that head is operating on *lists* (i.e. not indexed); defining `head` in terms of `nth` binds you to a particular data structure under the covers. 

personally i'd be happy to remove `pluck`, if only to reduce the lib's footprint. But I don't feel strongly, and am receptive to the "common use case" argument in this case.

**Comment by CrossEye** [comment]
I just started a new job a month ago, so I haven't built up a large codebase here using Ramda.  I will check on some personal repos at home, but I'm guessing that `pluck` is in the top dozen functions I use.  Yes, it's derivable, but then `map`, `filter`, `find`, and many others are derivable from `reduce`.

If we're looking to clean up, I'd much rather look at other things.  `*last*` comes to mind, as does transducer support.

**Comment by GingerPlusPlus** [comment]
> the name describes what is does fine

This is interesting.

I'm not a native English speaker, and I don't think the word is commonly used; I only learnt its meaning today. And I couldn't find any spot-on translation to my native language. Maybe that's why the function haven't "clicked" for me.

Closing until there are more people supporting the deprecation.

<hr />

> I'd much rather look at other things.

`R.forEach`?

> `*last*` comes to mind, as does transducer support.

`last` is not pretty to define: `const last = array => array[array.length - 1]`, please leave it in.

And, about transducers, I think you haven't utilized them to their fullest. They can be used to implement some transformations in a type-agnostic way, reducing the needs to switch on types. I expect to submit a proposal to you about this in next few days.

**Comment by CrossEye** [comment]
> I'm not a native English speaker, and I don't think the word is commonly used;

I do think it's fairly common.  As a verb it means to pull or pick something using some force or speed.  *Plucking ones eyebrows* is thinning them by forcefully pulling out individual hairs.  It's also used to denote something being removed *from* a certain situation: "The principal plucked the guilty children from their classrooms, one by one."  All in all, it's not a bad fit, and certainly nicer than 

```js
const pullTheNamedPropertyFromEachObjectInTheArray = (name) => (xs) => ...
```

:smile:

As to `*last*` it's not just the `last` function, but also `dropLast`, `dropLastWhile`, `findLast`, `findLastIndex`, `lastIndexOf`, `takeLast`, and `takeLastWhile`.  I'd like Ramda to be as useful as possible with streams, with car-cdr style lists, with infinite lists, etc.  None of these makes any sense in many of the environs.  I do not have any great drive to remove these, BTW.  This was simply the first thing to come to my head after transducers.

And speaking of transducers, I'm curious to see what you are going to suggest.  Just so you know, though, I may not see it for a while, as I leave Sunday for a two-week vacation.

**Comment by foxbunny** [comment]
propEach?

And yes, that is a very nice bike shed. 😋

**Comment by Bradcomp** [comment]
> `R.forEach`

👍  I am definitely for deprecating this one (and the related and very awkwardly named `forEachObjIndexed`).

While they are useful for explicitly executing side effects, they're also an odd fit for Ramda, and not hard to create on your own.
