### ISSUE TITLE
`R.split` should work on lists and not just strings

### ISSUE THREAD

**Issue by Bradcomp** [ramda/ramda#2619]
Does that seem reasonable? I am a little hesitant due to how weird strings are in JS with no underlying char class.

**Comment by Bradcomp** [comment]
`split(0, [1, 0, 2, 3, 0, 4, 5]); //=> [[1], [2, 3], [4, 5]]`
`split(0, [0, 1, 0, 2, 0, 3]); //=> [[1], [2], [3]]`

What you have there is `filter` 😛

**Comment by buzzdecafe** [comment]
thx, wasn't cear what you were after. Why wouldn't the second one be 

`split(0, [0, 1, 0, 2, 0, 3]); //=> [[], [1], [2], [3]]`

**Comment by Bradcomp** [comment]
Isn't that what I have? I initially had it without the empty list, but almost immediately edited it.

**Comment by buzzdecafe** [comment]
![image](https://user-images.githubusercontent.com/716260/43458714-3cc13596-9499-11e8-9b04-ebed451e2495.png)

I must've gotten in there before you updated. I retract the question :-)

**Comment by tylerwray** [comment]
I'd like to take this if no one is working on it yet.

**Comment by atassis** [comment]
@Bradcomp since split function works with strings only in javascript, python, php, java and many others, I suppose making split for non-string iterables is a bad idea.

**Comment by customcommander** [comment]
This proposal doesn't seem to be gaining much traction. Any objection to close for now @ramda/core ?
