### ISSUE TITLE
R.either / R.both should take more than 2 args

### ISSUE THREAD

**Issue by Mati365** [ramda/ramda#2631]
https://ramdajs.com/docs/#either
as you can at the top of section is:
`(*… → Boolean) → (*… → Boolean) → (*… → Boolean)`
it can mislead programmer to use something like it:
`R.either(R.isNil, R.isEmpty, R.is(Number))(2)` which ignores last arg

**Comment by Bradcomp** [comment]
Hi @Mati365 

Thanks for your issue. the type signature here is correct, but I can see how it might be misleading. It says that the function takes two functions each of which return a boolean, and returns a function that returns a boolean. For more information on the type signatures, I would recommend this article in the wiki: https://github.com/ramda/ramda/wiki/Type-Signatures

If you need a function that takes more than two predicates, there's `anyPass` which will take an array of predicates instead.

**Comment by Mati365** [comment]
Thank you! It was that I was looking for :D

**Comment by inferusvv** [comment]
In case of issue author boolean result is ok. So `anyPass` can be used. But can anyPass return result of valid function? I have many possible paths (with priority) and want to take first valid.

**Comment by CrossEye** [comment]
I answered what I assume is your [StackOverflow question][so], but the main point here is that there is no built-in function for this.  It's not hard to write a custom one though, as demonstrated by the answers on SO.


  [so]: https://stackoverflow.com/questions/54455662/

**Comment by buzzdecafe** [comment]
`cond`
