### ISSUE TITLE
Lenses functions are undefined

### ISSUE THREAD

**Issue by HerlinMatos** [ramda/ramda#2634]
const { lens, lensProp } = require("rambda");

are undefined

**Comment by functionalStoic** [comment]
Try:

```
const { lens, lensProp } = require("ramda");
```

or if you are actually trying to use the [Rambda](https://github.com/selfrefactor/rambda) library as opposed to this library, install it.

**Comment by HerlinMatos** [comment]
Thank you @functionalStoic , I see the error.
