### ISSUE TITLE
Is there an interest in/need for a inRange function?

### ISSUE THREAD

**Issue by n0ruSh** [ramda/ramda#2636]
inRange: Ord a => a → a → a -> Boolean
```
R.inRange(10, 20, 11);   //   10 < 11 < 20
> true
R.inRange(10, 30, 100); // 100 > 30
> false

**Comment by Qquanwei** [comment]
you can using `R.median([10, 20, 11]) === 11`

**Comment by buzzdecafe** [comment]
This strikes me as a particular case of a function that represents a set of constraints. `allPass` is the more general, conjuctive case of this type of function (`anyPass` would work for disjunction):

```
const inRange = (low, high) => R.allPass([
    x => x > low, 
    x => x < high
]);

inRange(10, 20)(11) //=> true
inRange(10, 20)(100) //=> false
```

**Comment by CrossEye** [comment]
See previous discussions in #1603 and #2497.

While this function can be useful, it is a better foot for one of the auxiliary libraries or the Cookbook.
