### ISSUE TITLE
destructBy, padEnd, repeatStr

### ISSUE THREAD

**Issue by trustedtomato** [ramda/ramda#2638]
I've been working on a project where we heavily use Ramda.
I love it so much! Thanks for all the effort you put into it!

While working on the project, I've made some functions which might be suitable for the library too.

---

`padEnd` & friends:
```javascript
const padEnd = curry((n, str) => str.padEnd(n));
const padEndWith = curry((n, str, padString) => str.padEnd(n, padString));
const padStart = curry((n, str) => str.padStart(n));
const padStartWith = curry((n, str, padString) => str.padStart(n, padString));
```

---

`repeatStr`:
```javascript
const repeatStr = curry((n, str) => str.repeat(n));
```

---

`destructBy`:
This function returns a destruction of the given object, where the destruction is guided by a functor filled with functors and (transform) functions.
```javascript
const destructBy = curry((destructor, x) => {
	if(typeof destructor === 'function'){
		return destructor(x);
	}
	return map(
		childDestructor => destructBy(childDestructor, x),
		destructor
	);
});
```
Example use case:
```javascript
const users = [...];

const emails = new Map(
	map(
		destructBy([
			prop('username'),
			prop('email')
		]),
		users
	)
);
```

---

Let me know what you think!
I would be happy to do a pull request! :)

**Comment by CrossEye** [comment]
I think that the string manipulation functions would make sense in the [Cookbook][cb] or one of the auxiliary libraries, [ramda-adjunct][ra] or [ramda-extension][re].

`destructBy` is more interesting.  Although its output is different, it reminds me of 
[`applySpec`][as].  In fact, there is a fairly simple implementation of `destructBy` in terms of `applySpec`:

```js
const destructBy = curry(compose(values, (spec, obj) => applySpec(spec)(obj)))

const foo = destructBy({
  username: path(['user', 'name']),
  email: path(['contact', 'email'])
})

foo({
  user: {id: 1, name: 'fred'},
  contact: {email: 'fred@bedrock.com', phone: '8675309'}
})
//=> ["fred", "fred@bedrock.com"]
```

(A straight `applySpec` would have generated `{username: "fred", email: "fred@bedrock.com"}`.)

I find `applySpec` more generally useful, although the variadic output function is not wonderful.

Given that, @trustedtomato, do you think it's still a function important to include in Ramda?

  [as]: https://ramdajs.com/docs/#applySpec
  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [ra]: https://github.com/char0n/ramda-adjunct
  [re]: https://github.com/tommmyy/ramda-extension

**Comment by trustedtomato** [comment]
Thanks for the quick response!

Your implementation seems a bit off. Looking at the docs & reply, I found that the correct implementation is just `const destructBy = binary(applySpec)`.
I find the name `destructBy` more descriptive, but it is really just a stripped down version of applySpec.

I'm going to look at the cookbook and extension libraries, thanks for letting me know they exist! :)

**Comment by CrossEye** [comment]
Yes, I did misread your original, thinking the output was an array.  Clearly `binary(applySpec)` is better.

As to the name, you've probably heard the famous quote from Phil Karlton: 

> "There are only two hard things in Computer Science: cache invalidation and naming things."

Or my favorite gloss on it:

> There are only two hard things in Computer Science: cache invalidation, naming things, and off-by-one errors.
