### ISSUE TITLE
The current npm version is not rename key side-effects to sideEffects

### ISSUE THREAD

**Issue by yuriigeivakh** [ramda/ramda#2640]
Hi,
In the current version of the npm package, the old version of package.json has a misspelling in the sideEffects key (old was named side-effects). This was fixed by the commit (here is link: https://github.com/ramda/ramda/commit/b0b1c1fdaa04fbd6ca494d952aa511339c90f0f6) but so far npm is delivering the version with an error. Because of this, tree shaking does not work with Webpack. Could you please rebuild the package?

**Comment by CrossEye** [comment]
We should be getting a new version out soon.  I don't know if there's any way to republish an existing version to NPM.

**Comment by customcommander** [comment]
Property has been renamed and should be available in 0.28.0. Closing for now.
