### ISSUE TITLE
Deep merge with empty object doesn't work as expected

### ISSUE THREAD

**Issue by aryo** [ramda/ramda#2643]
## Example
```javascript
const obj1 = { outer: { inner: "test" } };
const obj2 = { outer: {} };
const result = mergeDeepRight(obj1, obj2);
// result: { outer: { inner: "test" } }
// expected: { outer: {} }
```
It should replace the outer branch with an empty object

**Comment by Qquanwei** [comment]
Maybe `mergeDeepWith` is your looking for. 

quote `mergeDeepRight` document
> and both values are objects, the two values will be recursively merged

**Comment by Bradcomp** [comment]
I agree with @Qquanwei that `mergeDeepWith` would be better for your use case. `mergeDeep[Left|Right]` are built to recursively merge objects. For more complicated logic the `With` versions should be used.
