### ISSUE TITLE
Inconsistent behaviour of `pathOr` and `propOr`

### ISSUE THREAD

**Issue by bzums** [ramda/ramda#2644]
Hey all, I am puzzled because of the output of the following [snippet](https://ramdajs.com/repl/?v=0.25.0#?console.log%28%27a%27%2C%20R.pathOr%28%7B%7D%2C%20%5B%27some%27%5D%2C%20%7B%20some%3A%20undefined%20%7D%29%20%3D%3D%3D%20undefined%29%20%2F%2F%20false%0Aconsole.log%28%27b%27%2C%20R.pathOr%28%7B%7D%2C%20%5B%27some%27%5D%2C%20%7B%7D%29%20%3D%3D%3D%20undefined%29%20%2F%2F%20false%0Aconsole.log%28%27c%27%2C%20R.propOr%28%7B%7D%2C%20%27some%27%2C%20%7B%20some%3A%20undefined%20%7D%29%20%3D%3D%3D%20undefined%29%20%2F%2F%20true%0Aconsole.log%28%27d%27%2C%20R.propOr%28%7B%7D%2C%20%27some%27%2C%20%7B%7D%29%20%3D%3D%3D%20undefined%29%20%2F%2F%20false%0A%0Aconsole.log%28%27---%27%29%3B):

```js
console.log(R.pathOr({}, ['some'], { some: undefined }) === undefined) // false
console.log(R.pathOr({}, ['some'], {}) === undefined) // false
console.log(R.propOr({}, 'some', { some: undefined }) === undefined) // true
console.log(R.propOr({}, 'some', {}) === undefined) // false
```

I found this confusing and had a look at the implementation which confused me more since `propOr` just proxies the call to `pathOr`: https://github.com/ramda/ramda/blob/master/source/propOr.js#L32 => how can the behaviour be different? 

Furthermore, the documentation says:

> If the given, non-null object has an own property with the specified name, returns the value of that property.

The wording "has own property" leads imo to the understanding that `hasOwnProperty` is actually used in the implementation. Imo that would also explain the behaviour from above since:

```js
Object.hasOwnProperty.call({ test: undefined }, 'test'); // true
```

What am I missing here and could the documentation be more explicit in some way?

__Update:__
I had a look at the test cases: https://github.com/ramda/ramda/blob/master/test/propOr.js#L27 this test seems to contradict with the code snippet, am I right?

**Comment by CrossEye** [comment]
We simply have not had a release since that was fixed.   It should work soon.

**Comment by bzums** [comment]
Perfect, will close this one then.
