### ISSUE TITLE
Proposal: between or inRange

### ISSUE THREAD

**Issue by slavaGanzin** [ramda/ramda#2651]
Hello everyone.

I propose to add function:
```js
R.between = R.curry((from, to, value) => from < value && value < to)
```

It's very convenient when you don't need to store `value`, e.g. evaluate on fly:
```js
inLastHour = R.between(new Date() - 60 * 1000, new Date())
inLastHour(myVeryComplicatedSQLQuery())
```

Currently this can be done with allPass, but reads harder:
```js
inLastHour = allPass(lt(new Date() - 60 * 1000), gt(new Date()))
```

I can do PR

**Comment by tommmyy** [comment]
Hi, see https://github.com/ramda/ramda/pull/2497
