### ISSUE TITLE
Why there is no docs for 0.26?

### ISSUE THREAD

**Issue by otaviopace** [ramda/ramda#2652]
I was looking for the documentation for the `hasPath` function when I realized that it was on the code, and introduced on `0.26`, but not on the docs. Is there a reason for that? How can I contribute to make that happen?

**Comment by CrossEye** [comment]
We still haven't released 0.26.  Someone (and I think that means me) needs to get a new release cut.

**Comment by otaviopace** [comment]
Ok! I see
