### ISSUE TITLE
Incorrect documentation for `replace()`

### ISSUE THREAD

**Issue by foxbunny** [ramda/ramda#2653]
The `replace()` function is documented as `RegExp|String → String → String → String`, but the second argument can also be a function due to the fact that `replace()` just delegates to `String.prototype.replace()`.

**Comment by CrossEye** [comment]
Interesting.  I've never used it that way, but you're absolutely right.  Want to make a quick PR?

**Comment by Bradcomp** [comment]
Before making a PR, we should ask if that is behavior we want to explicitly support? Just because it's possible doesn't mean it should be documented.

It might be better to just note that it delegates to String.replace, and people can then use that knowledge as they will.

**Comment by foxbunny** [comment]
I'm not opposed to either solution. Let me know what kind of PR you want. :)

**Comment by foxbunny** [comment]
This is (I assume) what the signature would look like if it were modified to match the actual behavior:

```
RegExp|String → (String|((*...) → String))  → String → String
```

Original documentation is [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter). If groups are used in the RegExp (first argument to `replace()`), the function can take a variable number of arguments, but then two more arguments are always supplied after them. 

I think making the signature more specific would not be very helpful without repeating the specification of the `String.prototype.replace()` function. Therefore, the user might still need to be told the Ramda function delegates to `String.prototype.replace()` so go look that up. In other words, what @Bradcomp suggests would probably be a good enough remedy, and would be necessary either way.
