### ISSUE TITLE
Wrong example for tryCatch

### ISSUE THREAD

**Issue by slavaGanzin** [ramda/ramda#2658]
This line in documentation is wrong because `R.prop` returns `undefined` and not throws when property is absent in supplied value:
```js
R.tryCatch(R.prop('x'), R.F)(null); //=> false
```

And this works as expected:
```js
R.tryCatch(x => x.x, R.F)(null)
```

**Comment by CrossEye** [comment]
This was fixed in #3894adde.  The docs will be updated when we release a new version.
