### ISSUE TITLE
Why trim and keys have a pre-underscore in the documentaion?

### ISSUE THREAD

**Issue by OsamaAbbas** [ramda/ramda#2659]
The first two functions in the documentaion are `_keys` and `_trim`. Obviously they are: `keys` and `trim`. The examples also says `R.keys` and `R.trim`, and the "source" url is broken, unless the _ is removed from it.

https://github.com/ramda/ramda/tree/v0.25.0/source/_keys.js (broken)
https://github.com/ramda/ramda/tree/v0.25.0/source/keys.js (OK)

Is this just a typo or there is some reason for that?

**Comment by CrossEye** [comment]
It was a bug in the documentation generation.  It should be fixed as soon as we release a new version.

**Comment by rpearce** [comment]
This seems to be fixed
