### ISSUE TITLE
Tap doesn't handle undefined or null properly.

### ISSUE THREAD

**Issue by paulpdaniels** [ramda/ramda#2661]
I'm not sure if this is just a case of not properly safeguarding our code, but we noticed while attempting to use `tap` to debug some ramda pipelines that we ended up getting additional errors thrown. Consider this [repl](https://ramdajs.com/repl/?v=0.25.0#?var%20xs%20%3D%20%5B%7Ba%3A%20%27a%27%7D%2C%20%7Ba%3A%20%27b%27%7D%2C%20%7Ba%3A%20%27c%27%7D%5D%3B%0AR.pipe%28%0A%20%20R.find%28R.propEq%28%27a%27%2C%20%27d%27%29%29%2C%0A%20%20R.prop%28%27a%27%29%0A%29%28xs%29%3B%20%2F%2F%3D%3E%20%7Ba%3A%202%7D). Which returns the expected: `undefined`. If we add a `tap` to this though ostensibly to check the output of the `find` we instead received a confusing error about `@@tranducer/step` not being a function. Seen [here](https://ramdajs.com/repl/?v=0.25.0#?var%20xs%20%3D%20%5B%7Ba%3A%20%27a%27%7D%2C%20%7Ba%3A%20%27b%27%7D%2C%20%7Ba%3A%20%27c%27%7D%5D%3B%0AR.pipe%28%0A%20%20R.find%28R.propEq%28%27a%27%2C%20%27d%27%29%29%2C%0A%20%20R.tap%28a%20%3D%3E%20console.log%28a%29%29%2C%0A%20%20R.prop%28%27a%27%29%0A%29%28xs%29%3B%20%2F%2F%3D%3E%20%7Ba%3A%202%7D). 

I tracked down the source of this which seems to be the `isTransformer` method that `tap` calls internally. Its made additionally confusing because `tap` isn't referenced, instead the stack starts with `curry2` and `dispatchable` which are executed before `_xtap`. Is this expected behavior? Is there a way to handle these gracefully?

**Comment by kurtmilam** [comment]
The underlying issue has been addressed here: https://github.com/ramda/ramda/pull/2344 .

That PR has been merged but we're waiting on a release.
