### ISSUE TITLE
clone loses constructor methods

### ISSUE THREAD

**Issue by jk121960** [ramda/ramda#2690]
I recently started using Ramda and overall I have been very happy, I have s simple Maybe monad that I use and when I clone the monad with R.clone is loses the instance methods of the monad while keeping the static. So as not to find out it is me with the problem. I tried underscore-contribs _.snapshot and the instance methods were back and working where they should be. Is this a known behavior? Is it scheduled to be changed or fixed? Thanks

**Comment by CrossEye** [comment]
Yes, this is a known, and expected, behavior of Ramda.

Ramda does not try very hard to work well with OO code.  Working with constructors and the prototype chain has never been a strong motivation for us.  Moreover, there is, as far as I know, no bulletproof way to clone a constructed object.  Perhaps `_.snapshot` has some tricks that Ramda doesn't try, but I'm betting that there are still fairly normal JS objects that it cannot clone well either.

For a `Maybe`, however, you should have a straightforward option.  Simply `myMaybe.map(clone)` should return a cloned version of `myMaybe`.

OTOH, why in the world do you want a clone of a `Maybe`?  A well-behaved Maybe is likely to be immutable, so what can you do with a clone that you can't do with the original?

**Comment by jk121960** [comment]
Hi and thanks, the maybe is incidental and merely part of the flow, it is the data that I am cloning. I could have extracted the data and then cloned but was avoiding a couple of statements to wrap and unwrap. I do appreciate the quick reply, I'll just package snapshot and use that. I really like I said have enjoyed the library and it fits with my approach better than the underscore or lodash libraries. Thanks for Ramda and Cheers!

**Comment by CrossEye** [comment]
Ok, glad to hear you have something that should work.  But again, unless it's the content of the Maybe that has the missing methods, `.map(clone)` should do what you need.

Best of luck!

**Comment by jk121960** [comment]
Thanks, and yes I'm fine. It is good to know the limitations of the clone in any event. Precisely what the structure is, is, a Maybe -> array -> (maybe)s -> data. I leave the Maybe's on to use the check methods as to the state of the data, this being a big part of what makes maybe's useful. Basically what was happening is the methods of the inner maybe that wrap around the individual data pieces not the main maybe that wraps the array, were losing the check methods (isJust, etc), but the basic structure was still intact. THis stopped me from checking the data state. it was actually popping on the use of the getOrElse method, even though in debug is still showed as a maybe and the data was there. The code for snapshot is not that involved but still seems to capture the methods. As seen here. 

function snapshot( obj ) {
	if ( obj == null || typeof(obj) != 'object' ) {
		return obj;
	}
	var temp = new obj.constructor();
	for ( var key in obj ) {
		if ( obj.hasOwnProperty( key ) ) {
			temp[ key ] = deepClone( obj[ key ] );
		}
	}
	return temp;
}

Thanks again for the quick replies I'm good just added a copy of this to a library file.
