### ISSUE TITLE
[Feature] Move item in a list

### ISSUE THREAD

**Issue by MadDeveloper** [ramda/ramda#2692]
Unless I'm mistaken, or have not found the function in the documentation yet, is it possible to add a function which permits to move and item in a list?
The simplest solution I found for now:
```javascript
const move = curry((at, to, list) => insert(to, prop(at, list), remove(at, 1, list)))
```

I'm new to Ramda, so my function could be simplified, but even if it's possible I think that a `move` function could be nice 😉

**EDIT**
An issue had been opened (https://github.com/ramda/ramda/issues/2218) but I don't see a solution. It's not exactly the same needs, but it's similar.

**Comment by CrossEye** [comment]
This is more general than what was suggested in #2218.  You could easily build `swap` atop such a `move`.  This is barely tested, and might fail on some boundary conditions, but I think it's close:

```js
const move = curry((at, to, list) => insert(to, nth(at, list), remove(at, 1, list)))

const swap = curry((idx1, idx2, list) => move(
  idx2 + (idx1 > idx2 ? 1 : -1), 
  idx1, 
  move(idx1, idx2, list))
)
```

I'm still less interested in `swap`, but there have been more requests for it, and `move` seems even more useful.  So, while there's no guarantee it would be accepted, I for one would love to see a PR for this.

**Comment by MadDeveloper** [comment]
Indeed the `move` permits to built from it some other functions, for examples: (I took back your swap function):
```javascript
const swap = curry((a, b, list) => move(b + (a > b ? 1 : -1), a, move(a, b, list)))
const rotateN = curry((n, list) => n === 0 ? list : rotateN(n - 1, move(-1, 0, list)))
const rotate = list => rotateN(1, list)

console.log(rotate(list)) // [4,1,2,3]
console.log(rotateN(2, list)) // [3,4,1,2]
console.log(swap(2, 3, list)) // [1,2,4,3]
```
If I have to write other functions (like swap, rotate, rotateN (or only fews of them)), do I need to make one PR for each, or I can bulk all in one?

**Comment by semmel** [comment]
`move`, `swap`, `rotate*`, ... would all be nice to have. :+1: 

This is how I do 1x rotate though:

```javascript
rotateRight = R.converge(R.prepend, [R.last, R.init]),
rotateLeft = R.converge(R.append, [R.head, R.tail])
```

**Comment by MadDeveloper** [comment]
@semmel thank's for `rotate*`, I noticed I'd forgotten the side of the rotation! I've updated my previous comment.

**Comment by CrossEye** [comment]
How about if you just do a  PR for `move`, which is what would make all these others easy to do?  If that's approved, then we can look at the others.

**Comment by MadDeveloper** [comment]
Done: https://github.com/ramda/ramda/pull/2694

**Comment by CrossEye** [comment]
@semmel:

I would prefer

```js
const rotateRight = R.lift(R.prepend)(R.last, R.init)
const rotateLeft = R.lift(R.append)(R.head, R.tail)
```

I always try to replace `converge` with the more standard `lift` when I can.  (I can't always, as `converge` is more flexible.)
