### ISSUE TITLE
Ramda documentation references ramda@0.25.0

### ISSUE THREAD

**Issue by char0n** [ramda/ramda#2716]
Documentation https://ramdajs.com/docs references in html following javascript file: https://ramdajs.com/docs/dist/ramda.js. Unfortunately this file is ramda@0.25.0 bundle instead of ramda@0.26.0

**Comment by CrossEye** [comment]
Yes, I noticed this too.  I will try to look at why tomorrow.

**Comment by damian-callstats** [comment]
I believe this bundle should be updated to latest one as some examples may fail in console e.g. [R.adjust](https://ramdajs.com/docs/#adjust) because of changes in argument ordering.

**Comment by CrossEye** [comment]
Wow, I dropped that.  Just getting back into looking at Ramda stuff.  I'll see what I can do tonight.

**Comment by customcommander** [comment]
Seems like issue #2803 is a duplicate of this one?

**Comment by char0n** [comment]
@customcommander yes, #2803 is just another manifestation of the issue. I've just checked and the issue is still present.

**Comment by customcommander** [comment]
@char0n We just published an update to the documentation. This should be fixed now. Could you please verify and close the issue if you're happy with the resolution?

**Comment by char0n** [comment]
I can confirm the latest version `0.28.0` is now served inside documentation: 

`dist/ramda.js`:

```
//  Ramda v0.28.0
//  https://github.com/ramda/ramda
//  (c) 2013-2022 Scott Sauyet, Michael Hurley, and David Chambers
//  Ramda may be freely distributed under the MIT license.
```
