### ISSUE TITLE
v0.26.1 Upgrade Guide

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#2723]
[v0.26.0...v0.26.1](https://github.com/ramda/ramda/compare/v0.26.0..v0.26.1)

:bulb: Changes:

- #2720 removed some `const`s that had snuck in before v1.0

:clipboard: Documentation fixes: #2708, #2709, #2717, #2722

:heavy_check_mark: Testing improvements:  #2703, #2710, #2711

----------

Many thanks to all the contributors supporting this release, especially to those helping with improvements to tests and documentation :tada:

**Comment by Captainlonate** [comment]
@CrossEye 
Would it make sense to add that `move` was added in 26**.1**, to the "Changes" notes? Was actually a little challenging to track down exactly when that was added.

**Comment by CrossEye** [comment]
Yes it would, if that's what happened.  I'll try to research this evening.
