### ISSUE TITLE
Documentation: "merge" shows "Deprecated true"

### ISSUE THREAD

**Issue by andys8** [ramda/ramda#2729]
I found this in the documentation. I'd go with "Deprecated" or better add the version.
![image](https://user-images.githubusercontent.com/13085980/49302277-f3747e00-f4c6-11e8-8f5d-f698611184ff.png)

Others show the version:

![image](https://user-images.githubusercontent.com/13085980/49302299-012a0380-f4c7-11e8-9869-ca6e858d1922.png)

**Comment by CrossEye** [comment]
Yes, that's definitely an error.  I published `v0.26.1` the other day but had trouble republishing the docs.  I'll add this to my list of things to clean up when I make that happen.

Thanks for the report.
