### ISSUE TITLE
Flip should be improved to be functional

### ISSUE THREAD

**Issue by DKurilo** [ramda/ramda#2731]
flip is not working with curried functions and with identity:
https://codesandbox.io/s/q85x7xwq69
```
const f = x => y => x / y;
const cf = curryN(2, uncurryN(2, f));

console.log(flip(f)(2)(3)); // should be 1.5, have NaN
console.log(flip(cf)(2)(3)); // 1.5

const cflip = f => x => y => f(y)(x);
console.log(cflip(f)(2)(3)); // 1.5
console.log(cflip(cf)(2)(3)); // 1.5

console.log(cflip(identity)(2)(f)(3)); // 0.6666666
console.log(cflip(identity)(2)(cf)(3)); // 0.6666666
console.log(flip(identity)(2)(f)(3)); // should be 0.6666666. raise error
console.log(flip(identity)(2)(cf)(3)); // should be 0.6666666. raise error

```
Sorry, I don't know how to fix it yet.

**Comment by CrossEye** [comment]
While we could create a `flip` that works that way, it wouldn't fit so well with the rest of Ramda, I believe.

`flip` works on polyadic functions, as do many Ramda functions.  We could alternatively make it work on manually curried binary functions.  But I don't think we can do it for both.

Meanwhile, I don't quite know what you would expect from `flip(identity)`.  `identity` is nothing more than `(a) => a`.  That can't quite be flipped.

**Comment by DKurilo** [comment]
I found this when I was making some experiments in converting functions from pointwise to pointfree.
And sometimes you need flip(flip)(identity) or flip(identity) to do it. (https://stackoverflow.com/questions/12339822/why-does-haskells-flip-id-has-this-type)  
I'm expecting to have something like:
console.log(flip(identity)(2)(x => x+3)); // error now
5
And it works with const cflip = f => x => y => f(y)(x);
console.log(cflip(identity)(2)(x => x+3));
5

**Comment by CrossEye** [comment]
That behavior depends on Haskell-style code, I think.  Certainly the explanation does.

While I'm thinking that Ramda might want to explore switching to simpler currying and embrace unary functions everywhere in the post-1.0 world, for now `identity` is a unary function, and `flip` works only on functions arity at least 2.

Note that at the moment, `R.flip` works fine on these

```js
const g = (x, y) => x / y;
// or
const quadraticEquation = (a, b, c) => [
  (-b - Math.sqrt(b * b - 4 * a * c)) / (2 * a),
  (-b + Math.sqrt(b * b - 4 * a * c)) / (2 * a),  
] // e.g. quadraticEquation(1, -8, 15) //=> [3, 5]
```

but `cflip` would not.

You could probably use `R.flip(R.call)` to handle that missing case for you.

**Comment by DKurilo** [comment]
I understood you. Thank you.
No, it will not help. If I know arity of my function, I can just use flip(uncurryN(arity, f)), but the problem is I don't always know it.
Yes, it's like question from between Haskell and JavaScript, but I really want to have FP library where I can just use what I can make in Haskell. :)
By the way, if flip will be defined as:
```
const cflips = f => x => y => curry(f)(y)(x);
const cflip = f => uncurryN(f.length, cflips(f));

```
it will work in both cases, as I understand it:
https://codesandbox.io/s/z39wymwnpx
Check lines 25-35 here.

**Comment by CrossEye** [comment]
> I really want to have FP library where I can just use what I can make in Haskell. :)

[Sanctuary][sa] might be a better fit, then.  While it started as a more strict  companion to Ramda, it has become its own complete API.  It is significantly closer to Haskell than is Ramda.


  [sa]: https://sanctuary.js.org/

**Comment by davidchambers** [comment]
Those unhappy with `R.flip` can see whether [`S.flip`][1] is more to their liking, as Scott suggested. :)


[1]: https://sanctuary.js.org/#flip
