### ISSUE TITLE
(pipeWith) transforming function is not applied on the 1st function

### ISSUE THREAD

**Issue by franzwong** [ramda/ramda#2733]
From the source code of `pipeWith`, it said `R.pipeWith(f)([g, h, i])(...args) = f(i, f(h, f(g, ...args)))`. 

I have created a test.

```
const R = require('ramda')

const trace = (f, res) => {
  const newRes = f(res)
  console.log(`old: ${res}, new: ${newRes}`)
  return newRes
}

const incrementThree = R.pipeWith(trace)([R.inc, R.inc, R.inc])

console.log('Try incrementTree')
incrementThree(10)

console.log('Try trace(R.inc, trace(R.inc, trace(R.inc, 10)))')
trace(R.inc, trace(R.inc, trace(R.inc, 10)))

console.log('Try trace(R.inc, trace(R.inc, R.inc(10)))')
trace(R.inc, trace(R.inc, R.inc(10)))
```

Here is the result

```
Try incrementTree
old: 11, new: 12
old: 12, new: 13
Try trace(R.inc, trace(R.inc, trace(R.inc, 10)))
old: 10, new: 11
old: 11, new: 12
old: 12, new: 13
Try trace(R.inc, trace(R.inc, R.inc(10)))
old: 11, new: 12
old: 12, new: 13
```

It looks like `pipeWith` is not working as its comment says. I don't know what the expected behaviour is.

**Comment by CrossEye** [comment]
I think it's working as expected.  If you can think of a way to clean up the comments, please feel free.  (See #2512 for the motivation.)

The idea is that now we can replace these

```js
pipeP(f, g, h)
pipeK(f, g, h)
```
with

```js
pipeWith(then, [f, g, h])
pipeWith(chain, [f, g, h])
```

as well as writing

```js
pipeWith(notNil, [f, g, h])
```

or whatever else we want to do between function invocations.  We could theoretically implement `pipe` and `compose` on top of these, using `identity`, but choose not to as they are some of the most central functions in the library.

**Comment by franzwong** [comment]
Updated with more accurate comment
