### ISSUE TITLE
Proposal: Can we have an operator similar to https://lodash.com/docs/4.17.11#at

### ISSUE THREAD

**Issue by minaseem** [ramda/ramda#2740]

**Comment by char0n** [comment]
You have it in ramda-adjunct : https://char0n.github.io/ramda-adjunct/2.13.0/RA.html#.paths

**Comment by CrossEye** [comment]
While I'd love to hear some more feedback, it seems to me that this would complete this square:

|                   | Single node        | Multiple nodes       |
| ----------------- | ------------------ | -------------------- |
| **Scalar input**  | [`prop`][pr]       | [`path`][pa]         |
| **Array input**   | [`props`][ps]      | `??`                 |

Obviously it's not essential.  It's fairly simple to write as `compose(juxt, map(path))`, or to wrap that in `uncurryN(2)` if that exact API is wanted.  But it does seem sensible to add.

@minaseem: Are you interested in creating a PR for this?

  [pa]: https://ramdajs.com/docs/#path
  [pr]: https://ramdajs.com/docs/#prop
  [ps]: https://ramdajs.com/docs/#props

**Comment by Bradcomp** [comment]
I think the name, per @char0n, should be `paths` rather than `at` to mirror `props`. Other than that this seems like a good idea to me.

**Comment by minaseem** [comment]
@CrossEye Can you please review PR - https://github.com/ramda/ramda/pull/2742
