### ISSUE TITLE
Round a number with Ramda

### ISSUE THREAD

**Issue by mohithg** [ramda/ramda#2743]
Can I round the number eg: 2.333 to 2.3 or 2.33 depending on the precision like lodash's round https://lodash.com/docs/4.17.11#round`

**Comment by CrossEye** [comment]
Ramda does not include such a function.  If you're interested in submitting a pull request, I promise it will get a fair hearing.  There's no guarantees that it would be accepted; I think this is the first request we've seen for it.

**Comment by Bradcomp** [comment]
This seems like a fairly reasonable function to me, at least as reasonable as the other math operations we support.

**Comment by Beraliv** [comment]
It can be reasonable to have both `floor` and `ceil` with a specified precision
So:

```js
R.ceil(6.688689, 2)    // 6.69
R.ceil(6.688689, 1)    // 6.7
R.ceil(6.688689, 0)    // 6.688689
R.ceil(6.688689, -1)   // 10
R.ceil(6.688689, -2)   // 100
```

It can also be applied to e-notation numbers

What do you think? @mohithg @CrossEye @Bradcomp @mattrybin

**Comment by Beraliv** [comment]
@CrossEye 

> I find your examples a bit confusing. Why wouldn't `R.ceil(6.688689, 0)` yield `7`?

Yeah, I agree with you, better to change order of parameters
And for `0` it should return `7` like a result of `Math.ceil`

> none of our math functions seem particularly necessary

You mean maybe in the future they will be deprecated?

**Comment by RetekBacsi** [comment]
I'd say if it ever gets introduced the parameters should be flipped to make function composing easier. 
e.g. roundTo2 = R.ceil(2)

**Comment by Beraliv** [comment]
@RetekBacsi all names of functions should be consistent
That's why `ceilTo` is more correct for reversed order of parameters
However `ceil` can be used as is
What do you think @CrossEye @ramda/core ?

**Comment by CrossEye** [comment]
@Beraliv:

First, my apologies.  I saw your previous question, didn't manage to answer immediately, and promptly forgot it.  So,

>> none of our math functions seem particularly necessary

> You mean maybe in the future they will be deprecated?

I think it's possible.  I'm working on a strawman roadmap document, looking at what we want to do (soon, I hope!) for v1.0, and what sorts of changes we might want for 2.x and/or 3.x.  One option we might consider along that path is to stop including anything not essential that can be trivially implemented by users.  `add` is only slightly clearer than `(a, b) => a + b`, and `divide` is confusing.  My current preference would be to keep them, but it's not a strong preference.
```js


> All function names should be consistent.  That's why `ceilTo` is more correct for reversed order of parameters.  However `ceil` can be used as is

I'm not following what you mean here.  Ramda is quite consistent about parameter order: we order them from least likely to change to most likely to change.  This allows the partial application that is fundamental to the main use-case for Ramda: building functions by composing smaller ones.

So Ramda would certainly prefer `round(2, 1.65076373)` to `round(1.65076373, 2)`.  I'm not sure what you meant by the "reversed order of parameters."  Reversed from what?

And I can't imagine why we would need `ceilTo` as well as or instead of `ceil`.

**Comment by Beraliv** [comment]
@CrossEye 

> I'm not sure what you meant by the "reversed order of parameters." Reversed from what?

I meant reversed to the example I mentioned above

> I'm not following what you mean here. Ramda is quite consistent about parameter order

It's a reference to the issue https://github.com/ramda/ramda/issues/1497 as `round` and `ceil` can be considered both left and right associative with different names

> And I can't imagine why we would need `ceilTo` as well as or instead of `ceil`.

Yeah, totally agree
