### ISSUE TITLE
Behaviour of _curryX functions is inconsistent

### ISSUE THREAD

**Issue by spukst3r** [ramda/ramda#2747]
I've noticed that due to the implementation of these functions, some ramda functions respect passed `this` and some don't.

For example, `when` ignores the context:

```javascript
function usesContext(a) { return this.a + a }

R.when(R.equals(1), usesContext).call({a: 42}, 1) // NaN, because `this.a` is `undefined`
```

While `ifElse` which is different arity does respect `this`:

```javascript
R.ifElse(R.equals(1), usesContext, R.identity).call({a: 42}, 1) // 43
```

I understand that using `this` is not quite encouraged in FP, but I think it's a good idea to respect the context like `_curry1` and `_curryN` do, and be consistent about it.

Edit: It seems like `ifElse` handles `this` on its own, so the issue may not be strictly about `_curryX` functions.

**Comment by CrossEye** [comment]
Ramda started by trying to respect the `this` context, as it made it easier to use Ramda-generated functions as object methods.  We found that was little-used when a bug for it in a common function was not discovered for a long period.  We've mostly abandoned the idea, as it adds complexity to the implementation of various functions, but we have not made a dedicated effort to go back and remove it.

But don't expect it to be there for long.

**Comment by CrossEye** [comment]
> That's sad.. Is it really a big hassle to pass the context around?

It can be.  It can really complicate code.  Often enough it isn't.  But Ramda and OOP is an odd mix. Allowing attempts to cater to OOP to complicate our code seems counter-productive.
