### ISSUE TITLE
`reduceBy`'s initial value should be shallowly copied to prevent mutations

### ISSUE THREAD

**Issue by Beraliv** [ramda/ramda#2754]
Written code

```js
const reduceToNamesBy = reduceBy((names, { name }) => {
  names.push(name)
  return names
}, [])
const namesByGrade = reduceToNamesBy(({ score }) => cond([
  [lt_(65), always('E')],
  [lt_(70), always('D')],
  [lt_(80), always('C')],
  [lt_(90), always('B')],
  [T, always('A')]
])(score))
const students = [
  { name: 'Lucy', score: 92 },
  { name: 'Drew', score: 85 },
  { name: 'Bart', score: 62 }
]

namesByGrade(students)
```

Expectations

```js
Expected value to equal:
      {"A": ["Lucy"], "B": ["Drew"], "E": ["Bart"]}
    Received:
      {"A": ["Lucy", "Drew", "Bart"], "B": ["Lucy", "Drew", "Bart"], "E": ["Lucy", "Drew", "Bart"]}
```

It happens because initial value `[]` is shared with every group which makes it mutable for all of them

I can provide fix if immutability here is an issue for `Ramda`

[Example with `concat`](https://ramdajs.com/repl/?v=0.26.1#?const%20reduceToNamesBy%20%3D%20reduceBy%28%28names%2C%20%7B%20name%20%7D%29%20%3D%3E%20names.concat%28name%29%2C%20%5B%5D%29%0A%20%20const%20namesByGrade%20%3D%20reduceToNamesBy%28%28%7B%20score%20%7D%29%20%3D%3E%20%7B%0A%20%20%20%20return%20score%20%3C%2065%0A%20%20%20%20%20%20%3F%20%27F%27%0A%20%20%20%20%20%20%3A%20score%20%3C%2070%0A%20%20%20%20%20%20%20%20%3F%20%27D%27%0A%20%20%20%20%20%20%20%20%3A%20score%20%3C%2080%0A%20%20%20%20%20%20%20%20%20%20%3F%20%27C%27%0A%20%20%20%20%20%20%20%20%20%20%3A%20score%20%3C%2090%0A%20%20%20%20%20%20%20%20%20%20%20%20%3F%20%27B%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%3A%20%27A%27%0A%20%20%7D%29%0A%20%20const%20students%20%3D%20%5B%0A%20%20%20%20%7B%20name%3A%20%27Lucy%27%2C%20score%3A%2092%20%7D%2C%0A%20%20%20%20%7B%20name%3A%20%27Drew%27%2C%20score%3A%2085%20%7D%2C%0A%20%20%20%20%7B%20name%3A%20%27Bart%27%2C%20score%3A%2062%20%7D%0A%20%20%5D%0A%0AnamesByGrade%28students%29)

[Example with `push`](https://ramdajs.com/repl/?v=0.26.1#?const%20reduceToNamesBy%20%3D%20reduceBy%28%28names%2C%20%7B%20name%20%7D%29%20%3D%3E%20%7B%0A%20%20names.push%28name%29%0A%20%20return%20names%0A%7D%2C%20%5B%5D%29%0A%20%20const%20namesByGrade%20%3D%20reduceToNamesBy%28%28%7B%20score%20%7D%29%20%3D%3E%20%7B%0A%20%20%20%20return%20score%20%3C%2065%0A%20%20%20%20%20%20%3F%20%27F%27%0A%20%20%20%20%20%20%3A%20score%20%3C%2070%0A%20%20%20%20%20%20%20%20%3F%20%27D%27%0A%20%20%20%20%20%20%20%20%3A%20score%20%3C%2080%0A%20%20%20%20%20%20%20%20%20%20%3F%20%27C%27%0A%20%20%20%20%20%20%20%20%20%20%3A%20score%20%3C%2090%0A%20%20%20%20%20%20%20%20%20%20%20%20%3F%20%27B%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%3A%20%27A%27%0A%20%20%7D%29%0A%20%20const%20students%20%3D%20%5B%0A%20%20%20%20%7B%20name%3A%20%27Lucy%27%2C%20score%3A%2092%20%7D%2C%0A%20%20%20%20%7B%20name%3A%20%27Drew%27%2C%20score%3A%2085%20%7D%2C%0A%20%20%20%20%7B%20name%3A%20%27Bart%27%2C%20score%3A%2062%20%7D%0A%20%20%5D%0A%0AnamesByGrade%28students%29)

**Comment by CrossEye** [comment]
Please see https://github.com/ramda/ramda/pull/2039#issuecomment-270146445.

Ramda intentionally remains a fairly low-level library.  While Ramda does not mutate your data, it makes no attempt to prevent you from doing so.  While it's been extremely infrequent, I *have* seen cases where this is used to good effect.  (Pun most definitely intended!)

**Comment by Beraliv** [comment]
@CrossEye I don't agree with you here
I don't want to mutate all the time
I just don't want to create extra arrays all the time, it's about the performance, isn't it?
Method itself creates potential place to mutate data

**Comment by foxbunny** [comment]
> should be shallowly copied

> I just don't want to create extra arrays

Not trying to be mean, but you are contradicting yourself.

**Comment by Beraliv** [comment]
@foxbunny I mean a shallow copy of initial value, not the result of reducer

**Comment by Beraliv** [comment]
@CrossEye yeah, I will create PR
I will link it to the issue and will mention team and you
Thank you for understanding
The solution is similar to what I've done in [PR#177 for nanoutils](https://github.com/nanoutils/nanoutils/pull/177)

**Comment by CrossEye** [comment]
I merged #2757.

Thank you for persisting through my initial dismissal.  This is a real improvement.

**Comment by Beraliv** [comment]
@CrossEye great, thanks!
