### ISSUE TITLE
What is the best way to sort this object?

### ISSUE THREAD

**Issue by smitach** [ramda/ramda#2761]

**Comment by smitach** [comment]
I am new to ramda. I want to get all the keys with 'Y' value. Below is the object.
form = {
      A_ALL: {A1_ALL: { A1_ONE: 'Y', A2_TWO: 'Y', A3_THREE: 'Y'}, A2: {A2_FOUR: 'Y', A2_FIVE: 'N', A2_SIX: 'Y'}, A3: 'Y', A4: 'N'},
      B_ALL: {B1_ALL: { B1_ONE: 'Y', B1_TWO: 'Y', B1_THREE: 'Y'}, B2: {B2_FOUR: 'Y', B2_FIVE: 'Y', B2_SIX: 'Y'}, B3: 'Y', B4: 'Y'},
      C_ALL: {XX: 'Y', YY:'Y'},
      D: 'Y',
      E: 'N'
}

I want the sorted object to look like below,
 {
  A_ALL: {A1_ALL: 'Y', A2: {A2_FOUR: 'Y', A2_SIX: 'Y'}, A3: 'Y'},
  B_ALL : 'Y',
  C: 'Y',
  D: 'Y'
}

**Comment by CrossEye** [comment]
I don't have real time to spend thinking about this now (bedtime), but I'd suggest that a better place for questions like this is on the [Gitter channel][gc] or [StackOverflow][so].  You can generally find smart people willing to help in both places.  While people are willing to help here, this is mostly reserved for discussions about problems with the library or potential enhancements to it.

  [gc]: https://gitter.im/ramda/ramda
  [so]: https://stackoverflow.com/questions/tagged/ramda.js

**Comment by CrossEye** [comment]
Never mind, I see that you asked on [StackOverflow][so].  And I had a quick thought, so I answered there, but it's not complete.  A better solution probably works recursively from the inside out.


  [so]: https://stackoverflow.com/q/54138854/1243641

**Comment by CrossEye** [comment]
@ArturAralin: See the [fairly simple solution][ss] from @scott-christopher on StackOverflow.


  [ss]: https://stackoverflow.com/q/54138854/1243641
