### ISSUE TITLE
R.toCamel [Feature]

### ISSUE THREAD

**Issue by yashikagarg13** [ramda/ramda#2769]
### Idea
To convert any given sting to camel case

### Examples
```
R.toCamel('yashikagarg') => YashikaGarg     // It can take array of indexes of string to bump
R.toCamel('yashika-garg') => YashikaGarg    // It can take joing character '-' to identify where to bump
R.toCamel('yashika_garg') => YashikaGarg    // It can take joing character '_' to identify where to bump
```

**Comment by ArturAralin** [comment]
I thing this is not good idea for ramda api. In addition this is trivial to implement https://goo.gl/UtAV7c

**Comment by CrossEye** [comment]
First, thank you for your suggestion.  I'm afraid I'm not inclined to include such a function.


1. I don't think it's common enough.  Ramda only has a few string utilities, and those I think are far more common than `toCamel` (or `toKebab` or `toSnake`, etc.) would be.

2. I'd like to see a solution that could convert `'helloworld'` to `'HelloWorld'` without a dictionary, and even with one, what might it do with `'towardofflake'`?

3. We prefer not to introduce function that can be made quite simply out of other functions, but we are willing to make exceptions for ones that seem common enough.  (`pluck` ~= `map(prop)`, for instance.)  This doesn't seem close to common enough for that.

Does anyone from @ramda/core disagree?

**Comment by davidchambers** [comment]
Such functions could live in a separate package focused on string manipulation. There may already be a well-maintained package in the npm registry which provides this function. :)
