### ISSUE TITLE
hasPath does not work if one attribute in the path is undefined 

### ISSUE THREAD

**Issue by sespinoza-dev** [ramda/ramda#2771]
## hasPath does not work if one attribute in the path is undefined 

If one of the object attributes in the path is undefined, hasPath throws an error. it should return false.

```console
R.hasPath(['a', 'b'], { a: undefined });
=> TypeError: Cannot convert undefined or null to object
// expected false
```

**Comment by CrossEye** [comment]
This is definitely a bug.  Are you interested in creating a PR?

**Comment by sespinozj** [comment]
I'll give it a try.

Greettings!

**Comment by machad0** [comment]
Hi @sespinozj, are you still into this issue? If you don't, I'd like to try

cheers

**Comment by sespinozj** [comment]
@machad0 do please go ahead. :)

**Comment by machad0** [comment]
Hi again,

Well, actually this bug was fixed at  #2738, it's just an outdated bundle.

```javascript
var hasPath = _curry2(function hasPath(_path, obj) {
...
  while (idx < _path.length) {
    if (_has(_path[idx], val)) {
      val = val[_path[idx]];
      idx += 1;
    } else {
      return false;
    }
 
```
the method doesn't contains the updated `hasPath` version, should we bump it?

**Comment by sespinozj** [comment]
yes, thanks for checking that out @machad0 

We use `pathOr` as a workaround in some cases thou.

Greetings!

**Comment by CrossEye** [comment]
Damn, I'm so caught up in what I want to do soon that I've forgotten what we've done recently!

**Comment by gouegd** [comment]
Just got bit by this bug, I don't think the fix is in the latest version (or it has not worked):
`R.hasPath(['a', 'b'], { a: undefined })`
and
`R.hasPath(['a', 'b'], { a: { b: undefined } })`
both crash

**Comment by gouegd** [comment]
@mattgrande That means the fix for #1 is on master but not published, doesn't it ?

**Comment by mattgrande** [comment]
That's what it seems like, yes.

**Comment by CrossEye** [comment]
I've been away from Ramda for a few weeks, and am trying to get back.  I will try to publish again soon, and this change should then be included.

**Comment by gahabeen** [comment]
Seems like there is still an issue. If the sub value isn't an Object (Object or Array), it fails.

I ended up with this exact error message:
```
C:\[PATH]\ramda\src\internal\_has.js:2
  return Object.prototype.hasOwnProperty.call(obj, prop);
                                         ^
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at _has (C:\[PATH]\ramda\src\internal\_has.js:2:42)
```

Fixed it by simply checking if the value is indeed an object and can be checked against a sub property.

```
// hasPath function
...
while (idx < keyPath.length) {
    if (!isNil(val) && is(Object, val) && _has(keyPath[idx], val)) {
      val = val[keyPath[idx]];
      idx += 1;
    } else {
      return false;
    }
  }
...
```

:)

**Comment by LorneCurrie** [comment]
Created a pull request #2825 for this issue

**Comment by PaulGrimshaw** [comment]
Is this going to be fixed?  We are still getting this issue...

**Comment by gulsicka** [comment]
Still getting the issue

**Comment by CrossEye** [comment]
@gulsicka:  Can you demonstrate?  It seems to be working correctly [in my test][ts].


  [ts]: https://tinyurl.com/yywdknje
