### ISSUE TITLE
Wrong Release packages

### ISSUE THREAD

**Issue by area73** [ramda/ramda#2774]
Hi,
I just notice that if we download  the zipped V 0.26.0 or V 0.26.1 from the releases, we are getting the V 0.25.0 version.

If we look at the package.json it is tag to V 0.26.x but if we look inside dist/ramda.js file it says V 0.25.0. I also check a commit to see if source was correct but it looks that you are including V 0.25.0 source code instead of 0.26.x. 

Take a look for example at internal/_isFunction.js, you will see that the code that you are delivering on V 0.26.0 & V 0.26.1 is the old code from V 0.25.0

Thanks

**Comment by CrossEye** [comment]
I think that when I published the release, I forgot to do the GitHub version.  I was thinking only in terms of NPM.  I just did a release on GitHub.  Can you tell me if that fixed your problem?

**Comment by area73** [comment]
Well... yes and no :smiley: 

Now I see that on source the code looks ok (latest version), but on dist folder the ramda.js file (and I guess also the min version) is the old version (V 0.25.0)

Thanks for taking your time on this issue

**Comment by char0n** [comment]
@CrossEye also not sure if [release notes](https://github.com/ramda/ramda/releases/tag/0.26.1) are OK. 0.26.1 doesn't contain `R.andThen` but still contain `R.then`. This can be verified here: https://npm.runkit.com/ramda

**Comment by CrossEye** [comment]
Oh, boy.  It shouldn't include `andThen`, which should not have been released.  I will have to take a deeper look at this, and won't have time until tomorrow evening.  Sorry folks.

**Comment by char0n** [comment]
There seem to be a discrepancy between how you tag versions. `0.26.1` v `v0.26.1`

**Comment by davidchambers** [comment]
@CrossEye, the [automated release process][1] should take care of publishing to GitHub and to the public npm registry.


[1]: https://github.com/ramda/ramda/blob/v0.26.1/Makefile#L20-L22

**Comment by customcommander** [comment]
Assuming this has been fixed by now. Closing.
