### ISSUE TITLE
ramda where function not working

### ISSUE THREAD

**Issue by JeffreyChan** [ramda/ramda#2777]
here is error message:

> node_modules\ramda\src\where.js:44
    if (_has(prop, spec) && !spec[prop](testObj[prop]))

but strange thing is i use Try Ramda is ok.
my workstation is TS, is there a problem in TS?

here is version info

>   "dependencies": {
    "@types/node": "^10.12.19",
    "ramda": "^0.26.1"
  },
  "devDependencies": {
    "ts-node": "^8.0.2",
    "typescript": "^3.2.4"
  }

here is my code 

> var incomplete = R.filter(R.whereEq({ complete: false }));
var sortByDate = R.sortBy(R.prop('dueDate'));
var sortByDateDescend = R.compose(R.reverse, sortByDate);
var importantFields = R.project(['title', 'dueDate']);
var groupByUser = R.partition(R.prop('username'));
var activeByUser = R.compose(groupByUser, incomplete);
var gloss = R.compose(importantFields, R.take(5), sortByDateDescend);
var topData = R.compose(gloss, incomplete);
var topDataAllUsers = R.compose(R.map(gloss), activeByUser);
var byUser = R.useWith(R.ap, [R.filter, R.propEq("username")]);
console.log("Gloss for Scott:");
console.log(topData(byUser("Scott", tasks)));
console.log("====================");
console.log("Gloss for everyone:");
console.log(topDataAllUsers(tasks));

**Comment by JeffreyChan** [comment]
> The version of Ramda that code was written for is nearly five years old. I should update the article with a warning that it might not still work
> 
> As to this code, there are two functions which use older version of their Ramda functions. First, `partition` was renamed to `groupBy`, and then `partition` was reused for another concept. So you would need to replace
> 
> ```js
> var groupByUser = R.partition(R.prop('username'));
> ```
> 
> with
> 
> ```js
> var groupByUser = R.groupBy(R.prop('username'));
> ```
> 
> Second, the final function, `byUser` seems incorrectly converted from it's older style API. The article uses
> 
> ```js
> var byUser = R.use(R.filter).over(R.propEq("username"));
> ```
> 
> which we don't use anymore. The replacement is
> 
> ```js
> var byUser = useWith(R.filter, [R.propEq('username')])
> ```
> 
> Best practices might dictate that you add an `identity` to that as well:
> 
> ```js
> var byUser = useWith(R.filter, [R.propEq('username'), identity])
> ```
> 
> to show that the resulting function is binary, and passes its second argument directly through to `filter`. But since in the meantime ES6 has become ubiquitous, I might not recommend this at all. I would probably prefer something like
> 
> ```js
> var byUser = (user, tasks) => R.filter(R.propEq('username', user), tasks)
> ```
> 
> (possibly wrapped in `curry`, possibly not.)
> 
> This explicit version, is clearer to me than the version with `useWith`. I rarely reach for that any more, as arrow functions are usually more readable. I still sometimes use `converge`, or even better `lift` to perform a slightly different, but related task. Those make more sense than `useWith` to me.

Hi master, thanks for your reply.

  I love ramda so much. 
  About filter function, right now, I like this way:

> R.filter(R.propEq('username', memberName))

But I try to use function to combine filter and any others.

Anyway please close the issue.

**Comment by CrossEye** [comment]
I'm afraid I know almost nothing about these typings.
