### ISSUE TITLE
Is add returning a Number or a Function?

### ISSUE THREAD

**Issue by ericmorand** [ramda/ramda#2778]
I'm currently reading Ramda documentation and I'm very confused with it, from the very beginning: the `add` function.

https://ramdajs.com/docs/#add

Here what it says: 

> Returns Number

And then the given examples contradict that statement:

```
R.add(2, 3);       //=>  5
R.add(7)(10);      //=> 17
```

It is impossible for the second example to work if `add` returns a Number. It has to return a Function for the second example to work. But it is not clear when `add` returns a Function and when it returns a Number. I assume it returns a Function when it receives a single parameter and a number when it receives two parameters.

Is it a documentation issue or am I missing something?

**Comment by CrossEye** [comment]
I would love to find a way to upgrade the documentation so that things like this are easier to find for new users.  It's hard to attach such notes to the affected functions, as it's almost every one of them.

Any suggestions would be welcome.

**Comment by nfantone** [comment]
@ericmorand I understand the pain. One thing that _might_ help is to take a look at the function's **type signature**. In the case of `add`, it reads: `Number → Number → Number`.

![image](https://user-images.githubusercontent.com/476069/52213674-ab3b5880-2887-11e9-92de-02210bab181d.png)

Translated, this effectively means:

> `add` is a `function` that takes a `Number` and returns a `function` that takes a `Number` and returns a `Number`.

This is a very common case with curried functions. If you are not familiar with this type of notation (most people aren't!), it's called [_Hindley–Milner type system_](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system) and common in FP languages, such as Haskell. [Here](https://stackoverflow.com/questions/22337214/understanding-haskell-type-signatures) is a good SO question that may help dive into the system.

Hope that helps!

**Comment by CrossEye** [comment]
And there's always this document: https://github.com/ramda/ramda/wiki/Type-Signatures

**Comment by nfantone** [comment]
@CrossEye Is there a link to _that_ wiki in the main docs? That would probably help.

**Comment by ericmorand** [comment]
@nfantone, @CrossEye, I stumbled upon the Type signatures document a few days ago and it made things much clearer. I agree that it should be linked from the main docs and that it's enough to understand the main docs without any further clarifications.

@nfantone, shouldn't `Number-> Number-> Number` mean:

> `add` is a `function` that takes a `Number` and returns a `function` that takes a `Number` and returns a `Number`; or takes two `Number` and returns a `Number`.

Thanks to both of you. I'll read the Hindley–Milner type system article, looks quite interesting.

**Comment by CrossEye** [comment]
> Shouldn't `Number-> Number-> Number` mean:

>> `add` is a `function` that takes a `Number` and returns a `function` that takes a `Number` and returns a `Number`; or takes two `Number` and returns a `Number`.

That's a matter of debate, I think.  The signature means what nfantone suggested.  That's how it's used in the languages where this style originated.  Ramda offers a gloss on its curried functions that allow you to supply multiple parameters at a time to a curried function.  Again, I would love for the documentation to make this clear.  But I wouldn't try to capture that fact in these signatures.  Think of the signatures as describing a fairly standard way of describing this function.  Ramda then layers an optional secondary API on top of them.  That's all.

**Comment by ericmorand** [comment]
Thanks a lot to both of you. It makes a lot of sense now.
