### ISSUE TITLE
R.intersection(", '').length should return 1 (empty strings)

### ISSUE THREAD

**Issue by MozilaIP** [ramda/ramda#2785]
Maybe I am breaking the rules because docs says that `intersection` method accepts lists, but anyway...

I can provide String arguments and they will be processed as lists and intersections will be found. Moreover ``` includes('', '') ``` also returns **true**. So behavior of ```intersection('','')``` is a little bit controversial IMHO.

Do you have any plans to make ```intersection``` friendly to such edge case?

**Comment by Bradcomp** [comment]
I think the fact that intersection works on strings is purely coincidental. It is an operation that is meant to work on sets, where lists are just the closest ES5 native structure to a set. 

I don't think we would want to explicitly support strings.
