### ISSUE TITLE
How `pathSatisfies` handles empty paths `[]`

### ISSUE THREAD

**Issue by rjhilgefort** [ramda/ramda#2788]
`pathSatisfies` currently handles empty `path` arguments by just returning `false` instead of trying to compare anything.

```javascript
pathSatisfies(is(Object), ['foo'], { foo: { bar: 'bar' } }) // true
pathSatisfies(is(Object), [], { bar: 'bar' }) // false
```

I believe the argument for why this is the case goes something like: "Because a path is not specified, we should assume that the value at nothing will always be false". However, I think the behavior should be that when a path is not specified, `pathSatisfies` will compare the given `data` against the `pred` passed.

I've overridden `pathSatisfies` in my own project like this which might demonstrate what I mean better:

```javascript
import * as R from 'ramda'
const { curry, cond, isEmpty, T }

const pathSatisfies = curry((pred, path, data) => cond([
  [isEmpty, () => pred(data)],
  [T, R.pathSatisfies(pred, __, data)]
])(path))

pathSatisfies(is(Object), ['foo'], { foo: { bar: 'bar' } }) // true
pathSatisfies(is(Object), [], { bar: 'bar' }) // true
```

**Comment by CrossEye** [comment]
I agree.  This is clumsy as is.  Would you be willing to create a PR for this?

**Comment by rjhilgefort** [comment]
Sure, I’ll take a stab at it! Thanks for the reply!

**Comment by rjhilgefort** [comment]
I threw out a PR- see ☝️

**Comment by rjhilgefort** [comment]
This change has been implemented in https://github.com/ramda/ramda/pull/2791 and is merged
