### ISSUE TITLE
weird behaviour of 'both' with lenses

### ISSUE THREAD

**Issue by Powerplex** [ramda/ramda#2794]
I found a case where 'both' returns null, instead of a boolean. 

```

const dataLens = lensProp('data')

// authenticated
const authenticatedLens = lensProp('isAuthenticated') // true, false or null because of API design... :(
const isLoggedIn = pipe(view(authenticatedLens), status => status === true)

// account type
const isProLens = lensProp('isPro')

// BUG
const isPro = both(
  view(authenticatedLens),
  view(isProLens)
)

// NO BUG
const isPro = both(
  isLoggedIn,
  view(isProLens)
)

isPro({
  isPro: false,
  isImport: false,
  isFetching: false,
  isAuthenticated: null,
  data: {
    accountType: 1,
    personalData: { firstName: 'firstName', pseudo: 'pseudo' } 
  } 
})


```

I think that 'both' should always return a boolean ?

**Comment by Bradcomp** [comment]
Hi @Powerplex, thanks for bringing this up!

If you take a look at the [docs](https://github.com/ramda/ramda/blob/master/source/both.js#L8) for `both`, you can see that the function doesn't coerce the results to a boolean, but instead just uses truthy and falsy.

This behavior is expected, and can actually be useful sometimes.

**Comment by Powerplex** [comment]
Oh okay sorry. I was confused when I read (*… → Boolean) → (*… → Boolean) → (*… → Boolean)

As both methods are supposed to return a boolean, I expected a boolean to be enforced. Do you have an example of when this behaviour can be useful :) ?

**Comment by CrossEye** [comment]
If you want very long discussions about this, see #1218 and #1335.
