### ISSUE TITLE
Whether zipwith can be rewritten

### ISSUE THREAD

**Issue by jiameng123** [ramda/ramda#2796]
Whether zipwith can be rewritten ? 

var zipWith =  curry(function(f, list1, list2, init) {
    if(!list1.length || !list2.length ) return init;
    init[init.length] = f(list1[0], list2[0]);

   return zipWith(f, tail(list1), tail(list2), init)
    
});

export default zipWith(R_, R_, R_, []);

**Comment by CrossEye** [comment]
The very early history of Ramda involved @buzzdecafe and me writing nice elegant recursive code for everything, in a library called [Eweda][ew].  It failed miserably at being practical; even when our code was eligible for tail-call optimization, the engines wouldn't provide it.  Ramda was a rewrite with an emphasis on the practical.

So, while that looks elegant to me, I'd be extremely wary of including it in Ramda.

  [ew]: https://github.com/CrossEye/eweda
