### ISSUE TITLE
R.isEmpty(Buffer.from("")) returns false

### ISSUE THREAD

**Issue by abeMedia** [ramda/ramda#2799]
It appears `isEmpty` does not work for Buffers. Since Buffers have the `length` property, my suggestion would be to first check for the length property and return true if this exists and is `0`. This would already cover almost everything but objects and would probably also be more efficient than creating an empty var to compare against.

**Comment by CrossEye** [comment]
Are you interested in creating a PR for this?  I think there might be some significant discussion, and I can't guarantee that it would be accepted, but it's easier to talk about a concrete proposal.

**Comment by DanielRX** [comment]
@abeMedia Looking at the test cases for `isEmpty` I see `isEmpty({length: 0}) -> false` so I don't think you could check it that way (unless you first rule out that case)
Also just to note, `Array(1)` produces an empty array with length 1, so this also would not catch that case

**Comment by canytra** [comment]
I took a stab at this...

Instead of just Buffer, implemented it for all TypedArrays.

**Comment by CrossEye** [comment]
@cantyra: Thank you!  The PR looks great to me!

**Comment by canytra** [comment]
No problem! And thanks! Happy to contribute

**Comment by canytra** [comment]
@CrossEye I think this can safely be closed now. Thank you!
