### ISSUE TITLE
Cannot call `R.allPass` with array literal bounds to `fns`

### ISSUE THREAD

**Issue by genesst** [ramda/ramda#2800]
Using `ramda` in React project with Flow enabled. Have a validator method like this:
```js
export const isLayoutValid: ((GridItem[]) => boolean) = R.allPass([
  R.is(Array),
  R.complement(R.isEmpty),
  R.all(
    R.allPass([
      R.is(Object),
      R.propIs(String, 'i'),
      R.propIs(Number, 'x'),
      R.propIs(Number, 'y'),
      R.propIs(Number, 'w'),
      R.propIs(Number, 'h')
    ])
  )
]);
```

Line with ` R.propIs(String, 'i')` is highlighted with following error:
```
Cannot call `R.allPass` with array literal bounds to `fns` because rest array [1] 
has an unknown number of elements, so is incompatible with tuple type [2] 
in array element
```

[1] is referred to:
```javascript
declare function allPass<T>(
  fns: Array<(...args: Array<T>) => boolean>
): (...args: Array<T>) => boolean;
```

[2] is referred to:
```javascript
declare type __CurriedFunction1<A, R, AA: A> = (...r: [AA]) => R;
```

`GridItem` type definition:
```javascript
export type GridItem = {
  i: string,
  x: number,
  y: number,
  w: number,
  h: number
};
```

I know this is not Flow issue tracker, but maybe someone had this already.

**Comment by CrossEye** [comment]
I'm afraid I personally know nothing about using Flow (and as little about Typescript as I can get away with!)

There may be Ramda folks who know, but usually such issues need to be resolved by the Flow(/Typescript) teams.

**Comment by eugestarr** [comment]
> I'm afraid I personally know nothing about using Flow (and as little about Typescript as I can get away with!)
> 
> There may be Ramda folks who know, but usually such issues need to be resolved by the Flow(/Typescript) teams.

Hi Scott, thanks for taking time to answering this, just for cross reference added this to flow-typed issue tracker - https://github.com/flow-typed/flow-typed/issues/3217
