### ISSUE TITLE
R.then documented but not available

### ISSUE THREAD

**Issue by villesau** [ramda/ramda#2803]
In 0.26.1, [R.then](https://ramdajs.com/docs/#then) is documented, but when pulling the library from NPM, it's undefined.

**Comment by CrossEye** [comment]
There's some real confusion about the what's been published.  It was replaced by `andThen`, but wasn't supposed to have been published like that yet.  I will try to rectify it this weekend.

**Comment by villesau** [comment]
Nice! :)

BTW. The Ramda version available in console on website is outdated as well. `R.then` or `R.andThen` and `R.composeWith` can't be found.

**Comment by CrossEye** [comment]
Hmm, I don't get `andThen`, but I do get the others.

**Comment by villesau** [comment]
<img width="321" alt="Screenshot 2019-03-21 at 21 11 38" src="https://user-images.githubusercontent.com/2647016/54778662-fafa9700-4c1d-11e9-92cd-dfe5272ab30e.png">

e.g composeP is found. Maybe there is a CDN or other caching issue then?

**Comment by CrossEye** [comment]
I almost forgot we even had that there.  I usually use the REPL.

I will try to find time this weekend to publish another version with all this worked out.

**Comment by customcommander** [comment]
AFAICT this is still an issue:

<img width="1507" alt="Screenshot 2021-12-24 at 15 18 43" src="https://user-images.githubusercontent.com/681975/147361885-7a86d5c5-e70f-428b-9c77-34888a18f84f.png">

@CrossEye Shall I transfer this issue to the website repo?

**Comment by CrossEye** [comment]
@customcommander: that makes sense

**Comment by customcommander** [comment]
@CrossEye @villesau The documentation site has been updated. Happy to close?

**Comment by villesau** [comment]
Nice! :)
