### ISSUE TITLE
R.takeAnyOne

### ISSUE THREAD

**Issue by PaulGrimshaw** [ramda/ramda#2812]
I sometimes want to take the first element of an array (e.g. `head`).  However, I take this first element as I actually don't care what element I get, which differs in meaning from when I might take the first element of a sorted array.

I would like a `takeAnyOne` which simply maps directly to `head` but descriptively puts the different meaning in.  (e.g. implementation = `const takeAnyOne = head`)

Example usage: `const moduleName = takeAnyOne(serviceDefinitions).module`

To me this reads much better than `const moduleName = head(serviceDefinitions).module`, as this latter one insinuates that the order may be important (obviously useful in some other cases)

Other name could be `takeOne`

Thoughts?

**Comment by Bradcomp** [comment]
As a general rule, Ramda is [against aliases](https://github.com/ramda/ramda/pull/574#issuecomment-64124850).

**Comment by PaulGrimshaw** [comment]
Ok, i guess that's fair enough.  I would almost argue this is not an alias however, and alias to me is just an alternative.  The `takeAnyOne` suggestion has a different meaning, and the implementation (`head`) would be a hidden and changeable.  But appreciate if this was done everywhere in ramda it may get a bit cluttered

**Comment by CrossEye** [comment]
We have once or twice had aliases for exactly this reason, that semantically different functions had the same implementations.  It's been rare, and I think those have mostly lasted only through a deprecation cycle.  I would be quite wary of introducing another one without strong reason.

But I have a more fundamental objection to including this function.  Ramda is very interested in working only with pure functions.  That means that every time a particular Ramda function is called with the same input, it yields the same output and has no side-effects.

Obviously if the proposed `takeAnyOne` simply delegated to `head`, it would have the same behavior.  But the only reason to consider this alias would be that the semantics of `takeAnyOne` are different.  There is the expectation that `takeAnyOne(['larry', 'moe', 'curly'])` would return `'larry'` one time and `'curly'` a different time.  Even if our function is technically pure, I don't want to even *give the impression* that we supply an impure function.

**Comment by PaulGrimshaw** [comment]
Yes I have been thinking a bit too, and actually came to a similar conclusion.  It does give a sense of uncertainty that it would actually be pure.  Should rather be named something like `takeHeadToRepresentAny` .  Anyhow, will close for now :-)
