### ISSUE TITLE
Any reason mergeDeepWithKey does not compare reference equality

### ISSUE THREAD

**Issue by jmdsg** [ramda/ramda#2814]
I currently have two issues, the first one (1) is that i'm merging some large objects and checking ramda's code i note that the objects are merged no matter if they are the exact same object.

Is there any reason for not having something like this in `R.mergeDeepWithKey`?

```javascript
var mergeDeepWithKey = _curry3(function mergeDeepWithKey(fn, lObj, rObj) {
  if (lObj === rObj) return lObj; // <- compare here
  return mergeWithKey(function(k, lVal, rVal) {
    if (_isObject(lVal) && _isObject(rVal)) {
      return mergeDeepWithKey(fn, lVal, rVal);
    } else {
      return fn(k, lVal, rVal);
    }
  }, lObj, rObj);
});
```

I been using ramda for a while now, but don't much about the internal implementation, so no idea if something like this is against the general guideline of the library.

The second issue (2) is when i deep merge objects that contain as value [moment](https://github.com/moment/moment) instances (which are objects) then some of the moment functionalities gets broken.

If i have the same moment instance i keep the left [or right] which is similar to issue (1).
And when they are not the same instance, but at least one of them is a moment instance then i keep left [or right].

Currently have this utils:

```javascript
export const mergeDeepUnless = R.curry((fnUnless, fnObj, fnVal, lObj, rObj) => {
  const recursiveMergeDeepUnless = (lObj0, rObj0, k0) => {
    if (fnUnless(k0, lObj0, rObj0)) {
      return fnObj(k0, lObj0, rObj0);
    }
    return R.mergeWithKey((k, lVal, rVal) => {
      if (R.is(Object)(lVal) && R.is(Object)(rVal)) {
        return recursiveMergeDeepUnless(lVal, rVal, k);
      }
      return fnVal(k, lVal, rVal);
    }, lObj0, rObj0);
  };
  return recursiveMergeDeepUnless(lObj, rObj);
});
export const mergeDeepWhen = R.curry((fnWhen, fnObj, fnVal, lObj, rObj) => mergeDeepUnless(
  R.complement(fnWhen), fnObj, fnVal, lObj, rObj,
));
export const mergeDeepLeftWhen = R.curry((fnWhen, lObj, rObj) => mergeDeepUnless(
  R.complement(fnWhen), R.nthArg(1), R.nthArg(1), lObj, rObj,
));
export const mergeDeepRightWhen = R.curry((fnWhen, lObj, rObj) => mergeDeepUnless(
  R.complement(fnWhen), R.nthArg(2), R.nthArg(2), lObj, rObj,
));
```

And i use them like:

```javascript
const mergeDeepLeftWhenIsNotRefEquals = mergeDeepLeftWhen((k, l, r) => l !== r);

const isNotMoment = R.complement(R.is)(moment);
const mergeDeepLeftWhenIsNotMoment = mergeDeepLeftWhen(
  (k, l, r) => isNotMoment(l) && isNotMoment(r),
);
```

----

So the question is just that, is there is a built in way of doing something like this.

**Comment by CrossEye** [comment]
Every time Ramda chooses to optimize by returning an unaltered value in a function that usually alters that value, we end up causing problems with JS users' expectations.  Of course this wouldn't be an issue if users never mutated data.  This, unfortunately, is outside our control, and sometimes they do mutate it. If they mutate a property on the merged object that happens to be a reference to the property on an original object, they mutate the original too.  And they blame Ramda, with at least some justification.

That is why we don't tend to do this.

As to Moment, I don't know that there is an alternative.  We do our deep merge without ever trying to handle the prototype chain.  I don't see a way to do this differently, not with complete accuracy.  A constructor that uses its parameters to set up some invariants the object then maintains seems impossible to duplicate without access to the original parameters.  But even if we just wanted to merge `{x: new Rectangle(7, 4)}` and `{x: new Square(5)}`, which constructor would we try to use?  Right now we would probably get something like `{width: 7, height: 4, side: 5}` without the `area` or `perimeter` methods from those classes.  If you have a suggestion for how we could fix this, I'm very interested.  I've been trying to conceive of one for some time, with no success.

**Comment by jmdsg** [comment]
Yeah i understand that is difficult to decide when to return the original object and when to return a new one (performance vs usability?). But i think if the user is already using ramda, and wants to change some object's value, then it should do it using ramda, and not mutating the object directly, that's the point of `assoc` and similar methods.

If you have some objects to this:

```javascript
const objDoNotWantToMutate = { value: 1 };
const objToMerge1 = { deep: { key1: objDoNotWantToMutate } };
const objToMerge2 = { deep: { key1: objDoNotWantToMutate } };
const objToMerge3 = { deep: { key2: objDoNotWantToMutate } };
```

If you merge `objToMerge1` with `objToMerge2` and mutate the `key1`, then the original object is not mutated.

```javascript
const result = R.mergeDeepLeft(objToMerge1)(objToMerge2);
const obj = R.path(["deep", "key1"])(result);
obj.value = 2; // does not mutate 'objDoNotWantToMutate'
```

But if you merge `objToMerge1` with `objToMerge3` and mutate the `key1`, then the original object is mutated.

```javascript
const result = R.mergeDeepLeft(objToMerge1)(objToMerge3);
const obj = R.path(["deep", "key1"])(result);
obj.value = 2; // it does mutate 'objDoNotWantToMutate'
```

If you are mutating the result of a merge, you either have no idea/do not care that the original object is mutated or you know very well the structures of the objects been merged. In the first case the object is not cloned due to performance, and in the second case is merged to be less error prone (due to user misusing), is hard to maintain consistensy, while balancing performance and usability [but it can at least another method to provide more flexibility to the user, see below].

----

As of the moment thing, i agree, i don't think there is a logical way of implementing something like that. I mean what would be the logical result of merging a `new Circle(5)` with a `new Square(5)` (the only difference in the contructors is the name of the argument and is not reliable at all), the `area` method of both also return different values. So the most logical result of this merge would be the current behavior, an object that doesn't handle prototypes: `{ radio: 5, side: 5, area: f() }` where the area method is the one of the circle or the one of the square, depending whether it was a left or right or a merge with.

The only person that would know how to combine the `Circle` with the `Square` should be the user, he/she may prefer circles over squares, circles may be merged by radio average, and squares by max side size.

So i think it should be a method that allows to provide a function like this one (currently not posible since both `Circle` and `Square` are objects):

```javascript
const customMerge = (key, left, right) => {
  if (R.is(Circle)(left) && R.is(Square)(right)) return left; // prefer circles
  if (R.is(Square)(left) && R.is(Circle)(right)) return right; // prefer circles
  if (R.is(Circle)(left) && R.is(Circle)(right)) return new Circle(
    (left.radio + right.radio) / 2.0,
  ); // average circle radio
  if (R.is(Square)(left) && R.is(Square)(right)) { // prefer larger squares
    if (left.side >= right.side) return left; // or new Square(left.side) or left.clone()
    return right; // or new Square(right.side) or right.clone()
  }
}
```

This would allow the user to decide for instance, what to do when the objects are exacly the same (first example):

```javascript
const customMerge = (left, right) => {
  if (left === right) return left;
}
```

**Comment by Bradcomp** [comment]
> So i think it should be a method that allows to provide a function like this one (currently not possible [at least not in deep merges, in simple merges is possible using R.mergeWith] since both Circle and Square are objects)

Have you seen [`mergeDeepWithKey`](https://ramdajs.com/docs/#mergeDeepWithKey)?

**Comment by jmdsg** [comment]
> Have you seen [`mergeDeepWithKey`](https://ramdajs.com/docs/#mergeDeepWithKey)?

```javascript
function Circle(radio) {
  this.radio = radio;
  this.area = function() {
    return this.radio * this.radio * Math.PI;
  };
  this.area = this.area.bind(this);
};
function Square(side) {
  this.side = side;
  this.area = function() {
    return this.side * this.side;
  };
  this.area = this.area.bind(this);
};
```

Using the first `customMerge` in my last comment

```javascript
const simpleObj1 = { shape: new Circle(5) };
const simpleObj2 = { shape: new Square(5) };

const simpleMerge = R.mergeWithKey(customMerge)(simpleObj1)(simpleObj2);
// { shape: Circle{ radio: 5, area: f } }

simpleMerge === simpleObj1 // false
simpleMerge === simpleObj2 // false
simpleMerge.shape === simpleObj1.shape // true
```

Here everything it ok.

```javascript
const complexObj1 = { deep: { shape: new Circle(5) } };
const complexObj2 = { deep: { shape: new Square(5) } };

const complexMerge = R.mergeDeepWithKey(customMerge)(complexObj1)(complexObj2);
// { deep: { shape: { radio: 5, side: 5, area: undefined } } }

complexMerge === complexObj1 // false
complexMerge === complexObj2 // false
complexMerge.deep.shape === complexObj1.deep.shape // false
complexMerge.deep.shape === complexObj2.deep.shape // false
```

Here is not, and there is no way (that i know of) of doing this in ramda, have to implement the merge myself.

**Comment by CrossEye** [comment]
I suppose what I'd like to see is a PR for your proposal.  I'm not sure what the team would think, but i can promise a fair hearing.  I'm getting lost between what you think is desired behavior, and what you do and don't like about the current `merge*` functions.

**Comment by jmdsg** [comment]
Well when i first opened the issue i was just wondering why deep merge didn't make a simple `===` since the deep merge already do some optimizations; like avoiding to clone objects when is not necessary (e.g. key in just one of the two objects to be merged).

Now i think is just easier to provide a way to customize the behavior of the deep merge, so it doesn't affect any of the already existing methods.

But not sure if you want yet another merge function, or how many people would find it useful. I'm currently using some sort of custom deep merge in 3 of my 4 projects where i use ramda.

The implementation would be almost the same as `mergeDeepWithKey` except it receives another function. When this function `fnObj` returns an object, this result is used, and when it doesn't then the deep merge is done as usual.

```javascript
var mergeDeepUsingKey = _curry3(function mergeDeepUsingKey(fnObj, fnVal, lObj, rObj) {
  return mergeWithKey(function(k, lVal, rVal) {
    if (_isObject(lVal) && _isObject(rVal)) {
	  var r = fnObj(k, lVal, rVal);
	  return _isObject(r) ? r : mergeDeepUsingKey(fnObj, fnVal, lVal, rVal);
    } else {
      return fnVal(k, lVal, rVal);
    }
  }, lObj, rObj);
});
export default mergeDeepUsingKey;
```

The functionality of `mergeDeepWithKey` is the same as `mergeDeepUsingKey(always(null))`.

Or if it makes sense that `fnObj` returns another types, and not only objects, the result can be compared with a constant (like R.T) to continue the deep merge.
