### ISSUE TITLE
Add splitEveryWhen ?

### ISSUE THREAD

**Issue by macabeus** [ramda/ramda#2820]
I think that would be useful adds on Ramda a function that is like [`splitEvery`](https://ramdajs.com/docs/#splitEvery) + [`splitWhen`](https://ramdajs.com/docs/#splitWhen), because sometimes we need it to resolves some problems and isn't easy to compose these functions.

For example, if we have a list like a columns ID on Excel that always ends with `D` (`["A1", "B1", "C1", "D1", "A2", "D2", "A3", "B3", "D3"]`), we can't split these rows by `splitEvery` neither by `splitWhen`.

I implemented the `splitEveryWhen` using the following code:

```js
const splitEveryWhen = (pred) => reduce((acc, current) => {
  const lastInnerArray = last(acc)

  if (lastInnerArray.length === 0) {
    return [[current]]
  }

  const previous = last(lastInnerArray)
  if (pred(previous)) {
    acc.push([current])
    return acc
  }
  
  lastInnerArray.push(current)
  return acc
}, [[]])

splitEveryWhen(startsWith('D'))(["A1", "B1", "C1", "D1", "A2", "D2", "A3", "B3", "D3"])
```

**Comment by CrossEye** [comment]
I like the idea, and have had to write such functions myself often.   Please feel free to submit a PR for this.

**But**

  1. I'm not thrilled with the name.  `splitWhenever` sounds much cleaner to me.

  2. We would want Ramda's curried style that let us call `splitEveryWhen(pred)(xs)` or `splitEveryWhen(pred, xs)` interchangeably.  This can easily be done by calling `curry`, or really the internal `curry2`, on the uncurried version of this function.

  3. I usually want a slightly different function, one that *starts* a group whenever the predicate matches, not one that *ends* a group according to that predicate.  That is, I would get the same result as you want by passing `startsWith('A')`.

     We could offer both versions, although naming again gets ugly.  Or we could offer `splitBetween :: ((a, a) -> Bool) -> [a] -> [[a]]`, which offers up *both* the current and the previous values to decide if there should be a split between them.  The modification to your function would be trivial: `if (pred(previous)) {` => `if (pred(previous, current)) {`.  It would be used like:

     ```js
     splitBetween(gt)([8, 6, 7, 5, 3, 0, 9]) 
     //=>[[8], [6, 7], [5], [3], [0, 9]] // now broken into increasing groups.
     ```

     The problem is that, while this would work fine for the general case, and work easily for my case, simply because it would ignore the second parameter, it would make your case a bit harder.  It's not a *lot* harder.  You could simply write `splitEveryWhen((a, b) => b.startsWith('D'))` or some point-free equivalent, but it's slightly less elegant.

**Comment by CrossEye** [comment]
Wait a minute.  We already have something like this.  It's call `groupWith`, rather than `splitBetween`, and the sense of the predicate is reversed.  I **knew** I'd written something like this before!

```js
groupWith((a, b) => b.startsWith('D'))(["A1", "B1", "C1", "D1", "A2", "D2", "A3", "B3", "D3"])
//=> [["A1"], ["B1"], ["C1", "D1"], ["A2", "D2"], ["A3"], ["B3", "D3"]]
```

Does that cover your case well enough?

**Comment by macabeus** [comment]
@CrossEye Hello, thank you for the nice feedback on the issue! 😄

The `groupWith` isn't cover my case, because I need the following output:

```js
[["A1", "B1", "C1", "D1"], ["A2", "D2"], ["A3", "B3", "D3"]]
```

That is, I need to group the elements splitting whenever that the predicate is true.
**But** updating your code to this, works!

```js
groupWith((a, b) => b.endsWith(tail(a)))(["A1", "B1", "C1", "D1", "A2", "D2", "A3", "B3", "D3"])
// => [["A1", "B1", "C1", "D1"], ["A2", "D2"], ["A3", "B3", "D3"]]
```

Then I can group the cells on the same row. It is another way to solve my problem - instead of looking for the column ID, I can looking for the row number.

About the topics:

1. Okay. `splitWhenever` is a good name.
2. Yeah. Well remembered. In the PR I'll curry this function.
3. I like this improvement, using `if (pred(previous, current)) {` instead of `if (pred(previous)) {`. It will be useful for more cases and it doesn't affect my original code! The result is the same. You can see it: [first version](https://ramdajs.com/repl/#?const%20splitEveryWhen%20%3D%20%28pred%29%20%3D%3E%20reduce%28%28acc%2C%20current%29%20%3D%3E%20%7B%0A%20%20const%20lastInnerArray%20%3D%20last%28acc%29%0A%0A%20%20if%20%28lastInnerArray.length%20%3D%3D%3D%200%29%20%7B%0A%20%20%20%20return%20%5B%5Bcurrent%5D%5D%0A%20%20%7D%0A%0A%20%20const%20previous%20%3D%20last%28lastInnerArray%29%0A%20%20if%20%28pred%28previous%29%29%20%7B%0A%20%20%20%20acc.push%28%5Bcurrent%5D%29%0A%20%20%20%20return%20acc%0A%20%20%7D%0A%20%20%0A%20%20lastInnerArray.push%28current%29%0A%20%20return%20acc%0A%7D%2C%20%5B%5B%5D%5D%29%0A%0AsplitEveryWhen%28startsWith%28%27D%27%29%29%28%5B%22A1%22%2C%20%22B1%22%2C%20%22C1%22%2C%20%22D1%22%2C%20%22A2%22%2C%20%22D2%22%2C%20%22A3%22%2C%20%22B3%22%2C%20%22D3%22%5D%29) - [second version](https://ramdajs.com/repl/#?const%20splitEveryWhen%20%3D%20%28pred%29%20%3D%3E%20reduce%28%28acc%2C%20current%29%20%3D%3E%20%7B%0A%20%20const%20lastInnerArray%20%3D%20last%28acc%29%0A%0A%20%20if%20%28lastInnerArray.length%20%3D%3D%3D%200%29%20%7B%0A%20%20%20%20return%20%5B%5Bcurrent%5D%5D%0A%20%20%7D%0A%0A%20%20const%20previous%20%3D%20last%28lastInnerArray%29%0A%20%20if%20%28pred%28previous%2C%20current%29%29%20%7B%0A%20%20%20%20acc.push%28%5Bcurrent%5D%29%0A%20%20%20%20return%20acc%0A%20%20%7D%0A%20%20%0A%20%20lastInnerArray.push%28current%29%0A%20%20return%20acc%0A%7D%2C%20%5B%5B%5D%5D%29%0A%0AsplitEveryWhen%28startsWith%28%27D%27%29%29%28%5B%22A1%22%2C%20%22B1%22%2C%20%22C1%22%2C%20%22D1%22%2C%20%22A2%22%2C%20%22D2%22%2C%20%22A3%22%2C%20%22B3%22%2C%20%22D3%22%5D%29).

If you think that it is a good improvement for Ramda, I could create a pull request. I could solve my problem using a simpler strategy, thank you 😋

**Comment by CrossEye** [comment]
Sorry, I must have copy-pasted the wrong block.

This was the version that seemed to work:


```js
groupWith((a, b) => !a.startsWith('D'))(["A1", "B1", "C1", "D1", "A2", "D2", "A3", "B3", "D3"])
//=> [["A1", "B1", "C1", "D1"], ["A2", "D2"], ["A3", "B3", "D3"]]
```

That's why I think this might be unnecessary.  It's mostly covered by the `groupWith` function.

Please feel free to try to convince me otherwise.  It's been known to happen!

**Comment by Bradcomp** [comment]
`groupWith` only works with contiguous elements. I think this is closer to a generic version of `partition`, which is subtly different.

While I am not against this, I typically just use `groupBy`. If I need an Array instead of an Object I can call `values` on the result, but I find that doesn't happen often, as the Object is typically nicer to work with.

**Comment by macabeus** [comment]
I'm thinking the same.
I can't find a situation that `groupWith` isn't covering the work of `splitWhenever`, just using some differences on predicate.
