### ISSUE TITLE
pipeWith with composed piping function

### ISSUE THREAD

**Issue by daguix** [ramda/ramda#2823]
Hi,

  `pipeWith` is a great function. We can use it to `pipe` with Promise `pipe(then)` or with passing undefined like in the docs `pipe(unless(isNil)`.

  But if we want to do both and composing `then` and `unless(isNil)`, we end up with:
`pipeWith(
(f,res) => pipe(then, unless(isNil))(f)(res)
)`

  It would be better and more expressive to have: 
`pipeWith( pipe(then, unless(isNil)) )`

  In the `pipeWith` code, `xf` should be called twice with each argument instead of once and should be curried for retrocompatibility.

**Comment by CrossEye** [comment]
Please feel free to open a PR for this.

**Comment by daguix** [comment]
I will

**Comment by daguix** [comment]
In javascript the only way to check if a binary function is curried is to call the function with `undefined` as the second argument and check that it returns a function. So it means calling the function twice eventually (first with undefined and then with the correct argument) and dealing with potential exceptions.

You probably want to stay with the chosen definition of pipeWith. For people who want a more expressive version of `pipeWith` can define:
`const pipeWithCurried = pipe(uncurryN(2), pipeWith)`

**Comment by CrossEye** [comment]
... and since JS functions are proper values, that is actually not even a guarantee.  I guess you can tell that it's *not* curried if you call it with one parameter and get back something that's not a function, but... eww.
