### ISSUE TITLE
Feature request: `viewOr` 

### ISSUE THREAD

**Issue by ilyalesik** [ramda/ramda#2824]
Probably will be convenient to have `viewOr` function, similar to `propOr`
```javascript
const xLens = R.lensProp('x');

R.viewOr(1, xLens, { y: 2});  //=> 1
```

**Comment by CrossEye** [comment]
Ramda has mostly stuck with complete lenses, and I'm not sure if there's a great argument to start including other optics.

Obviously it's not hard to create this in userland if desired:


```js
const xLens = lensProp ('x');
compose (defaultTo (1), view (xLens)) ( {x : 2} )  //=> 1

// or

const viewOr = curry ( (dflt, lens, value) =>
  defaultTo (dflt, view (lens, value) ))

viewOr (1, xLens) ( {y: 2} ) //=> 1
```

@polytypic's [patial-lenses][pl] is an excellent library if you are looking for this sort of thing.


  [pl]: https://github.com/calmm-js/partial.lenses

**Comment by ilyalesik** [comment]
Thanks!
