### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by LeonardoHabitzreuter** [ramda/ramda#2826]
Basically I would like to import the functions separately.
Motivation: My project doesn't use the entire library, even so the whole bunch of code is imported.

I can send a PR. What do you tell me?

**Comment by CrossEye** [comment]
```js
const map = require('ramda/src/map')

console.log(map(n => n * n, [1, 2, 3, 4, 5]))
```

I believe tree-shaking tools should work with Ramda as well.

**Comment by customcommander** [comment]
See also https://github.com/ramda/ramda#usage
