### ISSUE TITLE
typescript: R.propOr return type {}

### ISSUE THREAD

**Issue by paperx123** [ramda/ramda#2830]
Changing to typescript and had this issue - The depth is prompted to be  type of {}.  should it be the typeof 1 | typeof row.depth?

          const row = { depth: 1 };
          const test = R.propOr(1, 'depth')(row);

**Comment by ozzywalsh** [comment]
I would imagine this is an issue for [@types/ramda](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/).

To fix your issue for now, you could just explicitly annotate the value of the `test` variable.
```
const row = { depth: 1 };
const test: number = R.propOr(1, 'depth')(row);
```

**Comment by CrossEye** [comment]
Agreed, this issue is for whoever maintains the typing file you use.
