### ISSUE TITLE
Graph functions

### ISSUE THREAD

**Issue by bionicles** [ramda/ramda#2834]
We want to make a knowledge graph editor in the front end, and we’re curious about ramda. The docs don’t mention much about graph algorithms... we would like to use ramda for this; an immutable store / reducer / dispatch pattern could hold multiple graphs which might share vertices and/or edges, plus the objects could have other properties, and we would like to implement access control lists / roles

Like so: 
Store = { graphs: { id: Graph }, vertices: { id: Vertex }, edges: { id: Edge } }
Graph = { key: value, vertices : Set(id}, edges: Set(id) }
Vertex = { key: value, edges: Set(id), neighbors: Set(id) }
Edge = { key: value, source: id, target: id } 

Or, can json handle circular references? Then edges can contain vertices (by reference) which contain edges and neighbors? Might be easier to traverse this way with index free adjacency by reference

how do you use ramda for functional graph programming, especially to implement something like TinkerPop Gremlin traversals?

https://www.datastax.com/dev/blog/a-gremlin-implementation-of-the-gremlin-traversal-machine

https://en.wikipedia.org/wiki/Glossary_of_graph_theory_terms

http://hackage.haskell.org/package/fgl

https://github.com/gistya/Functional-Swift-Graph

Maybe 
https://schema.org/docs/full.html
https://www.w3.org/TR/json-ld11/

**Comment by CrossEye** [comment]
Nothing built into Ramda would offer specific help for this.  But if you were to use Ramda as a utility library, it should offer the immutability support and some help with structural sharing.  (It is not sophisticated in this, but functions like `assoc` / `dissoc`, and the lenses built atop them would share whatever structures they can.)

**Comment by bionicles** [comment]
thanks @CrossEye , ramda definitely helps with graph algorithms because of the strong overall concept of function-building, and so is the Ramda REPL, although **I wish the REPL console printed the input line which produces a certain output because sometimes it just reads `Cannot read property 'undefined' of undefined`** with no indication of what causes the problem! No bueno!

assoc, assocPath, evolve, merge, mapObjIndexed, forEach, filter, map, toPairs, 

all come in handy

selections feel hard because we have to update in multiple places... but i swear i've learned a ton about javascript since i started using ramda. 

it might be nice to make assocPaths or evolvePaths to make multiple adjustments at once. Another thing we sometimes have to is apply a computation over one object to update another. For example to make a vertex, we make edges to connect it to a bunch of prior selections, then we need to add those edge ids to that new vertex and to the prior selection. Later on if we delete a vertex, it makes sense to go back and delete all the incident edges. 

We might also want to track the neighbors on vertices ... and are they children? or parents? This type of indexing might be expensive at runtime but might save ridiculous compute later on...and furthermore, various graph traversal queries are IMPOSSIBLE in a SQL setting, but easy on the right graph. It's nice to think we could use arrays, but what happens if 5000 people have 5000 friends and they each want to de-friend one person? that's potentially O(5000^2) -- and in systems biology, there are 20,000 genes many with multiple splice sites. Good luck looping through adjacency lists fast enough to provide a good user experience in systems biology!

Evolve seems like it could handle a lot, but we often need to update the properties using the other properties, so we can't just evolve objects by operations restricted to individual properties. It would be pretty cool if we could !

That's not 'index-free adjacency' but we could still do traversals with a "walk" function, we give it a list of paths and filters and it goes from one, to another, to another object ... need to track neighbor / source / target / edge indexes on each vertex before we can even get there. It is possible. and 

Will post code soonish. Just so everyone can benefit.

updating multiple nested objects in multiple different ways based on other nested objects ... brain melt

**Comment by CrossEye** [comment]
I could certainly see a function that combines `evolve` with `applySpec`, one which transforms the named properties with a function accepting the whole object and copies over intact any properties not named.  It's not quite clear to me whether this would help you, but it makes sense to me:

```js
evolveSpec({  // naming is hard!
  prev: o => o.curr,
  curr: o => o.prev + o.curr,
}, {
  curr: 1,
  prev: 0,
  name: 'fibonacci'
}) 
//=> {
//  prev: 1,
//  curr: 1,
//  name: 'fibonacci' // carried over even though not in spec
// }
```

----------

I'm looking forward to seeing what you're doing with this!

**Comment by bionicles** [comment]
```
let objects = {
  1: {
    edges: {
      2: 'ramda',
      3: 'rocks',
      4: 'rocks',
      5: 'in',
      6: 'in',
      7: 'in',
      8: 'out',
    }
  }
}

// pathLookup :: object -> fn(path) -> object at path
const pathLookup = flip(path)

// pathLookup :: (object, path:array of keys) -> object with unique counts at path
const countUnique = pipe(pathLookup, values, countBy(identity));

let vertexId = 1
let atPath = [vertexId, 'edges'];
let counts = countUnique(objects, atPath);

`vertex ${vertexId} edge count: ${counts.in} in and ${counts.out} out`
```

**Comment by bionicles** [comment]
```
let simulations = {
  1: {
    nodes: [1, 2, 3]
  },
  2: {
    nodes: [4,5,6]
  },
  3: {
    nodes: [7,8,9]
  }
}

const assemble = propName => {
  return pipe(
    values(),
    pluck(propName),
    unnest
  )
}

assemble("nodes")(simulations)
```

> [1, 2, 3, 4, 5, 6, 7, 8, 9]
