### ISSUE TITLE
differenceWith 

### ISSUE THREAD

**Issue by moriyalb** [ramda/ramda#2838]
`differenceWith` has a strange result , check code below:
```js
    let cmp = (a, b) => a%2 == b%2
    R.differenceWith(cmp, [1,2,3,4], [5,7]) //=> [2]  //maybe we want [2,4]
```
I find that `pred` function will be also invoked to the out list values.
Is that confused to you?

**Comment by CrossEye** [comment]
You're right.  That doesn't seem right.  It should return `[2, 4]`.

Are you interested in trying to create a Pull Request to fix this?

**Comment by moriyalb** [comment]
> Absolutely. That doesn't seem right. It should return `[2, 4]`.
> 
> Are you interested in trying to create a Pull Request to fix this?

Fine, I will fix this.

**Comment by moriyalb** [comment]
> > Absolutely. That doesn't seem right. It should return `[2, 4]`.
> > Are you interested in trying to create a Pull Request to fix this?
> 
> Fine, I will fix this.

this problem is fixed in new version.  I should update my libs now.

**Comment by sarus** [comment]
Hello,

We're seeing this issue in v0.26.1.  Is this resolved in v0.27.0?  If so, is that release something that can be pushed to npm?

Thank you!

**Comment by BobbieBarker** [comment]
This isn't fixed in the current version. You can throw OP's example in the ramda repl and easily reproduce the issue.

**Comment by CrossEye** [comment]
I'll try to look into this tonight.  I don't recall any recent changes that would have addressed this.

**Comment by kurtmilam** [comment]
I'm pretty sure the described behavior is by design.

According to the given predicate, `2` and `4` are duplicates.

`R.differenceWith` returns a Set (with no duplicates, where duplication is defined by the supplied predicate).

In essence, we have three arrays: `first` and `second` (the inputs) and `out` (the output).

Each element in `first` is compared to each element in `second` AND each element in `out`. The element from `first` is only added to `out` if a duplicate (as defined by the supplied predicate function) is not found in `second` OR `out`.

[Here are some notes and links I posted in the gitter channel](https://gitter.im/ramda/ramda?at=5d8228e328c1df0ed65150ed) before I saw this issue.

**Comment by kurtmilam** [comment]
On [September 14, 2014](https://github.com/ramda/ramda/blob/45f9b2ee0f57e2e616dc626d2126e1ae41a23e7a/ramda.js#L5026), it looked like this:
```
    R.differenceWith = curry3(function differenceWith(pred, first, second) {
        return uniqWith(pred)(reject(flip(R.containsWith(pred))(second), first));
    });
```

So, it was returning a Set of unique values, but it wasn't using the predicate to determine uniqueness in `out`.

The current behavior was added on [October 18, 2014](https://github.com/ramda/ramda/commit/0eccd0dff9a3671524f422f69680797bed18dd15#diff-19b69ff9ef07f9c773e75547746c66c6R5313):
```
    R.differenceWith = curry3(function differenceWith(pred, first, second) {
	var out = [];
        var idx = -1;
        var firstLen = first.length;
        var containsPred = R.containsWith(pred);
        while (++idx < firstLen) {
            if (!containsPred(first[idx], second) && !containsPred(first[idx], out)) {
                out.push(first[idx]);
            }
        }
        return out;
    });	
```

**Comment by kurtmilam** [comment]
Actually, I got that wrong. The current behavior was added earlier than October 18, 2014. On that date, the implementation I pasted above replaced this similar (identical in functionality?) one, just written differently:
```
    R.differenceWith = curry3(function differenceWith(pred, first, second) {
        return uniqWith(pred)(reject(flip(R.containsWith(pred))(second), first));
    });	
```

**Comment by sarus** [comment]
Your explanation makes sense to me now but the resulting behavior where the predicate is also applied to deduping operation was pretty non-intuitive for me (at least with the use case we had).  

It would be great if there was a way to either supply a different predicate for the deduping operation or to just turn it off entirely.

Thank you for the detailed explanation!

**Comment by kurtmilam** [comment]
@sarus I agree that the behavior could be explained more explicitly in the docs. There's a new PR for that: https://github.com/ramda/ramda/pull/2893
