### ISSUE TITLE
Do we have any ramda method for finding if key exists or not?

### ISSUE THREAD

**Issue by skirankumar7** [ramda/ramda#2844]
As far I know that we have Ramda method **R.prop** but it gives the **value of that key if key exits else return undefined** but I don't want that.

of course we have **object.hasOwnProperty** method, but I want  ramda method,

better if we have this feature something like this: **hasProp('name',object)**

**Comment by CrossEye** [comment]
For anyone else who stumbles across this, the function [`has`][ha] serves this purpose.


  [ha]: https://ramdajs.com/docs/#has
