### ISSUE TITLE
Should Set operations accept variable argument lists?

### ISSUE THREAD

**Issue by bd82** [ramda/ramda#2846]
E.g **union** / **Intersect** / **symmetricDifference**

```javascript
R.union([1, 2, 3], [2, 3, 4], [4, 5]); //=> [1, 2, 3, 4, 5]
```

I am new to Ramda, so maybe I am missing something basic here?

Thanks for Ramda 👍

**Comment by CrossEye** [comment]
Ramda has avoided such variadic functions, with a few unfortunate exceptions like `pipe`.

Ramda is built around composing functions, and thus curried functions are extremely important.  But it is very difficult to combine currying with variadic functions.  This is the same reason that Ramda avoids optional parameters.

**Comment by Bradcomp** [comment]
You could make something yourself pretty easy:

```
pipe(
  unapply(unnest),
  uniq
)([1,2,3], [2,3,4], [4,5,6])  // [1,2,3,4,5,6]
```

Or use ES6 functions to make it nicer...

**Comment by bd82** [comment]
Thanks for the quick replies and provided snippets 👍
