### ISSUE TITLE
R.template: compound strings with tagged template literals

### ISSUE THREAD

**Issue by renatorib** [ramda/ramda#2853]
This is just a suggestion. If it sounds good, let me know. I'd love to be able to create my first pull request here.

### The case

I see that composing a string from my data is something that is not very simple yet, despite having quite a few common cases. 

```js
const data = {
  profile: {
    firstName: "Renato",
    lastName: "Ribeiro"
  }
}

R.pipe(
  R.prop('profile'),
  R.pick(['firstName', 'lastName']),
  R.values,
  R.join(' '),
)(data) // => "Renato Ribeiro"
``` 

This works fine for the case in question, although it is verbose, but it's not very flexible in case I want to build a more complex string.

```js
const data = {
  address: {
    street: "Hursley Park",
    city: "Winchester",
    postCode: "SO21 2JN"
  }
}

R.pipe(
  R.prop('address'),
  address => `${address.street}, ${address.city} - (${address.postCode})`
)(data) // => "Hursley Park, Winchester - (SO21 2JN)"
```

### R.template

I see there's room for an elegant solution using Tagged Template Literals so we can do things like this:

```js
const data = {
  address: {
    street: "Hursley Park",
    city: "Winchester",
    postCode: "SO21 2JN"
  }
}

R.pipe(
  R.prop('address'),
  R.template`${R.prop('street')}, ${R.prop('city')} - (${R.prop('postCode')})`
)(data) // => "Hursley Park, Winchester - (SO21 2JN)"
```

```js
const data = {
  profile: {
    firstName: "Renato",
    lastName: "Ribeiro"
  }
}

R.pipe(
  R.prop('profile'),
  R.template`${R.prop('firstName')} ${R.prop('lastName')}`
)(data) // => "Renato Ribeiro"
``` 

It works very similar to the styled-components. Each interpolation can act as a function that receives the data, for example:
```js
R.template`${data => ...} some text ${data => ...}`(data)
```

```js
// if interpolation value isn't a function, it is used as raw value
const greet = "Hello"
const yellGreet = R.template`${greet}, ${R.toUpper}` 
yellGreet('Renato') // => "Hello, RENATO"

const formatFullName = R.template`${R.prop('firstName')} ${R.prop('lastName')}`
formatFullName({ firstName: "Renato", lastName: "Ribeiro" })

const strong = R.template`<strong>${R.identity}</strong>`
strong('More bold than ever') // => "<strong>More bold than ever</strong>"
```

[A dirty implementation (demo purpose) can be seen here.](https://ramdajs.com/repl/?v=0.26.1#?R.template%20%3D%20%28strings%2C%20...values%29%20%3D%3E%20props%20%3D%3E%0A%20%20pipe%28%0A%20%20%20%20addIndex%28map%29%28%28string%2C%20i%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20string%20%2B%20defaultTo%28%27%27%2C%20typeof%20values%5Bi%5D%20%3D%3D%3D%20%27function%27%20%3F%20values%5Bi%5D%28props%29%20%3A%20values%5Bi%5D%29%0A%20%20%20%20%7D%29%2C%0A%20%20%20%20join%28%27%27%29%0A%20%20%29%28strings%29%0A%0Aconst%20user%20%3D%20%7B%0A%20%20profile%3A%20%7B%0A%20%20%20%20firstName%3A%20%27Renato%27%2C%0A%20%20%20%20lastName%3A%20%27Ribeiro%27%0A%20%20%7D%2C%0A%20%20address%3A%20%7B%0A%20%20%20%20street%3A%20%22Hursley%20Park%22%2C%0A%20%20%20%20city%3A%20%22Winchester%22%2C%0A%20%20%20%20postCode%3A%20%22SO21%202JN%22%0A%20%20%7D%2C%0A%7D%0A%0AR.applySpec%28%7B%0A%20%20fullName%3A%20R.pipe%28%0A%20%20%20%20R.prop%28%27profile%27%29%2C%0A%20%20%20%20R.template%60%24%7BR.prop%28%27firstName%27%29%7D%20%24%7BR.prop%28%27lastName%27%29%7D%60%0A%20%20%29%2C%0A%20%20fullAddress%3A%20R.pipe%28%0A%20%20%20%20R.prop%28%27address%27%29%2C%0A%20%20%20%20R.template%60%24%7BR.prop%28%27street%27%29%7D%2C%20%24%7BR.prop%28%27city%27%29%7D%20%28%24%7BR.prop%28%27postCode%27%29%7D%29%60%0A%20%20%29%0A%7D%29%28user%29%0A%0A%0A)

### The problems

1. As the behavior of a tagged template literals is quite different from a common function, it would not be possible to curry it. But it works as well:
```R.template`${...}`(data)``` 
2. The same problem for partial application (I guess).
3. Signature?
4. ?

---

> If it sounds good, let me know. I'd love to be able to create my first pull request here.

**Comment by jethrolarson** [comment]
This is neat but seems to be outside the scope of ramda, IMO.

**Comment by CrossEye** [comment]
My first thought is simply: *why*?

Ramda has a two-fold goal: making FP techniques more readily accessible for Javascript users, and making Javascript comfortable for experienced FPers.  It's not meant to be a general-purpose utility library in the mold of Underscore.

So while I can see some utility in this function, I don't see it as helping with either of those goals.  Moreover, I don't think it offers much of a clean-up over the lambda functions you replace with it.  I agree with @jethrolarson: this makes more sense to me in one of the companion libraries and/or the Ramda [Cookbook][cb].

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by renatorib** [comment]
I got it. Thanks guys :)

**Comment by CrossEye** [comment]
@renatorib: Regardless, thank you very much for your contribution!
