### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by mayinghan** [ramda/ramda#2854]
```
Environment: 
    NAME="Ubuntu"
    VERSION="18.04.1 LTS (Bionic Beaver)"
npm version: 6.4.1
node version: 10.15.3
run command: node --max-semi-space-size=10000 --max-old-space-size=40000 xx.js
Memory: 80G
Dataset size: 1028673 records (1 record ~= 4kb) (so approx. 4gib in total)
```
```
<--- Last few GCs --->

[19246:0x3c0ba70] 13018753 ms: Scavenge 15929.0 (32800.1) -> 17647.7 (32800.1) MB, 236071.8 / 0.0 ms  (average mu = 0.309, current mu = 0.369) allocation failure 
[19246:0x3c0ba70] 13263082 ms: Scavenge 15929.0 (32800.1) -> 17701.0 (32800.1) MB, 238469.3 / 0.0 ms  (average mu = 0.309, current mu = 0.369) allocation failure 
[19246:0x3c0ba70] 13510095 ms: Scavenge 15929.0 (32800.1) -> 17763.1 (32800.1) MB, 240951.1 / 0.0 ms  (average mu = 0.309, current mu = 0.369) allocation failure 


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [node]
 2: 0x8dc55c  [node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec7bf2  [node]
 6: 0xefaf66 v8::internal::MarkCompactCollector::Evacuate() [node]
 7: 0xefb5c2 v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: 0xed3411 v8::internal::Heap::MarkCompact() [node]
 9: 0xed3b01 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
11: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
12: 0xea0466 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [node]
13: 0xea0cea v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [node]
14: 0xea12a7 v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::PretenureFlag) [node]
15: 0xe62190  [node]
16: 0xe65322  [node]
17: 0xe65682  [node]
18: 0xe665a2 v8::internal::ArrayConstructInitializeElements(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Arguments*) [node]
19: 0x10fa09f v8::internal::Runtime_NewArray(int, v8::internal::Object**, v8::internal::Isolate*) [node]
20: 0x1bac6fc5be1d 
Aborted (core dumped)
```

The code snippet where breaks the program:
The input will be a 1028673 Json objects. Each object contains an array called enrollment, and the following code will only take out and deal with
that array in each object. (Here, ramda function over() is used to perform this operation).
The total length of that field (the enrollment array) is 71,157,478.

Then I performed three steps on that array for each object: 

step one, add empty field for each element inside the array  
step two, remove duplication based on one of the properties of the elements inside the array
step three, sort

``` 
const enrollments = compose(  //ramda functions
	sortBy(prop('date')), //step 3 
	deduplicate, //step 2
	map(normalize) //step 1
);
```

Is there any potential memory leak issue on function over() / compose() / map()?
Thanks in advance

**Comment by Bradcomp** [comment]
With the amount of data you are dealing with, I would guess that the issue is due to Ramda's principal for not mutating the input data. Each call to `over` will generate a new object, as will the call to `map`, and the call to `sortBy` I believe.

This will create a whole bunch of new objects that could be the cause of your memory woes.

In the past, when working with large data transformations it to prototype it in Ramda, make sure I have tests that prove it's working, then rewrite the code using lower level constructs so that I can take advantage of mutations to improve efficiency, while using my tests as a way to not break things.

**Comment by CrossEye** [comment]
Can you share more of your code?  What's happening in `deduplicate`?  Are you calling `over` on the enrollments property of your records, or on something else?  Have you tested without the `sort`?

I tend to deal with hundreds, thousands, occasionally tens of thousands of records, never hundreds of thousands or millions.  So I don't have experience dealing with this size data in JS.  So I defer to Brad's expertise here.

But if we can see more code, perhaps we can get an idea.

**Comment by mayinghan** [comment]
@CrossEye Sure, so the code snippet that I called 'enrollments' is like the following:
```
map(over(lensProps('enrollment', enrollments)
```
where enrollment is the object prop that I wish to deal with.

**Comment by CrossEye** [comment]
Something looks odd about that, something beside the unbalanced parentheses, `over` takes a lens, a transformer function, and the data.  I don't see a function here.  What is the action you're performing with that lens?

Are you using `R.uniq*` in there?  That is one of the functions with the slowest performance characteristics; I wouldn't be at all surprised if it's also memory-intensive.

**Comment by mayinghan** [comment]
@CrossEye Sorry about the typo. I've already updated my previous comment. The 'enrollments' is a bunch of functions that I bind using compose() 
```
const enrollments = compose(  //ramda functions
	sortBy(prop('date')), //step 3 
	deduplicate, //step 2
	map(normalize) //step 1
);
```

**Comment by CrossEye** [comment]
So how large are the arrays passed to `sortBy`?  Because if those are something like the 71 million records you mention above, and your doing this a million times, it will at the very least be time-consuming.  I can't see why it would be particularly memory intensive, but I guess it depends on what's in them.
