### ISSUE TITLE
Why R.hasPath is still unsafe?

### ISSUE THREAD

**Issue by drebits** [ramda/ramda#2857]
There is [validation to avoid this problem](https://github.com/ramda/ramda/blob/03817fe578048652b9532ae71fd1f1705da4de60/source/hasPath.js#L29), and there are [tests](https://github.com/ramda/ramda/blob/03817fe578048652b9532ae71fd1f1705da4de60/test/hasPath.js#L70) too. However, when you install ramda **R.hasPath** is still unsafe, and even in the Ramda REPL is failing too, with [undefined](https://ramdajs.com/repl/?v=0.26.1#?R.hasPath%28%5B%27hello%27%2C%20%27world%27%5D%2C%20undefined%29%0A) or [null](https://ramdajs.com/repl/?v=0.26.1#?R.hasPath%28%5B%27hello%27%2C%20%27world%27%5D%2C%20null%29%0A).

@char0n do you know something about this?

**Comment by char0n** [comment]
@drebits there is slight confusion in [ramda release](https://github.com/ramda/ramda/releases) process lately. Although I fixed the problem in [R.hasPath](https://github.com/ramda/ramda/commit/4cd4e4bb85ab9d7a532fbb45e5e70009cdbc2098) and it was successfully merged to master, there never has been a release of this bugfix. 

In the meantime I suggest you to use [RA.hasPath](https://char0n.github.io/ramda-adjunct/2.18.0/RA.html#.hasPath) which is safe and without any problems.

**Comment by drebits** [comment]
Wow, thanks @char0n, I didn't know that.
I guess this answers my question, I'll keep using [RA.hasPath](https://char0n.github.io/ramda-adjunct/2.18.0/RA.html#.hasPath).

**Comment by CrossEye** [comment]
I'm hoping the long weekend will give me time to get a new release out.
