### ISSUE TITLE
Question about type method

### ISSUE THREAD

**Issue by MatteoGioioso** [ramda/ramda#2858]
Hello
Out of curiosity I saw in the source code of `type`: 
```
var type = _curry1(function type(val) {
  return val === null
    ? 'Null'
    : val === undefined
      ? 'Undefined'
      : Object.prototype.toString.call(val).slice(8, -1);
});
``` 

you do an additional check to get the type of `null` and `undefined`, but I saw that you can get as well `'Null'` or `'Undefined'` with simply: 
```
var type = _curry1(function type(val) {
  return Object.prototype.toString.call(val).slice(8, -1);
})
```
Is there any reason for this?

Thanks

**Comment by CrossEye** [comment]
I'm not certain that this was the case at the time the function was written, and I suspect that there may be environments where it would still fail.  but I don't recall any specifics.

However, unless we can find such, a PR to change this would be welcome.

**Comment by MatteoGioioso** [comment]
@CrossEye Hey, thanks for the answer. 
I understand, I could take a look at it when I have some time.

Thanks
