### ISSUE TITLE
R.all and R.none have the same behavior for empty array

### ISSUE THREAD

**Issue by git-josephlin** [ramda/ramda#2860]
### Bug Report
R.all and R.none have the same behavior on a empty array

### To Reproduce
```

const R = require('ramda');
console.log(R.all(R.gt(10))([])) // => true
console.log(R.none(R.gt(10))([])) // => true
```
### Expected Behavior
This is due to the fact that none passes complement of the predicate to All, then returns the result. I'm not sure what the appropriate fix would be here.

**Comment by Bradcomp** [comment]
It seems to me that it is `true` both that all of the items in [] are both greater than, and not greater than, 10.

The behavior of these functions with an empty list are based on the concept of a [vacuous truth](https://en.wikipedia.org/wiki/Vacuous_truth).

**Comment by git-josephlin** [comment]
Okay, this will require some reexamining on how we want to architect this. Sounds good. Thanks for the feedback.
