### ISSUE TITLE
Pipe access

### ISSUE THREAD

**Issue by glebfeklistov** [ramda/ramda#2865]
```js
const references = ({Model, references}) => R.pipe(
  R.prop('model'),
  R.when(R.is(String), R.pipe(
    R.prop(__, this.sequelize.models),
    relations(Model)
    )
  )
)(references);                          
```

How to access to pipe arguments without arrow wrapper function

Like this:
```js
R.pipe(
  R.prop('rawAttributes'),
  R.map(references)
);              
```

**Comment by CrossEye** [comment]
Sorry, I ignored this when I first saw it because I didn't know what you were asking, told myself I'd come back to it and promptly forgot.

Could you add some more explanation of what you're trying to do and what is not working?

**Comment by glebfeklistov** [comment]
I allready found answer, thanks.
