### ISSUE TITLE
type into in typescript

### ISSUE THREAD

**Issue by edgarjrg** [ramda/ramda#2868]
Hi! 
first, thank you all for this superb library! 

I've read some issues here about typescript and know that the core team is not maintaining the typescript typing, but still think this is the best place to put this question and maybe reference it somewhere else.

I loooove transducers, so i'm usually using `transducer` or `into` everywhere i can, but in typescript land, it has been very hard for me to type it, i would like to understand both how could type it and if it is not possible where is the issue.

```

import {
  filter,
  into,
  map,
  compose,
} from 'ramda';

type OrderAndValue = { order: number, value: string }

type Values = string[]

const vals: Values = into<any>(
  [],
  compose<any, any, any>(
    filter<any>(x => x.id > 5),
    map<any, any>(x => x.val)
  ),
  [
    { order: 1, value: 'a' },
    { order: 5, value: 'b' },
    { order: 10, value: 'c' },
  ]
)
```

here, for typescript is so difficult to understand what gets into `map`, because transducer expects to apply the fns in `compose` in the read order.

My question: is there any way to type this ? to get the type of `OrderAndValue` in the `map` and return `Values` ?

**Comment by CrossEye** [comment]
We'll see if anyone here has an answer.  I'm afraid I have no clue about the Typescript typings.

I would suggest that the best place to get an answer is somewhere they maintain one of the typing files.

**Comment by GingerPlusPlus** [comment]
`DefinitelyTyped` seems to have no proper transducer typings for [`map`], [`filter`], even [`into`]!

I'm very slowly working on transducer-first FP library in TS, maybe its typings will be helpful for contributing to `DefinitelyTyped`.

[`map`]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6c9d016e6916e138f4d8e1df19606758c0d20c72/types/ramda/index.d.ts#L971-L979
[`filter`]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6c9d016e6916e138f4d8e1df19606758c0d20c72/types/ramda/tools.d.ts#L225-L231
[`into`]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6c9d016e6916e138f4d8e1df19606758c0d20c72/types/ramda/index.d.ts#L829-L831

**Comment by CrossEye** [comment]
@GingerPlusPlus: Is that work publicly available now?  I'd love to take a look.

**Comment by GingerPlusPlus** [comment]
Not yet. I'll publish it and post a link here as soon as I get `map` fully working.

**Comment by GingerPlusPlus** [comment]
I fell down the rabbit hole when designing dispatching, so the library might take a while. Instead, here are typings for transducers (inspired by https://github.com/dphilipson/transducist/blob/master/src/types.ts):

```ts
interface Reduced<T> {
    readonly "@@transducer/reduced": true;
    readonly "@@transducer/value": T;
}

type MaybeReduced<T> = T | Reduced<T>;

interface Transformer<Input, Result, Complete = Result> {
    "@@transducer/init"(): Result;
    "@@transducer/step"(result: Result, input: Input): MaybeReduced<Result>;
    "@@transducer/result"(result: Result): Complete;
}

type Transducer<Input, Output> = <Result, Complete>(
    xf: Transformer<Output, Result, Complete>
) => Transformer<Input, Result, Complete>;
```
