### ISSUE TITLE
pick after applySpec picks keys with undefined value

### ISSUE THREAD

**Issue by kostenko** [ramda/ramda#2874]
Hello,

According to the documentation, `R.pick`
> Returns a partial copy of an object containing only the keys specified. If the key does not exist, the property is ignored.

However, if there is `R.applySpec` before — it affects its behaviour:

```
R.pipe(
  R.applySpec({
    foo: R.prop('foo'),
    bar: R.prop('bar'),
  }),
  R.pick(['foo', 'bar']),
  // R.pickBy(R.complement(R.isNil)), // workaround
)({ foo: 'FOO' })

// returns {"bar": undefined, "foo": "FOO"}
// expecting {"foo": "FOO"}
```

Here it's reproduced in [REPL](https://ramdajs.com/repl/#?R.pipe%28%0A%20%20R.applySpec%28%7B%0A%20%20%20%20foo%3A%20R.prop%28%27foo%27%29%2C%0A%20%20%20%20bar%3A%20R.prop%28%27bar%27%29%2C%0A%20%20%7D%29%2C%0A%20%20R.pick%28%5B%27foo%27%2C%20%27bar%27%5D%29%2C%0A%29%28%7B%20foo%3A%20%27FOO%27%20%7D%29)

**Comment by Bradcomp** [comment]
We can see what's happening here if we split up the two operations:

```
R.applySpec({
    foo: R.prop('foo'),
    bar: R.prop('bar'),
  })({foo: 'FOO'})

// {foo: 'FOO', bar: undefined}

R.pick(['foo', 'bar'])( {foo: 'FOO', bar: undefined} )

//The same as the input
```

So because `applySpec` actually _adds in_ the `bar` property, it's then picked up by `pick`.

If you're looking for something to remove properties if their value is `undefined` you could use `R.reject(isNil)(obj)`.

`reject will remove any item matching the predicate, which should take care of your edge case here.

**Comment by CrossEye** [comment]
`undefined` is such a strange value in JS.  If `null` was the [billion-dollar mistake][th], it is at least an understandable version of, "hey, we all know that there's no value here".  `undefined` is billion-shrug mistake: "hey, I dunno, we can pretend it's this value if you like..."


  [th]: https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions

**Comment by kostenko** [comment]
Oh, ok, I can see why I made a wrong assumption.
