### ISSUE TITLE
Filter used along with sortBy in pipe results in type error

### ISSUE THREAD

**Issue by vicrac** [ramda/ramda#2876]
Simple use case: filtering a list of objects and then sorting it by some property is crashing on types. I made the simplest possible reproduction (althought I had to bootstrap a whole Angular app for that, since Ramda REPL doesn't work with typescript and with typescript REPL one cannot add Ramda as dep): https://stackblitz.com/edit/angular-vwm9fc.

**Comment by Bradcomp** [comment]
Hi @vicrac 

Most of the Ramda team has little experience with TS, and the types are not maintained by any of the core team members.

You might have better luck figuring this out by checking with the people who maintain the typings.

**Comment by vicrac** [comment]
Hi @Bradcomp, thanks for redirection. I made a duplicated issue in DefinitelyTyped and I am closing the one in here. If interested, please check out the related issue (linked above).
