### ISSUE TITLE
Release 0.27.0 not published

### ISSUE THREAD

**Issue by MarcNq** [ramda/ramda#2879]
Hi guys,

We would like to use the 0.27.0 update because it solves the issue in #2771, but we realized it hasn't been published to NPM yet.
Is there any reason for it? Can we help in some way?

Thanks!

**Comment by Chypa74** [comment]
Hi guys,

I would like to use hasPath function from a master because it solves some issues with null and undefined, but 0.27.0 version hasn't been published to NPM.

When it will be published?

**Comment by krzepah** [comment]
Hello there, It might be a temporary fix but you should be able to install Ramda directly from GitHub

In your package.json 
```
{
  "dependencies" : {
     "ramda": "ramda/ramda#0.27.0"
   }
}
```

Well that's untested but you got the idea, I hope I'm not wasting your time :)

**Comment by kibertoad** [comment]
@CrossEye Are there any outstanding issues before 0.27.0 can be released?

**Comment by moroine** [comment]
Any update?

**Comment by jordie23** [comment]
@CrossEye @Bradcomp Any idea if 0.27 will be published to NPM? Or if there will be another release soon?

**Comment by CrossEye** [comment]
Somehow I wasn't seeing these messages.  I have some Ramda work to do over the next few days, and I will try to ensure that 0.27 publication is part of it.

**Comment by jordie23** [comment]
Thanks. We appreciate the effort you put in!

**Comment by kibertoad** [comment]
@CrossEye Sorry for another bump. Any status updates?

**Comment by CrossEye** [comment]
I tried to release it this past weekend and hit some snags.  If I don't get it in the next few days, I may just do another bump to 0.28.  I've mostly been focused on finally getting out 1.0.  But that's slow going.

**Comment by monotykamary** [comment]
@CrossEye I'm gravely concerned there's not a good amount of effort being put in - or it has become impossible to publish the next version.

**Comment by CrossEye** [comment]
Not impossible, but an incomplete publish really got in the way and made it difficult.  I *think* I got it right this time.

**Comment by char0n** [comment]
Is there some changelog for the 0.27.0 version ? Some document that would describe what has been changed, what has been added, what has  been fixed etc...

Thank you
