### ISSUE TITLE
Suggesting a new function to split an array into multiple at a given value

### ISSUE THREAD

**Issue by mudit56** [ramda/ramda#2881]
Several times while working with different data set, I felt the need for a function to do the partitions like below : 

[1, 2, 3 ,2, 4, 5, 2, 6, 7]  ( break at 2 ) ===>  [ [1] , [3] , [4,5] , [6,7] ]
[1, 2, 1]  (break at 2) ===> [ [1] ,  [1] ]
[1, 2, 1] (break at 1) ===> [ [2] ]

I have also worked on the same which also support whether to exclude or include the delimiter. I have followed the contribution guidelines, and willing to provide the PR.

**Comment by CrossEye** [comment]
I could definitely imagine including something like `splitWhenever` or something.

```hs
splitWhenever :: (a -> Bool) -> [a] -> [[a]]
```

Would you be interested in creating a PR for it?  No guarantees it would be accepted, but I promise at least a fair hearing.

**Comment by mudit56** [comment]
I have opened the PR as suggested.
