### ISSUE TITLE
R.ifElse not work in simple demo

### ISSUE THREAD

**Issue by lizy0329** [ramda/ramda#2886]
```javascript
R.ifElse(
  R.T(),
  R.identity(1),
  R.identity(2)
)(1)
// => First argument to _arity must be a non-negative integer no greater than ten
```

**Comment by CrossEye** [comment]
Well, it's not at all clear what you want to do with your simple demo, but you are definitely misusing the functions there.

All three arguments to `ifElse` should be *functions*.  You are writing the equivalent of `ifElse(true, 1, 2)`, which is meaningless to Ramda.  `identity` is a function which returns the value supplied to it, a surprisingly useful function at times, but not what you would want here.  `always` is a a function which accepts a value and returns a *function* which will return that value.

```js
const foo = R.ifElse(
  R.identity,
  R.always(1),
  R.always(2)
)

foo(true)  //=> 1
foo(false) //=> 2
```

or you could write

```js
const bar = R.ifElse(
  R.equals(42),
  R.always('the meaning'),
  R.always('huh?')
)

bar(42)  //=> "the meaning"
bar(10) //=> "huh?"
```

**Comment by lizy0329** [comment]
em...Actually, I am processing json data returned from the backend

like this: 

```
const ignoreField = [
  'company_name',
  'company_code',
  'company_business_license_img',
  'media_official_website'
];

const data = { company_name: 1, other_value: 'ho!ho!ho!', other_value2: 'gee!gee!gee!' }

const filterData = key => {
  return R.ifElse(
    R.includes(key),
    R.always(false),
    R.always(true),
  )(ignoreField)
}

const filterKeyFromData = R.filter(filterData)

R.compose(
  R.flip(R.pick)(data),
  filterKeyFromData,
  R.keys
)(data)
// => {"other_value": "ho!ho!ho!", "other_value2": "gee!gee!gee!"}
```
R.isElse function is easily make a mistaken for passing in incorrect params. Understood as R.isElse(true/false, value1, value2).

Thank for the explanation

**Comment by CrossEye** [comment]
@lizy0329: Can you suggest an improvement to the documentation which might make this error less likely?

**Comment by lizy0329** [comment]
Vue documentation is a best one to reference. It has clear api, more example and some warnning or error by people to use.

In this case, I think it should add wranning to underline the params for R.ifElse func.
