### ISSUE TITLE
prop, propOr and propOr documentation are inconsistent

### ISSUE THREAD

**Issue by Tworley96** [ramda/ramda#2887]
A previous issue (https://github.com/ramda/ramda/issues/2534) highlighted inconsistent behavior between propOr and pathOr. pathOr's behavior was applied to propOr. This change in behavior makes both the propOr documentation inconsistent with propOr's functionality and prop and propOr's functionality inconsistent. 

<br>

**Documentation Inconsistency**

Another previous issue (https://github.com/ramda/ramda/issues/2644) brought up the documentation inconsistency as a side point but was closed by the author once the main point was addressed. The documentation inconsistency point remains unaddressed. 

The documentation states:
> If the given, non-null object has an own property with the specified name, returns the value of that property.

As was brought up in the previous issue, 
>The wording "has own property" leads imo to the understanding that hasOwnProperty is actually used in the implementation.

hasOwnProperty returns true regardless of the value of the key, so long as the key is on the object

```javascript
 var data = { education: null }
 data.hasOwnProperty('education') // => true 
 R.propOr('default', 'education', data)// => 'default 
```

Given that data is not null and has 'education' as its own property, one would expect that propOr returns the value of the 'education' property of the object. Instead it returns the default, 'default'.

<br>

**prop Inconsistency**

One would logically expect prop and propOr to only differ in the case where the key is not on the object, however this is not the case. 

```javascript
 R.prop('education', data) // => null
 R.prop('education2', data) // => undefined
 R.propOr('default', 'education', data) // => 'default'
 R.propOr('default', 'education2', data) // => 'default'
```

propOr returns the same value in each of the two cases here, where prop treats each case differently and one would expect, based on the naming, that they would act on both cases in the same manner.

Both inconsistencies can be addressed by reverting the change made to propOr(and instead applying propOr's behavior to pathOr). If this is not desired behavior of the *Or functions, then the documentation should be updated to reflect the actual behavior of propOr and accept the differences between prop and propOr.

**Comment by CrossEye** [comment]
You're right, we're being contradictory here.  I personally prefer the documented behavior to the actual one.  Are you interested in creating a PR to fix it?

**Comment by Tworley96** [comment]
> You're right, we're being contradictory here. I personally prefer the documented behavior to the actual one. Are you interested in creating a PR to fix it?

Agreed, I prefer the documented behavior as well. I can a PR to fix it a shot.

**Comment by Tworley96** [comment]
After starting the pr, I would like to ask a follow up question about the following code.

```javascript
R.prop('default', education, { 'education': undefined })
```

Should the above snippet return undefined or 'default'? To me it seems like it should return 'default', but hasOwnProperty detects the 'education' key in the dictionary. If it were to return 'default', the documentation should be updated because hasOwnProperty does recognize keys with undefined values. If it returns undefined then the docs could be left alone.

**Comment by CrossEye** [comment]
I think the focus should not be on `undefined` versus other values but simply on whether the object has the particular key.  It would be nice to drop the talk of "own property" and just use "property", probably tested with `'foo' in bar`.

**Comment by Tworley96** [comment]
Made a pr here: https://github.com/ramda/ramda/pull/2888

**Comment by customcommander** [comment]
> I think the focus should not be on `undefined` versus other values but simply on whether the object has the particular key. It would be nice to drop the talk of "own property" and just use "property", probably tested with `'foo' in bar`.

@CrossEye: I think that makes sense but that doesn't seem how it works right now:

```javascript
/* v0.28.0 */

propOr('foo', 'x', {});
//=> 'foo'

propOr('bar', 'x', {x: undefined});
//=> 'bar'

propOr('baz', 'x', {x: null});
//=> 'baz'

propOr('bat', 'x', {x: NaN});
//=> 'bat'
```

This could possibly go in a `v1.0` release.
