### ISSUE TITLE
Functional deep learning?

### ISSUE THREAD

**Issue by bionicles** [ramda/ramda#2889]
Would it be possible to do functional deep learning like Jax / Stax / jaxnet using ramda?

Who’s interested / how do we do this easily?

**Comment by CrossEye** [comment]
Is there something specific you're trying to do?  I don't know the Python AI implementations.  What would you like to do in JS, and how do you think Ramda might help?

**Comment by bionicles** [comment]
Most AI frameworks are heavily object oriented and mutate all the things. It gets annoying and I reckon functional neural net api would be easier to develop and debug

**Comment by CrossEye** [comment]
@bionicles: I imagine it would be nicer to debug.  But of course one of the places where OO performance shines is when there are many parts with the same API but different data, like a network of neurons, I would imagine.

I'd be curious to watch how progress might be made in this.  I imagine there are Haskell NN implementations that might serve as inspiration, or at least as a guide to efficient data structures.

But I doubt I'd get involved at the moment, as I have too much on my plate.
