### ISSUE TITLE
R.splitEvery() returning 2 chunks instead of 44

### ISSUE THREAD

**Issue by flcli** [ramda/ramda#2891]
I have an array of 2163 objects of this shape:
```js
{
  foo: { ... },
  bar: { ... }
}
```

I'm calling `splitEvery` like this:
```js
R.splitEvery( 50, theArray )
```

Expected output:
A new array of 44 elements, each of which is a chunk of 50 elements from the initial array.

Actual output:
A 2 element array. The first element is a chunk of 50 elements from the initial array. The second element is the remaining 2113 elements from the initial array.

Any ideas?

**Comment by CrossEye** [comment]
@flcli: Did you solve this?  What was the issue?

It seems to work correctly for me:

```js
const randNbr = () => Math.floor(Math.random() * 5) + 1
const data = R.times(() => ({foo: randNbr(), bar: randNbr()}), 2163)
const res = R.splitEvery(50, data)

res.length     //=> 44

res[0].length  //=> 50
res[2].length  //=> 50
res[3].length  //=> 50
// ...
res[42].length //=> 50
res[43].length //=> 13
```

**Comment by sdenni** [comment]
sory @flcli , how did you resolve this problem, I opened new issue on https://github.com/ramda/ramda/issues/3040

thx
