### ISSUE TITLE
R.useWith(Math.pow, [R.identity, R.identity])(3, 4) not work in Try ramda

### ISSUE THREAD

**Issue by VictorSoroka1** [ramda/ramda#2896]
Example from the documentation is not working in [repl](https://ramdajs.com/repl). However, it works okay in [jsfiddle](https://jsfiddle.net/viktor_s/7hwLjvc0/4/).

**Comment by rferromoreno** [comment]
I had just tried your example in [repl](https://ramdajs.com/repl/#?R.useWith%28Math.pow%2C%20%5BR.identity%2C%20R.identity%5D%29%283%2C%204%29) and I see it works fine.

![Untitled](https://user-images.githubusercontent.com/5116187/65657280-1beedb00-dff9-11e9-8a3b-a42e283960af.png)

Which browser/version are you using? Do you have any messages in your browser's console? Which Ramda version is running in the REPL?

**Comment by VictorSoroka1** [comment]
Now everything works, before it it was an error kind of `u(t)` string or something like this.
