### ISSUE TITLE
would it be possible to search docs from https://ramdajs.com/ ?

### ISSUE THREAD

**Issue by bionicles** [ramda/ramda#2907]
hi, right now you have to click on "docs" to begin a search for a function

 rom a  "functional" perspective (no pun intended), to be frictionless,
 would it be possible to search docs directly from https://ramdajs.com/ ?

also, just imagine we include the cookbook in the search, maybe below a divider, so people can learn / refer faster to this library, i think it might help us move fast (and not die slow)

**Comment by CrossEye** [comment]
Sorry, I missed this when it was posted, and only saw in now during a cleanup.

This sounds like a pretty good idea.  I'm all ears for a suggested implementation, or, even better, a pull request.

**Comment by bionicles** [comment]
Thanks, I realized it’s a super minor issue and we should probably focus on higher yield things. Might be pretty easy but I’m not up to speed on the codebase

**Comment by Bradcomp** [comment]
I think at least linking to the cookbook in the docs would be a great idea
