### ISSUE TITLE
Why "take" behaves that way?

### ISSUE THREAD

**Issue by makarkotlov** [ramda/ramda#2910]
I don't get why `take` in this case
![Снимок экрана 2019-10-31 в 16 53 35](https://user-images.githubusercontent.com/32848434/67953034-61f21c80-fbff-11e9-8b4a-64144c0f3e02.png)
will produce that result
![Снимок экрана 2019-10-31 в 16 53 41](https://user-images.githubusercontent.com/32848434/67953050-6ae2ee00-fbff-11e9-9394-a79760be4b8a.png)
instead of
![Снимок экрана 2019-10-31 в 16 55 42](https://user-images.githubusercontent.com/32848434/67953058-70d8cf00-fbff-11e9-8b3b-71b93b28f6e3.png)
Is it the right behavior?

**Comment by Bradcomp** [comment]
@makarkotlov If you'd like to return the first element, try `head`.

**Comment by makarkotlov** [comment]
Thank you!
