### ISSUE TITLE
[Feature request] R.update like function to update nested arrays

### ISSUE THREAD

**Issue by GCrispino** [ramda/ramda#2911]
Hello you all. I was using R.update to update arrays but for some use cases I had to generalize it to update nested arrays as well, by passing multiple indexes. For example:
```javascript
const R = require('ramda');

const props1 = [1, 2, 3];
const props2 = [[1, 2, 3], 4, 5, 6];
const props3 = [[[1, 2, 3]], 4, 5,6];

// "update" is my custom function

console.log(update(5, props1, 1)); // [1, 5, 3]
console.log(update(5, props2, 0, 2)); // [[1, 2, 5], 4, 5, 6]
console.log(update(5, props3, 0, 0, 1));  // [[[5, 2, 3]], 4, 5, 6]
```

I think it can be a rather common use case and it would be an useful function. I can also work on a PR for this, I'd just want to know if it would fit the library standards.

Cheers!

**Comment by CrossEye** [comment]
Just getting back to Ramda after some time away...

I think Ramda already has two alternatives that would work for you.

  - `assocPath` works with arrays as well as objects:

    ```js
    const props1 = [1, 2, 3];  
    const props2 = [[1, 2, 3], 4, 5, 6];
    const props3 = [[[1, 2, 3]], 4, 5,6];

    assocPath ([1], 5, props1)        //=> [1, 5, 3]
    assocPath ([0, 2], 5, props2)     //=> [[1, 2, 5], 4, 5, 6]
    assocPath ([0, 0, 1], 5, props3)  //=> [[[1, 5, 3]], 4, 5, 6]
    ```

  - `lenses` offer a more general way to focus on a particular node to get, set, or update the value:

    ```js
    view (lensPath ([1]), props1)            //=> 2
    set (lensPath ([0, 2]), 5, props2)       //=> [[1, 2, 5], 4, 5, 6]
    over (lensPath ([0, 0, 1]), inc, props3) //=> [[[1, 3, 3]], 4, 5, 6]
    ```

Would one of those do it for you?

**Comment by GCrispino** [comment]
Yes! Sorry, but I did not know that assocPath could do this... I am gonna close the issue. Thanks!
