### ISSUE TITLE
Share button in ramda REPL not working

### ISSUE THREAD

**Issue by bliotti** [ramda/ramda#2913]
The share button in ramda's REPL is not working. It used to give me a short link.

**Comment by Bradcomp** [comment]
Hi @bliotti!

This is a known issue. goo.gl shut down and we currently haven't set up an alternative.

https://github.com/ramda/repl/issues/61

**Comment by CrossEye** [comment]
... and we'd gratefully accept contributions from someone who's worked with one of these shorteners!

**Comment by IMHOJEONG** [comment]
I tried adding a feature once.
https://github.com/ramda/ramda.github.io/pull/226

**Comment by CrossEye** [comment]
@IMHOJEONG: What does that Facebook link have to do with the shortener?  Does Facebook present its own shortener?  I'm confused.

**Comment by IMHOJEONG** [comment]
The share button didn't work, 
so I don't know in detail whether facebook provides a shortener, 
but I tried using the share link provided by facebook.
https://stackoverflow.com/questions/9120539/facebook-share-link-without-javascript

**Comment by CrossEye** [comment]
Ahhh, this was not a social media-style sharing feature, at least not directly.  It used a now-defunct URL shortening API to take our long URL and create one useful for posting here or in help forums (or on Twitter/Facebook/etc.)  Google has shut down https://goo.gl, and we need to find another one to work with.  It's just not become a priority for anyone from the team.

**Comment by VasiliKubarka** [comment]
Hello, please, can you provide status of solving this issue?
why don't to use services recommended by google:
https://bitly.com/a/your_new_home
https://hootsuite.com/pages/owly

**Comment by zehua** [comment]
Fixed. Give it a try 😄

**Comment by bliotti** [comment]
> Fixed. Give it a try 😄

Thanks!    https://tinyurl.com/y43jhpoc
