### ISSUE TITLE
Should DefinitelyTyped Typescript types be referenced on README.md?

### ISSUE THREAD

**Issue by estaub** [ramda/ramda#2918]
I know nothing technically about the two typing options, but the [npm-ramda types haven't been updated in over a year](https://github.com/types/npm-ramda/graphs/contributors), whereas there are [several active contributors to the DefinitelyTyped types](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/ramda/index.d.ts).

There's also a bigger backlog of issues for types/npm-ramda, but that can easily be misleading.

The [Ramda README](https://github.com/ramda/ramda#typings) currently references the inactive npm-ramda types.  A few years ago these were thought to be better than the DefinitelyTyped types.  I'm wondering if it should reference the DefinitelyTyped types instead, or perhaps reference both with some guidance to when each is the better choice.

I'm hoping someone with more knowledge will comment.

**Comment by CrossEye** [comment]
@estaub: 
If you are interested in creating a PR for the README on this, we'd love to see it.  I'm afraid the Ramda core team includes no one particularly versed in Typescript or its typing files.  (I personally don't even know anything about the two organizations you discuss, never mind their technical merits.)

**Comment by estaub** [comment]
@CrossEye Thanks, I will if and when I know more on the merits of the typings themselves.

@tycho01 , @ikatyang , @pirix-gh, @RyanCavanaugh, @imcotton - any thoughts?  Anyone else I should ping?

**Comment by pirix-gh** [comment]
You are right, **DefinitelyTyped** is the new place for ramda typings. For my part, I mostly worked on providing precise types for **curry**, **flatten**, and **merge** family functions. **npm-ramda** will probably not have updates any longer, and you can consider it as archived. 

So yes, you can update the README.

**Comment by tycho01** [comment]
Apologies I hadn't updated this before.
I may have put in this link originally, but  agree that the official DefinitelyTyped have surpassed the npm-ramda ones, as @pirix-gh attested.
