### ISSUE TITLE
uncurryN returns a ramda style curried function from a standard curried function?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#2921]
```js
const addFour = a => b => c => d => a + b + c + d;
const uncurriedAddFour = R.uncurryN(4, addFour);
uncurriedAddFour(1, 2, 3, 4); //=> 10
```

This also works:
```js
uncurriedAddFour(1, 2, 3)(4); //=> 10
```

Should this function add some additional explanation like "Note that, the returned function is an n-ary ramda style curried function" ?

**Comment by CrossEye** [comment]
Yes, that would be an improvement.  Do you want to create a PR or should I do it?

**Comment by adispring** [comment]
OK, I will create a PR.
