### ISSUE TITLE
feat: whereAny

### ISSUE THREAD

**Issue by hitmands** [ramda/ramda#2923]
### Feature Request
Implement `whereAny` as opposite of `where`.

### Motivation
Ramda has a lot of complementary apis, such as `allPass` and `anyPass`, but `where` feels like it's missing its counterpart.
as stated in the doc:
> `where` returns true if all the predicates return true, false otherwise. 

but we don't have an api that, given a spec object, returns `true` if at least one of the predicates returns true.

### Use Case
Let us build a simple search of a list of users:
```typescript
const users = [
  { name: 'Giuseppe', surname: 'Mandato' },
  { name: 'Jimi', surname: 'Hendrix' }, 
  { name: 'Freddie', surname: 'Mercuri' }, 
];

const find = (value) => R.whereAny(
  name: R.equals(value),
  surname: R.equals(value), 
);

R.filter(find('Giuseppe'), users);
// [ { name: 'Giuseppe', surname: 'Mandato' } ]


R.filter(find('Charles'), users);
// []
```

### Alternatives
1. we could enhance the `anyPass` api to also take a spec object, but this would then be in contrast with `allPass`

### Notes
**I'd love to provide a pull request** to implement this api if it'd be of interest.

### Resources
 - [`where`](https://ramdajs.com/docs/#where)
 - [`allPass`](https://ramdajs.com/docs/#allPass)
 - [`anyPass`](https://ramdajs.com/docs/#anyPass)

**Comment by CrossEye** [comment]
:+1:

This sounds like a good idea.  I agree that this is better as a separate function than as an extension to `anyPass`.  I'd love to see a PR.

Also, thank you very much for a well-written and clear feature request!
