### ISSUE TITLE
addIndex on reduceWhile, provide index to both predicate and iterator?

### ISSUE THREAD

**Issue by karlmacklin** [ramda/ramda#2931]
Hi, beginner question here.

I find myself in a situation where I want to wrap reduceWhile in addIndex. I want to access the index in *both the predicate and iterator function*.
I know I can flip() reduceWhile to choose the other one if I so please, but I need it in both.

Can this be solved with some existing ramda function I've missed?

If you're curious, I'm doing advent of code 2019, day 2 part 1. That's the scenario where I need this to work.
Contrived example, perhaps, but my challenge is to solve it as ramda-functional as possible.

**Comment by CrossEye** [comment]
No, I don't think Ramda has anything particularly helpful here.  I certainly have never thought about that before.

I'd be interested to see how that would help you with the problem.  I solved it recursively, and it seemed fairly simple, straightforward code.

**Comment by karlmacklin** [comment]
Actually I had an extra self imposed restriction on that challenge - don't use recursion. Overly complicating it most likely.

**Comment by Bradcomp** [comment]
@karlmacklin  it might help to `zip` the indexes and values together then `reduceWhile` over the pairs.

If you run into more issues it might help to look into the Ramda [chat room](https://gitter.im/ramda/ramda) which might get you help a bit faster, or get you more input.

**Comment by CrossEye** [comment]
Here is an only-slightly tested version:

```js
const addIndices = (fn) => (...args) => fn (... [
  ... init (args) .map (
    arg => is (Function, arg) 
      ? (...args) => arg (...[...args.slice(0, -1), ...args[args.length - 1]])
      : arg
  ),
  zip (last (args), range(0, args .length))
])


addIndices (reduceWhile) (
  (a, x, i) => x <= i,
  (a, x, i) => `${a} (${x}:${i})`,
  'start',
  [0, 0, 1, 2, 9, 4]
)
//=> "start (0:0) (0:1) (1:2) (2:3)"
```

It might also be cleaner to abstract something like

```
const spreadLast = (fn) => (...args) => 
  fn (...[...args.slice(0, -1), ...args[args.length - 1]])
```

and replace 

```js
    arg => is (Function, arg) 
      ? (...args) => arg (...[...args.slice(0, -1), ...args[args.length - 1]])
      : arg
```

with 

```js
      arg => is (Function, arg) 
        ? spreadLast (arg) 
        : arg
```

This assumes that all function parameters need to be updated.  I can't think of a better alternative, but as with `R.addIdx`, that is problematic in the general case.
