### ISSUE TITLE
Questions about _XAperture.js

### ISSUE THREAD

**Issue by 152dyn** [ramda/ramda#2936]
> ```js
>  _XAperture.js
> 
>  XAperture.prototype.getCopy = function() {
>   return _concat(Array.prototype.slice.call(this.acc, this.pos),
>     Array.prototype.slice.call(this.acc, 0, this.pos)
>   );
> };
> ```
> 
> **Question**: What is the purpose of the following writing？
> 
> ```js
> return _concat(Array.prototype.slice.call(this.acc, this.pos), Array.prototype.slice.call(this.acc, 0, this.pos)
> ```
> 
> Why not:
> 
> ```js
> return Array.prototype.slice.call(this.acc, this.pos)
> ```

**Comment by CrossEye** [comment]
Sorry, I missed this when it was posted and only noticed it now when doing some cleanup.

Well, those two snippets do different things.  Have you tried running it with your change?
