### ISSUE TITLE
is it possible that `propEq` receives 'lensProp' as the first argument?

### ISSUE THREAD

**Issue by jabbla** [ramda/ramda#2942]
now i have the code below:
```js
const tagTypeLens = R.lensProp('_tagType');
const lensEq = lens => value => target => R.equals(R.view(lens, target), value);
const isNumberType = lensEq(tagTypeLens)('number');
```
can i use ``propEq`` with ``lensProp`` like this?
```js
const tagTypeLens = R.lensProp('_tagType');
const isNumberType = R.propEq(tagTypeLens, 'number');
```
i think the ``lens`` related apis could be very powerful, they could use with any ``prop``, ``path`` related apis. 

does it make sense?

**Comment by CrossEye** [comment]
I'm afraid I don't see how that would work.  Do you have a suggested implementation?  Lenses are [complicated beasts][le], and don't seem to share any common abstraction with the Strings that serve as the input to `propEq`.

I might write this as 

```js
const lensIs = curry((type, lens, value) => is (type) (view (lens, value)))
const obj = {foo: 'abc', bar: 42, baz: {}}
lensIs (Number) (lensProp('foo')) (obj) //=> false
lensIs (Number) (lensProp('bar')) (obj) //=> true
```

I feel that the tools you want are there and just need to be combined.  Am I missing something?


  [le]: https://github.com/ramda/ramda/blob/v0.26.1/source/lens.js

**Comment by jabbla** [comment]
Thanks for your reply. 

You were right!

Is it possible that ``lensEq``, ``lensIs``,``lensSatisfies`` become ramda's APIs in the future?

**Comment by CrossEye** [comment]
@jabbla: 

>Is it possible that `lensEq`, `lensIs`, `lensSatisfies` become ramda APIs in the future?

Feel free to raise a PR for that if you like.  I don't know what other core members would think, but I would need some convincing that these are general-purpose enough to include.

**Comment by jabbla** [comment]
@CrossEye
