### ISSUE TITLE
Cannot pass object with a tail method to tail function

### ISSUE THREAD

**Issue by zlydenko** [ramda/ramda#2947]
> Returns all but the first element of the given list or string (**or object with a tail method**).

```
const tailTest = {
  head: [1],
  tail: () => [2, 3]
};
```

I'm receiving typescript error:

> No overload matches this call.
  Overload 1 of 2, '(list: string): string', gave the following error.
    Argument of type '{ head: number[]; tail: () => number[]; }' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(list: readonly any[]): any[]', gave the following error.
    Argument of type '{ head: number[]; tail: () => number[]; }' is not assignable to parameter of type 'readonly any[]'.
      Type '{ head: number[]; tail: () => number[]; }' is missing the following properties from type 'readonly any[]': length, concat, join, slice, and 16 more.ts(2769)

Next time, I tried some list class:

```
class TestList<T> extends Array {
  private head: T;
  private tail2: Array<T> = [];

  constructor(a: Array<T>) {
    super();
    this.head = a[0];
    this.tail2 = a.slice(1);
  }

  public tail(): Array<T> {
    return this.tail2;
  }
}
const tailTest = new TestList<number>([1, 2, 3]);
```

Received no error (maybe because I'm extending Array class, but result is empty array.
Maybe I didn't fully understand what documentation said about **object with a tail method** or i do something wrong. le help

**Comment by CrossEye** [comment]
I'm afraid that this is a combination of problems.  In the first case, I think you're dealing with an issue of the Typescript typing file you're using.

This plain JS version works fine:

```js
const tailTest = {
  head: [1],
  tail: () => [2, 3]
};

tail(tailTest) //=> [2. 3]
```

The Ramda team does not maintain these Typescript files.  You would need to check with its maintainers.

The second issue is fairly fundamental.  Ramda provides an implementation of `tail` for arrays.  It delegates for other objects that have a `tail` method.  But your array extension object **is** an array, so it passes the first test and uses the Ramda array implementation.

While it sounds as though we could test for an object method first, this would fail in the general case.  We do not, for instance, want `R.map` to delegate to `Array.prototype.map`.  I don't see any great way to resolve that.

(A side note: I am slowly working on another library, which I'm not nearly ready to share.  That one does not delegate to *methods* at all, but allows you to tell it about your type, giving *functions* which apply to it as well as a membership predicate and its place in any hierarchy.  That library would not have the current issue -- but I can't see that ever folding into Ramda.)

**Comment by zlydenko** [comment]
Thanks! Tested in pure js and works fine. Probably need to contact @types/ramda team.
