### ISSUE TITLE
Cloning a readonly object gives error assigning to non immutable type ?

### ISSUE THREAD

**Issue by iangregsondev** [ramda/ramda#2948]
Hi,

I have a readonly array that is passed in as readonly, i tried to use clone but I get the following error

```
The type 'readonly SomethingElseEntity[]' is 'readonly' and cannot be assigned to the mutable type '{ id: number; }[]'.
```

Am I using it correctly ?

I would like to continue passing in the readonly "SomethingElseEntity" otherwise I have a eslint plugin that complains because its not immutable. I believe this is the correct functionality.

Here is my function

```
    getSomethingElseSuccess: (mutable_state, action: PayloadAction<readonly SomethingElseEntity[]>) => {
      mutable_state.loaded = true
      mutable_state.entities = clone(action.payload) // HERE IS THE ISSUE
    },
```

![image](https://user-images.githubusercontent.com/2370364/71570506-b1f14080-2ad5-11ea-9bd2-4fd2496f0d30.png)

So although I am cloning it to make it a new object it seems to retain the readonly properties

Any ideas ?

**Comment by Bradcomp** [comment]
Hi @iangregsondev 

I think this may be a problem with the Ramda Typescript files and not Ramda itself. It looks like `clone` is typed to return the same data type as it receives, probably meaning the `readonly` part is being cloned too (virtually of course).

You may want to look into @types/Ramda to see if they can help, or else maybe put an explicit type on `clone` or cast as mutable if you can do that in TS.

**Comment by iangregsondev** [comment]
Thanks, @Bradcomp , yes, in the end, I just did a spread operator of any array - which creates a new array. I will take a look closer at the types. Thanks for your help.
