### ISSUE TITLE
Partial Builds

### ISSUE THREAD

**Issue by philipjrosen** [ramda/ramda#2950]
On the Ramda home page it says that you can create a partial build by doing

`npm run --silent partial-build compose reduce filter > dist/ramda.custom.js`

this runs the script `"partial-build": "node ./scripts/partialBuild"` in package.json

However, there is no  scripts folder or partialBuild script in the node_modules/ramda directory.

How can I do a partial build of Ramda?

**Comment by CrossEye** [comment]
That was never exposed in the NPM publication, as we didn't think it was important there.  If there is a real need, we could certainly discuss it.  But if you clone the repo from GitHub, it should still work.

**Comment by philipjrosen** [comment]
Thanks, I'll give that a shot.
