### ISSUE TITLE
R.evolve transforming unmentioned keys.

### ISSUE THREAD

**Issue by JAForbes** [ramda/ramda#2953]
Hey I noticed some strange behaviour on 0.26.1

Expected: 

```js
R.map( R.evolve({ deploys: x => x })) ({ version: 4, deploys: {}, workspace: "hello" })
//=> { version: 4, deploys: {}, workspace: "hello" }
```

Actual: 

```js
R.map( R.evolve({ deploys: x => x })) ({ version: 4, deploys: {}, workspace: "hello" })
{ version: {}, deploys: {}, workspace: { '0': 'h', '1': 'e', '2': 'l', '3': 'l', '4': 'o' } }
```

The docs say:

> A transformation function will not be invoked if its corresponding key does not exist in the evolved object.

So I'm a little surprised `version` and `workspace` are altered at all.

**Comment by adispring** [comment]
Because `R.evolve` can only accept Object and Array, `4` and "hello" is primitive JS value and String.

**Comment by JAForbes** [comment]
Ahh you're right it was that errant map! Thanks @adispring 

My real code was traversing several layers and only evolving at the final step and for some reason when creating a repro I kept the `map`.
