### ISSUE TITLE
Feature suggestion: SatisfyOr

### ISSUE THREAD

**Issue by dr3** [ramda/ramda#2954]
While doing some refactoring I thought this function would be very helpful, if theres already a good alternative please let me know, as I could find one.

```js
satisfyOr(10, v => v > 5, 12) // 12
satisfyOr(10, v => v > 5, 3) // 10
satisfyOr([1,2,3], v => !isEmpty(v), []) // [1,2,3]
satisfyOr([1,2,3], v => !isEmpty(v), [4,5,6]) // [4,5,6]
```
You could also then simply have a `satisfy` function.

**Comment by adispring** [comment]
`when` and `unless` may be what you need

**Comment by dr3** [comment]
@adispring I was trying to rewrite 
```js
const orange = 'abcd';

const value =
    pear[orange] &&
    pear[orange].banana &&
    pear[orange].banana.length
      ? pear[orange].banana
      : apple;
```
as
```js
const orange = 'abcd';

const value = satisfyOr(
  apple, 
  x => x && x.length, 
  path([orange, 'banana']], pear)
)
```

But I cant see how I would use `when` and `unless` without having to declare a new const or duplicating?

**Comment by dr3** [comment]
@adispring I was trying to rewrite this
```js
const orange = 'abcd';

const value =
    pear[orange] &&
    pear[orange].banana &&
    pear[orange].banana.length
      ? pear[orange].banana
      : apple;
```
and though this would be nice
```js
const orange = 'abcd';

const value = satisfyOr(
  apple, 
  x => !isEmpty(x), 
  path([orange, 'banana']], pear)
)
```

But I cant see how I would use `when` and `unless` without having to declare a new const or duplicating?

**Comment by CrossEye** [comment]
I think what @adispring was suggesting is that this is very close to the `when`/`unless` behavior:

```js
unless(n => n > 5, always(10)) (12)          //=> 12
unless(n => n > 5, always(10)) (3)           //=> 10
when(isEmpty, always([1, 2, 3])) ([])        //=> [1, 2, 3] 
when(isEmpty, always([1, 2, 3])) ([4, 5, 6]) //=> [4, 5, 6] 
```

The difference is that `when` and `unless` -- like their `ifElse` cousin -- take a function rather than a scalar value.  This is more flexible, but for this case requires wrapping them up as `always(10)` or `() => 10`.

Does that do what you need?

**Comment by dr3** [comment]
@CrossEye Ah interesting, thanks that works, these both (would) do the same :)

```
const value = satisfyOr(
  apple, 
  x => !isEmpty(x), 
  path([orange, 'banana']], pear)
)
```

```
when(isEmpty, always(apple))(
    path([orange, 'banana'], pear)
);
```

**Comment by adispring** [comment]
> ```
> when(isEmpty, always(apple))(
>     path([orange, 'banana'], pear)
> );
> ```

Maybe composing functions to pipeline is more elegant? And the new pipeline can be composed continuously.

```
const getOrangeBananaOrApply = R.compose(
  R.when(isEmpty, always(apply)),
  R.path([orange, 'banada'])
)
```
