### ISSUE TITLE
Typo in tryCatch documentation

### ISSUE THREAD

**Issue by jonhallur** [ramda/ramda#2957]
https://brians.wsu.edu/2016/05/31/catched/

"catched" should be "caught"

**Comment by CrossEye** [comment]
I wonder how that snuck through.  Do you want to create a quick PR to fix it?

**Comment by B1Z0N** [comment]
does anybody closing it?

**Comment by CrossEye** [comment]
It was fixed in #2968.  The documentation will be updated the next time the library is published.
