### ISSUE TITLE
R.match with capturing groups and global flag (g)

### ISSUE THREAD

**Issue by Cottin** [ramda/ramda#2964]
Extracting capturing groups from regex can be done using `R.match` like so:
```
R.match(/(\w+):\s(\w+)/, 'name: Anna');
// returns [..., "name", "Anna", ... ]
```
[REPL-link](https://ramdajs.com/repl/?v=0.26.1#?R.match%28%2F%28%5Cw%2B%29%3A%5Cs%28%5Cw%2B%29%2F%2C%20%27name%3A%20Anna%27%29%3B
)

But when doing the same thing with the global flag, capturing groups are not longer in the result:
```
R.match(/(\w+):\s(\w+)/g, 'name: Anna, name: Stina');
// returns ["name: Anna", "name: Stina"]
```
i.e. the returned result above is only the full result, not the result of the capturing groups.
[REPL-link](https://ramdajs.com/repl/?v=0.26.1#?R.match%28%2F%28%5Cw%2B%29%3A%5Cs%28%5Cw%2B%29%2Fg%2C%20%27name%3A%20Anna%2C%20name%3A%20Stina%27%29%3B)

If we did this using "raw" javascript, ie. the `exec` function of a `RegExp`-object we'd get the full result **as well as** the capturing groups results:
[Online regex editor with results](https://regex101.com/r/TtjUOR/1)
Eg. using this code:
```
const regex = /(\w+):\s(\w+)/g;
const str = `name: Anna, name: Stina`;
let m;

while ((m = regex.exec(str)) !== null) {
    // This is necessary to avoid infinite loops with zero-width matches
    if (m.index === regex.lastIndex) {
        regex.lastIndex++;
    }
    
    // The result can be accessed through the `m`-variable.
    m.forEach((match, groupIndex) => {
        console.log(`Found match, group ${groupIndex}: ${match}`);
    });
}
// Result:
// "Found match, group 0: name: Anna"
// "Found match, group 1: name"
// "Found match, group 2: Anna"
// "Found match, group 0: name: Stina"
// "Found match, group 1: name"
// "Found match, group 2: Stina"
```
[Code generated at regex101.com](https://regex101.com/r/TtjUOR/1/codegen?language=javascript)

Is there anyway of getting the result of the capturing groups when using `R.match` with the global flag?

My workaround is to implement a `matchG` function like so:
```
# CoffeeScript
matchG = curry (re, str) ->
	res = []
	reG = new RegExp re.source, re.flags + test(/g/, re.flags) && '' || 'g'
	while (m = reG.exec(str)) != null
		# This is necessary to avoid infinite loops with zero-width matches
		if m.index == reG.lastIndex
			reG.lastIndex++
		# The result can be accessed through the `m`-variable.
		lastGroupIndex = 999
		m.forEach (match, groupIndex) ->
			if groupIndex < lastGroupIndex then res.push []
			res[res.length-1].push match
			lastGroupIndex = groupIndex
	return res


```
e.g.
```
matchG(/(\w+):\s(\w+)/g, 'name: Anna, name: Stina')
// returns [
//    [ 'name: Anna', 'name', 'Anna' ],
//    [ 'name: Stina', 'name', 'Stina' ]
//  ]
```
Note the result from matchG above has for each match the full result **AND** the result of each capturing group.

Is this `matchG` workaround needed or can I achieve this result using Ramda in some other way?

**Comment by CrossEye** [comment]
Ramda does not offer anything like this.  `match` is meant to mimic `String.prototype.match`, and it does so by defaulting to it, only replacing the possible `null` output with an empty array for consistency.

Feel free to propose your function for inclusion in Ramda with a pull request if you like.  I promise a fair hearing.  But my initial response would be negative.  JS regular expressions are inherently stateful and `exec` has a [fairly complex][ex] API that doesn't feel like a good match with Ramda's focus on simplicity.


  [ex]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#Description

**Comment by Cottin** [comment]
Thanks a lot for the explanation!
I tried out `String.prototype.match` and realise that's just how it behaves.
I guess most people using `R.match` is just thinking of it like mimicing that function and not like me that thinks it should handle the essentials of what regex.`exec` does...

I agree, it's probably not a common use case enough / easy to create a simple API-enough to include.

I'll put `matchG` in [ramda-extras](https://github.com/Cottin/ramda-extras) like I've done before ;)
