### ISSUE TITLE
Return type of propSatisfies/pathSatisfies does not correspond the docs

### ISSUE THREAD

**Issue by Shastel** [ramda/ramda#2966]
According to docs, these functions should return Bool
```
 * Returns `true` if the specified object property satisfies the given
 * predicate; `false` otherwise. You can test multiple properties with
```
```
 * Returns `true` if the specified object property at given path satisfies the
 * given predicate; `false` otherwise.
```

But according to implementation they just applying given pred to prop or path. 
For my case, it is unexpected to see, for [example](https://ramdajs.com/repl/#?R.pathSatisfies%28R.length%2C%20%5B%27some%27%2C%20%27nested%27%2C%20%27array%27%5D%2C%20%7B%7D%29):
```js
R.pathSatisfies(R.length, ['some', 'nested', 'array'], {}) // will return NaN
```

Could you please tell me is it an intentional feature or an issue in docs/implementation?

**Comment by adispring** [comment]
`R.pathSatisfies` first argument's signature is `a → Boolean`, but `R.length` is not a predicate function, its signature is `[a] → Number`.
