### ISSUE TITLE
partialRight with partially applied objects not working

### ISSUE THREAD

**Issue by aecorredor** [ramda/ramda#2967]
Hey guys, I'm having this weird issue:

```js
const options = { sayHi: () => 'hi' };
const mapFunction = (item, { sayHi }) => {
  console.log(`${item} says ${sayHi()}`);
}

mapFunction('test', options);
// "test says hi"

const partiallyAppliedMapFunction = partialRight(mapFunction, [options]);
partiallyAppliedMapFunction('ramda');
// "ramda says hi"

['foo', 'bar'].map(partiallyAppliedMapFunction);
// "Error: sayHi is not a function"
```

I'm expecting this to work, but `sayHi` is undefined when using `partialRight`. Am I missing something? 

Thanks!

**Comment by aecorredor** [comment]
So yeah...obviously map takes a function whose second argument is the `index`, so that overrides the partially applied argument. That's what's happening.

**Comment by CrossEye** [comment]
One of the main differences between `Array.prototype.map` and `R.map`!

Glad you figured it out!
