### ISSUE TITLE
then.js file missing in version 0.27

### ISSUE THREAD

**Issue by dpinart-uxland** [ramda/ramda#2969]
I just updated to 0.27 version from npm and it seems that then.js file is missing, so... there's no then function and I'm getting several errors when running my app.

**Comment by haakenlid** [comment]
I think it was renamed to `andThen`, but I don't know if there's a changelog published.

https://github.com/ramda/ramda/pull/2772

**Comment by CrossEye** [comment]
I will try to get the changelog out tomorrow.

**Comment by alexpanchuk** [comment]
`Otherwhise` documentation also relies on `then` in example and contains a broken link to it

**Comment by adispring** [comment]
> `Otherwhise` documentation also relies on `then` in example and contains a broken link to it

This will be fixed in the next publish: https://github.com/ramda/ramda/pull/2963/files

**Comment by customcommander** [comment]
Checked the doc and seems to be fixed. Closing for now.
