### ISSUE TITLE
extend R.evolve functionality

### ISSUE THREAD

**Issue by allexysleeps** [ramda/ramda#2972]
HI, Ramda team. 
I often need a method similar to evolve, but it to be able to get all object fields instead of the field value.

i.e. 

```
R.evolveFull({
 a: R.prop('b'),
 b: R.prop('c'),
 c: R.always('')
})({ a: 1, b: 2, c: 3})
```

We could add the whole object as a second argument to the function or create a new method.

I would be happy to develop it myself. 

Also, it might happen that such function already exists, and I just couldn't find it. Happened to me before, I tried to reinvent R.applySpec :) In this case, sorry for the bothering :)

**Comment by adispring** [comment]
Maybe you need `R.applySpec`.

**Comment by allexysleeps** [comment]
@adispring  in R.applySpec, you need to define all fields.
In my case, I need to change several fields and keep other fields untouched.

This how I'm doing it right now:

```
const srcObject = {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5,
  f: 6,
}

const updObject = R.mergeRight(srcObject, R.applySpec({
  a: ({ a, b}) => a + b,
  b: R.prop('c'),
  c: R.always(null)
})(srcObject))

 // updObject  === {"a": 3, "b": 3, "c": null, "d": 4, "e": 5, "f": 6}
```

**Comment by adispring** [comment]
Try this:

```js
R.converge(R.mergeRight, [R.identity, R.applySpec])
```
or
```js
R.chain(R.mergeLeft, R.applySpec({ ... }))
```

**Comment by allexysleeps** [comment]
@adispring  I'll try these ones
thanks!

**Comment by allexysleeps** [comment]
@adispring
It works.
So don't you think it might be useful to add this abstraction to the library core as a separate function?
If not, feel free to close this one.

**Comment by adispring** [comment]
Maybe this function is easy to implement with existing apis. And you can read this post about what api can be added to ramda: https://fr.umio.us/the-philosophy-of-ramda/

> we have to be convinced they will be used and that they offer value not easily achieved through current functions.

**Comment by allexysleeps** [comment]
Ok, sounds fair, thanks!
