### ISSUE TITLE
Curried functions do not work as expected

### ISSUE THREAD

**Issue by walze** [ramda/ramda#2973]
I was trying to compose a curried function with 2 arguments and a function with 1 argument

```javascript
// works in haskell so should work here too
// in haskell is like `(.) . (.)`
// and has the type of `(b -> c) -> (a1 -> a2 -> b) -> a1 -> a2 -> c`
const compose2 = compose(compose)(compose)
```

but i got an error `compose2(...)(...) is not a function`

i tried to do
```javascript
// initial code
const a = n => console.log('/users/' + n)

// error Uncaught TypeError: compose2(...)(...) is not a function
// b(1) should console `/users/1`
const b = compose2(console.warn)(add)('/users/')
```
so it seemed to be a problem with the non-curried version of compose because i tried implementing  my own compose and it worked

```javascript
const _compose = g => f => x => g(f(x))
const _compose2 = _compose(_compose)(_compose)
const _add = a => b => a + b

// works
const c = _compose2(console.warn)(_add)('/users/')
// c(1) consoles `/users/1`
```

i also had to implement my own add for `c` to work, i believe it's the same problem.

is there a way for me to disable all non-curried functions from ramda? Like, it only be possible to do `compose(a)(b)` and never `compose(a, b)`?

**Comment by CrossEye** [comment]
> Is there a way for me to disable all non-curried functions from ramda? Like, it only be possible to do `compose(a)(b)` and never `compose(a, b)`?

I'm afraid not.  That style was one of the defining decisions of Ramda.  Sometimes I regret it and wish we'd only done the plain currying.  But the library has grown so popular based in part on how familiar it is to JS users.

While you can use our [binary version][o] of `compose` for this,

```js
const compose2 = o (o) (o)
```

You would still need your custom version of `add`, though, so I'm not sure how much help this is.


  [o]: https://ramdajs.com/docs/#o

**Comment by walze** [comment]
> You can use our binary version of compose for this,

Thanks, that helps a bit.

Shame ramda does not support that kind of style, JS really lacks typescript compatible functional libraries; Ramda is pretty much the best one out there :( thanks anyway

**Comment by ukslim** [comment]
Note that sanctuary.js made the decision to always use the unary style:

> There is, for example, exactly one way to apply S.reduce to S.add, 0, and xs:
> 
> `S.reduce (S.add) (0) (xs)`

I like, and use Ramda, but if what you're looking for is something Sanctuary is, and Ramda is not, then you could give it a go.

**Comment by walze** [comment]
@ukslim i have tried sanctuary before and fell in love with it but it does not work well with typescript so idk, the @types/sanctuary is not very complete but it does have its own type system which is pretty cool
