### ISSUE TITLE
Feature request: mapWhere

### ISSUE THREAD

**Issue by LarsKoelpin** [ramda/ramda#2975]
I feel like often I have to to map over an array for a given predicate similiar to the 
```UPDATE xy WHERE yz``` statement in SQL.

My Proposal would be to have something like `mapWhere` which maps over an array,
for a given predicate. If the predicate returns true, the map function applies, otherwise it simply returns the identity.

```
const x = [1,2,3,4,5,6,7,8,9]
const capToFive= mapWhere(lt(5), always(5))
const y = capToFive(x) // [1, 2, 3, 4,5, 5, 5, 5,5]
```

Would this function be a case for the ramda library or is it to specific?

**Comment by adispring** [comment]
You can compose `R.map` with `R.when` to do this? as follows:

```js
const arr = [1, 2, 3, 4, 5, 6, 7, 8]

const mapWhen = R.curry((pred, transformer, list) =>
  R.map(R.when(pred, transformer), list)
)

const result = mapWhen(R.gt(R.__, 5), R.always(5))(arr)
console.log(result) //=> [1, 2, 3, 4, 5, 5, 5, 5]
```

**Comment by LarsKoelpin** [comment]
Hi, I know how and that i can do that.

The question is, if the use case justifies beeing implemented in the ramda library.

**Comment by hitmands** [comment]
I don't feel like this api would improve expressiveness if compared to overall bundle size and api size growth.

```

**Comment by CrossEye** [comment]
I agree with @hitmands and @adispring.  It doesn't seem to add much.

I'd be more interested in a `filterMap` implementation, but even there probably not very interested.

**Comment by LarsKoelpin** [comment]
So I'm closing this, thanks for your feedback
