### ISSUE TITLE
0.27.0 not reflected in website docs

### ISSUE THREAD

**Issue by mikestopcontinues** [ramda/ramda#2977]
Hi! `npm install ramda` installs 0.27.0, but the docs don't reflect the updates. And as a result, neither does Alex Bepple's Dash docset. I've ran into differences a few times. Can someone clear up the status on this?

https://github.com/alexbepple/ramda-dash-docset/issues/19

**Comment by CrossEye** [comment]
The status is simply that I messed up, and messed up again when I tried to fix it.  I will try again in the next few days.

**Comment by CrossEye** [comment]
I think this is correct now.  Someone please tell me if I've messed up one more time!

**Comment by mikestopcontinues** [comment]
Looks good to me! Thanks!
