### ISSUE TITLE
0.27.0 is not semver compliant

### ISSUE THREAD

**Issue by MFogleman** [ramda/ramda#2982]
Per https://docs.npmjs.com/about-semantic-versioning, NPM packages are encouraged to be Semantic Versioning compliant.  I do not believe Ramda 0.27 is compliant.

In Semver, the idea is that version number represents `major.minor.bugfix`.  

Bugfix is just that, changes that dont add or remove functionality, just fix problems.
Minor is for new features, e.g. a new exposed method/module.
Major is for breaking changes.

If someone defines ramda in their package.json, and wants to have all non-API changing fixes, they could use (per https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).  
`"ramda": "~0"`

This would cause `0.26.1` to update to `0.27.0`, which should be a minor update.

With the removal of `then`, anyone running a fresh `npm install` on their project with Ramda defined like this is going to start crashing if they are using `then`.  

I believe this should be considered a major change if `R.then` is removed.  If the maintainers wish to avoid that, perhaps leave `R.then` in as well ass `R.andThen` ?

Edit:  Further, it appears that the 0.27 changes are in effect on master, ('/source/andThen.js' exists on master), but `package.json` says the version is still 0.26.1.  Is this unintended, or am I missing something regarding how github/npm handle releases?

**Comment by nifgraup** [comment]
https://semver.org/#spec-item-4 "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

**Comment by MFogleman** [comment]
Oh, wow.  Yeah thats a pretty important rule that I wasn't aware of.  Good catch, thanks.  Issue closed

**Comment by CrossEye** [comment]
On the other hand, this library is long, long overdue to have a version 1.0.  And after that, this point would be entirely valid.
