### ISSUE TITLE
In React app: Cannot read property 'fantasy-land/reduce' of undefined

### ISSUE THREAD

**Issue by trentlarson** [ramda/ramda#2991]
I just added ramda in my React app and I'm able to use it in my tests, but after bundling and hitting a page with it in a browser I get the following:

```_reduce.js:54 Uncaught TypeError: Cannot read property 'fantasy-land/reduce' of undefined
    at _reduce (_reduce.js:54)
    at Module.f3 (_curry3.js:46)
    at createStepsById (workflowUtils.js:20)
    at Workflow (Workflow.jsx:96)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)```

I've run `npm install` and even `npm ci`.

package.json is attached
[package.json.txt](https://github.com/ramda/ramda/files/4268283/package.json.txt)

I didn't see any other "fantasy-land" issues that looked similar to this.  Any help is appreciated.  Thanks.

**Comment by trentlarson** [comment]
I've tried different ways of importing:

const R = require('ramda');
import R from 'ramda'
import * as R from 'ramda';
import { assoc, map, reduce } from 'ramda';

**Comment by Bradcomp** [comment]
Ramda is being imported fine here, but there is an error in the way reduce is being called. Can you provide some example code?

Given the stack trace, I would start by looking here: `workflowUtils.js:20`

**Comment by kiyutink** [comment]
i think @trentlarson 's usage is something like this: https://ramdajs.com/repl/?v=0.27.0#?R.reduce%28R.sum%2C%200%2C%20undefined%29 ; The usage of react is not relevant though.

I've noticed the same problem with R.map: https://ramdajs.com/repl/?v=0.27.0#?R.map%28R.identity%2C%20undefined%29

Doesn't look like this behavior is intended

**Comment by CrossEye** [comment]
@kiyutink:

That sounds like a good guess.  While this behavior is not particularly intended, Ramda has always taken a no-hands-holding approach.  If you use it as documented, it should do as you expect.  But if you pass unexpected data (such as `undefined` where an object, array, function, or fantasy-land-compatible functor is expected), then anything can happen.

While it would be nice to get better error messaging in these cases, the Ramda team has not been very interested in adding the necessary type-checking that would slow down the code for the happy paths.

But if you (or @trentlarson) is interested in creating a PR to fix this, we would certainly consider it.
