### ISSUE TITLE
compose(all, whereEq) for empy array incorrect result

### ISSUE THREAD

**Issue by hcygit** [ramda/ramda#2996]
version 0.27.0
os: macOS 10.15.3
node: 12.16.0

```
const data1 = [{
  name: 'A',
  age: 10
},{
  name: 'B',
  age: 10
}, {
  name: 'C',
  age: 10
}]

const data2 = []

compose(all, whereEq)({ age: 10 })(data1) // true
compose(all, whereEq)({ age: 10 })(data2) // true (expected false)
```

for example above
while passing an empty array, the compose result is true instead of false
but the result is expected to be false

**Comment by CrossEye** [comment]
That is the correct behavior.  `add(pred)` and `~any(~pred)` should return identical values.  (You can use `complement` for `~`.)  You can think of `all` as `reduce(and, true)`, and of `any` as `reduce(or, false)`.  If you pass either an empty array, you will get `true` and `false`, respectively.

You might want to read about [vacuous truths][vt].

  [vt]: https://en.wikipedia.org/wiki/Vacuous_truth

**Comment by hcygit** [comment]
> That is the correct behavior. `add(pred)` and `~any(~pred)` should return identical values. (You can use `complement` for `~`.) You can think of `all` as `reduce(and, true)`, and of `any` as `reduce(or, false)`. If you pass either an empty array, you will get `true` and `false`, respectively.
> 
> You might want to read about [vacuous truths](https://en.wikipedia.org/wiki/Vacuous_truth).

ok, i've learned from this wiki and totally agree
