### ISSUE TITLE
Bidirectional Range

### ISSUE THREAD

**Issue by tforward** [ramda/ramda#3000]
R.range(1, 5)   =>  [1, 2, 3, 4]
R.range(5, 1)   =>  [ ]
==============

Shouldn't [5, 1]  return [4, 3, 2, 1] ? 

There may be a very logical reason why it does not work this way, and is beyond me

As a workaround I got around it by doing this:

```
const bidirectionalRange = ifElse(
  (n1, n2) => R.lte(n1, n2),
  (n1, n2) => R.range(n1, n2),                   
  (n1, n2) => R.reverse(R.range(n2, n1)),
);

const result = bidirectionalRange (5, 1);   // =>  [4, 3, 2, 1]
```

**Comment by Bradcomp** [comment]
Hi @tforward ! 

This is a good question. Here is a blog post related to the API design for `range`: https://fr.umio.us/ranging-near-and-far/

**Comment by CrossEye** [comment]
The article @Bradcomp mentioned explained my feeling about the range API, but I would like to point out that your implementation uses some unnecessary lambdas.

I might write it this way:

```js
const bidirectionalRange = ifElse (
  lte,
  range,
  compose (reverse, flip(range))
);

**Comment by tforward** [comment]
Thank you for the feedback Scott, no idea I could do it that way
