### ISSUE TITLE
Faulty typing in R.either

### ISSUE THREAD

**Issue by jonni-larjomaa** [ramda/ramda#3004]
The either function has wrong typings, the outcome of R.eihter predicates should not be booleans but actually any, the either should not return the boolean value but the value of function generated, which then is compared as being truth-y value or not.

/**
         * A function wrapping calls to the two functions in an || operation, returning the result of the first
         * function if it is truth-y and the result of the second function otherwise. Note that this is
         * short-circuited, meaning that the second function will not be invoked if the first returns a truth-y value.
         */
        either(pred1: Pred, pred2: Pred): Pred;
        either(pred1: Pred): (pred2: Pred) => Pred;

and then the type of Pred is of course as follows:

type Pred = (...a: readonly any[]) => boolean;

in general this is not wrong, but in the case of either the returning value should not be the predicate it self but the actual, value generated by eihter functions.

so the typings should be

either(pred1: T1, pred2: T2): <T1 | T2>;

**Comment by CrossEye** [comment]
The Ramda team does not manage these typings (at least so far.)  You might want to take it up with those who maintain whatever TS/Flow typing file you use.
