### ISSUE TITLE
Tap does not execute the provided function if it receives no arguments

### ISSUE THREAD

**Issue by kallja** [ramda/ramda#3006]
The function created by calling `R.tap` does not execute if arguments are not provided.

See the provided example.

```js
const tap = R.tap(() => { console.log('some debug logging'); });

// Executes `logSomething`
tap(undefined);

// Does not execute `logSomething`
tap();
```

**Comment by adispring** [comment]
Because ramda's functions are auto curried, in ramda's curry mechanism:

1. `tap()` receiving zero argument, and just return the `tap` itself, `tap() === tap`
2. `tap(undefined)` receiving one argument, and execute tap's body.

This is what ramda's inner help function `_curry1` do :

```js
export default function _curry1(fn) {
  return function f1(a) {
    if (arguments.length === 0 || _isPlaceholder(a)) {
      return f1;
    } else {
      return fn.apply(this, arguments);
    }
  };
}
```

as you can see, 

```js
_curry1(console.log)()                    // just do nothing but returned console.log
_curry1(console.log)(undefined)  // output 'undefined'
```

**Comment by CrossEye** [comment]
The only use I've ever had for `tap` is to log something in the middle of a pipeline:

<pre><code>
const foo = pipe (
    doSomething,
    doSomethingElse,
    <strong>tap (console.log)</strong>,
    weNowReturnYouToYourRegularlyScheduledPipeline,
    doOneMoreThing
)
</code></pre>

And in such circumstances, of course, the pipeline must be supplying data, so one would never notice that `tap (fn) ()` doesn't actually do something.

Of course @adispring's analysis of *why* this is so is spot-on.  @buzzdecafe has long argued that `curry1` is superfluous, that we should throw if no data is supplied.  Thankfully for just as long, cooler heads have prevailed.  :wink:.  In any case, this is not something I see changing soon.

**Comment by kallja** [comment]
> The only use I've ever had for `tap` is to log something in the middle of a pipeline

Unless of course the data comes into your pipeline as a part of a more complex process and you're logging your input as the very first step of the Ramda pipeline, which was the case where I noticed this happening.

As addressing this would probably need unfortunate tradeoffs in other areas (change currying) and as this is pretty much an edge case, it's probably not worth acting upon in any way. It's just good to know that not seeing an expected log message might be caused by this.

**Comment by CrossEye** [comment]
@adispring:  Could you get in touch with me at some point?  I'd like to ask you something in a quieter forum.  I'm scott@sauyet.com and @scott_sauyet on Twitter.
