### ISSUE TITLE
Unexpected `path` edge cases for objects with numbers as keys.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [ramda/ramda#3007]
I proverbially stubbed my toe against some unexpected hard edges with `path` recently...

```js
path('-5', { "-5": "boo"} ) // undefined
path('5', { "5": "boo"} ) // 'boo'
path([-5], { "-5": "boo"}) // undefined
path([5], { "5": "boo"}) // 'boo'
```

([repl](https://ramdajs.com/repl/#?%0Apath%28%27-5%27%2C%20%7B%20%22-5%22%3A%20%22boo%22%7D%20%29%20%2F%2F%20undefined%0Apath%28%275%27%2C%20%7B%20%225%22%3A%20%22boo%22%7D%20%29%20%2F%2F%20%27boo%27%0Apath%28%5B-5%5D%2C%20%7B%20%22-5%22%3A%20%22boo%22%7D%29%20%2F%2F%20undefined%0Apath%28%5B5%5D%2C%20%7B%20%225%22%3A%20%22boo%22%7D%29%20%2F%2F%20%27boo%27%0A))

Granted, I'm now all too painfully familiar with how passing in `5` and `'5'` have *potentially very different behaviors* for functions that involve path, e.g. `assocPath` (we've actually created a `assocPathStr` because we mess it up so often and always want strings anyway)... but I really didn't expect the presence of a negative value to make such a difference.

Is this ... a bug? Expected?

**Comment by adispring** [comment]
According to `path`'s signature

```js
[Idx] → {a} → a | Undefined
Idx = String | Int
```

`path` only accepts array as its first parameter, and the item in the array should be either `String` or `Int`. So the the following writings are wrong:

```js
path('-5', { "-5": "boo"} ) // undefined
path('5', { "5": "boo"} ) // 'boo'
```

If item in the array is an negative Integer, then `path`‘s second parameter related part should be an array. 

`path` implemented by `paths` and `nth`, this two apis support (negative) number, and already cause some problems.

**Comment by CrossEye** [comment]
The only one of those examples that feels even slightly surprising is

```js
path([-5], { "-5": "boo"}) // undefined
```

I suppose that our signature should really be 

```hs
:: [Idx] → {a} → a | Undefined
:: Idx = String | NonNegativeInt
```

What happens if you don't pass an array for the path is undefined, and, as always,  *caveat emptor*. 

This is actually the most interesting one:

```js
path([5], { "5": "boo"}) // 'boo'
```

When Ramda's path is passed a (non-negative, ideally) integer inside the first parameter, it is expecting an array at that point.  But since JS Arrays are simply Objects with an attitude, the same code works to get an object property:

```js
// expected input for ['b', 5]
path (['b', 5]) ({
  a: 42, 
  b: ['foo', 'goo', 'moo', 'too', 'poo', 'boo', 'scooby-doo']
}) //=> 'boo'
// legal input for ['b', 5]
path (['b', 5]) ({
  a: 42, 
  b: {8: 'foo', 6: 'goo', 7: 'moo', 5: 'too', 3: 'poo', 0: 'boo', 9: 'scooby-doo'}
}) //=> 'too'
```

Is there a strong reason to try to fix the `path([-5], { "-5": "boo"})` case?

**Comment by AndrewSouthpaw** [comment]
Thanks for the responses! I feel like I've learned a few new things about the library yet again. I've created a PR with some suggested doc improvements.

> Is there a strong reason to try to fix the path([-5], { "-5": "boo"}) case?

In our project, we have an index of things by ID, but some would have a temp ID like `-1`, `-2`, etc. When we upgraded from v0.25, `path` stopped behaving the way we would expect. But, we tend to be lax about passing integer lookups for an object and it's bitten us before.

What surprised me was that I had come to learn that Integer path values simply behaved differently from String path values. But now it seems like Integer and String values are interchangeable, except for negative Integer values.

I've also come to realize that starting with v0.27 `assocPath` no longer suffers the strange behavior where passing an integer path for an object would convert it to an array. 😅 Neat!

**Comment by AndrewSouthpaw** [comment]
Oh wow! I didn't realize that difference in behavior... the update behavior depends on both whether the path `Id` is a string or number as well as whether the existing value is an object or nothing.

```
assocPath(['a', 0], 'yay', {b: 42})  //=> {a: ["yay"], b: 42}
assocPath(['a', 0], 'yay', {a: {c: 1}, b: 42}) //=> {a: {0: "yay", c: 1}, b: 42}
```
