### ISSUE TITLE
R.is(Object, []) returns true

### ISSUE THREAD

**Issue by fruity4pie** [ramda/ramda#3008]
It shouldn't work like that:

R.is(Object, []) // true

**Comment by CrossEye** [comment]
But it *is* an object.  That's how Javascript implements Arrays, as objects whose keys are usually consecutive low-numbered integers, with some slight magic handling of the `length` property.

```js
Object .prototype .isPrototypeOf ([]) //=> true
```

**Comment by fruity4pie** [comment]
@CrossEye, I know, it is an instance of Object, but it isn't an Object :)

**Comment by adispring** [comment]
Maybe @fruity4pie  want a lodash's `isObject`.

**Comment by CrossEye** [comment]
I feel that this is more like 

```js
is (Rectangle, new Square(5)) //=> true, so long as Rectangle is in Square's prototype chain.
```

Something can be a Rectangle *and* a Square.  Something can be an Array *and* an Object.

I really can't see changing the behavior of `is` for this.  If you're interested in promoting a `isPlainObject` function, please feel free.  It would take some convincing for me, but I'm not entirely opposed.

**Comment by customcommander** [comment]
Closing assuming that `R.is(Object, [])` works as expected. We can raise a separate issue for adding `isPlainObject` to the library.
