### ISSUE TITLE
How are API documents generated ?

### ISSUE THREAD

**Issue by snkzhong** [ramda/ramda#3009]
Ramda's documentation is great. It looks like generated from code comments. What tool is used?

**Comment by CrossEye** [comment]
It is generated from code comments, via [JSDoc][jd].  The code to build it is in the project's [website directory][rg].

I'm actually not much of a fan of this process or of the JSDoc annotations, but I've never spent a great deal of time trying to come up with a good alternative.  It works, and people seem reasonably pleased with the results.


  [jd]: https://jsdoc.app/
  [rg]: https://github.com/ramda/ramda.github.io
