### ISSUE TITLE
R.equals doesn't work with nested monads (created via "monet" library)

### ISSUE THREAD

**Issue by siarhei-murkou** [ramda/ramda#3015]
Method `R.equals` doesn't support compaaring of nested objects created by "monet" library.
For comparison, `Lodash` does.

To have more information about my issue, please have a look at the example below:
```
import { NonEmptyList } from "monet";
import * as R from "ramda";
import * as _ from "lodash";

const elements = [
    { a: NonEmptyList.fromArray([{ a: 1 }]).just() },
    { a: NonEmptyList.fromArray([{ a: 1 }]).just() }
];
const nel1 = NonEmptyList.fromArray([ elements[0] ]).just();
const nel2 = NonEmptyList.fromArray([ elements[1] ]).just();

console.log(R.equals(nel1, nel2));    // false
console.log(_.isEqual(nel1, nel2));   // true
```

Ramda version: _0.27.0_

**Comment by CrossEye** [comment]
Ramda has never really concerned itself with the prototype chain when dealing with equality.

It would be interesting to update to cover more cases, if you have any suggestions.  I really don't think its possible to cover every way people can create objects, but if we can cover more without bloating the function too much, I'd love to know.

**Comment by Bradcomp** [comment]
I was pretty curious what was going on here:

I didn't download any code to run, but my gut says that it is due to Ramda dispatching to `equals`:
https://github.com/monet/monet.js/blob/develop/src/monet.js#L364
https://github.com/ramda/ramda/blob/master/source/internal/_equals.js#L50

Lodash doesn't dispatch:
https://github.com/lodash/lodash/blob/master/eqDeep.js

So then the question becomes, what does this code do?
```
import { NonEmptyList } from "monet";
import * as R from "ramda";
import * as _ from "lodash";

const elements = [
    { a: NonEmptyList.fromArray([{ a: 1 }]).just() },
    { a: NonEmptyList.fromArray([{ a: 1 }]).just() }
];
const nel1 = NonEmptyList.fromArray([ elements[0] ]).just();
const nel2 = NonEmptyList.fromArray([ elements[1] ]).just();

console.log(nel1.equals(nel2));
```

If that's false, then we can look into why monet doesn't think those two objects aren't equal.

**Comment by CrossEye** [comment]
And he calls it!  Good find, @Bradcomp.

Yes, it returns `false`:  https://runkit.com/crosseye/ramdaissue3015

**Comment by Bradcomp** [comment]
Looks like Monet uses reference equality for anything that doesn't dispatch:
https://github.com/monet/monet.js/blob/develop/src/monet.js#L148

@siarhei-murkou Unfortunately this behavior is by design. I think you'll need to use lodash's `isEqual` in this case.
