### ISSUE TITLE
Sponsorship opportunities

### ISSUE THREAD

**Issue by Bradcomp** [ramda/ramda#3016]
An individual [reached out in the chat room](https://gitter.im/ramda/ramda?at=5e9ab29963e7b73a5fe632dd) about making a monetary contribution to Ramda. 

I am realizing that I don't know much about who keeps the lights on around here. I assume there are probably costs associated with hosting / domain / etc?

Is there interest in setting up something like github sponsorship (or whatever) so that people can contribute?

**Comment by CrossEye** [comment]
I've footed the very minor bill for our domain name (less than $20/year, if I recall correctly).  The few times we've done some contests, @buzzdecafe or I put up the inexpensive prize.  I can't think of any other costs we've incurred.  Hosting has been free through GitHub.

However, if people want to make donations, I certainly don't want to discourage it!  I'm quite sure we can discover some useful and creative way to use it.

I have no experience setting any of this up, or managing money for such an organization.  Is there anyone around who has some experience and wants to offer suggestions?  

Pinging @ramda/core!

**Comment by kedashoe** [comment]
We could set up an [Open Collective](https://opencollective.com/) project. I've never done it myself but I see other projects using it.

**Comment by kabo** [comment]
Open collective, github sponsors, liberapay, donorbox, bountysource salt, there's a few different options. It may also be nice to have a couple of different ways of donating.

**Comment by CrossEye** [comment]
@kabo: Have  you had better or worse experiences with any of these?  I've supported coders through github sponsorship and Patreon, as well as various kickstarter sites, and all have been painless.

I'm mostly worried about how to manage it from this end.  I will try to do some research over the next week into tools.  I will investigate all those in your list.  Anyone have others?

**Comment by davidchambers** [comment]
[GitHub Sponsors][1] puts the focus on individual contributors rather than teams, which does not feel quite right for Ramda. I don't have much experience with the other options.


[1]: https://github.com/sponsors

**Comment by kabo** [comment]
@CrossEye LiberaPay, Open Collective, Donorbox have been good. Bountysource salt has not been a good experience.
I'm primarily interested in making a one-time donation, another aspect to add to the mix :)

**Comment by CrossEye** [comment]
@kabo: Thank you.   I'll be looking into this sometime soon.

**Comment by kabo** [comment]
bump

**Comment by CrossEye** [comment]
@kabo:

Thanks.  I have been looking, and like Open Collective best so far.  But I would like to stew on it another few days before making a recommendation.

**Comment by CrossEye** [comment]
Ok, there are lots of options, and I've spent some time on a bunch of them, and I definitely prefer Open Collective.

What I especially like is that this it is all about doing everything in the open, and helping teams keep accountable for it.

I'd like to hear if anyone has a suggestion they really prefer.  And if not, are there any objections to my starting up an account there for the Ramda projects?

**Comment by kabo** [comment]
Sooo... any update? :)

**Comment by CrossEye** [comment]
Sorry.  While I have created an Open Collective account (https://opencollective.com/ramda), I have done little more than setting it up.  I will add links to our README, etc. sometime soon.

**Comment by kabo** [comment]
I've donated now, I'm glad I'm able to contribute back :)

**Comment by CrossEye** [comment]
@kabo: Sorry that took so long.

**Comment by customcommander** [comment]
@CrossEye I've assigned this issue to you as a reminder to update the README. I checked and couldn't find anything and I'm assuming you're probably the best person to set this up?

**Comment by CrossEye** [comment]
Perhaps something like the following?:

-----

Sponsorships
------------

Ramda has few expenses and does not actively seek financial support, but if you would still like to contribute, it is welcome and we will find good use for it.  You can contribute at [Open Collective][oc].


  [oc]: https://opencollective.com/ramda
