### ISSUE TITLE
question : would you help me to understand why `_isInteger(path[1])`  being used here ? 

### ISSUE THREAD

**Issue by mohan-mu** [ramda/ramda#3020]
Hi Developers ,

I was going through `assocPath` code snippet , & i didn't understand why you guys are using `_isInteger(path[1])` why not `_isInteger(idx) ` .

https://github.com/ramda/ramda/blob/ed191e6a476330e37db259a5c2d04bfba0b2d63d/source/assocPath.js#L39

![image](https://user-images.githubusercontent.com/20799929/80054003-d917c600-853b-11ea-8c05-ad6e92b091cd.png)

**Comment by Bradcomp** [comment]
Hi @mohan-mu, thanks for the question!

Let's take a look:
```
// If the path length is more than 1 then it means we haven't reached the base case
if (path.length > 1) {
     // We are getting the next level object to recurse into
    var nextObj = (
        !isNil(obj) && 
        _has(idx, obj)
// If there is already an object there, use it.
    ) ? obj[idx] : 
           // Otherwise, is the next index in the path an integer?
          // If so, then we create an array
           // If not we create an object
         _isInteger(path[1]) ? [] : {};
    // Finally, get the value from calling assocPath recursively
    val = assocPath(Array.prototype.slice.call(path, 1), val, nextObj);
  }
```

So we can see that this code is stepping down into an object level by level until it reaches the bottom of the path. 

If it gets to a point where the next level it's looking for doesn't exist, it needs to create that level. So then it takes a peek at the next item in the path so that it knows what type of object to create. If that item is an integer then it creates an Array, otherwise it creates an Object.

**Comment by mohan-mu** [comment]
Hi @Bradcomp ,Thank you  

![image](https://user-images.githubusercontent.com/20799929/80119746-bae7af80-85a7-11ea-9dca-8b71cb40d6fa.png)

Here I was expecting result to be 
```javascript
"11" :{
    "4" :23
}
```

**Comment by CrossEye** [comment]
@mohan-mu:

You can get that result with

```js
assocPath(['11', '4'], "23", {}) //=> {"11": {"4": "23"}}
```

As @Bradcomp's walk-through demonstrates, Ramda uses integers vs string-wrapped integers to distinguish between array properties and similarly-name object properties.

It's this difference:

```js
// assocPath(['11', '4'], '23', {})
const foo = {}
foo['11'] = {}
foo['11']['4'] = '23'
foo //=> {'11': {'4': '23'}}

// assocPath([11, 4], '23', {})
const bar = {}
bar[11] = []
bar[11][4] = '23'
bar //=> {'11': [ , , , , '23']}
```

**Comment by mohan-mu** [comment]
@CrossEye Thank you
