### ISSUE TITLE
Update description/doc for mergeAll

### ISSUE THREAD

**Issue by klequis** [ramda/ramda#3024]
Modified description to make clear which values will be in the returned object. This was likely pretty obvious to those already well versed in Ramda but seems a good add for those less so.

**Current description:**

Merges a list of objects together into one object

**New description:**

Creates a new object with the own properties from a list of objects. If a key exists in more than one object, the value from the last object it exists in will be used.

**Comment by CrossEye** [comment]
Thank you!!
