### ISSUE TITLE
R.traverse doesn't dispatch to `traverse` method, contrary to documentation

### ISSUE THREAD

**Issue by joshtch** [ramda/ramda#3026]
The [documentation for `R.traverse`](https://ramdajs.com/docs/#traverse) says:

<pre>
Maps an Applicative-returning function over a Traversable, then uses `sequence` to
transform the resulting Traversable of Applicative into an Applicative of Traversable.

<b>Dispatches to the `traverse` method of the third argument, if present.</b>
</pre>

But [the code](https://github.com/ramda/ramda/blob/ed191e6a476330e37db259a5c2d04bfba0b2d63d/source/traverse.js#L33-L35) does not dispatch as described:

```js
var traverse = _curry3(function traverse(of, f, traversable) {
  return typeof traversable['fantasy-land/traverse'] === 'function' ?
    traversable['fantasy-land/traverse'](f, of) :
    sequence(of, map(f, traversable));
});
```

It instead dispatches to `fantasy-land/traverse` only.

My expectation had been that `R.traverse` would dispatch to the fantasy-land prefixed method, if present, then the non-prefixed method, if present, then fall back to the implementation. This behavior would make it consistent with `map`, `ap`, and a few other functions.

Whatever the case, though, either the code or the documentation needs modification so the two agree.

**Comment by CrossEye** [comment]
Agreed.  Are you interested in creating a PR for this?

**Comment by joshtch** [comment]
Hi Scott -- yes, certainly. 

Just to confirm, are you agreeing/do you agree that the correct functionality should be to dispatch to either of `fantasy-land/traverse` or `traverse` if they exist, preferring the former over the latter?
