### ISSUE TITLE
Does ramda have immutable data structure support？

### ISSUE THREAD

**Issue by lizy0329** [ramda/ramda#3027]
Ramda is immutable, but it implementation used plain js object before version. Does not perform well when handling large amounts of data. Now, how does ramda solve performance problems?

**Comment by CrossEye** [comment]
Do you have a more specific query?  What parts of Ramda are causing you performance problems?  What constitutes "large amounts of data"?

Ramda, we should note, does not enforce immutability, but itself refuses to mutate your data.  You're free to mutate it all  you want.

**Comment by Magnitus-** [comment]
I view the fact that ramda operates on and returns plain js objects as a positive feature of the library (compared to immutableJS for example).

It means that ramda is easy to integrate with other ecosystems (existing codebases, other libraries, etc) without having to write a lot glue code.

**Comment by kedashoe** [comment]
Also any immutable data structures that support fantasy land will work very well with ramda, eg https://github.com/funkia/list

**Comment by lizy0329** [comment]
Sorry I failed to make it clear.

1. immutable.js using **Persistent Data Structur** to achieve a balance between immutable data and speed

![persistent-data-structures-and-structural-sharing](https://miro.medium.com/max/1400/1*zYtOUrDIj0_-vLoBTbQGUQ.png)

And I want to know “What methods does Ramda.js use to achieve immutable data and speed?”

**Comment by CrossEye** [comment]
>And I want to know “What methods does Ramda.js use to achieve immutable data and speed?”

We do pretty much the same technique of structural sharing when you use things like `assoc`, `assocPath` or the `set` and `over`.  We don't do much unnecessary cloning, so something like `append` creates a new Array object, but its children are references to the old ones.  Of course we use Arrays, so we don't get the structural sharing of tails that happen in tools that use Pair-based lists.  We do what we can to avoid hogging memory.

**Comment by lizy0329** [comment]
Thank for your patience answer.
