### ISSUE TITLE
Remove ES Module build with a source change

### ISSUE THREAD

**Issue by Pyrolistical** [ramda/ramda#3028]
Right now the source is already a well organized set of ES Modules, thank you!

But there is one non-standard right now and its that its omitting the .js extension when importing. This is added back during the build and the files are published under the `es/` folder.

We can see this in action by looking at https://unpkg.com/ramda@0.27.0/es/uniq.js
```js
import identity from "./identity.js";
import uniqBy from "./uniqBy.js";
/**
 * Returns a new list containing only one copy of each element in the original
 * list. [`R.equals`](#equals) is used to determine equality.
 *
 * @func
 * @memberOf R
 * @since v0.1.0
 * @category List
 * @sig [a] -> [a]
 * @param {Array} list The array to consider.
 * @return {Array} The list of unique items.
 * @example
 *
 *      R.uniq([1, 1, 2, 1]); //=> [1, 2]
 *      R.uniq([1, '1']);     //=> [1, '1']
 *      R.uniq([[42], [42]]); //=> [[42]]
 */

var uniq =
/*#__PURE__*/
uniqBy(identity);
export default uniq;
```

Here's where we can do better. If all we did was add .js to all the imports, then we don't even need a build step. The tagged source from github is already usable. We can see https://raw.githubusercontent.com/ramda/ramda/v0.27.0/source/uniq.js is almost there
```js
import identity from './identity';
import uniqBy from './uniqBy';


/**
 * Returns a new list containing only one copy of each element in the original
 * list. [`R.equals`](#equals) is used to determine equality.
 *
 * @func
 * @memberOf R
 * @since v0.1.0
 * @category List
 * @sig [a] -> [a]
 * @param {Array} list The array to consider.
 * @return {Array} The list of unique items.
 * @example
 *
 *      R.uniq([1, 1, 2, 1]); //=> [1, 2]
 *      R.uniq([1, '1']);     //=> [1, '1']
 *      R.uniq([[42], [42]]); //=> [[42]]
 */
var uniq = uniqBy(identity);
export default uniq;
```

Btw, I noticed this when trying to use Ramda in https://github.com/denoland/deno

**Comment by CrossEye** [comment]
Although we would have to run it by people who better understand the various module builds, we would certainly welcome a PR on this.

**Comment by Andrew-Webb** [comment]
It would certainly be great to ensure Ramda works nicely with [Deno](https://deno.land/).  Then it can be added to Deno's [third-party modules list](https://deno.land/x), as `lodash` is.

**Comment by CrossEye** [comment]
My go-to person for this is @Andarist.  Any thoughts?

**Comment by Andarist** [comment]
Well, there is no much harm in including those extensions there, BUT why you (@Pyrolistical) would like to consume those files using source files? Distributed `es` directory is pretty much equivalent and it already contains those extensions. While Ramda is not really using much of a build step this might change in the future (probably not though). Having a distinction between source and distributed files give maintainers freedom to structure source files however they want, including using custom Babel plugins, TS, or whatever else.

> It would certainly be great to ensure Ramda works nicely with Deno. Then it can be added to Deno's third-party modules list, as lodash is.

This is an interesting argument - but from what I understand this requires no build step which is somewhat a bummer as mentioned by me above. Shouldn't be much of a problem for Ramda, but it doesn't seem like a good strategy for the entire ecosystem. For instance, any React-based library **has to** compile their source files and committing both sources and distributed files is also not ideal.

**Comment by Pyrolistical** [comment]
I'm "the build guy" as well, but dislike having any build at all. I really dislike the how built artifacts are pushed up to package managers like npm. We've seen the security implications of [this again](https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm)  and [again](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).

This is why I want to use Ramda's source directly via commit hash https://raw.githubusercontent.com/ramda/ramda/f494250c0aed9ecc096cc5b5b7823661edc14de2/source/uniq.js

Then at least I know in order for a malicious actor to inject code, it would require them [over $10,000 USD to find a sha1 collision](https://sha-mbles.github.io).

The way I think about it is, Ramda isn't something fancy like JSX in React, its just plain modern JS. If you wish you add a build to output a Babel tree shakable version, that is fine. Call it as such but not `es`.

**Comment by hitmands** [comment]
my view is that there would still be value in giving people ability to import modules directly, 
this is also where javascript is heading... 

However, 
I totally agree with having src/dist separation, 
this is essential for maintenance (build optimisations, bundle optimisations, metrics, etc.)

___

I think `es` consumption should be done via [`package.json#module`](https://github.com/ramda/ramda/blob/master/package.json#L59)

**Comment by Pyrolistical** [comment]
Yes, your argument makes sense in npm universe, but I'm not in that. I'm thinking about pure ES Module standard and things like [Deno that consume it directly](https://deno.land/manual/linking_to_external_code).

**Comment by Pyrolistical** [comment]
Hmm, also ran into a related issue when trying to use the `es` build. Ramda uses variable names which are keywords in TypeScript.

For example `type` is a keyword isn't allowed here https://github.com/ramda/ramda/blob/03817fe578048652b9532ae71fd1f1705da4de60/source/internal/_equals.js#L7

This problem is very tricky. Ramda has TypeScript type, but doesn't really have first class support as raised here https://github.com/ramda/ramda/issues/2976

On one hand its honestly not that hard to fix a bunch of minor code changes such that it is compatible with TypeScript, on the other hand Ramda never signed up for this.

**Comment by CrossEye** [comment]
That does become tricky.  While Ramda would like to play nicely with things like Typescript, it's never been a major goal.  And while renaming `type` to something that doesn't conflict is easy enough, how do we make the call of when to do so?  If only a slight change would make Ramda compatible with CoffeeScript, should we do it?  If Ramda could be used in Elm applications with only these two tiny tweaks, is it worth it?  If Ramda could be used inside R, if only we'd rename our usual export variable, should we?

**Comment by hitmands** [comment]
I find this issue very surprising, 
typescript should be "smart" enough to figure out whether the `type` word is being used as variable and not as a type.

This is absolutely fine in all my projects, 
I have just checked it.

Can you provide more info to reproduce the issue?

**Comment by Andarist** [comment]
> Yes, your argument makes sense in npm universe, but I'm not in that. I'm thinking about pure ES Module standard and things like Deno that consume it directly.

Won't Deno provide any means to consume things differently? I find it hard to believe that they would give up on npm ecosystem in which many packages are packaged before publishing. It's somewhat quirky to me to treat github as a package repository like that. It was not really meant to be one so assuming it can serve as such is somewhat a stretch - or rather, to expect everybody treat it as such at this point in time.

Im kinda playing devil's advocate here though as I maintain multiple packages, but nearly all of them are built from source codes. I would like to support Deno if possible but I'm currently not sure what's the best way to do that.

**Comment by Andrew-Webb** [comment]
> I find it hard to believe that they would give up on npm ecosystem in which many packages are packaged before publishing

Mr. Node doesn't like `npm`.

https://deno.land/v1#compatibility

"Unfortunately, many users will find a frustrating lack of compatibility with existing JavaScript tooling. Deno is not compatible, in general, with Node (NPM) packages."

Some rationale (from the same source):-

"Furthermore the [Node] mechanism for linking to external libraries is fundamentally centralized through the NPM repository, which is not inline with the ideals of the web."

**Comment by sebastienfilion** [comment]
Hey guys; since this conversation seems to have died down, I created a PR to resolve the issue reported. My feeling is that using the source directly through ES module is the direction the community is taking (Browser import, Deno import). I see people starting to create "experimental" FS modules inspired by Ramda for Deno; I know there is a strong community here and a lot of work went into this, I really want to register Ramda as a Deno third-party ASAP 😄

**Comment by CrossEye** [comment]
I'm all for a PR.  It gets really difficult to discuss such things in the abstract.

**Comment by sebastienfilion** [comment]
For those who are interested: I submitted Ramda as Deno third-party. denoland/deno_website2#1174

**Comment by alextes** [comment]
@sebastienfilion my types are still a mess with that, how do you handle the types?

I tried getting the ramda.d.ts from definitelytyped but it depends on more stuff still.

**Comment by sebastienfilion** [comment]
> @sebastienfilion my types are still a mess with that, how do you handle the types?
> 
> I tried getting the ramda.d.ts from definitelytyped but it depends on more stuff still.

There's no implementation of type in Ramda... I don't think it's a good idea to try to force types. Is there an alternative?

**Comment by alextes** [comment]
What do you mean force types? You mean you'd discourage @types/ramda? In that case there's only waiting for Ramda to support typescript #2976 , and otherwise a short list of typescript supporting fp libs but Ramda is great for people just getting into FP.

**Comment by sebastienfilion** [comment]
> What do you mean force types? 

I meant that I don't think that Ramda should be rewritten in TypeScript. In my opinion, the approach of DefinitelyTyped is better.

I think that the issue you're having with DefinitelyTyped is that the import statements omit the extension of the files; standard ESM requires a valid URL path -- which is how Deno implements ESM.

```js
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/es/map.d.ts
import { map } from '../index';
export default map;
```

**Comment by alextes** [comment]
@sebastienfilion right, so then my question is how do I get definitelytyped types with a Deno import? But I think I found my answer, right now that's not possible. [Over here](https://deno.land/manual/getting_started/typescript) they explain how some `d.ts` files expect to import others node style, which the ramda one does, which doesn't work for Deno. But that's an issue I can take up with people over on DefinitelyTyped.

If anyone has other suggestions for how to get Ramda types with Deno, I'm all ears.

**Comment by Andarist** [comment]
I've just wanted to chime in here again after thinking about this problem in a different repository. I believe that the best thing would be to keep build artifacts ignored on the branches but they could be added to git on a detached HEAD, just before tagging that detached HEAD. It would kinda let library authors have cake and eat it too. That way anyone could use dist files directly from the tagged commits and we wouldn't have to worry about people using source files directly as they very often are not for public consumption.

**Comment by CrossEye** [comment]
@Andarist: I like your thinking.  I have no real idea what other implications this would have, and would have to think about it and play around a bit.  (Unfortunately my main computer died and until the new year, I'm probably stuck coding on a tablet, so I don't expect to do too much myself for the next six weeks or so.)

**Comment by Andarist** [comment]
I don't think there would be a lot of implications - can't quite see any dangers from any side. Just tags would be created for commits that wouldn't exist in the main trunk of the git history but this doesn't seem to be inherently bad, those are not that uncommon situations.
