### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by hitmands** [ramda/ramda#3030]
Hi, 

there isn't probably a real value in that, 
but we could introduce github actions so that we could help keepings things all in github.

We could create a workflow:

- lint
- test
- build

and set it as CI check in prs

__

this would probably mean decomissioning github

**Comment by crash7** [comment]
I can give a hand here :)

@hitmands what about adding a semantic-release step too?


PS: I think you meant "decomissioning travis"

**Comment by hitmands** [comment]
it'd be interesting to hear @CrossEye here

**Comment by Bradcomp** [comment]
I really like the idea of having everything in one place. I don't know anything about our current Travis setup though.

**Comment by CrossEye** [comment]
The Travis setup was a long time ago, but I have no interest in maintaining it.  If we can do it all in GitHub, I think that would be great.  At work these days, we do everything in GitLab, and I love how little friction there is!
