### ISSUE TITLE
splitEvery returning 2 chunk instead of 5 chunk.

### ISSUE THREAD

**Issue by sdenni** [ramda/ramda#3040]
I tried for 20 len of array.
split for every 2 len.

expected with 10 chunk.

but resulted with 2 chunk.
where first is 2 data, and the last chunk is the remaining data.

well this is the same problem with: https://github.com/ramda/ramda/issues/2891
but I don't know how did he resolve this problem.

My code:
```
            ramda.splitEvery(split, arrayData).map((chunk, i) => {
                result.push(chunk)
            })
```

I have tried for

```
   var result = ramda.splitEvery(split, arrayData)
```

but the output is still 2 chunk.

my array:

```
[{
	element1: value1
	element2: value2
	element3: value3
	... : ...
},{
	element1: value1
	element2: value2
	element3: value3
	... : ...
},{
	element1: value1
	element2: value2
	element3: value3
	... : ...
},{
	....	
}]
```

**Comment by sdenni** [comment]
after I try to log this:

src/slice.js
![image](https://user-images.githubusercontent.com/19981817/84605450-861d1800-aec7-11ea-95b4-97bfa094943e.png)

return

![image](https://user-images.githubusercontent.com/19981817/84605480-c7152c80-aec7-11ea-97eb-47593b53f19e.png)

for the first is 02 is true, but the next one why 
`idx +=n` is 022 expected 4 cause 2+2 = 4.
 
on src/splitEvery.js
```
while (idx < list.length) {
    console.log('split every',n)
    result.push(slice(idx, idx += n, list));
  }
```

maybe someone new hot did this happen ?

*still trying to check problem.

**Comment by sdenni** [comment]
found, 
variable split read by js is string.

so
parseInt(split) solve the problem.

**Comment by CrossEye** [comment]
Interesting find.  Wonder if Ramda should do something different in this case.  While that might go against our no-hand-holding philosophy, if it's as simple as calling `Number()` on that first parameter, it would be safer, I think.
