### ISSUE TITLE
Callback hell problem

### ISSUE THREAD

**Issue by BravenxX** [ramda/ramda#3051]
Maybe I'm doing something wrong. But I'm trying to avoid using PipeP because deprecated but when I have to do a pipe with a list of async functions I don't know how to handle it without falling in a callback hell like this:

```
    const updateActiveUser = R.pipe(
      getUserFromStorage,
      R.andThen(
        R.pipe(
          R.head,
          R.tap(LocalStorageApps.removeGlobal('activeUser')),
          R.andThen(
            R.pipe(
              R.tap(LocalStorageApps.insertGlobal('activeUser')),
              R.andThen(
                R.pipe(
                  LocalStorageApps.getGlobal('activeUser'),
                  R.andThen(R.pipe( R.head, R.tap(onSetActiveUser), setFaenaChosen)),
                ),
              ),
            ),
          ),
        ),
      ),
    );
```

I know that it have to be a better way.

**Comment by Bradcomp** [comment]
`pipeP` deprecated in favor of `pipeWith`. It's possible to get the same behavior or `pipeP` with `pipeWith(andThen)` (except it accepts an array of inputs instead of many parameters).

I think using `pipeWith` would allow you to flatten that whole thing out to the top layer.

**Comment by Bradcomp** [comment]
```
const updateActiveUser = R.pipeWith(R.andThen, [
          getUserFromStorage,
          R.head,
          R.tap(LocalStorageApps.removeGlobal('activeUser')),
          R.tap(LocalStorageApps.insertGlobal('activeUser')),
          LocalStorageApps.getGlobal('activeUser'),
          R.head, 
          R.tap(onSetActiveUser), 
          setFaenaChosen
      ]
);
```
You might be able to simplify this further depending on the structure of the data... If the functions that you are calling `head` after return an Array of a single item you could use chain to get rid of those calls to `head`. Please note this is untested code:

```
const updateLocalStorage = (activeUser) => {
  LocalStorageApps.removeGlobal('activeUser', activeUser);
  LocalStorageApps.insertGlobal('activeUser', activeUser);
  return LocalStorageApps.getGlobal(`activeUser`, activeUser);  // does this require a second parameter? If not it may cause a bug the way it was before.
};
const handleUpdatedUser = R.pipe(R.tap(onSetActiveUser), setFaenaChosen);
const updateActiveUser = R.pipeWith(R.andThen, [
          getUserFromStorage,
          R.chain(updateLocalStorage),
          R.chain(handleUpdatedUser)  // Or use R.map(handleUpdatedUser) and then R.head if this doesn't work
      ]
);

**Comment by BravenxX** [comment]
@Bradcomp thanks man, I take the first code. But as pipeP the first code only will work when the first function in pipe is async. It's a little annoying. The second code I would say is a little complicated to understand.

**Comment by Bradcomp** [comment]
You can always use `Promise.resolve` as the first function in your pipeline!
