### ISSUE TITLE
F: Allow the use of non-promise return values in pipeP and composeP.

### ISSUE THREAD

**Issue by sugoidesune** [ramda/ramda#3058]
Currently pipeP and composeP only work with functions that return promises.
But not all of our functions benefit from promises and it would be useful to be able to pipe both promises and regular functions

`pipeP(
fetchBackend('/user'),
showMessage('Welcome {Name}')
)`

The fetchBackend function clearly benefits from returning a promise.
But displaying a message doesn't benefit from returning a promise.

If pipeP and composeP used the await syntax internally, any return value would be automatically turned into a promise.
Allowing to chain both promises and rnon-promises.

**Comment by Bradcomp** [comment]
Currently, `pipeP` and `composeP` are deprecated in favor of the more flexible `pipeWith` and `composeWith`.

For reference, you can recreate the original functionality of `pipeP` with `pipeWith(andThen)`.

You could also use `pipeWith` to do what is suggested here by creating a custom function to pass in:

```
const isPromise = (p) => {/* blah */}

const myPipe = pipeWith((f, p) => isPromise(p) ? p.then(f) : f(p));
```

Or else just use async await if that works for you.

**Comment by sugoidesune** [comment]
Thank you.
For anyone interested I made the following implementation:

`pipeAwait = (...args) => R.pipeWith(async (func, acc) => {
  await acc
  return await func() 
},args);  

pipeAwait(fetchBackend('/user'), showMessage('Welcome {Name}'))()
`
