### ISSUE TITLE
on.js is missing from es/ and src/ directories and R.on is not documented

### ISSUE THREAD

**Issue by semmel** [ramda/ramda#3062]
`on.js` is missing from `es/` and `src/` directories in the npm package and thus `R.on` is not included in the [jsdoc-generated documentation](https://github.com/ramda/ramda.github.io).

Applying my usual method publishing a module to npm by running `npm publish --dry-run` or `npm pack` reveals that `on.js` gets *included* in the **tgz file** as it should. It is however *missing* from the  package downloaded via `npm install ramda`. I cannot imagine where the file gets lost 🤔  How do you publish to npm?

**Comment by CrossEye** [comment]
I have no clue what's happening here.  This is really odd.  I'm quite busy trying to get ready for vacation.  So I hope someone else has time to investigate this oddity.  But if no one does, I will try to get to it before I leave this weekend.

The publish process starts with the `Makefile`, running `make release-minor`.

**Comment by semmel** [comment]
Okay I cloned the ramda repo, did a `npm install` and just did a simple `make release-minor`. 
Because  Ramda is using [xyz](https://github.com/davidchambers/xyz) for publishing, which does not work on *MacOS* I had to use my *Ubuntu* machine. 

My published package can be installed with `npm install semmel-ramda`. It contains `src/on.js` and `es/on.js`. So everything seems to be fine.

Where these files got lost in publishing the current release ramda v.0.27.0 I cannot find out on my side. Very strange... 👻  

Hope next release of Ramda includes them and thus – more importantly –  adds `R.on` to the documentation.

**Comment by CrossEye** [comment]
I had no idea that xyz doesn't work on *MacOS*.  @davidchambers: is there some easy way around this?

**Comment by semmel** [comment]
From the xyz homepage:
> macOS users should run brew install bash to install a compatible Bash version

I won't follow that advise, because I can't take the responsibility when switching the Bash could possibly break other shell scripts I rely on in my every day work.

**Comment by davidchambers** [comment]
@semmel, you need not switch to a recent Bash version *permanently* in order to run one command. :stuck_out_tongue_winking_eye:

[v0.27.0][1] was not released correctly: [`"version"` is still `"0.26.1"`][2]. Would you like me to rerelease v0.27.0 as v0.27.1?


[1]: https://github.com/ramda/ramda/releases/tag/v0.27.0
[2]: https://github.com/ramda/ramda/blob/v0.27.0/package.json#L41

**Comment by semmel** [comment]
@davidchambers 
> you need not switch to a recent Bash version permanently in order to run one command.

Good to know, I thought it'd replace the Bash shipped with macOS. Booting Ubuntu VM was however easier for me.

**Comment by CrossEye** [comment]
@davidchambers: If you have time to do that, I would definitely appreciate it.

**Comment by davidchambers** [comment]
<https://github.com/ramda/ramda/releases/tag/v0.27.1>

**Comment by semmel** [comment]
`on.js` seems to be still missing from tag v0.27.1 and the npm package.

Also the implementation is missing from the dist files.
```javascript
var R = require('ramda');
R.on // -> undefined
```

In v0.27 the R.on implementation was still included in the dist files.

**Comment by davidchambers** [comment]
The build tool I created for Ramda was replaced some time ago; I am no longer the right person to debug build issues. :shrug:

It is worth noting that running `npm install` now modifies __dist/ramda.js__, __dist/ramda.min.js__, and __package-lock.json__. I find this behaviour very surprising, and it provides a hint as to what the problem is here.

**Comment by semmel** [comment]
> It is worth noting that running npm install now modifies dist/ramda.js, dist/ramda.min.js, and package-lock.json. I find this behaviour very surprising, and it provides a hint as to what the problem is here.

Yeah [`npm install`](https://docs.npmjs.com/using-npm/scripts#npm-install) triggers `npm prepare` (which is essentially `npm run build`) in local git repo. `npm publish` does this too – at a later point of course.

In the build process it's difficult to disentangle the whole npm lifecycle sequence and git checkout 'n tagging operations sequence performed by xyz to see what is actually happening. Then try to fix it without breaking other stuff... OMG.

**Comment by CrossEye** [comment]
Obviously this build process is going to need some TLC.  I'm leaving Sunday for a two-week vacation and will not get to it before then.  If anyone else wants to take a look, that would be great.  Otherwise I'll look when I get back.

**Comment by sebastienfilion** [comment]
I was looking into this issue today, I need to use the P combinator, realized it was already on Ramda as `on` but was missing from the documentation website. Do we know what's the next step to fix this?

**Comment by semmel** [comment]
@sebastienfilion
Roughly 
1. clone ramda git 
1. `npm install` (This triggers `npm prepare`)
1. `make release-minor` (fine on Linux)
1. [What to do on a new release](https://github.com/ramda/ramda.github.io#what-to-do-on-a-new-release)

**Comment by sebastienfilion** [comment]
@semmel Yes I figured that it is something like that -- I manage a Ramda distro for Deno where we can access the `on` combinator; but I was concerned to update the website. Sadly, I don't have publication right.

**Comment by CrossEye** [comment]
I have several Ramda chores hanging over me.  I will try to get to them this weekend, and that includes republishing the docs.

**Comment by semmel** [comment]
@CrossEye republishing the docs might not be enough for every case.

Because e.g. `on.js` is missing from `es/` and `src/` directories in the published npm package, without a *Ramda release* the situation may occur, that a documentation mentioning `R.on` will not reflect the reality of the published  npm package.
