### ISSUE TITLE
What changed in v0.27.1?

### ISSUE THREAD

**Issue by agriffis** [ramda/ramda#3064]
I empathize with the sentiment here, but it's really not helpful for users...

![image](https://user-images.githubusercontent.com/50637/88944120-5a2cda80-d25a-11ea-8293-ff8823fb578d.png)

**Comment by semmel** [comment]
@agriffis see #3062, afaik nothing but the version number

**Comment by tomkel** [comment]
https://github.com/ramda/ramda/compare/v0.27.0..v0.27.1

**Comment by davidchambers** [comment]
That's right, @semmel. We bungled [v0.27.0][], and corrected the mistake in [v0.27.1][]. As for what changed in [v0.27.0][], I don't know as I'm no longer actively involved in Ramda's development.


[v0.27.0]: https://github.com/ramda/ramda/releases/tag/v0.27.0
[v0.27.1]: https://github.com/ramda/ramda/releases/tag/v0.27.1
