### ISSUE TITLE
Ramda 0.27.1 is broken

### ISSUE THREAD

**Issue by raja-jamwal** [ramda/ramda#3068]
I have a project which has a transitive dependency on ramda, seems like the `npm install` is not happy with ramda 0.27.1. `package.json`. `npm install` failed to parse ramda's `package.json`

```
npm ERR! Unexpected end of JSON input while parsing near '...w1J51z4mM3b3NrGwK5WmG'
```

When I downgraded ramda to `0.21.0`, the npm install worked fine.

**Comment by Bradcomp** [comment]
I just tried a direct install in a fresh repo and didn't run into any issues. 

We'll probably need some more information to troubleshoot this. What is the package that's breaking?

**Comment by ArthurClemens** [comment]
I noticed this too in a [CodeSandbox example](https://codesandbox.io/s/usestream-ramda-filter-w05t2) of mine. Version 0.24.1 works fine, and later versions are broken (R is undefined).

**Comment by CrossEye** [comment]
I'm not really sure what's going on here.  Perhaps it's something that #2999 fixed?  We should publish another version that includes this.

**Comment by zubko** [comment]
The `R is underfined` is another issue. But now Google lists this issue in the search result. For `R is underfined` check:
https://ramdajs.com/#installation
> Note for versions > 0.25 Ramda versions > 0.25 don't have a default export. So instead of import R from 'ramda';, one has to use import * as R from 'ramda'; Or better yet, import only the required functions via import { functionName } from 'ramda';

**Comment by semmel** [comment]
Can't reproduce. Installation works the same as for *any other project*.

https://user-images.githubusercontent.com/296476/118644238-e4d8c900-b7dd-11eb-83d2-1586df94cf66.mp4

This is one of the most reliable projects I've used over years. IMO this issue's title "Ramda 0.27.1 is broken" should be changed or this issue entirely be closed.

**Comment by ArthurClemens** [comment]
Agree. Somehow I and others have missed the notice that default export was removed.
