### ISSUE TITLE
clone non enumerable properties

### ISSUE THREAD

**Issue by felipe-gustavo** [ramda/ramda#3070]
`clone` doen't works with non enumerable properties, such below e.g.:

```js
class e {
  id;
  data;
  constructor(data) {
    this.id = Math.floor(Math.random() * 25);
    this.data = data;
    Object.defineProperty(this, "gTr", {
      enumerable: false,
      value: function () {
        return "it's me " + this.id + "!";
      }
    });
  }
}

const i = new e({ a: 1, b: 2 });
const u = Object.assign(
  Object.create(i),
  Object.getPrototypeOf(Object.create(i))
);
const o = clone(i);

u.id = 28;
u.data.a = 3;
o.data.a = 4;

console.log(
  "i:",
  "   " + (i.gTr && i.gTr()),
  "   " + i.data.a,
  "o:",
  "   " + (o.gTr && o.gTr()),
  "   " + o.data.a,
  "u:",
  "   " + (u.gTr && u.gTr()),
  "   " + u.data.a
);
```

output:
```
i:
   it's me! 23 
   3
o: 
   undefined
   4
u:
   it's me! 28 
   3

```

**Comment by Bradcomp** [comment]
Hi @felipe-gustavo! Thanks for the report!

It looks like we may be able to use [`getOwnPropertyNames`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) to solve this. Would you be interested in submitting a PR?

**Comment by felipe-gustavo** [comment]
@Bradcomp, thank for the quicky answer.

Are you talking about [this row](https://github.com/ramda/ramda/blob/1cd34a0dc028c1eaf44f22b9900c4bde8e1b7848/source/internal/_clone.js#L27)?
![image](https://user-images.githubusercontent.com/55498940/89595162-335a3f80-d82a-11ea-8e84-a07f48096ce2.png)

**Comment by felipe-gustavo** [comment]
> Hi @felipe-gustavo! Thanks for the report!
> 
> It looks like we may be able to use [`getOwnPropertyNames`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) to solve this. Would you be interested in submitting a PR?

This solutions to works with non-enumerables, but the object still lost your constructor, [see here](https://ramdajs.com/repl/?v=0.17.1#?class%20e%20%7B%0A%20%20id%3B%0A%20%20data%3B%0A%20%20constructor%28data%29%20%7B%0A%20%20%20%20this.id%20%3D%20Math.floor%28Math.random%28%29%20%2A%2025%29%3B%0A%20%20%20%20this.data%20%3D%20data%3B%0A%20%20%20%20Object.defineProperty%28this%2C%20%22gTr%22%2C%20%7B%0A%20%20%20%20%20%20enumerable%3A%20false%2C%0A%20%20%20%20%20%20value%3A%20function%20%28%29%20%7B%0A%20%20%20%20%20%20%20%20return%20%22it%27s%20me%20%22%20%2B%20this.id%20%2B%20%22%21%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%29%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20i%20%3D%20new%20e%28%7B%20a%3A%201%2C%20b%3A%202%20%7D%29%3B%0Aconst%20u%20%3D%20Object.assign%28%0A%20%20Object.create%28i%29%2C%0A%20%20Object.getPrototypeOf%28Object.create%28i%29%29%0A%29%3B%0Aconst%20o%20%3D%20clone%28i%29%3B%0A%0Au.id%20%3D%2028%3B%0Au.data.a%20%3D%203%3B%0Ao.data.a%20%3D%204%3B%0A%0Aconsole.log%28%0A%20%20%22i%3A%22%2C%0A%20%20%22%20%20%20gTr%3A%22%20%2B%20%28i.gTr%20%26%26%20i.gTr%28%29%29%2C%0A%20%20%22%20%20%20data.a%3A%22%20%2B%20i.data.a%2C%0A%20%20%22%20%20%20constructor%3A%22%20%2B%20i.constructor.name%2C%0A%20%20%22o%3A%22%2C%0A%20%20%22%20%20%20gTr%3A%22%20%2B%20%28o.gTr%20%26%26%20o.gTr%28%29%29%2C%0A%20%20%22%20%20%20data.a%3A%22%20%2B%20o.data.a%2C%0A%20%20%22%20%20%20constructor%3A%22%20%2B%20o.constructor.name%2C%0A%20%20%22u%3A%22%2C%0A%20%20%22%20%20%20gTr%3A%22%20%2B%20%28u.gTr%20%26%26%20u.gTr%28%29%29%2C%0A%20%20%22%20%20%20data.a%3A%22%20%2B%20u.data.a%2C%0A%20%20%22%20%20%20constructor%3A%22%20%2B%20u.constructor.name%20%0A%29%3B) a example.
![image](https://user-images.githubusercontent.com/55498940/89596010-892fe700-d82c-11ea-9e2c-7f67efabafc5.png)

**Comment by felipe-gustavo** [comment]
@Bradcomp, maybe add [`Object.create`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) if the value to be cloned is a object resolve this issue, see below example:

![image](https://user-images.githubusercontent.com/55498940/89659177-e025d280-d8a5-11ea-85cb-d22e99c27d93.png)

**Comment by felipe-gustavo** [comment]
I recently opened this pull request( #3072 ) to resolve this problem, @Bradcomp, can you analysys this PR?
