### ISSUE TITLE
[Question] Where is the ramda logo in the code?

### ISSUE THREAD

**Issue by apendrich** [ramda/ramda#3071]
Hi! I'm looking to use ramda, and was checking the readme and saw the comment in there that the logo is under creative commons. Please can someone let me know where in the codebase the logo is? I've been hunting around,  but failed to find it  so far. I want to work out if I'd be using to to make sure I attribute it correctly if I do. 

Thanks!

**Comment by buzzdecafe** [comment]
* [logos](http://ramda.jcphillipps.com/logo/) 
* [license](http://ramda.jcphillipps.com/logo/LOGO_LICENSE.html)

**Comment by apendrich** [comment]
Thanks @buzzdecafe, that's just want I needed! It's in a separate repository, not here in github with the main ramda package. No wonder I didn't find it here!

Thanks for your help!
