### ISSUE TITLE
Add webhook to update Deno default registry

### ISSUE THREAD

**Issue by sebastienfilion** [ramda/ramda#3074]
I would be very thankful if someone who has the permission could add a webhook to the Deno default registry. 🙏 

Here are the instruction as I understand them:
  * Go to the Settings tab.
  * Click on the Webhooks tab.
  * Click on the Add webhook button.
  * Enter the URL `https://api.deno.land/webhook/gh/ramda?subdir=source%2F` in the payload URL field.
  * Select application/json as the content type.
  * Select Let me select individual events.
  * Select only the Branch or tag creation event.
  * Press Add webhook.

**Comment by customcommander** [comment]
Suppose we'll know next time we make a release? Closing for now if that's case.
