### ISSUE TITLE
potential bug with composeWith signature 

### ISSUE THREAD

**Issue by woss** [ramda/ramda#3075]
hi guys, is this a bug?
the code from the npm @types/ramda says this

```ts
export function composeWith<V0, T> (
  composer: (a: any) => any,
  fns: ComposeWithFns<V0, T>
): (x0: V0) => T
```

and the example says this (https://ramdajs.com/docs/#composeWith)
```ts
const composeWhileNotNil = R.composeWith((f, res) => R.isNil(res) ? res : f(res));

composeWhileNotNil([R.inc, R.prop('age')])({age: 1}) //=> 2
composeWhileNotNil([R.inc, R.prop('age')])({}) //=> undefined
```

typescript is complaining and there is NO way to circumvent this without changing the signature to this:
```ts
export function composeWith<V0, T> (
  composer: (a: any,  r?: any) => any,
  fns: ComposeWithFns<V0, T>
): (x0: V0) => T

```
Please advise, if this i the correct approach then i will make a PR or one of the maintainers can fix it when they can

**Comment by CrossEye** [comment]
@woss:

There is no real plan... that's part of the problem.  I squeeze a few hours in for Ramda between family, work, other personal side projects, the horse farm my family runs, etc.  And I'm pretty sure all the other regulars are the same way.

We are definitely *not* moving the library to Typescript.  But we would like to move the typings files in-house.  You can follow that effort in #2976.  And the people working on that would probably like to see what you've done.

Thank you very much for the contribution.  Though we don't know exactly how yet, it will be used somehow to support Ramda.
