### ISSUE TITLE
without() is removing all elements - a bug or intention?

### ISSUE THREAD

**Issue by zatziky** [ramda/ramda#3086]
Hello,

I would expect this call `R.without("0:1", ["0", "0:1"])` to return `["0"]`.
The actual result is `[ ]`.

Is `:` causing `without()` to behave like a transducer?

**Comment by Bradcomp** [comment]
`without` takes a list of items as its first parameter. 

`R.without(["0:1"], ["0", "0:1"])` returns `["0"]`

**Comment by zatziky** [comment]
@Bradcomp Ok, so you are confirming a bug. :-)

Ramda version used is `0.27.1`.

![image](https://user-images.githubusercontent.com/2794365/93789835-a3822080-fc32-11ea-9b52-7f531d4cad1d.png)

**Comment by Bradcomp** [comment]
The signature of `without` is `[a] -> [a] -> [a]`

When it is called with something other than an array as the first parameter the behavior is undefined. 

Both "0" and "0:1" are string, not `[string]`. 

The most likely reason for this behavior is that `indexOf` works on both strings and arrays. So it doesn't crash when it's passed an invalid parameter in the first position and instead just returns a result based on the string behavior of indexOf.

If you wrap the first parameter in an Array like suggested above, the function works as expected.

**Comment by zatziky** [comment]
@Bradcomp True. It's a nice explanation.

Not sure if Ramda does validate inputs. If so, isn't it worth to validate that the input param is actually an array?

**Comment by adispring** [comment]
> @Bradcomp True. It's a nice explanation.
> 
> Not sure if Ramda does validate inputs. If so, isn't it worth to validate that the input param is actually an array?

@zatziky Ramda will optimize its Error Messaging and Type-Checking, and here is the related issue: https://github.com/ramda/ramda/issues/2998
