### ISSUE TITLE
Repl doesn't load

### ISSUE THREAD

**Issue by SeeThruHead** [ramda/ramda#3089]
waiting for bundle.run...

no errors. 
Seeing in latest chrome

**Comment by CrossEye** [comment]
Yeah, it's been on the list for a while.  I'll see if I have time tonight.  In the meantime, you can probably just stop the loading.  In Chrome and Firefox dev the `refresh` icon is an X when it's still loading.  If I click that, it's stops bothering with the two inessential loads.

**Comment by customcommander** [comment]
@CrossEye Is this an issue that could be transferred to the repl repository?

**Comment by CrossEye** [comment]
Actually, it was dealt with there and I'll just close this.
