### ISSUE TITLE
Can't import Ramda from Deno: 404 Not Found

### ISSUE THREAD

**Issue by jerrygreen** [ramda/ramda#3091]
> Might be related to https://github.com/ramda/ramda/issues/3090, but this one has a different error (so might be not related)

I get 404 error:

```
$ deno run https://gist.github.com/JerryGreen/9583a1054e90e89d2da6aaf4ad0b6fee/raw/c2aec40cbeebf0553ec7289762a72a6fd4e7fe5a/test-difference2.ts
Download https://gist.github.com/JerryGreen/9583a1054e90e89d2da6aaf4ad0b6fee/raw/c2aec40cbeebf0553ec7289762a72a6fd4e7fe5a/test-difference2.ts
Download https://gist.githubusercontent.com/JerryGreen/9583a1054e90e89d2da6aaf4ad0b6fee/raw/c2aec40cbeebf0553ec7289762a72a6fd4e7fe5a/test-difference2.ts
Download https://deno.land/x/ramda@v0.27.1/internal/_curry2
Download https://deno.land/x/ramda@v0.27.1/internal/_Set
error: Import 'https://deno.land/x/ramda@v0.27.1/internal/_curry2' failed: 404 Not Found
Imported from "https://deno.land/x/ramda@v0.27.1/difference.js:1"
```

It seems it's related to inability to import without extension (was this ever possible in Deno?):

https://github.com/denoland/deno/issues/2506

Try it yourself:

```
deno run https://gist.github.com/JerryGreen/9583a1054e90e89d2da6aaf4ad0b6fee/raw/c2aec40cbeebf0553ec7289762a72a6fd4e7fe5a/test-difference2.ts
```

**Comment by sebastienfilion** [comment]
The error occurs because `https://deno.land/x/ramda@v0.27.1/internal/_curry2` is not a valid URL.

https://github.com/ramda/ramda/issues/3090#issuecomment-699109302

**Comment by sebastienfilion** [comment]
@Bradcomp sorry to ping you again. Can you help me figure out why the extensions are stripped in the release package? https://github.com/ramda/ramda/issues/3090#issuecomment-699109302
