### ISSUE TITLE
Replace (for lists), adjustWhen, adjustAll, updateWhen

### ISSUE THREAD

**Issue by KayaLuken** [ramda/ramda#3097]
**replace (for lists)**
`replace(1, 2, [1, 1, 1]) // [2, 1, 1]`

**replaceAll**
`replaceAll(1, 2, [1, 1, 1]) // [2, 2, 2]`

**adjustWhen**
`adjustWhen(equals(1), inc, [1, 1, 1]) // [2, 1, 1]`

**adjustAll**
`adjustAll(equals(1), inc, [1, 1, 1]) // [2, 2, 2]`

**updateWhen**
`updateWhen(equals(1), 2, [1, 1, 1]) // [2, 1, 1]`

**updateAll**
`updateAll(equals(1), 2, [1, 1, 1]) // [2, 2, 2]`

I was surprised that `replace` didn't already exist for lists. This is a function that I have reached for several times and seems fundamental to me. If `without` and `filter/ find` are the D and R in CRUD operations on lists targetting specific values, `replace` (and the other functions listed) would be the U.

`adjustWhen` etc are particularly useful for nested data structures like lists of objects (extremely common use case).

Compare 

`const people = [{name: 'Jane', age: 20}, {name: 'John', age: 20}]`

```
const changeJanesAge = chain(
    adjust(__, assoc('age', 21),
    findIndex(propEq('name', 'Jane'))
)
```
to
```
const changeJanesAge = adjustWhen(
    propEq('name', 'Jane'),
    assoc('age', 21)
)
```

Yes, its the same LOC, but consider the mental hurdles you have to overcome to understanding and using the first compared to the second.

1. you have to be comfortable with the fact that chain acts on functions courtesy of the function monad (barely documented)
2. you have to parse 2 functions,  2 nested functions and a placeholder, instead of 2 simple function calls
3. you have read in reverse order and remember that chain happens to take a 2 arity function as first argument for obscure reasons that a layperson isnt going to know

For the second its simply maps to the problem.
1. find Jane 2. change her age

If theres a easier way already feel to correct me.

**Comment by CrossEye** [comment]
These are interesting, and I think certainly worthy of consideration.

I find the `*All` versions more compelling than their `all`-less companions.  Do you have strong use-cases for wanting to alter only the first element of a list that matches a predicate?

**Comment by KayaLuken** [comment]
No. The *all versions are probably more useful.

**Comment by CrossEye** [comment]
Are you interested in creating a PR for this?
