### ISSUE TITLE
pipeN

### ISSUE THREAD

**Issue by Levino** [ramda/ramda#3098]
I recently wanted to create a pipe but needed to wait for the last function to pipe through. So instead of
```typescript
R.pipe(f,g)(x)
```
I needed to do:
```typescript
R.pipeN(2,f)(g)(x)
```
Is there some equivalent for `R.pipeN(2)` (should be a function which takes a function `f` and returns a function which takes a function `g` and returns a function which takes an argument x and returns `g(f(x))`)

**Comment by Levino** [comment]
Signature maybe should be: `(((a, b, …, n) → o), (o → p), …, (x → y)) → ((y → z)) → ((a, b, …, n) → z)` Does this make sense?

**Comment by CrossEye** [comment]
I don't think there's anything close right now.  I'd be curious to hear of some use-cases, as I don't personally recall every needing this, but it is an interesting concept.

Note that there is a binary, curried version of `compose`, in `o`, which would serve for the case of `composeN(2)`.  But there isn't a `pipe` version of this.

**Comment by Bradcomp** [comment]
Is there anything wrong with using `curryN` with `pipe` or `compose`? That seems more straightforward than writing a new function here: 

```
const pipe3 = curryN(3, pipe)

pipe3(inc)(inc)(inc)(5) // 8
```

**Comment by Levino** [comment]
Sounds good enough. That is exactly the "equivalent" I was looking for. Thank you @Bradcomp
