### ISSUE TITLE
Documentation how composeWith deprecates composeP

### ISSUE THREAD

**Issue by vinnichase** [ramda/ramda#3099]
I have this super useful composition of async and sync functions:

```JS
import * as R from 'ramda';
import { promises as fs } from 'fs';

await R.composeP(
    console.log,
    JSON.parse,
    R.toString,
    fs.readFile,
)('path/to/file');
```

I did not manage to transfer the same behavior to `composeWith` which should replace `composeP`. Can someone point me to the documentation with an example?

**Comment by CrossEye** [comment]
You need to wrap the arguments to `pipeWith(yourFunction(` or `composeWith(yourFunction)` in an array.  

The idea is that `R.composeWith (R.andThen)` does what `composeP` did, except that it now requires an array.  (We don't want to add any new variadic functions to Ramda.)

So that should be 

```js
await R.composeP (R.andThen) ([
    console.log,
    JSON.parse,
    R.toString,
    fs.readFile,
]) ('path/to/file');
```

----------

You're right that this should be in the documentation.  Are you interested in creating a PR to add additional JSDoc examples for this?

**Comment by vinnichase** [comment]
cool thx! Yes When I find the time I will look for a PR to update the docs. So you mean
```JS
await R.composeWith (R.andThen) ([
    console.log,
    JSON.parse,
    R.toString,
    fs.readFile,
]) ('path/to/file');
```
> not `composeP`

Why don't you want to introduce new variadic fns? I mean I get it in general but in this case I would prefer consistency to the known compose/pipe functions.

**Comment by CrossEye** [comment]
Yes, sorry, I meant `composeWith`.

We'd prefer consistency too, and sometime after v1.0, I'm hoping we'll make `compse` / `pipe` match this.   We'd really like to have *no* variadic functions remaining in the library.

**Comment by vinnichase** [comment]
Yeah totally. That would also help typing the whole library perfectly with TypeScript.

**Comment by CrossEye** [comment]
Pinging @vinnichase: Are you still interested in writing a PR for this?  If so, the documentation is generated from the JSDocs tags in the source file.

**Comment by customcommander** [comment]
@CrossEye @vinnichase As I am not sure whether our documentation site can support multiple examples and whether it makes sense to document this in the latest version of the manual (we don't have `composeP` anymore), I chose to simply put this as a comment to #3218 for now.

Hope that's ok.
