### ISSUE TITLE
REPL is not working.

### ISSUE THREAD

**Issue by hmust92** [ramda/ramda#3102]
The REPL is broken. Noticed it last week and seems like it still hasn't been fixed.

This is what I see in the consle:
`Uncaught SyntaxError: Invalid or unexpected token bundle.js:54`
`Uncaught ReferenceError: ramdaRepl is not defined`
`at ?v=0.27.0:83`
`at ?v=0.27.0:141`

**Comment by CrossEye** [comment]
Can anyone else confirm?  It seems to be working fine for me (tested in Chrome/Windows and Brave/Android.

**Comment by hmust92** [comment]
Interesting - it has started working for me in incognito mode on chrome. 

Tried clearing application storage on my regular chrome browser and refreshing but it still doesn't work. If no one else runs into the same issue I can try reinstalling chrome again and checking to see if it works.

**Comment by hmust92** [comment]
Emptying cache and doing a hard reload has made it work for me again. Going to close this issue now.

**Comment by CrossEye** [comment]
Hmm, I wonder what it was.  Thanks for the report and for the followup!
