### ISSUE TITLE
Intersperse with index

### ISSUE THREAD

**Issue by codingedgar** [ramda/ramda#3104]
Is there a way to add index to interperse?

My use case is adding a divider to a list of jsx elements, reactjs asks each element to have `key`, intersperse is perfect but I cannot find a way to add an `key`.

**Comment by CrossEye** [comment]
I'm afraid Ramda has nothing built in; it's not a use-case I think we ever considered.

But it should be rather easy to write your own.  Something like this, perhaps:

```js
const intermingle = (fn) => (xs) => 
  xs .flatMap ((x, i) => i == 0 ? [x] : [fn(i), x])

intermingle((idx) => `divider-${idx}`)(['a', 'b', 'c', 'd'])
  //=> ["a", "divider-1", "b", "divider-2", "c", "divider-3", "d"]
```

or this, depending on what you want for an index, perhaps this:

```js
const intermingle = (fn) => (xs) => 
  xs .flatMap ((x, i) => i == 0 ? [x] : [fn(2 * i - 1), x])

 intermingle((idx) => `divider-${idx}`)(['a', 'b', 'c', 'd'])
   //=> ["a", "divider-1", "b", "divider-3", "c", "divider-5", "d"]```

**Comment by codingedgar** [comment]
Thank you, that is exactly what I ended up doing, using native `flatMap`, glad to have thought the same.

**Comment by rossng** [comment]
I encountered the same problem in our React app. Here's the `intermingle` I came up with:

```ts
function intermingle<T>(fn: (idx: number) => T) {
    function inner(xs: ((idx: number) => T)[]) {
        return xs.flatMap((x, i) => (i === 0 ? [x(0)] : [fn(2 * i - 1), x(2 * i)]));
    }
    return inner;
}
```

The main reason for doing it this way was just so that all the indices were calculated and passed by `intermingle` itself.

And here's an example of usage:

```tsx
intermingle((idx) => <span key={idx}>&nbsp;/&nbsp;</span>)(
    icons.map(
        (ic) =>
            function ButtonIcon(idx: number) {
                return <FAIcon key={idx} iconStyle={iconStyle} icon={ic} />;
            }
    )
)
```
