### ISSUE TITLE
Add "modify" and "modifyPath" that applies a function to a property or path of an object

### ISSUE THREAD

**Issue by daniel7grant** [ramda/ramda#3106]
This issue proposes the addition of a new function to the default Ramda library.

## Proposal

Introduce a new pair of functions to the library that makes it possible to change a property (or path) of an object by applying a function to the value. It should change the value at the property (or path) on the passed object immutably, while maintaining referential equality for all other properties. If the property (or path) does not exist, or the last parameter is not an object or array, the function returns the input value unchanged.

The proposed name is `modify` and `modifyPath`, with the signatures:

```
modify ::     Idx -> (v -> v) -> {k: v} -> {k: v}
modifyPath :: [Idx] -> (v -> v) -> {k: v} -> {k: v}
```

## Motivation

Piggybacking off of the issue #2317, I feel like there is a missing link in the library for applying functions to a property or path of an object.

Consider how you can read and update list, objects, and through lenses.

| | List | Object | Lens |
|--|:--:|:--:|:--:|
|retrieve data | `nth` | `prop / path` | `view` |
|set data | `update` | `assoc / assocPath` | `set` |
|apply fn to data | `adjust` | ??? / ??? | `over` |

There is no simple way to change a value of a property with a function. Currently it can be done either using `over . lensProp` or `evolve`, hovewer these feel clunky comparing to, for example, `adjust`.

In the original issue, the new function is contrasted to `evolve({ [prop]: newVal })`. It is correct that functionally the two is the same, however `evolve` seems overkill for a simple update on one property. Consider saying that `merge({ [prop]: newVal })` offers the same functionality as `assoc(prop, newVal)`, when it is apparent that the latter feels more intuitive, and reduces the mental overhead. Adding a `modify` would also play nicely with the introduction of `modifyPath`, which just feels way more natural than `evolve({ prop1 : { prop2 : { /* ... */ }}})`, and provides updates with dynamic path generation.

So this change would mostly be syntactic sugar, however it would also give the additional benefit of partial application. Similarly how `assoc(prop)` can be used to create multiple updates, `modify(prop)` could be applied to create multiple function updates.

### Basic usage
```js
const person = { name: 'James', age: 20, pets: ['dog', 'cat'] };
R.modify('age', R.add(1), person); //=> { name: 'James', age: 21, pets: ['dog', 'cat'] }
R.modify('pets', R.append('turtle'), person); //=> { name: 'James', age: 20, pets: ['dog', 'cat', 'turtle'] }
```

### Deep update with dynamic path
```js
const binaryTree = { left: { left: 'a', right: { left: 'b', right: 'c' } }, right: { left: { left: 'd', right: 'e' }, right: 'f' } };

const index = 5;
const binaryIndex = index.toString(2); //=> "101"

R.modifyPath(R.map(R.nth(R.__, ['left', 'right']), binaryIndex), R.concat('g'), binaryTree);
  //=> { left: { left: 'a', right: { left: 'b', right: 'c' } }, right: { left: { left: 'd', right: 'ge' }, right: 'f' } }
```

### Partial application
```js
const post = { title: 'Post', points: 1 };
const vote = R.modify('points');
const upvote = vote(R.inc);
const downvote = vote(R.dec);

upvote(post); //=> { title: 'Post', points: 2 };
downvote(post); //=> { title: 'Post', points: 0 };
```

**Comment by CrossEye** [comment]
That grid is quite convincing. 

When I saw the title, my first thought was, "we already have `over` -- why do we need more?"  But this grid makes it clear.

I would love to see a PR for this.  Are you interested in creating one?

**Comment by daniel7grant** [comment]
Thanks, Scott, I'm glad I could make my point clear.

I would love to contribute, I'll try to come up with an implementation over the weekend.

**Comment by semmel** [comment]
I would like to add `assoc` to another cell in the nice grid to make it complete.

  | List | Object | Lens
-- | -- | -- | --
retrieve data | nth | prop / path | view
set data | update / *assoc/assocPath* | assoc / assocPath | set
apply fn to data | adjust | ??? / ??? | over

Since #2787 `assoc` and `assocPath` work on arrays. (Which is nice because it corresponds to my mental model that arrays in JS are not so different from objects just with integer keys.)

Otherwise I think the proposed `modify`/`modifyPath` address one of the few blind spots ramda still has. I am looking forward to using those.

**Comment by daniel7grant** [comment]
Thanks, Matthias, I think you are making a very valid adjustment to the grid.

To simplify my explanation, I purposefully omitted the modifications of arrays, as there is already a function for that. However, if you note the proposed signature, it uses the standard `Idx` notation, which means it should work for both objects and arrays. In my view `modify(0)` and `adjust(0)` should and will be equivalent.

I mostly agree that mental model that arrays are just spicy objects (partly because it is also the real model in JavaScript, see `typeof []`). In this regard I think Ramda should move in the direction of thinking objects and arrays alike, when we modify them, and use arrays more in the way of iterators (e.g. `map`, `filter`, `find`).

**Comment by daniel7grant** [comment]
@CrossEye I am not really familiar with TypeScript, I don't know how the new function should be handled to have TypeScript signatures. Can you please help with this?

Otherwise, I think this (and probably the referenced issue) can be closed.

**Comment by CrossEye** [comment]
@daniel7grant:

The Typescript typings are still maintained independently by other projects.  There is some movement to bring them in-house, but we're not there yet.  @hitmands: do we have any updates on this?

So I don't think there's anything to do here.

**Comment by hitmands** [comment]
Hi, 
we once agreed that ts typings would be outside of the `DoD` for new feature development, 
this to facilitate contributions.

I'd suggest to descope ts definitions from this pr, 
and yes, as @CrossEye said, they're still on a separate repo in `@types/` project.

We're trying to bring them in, 
but still it's difficult to reach out to maintainers...

**Comment by semmel** [comment]
I just noticed that `modify(key, f)` ≅ `chain(assoc(key), o(f, prop(key)))`, so I need to revert my previous remark Ramda had a blind spot for this type of operation.

However #3107 is merged and hopefully useful for many. 

I am just always skeptical about discoverability of functions in Ramda' vast API.

**Comment by CrossEye** [comment]
@semmel:

> I am just always skeptical about discoverability of functions in Ramda's vast API.

That's a serious concern, and I still don't have any great answers for it.  I'd love to hear some suggestions.

On the flip side, I don't think it's a horrifying issue, as this has always been meant as a grab-bag library.  That you did something other than use the most appropriate Ramda function is not any sort of tragedy.  Maybe if someone points it out, you can use it next time.

**Comment by customcommander** [comment]
Closing for now as #3107 has been merged.
