### ISSUE TITLE
Add `splitEvenly`

### ISSUE THREAD

**Issue by vicrac** [ramda/ramda#3113]
I'd love seeing a version of `splitEvery` that excludes the last chunk it it'd be shorter than others. My particular use case is I don't want to display the final week of a given time period if it's missing some days, but I think there are several UI (and others!) use cases for that.

My current solution is:
```ts
export const splitEvenly = <T>(data: Array<T>, n: number): Array<Array<T>> =>
  R.splitEvery(n, data.slice(0, Math.floor(data.length / n) * n))
```

**Comment by CrossEye** [comment]
This is there first request I've seen for this behavior.

It certainly is a reasonable function, but I'd like to see more support for it before committing to including it.

After there strong reasons this belongs in Ramda itself rather than in the Cookbook?

**Comment by vicrac** [comment]
Well, for me it feels like this could be the default behavior actually - it makes stronger assumptions on the output (_if I pass it through this function, I can be sure the groups will be of same size_). Also, my implementation, simple as is, is slightly innefficient - it traverses the list twice instead of once and that's something I'd have to use some more complicated stuff to bypass (`reduceWhile`?) or some imperative `while` loop, whereas if included it will be nicely hidden.

Also (just a personal note) it's actually the only one such generic function in my project I missed so much (and use so much) I extracted it to `common/helpers` 😂

**Comment by CrossEye** [comment]
I can't see it being the default behavior, not when it throws away information.

I can certainly imagine cases where it might be useful.  My reluctance stems from wondering just how widespread the need would be.  As I said, this is the first request I remember for this functionality.

Ramda has to constrain its growth, so we always need to balance between how widely useful a function is and how difficult or easy it is for users to create their own versions of it.  This one is easy enough to write on our own, so the question then is whether the need is wide enough to add it to Ramda.

**Comment by vorticalbox** [comment]
I have used this sort of function a few times now would be nice to support it. if we move the data to the last arg we could do something like this

```
function splitEvenly(n: number): <T>(data: T[]) => Array<Array<T>>
function splitEvenly<T>(n: number, data: T[]): Array<Array<T>>
function splitEvenly<T>(n: number, data?: T[]) {
  return data
    ? R.splitEvery(n, data.slice(0, Math.floor(data.length / n) * n))
    : (data: T[]) => R.splitEvery(n, data.slice(0, Math.floor(data.length / n) * n))
}

const data = [1,2,3,4,5,6]
const  chunk3 = splitEvenly(3)
chunk3(data) // [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
splitEvenly(3, data) // [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]

```
