### ISSUE TITLE
Is transducer's map method actually a contramap?

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#3115]
The signature of `map` is `Functor f => (a → b) → f a → f b`, which means take a transform function `a → b` and a Functor `f a`, using `a → b` transform `a` of `f a` to `b`, and return `f b`. Here's an example:

```js
const isGoodEnough = score => score >= 80;
const scores = [75, 97, 86]

const scoreLevels = R.map(isGoodEnough, scores);
//=> [false, true, true]
```

But I found that, when using `R.map` to create a transducer, the signature of `R.map` changed:

```js
// transformer -> reducer -> reducer
// (b -> a) -> ((acc, a) -> acc) -> ((acc, b) -> acc)
// (b -> a) -> f a -> f b

// a simplified map transducer
const map = R.curry((transformer, reducer) => (acc, item) => {
  const transformedItem = transformer(item);
  const result = reducer(acc, transformedItem);
  return result;
});
```

If consider reducer as a functor, 
then `f a` in reducer is: `(acc, a) -> acc`, 
and then `R.map`'s signature is actually: `(b -> a) -> ((acc, a) -> acc) -> ((acc, b) -> acc)`, 
and more general:  `(b -> a) -> f a -> f b`, which is contramap's signature.

Here's an example using map to create a transducer: 

```js
// number -> boolean
const isGoodEnough = ({ score }) => score >= 80;

// (acc, boolean) -> acc
const booleanReducer = (acc, item) => acc && item;

// (acc, number) -> acc
const isGoodEnoughReducer = transducerCreator(isGoodEnough, booleanReducer)

// [number] -> boolean
const isAllGoodEnough = R.reduce(isGoodEnoughReducer, true)

isAllGoodEnough([75, 97, 65]) //=> false
```

The above example takes `isGoodEnough` (number -> boolean) and `booleanReducer`((acc, boolean) -> acc), then creates another reducer -- `isAllGoodEnoughReducer`((acc, number) -> acc).

And I found something about "map vs contramap" in [stackoverflow](https://stackoverflow.com/questions/48587361/what-is-the-purpose-of-contramap):

> Whereas in Haskell, one can think of a value of type f a (for which f is a Functor) as containing or producing a values, a contravariant functor f gives rise to values of type f a that can be thought of as consuming a values.

So, transducer's map method is actually a contramap?

**Comment by CrossEye** [comment]
I'd have to dig into the transducer implementation to get a good sense of it again.

There is always a lot of confusion over the order of transducer composition, and I wonder if this is a related question.  But not until I dig in deeper will I be sure I really even understand the question.

**Comment by CrossEye** [comment]
@adispring: Did you ever answer this to your own satisfaction?

**Comment by adispring** [comment]
I think my analyze above is correct. And it's ok to keep current name unchanged.
