### ISSUE TITLE
is Number Not working on NaN

### ISSUE THREAD

**Issue by ashrash290** [ramda/ramda#3120]
NaN is Not a number

is(Number, NaN) returns true. 

This should return false.

**Comment by semmel** [comment]
typeof NaN === 'number'

**Comment by Bradcomp** [comment]
`NaN` is a floating point number based on the floating point spec that JS bases its numbers on. Its type is number, its value is Not A Number. 

https://en.wikipedia.org/wiki/IEEE_754

**Comment by CrossEye** [comment]
`NaN` has been a thorn in JS's side for a long time.  But this behavior seems the most consistent.

The question from @semmel is a good one, I think.  For every non-`null` value, `val`, we would expect that there is at least one type, `T` such that `is (T, val)` returns `true`.  `Number` is the right type for `NaN`.

**Comment by ashrash290** [comment]
@Bradcomp I agree that JS gives you "number" for typeof(NaN). But when i'm going for a functional library like ramda in my project i would like ramda to provide some function to check if it is NaN.

**Comment by CrossEye** [comment]
@ashrash290:

Would `equals (NaN)` do for your uses? 

```js
equals (NaN) (NaN) //=> true
equals (NaN) (0/0) //=> true
equals (NaN) ('abc') //=> false
equals (NaN) (42) //=> false
equals (NaN) (null) //=> false
equals (NaN) (undefined) //=> false
```

**Comment by ashrash290** [comment]
@CrossEye Got it thanks !
