### ISSUE TITLE
Is there any function works like R.path but return undefined with negative index?

### ISSUE THREAD

**Issue by suienzan** [ramda/ramda#3124]
It's wired that R.path will accept negative index but R.hasPath does not.

```javascript
R.hasPath(["a", "b", -1], { a: { b: [1, 2, 3] } }); // => false

R.path(["a", "b", -1], { a: { b: [1, 2, 3] } }); // => 3
```

In the folllowing case. I tried to replace

`obj && obj.a && obj.a.b && obj.a.b[types.indexOf(type)]`

with

`R.path(['a', 'b', types.indexOf(type)], obj)`

and find it works different. I expect it return `undefined` but it's not.

```javascript
import { path } from "ramda";

const types = ["foo", "bar"];

const obj = {
  a: {
    b: ["fooObj", "barObj"],
  },
};

// const getObj = (type) => obj && obj.a && obj.a.b && obj.a.b[types.indexOf(type)];
const getObj = (type) => path(['a', 'b', types.indexOf(type)], obj);

// expected return undefined
getObj('baz'); // => 'barObj' 
```

I searched the API documentation but didn't find anything helps. Did I miss something?

**Comment by sebastienfilion** [comment]
Hey! I'm not to sure what you're expecting to happen but have you tried to test your type first?

```js
const getObj = type => types.indexOf(type) && path(['a', 'b', types.indexOf(type)], obj);
```

**Comment by suienzan** [comment]
In the code above `types.indexOf(type)` would be `["foo", "bar"].indexOf('baz') // => -1' `

**Comment by adispring** [comment]
@suienzan You can refer this issue: https://github.com/ramda/ramda/issues/3007

**Comment by sebastienfilion** [comment]
> In the code above `types.indexOf(type)` would be `["foo", "bar"].indexOf('baz') // => -1'`

Yes, and therefore it's falsy `-1 && true === true`;
Maybe there's something I'm missing, I want to understand. 🤔

**Comment by suienzan** [comment]
> 
> 
> > In the code above `types.indexOf(type)` would be `["foo", "bar"].indexOf('baz') // => -1'`
> 
> Yes, and therefore it's falsy `-1 && true === true`;
> Maybe there's something I'm missing, I want to understand. 🤔

It's `-1 && 'barObj'`

In my project, I get `obj` and `type` from backend. I want to use `getObj` to get the object in `obj.a.b` safely.

If I use `const getObj = (type) => path(['a', 'b', types.indexOf(type)], obj);`

Then `getObj(anythingElseButFooOrBar)` will return `'barObj'` while I expect to be `undefined`

**Comment by sebastienfilion** [comment]
I see, so something like this would be an acceptable alternative?

```js
const getObj = type => types.indexOf(type) ? path(['a', 'b', types.indexOf(type)], obj) : undefined;
```

**Comment by suienzan** [comment]
> 
> 
> I see, so something like this would be an acceptable alternative?
> 
> ```js
> const getObj = type => types.indexOf(type) ? path(['a', 'b', types.indexOf(type)], obj) : undefined;
> ```
Yes. It will has the right behavior but no more readable than

```javascript
const getObj = (type) => obj && obj.a && obj.a.b && obj.a.b[types.indexOf(type)];
```

I wonder if there have something like `pathPositiveIndex` with return `undefined` when getting negative index from array so I can write like this
```javascript
const getObj = (type) => pathPositiveIndex(['a', 'b', types.indexOf(type)], obj);
```

**Comment by sebastienfilion** [comment]
> Yes. It will has the right behavior but no more readable than

But it feels likes an oddly specific use case; there are more "ramda workarounds". 

```js
import { always, equals, flip, indexOf, pipe, path, when } from "ramda";

const indexOfOrUndefined = pipe(indexOf, when(equals(-1), always(undefined)));
const getTypeIndex = flip(indexOfOrUndefined)(types);

const getObj = (type) => path(['a', 'b', getTypeIndex(type)], obj);

// expected return undefined
console.log(getObj('foo')); // => 'fooObj'
console.log(getObj('baz')); // => undefined
```

**Comment by sebastienfilion** [comment]
Also, because I don't know your exact use case; you might want to look into `pathOr` https://ramdajs.com/docs/#pathOr

**Comment by suienzan** [comment]
Your code above looks nice. 

`pathOr` has no help with my case. `hasPath` would works as what I want if it returns the value of the path. 

I just found `R.hasPath(["a", "b", -1], { a: { b: [1, 2, 3] } })` will return `false`, but with the same arguments `R.path` will not return undefined. It make me wired.

**Comment by sebastienfilion** [comment]
Yes but technically you'd loop over twice. Easier to just do it once and deal with the result appropriately.

**Comment by adispring** [comment]
> I just found `R.hasPath(["a", "b", -1], { a: { b: [1, 2, 3] } })` will return `false`, but with the same arguments `R.path` will not return undefined. It make me wired.

`R.path` can handle both Object and Array(including negative index) recursivly, because `R.path` handle negative index specially. But `R.hasPath` does not handle negative index specially, so it can not handle Array with negative index.

Refer this issue to see more detail: https://github.com/ramda/ramda/issues/3007

**Comment by adispring** [comment]
The ability of handling negative index maybe remove from `R.path` in the future.

**Comment by suienzan** [comment]
I'm clear about my question now. Thank you all for your help. You can close this issue.
