### ISSUE TITLE
Make list methods compatible with native js implementation

### ISSUE THREAD

**Issue by Shastel** [ramda/ramda#3127]
Hi all,
I was implementing some stuff using [`R.find`](https://ramdajs.com/docs/#find)/[`R.findIndex`](https://ramdajs.com/docs/#findIndex) and what I noticed, is that callbacks for such function do not compatible with the native implementation of such methods.

Intuitively I was expecting a callback to handle an item, index, and collection as arguments, instead, all ramda implementations using only an item.

So I was wondering if it intentional implementation? Because from my point of view it might be useful for some cases.

**Comment by CrossEye** [comment]
Oh, this is very intentional.  See the knock-down, drag-out fight in #452 for a long discussion about why.

If you need these, you might look at [addIndex][ai], which offers one solution.

  [ai]: https://ramdajs.com/docs/#addIndex

**Comment by Shastel** [comment]
Thank you very much!
