### ISSUE TITLE
Please help me understand arity implementation

### ISSUE THREAD

**Issue by kfrp** [ramda/ramda#3130]
What is the purpose of these enumerated cases [here](https://github.com/ramda/ramda/blob/cbc65c7f311a366aa3618a18c1a439a72f482218/source/internal/_arity.js#L1)? Doesn't the code work the exact same way in all the cases? The arguments are named but the names are never referenced in the function as far as I can tell.

Please help me understand what I'm missing, as I'm still figuring frp out. Thanks!

**Comment by sebastienfilion** [comment]
That's a loaded question 😆. That's a utility that is used by many other functions to return a function with the correct argument length; I guess the most obvious example of that is `curryN` https://ramdajs.com/docs/#curryN
Just to be certain we have a common language, can you tell me if you understand currying?

**Comment by kfrp** [comment]
Thanks for your reply. Yes, I am familiar with currying. I also understand ramda implementions of _curry1, _curry2 and _curryN. These are all very powerful. But within those, there is always an examination of the length of the arguments object, which makes sense. In _arity, however, there is no such differentiation. My confusion is that aren't the following two cases effectively exactly the same in how they work? -

```js
    case 1: return function(a0) { return fn.apply(this, arguments); };
    case 10: return function(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9) { return fn.apply(this, arguments); };
```

In both cases, arguments doesn't know how many arguments it's returning, it's just an array with no names (a0 to a9)?

I guess my question is, what would change if I were to replace all cases 0-10 with the same return function as in case 0? Is it only for readability sake, or are these various cases doing different things that I'm not understanding?

Thank you for engaging, it's much appreciated.

**Comment by sebastienfilion** [comment]
I think that's because, the actual length of argument is not always the same as the expected function's argument length...
For example, you can do the following:
```js
const f = curryN(2, x => x * 2);

f(42, 24); // 48
```

**Comment by kfrp** [comment]
Yes but arity in any case is not doing anything to the arguments, just applying them without slicing or ensuring length. So why all the different cases?

**Comment by sebastienfilion** [comment]
Well the arity is set on the given number that is passed to the function and other functions from the library relies on the length to be set to decide if a function is resolved or not.

So using my previous example, `x  => x * 2` has a length of 1 -- if I didn't use `curryN(2, ...)` my function `f` wouldn't have the expected length of 2.
So it does nothing to the argument, but it does set the appropriate length on the returned function. Another way to look at it is with the following example:

```js
const f = curryN(2, x => x * 2);

f(42)(24); // 84
```

In this case, `f` is equivalent to `const f = x => y => x * 2;` -- although you can overload a function, you can't have a function to collect the remaining arguments implicitly -- that's what `_arity` does.

**Comment by kfrp** [comment]
Okay I do understand what you're saying about the function of _arity within curry. But what I'm trying to say is... if I replace the existing _arity implementation with the following:

```js
export default function _arity(n, fn) {
  if (typeof n === "number" && n >=0 && n <= 10) 
    return function () { return fn.apply(this, arguments) }
  else throw new Error('First argument to _arity must be a non-negative integer no greater than ten');
}
```

...everything else (curry1 through N) continues to work just as before. So why enumerate the cases 0 - 10 individually? For readability? 

Maybe my question is too small. (ツ)

**Comment by sebastienfilion** [comment]
Because the returning function won't have the right length. And many Ramda function relies on the functions length to be correct. Especially with your example, every function's length would be 0.

```js
const f = curryN(2, x => x * 2);

f.length === 2
```

**Comment by kfrp** [comment]
TIL! 
I'm glad I asked even though it was small, and thank you very much.

**Comment by sebastienfilion** [comment]
Phew. 😅 I'm just glad if I were able to answer you unscathed. 😆

**Comment by CrossEye** [comment]
> Because the returning function won't have the right length. Many Ramda function relies on the functions length to be correct.

And even more than for use with other Ramda functions, the point is to be a good neighbor.  If we create a function, it should be as useful to the users as it can be.  It should be as accurate as possible.  If some other code depends upon the arity of a function, Ramda should not screw that up.

This is designed mostly on speculation rather than out of real-world problems.  But as Sebastien points out, we could need it internally for Ramda.  It would be pretty embarrassing if Ramda could not accept the functions it generates.

There was a time when `arity` (or some predecessor?) used the Function constructor to do this rather than our 1-10 arity functions.  We stopped due the `eval` security concerns.  When we rewrite in modern JS, we can simply use `Object.defineProperty` to get this to work.  For now we have this ugly implementation.
