### ISSUE TITLE
Invalid comparison result

### ISSUE THREAD

**Issue by hihilisk** [ramda/ramda#3131]
R.is(Array, []) && R.is(Object, []) => true

[Online Example](https://ramdajs.com/repl/?v=0.27.0#?R.is%28Array%2C%20%5B%5D%29%20%26%26%20R.is%28Object%2C%20%5B%5D%29)

**Comment by sebastienfilion** [comment]
Well that's just JavaScript for you... 😆 If you run `[] instanceof Array && [] instanceof Object` you'll get the same result.

**Comment by hihilisk** [comment]
You right and i now it, but from function R.is i expecting `R.is(Array, []) !== R.is(Object, []) => true`

**Comment by sebastienfilion** [comment]
Yeah, it's not intuitive but there's nothing more to `is` than simple inheritance check. I don't think we want to change that.

**Comment by CrossEye** [comment]
This is not much different from 

```js
class Rectangle { ... }
class Square extends Rectangle { ... }
const s = new Square (5)

is (Square, s) && is (Rectangle, s) //=> true
```

For better or worse, Javascript implements Array atop Object.

**Comment by hihilisk** [comment]
> Yeah, it's not intuitive but there's nothing more to `is` than simple inheritance check. I don't think we want to change that.

Thank you, ok i close issue)
