### ISSUE TITLE
TS definition for R.until forces the same type for predicate and transformation function

### ISSUE THREAD

**Issue by maciejmiklas** [ramda/ramda#3132]
This is the original definition:
`export function until<T, U>(pred: (val: T) => boolean, fn: (val: T) => U, init: U): U;`

We have `T` as parameter for two methods but noting returns `T`. In this case it works only if `U` and `T` are of the same type.

Maybe changing `init: U `-> `init: T` would improve it?
`export function until<T, U>(pred: (val: T) => boolean, fn: (val: T) => U, init: T): U;`

or actually based on `(a → Boolean) → (a → a) → a → a` maybe this would be correct:
`export function until<T>(pred: (val: T) => boolean, fn: (val: T) => T, init: T): T;`

**Comment by kedashoe** [comment]
I'm not actually sure why they use two type variables, because they do need to be the same, right? Ah, I see your edit. Yes, I think ramda's signature is correct, see the source: https://github.com/ramda/ramda/blob/v0.27.0/source/until.js#L23-L29

**Comment by CrossEye** [comment]
@maciejmiklas: I think you need to speak with whoever maintains the types.  As Kevin said, they should definitely be the same type.

@kedashoe:  Great to see you around again!

**Comment by kedashoe** [comment]
> @kedashoe: Great to see you around again!

I'm always here lurking :upside_down_face:

**Comment by maciejmiklas** [comment]
I thought, that types are maintained also here - in such case please close the case and thank you :)
