### ISSUE TITLE
Is R.partition stable?

### ISSUE THREAD

**Issue by NicoleRauch** [ramda/ramda#3133]
Hello,

I'm sorry if this has been answered elsewhere, but I checked the docs as well as the issues and could not find any information about it.

My question is, is R.partition stable? (I.e. will the order of elements of the passed list be maintained in the two new lists?)

I don't see any reason why it shouldn't be, but I'm planning to base a feature off of this, so I would like to know for sure ;-)

Thanks for any answers!

**Comment by adispring** [comment]
Yes, it is. ` partition` use ` filter` to do partition, and ` filter` keep list items order.

**Comment by NicoleRauch** [comment]
Thank you very much!
