### ISSUE TITLE
RenameKey function

### ISSUE THREAD

**Issue by JuanluR8** [ramda/ramda#3137]
Is currently any function to rename a key in an object?

My aproach to do it is:

```javascript
const { allPass, assoc, compose: B, complement, has, omit, prop, when } = require('ramda');

const S_ = (f) => (g) => (x) => f (g (x)) (x);

const renameKey = (oldKey) => (newKey) => when(allPass([
    has(oldKey)
    , complement(has)(newKey)
]))
(B(omit([oldKey]), S_(assoc(newKey))(prop(oldKey))))
    
const obj = { fullname: 'Jon' };

renameKey('fullname')('name')(obj) // => { name: 'Jon' }
```

First I check that the object contains the oldKey and doesn't the newKey.
Then, I use de `S_` combinator to add the `newKey` with the `oldKey` value, and omit this `oldKey`.

**Comment by mattgrande** [comment]
There's a suggestion for how to do this in the [ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#rename-keys-of-an-object).

I created a PR to add this awhile ago (#2094), but there wasn't much support for it, so I closed it. If there's interest from the core team now, I could resurrect it?

**Comment by kedashoe** [comment]
> If there's interest from the core team now, I could resurrect it?

It's been requested a few times. I've definitely had the need come up in projects. +1 from me..

**Comment by CrossEye** [comment]
@mattgrande:

It might be worth revisiting.

I'm really much more interested in a general-purpose `rebuild` function that takes (a) a function from an key-value pair and returns an array of key-value pairs and (b) an object, then sandwiches that function between `toPairs` and `fromPairs`.  Then `renameKeys` would just be `fn => rebuild(([k, v]) => [[fn(k), v]])`.  And `renameKey` could be `(o, n) => build(([k, v]) => [[k == o ? n : k, v]])`.  This could also let us filter out certain pairs or to make several out of one.  I will try to create a PR for this soon, unless someone beats me to it.

@JuanluR8: Just a note that your `S_` combinator is how `R.chain` works when used with functions.

**Comment by JuanluR8** [comment]
Thanks for answers!

I didn’t notice about cookbook, I’ll check it for these type of functions first!

It’s very used functions like this rename, modify (also in the source but not published in a new version yet)...

**Comment by semmel** [comment]
@CrossEye You beat me to suggest that path be 20 mins. Damn!
Anyway, as you suggested in [#1361 comment](https://github.com/ramda/ramda/issues/1361#issuecomment-780716313) with `rebuild`
```javascript
var rebuild = R.curry((fn, obj) => R.fromPairs(R.chain(R.apply(fn), R.toPairs(obj))));
var mapKeys = fn => rebuild((k, v) => [[fn(k), v]]);
mapKeys(R.when(R.equals("foo"), R.toUpper))({bar:"BAR", foo: "FOO"})
// -> { bar: 'BAR', FOO: 'FOO' }
```
`renameKey(s)` becomes a particular application of a general solution.

**Comment by CrossEye** [comment]
@semmel: I knew I'd discussed this fairly recently, but didn't even recall if it was in a Ramda issue!  Thanks.

**Comment by CrossEye** [comment]
The `rebuild` above is so easy to write in modern JS that I don't want to bother writing this in the ES3-style the library currently has, since I'm hoping to move beyond that soon.  Will look again when we convert to modern styles, but closing for now.

```js
const rebuild = (fn) => (obj) =>
  Object .fromEntries ( Object.entries (obj) .flatMap (([k, v]) => fn (k, v)))
```
