### ISSUE TITLE
REPL not working (MIME type error)

### ISSUE THREAD

**Issue by abianche** [ramda/ramda#3141]
Hi, when loading the REPL site (https://ramdajs.com/repl/), the page is not working.

This is the error I get in the console:
```
Refused to apply style from 'https://raw.githack.com/ramda/repl/1.2.0/dist/bundle.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by abianche** [comment]
Ok, the issue seems to be solved, right after I reported the issue!
Closing.

**Comment by CrossEye** [comment]
Yes, githack had been a temporary work-around when there was an issue with our usual site.  When this happened, I switched back.

I assume githack is/was having problems, but I didn't investigate.
