### ISSUE TITLE
Lost splitWhenever in current document.

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#3142]
I found there is an api called `splitWhenever` in source directory, which is implemented since version 0.26.1. But it is not in the current document(v0.27.0).

**Comment by adispring** [comment]
And since we have merged lots of pull requests, when will we publish a new version.

**Comment by CrossEye** [comment]
I'd like to publish soon.  I'll see what I can do this weekend.  I will see if `splitWhenever` magically comes back, and if it doesn't I'll try to figure out why.

**Comment by CrossEye** [comment]
It's funny, because I *thought* we had such a function in Ramda, and went to use it the other day.  It wasn't there.  Odd.  But I didn't investigate further, simply rewriting it as needed.

**Comment by Bradcomp** [comment]
It's possible it's in an unreleased version. We really need to do an official release.

**Comment by CrossEye** [comment]
And home renovations kept me from even looking at it this weekend.  I'll try to find time soon.

**Comment by mudit56** [comment]
splitWhenever has not been released yet, Would like if it does, then I can go ahead and replace the custom implementation in my project.

**Comment by CrossEye** [comment]
Now released!
