### ISSUE TITLE
count function?

### ISSUE THREAD

**Issue by Nondv** [ramda/ramda#3143]
Hi!

I didn't find anything similar to `count(pred, list)` function that would count items with `pred(x) == true`.

Did I miss something?

I think it's a very common function and it makes sense to have it already defined and curried.

Usage example: 

```javascript
const isEven = n => n % 2 === 0;

R.count(isEven, [1, 2, 3, 4]); //=> 2
```

(obviously, it's quite nice to use in pipelines)

I added this ineffective definition to my code:

```javascript
const count = curry(compose(length, filter))
```

A better implementation would be something like:

```javascript
const count = curry((pred, list) => reduce((a, e) => pred(e) ? a + 1 : a, 0, list))
```

or with a transducer:

```javascript
const count = curry((pred, list) => transduce(filter(pred), inc, 0, list))
```

**Comment by CrossEye** [comment]
@Nondv:

Please feel free to create a PR for this, if you like.  It should be a simple enough function to write.

I can't guarantee that a PR would be accepted, but I can promise a fair hearing.

**Comment by Nondv** [comment]
@CrossEye will do. I was just wondering if I'm missing something or if this was already discussed
