### ISSUE TITLE
API document can not be executed now

### ISSUE THREAD

**Issue by kkxiaoa** [ramda/ramda#3147]
![image](https://user-images.githubusercontent.com/35802139/117576634-323ba300-b119-11eb-80cd-affec5eadefc.png)

**Comment by CrossEye** [comment]
Can you explain what you were trying to do?

**Comment by adispring** [comment]
Just click "run it here", will show that error. @CrossEye

**Comment by adispring** [comment]
I found out that, `runkit` can not require third-party modules in node 16. If switch to a node version less than 16, `runkit` works fine.

Other websites used `runkit` have the same problem, such [lodash](https://lodash.com/docs/4.17.15).

I think this is `runkit`'s problem, which relating to node new published version - v16.

**Comment by adispring** [comment]
I have created a bug report for runkit: https://discuss.runkit.com/t/runkit-can-not-require-modules-in-node-v16/3016

**Comment by kkxiaoa** [comment]
> Just click "run it here", will show that error. @CrossEye

Yes, but it is not a tricky issue. I found out a few days ago but it has not been resolved, so I filed an issue.

**Comment by kkxiaoa** [comment]
"run it here"  is normal,  Thanks for the feedback

**Comment by CrossEye** [comment]
Thanks @adispring.  I always use the REPL, so I never click that button.

**Comment by adispring** [comment]
Some web links and sources are banned in our country, so we can not open REPL, we can only use `run it here`.

**Comment by CrossEye** [comment]
@adispring: The same is true of many larger companies here in the US.  But I've never seen the REPL banned.  I wonder why...

**Comment by adispring** [comment]
Github's CDN is banned, so that repl's css and javascript resources can not be download, as follows:

* https://cdn.rawgit.com/ramda/repl/1.2.0/dist/bundle.css
* https://cdn.rawgit.com/ramda/repl/1.2.0/dist/bundle.js

**Comment by CrossEye** [comment]
I can't recall why those are served from the CDN rather than from GH pages directly.  But we can certainly look at changing that.  `rawgit` has had several issues lately for me as well.
