### ISSUE TITLE
New util: Scale or map range of number

### ISSUE THREAD

**Issue by kluplau** [ramda/ramda#3154]
I use the `map` function of ["math-toolbox"](https://github.com/terkelg/math-toolbox/blob/master/src/map.js) a lot. Could Ramda have a function like that?

```javascript
  it('maps input 1 in range 1-100 to value between 0-10', () => {
    expect(map(1, 0, 100, 0, 10)).toBe(0.1)
  })

  it('maps input 5 in range 0-10 to value between 0-100', () => {
    expect(map(5, 0, 10, 0, 100)).toBe(50)
  })
```

**Comment by CrossEye** [comment]
@kluplau: 

Can you explain why you think this belongs in Ramda?  I have certainly written such functions on occasion, but it's been pretty rare.  What do you do that makes this so common?  And how widespread do you think the need for this function is?

Of course we wouldn't include it under the name `map`, which is already pretty central to Ramda.  What might you choose to call it instead?  Something like `scaleTo` or `fitTo`?  Something else? 

It's a fairly trivial function to write, with the only complexities having to do with division by zero and whether to extrapolate or error on out-of-bounds inputs.  That is definitely a strike against it.  Usually functions included in Ramda are either very widely needed or tricky to implement correctly in one's code.  Neither seem to fit here.   Can you make a compelling point?

Of course you're always free to create a PR for this.  I can promise a fair hearing.  But I would need a fair bit of justification to be convinced.

**Comment by kluplau** [comment]
Hi Scott (@CrossEye)

Thank you for your time and for getting back to me with such an elaborate reply.

First, let's call it `scaleTo` (not a bad name at all!), at least for now.

I like to think of Ramda as a toolbelt with all my utility functions I need for my day-to-day work. You are right, `scaleTo` is very easy to implement yourself, but having to implement that function alone, or using another utility-library only for that function, feels wrong. I would like my toolbelt to be enough.

**Example usage**
Let's say you are building a graph. `scaleTo` would come in handy if you were to add a time indicator where the current time should be relative to the displayed graph - so mapping from a date to a pixel value
Or if you you wanted to get the precise date by the cursors position over the graph - so mapping from pixels to a date value.

Another example could be scaling/mapping a joystick with an output from a "-1" to "1" on both axis, to a pixel value on a screen resolution.

```js
const [x, y] = getJoystickPosition(); // [0.13, 0.84]
const x = scaleTo(x, -1, 1, 0, 1920); // 1084.8
const y = scaleTo(y, -1, 1, 0, 1080); //993.5999999999999
```

Out of bounds should work out of the box, so providing -2 in the latter example, while calculating x, should return `-960`.

I hope I covered everything you wanted to know from me. If I missed something, please let me know.

**Comment by CrossEye** [comment]
@kluplau:

> I like to think of Ramda as a toolbelt with all my utility functions I need for my day-to-day work. 

That's very different from my view.  I see it as the collection of tools making it simpler to do FP in JS.  It's never been intended as a general purpose tool-kit in the mold of Underscore or lodash.  Of course there are many functions there, and they have varying degrees of faithfulness to this vision.  Many early functions were added simply for the convenience of the two founders, with little discipline.

I do understand what the function does.  I've written versions of it several times.  I'm curious as to what type of coding you do that this is a common need.

If we do decide to include this, I would definitely change the signature.  Perhaps something like this:

```js
// scaleTo :: (Number, Number) -> (Number, Number) -> Number -> Number

const scaleX = scaleTo ([-1, 1], [0, 1920])
const scaleY = scaleTo ([-1, 1], [0, 1080])
const [x, y] = getJoystickPosition () //=> [0.13, 0.84]
const newX = scaleX (x)  //=> 1084.8
const newY = scaleY (y)  //=> 993.5999999999999
```

But I'm still not convinced that it belongs directly in Ramda.  It can always go into the [Cookbook][cb].  Perhaps something like [ramda-adjunct][ra], would be interested in it (@char0n -- what do you think?)  But feel free to press the case if you feel strongly about it.

  [cb]: https://github.com/ramda/ramda/wiki/Cookbook
  [ra]: https://github.com/char0n/ramda-adjunct

**Comment by char0n** [comment]
@CrossEye, @kluplau as mentioned in other issues before, [ramda-adjunct](https://github.com/char0n/ramda-adjunct) is always happy to adopt general purpose utils like this that build on top of ramda. As time proved, ramda-adjunct has become **THE** utility toolbelt for mane developers (myself included).

And I share @CrossEye vision that ramda should only  give tools for being able to do FP in JS and not deal with specific algorithmic problems in daily JS developement.

**Comment by kluplau** [comment]
Ah great. Never knew about `rambda-adjunct`. Will have a look.

Yeah I see your points, after reading both of your replies, and I agree. Thank you for your time, both of you.
