### ISSUE TITLE
function test need flag s

### ISSUE THREAD

**Issue by HoKangInfo** [ramda/ramda#3156]
s | Allow&nbsp;.&nbsp;to match newlines (added in&nbsp;ECMAScript 2018)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag

export default function _cloneRegExp(pattern) {  
return new RegExp(pattern.source, 
(pattern.global         ? 'g' : '') +
(pattern.ignoreCase ? 'i' : '') +   
(pattern.multiline     ? 'm' : '') +
(pattern.sticky          ? 'y' : '') +                              
(pattern.unicode      ? 'u' : ''));
}

**Comment by CrossEye** [comment]
Can you explain more clearly what you're looking for here and what it has to do with Ramda?

**Comment by HoKangInfo** [comment]
```
const s='123\n456'
const f1 = cond([
[R.test(/3.*4/s), R.match(/3.*4/s)],
[T, R.always('X')]
])

f1(s) // ~> X, not [3\n4]
```
R.test not support regexp flag 's', but R.match is ok
if R.test  support regexp flag 's', i can 
ex:
```
const tryMatch = R.pipe(R.of, R.ap([test, match])
const f2= cond([
tryMatch(/3.*4/s),
[T, R.always('X')]
])
```

**Comment by CrossEye** [comment]
Yes, it looks as though [`internal/_cloneRegExp`][rt] is missing [several flags][rf].

Would you care to create a PR to fix this?

  [rt]: https://github.com/ramda/ramda/blob/master/source/internal/_cloneRegExp.js
  [rf]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags

**Comment by HoKangInfo** [comment]
I try it, but I can not apply test case, because ESlint raise `Invalid regular expression flag`.

**Comment by HoKangInfo** [comment]
fix, add use first flags property, and support dotAll flag
#3158
