### ISSUE TITLE
add a new function -- compareBy

### ISSUE THREAD

**Issue by adispring** [ramda/ramda#3163]
The implementation and examples of `compareBy` are as follows:

```js
const compareBy = R.curry((transformer, compareFn) => R.useWith(compareFn, [transformer, transformer]));

const student1 = {
  id: 1,
  name: 'Alice',
  score: 85,
};

const student2 = {
  id: 2,
  name: 'Bob',
  score: 87,
};

const compareByScore = compareBy(R.prop('score'));

console.log(compareByScore(R.gt)(student1, student2)); //=> false

console.log(compareByScore(R.lt)(student1, student2)); //=> true

console.log(compareByScore(R.subtract)(student1, student2)); //=> -2
```

`R.eqBy` can also be implemented by `compareBy`

```js
const eqBy = compareBy(R.__, R.equals)
```

**Comment by CrossEye** [comment]
I like this idea.  I think it would be good to have, but I wonder if it makes more sense to [switch][rr] the first two parameters,:

```js
// :: (b -> b -> c) -> (a -> b) -> a -> a -> c
const compareBy = curry (
  (compare, transform, x, y) => compare (transform (x), transform (y))
)  

const student1 = {
  id: 1,
  name: 'Alice',
  score: 85,
}

const student2 = {
  id: 2,
  name: 'Bob',
  score: 87,
}

const greaterBy = compareBy (gt)
const subtractBy = compareBy (subtract)

greaterBy (prop ('score')) (student1, student2)  //=> false
greaterBy (prop ('score')) (student2, student1)  //=> true
subtractBy (prop ('score')) (student1, student2) //=> -2
```

Either version has uses.  One big advantage I see to this order is that it matches [Haskell's `on`][on].

Either way, it looks like a useful function.

  [on]: https://hoogle.haskell.org/?hoogle=(b%20-%3E%20b%20-%3E%20c)%20-%3E%20(a%20-%3E%20b)%20-%3E%20a%20-%3E%20a%20-%3E%20c
  [rr]: https://tinyurl.com/yzrckbaq

**Comment by adispring** [comment]
When I begin to write this implementation, I find that there's already a function called `on` in ramda library：https://github.com/ramda/ramda/blob/master/source/on.js . but not have been published.

So let's publish a new version of ramda? There are already many new features and functions that need to be released, Such as `whereAny`, `on`, etc.
