### ISSUE TITLE
applyTo missing in docs

### ISSUE THREAD

**Issue by Jazzmanpw** [ramda/ramda#3166]
I accidentally bumped on the `applyTo`, but I can't find it in the docs. I could use `flip(call)` to achieve the same result, but the first one seems clearer. Is it an undesired way to call a function?

I'm not sure, but may it be that some other functions are missing in the docs, too?

Also for some reason, this method is not accessible in the Ramda REPL.

**Comment by krzysztofpniak** [comment]
It's present in both REPL and docs for me.

**Comment by Jazzmanpw** [comment]
I'm sorry, I happened to open some older version of the docs

**Comment by CrossEye** [comment]
I'm curious where you ran across those old docs.  If you remember, could you let us know?

**Comment by Jazzmanpw** [comment]
I didn't remember, but the browser history is our saviour. There are some links in [this question on the StackOverflow](https://stackoverflow.com/questions/31504356/obtaining-the-largest-item-in-a-list-using-ramda) with the versions specified in them

**Comment by CrossEye** [comment]
Thank you very much.  I think we need to make that version number more prominent.

**Comment by Jazzmanpw** [comment]
That's a great idea. I think, a "this version is deprecated" message may be enough
