### ISSUE TITLE
add iso function

### ISSUE THREAD

**Issue by krzysztofpniak** [ramda/ramda#3167]
Please consider adding `iso` function and possibly `mapped` and `traversed` form: https://github.com/ramda/ramda-lens
I checked them and I think main repo is a good place to add these ones.
I can submit a PR with test and docs if I get a 'green light' from one of the maintainers.

**Comment by CrossEye** [comment]
Certainly our lenses repo fizzled out without going anywhere.  I would be very interested in adding further optics into the main repo.

Feel free to create a PR for this.  I can't guarantee approval, but it will certainly get a fair hearing, and I am personally in favor of doing something like this.

**Comment by CrossEye** [comment]
@krzysztofpniak: Are you interested in creating a PR?

**Comment by krzysztofpniak** [comment]
@CrossEye I can, but now I'm really busy. I think I can work on it in March.

**Comment by CrossEye** [comment]
Ok, then I will close this for now, we can start again then and hopefully be past `v1.0`.
