### ISSUE TITLE
why is the result of intersection not orderd, unlike that of innerJoin

### ISSUE THREAD

**Issue by nishino-tsukasa** [ramda/ramda#3172]
`xs'` is ordered the implementation guarantees that its values are in the same order as they appear in `xs`
I think the same applies to intersection

**Comment by CrossEye** [comment]
On vacation and will try a more complete answer when we get back, but intersection was optimized for performance in a manner that didn't allow us to choose the order from one input... And it makes some

**Comment by CrossEye** [comment]
Ping @nishino-tsukasa: While I never did get around to responding more deeply, is my short answer enough?  Do you have further comment?
