### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [ramda/ramda#3175]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
@CrossEye - once we have confirmed a fix for the reported issue [here](https://huntr.dev/bounties/51dfe927-1bf1-4b36-91ca-2197337e663a/), we can go ahead and assign a CVE for you.

Let us know what works best!

**Comment by CrossEye** [comment]
@JamieSlome.  Well it won't be fixed until #3177 is completed and we release a new version.  I'll let you know.  I have no idea what a CVE is, BTW.

**Comment by JamieSlome** [comment]
@CrossEye - awesome, thanks for the heads up!

Take a look into CVE here:

https://cve.mitre.org/
