### ISSUE TITLE
`gt` (and friends) not suited for partial apply

### ISSUE THREAD

**Issue by gomain** [ramda/ramda#3186]
```javascript
const R = require('ramda');

/* check if length greater than 1 */
let shouldBeTrue = R.compose(R.gt(1), R.length)([1,2]); // returned false

let theRightWayBut = R.compose(l => R.gt(l, 1), R.length)([1,2]);

let reallyRightWay = R.compose(R.gt(R.__, 1), R.length)([1,2]);

```

**Comment by CrossEye** [comment]
This has been discussed a number of times.  (Many of these issues touch on it: https://github.com/ramda/ramda/issues?page=1&q=commutative.)

We've never found a great solution that works well with both 

```js
gt(5, 2) //=> true, as expected
```

and
 
```js
const greaterThan5 = gt (5)

greaterThan5 (10) //=> false... surprise!
```

While additional suggestions are welcome, we have looked at this often and never found something satisfying.

**Comment by customcommander** [comment]
Closing as duplicate of https://github.com/ramda/ramda/issues/1497
