### ISSUE TITLE
Is `R.construct(Date)` supposed to work?

### ISSUE THREAD

**Issue by gomain** [ramda/ramda#3187]
```node
> new Date(1)
1970-01-01T00:00:00.001Z
> R.construct(Date)(1)
[Function (anonymous)]
```

**Comment by bunglegrind** [comment]
It' the correct behaviour. In fact it returns the curried constructor since Date.length = 7:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

**Comment by gomain** [comment]
@bunglegrind thanks for the explanation :heart: 

```node
> R.construct(Date).length
7
> R.construct(Date)(1).length
6
```

**Comment by imcotton** [comment]
There is also `R.constructN` btw:

```javascript
R.constructN(1, Date)(1)
```
