### ISSUE TITLE
reduce use 2 params has diff return

### ISSUE THREAD

**Issue by HoKangInfo** [ramda/ramda#3200]
`ramda@0.27.1`

var fn1 =R.reduce((r,x)=>{
  r.push(x)
  return r
},[])

fn1([1,2,3])  // [1,2,3]
fn1([4,5,6])  // [1,2,3,4,5,6]
 
var fn2 = z => R.reduce((r,x)=>{
  r.push(x)
  return r
},[], z)

fn2([1,2,3])  // [1,2,3]
fn2([4,5,6])  // [4,5,6]

why?
because
/** The iterator function receives two values: (acc, value). It may use R.reduced to shortcut the iteration. */
?

**Comment by adispring** [comment]
Because in `fn1`, `R.reduce` hold only one reducer: `(r,x)=>{ r.push(x); return r; }`, if you modify acc in place, all the subsequent call of `fn1` will be affected by the same `acc`

You should keep the `acc` immutable, and return a new `acc` , as follows:

```js
var fn1 =R.reduce((r,x)=>{
  const newAcc = [...r, x]
  return newAcc
},[])

fn1([1,2,3]) // [1,2,3]
fn1([4,5,6]) // [4,5,6]
```

**Comment by HoKangInfo** [comment]
:) THX, but ... Unintuitive as for me.
suggest More explanation on doc.

**Comment by adispring** [comment]
Yes, I think it is necessary to remind user of this situation in doc.

Or can we do something to optimize `R.reduce` to avoid this situation ?

@CrossEye

**Comment by HoKangInfo** [comment]
a Low-level error. I use a "side effect" method in iterator function. 
Because js array point is Immutable.

**Comment by CrossEye** [comment]
@HoKangInfo:  I have no problem adding a sentence to the documentation to warn about this.  The question has arisen on occasion.  Do you have suggested wording for it?

@adispring: I don't think `reduce` should try to handle this itself.  The minute we do, we break any existing code that actually depends on this behavior.  Ramda is supposed to be a library that helps users work in a certain style but it does not attempt to enforce that style.

**Comment by HoKangInfo** [comment]
@CrossEye THX, but my English is not good.

**Comment by CrossEye** [comment]
How does this sound (addition in **bold**):

> Returns a single item by iterating through the list, successively calling the iterator function and passing it an accumulator value and the current value from the array, and then passing the result to the next call.
> 
> The iterator function receives two values: *(acc, value)*. It may use `R.reduced` to shortcut the iteration.
> 
> Note: `R.reduce` does not skip deleted or unassigned indices (sparse arrays), unlike the native Array.prototype.reduce method. For more details on this behavior, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#Description
> 
> **Be cautious of mutating and returning the accumulator.  If you reuse it across invocations, it will continue to accumulate onto the same value.  The general recommendation is to always return a new value.  If you can't do so for performance reasons, then be sure to reinitialize the accumulator on each invocation.**
> 
> Dispatches to the reduce method of the third argument, if present. When doing so, it is up to the user to handle the `R.reduced` shortcuting, as this is not implemented by reduce.
> 
> See also `reduced`, `addIndex`, `reduceRight`.

**Comment by HoKangInfo** [comment]
Because my English is not good. 
Adding examples can be more intuitive.

**Comment by CrossEye** [comment]
I really don't like adding examples of what *not* to do to our documentation.  I'm afraid that would lead to trouble.

But maybe we can write an example of how to do it right that includes a comment explaining why the alternative is not recommended?  The trouble is that our current example just uses numbers where this won't be a problem and it does double-duty in showing the difference between `reduce` and `reduceRight`.

Suggestions?
