### ISSUE TITLE
what's mean R.all(R.identity)([])?

### ISSUE THREAD

**Issue by HoKangInfo** [ramda/ramda#3202]
R.all(R.identity)([]) //-> true
R.all(R.identity)([undefined]) //-> false

empty set self all element is same?

[].length //-> 0
[undefined].length //->1
var a= [] 
var b= [undefined]
a[0] //-> undefined
b[0] //-> undefined

**Comment by HoKangInfo** [comment]
I agree with everything you say.

R.all(R.identity)([]) //-> true
R.none(R.identity, []); //-> true

Is semantics unreasonable? or I should check if it is a empty list(array).

**Comment by CrossEye** [comment]
You might want to look up [vacuous truths][vt].  It explains why both of these are simultaneously correct:

```js
all (identity) ([]) //-> true
none (identity) ([]); //-> true
```

  [vt]: https://en.wikipedia.org/wiki/Vacuous_truth

**Comment by HoKangInfo** [comment]
THX, This helped me.

**Comment by customcommander** [comment]
Would you like to close this issue?

**Comment by HoKangInfo** [comment]
Yes,thx
