### ISSUE TITLE
Why does memoizeWith cache different objects as being the same arguments?

### ISSUE THREAD

**Issue by oliviera9** [ramda/ramda#3226]
I am using ramda 0.28.0.

Code esample is the following:
```js
const { identity, memoizeWith } = require('ramda')
const f = memoizeWith(identity, obj => console.info(obj))
```

Some output:
```
> f({test:1})
{ test: 1 }
undefined
> f({})
undefined
> f(2)
2
undefined
> f(2)
undefined
> f(3)
3
undefined
```
As you can see, `{}` does not reach `console.info`, but I expect `identity` to return a different key.
Why is this?

Thanks

**Comment by customcommander** [comment]
Most like what's happening is that both `{test:1}` and `{}` are converted into a string. The default `.toString()` will return `'[object Object]'` for both. You can verify this by implementing `.toString()` on both object to return a different string:

```javascript
const a = {foo:1};
const b = {};
const c = {foo:1};
const d = {};

c.toString = () => 'key1';
d.toString = () => 'key2';

const f = memoizeWith(identity, obj => console.info(obj));

console.log('f(a)');
f(a)
console.log('f(b)');
f(b)
console.log('f(c)');
f(c)
console.log('f(d)');
f(d)
```

Output

```none
f(a)
{"foo":1}
f(b)
f(c)
{"foo":1}
f(d)
{}
```

As you can see both `c` and `d` have generated different cache keys so they both went through the console.log.

**Comment by customcommander** [comment]
This is probably something the docs should cover. Related #2314
