### ISSUE TITLE
Coverage badge is broken

### ISSUE THREAD

**Issue by customcommander** [ramda/ramda#3229]
Not super urgent but still wanted to capture this in an issue. The coverage badge is broken:

<img width="652" alt="Screenshot 2022-02-07 at 08 36 03" src="https://user-images.githubusercontent.com/681975/152752905-8241e374-8fdb-4b96-97ad-01070985314e.png">

I've only superficially attempted to fix this by looking at the docs in Code Climate; perhaps they came up with new URL syntax or format? Couldn't see anything :-/ Is this potentially something you can look into @hitmands ?

**Comment by CrossEye** [comment]
I'm wondering if people care at all about such badges.  I personally don't.  I don't mind putting in small amounts of effort to fix them if they seem meaningful to people, but I've never really understood the fascination with them.

**Comment by customcommander** [comment]
@CrossEye: I wouldn't object to removing it if we don't have the scope to fix it. I'm also not a big fan of such badges too; they give only marginal value (if any) IMHO. Right now the value is none and possibly negative as it doesn't look on the homepage. Shall we remove it for now?

**Comment by CrossEye** [comment]
Yes, I'd say remove it for the moment, or even comment it out while we consider further.  Does that make sense?
