### ISSUE TITLE
Removing curry dependency for internal transducer creator functions.

### ISSUE THREAD

**Issue by xgbuils** [ramda/ramda#3230]
I've noticed ramda is using curried functions for internal functions like transducer creators. I'm pretty sure this is causing a lack of performance. 

Arbitrary curried functions could be interesting for public funcions. But transducer creators are used always in _dispatchable internal function that requires a transducer creator (`(...args) -> xf -> xf`). Then, wrapping transducerCreators could create an unnecessary increase of arguments.length and isPlaceHolder checks (See `internal/_curry1.js`, `internal/_curry2.js`, `internal/_curry3.js` and  `internal/_curryN.js`).

**Comment by CrossEye** [comment]
Thank you.  Looks like a good idea.  I'll dig deeper into the PR soon.
