### ISSUE TITLE
Install specific functions 502 Server Error

### ISSUE THREAD

**Issue by luis-antonio-ac** [ramda/ramda#3249]
On click at [Install individual functions](https://bitsrc.io/ramda/ramda) in https://ramdajs.com/ i get 
![image](https://user-images.githubusercontent.com/35160032/156675501-930e5a9e-0135-4f83-838c-1042affe1b8d.png)

**Comment by CrossEye** [comment]
I know almost nothing about bitsrc.  But even their top-level URLs are failing.  This is not a Ramda problem.  Have they simply moved servers?  Is this the same as https://bit.dev/ ?
