### ISSUE TITLE
Incorrect docs: code example for R.on

### ISSUE THREAD

**Issue by briandavidclark** [ramda/ramda#3253]
In the documentation for "R.on", the example has:

`R.on(R.contains, R.toLower)`

"R.contains" should be "R.includes"

**Comment by customcommander** [comment]
@briandavidclark you're absolutely correct. Would you like to submit a PR for this?

**Comment by CrossEye** [comment]
I've always been suspicious of the TC39's strict insistence on not breaking the web.  How long will we have to live with MooTools' old design choices?  `contains` is so much nicer than `includes`.

/endrant
