### ISSUE TITLE
Typing of R.converge

### ISSUE THREAD

**Issue by valerii15298** [ramda/ramda#3256]
First of all, thank you for such a great library! I discovered it not a long time ago and it is fantastic for me.

I tried to use `converge` function but typescript complains and i cannot understand how to type it correctly:
```ts
const isEmptyOrNil = R.converge(R.or, [R.isEmpty, R.isNil]);
```

Error:
```
TS2769: No overload matches this call.
The last overload gave the following error.
Argument of type '{ <T, U>(a: T, b: U): T | U; <T>(a: T): <U>(b: U) => T | U; }' is not
assignable to parameter of type '(...args: readonly [unknown] & { length: 1; }) => <U>(b: U) => unknown'.
Types of parameters 'a' and 'args' are incompatible. 
Type 'readonly [unknown] & { length: 1; }' is not assignable to type '[a: any, b: any]'.
```

How can I type it in a right way?

I can do something like:
```ts
const isEmptyOrNil = R.converge(R.or as (...args: any) => boolean, [R.isEmpty, R.isNil]);
```
but it does not seem very good to use `as` and `any`

**Comment by customcommander** [comment]
It is a known "issue" that typing Ramda isn't always straightforward. I personally don't know much about TypeScript so I can't really help. I would simply note that you don't need `R.converge` for this. You could use `R.either`:

```javascript
const isEmptyOrNil = R.either(R.isEmpty, R.isNil);
```

Not sure if that helps though :-/

Good luck!

🇺🇦

**Comment by customcommander** [comment]
Pinging @hitmands as he's a seasoned TS developer.

**Comment by hitmands** [comment]
It seems there are a few issues after taking a quick look, 
I'd suggest going for what @customcommander advised, it also reads better imho :)

**Comment by valerii15298** [comment]
Thank you. `R.either` definitely works. `R.converge` has problems in type definitions, probably I will make pull request soon to fix it.

@customcommander also thank you for your 🇺🇦position. This my first opened issue since of war and even here, surprisingly, I see support my country. Thanks.
