### ISSUE TITLE
Update typings in DefinetlyTyped

### ISSUE THREAD

**Issue by valerii15298** [ramda/ramda#3257]
Types for `ramda` are very useful but are not the best for now.
[tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/tsconfig.json) does not meet requirements from DefinetlyTyped as told in their Readme(all options must be set to `true`).
```json
"noImplicitAny": true,
"noImplicitThis": false,
"strictNullChecks": true,
"strictFunctionTypes": false,
```
should all be set to `true`, and even better to use `"strict": true` option, so in this way all users can use the library without typescript errors. Without it users with more strict config will have errors. Better tests and more strong typing will bring nice typescript experience with `ramda`.
Some typing needs to be changed.
I tested types with `strict` option enabled and we have exactly 12 functions ([check logs](https://gist.githubusercontent.com/valerii15298/afbb4df77c7127fd2c3635def09d095c/raw/e0c1d4bc388a29238ac2f3917aef019f46250e32/ramda-test-types-errors-with-strict.txt)) that needs to be changed:

- [x] `addIndex`
- [x] `construct`
- [x] `constructN`
- [x] `converge`
- [x] `groupWith`
- [x] `ifElse`
- [x] `is`
- [x] `reduceRight`
- [x] `symmetricDifferenceWith`
- [x] `toPairsIn`
- [x] `transduce`
- [x] `when`

My idea is to change all other functions to work under `strict` flag so we can have better typescript experience. I believe together we can do it. Also most likely it will be breaking change. But I believe it worth it(For example change all 12 functions and push it on npm as version `types/ramda@0.29.x`)

Update: magically most of the tests get fixed(I suspect someone changed them).

**Comment by CrossEye** [comment]
Very glad to see people working on this.  I don't know if TS is now capable of fully typing Ramda functions.  For a long time it wasn't.  

Thank you very much, @valerii15298, for your contributions!

**Comment by valerii15298** [comment]
Thanks to the contributors, ramda types repo is configured with `strict` typescript compiler option.
