### ISSUE TITLE
Tring to clone() object with no prototype gives error u.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by denishowew** [ramda/ramda#3258]
`clone()` can't handle _objects with no prototype_.  When trying to clone `value`, it does:

```
for (var key in value) {
  if (value.hasOwnProperty(key)) ...
```

which is fine for normal objects that inherit the `hasOwnProperty()` method.

However, objects created using `Object.create(null)` have no prototype and will trip up [unwary code](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create).

clone() blows up with error `u.hasOwnProperty is not a function`.

[Demo of the bug](https://ramdajs.com/repl/?v=0.28.0#?const%20o%20%3D%20Object.create%28null%29%3B%0Ao.a%20%3D%2042%3B%0AR.clone%28o%29%3B%0A):

```
const o = Object.create(null);
o.a = 42;
R.clone(o);

```

**Comment by CrossEye** [comment]
Getting back to Ramda after a short time away.

This is definitely a problem.  Are you interested in creating a PR to fix it?, @denishowew ?

**Comment by denishowew** [comment]
Sorry, no, I hate Ramda. :-)

**Comment by semmel** [comment]
I would volunteer

**Comment by thefourtheye** [comment]
> > Are you interested in creating a PR to fix it?,
> 
> I would volunteer

@semmel My apologies, I came in late and created a patch for this. If you already have been working on a fix, please let me know. I do not mind closing #3261.

**Comment by semmel** [comment]
> I do not mind closing https://github.com/ramda/ramda/pull/3261.

Not at all! All I care about is that there is a patch.
Great work in #3261 and thank you @thefourtheye for making our work/lives better!
