### ISSUE TITLE
Question: assocPath is creating array with undefined values if numeric key is given

### ISSUE THREAD

**Issue by minaseem** [ramda/ramda#3259]
Case 1:
R.assocPath(['a', 4, 4], 42, {a: 5}); //=> "a": {"4": [undefined, undefined, undefined, undefined, 42]}}

Case 2:
R.assocPath(['a', '4', '4'], 42, {a: 5}); //=> {"a": {"4": {"4": 42}}}

I expected output to be same in both the above cases and both the cases to have the output what I got in case 2. It seems that this by design ([assocPath link](https://github.com/ramda/ramda/blob/master/source/assocPath.js#L37)) that when encountered key is an integer, value go into an array else an object is created. Curious on why do we have such a behaviour?

P.S: I have been using ramda for more than 5 years now. Surprised why it took me so long to fall into this scenario.

**Comment by customcommander** [comment]
Keys of an object can only be strings and indexes of an array can only be numbers. So I _think_ this is the rationale for the design and explains what you are observing.

**Comment by CrossEye** [comment]
@customecommander has it exactly right.  The idea is that you *can* build arrays or objects with `assoc*`.  The only clear way to signal this is with integers representing array indices, so they are reserved for this.

**Comment by minaseem** [comment]
Okay. Probably I got confused because `assocPath` is tagged under `Object` category, and it felt little weird when it resulted in array like structure. Closing this.
Thanks!

**Comment by CrossEye** [comment]
I've rarely, if ever, used this for the top level of an object, but it is sometime useful for cases like this:

```js
assocPath (['foo', 1], 'corge') ({foo: ['bar', 'baz', 'qux']})
//=> {"foo": ["bar", "corge", "qux"]}
```
