### ISSUE TITLE
Typo in `ap` docs?

### ISSUE THREAD

**Issue by somebody1234** [ramda/ramda#3265]
> Dispatches to the `ap` method of the second argument, if present

According to the source it seems like it should instead be the first argument?

**Comment by adispring** [comment]
Yes, you are right. Do you have interest to make a pr to fix it?

**Comment by somebody1234** [comment]
never, mind, seems like it was fixed a while back in 9bffeb7?
so maybe the issue is that the docs haven't been re-generated since then?

**Comment by adispring** [comment]
Yes, that pr was merged (at Jan 23) after last release(Jan 18).

**Comment by adispring** [comment]
Yes, it should be, but I don't think there will be a new release in a short time, there may be something else to do.

**Comment by somebody1234** [comment]
yeah... maybe it's best to manually edit the docs.
maybe also add a note saying the docs as of 0.28.0 aren't correct, or point the source link for `ap` specifically to 9bffeb7.
changing the source link might be a little bit confusing if users then browse the rest of the tree from that commit - depending on how often people actually click that link it might be better to just leave it as it is?

**Comment by customcommander** [comment]
For now we need to make a new release in order to regenerate the docs. This is not ideal as typos such as the one you just reported aren't as quickly fixed as they should. This is something we're aware of but our focus right now is to reduce our current backlog before we cut a `v1.0` release.

**Comment by CrossEye** [comment]
And after 1.0, we should really fix this to allow us to create docs from any commit...
