### ISSUE TITLE
typescript tests

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#3273]
.d.ts files in ./types needing test coverage:

 - [ ]  __
 - [x]  add
 - [ ]  addIndex
 - [x]  adjust
 - [x]  all
 - [x]  allPass
 - [x]  always
 - [x]  and
 - [ ]  andThen
 - [x]  any
 - [ ]  anyPass
 - [ ]  ap
 - [ ]  aperture
 - [ ]  append
 - [ ]  apply
 - [ ]  applySpec
 - [ ]  applyTo
 - [ ]  ascend
 - [ ]  assoc
 - [ ]  assocPath
 - [ ]  binary
 - [ ]  bind
 - [ ]  both
 - [ ]  call
 - [ ]  chain
 - [ ]  clamp
 - [ ]  clone
 - [ ]  collectBy
 - [ ]  comparator
 - [ ]  complement
 - [ ]  compose
 - [ ]  composeWith
 - [ ]  concat
 - [ ]  cond
 - [ ]  construct
 - [ ]  constructN
 - [ ]  converge
 - [ ]  count
 - [ ]  countBy
 - [ ]  curry
 - [ ]  curryN
 - [ ]  dec
 - [ ]  defaultTo
 - [ ]  descend
 - [ ]  difference
 - [ ]  differenceWith
 - [ ]  dissoc
 - [ ]  dissocPath
 - [ ]  divide
 - [ ]  drop
 - [ ]  dropLast
 - [ ]  dropLastWhile
 - [ ]  dropRepeats
 - [x]  dropRepeatsBy
 - [ ]  dropRepeatsWith
 - [ ]  dropWhile
 - [ ]  either
 - [ ]  empty
 - [ ]  endsWith
 - [ ]  eqBy
 - [ ]  eqProps
 - [ ]  equals
 - [ ]  evolve
 - [ ]  F
 - [ ]  filter
 - [ ]  find
 - [ ]  findIndex
 - [ ]  findLast
 - [ ]  findLastIndex
 - [ ]  flatten
 - [ ]  flip
 - [ ]  forEach
 - [ ]  forEachObjIndexed
 - [ ]  fromPairs
 - [ ]  groupBy
 - [ ]  groupWith
 - [ ]  gt
 - [ ]  gte
 - [ ]  has
 - [ ]  hasIn
 - [ ]  hasPath
 - [ ]  head
 - [ ]  identical
 - [ ]  identity
 - [ ]  ifElse
 - [ ]  inc
 - [ ]  includes
 - [ ]  indexBy
 - [ ]  indexOf
 - [ ]  init
 - [ ]  innerJoin
 - [ ]  insert
 - [ ]  insertAll
 - [ ]  intersection
 - [ ]  intersperse
 - [ ]  into
 - [ ]  invert
 - [ ]  invertObj
 - [ ]  invoker
 - [ ]  is
 - [ ]  isEmpty
 - [ ]  isNil
 - [x]  isNotNil
 - [ ]  join
 - [ ]  juxt
 - [ ]  keys
 - [ ]  keysIn
 - [ ]  last
 - [ ]  lastIndexOf
 - [ ]  length
 - [ ]  lens
 - [ ]  lensIndex
 - [ ]  lensPath
 - [ ]  lensProp
 - [ ]  lift
 - [ ]  liftN
 - [ ]  lt
 - [ ]  lte
 - [ ]  map
 - [ ]  mapAccum
 - [ ]  mapAccumRight
 - [ ]  mapObjIndexed
 - [ ]  match
 - [ ]  mathMod
 - [ ]  max
 - [ ]  maxBy
 - [ ]  mean
 - [ ]  median
 - [ ]  memoizeWith
 - [ ]  mergeAll
 - [ ]  mergeDeepLeft
 - [ ]  mergeDeepRight
 - [ ]  mergeDeepWith
 - [ ]  mergeDeepWithKey
 - [ ]  mergeLeft
 - [ ]  mergeRight
 - [ ]  mergeWith
 - [ ]  mergeWithKey
 - [ ]  min
 - [ ]  minBy
 - [ ]  modulo
 - [ ]  move
 - [ ]  multiply
 - [ ]  nAry
 - [ ]  negate
 - [ ]  none
 - [ ]  not
 - [ ]  nth
 - [ ]  nthArg
 - [ ]  o
 - [ ]  objOf
 - [ ]  of
 - [ ]  omit
 - [ ]  on
 - [ ]  once
 - [ ]  or
 - [ ]  otherwise
 - [ ]  over
 - [ ]  pair
 - [ ]  partial
 - [ ]  partialObject
 - [ ]  partialRight
 - [ ]  partition
 - [ ]  path
 - [ ]  pathEq
 - [ ]  pathOr
 - [ ]  paths
 - [ ]  pathSatisfies
 - [ ]  pick
 - [ ]  pickAll
 - [ ]  pickBy
 - [ ]  pipe
 - [ ]  pipeWith
 - [ ]  pluck
 - [ ]  prepend
 - [ ]  product
 - [ ]  project
 - [ ]  promap
 - [ ]  prop
 - [ ]  propEq
 - [ ]  propIs
 - [ ]  propOr
 - [ ]  props
 - [ ]  propSatisfies
 - [ ]  range
 - [ ]  reduce
 - [ ]  reduceBy
 - [ ]  reduced
 - [ ]  reduceRight
 - [ ]  reduceWhile
 - [ ]  reject
 - [ ]  remove
 - [ ]  repeat
 - [ ]  replace
 - [ ]  reverse
 - [ ]  scan
 - [ ]  set
 - [ ]  slice
 - [ ]  sort
 - [ ]  sortBy
 - [ ]  sortWith
 - [ ]  split
 - [ ]  splitAt
 - [ ]  splitEvery
 - [ ]  splitWhen
 - [ ]  splitWhenever
 - [ ]  startsWith
 - [ ]  subtract
 - [ ]  sum
 - [ ]  symmetricDifference
 - [ ]  symmetricDifferenceWith
 - [ ]  T
 - [ ]  tail
 - [ ]  take
 - [ ]  takeLast
 - [ ]  takeLastWhile
 - [ ]  takeWhile
 - [ ]  tap
 - [ ]  test
 - [ ]  thunkify
 - [ ]  times
 - [ ]  toLower
 - [ ]  toPairs
 - [ ]  toPairsIn
 - [ ]  toString
 - [ ]  toUpper
 - [ ]  transduce
 - [ ]  transpose
 - [ ]  traverse
 - [ ]  trim
 - [ ]  tryCatch
 - [ ]  type
 - [ ]  unapply
 - [ ]  unary
 - [ ]  uncurryN
 - [ ]  unfold
 - [ ]  union
 - [ ]  unionWith
 - [ ]  uniq
 - [ ]  uniqBy
 - [ ]  uniqWith
 - [ ]  unless
 - [ ]  unnest
 - [ ]  until
 - [ ]  update
 - [ ]  useWith
 - [ ]  values
 - [ ]  valuesIn
 - [ ]  view
 - [ ]  when
 - [ ]  where
 - [ ]  whereEq
 - [ ]  without
 - [ ]  xor
 - [ ]  xprod
 - [ ]  zip
 - [ ]  zipObj
 - [ ]  zipWith
---
I think tests would be a great place to start. That way we can be more confident about everything else we do. @somebody1234 , I know you mentioned working on the tests in DT, would you be interested in working on the initial PR for that here? The smaller the better, maybe the framework and then the tests for 2-4 functions?

**Comment by somebody1234** [comment]
DT uses their own tool dtslint... but they point to [tsd](https://github.com/SamVerschueren/tsd) to use elsewhere, should be easy enough to set that up... do note that on DT the tests are written alongside the types so everyone else works on the tests too.

Off-topic but... not too sure about using such an old version of the types, there's a huge amount of work on the types that *will* need to be carried over... it's probably easier/better to start with the latest version and gradually remove ts-toolbelt

**Comment by essenmitsosse** [comment]
There was a discussion with @sandersn from the TypeScript compiler team about an issue we had with dtslint on [Discord](https://discord.com/channels/508357248330760243/757992230077333655/957038832363122698). 

Long story short: While dtslint is quite useful to tests types, the way its done is also quite primitive. Basically all it does is compare the string output of the generated types. But to dtslint `string | number` and `number | string` are not compatible, which can a) be super annoying and b) lead to random breaks if the TypeScript compiler changes (in that case it did for a patch release).

Ideally we'd have a tool that uses the actual TypeScript compiler to check types. Is anyone aware of any such tool?

**Comment by essenmitsosse** [comment]
Another idea: have a file that has some pseudo TypeScript code, over which we let `tsc` run as part of the test suit and expect it not to error.

```typescript
/// Pseudo code
CompareTypes<string, string> // this is fine
CompareTypes<string, number | string> // this throws an error
```

**Comment by somebody1234** [comment]
re: checking types, that would be tsd, no?
they do seem to use the internal `isTypeIdenticalTo` check ([see here](https://github.com/SamVerschueren/tsd/blob/106af14cef85530c73b390ddc4a51560c60dfb64/source/lib/assertions/handlers/identicality.ts#L42))

**Comment by somebody1234** [comment]
re: the file with pseudo typescript code, that's good and all but we'd lose the ability to check error cases... which i feel would make the tests a lot less useful

**Comment by essenmitsosse** [comment]
@somebody1234 ah yes tsd looks great at first glance. Also you are absolutely right about the error cases. But maybe we can mix different approaches?

On the other hand: what always bothered me was, that you were just checking that there was an error, not where or which. So these tests always seems very prone to be false positive to me.

**Comment by somebody1234** [comment]
yeah... too bad neither ts-expect-error nor tsd let you specify specific errors... :(

could maybe fork tsd to support that i guess?

**Comment by kedashoe** [comment]
Now that we have the file structure in place, I think this would be a good next issue to tackle.

Would anyone like to work on it? @essenmitsosse ? @somebody1234 ?

As mentioned in the post at the top, for the initial PR probably just the framework and a small number of functions would be good.

**Comment by essenmitsosse** [comment]
@essenmitsosse im still on parental leave for the week but will have a look once I'm back.

**Comment by valerii15298** [comment]
We can do checklist for every function.

Ramda has its own tests. We can change some of them gradually to typescript. Some part of them(not sure we can change all due to placeholders and curring)
In this way we can avoid code duplication and even have more confidence in tests.

**Comment by CrossEye** [comment]
@valerii15298: I think I would have an issue with changing the current tests to TS.  Bringing the TS typings in-house is a fine idea, so long as we have people willing to support it.  But that won't change the fact that this is a JS library, and it should always remain usable and understandable to those who know JS but not TS.

For separate reasons, I don't want to change the tests overmuch before we reach `1.0`, as they should serve as guardrails for the subsequent transition to modern ES in `2.0`.  After that, I expect to also modernize the tests, and if we can do so in a manner that supports both TS and JS, that would be great, but I haven't given that much thought.

**Comment by kedashoe** [comment]
> We can do checklist for every function.

Ya I think this is probably the way to go. I'll update the top post in this thread with a checklist at some point today.

**Comment by kedashoe** [comment]
ok I've attempted to make a list of all .d.ts files in /types in the top comment. Everyone feel free to start grabbing your favorites to add tests for :stuck_out_tongue: 

I'll make a separate issue for src files missing an accompany type file (not that many).

**Comment by younes-io** [comment]
I want to use `splitWhenever` in Typescript but I can't :/ Too bad things were done halfway...

**Comment by kedashoe** [comment]
see https://github.com/ramda/types
