### ISSUE TITLE
Functions missing type definitions

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#3287]
PRs welcome!

- [ ] addIndexRight
- [x] dropRepeatsBy
- [x] isNotNil
- [ ] modify
- [ ] modifyPath
- [ ] sequence
- [ ] swap
- [ ] unwind
- [ ] whereAny

**Comment by CrossEye** [comment]
@admodev: Thank you.  We appreciate the help.  Remember to do this against the `ts` branch.

**Comment by jgsheppa** [comment]
@CrossEye Has there been any progress on this issue? I have written types for `isNotNull` and `dropRepeatsBy`, but I'm wondering if there's a way to test the types against the JS code to test out my types? Or should I just submit a PR? I would be happy to give the other functions a shot, but thought I would get to know the code a bit better first.

**Comment by kedashoe** [comment]
@jgsheppa You can add tests. Here is the PR that introduced testing types: https://github.com/ramda/ramda/pull/3283

**Comment by jgsheppa** [comment]
@kedashoe Thanks! I saw there was one test, so I wasn't sure if I should try and write my own.
