### ISSUE TITLE
`equals` returns false if the ordering is different

### ISSUE THREAD

**Issue by skjo0c** [ramda/ramda#3354]
If the ordering of data is different in two array, `equals` function returns false.

![image](https://user-images.githubusercontent.com/20612562/221146332-51826e15-2436-4aa9-a646-a51071046ea0.png)

**Comment by jlissner** [comment]
It should return `false` as they are not equal.

For two arrays to be equal, they must have the same value at each index.

In your example, `arr1[1]` doesn't equal `arr2[1]`.
