### ISSUE TITLE
Ramda `0.28.0` contains CWE-843 and CWE-915

### ISSUE THREAD

**Issue by tsologub** [ramda/ramda#3359]
Hey folks, 
our security scans report that Ramdajs `0.28.0` is vulnerable to a prototype pollution attack due to insufficient protections in the `source/mapObjIndexed.js`. A remote attacker may be able to execute arbitrary code, or cause a denial-of-service (DoS) by tricking the application into modifying or adding properties of `Object.prototype`. 

Any plans on addressing this security vulnerability? 
Much appreciate.

**Comment by bunglegrind** [comment]
see here:

https://github.com/ramda/ramda/pull/3192
