### ISSUE TITLE
Documentation errors in R.swap examples

### ISSUE THREAD

**Issue by foxdonut** [ramda/ramda#3367]
There are two errors in the documentation of `R.swap` examples.

Reference: 

https://ramdajs.com/docs/#swap

**First error:**

```js
R.swap(-1, 0, ['a', 'b', 'c', 'd', 'e', 'f']); //=> ['f', 'b', 'c', 'd', 'e', 'a'] list rotation
```
This is not list rotation. Rotating the list would result in `['b', 'c', 'd', 'e', 'f', 'a']`.

**Second error:**

```js
R.swap('a', 'b', {a: 1, b: 2}); //=> {a: 2, b: 2}
```

The result is incorrect, it should be `{a: 2, b: 1}`.

Thanks!

**Comment by kedashoe** [comment]
Thank you for the issue, agreed on both! Would you like to submit a PR?

**Comment by foxdonut** [comment]
@kedashoe With pleasure. PR submitted.

**Comment by kedashoe** [comment]
https://github.com/ramda/ramda/pull/3368
