### ISSUE TITLE
Example with R.find() does not work

### ISSUE THREAD

**Issue by adamblok** [ramda/ramda#3371]
The example provided in [https://github.com/ramda/ramda/blob/afe98b03c322fc4d22742869799c9f2796c79744/dist/ramda.js](https://github.com/ramda/ramda/blob/afe98b03c322fc4d22742869799c9f2796c79744/dist/ramda.js) of R.find() usage:

```javascript
const xs = [{a: 1}, {a: 2}, {a: 3}];
R.find(R.propEq('a', 2))(xs);
```

`R.find()` in this example returns `undefined` while it should return `{a: 2}`.

it works fine in 0.28.0.

**Comment by aqibmapari** [comment]
The order of arguments of propEq has changed in 0.29.0. Not sure if this was an intended change. Looks like a bug to me.
Changing the order of argument for propEq returns expected result.
Below code will provide desired result.
```
const xs = [{a: 1}, {a: 2}, {a: 3}];
R.find(R.propEq(2, 'a'))(xs);
```

https://ramdajs.com/repl/?v=0.29.0#?const%20xs%20%3D%20%5B%7Ba%3A%201%7D%2C%20%7Ba%3A%202%7D%2C%20%7Ba%3A%203%7D%5D%3B%0AR.find%28R.propEq%282%2C%20%27a%27%29%29%28xs%29%3B

**Comment by adamblok** [comment]
@aqibmapari Thank you for your help.

**Comment by kedashoe** [comment]
@adamblok thank you for reporting the issue. Would you like to submit a PR to update the docs?
