### ISSUE TITLE
`is` implementation can not pass leetcode testing

### ISSUE THREAD

**Issue by kayac-chang** [ramda/ramda#3375]
For https://github.com/ramda/ramda/blob/7ed79b4dd21e31271038d22e8533ef154a182cbc/source/is.js#L28 improvement.

Although leet code is not a real-world scenario, 
but I think is good to have an implementation to pass this [exam][1].

The re-implementation below can pass leet code exam, maybe we can consider using this:
```js
function is(Ctor, val) {
    if(val === null || val === undefined || typeof Ctor !== 'function') return false;
    return Object(val) instanceof Ctor;
}
```

another implementation is following the prototype chain
```js
function is(Ctor, val) {
    if (val === null || val === undefined) {
      return false
    }

    if (val.constructor === Ctor){
        return true
    }

    return is(Ctor, Object.getPrototypeOf(val))
}
```

[1]: https://leetcode.com/problems/check-if-object-instance-of-class/

**Comment by kedashoe** [comment]
I don't have a strong opinion here, but a PR would be good to see along with if there are any changes in which tests pass/fail, and what new tests would pass with the change.

**Comment by jlissner** [comment]
Both of these implementations don't work as I would expect it. Both of them would fail one of the existing examples:

```javascript
is(Object, 's') // returns true, but should be false
```

**Comment by kayac-chang** [comment]
> Both of these implementations don't work as I would expect it. Both of them would fail one of the existing examples:
> 
> ```js
> is(Object, 's') // returns true, but should be false
> ```

Hey @jlissner,
this is also the weird part of me, I couldn't fully understand.

In leetcode exam, they actually consider `'s'` is an Object instance,
but in ramda we consider 's' is not an Object instance.

I just wonder which is the standard way to understand about this.

**Comment by jlissner** [comment]
Let's say I have a variable named `maybeJson`, and I know that `maybeJson` could either be a `string` or an `object`, like a stringified JSON or an already parsed JSON, I might write something like

```javascript
const definitelyAnObject = R.when(R.is(String), JSON.parse)(maybeJson);
// or
const definitelyAnObject = R.unless(R.is(Object), JSON.parse)(maybeJson);
```

and I'd expect them both to work. If `is(Object, 's')` returns `true`, then my code isn't going to work as expected.

All this to say, I believe that `is(Object, 's')` SHOULD return `false`.

**Comment by kayac-chang** [comment]
> Let's say I have a variable named `maybeJson`, and I know that `maybeJson` could either be a `string` or an `object`, like a stringified JSON or an already parsed JSON, I might write something like
> 
> ```js
> const definitelyAnObject = R.when(R.is(String), JSON.parse)(maybeJson);
> // or
> const definitelyAnObject = R.unless(R.is(Object), JSON.parse)(maybeJson);
> ```
> 
> and I'd expect them both to work. If `is(Object, 's')` returns `true`, then my code isn't going to work as expected.
> 
> All this to say, I believe that `is(Object, 's')` SHOULD return `false`.

Yes, the use case also make sense for me.

I think leetcode exam is not very satisfy the real world use case. 
Close this issue.

**Comment by CrossEye** [comment]
See also, https://fr.umio.us/the-philosophy-of-ramda/#somewhatsurprising for a discussion of this.

**Comment by FernandoBasso** [comment]
Also, I would like to point out that ECMAScript makes a distinction between a few literal values vs their object form, and `'s'` is a string *literal*, not a string object.
