### ISSUE TITLE
Cannot update a nested map via R.modifyPath

### ISSUE THREAD

**Issue by Kolis121** [ramda/ramda#3379]
I am trying to update a nested map i.e. put a new nested map inside the mother-nested map.

`R.modifyPath([path1, path2], updatedNestedMap, motherMap);`

I tried using the above but it does not work giving me the following error:

fn is not a function at _modify

**Comment by jlissner** [comment]
`R.modifyPath` expects a function, but you appear to be providing an object, I believe you want to use `R.assocPath` instead
