### ISSUE TITLE
propEq documentation error

### ISSUE THREAD

**Issue by adamatat** [ramda/ramda#3384]
Apparently, the `propEq` function temporarily had its argument order reversed from prop -> value to value -> prop before it was reverted.  However, the example on the ramdajs documentation for `propEq` shows the wrong order.

**Comment by kedashoe** [comment]
It's not been reverted? Currently value -> prop. https://ramdajs.com/repl/?v=0.29.0#?let%20x%20%3D%20%7Ba%3A1%7D%0ApropEq%281%2C%20%27a%27%2C%20x%29%3B

```ts
let x = {a:1}
propEq(1, 'a', x); // => true
```

**Comment by adamatat** [comment]
> It's not been reverted? Currently value -> prop. https://ramdajs.com/repl/?v=0.29.0#?let%20x%20%3D%20%7Ba%3A1%7D%0ApropEq%281%2C%20%27a%27%2C%20x%29%3B
> 
> ```ts
> let x = {a:1}
> propEq(1, 'a', x); // => true
> ```

#2938

**Comment by kedashoe** [comment]
Sorry I'm missing something. For me, the current documentation matches the current release. The `propEq` example from the docs is `const hasBrownHair = R.propEq('brown', 'hair');`, which is "value -> prop", which matches the current release.

**Comment by adamatat** [comment]
I am using 27.0.2, and I'm going to stay on that then.
