### ISSUE TITLE
[Bug] groupBy result keys order when 0 as first character

### ISSUE THREAD

**Issue by mathieutu** [ramda/ramda#3385]
Hi, and thanks for your work.

I'm trying to group items by there two first letters:
```js
const items = ["01 885", "01 200", "02 012", "83 903", "98 842"]

const groupedItems = groupBy(item => item.slice(0,2), items)
```

However when items are starting with a `0`, the  will be put at the end of the object.

For example, with the previous code: 
```js
keys(groupedItems) // ["83", "98", "01", "02"]
```

No problem for other strings.

Repro: 
- [Non working](https://ramdajs.com/repl/?v=0.29.0#?const%20items%20%3D%20%5B%2201%20885%22%2C%20%2201%20200%22%2C%20%2283%20903%22%2C%20%2298%20842%22%5D%0A%0Aconst%20groupedItems%20%3D%20groupBy%28item%20%3D%3E%20item.slice%280%2C2%29%2C%20items%29%0A%0Akeys%28groupedItems%29%20%2F%2F%20should%20be%2001%2C%2083%2C%2098%0A)
- [Working](https://ramdajs.com/repl/#?const%20items%20%3D%20%5B%2211%20885%22%2C%20%2211%20200%22%2C%20%2283%20903%22%2C%20%2298%20842%22%5D%0A%0Aconst%20groupedItems%20%3D%20groupBy%28item%20%3D%3E%20item.slice%280%2C2%29%2C%20items%29%0A%0Akeys%28groupedItems%29)

Am I doing something wrong?

Thanks for your help.

Mathieu.

**Comment by jlissner** [comment]
An objects keys are not guaranteed to be in any specific order. If you want the array of keys sorted, you will have to sort them. For more reading, you can check out https://javascript.plainenglish.io/are-javascript-object-keys-ordered-and-iterable-5147eedb26ce

**Comment by mathieutu** [comment]
In theory yeah, but in practice it's weird to see that it respects the initial order, except with key starting with 0. Don't you think?

**Comment by jlissner** [comment]
This is, in practice, how JavaScript works.

```javascript
var x = {};
x['01'] = true;
x['11'] = true;

Object.keys(x) // ['11', '01']


var y = {};
y['11'] = true;
y['12'] = true;

Object.keys(x) // ['11', '12']
```

**Comment by mathieutu** [comment]
🤯 

Indeed, 
```js
Object.entries({ '01': 'foo',  '11': 'bar'}) // [ [ '11', 'bar' ], [ '01', 'foo' ] ]
```

My bad, sorry for the noise.

**Comment by mathieutu** [comment]
For the record, this is because when getting the keys, JS puts the numbers first, then the strings. And `'11'` is cast as a number, while `'01'` can't be and is a string.

See https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinaryownpropertykeys

**Comment by bunglegrind** [comment]
another glorious wat moment for javascript

https://www.destroyallsoftware.com/talks/wat
