### ISSUE TITLE
Ramda is 3x slower because it uses the arguments object?

### ISSUE THREAD

**Issue by icetbr** [ramda/ramda#3396]
Hi, I'm no expert, and I don't know exactly what this means. I was benchmarking some ideas when I saw this. It is a simple benchmark, just add 2 tests of any function. I'm using filter.

https://github.com/icetbr/experiments/tree/main/perf/packages/arguments

Quoting from my repo:
```js
suite
    .add('ramda 1', function () {
        return R.filter(x => x % 2 !== 0)(numbers);
    })

    .add('ramda 2', function () {
        return R.filter(x => x % 2 !== 0)(numbers);
    })
```
```
ramda 1 x 2,988,212 ops/sec ±1.41% (23 runs sampled)
ramda 2 x 964,727 ops/sec ±1.70% (20 runs sampled)
```

See the ts-belt test for the with/without arguments test.

One possible explanation

> The difference between using arguments vs. not using it could be anywhere between 1.5 times to 4 times slower, depending on the browser
> -- <cite>[stackoverflow][1]</cite>

[1]: https://stackoverflow.com/questions/5325554/javascript-functions-and-arguments-object-is-there-a-cost-involved

**Comment by jhonnatangomes** [comment]
I'm sorry, but where exactly is the difference between these two functions?

**Comment by icetbr** [comment]
They're the same, on purpose, that's the test.

**Comment by jhonnatangomes** [comment]
Yeah, but how does one use the arguments object and the other doesn't if it's the same function? I'm confused about it.

**Comment by icetbr** [comment]
They both use it.

**Comment by jhonnatangomes** [comment]
Alright, now I get it.

**Comment by icetbr** [comment]
I don't think it affects your `isEven`. Would you try to inline it?

**Comment by kedashoe** [comment]
Ya that did it (not quite as dramatic)
```
┌────────────────────────┬────────────────────────┬────────────────────────┐
│ filter                 │ Hertz                  │ Margin of Error        │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ ramda 1                │ 8,461,934              │ 2.41%                  │
├────────────────────────┼────────────────────────┼────────────────────────┤
│ ramda 2                │ 5,847,963              │ 0.56%                  │
└────────────────────────┴────────────────────────┴────────────────────────┘

```
Strange one, not sure why

**Comment by icetbr** [comment]
The gap may be related to the benchmark library. Also the node version, perhaps other might chime in with their results.

**Comment by kedashoe** [comment]
ty for the issue @icetbr , closing as not actionable for ramda
