### ISSUE TITLE
R.without broke backwards compatibility on #2603

### ISSUE THREAD

**Issue by manotas-scv** [ramda/ramda#3418]
Previous to 0.29.0:
```js
R.without('abc', ['abc'])
```

returned an empty array

After 0.29.0 it doesn't.

The doc indicates that both arguments should be arrays, and I think that is the proper behavior. This happened when migrating from loadsh to ramda, which has a different behavior.

I don't expect it to work as before, but I'd suggest either a warning/error when the first argument is not an array, or a note on the migration guide.

**Comment by kedashoe** [comment]
Thank you, [upgrade guide](https://github.com/ramda/ramda/issues/3369) updated!
