### ISSUE TITLE
Support promises for pipe and pipeWith

### ISSUE THREAD

**Issue by b-sudhakar** [ramda/ramda#3438]
Currently pipe and pipeWith does not wait for promises to complete, enhance pipe functions to support promises.

**Comment by kedashoe** [comment]
Hi @b-sudhakar , you can use `andThen` for this. eg `pipeWith(andThen)` or `pipe(f, g, andThen(h))`. There is an example [in the andThen docs](https://ramdajs.com/docs/#andThen). Might be nice to add and `pipeWith` example as well, maybe to `andThen` and to the `pipeWith` docs. Would you like to submit a PR?

**Comment by b-sudhakar** [comment]
Thanks @kedashoe , let me take look and will create a PR.

**Comment by toni-sharpe** [comment]
@kedashoe thought I'd pick this up, there doesn't seem to be a PR, it's six months now
