### ISSUE TITLE
Add minify to partial build

### ISSUE THREAD

**Issue by Domixy500** [ramda/ramda#3451]
Hi all,
i like the partial build function to reduce some overhead.
Is there a way to to include a minify function in the partial build?
To get a **ramda.custom.js** and a **ramda.custom.min.js** as a result.
Like **ramda.js** and a **ramda.min.js**

Best regards.

**Comment by kedashoe** [comment]
I think this is best left up to the user, yes? Also this would require us to depend on a minifier..
