### ISSUE TITLE
Since v0.30 functions curried by Ramda break when used with `R.__` from another Ramda version 

### ISSUE THREAD

**Issue by semmel** [ramda/ramda#3458]
### Conditions
Your project uses a certain version of Ramda, say `v0.29.1`. 
You require/import a library which depends on a version of Ramda >= `v0.30`. This prevents deduplication of Ramda, so your project depends on two versions now.

![Screenshot 2024-05-01 at 17 24 04](https://github.com/ramda/ramda/assets/296476/ebc4e607-751c-49ff-b786-d983fe2b06a9)

In your project you use the `v0.29.1` placeholder `R.__` on a curried value-returning function imported from the dependent library.

### Error
When invoking the function with the last remaining argument you'll get an exception like "fn(...)(...) is not a function".
This is because `R.__` is not recognised as placeholder and simply delivered as argument to the original function. Thus the last `(...)` instruction tries to call a value.

### Demo

```javascript
// lib030/index.js and lib028/index.js
const 
  { add, curry } = require('ramda'),  // v0.30 or v0.28 resp.
  med = curry((a, b) => 2 / (1 / a + 1 / b));
  
  module.exports = {
    add, med
  };

// proj029/index.js
const 
  { __ } = require('ramda'),  // v0.29.1
  { add: add030, med: med030 } = require('lib030'),
  { add: add028, med: med028 } = require('lib028');

med030(__)(4)(1); // throws "… not a function"
add030(__)(1)(2); // throws "… not a function"

// importing from older Ramda versions works:
console.assert(med028(__)(4)(1) === 1.6);
console.assert(add028(__)(1)(2) === 3);
```

### Reason for the behaviour
In #3388 we switched from duck-typing to  identity (`===`) comparison in `isPlaceholder`. The placeholder from a particular version of Ramda is no longer recognised by the `curry` function of another Ramda version.

### Previous behaviour
With `v0.29.1` and below, cross-version compatibility is given.

**Comment by Harris-Miller** [comment]
Ohh good catch. I think just this part needs to be reverted: https://github.com/ramda/ramda/pull/3388/files#diff-cfb81eb9592aa5597e5aa32c6e449214f5b7eabeb172ad2447e2e537232454d2L2-R4
