### ISSUE TITLE
R.head documentation doesn't meet the test

### ISSUE THREAD

**Issue by ivshalin** [ramda/ramda#3476]
Hi Team,
Documentation states that R.head('') should return undefined. A comment in master/source/head.js also says it. However, a test written for this function in master/test/head.js states that R.head('') should return '' (an empty string). Is it a bug in documentation or in function itself?

**Comment by kedashoe** [comment]
Looks to me like the documentation is wrong. `head` uses our internal `_nth` under the hood, which in turn uses `charAt` for strings. `charAt` returns the empty string if the index is out of bounds (undefined seems more correct to me in this case, but that is another matter).

Would you like to submit a PR to update master/source/head.js docs?

**Comment by Harris-Miller** [comment]
Heads up `R.last('')` has the same problem

**Comment by ivshalin** [comment]
Thank you for the answers!
Yes, looks like the root cause is how `_nth` function works.

I've noticed what "Try Ramda" page shows a bit different behavior.
`R.nth(11, '')` returns `undefined` (as documentation says) [check](https://ramdajs.com/repl/?v=0.30.1#?R.nth%2811%2C%20%27%27%29), but ramda from npm package returns an empty string in this case. The reason is that `_nth` function from `ramda.min.js` doesn't use `charAt` method under the hood, it tries to get the value from string by the index directly instead 
<img width="254" alt="_nth" src="https://github.com/ramda/ramda/assets/1625968/5eaf8552-7e02-4fa6-8d62-6383c066fbc2">
When we try to get something out of String's boundaries we receive undefined. So, we should decide which answer is right first, empty string or undefined and fix code or documentation after

**Comment by kedashoe** [comment]
Ya it is the minifier doing that. I do prefer though that it return undefined as the array version does. A breaking change unfortunately. I suspect it is not common to use `head`, `last`, etc on strings? If it were common, I would have expected this issue to be raised previously.

Thoughts anyone? Update the impl to match the docs (and the minifier)? Or update the docs?

**Comment by Harris-Miller** [comment]
I wouldn't call fixing this to return undefined a breaking change. We're not changing the function signature, we're aligning the runtime behavior to that signature. And like you said, very rare use case likely

**Comment by Harris-Miller** [comment]
I prefer it to return undefined as well, aligning with array behaviors is important for interop with nother functions that work with both strings and arrays

**Comment by ivshalin** [comment]
I agree with undefined too. It will make consistency for strings and arrays and also will match the docs

**Comment by kedashoe** [comment]
> I agree with undefined too. It will make consistency for strings and arrays and also will match the docs

:+1: Would you like to submit a PR for it @ivshalin ?

**Comment by ivshalin** [comment]
@kedashoe  Yes, here it is #3477
