### ISSUE TITLE
`lensPath` doesn't accept negative indexing

### ISSUE THREAD

**Issue by AlexFrazer** [ramda/ramda#3478]
Here's what I am trying to do. I have a list of pages from `@tanstack/react-query`. When I take some action, I want to either append or update an item in _the last page_. I wanted to do something like this:

```typescript
interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  size: number;
}

const lastPageLens = lensPath(["pages", -1, "items"]);

const upsert = curry(function upsert(item: T, data: T[]) {
  const index = findIndex(propEq('id', item.id), data);
  return index < 0
    ? append(item, data)
    ? adjust<T>(index, mergeLeft(item), items)
});

function optimisticInsert<T>(item: T, data: InfiniteData<PaginatedResponse<T>>) {
  return over(lastPageLens, upsert(item));
}
```
However, when I run this, it will attempt to set the lens on `-1` in pages, i.e.
```typescript
{
  pages: {
    0: [some pages],
    -1: [the thing I wanted to upsert]
  }
}
```
I don't think this is intentional, as when I looked at `update` and `adjust`, they allowed for negative indexing

**Comment by Harris-Miller** [comment]
> I don't think this is intentional, as when I looked at update and adjust, they allowed for negative indexing

You're correct. `lensPath()`'s `getter` [function](https://github.com/ramda/ramda/blob/master/source/internal/_path.js#L13) utilizes `R.nth`, which works with negative indexes, but the `setter` [function](https://github.com/ramda/ramda/blob/master/source/internal/_assoc.js#L19) is doing regular index accessing
