### ISSUE TITLE
forEach: function or object?

### ISSUE THREAD

**Issue by donnut** [ramda/ramda#360]
During creating a ramda definition type file for TypeScript I run into a problem with forEach.idx. This is a bit of an awkward function definition. `forEach` is a function with some signature. No problem there. But then we get `forEach.idx`. Of course it is a function too, but it is also a property of `forEach`. In javascript a completely legitimated construction, but I am not sure how this translates to the type theory (of which I know very little). Is it a option to rename the `forEach.idx` to `forEachIdx` (and `reduce.idx`, etc)? That would make my life a bit easier anyway.

**Comment by CrossEye** [comment]
ping @donnut: Someone was asking today in the [Gitter room][gr] if we had a bridge to Typescript.  I remembered that you had worked on one.  Did you ever complete it?  Has it been kept up-to-date?


  [gr]: https://gitter.im/ramda/ramda
