### ISSUE TITLE
let's explore lazy evaluation

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#446]
transducers.js is pretty slick. I'd like to see a way to provoke lazy evaluation of ramda compositions, e.g.:

`R.compose(R.filter(someFn), R.map(someOtherFn), R.lazily)`

... where lazily would change the evaluation strategy of the composition. This will probably mean some invasive changes to ramda core fns such as `map`, `reduce`, etc. but that seems like a nice API

**Comment by davidchambers** [comment]
@buzzdecafe, are you ready to open a pull request for your xduce branch? It needn't be complete in order to garner feedback.

**Comment by buzzdecafe** [comment]
sure, let me rebase and make a pr

**Comment by kevinbeaty** [comment]
See #878

**Comment by buzzdecafe** [comment]
superseded by #878
