### ISSUE TITLE
R.until, R.while ? Looping

### ISSUE THREAD

**Issue by fyyyyy** [ramda/ramda#564]
I'm not sure yet how to create loops of functions in Ramda ?

So i thought something like this may be handy ?
```js
var cycle = R.until(R.gt(100), R.add(-1), R.multiply(2), R.add(2))
cycle(1) => // 102

R.while(R.eq(undefined), findNext)

**Comment by CrossEye** [comment]
Closing without prejudice.  We can revisit later if desired.
