### ISSUE TITLE
mapAccuml and mapAccumR

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#632]
Apologies if this also already exists, but could not find it in the docs:

mapAccumL: http://hackage.haskell.org/package/base-4.7.0.1/docs/Data-List.html#v:mapAccumL
mapAccumR: http://hackage.haskell.org/package/base-4.7.0.1/docs/Data-List.html#v:mapAccumR

**Comment by Izhaki** [comment]
Any justification why scan returns both the final accumulator (which by some seen as the intermediate value) AND the mapped list? After all, can't you just get the last item of the mapped list?

**Comment by buzzdecafe** [comment]
> Any justification why scan returns both the final accumulator (which by some seen as the intermediate value) AND the mapped list? After all, can't you just get the last item of the mapped list?

`scan` does not do that, it returns a single list.

`mapAccum` returns both the accumulator and another value, but nothing says it has to be the accumulator as well. For example:

```js
R.mapAccum((a, b) => [a+b, b], "",  ['1', '2', '3', '4']); //=> ["1234", ["1", "2", "3", "4"]]

R.mapAccum((x, y) => [x, x*y], 5, [9,6,3]); //=>  [5, [45, 30, 15]]

R.mapAccum((x, y) => [x+y, x*y], 5, [2,4,8]); //=>[19, [10,28,88]]
```

etc.

**Comment by Izhaki** [comment]
Thanks so much @buzzdecafe, and sorry for mixing it up with `scan`.

Other than the example provided, any practical examples (ie, use cases)?

It just happens that I came across this signature whilst working on a lazy tree implementation for a client that had a 2-stage algorithm and that signature is just gold for that scenario. But I can't think of other scenarios outside trees.
