### ISSUE TITLE
update path to ramda.min.js in jsdelivr/jsdelivr

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#661]
Presumably `files.include` should be changed to `["dist/ramda.min.js"]` in [__update.json__][1]. @megawac, can you confirm this and also advise us as to the appropriate timing?

[1]: https://github.com/jsdelivr/jsdelivr/blob/master/files/ramda/update.json

**Comment by davidchambers** [comment]
https://github.com/ramda/jsdelivr/compare/jsdelivr:master...ramda

**Comment by jimaek** [comment]
@davidchambers basepath should be inside `files`, here is the format https://github.com/jsdelivr/libgrabber#add-updatejson-schema

**Comment by davidchambers** [comment]
Thanks, @jimaek! I've updated that branch.

**Comment by jimaek** [comment]
:+1:

**Comment by CrossEye** [comment]
@davidchambers: I never really payed attention to this issue.  Can it be closed now?

**Comment by davidchambers** [comment]
Not yet. We need to submit a pull request to jsDelivr *after* publishing a new version.
