### ISSUE TITLE
R.call is undefined

### ISSUE THREAD

**Issue by safareli** [ramda/ramda#671]
i saw 'R.call' in documentation but it isn't in current version and not in`/dist/ramda.js` so when it will be available?

**Comment by Dakuan** [comment]
also seeing this in 0.8.0

**Comment by Dakuan** [comment]
(installed via npm)

**Comment by davidchambers** [comment]
`R.call` was added after the publication of 0.8.0: https://github.com/ramda/ramda/compare/v0.8.0...master. It'll be included in 0.9.0 which we plan to release in the next few weeks.
