### ISSUE TITLE
Ramda command line

### ISSUE THREAD

**Issue by jpospychala** [ramda/ramda#682]
hi,
I'm under great impression from using ramda in NodeJS. It makes processing JSON a real joy. What struck me recently was that having tool like ramda in shell would make a great sense for writing all sorts of scripts that talk with REST APIs.
I've been prototyping a tool like that following some of ramda concepts and created https://github.com/jpospychala/rcli
I don't see why ramda npm package couldn't have an executable that exposes some pretty cli api.

**Comment by buzzdecafe** [comment]
thanks for letting us know about this project!

**Comment by raine** [comment]
Here's a bit different approach: [ramda-cli](https://github.com/raine/ramda-cli)

**Comment by CrossEye** [comment]
:100:

**Comment by wayneseymour** [comment]
I like the idea of `ramda-cli`.
