### ISSUE TITLE
Supporting more than just arrays

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#695]
So, the issue I'm facing is that I want to use ramda everywhere in my project, but I am frequently dealing with other kinds of data structures (for example, facebook's immutable data structures). Currently I'm just wrapping up immutable's methods in curryN's to get similar behavior, but it really would be nice to translate the increasing amount of work in this library in other places (for example, immutable *does* have map, but it doesn't have some of the other funcs, and these just need to be re-written (often times copy-pasting with minimal changes)). I was wondering whether consideration had been given to generalizing these functions, perhaps against JS's iterator spec ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/The_Iterator_protocol )?

However, this only covers half the equation because it doesn't really define what the *result* type should be unfortunately. Perhaps (at least internally), iteration methods could be defined in terms of two base functions: next and push, which would form an iterable-instantiable tuple: [next, push]. For example, say we defined map as so:

```javascript
function map(f, iterable)
{
    next = iterable[0],
    push = iterable[1];
    result = push();
    while ([value, next, done] = next())
    {
        if (done)
            return result;

        result = push(result, f(value));
   }
}
```

So, for arrays it would be something like this:

```javascript
function arrayToIterable(anArray)
{
    return [ arrayNext(anArray, 0) concat]
}

function arrayNext(anArray, anIndex)
{
    function ()
    {
        return [anArray[anIndex], anIndex < anArray.length - 1, next(anArray, anIndex + 1)];
    }
}

function arrayPush(lhs, value)
{
    if ( arguments.length === 0)
       return [];

   lhs.push(rhs);

   return lhs;
}
```

So now map(f, arrayToIterable([1,2,3])) works fine. To make it even more painless for the array common case:

```javascript
function toIterable(anObject)
{
    if (anObject.next && anObject.concat)
        return anObject;

    if (Array.isArray(anObject))
        return arrayToIterable(anObject);

    if (anObject.toIterable)
        return anObject.toIterable();

    return objectToIterable(anObject);
}

function map(f, iterable)
{
    iterable = toIterable(iterable); // no op for existing iterables...
}
```

Now map(f, [1,2,3]) works again. And if we fill in the missing objectToIterable:

```javascript
function objectToIterable(anObject)
{
    return [ objectNext, objectPush];

}

function objectNext(anObject, keys, index)
{
    return [[anObject[keys[index]], keys[index]], index < keys.length - 1, objectNext(anObject, keys, index + 1)];
}

function objectPush(anObject, keyvalue)
{
    if (arguments.length === 0)
        return { };

    anObject[keyvalue[1]] = keyvalue[0];

    return anObject;
}
```

Now all of a sudden map works for objects right out of the gate: 

```
map(function(keyvalue) { return [keyvalue[0], toUpperCase(keyvalue[1])]; }, { "hEllo" : 5, "bye": 0 });
```

And it gives me the ability to take Facebook's immutability library and add this:

```javascript
List.prototype.toIterable = function()
{
   return [ ListNext(aList, 0), function(aList, aValue) { return aList.push(aValue); } ]
}

function ListNext(aList, anIndex)
{
    if (arguments.length === 0)
        return new List();

    return [aList.get(anIndex), anIndex < aList.size - 1, ListNext(aList, anIndex + 1) ];
}
```

And now I can use all of Ramda's funcs with facebook's work. Also interesting, is that I can actually get translate functions for free, by just doing this:

```javascript
iterable = myList.toIterable();
iterable.push = arrayPush;
toArray = R.map(R.identitity, iterable);
array = toArray(myList);
```

**Comment by JAForbes** [comment]
@buzzdecafe 

> We already dispatch to any object that implements map

I had no idea!  Could this be generalised for all Ramda iterating functions?  This is the main reason I still have lodash in most projects.  I use objects _much_ more than arrays, but find Ramda gives preferential treatment to arrays.

I really like this feature.

**Comment by buzzdecafe** [comment]
@JAForbes yeah, we should make a bigger deal about that feature. At present we dispatch on most of the Fantasy-Land "methods", and a few more for lazylist integration. I'm working with @kevinbeaty on implementing list iterators as transducers which may make what you are after easier

**Comment by fyyyyy** [comment]
Iterating linked lists vs array is about 50x faster in most browsers (Made this point somewhere else already, cant remember where)
http://jsperf.com/usage-of-linked-list-vs-array/17
This would be something i would love to have, also for copying immutable large lists, the linked list would be much more efficient allowing shared memory items as in Clojure.

**Comment by CrossEye** [comment]
While there might be some good information there, that perf test is significantly flawed.

The linked list and array implementations have different behavior.  It's pretty useless to compare them.  Also, really, what's the point of comparing single-element iterations?  Why bother?

I'm also not a fan of comparing multiple different things in a single JSPerf test, but that's secondary.

It seems likely that a linked list like this might have pretty good iteration performance, but this test fails to demonstrate it.

**Comment by CrossEye** [comment]
Although this has some interesting ideas in it, and the work @buzzdecafe and @kevinbeaty have been doing on transducer integration is related, I don't think this issue involves any further action for now.  Closing without prejudice.
