### ISSUE TITLE
Individual function packages for npm

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#697]
I'd like to enable individual function downloads from npm. So if you just want `map` and `filter` you don't have to pull down the whole lib, nor build it yourself.

the question is: do we include dependencies in the package, or reference them in package.json and let npm figure it out?

**Comment by nikolayhg** [comment]
it would be great to have ramda like amp from Ampersand.js:
* http://amp.ampersandjs.com/
* http://blog.andyet.com/2015/01/07/modularizing-underscorejs

**Comment by CrossEye** [comment]
@nikolayhg: Something like that has been on my wish-list since early on.  I'm not sure if we'll manage to get to it, and if so, when, but I agree that it would be very nice to have.

**Comment by davidchambers** [comment]
I don't think this approach makes sense given how many Ramda functions are defined in terms of other Ramda functions. Assume one wants three Ramda functions: `foo`, `bar`, and `baz`. All three are defined in terms of `quux`. If one were to use standalone packages for the three functions one would end up defining `quux`, internally, three times. This would compress well, of course, but the alternative seems simpler:

```console
$ ./scripts/build -- foo.js bar.js baz.js >path/to/app/scripts/ramda-custom.js
```

**Comment by CrossEye** [comment]
@davidchambers: There aren't that many deep dependencies.  So they could be used as individual modules much more easily than could be the lodash deep dependency trees.  When working in Node, this sort of repetition of dependencies is considered normal; at some threshold, presumably it would make more sense to switch to a full version of Ramda.  When working with something like browserify, I assume there is something done to avoid repeated dependencies, no? 

But I was thinking more of a UI built on top of the `scripts/build` that would let you easily create your custom build online, much the way [Modernizr][md] and [jQueryUI][ju] do.  That's what I would love to see one day.


  [md]: http://modernizr.com/download/
  [ju]: http://jqueryui.com/download/

**Comment by jdalton** [comment]
> So they could be used as individual modules much more easily than could be the lodash deep dependency trees

With [lodash 3.0](https://github.com/lodash/lodash/releases/tag/3.0.0) those are a thing of the past:
<table><tbody>
<tr><td valign="top">
<img src="http://f.cl.ly/items/2P1g0x0d0u2q3N0d022J/v2-dep-graph.png" alt="v2 dep graph" height=60% width=60%>
</td><td valign="top">
<img src="http://f.cl.ly/items/1q0h3Y3C3A2n351B0e0S/v3-dep-graph.png" alt="v3 dep graph" height=40% width=60%>
</td></tr>
</tbody></table>

**Comment by CrossEye** [comment]
@jdalton That's a huge improvement!

**Comment by jdalton** [comment]
> That's a huge improvement!

Thanks! With v3 we’ve improved [lodash-cli’s](https://www.npmjs.com/package/lodash-cli) ability to inline dependencies allowing us to easily customize inlining per method, enabling a better balance between deep dependency graphs & code duplication.

**Comment by davidchambers** [comment]
> When working in Node, this sort of repetition of dependencies is considered normal; at some threshold, presumably it would make more sense to switch to a full version of Ramda.

When writing server-side JavaScript file size is not important. If I were to depend on Ramda at all I'd simply add `"ramda"` to __package.json__. For browser development, though, individual packages or custom builds are very useful. I favour the latter, if it's to be one or the other.

**Comment by davidchambers** [comment]
Shall we close this in favour of #829?

**Comment by buzzdecafe** [comment]
ok
