### ISSUE TITLE
R.noop

### ISSUE THREAD

**Issue by mondalaci** [ramda/ramda#701]
It'd be useful to have a function that doesn't do anything.

```
R.noop = function() {}; // obviously, noop stands for no operation
```

Could be used in scenarios like:

```
(functionArray[selectedItem] || R.noop)();
```

**Comment by buzzdecafe** [comment]
if no one wants to fight for it, i'm gonna close it

**Comment by despairblue** [comment]
I'd like that function since it makes the use case below was easier:
```javascript
var noop = () => undefined

R.cond(
  [R.eq('Known Error 1'), noop],
  [R.eq('Known Error 2'), noop],
  // something we don't expect and thus want to log
  [R.T, error => error]
)('Known Error 1')

// instead of  

R.cond(
  [R.not(
  	R.anyPass([
      R.eq('Known Error 1'),
      R.eq('Known Error 2')
    ])
  ), error => error]
)('Known Error 1')
```

the noop function would ignore all arguments, return undefined and have no side effects, basically be `function(){}` or `() => undefined`

**Comment by CrossEye** [comment]
There are three questions:

  - is the function useful?
  - does it fit well with Ramda?
  - is it easy to work around not having it?

Clearly it's useful.  I use some version of it often.

But I don't think it fits well with Ramda.  Ramda is about dealing with values.  This would be very much an oddball function in Ramda.

And it's very easy to create, either manually, as you've done in your example, or with Ramda:

    var noop = R.always(undefined);

If you want to use ramda's `R` as a namespace for your own functions, you could do this:

    R.noop = R.always(undefined);

I don't have a serious objection to this; it simply doesn't feel like a good fit.

**Comment by mondalaci** [comment]
I don't think that the "it's easy to create" argument is a valid one. I personally rather don't want to extend libraries in any ways because later on a developer can come along looking up the library reference and (s)he won't find the function that I added, leading to confusion.

**Comment by buzzdecafe** [comment]
> I don't think that the "it's easy to create" argument is a valid one

I don't think that is especially persuasive either. IMO the best arguments are:

1. as above: "IMO ramda should be about evaluating expressions, as opposed to performing operations." (_argumentum ab auctoritae maea_?)
2. `noop` is just sugar for `always(undefined)`

**Comment by CrossEye** [comment]
I absolutely agree that "ramda should be about evaluating expressions, as opposed to performing operations."   (So it's at least _argumentum ab auctoritate nostra_.)

**Comment by despairblue** [comment]
Ok, convinced :)

**Comment by microcipcip** [comment]
@despairblue and anybody getting to this thread...[noop is available](https://char0n.github.io/ramda-adjunct/2.7.0/RA.html#.noop) in Ramda Adjunct

**Comment by tommmyy** [comment]
... and [Ramda-extension](https://ramda-extension.firebaseapp.com/docs/#noop) for really long time

**Comment by microcipcip** [comment]
@tommmyy OMG I had no idea about this project, thanks :)
