### ISSUE TITLE
Add step to range

### ISSUE THREAD

**Issue by bobiblazeski** [ramda/ramda#702]
Please add step to range like lodash, very important to avoid reversal of the result and sub integer
_.range(5,2,-0.5)
[5, 4.5, 4, 3.5, 3, 2.5]

https://lodash.com/docs#range
_.range([start=0], end, [step=1])

_.range(0, -4, -1);
// → [0, -1, -2, -3]

**Comment by alexandermckay** [comment]
I very rarely have to use a range with a step but something like this works for me:
`const isEven = compose(equals(0), modulo(__, 2))`
`const r = range(0, 10)`
`const wStep = filter(isEven, r) // [0, 2, 4, 6, 8, 10]`
