### ISSUE TITLE
A zipWith operator with many lists

### ISSUE THREAD

**Issue by xgrommx** [ramda/ramda#707]
Hello everyone,

Why I cannot use ramda zipWith with many lists? In RxJs library I can use it http://xgrommx.github.io/rx-book/content/core_objects/observable/observable_methods/zip.html#using-arguments like arguments of function.

**Comment by CrossEye** [comment]
Closing for now.  If someone wants to create a PR for a version of `zipWith` that accepts a list of lists, we will certainly consider it.

**Comment by kirilloid** [comment]
Why not use approach like in Haskell with `zipWith3`?

**Comment by CrossEye** [comment]
(Sorry for the slow reply: just back from vacation.)

We've tried to stay far from that.  As much as I like Haskell, that's one of its real warts.  I understand the necessity in Haskell, but creating these many numbered versions of the same function bothers me.  And what do you do if you need `zipWith6` but only `zipWith2` through `zipWith5` are available?

**Comment by tms1337** [comment]
> (Sorry for the slow reply: just back from vacation.)
> 
> We've tried to stay far from that. As much as I like Haskell, that's one of its real warts. I understand the necessity in Haskell, but creating these many numbered versions of the same function bothers me. And what do you do if you need `zipWith6` but only `zipWith2` through `zipWith5` are available?

But what if these are dynamically generated, for example `zipWith${N}`

**Comment by CrossEye** [comment]
The answer above from @davidchambers will still suffice, so long as you change the old `foldl` to `reduce`.  Or if you want a recursive version, something like this should do (untested):

 ```js
const zipWithAll = (fn) => ([xs, ...xss]) => 
   xs == undefined 
     ? []
   : xss.length == 0
     ? xs
   : zipWith (fn) (xs, zipWithAll (fn) (xss))
```

**Comment by uriva** [comment]
```javascript
// Zip some arrays by the length of the first.
const zip = (...arrays) => arrays[0].map((_, i) => arrays.map((arr) => arr[i]));
```
