### ISSUE TITLE
Add Lo-Dash / Underscore style chaining.

### ISSUE THREAD

**Issue by geekflyer** [ramda/ramda#710]
Hi all,

I wonder if there's a specific reason Ramda does not have the Lo-Dash style chaining? If not I would suggest the following feature. If you're fine with it I would implement it and send a pull request.

E.g. I would like sometimes to use:
```js
R()   // starts a Ramda chaining (not to be confused with the R.chain() thing) and returns a special Ramda chaining wrapper
.pluck('a')
.pluck('b')
.filter(R.propEq('c','foo'))
.map(doSomething)
.end()   // is ending the chain, similar like value() in Lo-Dash and returns a function which executes the specified Ramda operations in order.
```

In addition one could provide a value right at the beginning, so that end() would not return a function but instead the result of all the operations performed on the supplied value.

E.g. 
```js
var data = [{a:{b:{c:"foo"}}},{a:{b:{c:"bar"}}}

R(data)
.pluck('a')
.pluck('b')
.filter(R.propEq('c','foo'))
.end()  // --> returns [{c:"foo"}]
```

I know that there's R.pipe which performs a similar thing, but I often feel for longer chains the proposed style is more elegant and easier to read (might be a personal preference though). Also it's more convenient for users familiar with Underscore and Lo-Dash.

The equivalent R.pipe example would look the following:

```js
var data = [{a:{b:{c:"foo"}}},{a:{b:{c:"bar"}}}

R.pipe(
R.pluck('a'),
R.pluck('b'),
R.filter(R.propEq('c','foo'))
)(data)   //  --> returns [{c:"foo"}]
```

What do you think?

**Comment by fyyyyy** [comment]
https://www.youtube.com/watch?v=m3svKOdZijA

**Comment by geekflyer** [comment]
Hi @fyyyyy . Thx for the video. 
I get the point of flipping the arguments and autocurrying but for I don't think a compose or pipe necessarily reads better or composes better then a chain. 
* He says wrapping the value with _.chain and unwrapping it with value() is clutter, but effectively _.compose is also 1 line of clutter.
* For compose a you have to repeatetly prefix all ramda operations with the Ramda identifier `R.` which is clutter too.
* One has to surround all the operations into a set of braces, e.g. R.compose(op1,op2) and for a long set of operations the opening and closing braces would be at very different lines which makes it sometimes hard to track / write the right number of closing braces. 
* What I understand is that compose / pipe is more flexible, in that you can easily plug in non-ramda functions, but I tend to use >90 % ramda functions for my pipelines. Plugging in non ramda functions could still be done by using R.tap or something new like R.intercept. Eg.
```js
R()
.filter(R.propEq('c','foo'))
.intercept(nonRamdaFunc)
.end()
```

* advantage to underscore / lo -dash is that one can avoid tying operations to data, by using `R()` instead of `R(data)` which matches Ramda's currying behaviour.
* Commenting out the last operation in a R.compose or R.pipe potentially raises a syntax error, because of the comma, while with chaining it does not.
E.g.
```
R()
.filter(R.propEq('c','foo'))
//.intercept(nonRamdaFunc)   // no syntax error
.end()

R.pipe(
R.filter(R.propEq('c','foo')),   //syntax error because of comma
//nonRamdaFunc 
);
```

**Comment by CrossEye** [comment]
I can think of two major objections to this style for Ramda.  Both have to do with the underlying philosophy of Ramda.

First, Ramda is designed to help you work with little or no mutable state; that is one of the fundamental features of functional programming.  The output of Ramda functions is determined solely by the values of their parameters; no global state, no external configuration, no hidden closures are used to vary how your function behaves.  If we were to start down this road, Ramda itself is introducing state into the mix.  The output of the `.filter` method of a chained object would now depend upon the state of that object.

    R([1, 2, 3, 4, 5]).filter(isEven).end(); //=> [2, 4]
    R([1, 2, 3, 4, 6]).filter(isEven).end(); //=> [2, 4, 6]

Second, Ramda is predicated on the idea of building up functions out of smaller ones.  The currying and the parameter order is designed to support this workflow.  Chaining is the antithesis of this.  The expected general usage would be to create named functions for any useful groupings of functions:

    var myFunc = R.pipe(
        R.pluck('a'),
        R.pluck('b'),
        R.filter(R.propEq('c','foo'))
    );

    var data = [{a:{b:{c:"foo"}}},{a:{b:{c:"bar"}}}

     myFunc(data); //=> [{c:"foo"}]

That wouldn't make much sense with a chained version.  Perhaps we could get it to work, but even if we did, it would still limit usage to internal Ramda functions, which again is very much against the spirit of the library.

> Also it's more convenient for users familiar with Underscore and Lo-Dash.

That's never going to be a primary focus of Ramda.  Javascript has always had its functional side, but for many years, few people took advantage of it.  jQuery, for all its warts, offered some slight steps toward functional programming.  Underscore and Lo-Dash offer some more.  But none of these are really designed around the idea of promoting functional programming the way Ramda is.  Ramda is more than willing to break with how these libraries do things when they don't mesh well with Ramda's underlying philosophy.  This is definitely one of those times.

**Comment by fyyyyy** [comment]
@geekflyer 
Hmm agreed :+1:  chaining is not necessarily more clutter than composing. However you could avoid comma comment errors with a comma first policy. So this only comes down to syntax preference, possibly saving some R. with chain at the expense of ramda code size and also performance/memory due to wrapping/unwrapping.

```js
R.pipe(
R.filter(R.propEq('c','foo'))   //no syntax error because of comma first
//,nonRamdaFunc 
);

**Comment by geekflyer** [comment]
@fyyyyy 

How about this one :smiley: 

```js
R.pipe(
//R.filter(R.propEq('c','foo'))   //syntax error with comma first :-)
,nonRamdaFunc 
,R.pluck('prop')
);
```

Comma first just moves the syntax error problem to the first function in your pipe, instead of the last one.

But yes, you're right - at the end it boils down to some syntax preference and comes at a certain expense. @CrossEye kind of convinved me that introducing `R(data)` is not worth the trouble because of the mutable state / data passed through, but I still kind of like the R() end() variant which returns a function. The chaining syntax with dots as seperator is just soo much more familiar - many js libraries use it (e.g. gulp / node streams, Highland.js) and also I know it from Apache Spark (Scala) and Apache Flink. Which syntax is better simply depends on the use case (ratio of ramda native to normal functions) imho.

I'm having a look at lo-dashs code at the moment, to figure out how they implemented the chaining and how much code that would impose for ramda, but I think runtime / memory overhead for wrapping is neglible. It's basically just some minor overhead of storing the metadata of a chain.

**Comment by fyyyyy** [comment]
well, true! But the first function in a pipe is more unlikely to be commented out. For compose that's reversed however and as such comma first is revealed as a silly policy :smile:

**Comment by CrossEye** [comment]
While 

    R()
        .ramdaFunction1(..params)
        .ramdaFunction2(..params)
        // ...
        .end()

could be made to work, or maybe more clearly something like `R.chain()... ...end()`, the trouble is that I don't think it should.

As already discussed, this makes non-Ramda functions second-class citizens.

But perhaps more importantly this simply adds a second way of working with Ramda without adding any functionality.  And since it doesn't work with non-Ramda functions (without some sort of wrapper, in any case), it couldn't serve as a replacement for the current syntax.  As such, it adds unnecessary complexity to the library.

I have no issue with some syntactic sugar, but reworking of the library to support a style of programming that is not central to the mission of Ramda, one that is unrelated to most functional programming environments, and to do this chiefly to make Ramda more familiar to those working in libraries that are not particularly close to the heart of FP, makes no sense to me.

Once again, I think it's time to mention Rich Hickey's talk, [Simple Made Easy][rh], the essense of which we try to incorporate in Ramda as best we can, keeping everything we can simple, even when that's not always the easiest option.

  [rh]: http://www.infoq.com/presentations/Simple-Made-Easy

**Comment by buzzdecafe** [comment]
i'm with @CrossEye on this
