### ISSUE TITLE
Explaining ramda

### ISSUE THREAD

**Issue by fyyyyy** [ramda/ramda#711]
Actually i almost skipped this beautiful ramda before even trying, after reading these lines and still not understanding what this library is about

`Using this library should feel as much like using Javascript as possible. Of course it's functional Javascript, but we're not introducing lambda expressions in strings, we're not borrowing consed lists, we're not porting over all of the Clojure functions.`

`Our basic data structures will be normal Javascript objects, and our usual collections will be Javascript arrays. We will not try to reach the point where all the functions have only zero, one, or two arguments. We will certainly try to keep some of the normal features of Javascript that seem to be unusual in functional languages, including variable length function signatures and functions as objects with properties.`

To be fair, my attention span was short, but this would be true for most folks browsing hundreds of github libraries. I was looking at other FP libraries that explained themselves somewhat better to the common JS guy.

Thankfully i had seen http://fr.umio.us/why-ramda/ which did a better job of explaining to me what ramda actually is and convinced me to give ramda a shot.

`Ramda does offer a different style of coding, a style that's taken for granted in purely functional programming languages: Ramda makes it simple for you to build complex logic through functional composition. Note that any library with a compose function will allow you do functional composition; the real point here is: "makes it simple".`

I believe, the first few sentences of your readme should provide a stronger case for why to use ramda. Kind of the elevator pitch.

**Comment by buzzdecafe** [comment]
i agree, you make an excellent point. do you want to do a PR?

**Comment by fyyyyy** [comment]
ok, will do :+1:

**Comment by CrossEye** [comment]
Absolutely.  We don't want a long sales-pitch in the ReadMe.  But it would be good to start with **why**.  At least some of the text that's there might be worth saving.  But feel free to start from scratch too.  Don't hesitate to drop the Eweda references; that's long-dead.

**Comment by CrossEye** [comment]
And also borrow as you like from my stuff on http://fr.umio.us/ .

**Comment by geekflyer** [comment]
Hi, I like the introduction text :+1: 

Only the example could show better I think, maybe something with deep nested properties or so, where ramda composes significantly better than chaining.

Actually a shorter version of the existing example in Lo-Dash and Ramda would look like so.

```js
var phonesSortedByName = function(users){
   return _.(users)
               .sortBy('name')
               .pluck('phone')
               .value();
     }
```
with Ramda's *list comes last* (Lego®) style

```js
     var phonesSortedByName = R.pipe(
               R.sortBy(R.prop('phone')),
               R.pluck('name'))
     );
```

**Comment by geekflyer** [comment]
Oh, forget about my comment :-) Looked at an old revision of your changes.
