### ISSUE TITLE
Add favicon to docs site

### ISSUE THREAD

**Issue by saikobee** [ramda/ramda#714]

**Comment by CrossEye** [comment]
At some point I made an .ICO file from our logo.  I'll see if I can find it.

**Comment by buzzdecafe** [comment]
you can find the original svg art here: http://ramda.jcphillipps.com/logo/

**Comment by CrossEye** [comment]
Perfect.  I just remade it, because I couldn't find the old copy!  :smile:

Glad it doesn't take long.  For years I've used png2ico, which is very easy.

**Comment by buzzdecafe** [comment]
seems to be done
