### ISSUE TITLE
publish 0.9.0

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#722]
Any reason not to do this now?

**Comment by buzzdecafe** [comment]
if the docs are good to go, then let's do it

**Comment by CrossEye** [comment]
Only thing I think worth waiting for is `eqDeep`.  I think the docs are in reasonable shape, and I'd love to have the current progress available on the docs site.  I want to pick up again with `addIdx` but that can be in the following version.

**Comment by davidchambers** [comment]
Let's use the [0.9.0 milestone][1] to track the remaining tasks.


[1]: https://github.com/ramda/ramda/milestones/0.9.0
