### ISSUE TITLE
`R.wrap` should make curried function

### ISSUE THREAD

**Issue by anton-rudeshko** [ramda/ramda#725]
Kind of strange, isn't it stated that every function in Ramda is autmatically curried?

```js
var wrappedAdd = R.wrap(R.add, function(add, x, y) {
  console.log('adding %s and %s', x, y); 
  return add(x, y); 
});

wrappedAdd(1) // "adding 1 and undefined" => NaN
wrappedAdd(1, 2) // "adding 1 and 2" => 3
```

I particularly interested in wrapping functions for debugging as shown in this example.

**Comment by CrossEye** [comment]
I'm trying to think through any unusual implications of this, but I think you're right.  This:

    function wrap(fn, wrapper) {
        return arity(fn.length, function() {
            return wrapper.apply(this, _concat([fn], arguments));
        });
    };

could easily become this: 
    
    function wrap(fn, wrapper) {
        return curryN(fn.length, function() {
            return wrapper.apply(this, _concat([fn], arguments));
        });
    };

Any other thoughts?

**Comment by davidchambers** [comment]
Sounds like a good idea to me.

**Comment by buzzdecafe** [comment]
:+1:

**Comment by anton-rudeshko** [comment]
@CrossEye, ***+1***

**Comment by CrossEye** [comment]
Unless someone beats me to it (or @anton-rudeshko, unless you want to create a PR), I'll try to get to it this evening.  (I'm still learning my way around an unfamiliar OS, so I'm a bit slow, but this should be straightforward.

**Comment by buzzdecafe** [comment]
> I'm still learning my way around an unfamiliar OS ...

@CrossEye is moving out of the dark (Windows) and into the light (GNU/Linux)

**Comment by CrossEye** [comment]
More specifically, Linux with an actual GUI! (In my case KDE.)  Linux is supposed to look like a plain terminal, damn it!

**Comment by buzzdecafe** [comment]
gui is just sugar. it's (turtle?) shells all the way down

**Comment by CrossEye** [comment]
Sorry, sugar's just too sweet for me, I guess.  Will try again tomorrow.  Maybe by then I can run things (like Mocha and Grunt) that I install with NPM!

**Comment by CrossEye** [comment]
I haven't forgotten this, just gotten behind.  (And I'm still having troubles with my new laptop.)  I will get to it soon.

**Comment by anton-rudeshko** [comment]
I don't hurry you =) Perhaps I'll make a PR on the weekend.
