### ISSUE TITLE
replace(str, ..., ...) only replacing first occurence

### ISSUE THREAD

**Issue by Cottin** [ramda/ramda#727]
docs: "Returns: string with all the matches replaced. "

```
replace( 'car', '', 'car boat car boat car' )
# expected: " boat  boat "
# actual: " boat car boat car"
```

it seems as if only the first match is replaced

**Comment by davidchambers** [comment]
Thank you for opening this issue. The function's description is incorrect and should be reworded. One would need to supply `/car/g` as the first argument to replace all occurrences of `car`.

**Comment by buzzdecafe** [comment]
this is consistent with existing js, e.g.:

`'car boat car boat car'.replace('car', '')`

to replace all, you can pass a regular expression, e.g.:

`replace( /car/g, '', 'car boat car boat car' )`

**Comment by buzzdecafe** [comment]
damn you are fast @davidchambers
