### ISSUE TITLE
curryN(3, ...) vs _curry2 / _curry3

### ISSUE THREAD

**Issue by neftaly** [ramda/ramda#728]
Hey everyone,

I'm playing around with an API function to accept an unlimited number of arguments, and am having a little trouble getting it to curry any more than 2/3 arguments. Apologies in advance if I've missed something simple; have only just picked this up.

Is there an existing way to implement `./internal/_curry` (or `./internal/_curryN`)?

---
---

The following works fine for 2 arguments:
```javascript
var _curry2 = require('./internal/_curry2');

module.exports = _curry2(function doSomething() {
    return stuff;
});
```

---

The following works fine for 3 arguments:
```javascript
var _curry3 = require('./internal/_curry3');

module.exports = _curry3(function doSomething() {
    return stuff;
});
```

---

The following fails testing:
```javascript
var curry = require('./curry');

module.exports = curry(function doSomething() {
    return stuff;
});
```
The test result is:
```
1) doSomething is curried:
     TypeError: object is not a function
      at ...
```

---

I would like to be able to do:
```javascript
var _curry = require('./internal/_curry');

module.exports = _curry(function doSomething() {
    return stuff;
});
```

**Comment by buzzdecafe** [comment]
> I'm modifying an API function to accept an unlimited number of arguments,  and am having a little trouble getting it to curry ...

Yeah, that won't work. You can only curry when the arity is known, either on the function `length` or supplied as a parameter to `curryN`

**Comment by CrossEye** [comment]
>> I'm modifying an API function to accept an unlimited number of arguments, and am having a little trouble getting it to curry ...

> Yeah, that won't work. You can only curry when the arity is known, either on the function `length` or supplied as a parameter to `curryN`

And the problem is not an implementation accident.  This is fundamental.  Curried functions, pretty well by definition, accept some arguments (just one in strict definitions, any number in a version like ours) and then check whether all the arguments to the original function have been supplied.  If so, it's called.  If not, it returns a new curried function that awaits the remaining ones.  But this all falls down if if can't tell if all the arguments have been supplied.  Hence we need to know up front how many arguments to expect.

**Comment by neftaly** [comment]
Thankyou for your thoughtful replies. Definitely a case of "the simple thing I missed"; I'll have to think about  how to implement it properly.

**Comment by neftaly** [comment]
I've gotten a fair bit further (though I still feel like a blind man doing a paint-by-number), and now have a working extension with appropriate unit tests, [R.mixinN](https://github.com/neftaly/ramda/commits/mixinN). I've implemented ```./mixinN.js``` as:
```javascript
module.exports = curryN(3, function mixinN() {
	return foldlIndexed(_extend, {}, arguments);
});
```
It works great, though I'm worried I might be abusing curryN. Instead, I'd like to use an internal currying function. I only have a vague idea of their internal logic, however, and can't seem to get my arguments correct. Any thoughts?

PS: The build system for Ramda is delightful - nice work, whoever set that up.

**Comment by davidchambers** [comment]
Perhaps it's too late for me to be reading code; I'm struggling to wrap my head around this. What's the significance of 3?

**Comment by buzzdecafe** [comment]
@davidchambers I agree, this still seems to be trying to curry a variadic function. 

@neftaly Is the intent to pass in an arity `n` and a list of objects `o_0 .. o_{n-1}`? But if the number of objects is `< n` return a function awaiting the remaining objects?

> PS: The build system for Ramda is excellent - nice work, whoever set that up.

thanks to @davidchambers for that. And even though i bitch about it all the time, I agree, it's quite nice, and *much* better than what was there. So, kudos, and thanks.

**Comment by neftaly** [comment]
It's basically a hack that calls a new curry each time you give it an object. It isn't good.

**Comment by CrossEye** [comment]
Am I missing something?  Is your end goal simply a multiple-arguments version of `mixin`?

That could be written as

    reduce(mixin, {})

if you want to pass a list of functions

or as

    unapply(reduce(mixin, {})

if you want these as arguments.

While I might have no problem with a dedicated function for this, I can't see what this has to do with the initial discussions about currying.

**Comment by CrossEye** [comment]
And as an extension of my previous answer, if you want to fix the `unapply`-ed version to a certain length, you could then wrap it in a `curryN` call.

**Comment by neftaly** [comment]
Thanks! I was intending to use `foldlindexed` to do the same from the other direction (haven't yet figured out how to access `reduce` in modules). So `mixin = mixinN(2)`. Was then trying to pass the arguments in with currying.

I wouldn't normally create an issue for this sort of thing, though I really wasn't sure where else to ask. Kept the discussion in here so I wouldn't be spamming basic questions as issues :)

**Comment by buzzdecafe** [comment]
interesting to note that this `reduce(mixin, {})` works! I expected it to work the first time, but then have the accumulator object in closure and keep mutating it. But the implementation of `mixin` saves the day here, and it consistently accumulates into a new, empty object. Unfortunately, you can't *rely* on this behavior, e.g.:

```javascript
function accX(acc, x) { 
    acc.x = acc.x || 0; 
    acc.x += x; 
    return acc;
}

f = reduce(accX, {});

f([1,2,3]); //=> {x: 6} 
f([4,5,6]); //=> {x: 21} oops
```

**Comment by CrossEye** [comment]
Yes, if `fn` mutates and returns the accumulator it receives, then `var f = reduce(fn, val)` really only makes sense in the for a primitive `val` (or I suppose a one-shot `f`.)  One more argument against mutation!

**Comment by buzzdecafe** [comment]
though it *does* make me wonder if we should `clone` the accumulator.

**Comment by neftaly** [comment]
I have a couple more questions :)

* What are your thoughts on a auto-curry function, that kept currying until the argument was `undefined`?

* With R.toPairs, is the order of keys and values guaranteed consistent?

* Is this worth considering?
```javascript
// To be wrapped in R.curry
R.mixinImmutable = function (object) {
	return R.compose(
		Object.freeze,
		R.mixin(object)
	);
};
```

With mixin, you can already do cool stuff like this:
```javascript
var applyDefaults = R.mixin({
	option1: true,
	option2: 5
});

var main = R.curry(function(options, data) {
	options = applyDefaults(options);

	return R.compose(
		doSomething(options)
	)(data);
});

main({option2: 10})(input)
```
But with mixinImmutable:
```javascript
var applyDefaults = R.mixinImmutable({
	option1: true,
	option2: 5
});

var main = R.curry(function(options, data) {
	options = applyDefaults(options);

	// Strawman to make this example simpler
	data = R.compose(
		doSomething(options)
	)(data);
	// Attempt to mutate `options`
	options.option1 = false; // Will fail silently (or loudly, if `"use strict"`)

	return R.compose(
		doSomething(options)
	)(data);
});
```

**Comment by neftaly** [comment]
I would also appreciate your thoughts on this. Really sorry if any of this stuff is already in there, by the way. I read through the manual, but it's hard to remember everything (and until Thursday the closest I'd ever gotten to functional programming was JS `map`/`forEach`).

The problem is that I want to return a R.compose function composition (in a tail call):

```javascript
var mixinImmutable_function = function (object) {
	return R.compose(
		Object.freeze,
		R.mixin(object)
	);
};

mixinImmutable_function(objectA)(objectB); //=> {objectA + objectB}
mixinImmutable_function(objectA, objectB); //=> function (objectB is discarded)
```

Now, you could just wrap it in R.curry:

```javascript
R.mixinImmutable = R.curry(function (object, data) {
    return mixinImmutable_function(object)(data);
});

R.mixinImmutable(objectA)(objectB); //=> {objectA + objectB}
R.mixinImmutable(objectA, objectB); //=> {objectA + objectB}
```

But that adds all the currying overhead. Instead, how about:
```javascript
// Not sure if "defer" is the right term
R.defer = function (func, value) {
    if (typeof value === "undefined") return func;
    return func(value);
}

R.mixinImmutable = function (object, data) {
    return R.defer(mixinImmutable_function(object), data);
};

R.mixinImmutable(objectA)(objectB); //=> {objectA + objectB}
R.mixinImmutable(objectA, objectB); //=> {objectA + objectB}
```

**Comment by CrossEye** [comment]
> What are your thoughts on a auto-curry function, that kept currying until an argument was `undefined`, at which point it executed the function?

I'd have to see some pretty good demonstrations of need.  There have been several discussions of variations of curry, some of them pretty interesting: 

  * https://github.com/ramda/ramda/issues/129#issuecomment-54679470
  * #143 
  * #732

The last one is very current.  But as currying is so central to Ramda, it's not something we change indiscriminately.  Not even something we add new versions of without strong rationale.  So go ahead, give us some strong reasons.  We'll listen.


> With R.toPairs, is the order of `[key, value]` guaranteed consistent? The doc is not explicit.

No, we should update the documentation to have the same caveat that's in `keys`.  `toPairs` is based on `keys` and inherits its issues.


> ... `mixinImmutable` ...

This doesn't strike me as a very common problem you're trying to solve.  I may be wrong, but I certainly have not needed this, and this is the first request we've seen.  My first inclination is to simply leave this in user-land.  There is one other issue.  So far we've been keeping compatible with ES3.  While that is becoming less relevant every month, it's nice that we've managed to do so.  But your solution involves `Object.freeze` which is not available until ES5.

**Comment by neftaly** [comment]
Understood. Can I please have your opinion on the deferred/delegated function exec post? It'd be mainly for exposing a function composition to the surface of some API/module, with optimized currying (i.e. no `R.curry` overhead).

Sidenote: As examples, I tried to look for where it would be useful in optimizing the Ramda core, but your implementation of `internal` (with the implied knowledge of how a function will be called) mitigates the need for it :+1:

**Comment by CrossEye** [comment]
I guess I don't understand exactly what you're trying to do with your optimized curry.

There is some overhead to `curry`, of course.  There are two extra function wrappers on a curried function, and the inner one involves two `if` statements, a concatenation, a comparison, several property look-ups, and another function call.  

But this is not huge, and currying is one of the central features of the library.  A manually curried function will of course perform better:

    var add = function add(a, b) {
        switch (arguments.length) {
            case 0: throw new TypeError("No arguments");
            case 1: return function(b) {return a + b;};
            default: return a + b;
        }
    };

    add(3, 5); //=> 8
    add(6)(36) //=> 42

But it is clearly not as clean as

    var add = curry(function add(a, b) {
        return a + b;
    });

All that said, I'm still not really clear what it is you're trying to do with `defer`.  Can you explain more fully?

**Comment by neftaly** [comment]
Sure! It's supposed to be a way to support both `(a, b)` and `(a)(b)` for functions that return a function. From an external POV, it looks identical to a curried function.

```javascript
var x = function (a, b) {
  return R.compose (
    stuff
  )(b);
}

x(a)(b); // doesn't work
x(a, b); // works
```
```javascript
var x = function (a) {
  return R.compose (
    stuff
  )//(b);
}

x(a)(b); // works
x(a, b); // doesn't work
```
---
```javascript
var _x = function (a, b) {
  return R.compose (
    stuff
  )(b);
};

var x = R.curry(_x);

x(a)(b); // works
x(a, b); // works
```

```javascript
var _x = function (a) {
  return R.compose (
    stuff
  )//(b);
}

var x = function (a, b) {
  return defer(_x(a), b);
}

x(a)(b); // works
x(a, b); // works
```

Does that help?

**Comment by CrossEye** [comment]
I guess my trouble is that I'm lost at the beginning.  I simply don't understand why you wouldn't write this equivalent:

    var mixinImmutable = curry(compose(Object.freeze, mixin));

But I'm still not sure I have your overall requirements right.  Are you looking for some sort of function-to-function transformation T such that for an arbitrary `f:: a -> (b -> c)` and any `a`, `b`, this is true:

    T(f)(a, b) == T(f)(a)(b) == f(a)(b)

?  Or am I still missing the point?

**Comment by neftaly** [comment]
It's an optimization. I actually spend my weekend being convinced that pursuing this sort of optimization is a bad thing :). I'm thinking that it'd also take some simplicity away from the API.
