### ISSUE TITLE
Variation on R.replace

### ISSUE THREAD

**Issue by wavded** [ramda/ramda#731]
I am new to Ramda and what I'd like is a function R.replace with this signature:

```js
R.replace(match, input, replacement)
```

Basically I want the replacement string to be last so it can be curried in later.  Seems like `flip` only does the first two arguments.  Is there something in Ramda itself that will allow me to transform it like this?  Is this a common enough use case for a new function?

Thanks much!

**Comment by wavded** [comment]
Look like this did the job, would anyone do it differently?

```js
R.replaceOf = R.curry(function (input, match, replacement) {
  return R.replace(match, replacement, input)
})
```

I like it because I can do transforms on the replacement value as well:

```js
var getInputType = R.compose(R.replaceOf('a sample input', /sample/), R.toLowerCase)
getInputType('SWEET') // => 'a sweet input'
```

**Comment by buzzdecafe** [comment]
first, welcome!

fwiw you could do something like this, e.g.:

```javascript
function placeRe(rx) { 
    return flip(replace(rx)); 
}
```

**Comment by wavded** [comment]
thx @buzzdecafe :)

Gotcha, that works too... what would you suggest if I wanted `placeRe` to also take the `input` string?  Just apply the next arg?

```js
function placeRe(rx, input) { 
    return flip(replace(rx))(input); 
}
```

Although it doesn't feel that composable at that point unless I wrap it in `R.curry`, but that feels like a lot of function calls.

**Comment by buzzdecafe** [comment]
yes, that's why i said "something like this" ;-)

considering the existing impl just calls native string replace, you could simply:

    var placeRe = curry(function(input, match, replacement) {
        return input.replace(match, replacement);
    });

**Comment by wavded** [comment]
got it, thx.  I'll close this for now.  If there is an interested in a formal `R.replaceOf` like call where replacements are curried in last, I'd be open to giving a swing at a PR.
