### ISSUE TITLE
R.some is not defined, though it's mentioned in the docs

### ISSUE THREAD

**Issue by geekflyer** [ramda/ramda#738]
In the docs there's R.some http://ramdajs.com/docs/R.html#some.

However it's not included in the dist or the sources. Perhaps it has been removed some time ago?

Which function should I use instead?

Best Regards Christian

**Comment by geekflyer** [comment]
Ah, ok, looking at the recent pull request I could see it's been renamed to `R.any` . The docs should be updated accordingly :-)

**Comment by CrossEye** [comment]
The docs are tracking the most recently published version on NPM, version 0.8.0.

We're about to release 0.9.0, and this should be rectified.  Sometime soon after, I'm hoping to start keeping separate doc versions for each release and one for HEAD.  But there suddenly seems to be a lot on our plates!

**Comment by despairblue** [comment]
So Ramda does not use semver or am I misunderstanding something here?

**Comment by davidchambers** [comment]
We haven't yet published 1.0.0, so all bets are off. When adding Ramda as a dependency I suggest something like `"ramda": "0.8.x"`.

**Comment by geekflyer** [comment]
Maybe you could add 0.9.0-pre as version to the package.json in this repo. That would clarify things a bit.

**Comment by despairblue** [comment]
Actually just read semver.org and that's normal, defined behavior. I didn't know that, my bad ^^

**Comment by anton-rudeshko** [comment]
Could you please link PR in which `some` got renamed to `any`? I missed why it was changed.

**Comment by CrossEye** [comment]
@anton-rudeshko: #634.

@davidchambers has been a fierce advocate for API consistency and a string critic of aliases.

**Comment by anton-rudeshko** [comment]
That's really weird o_O

Earlier I asked about introducing aliases and you convinced me that aliases is bad. I was sure that you want to be consistent with native [`Array` methods](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array#Iteration_methods), but with #634 this consistency is broken in every way. And you've also changed public API. 

It's not too late to rethink this change =)

**Comment by buzzdecafe** [comment]
surely you don't expect us to be *consistently* consistent, do you?

**Comment by anton-rudeshko** [comment]
@buzzdecafe, sorry, too much for my poor english to understand your question =)

**Comment by buzzdecafe** [comment]
@anton-rudeshko np, i was more or less agreeing with you--we have been swerving around a bit.

**Comment by CrossEye** [comment]
We're not trying to match native APIs in particular, neither with naming nor with API design.

Nor are we trying to duplicate the names used in any specific other functional language or any other JS library, although we do try to pick from among the familiar ones as much as possible..

What we absolutely do try to accomplish is to keep an internal consistency.  And this is where @davidchambers' sharp eye has been invaluable.  He's directed the cleaning up of all sorts of consistencies that I don't think either @buzzdecafe or I even noticed.

For example, we had two awkwardly named functions,

    R.anyPredicates :: [Predicate] -> Predicate
    R.allPredicates :: [Predicate] -> Predicate

where

    Predicate :: ..* -> Boolean

`anyPredicates` returned a function that would return true if and only if any one of its input functions returned true for the given parameters.  `allPredicates` returned true if all of them did.

The trouble was that these names weren't very clear.  At some point, we renamed them to the much clearer `anyPass` and `allPass`.

In #634, we removed an inconsistency we had between the naming of these functions and the naming of `some` and `every`, by making the latter `any` and `all`.  This leads to a nice internal consistency which we value more than we do matching any particular external API.

**Comment by anton-rudeshko** [comment]
First part of your comment reminds me about [xkcd 927](http://xkcd.com/927/) =):
![](http://imgs.xkcd.com/comics/standards.png)

Everything else is now clear for me, thanks for explanation.

**Comment by davidchambers** [comment]
Put another way, had we stuck with `some` and `every` we would have renamed the other functions to `somePass` and `everyPasses`, but these don't sound good.

**Comment by anton-rudeshko** [comment]
Absolutely true.

**Comment by unitario** [comment]
I don't have a bone to pick in this (completely outdated) fight. I love Ramda regardless, but I found this issue while googling for "the equivalent to 'some' in Ramda". Apparently its _any_ ...
