### ISSUE TITLE
mixin function curring

### ISSUE THREAD

**Issue by honzabrecka** [ramda/ramda#743]
Hi,

I'd like to use `mixin` function in a `pipe`, but it's not possible. I would expect that it behaves the same way as `divide` function does. Does it have any reason why is used `curry` instead of `op`? I think that `curry` should be used only for commutative functions.

I know that I can use converge, but it's not ideal from my point of view.

**Comment by davidchambers** [comment]
Great idea! `R.mixin({x: 0, y: 0})` handles the common case for me—specifying default values in a pipeline—but cannot easily be used in a pipeline to override values. `R.mixin(R.__, {x: 7, y: 2})` would be useful.

+1

**Comment by CrossEye** [comment]
:herb:  PR, @honzabrecka?

**Comment by CrossEye** [comment]
@buzzdecafe pointed out to me that you could also simply do `R.flip(R.mixin)` if necessary.

**Comment by davidchambers** [comment]
Doesn't that same argument apply to the functions to which we *do* give the `op` treatment?

Perhaps you're proposing `R.flip(R.mixin)` as a stopgap measure, rather than a reason not to make the proposed change.

**Comment by honzabrecka** [comment]
Great, I'll prepare PR tomorrow.

**Comment by CrossEye** [comment]
@davidchambers Yes, that was simply a way that the current code could still be used relatively easily for Honza's case.  Our brief IM conversation:

> **Mike**: can't you just `flip(mixin)`?
> **Scott**: you could. But any objection to op? You can also flip divide or subtract, but that's not always so useful
> **Mike**: no, no objection

**Comment by davidchambers** [comment]
Cool. Thank you for clarifying your position, @CrossEye. :)
