### ISSUE TITLE
move cname pointer to ramda/ramda

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#754]
see ramda.github.io

**Comment by CrossEye** [comment]
I believe this is now just a matter of removing the cname file from one repo and adding it to another.   I'll double-check when I'm on my computer, but I'm fairly certain that the registrar just points to github.com.

**Comment by buzzdecafe** [comment]
yep, it works.

**Comment by CrossEye** [comment]
:fireworks: 

And a big shout-out to @saikobee for the wonderful update to the docs!

**Comment by davidchambers** [comment]
Absolutely! This is a big improvement.

**Comment by saikobee** [comment]
:fireworks:

**Comment by fyyyyy** [comment]
very nice :+1:
