### ISSUE TITLE
New Website has no link to github

### ISSUE THREAD

**Issue by geekflyer** [ramda/ramda#757]
Hey, just noticed the new ramda site is up and looks nice.
However there's one annoything thing - there's nowhere a link to the github repo (or maybe I just couldn't find it?) Could you please add one, somewhere prominently at the top or so ?

Best Regards Christian

**Comment by CrossEye** [comment]
Good catch!

There are a number of little changes that need to be made to the docs now that the big changes are in.  We'll make sure that is included.

**Comment by buzzdecafe** [comment]
thanks for the heads up, this is covered by #764, will update once 0.9.1 is published
