### ISSUE TITLE
Logical operations should take more than just two arguments

### ISSUE THREAD

**Issue by honzabrecka** [ramda/ramda#770]
Hi,

I think that logical operations (`and` and `or`) should be able to take any count of predicates, not just two:

```
var isTransforming = R.or(isTranslating, isRotating, isScaling);
```

What do you think?

**Comment by buzzdecafe** [comment]
if you have a list of conditions to evaluate, why not just fold the binary functions over the list?

**Comment by CrossEye** [comment]
And if that becomes popular enough, we might consider adding list versions into the library, but we'd probably never include the variadic ones, which are not amenable to currying.  I could see something like this:

    var and2 = R.fold(R.and, R.T); // don't have a good name for `and2`
    var test = and2([odd, prime, above10, below100]); 
    test(6); //=> false (not odd)
    test(101); //=> false (not below 100)
    test(9); //=> false (not prime)
    test(17); //=> true

    // similarly
    var or2 = R.fold(R.or, R.F); // ...

**Comment by honzabrecka** [comment]
I've just found `allPass` and `anyPass` functions that do what you mentioned guys. :)

**Comment by CrossEye** [comment]
D'oh!!!  Or that.
