### ISSUE TITLE
`assoc` should work on lists as well as plain objects

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#773]
Right now:

    var arr = ['a', 'b', 'c', 'd', 'e'];
    R.assoc('2', 'xyz', arr);
    //=>{0: "a", 1: "b", 2: "xyz", 3: "d", 4: "e"}
 
To my mind, this should really return

    //=> ['a', 'b', 'xyz', 'd', 'e']

I'm not sure how straightforward that might be, as the current implementation is concerned with flattening the (enumerable part of the) prototype chain into the newly created object.  But that change looks to me to be the correct API.

**Comment by davidchambers** [comment]
Isn't this what [`R.insert`][1] does?


[1]: http://ramdajs.com/docs/#insert

**Comment by CrossEye** [comment]
Not quite.

    R.insert(2, 'xyz', x); //=> ['a', 'b', 'xyz', 'c', 'd', 'e']

I'm suggesting

    R.assoc(2, 'xyz', x); //=> ['a', 'b', 'xyz', 'd', 'e']

Which is similar to 

    var x = {a: 1, b: 2, c: 3, d: 4, c: 5}
    R.assoc('c', 42, x); //=> {a: 1, b: 2, c: 42, d: 4, c: 5}

**Comment by CrossEye** [comment]
I guess what I'm suggesting for the array case is the equivalent of 

    R.assoc(idx, val, arr) => clone(arr).splice(idx, 1, val);

**Comment by davidchambers** [comment]
Ah, yes. Seems reasonable to me. :)

**Comment by davidchambers** [comment]
Would `R.assoc(99, 'xyz', ['a', 'b', 'c', 'd', 'e'])` produce a sparse array?

How would `R.assoc(-1, 'xyz', ['a', 'b', 'c', 'd', 'e'])` evaluate?

How about `R.assoc('foo', 'xyz', ['a', 'b', 'c', 'd', 'e'])`?

**Comment by buzzdecafe** [comment]
so the signature of `assoc` is contingent upon its arguments? seems bad to me

**Comment by CrossEye** [comment]
All good questions @davidchambers.

I'm mostly concerned about the sparse array issue.  The negative index I would expect should be handled like we handle negative array indices elsewhere, as counters from the end.  And adding an arbitrary property to an Array instance is already quite possible:

    var x = [1, 2, 3];
    x.foo = 'bar';

But I really don't like having Ramda create sparse arrays, as we don't have good ways to handle them once created.  Still I feel that's likely a place for _caveat emptor_.

**Comment by buzzdecafe** [comment]
@CrossEye Is the type `k -> v -> {}` or is it `n -> v -> []`? It should not be both. Or why not combine `map/mapObj` etc.

:-1:

**Comment by CrossEye** [comment]
@buzzdecafe 

> so the signature of `assoc` is contingent upon its arguments? seems bad to me

That's practically the definition of dynamic dispatch!  :smiling_imp: 

We do something similar for `clone`.  It's signature is the anemic `{*} -> {*}`.  `assoc` could just as easily be named `cloneAndTweak`, so I don't think it's unreasonable that it has a signature of `k -> v -> {} | k -> v -> []`.  I'm certainly not set on this.  But this is a case of what is to me identical ideas that could easily be done with identical code.  And I feel that the current implementation is actually somewhat broken because it doesn't do so.  If we don't do this, then I think we might want to find some name that works now for lists that we could append `Obj` to for the current behavior.

**Comment by buzzdecafe** [comment]
no, they're different, as @davidchambers has pointed out. An array is ordered, while an object is just a set of `k,v` pairs. IMO `R.assoc(99, 'xyz', ['a', 'b', 'c', 'd', 'e'])` should be an `RangeError`. That goes for any value `n > list.length`

**Comment by CrossEye** [comment]
That's an interesting philosophical point.  `assoc` doesn't care if the value is already assigned when it sets it.  So there is a reasonable argument to be made that one should be able to set any value at all, and that `RangeError`s would be silly.  But Clojure, from whom we stole the name, [agrees with you][cd] on this point: 

> assoc[iate]. When applied to a map, returns a new map of the
>   same (hashed/sorted) type, that contains the mapping of key(s) to
>   val(s). When applied to a vector, returns a new vector that
>   contains val at index. Note - index must be <= (count vector).

On the other hand, they also agree with the broader point of retaining the type of the object.

Even if we decide we want to do this, we have a fundamental problem in that our current API includes the entire prototype chain, so a simple `clone` and change won't do.  So I don't actually have an implementation in mind.  I just wanted to throw the idea out there.  I wasn't actually expecting any pushback, so I want a little time to reflect, too.

  [cd]: https://clojuredocs.org/clojure.core/assoc

**Comment by megawac** [comment]
On mobile but is there no r.splice?

**Comment by buzzdecafe** [comment]
> is there no r.splice?

no, that might be simplest, to implement a non-mutating `splice` for lists

**Comment by CrossEye** [comment]
Several of the functions in place are there to take the place of `splice` which had so many optional parameters, I couldn't make it work.  See #78.

**Comment by buzzdecafe** [comment]
how about: `splice :: start -> deleteCount -> [replacements] -> list`? 

essentially replacing all of the optional `itemN` args with one list of arbitrary length

**Comment by CrossEye** [comment]
Part of the problem is the nastiness of `Array.prototype.splice`, not just the parameters, I guess, but the whole mutate-one-thing-and-return-another paradigm.  Obviously we couldn't do that.  And sure, your signature would be a reasonable Ramda-ized version of splice.  But unlike most of the functions that parallel native functionality, this would be quite far from the original.  And looking at the [MDN Examples][mdn] simply made me cringe.  I couldn't do it.

But if you want to do it, I have no actual objections.  I simply don't want to get my own hands dirty.


  [mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#Example:_Using_splice

**Comment by honzabrecka** [comment]
And `assocPath` should work on lists too: :fire:

```
assocPath('a.b.1.c', 8, {a: {b: [{c: 1}, {c: 2}]}});
// {a: {b: [{c: 5}, {c: 8}]}}
```

**Comment by buzzdecafe** [comment]
and `assocPath` should take an array instead of a string ... whatever happened to that issue?

**Comment by CrossEye** [comment]
Yes, @honzabrecka, if we do `assoc`, we should clearly also do `assocPath`.

@buzzdecafe Although you and I have discussed that in person, I don't think we've actually raised an issue for these ones unless @tolmasky was folding it into #637 (which seems to be stalled. )

**Comment by scott-christopher** [comment]
I've opened a PR (#973), that proposes introducing `adjust` and `update` functions for modifying the value of a list at a given index.

**Comment by scott-christopher** [comment]
With the inclusion of `adjust` and `update`, should this issue be closed now?

**Comment by davidchambers** [comment]
Yes, I think so.

**Comment by epeli** [comment]
How about the use case @buzzdecafe mentioned? When using `assocPath` to update an object inside  an array like in the example I wouldn't expect the array to be transformed to object.

**Comment by CrossEye** [comment]
Sorry, I was out on vacation when this question came in.  Still playing a little catch-up, even two weeks after my return.

I agree that this is weird and we might want to fix it.  But I think we're all more interested in seeing where the `lens` path takes us.

```js
R.set(R.compose(R.lensProp('a'), R.lensIndex(0), R.lensProp('b')), 2, {a: [{b: 1}]}); 
//=> {a: [{b: 2}]}
```

I think it might be really useful to add some sugar for this:

```js
R.set(R.lensPath(['a', 0, 'b']), 2, {a: [{b: 1}]}); 
//=> {a: [{b: 2}]}
```

... which would mostly remove the need for `assocPath`.  But no one has done anything about that yet.

**Comment by paldepind** [comment]
> I think it might be really useful to add some sugar for this:
```R.set(R.lensPath(['a', 0, 'b']), 2, {a: [{b: 1}]}); 
//=> {a: [{b: 2}]}```
... which would mostly remove the need for assocPath. But no one has done anything about that yet.

I agree that a convenience function would be nice. But that proposal would require magic to determine if each element in the list should be passed to `R.lensProp` or `R.lensIndex`. I'm not sure if that's a deal breaker but it is a bit against the Ramda philosophy so do this form of type checking to adjust behavior.

**Comment by epeli** [comment]
I thinks fixing this issue would also fix https://github.com/ramda/ramda/issues/1332


> I agree that a convenience function would be nice. But that proposal would require magic to determine if each element in the list should be passed to R.lensProp or R.lensIndex. I'm not sure if that's a deal breaker but it is a bit against the Ramda philosophy so do this form of type checking to adjust behavior.

Could `lensPath` be made to check for the existing types in the collection instead of checking the params?

**Comment by paldepind** [comment]
> Could lensPath be made to check for the existing types in the collection instead of checking the params?

How so? When the lens is created the collection is not available.

**Comment by epeli** [comment]
> How so?

I don't know. That's why I'm asking :)

Maybe with a smarter lens which checks the collection when it is being used?

**Comment by CrossEye** [comment]
> I agree that a convenience function would be nice. But that proposal would require magic to determine if each element in the list should be passed to `R.lensProp` or `R.lensIndex`. 

I was thinking that it didn't really have to be magic.  Since the only values allowed for indices are Numbers (specifically integers, but I have no problem having non-integers simply not returning values) and Numbers shouldn't be allowed for property names -- we can ignore coercion for sugar like this -- it could just take `[Sting | Number]` which would `compose` a `[lensProp(String) | lensIndex(Number)]`. (Please forgive the informal notation.)

**Comment by paldepind** [comment]
@CrossEye I know. That is excactly what I call magic. I can name many cases in Ramda in which similar  type checking whould be rejected.

Also not allowing numbers as property names is slightly too naive IMO.

**Comment by CrossEye** [comment]
@paldepind:

I'm far from certain about this, but it doesn't strike me as problematic.  It's not something I'm intent on having; it just seems like it would be nice to have.  

I would still allow numeric strings as property names, but if actual numbers were passed to the function, they would be assumed to be indices.

And yes it feels odd.  Perhaps that feeling is enough to worry us and keep us from doing it.  Or perhaps it's ok for something that's just sugar.  I'm not at all certain.

**Comment by bolasblack** [comment]
Hi @scott-christopher @davidchambers @CrossEye, I found the behaviour of `update` not as same as `assocPath`:

```js
R.assocPath([1], 'a', []) // => [ <1 empty item>, 'a' ]
R.update(1, 'a', []) // => []
```

And for cognitive and semantic considerations, I really hope `assoc` can behave like `assocPath`(This difference has led to some bugs in my team's work, and it really made people confused.):

```js
// expect
R.assoc(1, 'a', []) // => [ <1 empty item>, 'a' ]

// current
R.assoc(1, 'a', []) // => { '1': 'a' }
```

**Comment by CrossEye** [comment]
I agree that `assoc` and `assocath` should be compatible.

I'm less concerned about this specific case, as Ramda's philosophy is that all bets are off when you try to work with sparse arrays.

Our usual technique of resolving this sort of incompatibility is to implement the single-argument version in terms of the array one.  But that may not be so simple here since `assocPath` itself is written in terms of `assoc`.   It shouldn't be that difficult, though.  But this should probably not be tied to this old issue.  Could you raise a new issue with this?  If you're interested, I'd love to see a pull request.

**Comment by bolasblack** [comment]
Hi @CrossEye, I created the PR https://github.com/ramda/ramda/pull/2787
