### ISSUE TITLE
Is there a way to group an array into arrays of (maximum) given size?

### ISSUE THREAD

**Issue by mfirry** [ramda/ramda#774]
I need something like:
`([a], n) -> [array1, array2]` (or an equivalent curried form) where `array1` and `array2` have maximum `length` of `n`?

**Comment by davidchambers** [comment]
Do you want to transform something like `['a', 'b', 'c', 'd', 'e', 'f', 'g']` into `[['a', 'b', 'c'], ['d', 'e', 'f'], ['g']]`?

**Comment by mfirry** [comment]
Yeah, with n = 3, that'd be it.

**Comment by CrossEye** [comment]
There's nothing built in.  This is probably a job for recursion:

    var groupsOf = R.curry(function group(n, list) {
        return R.isEmpty(list) ? [] : R.prepend(R.take(n, list), group(n, R.drop(n, list)));
    });

I would almost certainly choose to put the `n` first, but obviously you could choose to organize it as you see fit.

**Comment by mfirry** [comment]
I'll try it out. Thanks! And yes, silly me, n first makes perfect sense. 
It'd be in fact some sort of groupOfN kind of thing.
Thanks!

**Comment by buzzdecafe** [comment]
you can also do it as a fold if you are worried about recursion stack:

```javascript
var subdivide = R.curry(function subdivide(n, ls) {
    function f(acc, elem, idx) {
        if (idx % n === 0) {
            return R.append([elem], acc);
        } else {
            var lastArr = R.last(acc);
            return R.append(R.append(elem, lastArr), R.init(acc));
        }
    }
    return R.foldlIndexed(f, [], ls);
});
```

but @CrossEye 's solution is a lot nicer

**Comment by CrossEye** [comment]
Well, I did mine recursively because I couldn't think of a clean way to do it without recursion, so bravo!

**Comment by tolmasky** [comment]
If there was an indexed version of groupBy, then you could just do:

groupByIndexed(array, R.unapply(R.pipe(R.prop(1), R.flip(R.divide)(3), parseInt)))

(that would give you { 0: ['a', 'b', 'c'], 1: ['d', 'e', 'f'], 2:[7] } , as opposed to [['a','b','c'], ['d'... )

**Comment by mfirry** [comment]
I might be completely off but what I need seems what Clojure calls [partition-all](https://clojuredocs.org/clojure.core/partition-all)

**Comment by stoeffel** [comment]
@mfirry Did just implement a [partition-all](https://github.com/stoeffel/partition-all) module out of fun.

**Comment by mfirry** [comment]
@stoeffel awesome! fun is fun :)

**Comment by davidchambers** [comment]
If anyone is interested in submitting a pull request to add this function please do so. :)

**Comment by megawac** [comment]
The method name should probably be `chunk` if implemented following lodash and other languages

**Comment by CrossEye** [comment]
If someone wants to make a PR for this, I don't really object to its inclusion, but I think we could bikeshed names then.  `partition-all` is used in [Closure][cl], `splitEvery` in [Haskell][ha], `grouped` in [Scala][sc], `chunk` is used in [lodash][ld] but I don't find it in other major JS libraries.  (`chunk` is also used in  [PHP][ph], but that's hardly a recommendation.)


  [cl]: http://clojuredocs.org/clojure.core/partition-all
  [ha]: https://hackage.haskell.org/package/split-0.1.1/docs/Data-List-Split.html#v:splitEvery
  [ld]: https://lodash.com/docs#chunk 
  [ph]: http://php.net/manual/en/function.array-chunk.php
  [sc]: http://www.scala-lang.org/api/current/index.html#scala.collection.Iterator$GroupedIterator

**Comment by buzzdecafe** [comment]
`subdivide`!

**Comment by megawac** [comment]
Ruby also uses chunk, can't think of any others off hand :)

**Comment by gtrak** [comment]
+1, was reaching for partition and decided to change the shape of my data instead :-(

**Comment by AdamMcCormick** [comment]
For anyone else who ends up here and is disappointed. This did get added at some point as [R.splitEvery](http://ramdajs.com/docs/#splitEvery)

**Comment by andrewb76** [comment]
R.splitEvery(3, [1, 2, 3, 4, 5, 6, 7]); //=> [[1, 2, 3], [4, 5, 6], [7]]

**Comment by woss** [comment]
If you need to split an array in the exact numbers of dimensions you can use something like this 

```ts
const R = require('ramda')
const arr = [1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15] // ts type number[] 
const numOfSubArrays = 2
const chunk = arr.length / numOfSubArrays

let myArray = [[],[]] // ts type [number[], number[]] 


myArray = R.splitEvery(chunk, arr);
// [[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]
```


https://runkit.com/woss/ramda-split-array-to-defined-subarray
