### ISSUE TITLE
Add a "merge all" function

### ISSUE THREAD

**Issue by benperez** [ramda/ramda#777]
I commonly find myself wishing that there was a function which acted like `R.mixin` but with an entire list of objects. Here's the type signature, implementation.
```javascript
// R.blend :: [{}] -> {}
R.blend = R.foldl(R.mixin, {});
```
Often I am constructing objects for things like database queries from a list of smaller objects.
```javascript
var shouldUpdateFoo = true;
var shouldUpdateBar = false;
var shouldUpdateBaz = true;
var updates = R.blend([
  shouldUpdateFoo ? {foo: 1} : {},
  shouldUpdateBar ? {bar: 2} : {},
  shouldUpdateBaz ? {baz: 3} : {},
]);
// {foo: 1, baz: 3}
```
For me, `R.blend` would conceptually be a cousin of `R.sum`, `R.product`, and `R.flatten`. These functions reduce monoids under the following operators
`R.sum` —> addition with identity element 0
`R.product` —> multiplication with identity element 1
`R.flatten`  —> does more than just this but can be thought of as concatenation with identity element []
`R.blend` —> `R.mixin` with identity element `{}`

**Comment by davidchambers** [comment]
I would use such a function quite often. I'm not sure about the name, though. :P

**Comment by benperez** [comment]
I like the name because it fits well with `R.mixin`, which already sounds like a baking instruction. You can either `R.mixin` one ingredient at a time, or you can throw them all in together and hit `R.blend`.

**Comment by davidchambers** [comment]
That's it, I'm sold!

**Comment by CrossEye** [comment]
:+1:

**Comment by buzzdecafe** [comment]
now we'll have to add functions for grate, liquefy, puree, and makeJulienneFries
