### ISSUE TITLE
memoize broken for no args

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#791]
Moving from 0.8.0 to 0.9.1, my memoized functions broke (not sure if new expected behavior, not specified in release notes I think):

expensiveThingThatGetsCreatedOnce = R.memoize(function()
{
  //expensive initialization process;
  return it;
});

expensiveThingThatGetsCreatedOnce() // undefined

**Comment by davidchambers** [comment]
79ebb4f7b8e92893ecefb5d7e29feff8d2f079e6 changed the handling of functions with length 0. The change was partially reverted in #613. I opened a pull request earlier today to revert the remainder.
