### ISSUE TITLE
"AKA" in documentation

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#792]
Having read this: https://github.com/ramda/ramda/commit/b7867021a423b0eed0de26add56fe49da3836086

I thought it might be a good idea to add an AKA section, or perhaps a "You may know it as", section to the docs under functions that have multiple names they've been popularized as. I'm totally onboard with having just one name for everything, and also choosing the name thats best for this library vs what it might be called in another library, but it can be quite frustrating when the function you know isn't available under the name you know it as (just the other day I was trying to think "what's the other word for every?"). At least for me, one of the more difficult parts of switching over to this style of programming was the nomenclature (it feels like a lot of times what you want is already implemented, if you just knew what it was called...). If the docs for example had foldl under "reduce", then a quick search would bring it up, you see what its called here, and then use that.

**Comment by CrossEye** [comment]
A very good idea.

Adding and formatting a JSDoc tag should be easy.  The trick will be to make it easily searchable in the documentation.

**Comment by buzzdecafe** [comment]
see #1038, closing as duplicate
