### ISSUE TITLE
Link to `Why Curry Helps` is broken.

### ISSUE THREAD

**Issue by cust0dian** [ramda/ramda#793]
Currently, [Hugh Jackson's website is down](https://github.com/hughfdjackson/hughfdjackson.github.com/issues/2), which means that [**Why Curry Helps**](http://hughfdjackson.com/javascript/why-curry-helps/) article, that is linked on the Home page, is inaccessible.

I'm not sure what's better be done in this situation: would you rather wait till the website is up, replace it with [Internet Archive's mirror](https://web.archive.org/web/20140714014530/http://hughfdjackson.com/javascript/why-curry-helps/) or something else?

In any case, I'll gladly submit a PR if needed.

**Comment by CrossEye** [comment]
@cust0dian: Sorry, this got lost in a flurry of activity.  I think a link to the mirror would be great if you would be willing to do a PR.
