### ISSUE TITLE
Continious release

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#800]
Ramda is a really active library when it comes to contributions and that's just great. However, I don't see that reflected in releases. IMHO, they could come more often. I think it would be great if the library could be released on a regular basis, say every Friday or something like that. The release would just contain whatever had been merged during the week. No need to say "We must get feature X into release Y". 

For this to work I suspect all of this needs to be true (some things I suspect/know are already working) 
 * Release should be a one-command process which would:
    * Run all the tests
    * Deploy to npm and other package managers of choice 
    * Create a tag in git
    * Generate change log
    * Publish the site with updated documentation

There might be a change in work flow regarding breaking changes. If a breaking change is merged that requires a major version bump (or minor in pre 1.0.0 land). And perhaps we want to bundle several breaking changes together in one release to not let the version numbers run amok. This could be addressed by simply not merging breaking changes until it is decided that they should be released. I.e. a breaking change may get a :cow2: stamp and be considered done, but we hold of the merge for a while. That solution might cause a problem for those of you running on the "latest" version. But I assume that solutions can be found for this.

Anyway. Hoping for a nice discussion here.

**Comment by buzzdecafe** [comment]
every friday might be a bit much, but i'd be ok with every other week.

**Comment by CrossEye** [comment]
:+1: for every two weeks.  My only concern is that it's not always as busy as it seems to be now, and pushing just to push is a little crazy, but if we can at least build the routine of pushing every other week if there are any significant changes.

Sorry, I'm being slow here.  Been sick and distracted by conversations over on FantasyLand.  Too much happening.  

I think most of this would be easy to do, except possibly the automated change log.  I know that people have built change-log generators from Git commits, but I prefer the curated approach @davidchambers has been demonstrating.

**Comment by davidchambers** [comment]
Recently we've been publishing a new minor version every six weeks or so. This feels about right to me. I don't think we need a formal release schedule.

**Comment by TheLudd** [comment]
To me, six weeks is way to long, especially in this phase. What is the good argument for letting time pass so long between releases? (assuming that all that was needed for a release was the execution of one command)

**Comment by CrossEye** [comment]
I agree with @davidchambers that we don't have to commit to a formal release schedule.  But I do think we could be better about putting out more of what would (after 1.0) be termed patch-level releases, but here could be used like point releases.  When we have a few new features or a few fixes, even if they're only documentation fixes, we could move from, e.g.,  0.10.3 to 0.10.4 easily enough.

**Comment by TheLudd** [comment]
And by no means do I mean that ramda should say "we officially release every Friday". I consider it more an ambition. So much is being done now, which again is awesome, that it sometimes feels that the releases are forgotten. I don't know if you have discussions on when to release. 

npm has releases more than once every week (I think). Angular also had weekly releases for a while at least. 

I really see no argument against this as long as there is the time and knowledge on how to perform the change.

**Comment by davidchambers** [comment]
One option is to create a `release` branch which could accept bug fixes and documentation tweaks between minor releases.

State upon the release of v0.10.0:

    release ---> o <--- master
    v0.10.0      |
                 |
                 |
                 o

Some commits are made to `master`, for inclusion in v0.11.0:

                     o <--- master
                     |
                     |
                     |
                     o
                    /
                   /
                  /
    release ---> o
    v0.10.0      |
                 |
                 |
                 o

Someone fixes a bug and opens a pull request against `release` (probably after first opening a pull request against `master` and having one of us politely close it). After merging the pull request (omitting the merge commit for simplicity) we'd have:

                     o <--- master
                     |
                     |
                     |
    release ---> o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

We'd then publish v0.10.1:

    release ---> o   o <--- master
    v0.10.1      |   |
                 |   |
                 |   |
                 o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

We'd then merge `release` into `master`:

                     o <--- master
                    /|
                   / |
                  /  |
    release ---> o   o
    v0.10.1      |   |
                 |   |
                 |   |
                 o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

Some more commits are made to `master`:

                     o <--- master
                     |
                     |
                     |
                     o
                     |
                     |
                     |
                     o
                    /|
                   / |
                  /  |
    release ---> o   o
    v0.10.1      |   |
                 |   |
                 |   |
                 o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

We decide to release v0.11.0:

    release ---> o
    v0.11.0      |
                 |
                 |
                 o <--- master
                 |
                 |
                 |
                 o
                 |
                 |
                 |
                 o
                 |\
                 | \
                 |  \
    v0.10.1 ---> o   o
                 |   |
                 |   |
                 |   |
                 o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

As with every release, the last step is to update `master`:

    release ---> o <--- master
    v0.11.0      |
                 |
                 |
                 o
                 |
                 |
                 |
                 o
                 |
                 |
                 |
                 o
                 |\
                 | \
                 |  \
    v0.10.1 ---> o   o
                 |   |
                 |   |
                 |   |
                 o   o
                 |  /
                 | /
                 |/
    v0.10.0 ---> o
                 |
                 |
                 |
                 o

This would provide some benefits, but it's also a significantly more complex model than the one we currently use. Even with our current approach we sometimes have some trouble with Git.

**Comment by CrossEye** [comment]
Given how bad my git-fu is, that scares me.  But it might be better to learn it than to keep with the current practice.  I think, @davidchambers, that you're the only one of the primary committers really comfortable with git.  Both @buzzdecafe and I are improving, but we're not there yet.

But I do think we should be able to cut releases from one or two recent small changes and not have to make sure all our ducks are in a row for the big things.  That might be the best way to do it.

**Comment by davidchambers** [comment]
@TheLudd suggested another approach which would not require changes to our Git workflow:

> This could be addressed by simply not merging breaking changes until it is decided that they should be released. I.e. a breaking change may get a :cow2: stamp and be considered done, but we hold of the merge for a while.

**Comment by CrossEye** [comment]
I suppose we could simply create a tag for that situation, close it the PR, but make sure all PRs with that tag are reviewed before release.  That might be easier.  Perhaps something like `WILLFIX` or `WILLMERGE`.

**Comment by TheLudd** [comment]
Some libs tag their issues in github with the numbers of the versions they should be released in.

**Comment by davidchambers** [comment]
Having given the matter more thought, I've convinced myself that the :cow2: approach is not currently viable. It's relatively common for a pull request to change the internal dependency graph in some way, resulting in reordering of function definitions in __ramda.js__. If such a pull request were to sit idle for several weeks it may then require manual merging. This is not a problem if the pull request in question was opened by a core committer since we all follow the project closely and would rebase the changes in a timely manner.

On the other hand a first-time or occasional contributor may open a pull request and respond promptly to feedback for the next hour or two, or even the next day or two, but is less likely to respond promptly to a request to resolve merge conflicts weeks later. A core committer could pull the branch, resolve merge conflicts, push directly to master, and close the pull request with a link to the commit, but this is more involved than our current GitHub-centric approach.

**Comment by CrossEye** [comment]
I've fallen down on a job I really meant to do, but once I do it, that should alleviate this concern, @davidchambers.

I really want to stop committing `ramda.js` manually, and let Travis generate it for us on successful builds.  I know this is possible, and I had once done some of the research, but I never followed through.  I think this would be cleaner, and it would allow us to have the file hosted but stop the silly traffic in derived artifacts.

**Comment by davidchambers** [comment]
Why update __ramda.js__ at all? Couldn't we update it at release time as is the case with __ramda.min.js__?

**Comment by CrossEye** [comment]
I think when someone checks out the repo, they should still get a working, complete library, but perhaps that's not essential.

The trouble is that requiring the user who wants to work off bleeding edge to have to have `make` or `grunt` installed seems too bad.  If I get this working, I would prefer to actually build `ramda.min.js` at the same time.

**Comment by TheLudd** [comment]
> I think when someone checks out the repo, they should still get a working, complete library, but perhaps that's not essential.

I actually think the exact opposite. I don't think build should be checked in. I do think however that it should be possible to build with one single command. And this is not really true:

> The trouble is that requiring the user who wants to work off bleeding edge to have to have make or grunt installed seems too bad

The user does not need to have grunt installed. It can be installed as a dev dependency to ramda and the build command can be exposed as an npm script. No global installs needed.

**Comment by TheLudd** [comment]
Revisiting this, trying to clarify the intent I had when I created this issue:

I'd like ramda to be released more often. 

If there are any *technical* objections to this, such as "No can do because releasing requires too much manual labor that I am not willing to go though with on a weekly/bi-weekly basis" then I am willing to help make these manual tasks automated so that releases can be done more frequently and without any need for the person making the release to feel pressured that they are getting everything right. Releasing should not be a commitment, it should be running something like `npm run release`

If there are any *conceptual* objections. "We don't think that releasing more often is a good idea" then this issue can be closed.

**Comment by davidchambers** [comment]
The one thing that's difficult to automate is the writing of release notes. We could simply provide a link to the compare view, but that's not as useful as an [upgrade guide][1].


[1]: https://github.com/ramda/ramda/issues?q=is%3Aissue+%22upgrade+guide%22

**Comment by TheLudd** [comment]
Difficult perhaps but not impossible. Other projects certainly do it.

**Comment by TheLudd** [comment]
Ramda already has a good practice in place by requiering that all PRs should be only one commit. If we add certain conventions to the first line of the commit message then they could be used as change log items. Suggestions could be:
 * If a certain issue is fixed, include #[issueNumber] which could generate a link to the issue
 * Prefix breaking changes, new features, optimizations, bug fixes and deprecations with certain letters to group the change log into sections

I have never implemented this myself before but I do believe that this is how change logs are usually generated.

**Comment by CrossEye** [comment]
>> The trouble is that requiring the user who wants to work off bleeding edge to have to have make or grunt installed seems too bad

> The user does not need to have grunt installed. It can be installed as a dev dependency to ramda and the build command can be exposed as an npm script. No global installs needed.

I missed this when it came around.  Requiring the user to have NPM installed is the exact same issue.  A user who would like to just use `ramda.js` or `ramda.min.js` but wants to get the latest from HEAD because of some shiny new feature being discussed cannot do so.  This would be alleviated by quicker releases, as you suggest, but it doesn't solve the basic issue.

Nonetheless, we're already proceeding down this route, removing `ramda.js` from the regular build.  At least that will stop it from causing issues on commit.
