### ISSUE TITLE
pickWith?

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda#801]
Today I found myself in the situation where I had a JavaScript object where some values were null and I wanted to filter out those values, essentially this would have been a "pickWith" function where instead of supplying an array of keys to pick, a callback would be supplied that returned true/false to determine if a key should be picked or not.

Does this sound interesting or is there an existing solution to this? I am a little confused on how the callback would look since it perhaps would need to take two arguments, the key and the value. This would make it hard to combine with other ramda functions. But perhaps there is a better solution..

**Comment by buzzdecafe** [comment]
`pickBy`

**Comment by TheLudd** [comment]
:sheep:

**Comment by buzzdecafe** [comment]
> :sheep:

:laughing: 

that's the spirit

**Comment by CrossEye** [comment]
It seems that `pickBy` survived the [Great Preposition Consolidation of 2014][gp].

It doesn't quite have the semantics of our other `*By` functions, which usually take a function that operates on a list element and return a key that is fed into another process.,  That was as distinguished from `*With` functions which take a function that operated on two list items and reported a boolean about their comparison (less than, equal to, etc.)  It would be useful to rename this to something different.  Let's see what's another good preposition?  How about "on"?  :smile:

  [gp]: https://github.com/ramda/ramda/issues/65

**Comment by buzzdecafe** [comment]
`pickUp, pickOver, pickUpon, pickAt` the possibilities are endless
