### ISSUE TITLE
clean up root dir

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#802]
proposed:

Move:

* docs/
* jsdoc-template/
* less/
 
under lib/doc

Move:

* sauce 

under lib/

Move:

* tasks/

under lib/grunt

Move 

* bench/

under lib/

**Comment by davidchambers** [comment]
I don't think this would gain us much. It would make it more difficult to view the histories of the affected files, though.

**Comment by buzzdecafe** [comment]
feels very noisy to me in the root dir, but if it's just me, then i won't bother

**Comment by davidchambers** [comment]
It is noisy, I agree. It's also easier to find things when they're at the top level:

```console
$ python -c 'import this' | grep nested
Flat is better than nested.
```

**Comment by buzzdecafe** [comment]
i don't think moving things under lib/ is particularly deep nesting. and most of the things i *want* to find are obscured by the noise.

**Comment by TheLudd** [comment]
@davidchambers 

>  It would make it more difficult to view the histories of the affected files, though.

If you are talking about git log just add `--follow` as a flag. It tracks files through their movements, and blame is not affected.

While this may not be the most important issue I have also come across the thought that the root dir is a bit bloated.

**Comment by buzzdecafe** [comment]
also, the affected files are entirely ancillary to the library. i'll make a PR and we can discuss further

**Comment by CrossEye** [comment]
It's not just you @buzz.  I don't like deep trees, but I also prefer an uncluttered root.
