### ISSUE TITLE
"make clean; make" leaves you without dist/ramda.min.js

### ISSUE THREAD

**Issue by nicolasv** [ramda/ramda#803]
After `make clean; make`, `git status` reports that `dist/ramda.min.js` has been deleted.

I would expect `make` to build both `dist/ramda.js` and `dist/ramda.min.js`.

**Comment by davidchambers** [comment]
__dist/ramda.min.js__ is only updated when we publish a new version (whereas __dist/ramda.js__ is updated with each commit), so perhaps `make clean` should leave that file intact.

**Comment by nicolasv** [comment]
If leaving `dist/ramda.min.js` in tact is the right thing to do, pull request #804 does that.
