### ISSUE TITLE
Partial builds?

### ISSUE THREAD

**Issue by benjamingr** [ramda/ramda#806]
Hey, Ramda is kind of big but I'm really enjoying it. Is there any supported/official way to create a partial build containing only the functions I'm using?

**Comment by buzzdecafe** [comment]
Thanks! Yes, it is a little big, and yes there is a way to roll your own. 

`./scripts/build -- src/curry.js src/compose.js src/reduce.js src/map.js src/filter.js > dist/ramda.custom.js`

We should add some documentation for that.
