### ISSUE TITLE
zip should use the length of the largest array

### ISSUE THREAD

**Issue by megawac** [ramda/ramda#81]
Most other libraries use a `zip` implementation that will apply the length of the largest array for the result.

```
zip([1, 2, 3], ['a', 'b', 'c', 'd']); // => [[1,"a"],[2,"b"],[3,"c"],[undefined,"d"]]
```

**Comment by kwijibo** [comment]
+1 for R.unzip

**Comment by CrossEye** [comment]
@kwijibo: Interested in creating a Pull Request?

**Comment by kwijibo** [comment]
@CrossEye I'll give it a go
