### ISSUE TITLE
support R.__ placeholder everywhere

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#817]
We're adding support for `R.__` on a function-by-function basis (see #813, for example). Is there any reason not to bake this into `R.curry` so *all* our functions (and functions curried by users) can benefit?

**Comment by buzzdecafe** [comment]
> Is there any reason not to bake this into R.curry so all our functions (and functions curried by users) can benefit?

yes, `op` is intended to convert prefix/infix functions, not as a general placeholder mechanism. as such, `op` only applies to binary operations. expanding that to arities > 2 means adding complexity.

So put me down as :-1:

**Comment by davidchambers** [comment]
> expanding that to arities > 2 means adding complexity

Implementation complexity, do you mean?

**Comment by buzzdecafe** [comment]
yes. for a function of arity `n` there are `n^2` ways to insert placeholders.

**Comment by davidchambers** [comment]
If I could come up with a straightforward implementation, would you withdraw your opposition?

**Comment by kedashoe** [comment]
I've been using curry anywhere in my work for a bit now. A quick search shows that the majority of uses are for things like `get`, `has`, `gt`, etc as you would expect.. but there are times when I've used it for some random function that would not be an obvious candidate for `op`. For me, I do not care about blazing speed at all and like the flexibility (I'm simply using a function similar to the internal ramda `switch` curries, so I don't have any interesting code to post).

I wonder even if there is objection to having this be the default curry that there could be an option to build ramda using it instead?

**Comment by buzzdecafe** [comment]
> If I could come up with a straightforward implementation, would you withdraw your opposition?

go for it

**Comment by davidchambers** [comment]
![Challenge accepted!](http://cdn.hellogiggles.com/wp-content/uploads/2014/09/18/challenge-accepted.jpg)

**Comment by davidchambers** [comment]
Resolved via #819 and #836
