### ISSUE TITLE
mark old docs as deprecated

### ISSUE THREAD

**Issue by michaeljosephrosenthal** [ramda/ramda#818]
[the old docs](http://ramdajs.com/ramdocs/docs/index.html) should be have a link at the top to the new

**Comment by buzzdecafe** [comment]
we should just take the old docs down i think. anybody have any objections?

**Comment by CrossEye** [comment]
Agreed

**Comment by davidchambers** [comment]
I like the idea of removing everything pertaining to the old documentation from this repository and from the website. Perhaps we should serve a tiny HTML document at the paths in question to redirect visitors. For example:

```html
<html>
  <head>
    <meta http-equiv="refresh" content="0; url=http://ramdajs.com/">
  </head>
</html>
```

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda.github.io/commit/33efabad6bea36c20801dc6e76653fd5b912dbb9

**Comment by CrossEye** [comment]
Funny, I thought I did this recently, and I thought the redirect was working.  But it was essentially the same change as this.  Don't know why it's 404ing now.
