### ISSUE TITLE
site: expose documentation for previous releases

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#821]

**Comment by buzzdecafe** [comment]
:+1: been meaning to do this for a long time. keeps winding up on the back burner

**Comment by buzzdecafe** [comment]
should this be moved to ramde.github.io? we have 0.9 - 0.11 on the site, but no links in.

**Comment by buzzdecafe** [comment]
see https://github.com/ramda/ramda.github.io/issues/10
