### ISSUE TITLE
Document R.__ placeholder

### ISSUE THREAD

**Issue by michaelckelly** [ramda/ramda#835]
It'd be great to see `R.__` broken out specifically in the docs.  It's fairly useful and only mentioned incidentally from what I have seen.

**Comment by davidchambers** [comment]
:+1:

**Comment by CrossEye** [comment]
Good idea.  Do I hear a PR coming?  :smile:

**Comment by lwassermann** [comment]
+1, though it did not work in most of the cases were I tried using it. Could there be a restriction about using it as placeholder for a function argument or such?

**Comment by CrossEye** [comment]
@lwassermann: It will probably work in many more places since #819 has been included, but that is not yet in any published version.

**Comment by buzzdecafe** [comment]
closed by #935
