### ISSUE TITLE
Add logical (|| , &&, !) and rename functional versions

### ISSUE THREAD

**Issue by jethrolarson** [ramda/ramda#843]
As of 0.10 `R.or`, `R.and`, and `R.not` all operate on functions. While this is certainly useful, the names sound more like functional implementations of the operators. The matching operator functions are not present in the library. We offer many other operator functions (`R.add`, `R.eq`, `R.gt,` etc),  and I think `||`, `&&`, and `!` are valid additions to complete the suite. 

I propose:
* `R.or` renamed to `R.either`
* `R.and` renamed to `R.both`
* `R.or = (a,b) => a || b`
* `R.and = (a, b) => a && b`

! is a bit trickier. I'm having difficulty coming up with an intuitive name for the functional "not".
Logical "not" should certainly be `R.not = (a) => ! a` but best I have for functional not is `R.opposite` or `R.notBy`.

Thoughts?

**Comment by buzzdecafe** [comment]
in your proposal does the function `||` e.g. follow the javascript semantics of returning the first operand that is truthy (else `false`)? or should it be guaranteed to return a Boolean no matter what?

**Comment by CrossEye** [comment]
I can't remember the rationale (in #40) for removing these and renaming the old `orFn`, `andFn`, and `notFn` to `or`, `and`,and `not`.

It just seems funny to be thinking about going in the other direction now, although these are definitely better names.

The thing that concerns me about functions like these is that they will mislead users.  People are used to short-circuiting `or`s and `and`s in JS.  But, as parameters, these could never be short-circuited.  In true FP, of course, it should never matter, but it's easy to see someone trying to turn this:

    if (obj && obj.prop) {...}

into

    if (R.and(obj, obj.prop))

and not understanding why it now breaks.  Come to think of it, that might be the reason we dropped these functions in #40.

**Comment by jethrolarson** [comment]
I think we should assume that users at least have a basic understanding
about how JavaScript function syntax works. This isn't #jQuery

**Comment by jethrolarson** [comment]
@buzzdecade yeah, I'd choose not to coerce it to bool. Less for the user to have to learn.

**Comment by jethrolarson** [comment]
If the user is blanket-replacing operators with functions they probably need the epiphany the bug may provide. There's always R.either if they need the lazy evaluation, or they could just use the operator.

**Comment by CrossEye** [comment]
> There's always R.either if they need the lazy evaluation, or they could just use the operator.

Right, but that could also be an argument against including these functions.

I'm not actually really opposed.  But I am tired of having functions renamed or disappear.  I'm really ready for our API to settle down.  (That's mostly me being grumpy; I **do** want to figure all this stuff out right ahead of 1.0.)

I guess I'm looking for a stronger case than "wouldn't it be nice if...?"

**Comment by jethrolarson** [comment]
I agree with settlement on names.so we just need to decide if we're never
providing these operators as functions, because if we do then there aren't
more intuitive names than || == or and we'll have to rename. Better to do
it now than post 1.0

**Comment by buzzdecafe** [comment]
i also do not recall the rationale for excluding the simple boolean operator functions. I am also tired of the API changes, but I do believe the worst is behind us.

**Comment by buzzdecafe** [comment]
I like:

>  `R.or` renamed to `R.either`
>  `R.and` renamed to `R.both`

For `R.not`, how about `R.nix`?

**Comment by jethrolarson** [comment]
`R.nix` is better than anything else I came up with. I hope R.either doesn't get confused with the monad.

**Comment by CrossEye** [comment]
I prefer `negate` to `nix`.  "Nix" sounds more to me like "decide against" rather than "the opposite of" or "the inverse of".

**Comment by jethrolarson** [comment]
Isn't there already R.negate?

**Comment by CrossEye** [comment]
Oh yeah, I guess that's a problem...  :smile:

**Comment by CrossEye** [comment]
`belie`? `gainsay`? `refute`?  I think I'm starting to like `nix`!  :smile:

**Comment by davidchambers** [comment]
:thumbsdown: on these functions. `||` has been a significant source of bugs in this project, and many others I'm sure. It should only be used on Boolean values: the arbitrary distinctions between "true" and "false" values for other types lead to unclear and sometimes incorrect programs.

Interestingly, [Sanctuary][1]'s `or` function does have type `a -> a -> a`, though its behaviour is very different from that proposed in this issue:

```javascript
S.or([], []);  // => []
S.or([], [99]);  // => [99]
S.or([42], []);  // => [42]
S.or([42], [99]);  // => [42]

S.or(S.Nothing(), S.Nothing());  // => S.Nothing()
S.or(S.Nothing(), S.Just('bar'));  // => S.Just('bar')
S.or(S.Just('foo'), S.Nothing());  // => S.Just('foo')
S.or(S.Just('foo'), S.Just('bar'));  // => S.Just('foo')
```


[1]: https://github.com/plaid/sanctuary

**Comment by jethrolarson** [comment]
@davidchambers I'm not sure what your actual objections are.

**Comment by jethrolarson** [comment]
I guess the real problem is that no one has come up with a strong use case for operator functions. My proposal boils down to "We have other operators, we should have &&, ||, and ! for consistency and completeness". I guess we can close this until the value is made clear. Still, I worry that if we do change it later the api will be so stable that we'll have to come up with silly names for the operator versions.

**Comment by davidchambers** [comment]
> @davidchambers I'm not sure what your actual objections are.

Fixes for Ramda bugs caused by incorrect use of `&&`, `||`, and `!`: #236, #496, #505, #507, #533, #785. I'm sure many similar bugs are still to be discovered.

I don't endorse function equivalents of these operators unless they are much stricter. All three functions should only accept Booleans (and possibly types which provide a suitable hook such as an `or` method).

**Comment by buzzdecafe** [comment]
@jethrolarson did you want to do a PR on this? Looks like you may face some resistance, but I think there is a good case to be made for having straight boolean operator functions. In any event, we should settle on this before 1.0

**Comment by CrossEye** [comment]
As this was just brought up again in Gitter, I think it's worth pursuing.

I don't share David's worries about coercing to booleans.  Yes, it can be used incorrectly, but it is also very useful, and is is how people are using -- and how they want to use -- Javascript.  I've had codebases where I insisted on forcing to booleans.  There are good reasons in some circumstances to be worried.  But I don't think that's the concern of a library like Ramda.  And my biggest concern about a `[Bool] -> Bool` version would be how often we had to explain it, and that we'd end up adding a `coerce` function and telling all the complainants to `map(coerce)` before calling `or`.  Something just seems wrong with that.

I still wish I could remember why we dropped the older versions of these functions.  Maybe it was simply to make way for the current functions (which still seem to me the more useful ones) to claim the best names.

**Comment by jethrolarson** [comment]
Sure. I'll see if I can whip it up.

**Comment by jethrolarson** [comment]
Feels weird that the sig for both of them is `* -> * -> *` but it also feels right in a way.

**Comment by jethrolarson** [comment]
I didn't feel comfortable switching R.not to R.nix so I'm leaving that out for now.

**Comment by jethrolarson** [comment]
At behest I've added R.nix to the PR. R.anti doesn't sound like a verb to me. Ixnay the ooleanbay!

**Comment by buzzdecafe** [comment]
ha, i like `ixnay`

**Comment by jethrolarson** [comment]
Should we add to this to some upgrade guide once it's in?

**Comment by davidchambers** [comment]
> Should we add to this to some upgrade guide once it's in?

When we release 0.12.0, yes.
