### ISSUE TITLE
Ramda needs a function that would name functions

### ISSUE THREAD

**Issue by yuri** [ramda/ramda#845]
I would like to propose a function `R.name(name, fn)` that would return a function that is equivalent to `fn` but named based on the value of `name`. In other words `R.name('get42', function() { return 42;})` will return a function named `get42` that returns 42 when called. This would come handy for debugging.

I can submit a PR for this, but wanted to see if this is something that would be seriously considered for inclusion. The implementation would need to be a bit ugly and would involve using the Function constructor. There will probably also need to be a mechanism for turning this off in production, so that `R.name(name, fn)` would just return `fn`.

**Comment by buzzdecafe** [comment]
definitely useful for the often discussed but just as often neglected "debug" build. AT present, we have *no* `eval` of any kind in the codebase. And that is a good thing. 

At one time @megawac was talking about storing metadata on functions. That may be another way to reach the same goal.

**Comment by yuri** [comment]
Limiting this to the debug build might be sensible. There would need to be a stub in the production build, that is `R.name()` that just returns the supplied function. Though, there are cases where this would be useful in production. The main one is where you have a module that exports a function created through Ramda. In the absence of `R.name()` one would need to do something along the lines of:

```
exports.getFoo = function getFoo(arg) {
  return R.compose(bar, baz)(arg);
};
```

`R.name()` would allow for what I would consider a more elegant solution:

```
exports.getFoo = R.name('getFoo', R.compose(bar, baz));
```

I am not sure how one would achieve the same result by storing metadata on functions.

**Comment by megawac** [comment]
I still am, it would let you remove all the arity functions by storing it
in a meta object

**Comment by buzzdecafe** [comment]
i realize it was *me* who tabled that in the past, but now i'm reconsidering. does it *cost* anything?

**Comment by megawac** [comment]
It'd be less code, the cost would be object creation of the meta object
which should be negligible

**Comment by CrossEye** [comment]
I'm pretty uncomfortable with bringing back any form of `eval` after we managed to root out the last one.  If there's a good way to do this without that, I could be for it, or I might be up for it for a 'debug' build.

**Comment by yuri** [comment]
If the Function constructor is a definite "no", then the other option would be to annotate the function object with the extra information (is this was @megawac wanted to do?) and then provide an implementation of `prepareStackTrace()` that can take advantage of those annotations. The downside is the user will have to choose between Ramda's stack formatting and other libraries that may want to overwrite `prepareStackTrace()`.

**Comment by xorgy** [comment]
I think the `prepareStackTrace()` route is probably saner, though I personally don't mind either implementation.

>“When I walk in a valley of stack trace, I fear no  `eval`, for thou art with me, thy lambda and thy combinator — they comfort me.”
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;– *Ramda 23:4*

**Comment by buzzdecafe** [comment]
is `prepareStackTrace` chrome only? in which case, eeeww.

**Comment by yuri** [comment]
V8, so Chrome and Node. There would need to be a separate solution for Firefox and it would need to not cause problems in other browsers. The cross-browser solution is the Function constructor. :)

**Comment by buzzdecafe** [comment]
oh javascript ..... :grimacing:

**Comment by TheLudd** [comment]
Is it ES3 compatible? :trollface:

**Comment by asaf-romano** [comment]
Firefox has this API:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName

**Comment by buzzdecafe** [comment]
i think this thread is picking up on similar ideas: #1125
