### ISSUE TITLE
remove remaining aliases

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#859]
Ramda now has just two :alien:s:

  - `R.I` is an :alien: for `R.identity`; and
  - `R.get` is an :alien: for `R.prop`.

I would love to be able to say _Ramda has no aliases_. I don't mind which of the four combinations we keep.

**Comment by TheLudd** [comment]
I certainly prefer `identity`  to `I`
I also think I prefer `prop` to `get` but that is less important for me.

**Comment by CrossEye** [comment]
I'm with @TheLudd on both, although there's a twinge on giving up `I`.

**Comment by buzzdecafe** [comment]
<3 `I`

**Comment by jethrolarson** [comment]
`R.T` and `R.F` are the only single char names now. Are they sticking around?

**Comment by davidchambers** [comment]
> Are they sticking around?

Yes. `R.T` is useful in conjunction with `R.cond`. :)

**Comment by jethrolarson** [comment]
But what about R.truth and R.phase? :P

**Comment by TheLudd** [comment]
@jethrolarson or `R.absolutelyRight` and `R.notInAnyWayCorrect`? ;)

**Comment by buzzdecafe** [comment]
i think we'll go with `R.indubitably` and `R.certainlyNot`

**Comment by jethrolarson** [comment]
+1 for R.indubitably

**Comment by buzzdecafe** [comment]
in that case let's got with `R.indubitably` and `R.dubitably`

**Comment by jethrolarson** [comment]
But literally dubitably means doubtful, so R.dubitably == Maybe(false)
