### ISSUE TITLE
[Question] replaceable implementations for map and list?

### ISSUE THREAD

**Issue by sleepyfox** [ramda/ramda#860]
I'd like to be able to use Ramda with the immutable data structures from Mori, I've seen that Eweda was built around the concept of pluggable List implementations, is this possible with Ramda?

**Comment by CrossEye** [comment]
Unfortunately it's not.  Ramda does do dynamic dispatching of many core functions, and I would not object to extending it to additional ones, but that will probably only work with libraries that present some sort of OO methods.  It works quite well, for instance, with the [FantasyLand][fl] specification, which dictates its functions as object methods.

Eweda was a simpler project and built everything on top of a very few base functions.  That's how we could work with replaceable cores; all we had to do was implement those functions and we had a new implementation.  Unfortunately, it was also deadly slow.

I would love to be able to work with mori, with immutable-js, and the other Immutable collections libraries.  But the will all be a challenge, and mori will probably be more so.

If you have some suggestions for how to go about doing this, I would love to hear them.

  [fl]: https://github.com/fantasyland/fantasy-land

**Comment by kevinbeaty** [comment]
See #878 for initial transducers implementation that  could potentially lead to support of Immutable.js / Mori in the future.
