### ISSUE TITLE
Is there an object-wrap?

### ISSUE THREAD

**Issue by tolmasky** [ramda/ramda#863]
Sorry, couldn't find this from a cursory look through, but given x, is it possible to return { a:x }? Something like:

f = R.wrap("a")
f(5) ==> { a: 5 }

**Comment by tolmasky** [comment]
Ah, I can accomplish it with assoc.

**Comment by CrossEye** [comment]
Sounds like `createMapEntry` would be your best fit if you're not trying to associate with an existing object.

    var f == R.createMapEntry('a');
    f(5); //=> {a: 5}

**Comment by tolmasky** [comment]
Ah yeah even better, thanks!
