### ISSUE TITLE
"show" function

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#875]
I'd like Ramda to provide a function from value to string representation. Ideally the output could be pasted into the REPL to produce a value equivalent to the input value.

```javascript
> R.show(42)
'42'
> R.show('42')
'"42"'
> R.show([1, 2, 3])
'[1, 2, 3]'
> R.show({x: 0, y: 0, 'foo-bar': true})
'{"foo-bar": true, x: 0, y: 0}'
> R.show(null)
'null'
```

Types could define `show`:

```javascript
function Nothing() {
  if (!(this instanceof Nothing)) {
    return new Nothing();
  }
}
Nothing.prototype.show = R.always('Nothing()');

function Just(value) {
  if (!(this instanceof Just)) {
    return new Just(value);
  }
  this.value = value;
}
Just.prototype.show = function() { return 'Just(' + R.show(this.value) + ')'; };

R.show([Nothing(), Just([1, 2, 3])]);  // => '[Nothing(), Just([1, 2, 3])]'
```

**Comment by kedashoe** [comment]
:+1:

Is there a reason not to call this `toString` though? I think it is not uncommon for authors to implement this, eg

https://github.com/facebook/immutable-js/blob/master/dist/immutable.js#L1736

That way the method would work nicely right off the bat with many JS objects in the wild. Or if you keep `show`, maybe can still check if the passed in argument is an object with a `toString` method different from `Object.prototype.toString` after checking for a `show` method

**Comment by davidchambers** [comment]
> Is there a reason not to call this `toString` though?

My reason for favouring `show` is that JavaScript provides `toString` methods which don't return a value suitable for pasting into the REPL:

```javascript
> ['abc', 1, 2, 3].toString()
'abc,1,2,3'
```

Supporting types which get `toString` right (such as the Map to which you linked) would be very nice indeed. We could make this work, as you suggest. We'd need something along these lines:

```
if x is a value of a built-in type other than Object:
    produce a suitable string representation
else if x has a "toString" method which is not Object.prototype.toString:
    dispatch to x's "toString" method
else:
    produce a suitable string representation (e.g. '{a: 1, b: 2}')
```

**Comment by CrossEye** [comment]
I'm :+1: if we can create a suitable implementation which is not horrible.  I've seen some of these that are pretty nasty.

**Comment by buzzdecafe** [comment]
what would the output be of  `show(function(x, y) { return x * y; })`?

what about `show(curry(function(x, y) { return x * y; }))`?

**Comment by davidchambers** [comment]
For functions we can dispatch to `toString`. This works well for vanilla functions but not for decorated functions. Even so, I'd prefer to use `toString` than to admit defeat and return `'[object Function]'`.

Arguments objects, on the other hand, can be handled nicely:

```javascript
R.toString((function() { return arguments; }('abc', 1, 2, 3)))
'(function() { return arguments; }("abc", 1, 2, 3))'
```

**Comment by buzzdecafe** [comment]
shouldn't it be recusrive? e.g. if arguments contains object & arrays, etc.

**Comment by davidchambers** [comment]
> shouldn't it be recusrive? e.g. if arguments contains object & arrays, etc.

It should be recursive, yes. For example:

```javascript
> R.toString((function() { return arguments; }('abc', [1, 2, 3])))
'(function() { return arguments; }("abc", [1, 2, 3]))'
```

**Comment by CrossEye** [comment]
> ```javascript
> > R.toString((function() { return arguments; }('abc', [1, 2, 3])))
> '(function() { return arguments; }("abc", [1, 2, 3]))'
> ```

I don't think there would be any way to achieve this.  The function application would be evaluated before it's passed to this `toString` function.

**Comment by davidchambers** [comment]
You're mentally misparsing the expression. The argument to `toString` is an Arguments object:

```javascript
> (function() { return arguments; }('abc', [1, 2, 3]))
{ '0': 'abc',
  '1': [ 1, 2, 3 ] }
```

**Comment by AutoSponge** [comment]
What do you think of using the standard `.toJSON` method which gets dispatched by `JSON` during serialization, for instance with `Date` objects?

This would mean `Nothing().toJSON(); //=> null` instead of the proposed description.

**Comment by CrossEye** [comment]
Right, I thought you were suggesting in essence that

```javascript
R.toString({ '0': 'abc', '1': [ 1, 2, 3 ] }); //=> '(function() { return arguments; }("abc", [1, 2, 3]))'
```

which made no sense to me.

**Comment by davidchambers** [comment]
@AutoSponge: There's a lot to dislike about the JSON specification and the JavaScript implementation specifically. `new Date(1350246457000)` and `'2012-10-14T20:27:37.000Z'` serialize to the same value, so metadata must be conveyed out of band in order to correctly deserialize ambiguous JSON strings. Different implementations may serialize `{a: 1, b: 2}` differently, and a single implementation may serialize `{a: 1, b: 2}` and `{b: 2, a: 1}` differently. `Infinity`, `-Infinity`, and `NaN` serialize to `'null'`. Many of the [differences between CANON and JSON][1] are deserving of [WAT][2] status.

@CrossEye: You were thrown off by the way arguments objects are displayed in Node's REPL. The proposed function will not return ambiguous values! :)


[1]: https://github.com/davidchambers/CANON#differences-between-canon-and-json
[2]: https://www.destroyallsoftware.com/talks/wat
