### ISSUE TITLE
[Question] How to transform object to array point free style

### ISSUE THREAD

**Issue by bobiblazeski** [ramda/ramda#877]
```javascript
//We have a list of elements, some are duplicates. We’re trying to figure out how to find
// the duplicate elements and increase a counter value by 1 for each instance of the element found.
// The list consists of lists with two elements, the first being the incremental counter,
// the second being the string sought.
// Example:
// Input ((1 "one") (1 "two") (1 "three") (1 "one") (1 "four") (1 "two"))
// 
// The result should be:   ((2 "one") (2 "two") (1 "three") (1 "four"))
// brunberg:flip(count each group v[;1];unique v[;1]) // q solution 

var example= [[1,"one"],[1,"two"],[1,"three"],[1,"one"],[1,"four"],[1,"two"]];
// This get's me to object
var brunberg = R.compose(R.mapObj(R.length),R.groupBy(R.nth(1)))
brunberg(example)
// =>"{"one":2,"two":2,"three":1,"four":1}"
// How to make it an array point free if possible
var whatINeed = [[2,"one"],[2,"two"],[1."three"],[1,"four"]];

```

**Comment by davidchambers** [comment]
Is the value of the first element of each tuple in the input list guaranteed to be `1`? Is the second element of each tuple guaranteed to be a string?

**Comment by bobiblazeski** [comment]
Here's the original question http://www.nsl.com/papers/kisntlisp.htm

**Comment by buzzdecafe** [comment]
`R.compose(R.invertObj, R.mapObj(R.length),R.groupBy(R.nth(1)))`

?

**Comment by bobiblazeski** [comment]
Can try it in my tablet but what I need is an array not inverted object. I find this pattern quite common in my usage. Start from object, usually as result of group, then transform into array, where I need both keys and values.

**Comment by davidchambers** [comment]
If your algorithm can't be expressed simply in a point-free style, that's not necessarily a problem. Sometimes one should just use a lambda. ;)

**Comment by buzzdecafe** [comment]
`R.map(function(pair) { return [R.nth(1, pair), R.nth(0, pair)]; }, R.toPairs(brunberg(example)))`

**Comment by bobiblazeski** [comment]
I guess lambda wil have to do. I wrote a little article about pointfree in Ramda giving above as an problem https://medium.com/@bobiblazeski/tacit-ramda-c914775ff4b1

**Comment by buzzdecafe** [comment]
> Plus I have a bitter sweet relationship with its authors, who never gave me what I've asked, but they always delivered what I need.

If it makes you feel any better, I often don't get what I want either! :smile:

**Comment by bobiblazeski** [comment]
No I accept the better approach even if comes from someone else. I learned to do without type dispatch and optional arguments.

**Comment by bobiblazeski** [comment]
Here's the solution without lambda 

var example= [[1,"one"],[1,"two"],[1,"three"],[1,"one"],[1,"four"],[1,"two"]];
var brunberg = R.compose(R.map(R.reverse),R.toPairs,R.mapObj(R.length),R.groupBy(R.nth(1)))    
JSON.stringify(brunberg(example));

**Comment by buzzdecafe** [comment]
nice!

**Comment by burabure** [comment]
IMHO Point free is great for understanding the details and effective workings of a problem. But point free code is pointless if it's not clearer than it's pointed version.

**Comment by buzzdecafe** [comment]
@burabure i agree, and in fairness, i think @bobiblazeski agrees with that point as well. In this case I think he was pursuing his curiousity to see what it would take to make a PF version.

**Comment by burabure** [comment]
Agree =)
