### ISSUE TITLE
avoid ++ and -- operators

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#886]
Postfix `++` and `--` are excessively tricky operators (to paraphrase [Crockford][1]). `x++` evaluates to the current value of `x` *then* increments `x`. I avoid these operators in my own code and our JSHint config forbids them in projects at Plaid.

Prefix `++` and `--` are less tricky but entirely unnecessary. `++x` can be written as `x += 1`. Again, I have JSHint configured to forbid the use of these operators.

The existence of both prefix and postfix forms is itself a source of confusion.

We have lots of code like this:

```javascript
var idx = -1;
var len = xs.length;
while (++idx < len) { ... }
```

I don't share the devotion to `while` over `for`. I don't like `++`, nor do I like initializing `idx` to a value one less than the first index. The code above can be expressed more clearly as a `for` loop:

```javascript
for (var idx = 0, len = xs.length; idx < len; idx += 1) { ... }
```

For reverse loops we use this idiom:

```javascript
var idx = xs.length;
while (idx--) { ... }
```

I dislike this approach for two reasons. First, it uses the tricksy postfix `--` operator. Secondly, it relies on implicit Number → Boolean conversion in evaluating the condition. A `for` loop can avoid these sources of incidental complexity:

```javascript
for (var idx = xs.length - 1; idx >= 0; idx -= 1) { ... }
```

I propose that we use JSHint's [`plusplus`][2] option to forbid `++` and `--` in both prefix and postfix forms, and that our conditional expressions evaluate to `true` or `false`.

[1]: http://www.jslint.com/lint.html#inc
[2]: http://jshint.com/docs/options/#plusplus

**Comment by buzzdecafe** [comment]
#947
