### ISSUE TITLE
replace all uses of Array.prototype.push with index assignment

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#890]
Added to the Google JavaScript Style Guide in [July 2010][1]:

> You can also use an array as a stringbuilder, and convert it into a string with `myArray.join('')`.  Note that since assigning values to an array is faster than using `push()` you should use assignment where possible.

It's worth noting that this commit was made almost five years ago. The section above was removed in [November 2012][2].

What's the story in 2015? It looks like [much of a muchness][3] to me.

/cc @megawac

[1]: https://code.google.com/p/google-styleguide/source/detail?r=52
[2]: https://code.google.com/p/google-styleguide/source/detail?r=97
[3]: http://jsperf.com/index-vs-push/6

**Comment by davidchambers** [comment]
@AutoSponge, in #592:

> Approximately 30% speed gain on filter benchmarks.

Before #887:

    Running suite filter [lib/bench/filter.bench.js]...
    >> _.filter(nums, isEven) x 2,735,544 ops/sec ±0.38% (102 runs sampled)
    >> filter(isEven, nums) x 2,483,532 ops/sec ±0.42% (97 runs sampled)
    >> filter(isEven)(nums) x 1,822,110 ops/sec ±3.81% (94 runs sampled)
    >> filterEven(nums) x 2,300,862 ops/sec ±5.15% (93 runs sampled)
    Fastest test is _.filter(nums, isEven) at 1.10x faster than filter(isEven, nums)

After #887:

    Running suite filter [lib/bench/filter.bench.js]...
    >> _.filter(nums, isEven) x 2,670,441 ops/sec ±0.32% (102 runs sampled)
    >> filter(isEven, nums) x 648,427 ops/sec ±0.45% (100 runs sampled)
    >> filter(isEven)(nums) x 602,343 ops/sec ±0.51% (98 runs sampled)
    >> filterEven(nums) x 618,233 ops/sec ±2.66% (93 runs sampled)
    Fastest test is _.filter(nums, isEven) at 4.1x faster than filter(isEven, nums)

That's significant. I'll open a pull request to replace all uses of `Array.prototype.push`.

**Comment by megawac** [comment]
Usually push is faster from my experience - at least it was 3 months ago in
v8 and ff
