### ISSUE TITLE
document steps for updating ramdajs.com

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#894]

**Comment by davidchambers** [comment]
Could you link to the relevant documentation?

**Comment by buzzdecafe** [comment]
didn't i write it into a chat window :smiling_imp:

**Comment by davidchambers** [comment]
> here's the $0.05 tour of the docs publishing "process"
>
> 1.  `grunt gh-pages`
>     this dumps the generated docs into dist/gh-pages
> 2.  make sure you have checked out ramda.github.io repo nearby
> 3.  `mkdir ../ramda.github.io/0.12`
> 4.  `cp -Rp dist/gh-pages/* ../ramda.github.io/0.12`
> 5.  `cd ../ramda.github.io`
> 6.  `cp -Rp 0.12/* ./`
> 7.  `git add --all .`
> 8.  `git commit -m "0.12 docs"`
> 9.  `git push`
> 10. profit
