### ISSUE TITLE
404 at http://ramdajs.com/docs/

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#895]
<http://ramdajs.com/docs/> attempts to load a script from <http://ramdajs.com/docs/main.js>, which does not exist.

Thanks for mentioning this, @joneshf.

**Comment by buzzdecafe** [comment]
gah, this is from the root-dir cleanup. copied it over by hand for now, will have to update gh-pages task

**Comment by davidchambers** [comment]
Thanks for the quick fix.

> will have to update gh-pages task

Shall I create an issue for this?

**Comment by buzzdecafe** [comment]
too late

#896
