### ISSUE TITLE
take lacks example

### ISSUE THREAD

**Issue by bobiblazeski** [ramda/ramda#926]
Please add example usage for take. http://ramdajs.com/docs/#take

**Comment by CrossEye** [comment]
Good idea.  Would you be interested in opening a [pull request][pr]?

  [pr]: https://github.com/ramda/ramda/pulls

**Comment by bobiblazeski** [comment]
Sure here it is https://github.com/ramda/ramda/pull/927

**Comment by buzzdecafe** [comment]
closed by #927
