### ISSUE TITLE
Transforming an object based on existing properties

### ISSUE THREAD

**Issue by eiriklv** [ramda/ramda#928]
First of all - awesome lib :-)

I have a very specific thing I'm doing in a stream processing application ([collectify](https://github.com/eiriklv/collectify)), where I would get an object like this into the pipeline:

```javascript
// enters the pipeline
{
  id: 123456,
  url: 'http://some-news-site.com/article/123456'
}
```

First i want to extend it to this:

```javascript
// extended
{
  id: 123456,
  url: 'http://some-news-site.com/article/123456',
  body: 'http://some-news-site.com/article/123456',
  shares: {
    facebook: 'http://some-news-site.com/article/123456',
    twitter: 'http://some-news-site.com/article/123456'
  }
}
```

Followed by an async transform creating this result:

```javascript
// transformed
{
  id: 123456,
  url: 'http://some-news-site.com/article/123456',
  body: '<p>the body of the article/site....yaddayadda</p>',
  shares: {
    facebook: 235,
    twitter: 432
  }
}
```

I'm currently solving this by using a self-made library ([fp-object-transform](https://github.com/eiriklv/object-transform)), but it looks like R.assoc/R.assocPath and R.evolve might be able to solve the same thing, and I'd really like to have som consistency, as I'm now using:

* [highland](https://github.com/caolan/highland) for streams
* [lodash-fp](https://github.com/lodash/lodash-fp) to fill in the gaps of highland and to provide ```rearg```(need it to make other libs like [mongoose](https://github.com/learnboost/mongoose/) comply more to fp/streams).
* [fp-object-stream](https://github.com/eiriklv/object-transform) to be able to copy/expand and async'ly derive new properties based on existing ones as input

Now I'm hoping Ramda can swallow some of these as a replacement (i.e lodash and fp-object-stream).

So my question I guess is - Can this be done in an elegant way with Ramda?

Any thoughts appreciated :-)

**Comment by CrossEye** [comment]
I think Ramda's tools might help.  This for instance would do your first step:

```javascript
var result = R.reduce(R.flip(R.assocPath(R.__, data.url)), data)(
    [['body'], ['shares', 'facebook'], ['shares', 'twitter']]
);
```

And then you could do things like

```javascript
updated = R.assocPath(['shares', 'facebook'], 235, result);
```

(This is making me pine a bit for the older API of the path functions.  This would be much nicer written, `['body', 'shares.facebook', 'shares.twitter']`.  The replacement API using arrays is more flexible, but it certainly doesn't look as nice to me.)

**Comment by eiriklv** [comment]
This would be ok if i had direct access to ```data```, but that isn't the case for this example I'm afraid.

Here's an a conceptual example of what the pipeline looks (just to clarify):

```javascript
// two-step process alternative
const extendedArticlesStream = articleStream
  .map(copyToFrom({
    body: 'url' // this means that 'data.url' is copied to 'data.body'
    shares: {
      facebook: 'url', // this means that 'data.url' is copied to 'data.shares.facebook'
      twitter: 'url' // this means that 'data.url' is copied to 'data.shares.twitter'
    }
  }))
  .map(transformTo({
    body: asyncFetchBody, // transform 'data.body'
    shares: {
      facebook: asyncFetchFacebookShares,  // transform 'data.shares.facebook'
      twitter: asyncFetchTwitterShares // transform 'data.shares.twitter'
    }
  })
)).parallel(10)



// Or



// single-step process alternative
const extendedArticlesStream = articleStream
  .map(deriveTo({
    body: ['url', asyncFetchBody], // transform 'data.url' with 'asyncFetchBody' and place it in 'data.body'
    shares: {
      facebook: ['url', asyncFetchFacebookShares],  // ...
      twitter: ['url', asyncFetchTwitterShares] // ...
    }
  })
)).parallel(10)



// a depiction of what the async* functions might look like



function asyncFetchBody(url, callback) {
   // .....
   callback(null, bodyOfUrl);
}

function asyncFetchFacebookShares(url, callback) {
   // .....
   callback(null, facebookSharesForUrl);
}

function asyncFetchTwitterShares(url, callback) {
   // .....
   callback(null, twitterSharesForUrl);
}
```

where ```copyToFrom``` and ```transformTo``` or ```deriveTo``` is the functionality I'm am looking for in Ramda. Or something that might get me there.

**Comment by CrossEye** [comment]
I don't think there are any simple functions to do what you want.  Two reasons:

  * async is going to be quite tricky when combined with immutability.  If your callbacks are actually asynchronous and you can't use something like Promises to run this only after you have back all the results you want, it sounds extremely difficult to combine with Ramda's philosophy of referentially transparent functions.
  * the function which seems to fit best it `evolve`.  The code below would be relatively close to your `transformTo` example above, but the updating functions `evolve` are only `value -> value`.  You seem to need the state of the entire input object for your `copyToFrom` (so, `value -> Object -> value`.)  While we might consider extending `evolve` that way, it's not clear if people would agree (me included) for reasons discussed many places, including the long thread at #452.

  ```javascript
  evolve({
      body: asyncFetchBody,
      shares: evolve({
          facebook: asyncFetchFacebookShares,
          twitter: asyncFetchTwitterShares
      })
  });
  ```

**Comment by scott-christopher** [comment]
If I understand correctly, you should be able to achieve this with the use of lenses (n.b. `R.composeL` and `R.lensProp` only just landed in master).

```js
function transformAsync(obj) {
    var bodyLens     = R.lensProp('body');
    var sharesLens   = R.lensProp('shares');
    var facebookLens = R.composeL(R.lensProp('facebook'), sharesLens);
    var twitterLens  = R.composeL(R.lensProp('twitter'), sharesLens);

    return Promise.all([
        fetchBody(obj.url).then(bodyLens.set),
        fetchFacebookShares(obj.url).then(facebookLens.set),
        fetchTwitterShares(obj.url).then(twitterLens.set)
    ]).then(R.reduce(function (obj, setter) { return setter(obj); }, {
        id: obj.id, url: obj.url, shares: {}
    }));
}

// assuming the following functions produce the necessary promises
function fetchBody(url) {
    return Promise.resolve('<html></html>');
}
function fetchFacebookShares(url) {
    return Promise.resolve(parseInt(Math.random() * 100, 10));
}
function fetchTwitterShares(url) {
    return Promise.resolve(parseInt(Math.random() * 100, 10));
}
```

Calling transformAsync will then return a promise of the fully transformed object,
resolving once all async operations have completed.
```js
transformAsync({
  id: 123456,
  url: 'http://some-news-site.com/article/123456'
}).done(function (obj) { console.log(obj); });
```

**Comment by eiriklv** [comment]
@scott-christopher This is the stuff I'm looking for - thanks! :-)

**Comment by CrossEye** [comment]
@scott-christopher: Nice work.  Obviously these lens additions are going to be useful!
