### ISSUE TITLE
rename R.nix

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#929]
I'd prefer `R.complement`. Clojure uses this name: [`clojure.core/complement`][1]. The definition is apt:

> the members of a set or class that are not members of a given subset

Nix, on the other hand, means "nothing" or "cancel".

[1]: https://clojuredocs.org/clojure.core/complement

**Comment by buzzdecafe** [comment]
ok by :cow2:

**Comment by CrossEye** [comment]
:bike:-:house_with_garden:

I don't like any of the names here.  `complement` seems to have more to do with complete sets than with predicates, but it's no worse than the others that we've discussed.

Mu.

**Comment by davidchambers** [comment]
`complement` reads nicely to me in cases such as this:

```haskell
even :: Int -> Int
even n = n `mod` 2 == 0

odd :: Int -> Int
odd = complement even
```

@CrossEye, what do you mean by the term "complete set"?

**Comment by CrossEye** [comment]
Just that to my mind

```haskell
complement:: Subset -> Subset
```

Not

```haskell
complement:: (a -> Bool) -> (a -> Bool)
```

It's not a big deal though.  I simply don't like any name here but `not`, which can't do double-duty.  :frowning:

**Comment by buzzdecafe** [comment]
there's always `bang`

**Comment by jethrolarson** [comment]
Lol at bang. Didn't think of that but I like it better than nix. Nix means "cease", not really negate or boolean reverse

**Comment by CrossEye** [comment]
While I don't love it, I do think `complement` is our best bet.  At least some people looking for this will try that name.  My objection above was only half-hearted.

**Comment by buzzdecafe** [comment]
let's go with `complement`.

**Comment by jethrolarson** [comment]
*You're looking dashing today*. How's that?
