### ISSUE TITLE
'Package' function

### ISSUE THREAD

**Issue by jtmarmon** [ramda/ramda#930]
Ever since starting to use ramda, I've begun to avoid the `function` keyword like the plague. And I'm pretty successful at it. However, there's one thing that still manages to get me to use that 'function' keyword: callbacks.

I use promises in my code; however, sometimes I'm forced (against my will) to interface with callbacks. In this case, the code ideally looks like:

```
myPromise.then(next).catch(next);
```

However, often times a successful promise will return some data, forcing me to do this:

```
myPromise.then(function() {
  next();
}).catch(next);
```

So what I would _love_ is a ramda method that allows me to 'package' data onto a function, applying that data and returning the result the next time the function is called.

For example:

```
myPromise.then(R.package(null, next)).catch(next)
```

Isn't that prettier?! Would be great to have. Not sure if you guys agree there's a good enough use case for this

Also - forgive me if this exists already in some form. I find it quite hard to traverse the docs to find a specific feature...not sure what a better implementation would be though.

**Comment by CrossEye** [comment]
I'm a bit confused by the request.  First of all does [`bind`][bi] do what you would like?  (It looks as though the documentation is missing examples, but it's similar to the native `Function.prototype.bind`, giving a fixed `this` context for the function.)  If not, you might see if [`partial`][pl] or [`partialRight`][pr] works for you.

But more importantly, I don't see why you need the `function(val) { ... }` wrapper at all.  Both the [Promises A++ Spec][pa] and the [ES6 Specification][es] require that the implementation call the success or failure handlers passing the appropriate values.  So it sounds as though it should just work.  Can you explain more fully, either here or in the [Gitter Room][gr].


  [bi]: http://ramdajs.com/docs/#bind
  [es]: http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.prototype.then
  [gr]: https://gitter.im/ramda/ramda
  [pa]: https://github.com/promises-aplus/promises-spec
  [pl]: http://ramdajs.com/docs/#partial
  [pr]: http://ramdajs.com/docs/#partialRight

**Comment by jtmarmon** [comment]
R.nAry(0, next) does what I want!
