### ISSUE TITLE
Old environment bugs.

### ISSUE THREAD

**Issue by jdalton** [ramda/ramda#933]
I was talking with @CrossEye on gitter and he suggested I post on some of the older environment issues that Ramda could address.
- `[DontEnum]` bug in IE < 9 skips iterating enumerable object properties that exist as non-enumerable properties of the `Object.prototype`. (so props like `constructor`, `toString`, & `valueOf`)
- `Function.prototype` iteration. Some older WebKit enviros will incorrectly treat the `.prototype` property of functions as enumerable.
- `arguments` object iteration. Some older WebKit treat its indexes as non-enumerable.
- Access of string chars through indexes (IE < 9 for string objects; IE < 8 for string primitives)
- Iteration of strings (some environments treat string indexes as non-enumerable)

For a summary of issues and affected environments check out the [support](https://github.com/lodash/lodash-compat/blob/3.5.0-npm/support.js#L38-L188) module of lodash-compat.

Instead of reworking fixes for these issues, as Underscore and Amp have tried and failed to do correctly, it would be great if Ramda leveraged modules, specifically [lodash-compat](https://www.npmjs.com/package/lodash-compat) modules, to tackle it.

``` js
var keys = require('lodash-compat/object/keys'),
    keysIn = require('lodash-compat/object/keysIn');
```

It should integrate into your build easy enough and has tackled these issues already. lodash is tested in old enviros and even IE compat modes so it's got these issues covered. So you could require the modules you need and avoid the headache of older environment fixes.

The [keys](https://github.com/lodash/lodash-compat/blob/3.5.0-npm/object/keys.js) and [keysIn](https://github.com/lodash/lodash-compat/blob/3.5.0-npm/object/keysIn.js) methods should do for most things (for-in et al), even strings as it follows ES6 rules and coerces them to objects. There's also [forOwn](https://github.com/lodash/lodash-compat/blob/3.5.0-npm/object/forOwn.js) and [forIn](https://github.com/lodash/lodash-compat/blob/3.5.0-npm/object/forIn.js) if you want.

**Comment by CrossEye** [comment]
Thank you very much.  We will definitely look into them.

I doubt we'll use the the lodash implementations directly; so far Ramda has no external dependencies and I don't think we want to start adding them.  I imagine we'll at the very least take inspiration from them.

I don't know if we'll worry about the old Webkit ones.  That's the nice thing about evergreen browsers.

So do you know of specific places where we iterate strings or access their characters through indices?  The `DontEnum` bug is one I should have thought about, though, for sure.  And that probably is affecting us.

Thanks!

**Comment by jdalton** [comment]
> doubt we'll use the the lodash implementations directly; so far Ramda has no external dependencies and I don't think we want to start adding them. I imagine we'll at the very least take inspiration from them.

That's super disappointing. I think embracing modules is a great way to punt on things that others have tackled to let you all focus on functional stuff instead of environment issues.

> I don't know if we'll worry about the old Webkit ones. That's the nice thing about evergreen browsers.

It affects things like various versions of PhantomJS too.

**Comment by CrossEye** [comment]
>> I doubt we'll use the the lodash implementations directly; so far Ramda has no external dependencies and I don't think we want to start adding them.

> That's super disappointing. I think embracing modules/packages (if not lodash's then some other) is a great way to punt on things that others have tackled to let you all focus on functional stuff instead of environment issues.

Well, maybe it _is_ a good idea.  Could you point to how lodash does this so that we might be able to use it as a model?

I've a bigger question, though.  You mentioned bugs in Ramda.  Do you have specific instances of any of these things in Ramda that would cause problems?  I just don't know of places where we iterate Strings, functions, or the arguments object, or where we use indices of Strings.  @buzzdecafe points out that our `keys` implementation does already handle the `DontEnum` issue - although it looks as though `keysIn` might need some work.  Remember that Ramda has a fairly focused API; we don't do what Underscore and lodash and FKit to try to unify handling of arrays, objects, strings, etc.

Obviously a test case would be very helpful, but even a pointer to what functions could cause issues would help.

**Comment by kevinbeaty** [comment]
>  I just don't know of places where we iterate Strings, functions, or the arguments object, or where we use indices of Strings.

I believe we added tests with the transducers integration that treats Strings as "Array like".  And `into` is documented that it works with strings so there may need to be a caveat added there.

**Comment by jdalton** [comment]
>  Could you point to how lodash does this so that we might be able to use it as a model?

The whole point about using modules/packages is so you don't have to worry about it.

>  I just don't know of places where we iterate Strings

As @kevinbeaty mentioned, I've heard with the addition of transducers strings could be supported.

> or the arguments object,

Just think of an `arguments` object as an object.

>  @buzzdecafe points out that our keys implementation does already handle the DontEnum issue

It only partially covers it. The `DontEnum` issue is pretty tricky. For example when iterating a `prototype` object several properties may rightly be non-enumerable.

> Remember that Ramda has a fairly focused API; we don't do what Underscore and lodash and FKit to try to unify handling of arrays, objects, strings, etc

I don't think that's what this issue is about. It's about iterating values correctly across enviros.

> but even a pointer to what functions could cause issues would help.

I noticed several places in Ramda that use for-in loops and each one has issues with value iteration.

**Comment by CrossEye** [comment]
@kevinbeaty: I'm going to have to look at those String tests.  It's something I've been resisting from the start.  A number of our list functions probably work on strings, but I don't want to document them and be forced to support that.  I don't think `into` is an issue as this just calls `string1 + string2` in `_stepCat`; there's no iteration, no indexing.

**Comment by CrossEye** [comment]
>> Could you point to how lodash does this so that we might be able to use it as a model?

> A win from leveraging modules/packages is that you don't have to worry about it.

So how exactly does lodash take advantage of external modules/packages?


>> @buzzdecafe points out that our keys implementation does already handle the `DontEnum` issue

> It only partially covers it. The `DontEnum` issue is pretty tricky. For example when iterating a prototype object several properties may rightly be non-enumerable.

Ok.  We'll take a look.


>> but even a pointer to what functions could cause issues would help.

> I noticed several places in Ramda that use for-in loops and each one has issues with value iteration.

Thanks.  There are ten `for-in` loops in our source now.  We'll take a look to see how they could be improved.  Worse, there one plain `for` loop.  How'd that sneak in?!  :warning:

**Comment by jdalton** [comment]
> So how exactly does lodash take advantage of external modules/packages?

At the time of implementing in lodash there wasn't a robust solution available and lodash wasn't modular as Ramda is now. That said there are plenty of examples of lodash usage in the wild (using cherry-picked modules, e.g. `require('lodash/object/keysIn')` or individual packages, e.g. require('lodash.keysin')). If you're interested I can point to some.

**Comment by kevinbeaty** [comment]
@CrossEye Fair enough here are a couple examples in [into](https://github.com/ramda/ramda/blob/master/test/into.js#L22) and [transduce](https://github.com/ramda/ramda/blob/master/test/transduce.js#L46).  I can't remember if we added string tests elsewhere.

**Comment by kevinbeaty** [comment]
Actually, nevermind.  Those look like they are iterating arrays now that I look at them again.
