### ISSUE TITLE
Mapping function over list of keys to return an object with same keys and mapped values

### ISSUE THREAD

**Issue by mcamac** [ramda/ramda#938]
I'd like to propose a binary function with signature `(String -> a) -> [String] -> {String: a}` which is equivalent to the following two functions (first using Ramda, second not):
```javscript
function g(f, keys) {
    return R.zipObj(keys, R.map(f, keys));
}

function g2(f, keys) {
    var newObj = {};
    keys.forEach(function (key) { newObj[key] = f(key); });
    return newObj;
}
```
A nice use-case of this is 
```javascript
var makeConstObj = g(R.identity);
makeConstObj(['BLUE', 'GREEN']) //=> { BLUE: 'BLUE', GREEN: 'GREEN' }
```
Another example is the equivalence
```javascript
R.pickAll = R.compose(g, R.flip(R.prop))
```
In particular, this function seems to be the first library function which transforms flat lists directly into objects. 

If this sounds reasonable, I'd be happy to submit a PR, but I understand if this function is too niche.

Sidenote: the best point-free version I could come up with Ramda (seems a bit long - I would love to see simpler versions) is: 

```javascript
var g3 = R.compose(R.apply(R.zipObj),
                   R.useWith(R.ap, 
                             R.compose(R.ap([R.always(R.identity), R.map]),
                                       R.of),
                             R.of))
```

**Comment by CrossEye** [comment]
I'd like to see other examples of its usefulness before I decided if I thought it was too niche or not.  And one other thing I'd really want to have is a name.  For some reason, `g` just doesn't cut it.  But this is actually a serious point.  In my experience, if I can't find a meaningful name for a function, then I probably don't have a useful abstraction.

As to points-free, we have the under-appreciated `nthArg`, which you can use like this:

```javascript
R.converge(R.zipObj, R.nthArg(1), R.map)
```

**Comment by CrossEye** [comment]
Also, it wouldn't be the very first function to convert a list to an object.

    fromPairs:: [{k: v}] -> {k: v}

Although we certainly don't have many.

**Comment by CrossEye** [comment]
Closing without prejudice for now.  If you want to present further rationale for the function, I'm more than willing to re-open discussion.

**Comment by Kinrany** [comment]
I've run into wanting this a few times.

It would be especially nice for TypeScript. We can write

```
const fn = (keys, lambda) => Object.fromEntries(keys.map(key => [key, lambda(key)]));
```

but the resulting type won't guarantee that the resulting object has all the keys.

**Comment by Kinrany** [comment]
Another example: I want to convert a list of statically known file names into a `Record<FileName, string>`.

A list cannot possibly guarantee that all possible members are present, so this cannot be achieved with just `fromPairs`.

**Comment by CrossEye** [comment]
@kinrany: I missed your earlier comment somehow. If you're interested in creating a PR for this, feel free.  I don't know if it will be accepted, but I can promise a fair hearing.
