### ISSUE TITLE
function returned by R.ifElse has incorrect length

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#939]
Clearly `R.ifElse(R.gt, R.subtract, R.add)` evaluates to a binary function:

```javascript
> R.ifElse(R.gt, R.subtract, R.add)(7, 2)
5
> R.ifElse(R.gt, R.subtract, R.add)(2, 7)
9
```

But it does not report its length correctly:

```javascript
> R.ifElse(R.gt, R.subtract, R.add).length
0
```

Also, partial application does not work as expected:

```javascript
> R.ifElse(R.gt, R.subtract, R.add)(2)(7)
-5
```

**Comment by buzzdecafe** [comment]
good question. What length should it have? The length of the predicate, the consequent, or the alternative? Or should the length be the `min` of those three lengths?

**Comment by buzzdecafe** [comment]
```
_curry3(function ifElse(condition, onTrue, onFalse) {
    var len = Math.max(condition.length, onTrue.length, onFalse.length);
    return curryN(len, function _ifElse() {
        return condition.apply(this, arguments) ? onTrue.apply(this, arguments) : onFalse.apply(this, arguments);
    });
});
```

?

**Comment by CrossEye** [comment]
Yup, ugliness.

Wrap in `arity(max length of predicate and consequents)` ?

Does that do it?

**Comment by CrossEye** [comment]
Works, but as always when we deal with arity, we've suddenly caused issues for functions that don't properly report arity.  Not a big deal if users pass along all arguments, but won't curry properly if not.

**Comment by buzzdecafe** [comment]
i can do a pr for this tonight
