### ISSUE TITLE
rename R.nAry or R.nwise

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#945]
We should be consistent. We should either have:

  - `R.nAry` and `R.nWise`; or
  - `R.nary` and `R.nwise`.

**Comment by CrossEye** [comment]
Before commiting #917, `nwise` was renamed to `aperture`.   So I don't think we need to change `nAry` simply for consistency.  Although I think I introduced `nAry`, I now prefer the look of `nary`, but it's so minor to me, I wouldn't bother changing it unless there were strong feelings involved.

**Comment by davidchambers** [comment]
> Before committing #917, `nwise` was renamed to `aperture`.

Oops! I should have checked that.
