### ISSUE TITLE
Article on Ramda Transducers

### ISSUE THREAD

**Issue by CrossEye** [ramda/ramda#950]
@kevinbeaty, @buzzdecafe, @kedashoe 

Are any of you interested in writing up a description of transducers as they're used in Ramda?  I think the topic is a little too large for a blurb on the 0.12.0 [upgrade guide][ug] (although I'll put something there regardless.)

It could be a blog post wherever you choose, or we could put it on the (mostly moribund) [wiki][wi], as you prefer.

  [ug]: https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22
  [wi]: https://github.com/ramda/ramda/wiki

**Comment by kevinbeaty** [comment]
@CrossEye I could probably whip something up.  It may be a few days though...

**Comment by CrossEye** [comment]
Great!  There are already pretty good articles on Transducers, but more information is never a bad thing.  What would clearly be helpful, though, is how Ramda is changed by the introduction of Transducers, what new possibilities they offer to users, what benefits they offer, and any potential gotchas.

**Comment by Luckvery** [comment]
Here is a great article for those who want to get a head start: 
http://phuu.net/2014/08/31/csp-and-transducers.html

**Comment by CrossEye** [comment]
Yes, that's one of the most readable articles around.   Thanks!

**Comment by kevinbeaty** [comment]
@CrossEye [Streaming Logs with Transducers and Ramda](http://simplectic.com/blog/2015/ramda-transducers-logs/).

**Comment by CrossEye** [comment]
Excellent!  Thank you very much!

**Comment by buzzdecafe** [comment]
:+1: 

i have an idea for a little article, if i find time i'll do that as well
