### ISSUE TITLE
Higher order functions and other ways of currying.

### ISSUE THREAD

**Issue by joneshf** [ramda/ramda#970]
For example:

http://ramdajs.com/repl/#R.reduce(function(x)%20%7B%0A%20%20return%20function(y)%20%7B%0A%20%20%20%20return%20x%20%2B%20y%3B%0A%20%20%7D%3B%0A%7D%2C%200%2C%20%5B1%2C2%2C3%5D)%3B

```javascript
R.reduce(function(x) {
  return function(y) {
    return x + y;
  };
}, 0, [1,2,3]);
```

Gives back 
```javascript
function (y) {
    return x + y;
  }
```

whereas 
http://ramdajs.com/repl/#R.reduce(R.add%2C%200%2C%20%5B1%2C2%2C3%5D)%3B
```javascript
R.reduce(R.add, 0, [1,2,3]);
```

Gives back
```javascript
6
```
 as expected.

**Comment by CrossEye** [comment]
My first response is that Javascript is not Haskell.

Functions are variadic, and if you choose to supply one with a lower arity as a parameter to one that expects a higher arity, there is nothing to catch you.  Your function is called with all the available parameters and if you choose to ignore them, you can feel free to ignore them.

We've chosen in Ramda to use Haskell-like type signatures to describe our functions, but there is not an exact match.

When `reduce` is called like this:

```javascript
R.reduce(function(x) {
  return function(y) {
    return x + y;
  };
}, 0, [1,2,3]);
```

although it's now made somewhat more complicated by the transducers implementation, the basics are this:

```javascript
function reduce(fn, acc, list) {
    var idx = -1, len = list.length;
    while (++idx < len) {
        acc = fn(acc, list[idx]);
    }
    return acc;
};
```

and with your call `fn` would be assigned

```javascript
function(x) {
  return function(y) {
    return x + y;
  };
}
```,

`acc` would get `0`, and `list` would get `[1, 2, 3]`.

So on the first iteration, we would assign

```javascript
acc = fn(1); //~=> function(y) {return 1 + y;}
``` 

And on the second

```javascript
acc = fn(2); //~=> function(y) {return 2 + y;}
``` 

And finally, we'd assign and return

```javascript
acc = fn(3); //~=> function(y) {return 3 + y;}
``` 

This is because `fn` was not an arity-2 function.  The fact that it's a manually curried version of `add` doesn't really help.  There's no way in JS to know that.

**Comment by joneshf** [comment]
Makes sense. Is this mentioned somewhere? I might've missed it if so.

Any thoughts on providing a function like `uncurryN` or some such, where it performs the inverse of `curryN`? Is that even possible?

**Comment by CrossEye** [comment]
More specifically, we couldn't replace the key line in the algorithm with this:

```javascript
        acc = fn (acc)(list [idx]);
```

because the user could just as well have supplied an unfortunately function to the call:

```javascript
R.reduce (function (a, b) {return a + b;}, 0, [1, 2, 3]);
```

So I don't see any way around this.

**Comment by CrossEye** [comment]
Actually, `uncurryN` would make a great deal of sense.   I'm not sure right off if there's an elegant implementation, but we could certainly do one in the style of `arity`.

**Comment by buzzdecafe** [comment]
thoughts:
http://ramdajs.com/repl/?v=0.13.0#var%20uncurryN%20%3D%20R.curryN(2%2C%20function%20uncurryN(n%2C%20fn)%20%7B%0A%20%20return%20R.arity(n%2C%20function()%20%7B%0A%20%20%20%20var%20idx%20%3D%200%3B%0A%20%20%20%20var%20value%20%3D%20fn%3B%0A%20%20%20%20while%20(idx%20%3C%20n)%20%7B%0A%20%20%20%20%20%20value%20%3D%20value(arguments%5Bidx%5D)%3B%0A%20%20%20%20%20%20idx%20%2B%3D%201%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20value%3B%0A%20%20%7D)%3B%0A%7D)%3B%0A%0Afunction%20a(x)%20%7B%0A%20%20return%20function(y)%20%7B%0A%20%20%20%20return%20x%20%2B%20y%3B%0A%20%20%7D%3B%0A%7D%0A%0AuncurryN(2%2C%20a)(10%2C%2020)%3B%20%2F%2F%3D%3E%2030


var uncurryN = R.curryN(2, function uncurryN(n, fn) {
  return R.arity(n, function() {
    var idx = 0;
    var value = fn;
    while (idx < n) {
      value = value(arguments[idx]);
      idx += 1;
    }
    return value;
  });
});

**Comment by buzzdecafe** [comment]
i'll do a pr for this tonight

**Comment by joneshf** [comment]
Cool!

**Comment by CrossEye** [comment]
As discussed, an alternative would be something like http://tinyurl.com/nb29uqh

```javascript
var uncurryN = R.curryN(2, function uncurryN(n, fn) {
  return R.arity(n, function() {
    var idx = 0;
    var value = fn;
    while (idx < n && R.is(Function, value)) {
      value = value.apply(this, R.slice(idx, arguments.length, arguments));
      idx += 1;
    }
    return value;
  });
});
```

This had the advantage of working on all sorts of functions, whether or not they were curried, and if so, whether they were curried with a `curry` function or manually.   But it also had the disadvantage of involving that nasty type-checking.

**Comment by buzzdecafe** [comment]
problem with both of these impls:

```javascript
function b(x) {
  return function(y) {
    return function(z) {
      return x + y + z;
    };
  };
}

uncurryN(3, b)(1, 2) //=> NaN  oooooops
```

**Comment by joneshf** [comment]
If it complicates things too much, it doesn't have to be added.

**Comment by buzzdecafe** [comment]
i feel like it's pretty close. I'm not done banging on it yet :smile:

**Comment by buzzdecafe** [comment]
it's *almost* `R.unapply(R.reduce(function(acc, x) { return acc(x); }, a));` but that returns a function that has arity 0.

**Comment by CrossEye** [comment]
@buzzdecafe: I don't know that this is a real problem, though.  The whole point is that this function takes a curried function of arity `n` and returns a fixed-arity function..  Obviously the original rationale would be that it would be suitable for using in, say, `reduce`, but it could be useful elsewhere.  The new function certainly does _not_ need to be curried..

And in either version, `uncurryN(3, b)(1, 2, 3); //=> 6` as expected.

**Comment by davidchambers** [comment]
Should the function returned be "auto"-curried?

**Comment by buzzdecafe** [comment]
that is the question. on the one hand, it's kind of weird for a function named `uncurry` to return a curried function. On the other hand, it could be useful? maybe?
