### ISSUE TITLE
isNaN('blue') is false

### ISSUE THREAD

**Issue by Cottin** [ramda/ramda#977]
isNaN seems broken: http://bit.ly/1xirZyx
`R.isNaN('blue')` returns false

The fun thing is that if you "install" all functions in ramda to `window` to avoid having to type `R.` all the time, `R.isNaN` will replace window.isNaN and all libraries that uses isNaN might behave a bit irrationally :)

**Comment by TheLudd** [comment]
I believe that this is correct behavior according to the documentation: http://ramdajs.com/docs/#isNaN

**Comment by Cottin** [comment]
Oh, sorry, you're right, seems `Number.isNaN('blabla')` is supposed to return false in ES6 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN). I don't seem why though..

So, my problem lies in that I'm "installing" isNaN from ramda to window which replaces the global `isNaN` which other libraries might depend upon not beeing "ES6-ish".

**Comment by CrossEye** [comment]
That could be a real issue.  I think we might want to rename that one, although it's hard to come up with a good value.  I know Ramda no longer supplies `installTo`, but I know I still like to use it, and I imagine others want the same sort of facility.  Overwriting native functions might be a bad idea.

**Comment by davidchambers** [comment]
> Overwriting native functions might be a bad idea.

Absolutely. This is one of the reasons not to attach arbitrary functions to the global object!

**Comment by Cottin** [comment]
> This is one of the reasons not to attach arbitrary functions to the global object!

It's sooo nice to do that though :)

In dev environment I "install" all of ramda to window and I then hook up SublimeText with remote debugging to chrome. This gives me a REPL where I can eval any code in my editor (js or coffee) by e.g. `cmd+return` like you'd do with clojure in LightTable or similar.

At the same time, I have a little plugin for Sublime that on file-save automatically destructures ramda to "import" the functions I'm using in the file. (Note that the repl cannot be dependent on using this since you haven't saved the file yet)

```
{map, inc, filter, even} = R = require 'ramda'   #auto-destruct-on-file-save
map inc, [1,2,3]
filter even, [1,2,3]
```

So, like this, I get a nice REPL with ramda installed to window in dev env and in prod env nothing weird is attached to window.

PS. one example is that react.js uses isNaN to determine if an inline style attribue-value is numeric and in that case appends `'px'` at the end. `color: 'white'` will get rendered as `color: 'whitepx'` if you install ramdas `isNaN` function to window. And it's not too easy to realize what's going on :) https://facebook.github.io/react/tips/inline-styles.html

**Comment by CrossEye** [comment]
I think it's important enough to support this workflow that we should rename the function.   But I don't have a good candidate name.   Any suggestions?

**Comment by TheLudd** [comment]
I'm with @davidchambers here. I think `isNaN` is the most suitable name for this function in ramda. I am surprised to learn that `window.isNaN('blue') === true`. I am in support of keeping this as is.

**Comment by buzzdecafe** [comment]
`isNaNtheValueNotNaNasIfItWereAType`

**Comment by kedashoe** [comment]
Can you do something like

    var R = require('..');
    var installTo = function installTo(dst, src, aliases) {
        var k;
        for (k in src) {
            dst[k in aliases ? aliases[k] : k] = src[k];
        }
    };

    installTo(global, R, {'isNaN':'notNumber'});
    console.log(isNaN('blue'), notNumber('red')); // -> true false

I'm not sure how Sublime plugins work and how easy it would be (if it's possible?) to work an alias into destructuring

**Comment by CrossEye** [comment]
My concern with this is that the user then has to update this when Ramda decides to add `alert` or `setImmediate` or some other name used for a host or native function. 

I would prefer that Ramda simply not conflict.

**Comment by Cottin** [comment]
@kedashoe nice aliases implementation! But yes, once you know about the issue, it's easy to work around it, the problem is that it's really quite hard to realise that's the problem.

I feel a library like ramda which is quite reasonable to "installTo" window (or "global" in node), at least in a dev env / repl, should at least have some warning in the docs about that if you do so, you'll override vital functions that many other libraries/frameworks depends upon.

I mean, if a library like react.js with 19k github stars relies on the _current_ behaviour of `isNaN`, I'm guessing a lot other libraries does too. https://github.com/facebook/react/blob/master/src/browser/ui/dom/dangerousStyleValue.js

**Comment by CrossEye** [comment]
I'll try to create a PR tonight, suggesting that we rename `isNaN` to `eqNaN`, which makes more sense to me, as it doesn't look as though its trying to test against type.

**Comment by buzzdecafe** [comment]
:+1: for `eqNaN` -- even though that means it *doesn't* equal `NaN` :stuck_out_tongue:

**Comment by CrossEye** [comment]
See #988
