### ISSUE TITLE
re-evaluate method signature documentation for people that don't know a Haskell

### ISSUE THREAD

**Issue by sunwukung** [ramda/ramda#984]
the method signatures in the Ramda docs are hard to read (unless you are familiar with Haskell style notation) - I would find the library far more approachable if the method signature was written with Javascript in mind.

**Comment by buzzdecafe** [comment]
would you care to elaborate on that? what would you prefer?

**Comment by CrossEye** [comment]
Note that an expanded version of the signature is available just by clicking on the concise types in the documentation, and it immediately follows them in the source code.

But the concise type signature, once you do get used to it, is often more helpful.

**Comment by nateabele** [comment]
-1

Ramda's documentation helped me _learn_ Haskell's notation.

**Comment by raine** [comment]
Ramda's documentation got me to learn Haskell.

**Comment by davidchase** [comment]
-1 same here, Ramda got me into Haskell

**Comment by buzzdecafe** [comment]
so we've got a few votes contra -- do you want to defend your position @sunwukung ? if not, i think we can close this issue

**Comment by TheLudd** [comment]
I can add that I don't think the fold out menu is very prominent on the site. I would not mind clarifying it or have it always visible. Wasn't this the case with the old site? On the current site it takes up quite a large amount of space. If it were to be always visible it that space could also be made smaller.

**Comment by CrossEye** [comment]
It used to be always visible.  Everything was smaller on the old version, but even then, I hated taking up space with what to me was redundant information.  That's why I like the type signatures; since I got used to reading them, they usually capture the structure of a function at a glance.  I wouldn't object to replacing the (fairly subtle) arrow with a "more info.../less info..." link or some such if people would find it more obvious.

**Comment by sunwukung** [comment]
Hey, I'm all for learning Haskell - *when I have time*, but my primary goal work related (I have a newborn, not much time for academic pursuits...)

I'm more than happy to learn this notation - but *where*? If it weren't for the fact that I'd ever seen Haskell then I wouldn't even know the provenance of this notation. It might be helpful to include some link or explanation - so anyone who hasn't been exposed to Haskell (or whatever this notation is based on) can help themselves to the requisite information at least. 

re: fold out menu 
I'm aware that the fold out menu exists, but taking "into" as a case in point, but I can't understand how these two bits of information relate to each other:

    a -> ( b -> b) -> [c] -> a
   --------
    * acc
    The initial accumulator value.

    function xf
    The transducer function. Receives a transformer and returns a transformer.

    Array list
    The list to iterate over.

    Returns *
    The final, accumulated value.

My apologies to those of you who enjoy the notation and how it started their Haskell journey, my needs are more pedestrian...

**Comment by CrossEye** [comment]
Sorry, I seem to have missed a few messages I should have responded to last week.  This was one of them.  We still need some work on the documentation, and explaining these signatures for those unaware of them should be on the list. 

As to `into` I actually think the signature there is incorrect.   I'll have to go look at the other transduced functions to see if they share the flaw.   I don't know if this will make it any clearer,  but to my mind, that signature should be

    a -> (transformer -> transformer) -> [b] -> a

But others might disagree.

**Comment by raine** [comment]
https://github.com/caiorss/Functional-Programming#useful-notations-for-functions

**Comment by buzzdecafe** [comment]
i would happily take a pr that highlights function behaviors. feel free to reopen if you want to discuss further
