### ISSUE TITLE
filterObj?

### ISSUE THREAD

**Issue by donnut** [ramda/ramda#993]
I have the following object:
```javascript
let storage = {
  11: {continue: true},
  21: {continue: true},
  31: {continue: false},
  41: {continue: true}
}
```
The number if occurrences of truth values of continue are of interest. 
I was thinking to use 
```javascript
return R.length(
    R.filter(function(v) {
        return v.continue === true;
    }, R.values(storage))
);
```
But what if I want to have all key/value pairs that equal the condition? So:
```js
{
  11: {continue: true},
  21: {continue: true},
  41: {continue: true}
}
```
Would this be an option?
```javascript
filterObj(function(val, key, obj) {
    return val.continue === true;
}, storage):
```
Or is there already a (efficient) function combination that does this?

edit: updated `return val` to `return val.continue`

**Comment by buzzdecafe** [comment]
`filterObj` seems reasonable to me. I don't see a simple solution for this, and key order is immaterial.

**Comment by TheLudd** [comment]
:horse:

**Comment by CrossEye** [comment]
I might write your first example differently.  I would definitely pass this to `filter`:

    R.where({continue: true})

And I might go all out and use this:

    var fn = R.pipe(R.values, R.filter(R.where({continue: true})), R.length);

For the more general problem (I assume you want `return val.continue === true`), I don't see any simple combination that generates what you're looking for.  Obviously something could be done involving a cycle of `toPairs` -> `filter` -> `fromPairs`, but that filter step would be a fairly ugly wrapper on the filter predicate supplied.

This does not fall prey to the issues described whenever we bring up a `foldObj` implementation.  Since the result is an object, it shouldn't matter in what order the keys are added.  I wouldn't mind seeing a PR for this, but I would also like to see some argument for its general usefulness.  Do you have a reasonably easy-to-describe real-world scenario?

**Comment by CrossEye** [comment]
I start typing a response, go away for a few minutes, come back to finish it up and find two others in ahead of me!  And as always, much more concise than me.  Especially the horse!

**Comment by buzzdecafe** [comment]
yes, i think :horse: is a "Godfather" reference, so we better include this function ....

**Comment by TheLudd** [comment]
Just trying to adapt to the current jargon =)

**Comment by donnut** [comment]
I'll make a PR. That's the easy part. The difficult part is to squash is into one commit :(

**Comment by TheLudd** [comment]
@donnut I am happy to teach. Mastering git rebase is a joy :)

**Comment by TheLudd** [comment]
If you are on the gitter chat you can write to me privately

**Comment by CrossEye** [comment]
"Joy", he calls it!

**Comment by donnut** [comment]
Thanks, @TheLudd, when i'm just before the point of complete despair, i'll gitter your (new verb?)

**Comment by TheLudd** [comment]
Squashing, amending and rebasing are the little bursts of happiness throughout my workday. After composing functions of course...

**Comment by TheLudd** [comment]
@donnut Sounds like a plan

**Comment by pscanf** [comment]
Isn't `pickBy` basically equivalent to the proposed `filterObj`? (It should only lack having the object passed as third argument to the predicate)

**Comment by donnut** [comment]
@pscanf I think you are right. It is a sort of in between of `filterObj` (value) and `filterObjIndexed` (value, key, object). I overlooked that function completely.

Aside from that, what I noticed is that `pickBy` does not create an new object, the reference to the target object remains, see http://bit.ly/1O2tSE5.
That seems to be the case for `zipObj` too.

**Comment by donnut** [comment]
There a comment of @pscanf in this thread suggesting that `pickBy` does the same thing as `filterObj`. But the comment was removed. I think he is right. `pickBy` is a sort of in between of `filterObj` (value) and `filterObjIndexed` (value, key, object). I overlooked that function completely.

**Comment by pscanf** [comment]
@donnut I think an hypothetical `filterObj` function should maintain the current behaviour of `pickBy`, that is, not cloning filtered values. That is consistent with what `R.filter` does for arrays (see http://bit.ly/1FxdFCG).

**Comment by pscanf** [comment]
(In any case, I vote in favour of `filterObj`+`filterObjIndexed`, even if only as aliases of `pickBy`, as they certainly have a more intuitive name :smiley: )

**Comment by buzzdecafe** [comment]
note that the name `pickBy` would also enable easy integration/dispatch to highland streams. see #1037

**Comment by buzzdecafe** [comment]
#1004
