### ISSUE TITLE
Dash docset

### ISSUE THREAD

**Issue by alexbepple** [ramda/ramda#995]
Not sure what is the best way to address this. You might be interested to know that I created a Ramda docset for Dash, the awesome documentation browser.

<https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Ramda>

**Comment by CrossEye** [comment]
I'm not a Dash user, so I can't go look at it.  But I'm excited that you've done it!

**Comment by alexbepple** [comment]
To give you an impression:
![screen shot 2015-04-02 at 01 03 51](https://cloud.githubusercontent.com/assets/159355/6954632/3ae8de56-d8d4-11e4-872b-92d9f52bccf2.png)
![screen shot 2015-04-02 at 01 04 03](https://cloud.githubusercontent.com/assets/159355/6954633/3cfa2ba0-d8d4-11e4-805d-86f9eed60989.png)

The documentation is based on <http://ramdajs.com>. I removed some links and images in order to make it less obtrusive for the purpose of browsing docs and fit for offline usage.

**Comment by alexbepple** [comment]
And in case it’s a platform issue, Dash-like tools are available for Windows and Linux: <https://blog.kapeli.com/dash-for-ios-android-windows-or-linux>

**Comment by buzzdecafe** [comment]
slick

**Comment by rkoch** [comment]
thank you! thank you! thank you!

**Comment by davidchambers** [comment]
@alexbepple, would you like to open a pull request to add a screenshot and a link to the README?

**Comment by alexbepple** [comment]
@davidchambers This would fit nicely into the section "Documentation". – I will.

**Comment by buzzdecafe** [comment]
i added a reference to this project on the main wiki page. Thanks!
