### ISSUE TITLE
publish additional builds

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda#996]
is there any support for publishing e.g. a "core" build at version-publish time, and maybe that just includes: [curry, curryN, compose, pipe, reduce, map, filter]?

**Comment by CrossEye** [comment]
:+1:

**Comment by davidchambers** [comment]
Surely everyone will have a different idea as to what is "core". I'd prefer to rely on custom builds.

**Comment by CrossEye** [comment]
Somehow I lost this thread last week.  My take is that we might want to define a build task or two for certain additional versions.  We wouldn't publish these to NPM or anything, but they could be made easily available for those who wanted them.
