### ISSUE TITLE
Version of defaultTo that takes a function

### ISSUE THREAD

**Issue by ashaffer** [ramda/ramda#997]
I know this can be achieved in other ways, but for me at least, it's an extremely common pattern where I want to do something like this:

```javascript
evolve({id: ifElse(identity, identity, generateId)})
```

This would be much nicer if I could just do

```javascript
evolve({id: defaultToFn(generateId)})
```

Anyone else have an interest in a function like this, or thoughts on what it should be called?

**Comment by ashaffer** [comment]
I discovered a slightly more concise way to express this using existing functions:

``javascript
evolve({id: either(identity, generateId)})
```

I suppose this essentially eliminates my problem.  Though it still might be nice to have a more explicit syntax for this, which could be implemented simply as:

```javascript
defaultWith = either(identity);
```

**Comment by CrossEye** [comment]
This sounds mostly like something for Ramda to keep in its back pocket in case there are a number of additional requests for it.  It looks as though you've discovered a simple-enough solution that you can do this easily with no Ramda changes.  But if there's a lot of desire for such a function, I could certainly imagine adding it.
